// «Guess the Aircraft» — GuessSync · E54 · did-you-know facts, ≤70 chars, verified true.
export const AIRCRAFT_FACTS = {
  // EASY
  boeing747: "The 'Jumbo Jet'; first flew in 1969 with its iconic hump",
  a380: "World's largest passenger airliner; a full double-decker",
  concorde: "Anglo-French supersonic jet cruising at twice the speed of sound",
  boeing737: "Boeing's short-haul twinjet; over 12,000 delivered",
  cessna172: "The most-produced aircraft ever; a classic trainer",
  spitfire: "British WWII fighter famed in the Battle of Britain",
  f16: "Single-engine US multirole fighter, first flown in 1974",
  apache: "US Army attack helicopter armed with a chain gun",
  boeing777: "Long-range twinjet; a top choice for intercontinental routes",
  f22: "US stealth air-superiority fighter, first flown in 1997",
  sr71: "Lockheed spy plane; the fastest air-breathing manned jet",
  c130: "Four-engine turboprop military transport, in service since 1956",
  chinook: "Twin-rotor US Army heavy-lift transport helicopter",
  fokkerdr1: "WWI triplane flown by the Red Baron, Manfred von Richthofen",
  f18: "US Navy carrier-based twin-engine fighter jet",
  b2spirit: "Northrop Grumman flying-wing stealth bomber",
  a320: "Airbus single-aisle jet; rival to the Boeing 737",
  boeing787: "Fuel-efficient twinjet built largely of composite materials",
  f35: "Stealth multirole fighter made in three variants",
  f14: "US Navy swing-wing fighter made famous by Top Gun",
  b52: "US strategic bomber flying since the 1950s",
  p51: "US WWII fighter that escorted bombers deep into Germany",
  blackhawk: "Sikorsky utility helicopter used by the US Army",
  wrightflyer: "First powered aircraft to fly, by the Wright brothers in 1903",
  bf109: "Germany's main WWII fighter; one of the most-built ever",
  // MEDIUM
  a350: "Airbus wide-body twinjet built mainly of carbon composites",
  boeing767: "Wide-body twinjet introduced in the early 1980s",
  boeing757: "Narrow-body twinjet known for its powerful engines",
  boeing727: "Three-engine jet with a distinctive rear T-tail",
  a330: "Airbus twin-engine wide-body for medium-long routes",
  a340: "Airbus four-engine long-haul wide-body jet",
  md80: "Stretched twinjet with rear-mounted engines and a T-tail",
  e190: "Brazilian Embraer regional jet seating around 100",
  crj: "Bombardier regional jet common on short airline routes",
  cessna152: "Two-seat light aircraft widely used to train pilots",
  pipercherokee: "Popular low-wing single-engine light aircraft",
  a10: "US attack jet built around a huge 30mm nose cannon",
  f15: "US air-superiority fighter with no air-to-air combat losses",
  f4phantom: "Cold War twin-engine jet flown by many air forces",
  mig29: "Soviet twin-engine fighter developed in the 1970s",
  su27: "Soviet long-range twin-engine air-superiority fighter",
  typhoon: "European canard-delta multirole fighter jet",
  rafale: "French twin-engine canard-delta multirole fighter",
  gripen: "Swedish single-engine lightweight multirole fighter",
  b1lancer: "US supersonic swing-wing strategic bomber",
  v22osprey: "Tiltrotor that takes off like a helicopter, flies like a plane",
  harrier: "Jump jet able to take off and land vertically",
  mi24: "Soviet gunship and troop transport, nicknamed the 'Hind'",
  huey: "Iconic US utility helicopter of the Vietnam War",
  lancaster: "British four-engine WWII heavy bomber",
  // HARD
  boeing707: "Early US jetliner that helped launch the jet age",
  dc3: "1930s propliner that revolutionized air travel",
  dc10: "Three-engine wide-body with an engine in the tail fin",
  l1011: "Lockheed tri-jet wide-body of the 1970s",
  md11: "Three-engine wide-body developed from the DC-10",
  tu154: "Soviet three-engine airliner, a workhorse of the East",
  il76: "Soviet four-engine heavy military transport jet",
  an124: "Soviet strategic airlifter, among the largest cargo planes",
  an225: "One-off Antonov six-engine giant, the heaviest aircraft built",
  a220: "Small Airbus single-aisle jet, originally the Bombardier CSeries",
  erj145: "Embraer regional jet seating around 50 passengers",
  atr72: "French-Italian twin-turboprop regional airliner",
  dash8: "Canadian twin-turboprop regional airliner",
  sr22: "Cirrus single-engine light plane with a whole-plane parachute",
  bonanza: "Beechcraft light plane once built with a distinctive V-tail",
  f117: "First operational stealth aircraft, a faceted attack jet",
  mig21: "Soviet delta-wing fighter, one of the most-produced jets",
  mig15: "Soviet Korean War jet fighter with swept wings",
  su25: "Soviet armored ground-attack jet, the 'Frogfoot'",
  tornado: "European swing-wing combat jet flown by the RAF",
  jaguar: "Anglo-French twin-engine ground-attack jet",
  mirage2000: "French single-engine delta-wing multirole fighter",
  f5: "Northrop lightweight supersonic fighter widely exported",
  vulcan: "British delta-wing Cold War nuclear bomber",
  u2: "Lockheed high-altitude reconnaissance spy plane",
  // IMPOSSIBLE
  b36: "Giant US bomber with six pusher props and four jets",
  convair990: "Fast US narrow-body jet with anti-shock bumps on the wing",
  vc10: "British airliner with four rear-mounted engines",
  trident: "British three-engine jet, an early pioneer of autoland",
  bac111: "British short-haul twinjet with rear-mounted engines",
  tu144: "Soviet supersonic airliner, rival to Concorde",
  caravelle: "French pioneer jet, first with rear-mounted engines",
  britannia: "British four-engine turboprop, the 'Whispering Giant'",
  saab340: "Swedish twin-turboprop regional airliner",
  fokkerf27: "Dutch twin-turboprop airliner of the 1950s",
  victor: "British V-bomber with a crescent-shaped wing",
  lightning: "British Mach-2 interceptor with stacked engines",
  meteor: "First British jet fighter, in service from 1944",
  comet: "World's first commercial jet airliner, flown in 1949",
  b57: "US-built version of the British Canberra bomber",
  f105: "US supersonic fighter-bomber heavily used over Vietnam",
  f106: "US delta-wing interceptor, the 'Ultimate Interceptor'",
  a5vigilante: "US Navy supersonic carrier bomber turned recon jet",
  f9fpanther: "US Navy straight-wing jet fighter of the Korean War",
  bv141: "WWII German recon plane with an unusual asymmetric layout",
  dox: "1929 German flying boat, the largest aircraft of its day",
  saroprincess: "British ten-engine flying boat of the 1950s",
  yb49: "Northrop flying-wing bomber prototype of the late 1940s",
  caproni60: "1921 Italian nine-wing flying-boat airliner prototype",
  spruntgoose: "Howard Hughes' huge wooden flying boat, the 'Spruce Goose'",
};
