// «Guess the Aircraft» — GuessSync · E54 · 100 aircraft (25/tier) · real photos from Wikimedia Commons
// Sorted by global recognizability: easy (Boeing 747, Spitfire, F-16) → impossible (obscure/rare types).
// Mix of commercial airliners + military jets + historic/WWII + helicopters + general aviation.
export const AIRCRAFT = [
  // EASY (25) — household-name aircraft
  { slug: "boeing747", name: "Boeing 747", level: "easy" },
  { slug: "a380", name: "Airbus A380", level: "easy" },
  { slug: "concorde", name: "Concorde", level: "easy" },
  { slug: "boeing737", name: "Boeing 737", level: "easy" },
  { slug: "cessna172", name: "Cessna 172", level: "easy" },
  { slug: "spitfire", name: "Supermarine Spitfire", level: "easy" },
  { slug: "f16", name: "F-16 Fighting Falcon", level: "easy" },
  { slug: "apache", name: "AH-64 Apache", level: "easy" },
  { slug: "boeing777", name: "Boeing 777", level: "easy" },
  { slug: "f22", name: "F-22 Raptor", level: "easy" },
  { slug: "sr71", name: "SR-71 Blackbird", level: "easy" },
  { slug: "c130", name: "C-130 Hercules", level: "easy" },
  { slug: "chinook", name: "CH-47 Chinook", level: "easy" },
  { slug: "fokkerdr1", name: "Fokker Dr.I", level: "easy" },
  { slug: "f18", name: "F/A-18 Hornet", level: "easy" },
  { slug: "b2spirit", name: "B-2 Spirit", level: "easy" },
  { slug: "a320", name: "Airbus A320", level: "easy" },
  { slug: "boeing787", name: "Boeing 787 Dreamliner", level: "easy" },
  { slug: "f35", name: "F-35 Lightning II", level: "easy" },
  { slug: "f14", name: "F-14 Tomcat", level: "easy" },
  { slug: "b52", name: "B-52 Stratofortress", level: "easy" },
  { slug: "p51", name: "P-51 Mustang", level: "easy" },
  { slug: "blackhawk", name: "UH-60 Black Hawk", level: "easy" },
  { slug: "wrightflyer", name: "Wright Flyer", level: "easy" },
  { slug: "bf109", name: "Messerschmitt Bf 109", level: "easy" },
  // MEDIUM (25) — widely seen airliners + well-known military
  { slug: "a350", name: "Airbus A350", level: "medium" },
  { slug: "boeing767", name: "Boeing 767", level: "medium" },
  { slug: "boeing757", name: "Boeing 757", level: "medium" },
  { slug: "boeing727", name: "Boeing 727", level: "medium" },
  { slug: "a330", name: "Airbus A330", level: "medium" },
  { slug: "a340", name: "Airbus A340", level: "medium" },
  { slug: "md80", name: "McDonnell Douglas MD-80", level: "medium" },
  { slug: "e190", name: "Embraer E190", level: "medium" },
  { slug: "crj", name: "Bombardier CRJ", level: "medium" },
  { slug: "cessna152", name: "Cessna 152", level: "medium" },
  { slug: "pipercherokee", name: "Piper PA-28 Cherokee", level: "medium" },
  { slug: "a10", name: "A-10 Thunderbolt II", level: "medium" },
  { slug: "f15", name: "F-15 Eagle", level: "medium" },
  { slug: "f4phantom", name: "F-4 Phantom II", level: "medium" },
  { slug: "mig29", name: "MiG-29", level: "medium" },
  { slug: "su27", name: "Sukhoi Su-27", level: "medium" },
  { slug: "typhoon", name: "Eurofighter Typhoon", level: "medium" },
  { slug: "rafale", name: "Dassault Rafale", level: "medium" },
  { slug: "gripen", name: "Saab Gripen", level: "medium" },
  { slug: "b1lancer", name: "B-1 Lancer", level: "medium" },
  { slug: "v22osprey", name: "V-22 Osprey", level: "medium" },
  { slug: "harrier", name: "AV-8B Harrier II", level: "medium" },
  { slug: "mi24", name: "Mil Mi-24 Hind", level: "medium" },
  { slug: "huey", name: "Bell UH-1 Huey", level: "medium" },
  { slug: "lancaster", name: "Avro Lancaster", level: "medium" },
  // HARD (25) — enthusiast-level types
  { slug: "boeing707", name: "Boeing 707", level: "hard" },
  { slug: "dc3", name: "Douglas DC-3", level: "hard" },
  { slug: "dc10", name: "McDonnell Douglas DC-10", level: "hard" },
  { slug: "l1011", name: "Lockheed L-1011 TriStar", level: "hard" },
  { slug: "md11", name: "McDonnell Douglas MD-11", level: "hard" },
  { slug: "tu154", name: "Tupolev Tu-154", level: "hard" },
  { slug: "il76", name: "Ilyushin Il-76", level: "hard" },
  { slug: "an124", name: "Antonov An-124", level: "hard" },
  { slug: "an225", name: "Antonov An-225 Mriya", level: "hard" },
  { slug: "a220", name: "Airbus A220", level: "hard" },
  { slug: "erj145", name: "Embraer ERJ-145", level: "hard" },
  { slug: "atr72", name: "ATR 72", level: "hard" },
  { slug: "dash8", name: "De Havilland Dash 8", level: "hard" },
  { slug: "sr22", name: "Cirrus SR22", level: "hard" },
  { slug: "bonanza", name: "Beechcraft Bonanza", level: "hard" },
  { slug: "f117", name: "F-117 Nighthawk", level: "hard" },
  { slug: "mig21", name: "MiG-21", level: "hard" },
  { slug: "mig15", name: "MiG-15", level: "hard" },
  { slug: "su25", name: "Sukhoi Su-25", level: "hard" },
  { slug: "tornado", name: "Panavia Tornado", level: "hard" },
  { slug: "jaguar", name: "SEPECAT Jaguar", level: "hard" },
  { slug: "mirage2000", name: "Dassault Mirage 2000", level: "hard" },
  { slug: "f5", name: "Northrop F-5", level: "hard" },
  { slug: "vulcan", name: "Avro Vulcan", level: "hard" },
  { slug: "u2", name: "Lockheed U-2", level: "hard" },
  // IMPOSSIBLE (25) — obscure / rare / historic types
  { slug: "b36", name: "Convair B-36 Peacemaker", level: "impossible" },
  { slug: "convair990", name: "Convair 990 Coronado", level: "impossible" },
  { slug: "vc10", name: "Vickers VC10", level: "impossible" },
  { slug: "trident", name: "Hawker Siddeley Trident", level: "impossible" },
  { slug: "bac111", name: "BAC One-Eleven", level: "impossible" },
  { slug: "tu144", name: "Tupolev Tu-144", level: "impossible" },
  { slug: "caravelle", name: "Sud Aviation Caravelle", level: "impossible" },
  { slug: "britannia", name: "Bristol Britannia", level: "impossible" },
  { slug: "saab340", name: "Saab 340", level: "impossible" },
  { slug: "fokkerf27", name: "Fokker F27 Friendship", level: "impossible" },
  { slug: "victor", name: "Handley Page Victor", level: "impossible" },
  { slug: "lightning", name: "English Electric Lightning", level: "impossible" },
  { slug: "meteor", name: "Gloster Meteor", level: "impossible" },
  { slug: "comet", name: "De Havilland Comet", level: "impossible" },
  { slug: "b57", name: "Martin B-57 Canberra", level: "impossible" },
  { slug: "f105", name: "F-105 Thunderchief", level: "impossible" },
  { slug: "f106", name: "Convair F-106 Delta Dart", level: "impossible" },
  { slug: "a5vigilante", name: "A-5 Vigilante", level: "impossible" },
  { slug: "f9fpanther", name: "Grumman F9F Panther", level: "impossible" },
  { slug: "bv141", name: "BV 141", level: "impossible" },
  { slug: "dox", name: "Dornier Do X", level: "impossible" },
  { slug: "saroprincess", name: "Saunders-Roe Princess", level: "impossible" },
  { slug: "yb49", name: "Northrop YB-49", level: "impossible" },
  { slug: "caproni60", name: "Caproni Ca.60", level: "impossible" },
  { slug: "spruntgoose", name: "Hughes H-4 Hercules", level: "impossible" },
];
