// E39 Airline Logo facts — one verified TRUE fact per airline (≤70 chars): founding year / country / hub.
export const AIRLINELOGO_FACTS = {
  // ===== EASY =====
  "emirates": "Dubai's flag carrier; founded 1985, hub at Dubai Intl (DXB).",
  "qatarairways": "Qatar's flag carrier; founded 1993, hub in Doha.",
  "lufthansa": "Germany's flag carrier; founded 1953, hub in Frankfurt.",
  "delta": "US major airline founded 1925; hub in Atlanta.",
  "americanairlines": "World's largest airline; founded 1930, hub in Dallas.",
  "unitedairlines": "US major airline founded 1926; hub in Chicago.",
  "britishairways": "UK flag carrier; founded 1974, hub at London Heathrow.",
  "airfrance": "France's flag carrier; founded 1933, hub at Paris CDG.",
  "turkishairlines": "Turkey's flag carrier; founded 1933, hub in Istanbul.",
  "singaporeairlines": "Singapore's flag carrier; founded 1947, hub at Changi.",
  "klm": "World's oldest airline still flying; founded 1919, Amsterdam.",
  "ryanair": "Irish low-cost giant; founded 1984, hub in Dublin.",
  "easyjet": "UK low-cost airline; founded 1995, based at London Luton.",
  "etihad": "UAE flag carrier; founded 2003, hub in Abu Dhabi.",
  "qantas": "Australia's flag carrier; founded 1920, hub in Sydney.",
  "cathaypacific": "Hong Kong's flag carrier; founded 1946.",
  "aircanada": "Canada's flag carrier; founded 1937, hub in Toronto.",
  "southwest": "World's biggest low-cost carrier; founded 1967 in Texas.",
  "japanairlines": "Japan's flag carrier; founded 1951, hub in Tokyo.",
  "ana": "Japan's largest airline; founded 1952, hub in Tokyo.",
  "saudia": "Saudi Arabia's flag carrier; founded 1945, hub in Jeddah.",
  "aeroflot": "Russia's flag carrier; founded 1923, hub in Moscow.",
  "iberia": "Spain's flag carrier; founded 1927, hub in Madrid.",
  "virginatlantic": "British airline founded 1984 by Richard Branson.",
  "airindia": "India's flag carrier; founded 1932, hub in Delhi.",
  // ===== MEDIUM =====
  "swiss": "Switzerland's flag carrier; founded 2002, hub in Zurich.",
  "austrian": "Austria's flag carrier; founded 1957, hub in Vienna.",
  "sas": "Scandinavia's airline; founded 1946, hub in Copenhagen.",
  "finnair": "Finland's flag carrier; founded 1923, hub in Helsinki.",
  "tap": "Portugal's flag carrier; founded 1945, hub in Lisbon.",
  "aerlingus": "Ireland's flag carrier; founded 1936, hub in Dublin.",
  "ita": "Italy's flag carrier; founded 2020, hub in Rome Fiumicino.",
  "brussels": "Belgium's flag carrier; founded 2006, hub in Brussels.",
  "lot": "Poland's flag carrier; founded 1929, hub in Warsaw.",
  "vueling": "Spanish low-cost airline; founded 2004, hub in Barcelona.",
  "wizzair": "Hungarian low-cost airline; founded 2003, hub in Budapest.",
  "norwegian": "Norwegian low-cost airline; founded 1993, hub in Oslo.",
  "spirit": "US ultra-low-cost airline; founded 1980, based in Florida.",
  "frontier": "US ultra-low-cost airline; founded 1994, hub in Denver.",
  "jetblue": "US low-cost airline; founded 1998, hub in New York JFK.",
  "alaska": "US airline founded 1932; hub in Seattle.",
  "hawaiian": "Hawaii's airline; founded 1929, hub in Honolulu.",
  "westjet": "Canadian low-cost airline; founded 1996, hub in Calgary.",
  "airasia": "Malaysian low-cost giant; founded 1993, Kuala Lumpur.",
  "jetstar": "Australian low-cost airline; founded 2003 by Qantas.",
  "koreanair": "South Korea's flag carrier; founded 1969, hub in Seoul.",
  "chinasouthern": "China's largest airline; founded 1988, in Guangzhou.",
  "chinaeastern": "Chinese major airline; founded 1988, hub in Shanghai.",
  "airchina": "China's flag carrier; founded 1988, hub in Beijing.",
  "thaiairways": "Thailand's flag carrier; founded 1960, hub in Bangkok.",
  // ===== HARD =====
  "evaair": "Taiwanese airline; founded 1989, hub in Taipei.",
  "chinaairlines": "Taiwan's flag carrier; founded 1959, hub in Taipei.",
  "malaysiaairlines": "Malaysia's flag carrier; founded 1947, Kuala Lumpur.",
  "garuda": "Indonesia's flag carrier; founded 1949, hub in Jakarta.",
  "philippineairlines": "Asia's oldest airline; founded 1941, hub in Manila.",
  "vietnamairlines": "Vietnam's flag carrier; founded 1956, hub in Hanoi.",
  "gulfair": "Bahrain's flag carrier; founded 1950, hub in Manama.",
  "omanair": "Oman's flag carrier; founded 1993, hub in Muscat.",
  "kuwaitairways": "Kuwait's flag carrier; founded 1953, in Kuwait City.",
  "royaljordanian": "Jordan's flag carrier; founded 1963, hub in Amman.",
  "egyptair": "Egypt's flag carrier; founded 1932, hub in Cairo.",
  "royalairmaroc": "Morocco's flag carrier; founded 1957, in Casablanca.",
  "kenyaairways": "Kenya's flag carrier; founded 1977, hub in Nairobi.",
  "ethiopian": "Ethiopia's flag carrier; founded 1945, in Addis Ababa.",
  "saa": "South Africa's flag carrier; founded 1934, Johannesburg.",
  "latam": "Latin America's biggest airline; formed 2012 in Chile.",
  "avianca": "Colombia's flag carrier; founded 1919, hub in Bogota.",
  "aeromexico": "Mexico's flag carrier; founded 1934, in Mexico City.",
  "copa": "Panama's flag carrier; founded 1947, in Panama City.",
  "azul": "Brazilian airline; founded 2008 by David Neeleman.",
  "gol": "Brazilian low-cost airline; founded 2000, in Sao Paulo.",
  "aerolineas": "Argentina's flag carrier; founded 1950, Buenos Aires.",
  "icelandair": "Iceland's flag carrier; founded 1937, in Reykjavik.",
  "pegasus": "Turkish low-cost airline; founded 1990, hub in Istanbul.",
  "srilankan": "Sri Lanka's flag carrier; founded 1979, in Colombo.",
  // ===== IMPOSSIBLE =====
  "bangkokairways": "Thai regional airline; founded 1968, hub in Bangkok.",
  "bambooairways": "Vietnamese airline; founded 2017, hub in Hanoi.",
  "cebupacific": "Philippine low-cost airline; founded 1988, in Manila.",
  "indigo": "India's largest airline; founded 2006, hub in Delhi.",
  "spicejet": "Indian low-cost airline; founded 2005, hub in Delhi.",
  "vistara": "Indian airline; founded 2013, hub in Delhi.",
  "airastana": "Kazakhstan's flag carrier; founded 2001, in Almaty.",
  "uzbekistan": "Uzbekistan's flag carrier; founded 1992, in Tashkent.",
  "azal": "Azerbaijan's flag carrier; founded 1992, hub in Baku.",
  "georgian": "Georgian airline; founded 1993, hub in Tbilisi.",
  "airserbia": "Serbia's flag carrier; founded 1927, hub in Belgrade.",
  "croatia": "Croatia's flag carrier; founded 1989, hub in Zagreb.",
  "tarom": "Romania's flag carrier; founded 1954, in Bucharest.",
  "bulgariaair": "Bulgaria's flag carrier; founded 2002, hub in Sofia.",
  "airbaltic": "Latvia's flag carrier; founded 1995, hub in Riga.",
  "luxair": "Luxembourg's flag carrier; founded 1962.",
  "airmalta": "Malta's flag carrier; founded 1973, hub in Luqa.",
  "mea": "Lebanon's flag carrier; founded 1945, hub in Beirut.",
  "tunisair": "Tunisia's flag carrier; founded 1948, hub in Tunis.",
  "airalgerie": "Algeria's flag carrier; founded 1947, hub in Algiers.",
  "rwandair": "Rwanda's flag carrier; founded 2002, hub in Kigali.",
  "airmauritius": "Mauritius' flag carrier; founded 1967, in Port Louis.",
  "fijiairways": "Fiji's flag carrier; founded 1951, hub in Nadi.",
  "airtahitinui": "French Polynesia's airline; founded 1996, in Papeete.",
  "bahamasair": "Bahamas' flag carrier; founded 1973, hub in Nassau.",
};
