// E39 «Guess the Airline Logo» — GuessSync · 100 airlines · absolute difficulty (easy world-famous → impossible regional). image: airlines/<slug>.png
export const AIRLINELOGOS = [
  // ===== EASY (25) =====
  { slug: "emirates", name: "Emirates", level: "easy" },
  { slug: "qatarairways", name: "Qatar Airways", level: "easy" },
  { slug: "lufthansa", name: "Lufthansa", level: "easy" },
  { slug: "delta", name: "Delta Air Lines", level: "easy" },
  { slug: "americanairlines", name: "American Airlines", level: "easy" },
  { slug: "unitedairlines", name: "United Airlines", level: "easy" },
  { slug: "britishairways", name: "British Airways", level: "easy" },
  { slug: "airfrance", name: "Air France", level: "easy" },
  { slug: "turkishairlines", name: "Turkish Airlines", level: "easy" },
  { slug: "singaporeairlines", name: "Singapore Airlines", level: "easy" },
  { slug: "klm", name: "KLM", level: "easy" },
  { slug: "ryanair", name: "Ryanair", level: "easy" },
  { slug: "easyjet", name: "easyJet", level: "easy" },
  { slug: "etihad", name: "Etihad Airways", level: "easy" },
  { slug: "qantas", name: "Qantas", level: "easy" },
  { slug: "cathaypacific", name: "Cathay Pacific", level: "easy" },
  { slug: "aircanada", name: "Air Canada", level: "easy" },
  { slug: "southwest", name: "Southwest Airlines", level: "easy" },
  { slug: "japanairlines", name: "Japan Airlines", level: "easy" },
  { slug: "ana", name: "All Nippon Airways", level: "easy" },
  { slug: "saudia", name: "Saudia", level: "easy" },
  { slug: "aeroflot", name: "Aeroflot", level: "easy" },
  { slug: "iberia", name: "Iberia", level: "easy" },
  { slug: "virginatlantic", name: "Virgin Atlantic", level: "easy" },
  { slug: "airindia", name: "Air India", level: "easy" },
  // ===== MEDIUM (25) =====
  { slug: "swiss", name: "Swiss Intl Air Lines", level: "medium" },
  { slug: "austrian", name: "Austrian Airlines", level: "medium" },
  { slug: "sas", name: "Scandinavian Airlines", level: "medium" },
  { slug: "finnair", name: "Finnair", level: "medium" },
  { slug: "tap", name: "TAP Air Portugal", level: "medium" },
  { slug: "aerlingus", name: "Aer Lingus", level: "medium" },
  { slug: "ita", name: "ITA Airways", level: "medium" },
  { slug: "brussels", name: "Brussels Airlines", level: "medium" },
  { slug: "lot", name: "LOT Polish Airlines", level: "medium" },
  { slug: "vueling", name: "Vueling", level: "medium" },
  { slug: "wizzair", name: "Wizz Air", level: "medium" },
  { slug: "norwegian", name: "Norwegian Air Shuttle", level: "medium" },
  { slug: "spirit", name: "Spirit Airlines", level: "medium" },
  { slug: "frontier", name: "Frontier Airlines", level: "medium" },
  { slug: "jetblue", name: "JetBlue", level: "medium" },
  { slug: "alaska", name: "Alaska Airlines", level: "medium" },
  { slug: "hawaiian", name: "Hawaiian Airlines", level: "medium" },
  { slug: "westjet", name: "WestJet", level: "medium" },
  { slug: "airasia", name: "AirAsia", level: "medium" },
  { slug: "jetstar", name: "Jetstar", level: "medium" },
  { slug: "koreanair", name: "Korean Air", level: "medium" },
  { slug: "chinasouthern", name: "China Southern Airlines", level: "medium" },
  { slug: "chinaeastern", name: "China Eastern Airlines", level: "medium" },
  { slug: "airchina", name: "Air China", level: "medium" },
  { slug: "thaiairways", name: "Thai Airways", level: "medium" },
  // ===== HARD (25) =====
  { slug: "evaair", name: "EVA Air", level: "hard" },
  { slug: "chinaairlines", name: "China Airlines", level: "hard" },
  { slug: "malaysiaairlines", name: "Malaysia Airlines", level: "hard" },
  { slug: "garuda", name: "Garuda Indonesia", level: "hard" },
  { slug: "philippineairlines", name: "Philippine Airlines", level: "hard" },
  { slug: "vietnamairlines", name: "Vietnam Airlines", level: "hard" },
  { slug: "gulfair", name: "Gulf Air", level: "hard" },
  { slug: "omanair", name: "Oman Air", level: "hard" },
  { slug: "kuwaitairways", name: "Kuwait Airways", level: "hard" },
  { slug: "royaljordanian", name: "Royal Jordanian", level: "hard" },
  { slug: "egyptair", name: "EgyptAir", level: "hard" },
  { slug: "royalairmaroc", name: "Royal Air Maroc", level: "hard" },
  { slug: "kenyaairways", name: "Kenya Airways", level: "hard" },
  { slug: "ethiopian", name: "Ethiopian Airlines", level: "hard" },
  { slug: "saa", name: "South African Airways", level: "hard" },
  { slug: "latam", name: "LATAM Airlines", level: "hard" },
  { slug: "avianca", name: "Avianca", level: "hard" },
  { slug: "aeromexico", name: "Aeroméxico", level: "hard" },
  { slug: "copa", name: "Copa Airlines", level: "hard" },
  { slug: "azul", name: "Azul Brazilian Airlines", level: "hard" },
  { slug: "gol", name: "GOL Linhas Aéreas", level: "hard" },
  { slug: "aerolineas", name: "Aerolíneas Argentinas", level: "hard" },
  { slug: "icelandair", name: "Icelandair", level: "hard" },
  { slug: "pegasus", name: "Pegasus Airlines", level: "hard" },
  { slug: "srilankan", name: "SriLankan Airlines", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { slug: "bangkokairways", name: "Bangkok Airways", level: "impossible" },
  { slug: "bambooairways", name: "Bamboo Airways", level: "impossible" },
  { slug: "cebupacific", name: "Cebu Pacific", level: "impossible" },
  { slug: "indigo", name: "IndiGo", level: "impossible" },
  { slug: "spicejet", name: "SpiceJet", level: "impossible" },
  { slug: "vistara", name: "Vistara", level: "impossible" },
  { slug: "airastana", name: "Air Astana", level: "impossible" },
  { slug: "uzbekistan", name: "Uzbekistan Airways", level: "impossible" },
  { slug: "azal", name: "Azerbaijan Airlines", level: "impossible" },
  { slug: "georgian", name: "Georgian Airways", level: "impossible" },
  { slug: "airserbia", name: "Air Serbia", level: "impossible" },
  { slug: "croatia", name: "Croatia Airlines", level: "impossible" },
  { slug: "tarom", name: "TAROM", level: "impossible" },
  { slug: "bulgariaair", name: "Bulgaria Air", level: "impossible" },
  { slug: "airbaltic", name: "airBaltic", level: "impossible" },
  { slug: "luxair", name: "Luxair", level: "impossible" },
  { slug: "airmalta", name: "Air Malta", level: "impossible" },
  { slug: "mea", name: "Middle East Airlines", level: "impossible" },
  { slug: "tunisair", name: "Tunisair", level: "impossible" },
  { slug: "airalgerie", name: "Air Algérie", level: "impossible" },
  { slug: "rwandair", name: "RwandAir", level: "impossible" },
  { slug: "airmauritius", name: "Air Mauritius", level: "impossible" },
  { slug: "fijiairways", name: "Fiji Airways", level: "impossible" },
  { slug: "airtahitinui", name: "Air Tahiti Nui", level: "impossible" },
  { slug: "bahamasair", name: "Bahamasair", level: "impossible" },
];
