// «Guess the Amphibian» — GuessSync · E56 · did-you-know facts, ≤70 chars, verified true.
export const AMPHIBIAN_FACTS = {
  // EASY
  "greentreefrog": "Bright green frog with a white stripe along each side",
  "bullfrog": "North America's largest frog; males bellow like a cow",
  "poisondartfrog": "Skin toxins once tipped the blow-darts of rainforest tribes",
  "commontoad": "Warty toad that walks more than it hops and eats slugs",
  "axolotl": "A salamander that stays aquatic and never metamorphoses",
  "firesalamander": "Black with yellow spots; secretes toxins from its skin",
  "redeyedtreefrog": "Flashes red eyes to startle predators and buy a getaway",
  "smoothnewt": "Common Eurasian newt; males grow a wavy breeding crest",
  "canetoad": "Invasive toad with glands that poison would-be predators",
  "commonfrog": "Familiar European frog that lays clumps of frogspawn",
  "americantoad": "Warty toad whose long trill rings out on spring nights",
  "leopardfrog": "Green frog covered in dark rounded leopard-like spots",
  "europeantreefrog": "Tiny green climber with sticky discs on its toes",
  "tigersalamander": "Large burrowing salamander with yellow tiger markings",
  "goliathfrog": "The world's largest frog; can reach a foot in length",
  "africanclawedfrog": "Clawed aquatic frog once used for pregnancy testing",
  "pacmanfrog": "Round wide-mouthed frog that ambushes and gulps prey",
  "whitestreefrog": "Plump blue-green tree frog nicknamed the dumpy frog",
  "springpeeper": "Tiny frog whose loud peeps announce spring in the east",
  "woodfrog": "Survives winter by freezing solid, then thawing alive",
  "coloradorivertoad": "Big toad whose venom holds a powerful psychedelic",
  "greatcrestednewt": "Big warty newt; males sport a jagged breeding crest",
  "goldenpoisonfrog": "Among Earth's deadliest animals; skin holds batrachotoxin",
  "bluepoisonfrog": "Vivid blue dart frog whose skin carries potent toxins",
  "marshfrog": "Europe's largest native frog, with a laughing-like call",
  // MEDIUM
  "ediblefrog": "A natural hybrid frog once served as French frog legs",
  "poolfrog": "Small green water frog that basks at the pond's edge",
  "natterjacktoad": "Runs instead of hopping; wears a yellow back stripe",
  "spadefoottoad": "Uses spade-like hind feet to dig backward into soil",
  "firebelliedtoad": "Arches to flash a bright warning belly when threatened",
  "paintedreedfrog": "Small African reed frog with vivid variable patterns",
  "easternnewt": "Its bright orange land stage is called a red eft",
  "alpinenewt": "Mountain newt with a striking bright orange belly",
  "palmatenewt": "Tiny newt; breeding males get webbed black hind feet",
  "marbledsalamander": "Stout salamander banded in white or silvery crossbars",
  "spottedsalamander": "Black salamander with two rows of bright yellow spots",
  "redsalamander": "Bright orange-red skin dusted with small black spots",
  "mudpuppy": "Aquatic salamander that keeps red feathery gills for life",
  "graytreefrog": "Camouflaged frog that shifts between gray and green",
  "cubantreefrog": "Largest tree frog in North America and a spreading pest",
  "paradoxfrog": "Its huge tadpole shrinks into a much smaller adult frog",
  "roughskinnednewt": "Its skin holds tetrodotoxin, a deadly nerve poison",
  "californianewt": "Toxic brown newt that raises its tail to warn attackers",
  "firebellynewt": "Dark newt that flashes a red-orange belly as a warning",
  "redbackedsalamander": "Lungless woodland salamander that breathes through skin",
  "slimysalamander": "Oozes a sticky glue-like slime that is hard to wash off",
  "midwifetoad": "The male carries the eggs wrapped around his hind legs",
  "yellowbelliedtoad": "Arches its back to flash a mottled yellow warning belly",
  "barkingtreefrog": "A large US tree frog whose call sounds like a barking dog",
  "pickerelfrog": "Square-spotted frog with skin secretions that irritate",
  // HARD
  "waxymonkeyfrog": "Wipes a waxy coat over its skin to keep from drying out",
  "amazonmilkfrog": "Named for the milky toxin it oozes when it is disturbed",
  "goldenmantella": "Tiny fiery-orange Madagascar frog with toxic skin",
  "wallacesflyingfrog": "Glides between trees on huge webbed parachute feet",
  "malabargliding": "Bright green Indian frog that glides on webbed feet",
  "vietnamesemossyfrog": "Bumpy skin mimics moss for near-perfect camouflage",
  "hourglasstreefrog": "Small frog marked with an hourglass shape on its back",
  "crocodilenewt": "Knobby Asian newt with bright orange warty rib ridges",
  "iberianribbednewt": "Pushes sharp ribs through its skin to jab at attackers",
  "marblednewt": "Green-and-black marbled newt from western Europe",
  "emperornewt": "Black newt with bright orange warts along its back",
  "cavesalamander": "Orange cave salamander with a long prehensile tail",
  "bluespottedsalamander": "Black salamander flecked with bright blue-white spots",
  "jeffersonsalamander": "Slender gray salamander that breeds in early spring pools",
  "longtailedsalamander": "Yellow salamander whose tail is over half its length",
  "ensatina": "Drops its tail to escape, then slowly regrows a new one",
  "arborealsalamander": "Climbing salamander that can bite with sharp jaw teeth",
  "commoncoqui": "Puerto Rican frog named for its loud ko-kee night call",
  "gladiatortreefrog": "Males fight with sharp spines hidden on their thumbs",
  "cricketfrog": "Tiny frog whose call sounds like two stones tapping",
  "chorusfrog": "Its rising call sounds like a thumb run down a comb",
  "gopherfrog": "Shelters inside gopher tortoise burrows in the pinelands",
  "crawfishfrog": "Lives inside crayfish burrows and rarely leaves them",
  "squirreltreefrog": "Small Florida tree frog with a rain-like chattering call",
  "pinebarrenstreefrog": "Green tree frog with plum stripes edged in white",
  // IMPOSSIBLE
  "olm": "Blind cave salamander that can live for over a century",
  "purplefrog": "Bloated burrower that surfaces only days a year to breed",
  "surinamtoad": "The female carries her eggs embedded in her own back",
  "hellbender": "Giant aquatic salamander that breathes through skin folds",
  "glassfrog": "Its see-through belly reveals the heart and organs inside",
  "tomatofrog": "Puffs up and oozes a sticky white glue when threatened",
  "caecilian": "A limbless burrowing amphibian that looks like a worm",
  "greatersiren": "Eel-like salamander with only tiny front legs and gills",
  "amphiuma": "Eel-like salamander with four tiny near-useless legs",
  "lessersiren": "Slender aquatic salamander with feathery outside gills",
  "texasblindsalamander": "Blind cave salamander with translucent pale pink skin",
  "chinesegiantsalamander": "The world's largest amphibian, nearly six feet long",
  "japanesegiantsalamander": "Giant river salamander that can live for many decades",
  "titicacafrog": "Baggy skin folds help it breathe in a cold high lake",
  "hairyfrog": "Breaks its own toe bones to push out claws for defense",
  "goldentoad": "A dazzling orange toad last seen in 1989, now extinct",
  "darwinsfrog": "The father broods his tadpoles inside his own vocal sac",
  "malayanhornedfrog": "Leaf-mimic frog with sharp horns over each eye",
  "budgettsfrog": "Flat wide frog that screams and lunges when annoyed",
  "turtlefrog": "Squat frog that digs headfirst and feeds on termites",
  "desertrainfrog": "Round desert frog with a squeaky toy-like distress call",
  "redbellynewt": "Coastal California newt with a tomato-red belly",
  "splendidleaffrog": "Vivid green leaf frog with orange flanks and webbing",
  "helmetedwatertoad": "Massive Chilean frog with a mouth big enough for mice",
  "mexicanburrowingtoad": "Bloated burrowing toad with a loud whooping mating call",
};
