// E112 «Guess the ZOOMED Amphibian» — GuessSync "What the Zoom" hard-mode.
// Reuses the EXACT E56 amphibian image set (amphibians/<slug>.jpg) and E56's AMPHIBIAN_FACTS +
// am-<slug>.wav answer VOs (copied to amz-<slug>.wav — identical "It's the <name>!" line, zero new
// audio cost), but RE-TIERED by how hard each amphibian is to name from an EXTREME off-center
// close-up crop (skin patch, scale 3.0). Difficulty tracks SKIN COLOR/PATTERN distinctiveness, NOT
// general amphibian fame: EASY = bold color/markings survive any tiny crop (Fire Salamander's
// black-and-yellow, Golden Poison Frog, Blue-Spotted Salamander...). IMPOSSIBLE = plain brown/olive/
// generic warty skin — a crop of it looks like any other frog or toad (Common Toad, Chorus Frog, etc.)
// image: amphibians/<slug>.jpg | answer VO: sfx/amz-<slug>.wav (copied from E56's am-<slug>.wav)
export const AMPHIBIANZOOM = [
  // ===== EASY (25) =====
  { slug: "bluespottedsalamander", name: "Blue-Spotted Salamander", level: "easy" },
  { slug: "marbledsalamander", name: "Marbled Salamander", level: "easy" },
  { slug: "spottedsalamander", name: "Spotted Salamander", level: "easy" },
  { slug: "goldenmantella", name: "Golden Mantella", level: "easy" },
  { slug: "marblednewt", name: "Marbled Newt", level: "easy" },
  { slug: "goldentoad", name: "Golden Toad", level: "easy" },
  { slug: "goldenpoisonfrog", name: "Golden Poison Frog", level: "easy" },
  { slug: "leopardfrog", name: "Leopard Frog", level: "easy" },
  { slug: "tigersalamander", name: "Tiger Salamander", level: "easy" },
  { slug: "redsalamander", name: "Red Salamander", level: "easy" },
  { slug: "redbackedsalamander", name: "Red-Backed Salamander", level: "easy" },
  { slug: "purplefrog", name: "Purple Frog", level: "easy" },
  { slug: "hairyfrog", name: "Hairy Frog", level: "easy" },
  { slug: "redbellynewt", name: "Red-Bellied Newt", level: "easy" },
  { slug: "greentreefrog", name: "Green Tree Frog", level: "easy" },
  { slug: "redeyedtreefrog", name: "Red-Eyed Tree Frog", level: "easy" },
  { slug: "whitestreefrog", name: "White's Tree Frog", level: "easy" },
  { slug: "bluepoisonfrog", name: "Blue Poison Dart Frog", level: "easy" },
  { slug: "bullfrog", name: "American Bullfrog", level: "easy" },
  { slug: "axolotl", name: "Axolotl", level: "easy" },
  { slug: "firesalamander", name: "Fire Salamander", level: "easy" },
  { slug: "smoothnewt", name: "Smooth Newt", level: "easy" },
  { slug: "canetoad", name: "Cane Toad", level: "easy" },
  { slug: "americantoad", name: "American Toad", level: "easy" },
  { slug: "poisondartfrog", name: "Poison Dart Frog", level: "easy" },
  // ===== MEDIUM (25) =====
  { slug: "goliathfrog", name: "Goliath Frog", level: "medium" },
  { slug: "springpeeper", name: "Spring Peeper", level: "medium" },
  { slug: "woodfrog", name: "Wood Frog", level: "medium" },
  { slug: "marshfrog", name: "Marsh Frog", level: "medium" },
  { slug: "ediblefrog", name: "Edible Frog", level: "medium" },
  { slug: "poolfrog", name: "Pool Frog", level: "medium" },
  { slug: "natterjacktoad", name: "Natterjack Toad", level: "medium" },
  { slug: "firebelliedtoad", name: "Fire-Bellied Toad", level: "medium" },
  { slug: "easternnewt", name: "Eastern Newt", level: "medium" },
  { slug: "alpinenewt", name: "Alpine Newt", level: "medium" },
  { slug: "palmatenewt", name: "Palmate Newt", level: "medium" },
  { slug: "mudpuppy", name: "Mudpuppy", level: "medium" },
  { slug: "paradoxfrog", name: "Paradox Frog", level: "medium" },
  { slug: "roughskinnednewt", name: "Rough-Skinned Newt", level: "medium" },
  { slug: "californianewt", name: "California Newt", level: "medium" },
  { slug: "slimysalamander", name: "Slimy Salamander", level: "medium" },
  { slug: "midwifetoad", name: "Midwife Toad", level: "medium" },
  { slug: "pickerelfrog", name: "Pickerel Frog", level: "medium" },
  { slug: "crocodilenewt", name: "Crocodile Newt", level: "medium" },
  { slug: "emperornewt", name: "Emperor Newt", level: "medium" },
  { slug: "cavesalamander", name: "Cave Salamander", level: "medium" },
  { slug: "jeffersonsalamander", name: "Jefferson Salamander", level: "medium" },
  { slug: "longtailedsalamander", name: "Long-Tailed Salamander", level: "medium" },
  { slug: "ensatina", name: "Ensatina", level: "medium" },
  { slug: "arborealsalamander", name: "Arboreal Salamander", level: "medium" },
  // ===== HARD (25) =====
  { slug: "yellowbelliedtoad", name: "Yellow-Bellied Toad", level: "hard" },
  { slug: "cricketfrog", name: "Cricket Frog", level: "hard" },
  { slug: "chorusfrog", name: "Chorus Frog", level: "hard" },
  { slug: "gopherfrog", name: "Gopher Frog", level: "hard" },
  { slug: "crawfishfrog", name: "Crawfish Frog", level: "hard" },
  { slug: "olm", name: "Olm", level: "hard" },
  { slug: "surinamtoad", name: "Surinam Toad", level: "hard" },
  { slug: "hellbender", name: "Hellbender", level: "hard" },
  { slug: "glassfrog", name: "Glass Frog", level: "hard" },
  { slug: "tomatofrog", name: "Tomato Frog", level: "hard" },
  { slug: "caecilian", name: "Caecilian", level: "hard" },
  { slug: "greatersiren", name: "Greater Siren", level: "hard" },
  { slug: "amphiuma", name: "Amphiuma", level: "hard" },
  { slug: "lessersiren", name: "Lesser Siren", level: "hard" },
  { slug: "darwinsfrog", name: "Darwin's Frog", level: "hard" },
  { slug: "budgettsfrog", name: "Budgett's Frog", level: "hard" },
  { slug: "turtlefrog", name: "Turtle Frog", level: "hard" },
  { slug: "europeantreefrog", name: "European Tree Frog", level: "hard" },
  { slug: "africanclawedfrog", name: "African Clawed Frog", level: "hard" },
  { slug: "pacmanfrog", name: "Argentine Horned Frog", level: "hard" },
  { slug: "coloradorivertoad", name: "Colorado River Toad", level: "hard" },
  { slug: "greatcrestednewt", name: "Great Crested Newt", level: "hard" },
  { slug: "paintedreedfrog", name: "Painted Reed Frog", level: "hard" },
  { slug: "graytreefrog", name: "Gray Tree Frog", level: "hard" },
  { slug: "cubantreefrog", name: "Cuban Tree Frog", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { slug: "firebellynewt", name: "Japanese Fire-Bellied Newt", level: "impossible" },
  { slug: "barkingtreefrog", name: "Barking Tree Frog", level: "impossible" },
  { slug: "waxymonkeyfrog", name: "Waxy Monkey Tree Frog", level: "impossible" },
  { slug: "amazonmilkfrog", name: "Amazon Milk Frog", level: "impossible" },
  { slug: "wallacesflyingfrog", name: "Wallace's Flying Frog", level: "impossible" },
  { slug: "malabargliding", name: "Malabar Gliding Frog", level: "impossible" },
  { slug: "vietnamesemossyfrog", name: "Vietnamese Mossy Frog", level: "impossible" },
  { slug: "hourglasstreefrog", name: "Hourglass Tree Frog", level: "impossible" },
  { slug: "iberianribbednewt", name: "Iberian Ribbed Newt", level: "impossible" },
  { slug: "gladiatortreefrog", name: "Gladiator Tree Frog", level: "impossible" },
  { slug: "squirreltreefrog", name: "Squirrel Tree Frog", level: "impossible" },
  { slug: "pinebarrenstreefrog", name: "Pine Barrens Tree Frog", level: "impossible" },
  { slug: "texasblindsalamander", name: "Texas Blind Salamander", level: "impossible" },
  { slug: "chinesegiantsalamander", name: "Chinese Giant Salamander", level: "impossible" },
  { slug: "japanesegiantsalamander", name: "Japanese Giant Salamander", level: "impossible" },
  { slug: "titicacafrog", name: "Lake Titicaca Frog", level: "impossible" },
  { slug: "malayanhornedfrog", name: "Malayan Horned Frog", level: "impossible" },
  { slug: "desertrainfrog", name: "Desert Rain Frog", level: "impossible" },
  { slug: "splendidleaffrog", name: "Splendid Leaf Frog", level: "impossible" },
  { slug: "mexicanburrowingtoad", name: "Mexican Burrowing Toad", level: "impossible" },
  { slug: "commontoad", name: "Common Toad", level: "impossible" },
  { slug: "commonfrog", name: "Common Frog", level: "impossible" },
  { slug: "spadefoottoad", name: "Common Spadefoot", level: "impossible" },
  { slug: "commoncoqui", name: "Common Coquí", level: "impossible" },
  { slug: "helmetedwatertoad", name: "Helmeted Water Toad", level: "impossible" },
];
