// E03 — one verified ≤70-char fact per animal, shown on the reveal.
export const ANIMAL_FACTS = {
  "lion": "The only big cat that lives in social prides.",
  "tiger": "Its stripes are on its skin, not just its fur.",
  "elephant": "Too heavy to jump — its feet always stay grounded.",
  "giraffe": "The tallest land animal, yet has just 7 neck bones.",
  "zebra": "Every zebra's stripe pattern is unique, like a fingerprint.",
  "panda": "A bear that eats almost nothing but bamboo.",
  "penguin": "A bird that swims expertly but cannot fly.",
  "kangaroo": "It can't walk backwards, only hop forward.",
  "dog": "The first animal humans ever domesticated.",
  "cat": "It can't taste sweetness at all.",
  "horse": "It can sleep both standing up and lying down.",
  "cow": "It has nearly 360-degree panoramic vision.",
  "pig": "Smarter than a dog, and can learn its own name.",
  "sheep": "It can recognize dozens of faces for years.",
  "monkey": "Unlike apes, most monkeys have tails.",
  "bear": "It can smell food from miles away.",
  "polarbear": "Under its white fur, its skin is black.",
  "dolphin": "It sleeps with one half of its brain awake.",
  "shark": "Sharks existed before trees and dinosaurs.",
  "owl": "Its eyes can't move, so it turns its head 270 degrees.",
  "frog": "Many frogs drink and breathe through their skin.",
  "snake": "It smells the air using its flicking forked tongue.",
  "crocodile": "It has the strongest bite force ever measured.",
  "camel": "Its hump stores fat for energy, not water.",
  "rabbit": "Its teeth never stop growing its whole life.",
  "raccoon": "Its clever paws feel prey underwater to identify it.",
  "octopus": "It has three hearts and blue blood.",
  "flamingo": "It's born grey and turns pink from its food.",
  "koala": "Its fingerprints are nearly identical to a human's.",
  "otter": "Sea otters hold hands while sleeping to not drift apart.",
  "hedgehog": "It rolls into a spiky ball when threatened.",
  "meerkat": "Guards take turns as lookouts while the group feeds.",
  "chameleon": "Its two eyes can look in two directions at once.",
  "peacock": "Only the males grow the huge colorful tail.",
  "toucan": "Its huge bill releases body heat like a radiator.",
  "sloth": "The slowest mammal; algae even grows in its fur.",
  "llama": "It hums to communicate and spits when annoyed.",
  "seahorse": "The male, not the female, gets pregnant and gives birth.",
  "jellyfish": "It has no brain, heart, or bones.",
  "starfish": "It has no brain and eats by pushing its stomach out.",
  "walrus": "It uses its long tusks to haul itself onto ice.",
  "platypus": "A mammal that lays eggs and senses prey electrically.",
  "porcupine": "Its quills can't be shot, but detach on contact.",
  "ostrich": "The world's largest bird lays the biggest egg.",
  "seaturtle": "It can hold its breath underwater for hours.",
  "pelican": "It scoops fish in the huge pouch under its bill.",
  "prayingmantis": "The only insect that can turn its head 180 degrees.",
  "armadillo": "The only mammal with a hard, bony shell.",
  "bison": "The largest land animal in North America.",
  "hyena": "Its clans are ruled by dominant females.",
  "redpanda": "Not related to giant pandas; it's its own family.",
  "lemur": "Lemurs live wild only on the island of Madagascar.",
  "tapir": "It can walk along riverbeds and use its nose as a snorkel.",
  "okapi": "The giraffe's only living relative, with zebra-striped legs.",
  "capybara": "The world's largest rodent, and a strong swimmer.",
  "pangolin": "The only mammal covered in scales.",
  "wombat": "The only animal that produces cube-shaped poop.",
  "lynx": "Its huge furry paws work like built-in snowshoes.",
  "mongoose": "It can dodge cobra strikes and resist their venom.",
  "anteater": "It has no teeth and a tongue up to 2 feet long.",
  "aardvark": "It can dig a burrow faster than several people with shovels.",
  "wildebeest": "Over a million migrate across Africa each year.",
  "mandrill": "The largest and most colorful of all monkeys.",
  "cassowary": "Called the world's most dangerous bird.",
  "kingfisher": "It dives like a dart to snatch fish underwater.",
  "caracal": "It can leap high to snatch birds out of the air.",
  "axolotl": "It can regrow lost limbs, and even parts of its heart.",
  "manatee": "Its closest land relative is the elephant.",
  "puffin": "It can carry many fish in its beak at once.",
  "narwhal": "Its 'horn' is actually a spiral tusk, a giant tooth.",
  "ibex": "It can climb near-vertical cliffs and dam walls.",
  "hornbill": "The female seals herself inside a tree nest to breed.",
  "marmot": "It hibernates underground for over half the year.",
  "coati": "It walks with its long ringed tail held straight up.",
  "gecko": "Many geckos can climb glass and shed their tails.",
  "quokka": "Nicknamed the world's happiest-looking animal.",
  "ayeaye": "It taps trees, then digs out grubs with a long finger.",
  "saiga": "Its bulbous nose warms cold air and filters out dust.",
  "numbat": "The only marsupial that is fully active by day.",
  "kakapo": "The world's only flightless parrot.",
  "dhole": "This wild dog whistles to coordinate its pack.",
  "gharial": "A crocodile with a super-thin, fish-catching snout.",
  "binturong": "This 'bearcat' smells like buttered popcorn.",
  "fossa": "Madagascar's top predator, and a lemur's main hunter.",
  "markhor": "The largest wild goat, with corkscrew-spiral horns.",
  "gerenuk": "An antelope that stands on hind legs to reach leaves.",
  "colugo": "The best glider of all mammals, soaring tree to tree.",
  "jerboa": "A desert rodent that hops on kangaroo-like hind legs.",
  "olinguito": "The first new American carnivore found in 35 years.",
  "zorilla": "This polecat may be the world's smelliest animal.",
  "gaur": "The largest and tallest of all wild cattle.",
  "takin": "Its golden coat may have inspired the Golden Fleece myth.",
  "sifaka": "This lemur dances sideways to cross open ground.",
  "babirusa": "Its curved tusks grow up through the top of its snout.",
  "potoo": "By day it freezes and looks just like a broken branch.",
  "shoebill": "It stands like a statue, then clatters like a machine gun.",
  "solenodon": "One of the very few mammals with a venomous bite.",
  "maleo": "Its chick can fend for itself hours after hatching.",
  "kagu": "A nearly flightless bird with a dog-like barking call.",
  "vaquita": "The world's smallest and rarest marine mammal.",
};
