// E197 anime-emoji facts — one true <=70-char fact per anime, shown on reveal.
export const ANIME_EMOJI_3_FACTS = {
  // EASY
  "solo-leveling": "A Korean webtoon adaptation about a weak hunter who levels up.",
  "oshi-no-ko": "An idol reincarnates as her own child in this drama anime.",
  "frieren": "An elf mage reflects on mortality after her party disbands.",
  "dragon-ball-super": "Sequel series to Dragon Ball Z, starting after Majin Buu.",
  "boruto": "A sequel series following Naruto's son as a young ninja.",
  "howls-moving-castle": "A Ghibli film where a cursed girl lives in a walking castle.",
  "kikis-delivery-service": "A young witch starts a flying delivery service in a new town.",
  "ponyo": "A Ghibli film about a fish girl who wants to become human.",
  "princess-mononoke": "A Ghibli epic of a war between forest gods and humans.",
  "pretty-cure": "A long-running magical girl franchise from Toei Animation.",
  "bocchi-the-rock": "A socially anxious girl joins a band to overcome her fears.",
  "macross": "A classic mecha franchise mixing space war with pop idols.",
  "mazinger-z": "A pioneering giant-robot anime piloted from inside its head.",
  "ashita-no-joe": "A classic boxing anime about a delinquent turned fighter.",
  "weathering-with-you": "A Shinkai film about a girl who can control the weather.",
  "suzume": "A Shinkai film where a girl closes doors causing disasters.",
  "boy-and-the-heron": "A Miyazaki film about a boy guided by a mysterious heron.",
  "k-on": "A slice-of-life anime about high schoolers in a light music club.",
  "prince-of-tennis": "A shonen anime about a tennis prodigy at a top school.",
  "inazuma-eleven": "A sports anime blending soccer with fantastical special moves.",
  "cardfight-vanguard": "A shonen anime centered on a collectible card battle game.",
  "tokyo-mew-mew": "A magical girl anime where teens transform into animal hybrids.",
  "zatch-bell": "A boy and his mamodo partner fight to become the mamodo king.",
  "yowamushi-pedal": "A shy otaku discovers he's a natural at competitive cycling.",
  "mushoku-tensei": "A jobless man is reincarnated as a mage in a fantasy world.",
  // MEDIUM
  "madoka-magica": "A magical girl anime that subverts the genre with dark twists.",
  "fate-zero": "A prequel to Fate/stay night depicting the Fourth Holy Grail War.",
  "classroom-of-the-elite": "Students at an elite school compete in a hidden merit system.",
  "horimiya": "A popular girl and a quiet boy bond over their secret home lives.",
  "rent-a-girlfriend": "A student hires a rental girlfriend after a painful breakup.",
  "cyberpunk-edgerunners": "A street kid becomes a mercenary in dystopian Night City.",
  "dandadan": "A girl and a boy team up against ghosts and aliens.",
  "delicious-in-dungeon": "Adventurers cook and eat monsters to survive a deadly dungeon.",
  "mashle": "A magicless boy uses raw muscle to pass through a magic academy.",
  "ranking-of-kings": "A deaf, powerless prince strives to become a great king.",
  "tower-of-god": "A boy climbs a mysterious tower to reunite with his friend.",
  "god-of-high-school": "Fighters compete in a tournament with godlike prizes at stake.",
  "full-metal-panic": "A teen mercenary guards a schoolgirl who hides a secret power.",
  "outlaw-star": "A space adventure following a crew chasing a legendary treasure.",
  "eureka-seven": "A boy joins rebels who surf on flying machines called LFOs.",
  "certain-scientific-railgun": "An esper schoolgirl with electric powers fights crime in Academy City.",
  "wotakoi": "Coworkers who are secretly otaku fall into an awkward romance.",
  "saiki-k": "A psychic teen tries to live a quiet life hiding his powers.",
  "ouran": "A scholarship student joins an all-male high school host club.",
  "nozaki-kun": "A girl discovers her crush secretly draws a hit shojo manga.",
  "march-comes-in-like-a-lion": "A teenage professional shogi player struggles with isolation.",
  "chihayafuru": "A girl becomes obsessed with the competitive card game karuta.",
  "diamond-no-ace": "A pitcher joins a powerhouse high school baseball team.",
  "cross-game": "A baseball drama following a boy after losing someone close.",
  "castle-in-the-sky": "A Ghibli adventure chasing a legendary floating island.",
  // HARD
  "arifureta": "A bullied student becomes the strongest after a dungeon fall.",
  "realist-hero": "A summoned man rebuilds a failing kingdom using modern logic.",
  "eighty-six": "Teens piloted as disposable soldiers fight an unmanned war.",
  "ajin": "A student discovers he is an immortal being hunted by the state.",
  "uzumaki": "A Junji Ito horror story where a town is cursed by spirals.",
  "ghost-hunt": "A team investigates hauntings using science and the supernatural.",
  "sket-dance": "A high school club solves quirky problems for fellow students.",
  "beelzebub": "A delinquent is chosen to raise the demon king's infant son.",
  "voltes-v": "A classic super robot anime uniting five vehicles into one.",
  "zoids": "Pilots battle in giant mechanical creatures called Zoids.",
  "battle-angel-alita": "A cyborg girl rebuilt in a scrapyard seeks her lost past.",
  "knights-of-sidonia": "Humanity survives on a starship while fighting alien Gauna.",
  "aldnoah-zero": "A war erupts between Earth and Martian colonists with mecha.",
  "days-soccer": "A shy boy finds his place as a soccer team's newest member.",
  "wolf-girl-black-prince": "A girl's lie about a boyfriend spirals into real romance.",
  "snow-white-red-hair": "A herbalist with rare red hair becomes a court pharmacist.",
  "ancient-magus-bride": "A girl sold at auction becomes apprentice to a magus.",
  "natsumes-book-of-friends": "A boy who sees spirits inherits a book that binds them.",
  "vampire-knight": "A girl guards a school where day and night classes hide vampires.",
  "rosario-vampire": "A boy accidentally enrolls at a school for monsters.",
  "trinity-blood": "Vampires and humans clash in a future ruled by the Vatican.",
  "blood-blockade-battlefront": "A secret organization polices a city fused with another dimension.",
  "pandora-hearts": "A boy is thrown into a prison dimension called the Abyss.",
  "black-rock-shooter": "A girl's alter ego fights in a surreal parallel world.",
  "karneval": "An amnesiac boy joins a secret organization called Circus.",
  // IMPOSSIBLE
  "cat-returns": "A girl who saves a cat prince is whisked into the Cat Kingdom.",
  "whisper-of-the-heart": "A bookish girl follows a mysterious cat to a strange shop.",
  "when-marnie-was-there": "A lonely girl befriends a mysterious girl at a marshland house.",
  "arrietty": "A tiny borrower girl befriends a sickly human boy.",
  "pom-poko": "Shape-shifting raccoon dogs battle to save their forest home.",
  "ocean-waves": "A Ghibli TV film about a love triangle among high schoolers.",
  "poppy-hill": "Students fight to save their school clubhouse in 1960s Japan.",
  "rahxephon": "A boy pilots a bio-mechanical being to defend Tokyo Jupiter.",
  "nadia": "Two kids and an inventor girl battle a secret society at sea.",
  "fushigi-yuugi": "A girl is pulled into a book and made a legendary priestess.",
  "x-1999": "Seven seals and seven dragons of earth clash to decide fate.",
  "angelic-layer": "A girl competes in battles using small robotic dolls she designs.",
  "chrono-crusade": "A nun and a demon partner fight evil in 1920s New York.",
  "read-or-die": "A book-loving agent with paper-manipulation powers fights crime.",
  "escaflowne": "A girl is pulled into a fantasy world with a giant mecha.",
  "slayers": "A sorceress and her swordsman friend battle monsters for profit.",
  "magic-knight-rayearth": "Three schoolgirls are summoned to save a magical realm.",
  "ninja-scroll": "A wandering ninja battles eight supernatural demon warriors.",
  "vampire-hunter-d": "A dhampir hunter is hired to kill a vampire lord.",
  "utawarerumono": "An amnesiac man leads animal-eared people in a war of fate.",
  "scrapped-princess": "A princess prophesied to destroy the world is hunted by all.",
  "kimba-the-white-lion": "A pioneering anime following a white lion cub who becomes king.",
  "space-adventure-cobra": "A space pirate with a gun-arm chases treasure across the galaxy.",
  "galaxy-express-999": "A boy rides a space train seeking an immortal mechanical body.",
  "please-save-my-earth": "Reincarnated aliens slowly recall their past lives on the moon.",
};
