// E249 «Guess the Anime by Emoji» — 5th anime-emoji episode — one TRUE fact per id, ≤70 chars
export const ANIME_EMOJI5_FACTS = {
  // EASY
  "dragon-ball-gt": "A sequel where Goku is turned into a child again by a wish.",
  "fullmetal-alchemist-brotherhood": "Follows Arakawa's manga closer than the first 2003 anime.",
  "mobile-suit-gundam-seed": "A 2002 Gundam reboot aimed at a new generation of fans.",
  "love-live": "Nine schoolgirls form an idol group to save their school.",
  "aggretsuko": "A red panda office worker screams death metal to vent stress.",
  "grand-blue": "A college diving club comedy full of drunken antics.",
  "katekyo-hitman-reborn": "A baby hitman trains a boy to lead a mafia family.",
  "world-trigger": "Humans use Trigger tech to fight invaders from another world.",
  "another": "A cursed class where one extra student secretly causes deaths.",
  "ao-ashi": "A raw striker gets scouted into a top Tokyo youth academy.",
  "eyeshield-21": "A shy runner becomes an American football legend in disguise.",
  "ao-haru-ride": "Reunited childhood friends navigate first love in high school.",
  "domestic-girlfriend": "A boy's one-night stand turns out to be his new stepsister.",
  "blue-box": "A badminton boy falls for the basketball star he admires.",
  "yashahime": "Daughters of Sesshomaru and Inuyasha lead this sequel series.",
  "the-eminence-in-shadow": "A boy role-plays a mastermind, unaware his lies are real.",
  "ascendance-of-a-bookworm": "A book-loving girl reincarnates where books barely exist.",
  "the-melancholy-of-haruhi-suzumiya": "A girl unknowingly has reality-warping powers.",
  "mobile-suit-gundam-wing": "Five teen pilots fight in Gundams called Mobile Suits.",
  "the-saga-of-tanya-the-evil": "A ruthless man is reborn as a girl in a magic-war world.",
  "say-i-love-you": "A guarded loner slowly opens up to a popular classmate.",
  "grendizer": "A giant robot launches from a hidden underground base.",
  "future-boy-conan": "A boy survives on an island after civilization's collapse.",
  "devilman": "A gentle boy merges with a demon to fight other demons.",
  "idolmaster": "Producers train idols for stardom in this game-based franchise.",

  // MEDIUM
  "cyborg-009": "Nine kidnapped humans become cyborgs and turn on their captors.",
  "gatchaman": "Five costumed heroes pilot the Firebird against a syndicate.",
  "porco-rosso": "A cursed pilot who looks like a pig flies over the Adriatic.",
  "grimgar-of-fantasy-and-ash": "Stranded teens must kill to survive in a fantasy world.",
  "princess-tutu": "A duck transforms into a ballerina to save a storybook prince.",
  "record-of-lodoss-war": "One of the earliest classic Japanese fantasy anime series.",
  "beck-mongolian-chop-squad": "A boy joins a band named after a stray dog he rescued.",
  "vivy-fluorite-eyes-song": "A singing AI travels through time to prevent an AI uprising.",
  "plastic-memories": "A worker retrieves androids before their memories expire.",
  "junji-ito-collection": "An anthology adapting the horror manga artist's stories.",
  "time-of-eve": "Androids and humans mingle freely inside one quiet cafe.",
  "remi-nobodys-boy": "An orphan boy travels with a street performer and his dog.",
  "children-who-chase-lost-voices": "A girl follows a boy into a hidden underground realm.",
  "dr-slump": "A robot girl named Arale causes chaos in a quirky village.",
  "ah-my-goddess": "A goddess grants a lonely student's wish to be his companion.",
  "aquarion": "Three vehicles merge into one warrior to fight shadow angels.",
  "mieruko-chan": "A girl can see horrifying ghosts but pretends she can't.",
  "jigoku-shoujo": "A girl ferries the wronged to hell at the cost of her own soul.",
  "pop-team-epic": "Two girls star in a rapid-fire skit-comedy parody show.",
  "cromartie-high-school": "A delinquent high school somehow enrolls a talking robot.",
  "excel-saga": "An overzealous recruit joins a group plotting world conquest.",
  "flying-witch": "A young witch moves to the countryside to learn her craft.",
  "ookiku-furikabutte": "An anxious pitcher joins a rebuilding high school baseball team.",
  "giant-killing": "A struggling soccer club hires back a controversial old coach.",
  "kimagure-orange-road": "A boy with psychic powers hides them from the girl he loves.",

  // HARD
  "cats-eye": "Three art-thief sisters run a cafe by day, steal by night.",
  "wedding-peach": "A girl transforms into a bride-themed warrior of love.",
  "ojamajo-doremi": "A clumsy girl becomes a witch apprentice by accident.",
  "vampire-princess-miyu": "A vampire girl hunts demons that have escaped into the world.",
  "getter-robo": "Three pilots combine their jets into one giant robot.",
  "space-runaway-ideon": "An alien super-weapon awakens with catastrophic power.",
  "armored-trooper-votoms": "Small, gritty mecha called Scopedogs fight in gray-morality war.",
  "dancouga": "Four separate mecha combine into one lion-shaped super robot.",
  "aim-for-the-ace": "One of the earliest tennis-themed sports anime, from 1973.",
  "candy-candy": "An orphan girl faces hardship with unshakable optimism.",
  "combattler-v": "Five vehicles combine into one super robot warrior.",
  "golion": "Its footage was reedited to create the U.S. series Voltron.",
  "belle-and-sebastian": "A boy and his giant dog roam the French Pyrenees together.",
  "heidi-girl-of-the-alps": "A girl lives with her grandfather high in the Swiss Alps.",
  "3000-leagues-in-search-of-mother": "A boy sails from Italy to Argentina seeking his lost mother.",
  "ronia-the-robbers-daughter": "A robber chief's daughter befriends a rival clan's son.",
  "sayonara-zetsubou-sensei": "A pessimistic teacher despairs over modern society's flaws.",
  "perman": "An ordinary boy becomes a masked hero using alien gadgets.",
  "obake-no-q-taro": "A clumsy ghost moves in with an ordinary human family.",
  "groizer-x": "A giant robot show fondly remembered by 1980s Arab viewers.",
  "toward-the-terra": "Humanity's exiled psychic children seek a new home world.",
  "galaxy-angel": "A comedic crew searches the galaxy for a lost treasure.",
  "his-and-her-circumstances": "A perfect student and a hidden rebel fall for each other.",
  "genshiken": "A college club of otaku bond over anime, manga, and games.",
  "basilisk": "Two rival ninja clans are forced into a deadly succession war.",

  // IMPOSSIBLE
  "samurai-7": "Farmers hire ronin to defend their rice harvest from bandits.",
  "sengoku-basara": "Stylized warlords clash during Japan's Warring States era.",
  "kekkaishi": "A boy uses barrier magic to guard sacred land from demons.",
  "zambot-3": "Directed by Yoshiyuki Tomino, known for its tragic character deaths.",
  "attacker-you": "A pioneering 1984 volleyball anime for young athletes.",
  "trider-g7": "A giant robot is piloted by ordinary schoolkids, not soldiers.",
  "story-of-perrine": "A girl and her dog travel to France to find her grandfather.",
  "anne-of-green-gables": "An imaginative orphan is adopted by siblings on Prince Edward Island.",
  "tico-of-the-seven-seas": "A boy sails the seas alongside a loyal dolphin friend.",
  "a-dog-of-flanders": "A poor boy and his dog dream of seeing a famous painting.",
  "rascal-the-raccoon": "A boy raises a wild raccoon before releasing it to nature.",
  "peter-pan-no-bouken": "A boy who never grows up leads children to Neverland.",
  "ai-no-wakakusa-monogatari": "A Japanese anime adaptation of the novel Little Women.",
  "meiken-lassie": "A loyal collie is sold away but keeps finding her way home.",
  "adventures-of-tom-sawyer": "A mischievous boy rafts and explores along the Mississippi.",
  "nils-fushigi-na-tabi": "A shrunken boy flies across Sweden on the back of a goose.",
  "trapp-family-story": "An Austrian family of singers flees before World War II.",
  "little-lord-fauntleroy": "A poor American boy learns he is heir to an English estate.",
  "princess-sarah": "A wealthy girl is forced into servitude after losing her father.",
  "sinbad-no-bouken-1975": "A 1975 Japanese anime retelling of the sailor's classic voyages.",
  "cinderella-monogatari": "A Nippon Animation retelling of the classic Cinderella tale.",
  "little-match-girl": "Based on Hans Christian Andersen's classic fairy tale.",
  "kaiketsu-zorro": "A masked swordsman defends the people from a corrupt governor.",
  "gigantor": "A boy controls a giant flying robot by remote in this 1960s anime.",
  "alakazam-the-great": "A vain monkey king learns humility on a long journey.",
};
