// E156 emoji-anime-character facts — one verified <=70-char fact per character, shown on reveal.
export const ANIMECHAR_EMOJI_FACTS = {
  // EASY
  "goku": "Saiyan hero of Dragon Ball, famous for the Kamehameha wave.",
  "naruto": "Ninja who holds the Nine-Tailed Fox, from Naruto.",
  "luffy": "Straw Hat pirate captain with rubber powers, from One Piece.",
  "pikachu": "Ash's Electric-type mascot Pokemon, from Pokemon.",
  "sailor-moon": "Usagi transforms into the guardian Sailor Moon.",
  "ash-ketchum": "Pokemon Trainer from Pallet Town, from Pokemon.",
  "vegeta": "Proud Saiyan prince and Goku's rival, from Dragon Ball Z.",
  "ichigo-kurosaki": "Teen Soul Reaper who fights Hollows, from Bleach.",
  "light-yagami": "Student who kills with the Death Note, from Death Note.",
  "saitama": "Bald hero who wins in one punch, from One-Punch Man.",
  "levi-ackerman": "Humanity's strongest soldier, from Attack on Titan.",
  "tanjiro": "Water and Sun breathing demon slayer, from Demon Slayer.",
  "nezuko": "Tanjiro's sister turned demon, from Demon Slayer.",
  "eren-yeager": "Boy who becomes a Titan, from Attack on Titan.",
  "deku": "Izuku inherits One For All, from My Hero Academia.",
  "totoro": "Forest spirit befriending two girls, from My Neighbor Totoro.",
  "doraemon": "Blue robot cat from the future, from Doraemon.",
  "astro-boy": "Rocket-powered robot boy, from Astro Boy.",
  "gon-freecss": "Rookie Hunter seeking his father, from Hunter x Hunter.",
  "edward-elric": "Alchemist with an automail arm, from Fullmetal Alchemist.",
  "sasuke": "Uchiha rival wielding Chidori lightning, from Naruto.",
  "charizard": "Fire and Flying dragon-like Pokemon, from Pokemon.",
  "shin-chan": "Cheeky 5-year-old, from Crayon Shin-chan.",
  "inuyasha": "Half-demon with the sword Tessaiga, from Inuyasha.",
  "meowth": "Talking Team Rocket cat Pokemon, from Pokemon.",

  // MEDIUM
  "kakashi": "Masked Copy Ninja and Team 7 leader, from Naruto.",
  "zoro": "Three-sword swordsman with no sense of direction, One Piece.",
  "jotaro-kujo": "Star Platinum user in the peaked cap, from JoJo.",
  "gohan": "Goku's scholarly Saiyan son, from Dragon Ball Z.",
  "killua": "Ex-assassin who wields lightning, from Hunter x Hunter.",
  "all-might": "Smiling Symbol of Peace, from My Hero Academia.",
  "bakugo": "Explosive-quirk hothead, from My Hero Academia.",
  "yugi": "Duelist host of the Pharaoh, from Yu-Gi-Oh!.",
  "sakura": "Medic ninja with monster strength, from Naruto.",
  "shoyo-hinata": "Short volleyball ace of the crows, from Haikyuu!!.",
  "asta": "Anti-magic swordsman chasing Wizard King, Black Clover.",
  "mikasa": "Elite soldier in a red scarf, from Attack on Titan.",
  "kaneki": "Half-ghoul with a kagune, from Tokyo Ghoul.",
  "spike-spiegel": "Laid-back bounty hunter, from Cowboy Bebop.",
  "guts": "The Black Swordsman with a huge blade, from Berserk.",
  "alucard": "Vampire agent of Hellsing, from Hellsing.",
  "vash": "Gunman with a huge bounty, from Trigun.",
  "yusuke": "Spirit Detective with the Spirit Gun, Yu Yu Hakusho.",
  "kenshin": "Wanderer with a reverse-blade sword, Rurouni Kenshin.",
  "rukia": "Soul Reaper with an ice sword, from Bleach.",
  "shanks": "Red-Haired Emperor pirate, from One Piece.",
  "nami": "Straw Hat navigator who loves tangerines, One Piece.",
  "chopper": "Reindeer doctor of the Straw Hats, from One Piece.",
  "sanji": "Kicking chef of the Straw Hats, from One Piece.",
  "gintoki": "Sweet-toothed samurai with a wooden sword, Gintama.",

  // HARD
  "gojo": "Blindfolded sorcerer with Infinity, from Jujutsu Kaisen.",
  "sukuna": "King of Curses sealed in fingers, from Jujutsu Kaisen.",
  "yuji-itadori": "Vessel of Sukuna, from Jujutsu Kaisen.",
  "megumi": "Sorcerer of the Ten Shadows, from Jujutsu Kaisen.",
  "thorfinn": "Vengeful young Viking, from Vinland Saga.",
  "griffith": "Falcon leader of the Band of the Hawk, from Berserk.",
  "dio": "Vampire with the time-stopping World, from JoJo.",
  "saber": "King Arthur as a swordswoman, from Fate/stay night.",
  "lelouch": "Masked rebel with Geass, from Code Geass.",
  "roy-mustang": "Flame Alchemist with ignition gloves, Fullmetal Alchemist.",
  "escanor": "Lion's Sin whose power peaks at noon, Seven Deadly Sins.",
  "meliodas": "Dragon's Sin captain, from The Seven Deadly Sins.",
  "natsu": "Fire Dragon Slayer with a scaly scarf, from Fairy Tail.",
  "erza": "Requip knight Titania, from Fairy Tail.",
  "gray": "Ice-Make wizard who strips, from Fairy Tail.",
  "gaara": "Sand-wielding ninja of the Desert, from Naruto.",
  "hisoka": "Card-throwing clown Hunter, from Hunter x Hunter.",
  "kurapika": "Chain user with Scarlet Eyes, from Hunter x Hunter.",
  "rimuru": "Slime who becomes a demon lord, from Slime Isekai.",
  "ainz": "Skeletal overlord of Nazarick, from Overlord.",
  "todoroki": "Half-hot half-cold hero, from My Hero Academia.",
  "mob": "Powerful psychic middle-schooler, from Mob Psycho 100.",
  "senku": "Genius reviving science, from Dr. Stone.",
  "shinji": "Reluctant Eva pilot, from Neon Genesis Evangelion.",
  "asuka": "Fiery pilot of red Unit-02, Neon Genesis Evangelion.",

  // IMPOSSIBLE
  "jonathan-joestar": "Gentleman with Hamon ripple, from JoJo Part 1.",
  "joseph-joestar": "Trickster who predicts your next line, from JoJo.",
  "giorno": "Life-giving Gold Experience user, from JoJo Part 5.",
  "kenshiro": "Fist of the North Star martial artist, Hokuto no Ken.",
  "kamina": "Shades-wearing hero of the drill, from Gurren Lagann.",
  "simon": "Mecha-piloting digger, from Gurren Lagann.",
  "revy": "Dual-gun mercenary, from Black Lagoon.",
  "mugen": "Breakdancing swordsman, from Samurai Champloo.",
  "ryuk": "Apple-loving Shinigami, from Death Note.",
  "l-lawliet": "Sweets-loving genius detective, from Death Note.",
  "celty": "Headless motorcycle rider, from Durarara!!.",
  "okabe": "Self-styled mad scientist, from Steins;Gate.",
  "holo": "Wise wolf goddess of harvest, from Spice and Wolf.",
  "kino": "Traveler touring worlds by bike, from Kino's Journey.",
  "lain": "Girl drawn into the Wired, from Serial Experiments Lain.",
  "motoko": "Cyborg Major of Section 9, from Ghost in the Shell.",
  "dandy": "Pompadour alien hunter in space, from Space Dandy.",
  "ed-cowboy-bebop": "Barefoot child hacker, from Cowboy Bebop.",
  "faye": "Con-artist bounty hunter, from Cowboy Bebop.",
  "lupin": "Master gentleman thief, from Lupin the Third.",
  "goemon": "Samurai whose blade cuts anything, from Lupin the Third.",
  "jigen": "Fast-draw gunman in a fedora, from Lupin the Third.",
  "ashitaka": "Cursed prince riding an elk, from Princess Mononoke.",
  "san": "Wolf-raised princess, from Princess Mononoke.",
  "howl": "Vain wizard of the moving castle, from Howl's Moving Castle.",
};
