// «Guess the Animal v3» — GuessSync · did-you-know facts, ≤70 chars, verified true.
export const ANIMALS3_FACTS = {
  // EASY
  "seal": "Can slow its heartbeat and dive for tens of minutes at a time",
  "sealion": "Unlike true seals it can walk on land by rotating its hind flippers",
  "seaotter": "Holds hands while sleeping so the group won't drift apart",
  "blackbear": "A strong climber that sends cubs up a tree when danger nears",
  "vampirebat": "The only mammal that feeds entirely on blood to survive",
  "reddeer": "One of the largest deer, its autumn roars carry across valleys",
  "fallowdeer": "Males grow broad flattened antlers shaped like a palm",
  "muledeer": "Named for its large mule-like ears, it bounces on all four feet",
  "jackrabbit": "Not a rabbit but a hare, its huge ears help shed body heat",
  "bighornsheep": "Rams crash horns at high speed in booming head-butt duels",
  "mountaingoat": "Grips sheer cliffs with soft-padded, two-toed climbing hooves",
  "bactriancamel": "The two-humped camel that survives freezing Gobi winters",
  "capebuffalo": "So dangerous it is nicknamed the Black Death in Africa",
  "africanwilddog": "Hunts in packs that share food and win most of their chases",
  "pygmyhippo": "A shy forest hippo far smaller than its river cousin",
  "echidna": "A spiny egg-laying mammal that slurps ants with a sticky tongue",
  "elephantseal": "Males have a huge inflatable nose used to roar at rivals",
  "gerbil": "A desert rodent that barely needs to drink any water",
  "pika": "Stacks little hay piles to eat through the long mountain winter",
  "shrew": "Must eat almost constantly or it will starve within hours",
  "vicuna": "A wild Andean camel prized for the finest wool on Earth",
  "guanaco": "The wild ancestor of the llama, it can run at high altitude",
  "eland": "The largest antelope, yet it can still jump a two-metre fence",
  "peccary": "A pig-like animal that lives in herds and has a scent gland",
  "hyrax": "A rabbit-sized animal whose closest living relative is the elephant",

  // MEDIUM
  "manedwolf": "Not a wolf or a fox, this leggy runner is its own species",
  "raccoondog": "A wild dog with a masked face, the only canine that hibernates",
  "batearedfox": "Its giant ears pinpoint insects moving under the soil",
  "grayfox": "One of the few dogs that can climb straight up a tree",
  "swiftfox": "A tiny fast fox of the prairies, no bigger than a house cat",
  "sunbear": "The smallest bear, with a tongue long enough to reach honey",
  "slothbear": "Sucks up termites with a loud vacuum-like slurping noise",
  "spectacledbear": "South America's only bear, named for its pale eye rings",
  "pinemarten": "A tree-climbing hunter with a cream-coloured throat patch",
  "polecat": "The wild ancestor of the domestic ferret, with a masked face",
  "civet": "A cat-like mammal that produces a musk once used in perfume",
  "genet": "A slender spotted hunter with a long ringed tail like a cat",
  "redsquirrel": "Buries far more nuts than it recovers, planting new forests",
  "muskrat": "A river rodent that builds dome lodges out of reeds and mud",
  "gopher": "Digs vast tunnel networks and carries food in cheek pouches",
  "lemming": "A small Arctic rodent whose numbers boom and crash in cycles",
  "dormouse": "Sleeps in hibernation for over half the year, hence its name",
  "treekangaroo": "A kangaroo that lives in trees and can leap far to the ground",
  "tamandua": "A small tree anteater that rips open nests with strong claws",
  "waterbuck": "An antelope with a white ring on its rump like a target",
  "bushbuck": "A shy striped antelope that freezes at the first sign of danger",
  "hartebeest": "A fast antelope with a long face and sharply angled horns",
  "sikadeer": "A spotted deer that keeps its spots into adulthood",
  "roedeer": "A small deer that barks like a dog when it is alarmed",
  "zebu": "A humped cow of Asia that tolerates heat and resists ticks",

  // HARD
  "bushdog": "A small forest dog of South America with webbed swimming feet",
  "corsacfox": "A steppe fox that rarely drinks, getting water from its prey",
  "giantotter": "The longest otter, reaching almost two metres in the Amazon",
  "fisher": "A forest hunter that is one of the few predators of porcupines",
  "tayra": "A large tree-climbing weasel that will hide unripe fruit to eat later",
  "ringtail": "A cat-sized relative of the raccoon with a long banded tail",
  "palmcivet": "It eats coffee cherries, giving beans for the world's priciest coffee",
  "vole": "A stout mouse-like rodent that can breed several times a year",
  "degu": "A social rodent from Chile that talks in a range of squeaks",
  "kangaroorat": "Can live its whole life without ever drinking a drop of water",
  "paca": "A spotted rodent of the rainforest that swims to escape danger",
  "springhare": "Not a hare but a rodent that hops on two legs like a kangaroo",
  "pademelon": "A small forest cousin of the wallaby with a short thick tail",
  "brushtailpossum": "A bushy-tailed tree climber often heard on rooftops at night",
  "silkyanteater": "The smallest anteater, tiny enough to curl up in one hand",
  "topi": "One of the fastest antelopes, males guard tiny mating patches",
  "roan": "One of the largest antelopes, with backward-curving ringed horns",
  "sableantelope": "Males are jet black with long scimitar-shaped swept-back horns",
  "reedbuck": "A whistling antelope that hides in tall grass near water",
  "lechwe": "A wetland antelope with splayed hooves for running through water",
  "sambar": "A large Asian deer whose alarm calls warn of nearby tigers",
  "barasingha": "A swamp deer whose antlers can carry a dozen or more points",
  "waterdeer": "A small deer with no antlers but long fang-like tusks",
  "dallsheep": "A white wild sheep that scales the steep peaks of Alaska",
  "barbarysheep": "A North African wild sheep with a long shaggy neck mane",

  // IMPOSSIBLE
  "ethiopianwolf": "Africa's rarest canid, a slim red wolf that hunts alone by day",
  "culpeo": "A fox-like wild dog of the Andes, second largest in South America",
  "crabeatingfox": "A South American wild dog that hunts crabs on muddy plains",
  "darwinsfox": "A tiny rare fox found only in Chile, first noted by Darwin",
  "sable": "A forest marten of Siberia long hunted for its luxurious fur",
  "grison": "A low slung weasel of South America with a silvery grey back",
  "cacomistle": "A nocturnal tree climber of Central America related to raccoons",
  "linsang": "A slim spotted tree hunter with a very long boldly banded tail",
  "viscacha": "A rabbit-like rodent with a long tail that lives among rocks",
  "pacarana": "A slow rare rodent of South America with striped white markings",
  "potoroo": "A small hopping marsupial that digs up and eats underground fungi",
  "bettong": "A rabbit-sized marsupial that carries nesting grass with its tail",
  "cuscus": "A slow tree-dwelling marsupial with a curling gripping tail",
  "dunnart": "A tiny mouse-like marsupial that hunts insects at night",
  "kob": "A reddish antelope where males cluster on small display grounds",
  "oribi": "A small graceful antelope that gives a sharp whistle when fleeing",
  "steenbok": "A tiny antelope that lives alone and hides in shallow burrows",
  "suni": "One of the smallest antelopes, standing only about knee high",
  "brocket": "A small shy forest deer with short simple spike-like antlers",
  "europeanbison": "Europe's heaviest land animal, saved from extinction in the wild",
  "watusi": "A cattle breed famous for enormous horns spanning over a metre",
  "urial": "A wild sheep of central Asia with a black-and-white neck ruff",
  "bharal": "A blue-grey wild sheep that grazes high Himalayan slopes",
  "leopardseal": "A fierce Antarctic seal that hunts penguins near the ice",
  "starnosedmole": "Feels with 22 pink tentacles, the fastest-eating mammal known",
};
