// E178 anime-emoji-2 facts — one true <=70-char fact per anime, shown on reveal.
export const ANIME_EMOJI_2_FACTS = {
  // EASY
  "pokemon": "1997 anime; kids train pocket monsters to battle.",
  "digimon": "1999 Toei; kids and digital monsters save two worlds.",
  "the-seven-deadly-sins": "2014 A-1 fantasy about outlawed holy knights.",
  "fire-force": "2019 David Production; pyrokinetic firefighters.",
  "black-butler": "2008 A-1 Pictures; a demon butler serves a young earl.",
  "sonic-x": "2003 TMS anime of Sega's speedy blue hedgehog.",
  "shaman-king": "2001 tournament to become king of the spirits.",
  "yo-kai-watch": "2014 anime; a boy uses a watch to see yo-kai.",
  "gundam": "1979 Sunrise mecha war saga of mobile suits.",
  "saint-seiya": "1986 Toei; armored warriors guard Athena.",
  "jojos-bizarre-adventure": "2012 David Production; the Joestars fight evil.",
  "astro-boy": "1963 Tezuka classic; a powerful robot boy hero.",
  "speed-racer": "1967 Mach GoGoGo; a young race-car driver.",
  "initial-d": "1998 street-racing anime of a tofu-shop drifter.",
  "ranma-1-2": "1989 Takahashi; a boy turns female in cold water.",
  "blue-lock": "2022 8bit; a project to forge Japan's top striker.",
  "kuroko-no-basket": "2012 Production I.G basketball with a phantom player.",
  "free-iwatobi-swim-club": "2013 Kyoto Animation high-school swimming drama.",
  "hellsing": "2001 anime; Alucard hunts vampires for Hellsing.",
  "fist-of-the-north-star": "1984 post-apocalyptic martial-arts epic.",
  "lupin-the-third": "1971 anime of the gentleman master thief Lupin.",
  "cardcaptor-sakura": "1998 CLAMP; a girl captures magical Clow cards.",
  "beyblade": "2001 anime about competitive spinning-top battles.",
  "hamtaro": "2000 anime about a small pet hamster's adventures.",
  "crayon-shin-chan": "1992 comedy about a cheeky five-year-old boy.",
  // MEDIUM
  "bakuman": "2010 J.C.Staff; two teens chase manga stardom.",
  "great-teacher-onizuka": "1999 ex-biker becomes an unorthodox teacher.",
  "golden-kamuy": "2018 Geno; a soldier and Ainu girl hunt gold.",
  "kaiji": "2007 Madhouse; a gambler risks all on debt games.",
  "akame-ga-kill": "2014 White Fox; assassins fight a corrupt empire.",
  "goblin-slayer": "2018 White Fox; a warrior devoted to slaying goblins.",
  "tokyo-revengers": "2021 Liden Films; a man time-leaps to save his ex.",
  "magi": "2012 A-1 Pictures Arabian-Nights adventure of Aladdin.",
  "fate-stay-night": "2006 mages battle in a war for the Holy Grail.",
  "no-game-no-life": "2014 Madhouse; sibling gamers conquer a game world.",
  "the-rising-of-the-shield-hero": "2019 hero armed only with a shield.",
  "log-horizon": "2013 gamers trapped inside an online RPG world.",
  "the-devil-is-a-part-timer": "2013 a demon lord flips burgers in Tokyo.",
  "gate": "2015 A-1 Pictures; the JSDF enters a fantasy portal.",
  "kill-la-kill": "2013 Trigger; a girl's living uniform seeks revenge.",
  "space-dandy": "2014 Bones; a dandy guy hunts rare aliens in space.",
  "durarara": "2010 Brain's Base; tangled lives in Ikebukuro.",
  "highschool-of-the-dead": "2010 Madhouse zombie survival horror.",
  "deadman-wonderland": "2011 a framed boy is sent to a deadly prison park.",
  "anohana": "2011 A-1 Pictures; friends mourn a lost childhood girl.",
  "my-dress-up-darling": "2022 CloverWorks; cosplay romance with a sewist.",
  "nisekoi": "2014 Shaft; a fake romance between rival families.",
  "baccano": "2007 Brain's Base; immortals clash on a 1930s train.",
  "school-rumble": "2004 anime; tangled high-school love triangles.",
  "orange": "2016 a girl gets letters from her future self.",
  // HARD
  "dorohedoro": "2020 MAPPA; a lizard-headed man seeks his lost face.",
  "drifters": "2016 Hoods; historic warriors reborn in a fantasy war.",
  "btooom": "2012 Madhouse; players fight with bombs on an island.",
  "hajime-no-ippo": "2000 Madhouse; a shy teen becomes a boxer.",
  "megalo-box": "2018 TMS; an underdog fights in geared-up boxing.",
  "banana-fish": "2018 MAPPA; a gang leader and a deadly drug secret.",
  "gungrave": "2003 Madhouse; a resurrected gunman seeks revenge.",
  "blame": "2017 Polygon; a lone wanderer in a cyber megastructure.",
  "baki": "2001 anime; a young fighter trains to beat his father.",
  "kengan-ashura": "2019 Larx; corporate gladiators fight bare-fisted.",
  "record-of-ragnarok": "2021 gods and humans duel over humanity's fate.",
  "to-your-eternity": "2021 Brain's Base; an immortal being learns to feel.",
  "dororo": "2019 MAPPA; a ronin reclaims body parts from demons.",
  "the-tatami-galaxy": "2010 Madhouse; a student relives college on a loop.",
  "aku-no-hana": "2013 Zexcs; a boy's crush spirals into dark obsession.",
  "psycho-pass": "2012 Production I.G; police judge minds in future Japan.",
  "terror-in-resonance": "2014 MAPPA; two teens stage bombings in Tokyo.",
  "darker-than-black": "2007 Bones; contractors wield powers under fake stars.",
  "eden-of-the-east": "2009 Production I.G; a man with amnesia and a phone.",
  "higurashi": "2006 anime; a rural village hides a deadly curse.",
  "umineko": "2009 Studio Deen; a family murdered on a witch's island.",
  "bakemonogatari": "2009 Shaft; a boy helps girls haunted by oddities.",
  "katanagatari": "2010 White Fox; a swordless master gathers 12 blades.",
  "planetes": "2003 Sunrise; workers collect debris in Earth's orbit.",
  "moribito": "2007 Production I.G; a spear-woman guards a prince.",
  // IMPOSSIBLE
  "texhnolyze": "2003 Madhouse; a bleak underground city and prosthetics.",
  "kaiba": "2008 Madhouse; love and memory in a world of mind chips.",
  "casshern-sins": "2008 Madhouse; a robot wanders a rusting apocalypse.",
  "now-and-then-here-and-there": "1999 a boy is pulled into a war-torn future.",
  "the-big-o": "1999 Sunrise; a mecha-piloting detective in a lost city.",
  "mind-game": "2004 Yuasa; a man escapes death inside a whale.",
  "tekkonkinkreet": "2006 Studio 4C; two orphan boys rule Treasure Town.",
  "angels-egg": "1985 Oshii; a silent girl guards a mysterious egg.",
  "belladonna-of-sadness": "1973 Mushi; a woman's dark pact amid witch hunts.",
  "night-on-the-galactic-railroad": "1985 cats ride a train through the stars.",
  "barefoot-gen": "1983 a boy survives the Hiroshima atomic bombing.",
  "grave-of-the-fireflies": "1988 Ghibli; siblings struggle in wartime Japan.",
  "only-yesterday": "1991 Ghibli; a woman recalls her childhood self.",
  "the-tale-of-the-princess-kaguya": "2013 Ghibli; a girl found inside bamboo.",
  "wolf-children": "2012 Hosoda; a mother raises two half-wolf kids.",
  "the-girl-who-leapt-through-time": "2006 Hosoda; a teen learns to leap in time.",
  "millennium-actress": "2001 Kon; a crew traces an actress's lost love.",
  "tokyo-godfathers": "2003 Kon; a homeless trio finds a baby at Christmas.",
  "redline": "2010 Madhouse; a wild anything-goes space car race.",
  "summer-wars": "2009 Hosoda; a family battles an AI in a virtual world.",
  "patlabor": "1989 Headgear; police pilot robots to fight crime.",
  "legend-of-the-galactic-heroes": "1988 epic war between two space empires.",
  "rose-of-versailles": "1979 anime; a woman guards France's queen.",
  "space-battleship-yamato": "1974 a crew sails a space warship to save Earth.",
  "aria-the-animation": "2005 Hal; gondoliers on a terraformed future Mars.",
};
