// E189 animal-emoji facts — one true <=70-char fact per animal, shown on reveal.
export const ANIMAL_EMOJI_3_FACTS = {
  // EASY
  "polar-bear": "The largest land carnivore, hunting seals on Arctic sea ice.",
  "grizzly-bear": "A powerful brown bear subspecies found across North America.",
  "buffalo": "A massive African bovine that lives and grazes in herds.",
  "bull": "An adult male of the cattle species, raised for breeding.",
  "reindeer": "A cold-adapted deer, also called caribou in North America.",
  "chimpanzee": "Humans' closest living relative, sharing about 98% of our DNA.",
  "goldfish": "A domesticated fish first bred in China over 1,000 years ago.",
  "sea-turtle": "An ancient marine reptile that returns to nest on its birth beach.",
  "eel": "A long, snake-like fish that can migrate thousands of miles.",
  "sea-lion": "An eared seal known for loud barking and agile swimming.",
  "blue-whale": "The largest animal ever known to have lived on Earth.",
  "humpback-whale": "Famous for its long, complex songs heard underwater.",
  "hare": "A fast, long-eared mammal born fully furred, unlike rabbits.",
  "red-panda": "A bamboo-eating mammal unrelated to the giant panda.",
  "sea-otter": "Uses rocks as tools to crack open shellfish on its chest.",
  "arctic-fox": "Grows a thick white coat that turns brown in summer.",
  "canary": "A small songbird once used by miners to detect gas.",
  "stork": "A tall wading bird linked in folklore to delivering babies.",
  "falcon": "A swift raptor; the peregrine can dive over 300 km/h.",
  "hawk": "A sharp-eyed bird of prey that hunts small mammals in daylight.",
  "clownfish": "Lives safely among sea anemone tentacles thanks to its mucus coat.",
  "swordfish": "Has a long, flat bill used to slash at schools of prey.",
  "catfish": "Named for its whisker-like barbels used to sense food.",
  "honey-badger": "Famous for its fearless attitude toward far larger predators.",
  "sparrow": "A small, adaptable bird that often nests near human homes.",

  // MEDIUM
  "alpaca": "A South American camelid raised mainly for its soft fleece.",
  "baboon": "A large, ground-dwelling monkey that lives in troops in Africa.",
  "gibbon": "A small ape that swings rapidly through trees by its arms.",
  "wallaby": "A smaller relative of the kangaroo found in Australia.",
  "dromedary": "A one-humped camel adapted to hot desert climates.",
  "rat": "A highly adaptable rodent found on every continent but Antarctica.",
  "gecko": "A lizard with sticky toe pads that let it climb smooth walls.",
  "macaw": "A large, colorful parrot native to Central and South America.",
  "kiwi": "A flightless New Zealand bird with nostrils at the tip of its bill.",
  "emu": "Australia's largest bird, unable to fly but a fast runner.",
  "hammerhead-shark": "Has a flattened, T-shaped head that widens its field of vision.",
  "electric-eel": "Can generate shocks over 600 volts to stun prey.",
  "piranha": "A South American fish with sharp teeth, often overhyped as deadly.",
  "barracuda": "A sleek predatory fish with a fearsome underbite of teeth.",
  "blobfish": "Its saggy look only appears out of the deep-sea pressure it lives in.",
  "mantis-shrimp": "Punches prey with a claw strike among the fastest in nature.",
  "poison-dart-frog": "Its bright skin warns predators of its toxic secretions.",
  "snow-leopard": "A high-altitude big cat with a thick tail for balance.",
  "cougar": "Also called a mountain lion, it has the widest range of any wild cat.",
  "python": "A large constrictor that squeezes prey rather than using venom.",
  "rattlesnake": "Shakes keratin segments in its tail to warn off threats.",
  "flying-squirrel": "Glides between trees using a furred skin flap, not true flight.",
  "vampire-bat": "Feeds on the blood of other animals, mainly livestock.",
  "cockatoo": "A crested parrot known for mimicking sounds and words.",
  "whale-shark": "The largest fish in the ocean, yet it only eats plankton.",

  // HARD
  "naked-mole-rat": "A nearly hairless rodent that lives in underground colonies.",
  "proboscis-monkey": "Males have an unusually large nose that amplifies their calls.",
  "leafy-seadragon": "A seahorse relative disguised with leaf-like body extensions.",
  "mudskipper": "A fish that can walk and breathe air out of the water.",
  "frilled-lizard": "Flares a wide neck frill to startle off potential predators.",
  "blue-footed-booby": "Known for its bright blue feet used in courtship dances.",
  "horned-lizard": "Can squirt blood from its eyes to deter predators.",
  "glass-frog": "Has translucent skin that reveals its internal organs.",
  "sea-cucumber": "A soft-bodied sea floor animal related to starfish.",
  "sea-urchin": "A spiny, round sea creature that grazes on algae.",
  "nautilus": "A shelled cephalopod whose spiral chambers hold gas for buoyancy.",
  "vampire-squid": "Lives in deep, oxygen-poor waters despite its ominous name.",
  "giant-isopod": "A deep-sea crustacean that can survive years without eating.",
  "coelacanth": "A 'living fossil' fish once thought extinct for 66 million years.",
  "cassowary": "A large flightless bird with a dagger-like inner toe claw.",
  "alligator": "Has a wider, U-shaped snout compared to a crocodile's V-shape.",
  "king-cobra": "The world's longest venomous snake, able to stand tall to strike.",
  "hoatzin": "A tropical bird whose chicks have claws on their wings.",
  "quetzal": "A vividly colored bird sacred to ancient Mesoamerican cultures.",
  "lyrebird": "Can mimic almost any sound it hears, including chainsaws.",
  "viper": "A venomous snake with long, hinged fangs that fold back.",
  "thorny-devil": "An Australian lizard covered in spikes that also channel water.",
  "slow-loris": "A slow-moving primate with a venomous bite from its elbow gland.",
  "hellbender": "North America's largest salamander, breathing through its skin.",
  "star-nosed-mole": "Has 22 fleshy tentacles that detect prey by touch in the dark.",

  // IMPOSSIBLE
  "tardigrade": "A microscopic animal that can survive the vacuum of space.",
  "dumbo-octopus": "Named for the ear-like fins near its head that help it swim.",
  "yeti-crab": "A deep-sea crab with hairy, bristle-covered claws.",
  "pink-fairy-armadillo": "The smallest armadillo species, native to Argentina.",
  "blue-dragon-sea-slug": "A tiny sea slug that stores stinging cells from its prey.",
  "sea-pig": "A pink, plump sea cucumber that walks on the deep ocean floor.",
  "giant-oarfish": "The longest bony fish, linked to old sea-serpent legends.",
  "immortal-jellyfish": "Can revert its cells to a younger stage, in theory forever.",
  "goblin-shark": "A rare deep-sea shark with a jaw that thrusts forward to bite.",
  "barreleye-fish": "Has a transparent head revealing its tube-shaped eyes.",
  "mimic-octopus": "Can impersonate the shape and motion of other sea animals.",
  "sea-angel": "A tiny, translucent sea slug that appears to fly underwater.",
  "giant-clam": "The largest living bivalve, with a colorful fleshy mantle.",
  "horseshoe-crab": "Its blue, copper-based blood is used to test medical safety.",
  "pistol-shrimp": "Snaps its claw fast enough to stun prey with a shock wave.",
  "bobbit-worm": "An ambush predator that strikes from sand with sharp jaws.",
  "hagfish": "Releases huge amounts of slime to escape predators' jaws.",
  "giant-weta": "One of the heaviest insects on Earth, native to New Zealand.",
  "titan-beetle": "One of the largest beetles, found in South American rainforests.",
  "peacock-spider": "A tiny Australian spider that dances to attract mates.",
  "camel-spider": "A fast desert arachnid, despite myths it is not deadly.",
  "bombardier-beetle": "Sprays a hot, chemical burst from its abdomen to defend itself.",
  "velvet-worm": "An ancient predator that shoots sticky slime to trap prey.",
  "ribbon-eel": "A vividly colored moray eel that changes color as it matures.",
  "sea-pen": "A colonial marine animal shaped like an old quill pen.",
};
