// E212 animal-emoji facts — one true <=70-char fact per animal, shown on reveal.
export const ANIMAL_EMOJI_4_FACTS = {
  // EASY
  "leopard": "Leopards drag prey up trees to keep it safe from other predators.",
  "elk": "Elk bugle loud calls that carry for miles across mountain forests.",
  "yak": "Yaks grow thick wool coats to survive Himalayan high-altitude cold.",
  "ox": "Oxen are trained cattle used for centuries to pull plows and carts.",
  "mule": "Mules are horse-donkey hybrids prized for strength and sure footing.",
  "goose": "Geese fly in a V formation to save energy on long migrations.",
  "crow": "Crows are among the smartest birds, able to use tools and count.",
  "raven": "Ravens can mimic human speech and solve multi-step puzzles.",
  "pigeon": "Pigeons can find their way home from over 1,000 miles away.",
  "quail": "Quail chicks can walk and feed themselves within hours of hatching.",
  "crane": "Cranes perform elaborate dances as part of their courtship ritual.",
  "heron": "Herons stand motionless in water for minutes to spear passing fish.",
  "hummingbird": "Hummingbirds can beat their wings up to 80 times per second.",
  "woodpecker": "Woodpeckers peck trees up to 20 times per second without brain harm.",
  "moth": "Moths outnumber butterflies roughly ten to one worldwide.",
  "wasp": "Wasps can sting repeatedly, unlike bees which sting only once.",
  "salmon": "Salmon swim upstream against currents to return to their birth river.",
  "tuna": "Tuna can swim at bursts of over 40 miles per hour.",
  "trout": "Trout can see ultraviolet light, helping them spot tiny prey.",
  "lionfish": "Lionfish have venomous spines and few predators in new habitats.",
  "black-bear": "Black bears are strong climbers and often nest young cubs in trees.",
  "brown-bear": "Brown bears can smell food from up to 18 miles away.",
  "muskox": "Muskoxen form a defensive circle to protect calves from wolves.",
  "sturgeon": "Sturgeon are ancient fish that can live over 100 years.",
  "hoopoe": "The hoopoe's crest fans open when it lands or gets excited.",
  // MEDIUM
  "bobcat": "Bobcats are named for their short, stubby tail.",
  "ocelot": "Ocelots hunt mostly at night using excellent night vision.",
  "serval": "Servals have the largest ears relative to body size of any cat.",
  "wildcat": "Wildcats look like house cats but are wary of humans.",
  "clouded-leopard": "Clouded leopards can climb down trees headfirst like squirrels.",
  "guinea-pig": "Guinea pigs cannot produce their own vitamin C and need it in food.",
  "ferret": "Ferrets sleep up to 18 hours a day.",
  "shrew": "Shrews must eat almost constantly or they can starve within hours.",
  "vole": "Voles dig shallow tunnel systems through grass and soil.",
  "gerbil": "Gerbils store extra food in their cheek pouches.",
  "albatross": "Albatrosses can glide for hours without flapping their wings.",
  "seagull": "Seagulls can drink both fresh water and salt water.",
  "kingfisher": "Kingfishers dive headfirst into water to catch fish in their beak.",
  "hornbill": "Hornbills seal females inside tree nests using mud for safety.",
  "ibis": "The ibis was considered sacred and linked to wisdom in ancient Egypt.",
  "egret": "Egrets often follow grazing animals to catch insects they stir up.",
  "condor": "Condors can soar for hours riding thermals without flapping wings.",
  "kestrel": "Kestrels can hover almost motionless in the air while hunting.",
  "magpie": "Magpies are known for being drawn to shiny objects.",
  "macaque": "Some macaques in Japan soak in hot springs to stay warm in winter.",
  "marmoset": "Marmosets communicate using high-pitched calls above human hearing.",
  "tamarin": "Golden lion tamarins have a mane of fur around their face.",
  "capuchin": "Capuchin monkeys use rocks as tools to crack open nuts.",
  "bonobo": "Bonobos resolve conflicts through social bonding rather than fighting.",
  "siamang": "Siamangs inflate a throat pouch to make loud booming calls.",
  // HARD
  "sloth-bear": "Sloth bears suck up termites through gaps left by missing front teeth.",
  "boa-constrictor": "Boa constrictors squeeze prey until its heart stops, then swallow it.",
  "mamba": "The black mamba is one of the fastest snakes, striking with speed.",
  "adder": "The adder is the only venomous snake native to Britain.",
  "monitor-lizard": "Some monitor lizards can run on their hind legs for short bursts.",
  "skink": "Some skinks can detach their tail to escape a predator's grip.",
  "snapping-turtle": "Snapping turtles have a powerful bite that can snap through bone.",
  "newt": "Newts can regrow lost limbs, eyes, and even parts of their heart.",
  "tree-frog": "Tree frogs have sticky toe pads that let them cling to smooth leaves.",
  "bullfrog": "Bullfrogs get their name from a deep croak resembling a bull's bellow.",
  "grasshopper": "Grasshoppers can jump roughly 20 times the length of their own body.",
  "stick-insect": "Stick insects freeze motionless to mimic twigs and avoid predators.",
  "millipede": "Millipedes curl into a tight spiral to protect their soft underside.",
  "langur": "Langurs are considered sacred in India and roam temples freely.",
  "colobus": "Colobus monkeys lack thumbs, an adaptation for swinging through trees.",
  "howler-monkey": "Howler monkey calls can carry three miles through dense jungle.",
  "spider-monkey": "Spider monkeys use their tail as a fifth limb to grip branches.",
  "squirrel-monkey": "Squirrel monkeys live in troops that can number over 100 individuals.",
  "sawfish": "Sawfish use their long toothed snout to slash and stun prey fish.",
  "wobbegong": "Wobbegong sharks have skin patterns that camouflage the seafloor.",
  "thresher-shark": "Thresher sharks whip their long tail to stun schools of fish.",
  "lanternfish": "Lanternfish produce their own light using organs called photophores.",
  "frogfish": "Frogfish wiggle a lure on their head to attract unsuspecting prey.",
  "archerfish": "Archerfish spit jets of water to knock insects off overhanging leaves.",
  "remora": "Remoras attach to sharks with a suction disk to hitch free rides.",
  // IMPOSSIBLE
  "fanaloka": "The fanaloka is a cat-sized carnivore found only in Madagascar.",
  "linsang": "Linsangs are slender, tree-dwelling carnivores active mostly at night.",
  "genet": "Genets have a long spotted body and ringed tail like a small leopard.",
  "serow": "The serow is a goat-antelope that lives on steep Asian forest slopes.",
  "goral": "Gorals leap between rocky cliffs with remarkable balance and grip.",
  "pronghorn": "The pronghorn is the fastest land mammal in the Americas.",
  "addax": "The addax antelope can survive long periods without drinking water.",
  "oryx": "The oryx's straight horns may have inspired the unicorn legend.",
  "springbok": "Springbok leap high in a display called pronking to signal fitness.",
  "impala": "The impala can leap over 3 meters high to escape predators.",
  "eland": "The eland is the largest antelope species in the world.",
  "topi": "Topi stand on termite mounds to scan the savanna for predators.",
  "hartebeest": "The hartebeest has an unusually long, narrow face among antelopes.",
  "duiker": "Duikers get their name from an Afrikaans word meaning 'diver.'",
  "klipspringer": "Klipspringers walk on the very tips of their hooves on rocky cliffs.",
  "nyala": "Male nyala have spiral horns and white stripes on their sides.",
  "sitatunga": "Sitatunga have splayed hooves adapted for walking on swampy ground.",
  "lechwe": "Lechwe antelope are strong swimmers found in African wetlands.",
  "waterbuck": "Waterbuck secrete an oily musk that waterproofs their coat.",
  "bharal": "The bharal, or blue sheep, lives high in the Himalayan mountains.",
  "argali": "The argali is the largest wild sheep species, prized for huge horns.",
  "urial": "The urial wild sheep has tightly curled horns and a dark neck ruff.",
  "mouflon": "The mouflon is considered the wild ancestor of domestic sheep.",
  "corsac-fox": "The corsac fox lives on the steppes and semi-deserts of Central Asia.",
  "kob": "Kob antelope males gather on small display grounds to attract mates.",
};
