// E156 «Guess the Anime Character by Emoji» — 100 characters · 25/tier · clue = plain Unicode emoji (mirrors E26 isEmoji rendering)
// Guessed via the CHARACTER'S iconic look/power, not the show logo. VO: sfx/e156-<id>.wav
export const ANIMECHAR_EMOJI = [
  // ===== EASY (25) — globally famous =====
  { id: "goku", title: "Goku", emojis: "🔥🥋", level: "easy" },
  { id: "naruto", title: "Naruto", emojis: "🍜🦊", level: "easy" },
  { id: "luffy", title: "Monkey D. Luffy", emojis: "👒🍖", level: "easy" },
  { id: "pikachu", title: "Pikachu", emojis: "⚡🐭", level: "easy" },
  { id: "sailor-moon", title: "Sailor Moon", emojis: "🌙👧", level: "easy" },
  { id: "ash-ketchum", title: "Ash Ketchum", emojis: "🧢⚡", level: "easy" },
  { id: "vegeta", title: "Vegeta", emojis: "🔥👑", level: "easy" },
  { id: "ichigo-kurosaki", title: "Ichigo Kurosaki", emojis: "⚔👹", level: "easy" },
  { id: "light-yagami", title: "Light Yagami", emojis: "📓💀", level: "easy" },
  { id: "saitama", title: "Saitama", emojis: "👊🥚", level: "easy" },
  { id: "levi-ackerman", title: "Levi Ackerman", emojis: "⚔🧹", level: "easy" },
  { id: "tanjiro", title: "Tanjiro", emojis: "🔥🗡", level: "easy" },
  { id: "nezuko", title: "Nezuko", emojis: "🎋👺", level: "easy" },
  { id: "eren-yeager", title: "Eren Yeager", emojis: "💪🦖", level: "easy" },
  { id: "deku", title: "Deku", emojis: "💪⚡", level: "easy" },
  { id: "totoro", title: "Totoro", emojis: "🌳☂", level: "easy" },
  { id: "doraemon", title: "Doraemon", emojis: "🔵🔔", level: "easy" },
  { id: "astro-boy", title: "Astro Boy", emojis: "🤖🚀", level: "easy" },
  { id: "gon-freecss", title: "Gon Freecss", emojis: "🎣🌳", level: "easy" },
  { id: "edward-elric", title: "Edward Elric", emojis: "⚗🦾", level: "easy" },
  { id: "sasuke", title: "Sasuke", emojis: "🐍⚡", level: "easy" },
  { id: "charizard", title: "Charizard", emojis: "🔥🐉", level: "easy" },
  { id: "shin-chan", title: "Shin-chan", emojis: "🖍👦", level: "easy" },
  { id: "inuyasha", title: "Inuyasha", emojis: "🐕⚔", level: "easy" },
  { id: "meowth", title: "Meowth", emojis: "🐱💰", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "kakashi", title: "Kakashi", emojis: "🎭📖", level: "medium" },
  { id: "zoro", title: "Zoro", emojis: "⚔🩹", level: "medium" },
  { id: "jotaro-kujo", title: "Jotaro Kujo", emojis: "🧢⭐", level: "medium" },
  { id: "gohan", title: "Gohan", emojis: "📖🔥", level: "medium" },
  { id: "killua", title: "Killua", emojis: "⚡🛹", level: "medium" },
  { id: "all-might", title: "All Might", emojis: "💪😁", level: "medium" },
  { id: "bakugo", title: "Bakugo", emojis: "💥😡", level: "medium" },
  { id: "yugi", title: "Yugi", emojis: "🃏👑", level: "medium" },
  { id: "sakura", title: "Sakura", emojis: "🌸👊", level: "medium" },
  { id: "shoyo-hinata", title: "Shoyo Hinata", emojis: "🏐🐦", level: "medium" },
  { id: "asta", title: "Asta", emojis: "🍀🗡", level: "medium" },
  { id: "mikasa", title: "Mikasa", emojis: "🧣⚔", level: "medium" },
  { id: "kaneki", title: "Ken Kaneki", emojis: "🎭🩸", level: "medium" },
  { id: "spike-spiegel", title: "Spike Spiegel", emojis: "🚬🔫", level: "medium" },
  { id: "guts", title: "Guts", emojis: "🗡🖤", level: "medium" },
  { id: "alucard", title: "Alucard", emojis: "🧛🔫", level: "medium" },
  { id: "vash", title: "Vash", emojis: "🔫🕶", level: "medium" },
  { id: "yusuke", title: "Yusuke", emojis: "👻👊", level: "medium" },
  { id: "kenshin", title: "Kenshin", emojis: "🗡❌", level: "medium" },
  { id: "rukia", title: "Rukia", emojis: "❄⚰", level: "medium" },
  { id: "shanks", title: "Shanks", emojis: "🟥🗡", level: "medium" },
  { id: "nami", title: "Nami", emojis: "🍊🗺", level: "medium" },
  { id: "chopper", title: "Chopper", emojis: "🦌🎩", level: "medium" },
  { id: "sanji", title: "Sanji", emojis: "🚬🦵", level: "medium" },
  { id: "gintoki", title: "Gintoki", emojis: "🍬🗡", level: "medium" },

  // ===== HARD (25) =====
  { id: "gojo", title: "Gojo", emojis: "🙈♾", level: "hard" },
  { id: "sukuna", title: "Sukuna", emojis: "👹💀", level: "hard" },
  { id: "yuji-itadori", title: "Yuji Itadori", emojis: "🎽👹", level: "hard" },
  { id: "megumi", title: "Megumi", emojis: "🐺🌑", level: "hard" },
  { id: "thorfinn", title: "Thorfinn", emojis: "🗡🌊", level: "hard" },
  { id: "griffith", title: "Griffith", emojis: "🦅⚔", level: "hard" },
  { id: "dio", title: "Dio", emojis: "🧛🕰", level: "hard" },
  { id: "saber", title: "Saber", emojis: "⚔👑", level: "hard" },
  { id: "lelouch", title: "Lelouch", emojis: "🎭♟", level: "hard" },
  { id: "roy-mustang", title: "Roy Mustang", emojis: "🔥🧤", level: "hard" },
  { id: "escanor", title: "Escanor", emojis: "☀🦁", level: "hard" },
  { id: "meliodas", title: "Meliodas", emojis: "🐷🗡", level: "hard" },
  { id: "natsu", title: "Natsu", emojis: "🔥🧣", level: "hard" },
  { id: "erza", title: "Erza", emojis: "⚔🛡", level: "hard" },
  { id: "gray", title: "Gray", emojis: "❄🧊", level: "hard" },
  { id: "gaara", title: "Gaara", emojis: "⏳🏜", level: "hard" },
  { id: "hisoka", title: "Hisoka", emojis: "🃏🎪", level: "hard" },
  { id: "kurapika", title: "Kurapika", emojis: "⛓🔴", level: "hard" },
  { id: "rimuru", title: "Rimuru", emojis: "🔵🐉", level: "hard" },
  { id: "ainz", title: "Ainz", emojis: "💀👑", level: "hard" },
  { id: "todoroki", title: "Todoroki", emojis: "🔥❄", level: "hard" },
  { id: "mob", title: "Mob", emojis: "💯🌀", level: "hard" },
  { id: "senku", title: "Senku", emojis: "🧪🗿", level: "hard" },
  { id: "shinji", title: "Shinji", emojis: "🤖🎧", level: "hard" },
  { id: "asuka", title: "Asuka", emojis: "🔴🤖", level: "hard" },

  // ===== IMPOSSIBLE (25) — beloved deep cuts fans know =====
  { id: "jonathan-joestar", title: "Jonathan Joestar", emojis: "🎩💪", level: "impossible" },
  { id: "joseph-joestar", title: "Joseph Joestar", emojis: "🔮💬", level: "impossible" },
  { id: "giorno", title: "Giorno", emojis: "🐞✨", level: "impossible" },
  { id: "kenshiro", title: "Kenshiro", emojis: "💥⭐", level: "impossible" },
  { id: "kamina", title: "Kamina", emojis: "🕶🌀", level: "impossible" },
  { id: "simon", title: "Simon", emojis: "🌀🤖", level: "impossible" },
  { id: "revy", title: "Revy", emojis: "🔫🖤", level: "impossible" },
  { id: "mugen", title: "Mugen", emojis: "🗡🎧", level: "impossible" },
  { id: "ryuk", title: "Ryuk", emojis: "🍎👹", level: "impossible" },
  { id: "l-lawliet", title: "L", emojis: "🍰🕵", level: "impossible" },
  { id: "celty", title: "Celty", emojis: "🏍💀", level: "impossible" },
  { id: "okabe", title: "Okabe", emojis: "🥼⏰", level: "impossible" },
  { id: "holo", title: "Holo", emojis: "🐺🌾", level: "impossible" },
  { id: "kino", title: "Kino", emojis: "🏍🌍", level: "impossible" },
  { id: "lain", title: "Lain", emojis: "🐻🌐", level: "impossible" },
  { id: "motoko", title: "Motoko", emojis: "🤖🕶", level: "impossible" },
  { id: "dandy", title: "Dandy", emojis: "🚀💇", level: "impossible" },
  { id: "ed-cowboy-bebop", title: "Ed", emojis: "💻👧", level: "impossible" },
  { id: "faye", title: "Faye", emojis: "💋🔫", level: "impossible" },
  { id: "lupin", title: "Lupin III", emojis: "🎩💰", level: "impossible" },
  { id: "goemon", title: "Goemon", emojis: "🗡✂", level: "impossible" },
  { id: "jigen", title: "Jigen", emojis: "🎩🔫", level: "impossible" },
  { id: "ashitaka", title: "Ashitaka", emojis: "🏹🦌", level: "impossible" },
  { id: "san", title: "San", emojis: "🐺🩸", level: "impossible" },
  { id: "howl", title: "Howl", emojis: "🔥🏰", level: "impossible" },
];
