// E134 emoji-animal facts — one verified <=70-char fact per animal, shown on reveal.
export const ANIMAL_EMOJI_FACTS = {
  // EASY
  "cat": "Domestic cats sleep for around 12-16 hours out of every day.",
  "dog": "Dogs were the first animal humans domesticated, over 14,000 years ago.",
  "lion": "A lion's roar can be heard from up to 5 miles (8 km) away.",
  "elephant": "Elephants are the largest living land animals on Earth.",
  "tiger": "Every tiger has a unique stripe pattern, like a human fingerprint.",
  "horse": "Horses can sleep both lying down and standing up.",
  "cow": "Cows have almost 360-degree panoramic vision.",
  "pig": "Pigs are highly intelligent and can learn tricks faster than dogs.",
  "rabbit": "A rabbit's teeth never stop growing its entire life.",
  "bear": "Grizzly bears can run up to 35 mph despite their huge size.",
  "panda": "Giant pandas eat bamboo for up to 12 hours a day.",
  "monkey": "Monkeys use over 30 different vocal calls to communicate.",
  "koala": "Koalas sleep up to 20 hours a day to save energy for digestion.",
  "fox": "Foxes use Earth's magnetic field to hunt prey under snow.",
  "wolf": "Wolves live and hunt in tight family groups called packs.",
  "frog": "Frogs absorb water and breathe partly through their skin.",
  "chicken": "Chickens can recognize and remember over 100 different faces.",
  "sheep": "Sheep can recognize and remember up to 50 individual faces.",
  "goat": "Goats have rectangular pupils that give them near 360-degree vision.",
  "camel": "Camel humps store fat, not water, for energy in the desert.",
  "snake": "Snakes smell using their forked tongue, not just their nose.",
  "turtle": "Some turtles can live longer than 100 years.",
  "octopus": "Octopuses have three hearts and blue, copper-based blood.",
  "whale": "The blue whale is the largest animal ever known to have lived.",
  "giraffe": "A giraffe's tongue can be up to 20 inches (50 cm) long.",

  // MEDIUM
  "penguin": "Penguins can't fly, but some can leap 6 feet out of water.",
  "owl": "Owls can rotate their heads up to 270 degrees.",
  "peacock": "Only male peafowl grow the giant, colorful tail feathers.",
  "flamingo": "Flamingos are pink because of pigments in the shrimp they eat.",
  "raccoon": "Raccoons have highly sensitive front paws, almost like human hands.",
  "otter": "Sea otters hold hands while sleeping so they don't drift apart.",
  "seal": "Seals can hold their breath underwater for over an hour.",
  "walrus": "A walrus's tusks are actually two very long canine teeth.",
  "squirrel": "Squirrels forget where they buried up to 25% of their nuts.",
  "hippopotamus": "Hippos secrete a natural reddish oil that acts like sunscreen.",
  "chameleon": "Chameleons change color mainly to signal mood, not just to hide.",
  "cheetah": "Cheetahs can accelerate from 0 to 60 mph in about 3 seconds.",
  "panther": "\"Panther\" usually refers to a black-colored leopard or jaguar.",
  "jaguar": "Jaguars have the strongest bite of any big cat relative to size.",
  "hyena": "Spotted hyenas live in complex societies led by females.",
  "meerkat": "Meerkats post a sentry on watch while the group forages for food.",
  "platypus": "The platypus is a mammal that lays eggs and has a venomous spur.",
  "narwhal": "A narwhal's long spiral tusk is actually an oversized tooth.",
  "axolotl": "Axolotls can regrow entire lost limbs, even parts of their brain.",
  "capybara": "Capybaras are the largest rodents alive today.",
  "wombat": "Wombats produce cube-shaped droppings so they don't roll away.",
  "toucan": "A toucan's giant colorful bill helps it regulate body heat.",
  "mole": "Moles can dig tunnels up to 18 feet (5.5 m) an hour.",
  "ladybug": "Ladybugs are actually a type of beetle, not a true bug.",
  "skunk": "Skunks can accurately spray their odor up to 10 feet away.",

  // HARD
  "aardvark": "Aardvarks use a sticky tongue to eat thousands of termites nightly.",
  "pangolin": "Pangolins are the only mammals entirely covered in hard scales.",
  "okapi": "The okapi's zebra-striped legs help it hide in dense rainforest.",
  "tapir": "Tapirs are more closely related to horses and rhinos than to pigs.",
  "wolverine": "Wolverines have one of the strongest bites of any land mammal.",
  "mongoose": "Mongooses have partial immunity to venom from cobras they hunt.",
  "binturong": "A binturong's fur famously smells like fresh buttered popcorn.",
  "fennec-fox": "The fennec fox has the largest ears relative to body size of any fox.",
  "dingo": "Dingoes are wild dogs that have lived in Australia for millennia.",
  "coyote": "Coyotes can run at speeds of up to 40 mph when chasing prey.",
  "jackal": "Jackals often mate for life and hunt in monogamous pairs.",
  "lynx": "A lynx's ear tufts help it pinpoint the exact direction of sounds.",
  "badger": "Badgers dig extensive underground tunnel systems called setts.",
  "weasel": "Weasels are among the smallest true carnivores on Earth.",
  "armadillo": "The three-banded armadillo can roll itself into a complete ball.",
  "anteater": "A giant anteater's tongue can flick in and out 150 times a minute.",
  "manatee": "A manatee's closest living relative is the elephant.",
  "dugong": "Sailors once mistook dugongs at sea for mythical mermaids.",
  "quokka": "Quokkas are nicknamed \"the world's happiest animal\" for their smile.",
  "numbat": "Numbats eat almost exclusively termites, up to 20,000 a day.",
  "echidna": "Echidnas lay eggs despite being covered in spines like a hedgehog.",
  "tarsier": "A tarsier's eyes are each roughly the size of its entire brain.",
  "gharial": "A gharial's thin snout is lined with over 100 sharp teeth for fish.",
  "komodo-dragon": "The Komodo dragon is the largest living lizard species on Earth.",
  "civet": "Civet-processed coffee beans are used to make kopi luwak coffee.",

  // IMPOSSIBLE
  "aye-aye": "An aye-aye taps trees and uses one long finger to fish out grubs.",
  "quoll": "Quolls are spotted, cat-sized marsupial predators native to Australia.",
  "saola": "The saola was only discovered by scientists in Vietnam in 1992.",
  "kakapo": "The kakapo is the world's only flightless, nocturnal parrot.",
  "shoebill": "The shoebill stork can stand motionless for hours while hunting fish.",
  "solenodon": "The solenodon is one of few mammals with venomous saliva.",
  "fossa": "The fossa is Madagascar's largest predator, related to the mongoose.",
  "tenrec": "Some tenrecs communicate by rubbing quills together, like crickets.",
  "babirusa": "A male babirusa's upper tusks grow upward through its own snout.",
  "markhor": "The markhor's spiral horns can grow over 5 feet (1.6 m) long.",
  "gerenuk": "Gerenuks stand on hind legs to browse leaves other antelope miss.",
  "saiga": "The saiga's huge droopy nose filters dust and warms cold air.",
  "kinkajou": "Kinkajous have a prehensile tail and are nicknamed \"honey bears\".",
  "colugo": "Colugos glide between trees using a skin membrane, but cannot fly.",
  "pika": "Pikas gather and dry \"hay piles\" of plants to survive winter.",
  "bilby": "Bilbies are sometimes called the \"Australian Easter Bunny.\"",
  "thylacine": "The last known thylacine died in a Tasmanian zoo in 1936.",
  "springhare": "Despite its name, the springhare is a rodent, not a hare or rabbit.",
  "dhole": "Dholes, Asian wild dogs, hunt in packs and whistle to each other.",
  "onager": "The onager is a wild ass and one of the fastest equids on Earth.",
  "indri": "The indri is the largest living lemur, known for loud singing.",
  "aardwolf": "Aardwolves are hyena relatives that feed almost entirely on termites.",
  "bongo": "The bongo is the largest and heaviest forest antelope in Africa.",
  "nilgai": "The nilgai is the largest antelope species native to Asia.",
  "zorilla": "The zorilla, or striped polecat, sprays a skunk-like defensive odor.",
};
