// E197 «Guess the Anime by Emoji 3» — 100 anime · 25/tier
// VO: sfx/e197-<id>.wav
export const ANIME_EMOJI_3 = [
  // ===== EASY (25) =====
  { id: "solo-leveling", title: "Solo Leveling", emojis: "⚔🌑", level: "easy" },
  { id: "oshi-no-ko", title: "Oshi no Ko", emojis: "⭐👶", level: "easy" },
  { id: "frieren", title: "Frieren: Beyond Journey's End", emojis: "🧝⏳", level: "easy" },
  { id: "dragon-ball-super", title: "Dragon Ball Super", emojis: "🐉💥", level: "easy" },
  { id: "boruto", title: "Boruto: Naruto Next Generations", emojis: "🌀👦", level: "easy" },
  { id: "howls-moving-castle", title: "Howl's Moving Castle", emojis: "🏰🔥", level: "easy" },
  { id: "kikis-delivery-service", title: "Kiki's Delivery Service", emojis: "🧹🐱", level: "easy" },
  { id: "ponyo", title: "Ponyo", emojis: "🐟👧", level: "easy" },
  { id: "princess-mononoke", title: "Princess Mononoke", emojis: "🐺🗡", level: "easy" },
  { id: "pretty-cure", title: "Pretty Cure", emojis: "🎀💗", level: "easy" },
  { id: "bocchi-the-rock", title: "Bocchi the Rock!", emojis: "🎸😰", level: "easy" },
  { id: "macross", title: "Macross", emojis: "🎤🚀", level: "easy" },
  { id: "mazinger-z", title: "Mazinger Z", emojis: "🤖👊", level: "easy" },
  { id: "ashita-no-joe", title: "Ashita no Joe", emojis: "🥊🚬", level: "easy" },
  { id: "weathering-with-you", title: "Weathering with You", emojis: "☔👧", level: "easy" },
  { id: "suzume", title: "Suzume", emojis: "🚪🐈", level: "easy" },
  { id: "boy-and-the-heron", title: "The Boy and the Heron", emojis: "🦅🗼", level: "easy" },
  { id: "k-on", title: "K-On!", emojis: "🎸☕", level: "easy" },
  { id: "prince-of-tennis", title: "The Prince of Tennis", emojis: "🎾👑", level: "easy" },
  { id: "inazuma-eleven", title: "Inazuma Eleven", emojis: "⚽⚡", level: "easy" },
  { id: "cardfight-vanguard", title: "Cardfight!! Vanguard", emojis: "🃏⚔", level: "easy" },
  { id: "tokyo-mew-mew", title: "Tokyo Mew Mew", emojis: "🐱💗", level: "easy" },
  { id: "zatch-bell", title: "Zatch Bell!", emojis: "📖⚡", level: "easy" },
  { id: "yowamushi-pedal", title: "Yowamushi Pedal", emojis: "🚴🔥", level: "easy" },
  { id: "mushoku-tensei", title: "Mushoku Tensei", emojis: "🌲🧙", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "madoka-magica", title: "Puella Magi Madoka Magica", emojis: "🎀🔫", level: "medium" },
  { id: "fate-zero", title: "Fate/Zero", emojis: "⚔🌙", level: "medium" },
  { id: "classroom-of-the-elite", title: "Classroom of the Elite", emojis: "🏫🎭", level: "medium" },
  { id: "horimiya", title: "Horimiya", emojis: "💕📓", level: "medium" },
  { id: "rent-a-girlfriend", title: "Rent-a-Girlfriend", emojis: "💑📱", level: "medium" },
  { id: "cyberpunk-edgerunners", title: "Cyberpunk: Edgerunners", emojis: "🤖⚡", level: "medium" },
  { id: "dandadan", title: "Dandadan", emojis: "👽👻", level: "medium" },
  { id: "delicious-in-dungeon", title: "Delicious in Dungeon", emojis: "🍲🐉", level: "medium" },
  { id: "mashle", title: "Mashle: Magic and Muscle", emojis: "💪🪄", level: "medium" },
  { id: "ranking-of-kings", title: "Ranking of Kings", emojis: "👑⚔", level: "medium" },
  { id: "tower-of-god", title: "Tower of God", emojis: "🗼👦", level: "medium" },
  { id: "god-of-high-school", title: "The God of High School", emojis: "🥋⚡", level: "medium" },
  { id: "full-metal-panic", title: "Full Metal Panic!", emojis: "🎯🤖", level: "medium" },
  { id: "outlaw-star", title: "Outlaw Star", emojis: "🚀🔫", level: "medium" },
  { id: "eureka-seven", title: "Eureka Seven", emojis: "🏄🤖", level: "medium" },
  { id: "certain-scientific-railgun", title: "A Certain Scientific Railgun", emojis: "⚡👧", level: "medium" },
  { id: "wotakoi", title: "Wotakoi: Love Is Hard for Otaku", emojis: "💻💕", level: "medium" },
  { id: "saiki-k", title: "The Disastrous Life of Saiki K.", emojis: "🔮😑", level: "medium" },
  { id: "ouran", title: "Ouran High School Host Club", emojis: "🌹🎩", level: "medium" },
  { id: "nozaki-kun", title: "Monthly Girls' Nozaki-kun", emojis: "📖💐", level: "medium" },
  { id: "march-comes-in-like-a-lion", title: "March Comes in Like a Lion", emojis: "♟🦁", level: "medium" },
  { id: "chihayafuru", title: "Chihayafuru", emojis: "🎴💨", level: "medium" },
  { id: "diamond-no-ace", title: "Diamond no Ace", emojis: "⚾💎", level: "medium" },
  { id: "cross-game", title: "Cross Game", emojis: "⚾💕", level: "medium" },
  { id: "castle-in-the-sky", title: "Castle in the Sky", emojis: "🏰☁", level: "medium" },

  // ===== HARD (25) =====
  { id: "arifureta", title: "Arifureta: From Commonplace to World's Strongest", emojis: "⚔🕳", level: "hard" },
  { id: "realist-hero", title: "How a Realist Hero Rebuilt the Kingdom", emojis: "👑📊", level: "hard" },
  { id: "eighty-six", title: "86 Eighty-Six", emojis: "🎖🖤", level: "hard" },
  { id: "ajin", title: "Ajin: Demi-Human", emojis: "🧟🖤", level: "hard" },
  { id: "uzumaki", title: "Uzumaki", emojis: "🌀😱", level: "hard" },
  { id: "ghost-hunt", title: "Ghost Hunt", emojis: "👻🔍", level: "hard" },
  { id: "sket-dance", title: "Sket Dance", emojis: "🕵🏫", level: "hard" },
  { id: "beelzebub", title: "Beelzebub", emojis: "👶😈", level: "hard" },
  { id: "voltes-v", title: "Voltes V", emojis: "🤖🌩", level: "hard" },
  { id: "zoids", title: "Zoids", emojis: "🦖🤖", level: "hard" },
  { id: "battle-angel-alita", title: "Battle Angel Alita", emojis: "🤖👁", level: "hard" },
  { id: "knights-of-sidonia", title: "Knights of Sidonia", emojis: "🚀👹", level: "hard" },
  { id: "aldnoah-zero", title: "Aldnoah.Zero", emojis: "🚀⚔", level: "hard" },
  { id: "days-soccer", title: "Days", emojis: "⚽📔", level: "hard" },
  { id: "wolf-girl-black-prince", title: "Wolf Girl and Black Prince", emojis: "🐺🖤", level: "hard" },
  { id: "snow-white-red-hair", title: "Snow White with the Red Hair", emojis: "❄👑", level: "hard" },
  { id: "ancient-magus-bride", title: "The Ancient Magus' Bride", emojis: "🔮💀", level: "hard" },
  { id: "natsumes-book-of-friends", title: "Natsume's Book of Friends", emojis: "📖🐱", level: "hard" },
  { id: "vampire-knight", title: "Vampire Knight", emojis: "🧛🌙", level: "hard" },
  { id: "rosario-vampire", title: "Rosario + Vampire", emojis: "🧛🌹", level: "hard" },
  { id: "trinity-blood", title: "Trinity Blood", emojis: "✝🩸", level: "hard" },
  { id: "blood-blockade-battlefront", title: "Blood Blockade Battlefront", emojis: "🩸🕶", level: "hard" },
  { id: "pandora-hearts", title: "Pandora Hearts", emojis: "🐰⏳", level: "hard" },
  { id: "black-rock-shooter", title: "Black Rock Shooter", emojis: "⭐🔫", level: "hard" },
  { id: "karneval", title: "Karneval", emojis: "🎪🐱", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "cat-returns", title: "The Cat Returns", emojis: "🐱👑", level: "impossible" },
  { id: "whisper-of-the-heart", title: "Whisper of the Heart", emojis: "🐱📚", level: "impossible" },
  { id: "when-marnie-was-there", title: "When Marnie Was There", emojis: "👻🏡", level: "impossible" },
  { id: "arrietty", title: "The Secret World of Arrietty", emojis: "🧵🐁", level: "impossible" },
  { id: "pom-poko", title: "Pom Poko", emojis: "🦝🎏", level: "impossible" },
  { id: "ocean-waves", title: "Ocean Waves", emojis: "🌊💭", level: "impossible" },
  { id: "poppy-hill", title: "From Up on Poppy Hill", emojis: "🌺⚓", level: "impossible" },
  { id: "rahxephon", title: "RahXephon", emojis: "🤖🎼", level: "impossible" },
  { id: "nadia", title: "Nadia: The Secret of Blue Water", emojis: "🌊👧", level: "impossible" },
  { id: "fushigi-yuugi", title: "Fushigi Yuugi", emojis: "🐦📖", level: "impossible" },
  { id: "x-1999", title: "X/1999", emojis: "✝🌆", level: "impossible" },
  { id: "angelic-layer", title: "Angelic Layer", emojis: "🎮👧", level: "impossible" },
  { id: "chrono-crusade", title: "Chrono Crusade", emojis: "✝🔫", level: "impossible" },
  { id: "read-or-die", title: "Read or Die", emojis: "📖🔫", level: "impossible" },
  { id: "escaflowne", title: "The Vision of Escaflowne", emojis: "⚔🐉", level: "impossible" },
  { id: "slayers", title: "Slayers", emojis: "🧙💥", level: "impossible" },
  { id: "magic-knight-rayearth", title: "Magic Knight Rayearth", emojis: "⚔🌈", level: "impossible" },
  { id: "ninja-scroll", title: "Ninja Scroll", emojis: "🥷🗡", level: "impossible" },
  { id: "vampire-hunter-d", title: "Vampire Hunter D", emojis: "🧛🐴", level: "impossible" },
  { id: "utawarerumono", title: "Utawarerumono", emojis: "🎭🦊", level: "impossible" },
  { id: "scrapped-princess", title: "Scrapped Princess", emojis: "👑🗺", level: "impossible" },
  { id: "kimba-the-white-lion", title: "Kimba the White Lion", emojis: "🦁👑", level: "impossible" },
  { id: "space-adventure-cobra", title: "Space Adventure Cobra", emojis: "🚀🐍", level: "impossible" },
  { id: "galaxy-express-999", title: "Galaxy Express 999", emojis: "🚂🌠", level: "impossible" },
  { id: "please-save-my-earth", title: "Please Save My Earth", emojis: "🌍🌙", level: "impossible" },
];
