// E133 emoji-anime facts — one verified <=70-char fact per anime, shown on reveal.
export const ANIME_EMOJI_FACTS = {
  // EASY
  "naruto": "Masashi Kishimoto's manga began in 1999; anime debuted in 2002.",
  "one-piece": "Eiichiro Oda's manga started in 1997; still ongoing as of 2026.",
  "dragon-ball": "Akira Toriyama's manga began in 1984; anime aired from 1986.",
  "dragon-ball-z": "1989 sequel anime; adapted the second half of Toriyama's manga.",
  "attack-on-titan": "Hajime Isayama's manga began 2009; anime by Wit/MAPPA from 2013.",
  "demon-slayer": "Koyoharu Gotouge's manga began 2016; Ufotable anime aired 2019.",
  "my-hero-academia": "Kohei Horikoshi's manga began 2014; Studio Bones anime from 2016.",
  "death-note": "Ohba & Obata's manga ran 2003-2006; Madhouse anime aired 2006.",
  "sailor-moon": "Naoko Takeuchi's manga began 1991; Toei anime aired from 1992.",
  "doraemon": "Fujiko F. Fujio's manga began 1969; the robot cat is a Japanese icon.",
  "fullmetal-alchemist": "Hiromu Arakawa's manga began 2001; Brotherhood anime aired 2009.",
  "bleach": "Tite Kubo's manga ran 2001-2016; Studio Pierrot anime debuted 2004.",
  "hunter-x-hunter": "Yoshihiro Togashi's manga began 1998; 2011 anime by Madhouse.",
  "jujutsu-kaisen": "Gege Akutami's manga began 2018; MAPPA anime debuted 2020.",
  "spirited-away": "Ghibli's 2001 Miyazaki film won the Best Animated Feature Oscar.",
  "my-neighbor-totoro": "Studio Ghibli's 1988 film directed by Hayao Miyazaki.",
  "detective-conan": "Gosho Aoyama's manga began 1994; anime has aired since 1996.",
  "yu-gi-oh": "Kazuki Takahashi's manga began 1996; card game anime aired from 1998.",
  "cowboy-bebop": "Shinichiro Watanabe's Sunrise anime aired in 1998.",
  "neon-genesis-evangelion": "Hideaki Anno's Gainax anime aired in 1995.",
  "fairy-tail": "Hiro Mashima's manga began 2006; A-1 Pictures anime aired from 2009.",
  "one-punch-man": "ONE's webcomic began 2009; Madhouse anime adaptation aired 2015.",
  "spy-x-family": "Tatsuya Endo's manga began 2019; Wit/CloverWorks anime aired 2022.",
  "chainsaw-man": "Tatsuki Fujimoto's manga began 2018; MAPPA anime debuted 2022.",
  "tokyo-ghoul": "Sui Ishida's manga ran 2011-2014; Studio Pierrot anime aired 2014.",

  // MEDIUM
  "slam-dunk": "Takehiko Inoue's basketball manga ran 1990-1996; Toei anime 1993.",
  "captain-tsubasa": "Yoichi Takahashi's soccer manga began 1981; anime aired from 1983.",
  "inuyasha": "Rumiko Takahashi's manga ran 1996-2008; Sunrise anime aired 2000.",
  "fruits-basket": "Natsuki Takaya's manga began 1998; anime aired 2001, rebooted 2019.",
  "black-clover": "Yuki Tabata's manga began 2015; Pierrot anime aired from 2017.",
  "haikyuu": "Haruichi Furudate's volleyball manga began 2012; anime aired 2014.",
  "dr-stone": "Riichiro Inagaki & Boichi's manga began 2017; TMS anime aired 2019.",
  "the-promised-neverland": "Shirai & Demizu's manga began 2016; anime aired 2019.",
  "code-geass": "Sunrise's original anime by Goro Taniguchi aired in 2006.",
  "steins-gate": "White Fox's 2011 anime is based on the 2009 visual novel.",
  "re-zero": "Tappei Nagatsuki's light novel began 2012; White Fox anime aired 2016.",
  "sword-art-online": "Reki Kawahara's light novel began 2009; A-1 Pictures anime aired 2012.",
  "vinland-saga": "Makoto Yukimura's manga began 2005; Wit Studio anime aired 2019.",
  "mob-psycho-100": "ONE's webcomic began 2012; Studio Bones anime aired 2016.",
  "violet-evergarden": "Kyoto Animation's 2018 anime adapts Kana Akatsuki's novel.",
  "a-silent-voice": "Kyoto Animation's 2016 film is based on Yoshitoki Oima's manga.",
  "your-name": "Makoto Shinkai's 2016 film is among Japan's top-grossing anime.",
  "ghost-in-the-shell": "Mamoru Oshii's 1995 film adapts Masamune Shirow's manga.",
  "akira": "Katsuhiro Otomo directed this landmark 1988 cyberpunk film.",
  "berserk": "Kentaro Miura's manga began 1989; OLM anime aired in 1997.",
  "yu-yu-hakusho": "Yoshihiro Togashi's manga ran 1990-1994; anime aired 1992.",
  "rurouni-kenshin": "Nobuhiro Watsuki's manga ran 1994-1999; anime aired 1996.",
  "gintama": "Hideaki Sorachi's manga began 2003; Sunrise anime aired from 2006.",
  "assassination-classroom": "Yusei Matsui's manga ran 2012-2016; Lerche anime aired 2015.",
  "toradora": "Yuyuko Takemiya's light novel began 2006; J.C.Staff anime aired 2008.",

  // HARD
  "erased": "Kei Sanbe's manga began 2012; A-1 Pictures anime aired in 2016.",
  "parasyte": "Hitoshi Iwaaki's manga ran 1988-1995; Madhouse anime aired 2014.",
  "kaguya-sama-love-is-war": "Aka Akasaka's manga began 2015; A-1 Pictures anime aired 2019.",
  "devilman-crybaby": "Masaaki Yuasa's 2018 Netflix anime reimagines Go Nagai's 1972 manga.",
  "made-in-abyss": "Akihito Tsukushi's manga began 2012; Kinema Citrus anime aired 2017.",
  "konosuba": "Natsume Akatsuki's novel began 2013; Studio Deen anime aired 2016.",
  "overlord": "Kugane Maruyama's light novel began 2012; Madhouse anime aired 2015.",
  "that-time-i-got-reincarnated-as-a-slime": "Fuse's light novel began 2013; 8bit anime aired in 2018.",
  "food-wars": "Tsukuda & Saeki's manga began 2012; anime aired 2015.",
  "nichijou": "Keiichi Arawi's manga began 2006; Kyoto Animation anime aired 2011.",
  "clannad": "Key's visual novel released 2004; Kyoto Animation anime aired 2007.",
  "angel-beats": "Jun Maeda wrote this 2010 P.A. Works original anime.",
  "rascal-does-not-dream-of-bunny-girl-senpai": "Hajime Kamoshida's novel began 2014; anime aired 2018.",
  "noragami": "Adachitoka's manga began 2010; Bones anime aired 2014.",
  "blue-exorcist": "Kazue Kato's manga began 2009; A-1 Pictures anime aired 2011.",
  "soul-eater": "Atsushi Okubo's manga ran 2004-2013; Bones anime aired 2008.",
  "d-gray-man": "Katsura Hoshino's manga began 2004; TMS anime aired 2006.",
  "claymore": "Norihiro Yagi's manga ran 2001-2014; Madhouse anime aired 2007.",
  "elfen-lied": "Lynn Okamoto's manga ran 2002-2005; Arms anime aired 2004.",
  "trigun": "Yasuhiro Nightow's manga began 1995; Madhouse anime aired 1998.",
  "samurai-champloo": "Shinichiro Watanabe's Manglobe anime aired in 2004.",
  "nana": "Ai Yazawa's manga began 2000; Madhouse anime aired 2006.",
  "paranoia-agent": "Satoshi Kon's original Madhouse anime aired in 2004.",
  "paprika": "Satoshi Kon directed this 2006 film based on Yasutaka Tsutsui's novel.",
  "gurren-lagann": "Gainax's original anime by Hiroyuki Imaishi aired in 2007.",

  // IMPOSSIBLE
  "serial-experiments-lain": "Yoshitoshi ABe & Chiaki Konaka's Triangle Staff anime aired 1998.",
  "texhnolyze": "Madhouse's original cyberpunk anime by Hiroshi Hamasaki aired in 2003.",
  "kinos-journey": "Keiichi Sigsawa's light novel began 2000; A.C.G.T. anime aired 2003.",
  "haibane-renmei": "Yoshitoshi ABe's original Radix anime aired in 2002.",
  "mushishi": "Yuki Urushibara's manga began 1999; Artland anime aired 2005.",
  "flip-flappers": "Studio 3Hz's original anime by Kiyotaka Oshiyama aired in 2016.",
  "land-of-the-lustrous": "Haruko Ichikawa's manga began 2012; Orange's 2017 CG anime adapted it.",
  "girls-last-tour": "Tsukumizu's manga began 2014; White Fox anime aired 2017.",
  "shinsekai-yori": "Yusuke Kishi's novel adapted as From the New World in 2012.",
  "boogiepop-phantom": "Madhouse's 2000 anime adapts Kouhei Kadono's Boogiepop light novels.",
  "welcome-to-the-nhk": "Tatsuhiko Takimoto's novel adapted by Gonzo as a 2006 anime.",
  "revolutionary-girl-utena": "Kunihiko Ikuhara's J.C.Staff anime aired in 1997.",
  "now-and-then-here-and-there": "AIC's dark 1999 anime by Akitaroh Daichi aired in 1999.",
  "kaiba": "Masaaki Yuasa's original Madhouse anime aired in 2008.",
  "dennou-coil": "Mitsuo Iso's original Madhouse anime about AR glasses aired 2007.",
  "ergo-proxy": "Manglobe's original cyberpunk anime aired in 2006.",
  "cat-soup": "Tatsuo Sato's surreal Nekojiru-inspired short OVA aired in 2001.",
  "flcl": "Gainax's six-episode OVA directed by Kazuya Tsurumaki aired in 2000.",
  "shigurui": "Norio Nanjo's novel adapted by Madhouse as a 2007 anime.",
  "requiem-for-the-phantom": "Bee Train's 2009 anime adapts the 2000 Phantom of Inferno game.",
  "kemonozume": "Masaaki Yuasa's original Madhouse anime aired in 2006.",
  "mononoke": "Toei's stylized 2007 anime spun off from Ayakashi anthology.",
  "wolfs-rain": "Bones' original anime by Tensai Okamura aired in 2003.",
  "shiki": "Fuyumi Ono's novel adapted by Daume as a 2010 anime.",
  "gankutsuou": "Gonzo's 2004 sci-fi anime reimagines The Count of Monte Cristo.",
};
