// E75 «Guess the ZOOMED Animal» — GuessSync "What the Zoom" hard-mode.
// Reuses the EXACT E03 animal image set (animals/<slug>.png) and E03's ANIMAL_FACTS + an-<slug>.wav
// answer VOs (copied to az-<slug>.wav), but RE-TIERED by how hard each animal is to name from an
// EXTREME off-center close-up crop (scale 3.0). A random patch shows one surface region only, so:
//   EASY = unmistakable pattern/texture/colour survives any crop (stripes/spots/scales/bright hue)
//   IMPOSSIBLE = plain single-colour fur/skin (a crop = one flat colour) or ultra-obscure species
// image: animals/<slug>.png | answer VO: sfx/az-<slug>.wav (copied from E03's an-<slug>.wav)
export const ANIMALZOOM = [
  // ===== EASY (25) — bold pattern / texture / colour recognisable from any patch =====
  { slug: "zebra", name: "Zebra", level: "easy" },
  { slug: "tiger", name: "Tiger", level: "easy" },
  { slug: "giraffe", name: "Giraffe", level: "easy" },
  { slug: "panda", name: "Giant Panda", level: "easy" },
  { slug: "penguin", name: "Penguin", level: "easy" },
  { slug: "peacock", name: "Peacock", level: "easy" },
  { slug: "flamingo", name: "Flamingo", level: "easy" },
  { slug: "pangolin", name: "Pangolin", level: "easy" },
  { slug: "armadillo", name: "Armadillo", level: "easy" },
  { slug: "porcupine", name: "Porcupine", level: "easy" },
  { slug: "chameleon", name: "Chameleon", level: "easy" },
  { slug: "gecko", name: "Leopard Gecko", level: "easy" },
  { slug: "mandrill", name: "Mandrill", level: "easy" },
  { slug: "kingfisher", name: "Kingfisher", level: "easy" },
  { slug: "cassowary", name: "Cassowary", level: "easy" },
  { slug: "axolotl", name: "Axolotl", level: "easy" },
  { slug: "starfish", name: "Starfish", level: "easy" },
  { slug: "jellyfish", name: "Jellyfish", level: "easy" },
  { slug: "seahorse", name: "Seahorse", level: "easy" },
  { slug: "octopus", name: "Octopus", level: "easy" },
  { slug: "puffin", name: "Atlantic Puffin", level: "easy" },
  { slug: "toucan", name: "Toucan", level: "easy" },
  { slug: "snake", name: "Snake", level: "easy" },
  { slug: "crocodile", name: "Crocodile", level: "easy" },
  { slug: "hornbill", name: "Hornbill", level: "easy" },
  // ===== MEDIUM (25) — distinctive feature/colour, but a random patch can be ambiguous =====
  { slug: "elephant", name: "Elephant", level: "medium" },
  { slug: "shark", name: "Shark", level: "medium" },
  { slug: "ostrich", name: "Ostrich", level: "medium" },
  { slug: "owl", name: "Owl", level: "medium" },
  { slug: "frog", name: "Frog", level: "medium" },
  { slug: "hedgehog", name: "Hedgehog", level: "medium" },
  { slug: "meerkat", name: "Meerkat", level: "medium" },
  { slug: "sloth", name: "Sloth", level: "medium" },
  { slug: "koala", name: "Koala", level: "medium" },
  { slug: "raccoon", name: "Raccoon", level: "medium" },
  { slug: "lemur", name: "Ring-tailed Lemur", level: "medium" },
  { slug: "redpanda", name: "Red Panda", level: "medium" },
  { slug: "camel", name: "Camel", level: "medium" },
  { slug: "bison", name: "Bison", level: "medium" },
  { slug: "walrus", name: "Walrus", level: "medium" },
  { slug: "pelican", name: "Pelican", level: "medium" },
  { slug: "platypus", name: "Platypus", level: "medium" },
  { slug: "seaturtle", name: "Sea Turtle", level: "medium" },
  { slug: "caracal", name: "Caracal", level: "medium" },
  { slug: "lynx", name: "Lynx", level: "medium" },
  { slug: "otter", name: "Otter", level: "medium" },
  { slug: "prayingmantis", name: "Praying Mantis", level: "medium" },
  { slug: "coati", name: "Coati", level: "medium" },
  { slug: "gharial", name: "Gharial", level: "medium" },
  { slug: "ibex", name: "Ibex", level: "medium" },
  // ===== HARD (25) — plain fur / subtle features; a close-up patch gives little away =====
  { slug: "lion", name: "Lion", level: "hard" },
  { slug: "kangaroo", name: "Kangaroo", level: "hard" },
  { slug: "dog", name: "Dog", level: "hard" },
  { slug: "cat", name: "Cat", level: "hard" },
  { slug: "horse", name: "Horse", level: "hard" },
  { slug: "cow", name: "Cow", level: "hard" },
  { slug: "pig", name: "Pig", level: "hard" },
  { slug: "sheep", name: "Sheep", level: "hard" },
  { slug: "monkey", name: "Monkey", level: "hard" },
  { slug: "bear", name: "Brown Bear", level: "hard" },
  { slug: "polarbear", name: "Polar Bear", level: "hard" },
  { slug: "rabbit", name: "Rabbit", level: "hard" },
  { slug: "llama", name: "Llama", level: "hard" },
  { slug: "hyena", name: "Hyena", level: "hard" },
  { slug: "tapir", name: "Tapir", level: "hard" },
  { slug: "okapi", name: "Okapi", level: "hard" },
  { slug: "capybara", name: "Capybara", level: "hard" },
  { slug: "wombat", name: "Wombat", level: "hard" },
  { slug: "mongoose", name: "Mongoose", level: "hard" },
  { slug: "anteater", name: "Giant Anteater", level: "hard" },
  { slug: "aardvark", name: "Aardvark", level: "hard" },
  { slug: "wildebeest", name: "Wildebeest", level: "hard" },
  { slug: "marmot", name: "Marmot", level: "hard" },
  { slug: "sifaka", name: "Sifaka", level: "hard" },
  { slug: "shoebill", name: "Shoebill", level: "hard" },
  // ===== IMPOSSIBLE (25) — flat plain surface (crop = one colour) or ultra-obscure =====
  { slug: "dolphin", name: "Dolphin", level: "impossible" },
  { slug: "manatee", name: "Manatee", level: "impossible" },
  { slug: "vaquita", name: "Vaquita", level: "impossible" },
  { slug: "narwhal", name: "Narwhal", level: "impossible" },
  { slug: "colugo", name: "Colugo", level: "impossible" },
  { slug: "olinguito", name: "Olinguito", level: "impossible" },
  { slug: "solenodon", name: "Solenodon", level: "impossible" },
  { slug: "numbat", name: "Numbat", level: "impossible" },
  { slug: "saiga", name: "Saiga Antelope", level: "impossible" },
  { slug: "kakapo", name: "Kakapo", level: "impossible" },
  { slug: "dhole", name: "Dhole", level: "impossible" },
  { slug: "binturong", name: "Binturong", level: "impossible" },
  { slug: "fossa", name: "Fossa", level: "impossible" },
  { slug: "markhor", name: "Markhor", level: "impossible" },
  { slug: "gerenuk", name: "Gerenuk", level: "impossible" },
  { slug: "gaur", name: "Gaur", level: "impossible" },
  { slug: "takin", name: "Takin", level: "impossible" },
  { slug: "babirusa", name: "Babirusa", level: "impossible" },
  { slug: "potoo", name: "Potoo", level: "impossible" },
  { slug: "maleo", name: "Maleo", level: "impossible" },
  { slug: "kagu", name: "Kagu", level: "impossible" },
  { slug: "zorilla", name: "Zorilla", level: "impossible" },
  { slug: "jerboa", name: "Jerboa", level: "impossible" },
  { slug: "quokka", name: "Quokka", level: "impossible" },
  { slug: "ayeaye", name: "Aye-aye", level: "impossible" },
];
