// E233 anime-emoji facts — one true <=70-char fact per anime, shown on reveal.
export const ANIME_EMOJI4_FACTS = {
  // EASY
  "bungo-stray-dogs": "Detectives use powers named after real literary authors.",
  "beastars": "A drama about predator and prey students at an animal high school.",
  "great-pretender": "A Japanese swindler joins a crew of international con artists.",
  "city-hunter": "A Shinjuku bodyguard-for-hire mixes comedy with sharpshooting.",
  "5-centimeters-per-second": "A Shinkai film about childhood sweethearts drifting apart.",
  "uma-musume-pretty-derby": "Racehorse spirits are reborn as schoolgirls who race.",
  "apothecary-diaries": "A clever apothecary solves mysteries inside an imperial palace.",
  "shangri-la-frontier": "A gamer who loves beating bad games tackles a legendary one.",
  "wind-breaker": "A lone delinquent joins a biker gang that protects its town.",
  "sakamoto-days": "A retired hitman keeps fighting while running a corner store.",
  "undead-unluck": "An immortal girl teams with a man cursed with terrible luck.",
  "blue-period": "A delinquent teen discovers a passion for oil painting.",
  "run-with-the-wind": "College misfits are recruited to run Japan's top relay race.",
  "major": "A long-running series tracking a boy's baseball career from childhood.",
  "cells-at-work": "Anthropomorphized blood cells work inside a human body.",
  "gantz": "The recently dead are forced to hunt aliens with sci-fi weapons.",
  "death-parade": "The newly dead play games in a bar to decide their afterlife.",
  "kaiju-no-8": "A cleanup-crew worker gains the power to transform into a kaiju.",
  "yuri-on-ice": "A figure skater is coached back to form by a Russian legend.",
  "toilet-bound-hanako-kun": "A boy befriends a ghost who haunts the school's third stall.",
  "wonder-egg-priority": "Grieving girls crack magical eggs to fight for a friend's revival.",
  "given": "A high schooler joins a band and falls for its guitarist.",
  "hyouka": "An energy-saving student is pulled into small school mysteries.",
  "kids-on-the-slope": "Two teens bond over jazz music in 1960s Japan.",
  "lucky-star": "A slice-of-life comedy following four otaku high-school girls.",

  // MEDIUM
  "maison-ikkoku": "A Rumiko Takahashi romance set in a Tokyo boarding house.",
  "urusei-yatsura": "A classic Takahashi comedy about a boy stuck with an alien girl.",
  "cutie-honey": "A pioneering android heroine who transforms to fight evil.",
  "the-garden-of-words": "A Shinkai short film about two strangers meeting in the rain.",
  "kotaro-lives-alone": "A tiny boy inexplicably lives alone in an apartment complex.",
  "kemono-friends": "Extinct and endangered animals become girls in a wildlife park.",
  "yona-of-the-dawn": "An exiled princess seeks four warriors to reclaim her throne.",
  "prison-school": "Five boys are jailed by a strict student council at their school.",
  "konohana-kitan": "Fox spirits work as staff at a hot-spring inn between worlds.",
  "mermaid-melody": "Mermaid princesses transform into idol singers to save the ocean.",
  "zombie-land-saga": "Reanimated girls from different eras are formed into an idol group.",
  "recovery-of-an-mmo-junkie": "An adult quits her job to play an MMO under a new avatar.",
  "barakamon": "A young calligrapher is exiled to a small island to reflect.",
  "silver-spoon": "A city boy enrolls at a rural agricultural high school.",
  "usagi-drop": "A bachelor raises his late grandfather's young illegitimate daughter.",
  "non-non-biyori": "A city girl adjusts to a tiny one-room countryside school.",
  "laid-back-camp": "High-school girls bond over solo and group camping trips.",
  "a-place-further-than-the-universe": "Four girls join an expedition ship bound for Antarctica.",
  "sonny-boy": "Students drift between dimensions after their school vanishes.",
  "odd-taxi": "An anthropomorphic walrus taxi driver gets tangled in a noir mystery.",
  "the-case-study-of-vanitas": "A vampire hunter seeks a cursed book said to cure vampirism.",
  "dance-dance-danseur": "A boy hides his love of ballet until a teacher spots his talent.",
  "tomo-chan-is-a-girl": "A tomboy tries to get her childhood best friend to see her as a girl.",
  "my-love-story": "A big, kind-hearted guy finally finds a girl who sees his true self.",
  "a-sign-of-affection": "A deaf student falls for a boy who learns sign language for her.",

  // HARD
  "michiko-and-hatchin": "A fugitive woman and a girl she frees ride across a Brazil-like land.",
  "samurai-flamenco": "A cosplayer's amateur superhero act becomes dangerously real.",
  "concrete-revolutio": "Superhumans clash with a government bureau that controls them.",
  "gatchaman-crowds": "A high schooler leads a social-network-powered hero team.",
  "flip-flappers": "Two girls jump through surreal parallel worlds via a pudding pod.",
  "space-patrol-luluco": "A girl officer patrols a city where anything can be illegal.",
  "star-driver": "A boy in a school uniform pilots mechs on an island of maidens.",
  "promare": "Firefighting mechs battle a burning terrorist organization.",
  "rozen-maiden": "A boy is drawn into battles between living antique dolls.",
  "shakugan-no-shana": "A flame-haired girl fights beings that devour human souls.",
  "a-certain-magical-index": "A boy with a power-erasing hand meets a nun carrying forbidden texts.",
  "accel-world": "An overweight boy finds a program letting him fight in hyperspeed.",
  "baka-and-test": "Students summon exam-score avatars to battle for better classrooms.",
  "arakawa-under-the-bridge": "A man saved from drowning must live under a bridge with eccentrics.",
  "martian-successor-nadesico": "A parody mecha crew fights aliens aboard a food-obsessed starship.",
  "tiger-and-bunny": "A veteran and rookie hero team up while sponsors cover their suits.",
  "gunslinger-girl": "Trained young girls are cybernetically enhanced into assassins.",
  "speed-grapher": "A war photographer gains a camera that can kill what it shoots.",
  "jormungand": "An arms dealer with a mysterious past travels the globe with her crew.",
  "hakumei-to-mikochi": "Two tiny forest-dwelling girls live among mushroom-shaped homes.",
  "spice-and-wolf": "A traveling merchant partners with a wolf goddess of the harvest.",
  "gunbuster": "Trainee pilots learn to fight aliens in giant robots to save Earth.",
  "kado-the-right-answer": "A giant cube-shaped alien craft offers humanity advanced technology.",
  "darling-in-the-franxx": "Paired boys and girls pilot mechs called Franxx against monsters.",
  "kabaneri-of-the-iron-fortress": "An armored train fights zombie-like Kabane to protect its passengers.",

  // IMPOSSIBLE
  "key-the-metal-idol": "An android girl must gain 30,000 friends to become human.",
  "jin-roh-the-wolf-brigade": "Armored police fight rebels in an alternate postwar Japan.",
  "wings-of-honneamise": "A young man joins a struggling nation's first space program.",
  "birdy-the-mighty": "An alien police officer fuses with a human host to fight crime.",
  "gasaraki": "A mecha pilot is entangled in ancient ritual and modern politics.",
  "this-corner-of-the-world": "A young bride survives World War II near Hiroshima.",
  "giovannis-island": "Brothers cope with a Soviet occupation of their Japanese island.",
  "colorful": "A dead soul is reincarnated into a boy's body to learn why he lived.",
  "patema-inverted": "A girl from an underground world has inverted gravity on the surface.",
  "a-letter-to-momo": "A grieving girl moves to a remote island and meets three yokai.",
  "the-anthem-of-the-heart": "A girl cursed to stay silent finds her voice through a school musical.",
  "kanon": "A boy returns to a snowy town and recalls old childhood promises.",
  "air": "A traveling puppeteer meets a girl tied to an ancient winged curse.",
  "true-tears": "A small-town teen drama unfolds around unspoken feelings and rivalry.",
  "bubblegum-crisis": "Mercenary women in powered armor fight rogue androids in future Tokyo.",
  "dirty-pair": "Two glamorous troubleshooter agents leave chaos wherever they go.",
  "giant-robo": "A boy pilots a giant robot for a global justice organization.",
  "nausicaa-of-the-valley-of-the-wind": "A princess protects her world from a toxic, insect-filled jungle.",
  "kimi-ni-todoke": "A shy girl nicknamed after a horror ghost slowly makes real friends.",
  "the-wind-rises": "Miyazaki's film follows a fictionalized WWII aircraft designer.",
  "earwig-and-the-witch": "Ghibli's first 3DCG film follows a girl raised by a witch.",
  "chobits": "A boy finds a human-like android girl discarded on the street.",
  "el-hazard": "Students are pulled into a fantasy world with a volcano-god threat.",
  "tenchi-muyo": "A boy's quiet life is upended by a string of alien princesses.",
  "video-girl-ai": "A girl steps out of a rental videotape to help a heartbroken boy.",
};
