// E233 «Guess the Anime by Emoji 4» — 100 anime · 25/tier · clue = plain Unicode emoji (mirrors E26 isEmoji rendering)
// VO: sfx/e233-<id>.wav
export const ANIME_EMOJI4 = [
  // ===== EASY (25) =====
  { id: "bungo-stray-dogs", title: "Bungo Stray Dogs", emojis: "🐕📖", level: "easy" },
  { id: "beastars", title: "Beastars", emojis: "🐺🐰", level: "easy" },
  { id: "great-pretender", title: "Great Pretender", emojis: "🃏✈", level: "easy" },
  { id: "city-hunter", title: "City Hunter", emojis: "🔫🕶", level: "easy" },
  { id: "5-centimeters-per-second", title: "5 Centimeters per Second", emojis: "🌸🚄", level: "easy" },
  { id: "uma-musume-pretty-derby", title: "Uma Musume Pretty Derby", emojis: "🐎👟", level: "easy" },
  { id: "apothecary-diaries", title: "The Apothecary Diaries", emojis: "💊📜", level: "easy" },
  { id: "shangri-la-frontier", title: "Shangri-La Frontier", emojis: "🎮🏔", level: "easy" },
  { id: "wind-breaker", title: "Wind Breaker", emojis: "💨🚲", level: "easy" },
  { id: "sakamoto-days", title: "Sakamoto Days", emojis: "🔫🏪", level: "easy" },
  { id: "undead-unluck", title: "Undead Unluck", emojis: "💀🍀", level: "easy" },
  { id: "blue-period", title: "Blue Period", emojis: "🎨🖌", level: "easy" },
  { id: "run-with-the-wind", title: "Run with the Wind", emojis: "🏃💨", level: "easy" },
  { id: "major", title: "Major", emojis: "⚾👦", level: "easy" },
  { id: "cells-at-work", title: "Cells at Work!", emojis: "🩸🦠", level: "easy" },
  { id: "gantz", title: "Gantz", emojis: "🛸💀", level: "easy" },
  { id: "death-parade", title: "Death Parade", emojis: "🎳💀", level: "easy" },
  { id: "kaiju-no-8", title: "Kaiju No. 8", emojis: "🧹👹", level: "easy" },
  { id: "yuri-on-ice", title: "Yuri on Ice", emojis: "⛸💕", level: "easy" },
  { id: "toilet-bound-hanako-kun", title: "Toilet-Bound Hanako-kun", emojis: "🚪👻", level: "easy" },
  { id: "wonder-egg-priority", title: "Wonder Egg Priority", emojis: "🥚😢", level: "easy" },
  { id: "given", title: "Given", emojis: "🎸💕", level: "easy" },
  { id: "hyouka", title: "Hyouka", emojis: "🌸🔍", level: "easy" },
  { id: "kids-on-the-slope", title: "Kids on the Slope", emojis: "🎹🥁", level: "easy" },
  { id: "lucky-star", title: "Lucky Star", emojis: "🍀⭐", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "maison-ikkoku", title: "Maison Ikkoku", emojis: "🏠💕", level: "medium" },
  { id: "urusei-yatsura", title: "Urusei Yatsura", emojis: "👽💍", level: "medium" },
  { id: "cutie-honey", title: "Cutie Honey", emojis: "🍯🗡", level: "medium" },
  { id: "the-garden-of-words", title: "The Garden of Words", emojis: "🌧☂", level: "medium" },
  { id: "kotaro-lives-alone", title: "Kotaro Lives Alone", emojis: "🏠👦", level: "medium" },
  { id: "kemono-friends", title: "Kemono Friends", emojis: "🦁👧", level: "medium" },
  { id: "yona-of-the-dawn", title: "Yona of the Dawn", emojis: "🏹👸", level: "medium" },
  { id: "prison-school", title: "Prison School", emojis: "🔒🏫", level: "medium" },
  { id: "konohana-kitan", title: "Konohana Kitan", emojis: "♨🦊", level: "medium" },
  { id: "mermaid-melody", title: "Mermaid Melody", emojis: "🧜🎤", level: "medium" },
  { id: "zombie-land-saga", title: "Zombie Land Saga", emojis: "🧟🎤", level: "medium" },
  { id: "recovery-of-an-mmo-junkie", title: "Recovery of an MMO Junkie", emojis: "🎮👩", level: "medium" },
  { id: "barakamon", title: "Barakamon", emojis: "🖌🏝", level: "medium" },
  { id: "silver-spoon", title: "Silver Spoon", emojis: "🐄🌾", level: "medium" },
  { id: "usagi-drop", title: "Usagi Drop", emojis: "🐰👶", level: "medium" },
  { id: "non-non-biyori", title: "Non Non Biyori", emojis: "🌾👧", level: "medium" },
  { id: "laid-back-camp", title: "Laid-Back Camp", emojis: "⛺🔥", level: "medium" },
  { id: "a-place-further-than-the-universe", title: "A Place Further Than the Universe", emojis: "🧊🚢", level: "medium" },
  { id: "sonny-boy", title: "Sonny Boy", emojis: "🏝🌀", level: "medium" },
  { id: "odd-taxi", title: "Odd Taxi", emojis: "🚕🦫", level: "medium" },
  { id: "the-case-study-of-vanitas", title: "The Case Study of Vanitas", emojis: "🧛📕", level: "medium" },
  { id: "dance-dance-danseur", title: "Dance Dance Danseur", emojis: "🩰🕺", level: "medium" },
  { id: "tomo-chan-is-a-girl", title: "Tomo-chan Is a Girl!", emojis: "🥋💕", level: "medium" },
  { id: "my-love-story", title: "My Love Story!!", emojis: "💪💘", level: "medium" },
  { id: "a-sign-of-affection", title: "A Sign of Affection", emojis: "🤟💗", level: "medium" },

  // ===== HARD (25) =====
  { id: "michiko-and-hatchin", title: "Michiko & Hatchin", emojis: "🏍👧", level: "hard" },
  { id: "samurai-flamenco", title: "Samurai Flamenco", emojis: "🦸🎭", level: "hard" },
  { id: "concrete-revolutio", title: "Concrete Revolutio", emojis: "🦸⚖", level: "hard" },
  { id: "gatchaman-crowds", title: "Gatchaman Crowds", emojis: "🦸📱", level: "hard" },
  { id: "flip-flappers", title: "Flip Flappers", emojis: "🌀🍮", level: "hard" },
  { id: "space-patrol-luluco", title: "Space Patrol Luluco", emojis: "🚨👧", level: "hard" },
  { id: "star-driver", title: "Star Driver", emojis: "🌊🤖", level: "hard" },
  { id: "promare", title: "Promare", emojis: "🔥🚀", level: "hard" },
  { id: "rozen-maiden", title: "Rozen Maiden", emojis: "🎎🎀", level: "hard" },
  { id: "shakugan-no-shana", title: "Shakugan no Shana", emojis: "🔥⚔", level: "hard" },
  { id: "a-certain-magical-index", title: "A Certain Magical Index", emojis: "🔮📚", level: "hard" },
  { id: "accel-world", title: "Accel World", emojis: "🎮⚡", level: "hard" },
  { id: "baka-and-test", title: "Baka and Test", emojis: "📝👊", level: "hard" },
  { id: "arakawa-under-the-bridge", title: "Arakawa Under the Bridge", emojis: "🌉👩", level: "hard" },
  { id: "martian-successor-nadesico", title: "Martian Successor Nadesico", emojis: "🚀😼", level: "hard" },
  { id: "tiger-and-bunny", title: "Tiger & Bunny", emojis: "🐯🐰", level: "hard" },
  { id: "gunslinger-girl", title: "Gunslinger Girl", emojis: "🔫👧", level: "hard" },
  { id: "speed-grapher", title: "Speed Grapher", emojis: "📷💥", level: "hard" },
  { id: "jormungand", title: "Jormungand", emojis: "🔫✈", level: "hard" },
  { id: "hakumei-to-mikochi", title: "Hakumei to Mikochi", emojis: "🍄🌲", level: "hard" },
  { id: "spice-and-wolf", title: "Spice and Wolf", emojis: "🐺🌾", level: "hard" },
  { id: "gunbuster", title: "Gunbuster", emojis: "🤖👊", level: "hard" },
  { id: "kado-the-right-answer", title: "Kado: The Right Answer", emojis: "🛸🤝", level: "hard" },
  { id: "darling-in-the-franxx", title: "Darling in the Franxx", emojis: "🤖💗", level: "hard" },
  { id: "kabaneri-of-the-iron-fortress", title: "Kabaneri of the Iron Fortress", emojis: "🚂🧟", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "key-the-metal-idol", title: "Key the Metal Idol", emojis: "🤖🎤", level: "impossible" },
  { id: "jin-roh-the-wolf-brigade", title: "Jin-Roh: The Wolf Brigade", emojis: "🐺🎭", level: "impossible" },
  { id: "wings-of-honneamise", title: "Wings of Honnêamise", emojis: "🚀🕊", level: "impossible" },
  { id: "birdy-the-mighty", title: "Birdy the Mighty", emojis: "👽👮", level: "impossible" },
  { id: "gasaraki", title: "Gasaraki", emojis: "🤖⛩", level: "impossible" },
  { id: "this-corner-of-the-world", title: "In This Corner of the World", emojis: "🎨💣", level: "impossible" },
  { id: "giovannis-island", title: "Giovanni's Island", emojis: "🏝👦", level: "impossible" },
  { id: "colorful", title: "Colorful", emojis: "👻🚲", level: "impossible" },
  { id: "patema-inverted", title: "Patema Inverted", emojis: "🕳👧", level: "impossible" },
  { id: "a-letter-to-momo", title: "A Letter to Momo", emojis: "👹✉", level: "impossible" },
  { id: "the-anthem-of-the-heart", title: "The Anthem of the Heart", emojis: "🥚🎤", level: "impossible" },
  { id: "kanon", title: "Kanon", emojis: "❄👧", level: "impossible" },
  { id: "air", title: "Air", emojis: "🪽👧", level: "impossible" },
  { id: "true-tears", title: "True Tears", emojis: "💧👧", level: "impossible" },
  { id: "bubblegum-crisis", title: "Bubblegum Crisis", emojis: "🤖🌃", level: "impossible" },
  { id: "dirty-pair", title: "Dirty Pair", emojis: "💥🕶", level: "impossible" },
  { id: "giant-robo", title: "Giant Robo", emojis: "🤖⚙", level: "impossible" },
  { id: "nausicaa-of-the-valley-of-the-wind", title: "Nausicaä of the Valley of the Wind", emojis: "🦋🌬", level: "impossible" },
  { id: "kimi-ni-todoke", title: "Kimi ni Todoke", emojis: "👻💌", level: "impossible" },
  { id: "the-wind-rises", title: "The Wind Rises", emojis: "✈👓", level: "impossible" },
  { id: "earwig-and-the-witch", title: "Earwig and the Witch", emojis: "🪄🐈", level: "impossible" },
  { id: "chobits", title: "Chobits", emojis: "💻👧", level: "impossible" },
  { id: "el-hazard", title: "El-Hazard: The Magnificent World", emojis: "🗡🌋", level: "impossible" },
  { id: "tenchi-muyo", title: "Tenchi Muyo!", emojis: "👽🚀", level: "impossible" },
  { id: "video-girl-ai", title: "Video Girl Ai", emojis: "📼👧", level: "impossible" },
];
