// E238 «Guess the Animal by Emoji» — one verified TRUE fact per id, <=70 chars
export const ANIMAL_EMOJI6_FACTS = {
  "opossum": "North America's only marsupial; plays dead when threatened.",
  "roadrunner": "Can sprint up to 20 mph and rarely bothers to fly.",
  "cockatiel": "A small cockatoo that whistles tunes and mimics sounds.",
  "budgerigar": "Wild budgies fly in huge flocks across Australia's outback.",
  "lovebird": "Small African parrots that often perch in bonded pairs.",
  "bearded-dragon": "Puffs its spiky throat pouch dark when threatened.",
  "gila-monster": "One of the few venomous lizards, native to the US Southwest.",
  "nile-crocodile": "Africa's largest crocodile; can grow over 5 meters long.",
  "caiman": "Smaller cousin of alligators, found across Central/South America.",
  "coral-snake": "Its red-yellow-black bands warn of potent venom.",
  "cottonmouth": "Opens its mouth wide to show a white lining as a threat.",
  "copperhead": "Named for its coppery, hourglass-patterned head.",
  "cane-toad": "Secretes toxin strong enough to kill predators that bite it.",
  "box-turtle": "Can pull its shell shut like a hinged box.",
  "dung-beetle": "Rolls dung into balls and navigates using the Milky Way.",
  "cicada": "Some broods stay underground for 17 years before emerging.",
  "locust": "Swarms can contain billions and strip fields bare.",
  "red-kangaroo": "Largest marsupial; can leap over 8 meters in one bound.",
  "tammar-wallaby": "Small wallaby that can survive drinking seawater.",
  "common-brushtail-possum": "Aussie marsupial that dens in tree hollows at night.",
  "praying-mantis": "Rotates its head almost 180 degrees to scan for prey.",
  "stag-beetle": "Males use huge jaws shaped like antlers to wrestle rivals.",
  "rhinoceros-beetle": "Can lift objects 850 times its own body weight.",
  "bee-eater": "Rubs bees against branches to remove the stinger before eating.",
  "osprey": "Dives feet-first into water to snatch fish with its talons.",
  "chuckwalla": "Wedges into rock crevices and inflates its body to stay stuck.",
  "anole": "Flashes a colorful throat fan called a dewlap to signal.",
  "milk-snake": "Harmless mimic that copies venomous coral snake colors.",
  "bushmaster": "Longest venomous snake in the Americas, up to 3 meters.",
  "tegu": "Large lizard that can raise its body temperature like a mammal.",
  "legless-lizard": "Looks like a snake but has eyelids and ear openings.",
  "softshell-turtle": "Has a flat, leathery shell instead of hard scutes.",
  "spring-peeper": "Tiny frog whose chorus signals the arrival of spring.",
  "surinam-toad": "Eggs hatch out of pits embedded in the mother's back skin.",
  "goliath-frog": "World's largest frog; can weigh over 3 kilograms.",
  "mudpuppy": "Aquatic salamander that keeps feathery external gills for life.",
  "marbled-salamander": "Lays eggs on land, guarding them until autumn rains flood the nest.",
  "basilisk-lizard": "Sprints across water on its hind legs to escape predators.",
  "flying-snake": "Flattens its body and glides between trees.",
  "earwig": "Uses pincers on its tail for defense, not for stinging ears.",
  "weevil": "Beetle with an elongated snout used to bore into plants.",
  "katydid": "Its wings look almost exactly like green leaves.",
  "damselfly": "Folds its wings along its body when resting, unlike dragonflies.",
  "turaco": "Only bird group with true green and red pigment in feathers.",
  "trogon": "Relative of the resplendent quetzal with iridescent plumage.",
  "oxpecker": "Perches on rhinos and buffalo to pick off ticks.",
  "rhea": "South America's largest bird; males alone incubate the eggs.",
  "frogmouth": "Freezes stiff at dawn to mimic a broken tree branch.",
  "umbrellabird": "Male has an umbrella-like crest and an inflatable throat pouch.",
  "honeyguide": "Leads humans to beehives, then eats the leftover wax.",
  "assassin-bug": "Ambushes prey and injects venom that liquefies its insides.",
  "antlion": "Larva digs a pit trap to snare ants that slip in.",
  "silverfish": "Wingless insect named for its silvery, fish-like wiggle.",
  "leafhopper": "Coats itself in a waxy substance and jumps to escape.",
  "click-beetle": "Snaps its body with a loud click to flip itself upright.",
  "glowworm": "Larva glows to lure prey into sticky silk snare threads.",
  "tiger-beetle": "One of the fastest runners relative to body size on Earth.",
  "mayfly": "Adults often live for less than 24 hours after hatching.",
  "water-strider": "Uses surface tension to walk on top of still water.",
  "giant-water-bug": "Male carries the fertilized eggs glued to its own back.",
  "bittern": "Freezes with its bill pointed up to blend into reeds.",
  "spoonbill": "Sweeps its flat, spoon-shaped bill through water to feed.",
  "frigatebird": "Male inflates a huge red throat pouch to attract mates.",
  "gannet": "Dives from great heights, hitting the water at high speed.",
  "tern": "Many tern species migrate huge distances between hemispheres.",
  "skua": "Chases other seabirds mid-air to steal their catch.",
  "razorbill": "Black-and-white seabird with a thick, blade-shaped bill.",
  "cormorant": "Spreads its wings to dry them after diving for fish.",
  "loon": "Its eerie call echoes across northern lakes at night.",
  "grebe": "Chicks often ride on a parent's back while it swims.",
  "coot": "Has oddly lobed toes instead of webbed feet for swimming.",
  "bustard": "One of the heaviest birds still capable of flight.",
  "nightjar": "Nocturnal bird with a camouflage pattern like tree bark.",
  "potoo": "Perches upright and motionless to look like a broken stump.",
  "harrier": "Hunts low over open fields with a wobbling glide.",
  "rock-wallaby": "Bounds across steep, rocky outcrops with remarkable grip.",
  "painted-turtle": "Has bright red and yellow stripes along its shell edges.",
  "wood-frog": "Freezes solid in winter and thaws back to life in spring.",
  "fire-salamander": "Bold yellow-black pattern warns predators of its toxins.",
  "vine-snake": "Slender green snake that resembles a hanging vine.",
  "antechinus": "Males mate frantically for weeks, then often die of exhaustion.",
  "striped-possum": "Has skunk-like stripes and a long tongue for eating grubs.",
  "monito-del-monte": "Ancient Chilean marsupial, closer kin to Australian ones.",
  "water-opossum": "Only marsupial adapted to a fully aquatic lifestyle.",
  "oilbird": "Nocturnal bird that echolocates like a bat inside caves.",
  "swift": "Can stay airborne for months without ever landing.",
  "sunbird": "Its iridescent feathers shift color depending on the light.",
  "bowerbird": "Male builds and decorates a bower to court females.",
  "fairywren": "Tiny songbird known for its cocked, upright tail.",
  "jacamar": "Catches insects mid-air with a long, needle-like bill.",
  "motmot": "Swings its racket-tipped tail like a pendulum.",
  "tody": "Tiny bright-green bird found only in the Caribbean.",
  "roller": "Named for its tumbling, acrobatic courtship flight display.",
  "caracara": "Ground-walking falcon relative that scavenges carrion.",
  "shrike": "Impales prey on thorns to store food, earning 'butcherbird'.",
  "nuthatch": "One of few birds that can climb down tree trunks headfirst.",
  "pukeko": "Purple swamphen with huge feet for walking on wetland plants.",
  "tinamou": "Lays glossy, jewel-like eggs in shades like turquoise.",
  "goshawk": "Fierce forest hawk that ambushes prey through dense trees.",
  "tiger-salamander": "Largest land salamander species in North America.",
};
