// E222 «Guess the Animal by Emoji» — one true, ≤70-char fact per item id
export const ANIMAL_EMOJI5_FACTS = {
  "chinchilla": "Chinchilla fur is so dense that fleas cannot live in it.",
  "porcupine": "A porcupine has around 30,000 quills covering its body.",
  "groundhog": "Groundhogs whistle loudly when startled, hence whistle-pig.",
  "prairie-dog": "Prairie dogs have distinct alarm calls for different predators.",
  "puffin": "Puffins can hold over a dozen small fish in their beak at once.",
  "kookaburra": "The kookaburra's call sounds like loud, echoing human laughter.",
  "water-buffalo": "Water buffalo wallow in mud and rivers to cool off all day.",
  "guinea-fowl": "Guinea fowl eat ticks and are used as natural pest control.",
  "bald-eagle": "Bald eagles build the largest nests of any North American bird.",
  "snowy-owl": "Snowy owls hunt during the day, unlike most owl species.",
  "cardinal": "Only male cardinals are bright red; females are soft brown.",
  "blue-jay": "Blue jays are not truly blue; their feathers just scatter light.",
  "robin": "A robin can raise up to three broods of chicks in one season.",
  "mockingbird": "A mockingbird can learn and mimic over 200 different songs.",
  "dragonfly": "Dragonflies can fly in six directions, including backwards.",
  "slug": "A slug's slime lets it glide over a sharp razor blade unharmed.",
  "centipede": "Despite the name, no centipede species has exactly 100 legs.",
  "nightingale": "Nightingales sing their loudest songs late at night when unpaired.",
  "barn-swallow": "Barn swallows build cup-shaped mud nests under building eaves.",
  "starling": "Starlings form huge swirling flocks called murmurations.",
  "wren": "The tiny wren sings one of the loudest songs per body size.",
  "finch": "Darwin's finches helped inspire his theory of natural selection.",
  "bloodhound": "A bloodhound's nose holds about 300 million scent receptors.",
  "zebu": "Zebu cattle have a distinctive muscular hump above their shoulders.",
  "highland-cow": "Highland cows grow a long double coat to survive cold winters.",
  "vervet-monkey": "Vervet monkeys use different alarm calls for different predators.",
  "patas-monkey": "Patas monkeys can sprint faster than 30 miles per hour.",
  "ring-tailed-lemur": "Ring-tailed lemurs sunbathe by sitting upright facing the sun.",
  "sifaka": "Sifakas cross open ground with sideways leaping hops.",
  "bush-baby": "Bush babies have huge eyes and can leap 6 feet between branches.",
  "fruit-bat": "Fruit bats navigate mostly by sight and smell, not echolocation.",
  "marten": "Pine martens can rotate their ankles to climb down trees headfirst.",
  "stoat": "A stoat's brown coat turns pure white in winter, called ermine.",
  "mink": "Minks are semi-aquatic and have partially webbed feet.",
  "polecat": "Polecats spray a strong musky odor when they feel threatened.",
  "coati": "Coatis hold their long ringed tails straight up while walking.",
  "ringtail": "Ringtails can rotate their hind feet 180 degrees to climb down.",
  "jaguarundi": "Jaguarundis hunt by day, unlike most wild cat species.",
  "sand-cat": "Sand cats have furry paws that protect them from hot desert sand.",
  "pallas-cat": "Pallas's cats have the densest fur of any cat species.",
  "muntjac": "Muntjac deer are nicknamed barking deer for their dog-like call.",
  "chital": "Chital deer keep their white spots into adulthood, unlike most deer.",
  "sambar-deer": "Sambar deer are among the largest deer species in Asia.",
  "pudu": "The pudú is the world's smallest deer species.",
  "nilgai": "Nilgai means blue bull, named for the male's blue-grey coat.",
  "blackbuck": "Male blackbucks can leap nearly 8 feet high to escape predators.",
  "blesbok": "Blesboks have a white blaze marking that runs down their face.",
  "steenbok": "Steenboks bury their dung to hide their scent from predators.",
  "roan-antelope": "Roan antelope are among Africa's largest antelope species.",
  "sable-antelope": "Male sable antelope can grow horns over 5 feet long.",
  "secretary-bird": "Secretary birds stomp venomous snakes to death with their feet.",
  "marbled-cat": "The marbled cat has one of the longest tails relative to its body.",
  "geoffroys-cat": "Geoffroy's cats are strong swimmers that often hunt in water.",
  "kodkod": "The kodkod is South America's smallest wild cat species.",
  "andean-cat": "Andean cats live above 13,000 feet in the high Andes mountains.",
  "bat-eared-fox": "Bat-eared foxes use their giant ears to find insects underground.",
  "cape-fox": "The Cape fox is the only true fox species native to South Africa.",
  "kit-fox": "Kit foxes get nearly all their water from the prey they eat.",
  "african-wild-dog": "African wild dogs have a hunting success rate near 80 percent.",
  "ethiopian-wolf": "The Ethiopian wolf is Africa's rarest and most endangered carnivore.",
  "side-striped-jackal": "Side-striped jackals are mostly silent, unlike other jackals.",
  "fisher": "Fishers are one of the few predators that regularly kill porcupines.",
  "olingo": "Olingos are nocturnal and rarely leave the rainforest canopy.",
  "cacomistle": "Cacomistles are shy, nocturnal relatives of the raccoon.",
  "bettong": "Bettongs carry nesting material coiled up in their tails.",
  "bandicoot": "Bandicoots dig small cone-shaped holes while foraging for insects.",
  "tree-kangaroo": "Tree kangaroos can rotate their ankles, unlike ground kangaroos.",
  "pademelon": "Pademelons are small, shy relatives of the kangaroo and wallaby.",
  "cuscus": "Cuscuses have a strong prehensile tail used like an extra hand.",
  "takahe": "The takahē was believed extinct for 50 years before its rediscovery.",
  "kagu": "The nearly flightless kagu is New Caledonia's national bird.",
  "weka": "Wekas are curious flightless birds known for stealing shiny objects.",
  "sunbittern": "Sunbitterns flash huge eye-like wing patterns to startle predators.",
  "jabiru": "The jabiru stork has a massive bill and stands nearly 5 feet tall.",
  "saddle-billed-stork": "Saddle-billed storks have a bright red, black and yellow bill.",
  "marabou-stork": "Marabou storks are scavengers nicknamed the undertaker bird.",
  "musky-rat-kangaroo": "The musky rat-kangaroo is the smallest living kangaroo relative.",
  "kultarr": "Kultarrs can leap over a foot high while hunting insects at night.",
  "mulgara": "Mulgaras are carnivorous marsupials that rarely need to drink water.",
  "dunnart": "Dunnarts are mouse-sized marsupial hunters found across Australia.",
  "feathertail-glider": "The feathertail glider is the world's smallest gliding mammal.",
  "honey-possum": "Honey possums feed only on nectar and pollen, not insects.",
  "leadbeaters-possum": "Leadbeater's possum is the official animal emblem of Victoria.",
  "bushbuck": "Bushbucks freeze and lie flat on the ground to avoid predators.",
  "suni": "The suni antelope stands barely over a foot tall at the shoulder.",
  "dibatag": "The dibatag curls its tail over its back like a squirrel.",
  "beira": "The beira antelope survives on moisture from plants alone.",
  "royal-antelope": "The royal antelope is the world's smallest hoofed mammal.",
  "four-horned-antelope": "The four-horned antelope is the only bovid with four horns.",
  "chinese-water-deer": "Chinese water deer grow fangs instead of antlers.",
  "tufted-deer": "Tufted deer have small fangs and a dark tuft of hair on the head.",
  "visayan-warty-pig": "Visayan warty pigs grow a dramatic mohawk-like mane when breeding.",
  "red-river-hog": "Red river hogs have tufted white ears and a bright reddish coat.",
  "giant-forest-hog": "The giant forest hog is Africa's largest wild pig species.",
  "pygmy-hippopotamus": "Pygmy hippos are mostly solitary, unlike their river-dwelling cousins.",
  "falanouc": "The falanouc is a rare Madagascar carnivore that mainly eats worms.",
  "ring-tailed-vontsira": "The ring-tailed vontsira is Madagascar's national animal.",
  "giant-otter-shrew": "The giant otter shrew swims using its long, flattened tail.",
  "cape-golden-mole": "Cape golden moles have iridescent fur and no visible eyes.",
  "marsupial-mole": "The marsupial mole swims through sand and is almost blind.",
};
