// E249 «Guess the Anime by Emoji» — 5th anime-emoji episode — 100 anime series · 25/tier · clue = plain Unicode emoji (mirrors E26 isEmoji rendering)
// VO: sfx/e249-<id>.wav
export const ANIME_EMOJI5 = [
  // ===== EASY (25) =====
  { id: "dragon-ball-gt", title: "Dragon Ball GT", emojis: "🐉🌌", level: "easy" },
  { id: "fullmetal-alchemist-brotherhood", title: "Fullmetal Alchemist: Brotherhood", emojis: "⚗🦾", level: "easy" },
  { id: "mobile-suit-gundam-seed", title: "Mobile Suit Gundam SEED", emojis: "🤖🌱", level: "easy" },
  { id: "love-live", title: "Love Live!", emojis: "🎤⭐", level: "easy" },
  { id: "aggretsuko", title: "Aggretsuko", emojis: "🦝😤", level: "easy" },
  { id: "grand-blue", title: "Grand Blue", emojis: "🤿🍺", level: "easy" },
  { id: "katekyo-hitman-reborn", title: "Katekyo Hitman Reborn!", emojis: "👶🔫", level: "easy" },
  { id: "world-trigger", title: "World Trigger", emojis: "🌍🔫", level: "easy" },
  { id: "another", title: "Another", emojis: "🎒💀", level: "easy" },
  { id: "ao-ashi", title: "Ao Ashi", emojis: "⚽🦵", level: "easy" },
  { id: "eyeshield-21", title: "Eyeshield 21", emojis: "🏈👓", level: "easy" },
  { id: "ao-haru-ride", title: "Ao Haru Ride", emojis: "🚲💙", level: "easy" },
  { id: "domestic-girlfriend", title: "Domestic Girlfriend", emojis: "🏠💔", level: "easy" },
  { id: "blue-box", title: "Blue Box", emojis: "🏸🏃", level: "easy" },
  { id: "yashahime", title: "Yashahime: Princess Half-Demon", emojis: "👹👑", level: "easy" },
  { id: "the-eminence-in-shadow", title: "The Eminence in Shadow", emojis: "🕶🌑", level: "easy" },
  { id: "ascendance-of-a-bookworm", title: "Ascendance of a Bookworm", emojis: "📚🐛", level: "easy" },
  { id: "the-melancholy-of-haruhi-suzumiya", title: "The Melancholy of Haruhi Suzumiya", emojis: "😐🌀", level: "easy" },
  { id: "mobile-suit-gundam-wing", title: "Mobile Suit Gundam Wing", emojis: "🤖🕊", level: "easy" },
  { id: "the-saga-of-tanya-the-evil", title: "The Saga of Tanya the Evil", emojis: "👧✈", level: "easy" },
  { id: "say-i-love-you", title: "Say I Love You", emojis: "💬❤", level: "easy" },
  { id: "grendizer", title: "Grendizer", emojis: "🛸🌋", level: "easy" },
  { id: "future-boy-conan", title: "Future Boy Conan", emojis: "🏝👦", level: "easy" },
  { id: "devilman", title: "Devilman", emojis: "😈🩸", level: "easy" },
  { id: "idolmaster", title: "Idolmaster", emojis: "💃🎬", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "cyborg-009", title: "Cyborg 009", emojis: "🤖🔢", level: "medium" },
  { id: "gatchaman", title: "Gatchaman", emojis: "🦅🎽", level: "medium" },
  { id: "porco-rosso", title: "Porco Rosso", emojis: "🐷✈", level: "medium" },
  { id: "grimgar-of-fantasy-and-ash", title: "Grimgar of Fantasy and Ash", emojis: "⚔🌫", level: "medium" },
  { id: "princess-tutu", title: "Princess Tutu", emojis: "🩰🦢", level: "medium" },
  { id: "record-of-lodoss-war", title: "Record of Lodoss War", emojis: "🐉🛡", level: "medium" },
  { id: "beck-mongolian-chop-squad", title: "Beck: Mongolian Chop Squad", emojis: "🎸🐕", level: "medium" },
  { id: "vivy-fluorite-eyes-song", title: "Vivy: Fluorite Eye's Song", emojis: "🤖🎵", level: "medium" },
  { id: "plastic-memories", title: "Plastic Memories", emojis: "🤖⏳", level: "medium" },
  { id: "junji-ito-collection", title: "Junji Ito Collection", emojis: "🌀😱", level: "medium" },
  { id: "time-of-eve", title: "Time of Eve", emojis: "☕🤖", level: "medium" },
  { id: "remi-nobodys-boy", title: "Remi, Nobody's Boy", emojis: "🐕🎻", level: "medium" },
  { id: "children-who-chase-lost-voices", title: "Children Who Chase Lost Voices", emojis: "🕳🎶", level: "medium" },
  { id: "dr-slump", title: "Dr. Slump", emojis: "🤖👧", level: "medium" },
  { id: "ah-my-goddess", title: "Ah! My Goddess", emojis: "👼💍", level: "medium" },
  { id: "aquarion", title: "Aquarion", emojis: "🤖❤", level: "medium" },
  { id: "mieruko-chan", title: "Mieruko-chan", emojis: "👁👻", level: "medium" },
  { id: "jigoku-shoujo", title: "Jigoku Shoujo", emojis: "👧🔥", level: "medium" },
  { id: "pop-team-epic", title: "Pop Team Epic", emojis: "🤪💥", level: "medium" },
  { id: "cromartie-high-school", title: "Cromartie High School", emojis: "🎓🤖", level: "medium" },
  { id: "excel-saga", title: "Excel Saga", emojis: "🐕🌍", level: "medium" },
  { id: "flying-witch", title: "Flying Witch", emojis: "🧹🌿", level: "medium" },
  { id: "ookiku-furikabutte", title: "Ookiku Furikabutte", emojis: "⚾🧤", level: "medium" },
  { id: "giant-killing", title: "Giant Killing", emojis: "⚽👑", level: "medium" },
  { id: "kimagure-orange-road", title: "Kimagure Orange Road", emojis: "🍊✨", level: "medium" },

  // ===== HARD (25) =====
  { id: "cats-eye", title: "Cat's Eye", emojis: "🎨🐈", level: "hard" },
  { id: "wedding-peach", title: "Wedding Peach", emojis: "💐👰", level: "hard" },
  { id: "ojamajo-doremi", title: "Ojamajo Doremi", emojis: "🪄🔔", level: "hard" },
  { id: "vampire-princess-miyu", title: "Vampire Princess Miyu", emojis: "🧛🌙", level: "hard" },
  { id: "getter-robo", title: "Getter Robo", emojis: "🤖🚀", level: "hard" },
  { id: "space-runaway-ideon", title: "Space Runaway Ideon", emojis: "🛸💥", level: "hard" },
  { id: "armored-trooper-votoms", title: "Armored Trooper Votoms", emojis: "🤖🪖", level: "hard" },
  { id: "dancouga", title: "Dancouga", emojis: "🦁🤖", level: "hard" },
  { id: "aim-for-the-ace", title: "Aim for the Ace!", emojis: "🎾⭐", level: "hard" },
  { id: "candy-candy", title: "Candy Candy", emojis: "🌻💔", level: "hard" },
  { id: "combattler-v", title: "Combattler V", emojis: "🤖⚡", level: "hard" },
  { id: "golion", title: "GoLion", emojis: "🦁🔗", level: "hard" },
  { id: "belle-and-sebastian", title: "Belle and Sebastian", emojis: "🐕⛰", level: "hard" },
  { id: "heidi-girl-of-the-alps", title: "Heidi, Girl of the Alps", emojis: "🐐⛰", level: "hard" },
  { id: "3000-leagues-in-search-of-mother", title: "3000 Leagues in Search of Mother", emojis: "🚢💌", level: "hard" },
  { id: "ronia-the-robbers-daughter", title: "Ronia, the Robber's Daughter", emojis: "🗡🌲", level: "hard" },
  { id: "sayonara-zetsubou-sensei", title: "Sayonara, Zetsubou-Sensei", emojis: "😔🌳", level: "hard" },
  { id: "perman", title: "Perman", emojis: "🦸✨", level: "hard" },
  { id: "obake-no-q-taro", title: "Obake no Q-Taro", emojis: "👻🍔", level: "hard" },
  { id: "groizer-x", title: "Groizer X", emojis: "🤖🌟", level: "hard" },
  { id: "toward-the-terra", title: "Toward the Terra", emojis: "🌍✨", level: "hard" },
  { id: "galaxy-angel", title: "Galaxy Angel", emojis: "👼🚀", level: "hard" },
  { id: "his-and-her-circumstances", title: "His and Her Circumstances", emojis: "📖💘", level: "hard" },
  { id: "genshiken", title: "Genshiken", emojis: "🎮📚", level: "hard" },
  { id: "basilisk", title: "Basilisk", emojis: "🥷🐍", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "samurai-7", title: "Samurai 7", emojis: "🌾⚔", level: "impossible" },
  { id: "sengoku-basara", title: "Sengoku Basara", emojis: "⚔🎏", level: "impossible" },
  { id: "kekkaishi", title: "Kekkaishi", emojis: "🛡🏠", level: "impossible" },
  { id: "zambot-3", title: "Zambot 3", emojis: "🤖😢", level: "impossible" },
  { id: "attacker-you", title: "Attacker You!", emojis: "🏐👊", level: "impossible" },
  { id: "trider-g7", title: "Trider G7", emojis: "🤖🎒", level: "impossible" },
  { id: "story-of-perrine", title: "The Story of Perrine", emojis: "🚶🐕", level: "impossible" },
  { id: "anne-of-green-gables", title: "Anne of Green Gables", emojis: "🧡👧", level: "impossible" },
  { id: "tico-of-the-seven-seas", title: "Tico of the Seven Seas", emojis: "🐬⛵", level: "impossible" },
  { id: "a-dog-of-flanders", title: "A Dog of Flanders", emojis: "🐕🎨", level: "impossible" },
  { id: "rascal-the-raccoon", title: "Rascal the Raccoon", emojis: "🦝🌳", level: "impossible" },
  { id: "peter-pan-no-bouken", title: "Peter Pan no Bouken", emojis: "🧚⏰", level: "impossible" },
  { id: "ai-no-wakakusa-monogatari", title: "Ai no Wakakusa Monogatari", emojis: "📗👧", level: "impossible" },
  { id: "meiken-lassie", title: "Meiken Lassie", emojis: "🐕🐑", level: "impossible" },
  { id: "adventures-of-tom-sawyer", title: "The Adventures of Tom Sawyer", emojis: "🛶🌊", level: "impossible" },
  { id: "nils-fushigi-na-tabi", title: "The Wonderful Adventures of Nils", emojis: "🪿🧒", level: "impossible" },
  { id: "trapp-family-story", title: "Trapp Family Story", emojis: "🎵🏔", level: "impossible" },
  { id: "little-lord-fauntleroy", title: "Little Lord Fauntleroy", emojis: "🎩👦", level: "impossible" },
  { id: "princess-sarah", title: "Princess Sarah", emojis: "👑😢", level: "impossible" },
  { id: "sinbad-no-bouken-1975", title: "Sinbad no Bouken", emojis: "🌊⚓", level: "impossible" },
  { id: "cinderella-monogatari", title: "Cinderella Monogatari", emojis: "👠🎃", level: "impossible" },
  { id: "little-match-girl", title: "The Little Match Girl", emojis: "🔥🕯", level: "impossible" },
  { id: "kaiketsu-zorro", title: "Kaiketsu Zorro", emojis: "🗡🖤", level: "impossible" },
  { id: "gigantor", title: "Gigantor", emojis: "🤖📡", level: "impossible" },
  { id: "alakazam-the-great", title: "Alakazam the Great", emojis: "🐒🌪", level: "impossible" },
];
