// E183 «Guess the Animal by Emoji 2» — 100 animals · 25/tier
// VO: sfx/e183-<id>.wav
export const ANIMAL_EMOJI_2_FACTS = {
  // EASY
  "dolphin": "Highly intelligent marine mammal that lives in the ocean.",
  "shark": "Cartilaginous fish and apex predator of the seas.",
  "crab": "Ten-legged crustacean that walks sideways on shores.",
  "shrimp": "Small swimming crustacean found in oceans worldwide.",
  "lobster": "Large clawed crustacean living on the sea floor.",
  "squid": "Fast-swimming ten-armed ocean mollusk with ink.",
  "bee": "Flying insect that makes honey and pollinates flowers.",
  "butterfly": "Insect with large colorful wings and a coiled tongue.",
  "spider": "Eight-legged arachnid that spins silk webs.",
  "ant": "Tiny social insect that lives in large colonies.",
  "snail": "Slow mollusk that carries a spiral shell on its back.",
  "duck": "Web-footed water bird found on ponds and lakes.",
  "deer": "Hoofed forest mammal; males grow bony antlers.",
  "zebra": "African horse relative with black-and-white stripes.",
  "kangaroo": "Hopping Australian marsupial with a pouch for young.",
  "crocodile": "Large armored reptile lurking in tropical waters.",
  "gorilla": "Largest living ape, native to African forests.",
  "eagle": "Powerful bird of prey with keen eyesight.",
  "parrot": "Colorful tropical bird that can mimic sounds.",
  "bat": "Only mammal capable of true flight; active at night.",
  "mouse": "Small rodent with a long tail, fond of cheese.",
  "hamster": "Small pet rodent that stores food in cheek pouches.",
  "rooster": "Male chicken known for crowing at sunrise.",
  "hedgehog": "Small spiny mammal that rolls into a ball.",
  "rhinoceros": "Huge horned mammal roaming African and Asian plains.",
  // MEDIUM
  "seahorse": "Tiny upright fish; the males carry the babies.",
  "jellyfish": "Boneless drifting sea animal with stinging tentacles.",
  "starfish": "Five-armed sea creature that lives on the ocean floor.",
  "swan": "Large elegant white water bird with a long neck.",
  "turkey": "Large ground bird native to North America.",
  "dove": "Gentle pale bird and a symbol of peace.",
  "beaver": "Rodent that builds dams and lodges from wood.",
  "sloth": "Slow tree-dwelling mammal of the Americas.",
  "orangutan": "Reddish great ape living in Asian rainforests.",
  "llama": "Andean pack animal related to the camel.",
  "bison": "Massive shaggy wild ox of American grasslands.",
  "boar": "Wild pig with sharp tusks living in forests.",
  "blowfish": "Fish that puffs into a spiky ball when threatened.",
  "worm": "Long soft-bodied invertebrate living in the soil.",
  "beetle": "Insect with hard wing cases; a huge insect group.",
  "cricket": "Jumping insect that chirps by rubbing its wings.",
  "scorpion": "Arachnid with pincers and a venomous stinging tail.",
  "mosquito": "Small fly whose females bite and suck blood.",
  "cockroach": "Hardy fast insect that thrives near humans.",
  "caterpillar": "Larva of a butterfly or moth that eats leaves.",
  "iguana": "Large tropical lizard that basks in the sun.",
  "poodle": "Curly-coated dog breed prized in dog shows.",
  "donkey": "Sturdy long-eared relative of the horse.",
  "ram": "Adult male sheep with large curling horns.",
  "fly": "Common two-winged insect found around the world.",
  // HARD
  "lemur": "Big-eyed primate found only on Madagascar.",
  "mandrill": "Largest monkey, with a vivid red-and-blue face.",
  "wildebeest": "African antelope famous for its mass migrations.",
  "ibex": "Wild mountain goat with long ridged horns.",
  "moose": "Largest deer, with huge flat palmate antlers.",
  "mammoth": "Extinct shaggy elephant relative of the Ice Age.",
  "dodo": "Extinct flightless bird once native to Mauritius.",
  "ostrich": "Largest living bird; flightless and a fast runner.",
  "pelican": "Water bird with a big throat pouch for fish.",
  "orca": "Black-and-white apex predator, the largest dolphin.",
  "anglerfish": "Deep-sea fish that lures prey with a glowing rod.",
  "flying-fish": "Fish that glides above water on wing-like fins.",
  "toad": "Warty land amphibian related to the frog.",
  "tortoise": "Slow land reptile with a high domed shell.",
  "chipmunk": "Small striped rodent that stores nuts in its cheeks.",
  "tarantula": "Large hairy spider that hunts on the ground.",
  "mantis": "Predatory insect that holds its forelegs as if praying.",
  "firefly": "Beetle that glows in the dark to attract mates.",
  "salamander": "Slender amphibian with a tail and moist skin.",
  "hornet": "Large aggressive wasp with a painful sting.",
  "termite": "Wood-eating insect that builds tall earthen mounds.",
  "warthog": "Wild African pig with facial warts and tusks.",
  "anaconda": "Huge South American snake that crushes its prey.",
  "cobra": "Venomous snake that spreads a hood when alarmed.",
  "vulture": "Bald scavenging bird that feeds on carrion.",
  // IMPOSSIBLE
  "numbat": "Striped Australian marsupial that eats termites.",
  "potoroo": "Small rabbit-sized relative of the kangaroo.",
  "margay": "Small spotted wildcat that climbs trees expertly.",
  "caracal": "Slender wildcat with long black ear tufts.",
  "quagga": "Extinct half-striped subspecies of the zebra.",
  "gaur": "Largest wild cattle species, native to South Asia.",
  "takin": "Stocky goat-antelope of the eastern Himalayas.",
  "dik-dik": "Tiny African antelope the size of a rabbit.",
  "vaquita": "Rarest porpoise, found only in Mexico's gulf.",
  "beluga": "Small white Arctic whale with a bulging forehead.",
  "olm": "Blind cave salamander with pale pink skin.",
  "caecilian": "Limbless burrowing amphibian that looks like a worm.",
  "tuatara": "Ancient lizard-like reptile of New Zealand.",
  "matamata": "Odd flat-headed river turtle of South America.",
  "kea": "Alpine parrot of New Zealand known for mischief.",
  "desman": "Aquatic mole relative with a long flexible snout.",
  "zorilla": "African striped polecat resembling a skunk.",
  "maned-wolf": "Tall long-legged wild canid of South America.",
  "bush-dog": "Small short-legged wild dog of South America.",
  "tanuki": "Raccoon-like wild dog native to East Asia.",
  "fishing-cat": "Wildcat that dives for fish in Asian wetlands.",
  "tamandua": "Tree-dwelling anteater of the Americas.",
  "sun-bear": "Smallest bear, with a pale chest crescent.",
  "jerboa": "Desert rodent that hops on long kangaroo-like legs.",
  "chevrotain": "Tiny deer-like animal, the smallest hoofed mammal.",
};
