// «Guess the Animal v3» — GuessSync · ANIMALS3 · 100 animals (25/tier)
// Third animal episode. Species are DIFFERENT from E03 (animalsData.js) AND E70
// (animals2Data.js) — unique slug AND name vs both. Avoids whole-subject episodes
// (birds/fish/insects/reptiles/snakes/amphibians/spiders/sea-creatures/dinosaurs/
// horses/dogs/cats/primates). Real Wikimedia photos.
// Absolute difficulty: easy (seal/black bear) → impossible (starnosed mole/dunnart).
// Answer VO a3-<slug>.wav = "It's the <name>!"
export const ANIMALS3 = [
  // EASY (25) — highest recognition in the remaining pool
  { slug: "seal", name: "Seal", level: "easy" },
  { slug: "sealion", name: "Sea Lion", level: "easy" },
  { slug: "seaotter", name: "Sea Otter", level: "easy" },
  { slug: "blackbear", name: "Black Bear", level: "easy" },
  { slug: "vampirebat", name: "Vampire Bat", level: "easy" },
  { slug: "reddeer", name: "Red Deer", level: "easy" },
  { slug: "fallowdeer", name: "Fallow Deer", level: "easy" },
  { slug: "muledeer", name: "Mule Deer", level: "easy" },
  { slug: "jackrabbit", name: "Jackrabbit", level: "easy" },
  { slug: "bighornsheep", name: "Bighorn Sheep", level: "easy" },
  { slug: "mountaingoat", name: "Mountain Goat", level: "easy" },
  { slug: "bactriancamel", name: "Bactrian Camel", level: "easy" },
  { slug: "capebuffalo", name: "Cape Buffalo", level: "easy" },
  { slug: "africanwilddog", name: "African Wild Dog", level: "easy" },
  { slug: "pygmyhippo", name: "Pygmy Hippo", level: "easy" },
  { slug: "echidna", name: "Echidna", level: "easy" },
  { slug: "elephantseal", name: "Elephant Seal", level: "easy" },
  { slug: "gerbil", name: "Gerbil", level: "easy" },
  { slug: "pika", name: "Pika", level: "easy" },
  { slug: "shrew", name: "Shrew", level: "easy" },
  { slug: "vicuna", name: "Vicuna", level: "easy" },
  { slug: "guanaco", name: "Guanaco", level: "easy" },
  { slug: "eland", name: "Eland", level: "easy" },
  { slug: "peccary", name: "Peccary", level: "easy" },
  { slug: "hyrax", name: "Hyrax", level: "easy" },

  // MEDIUM (25)
  { slug: "manedwolf", name: "Maned Wolf", level: "medium" },
  { slug: "raccoondog", name: "Raccoon Dog", level: "medium" },
  { slug: "batearedfox", name: "Bat-eared Fox", level: "medium" },
  { slug: "grayfox", name: "Gray Fox", level: "medium" },
  { slug: "swiftfox", name: "Swift Fox", level: "medium" },
  { slug: "sunbear", name: "Sun Bear", level: "medium" },
  { slug: "slothbear", name: "Sloth Bear", level: "medium" },
  { slug: "spectacledbear", name: "Spectacled Bear", level: "medium" },
  { slug: "pinemarten", name: "Pine Marten", level: "medium" },
  { slug: "polecat", name: "Polecat", level: "medium" },
  { slug: "civet", name: "Civet", level: "medium" },
  { slug: "genet", name: "Genet", level: "medium" },
  { slug: "redsquirrel", name: "Red Squirrel", level: "medium" },
  { slug: "muskrat", name: "Muskrat", level: "medium" },
  { slug: "gopher", name: "Gopher", level: "medium" },
  { slug: "lemming", name: "Lemming", level: "medium" },
  { slug: "dormouse", name: "Dormouse", level: "medium" },
  { slug: "treekangaroo", name: "Tree Kangaroo", level: "medium" },
  { slug: "tamandua", name: "Tamandua", level: "medium" },
  { slug: "waterbuck", name: "Waterbuck", level: "medium" },
  { slug: "bushbuck", name: "Bushbuck", level: "medium" },
  { slug: "hartebeest", name: "Hartebeest", level: "medium" },
  { slug: "sikadeer", name: "Sika Deer", level: "medium" },
  { slug: "roedeer", name: "Roe Deer", level: "medium" },
  { slug: "zebu", name: "Zebu", level: "medium" },

  // HARD (25)
  { slug: "bushdog", name: "Bush Dog", level: "hard" },
  { slug: "corsacfox", name: "Corsac Fox", level: "hard" },
  { slug: "giantotter", name: "Giant Otter", level: "hard" },
  { slug: "fisher", name: "Fisher", level: "hard" },
  { slug: "tayra", name: "Tayra", level: "hard" },
  { slug: "ringtail", name: "Ringtail", level: "hard" },
  { slug: "palmcivet", name: "Palm Civet", level: "hard" },
  { slug: "vole", name: "Vole", level: "hard" },
  { slug: "degu", name: "Degu", level: "hard" },
  { slug: "kangaroorat", name: "Kangaroo Rat", level: "hard" },
  { slug: "paca", name: "Paca", level: "hard" },
  { slug: "springhare", name: "Springhare", level: "hard" },
  { slug: "pademelon", name: "Pademelon", level: "hard" },
  { slug: "brushtailpossum", name: "Brushtail Possum", level: "hard" },
  { slug: "silkyanteater", name: "Silky Anteater", level: "hard" },
  { slug: "topi", name: "Topi", level: "hard" },
  { slug: "roan", name: "Roan Antelope", level: "hard" },
  { slug: "sableantelope", name: "Sable Antelope", level: "hard" },
  { slug: "reedbuck", name: "Reedbuck", level: "hard" },
  { slug: "lechwe", name: "Lechwe", level: "hard" },
  { slug: "sambar", name: "Sambar", level: "hard" },
  { slug: "barasingha", name: "Barasingha", level: "hard" },
  { slug: "waterdeer", name: "Water Deer", level: "hard" },
  { slug: "dallsheep", name: "Dall Sheep", level: "hard" },
  { slug: "barbarysheep", name: "Barbary Sheep", level: "hard" },

  // IMPOSSIBLE (25)
  { slug: "ethiopianwolf", name: "Ethiopian Wolf", level: "impossible" },
  { slug: "culpeo", name: "Culpeo", level: "impossible" },
  { slug: "crabeatingfox", name: "Crab-eating Fox", level: "impossible" },
  { slug: "darwinsfox", name: "Darwin's Fox", level: "impossible" },
  { slug: "sable", name: "Sable", level: "impossible" },
  { slug: "grison", name: "Grison", level: "impossible" },
  { slug: "cacomistle", name: "Cacomistle", level: "impossible" },
  { slug: "linsang", name: "Linsang", level: "impossible" },
  { slug: "viscacha", name: "Viscacha", level: "impossible" },
  { slug: "pacarana", name: "Pacarana", level: "impossible" },
  { slug: "potoroo", name: "Potoroo", level: "impossible" },
  { slug: "bettong", name: "Bettong", level: "impossible" },
  { slug: "cuscus", name: "Cuscus", level: "impossible" },
  { slug: "dunnart", name: "Dunnart", level: "impossible" },
  { slug: "kob", name: "Kob", level: "impossible" },
  { slug: "oribi", name: "Oribi", level: "impossible" },
  { slug: "steenbok", name: "Steenbok", level: "impossible" },
  { slug: "suni", name: "Suni", level: "impossible" },
  { slug: "brocket", name: "Brocket Deer", level: "impossible" },
  { slug: "europeanbison", name: "European Bison", level: "impossible" },
  { slug: "watusi", name: "Watusi", level: "impossible" },
  { slug: "urial", name: "Urial", level: "impossible" },
  { slug: "bharal", name: "Bharal", level: "impossible" },
  { slug: "leopardseal", name: "Leopard Seal", level: "impossible" },
  { slug: "starnosedmole", name: "Star-nosed Mole", level: "impossible" },
];
export const ANIMALS3_LEVELS = ["easy", "medium", "hard", "impossible"];
