// E163 legendary-weapon/artifact-by-emoji facts — one TRUE <=70-char fact per item, shown on reveal.
export const ARTIFACT_EMOJI_FACTS = {
  // EASY
  "excalibur": "King Arthur's legendary sword from British Arthurian legend.",
  "mjolnir": "Thor's hammer in Norse myth; only the worthy can lift it.",
  "one-ring": "The One Ring from Tolkien's The Lord of the Rings.",
  "holy-grail": "The sacred cup of Arthurian and Christian legend.",
  "aladdins-lamp": "The magic lamp of Aladdin from One Thousand and One Nights.",
  "lightsaber": "The glowing energy-blade wielded by Jedi in Star Wars.",
  "infinity-gauntlet": "Thanos's glove holds the six Infinity Stones in Marvel.",
  "elder-wand": "The unbeatable wand of Harry Potter's Deathly Hallows.",
  "poseidon-trident": "The three-pronged spear of the Greek sea-god Poseidon.",
  "captain-america-shield": "Captain America's round vibranium shield in Marvel Comics.",
  "pandoras-box": "In Greek myth it released all evils into the world.",
  "cupids-bow": "Cupid's arrows make people fall in love in Roman myth.",
  "crystal-ball": "The classic fortune-teller's orb for seeing the future.",
  "green-lantern-ring": "DC's power ring channels willpower into green energy.",
  "master-sword": "Link's blade that seals evil in The Legend of Zelda.",
  "lasso-of-truth": "Wonder Woman's golden lariat forces captives to be honest.",
  "golden-fleece": "The prize Jason and the Argonauts sought in Greek myth.",
  "sword-in-the-stone": "Only the true king could pull it free in Arthurian legend.",
  "philosophers-stone": "Alchemists' stone said to turn metal to gold and grant life.",
  "book-of-the-dead": "Ancient Egyptian spells guiding the dead through the afterlife.",
  "ark-of-the-covenant": "The gold chest holding the Ten Commandments tablets.",
  "glass-slipper": "The slipper Cinderella leaves behind at the ball.",
  "ruby-slippers": "Dorothy's magic shoes in The Wizard of Oz film.",
  "golden-ticket": "Wins a tour of Willy Wonka's chocolate factory.",
  "magic-mirror": "The Evil Queen's talking mirror in Snow White.",

  // MEDIUM
  "stormbreaker": "The axe Thor forges in Avengers: Infinity War.",
  "tesseract": "The blue cube holding the Space Stone in the MCU.",
  "eye-of-agamotto": "Doctor Strange's amulet houses the green Time Stone.",
  "cloak-of-levitation": "Doctor Strange's sentient red cape that lets him fly.",
  "batarang": "Batman's bat-shaped throwing weapon in DC Comics.",
  "web-shooters": "Spider-Man's wrist devices that fire webbing.",
  "arc-reactor": "The glowing device powering Iron Man's suit and heart.",
  "sword-of-gryffindor": "Goblin-made blade that appears to worthy Gryffindors.",
  "marauders-map": "A map revealing everyone's location at Hogwarts.",
  "sorting-hat": "The Hogwarts hat that sorts students into houses.",
  "time-turner": "Hermione's hourglass device for time travel in Harry Potter.",
  "mirror-of-erised": "The mirror showing your deepest desire in Harry Potter.",
  "death-note": "A notebook that kills anyone whose name is written in it.",
  "dragon-balls": "Seven orbs that summon a wish-granting dragon.",
  "triforce": "The sacred golden relic of power in The Legend of Zelda.",
  "ocarina-of-time": "The magic flute controlling time in the Zelda game.",
  "portal-gun": "Fires linked portals in the game Portal.",
  "keyblade": "The key-shaped weapon of the Kingdom Hearts games.",
  "trojan-horse": "The hollow wooden horse that fooled Troy in Greek legend.",
  "cornucopia": "The horn of plenty overflowing with food in Greek myth.",
  "caduceus": "Hermes's winged staff entwined by two serpents.",
  "aegis": "The protective shield of Zeus and Athena in Greek myth.",
  "zeus-thunderbolt": "The lightning bolt hurled by Zeus, king of the gods.",
  "holy-lance": "The Spear of Longinus that pierced Christ's side.",
  "crystal-skull": "The mysterious carved skull of Indiana Jones lore.",

  // HARD
  "golden-idol": "The fertility idol Indiana Jones grabs in Raiders.",
  "shroud-of-turin": "A linen cloth said to bear the image of Christ.",
  "koh-i-noor": "A famed diamond among the British Crown Jewels.",
  "stone-of-destiny": "The Stone of Scone used to crown Scottish kings.",
  "poisoned-apple": "The apple the Evil Queen uses to poison Snow White.",
  "wardrobe-of-narnia": "The wardrobe that leads to Narnia in C.S. Lewis's tale.",
  "sonic-screwdriver": "The Doctor's multi-tool in the show Doctor Who.",
  "vorpal-sword": "The blade that slays the Jabberwock in Lewis Carroll's poem.",
  "sting": "Bilbo's Elvish blade that glows blue near orcs in Tolkien.",
  "hattori-hanzo-sword": "The custom katana forged for the Bride in Kill Bill.",
  "necronomicon": "The fictional book of the dead from Lovecraft and Evil Dead.",
  "golden-snitch": "The tiny winged golden ball in Quidditch, Harry Potter.",
  "winged-sandals": "Hermes's flying sandals, the Talaria, in Greek myth.",
  "rod-of-asclepius": "The snake-entwined staff, symbol of medicine.",
  "golden-apple": "The Apple of Discord marked 'to the fairest' in Greek myth.",
  "sword-of-damocles": "A sword hung by a hair over Damocles in Greek legend.",
  "gordian-knot": "The knot Alexander the Great cut with his sword.",
  "deathly-hallows": "The symbol of the three Hallows in Harry Potter.",
  "gram": "The sword Sigurd uses to slay the dragon Fafnir in Norse myth.",
  "narsil": "Aragorn's broken blade, reforged as Andúril in Tolkien.",
  "scarab-amulet": "The beetle amulet of protection in ancient Egypt.",
  "gjallarhorn": "Heimdall's horn that sounds to signal Ragnarök.",
  "draupnir": "Odin's magic ring that drips eight new rings each night.",
  "palantir": "The seeing-stones used to spy across Middle-earth in Tolkien.",
  "curtana": "The blunt-tipped Sword of Mercy in English coronations.",

  // IMPOSSIBLE
  "durendal": "The indestructible sword of Roland in French epic.",
  "joyeuse": "The legendary sword of Emperor Charlemagne.",
  "tyrfing": "A cursed Norse sword that must draw blood once drawn.",
  "kusanagi": "The sacred sword among Japan's Imperial Regalia.",
  "gae-bolg": "Cú Chulainn's barbed spear in Irish mythology.",
  "gungnir": "Odin's spear that never misses in Norse myth.",
  "hades-bident": "The two-pronged staff of Hades, Greek lord of the dead.",
  "helm-of-darkness": "Hades's cap of invisibility in Greek myth.",
  "bow-of-apollo": "The silver bow of the Greek god Apollo.",
  "brisingamen": "Freyja's prized necklace in Norse mythology.",
  "cintamani": "A wish-granting jewel in Hindu and Buddhist lore.",
  "holy-hand-grenade": "The exploding relic from Monty Python and the Holy Grail.",
  "sword-of-goujian": "An ancient bronze sword unearthed nearly intact in China.",
  "green-destiny": "The prized sword in Crouching Tiger, Hidden Dragon.",
  "muramasa": "Blades by smith Muramasa, called cursed in Japanese lore.",
  "fragarach": "The Irish 'Answerer' sword said to cut any shield.",
  "claiomh-solais": "The glowing 'Sword of Light' of Irish folklore.",
  "kladenets": "A self-swinging magic sword of Slavic folklore.",
  "tizona": "One of the two famed swords of Spain's El Cid.",
  "wallace-sword": "The great sword attributed to Scotland's William Wallace.",
  "seven-branched-sword": "Ancient ceremonial sword of Korea's Baekje with six branches.",
  "hrunting": "The sword lent to Beowulf to fight Grendel's mother.",
  "naegling": "Beowulf's own sword that shatters against the dragon.",
  "mistilteinn": "A magic 'Mistletoe' sword from Norse saga.",
  "honjo-masamune": "A legendary blade by master smith Masamune, now lost.",
};
