// BIRDS2 · «Guess the Bird v2» — 100 طائر (25/مستوى) · صورة birds2/<slug>.jpg (Wikimedia, free licenses) · صوت b2-<slug>.wav
// 100% مختلفة عن E19 (birdsData.js): لا يتكرر أي slug أو name.
// name = الإجابة المعروضة/المنطوقة (قصير، VO ≤3.33s) · level = صعوبة مطلقة داخل الحلقة.
export const BIRDS2 = [
  // ===== EASY (25) — طيور يعرفها الجميع تقريبًا =====
  { slug: "american-crow", name: "American Crow", level: "easy" },
  { slug: "european-starling", name: "Starling", level: "easy" },
  { slug: "emu", name: "Emu", level: "easy" },
  { slug: "king-penguin", name: "King Penguin", level: "easy" },
  { slug: "white-stork", name: "White Stork", level: "easy" },
  { slug: "great-white-pelican", name: "White Pelican", level: "easy" },
  { slug: "herring-gull", name: "Herring Gull", level: "easy" },
  { slug: "common-cuckoo", name: "Common Cuckoo", level: "easy" },
  { slug: "common-blackbird", name: "Blackbird", level: "easy" },
  { slug: "great-tit", name: "Great Tit", level: "easy" },
  { slug: "eurasian-collared-dove", name: "Collared Dove", level: "easy" },
  { slug: "common-wood-pigeon", name: "Wood Pigeon", level: "easy" },
  { slug: "greylag-goose", name: "Greylag Goose", level: "easy" },
  { slug: "eurasian-coot", name: "Coot", level: "easy" },
  { slug: "grey-heron", name: "Grey Heron", level: "easy" },
  { slug: "common-chaffinch", name: "Chaffinch", level: "easy" },
  { slug: "house-finch", name: "House Finch", level: "easy" },
  { slug: "mourning-dove", name: "Mourning Dove", level: "easy" },
  { slug: "red-winged-blackbird", name: "Red-winged Blackbird", level: "easy" },
  { slug: "turkey-vulture", name: "Turkey Vulture", level: "easy" },
  { slug: "osprey", name: "Osprey", level: "easy" },
  { slug: "peregrine-falcon", name: "Peregrine Falcon", level: "easy" },
  { slug: "golden-eagle", name: "Golden Eagle", level: "easy" },
  { slug: "great-cormorant", name: "Cormorant", level: "easy" },
  { slug: "black-swan", name: "Black Swan", level: "easy" },

  // ===== MEDIUM (25) — مألوفة لكن تحتاج معرفة بسيطة =====
  { slug: "gentoo-penguin", name: "Gentoo Penguin", level: "medium" },
  { slug: "african-penguin", name: "African Penguin", level: "medium" },
  { slug: "common-kestrel", name: "Kestrel", level: "medium" },
  { slug: "red-tailed-hawk", name: "Red-tailed Hawk", level: "medium" },
  { slug: "great-spotted-woodpecker", name: "Great Spotted Woodpecker", level: "medium" },
  { slug: "eurasian-bullfinch", name: "Bullfinch", level: "medium" },
  { slug: "eurasian-jay", name: "Eurasian Jay", level: "medium" },
  { slug: "northern-mockingbird", name: "Mockingbird", level: "medium" },
  { slug: "baltimore-oriole", name: "Baltimore Oriole", level: "medium" },
  { slug: "cedar-waxwing", name: "Cedar Waxwing", level: "medium" },
  { slug: "eastern-bluebird", name: "Eastern Bluebird", level: "medium" },
  { slug: "common-nightingale", name: "Nightingale", level: "medium" },
  { slug: "common-swift", name: "Common Swift", level: "medium" },
  { slug: "common-tern", name: "Common Tern", level: "medium" },
  { slug: "black-headed-gull", name: "Black-headed Gull", level: "medium" },
  { slug: "whooper-swan", name: "Whooper Swan", level: "medium" },
  { slug: "tufted-puffin", name: "Tufted Puffin", level: "medium" },
  { slug: "white-tailed-eagle", name: "White-tailed Eagle", level: "medium" },
  { slug: "northern-pintail", name: "Pintail", level: "medium" },
  { slug: "northern-shoveler", name: "Shoveler", level: "medium" },
  { slug: "great-crested-grebe", name: "Great Crested Grebe", level: "medium" },
  { slug: "eurasian-nuthatch", name: "Nuthatch", level: "medium" },
  { slug: "goldcrest", name: "Goldcrest", level: "medium" },
  { slug: "eurasian-skylark", name: "Skylark", level: "medium" },
  { slug: "song-thrush", name: "Song Thrush", level: "medium" },

  // ===== HARD (25) — لافتة/غريبة، معروفة نسبيًا =====
  { slug: "smew", name: "Smew", level: "hard" },
  { slug: "harlequin-duck", name: "Harlequin Duck", level: "hard" },
  { slug: "king-eider", name: "King Eider", level: "hard" },
  { slug: "hooded-merganser", name: "Hooded Merganser", level: "hard" },
  { slug: "bearded-reedling", name: "Bearded Reedling", level: "hard" },
  { slug: "indian-roller", name: "Indian Roller", level: "hard" },
  { slug: "malachite-kingfisher", name: "Malachite Kingfisher", level: "hard" },
  { slug: "pied-kingfisher", name: "Pied Kingfisher", level: "hard" },
  { slug: "superb-starling", name: "Superb Starling", level: "hard" },
  { slug: "gouldian-finch", name: "Gouldian Finch", level: "hard" },
  { slug: "java-sparrow", name: "Java Sparrow", level: "hard" },
  { slug: "red-avadavat", name: "Red Avadavat", level: "hard" },
  { slug: "bohemian-waxwing", name: "Bohemian Waxwing", level: "hard" },
  { slug: "northern-lapwing", name: "Northern Lapwing", level: "hard" },
  { slug: "pied-avocet", name: "Pied Avocet", level: "hard" },
  { slug: "black-winged-stilt", name: "Black-winged Stilt", level: "hard" },
  { slug: "eurasian-oystercatcher", name: "Oystercatcher", level: "hard" },
  { slug: "razorbill", name: "Razorbill", level: "hard" },
  { slug: "common-guillemot", name: "Guillemot", level: "hard" },
  { slug: "northern-gannet", name: "Northern Gannet", level: "hard" },
  { slug: "blue-footed-booby", name: "Blue-footed Booby", level: "hard" },
  { slug: "brown-pelican", name: "Brown Pelican", level: "hard" },
  { slug: "purple-gallinule", name: "Purple Gallinule", level: "hard" },
  { slug: "sarus-crane", name: "Sarus Crane", level: "hard" },
  { slug: "demoiselle-crane", name: "Demoiselle Crane", level: "hard" },

  // ===== IMPOSSIBLE (25) — نادرة/استوائية غامضة =====
  { slug: "golden-headed-quetzal", name: "Golden-headed Quetzal", level: "impossible" },
  { slug: "long-tailed-broadbill", name: "Long-tailed Broadbill", level: "impossible" },
  { slug: "horned-guan", name: "Horned Guan", level: "impossible" },
  { slug: "helmeted-hornbill", name: "Helmeted Hornbill", level: "impossible" },
  { slug: "wreathed-hornbill", name: "Wreathed Hornbill", level: "impossible" },
  { slug: "philippine-eagle", name: "Philippine Eagle", level: "impossible" },
  { slug: "harpy-eagle", name: "Harpy Eagle", level: "impossible" },
  { slug: "bearded-vulture", name: "Bearded Vulture", level: "impossible" },
  { slug: "king-vulture", name: "King Vulture", level: "impossible" },
  { slug: "cinereous-vulture", name: "Cinereous Vulture", level: "impossible" },
  { slug: "maleo", name: "Maleo", level: "impossible" },
  { slug: "crested-partridge", name: "Crested Partridge", level: "impossible" },
  { slug: "himalayan-monal", name: "Himalayan Monal", level: "impossible" },
  { slug: "temmincks-tragopan", name: "Temminck's Tragopan", level: "impossible" },
  { slug: "great-argus", name: "Great Argus", level: "impossible" },
  { slug: "crowned-eagle", name: "Crowned Eagle", level: "impossible" },
  { slug: "bateleur", name: "Bateleur", level: "impossible" },
  { slug: "splendid-fairywren", name: "Splendid Fairywren", level: "impossible" },
  { slug: "regent-bowerbird", name: "Regent Bowerbird", level: "impossible" },
  { slug: "satin-bowerbird", name: "Satin Bowerbird", level: "impossible" },
  { slug: "paradise-tanager", name: "Paradise Tanager", level: "impossible" },
  { slug: "green-honeycreeper", name: "Green Honeycreeper", level: "impossible" },
  { slug: "turquoise-browed-motmot", name: "Turquoise-browed Motmot", level: "impossible" },
  { slug: "violet-backed-starling", name: "Violet-backed Starling", level: "impossible" },
  { slug: "nicobar-pigeon", name: "Nicobar Pigeon", level: "impossible" },
];

export const BIRDS2_LEVELS = ["easy", "medium", "hard", "impossible"];
