// E98 «Guess the ZOOMED Bird» — GuessSync "What the Zoom" hard-mode.
// Reuses the EXACT E19 bird image set (birds/<slug>.jpg) and E19's BIRD_FACTS + bd-<slug>.wav
// answer VOs (copied to bz-<slug>.wav — identical "It's the <name>!" line, zero new audio cost),
// but RE-TIERED by how easy each bird is to name from an EXTREME off-center close-up crop of
// plumage/bill (scale 3.0). A random patch shows one feather-patch/bill/head region only, so
// difficulty here tracks COLOR/PATTERN saturation of the crop, NOT general bird fame:
//   EASY = saturated/unmistakable color or bill shape survives any crop (solid pink flamingo,
//          rainbow macaw, giant toucan bill, iridescent quetzal, etc.)
//   IMPOSSIBLE = plain brown/grey/camouflaged plumage or a crop with no distinguishing feature
// image: birds/<slug>.jpg | answer VO: sfx/bz-<slug>.wav (copied from E19's bd-<slug>.wav)
export const BIRDZOOM = [
  // ===== EASY (25) — saturated, unmistakable color/pattern/bill in any close-up patch =====
  { slug: "greater-flamingo", name: "Greater Flamingo", sci: "Phoenicopterus roseus", level: "easy" },
  { slug: "american-flamingo", name: "American Flamingo", sci: "Phoenicopterus ruber", level: "easy" },
  { slug: "indian-peafowl", name: "Indian Peafowl", sci: "Pavo cristatus", level: "easy" },
  { slug: "scarlet-macaw", name: "Scarlet Macaw", sci: "Ara macao", level: "easy" },
  { slug: "hyacinth-macaw", name: "Hyacinth Macaw", sci: "Anodorhynchus hyacinthinus", level: "easy" },
  { slug: "toco-toucan", name: "Toco Toucan", sci: "Ramphastos toco", level: "easy" },
  { slug: "keel-billed-toucan", name: "Keel-billed Toucan", sci: "Ramphastos sulfuratus", level: "easy" },
  { slug: "mandarin-duck", name: "Mandarin Duck", sci: "Aix galericulata", level: "easy" },
  { slug: "rainbow-lorikeet", name: "Rainbow Lorikeet", sci: "Trichoglossus moluccanus", level: "easy" },
  { slug: "northern-cardinal", name: "Northern Cardinal", sci: "Cardinalis cardinalis", level: "easy" },
  { slug: "painted-bunting", name: "Painted Bunting", sci: "Passerina ciris", level: "easy" },
  { slug: "scarlet-ibis", name: "Scarlet Ibis", sci: "Eudocimus ruber", level: "easy" },
  { slug: "resplendent-quetzal", name: "Resplendent Quetzal", sci: "Pharomachrus mocinno", level: "easy" },
  { slug: "roseate-spoonbill", name: "Roseate Spoonbill", sci: "Platalea ajaja", level: "easy" },
  { slug: "golden-pheasant", name: "Golden Pheasant", sci: "Chrysolophus pictus", level: "easy" },
  { slug: "lilac-breasted-roller", name: "Lilac-breasted Roller", sci: "Coracias caudatus", level: "easy" },
  { slug: "vermilion-flycatcher", name: "Vermilion Flycatcher", sci: "Pyrocephalus rubinus", level: "easy" },
  { slug: "andean-cock-of-the-rock", name: "Andean Cock-of-the-rock", sci: "Rupicola peruvianus", level: "easy" },
  { slug: "guianan-cock-of-the-rock", name: "Guianan Cock-of-the-rock", sci: "Rupicola rupicola", level: "easy" },
  { slug: "greater-bird-of-paradise", name: "Greater Bird-of-paradise", sci: "Paradisaea apoda", level: "easy" },
  { slug: "wilsons-bird-of-paradise", name: "Wilson's Bird-of-paradise", sci: "Cicinnurus respublica", level: "easy" },
  { slug: "king-of-saxony-bird-of-paradise", name: "King-of-Saxony Bird-of-paradise", sci: "Pteridophora alberti", level: "easy" },
  { slug: "shoebill", name: "Shoebill", sci: "Balaeniceps rex", level: "easy" },
  { slug: "atlantic-puffin", name: "Atlantic Puffin", sci: "Fratercula arctica", level: "easy" },
  { slug: "emperor-penguin", name: "Emperor Penguin", sci: "Aptenodytes forsteri", level: "easy" },
  // ===== MEDIUM (25) — distinctive pattern, but crop needs a bit more context =====
  { slug: "sulphur-crested-cockatoo", name: "Sulphur-crested Cockatoo", sci: "Cacatua galerita", level: "medium" },
  { slug: "grey-parrot", name: "Grey Parrot", sci: "Psittacus erithacus", level: "medium" },
  { slug: "budgerigar", name: "Budgerigar", sci: "Melopsittacus undulatus", level: "medium" },
  { slug: "barn-owl", name: "Barn Owl", sci: "Tyto alba", level: "medium" },
  { slug: "snowy-owl", name: "Snowy Owl", sci: "Bubo scandiacus", level: "medium" },
  { slug: "great-horned-owl", name: "Great Horned Owl", sci: "Bubo virginianus", level: "medium" },
  { slug: "wood-duck", name: "Wood Duck", sci: "Aix sponsa", level: "medium" },
  { slug: "ruby-throated-hummingbird", name: "Ruby-throated Hummingbird", sci: "Archilochus colubris", level: "medium" },
  { slug: "sword-billed-hummingbird", name: "Sword-billed Hummingbird", sci: "Ensifera ensifera", level: "medium" },
  { slug: "common-kingfisher", name: "Common Kingfisher", sci: "Alcedo atthis", level: "medium" },
  { slug: "belted-kingfisher", name: "Belted Kingfisher", sci: "Megaceryle alcyon", level: "medium" },
  { slug: "european-bee-eater", name: "European Bee-eater", sci: "Merops apiaster", level: "medium" },
  { slug: "american-goldfinch", name: "American Goldfinch", sci: "Spinus tristis", level: "medium" },
  { slug: "eurasian-blue-tit", name: "Eurasian Blue Tit", sci: "Cyanistes caeruleus", level: "medium" },
  { slug: "helmeted-guineafowl", name: "Helmeted Guineafowl", sci: "Numida meleagris", level: "medium" },
  { slug: "southern-ground-hornbill", name: "Southern Ground Hornbill", sci: "Bucorvus leadbeateri", level: "medium" },
  { slug: "great-hornbill", name: "Great Hornbill", sci: "Buceros bicornis", level: "medium" },
  { slug: "rhinoceros-hornbill", name: "Rhinoceros Hornbill", sci: "Buceros rhinoceros", level: "medium" },
  { slug: "magnificent-frigatebird", name: "Magnificent Frigatebird", sci: "Fregata magnificens", level: "medium" },
  { slug: "grey-crowned-crane", name: "Grey Crowned Crane", sci: "Balearica regulorum", level: "medium" },
  { slug: "southern-cassowary", name: "Southern Cassowary", sci: "Casuarius casuarius", level: "medium" },
  { slug: "victoria-crowned-pigeon", name: "Victoria Crowned Pigeon", sci: "Goura victoria", level: "medium" },
  { slug: "kea", name: "Kea", sci: "Nestor notabilis", level: "medium" },
  { slug: "hamerkop", name: "Hamerkop", sci: "Scopus umbretta", level: "medium" },
  { slug: "secretarybird", name: "Secretarybird", sci: "Sagittarius serpentarius", level: "medium" },
  // ===== HARD (25) — generic brown/grey plumage, a crop patch reveals little =====
  { slug: "rock-pigeon", name: "Rock Pigeon", sci: "Columba livia", level: "hard" },
  { slug: "house-sparrow", name: "House Sparrow", sci: "Passer domesticus", level: "hard" },
  { slug: "mallard", name: "Mallard", sci: "Anas platyrhynchos", level: "hard" },
  { slug: "american-robin", name: "American Robin", sci: "Turdus migratorius", level: "hard" },
  { slug: "bald-eagle", name: "Bald Eagle", sci: "Haliaeetus leucocephalus", level: "hard" },
  { slug: "common-raven", name: "Common Raven", sci: "Corvus corax", level: "hard" },
  { slug: "european-robin", name: "European Robin", sci: "Erithacus rubecula", level: "hard" },
  { slug: "red-junglefowl", name: "Red Junglefowl", sci: "Gallus gallus", level: "hard" },
  { slug: "barn-swallow", name: "Barn Swallow", sci: "Hirundo rustica", level: "hard" },
  { slug: "rockhopper-penguin", name: "Rockhopper Penguin", sci: "Eudyptes chrysocome", level: "hard" },
  { slug: "blue-jay", name: "Blue Jay", sci: "Cyanocitta cristata", level: "hard" },
  { slug: "great-blue-heron", name: "Great Blue Heron", sci: "Ardea herodias", level: "hard" },
  { slug: "european-goldfinch", name: "European Goldfinch", sci: "Carduelis carduelis", level: "hard" },
  { slug: "pileated-woodpecker", name: "Pileated Woodpecker", sci: "Dryocopus pileatus", level: "hard" },
  { slug: "greater-roadrunner", name: "Greater Roadrunner", sci: "Geococcyx californianus", level: "hard" },
  { slug: "common-loon", name: "Common Loon", sci: "Gavia immer", level: "hard" },
  { slug: "wild-turkey", name: "Wild Turkey", sci: "Meleagris gallopavo", level: "hard" },
  { slug: "great-egret", name: "Great Egret", sci: "Ardea alba", level: "hard" },
  { slug: "eurasian-magpie", name: "Eurasian Magpie", sci: "Pica pica", level: "hard" },
  { slug: "laughing-kookaburra", name: "Laughing Kookaburra", sci: "Dacelo novaeguineae", level: "hard" },
  { slug: "black-capped-chickadee", name: "Black-capped Chickadee", sci: "Poecile atricapillus", level: "hard" },
  { slug: "wandering-albatross", name: "Wandering Albatross", sci: "Diomedea exulans", level: "hard" },
  { slug: "eurasian-hoopoe", name: "Eurasian Hoopoe", sci: "Upupa epops", level: "hard" },
  { slug: "andean-condor", name: "Andean Condor", sci: "Vultur gryphus", level: "hard" },
  { slug: "green-woodpecker", name: "European Green Woodpecker", sci: "Picus viridis", level: "hard" },
  // ===== IMPOSSIBLE (25) — plain/camouflaged plumage or obscure species =====
  { slug: "common-ostrich", name: "Ostrich", sci: "Struthio camelus", level: "impossible" },
  { slug: "mute-swan", name: "Mute Swan", sci: "Cygnus olor", level: "impossible" },
  { slug: "canada-goose", name: "Canada Goose", sci: "Branta canadensis", level: "impossible" },
  { slug: "kakapo", name: "Kakapo", sci: "Strigops habroptilus", level: "impossible" },
  { slug: "hoatzin", name: "Hoatzin", sci: "Opisthocomus hoazin", level: "impossible" },
  { slug: "great-potoo", name: "Great Potoo", sci: "Nyctibius grandis", level: "impossible" },
  { slug: "papuan-frogmouth", name: "Papuan Frogmouth", sci: "Podargus papuensis", level: "impossible" },
  { slug: "bee-hummingbird", name: "Bee Hummingbird", sci: "Mellisuga helenae", level: "impossible" },
  { slug: "superb-lyrebird", name: "Superb Lyrebird", sci: "Menura novaehollandiae", level: "impossible" },
  { slug: "wallcreeper", name: "Wallcreeper", sci: "Tichodroma muraria", level: "impossible" },
  { slug: "kagu", name: "Kagu", sci: "Rhynochetos jubatus", level: "impossible" },
  { slug: "oilbird", name: "Oilbird", sci: "Steatornis caripensis", level: "impossible" },
  { slug: "sunbittern", name: "Sunbittern", sci: "Eurypyga helias", level: "impossible" },
  { slug: "long-wattled-umbrellabird", name: "Long-wattled Umbrellabird", sci: "Cephalopterus penduliger", level: "impossible" },
  { slug: "marvelous-spatuletail", name: "Marvelous Spatuletail", sci: "Loddigesia mirabilis", level: "impossible" },
  { slug: "long-tailed-ground-roller", name: "Long-tailed Ground Roller", sci: "Uratelornis chimaera", level: "impossible" },
  { slug: "capuchinbird", name: "Capuchinbird", sci: "Perissocephalus tricolor", level: "impossible" },
  { slug: "hooded-pitohui", name: "Hooded Pitohui", sci: "Pitohui dichrous", level: "impossible" },
  { slug: "standard-winged-nightjar", name: "Standard-winged Nightjar", sci: "Caprimulgus longipennis", level: "impossible" },
  { slug: "sri-lanka-frogmouth", name: "Sri Lanka Frogmouth", sci: "Batrachostomus moniliger", level: "impossible" },
  { slug: "red-bearded-bee-eater", name: "Red-bearded Bee-eater", sci: "Nyctyornis amictus", level: "impossible" },
  { slug: "bare-throated-bellbird", name: "Bare-throated Bellbird", sci: "Procnias nudicollis", level: "impossible" },
  { slug: "spangled-cotinga", name: "Spangled Cotinga", sci: "Cotinga cayana", level: "impossible" },
  { slug: "tawny-frogmouth", name: "Tawny Frogmouth", sci: "Podargus strigoides", level: "impossible" },
  { slug: "european-roller", name: "European Roller", sci: "Coracias garrulus", level: "impossible" },
];
