// E141 «Guess the Board Game by Emoji» — 100 board/tabletop games · 25/tier · clue = plain Unicode emoji (mirrors emoji-quiz rendering)
// VO: sfx/e141-<id>.wav ("It's <Game>!"). Born fair: every emoji fairly leads to the game (iconic component or name rebus). No two items share the same emoji set.
export const BOARDGAME_EMOJI = [
  // ===== EASY (25) — globally known =====
  { id: "chess", title: "Chess", emojis: "♟👑", level: "easy" },
  { id: "monopoly", title: "Monopoly", emojis: "🎩💰", level: "easy" },
  { id: "scrabble", title: "Scrabble", emojis: "🔤🧩", level: "easy" },
  { id: "jenga", title: "Jenga", emojis: "🧱🗼", level: "easy" },
  { id: "battleship", title: "Battleship", emojis: "🚢💥", level: "easy" },
  { id: "clue", title: "Clue", emojis: "🔍🔪", level: "easy" },
  { id: "risk", title: "Risk", emojis: "🌍⚔", level: "easy" },
  { id: "catan", title: "Catan", emojis: "🌾🏘", level: "easy" },
  { id: "ticket-to-ride", title: "Ticket to Ride", emojis: "🚂🎫", level: "easy" },
  { id: "uno", title: "Uno", emojis: "🔄🃏", level: "easy" },
  { id: "snakes-and-ladders", title: "Snakes and Ladders", emojis: "🐍🪜", level: "easy" },
  { id: "candy-land", title: "Candy Land", emojis: "🍭🍬", level: "easy" },
  { id: "operation", title: "Operation", emojis: "🩺⚡", level: "easy" },
  { id: "trivial-pursuit", title: "Trivial Pursuit", emojis: "❓🥧", level: "easy" },
  { id: "sorry", title: "Sorry!", emojis: "😔🔙", level: "easy" },
  { id: "yahtzee", title: "Yahtzee", emojis: "🎲📋", level: "easy" },
  { id: "twister", title: "Twister", emojis: "🌀🦵", level: "easy" },
  { id: "bingo", title: "Bingo", emojis: "🔢🗣", level: "easy" },
  { id: "pictionary", title: "Pictionary", emojis: "✏🖼", level: "easy" },
  { id: "checkers", title: "Checkers", emojis: "🔴👑", level: "easy" },
  { id: "tic-tac-toe", title: "Tic-Tac-Toe", emojis: "⭕❌", level: "easy" },
  { id: "hangman", title: "Hangman", emojis: "💀🔤", level: "easy" },
  { id: "the-game-of-life", title: "The Game of Life", emojis: "🚗👶", level: "easy" },
  { id: "guess-who", title: "Guess Who?", emojis: "🕵❓", level: "easy" },
  { id: "mouse-trap", title: "Mouse Trap", emojis: "🐭🧀", level: "easy" },

  // ===== MEDIUM (25) — classic + popular hobby =====
  { id: "backgammon", title: "Backgammon", emojis: "🎲🔻", level: "medium" },
  { id: "mahjong", title: "Mahjong", emojis: "🀄🌸", level: "medium" },
  { id: "carcassonne", title: "Carcassonne", emojis: "🏰🛤", level: "medium" },
  { id: "pandemic", title: "Pandemic", emojis: "🦠🌍", level: "medium" },
  { id: "dominion", title: "Dominion", emojis: "👑🪙", level: "medium" },
  { id: "stratego", title: "Stratego", emojis: "🚩💣", level: "medium" },
  { id: "rummikub", title: "Rummikub", emojis: "🔢🎴", level: "medium" },
  { id: "scattergories", title: "Scattergories", emojis: "🔠⏱", level: "medium" },
  { id: "boggle", title: "Boggle", emojis: "🔡⏳", level: "medium" },
  { id: "taboo", title: "Taboo", emojis: "🚫🗣", level: "medium" },
  { id: "codenames", title: "Codenames", emojis: "🕵🔑", level: "medium" },
  { id: "dixit", title: "Dixit", emojis: "🐰🖌", level: "medium" },
  { id: "azul", title: "Azul", emojis: "🔷🏛", level: "medium" },
  { id: "splendor", title: "Splendor", emojis: "💎🪙", level: "medium" },
  { id: "wingspan", title: "Wingspan", emojis: "🐦🥚", level: "medium" },
  { id: "cranium", title: "Cranium", emojis: "🧠🎨", level: "medium" },
  { id: "rush-hour", title: "Rush Hour", emojis: "🚗🚦", level: "medium" },
  { id: "mastermind", title: "Mastermind", emojis: "🧠🔐", level: "medium" },
  { id: "blokus", title: "Blokus", emojis: "🟦🧩", level: "medium" },
  { id: "sudoku", title: "Sudoku", emojis: "🔢🔳", level: "medium" },
  { id: "shogi", title: "Shogi", emojis: "⛩♟", level: "medium" },
  { id: "xiangqi", title: "Xiangqi", emojis: "🐉♟", level: "medium" },
  { id: "ludo", title: "Ludo", emojis: "🎲🏁", level: "medium" },
  { id: "mancala", title: "Mancala", emojis: "🕳🫘", level: "medium" },
  { id: "dungeons-and-dragons", title: "Dungeons & Dragons", emojis: "🐉🎲", level: "medium" },

  // ===== HARD (25) — modern hobby favorites =====
  { id: "terraforming-mars", title: "Terraforming Mars", emojis: "🚀🌡", level: "hard" },
  { id: "gloomhaven", title: "Gloomhaven", emojis: "⚔🏚", level: "hard" },
  { id: "scythe", title: "Scythe", emojis: "🌾🤖", level: "hard" },
  { id: "everdell", title: "Everdell", emojis: "🐿🌳", level: "hard" },
  { id: "root", title: "Root", emojis: "🦝🌲", level: "hard" },
  { id: "brass-birmingham", title: "Brass: Birmingham", emojis: "🏭🚂", level: "hard" },
  { id: "spirit-island", title: "Spirit Island", emojis: "🌋🏝", level: "hard" },
  { id: "gaia-project", title: "Gaia Project", emojis: "🌌🪐", level: "hard" },
  { id: "twilight-imperium", title: "Twilight Imperium", emojis: "👽👑", level: "hard" },
  { id: "arkham-horror", title: "Arkham Horror", emojis: "🐙📖", level: "hard" },
  { id: "blood-rage", title: "Blood Rage", emojis: "🪓⚡", level: "hard" },
  { id: "mysterium", title: "Mysterium", emojis: "👻🔮", level: "hard" },
  { id: "betrayal-at-house-on-the-hill", title: "Betrayal at House on the Hill", emojis: "🏚🔦", level: "hard" },
  { id: "seven-wonders", title: "7 Wonders", emojis: "🏛📜", level: "hard" },
  { id: "concordia", title: "Concordia", emojis: "🏺⚓", level: "hard" },
  { id: "agricola", title: "Agricola", emojis: "🚜🐖", level: "hard" },
  { id: "power-grid", title: "Power Grid", emojis: "🔌⚡", level: "hard" },
  { id: "puerto-rico", title: "Puerto Rico", emojis: "🌴☕", level: "hard" },
  { id: "lords-of-waterdeep", title: "Lords of Waterdeep", emojis: "🏰🧙", level: "hard" },
  { id: "cosmic-encounter", title: "Cosmic Encounter", emojis: "🪐👽", level: "hard" },
  { id: "small-world", title: "Small World", emojis: "🧝⚔", level: "hard" },
  { id: "tigris-and-euphrates", title: "Tigris & Euphrates", emojis: "🌊🏛", level: "hard" },
  { id: "el-grande", title: "El Grande", emojis: "🏰👑", level: "hard" },
  { id: "inis", title: "Inis", emojis: "🍀⚔", level: "hard" },
  { id: "photosynthesis", title: "Photosynthesis", emojis: "🌳☀", level: "hard" },

  // ===== IMPOSSIBLE (25) — real but tricky; gettable to a board-gamer =====
  { id: "food-chain-magnate", title: "Food Chain Magnate", emojis: "🍔📈", level: "impossible" },
  { id: "terra-mystica", title: "Terra Mystica", emojis: "🧙🏔", level: "impossible" },
  { id: "through-the-ages", title: "Through the Ages", emojis: "📜⏳", level: "impossible" },
  { id: "twilight-struggle", title: "Twilight Struggle", emojis: "🗽🐻", level: "impossible" },
  { id: "war-of-the-ring", title: "War of the Ring", emojis: "💍🌋", level: "impossible" },
  { id: "android-netrunner", title: "Android: Netrunner", emojis: "🤖💻", level: "impossible" },
  { id: "race-for-the-galaxy", title: "Race for the Galaxy", emojis: "🌌🃏", level: "impossible" },
  { id: "caverna", title: "Caverna", emojis: "⛏🧔", level: "impossible" },
  { id: "patchwork", title: "Patchwork", emojis: "🧵🟦", level: "impossible" },
  { id: "tzolkin", title: "Tzolk'in", emojis: "🗿⚙", level: "impossible" },
  { id: "keyflower", title: "Keyflower", emojis: "🗝🌸", level: "impossible" },
  { id: "hansa-teutonica", title: "Hansa Teutonica", emojis: "🪙🛤", level: "impossible" },
  { id: "le-havre", title: "Le Havre", emojis: "⚓🏗", level: "impossible" },
  { id: "troyes", title: "Troyes", emojis: "⛪🎲", level: "impossible" },
  { id: "orleans", title: "Orléans", emojis: "👝⚜", level: "impossible" },
  { id: "yokohama", title: "Yokohama", emojis: "🏮⚓", level: "impossible" },
  { id: "lisboa", title: "Lisboa", emojis: "🔥🏗", level: "impossible" },
  { id: "barrage", title: "Barrage", emojis: "💧⚡", level: "impossible" },
  { id: "teotihuacan", title: "Teotihuacan", emojis: "🌞🔺", level: "impossible" },
  { id: "dune-imperium", title: "Dune: Imperium", emojis: "🏜🪱", level: "impossible" },
  { id: "ark-nova", title: "Ark Nova", emojis: "🦏🏗", level: "impossible" },
  { id: "maracaibo", title: "Maracaibo", emojis: "🚢🌴", level: "impossible" },
  { id: "great-western-trail", title: "Great Western Trail", emojis: "🤠🐄", level: "impossible" },
  { id: "clank", title: "Clank!", emojis: "🐉💎", level: "impossible" },
  { id: "pax-pamir", title: "Pax Pamir", emojis: "🐪⛰", level: "impossible" },
];
