// E221 «Guess the Board Game by Emoji 2» — facts, one TRUE fact per id, <=70 chars
export const BOARDGAME_EMOJI_2_FACTS = {
  "connect-four": "Milton Bradley released it in 1974; drop discs to line up 4.",
  "dominoes": "Domino tiles trace back to 12th-century China.",
  "chinese-checkers": "Invented in Germany in 1892, despite its name.",
  "pictureka": "Hasbro's speed game has players spot hidden pictures fast.",
  "sequence": "Players place chips on cards to form rows of five.",
  "labyrinth": "Ravensburger's maze game has sliding tiles that shift paths.",
  "chutes-and-ladders": "Based on the ancient Indian game Snakes and Ladders.",
  "perfection": "Pop 25 shapes into slots before the timer's pop!",
  "trouble": "Its Pop-O-Matic dice bubble was patented in 1965.",
  "headbanz": "Players wear cards on headbands and guess what they are.",
  "apples-to-apples": "A green card is judged by matching red cards, party-style.",
  "kerplunk": "Pull sticks without dropping the marbles inside the tube.",
  "jacks": "An ancient street game played with a small ball and metal pieces.",
  "tumblin-dice": "Crokinole flicks discs across a wooden board into a hole.",
  "shoots-marbles": "One of the oldest games, played with small glass or clay balls.",
  "cards-against-humanity": "A crowdfunded 2011 party game of dark fill-in-the-blank humor.",
  "spoons": "Grab a spoon fast when you collect four of a kind.",
  "uno-stacko": "A wobbly tower game spun off from the card game Uno.",
  "memory": "Flip two cards at a time to find matching pairs.",
  "musical-chairs": "Walk around chairs and grab a seat when the music stops.",
  "simon": "Milton Bradley's 1978 electronic game repeats color sequences.",
  "jumanji": "A jungle-themed board game inspired by the 1995 film.",
  "domino-rally": "A toy line built for setting up giant toppling domino chains.",
  "old-maid": "Avoid being stuck holding the unmatched odd card.",
  "go-fish": "Ask opponents for cards to complete sets of four.",
  "go": "An ancient Chinese game where stones capture territory.",
  "liars-dice": "Players bluff about hidden dice under cups.",
  "sungka": "A Filipino mancala-style game using shells and a wooden board.",
  "farkle": "A dice game where you bank points or risk losing them all.",
  "bunco": "A social dice game played in rounds of three.",
  "qwirkle": "Match tiles by shape or color, like Scrabble with blocks.",
  "bananagrams": "Race to build a crossword grid from a banana-shaped pouch.",
  "telestrations": "A drawing telephone game where sketches get hilariously lost.",
  "5-second-rule": "Name three things in a category before five seconds run out.",
  "wits-and-wagers": "Players bet chips on the best guess to trivia questions.",
  "balderdash": "Invent fake definitions to trick opponents into believing you.",
  "outburst": "Shout answers to fill a category list before time runs out.",
  "boss-monster": "Players build dungeons to defeat invading heroes.",
  "king-of-tokyo": "Kaiju monsters battle for control of Tokyo using dice.",
  "sushi-go": "A fast card-drafting game about building sushi combos.",
  "love-letter": "A tiny 16-card game of deduction to reach the princess.",
  "hive": "A tile game with no board, built from interlocking bug pieces.",
  "onitama": "A minimalist strategy game inspired by martial arts moves.",
  "quoridor": "Block your opponent's path while racing to the other side.",
  "abalone": "Push marbles off a hexagonal board using in-line strength.",
  "camel-up": "Bet on racing camels that can stack on top of each other.",
  "coup": "A bluffing game where players claim false character powers.",
  "the-resistance": "A hidden-role game of spies and secret missions.",
  "just-one": "Give one-word clues, but duplicates get cancelled out.",
  "forbidden-island": "A cooperative game where players race to escape a sinking isle.",
  "viticulture": "Players manage a vineyard through the seasons of winemaking.",
  "century-spice-road": "Trade spices along caravan routes to grow your merchant empire.",
  "isle-of-skye": "Bid on tiles to build a Scottish kingdom, then sell what's left.",
  "castles-of-burgundy": "Roll dice to place hexagonal tiles and build a medieval estate.",
  "san-juan": "A card-based city-builder set in the world of Puerto Rico.",
  "arboretum": "Players plant trees in a path while hiding their best cards.",
  "tokaido": "Travel a scenic Japanese road, savoring the journey over speed.",
  "kingdomino": "Match terrain edges of domino tiles to build a kingdom.",
  "century-golem-edition": "A spice-trading game retold with golems and elemental gems.",
  "sagrada": "Draft dice to build a stained-glass window inspired by Gaudi.",
  "welcome-to": "Players draft house numbers to design their dream street.",
  "railroad-ink": "Draw dice-rolled routes to connect railways and roads.",
  "flamme-rouge": "A bicycle race game where riders alternate sprinting and drafting.",
  "colt-express": "Players place 3D figures on a train to plan a heist.",
  "raiders-of-the-north-sea": "Recruit crew and raid villages in a Viking worker-placement game.",
  "santorini": "Build towers and climb them on a Greek island-inspired board.",
  "the-castles-of-mad-king-ludwig": "Players build wild, sprawling castle rooms for a mad king.",
  "5-tribes": "Move meeples across an oasis to trigger powerful actions.",
  "modern-art": "Players auction paintings to inflate an artist's market value.",
  "chinatown": "Players negotiate and trade land plots to build businesses.",
  "targi": "A two-player desert trading game using a shared tile grid.",
  "istanbul": "Race through a bazaar collecting rubies for your merchant stall.",
  "the-crew": "A cooperative trick-taking game set on a space mission.",
  "the-quest-for-el-dorado": "Race through the jungle by building a deck of movement cards.",
  "gizmos": "Build chain-reaction machines using colored energy marbles.",
  "vinhos": "Manage a Portuguese winery from vineyard to wine expo.",
  "kanban": "Players manage an automotive factory's production line.",
  "brass-lancashire": "Build canals then railways during England's industrial revolution.",
  "vasco-da-gama": "A game of missions inspired by Portugal's age of explorers.",
  "the-gallerist": "Manage an art gallery, from acquiring works to running exhibitions.",
  "fields-of-arle": "A farming game set in a windswept German coastal region.",
  "caylus": "Players build a medieval French town around its castle.",
  "agricola-farmers": "Ora et Labora builds a monastery economy through prayer and work.",
  "russian-railroads": "Players lay track across Russia to expand rail networks.",
  "the-navigators": "Trading companies compete for goods in the age of sail.",
  "trajan": "A mancala-inspired game of managing ancient Rome's resources.",
  "amerigo": "Explore and settle a new world using a rondel and dice.",
  "bora-bora": "Players develop a Polynesian island through varied worker actions.",
  "kemet": "Egyptian-mythology armies battle for power and divine favor.",
  "rising-sun": "Japanese clans battle and form alliances for imperial control.",
  "cyclades": "Greek gods empower players' armies and mythic creatures.",
  "chaos-in-the-old-world": "Chaos gods vie to corrupt and conquer the Old World.",
  "eclipse": "Players build interstellar empires and battle for galactic sectors.",
  "space-empires": "A classic 4X game of exploring and conquering the galaxy.",
  "here-i-stand": "A history game of the Protestant Reformation's political struggle.",
  "paths-of-glory": "A card-driven wargame covering the First World War.",
  "advanced-squad-leader": "A detailed tactical WWII wargame famed for its rulebook depth.",
  "die-macher": "Players run political campaigns across German regional elections.",
  "container": "Players manufacture and trade goods in a shipping economy.",
  "hansa": "A trade network game inspired by the medieval Hanseatic League.",
};
