// E141 emoji-board-game facts — one verified <=70-char fact per game, shown on reveal.
export const BOARDGAME_EMOJI_FACTS = {
  // EASY
  "chess": "Ancient strategy game; the goal is to checkmate the king.",
  "monopoly": "1935 Parker Brothers classic of buying and trading property.",
  "scrabble": "1948 word game; score points by placing lettered tiles.",
  "jenga": "1983 game; pull wooden blocks without toppling the tower.",
  "battleship": "Guessing game of sinking your opponent's hidden fleet.",
  "clue": "1949 mystery game; deduce the killer, weapon, and room.",
  "risk": "1957 game of world conquest by armies and dice battles.",
  "catan": "1995 Klaus Teuber classic; settle and trade for resources.",
  "ticket-to-ride": "2004 Alan Moon game; claim train routes across a map.",
  "uno": "1971 card game; match colors and numbers to empty your hand.",
  "snakes-and-ladders": "Ancient race game of lucky ladders and unlucky snakes.",
  "candy-land": "1949 kids' race game along a colorful candy path.",
  "operation": "1965 game; remove ailments without buzzing the tweezers.",
  "trivial-pursuit": "1979 trivia game; collect wedges by answering questions.",
  "sorry": "Race game where you bump rivals' pawns back to start.",
  "yahtzee": "1956 dice game; roll five dice for scoring combinations.",
  "twister": "1966 party game; place hands and feet on colored dots.",
  "bingo": "Match called numbers on your card to complete a line.",
  "pictionary": "1985 party game; teammates guess your quick sketches.",
  "checkers": "Ancient game; jump and capture across a checkered board.",
  "tic-tac-toe": "Pencil game; line up three X's or O's to win.",
  "hangman": "Word game; guess letters before the drawing completes.",
  "the-game-of-life": "1960 Milton Bradley game; drive through life's milestones.",
  "guess-who": "1979 game; ask yes/no questions to find the mystery face.",
  "mouse-trap": "1963 game; build a wacky contraption to trap mice.",

  // MEDIUM
  "backgammon": "Ancient race game; bear off checkers guided by dice.",
  "mahjong": "Chinese tile game; build sets to a winning hand.",
  "carcassonne": "2000 tile game; place cities, roads, and meeples.",
  "pandemic": "2008 Matt Leacock co-op; cure four global diseases.",
  "dominion": "2008 Vaccarino game that launched the deck-builder genre.",
  "stratego": "Capture the flag by hidden ranks and bombs on a board.",
  "rummikub": "1950 tile game; arrange runs and groups of numbers.",
  "scattergories": "Name things in categories starting with a rolled letter.",
  "boggle": "1972 game; find words in a grid of shaken letter dice.",
  "taboo": "1989 game; describe a word without using the banned words.",
  "codenames": "2015 Vlaada Chvatil game; find agents from one-word clues.",
  "dixit": "2008 game; guess the card matching a dreamy clue.",
  "azul": "2017 Michael Kiesling game; draft colorful Portuguese tiles.",
  "splendor": "2014 Marc Andre game; collect gems to buy cards.",
  "wingspan": "2019 Elizabeth Hargrave game of attracting birds.",
  "cranium": "1998 party game blending trivia, art, and word play.",
  "rush-hour": "1996 puzzle; slide cars to free your red car from a jam.",
  "mastermind": "1970 game; crack the hidden code of colored pegs.",
  "blokus": "2000 game; place your color's pieces edge to edge.",
  "sudoku": "Logic puzzle; fill the grid so digits never repeat.",
  "shogi": "Japanese chess; captured pieces can return to play.",
  "xiangqi": "Chinese chess; capture the general across a river.",
  "ludo": "Race game from India's Pachisi; get four pawns home.",
  "mancala": "Ancient sowing game; scoop and drop seeds around pits.",
  "dungeons-and-dragons": "1974 Gygax and Arneson tabletop role-playing game.",

  // HARD
  "terraforming-mars": "2016 Jacob Fryxelius game of making Mars livable.",
  "gloomhaven": "2017 Isaac Childres campaign dungeon-crawler.",
  "scythe": "2016 Jamey Stegmaier game of farms and war mechs.",
  "everdell": "2018 worker-placement game in a woodland of critters.",
  "root": "2018 Cole Wehrle game of asymmetric woodland factions.",
  "brass-birmingham": "2018 economic game of the Industrial Revolution.",
  "spirit-island": "2017 co-op; island spirits repel colonial invaders.",
  "gaia-project": "2017 game; 14 factions terraform and settle space.",
  "twilight-imperium": "1997 epic game of galactic empire and politics.",
  "arkham-horror": "Lovecraftian co-op against cosmic horrors in Arkham.",
  "blood-rage": "2015 Eric Lang game of Vikings battling at Ragnarok.",
  "mysterium": "2015 co-op; a ghost sends visions to solve a murder.",
  "betrayal-at-house-on-the-hill": "2004 game; explore a haunted house till a traitor turns.",
  "seven-wonders": "2010 Antoine Bauza card-drafting civilization game.",
  "concordia": "2013 Mac Gerdts game of Roman Mediterranean trade.",
  "agricola": "2007 Uwe Rosenberg game of building up a farm.",
  "power-grid": "2004 Friese game; build networks to power cities.",
  "puerto-rico": "2002 Seyfarth game of colonial plantations and trade.",
  "lords-of-waterdeep": "2012 D&D worker-placement game of hiring agents.",
  "cosmic-encounter": "1977 game of alien powers battling for the galaxy.",
  "small-world": "2009 game; fantasy races conquer a too-small map.",
  "tigris-and-euphrates": "1997 Reiner Knizia game of Mesopotamian dynasties.",
  "el-grande": "1995 game; deploy caballeros for power in old Spain.",
  "inis": "2016 game of Celtic clans vying to be island king.",
  "photosynthesis": "2017 game; grow trees and collect sunlight to score.",

  // IMPOSSIBLE
  "food-chain-magnate": "2015 Splotter game of cut-throat fast-food empires.",
  "terra-mystica": "2012 game; 14 factions terraform to expand realms.",
  "through-the-ages": "2006 Vlaada Chvatil civilization-building card game.",
  "twilight-struggle": "2005 two-player game of the US-Soviet Cold War.",
  "war-of-the-ring": "2004 game reliving the Lord of the Rings conflict.",
  "android-netrunner": "Asymmetric card game of hackers vs. megacorporations.",
  "race-for-the-galaxy": "2007 Tom Lehmann card game of building space empires.",
  "caverna": "2013 Uwe Rosenberg game of dwarven cave farming.",
  "patchwork": "2014 Uwe Rosenberg two-player quilt-building puzzle.",
  "tzolkin": "2012 game; Mayan workers ride giant turning gears.",
  "keyflower": "2012 game; win tiles at auction to build a village.",
  "hansa-teutonica": "2009 game of building medieval trade networks.",
  "le-havre": "2008 Uwe Rosenberg game of harbor commerce.",
  "troyes": "2010 game; use dice as workers in a medieval city.",
  "orleans": "2014 Stockhausen bag-building game of medieval France.",
  "yokohama": "2016 game of building trade in Meiji-era Japan.",
  "lisboa": "2017 Vital Lacerda game of rebuilding Lisbon.",
  "barrage": "2019 game; build Alpine dams for hydroelectric power.",
  "teotihuacan": "2018 Tascini game; worker dice build a Mesoamerican city.",
  "dune-imperium": "2020 Paul Dennen deck-building game set on Arrakis.",
  "ark-nova": "2021 Mathias Wigge game of designing a modern zoo.",
  "maracaibo": "2019 Alexander Pfister game of Caribbean voyages.",
  "great-western-trail": "2016 Pfister game of driving cattle to Kansas City.",
  "clank": "2016 Paul Dennen deck-builder of dungeon-heist theft.",
  "pax-pamir": "2019 Cole Wehrle game of the Afghan Great Game.",
};
