// «Guess the Boat or Ship» — GuessSync · E55 · 100 vessel TYPES (25/tier) · real photos from Wikimedia Commons
// Tiered by real-world recognizability: easy (Sailboat/Submarine/Kayak) → impossible (Xebec/Caballito/Mtepe-class traditional craft).
export const BOATS = [
  // EASY (25) — household-name vessel types
  { slug: "sailboat", name: "Sailboat", level: "easy" },
  { slug: "cruiseship", name: "Cruise Ship", level: "easy" },
  { slug: "submarine", name: "Submarine", level: "easy" },
  { slug: "kayak", name: "Kayak", level: "easy" },
  { slug: "canoe", name: "Canoe", level: "easy" },
  { slug: "yacht", name: "Yacht", level: "easy" },
  { slug: "ferry", name: "Ferry", level: "easy" },
  { slug: "aircraftcarrier", name: "Aircraft Carrier", level: "easy" },
  { slug: "tugboat", name: "Tugboat", level: "easy" },
  { slug: "gondola", name: "Gondola", level: "easy" },
  { slug: "speedboat", name: "Speedboat", level: "easy" },
  { slug: "rowboat", name: "Rowboat", level: "easy" },
  { slug: "catamaran", name: "Catamaran", level: "easy" },
  { slug: "jetski", name: "Jet Ski", level: "easy" },
  { slug: "cargoship", name: "Cargo Ship", level: "easy" },
  { slug: "fishingtrawler", name: "Fishing Trawler", level: "easy" },
  { slug: "pirateship", name: "Pirate Ship", level: "easy" },
  { slug: "raft", name: "Raft", level: "easy" },
  { slug: "lifeboat", name: "Lifeboat", level: "easy" },
  { slug: "houseboat", name: "Houseboat", level: "easy" },
  { slug: "oiltanker", name: "Oil Tanker", level: "easy" },
  { slug: "pontoonboat", name: "Pontoon Boat", level: "easy" },
  { slug: "paddlesteamer", name: "Paddle Steamer", level: "easy" },
  { slug: "hovercraft", name: "Hovercraft", level: "easy" },
  { slug: "inflatableboat", name: "Inflatable Boat", level: "easy" },
  // MEDIUM (25)
  { slug: "trimaran", name: "Trimaran", level: "medium" },
  { slug: "barge", name: "Barge", level: "medium" },
  { slug: "schooner", name: "Schooner", level: "medium" },
  { slug: "clipper", name: "Clipper", level: "medium" },
  { slug: "icebreaker", name: "Icebreaker", level: "medium" },
  { slug: "containership", name: "Container Ship", level: "medium" },
  { slug: "bulkcarrier", name: "Bulk Carrier", level: "medium" },
  { slug: "destroyer", name: "Destroyer", level: "medium" },
  { slug: "frigate", name: "Frigate", level: "medium" },
  { slug: "battleship", name: "Battleship", level: "medium" },
  { slug: "dragonboat", name: "Dragon Boat", level: "medium" },
  { slug: "outriggercanoe", name: "Outrigger Canoe", level: "medium" },
  { slug: "windsurfer", name: "Windsurf Board", level: "medium" },
  { slug: "airboat", name: "Airboat", level: "medium" },
  { slug: "dukw", name: "Amphibious DUKW", level: "medium" },
  { slug: "cabincruiser", name: "Cabin Cruiser", level: "medium" },
  { slug: "rib", name: "Rigid Inflatable Boat", level: "medium" },
  { slug: "bassboat", name: "Bass Boat", level: "medium" },
  { slug: "paddleboard", name: "Paddleboard", level: "medium" },
  { slug: "pedalo", name: "Pedal Boat", level: "medium" },
  { slug: "narrowboat", name: "Narrowboat", level: "medium" },
  { slug: "cutter", name: "Coast Guard Cutter", level: "medium" },
  { slug: "riverboat", name: "Riverboat", level: "medium" },
  { slug: "whaleboat", name: "Whaleboat", level: "medium" },
  { slug: "dredger", name: "Dredger", level: "medium" },
  // HARD (25) — specialist / classic-rig / historic vessels
  { slug: "junk", name: "Junk", level: "hard" },
  { slug: "brigantine", name: "Brigantine", level: "hard" },
  { slug: "brig", name: "Brig", level: "hard" },
  { slug: "ketch", name: "Ketch", level: "hard" },
  { slug: "yawl", name: "Yawl", level: "hard" },
  { slug: "sloop", name: "Sloop", level: "hard" },
  { slug: "coracle", name: "Coracle", level: "hard" },
  { slug: "punt", name: "Punt", level: "hard" },
  { slug: "scow", name: "Scow", level: "hard" },
  { slug: "skiff", name: "Skiff", level: "hard" },
  { slug: "jonboat", name: "Jon Boat", level: "hard" },
  { slug: "wherry", name: "Wherry", level: "hard" },
  { slug: "cog", name: "Cog", level: "hard" },
  { slug: "carrack", name: "Carrack", level: "hard" },
  { slug: "longship", name: "Longship", level: "hard" },
  { slug: "trireme", name: "Trireme", level: "hard" },
  { slug: "catboat", name: "Catboat", level: "hard" },
  { slug: "hydrofoil", name: "Hydrofoil", level: "hard" },
  { slug: "fireboat", name: "Fireboat", level: "hard" },
  { slug: "pilotboat", name: "Pilot Boat", level: "hard" },
  { slug: "shipoftheline", name: "Ship of the Line", level: "hard" },
  { slug: "galley", name: "Galley", level: "hard" },
  { slug: "sternwheeler", name: "Sternwheeler", level: "hard" },
  { slug: "trawleryacht", name: "Trawler Yacht", level: "hard" },
  { slug: "gig", name: "Rowing Gig", level: "hard" },
  // IMPOSSIBLE (25) — obscure / historic / regional traditional craft
  { slug: "dhow", name: "Dhow", level: "impossible" },
  { slug: "felucca", name: "Felucca", level: "impossible" },
  { slug: "sampan", name: "Sampan", level: "impossible" },
  { slug: "pirogue", name: "Pirogue", level: "impossible" },
  { slug: "xebec", name: "Xebec", level: "impossible" },
  { slug: "caravel", name: "Caravel", level: "impossible" },
  { slug: "dhoni", name: "Dhoni", level: "impossible" },
  { slug: "umiak", name: "Umiak", level: "impossible" },
  { slug: "currach", name: "Currach", level: "impossible" },
  { slug: "jangada", name: "Jangada", level: "impossible" },
  { slug: "reedboat", name: "Reed Boat", level: "impossible" },
  { slug: "proa", name: "Proa", level: "impossible" },
  { slug: "waka", name: "Waka", level: "impossible" },
  { slug: "sandolo", name: "Sandolo", level: "impossible" },
  { slug: "bragozzo", name: "Bragozzo", level: "impossible" },
  { slug: "moliceiro", name: "Moliceiro", level: "impossible" },
  { slug: "baghlah", name: "Baghlah", level: "impossible" },
  { slug: "sambuk", name: "Sambuk", level: "impossible" },
  { slug: "vinta", name: "Vinta", level: "impossible" },
  { slug: "bangka", name: "Bangka", level: "impossible" },
  { slug: "jukung", name: "Jukung", level: "impossible" },
  { slug: "tongkang", name: "Tongkang", level: "impossible" },
  { slug: "caballito", name: "Caballito de Totora", level: "impossible" },
  { slug: "mokoro", name: "Mokoro", level: "impossible" },
  { slug: "shikara", name: "Shikara", level: "impossible" },
];
