// «Guess the Boat or Ship» — GuessSync · E55 · did-you-know facts, ≤70 chars, verified true (use / origin).
export const BOAT_FACTS = {
  // EASY
  "sailboat": "Uses cloth sails to turn wind into forward motion",
  "cruiseship": "A floating hotel built for holidays, not for cargo",
  "submarine": "Warship that dives and travels beneath the surface",
  "kayak": "A paddler sits low and uses a double-bladed paddle",
  "canoe": "Open-topped craft paddled with a single-bladed paddle",
  "yacht": "A sail or motor boat used mainly for leisure cruising",
  "ferry": "Carries people and vehicles on short set crossings",
  "aircraftcarrier": "A warship whose flat deck launches and lands planes",
  "tugboat": "Small but powerful boat that pushes and tows big ships",
  "gondola": "Flat-bottomed rowing boat of the canals of Venice",
  "speedboat": "A small motorboat built for high-speed running",
  "rowboat": "A simple boat moved by pulling on a pair of oars",
  "catamaran": "Has twin parallel hulls for a stable, fast ride",
  "jetski": "A stand or sit personal watercraft you ride like a bike",
  "cargoship": "Hauls goods and freight across the world's oceans",
  "fishingtrawler": "Drags large nets behind it to catch fish at sea",
  "pirateship": "The armed sailing ship of legendary sea raiders",
  "raft": "A flat floating platform, often of logs lashed together",
  "lifeboat": "Kept aboard or ashore to rescue people in danger",
  "houseboat": "A boat built to be lived in as a floating home",
  "oiltanker": "A huge ship that carries crude oil in bulk tanks",
  "pontoonboat": "A flat deck floating on sealed metal tubes",
  "paddlesteamer": "Driven by steam-powered paddle wheels on its sides",
  "hovercraft": "Rides on a cushion of air over water or land",
  "inflatableboat": "A light boat with air-filled tubes for its sides",
  // MEDIUM
  "trimaran": "Has one main hull flanked by two smaller outer hulls",
  "barge": "A flat freight boat for canals and inland rivers",
  "schooner": "A sailing ship with two or more fore-and-aft masts",
  "clipper": "A fast 1800s sailing ship built for the tea trade",
  "icebreaker": "A strong ship that smashes a path through sea ice",
  "containership": "Carries stacked steel boxes of cargo across oceans",
  "bulkcarrier": "Ships loose cargo like grain, coal and ore in bulk",
  "destroyer": "A fast, agile warship that escorts larger fleets",
  "frigate": "A mid-sized warship used for patrol and escort duty",
  "battleship": "A heavily armored warship with huge gun turrets",
  "dragonboat": "A long paddled racing boat with a carved dragon head",
  "outriggercanoe": "A canoe with a side float for balance at sea",
  "windsurfer": "A board with a sail you steer by hand while standing",
  "airboat": "A flat boat pushed by a large aircraft-style fan",
  "dukw": "A six-wheeled amphibious truck that swims and drives",
  "cabincruiser": "A motorboat with an enclosed cabin for overnighting",
  "rib": "A rigid hull fitted with tough inflatable side tubes",
  "bassboat": "A low freshwater boat built for angling for bass",
  "paddleboard": "A wide board you stand on and move with a long paddle",
  "pedalo": "A small leisure boat driven by foot pedals",
  "narrowboat": "A slim boat built to fit Britain's narrow canals",
  "cutter": "A patrol vessel used by the coast guard at sea",
  "riverboat": "A shallow craft that carries trade along rivers",
  "whaleboat": "A slim double-ended rowing boat once used to hunt whales",
  "dredger": "A ship that scoops mud to deepen harbors and channels",
  // HARD
  "junk": "An ancient Chinese sailing ship with battened sails",
  "brigantine": "A two-masted ship, square-rigged only on the foremast",
  "brig": "A two-masted ship square-rigged on both masts",
  "ketch": "A two-masted sailboat with a smaller mast near the stern",
  "yawl": "Like a ketch but its rear mast sits behind the rudder",
  "sloop": "A single-masted sailboat with one mainsail and a jib",
  "coracle": "A tiny round basket boat covered in a waterproof skin",
  "punt": "A flat boat pushed along by a long pole on the riverbed",
  "scow": "A flat, blunt-ended boat for hauling bulk loads",
  "skiff": "A small light open boat rowed or driven by one person",
  "jonboat": "A flat aluminum boat for calm rivers and lakes",
  "wherry": "A light rowing boat once used to ferry city passengers",
  "cog": "A round medieval trading ship with a single square sail",
  "carrack": "A large 1400s ocean sailing ship with high fore-castles",
  "longship": "The long, narrow warship rowed by the Vikings",
  "trireme": "An ancient war galley rowed by three banks of oars",
  "catboat": "A wide single-sail boat with its mast right at the bow",
  "hydrofoil": "Rises up on underwater wings to skim above the water",
  "fireboat": "A boat with powerful pumps to fight fires on the water",
  "pilotboat": "A fast boat that carries harbor pilots out to ships",
  "shipoftheline": "A sail warship built to fight in a battle line of guns",
  "galley": "A long warship driven mainly by banks of rowers",
  "sternwheeler": "A riverboat driven by one paddle wheel at the stern",
  "trawleryacht": "A cruising yacht styled after a sturdy fishing trawler",
  "gig": "A slim, light rowing boat raced by teams of oarsmen",
  // IMPOSSIBLE
  "dhow": "A traditional Arab sailing ship with triangular sails",
  "felucca": "A wooden sailing boat of the Nile with a lateen sail",
  "sampan": "A small flat Asian boat for rivers and coastal waters",
  "pirogue": "A narrow dugout canoe used in African and Cajun waters",
  "xebec": "A three-masted Mediterranean ship used by corsairs",
  "caravel": "A small nimble ship Portuguese explorers sailed",
  "dhoni": "A traditional wooden boat of the Maldive islands",
  "umiak": "An open Arctic boat framed in wood and covered in skin",
  "currach": "An Irish boat of tarred canvas over a wooden frame",
  "jangada": "A log sailing raft used by Brazilian coast fishermen",
  "reedboat": "A boat woven from bundles of dried reeds or rushes",
  "proa": "A Pacific sailing canoe with a single balancing float",
  "waka": "A Maori canoe, some carved for war from a single tree",
  "sandolo": "A slim flat rowing boat of the Venetian lagoon",
  "bragozzo": "A flat-bottomed sailing fishing boat of the Adriatic",
  "moliceiro": "A colourful Portuguese boat once used to gather seaweed",
  "baghlah": "A large old Arab deep-sea trading dhow",
  "sambuk": "A wooden dhow with a high stern, sailed in the Red Sea",
  "vinta": "A colourful outrigger sailboat of the Philippines",
  "bangka": "A Filipino outrigger canoe used for fishing and travel",
  "jukung": "A small wooden outrigger fishing canoe from Bali",
  "tongkang": "A wooden cargo boat once common in Southeast Asia",
  "caballito": "A reed surf-craft Peruvian fishermen have ridden for ages",
  "mokoro": "A dugout canoe poled through Botswana's Okavango Delta",
  "shikara": "A carved wooden boat rowed on the lakes of Kashmir",
};
