// E200 book-emoji facts — one verified <=70-char fact per book, shown on reveal.
export const BOOK_EMOJI_4_FACTS = {
  "sleeping-beauty": "A princess sleeps 100 years until true love's kiss wakes her.",
  "beauty-and-the-beast": "A cursed prince is freed from beast form by a woman's love.",
  "rapunzel": "A girl with magical long hair is locked in a tall tower.",
  "hansel-and-gretel": "Two siblings escape a witch's house made of candy.",
  "the-little-mermaid": "A mermaid trades her voice for legs to find true love.",
  "the-ugly-duckling": "A mocked cygnet grows into a graceful swan, by Andersen.",
  "puss-in-boots": "A clever booted cat wins his master a fortune and a castle.",
  "the-three-little-pigs": "A wolf huffs and puffs to blow down two pigs' flimsy houses.",
  "jack-and-the-beanstalk": "A boy climbs a giant beanstalk to a castle in the clouds.",
  "little-red-riding-hood": "A girl in a red cloak meets a wolf on the way to grandma's.",
  "the-boy-who-cried-wolf": "An Aesop fable about a shepherd whose false alarms backfire.",
  "the-tortoise-and-the-hare": "Aesop's fable where the slow, steady tortoise wins the race.",
  "pippi-longstocking": "Astrid Lindgren's super-strong, freckled Swedish girl, 1945.",
  "mary-poppins": "A magical nanny with a flying umbrella, by P. L. Travers.",
  "the-hound-of-the-baskervilles": "Sherlock Holmes hunts a spectral hound on the moor.",
  "alice-through-the-looking-glass": "Alice steps through a mirror into a chess-themed world.",
  "the-house-at-pooh-corner": "A. A. Milne's second Winnie-the-Pooh storybook, 1928.",
  "the-velveteen-rabbit": "A toy rabbit becomes real through a boy's love, 1922.",
  "harry-potter-chamber-of-secrets": "A basilisk lurks while a cursed diary controls a student.",
  "harry-potter-goblet-of-fire": "Harry is entered into the deadly Triwizard Tournament.",
  "harry-potter-deathly-hallows": "The final Harry Potter book, released in 2007.",
  "prince-caspian": "Narnia's second book: the Pevensies return to help a prince.",
  "voyage-of-the-dawn-treader": "Narnia's third book follows a ship sailing to world's end.",
  "fellowship-of-the-ring": "The first volume of Tolkien's Lord of the Rings, 1954.",
  "return-of-the-king": "The third and final volume of The Lord of the Rings.",
  "the-adventures-of-tom-sawyer": "Mark Twain's 1876 tale of a mischievous boy on the Mississippi.",
  "little-women": "Louisa May Alcott's 1868 novel of the four March sisters.",
  "the-phantom-of-the-opera": "Gaston Leroux's 1910 tale of a masked figure under a theatre.",
  "the-man-in-the-iron-mask": "Dumas's tale of a prisoner hidden behind an iron mask.",
  "the-mysterious-island": "Jules Verne's 1874 tale of castaways surviving by invention.",
  "the-invisible-man": "H. G. Wells's 1897 tale of a scientist who turns invisible.",
  "heidi": "Johanna Spyri's 1881 novel of a girl in the Swiss Alps.",
  "swiss-family-robinson": "A shipwrecked family builds a home on a tropical island.",
  "a-little-princess": "Frances Hodgson Burnett's 1905 tale of a girl reduced to a servant.",
  "the-railway-children": "E. Nesbit's 1906 novel of children living by a railway line.",
  "the-magicians-nephew": "Narnia's prequel book, telling how Narnia was created.",
  "the-last-battle": "The seventh and final book of C. S. Lewis's Narnia series.",
  "the-trumpet-of-the-swan": "E. B. White's 1970 tale of a voiceless trumpeter swan.",
  "bambi": "Felix Salten's 1923 novel about a young deer in the forest.",
  "pollyanna": "Eleanor Porter's 1913 novel about an incurably optimistic girl.",
  "anne-of-avonlea": "The 1909 sequel to Anne of Green Gables, set in Canada.",
  "little-lord-fauntleroy": "Frances Hodgson Burnett's 1886 tale of a boy who becomes an earl.",
  "doctor-dolittle": "Hugh Lofting's 1920 tales of a doctor who talks to animals.",
  "king-solomons-mines": "H. Rider Haggard's 1885 adventure hunting lost treasure.",
  "little-house-on-the-prairie": "Laura Ingalls Wilder's pioneer-family series, begun 1932.",
  "the-nutcracker": "E. T. A. Hoffmann's 1816 tale that inspired the ballet.",
  "anne-of-the-island": "The third Anne of Green Gables book, following Anne to college.",
  "five-on-a-treasure-island": "Enid Blyton's 1942 book, the first Famous Five adventure.",
  "the-secret-of-the-old-clock": "The first Nancy Drew mystery novel, published in 1930.",
  "the-prisoner-of-zenda": "Anthony Hope's 1894 swashbuckling tale of a royal impostor.",
  "the-mill-on-the-floss": "George Eliot's 1860 novel set around a family-run mill.",
  "silas-marner": "George Eliot's 1861 novel of a weaver who hoards gold coins.",
  "adam-bede": "George Eliot's 1859 debut novel about a village carpenter.",
  "north-and-south": "Elizabeth Gaskell's 1854 novel of industrial England.",
  "cranford": "Elizabeth Gaskell's 1853 novel of a small English town's women.",
  "barchester-towers": "Anthony Trollope's 1857 comic novel of cathedral-town politics.",
  "the-warden": "The first novel in Trollope's Barsetshire Chronicles, 1855.",
  "barnaby-rudge": "Dickens's 1841 novel set during the 1780 Gordon Riots.",
  "martin-chuzzlewit": "Charles Dickens's 1844 novel skewering greed and hypocrisy.",
  "nicholas-nickleby": "Dickens's 1839 novel exposing abusive boarding schools.",
  "the-old-curiosity-shop": "Dickens's 1841 novel following young Little Nell.",
  "dombey-and-son": "Dickens's 1848 novel about a proud merchant and his heir.",
  "little-dorrit": "Dickens's 1857 novel partly set in a debtors' prison.",
  "hard-times": "Dickens's 1854 novel critiquing industrial-age utilitarianism.",
  "our-mutual-friend": "Dickens's last complete novel, published in 1865.",
  "the-pickwick-papers": "Dickens's comic 1836 debut novel about a gentlemen's club.",
  "wives-and-daughters": "Elizabeth Gaskell's unfinished final novel, published 1866.",
  "framley-parsonage": "Trollope's 1861 Barsetshire novel about debt and clergy life.",
  "the-way-we-live-now": "Trollope's 1875 satire of financial speculation and fraud.",
  "can-you-forgive-her": "The first of Trollope's Palliser political novels, 1864.",
  "phineas-finn": "Trollope's 1869 novel following an Irish MP's career.",
  "he-knew-he-was-right": "Trollope's 1869 novel of a marriage ruined by jealousy.",
  "the-eustace-diamonds": "Trollope's 1871 novel centred on a disputed necklace.",
  "cousin-bette": "Honoré de Balzac's 1846 novel of a spinster's slow revenge.",
  "pere-goriot": "Balzac's 1835 novel of a father's ruinous love for his daughters.",
  "confessions-rousseau": "Jean-Jacques Rousseau's candid autobiography, published 1782.",
  "candide": "Voltaire's 1759 satire mocking blind philosophical optimism.",
  "gargantua-and-pantagruel": "Rabelais's comic 16th-century tales of two giant kings.",
  "the-decameron": "Boccaccio's tales told by ten people fleeing the Black Death.",
  "metamorphoses-ovid": "Ovid's Latin poem chronicling myths of transformation.",
  "orlando-furioso": "Ariosto's 16th-century Italian epic of a knight driven mad.",
  "jerusalem-delivered": "Torquato Tasso's 1581 epic poem of the First Crusade.",
  "the-faerie-queene": "Edmund Spenser's allegorical epic poem, published 1590.",
  "njals-saga": "A 13th-century Icelandic saga of a feud turned bloody.",
  "the-prose-edda": "Snorri Sturluson's 13th-century guide to Norse mythology.",
  "the-mabinogion": "A collection of medieval Welsh mythological tales.",
  "le-morte-darthur": "Thomas Malory's 1485 compilation of Arthurian legend.",
  "parzival": "Wolfram von Eschenbach's medieval epic of the Grail quest.",
  "the-song-of-roland": "The oldest surviving major work of French literature.",
  "poema-de-mio-cid": "A medieval Spanish epic poem about the hero El Cid.",
  "egils-saga": "An Icelandic saga chronicling a Viking poet-warrior's life.",
  "the-kalevala": "Elias Lönnrot's 1835 compiled Finnish national epic.",
  "popol-vuh": "A sacred Mayan text recounting creation and hero twins.",
  "the-epic-of-gilgamesh": "An ancient Mesopotamian epic, among the oldest works of literature.",
  "the-ramayana": "An ancient Sanskrit epic about Prince Rama's exile and war.",
  "the-mahabharata": "An ancient Sanskrit epic containing the Bhagavad Gita.",
  "journey-to-the-west": "A 16th-century Chinese classic starring the Monkey King.",
  "dream-of-the-red-chamber": "Cao Xueqin's 18th-century classic Chinese family saga.",
  "the-tale-of-the-heike": "A medieval Japanese epic of the fall of the Heike clan.",
  "the-pillow-book": "Sei Shōnagon's personal musings from the Heian imperial court.",
};
