// E200 «Guess the Book by Emoji 4» — 100 books · 25/tier
// VO: sfx/e200-<id>.wav
export const BOOK_EMOJI_4 = [

  // ===== EASY (25) =====
  { id: "sleeping-beauty", title: "Sleeping Beauty", emojis: "👸💤", level: "easy" },
  { id: "beauty-and-the-beast", title: "Beauty and the Beast", emojis: "🌹👹", level: "easy" },
  { id: "rapunzel", title: "Rapunzel", emojis: "👸🗼", level: "easy" },
  { id: "hansel-and-gretel", title: "Hansel and Gretel", emojis: "🍬🏠", level: "easy" },
  { id: "the-little-mermaid", title: "The Little Mermaid", emojis: "🧜🌊", level: "easy" },
  { id: "the-ugly-duckling", title: "The Ugly Duckling", emojis: "🦆🦢", level: "easy" },
  { id: "puss-in-boots", title: "Puss in Boots", emojis: "🐈👢", level: "easy" },
  { id: "the-three-little-pigs", title: "The Three Little Pigs", emojis: "🐺🏠", level: "easy" },
  { id: "jack-and-the-beanstalk", title: "Jack and the Beanstalk", emojis: "🌱🏰", level: "easy" },
  { id: "little-red-riding-hood", title: "Little Red Riding Hood", emojis: "🧺🐺", level: "easy" },
  { id: "the-boy-who-cried-wolf", title: "The Boy Who Cried Wolf", emojis: "🐑🐺", level: "easy" },
  { id: "the-tortoise-and-the-hare", title: "The Tortoise and the Hare", emojis: "🐢🐇", level: "easy" },
  { id: "pippi-longstocking", title: "Pippi Longstocking", emojis: "🧦👧", level: "easy" },
  { id: "mary-poppins", title: "Mary Poppins", emojis: "☂👜", level: "easy" },
  { id: "the-hound-of-the-baskervilles", title: "The Hound of the Baskervilles", emojis: "🐶👻", level: "easy" },
  { id: "alice-through-the-looking-glass", title: "Through the Looking-Glass", emojis: "🪞🐇", level: "easy" },
  { id: "the-house-at-pooh-corner", title: "The House at Pooh Corner", emojis: "🐻🏠", level: "easy" },
  { id: "the-velveteen-rabbit", title: "The Velveteen Rabbit", emojis: "🐇❤", level: "easy" },
  { id: "harry-potter-chamber-of-secrets", title: "Harry Potter and the Chamber of Secrets", emojis: "🐍📓", level: "easy" },
  { id: "harry-potter-goblet-of-fire", title: "Harry Potter and the Goblet of Fire", emojis: "🏆🔥", level: "easy" },
  { id: "harry-potter-deathly-hallows", title: "Harry Potter and the Deathly Hallows", emojis: "🔺💀", level: "easy" },
  { id: "prince-caspian", title: "Prince Caspian", emojis: "🦁⚔", level: "easy" },
  { id: "voyage-of-the-dawn-treader", title: "The Voyage of the Dawn Treader", emojis: "⛵🐉", level: "easy" },
  { id: "fellowship-of-the-ring", title: "The Fellowship of the Ring", emojis: "💍🚶", level: "easy" },
  { id: "return-of-the-king", title: "The Return of the King", emojis: "👑⚔", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "the-adventures-of-tom-sawyer", title: "The Adventures of Tom Sawyer", emojis: "🖌🛶", level: "medium" },
  { id: "little-women", title: "Little Women", emojis: "✍👗", level: "medium" },
  { id: "the-phantom-of-the-opera", title: "The Phantom of the Opera", emojis: "🎭👻", level: "medium" },
  { id: "the-man-in-the-iron-mask", title: "The Man in the Iron Mask", emojis: "🎭🔒", level: "medium" },
  { id: "the-mysterious-island", title: "The Mysterious Island", emojis: "🏝⚙", level: "medium" },
  { id: "the-invisible-man", title: "The Invisible Man", emojis: "👤🥼", level: "medium" },
  { id: "heidi", title: "Heidi", emojis: "🐐⛰", level: "medium" },
  { id: "swiss-family-robinson", title: "Swiss Family Robinson", emojis: "🌴🏝", level: "medium" },
  { id: "a-little-princess", title: "A Little Princess", emojis: "👸🕯", level: "medium" },
  { id: "the-railway-children", title: "The Railway Children", emojis: "🚃👧", level: "medium" },
  { id: "the-magicians-nephew", title: "The Magician's Nephew", emojis: "🎩🌳", level: "medium" },
  { id: "the-last-battle", title: "The Last Battle", emojis: "🦁🔥", level: "medium" },
  { id: "the-trumpet-of-the-swan", title: "The Trumpet of the Swan", emojis: "🎺🦢", level: "medium" },
  { id: "bambi", title: "Bambi", emojis: "🦌🌲", level: "medium" },
  { id: "pollyanna", title: "Pollyanna", emojis: "😀☀", level: "medium" },
  { id: "anne-of-avonlea", title: "Anne of Avonlea", emojis: "👧🍁", level: "medium" },
  { id: "little-lord-fauntleroy", title: "Little Lord Fauntleroy", emojis: "🎩👦", level: "medium" },
  { id: "doctor-dolittle", title: "Doctor Dolittle", emojis: "🦜🩺", level: "medium" },
  { id: "king-solomons-mines", title: "King Solomon's Mines", emojis: "💎🗺", level: "medium" },
  { id: "little-house-on-the-prairie", title: "Little House on the Prairie", emojis: "🌾🏠", level: "medium" },
  { id: "the-nutcracker", title: "The Nutcracker and the Mouse King", emojis: "🌰👑", level: "medium" },
  { id: "anne-of-the-island", title: "Anne of the Island", emojis: "👧🎓", level: "medium" },
  { id: "five-on-a-treasure-island", title: "Five on a Treasure Island", emojis: "🏝🔦", level: "medium" },
  { id: "the-secret-of-the-old-clock", title: "The Secret of the Old Clock", emojis: "🔍⏰", level: "medium" },
  { id: "the-prisoner-of-zenda", title: "The Prisoner of Zenda", emojis: "👑🗡", level: "medium" },

  // ===== HARD (25) =====
  { id: "the-mill-on-the-floss", title: "The Mill on the Floss", emojis: "⚙🌊", level: "hard" },
  { id: "silas-marner", title: "Silas Marner", emojis: "🧶💰", level: "hard" },
  { id: "adam-bede", title: "Adam Bede", emojis: "🔨👨", level: "hard" },
  { id: "north-and-south", title: "North and South", emojis: "🧭🏭", level: "hard" },
  { id: "cranford", title: "Cranford", emojis: "🏘👵", level: "hard" },
  { id: "barchester-towers", title: "Barchester Towers", emojis: "⛪🏰", level: "hard" },
  { id: "the-warden", title: "The Warden", emojis: "🔑⛪", level: "hard" },
  { id: "barnaby-rudge", title: "Barnaby Rudge", emojis: "🐦🔥", level: "hard" },
  { id: "martin-chuzzlewit", title: "Martin Chuzzlewit", emojis: "💰👴", level: "hard" },
  { id: "nicholas-nickleby", title: "Nicholas Nickleby", emojis: "🏫😢", level: "hard" },
  { id: "the-old-curiosity-shop", title: "The Old Curiosity Shop", emojis: "🏚👧", level: "hard" },
  { id: "dombey-and-son", title: "Dombey and Son", emojis: "🚂💼", level: "hard" },
  { id: "little-dorrit", title: "Little Dorrit", emojis: "🔑👧", level: "hard" },
  { id: "hard-times", title: "Hard Times", emojis: "🏭📊", level: "hard" },
  { id: "our-mutual-friend", title: "Our Mutual Friend", emojis: "💰🌊", level: "hard" },
  { id: "the-pickwick-papers", title: "The Pickwick Papers", emojis: "🎩🍺", level: "hard" },
  { id: "wives-and-daughters", title: "Wives and Daughters", emojis: "💍🩺", level: "hard" },
  { id: "framley-parsonage", title: "Framley Parsonage", emojis: "⛪💰", level: "hard" },
  { id: "the-way-we-live-now", title: "The Way We Live Now", emojis: "💰🚂", level: "hard" },
  { id: "can-you-forgive-her", title: "Can You Forgive Her?", emojis: "💔🗳", level: "hard" },
  { id: "phineas-finn", title: "Phineas Finn", emojis: "🏛🗳", level: "hard" },
  { id: "he-knew-he-was-right", title: "He Knew He Was Right", emojis: "💔🔒", level: "hard" },
  { id: "the-eustace-diamonds", title: "The Eustace Diamonds", emojis: "💎🔒", level: "hard" },
  { id: "cousin-bette", title: "Cousin Bette", emojis: "💔👵", level: "hard" },
  { id: "pere-goriot", title: "Père Goriot", emojis: "👴💔", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "confessions-rousseau", title: "Confessions", emojis: "📜😔", level: "impossible" },
  { id: "candide", title: "Candide", emojis: "🌍😀", level: "impossible" },
  { id: "gargantua-and-pantagruel", title: "Gargantua and Pantagruel", emojis: "🍗👑", level: "impossible" },
  { id: "the-decameron", title: "The Decameron", emojis: "🦠🏰", level: "impossible" },
  { id: "metamorphoses-ovid", title: "Metamorphoses", emojis: "🦋👤", level: "impossible" },
  { id: "orlando-furioso", title: "Orlando Furioso", emojis: "🐴⚔", level: "impossible" },
  { id: "jerusalem-delivered", title: "Jerusalem Delivered", emojis: "⛪⚔", level: "impossible" },
  { id: "the-faerie-queene", title: "The Faerie Queene", emojis: "👸🐉", level: "impossible" },
  { id: "njals-saga", title: "Njál's Saga", emojis: "🪓❄", level: "impossible" },
  { id: "the-prose-edda", title: "The Prose Edda", emojis: "📜⚡", level: "impossible" },
  { id: "the-mabinogion", title: "The Mabinogion", emojis: "🐴🛡", level: "impossible" },
  { id: "le-morte-darthur", title: "Le Morte d'Arthur", emojis: "⚔🗡", level: "impossible" },
  { id: "parzival", title: "Parzival", emojis: "🏆⚔", level: "impossible" },
  { id: "the-song-of-roland", title: "The Song of Roland", emojis: "📯⚔", level: "impossible" },
  { id: "poema-de-mio-cid", title: "Poema de Mio Cid", emojis: "🛡⚔", level: "impossible" },
  { id: "egils-saga", title: "Egil's Saga", emojis: "🪓📜", level: "impossible" },
  { id: "the-kalevala", title: "The Kalevala", emojis: "🎻❄", level: "impossible" },
  { id: "popol-vuh", title: "Popol Vuh", emojis: "🌽🏛", level: "impossible" },
  { id: "the-epic-of-gilgamesh", title: "The Epic of Gilgamesh", emojis: "🦁🌊", level: "impossible" },
  { id: "the-ramayana", title: "The Ramayana", emojis: "🏹👑", level: "impossible" },
  { id: "the-mahabharata", title: "The Mahabharata", emojis: "⚔🏹", level: "impossible" },
  { id: "journey-to-the-west", title: "Journey to the West", emojis: "🐒☁", level: "impossible" },
  { id: "dream-of-the-red-chamber", title: "Dream of the Red Chamber", emojis: "🏮💔", level: "impossible" },
  { id: "the-tale-of-the-heike", title: "The Tale of the Heike", emojis: "⚔🌸", level: "impossible" },
  { id: "the-pillow-book", title: "The Pillow Book", emojis: "✍🌙", level: "impossible" },
];
