// E229 «Guess the Book by Emoji 5» — one true fact per id, <=70 chars
export const BOOK_EMOJI5_FACTS = {
  "hamlet": "Shakespeare wrote Hamlet around 1600; it's his longest play.",
  "macbeth": "Shakespeare's shortest tragedy, written around 1606.",
  "jaws": "Peter Benchley's 1974 novel inspired Spielberg's 1975 film.",
  "murder-on-the-orient-express": "Agatha Christie wrote this Poirot novel in 1934.",
  "the-neverending-story": "Michael Ende published this German fantasy novel in 1979.",
  "fifty-shades-of-grey": "E.L. James's 2011 novel began as Twilight fan fiction.",
  "sense-and-sensibility": "Jane Austen's first published novel, released in 1811.",
  "persuasion": "Jane Austen's last completed novel, published in 1817.",
  "a-court-of-thorns-and-roses": "Sarah J. Maas began this fantasy series in 2015.",
  "fourth-wing": "Rebecca Yarros's dragon-rider novel topped charts in 2023.",
  "and-then-there-were-none": "Agatha Christie's 1939 novel is the best-selling mystery ever.",
  "the-song-of-achilles": "Madeline Miller won the Orange Prize for this 2011 novel.",
  "circe": "Madeline Miller's 2018 novel retells the witch of the Odyssey.",
  "cyrano-de-bergerac": "Edmond Rostand's play premiered in Paris in 1897.",
  "the-importance-of-being-earnest": "Oscar Wilde's comedy premiered in London in 1895.",
  "walden": "Henry David Thoreau published this 1854 memoir of pond life.",
  "on-the-origin-of-species": "Charles Darwin published his evolution theory in 1859.",
  "i-know-why-the-caged-bird-sings": "Maya Angelou's 1969 memoir was a National Book Award finalist.",
  "rich-dad-poor-dad": "Robert Kiyosaki self-published this finance book in 1997.",
  "how-to-win-friends-and-influence-people": "Dale Carnegie's 1936 book has sold over 30 million copies.",
  "the-stand": "Stephen King's 1978 epic centers on a deadly super-flu.",
  "the-three-body-problem": "Liu Cixin's 2008 novel won the 2015 Hugo Award.",
  "klara-and-the-sun": "Kazuo Ishiguro published this AI novel in 2021.",
  "long-walk-to-freedom": "Nelson Mandela's 1994 autobiography covers his 27 prison years.",
  "a-thousand-splendid-suns": "Khaled Hosseini published this Afghanistan novel in 2007.",
  "a-midsummer-nights-dream": "Shakespeare's comedy was written around 1595-96.",
  "the-tempest": "Believed to be Shakespeare's last solo-written play, c.1611.",
  "emma": "Jane Austen's 1815 novel follows a matchmaking heroine.",
  "divergent": "Veronica Roth published this dystopian YA novel in 2011.",
  "the-maze-runner": "James Dashner's dystopian novel was published in 2009.",
  "a-clash-of-kings": "George R.R. Martin's second Ice and Fire book, 1998.",
  "the-horse-and-his-boy": "C.S. Lewis published this Narnia novel in 1954.",
  "love-in-the-time-of-cholera": "Gabriel García Márquez published this novel in 1985.",
  "like-water-for-chocolate": "Laura Esquivel's Mexican novel was published in 1989.",
  "norwegian-wood": "Haruki Murakami's breakthrough novel was published in 1987.",
  "things-fall-apart": "Chinua Achebe's 1958 novel is Africa's most-read novel.",
  "white-tiger": "Aravind Adiga won the 2008 Booker Prize for this novel.",
  "the-namesake": "Jhumpa Lahiri published this debut novel in 2003.",
  "a-dolls-house": "Henrik Ibsen's play premiered in Copenhagen in 1879.",
  "pygmalion": "George Bernard Shaw's play premiered in Vienna in 1913.",
  "outliers": "Malcolm Gladwell coined the '10,000-hour rule' in this 2008 book.",
  "blink": "Malcolm Gladwell's 2005 book explores snap-judgment thinking.",
  "big-little-lies": "Liane Moriarty's 2014 novel became an HBO series in 2017.",
  "the-thursday-murder-club": "Richard Osman published this cozy mystery in 2020.",
  "the-night-circus": "Erin Morgenstern's debut fantasy novel came out in 2011.",
  "normal-people": "Sally Rooney's 2018 novel won the Costa Book Award.",
  "convenience-store-woman": "Sayaka Murata's novel won Japan's Akutagawa Prize in 2016.",
  "the-vegetarian": "Han Kang won the 2016 Booker International for this novel.",
  "a-study-in-scarlet": "Arthur Conan Doyle's 1887 novel introduced Sherlock Holmes.",
  "bird-box": "Josh Malerman's horror novel was published in 2014.",
  "king-lear": "Shakespeare's tragedy was first performed around 1606.",
  "othello": "Shakespeare's tragedy of jealousy was written around 1603.",
  "piranesi": "Susanna Clarke published this novel in 2020, 16 years after her first.",
  "jonathan-strange-and-mr-norrell": "Susanna Clarke's debut fantasy novel came out in 2004.",
  "mexican-gothic": "Silvia Moreno-Garcia published this horror novel in 2020.",
  "the-vanishing-half": "Brit Bennett's novel topped the 2020 bestseller lists.",
  "their-eyes-were-watching-god": "Zora Neale Hurston published this novel in 1937.",
  "native-son": "Richard Wright's novel shocked readers on release in 1940.",
  "the-bluest-eye": "Toni Morrison's debut novel was published in 1970.",
  "song-of-solomon": "Toni Morrison won the National Book Critics Circle Award in 1977.",
  "half-of-a-yellow-sun": "Chimamanda Ngozi Adichie set this 2006 novel in Biafra.",
  "purple-hibiscus": "Chimamanda Ngozi Adichie's debut novel came out in 2003.",
  "the-shadow-of-the-wind": "Carlos Ruiz Zafón set this 2001 novel in postwar Barcelona.",
  "kafka-on-the-shore": "Haruki Murakami published this novel in Japan in 2002.",
  "my-antonia": "Willa Cather published this prairie novel in 1918.",
  "tender-is-the-night": "F. Scott Fitzgerald published this novel in 1934.",
  "a-passage-to-india": "E.M. Forster published this novel in 1924.",
  "howards-end": "E.M. Forster published this English novel in 1910.",
  "sons-and-lovers": "D.H. Lawrence published this semi-autobiographical novel in 1913.",
  "lady-chatterleys-lover": "D.H. Lawrence's novel was banned in the UK until 1960.",
  "one-day-in-the-life-of-ivan-denisovich": "Solzhenitsyn published this gulag novel in 1962.",
  "interview-with-the-vampire": "Anne Rice published her debut vampire novel in 1976.",
  "salems-lot": "Stephen King's second novel about vampires came out in 1975.",
  "pet-sematary": "Stephen King published this horror novel in 1983.",
  "geralds-game": "Stephen King published this thriller novel in 1992.",
  "beyond-good-and-evil": "Friedrich Nietzsche published this philosophy work in 1886.",
  "thus-spoke-zarathustra": "Nietzsche wrote this philosophical novel in the 1880s.",
  "the-communist-manifesto": "Marx and Engels published this pamphlet in 1848.",
  "the-gulag-archipelago": "Solzhenitsyn published this exposé in 1973, leading to exile.",
  "cancer-ward": "Solzhenitsyn drew on his own cancer treatment for this 1968 novel.",
  "we": "Yevgeny Zamyatin's 1924 novel inspired George Orwell's 1984.",
  "oedipus-rex": "Sophocles' tragedy was first performed around 429 BC.",
  "antigone": "Sophocles wrote this tragedy around 441 BC.",
  "medea": "Euripides' tragedy premiered in Athens in 431 BC.",
  "the-bacchae": "Euripides wrote this tragedy shortly before his death, 405 BC.",
  "lysistrata": "Aristophanes' comedy premiered in Athens in 411 BC.",
  "snow-country": "Yasunari Kawabata published this novel in installments, 1935-47.",
  "the-wind-up-bird-chronicle": "Haruki Murakami published this novel in Japan in 1994.",
  "1q84": "Haruki Murakami's three-volume novel was published 2009-2010.",
  "soul-mountain": "Gao Xingjian's novel helped win him the 2000 Nobel Prize.",
  "wild-swans": "Jung Chang's family memoir was published in 1991.",
  "winesburg-ohio": "Sherwood Anderson published this story cycle in 1919.",
  "this-side-of-paradise": "F. Scott Fitzgerald's debut novel came out in 1920.",
  "orlando": "Virginia Woolf published this gender-shifting novel in 1928.",
  "the-waves": "Virginia Woolf published this experimental novel in 1931.",
  "women-in-love": "D.H. Lawrence published this novel in 1920.",
  "we-have-always-lived-in-the-castle": "Shirley Jackson's final novel was published in 1962.",
  "hyperion": "Dan Simmons' novel won the Hugo Award for Best Novel in 1990.",
  "station-eleven": "Emily St. John Mandel published this pandemic novel in 2014.",
  "nightwood": "Djuna Barnes published this modernist novel in 1936.",
};
