// E227 brand facts — one verified <=70-char fact per brand, shown on reveal.
export const BRAND_EMOJI5_FACTS = {
  "sony": "Japanese giant founded 1946; makes PlayStation consoles.",
  "toyota": "World's top-selling carmaker, founded in Japan in 1937.",
  "reeses": "Peanut-butter cups invented by H.B. Reese in Pennsylvania, 1928.",
  "starburst": "Fruit chews launched in the UK in 1960 as Opal Fruits.",
  "mattel": "US toy giant founded 1945; makes Barbie and Hot Wheels.",
  "xerox": "US firm whose name became a verb for photocopying.",
  "tropicana": "Orange-juice brand founded in Florida, USA, in 1947.",
  "capri-sun": "German pouch-drink brand launched in 1969.",
  "arizona": "US iced-tea brand famous for its 99-cent tall can.",
  "blizzard": "US studio behind Warcraft, founded in California, 1991.",
  "logitech": "Swiss maker of computer mice and keyboards, founded 1981.",
  "nerds": "Tiny crunchy candy launched by Willy Wonka Candy Co. in 1983.",
  "sour-patch-kids": "US gummy candy slogan is 'sour then sweet', launched 1985.",
  "life-savers": "US mint launched in 1912, named for its ring shape.",
  "jolly-rancher": "Hard candy brand created in Colorado, USA, in 1949.",
  "trolli": "German company that invented the gummy worm in 1981.",
  "philips": "Dutch electronics firm founded in Eindhoven in 1891.",
  "fujifilm": "Japanese photography firm founded in 1934.",
  "johnnie-walker": "Scotch whisky brand founded in Scotland in 1820.",
  "panasonic": "Japanese electronics maker founded 1918, formerly Matsushita.",
  "tic-tac": "Italian mint brand launched by Ferrero in 1969.",
  "kool-aid": "US powdered drink invented in Nebraska in 1927.",
  "reebok": "British-founded sportswear brand named after an African gazelle.",
  "minute-maid": "US juice brand founded in Florida in 1945.",
  "baileys": "Irish cream liqueur first sold in Dublin in 1974.",
  "lg": "South Korean electronics giant whose slogan is 'Life's Good'.",
  "schweppes": "Swiss-founded tonic water brand dating to 1783.",
  "smirnoff": "World's best-selling vodka, with roots in 19th-century Russia.",
  "moet-chandon": "French champagne house founded in 1743.",
  "epson": "Japanese printer maker, part of Seiko, founded 1942.",
  "kodak": "US film pioneer founded by George Eastman in 1888.",
  "electronic-arts": "US game publisher founded 1982, maker of FIFA and Madden.",
  "activision": "US publisher of Call of Duty, founded in California, 1979.",
  "valve": "US studio behind Steam and Half-Life, founded 1996.",
  "riot-games": "US studio that made League of Legends, founded 2006.",
  "a-and-w": "Oldest US root-beer brand, founded in California in 1919.",
  "folgers": "US coffee brand founded in San Francisco in 1850.",
  "covergirl": "US cosmetics brand launched by Noxzema in 1961.",
  "max-factor": "Pioneered Hollywood movie makeup, founded in the US in 1909.",
  "mac-cosmetics": "Canadian makeup brand founded by artists in 1984.",
  "sephora": "French beauty retailer founded in Limoges in 1969.",
  "clinique": "US dermatologist-designed skincare line launched 1968.",
  "estee-lauder": "US cosmetics empire founded by Estée Lauder in 1946.",
  "neutrogena": "US skincare brand famous for its orange soap bar.",
  "cetaphil": "Gentle skincare brand created by a pharmacist in 1947.",
  "aquafresh": "UK toothpaste brand known for its striped paste.",
  "sensodyne": "Toothpaste brand made for sensitive teeth since 1961.",
  "oral-b": "US dental brand famous for electric toothbrushes.",
  "black-and-decker": "US power-tool maker founded in Maryland in 1910.",
  "cuisinart": "US kitchen brand that popularized the food processor.",
  "brita": "German water-filter brand founded in 1966.",
  "tupperware": "US plastic-storage brand invented by Earl Tupper in 1946.",
  "rubbermaid": "US household-goods maker founded in Ohio in 1920.",
  "pyrex": "US heat-resistant glassware brand launched in 1915.",
  "le-creuset": "French cast-iron cookware founded in 1925, famed for orange.",
  "kitchenaid": "US stand-mixer brand launched in Ohio in 1919.",
  "vitamix": "US high-power blender brand founded in Ohio in 1921.",
  "ninja-kitchen": "US kitchen-appliance brand known for its blenders.",
  "instant-pot": "Canadian electric pressure cooker launched in 2010.",
  "crock-pot": "US slow-cooker brand introduced in 1971.",
  "keurig": "US single-serve coffee-pod system launched in 1998.",
  "yeti": "US cooler and drinkware brand founded in Texas in 2006.",
  "stanley": "US insulated tumbler brand dating back to 1913.",
  "hydro-flask": "US insulated bottle brand founded in Oregon in 2009.",
  "patagonia": "US outdoor-clothing brand founded by Yvon Chouinard, 1973.",
  "arc-teryx": "Canadian outdoor-gear brand founded in 1989.",
  "merrell": "US hiking-boot brand founded in Michigan in 1981.",
  "salomon": "French ski and outdoor-gear brand founded in 1947.",
  "birkenstock": "German sandal maker with roots dating to 1774.",
  "dr-martens": "British boot brand invented by a German doctor in 1945.",
  "asics": "Japanese running-shoe brand whose name is a Latin acronym.",
  "moleskine": "Italian notebook brand relaunched in Milan in 1997.",
  "victorinox": "Swiss maker of the original Swiss Army knife, founded 1884.",
  "leatherman": "US multi-tool brand founded in Oregon in 1983.",
  "igloo": "US cooler brand founded in Texas in 1947.",
  "tabasco": "US hot sauce made on Avery Island, Louisiana, since 1868.",
  "old-el-paso": "US Mexican-food brand launched in Texas in 1938.",
  "franks-redhot": "US hot sauce created in Louisiana in 1920.",
  "sriracha": "Huy Fong hot sauce famous for its rooster-logo bottle.",
  "mccormick": "US spice giant founded in Baltimore in 1889.",
  "lawrys": "US seasoned-salt brand created in Los Angeles in 1938.",
  "old-bay": "Maryland seafood seasoning created in 1939.",
  "goya": "Largest Hispanic-owned food company in the US, founded 1936.",
  "knorr": "German soup and bouillon brand founded in 1838.",
  "maggi": "Nestlé seasoning brand created in Switzerland in 1884.",
  "barilla": "Italian pasta maker founded in Parma in 1877.",
  "godiva": "Belgian chocolatier founded in Brussels in 1926.",
  "ghirardelli": "US chocolate brand founded in San Francisco in 1852.",
  "green-and-blacks": "UK organic chocolate brand launched in 1991.",
  "jelly-belly": "US jelly-bean maker famous for gourmet flavors since 1976.",
  "mike-and-ike": "US candy named after two friends, launched in 1940.",
  "peeps": "US marshmallow candy shaped like chicks, made since 1953.",
  "laffy-taffy": "US taffy brand known for its corny jokes on wrappers.",
  "now-and-later": "US chewy candy launched in New York in 1962.",
  "dubble-bubble": "US brand that made the first bubble gum in 1928.",
  "bazooka": "Bubble gum brand famous for its Bazooka Joe comics.",
  "tang": "US powdered drink that flew with NASA astronauts in the 1960s.",
  "ovaltine": "Swiss malted-milk drink created in 1904.",
  "horlicks": "British bedtime malted-milk drink launched in 1873.",
  "milo": "Nestlé chocolate-malt drink created in Australia in 1934.",
};
