// E196 «Guess the Brand by Emoji 4» — 100 brands · 25/tier
// VO: sfx/e196-<id>.wav
export const BRAND_EMOJI_4 = [
  // ===== EASY (25) =====
  { id: "zara", title: "Zara", emojis: "👗✂", level: "easy" },
  { id: "duolingo", title: "Duolingo", emojis: "🦉📚", level: "easy" },
  { id: "minecraft", title: "Minecraft", emojis: "⛏🧊", level: "easy" },
  { id: "roblox", title: "Roblox", emojis: "🧱🎮", level: "easy" },
  { id: "candy-crush", title: "Candy Crush", emojis: "🍬💥", level: "easy" },
  { id: "steam", title: "Steam", emojis: "♨🎮", level: "easy" },
  { id: "crayola", title: "Crayola", emojis: "🖍🌈", level: "easy" },
  { id: "magnum", title: "Magnum", emojis: "🍦🖤", level: "easy" },
  { id: "krispy-kreme", title: "Krispy Kreme", emojis: "🍩✨", level: "easy" },
  { id: "ben-and-jerrys", title: "Ben & Jerry's", emojis: "🐄🍨", level: "easy" },
  { id: "tide", title: "Tide", emojis: "👕✨", level: "easy" },
  { id: "booking-com", title: "Booking.com", emojis: "🏨👍", level: "easy" },
  { id: "qantas", title: "Qantas", emojis: "✈🦘", level: "easy" },
  { id: "turkish-airlines", title: "Turkish Airlines", emojis: "✈🦃", level: "easy" },
  { id: "air-france", title: "Air France", emojis: "✈🥐", level: "easy" },
  { id: "air-canada", title: "Air Canada", emojis: "✈🍁", level: "easy" },
  { id: "hawaiian-airlines", title: "Hawaiian Airlines", emojis: "✈🌺", level: "easy" },
  { id: "white-castle", title: "White Castle", emojis: "🏰🍔", level: "easy" },
  { id: "applebees", title: "Applebee's", emojis: "🍎🐝", level: "easy" },
  { id: "battleship", title: "Battleship", emojis: "🚢💥", level: "easy" },
  { id: "buffalo-wild-wings", title: "Buffalo Wild Wings", emojis: "🐃🍗", level: "easy" },
  { id: "nerf", title: "Nerf", emojis: "🔫🧡", level: "easy" },
  { id: "jetblue", title: "JetBlue", emojis: "✈💙", level: "easy" },
  { id: "spirit-airlines", title: "Spirit Airlines", emojis: "✈👻", level: "easy" },
  { id: "ziploc", title: "Ziploc", emojis: "🥪🔒", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "outback-steakhouse", title: "Outback Steakhouse", emojis: "🥩🦘", level: "medium" },
  { id: "dennys", title: "Denny's", emojis: "🍳🌙", level: "medium" },
  { id: "papa-johns", title: "Papa John's", emojis: "🍕👨", level: "medium" },
  { id: "little-caesars", title: "Little Caesars", emojis: "🍕🤴", level: "medium" },
  { id: "chuck-e-cheese", title: "Chuck E. Cheese", emojis: "🐭🍕", level: "medium" },
  { id: "red-lobster", title: "Red Lobster", emojis: "🦞🌊", level: "medium" },
  { id: "sonic-drive-in", title: "Sonic Drive-In", emojis: "🍔🛼", level: "medium" },
  { id: "culvers", title: "Culver's", emojis: "🍦🍔", level: "medium" },
  { id: "whataburger", title: "Whataburger", emojis: "🍔🧡", level: "medium" },
  { id: "churchs-chicken", title: "Church's Chicken", emojis: "⛪🍗", level: "medium" },
  { id: "wingstop", title: "Wingstop", emojis: "🍗🛑", level: "medium" },
  { id: "windex", title: "Windex", emojis: "🪟✨", level: "medium" },
  { id: "swiffer", title: "Swiffer", emojis: "🧹✨", level: "medium" },
  { id: "glad", title: "Glad", emojis: "😊🗑", level: "medium" },
  { id: "bic", title: "Bic", emojis: "🖊🔥", level: "medium" },
  { id: "sharpie", title: "Sharpie", emojis: "🖊🖤", level: "medium" },
  { id: "playdoh", title: "Play-Doh", emojis: "🫙🎨", level: "medium" },
  { id: "jenga", title: "Jenga", emojis: "🧱📉", level: "medium" },
  { id: "twister", title: "Twister", emojis: "🌈🤸", level: "medium" },
  { id: "scrabble", title: "Scrabble", emojis: "🔤🏆", level: "medium" },
  { id: "yahtzee", title: "Yahtzee", emojis: "🎲🏆", level: "medium" },
  { id: "singapore-airlines", title: "Singapore Airlines", emojis: "✈🦁", level: "medium" },
  { id: "british-airways", title: "British Airways", emojis: "✈🎩", level: "medium" },
  { id: "tgi-fridays", title: "TGI Fridays", emojis: "📅🍹", level: "medium" },
  { id: "cold-stone-creamery", title: "Cold Stone Creamery", emojis: "🧊🍦", level: "medium" },

  // ===== HARD (25) =====
  { id: "tripadvisor", title: "TripAdvisor", emojis: "🦉🧳", level: "hard" },
  { id: "etsy", title: "Etsy", emojis: "🧶✂", level: "hard" },
  { id: "yelp", title: "Yelp", emojis: "⭐🍴", level: "hard" },
  { id: "groupon", title: "Groupon", emojis: "🏷💵", level: "hard" },
  { id: "indeed", title: "Indeed", emojis: "🔍💼", level: "hard" },
  { id: "zillow", title: "Zillow", emojis: "🏠🔍", level: "hard" },
  { id: "grammarly", title: "Grammarly", emojis: "👍✍", level: "hard" },
  { id: "trello", title: "Trello", emojis: "📋👍", level: "hard" },
  { id: "robinhood", title: "Robinhood", emojis: "🪶📈", level: "hard" },
  { id: "binance", title: "Binance", emojis: "🪙💎", level: "hard" },
  { id: "western-union", title: "Western Union", emojis: "💸🌍", level: "hard" },
  { id: "zelle", title: "Zelle", emojis: "💸⚡", level: "hard" },
  { id: "delta-air-lines", title: "Delta Air Lines", emojis: "✈🔺", level: "hard" },
  { id: "american-airlines", title: "American Airlines", emojis: "✈🦅", level: "hard" },
  { id: "alaska-airlines", title: "Alaska Airlines", emojis: "✈🐻", level: "hard" },
  { id: "frontier-airlines", title: "Frontier Airlines", emojis: "✈🐺", level: "hard" },
  { id: "aston-martin", title: "Aston Martin", emojis: "🚗🕶", level: "hard" },
  { id: "bugatti", title: "Bugatti", emojis: "🚗💎", level: "hard" },
  { id: "mclaren", title: "McLaren", emojis: "🚗🧡", level: "hard" },
  { id: "lotus", title: "Lotus Cars", emojis: "🚗🪷", level: "hard" },
  { id: "fiat", title: "Fiat", emojis: "🚗🍝", level: "hard" },
  { id: "haagen-dazs", title: "Häagen-Dazs", emojis: "🍨❄", level: "hard" },
  { id: "klondike", title: "Klondike", emojis: "🐻❄", level: "hard" },
  { id: "long-john-silvers", title: "Long John Silver's", emojis: "🐟🦜", level: "hard" },
  { id: "el-pollo-loco", title: "El Pollo Loco", emojis: "🐔🤪", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "lysol", title: "Lysol", emojis: "🦠🚫", level: "impossible" },
  { id: "coinbase", title: "Coinbase", emojis: "🪙💻", level: "impossible" },
  { id: "stripe", title: "Stripe", emojis: "💳🔗", level: "impossible" },
  { id: "notion", title: "Notion", emojis: "📝👍", level: "impossible" },
  { id: "risk", title: "Risk", emojis: "🌍⚔", level: "impossible" },
  { id: "clue", title: "Clue", emojis: "🔍🔪", level: "impossible" },
  { id: "trivial-pursuit", title: "Trivial Pursuit", emojis: "❓🥧", level: "impossible" },
  { id: "candy-land", title: "Candy Land", emojis: "🍭🗺", level: "impossible" },
  { id: "pampers", title: "Pampers", emojis: "👶🍼", level: "impossible" },
  { id: "johnsons-baby", title: "Johnson's Baby", emojis: "👶🧴", level: "impossible" },
  { id: "nivea", title: "Nivea", emojis: "🧴💙", level: "impossible" },
  { id: "arbys", title: "Arby's", emojis: "🥪🤠", level: "impossible" },
  { id: "united-airlines", title: "United Airlines", emojis: "✈🤝", level: "impossible" },
  { id: "norwegian-air", title: "Norwegian Air", emojis: "✈🧊", level: "impossible" },
  { id: "grubhub", title: "Grubhub", emojis: "🍔🚴", level: "impossible" },
  { id: "moneygram", title: "MoneyGram", emojis: "💸✉", level: "impossible" },
  { id: "shein", title: "Shein", emojis: "🛍📦", level: "impossible" },
  { id: "temu", title: "Temu", emojis: "🛍💸", level: "impossible" },
  { id: "canva", title: "Canva", emojis: "🎨💻", level: "impossible" },
  { id: "asos", title: "ASOS", emojis: "🛍👗", level: "impossible" },
  { id: "primark", title: "Primark", emojis: "👗💰", level: "impossible" },
  { id: "forever-21", title: "Forever 21", emojis: "👗♾", level: "impossible" },
  { id: "postmates", title: "Postmates", emojis: "📦🚴", level: "impossible" },
  { id: "squarespace", title: "Squarespace", emojis: "🌐✏", level: "impossible" },
  { id: "glassdoor", title: "Glassdoor", emojis: "🏢👀", level: "impossible" },
];
