// E129 emoji-brand-2 facts — one verified ≤70-char fact per brand, shown on reveal.
export const BRAND_EMOJI_2_FACTS = {
  // EASY
  "walmart": "Founded by Sam Walton in 1962; world's largest retailer.",
  "target": "Discount retailer founded in Minnesota in 1962.",
  "subway": "Sandwich chain founded in 1965 as Pete's Super Submarines.",
  "dominos": "Founded in 1960; pioneered 30-minutes-or-free delivery.",
  "uber": "Ride-hailing app founded in San Francisco in 2009.",
  "zoom": "Video app founded by Eric Yuan; boomed in 2020 lockdowns.",
  "linkedin": "Professional network launched in 2003; now owned by Microsoft.",
  "pinterest": "Visual discovery and idea-pinning app launched in 2010.",
  "reddit": "Launched in 2005; its alien mascot is named Snoo.",
  "tacobell": "Founded in 1962 by Glen Bell in Downey, California.",
  "dunkin": "Coffee-and-donut chain founded in Massachusetts in 1950.",
  "telegram": "Messaging app launched in 2013 by the Durov brothers.",
  "tinder": "Dating app launched in 2012; famous for the swipe.",
  "monopoly": "Board game published by Parker Brothers since 1935.",
  "toysrus": "Toy retailer founded 1948; mascot Geoffrey the Giraffe.",
  "cheetos": "Cheese snack launched in 1948; mascot Chester Cheetah.",
  "hershey": "Founded by Milton Hershey in 1894 in Pennsylvania.",
  "sprite": "Lemon-lime soda launched by Coca-Cola in 1961.",
  "budweiser": "Beer brand founded 1876; famous for Clydesdale horses.",
  "dove": "Personal-care brand launched in 1957 with its beauty bar.",
  "levis": "Jeans brand founded 1853; invented riveted denim.",
  "dairyqueen": "Soft-serve chain founded in Joliet, Illinois, in 1940.",
  "pizzahut": "Founded in 1958 by two brothers in Wichita, Kansas.",
  "staples": "Office-supply retailer founded in Massachusetts in 1986.",
  "homedepot": "Home-improvement retailer founded in Atlanta in 1978.",

  // MEDIUM
  "costco": "Membership warehouse chain founded in Seattle in 1983.",
  "lowes": "Home-improvement chain founded in North Carolina in 1946.",
  "adobe": "Software firm founded in 1982; makes Photoshop.",
  "slack": "Workplace chat app launched in 2013.",
  "discord": "Chat app launched in 2015; huge with gamers.",
  "twitch": "Live-streaming site launched in 2011, owned by Amazon.",
  "signal": "Encrypted messaging app run by a nonprofit foundation.",
  "venmo": "Peer-to-peer payment app launched in 2009.",
  "cashapp": "Mobile payment app launched by Square in 2013.",
  "mastercard": "Payment network founded in 1966 as Interbank Card.",
  "ford": "Founded by Henry Ford in 1903 in Michigan.",
  "jeep": "Off-road brand born from WWII military vehicles.",
  "harley": "Motorcycle maker founded in Milwaukee in 1903.",
  "champion": "Sportswear brand founded 1919; credited with the hoodie.",
  "billabong": "Australian surf brand founded on the Gold Coast in 1973.",
  "lacoste": "Founded 1933 by tennis champ René Lacoste; famed for its crocodile.",
  "hm": "Swedish fashion retailer founded in 1947.",
  "milka": "Chocolate brand founded in 1901, known for its lilac cow.",
  "campbells": "Soup company founded in New Jersey in 1869.",
  "lays": "Potato chip brand named after founder Herman Lay.",
  "doritos": "Tortilla chip brand created by Frito-Lay in 1964.",
  "kelloggs": "Cereal maker founded by W.K. Kellogg in 1906.",
  "nesquik": "Chocolate milk brand launched by Nestlé in 1948.",
  "jackdaniels": "Tennessee whiskey; the brand dates itself to 1866.",
  "mountaindew": "Citrus soda created in Tennessee in the 1940s.",

  // HARD
  "vespa": "Italian scooter maker; its name means 'wasp' in Italian.",
  "tiffany": "Luxury jeweler founded in New York City in 1837.",
  "cartier": "French jewelry house founded in Paris in 1847.",
  "swatch": "Swiss watchmaker founded in 1983 to revive the industry.",
  "hermes": "French luxury house founded in 1837 as a saddlery.",
  "fendi": "Italian fashion house founded in Rome in 1925.",
  "pandora": "Danish jeweler founded 1982; famous for charm bracelets.",
  "swarovski": "Austrian crystal maker founded in 1895.",
  "converse": "American shoe brand since 1908; famous for the All Star sneaker.",
  "loreal": "French cosmetics giant founded in Paris in 1909.",
  "maybelline": "US cosmetics brand named for founder's sister Mabel.",
  "axe": "Unilever grooming brand launched in France in 1983.",
  "oldspice": "Men's grooming brand launched by Shulton in 1937.",
  "crest": "Toothpaste brand launched by Procter & Gamble in 1955.",
  "vaseline": "Petroleum jelly brand created by Robert Chesebrough in 1870.",
  "intel": "Chipmaker founded in 1968 by Noyce and Moore.",
  "drpepper": "Soft drink invented in Waco, Texas, in 1885.",
  "wendys": "Burger chain founded by Dave Thomas in 1969.",
  "baskinrobbins": "Ice cream chain famous for its '31 flavors' since 1945.",
  "cinnabon": "Cinnamon-roll chain founded in Seattle in 1985.",
  "chickfila": "Chicken chain famous for cows urging 'Eat Mor Chikin'.",
  "innout": "California burger chain founded in 1948.",
  "shakeshack": "Started as a NYC hot-dog cart in Madison Square Park.",
  "pandaexpress": "American Chinese-food chain founded in 1983.",
  "olivegarden": "Italian-American restaurant chain founded in 1982.",

  // IMPOSSIBLE
  "emirates": "Dubai's flagship airline, launched in 1985.",
  "ryanair": "Irish low-cost airline founded in 1984.",
  "easyjet": "British low-cost airline founded in 1995.",
  "klm": "Dutch airline founded in 1919, oldest still flying its name.",
  "pixar": "Animation studio bought by Steve Jobs in 1986.",
  "marvel": "Comics publisher founded in 1939 as Timely Comics.",
  "uno": "Card game invented in Ohio in 1971; now owned by Mattel.",
  "skype": "Video-call app launched 2003, later bought by Microsoft.",
  "doordash": "Food-delivery app founded in Palo Alto in 2013.",
  "lyft": "Ride-share app founded in San Francisco in 2012.",
  "chipotle": "Fast-casual chain founded in Denver in 1993.",
  "cadbury": "British chocolate maker founded in Birmingham in 1824.",
  "android": "Google's mobile OS launched in 2008; mascot is a green robot.",
  "absolut": "Swedish vodka; the modern brand launched in 1979.",
  "shazam": "Music-recognition app launched in 2002 in the UK.",
  "mailchimp": "Email marketing platform founded in Atlanta in 2001.",
  "evernote": "Note-taking app launched in 2008.",
  "tumblr": "Blogging platform launched in 2007 by David Karp.",
  "myspace": "Social network launched in 2003, once the world's biggest.",
  "napster": "Pioneering music-sharing service launched in 1999.",
  "blackberry": "Canadian phone maker once famed for physical keyboards.",
  "nokia": "Finnish company famous for its built-in Snake phone game.",
  "sega": "Japanese gaming firm; mascot Sonic debuted in 1991.",
  "atari": "Video-game pioneer founded in California in 1972.",
  "quiksilver": "Australian surf brand founded in Torquay in 1969.",
};
