// E227 «Guess the Brand by Emoji 5» — 100 brands · 25/tier · clue via OpenMoji
export const BRAND_EMOJI5 = [
  { id: "sony", title: "Sony", emojis: "📺🎮", level: "easy" },
  { id: "toyota", title: "Toyota", emojis: "🚗🗻", level: "easy" },
  { id: "reeses", title: "Reese's", emojis: "🥜🍫", level: "easy" },
  { id: "starburst", title: "Starburst", emojis: "🍬⭐", level: "easy" },
  { id: "mattel", title: "Mattel", emojis: "🧸🎲", level: "easy" },
  { id: "xerox", title: "Xerox", emojis: "🖨📄", level: "easy" },
  { id: "tropicana", title: "Tropicana", emojis: "🍊🥤", level: "easy" },
  { id: "capri-sun", title: "Capri Sun", emojis: "🧃☀", level: "easy" },
  { id: "arizona", title: "Arizona", emojis: "🌵🍹", level: "easy" },
  { id: "blizzard", title: "Blizzard Entertainment", emojis: "🎮❄", level: "easy" },
  { id: "logitech", title: "Logitech", emojis: "💻⌨", level: "easy" },
  { id: "nerds", title: "Nerds", emojis: "🍬🤓", level: "easy" },
  { id: "sour-patch-kids", title: "Sour Patch Kids", emojis: "🍬😖", level: "easy" },
  { id: "life-savers", title: "Life Savers", emojis: "🍬🛟", level: "easy" },
  { id: "jolly-rancher", title: "Jolly Rancher", emojis: "🍬🤠", level: "easy" },
  { id: "trolli", title: "Trolli", emojis: "🐛🍬", level: "easy" },
  { id: "philips", title: "Philips", emojis: "💡🌀", level: "easy" },
  { id: "fujifilm", title: "Fujifilm", emojis: "📷🎞", level: "easy" },
  { id: "johnnie-walker", title: "Johnnie Walker", emojis: "🥃🚶", level: "easy" },
  { id: "panasonic", title: "Panasonic", emojis: "🔋📺", level: "easy" },
  { id: "tic-tac", title: "Tic Tac", emojis: "🍬📦", level: "easy" },
  { id: "kool-aid", title: "Kool-Aid", emojis: "🥤😎", level: "easy" },
  { id: "reebok", title: "Reebok", emojis: "👟🏋", level: "easy" },
  { id: "minute-maid", title: "Minute Maid", emojis: "🍊⏱", level: "easy" },
  { id: "baileys", title: "Baileys", emojis: "🥃🍀", level: "easy" },
  { id: "lg", title: "LG", emojis: "📺💚", level: "medium" },
  { id: "schweppes", title: "Schweppes", emojis: "🥤🫧", level: "medium" },
  { id: "smirnoff", title: "Smirnoff", emojis: "🍸❄", level: "medium" },
  { id: "moet-chandon", title: "Moët & Chandon", emojis: "🍾⭐", level: "medium" },
  { id: "epson", title: "Epson", emojis: "🖨🌈", level: "medium" },
  { id: "kodak", title: "Kodak", emojis: "📷🕰", level: "medium" },
  { id: "electronic-arts", title: "Electronic Arts", emojis: "🎮⚡", level: "medium" },
  { id: "activision", title: "Activision", emojis: "🎮💣", level: "medium" },
  { id: "valve", title: "Valve", emojis: "🎮🔧", level: "medium" },
  { id: "riot-games", title: "Riot Games", emojis: "🎮⚔", level: "medium" },
  { id: "a-and-w", title: "A&W", emojis: "🍺🐻", level: "medium" },
  { id: "folgers", title: "Folgers", emojis: "☕🌅", level: "medium" },
  { id: "covergirl", title: "CoverGirl", emojis: "💄⭐", level: "medium" },
  { id: "max-factor", title: "Max Factor", emojis: "💄🎬", level: "medium" },
  { id: "mac-cosmetics", title: "MAC Cosmetics", emojis: "💄🎨", level: "medium" },
  { id: "sephora", title: "Sephora", emojis: "💄🛍", level: "medium" },
  { id: "clinique", title: "Clinique", emojis: "💄🧴", level: "medium" },
  { id: "estee-lauder", title: "Estée Lauder", emojis: "💄🌟", level: "medium" },
  { id: "neutrogena", title: "Neutrogena", emojis: "🧴🌞", level: "medium" },
  { id: "cetaphil", title: "Cetaphil", emojis: "🧴💧", level: "medium" },
  { id: "aquafresh", title: "Aquafresh", emojis: "🦷🌊", level: "medium" },
  { id: "sensodyne", title: "Sensodyne", emojis: "🦷❄", level: "medium" },
  { id: "oral-b", title: "Oral-B", emojis: "🦷🔌", level: "medium" },
  { id: "black-and-decker", title: "Black+Decker", emojis: "🛠🔋", level: "medium" },
  { id: "cuisinart", title: "Cuisinart", emojis: "🍽🌀", level: "medium" },
  { id: "brita", title: "Brita", emojis: "💧🧊", level: "hard" },
  { id: "tupperware", title: "Tupperware", emojis: "🥡🔒", level: "hard" },
  { id: "rubbermaid", title: "Rubbermaid", emojis: "🗑🔒", level: "hard" },
  { id: "pyrex", title: "Pyrex", emojis: "🍽🔥", level: "hard" },
  { id: "le-creuset", title: "Le Creuset", emojis: "🍲🧡", level: "hard" },
  { id: "kitchenaid", title: "KitchenAid", emojis: "🥣🎨", level: "hard" },
  { id: "vitamix", title: "Vitamix", emojis: "🥤🌀", level: "hard" },
  { id: "ninja-kitchen", title: "Ninja", emojis: "🥷🍹", level: "hard" },
  { id: "instant-pot", title: "Instant Pot", emojis: "🍲⚡", level: "hard" },
  { id: "crock-pot", title: "Crock-Pot", emojis: "🍲🐢", level: "hard" },
  { id: "keurig", title: "Keurig", emojis: "☕💊", level: "hard" },
  { id: "yeti", title: "YETI", emojis: "🧊🏔", level: "hard" },
  { id: "stanley", title: "Stanley", emojis: "🥤🏕", level: "hard" },
  { id: "hydro-flask", title: "Hydro Flask", emojis: "🥤🌊", level: "hard" },
  { id: "patagonia", title: "Patagonia", emojis: "🧥🏔", level: "hard" },
  { id: "arc-teryx", title: "Arc'teryx", emojis: "🧥🦅", level: "hard" },
  { id: "merrell", title: "Merrell", emojis: "🥾🌲", level: "hard" },
  { id: "salomon", title: "Salomon", emojis: "⛷🏔", level: "hard" },
  { id: "birkenstock", title: "Birkenstock", emojis: "🩴🦶", level: "hard" },
  { id: "dr-martens", title: "Dr. Martens", emojis: "🥾⚡", level: "hard" },
  { id: "asics", title: "Asics", emojis: "👟🏃", level: "hard" },
  { id: "moleskine", title: "Moleskine", emojis: "📓✒", level: "hard" },
  { id: "victorinox", title: "Victorinox", emojis: "🔪🎒", level: "hard" },
  { id: "leatherman", title: "Leatherman", emojis: "🛠🤚", level: "hard" },
  { id: "igloo", title: "Igloo", emojis: "🧊🏠", level: "hard" },
  { id: "tabasco", title: "Tabasco", emojis: "🌶🔥", level: "impossible" },
  { id: "old-el-paso", title: "Old El Paso", emojis: "🌮🤠", level: "impossible" },
  { id: "franks-redhot", title: "Frank's RedHot", emojis: "🌶🍗", level: "impossible" },
  { id: "sriracha", title: "Sriracha", emojis: "🐓🌶", level: "impossible" },
  { id: "mccormick", title: "McCormick", emojis: "🧂🌿", level: "impossible" },
  { id: "lawrys", title: "Lawry's", emojis: "🧂🥩", level: "impossible" },
  { id: "old-bay", title: "Old Bay", emojis: "🦀🧂", level: "impossible" },
  { id: "goya", title: "Goya Foods", emojis: "🥫🌴", level: "impossible" },
  { id: "knorr", title: "Knorr", emojis: "🍲🧂", level: "impossible" },
  { id: "maggi", title: "Maggi", emojis: "🍜🧂", level: "impossible" },
  { id: "barilla", title: "Barilla", emojis: "🍝🌾", level: "impossible" },
  { id: "godiva", title: "Godiva", emojis: "🍫👑", level: "impossible" },
  { id: "ghirardelli", title: "Ghirardelli", emojis: "🍫⛰", level: "impossible" },
  { id: "green-and-blacks", title: "Green & Black's", emojis: "🍫🌿", level: "impossible" },
  { id: "jelly-belly", title: "Jelly Belly", emojis: "🍬🌈", level: "impossible" },
  { id: "mike-and-ike", title: "Mike and Ike", emojis: "🍬👬", level: "impossible" },
  { id: "peeps", title: "Peeps", emojis: "🐤🍬", level: "impossible" },
  { id: "laffy-taffy", title: "Laffy Taffy", emojis: "😂🍬", level: "impossible" },
  { id: "now-and-later", title: "Now and Later", emojis: "⏰🍬", level: "impossible" },
  { id: "dubble-bubble", title: "Dubble Bubble", emojis: "🫧🍬", level: "impossible" },
  { id: "bazooka", title: "Bazooka", emojis: "💣🍬", level: "impossible" },
  { id: "tang", title: "Tang", emojis: "🍊🚀", level: "impossible" },
  { id: "ovaltine", title: "Ovaltine", emojis: "🥛🥚", level: "impossible" },
  { id: "horlicks", title: "Horlicks", emojis: "🥛😴", level: "impossible" },
  { id: "milo", title: "Milo", emojis: "🥛🏃", level: "impossible" },
];
