// E123 facts — one short did-you-know per brand, keyed by slug. Each <=70 chars.
export const BRAND_SLOGAN_FACTS = {
  // EASY
  nike: "Nike is named after the Greek goddess of victory.",
  mcdonalds: "McDonald's serves about 69 million customers every day.",
  apple: "Apple's first logo showed Isaac Newton under a tree.",
  loreal: "L'Oreal began in 1909 with a hair-dye formula in Paris.",
  kfc: "Colonel Sanders started his chicken business at age 65.",
  bmw: "BMW's roundel logo nods to its aircraft-engine roots.",
  adidas: "Adidas was founded by Adolf 'Adi' Dassler in 1949.",
  redbull: "Red Bull sells over 12 billion cans worldwide each year.",
  mastercard: "Mastercard's interlocking circles date back to 1966.",
  gillette: "Gillette sold its first safety razor in 1903.",
  debeers: "De Beers once controlled most of the world's diamonds.",
  lays: "Lay's Wavy chips were invented to hold more dip.",
  energizer: "The Energizer Bunny has run since 1989.",
  walmart: "Walmart opened its first store in Arkansas in 1962.",
  subway: "Subway started as a sandwich shop called Pete's in 1965.",
  dunkin: "Dunkin' dropped 'Donuts' from its name in 2019.",
  haribo: "Haribo's name blends founder Hans Riegel and Bonn.",
  skittles: "Skittles were first sold in the UK back in 1974.",
  nokia: "Nokia began as a Finnish paper mill in 1865.",
  wendys: "Wendy's is named after founder Dave Thomas's daughter.",
  capitalone: "Capital One was founded in Virginia in 1994.",
  toyota: "Toyota started out making automatic looms, not cars.",
  airbnb: "Airbnb began with founders renting air mattresses.",
  disney: "Disneyland opened in Anaheim, California, in 1955.",
  burgerking: "Burger King's Whopper launched back in 1957.",

  // MEDIUM
  dell: "Michael Dell started the company from his dorm room.",
  fedex: "FedEx's logo hides an arrow between the E and x.",
  lego: "The word LEGO comes from Danish 'leg godt', play well.",
  ikea: "IKEA's name combines founder Ingvar Kamprad's initials.",
  avis: "Avis has long branded itself the number two rental firm.",
  heinz: "Heinz once marketed '57 Varieties' though it had more.",
  levis: "Levi's made the first riveted blue jeans in 1873.",
  volkswagen: "Volkswagen means 'people's car' in German.",
  amex: "American Express began in 1850 as an express-mail firm.",
  maybelline: "Maybelline was named after founder's sister Mabel.",
  cocacola: "Coca-Cola was originally sold as a medicinal tonic.",
  pepsi: "Pepsi was named after the digestive enzyme pepsin.",
  snickers: "Snickers is named after the Mars family's horse.",
  oldspice: "Old Spice launched for women before targeting men.",
  audi: "Audi's four rings represent four merged German firms.",
  honda: "Honda began by making motorized bicycles in 1948.",
  ford: "Ford's Model T made cars affordable for everyday people.",
  target: "Target's bullseye logo has barely changed since 1962.",
  homedepot: "The first Home Depot opened in Atlanta in 1979.",
  statefarm: "State Farm began as an auto insurer for farmers.",
  allstate: "Allstate was originally launched inside Sears stores.",
  bounty: "Bounty paper towels debuted by Procter & Gamble in 1965.",
  mms: "M&M's stands for Mars and Murrie, its co-creators.",
  timex: "Timex traces back to the Waterbury Clock Company.",
  frostedflakes: "Tony the Tiger has fronted Frosted Flakes since 1952.",

  // HARD
  panasonic: "Panasonic was originally founded as Matsushita in 1918.",
  sony: "Sony's name blends Latin 'sonus' with 'sonny boy'.",
  samsung: "Samsung means 'three stars' in Korean.",
  lg: "LG originally stood for Lucky-Goldstar.",
  ge: "GE traces back to Thomas Edison's lighting company.",
  ibm: "IBM's 'Think' slogan dates back to the 1910s.",
  chipotle: "Chipotle opened its first shop in Denver in 1993.",
  pizzahut: "Pizza Hut got its name because the sign only fit 3 words.",
  papajohns: "Papa John's started in a broom closet in Indiana.",
  carlsberg: "Carlsberg's lab helped invent the pH scale.",
  guinness: "A pint of Guinness takes about 120 seconds to pour well.",
  budweiser: "Budweiser's Clydesdale horses debuted in 1933.",
  heineken: "Heineken's red star traces back to medieval brewing.",
  duracell: "Duracell's name blends 'durable' and 'cell'.",
  rolex: "Rolex was the first watch certified as a chronometer.",
  jeep: "The Jeep name may come from the military term 'GP'.",
  mazda: "Mazda is named after Ahura Mazda, a Zoroastrian god.",
  hyundai: "Hyundai means 'modernity' in Korean.",
  puma: "Puma and Adidas were founded by feuding brothers.",
  underarmour: "Under Armour began by selling gear from a car trunk.",
  reebok: "Reebok is named after an African gazelle, the rhebok.",
  gatorade: "Gatorade was invented for the Florida Gators in 1965.",
  michelin: "Michelin created the famous restaurant guide in 1900.",
  siemens: "Siemens was founded in Berlin back in 1847.",
  volvo: "Volvo means 'I roll' in Latin.",

  // IMPOSSIBLE
  tesco: "Tesco's name comes from a tea supplier's initials.",
  aldi: "Aldi's name blends Albrecht and 'discount'.",
  lidl: "Lidl bought the rights to its name from a schoolteacher.",
  sainsburys: "Sainsbury's opened its first shop in London in 1869.",
  johnlewis: "John Lewis is owned by its own employees as partners.",
  specsavers: "Specsavers was founded by a husband-and-wife team.",
  ronseal: "Ronseal is a British wood-care and varnish brand.",
  comparethemarket: "Compare the Market's meerkat mascot debuted in 2009.",
  kwikfit: "Kwik Fit was founded in Edinburgh, Scotland, in 1971.",
  yellowpages: "The first phone directory turned yellow by accident.",
  toysrus: "Toys R Us began as a baby-furniture store in 1948.",
  meowmix: "Meow Mix launched its jingle-based ads in the 1970s.",
  riceoroni: "Rice-A-Roni actually began as an Armenian pilaf recipe.",
  greyhound: "Greyhound Lines started with a single Hupmobile in 1914.",
  maxwellhouse: "Maxwell House was named after an Atlanta hotel.",
  mortonsalt: "Morton Salt's umbrella girl logo debuted in 1914.",
  alkaseltzer: "Alka-Seltzer tablets were invented during a flu epidemic.",
  trix: "Trix cereal launched by General Mills back in 1954.",
  almondjoy: "Almond Joy and Mounds are made by the same company.",
  folgers: "Folgers coffee dates back to gold-rush era California.",
  littlecaesars: "Little Caesars was founded by a husband-and-wife duo.",
  arbys: "Arby's name comes from the initials R.B., Raffel Brothers.",
  popeyes: "Popeyes is named after Popeye Doyle from The French Connection.",
  sprite: "Sprite launched in the US in 1961 as a 7Up rival.",
  drpepper: "Dr Pepper predates Coca-Cola, launching in 1885.",
};
