// E129 «Guess the Brand by Emoji 2» — 100 brands · 25/tier · clue via OpenMoji · VO: sfx/eb2-<id>.wav
export const BRAND_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "walmart", title: "Walmart", emojis: "🛒🔵", level: "easy" },
  { id: "target", title: "Target", emojis: "🎯🔴", level: "easy" },
  { id: "subway", title: "Subway", emojis: "🥪🚇", level: "easy" },
  { id: "dominos", title: "Domino's Pizza", emojis: "🍕🎲", level: "easy" },
  { id: "uber", title: "Uber", emojis: "🚗⬛", level: "easy" },
  { id: "zoom", title: "Zoom", emojis: "🎥🔵", level: "easy" },
  { id: "linkedin", title: "LinkedIn", emojis: "💼🔵", level: "easy" },
  { id: "pinterest", title: "Pinterest", emojis: "🖼🔴", level: "easy" },
  { id: "reddit", title: "Reddit", emojis: "👽🟠", level: "easy" },
  { id: "tacobell", title: "Taco Bell", emojis: "🌮🔔", level: "easy" },
  { id: "dunkin", title: "Dunkin'", emojis: "🍩☕", level: "easy" },
  { id: "telegram", title: "Telegram", emojis: "✈🔵", level: "easy" },
  { id: "tinder", title: "Tinder", emojis: "🔥❤", level: "easy" },
  { id: "monopoly", title: "Monopoly", emojis: "🎩🏠", level: "easy" },
  { id: "toysrus", title: "Toys\"R\"Us", emojis: "🦒🧸", level: "easy" },
  { id: "cheetos", title: "Cheetos", emojis: "🧀🐆", level: "easy" },
  { id: "hershey", title: "Hershey's", emojis: "🍫💋", level: "easy" },
  { id: "sprite", title: "Sprite", emojis: "🥤🍋", level: "easy" },
  { id: "budweiser", title: "Budweiser", emojis: "🍺🐴", level: "easy" },
  { id: "dove", title: "Dove", emojis: "🕊🤍", level: "easy" },
  { id: "levis", title: "Levi's", emojis: "👖🔴", level: "easy" },
  { id: "dairyqueen", title: "Dairy Queen", emojis: "🍦👑", level: "easy" },
  { id: "pizzahut", title: "Pizza Hut", emojis: "🍕🏠", level: "easy" },
  { id: "staples", title: "Staples", emojis: "📎🔴", level: "easy" },
  { id: "homedepot", title: "Home Depot", emojis: "🏠🟠", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "costco", title: "Costco", emojis: "📦🔴", level: "medium" },
  { id: "lowes", title: "Lowe's", emojis: "🏠🔵", level: "medium" },
  { id: "adobe", title: "Adobe", emojis: "🎨🔴", level: "medium" },
  { id: "slack", title: "Slack", emojis: "💬🟣", level: "medium" },
  { id: "discord", title: "Discord", emojis: "🎮👾", level: "medium" },
  { id: "twitch", title: "Twitch", emojis: "🎥🟣", level: "medium" },
  { id: "signal", title: "Signal", emojis: "🔒💬", level: "medium" },
  { id: "venmo", title: "Venmo", emojis: "💵🔵", level: "medium" },
  { id: "cashapp", title: "Cash App", emojis: "💵🟢", level: "medium" },
  { id: "mastercard", title: "Mastercard", emojis: "💳🔴", level: "medium" },
  { id: "ford", title: "Ford", emojis: "🚗🔵", level: "medium" },
  { id: "jeep", title: "Jeep", emojis: "🚗🟩", level: "medium" },
  { id: "harley", title: "Harley-Davidson", emojis: "🏍🦅", level: "medium" },
  { id: "champion", title: "Champion", emojis: "🏆👕", level: "medium" },
  { id: "billabong", title: "Billabong", emojis: "🌊🏄", level: "medium" },
  { id: "zara", title: "Zara", emojis: "👗⚫", level: "medium" },
  { id: "hm", title: "H&M", emojis: "👕🔴", level: "medium" },
  { id: "milka", title: "Milka", emojis: "🍫🐄", level: "medium" },
  { id: "campbells", title: "Campbell's", emojis: "🥫🔴", level: "medium" },
  { id: "lays", title: "Lay's", emojis: "🥔🟡", level: "medium" },
  { id: "doritos", title: "Doritos", emojis: "🔺🔴", level: "medium" },
  { id: "kelloggs", title: "Kellogg's", emojis: "🐓🌽", level: "medium" },
  { id: "nesquik", title: "Nesquik", emojis: "🐰🥛", level: "medium" },
  { id: "jackdaniels", title: "Jack Daniel's", emojis: "🥃⬛", level: "medium" },
  { id: "mountaindew", title: "Mountain Dew", emojis: "🥤🟢", level: "medium" },

  // ===== HARD (25) =====
  { id: "vespa", title: "Vespa", emojis: "🛵🐝", level: "hard" },
  { id: "tiffany", title: "Tiffany & Co.", emojis: "💍🔵", level: "hard" },
  { id: "cartier", title: "Cartier", emojis: "⌚🐆", level: "hard" },
  { id: "swatch", title: "Swatch", emojis: "⌚🌈", level: "hard" },
  { id: "hermes", title: "Hermès", emojis: "👜🟠", level: "hard" },
  { id: "fendi", title: "Fendi", emojis: "👜🟡", level: "hard" },
  { id: "pandora", title: "Pandora", emojis: "💍📦", level: "hard" },
  { id: "swarovski", title: "Swarovski", emojis: "💎✨", level: "hard" },
  { id: "reebok", title: "Reebok", emojis: "👟⚡", level: "hard" },
  { id: "loreal", title: "L'Oréal", emojis: "💇✨", level: "hard" },
  { id: "maybelline", title: "Maybelline", emojis: "👁✨", level: "hard" },
  { id: "axe", title: "Axe", emojis: "🪓💨", level: "hard" },
  { id: "oldspice", title: "Old Spice", emojis: "⛵🧼", level: "hard" },
  { id: "crest", title: "Crest", emojis: "🪥🔵", level: "hard" },
  { id: "vaseline", title: "Vaseline", emojis: "🫙🤍", level: "hard" },
  { id: "intel", title: "Intel", emojis: "💻🎵", level: "hard" },
  { id: "drpepper", title: "Dr Pepper", emojis: "🥤🟤", level: "hard" },
  { id: "wendys", title: "Wendy's", emojis: "🍔🟠", level: "hard" },
  { id: "baskinrobbins", title: "Baskin-Robbins", emojis: "🍦🔢", level: "hard" },
  { id: "cinnabon", title: "Cinnabon", emojis: "🌀🍞", level: "hard" },
  { id: "chickfila", title: "Chick-fil-A", emojis: "🐄🍗", level: "hard" },
  { id: "innout", title: "In-N-Out", emojis: "🍔🌴", level: "hard" },
  { id: "shakeshack", title: "Shake Shack", emojis: "🍦🍔", level: "hard" },
  { id: "pandaexpress", title: "Panda Express", emojis: "🐼🍜", level: "hard" },
  { id: "olivegarden", title: "Olive Garden", emojis: "🫒🌿", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "emirates", title: "Emirates", emojis: "✈🟡", level: "impossible" },
  { id: "ryanair", title: "Ryanair", emojis: "✈💛", level: "impossible" },
  { id: "easyjet", title: "EasyJet", emojis: "✈🟠", level: "impossible" },
  { id: "klm", title: "KLM", emojis: "✈👑", level: "impossible" },
  { id: "pixar", title: "Pixar", emojis: "💡🎬", level: "impossible" },
  { id: "marvel", title: "Marvel", emojis: "🦸🔴", level: "impossible" },
  { id: "uno", title: "UNO", emojis: "🃏🔴", level: "impossible" },
  { id: "skype", title: "Skype", emojis: "📞🔵", level: "impossible" },
  { id: "doordash", title: "DoorDash", emojis: "🚪🏃", level: "impossible" },
  { id: "lyft", title: "Lyft", emojis: "🚗💗", level: "impossible" },
  { id: "chipotle", title: "Chipotle", emojis: "🌯🌶", level: "impossible" },
  { id: "cadbury", title: "Cadbury", emojis: "🍫🟣", level: "impossible" },
  { id: "dell", title: "Dell", emojis: "💻🔵", level: "impossible" },
  { id: "absolut", title: "Absolut Vodka", emojis: "🍸⬜", level: "impossible" },
  { id: "shazam", title: "Shazam", emojis: "🎧🔵", level: "impossible" },
  { id: "mailchimp", title: "Mailchimp", emojis: "🐵💛", level: "impossible" },
  { id: "evernote", title: "Evernote", emojis: "🐘💚", level: "impossible" },
  { id: "tumblr", title: "Tumblr", emojis: "📝🔵", level: "impossible" },
  { id: "myspace", title: "Myspace", emojis: "👤🔵", level: "impossible" },
  { id: "napster", title: "Napster", emojis: "🎵🐱", level: "impossible" },
  { id: "blackberry", title: "BlackBerry", emojis: "📱⚫", level: "impossible" },
  { id: "nokia", title: "Nokia", emojis: "📱🐍", level: "impossible" },
  { id: "sega", title: "Sega", emojis: "🎮🦔", level: "impossible" },
  { id: "atari", title: "Atari", emojis: "👾🔲", level: "impossible" },
  { id: "quiksilver", title: "Quiksilver", emojis: "🌊⚡", level: "impossible" },
];
