// E239 «Guess the Brand by Emoji 6» — 100 brands · 25/tier · clue via OpenMoji
export const BRAND_EMOJI6 = [
  // ===== EASY (25) =====
  { id: "renault", title: "Renault", emojis: "🚗🔷", level: "easy" },
  { id: "opel", title: "Opel", emojis: "🚗⚡", level: "easy" },
  { id: "xiaomi", title: "Xiaomi", emojis: "📱🐰", level: "easy" },
  { id: "huawei", title: "Huawei", emojis: "📱🌸", level: "easy" },
  { id: "kraft", title: "Kraft", emojis: "🧀📦", level: "easy" },
  { id: "7up", title: "7Up", emojis: "🥤🍋", level: "easy" },
  { id: "uniqlo", title: "Uniqlo", emojis: "👕🧦", level: "easy" },
  { id: "fila", title: "Fila", emojis: "👟🎾", level: "easy" },
  { id: "tommy-hilfiger", title: "Tommy Hilfiger", emojis: "⛵👕", level: "easy" },
  { id: "calvin-klein", title: "Calvin Klein", emojis: "👖✨", level: "easy" },
  { id: "southwest-airlines", title: "Southwest Airlines", emojis: "✈❤", level: "easy" },
  { id: "espn", title: "ESPN", emojis: "🏈📺", level: "easy" },
  { id: "warner-bros", title: "Warner Bros", emojis: "🎬🐰", level: "easy" },
  { id: "universal-pictures", title: "Universal Pictures", emojis: "🎬🌍", level: "easy" },
  { id: "paramount-pictures", title: "Paramount Pictures", emojis: "🎬🏔", level: "easy" },
  { id: "hbo", title: "HBO", emojis: "📺🐉", level: "easy" },
  { id: "fox", title: "Fox", emojis: "📺🦊", level: "easy" },
  { id: "cnn", title: "CNN", emojis: "📺🗽", level: "easy" },
  { id: "bbc", title: "BBC", emojis: "📺👑", level: "easy" },
  { id: "mtv", title: "MTV", emojis: "📺🎵", level: "easy" },
  { id: "fortnite", title: "Fortnite", emojis: "🎮🏝", level: "easy" },
  { id: "pokemon", title: "Pokémon", emojis: "🎮⚡", level: "easy" },
  { id: "pac-man", title: "Pac-Man", emojis: "🎮👻", level: "easy" },
  { id: "super-mario", title: "Super Mario", emojis: "🎮🍄", level: "easy" },
  { id: "american-express", title: "American Express", emojis: "💳🎖", level: "easy" },
  // ===== MEDIUM (25) =====
  { id: "nissan", title: "Nissan", emojis: "🚗🍃", level: "medium" },
  { id: "suzuki", title: "Suzuki", emojis: "🚗🛵", level: "medium" },
  { id: "mazda", title: "Mazda", emojis: "🚗🌀", level: "medium" },
  { id: "mitsubishi", title: "Mitsubishi", emojis: "🚗💎", level: "medium" },
  { id: "lenovo", title: "Lenovo", emojis: "🧠💻", level: "medium" },
  { id: "asus", title: "Asus", emojis: "🦅💻", level: "medium" },
  { id: "alibaba", title: "Alibaba", emojis: "📦🛍", level: "medium" },
  { id: "aliexpress", title: "AliExpress", emojis: "📦🌐", level: "medium" },
  { id: "shopify", title: "Shopify", emojis: "🛍💻", level: "medium" },
  { id: "expedia", title: "Expedia", emojis: "✈🧳", level: "medium" },
  { id: "philadelphia", title: "Philadelphia", emojis: "🧀🥯", level: "medium" },
  { id: "chips-ahoy", title: "Chips Ahoy", emojis: "🍪⚓", level: "medium" },
  { id: "carlsberg", title: "Carlsberg", emojis: "🍺👑", level: "medium" },
  { id: "head-and-shoulders", title: "Head & Shoulders", emojis: "🧴❄", level: "medium" },
  { id: "skechers", title: "Skechers", emojis: "👟☁", level: "medium" },
  { id: "hollister", title: "Hollister", emojis: "🏖🦅", level: "medium" },
  { id: "citibank", title: "Citibank", emojis: "🏦🌃", level: "medium" },
  { id: "chase", title: "Chase", emojis: "🏦🗽", level: "medium" },
  { id: "hsbc", title: "HSBC", emojis: "🏦🌐", level: "medium" },
  { id: "sonos", title: "Sonos", emojis: "🔊🏠", level: "medium" },
  { id: "marshall", title: "Marshall", emojis: "🔊🎸", level: "medium" },
  { id: "rockstar-games", title: "Rockstar Games", emojis: "🎮🚓", level: "medium" },
  { id: "cartoon-network", title: "Cartoon Network", emojis: "📺🎨", level: "medium" },
  { id: "nickelodeon", title: "Nickelodeon", emojis: "📺🧽", level: "medium" },
  { id: "tetris", title: "Tetris", emojis: "🎮🧱", level: "medium" },
  // ===== HARD (25) =====
  { id: "razer", title: "Razer", emojis: "🐍💻", level: "hard" },
  { id: "baidu", title: "Baidu", emojis: "🐾🔍", level: "hard" },
  { id: "tencent", title: "Tencent", emojis: "🐧💬", level: "hard" },
  { id: "wechat", title: "WeChat", emojis: "💬📱", level: "hard" },
  { id: "wayfair", title: "Wayfair", emojis: "🛋📦", level: "hard" },
  { id: "ruffles", title: "Ruffles", emojis: "🥔🌊", level: "hard" },
  { id: "mentos", title: "Mentos", emojis: "🥤💥", level: "hard" },
  { id: "jameson", title: "Jameson", emojis: "🥃☘", level: "hard" },
  { id: "jim-beam", title: "Jim Beam", emojis: "🥃🌽", level: "hard" },
  { id: "herbal-essences", title: "Herbal Essences", emojis: "🧴🌿", level: "hard" },
  { id: "cerave", title: "CeraVe", emojis: "🧴🧪", level: "hard" },
  { id: "listerine", title: "Listerine", emojis: "🦷💧", level: "hard" },
  { id: "warby-parker", title: "Warby Parker", emojis: "👓📦", level: "hard" },
  { id: "seiko", title: "Seiko", emojis: "⌚🗻", level: "hard" },
  { id: "citizen", title: "Citizen", emojis: "⌚☀", level: "hard" },
  { id: "qatar-airways", title: "Qatar Airways", emojis: "✈🐫", level: "hard" },
  { id: "etihad-airways", title: "Etihad Airways", emojis: "✈🌴", level: "hard" },
  { id: "cathay-pacific", title: "Cathay Pacific", emojis: "✈🀄", level: "hard" },
  { id: "japan-airlines", title: "Japan Airlines", emojis: "✈🗻", level: "hard" },
  { id: "among-us", title: "Among Us", emojis: "🚀🔪", level: "hard" },
  { id: "pubg", title: "PUBG", emojis: "🎮🪂", level: "hard" },
  { id: "goldman-sachs", title: "Goldman Sachs", emojis: "🏦🥇", level: "hard" },
  { id: "beats-by-dre", title: "Beats by Dre", emojis: "🎧🎤", level: "hard" },
  { id: "ubisoft", title: "Ubisoft", emojis: "🎮🗡", level: "hard" },
  { id: "naughty-dog", title: "Naughty Dog", emojis: "🎮🐶", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { id: "ducati", title: "Ducati", emojis: "🏍❤", level: "impossible" },
  { id: "kawasaki", title: "Kawasaki", emojis: "🏍🥷", level: "impossible" },
  { id: "triumph-motorcycles", title: "Triumph Motorcycles", emojis: "🏍👑", level: "impossible" },
  { id: "rivian", title: "Rivian", emojis: "🚗⛰", level: "impossible" },
  { id: "lucid-motors", title: "Lucid Motors", emojis: "🚗💡", level: "impossible" },
  { id: "polestar", title: "Polestar", emojis: "🚗⭐", level: "impossible" },
  { id: "infiniti", title: "Infiniti", emojis: "🚗♾", level: "impossible" },
  { id: "halls", title: "Halls", emojis: "🤧🍬", level: "impossible" },
  { id: "chivas-regal", title: "Chivas Regal", emojis: "🥃👑", level: "impossible" },
  { id: "dom-perignon", title: "Dom Pérignon", emojis: "🍾💰", level: "impossible" },
  { id: "saudia", title: "Saudia", emojis: "✈🕌", level: "impossible" },
  { id: "epic-games", title: "Epic Games", emojis: "🎮⚔", level: "impossible" },
  { id: "valve-corporation", title: "Valve Corporation", emojis: "🎮🌀", level: "impossible" },
  { id: "muji", title: "Muji", emojis: "🛍🤍", level: "impossible" },
  { id: "decathlon", title: "Decathlon", emojis: "🏃🏸", level: "impossible" },
  { id: "aldi", title: "Aldi", emojis: "🛒💸", level: "impossible" },
  { id: "7-eleven", title: "7-Eleven", emojis: "🏪🕛", level: "impossible" },
  { id: "walgreens", title: "Walgreens", emojis: "💊⚕", level: "impossible" },
  { id: "cvs-pharmacy", title: "CVS Pharmacy", emojis: "💊🩹", level: "impossible" },
  { id: "trader-joes", title: "Trader Joe's", emojis: "🛒🌺", level: "impossible" },
  { id: "whole-foods", title: "Whole Foods", emojis: "🛒🥦", level: "impossible" },
  { id: "panera-bread", title: "Panera Bread", emojis: "🍞💻", level: "impossible" },
  { id: "red-robin", title: "Red Robin", emojis: "🍔🐦", level: "impossible" },
  { id: "chilis", title: "Chili's", emojis: "🌶🍔", level: "impossible" },
  { id: "hooters", title: "Hooters", emojis: "🦉🍗", level: "impossible" },
];
