// «Guess the Brand by its Slogan» — GuessSync E123 · 100 real brand slogans (25/tier)
// Pure TEXT clue: the brand's famous slogan is shown as big styled text; answer is the BRAND.
// Tiered by fame: ultra-famous global taglines => easy; obscure but real, verified => impossible.
// Every slogan is a REAL slogan actually used by that brand — verified via WebSearch where uncertain.
// Answer VO bs-<slug>.wav = "It's <name>!"
export const BRAND_SLOGAN = [
  // EASY (25)
  { slug: "nike", name: "Nike", slogan: "Just Do It", level: "easy" },
  { slug: "mcdonalds", name: "McDonald's", slogan: "I'm Lovin' It", level: "easy" },
  { slug: "apple", name: "Apple", slogan: "Think Different", level: "easy" },
  { slug: "loreal", name: "L'Oreal", slogan: "Because You're Worth It", level: "easy" },
  { slug: "kfc", name: "KFC", slogan: "Finger Lickin' Good", level: "easy" },
  { slug: "bmw", name: "BMW", slogan: "The Ultimate Driving Machine", level: "easy" },
  { slug: "adidas", name: "Adidas", slogan: "Impossible Is Nothing", level: "easy" },
  { slug: "redbull", name: "Red Bull", slogan: "Gives You Wiiings", level: "easy" },
  { slug: "mastercard", name: "Mastercard", slogan: "Priceless", level: "easy" },
  { slug: "gillette", name: "Gillette", slogan: "The Best a Man Can Get", level: "easy" },
  { slug: "debeers", name: "De Beers", slogan: "A Diamond Is Forever", level: "easy" },
  { slug: "lays", name: "Lay's", slogan: "Betcha Can't Eat Just One", level: "easy" },
  { slug: "energizer", name: "Energizer", slogan: "Keeps Going and Going", level: "easy" },
  { slug: "walmart", name: "Walmart", slogan: "Save Money. Live Better.", level: "easy" },
  { slug: "subway", name: "Subway", slogan: "Eat Fresh", level: "easy" },
  { slug: "dunkin", name: "Dunkin'", slogan: "America Runs on Dunkin'", level: "easy" },
  { slug: "haribo", name: "Haribo", slogan: "Kids and Grown-ups Love It So", level: "easy" },
  { slug: "skittles", name: "Skittles", slogan: "Taste the Rainbow", level: "easy" },
  { slug: "nokia", name: "Nokia", slogan: "Connecting People", level: "easy" },
  { slug: "wendys", name: "Wendy's", slogan: "Where's the Beef?", level: "easy" },
  { slug: "capitalone", name: "Capital One", slogan: "What's in Your Wallet?", level: "easy" },
  { slug: "toyota", name: "Toyota", slogan: "Let's Go Places", level: "easy" },
  { slug: "airbnb", name: "Airbnb", slogan: "Belong Anywhere", level: "easy" },
  { slug: "disney", name: "Disney", slogan: "Where Dreams Come True", level: "easy" },
  { slug: "burgerking", name: "Burger King", slogan: "Have It Your Way", level: "easy" },

  // MEDIUM (25)
  { slug: "dell", name: "Dell", slogan: "Dude, You're Getting a Dell", level: "medium" },
  { slug: "fedex", name: "FedEx", slogan: "The World On Time", level: "medium" },
  { slug: "lego", name: "LEGO", slogan: "Just Imagine", level: "medium" },
  { slug: "ikea", name: "IKEA", slogan: "Wonderful Everyday", level: "medium" },
  { slug: "avis", name: "Avis", slogan: "We Try Harder", level: "medium" },
  { slug: "heinz", name: "Heinz", slogan: "Beanz Meanz Heinz", level: "medium" },
  { slug: "levis", name: "Levi's", slogan: "Quality Never Goes Out of Style", level: "medium" },
  { slug: "volkswagen", name: "Volkswagen", slogan: "Das Auto", level: "medium" },
  { slug: "amex", name: "American Express", slogan: "Don't Leave Home Without It", level: "medium" },
  { slug: "maybelline", name: "Maybelline", slogan: "Maybe She's Born With It. Maybe It's Maybelline.", level: "medium" },
  { slug: "cocacola", name: "Coca-Cola", slogan: "Taste the Feeling", level: "medium" },
  { slug: "pepsi", name: "Pepsi", slogan: "The Choice of a New Generation", level: "medium" },
  { slug: "snickers", name: "Snickers", slogan: "You're Not You When You're Hungry", level: "medium" },
  { slug: "oldspice", name: "Old Spice", slogan: "Smell Like A Man, Man", level: "medium" },
  { slug: "audi", name: "Audi", slogan: "Vorsprung Durch Technik", level: "medium" },
  { slug: "honda", name: "Honda", slogan: "The Power of Dreams", level: "medium" },
  { slug: "ford", name: "Ford", slogan: "Built Ford Tough", level: "medium" },
  { slug: "target", name: "Target", slogan: "Expect More. Pay Less.", level: "medium" },
  { slug: "homedepot", name: "The Home Depot", slogan: "More Saving. More Doing.", level: "medium" },
  { slug: "statefarm", name: "State Farm", slogan: "Like a Good Neighbor, State Farm Is There", level: "medium" },
  { slug: "allstate", name: "Allstate", slogan: "You're in Good Hands", level: "medium" },
  { slug: "bounty", name: "Bounty", slogan: "The Quicker Picker Upper", level: "medium" },
  { slug: "mms", name: "M&M's", slogan: "Melts in Your Mouth, Not in Your Hands", level: "medium" },
  { slug: "timex", name: "Timex", slogan: "Takes a Licking and Keeps on Ticking", level: "medium" },
  { slug: "frostedflakes", name: "Frosted Flakes", slogan: "They're Great!", level: "medium" },

  // HARD (25)
  { slug: "panasonic", name: "Panasonic", slogan: "Ideas for Life", level: "hard" },
  { slug: "sony", name: "Sony", slogan: "make.believe", level: "hard" },
  { slug: "samsung", name: "Samsung", slogan: "Do What You Can't", level: "hard" },
  { slug: "lg", name: "LG", slogan: "Life's Good", level: "hard" },
  { slug: "ge", name: "GE", slogan: "Imagination at Work", level: "hard" },
  { slug: "ibm", name: "IBM", slogan: "Think", level: "hard" },
  { slug: "chipotle", name: "Chipotle", slogan: "Food With Integrity", level: "hard" },
  { slug: "pizzahut", name: "Pizza Hut", slogan: "No One OutPizzas the Hut", level: "hard" },
  { slug: "papajohns", name: "Papa John's", slogan: "Better Ingredients. Better Pizza.", level: "hard" },
  { slug: "carlsberg", name: "Carlsberg", slogan: "Probably the Best Beer in the World", level: "hard" },
  { slug: "guinness", name: "Guinness", slogan: "Good Things Come to Those Who Wait", level: "hard" },
  { slug: "budweiser", name: "Budweiser", slogan: "King of Beers", level: "hard" },
  { slug: "heineken", name: "Heineken", slogan: "Open Your World", level: "hard" },
  { slug: "duracell", name: "Duracell", slogan: "Trusted Everywhere", level: "hard" },
  { slug: "rolex", name: "Rolex", slogan: "A Crown for Every Achievement", level: "hard" },
  { slug: "jeep", name: "Jeep", slogan: "Go Anywhere. Do Anything.", level: "hard" },
  { slug: "mazda", name: "Mazda", slogan: "Zoom-Zoom", level: "hard" },
  { slug: "hyundai", name: "Hyundai", slogan: "New Thinking. New Possibilities.", level: "hard" },
  { slug: "puma", name: "Puma", slogan: "Forever Faster", level: "hard" },
  { slug: "underarmour", name: "Under Armour", slogan: "I Will", level: "hard" },
  { slug: "reebok", name: "Reebok", slogan: "Be More Human", level: "hard" },
  { slug: "gatorade", name: "Gatorade", slogan: "Is It in You?", level: "hard" },
  { slug: "michelin", name: "Michelin", slogan: "A Better Way Forward", level: "hard" },
  { slug: "siemens", name: "Siemens", slogan: "Ingenuity for Life", level: "hard" },
  { slug: "volvo", name: "Volvo", slogan: "Volvo, For Life", level: "hard" },

  // IMPOSSIBLE (25)
  { slug: "tesco", name: "Tesco", slogan: "Every Little Helps", level: "impossible" },
  { slug: "aldi", name: "Aldi", slogan: "Like Brands. Only Cheaper.", level: "impossible" },
  { slug: "lidl", name: "Lidl", slogan: "Big on Quality, Lidl on Price", level: "impossible" },
  { slug: "sainsburys", name: "Sainsbury's", slogan: "Live Well for Less", level: "impossible" },
  { slug: "johnlewis", name: "John Lewis", slogan: "Never Knowingly Undersold", level: "impossible" },
  { slug: "specsavers", name: "Specsavers", slogan: "Should've Gone to Specsavers", level: "impossible" },
  { slug: "ronseal", name: "Ronseal", slogan: "Does Exactly What It Says on the Tin", level: "impossible" },
  { slug: "comparethemarket", name: "Compare the Market", slogan: "Simples", level: "impossible" },
  { slug: "kwikfit", name: "Kwik Fit", slogan: "You Can't Get Better Than a Kwik Fit Fitter", level: "impossible" },
  { slug: "yellowpages", name: "Yellow Pages", slogan: "Let Your Fingers Do the Walking", level: "impossible" },
  { slug: "toysrus", name: "Toys R Us", slogan: "I Don't Wanna Grow Up, I'm a Toys R Us Kid", level: "impossible" },
  { slug: "meowmix", name: "Meow Mix", slogan: "Tastes So Good, Cats Ask for It by Name", level: "impossible" },
  { slug: "riceoroni", name: "Rice-A-Roni", slogan: "The San Francisco Treat", level: "impossible" },
  { slug: "greyhound", name: "Greyhound", slogan: "Leave the Driving to Us", level: "impossible" },
  { slug: "maxwellhouse", name: "Maxwell House", slogan: "Good to the Last Drop", level: "impossible" },
  { slug: "mortonsalt", name: "Morton Salt", slogan: "When It Rains It Pours", level: "impossible" },
  { slug: "alkaseltzer", name: "Alka-Seltzer", slogan: "Plop Plop Fizz Fizz, Oh What a Relief It Is", level: "impossible" },
  { slug: "trix", name: "Trix", slogan: "Silly Rabbit, Trix Are for Kids", level: "impossible" },
  { slug: "almondjoy", name: "Almond Joy", slogan: "Sometimes You Feel Like a Nut, Sometimes You Don't", level: "impossible" },
  { slug: "folgers", name: "Folgers", slogan: "The Best Part of Wakin' Up Is Folgers in Your Cup", level: "impossible" },
  { slug: "littlecaesars", name: "Little Caesars", slogan: "Pizza Pizza", level: "impossible" },
  { slug: "arbys", name: "Arby's", slogan: "We Have the Meats", level: "impossible" },
  { slug: "popeyes", name: "Popeyes", slogan: "Love That Chicken from Popeyes", level: "impossible" },
  { slug: "sprite", name: "Sprite", slogan: "Obey Your Thirst", level: "impossible" },
  { slug: "drpepper", name: "Dr Pepper", slogan: "What's the Worst That Could Happen?", level: "impossible" },
];
