// «Guess the Bread» — GuessSync · E65 · 100 breads of the world (25/tier) · real photos from Wikimedia Commons
// Absolute difficulty by global recognisability: easy (Baguette/Bagel) ← impossible (Injera/Cozonac/Selroti).
export const BREADS = [
  // EASY (25) — household-name breads
  { slug: "baguette", name: "Baguette", level: "easy" },
  { slug: "ciabatta", name: "Ciabatta", level: "easy" },
  { slug: "sourdough", name: "Sourdough", level: "easy" },
  { slug: "pita", name: "Pita", level: "easy" },
  { slug: "naan", name: "Naan", level: "easy" },
  { slug: "bagel", name: "Bagel", level: "easy" },
  { slug: "pretzel", name: "Pretzel", level: "easy" },
  { slug: "focaccia", name: "Focaccia", level: "easy" },
  { slug: "brioche", name: "Brioche", level: "easy" },
  { slug: "ryebread", name: "Rye Bread", level: "easy" },
  { slug: "cornbread", name: "Cornbread", level: "easy" },
  { slug: "tortilla", name: "Tortilla", level: "easy" },
  { slug: "whiteloaf", name: "White Loaf", level: "easy" },
  { slug: "croissant", name: "Croissant", level: "easy" },
  { slug: "flatbread", name: "Flatbread", level: "easy" },
  { slug: "roti", name: "Roti", level: "easy" },
  { slug: "dinnerroll", name: "Dinner Roll", level: "easy" },
  { slug: "wholewheat", name: "Whole Wheat Bread", level: "easy" },
  { slug: "garlicbread", name: "Garlic Bread", level: "easy" },
  { slug: "breadstick", name: "Breadstick", level: "easy" },
  { slug: "englishmuffin", name: "English Muffin", level: "easy" },
  { slug: "burgerbun", name: "Burger Bun", level: "easy" },
  { slug: "multigrain", name: "Multigrain Bread", level: "easy" },
  { slug: "crumpet", name: "Crumpet", level: "easy" },
  { slug: "matzo", name: "Matzo", level: "easy" },
  // MEDIUM (25) — recognisable, needs a beat
  { slug: "bao", name: "Bao Bun", level: "medium" },
  { slug: "paindecampagne", name: "Pain de Campagne", level: "medium" },
  { slug: "sodabread", name: "Soda Bread", level: "medium" },
  { slug: "fougasse", name: "Fougasse", level: "medium" },
  { slug: "kaiserroll", name: "Kaiser Roll", level: "medium" },
  { slug: "boule", name: "Boule", level: "medium" },
  { slug: "chapati", name: "Chapati", level: "medium" },
  { slug: "paratha", name: "Paratha", level: "medium" },
  { slug: "puri", name: "Puri", level: "medium" },
  { slug: "grissini", name: "Grissini", level: "medium" },
  { slug: "simit", name: "Simit", level: "medium" },
  { slug: "pide", name: "Pide", level: "medium" },
  { slug: "roticanai", name: "Roti Canai", level: "medium" },
  { slug: "arepa", name: "Arepa", level: "medium" },
  { slug: "pupusa", name: "Pupusa", level: "medium" },
  { slug: "bolillo", name: "Bolillo", level: "medium" },
  { slug: "shokupan", name: "Milk Bread", level: "medium" },
  { slug: "melonpan", name: "Melonpan", level: "medium" },
  { slug: "paodequeijo", name: "Pão de Queijo", level: "medium" },
  { slug: "frybread", name: "Frybread", level: "medium" },
  { slug: "subroll", name: "Sub Roll", level: "medium" },
  { slug: "mantou", name: "Mantou", level: "medium" },
  { slug: "bing", name: "Bing", level: "medium" },
  { slug: "ekmek", name: "Ekmek", level: "medium" },
  { slug: "semolinabread", name: "Semolina Bread", level: "medium" },
  // HARD (25) — regional, less common globally
  { slug: "pumpernickel", name: "Pumpernickel", level: "hard" },
  { slug: "challah", name: "Challah", level: "hard" },
  { slug: "zopf", name: "Zopf", level: "hard" },
  { slug: "rugbrod", name: "Rugbrød", level: "hard" },
  { slug: "bannock", name: "Bannock", level: "hard" },
  { slug: "damper", name: "Damper", level: "hard" },
  { slug: "johnnycake", name: "Johnnycake", level: "hard" },
  { slug: "bialy", name: "Bialy", level: "hard" },
  { slug: "ficelle", name: "Ficelle", level: "hard" },
  { slug: "panecarasau", name: "Pane Carasau", level: "hard" },
  { slug: "michetta", name: "Michetta", level: "hard" },
  { slug: "broa", name: "Broa", level: "hard" },
  { slug: "vetkoek", name: "Vetkoek", level: "hard" },
  { slug: "sangak", name: "Sangak", level: "hard" },
  { slug: "taftan", name: "Taftan", level: "hard" },
  { slug: "rotijala", name: "Roti Jala", level: "hard" },
  { slug: "kulcha", name: "Kulcha", level: "hard" },
  { slug: "bhatura", name: "Bhatura", level: "hard" },
  { slug: "sheermal", name: "Sheermal", level: "hard" },
  { slug: "gozleme", name: "Gözleme", level: "hard" },
  { slug: "khachapuri", name: "Khachapuri", level: "hard" },
  { slug: "somun", name: "Somun", level: "hard" },
  { slug: "pogaca", name: "Pogača", level: "hard" },
  { slug: "altamura", name: "Pane di Altamura", level: "hard" },
  { slug: "yufka", name: "Yufka", level: "hard" },
  // IMPOSSIBLE (25) — obscure regional breads
  { slug: "injera", name: "Injera", level: "impossible" },
  { slug: "lavash", name: "Lavash", level: "impossible" },
  { slug: "pandesal", name: "Pandesal", level: "impossible" },
  { slug: "barbari", name: "Barbari", level: "impossible" },
  { slug: "borodinsky", name: "Borodinsky", level: "impossible" },
  { slug: "bammy", name: "Bammy", level: "impossible" },
  { slug: "rieska", name: "Rieska", level: "impossible" },
  { slug: "vanocka", name: "Vánočka", level: "impossible" },
  { slug: "kalach", name: "Kalach", level: "impossible" },
  { slug: "coppiaferrarese", name: "Coppia Ferrarese", level: "impossible" },
  { slug: "kaak", name: "Ka'ak", level: "impossible" },
  { slug: "manakish", name: "Manakish", level: "impossible" },
  { slug: "markook", name: "Markook", level: "impossible" },
  { slug: "kisra", name: "Kisra", level: "impossible" },
  { slug: "aishbaladi", name: "Aish Baladi", level: "impossible" },
  { slug: "matnakash", name: "Matnakash", level: "impossible" },
  { slug: "shotispuri", name: "Shotis Puri", level: "impossible" },
  { slug: "obinon", name: "Obi Non", level: "impossible" },
  { slug: "bazlama", name: "Bazlama", level: "impossible" },
  { slug: "rewena", name: "Rewena Bread", level: "impossible" },
  { slug: "selroti", name: "Selroti", level: "impossible" },
  { slug: "paximadi", name: "Paximadi", level: "impossible" },
  { slug: "freselle", name: "Freselle", level: "impossible" },
  { slug: "vortbrod", name: "Vörtbröd", level: "impossible" },
  { slug: "cozonac", name: "Cozonac", level: "impossible" },
];
