// «Guess the Bread» — GuessSync · E65 · did-you-know facts, ≤70 chars, verified true.
export const BREAD_FACTS = {
  // EASY
  "baguette": "Long, thin French loaf with a crisp crust and airy crumb",
  "ciabatta": "Italian wheat loaf; its name means 'slipper' in Italian",
  "sourdough": "Leavened by wild yeast and bacteria, giving a tangy taste",
  "pita": "Middle Eastern flatbread that puffs into a hollow pocket",
  "naan": "Leavened flatbread baked on a tandoor oven's hot wall",
  "bagel": "Boiled then baked ring of dough, of Polish-Jewish origin",
  "pretzel": "Knot-shaped bread of German origin, often salted",
  "focaccia": "Flat Italian oven bread dimpled and drizzled with oil",
  "brioche": "Rich French bread enriched with butter and eggs",
  "ryebread": "Dark, dense bread made partly or fully from rye flour",
  "cornbread": "American quick bread made from cornmeal, popular in the South",
  "tortilla": "Thin Mexican flatbread made from corn or wheat",
  "whiteloaf": "Soft sandwich loaf baked from refined white wheat flour",
  "croissant": "Flaky French crescent pastry of laminated buttery dough",
  "flatbread": "Thin unleavened or lightly leavened bread, eaten worldwide",
  "roti": "Unleavened Indian flatbread cooked on a hot griddle",
  "dinnerroll": "Small soft round of bread served alongside a meal",
  "wholewheat": "Bread made with flour that keeps the whole wheat grain",
  "garlicbread": "Bread topped with garlic butter and baked until golden",
  "breadstick": "Long, crisp dry stick of baked bread, of Italian origin",
  "englishmuffin": "Round griddled bread split and toasted, full of nooks",
  "burgerbun": "Soft round roll used to hold a hamburger patty",
  "multigrain": "Bread made from several grains and seeds for extra fibre",
  "crumpet": "Griddled British batter cake, spongy and full of holes",
  "matzo": "Unleavened Jewish flatbread eaten during Passover",
  // MEDIUM
  "bao": "Soft Chinese steamed bun, often folded around a filling",
  "paindecampagne": "French sourdough country loaf of wheat and rye flour",
  "sodabread": "Irish quick bread leavened with baking soda, not yeast",
  "fougasse": "Provençal flatbread slashed to resemble a leaf or ear",
  "kaiserroll": "Crusty round Austrian roll with a pinwheel top pattern",
  "boule": "Round rustic French loaf; its name means 'ball'",
  "chapati": "Unleavened Indian whole-wheat flatbread, a daily staple",
  "paratha": "Flaky, layered Indian flatbread fried on a griddle",
  "puri": "Deep-fried Indian flatbread that puffs up into a ball",
  "grissini": "Thin, crisp Italian breadsticks originating in Turin",
  "simit": "Turkish ring bread crusted with sesame seeds",
  "pide": "Turkish boat-shaped flatbread, often topped and filled",
  "roticanai": "Flaky Malaysian flatbread of Indian origin, served with curry",
  "arepa": "Cornmeal cake from Venezuela and Colombia, grilled or fried",
  "pupusa": "Thick stuffed corn flatbread, the national dish of El Salvador",
  "bolillo": "Crusty Mexican savoury roll shaped like a small baguette",
  "shokupan": "Soft, fluffy Japanese milk bread baked as a square loaf",
  "melonpan": "Sweet Japanese bun with a crisp cookie crust, no melon",
  "paodequeijo": "Brazilian cheese bread made with tapioca starch",
  "frybread": "Native American flatbread fried until golden and puffy",
  "subroll": "Long soft roll used to make submarine sandwiches",
  "mantou": "Plain Chinese steamed bun, a staple in northern China",
  "bing": "Chinese flatbread, pan-fried or baked in many forms",
  "ekmek": "Turkish everyday loaf; the word simply means 'bread'",
  "semolinabread": "Golden Italian bread made from durum wheat semolina",
  // HARD
  "pumpernickel": "Dense German rye bread baked slowly for many hours",
  "challah": "Braided Jewish egg bread eaten on the Sabbath",
  "zopf": "Swiss braided loaf of white flour, milk, butter and egg",
  "rugbrod": "Dense Danish rye bread packed with whole grains and seeds",
  "bannock": "Flat Scottish griddle bread, historically made of oats",
  "damper": "Australian bush soda bread once baked in campfire coals",
  "johnnycake": "Flat cornmeal bread of North America and the Caribbean",
  "bialy": "Chewy Polish-Jewish roll with an onion-filled centre",
  "ficelle": "Very thin French loaf, even slimmer than a baguette",
  "panecarasau": "Crisp, paper-thin Sardinian flatbread for shepherds",
  "michetta": "Hollow, star-shaped crusty roll from Milan, Italy",
  "broa": "Portuguese and Galician cornbread with a dense crumb",
  "vetkoek": "South African deep-fried dough bun, filled savoury or sweet",
  "sangak": "Iranian whole-wheat flatbread baked on hot stones",
  "taftan": "Leavened Persian and South Asian flatbread, often saffroned",
  "rotijala": "Lacy Malaysian net bread served with curry",
  "kulcha": "Soft leavened Indian flatbread, popular in Punjab",
  "bhatura": "Fluffy deep-fried Indian bread paired with chickpeas",
  "sheermal": "Mildly sweet saffron flatbread of Iran and South Asia",
  "gozleme": "Turkish hand-rolled flatbread stuffed and griddled",
  "khachapuri": "Georgian cheese-filled bread, often boat-shaped with egg",
  "somun": "Balkan leavened flatbread eaten during Ramadan",
  "pogaca": "Balkan and Turkish soft bread roll, sometimes filled",
  "altamura": "Italian durum-wheat sourdough from Altamura, Apulia",
  "yufka": "Thin Turkish unleavened flatbread, like a large wrap",
  // IMPOSSIBLE
  "injera": "Spongy Ethiopian sourdough flatbread made from teff",
  "lavash": "Thin Armenian flatbread baked in a tandoor-style oven",
  "pandesal": "Soft Filipino bread roll dusted with breadcrumbs",
  "barbari": "Thick Iranian flatbread, long with ridged top",
  "borodinsky": "Dark Russian rye bread flavoured with coriander",
  "bammy": "Jamaican flatbread made from grated cassava",
  "rieska": "Finnish flat barley or potato bread, quickly baked",
  "vanocka": "Czech braided sweet bread eaten at Christmas",
  "kalach": "Eastern European braided or ring-shaped white bread",
  "coppiaferrarese": "Twisted sourdough bread from Ferrara, Italy",
  "kaak": "Levantine bread ring crusted with sesame seeds",
  "manakish": "Levantine flatbread topped with za'atar and oil",
  "markook": "Very thin Levantine bread baked on a domed saj griddle",
  "kisra": "Thin Sudanese sorghum flatbread, slightly fermented",
  "aishbaladi": "Egyptian whole-wheat pita baked in very hot ovens",
  "matnakash": "Soft Armenian leavened bread with a grooved crust",
  "shotispuri": "Georgian bread baked on the wall of a tone oven",
  "obinon": "Round Uzbek tandoor bread stamped in the centre",
  "bazlama": "Turkish leavened village flatbread cooked on a griddle",
  "rewena": "Maori potato sourdough bread from New Zealand",
  "selroti": "Nepalese ring-shaped fried bread of rice flour",
  "paximadi": "Greek twice-baked barley rusk, very hard and dry",
  "freselle": "Southern Italian dried bread rings, soaked before eating",
  "vortbrod": "Swedish sweet rye bread made with spiced wort",
  "cozonac": "Romanian sweet braided bread with walnut filling",
};
