// BUTTERFLIES2 — one true ≤70-char fact per species, shown on the reveal.
export const BUTTERFLIES2_FACTS = {
  // ===== EASY =====
  "cloudless-sulphur": "Its caterpillars feed only on senna plants in the pea family.",
  "black-swallowtail": "It is the state butterfly of Oklahoma and New Jersey.",
  "anise-swallowtail": "Its larvae feed on anise, fennel, and other carrot-family plants.",
  "western-tiger-swallowtail": "It is common along rivers and streams in the American West.",
  "checkered-white": "Males and females show different wing patterns, unlike most whites.",
  "great-southern-white": "Large migratory swarms sometimes cross the Florida coastline.",
  "sleepy-orange": "Its name comes from a dark bar on the forewing, not its speed.",
  "white-peacock": "Its pale wings show faint eyespots ringed in orange-brown.",
  "red-spotted-purple": "It mimics the toxic pipevine swallowtail to deter predators.",
  "banded-orange": "Bright orange bands warn predators it may taste unpleasant.",
  "common-mormon": "Females can mimic several distasteful swallowtail species.",
  "lime-swallowtail": "Its caterpillars are pests on citrus trees across Asia.",
  "plain-tiger": "It stores toxins from milkweed to stay safe from predators.",
  "common-crow": "Its slow, gliding flight signals to birds that it tastes bad.",
  "common-rose": "Bright red body spots warn predators of its toxicity.",
  "paper-kite": "Its huge white wings make it a popular butterfly-house species.",
  "blue-pansy": "Males flash iridescent blue patches to attract mates.",
  "lemon-pansy": "Its wing color shifts with the season, pale in the dry months.",
  "isabella-tiger-moth": "Its fuzzy caterpillar is the famous banded woolly bear.",
  "peppered-moth": "It became a textbook example of evolution during England's soot era.",
  "spongy-moth": "Its name was changed in 2022 from an ethnic slur once used for it.",
  "tomato-hornworm-moth": "Its caterpillar is the green hornworm that strips tomato plants.",
  "puss-moth": "Its caterpillar rears up like a snake and sprays acid at threats.",
  "bogong-moth": "Billions migrate to cool Australian caves to escape summer heat.",
  "scarce-swallowtail": "Despite its name, it is fairly common across southern Europe.",

  // ===== MEDIUM =====
  "doris-longwing": "It comes in three color forms: red, blue, and yellow.",
  "sara-longwing": "Its glowing blue-green wings warn birds it is unpalatable.",
  "crimson-patched-longwing": "It can live for months, far longer than most butterflies.",
  "chocolate-pansy": "Its brown wings help it vanish among dry forest leaf litter.",
  "grey-pansy": "It often rests near ponds and marshy forest edges in Asia.",
  "yellow-pansy": "Bold orange-yellow wings carry a ring of blue eyespots.",
  "striped-blue-crow": "Its dark wings shimmer with blue-violet in direct sunlight.",
  "orange-barred-sulphur": "Males show a bold orange bar absent in most females.",
  "statira-sulphur": "Large flocks sometimes gather at damp mud puddles to drink.",
  "convolvulus-hawk-moth": "Its long tongue can reach nectar deep inside tubular flowers.",
  "privet-hawk-moth": "It is one of the largest moths found in Great Britain.",
  "poplar-hawk-moth": "At rest it holds its hind wings oddly ahead of the front ones.",
  "lime-hawk-moth": "Its caterpillar feeds on lime, elm, and birch tree leaves.",
  "eyed-hawk-moth": "Flashing hidden pink eyespots startles birds that threaten it.",
  "buff-tip-moth": "At rest its folded wings look just like a broken birch twig.",
  "vapourer-moth": "Females are wingless and never fly far from their cocoon.",
  "large-yellow-underwing": "Its dull brown forewings hide bright orange hind wings.",
  "red-underwing-moth": "Flashing crimson hind wings startle predators when disturbed.",
  "old-lady-moth": "Its dusky, mottled wings resemble an old woven shawl pattern.",
  "emperor-gum-moth": "Its huge caterpillar feeds on eucalyptus leaves in Australia.",
  "indian-moon-moth": "Long trailing tails on its wings mimic a bat's echo signal.",
  "ailanthus-silk-moth": "It was introduced to feed silk farms far from its native Asia.",
  "carolina-sphinx-moth": "Its caterpillar, the tobacco hornworm, feeds on nightshade plants.",
  "silver-washed-fritillary": "Males release a scent from special scales along wing veins.",
  "dark-green-fritillary": "Its underwings show a greenish sheen among silvery spots.",

  // ===== HARD =====
  "common-nawab": "It often perches high on treetops with wings held flat open.",
  "jungle-queen": "One of Asia's largest forest butterflies, it favors bamboo groves.",
  "common-lascar": "Its striped wing pattern resembles a naval officer's sleeve.",
  "commander-butterfly": "It patrols forest paths with a fast, darting flight.",
  "chestnut-tiger": "It migrates hundreds of miles between Japan and Taiwan.",
  "common-birdwing": "One of the largest butterflies in Southeast Asia's forests.",
  "golden-birdwing": "Males show brilliant gold hind wings that flash in flight.",
  "common-jay": "Its wings show pale green spots against velvety black.",
  "five-bar-swordtail": "Long tails on its hind wings trail like a swordsman's blade.",
  "clouded-apollo": "It lives in mountain meadows and depends on fumewort plants.",
  "large-copper": "It vanished from Britain in the 1850s due to fen drainage.",
  "purple-hairstreak": "It spends most of its life high in oak tree canopies.",
  "green-hairstreak": "It is Britain's only butterfly with solid green underwings.",
  "brown-hairstreak": "Females lay tiny white eggs on blackthorn twigs in autumn.",
  "white-letter-hairstreak": "Dutch elm disease wiped out much of its favored habitat.",
  "duke-of-burgundy": "Despite its name, it belongs to the metalmark family, not skippers.",
  "marsh-fritillary": "Its caterpillars spin communal silk webs on devil's-bit scabious.",
  "glanville-fritillary": "It is named after an early female British entomologist.",
  "large-blue": "Its caterpillars trick red ants into raising them as their own.",
  "silver-studded-blue": "Small silvery spots line the edge of its hind wings.",
  "long-tailed-blue": "Thin tails on its hind wings look like false antennae.",
  "wall-brown": "It often basks with open wings on sunlit bare ground or walls.",
  "grayling": "It closes its wings and tilts them to hide its shadow from birds.",
  "yellow-tail-moth": "Its caterpillar hairs can cause skin irritation if touched.",
  "oak-eggar-moth": "Its cocoon resembles a small egg, giving the moth its name.",

  // ===== IMPOSSIBLE =====
  "queen-alexandras-birdwing": "Females can span ten inches, the largest wingspan of any butterfly.",
  "homerus-swallowtail": "Jamaica's largest butterfly survives in only two isolated forests.",
  "luzon-peacock-swallowtail": "Iridescent green scales make this rare Philippine species shimmer.",
  "palawan-birdwing": "It is found only on the Philippine island of Palawan.",
  "wallaces-golden-birdwing": "Naturalist Alfred Russel Wallace named it after his own discovery.",
  "chimaera-birdwing": "It lives only in the cloud forests of Papua New Guinea's highlands.",
  "african-giant-swallowtail": "It has the widest wingspan of any African butterfly species.",
  "mocker-swallowtail": "Females mimic several toxic species, each in a different region.",
  "emperor-swallowtail": "It glides through montane African forests well above the canopy.",
  "regent-skipper": "It is the only skipper known to link its wings like a moth.",
  "green-banded-urania": "This day-flying moth is often mistaken for a tropical butterfly.",
  "hercules-moth": "It has the largest wing surface area of any moth on Earth.",
  "suraka-silk-moth": "It spins a large silk cocoon in the forests of Madagascar.",
  "owl-moth": "Its huge eyespot-like wing patterns can startle would-be predators.",
  "wallaces-sphinx-moth": "Darwin predicted its foot-long tongue before the moth was ever found.",
  "corsican-swallowtail": "This rare swallowtail survives only on Corsica and Sardinia.",
  "lesser-purple-emperor": "Its wings flash violet only when caught at certain light angles.",
  "cardinal-butterfly": "Its rosy underwing tint gives this fritillary its name.",
  "nickerbean-blue": "Its caterpillars feed on the seedpods of nickerbean shrubs.",
  "miami-blue": "One of America's most endangered butterflies, clinging to a few Keys.",
  "karner-blue": "Its caterpillars survive only on wild lupine, now increasingly rare.",
  "fenders-blue": "This Oregon prairie butterfly was thought extinct for decades.",
  "schaus-swallowtail": "Only a small population survives in the Florida Keys today.",
  "malabar-banded-peacock": "It is found only in the rainforests of India's Western Ghats.",
  "miranda-birdwing": "It lives deep in the rainforests of Borneo, rarely seen by people.",
};
