// BUTTERFLIES2 — "Guess the Butterfly & Moth v2". 100 species, 25 per difficulty tier.
// image: butterflies2/<slug>.jpg (objectFit cover) | VO: sfx/bf2-<slug>.wav ("It's the <name>!")
// images from Wikimedia Commons (PD/CC0/CC-BY/CC-BY-SA). Provenance: public/butterflies2/ATTRIBUTIONS-e-butterflies2.txt
// Confirmed zero overlap (slug AND name) with butterfliesData.js, insectsData.js, insects2Data.js.
export const BUTTERFLIES2 = [
  // ===== EASY (25) =====
  { slug: "cloudless-sulphur", name: "Cloudless Sulphur", sci: "Phoebis sennae", level: "easy" },
  { slug: "black-swallowtail", name: "Black Swallowtail", sci: "Papilio polyxenes", level: "easy" },
  { slug: "anise-swallowtail", name: "Anise Swallowtail", sci: "Papilio zelicaon", level: "easy" },
  { slug: "western-tiger-swallowtail", name: "Western Tiger Swallowtail", sci: "Papilio rutulus", level: "easy" },
  { slug: "checkered-white", name: "Checkered White", sci: "Pontia protodice", level: "easy" },
  { slug: "great-southern-white", name: "Great Southern White", sci: "Ascia monuste", level: "easy" },
  { slug: "sleepy-orange", name: "Sleepy Orange", sci: "Abaeis nicippe", level: "easy" },
  { slug: "white-peacock", name: "White Peacock", sci: "Anartia jatrophae", level: "easy" },
  { slug: "red-spotted-purple", name: "Red-spotted Purple", sci: "Limenitis arthemis astyanax", level: "easy" },
  { slug: "banded-orange", name: "Banded Orange", sci: "Dryadula phaetusa", level: "easy" },
  { slug: "common-mormon", name: "Common Mormon", sci: "Papilio polytes", level: "easy" },
  { slug: "lime-swallowtail", name: "Lime Swallowtail", sci: "Papilio demoleus", level: "easy" },
  { slug: "plain-tiger", name: "Plain Tiger", sci: "Danaus chrysippus", level: "easy" },
  { slug: "common-crow", name: "Common Crow", sci: "Euploea core", level: "easy" },
  { slug: "common-rose", name: "Common Rose", sci: "Pachliopta aristolochiae", level: "easy" },
  { slug: "paper-kite", name: "Paper Kite", sci: "Idea leuconoe", level: "easy" },
  { slug: "blue-pansy", name: "Blue Pansy", sci: "Junonia orithya", level: "easy" },
  { slug: "lemon-pansy", name: "Lemon Pansy", sci: "Junonia lemonias", level: "easy" },
  { slug: "isabella-tiger-moth", name: "Isabella Tiger Moth", sci: "Pyrrharctia isabella", level: "easy" },
  { slug: "peppered-moth", name: "Peppered Moth", sci: "Biston betularia", level: "easy" },
  { slug: "spongy-moth", name: "Spongy Moth", sci: "Lymantria dispar", level: "easy" },
  { slug: "tomato-hornworm-moth", name: "Tomato Hornworm Moth", sci: "Manduca quinquemaculata", level: "easy" },
  { slug: "puss-moth", name: "Puss Moth", sci: "Cerura vinula", level: "easy" },
  { slug: "bogong-moth", name: "Bogong Moth", sci: "Agrotis infusa", level: "easy" },
  { slug: "scarce-swallowtail", name: "Scarce Swallowtail", sci: "Iphiclides podalirius", level: "easy" },

  // ===== MEDIUM (25) =====
  { slug: "doris-longwing", name: "Doris Longwing", sci: "Heliconius doris", level: "medium" },
  { slug: "sara-longwing", name: "Sara Longwing", sci: "Heliconius sara", level: "medium" },
  { slug: "crimson-patched-longwing", name: "Crimson-patched Longwing", sci: "Heliconius erato", level: "medium" },
  { slug: "chocolate-pansy", name: "Chocolate Pansy", sci: "Junonia iphita", level: "medium" },
  { slug: "grey-pansy", name: "Grey Pansy", sci: "Junonia atlites", level: "medium" },
  { slug: "yellow-pansy", name: "Yellow Pansy", sci: "Junonia hierta", level: "medium" },
  { slug: "striped-blue-crow", name: "Striped Blue Crow", sci: "Euploea mulciber", level: "medium" },
  { slug: "orange-barred-sulphur", name: "Orange-barred Sulphur", sci: "Phoebis philea", level: "medium" },
  { slug: "statira-sulphur", name: "Statira Sulphur", sci: "Aphrissa statira", level: "medium" },
  { slug: "convolvulus-hawk-moth", name: "Convolvulus Hawk-moth", sci: "Agrius convolvuli", level: "medium" },
  { slug: "privet-hawk-moth", name: "Privet Hawk-moth", sci: "Sphinx ligustri", level: "medium" },
  { slug: "poplar-hawk-moth", name: "Poplar Hawk-moth", sci: "Laothoe populi", level: "medium" },
  { slug: "lime-hawk-moth", name: "Lime Hawk-moth", sci: "Mimas tiliae", level: "medium" },
  { slug: "eyed-hawk-moth", name: "Eyed Hawk-moth", sci: "Smerinthus ocellatus", level: "medium" },
  { slug: "buff-tip-moth", name: "Buff-tip Moth", sci: "Phalera bucephala", level: "medium" },
  { slug: "vapourer-moth", name: "Vapourer Moth", sci: "Orgyia antiqua", level: "medium" },
  { slug: "large-yellow-underwing", name: "Large Yellow Underwing", sci: "Noctua pronuba", level: "medium" },
  { slug: "red-underwing-moth", name: "Red Underwing Moth", sci: "Catocala nupta", level: "medium" },
  { slug: "old-lady-moth", name: "Old Lady Moth", sci: "Mormo maura", level: "medium" },
  { slug: "emperor-gum-moth", name: "Emperor Gum Moth", sci: "Opodiphthera eucalypti", level: "medium" },
  { slug: "indian-moon-moth", name: "Indian Moon Moth", sci: "Actias selene", level: "medium" },
  { slug: "ailanthus-silk-moth", name: "Ailanthus Silk Moth", sci: "Samia cynthia", level: "medium" },
  { slug: "carolina-sphinx-moth", name: "Carolina Sphinx Moth", sci: "Manduca sexta", level: "medium" },
  { slug: "silver-washed-fritillary", name: "Silver-washed Fritillary", sci: "Argynnis paphia", level: "medium" },
  { slug: "dark-green-fritillary", name: "Dark Green Fritillary", sci: "Argynnis aglaja", level: "medium" },

  // ===== HARD (25) =====
  { slug: "common-nawab", name: "Common Nawab", sci: "Polyura athamas", level: "hard" },
  { slug: "jungle-queen", name: "Jungle Queen", sci: "Stichophthalma camadeva", level: "hard" },
  { slug: "common-lascar", name: "Common Lascar", sci: "Pantoporia hordonia", level: "hard" },
  { slug: "commander-butterfly", name: "Commander Butterfly", sci: "Moduza procris", level: "hard" },
  { slug: "chestnut-tiger", name: "Chestnut Tiger", sci: "Parantica sita", level: "hard" },
  { slug: "common-birdwing", name: "Common Birdwing", sci: "Troides helena", level: "hard" },
  { slug: "golden-birdwing", name: "Golden Birdwing", sci: "Troides aeacus", level: "hard" },
  { slug: "common-jay", name: "Common Jay", sci: "Graphium doson", level: "hard" },
  { slug: "five-bar-swordtail", name: "Five-bar Swordtail", sci: "Graphium antiphates", level: "hard" },
  { slug: "clouded-apollo", name: "Clouded Apollo", sci: "Parnassius mnemosyne", level: "hard" },
  { slug: "large-copper", name: "Large Copper", sci: "Lycaena dispar", level: "hard" },
  { slug: "purple-hairstreak", name: "Purple Hairstreak", sci: "Favonius quercus", level: "hard" },
  { slug: "green-hairstreak", name: "Green Hairstreak", sci: "Callophrys rubi", level: "hard" },
  { slug: "brown-hairstreak", name: "Brown Hairstreak", sci: "Thecla betulae", level: "hard" },
  { slug: "white-letter-hairstreak", name: "White-letter Hairstreak", sci: "Satyrium w-album", level: "hard" },
  { slug: "duke-of-burgundy", name: "Duke of Burgundy", sci: "Hamearis lucina", level: "hard" },
  { slug: "marsh-fritillary", name: "Marsh Fritillary", sci: "Euphydryas aurinia", level: "hard" },
  { slug: "glanville-fritillary", name: "Glanville Fritillary", sci: "Melitaea cinxia", level: "hard" },
  { slug: "large-blue", name: "Large Blue", sci: "Phengaris arion", level: "hard" },
  { slug: "silver-studded-blue", name: "Silver-studded Blue", sci: "Plebejus argus", level: "hard" },
  { slug: "long-tailed-blue", name: "Long-tailed Blue", sci: "Lampides boeticus", level: "hard" },
  { slug: "wall-brown", name: "Wall Brown", sci: "Lasiommata megera", level: "hard" },
  { slug: "grayling", name: "Grayling", sci: "Hipparchia semele", level: "hard" },
  { slug: "yellow-tail-moth", name: "Yellow-tail Moth", sci: "Euproctis similis", level: "hard" },
  { slug: "oak-eggar-moth", name: "Oak Eggar Moth", sci: "Lasiocampa quercus", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { slug: "queen-alexandras-birdwing", name: "Alexandra's Birdwing", sci: "Ornithoptera alexandrae", level: "impossible" },
  { slug: "homerus-swallowtail", name: "Homerus Swallowtail", sci: "Papilio homerus", level: "impossible" },
  { slug: "luzon-peacock-swallowtail", name: "Luzon Peacock", sci: "Papilio chikae", level: "impossible" },
  { slug: "palawan-birdwing", name: "Palawan Birdwing", sci: "Troides trojana", level: "impossible" },
  { slug: "wallaces-golden-birdwing", name: "Wallace's Birdwing", sci: "Ornithoptera croesus", level: "impossible" },
  { slug: "chimaera-birdwing", name: "Chimaera Birdwing", sci: "Ornithoptera chimaera", level: "impossible" },
  { slug: "african-giant-swallowtail", name: "African Giant Swallowtail", sci: "Papilio antimachus", level: "impossible" },
  { slug: "mocker-swallowtail", name: "Mocker Swallowtail", sci: "Papilio dardanus", level: "impossible" },
  { slug: "emperor-swallowtail", name: "Emperor Swallowtail", sci: "Papilio ophidicephalus", level: "impossible" },
  { slug: "regent-skipper", name: "Regent Skipper", sci: "Euschemon rafflesia", level: "impossible" },
  { slug: "green-banded-urania", name: "Green-banded Urania", sci: "Urania leilus", level: "impossible" },
  { slug: "hercules-moth", name: "Hercules Moth", sci: "Coscinocera hercules", level: "impossible" },
  { slug: "suraka-silk-moth", name: "Suraka Silk Moth", sci: "Antherina suraka", level: "impossible" },
  { slug: "owl-moth", name: "Owl Moth", sci: "Brahmaea wallichii", level: "impossible" },
  { slug: "wallaces-sphinx-moth", name: "Wallace's Sphinx Moth", sci: "Xanthopan morganii", level: "impossible" },
  { slug: "corsican-swallowtail", name: "Corsican Swallowtail", sci: "Papilio hospiton", level: "impossible" },
  { slug: "lesser-purple-emperor", name: "Lesser Purple Emperor", sci: "Apatura metis", level: "impossible" },
  { slug: "cardinal-butterfly", name: "Cardinal Butterfly", sci: "Argynnis pandora", level: "impossible" },
  { slug: "nickerbean-blue", name: "Nickerbean Blue", sci: "Cyclargus ammon", level: "impossible" },
  { slug: "miami-blue", name: "Miami Blue", sci: "Cyclargus thomasi", level: "impossible" },
  { slug: "karner-blue", name: "Karner Blue", sci: "Plebejus samuelis", level: "impossible" },
  { slug: "fenders-blue", name: "Fender's Blue", sci: "Icaricia icarioides fenderi", level: "impossible" },
  { slug: "schaus-swallowtail", name: "Schaus' Swallowtail", sci: "Papilio aristodemus", level: "impossible" },
  { slug: "malabar-banded-peacock", name: "Malabar Banded Peacock", sci: "Papilio buddha", level: "impossible" },
  { slug: "miranda-birdwing", name: "Miranda Birdwing", sci: "Troides miranda", level: "impossible" },
];

export const BUTTERFLIES2_LEVELS = ["easy", "medium", "hard", "impossible"];
