// E105 «Guess the ZOOMED Butterfly» — GuessSync "What the Zoom" hard-mode.
// Reuses the EXACT base butterflies/<slug>.jpg image set + base FACTS + bt-<slug>.wav answer VOs
// (copied to new voPrefix — identical "It's the <name>!" line, zero new audio cost), but
// RE-TIERED by how recognizable each item is from an EXTREME off-center close-up crop (scale 3.0).
// Difficulty tracks close-up pattern/color distinctiveness, NOT general fame.
export const BUTTERFLYZOOM = [
  // ===== EASY (25) =====
  { slug: "blue-morpho", name: "Blue Morpho", sci: "Morpho menelaus", level: "easy" },
  { slug: "monarch", name: "Monarch", sci: "Danaus plexippus", level: "easy" },
  { slug: "ulysses-butterfly", name: "Ulysses Butterfly", sci: "Papilio ulysses", level: "easy" },
  { slug: "madagascan-sunset-moth", name: "Madagascan Sunset Moth", sci: "Chrysiridia rhipheus", level: "easy" },
  { slug: "peacock-butterfly", name: "Peacock Butterfly", sci: "Aglais io", level: "easy" },
  { slug: "owl-butterfly", name: "Owl Butterfly", sci: "Caligo eurilochus", level: "easy" },
  { slug: "common-buckeye", name: "Common Buckeye", sci: "Junonia coenia", level: "easy" },
  { slug: "atlas-moth", name: "Atlas Moth", sci: "Attacus atlas", level: "easy" },
  { slug: "tiger-swallowtail", name: "Eastern Tiger Swallowtail", sci: "Papilio glaucus", level: "easy" },
  { slug: "zebra-longwing", name: "Zebra Longwing", sci: "Heliconius charithonia", level: "easy" },
  { slug: "glasswing", name: "Glasswing", sci: "Greta oto", level: "easy" },
  { slug: "red-admiral", name: "Red Admiral", sci: "Vanessa atalanta", level: "easy" },
  { slug: "giant-swallowtail", name: "Giant Swallowtail", sci: "Papilio cresphontes", level: "easy" },
  { slug: "cairns-birdwing", name: "Cairns Birdwing", sci: "Ornithoptera euphorion", level: "easy" },
  { slug: "rajah-brookes-birdwing", name: "Rajah Brooke's Birdwing", sci: "Trogonoptera brookiana", level: "easy" },
  { slug: "paris-peacock", name: "Paris Peacock", sci: "Papilio paris", level: "easy" },
  { slug: "kaiser-i-hind", name: "Kaiser-i-Hind", sci: "Teinopalpus imperialis", level: "easy" },
  { slug: "postman", name: "Postman", sci: "Heliconius melpomene", level: "easy" },
  { slug: "great-eggfly", name: "Great Eggfly", sci: "Hypolimnas bolina", level: "easy" },
  { slug: "eighty-eight-butterfly", name: "88 Butterfly", sci: "Diaethria clymena", level: "easy" },
  { slug: "comet-moth", name: "Comet Moth", sci: "Argema mittrei", level: "easy" },
  { slug: "gaudy-baron", name: "Gaudy Baron", sci: "Euthalia lubentina", level: "easy" },
  { slug: "rosy-maple-moth", name: "Rosy Maple Moth", sci: "Dryocampa rubicunda", level: "easy" },
  { slug: "leopard-lacewing", name: "Leopard Lacewing", sci: "Cethosia cyane", level: "easy" },
  { slug: "spanish-moon-moth", name: "Spanish Moon Moth", sci: "Graellsia isabellae", level: "easy" },
  // ===== MEDIUM (25) =====
  { slug: "luna-moth", name: "Luna Moth", sci: "Actias luna", level: "medium" },
  { slug: "io-moth", name: "Io Moth", sci: "Automeris io", level: "medium" },
  { slug: "polyphemus-moth", name: "Polyphemus Moth", sci: "Antheraea polyphemus", level: "medium" },
  { slug: "cecropia-moth", name: "Cecropia Moth", sci: "Hyalophora cecropia", level: "medium" },
  { slug: "great-spangled-fritillary", name: "Great Spangled Fritillary", sci: "Speyeria cybele", level: "medium" },
  { slug: "gulf-fritillary", name: "Gulf Fritillary", sci: "Agraulis vanillae", level: "medium" },
  { slug: "small-tortoiseshell", name: "Small Tortoiseshell", sci: "Aglais urticae", level: "medium" },
  { slug: "malachite", name: "Malachite", sci: "Siproeta stelenes", level: "medium" },
  { slug: "tailed-jay", name: "Tailed Jay", sci: "Graphium agamemnon", level: "medium" },
  { slug: "blue-clipper", name: "Blue Clipper", sci: "Parthenos sylvia", level: "medium" },
  { slug: "banded-peacock", name: "Banded Peacock", sci: "Anartia fatima", level: "medium" },
  { slug: "scarlet-tiger-moth", name: "Scarlet Tiger Moth", sci: "Callimorpha dominula", level: "medium" },
  { slug: "garden-tiger-moth", name: "Garden Tiger Moth", sci: "Arctia caja", level: "medium" },
  { slug: "giant-leopard-moth", name: "Giant Leopard Moth", sci: "Hypercompe scribonia", level: "medium" },
  { slug: "common-jezebel", name: "Common Jezebel", sci: "Delias eucharis", level: "medium" },
  { slug: "great-orange-tip", name: "Great Orange Tip", sci: "Hebomoia glaucippe", level: "medium" },
  { slug: "apollo", name: "Apollo", sci: "Parnassius apollo", level: "medium" },
  { slug: "six-spot-burnet", name: "Six-spot Burnet", sci: "Zygaena filipendulae", level: "medium" },
  { slug: "cinnabar-moth", name: "Cinnabar Moth", sci: "Tyria jacobaeae", level: "medium" },
  { slug: "white-lined-sphinx", name: "White-lined Sphinx", sci: "Hyles lineata", level: "medium" },
  { slug: "elephant-hawk-moth", name: "Elephant Hawk-moth", sci: "Deilephila elpenor", level: "medium" },
  { slug: "oleander-hawk-moth", name: "Oleander Hawk-moth", sci: "Daphnis nerii", level: "medium" },
  { slug: "marbled-white", name: "Marbled White", sci: "Melanargia galathea", level: "medium" },
  { slug: "imperial-moth", name: "Imperial Moth", sci: "Eacles imperialis", level: "medium" },
  { slug: "white-witch-moth", name: "White Witch Moth", sci: "Thysania agrippina", level: "medium" },
  // ===== HARD (25) =====
  { slug: "mourning-cloak", name: "Mourning Cloak", sci: "Nymphalis antiopa", level: "hard" },
  { slug: "viceroy", name: "Viceroy", sci: "Limenitis archippus", level: "hard" },
  { slug: "purple-emperor", name: "Purple Emperor", sci: "Apatura iris", level: "hard" },
  { slug: "painted-lady", name: "Painted Lady", sci: "Vanessa cardui", level: "hard" },
  { slug: "old-world-swallowtail", name: "Swallowtail", sci: "Papilio machaon", level: "hard" },
  { slug: "emperor-moth", name: "Emperor Moth", sci: "Saturnia pavonia", level: "hard" },
  { slug: "dead-leaf-butterfly", name: "Dead Leaf Butterfly", sci: "Kallima inachus", level: "hard" },
  { slug: "cracker", name: "Cracker", sci: "Hamadryas februa", level: "hard" },
  { slug: "map-butterfly", name: "Map Butterfly", sci: "Araschnia levana", level: "hard" },
  { slug: "white-admiral", name: "White Admiral", sci: "Limenitis camilla", level: "hard" },
  { slug: "swallowtail-moth", name: "Swallow-tailed Moth", sci: "Ourapteryx sambucaria", level: "hard" },
  { slug: "promethea-moth", name: "Promethea Moth", sci: "Callosamia promethea", level: "hard" },
  { slug: "agrias-butterfly", name: "Agrias Butterfly", sci: "Agrias claudina", level: "hard" },
  { slug: "bhutan-glory", name: "Bhutan Glory", sci: "Bhutanitis lidderdalii", level: "hard" },
  { slug: "blue-tiger", name: "Blue Tiger", sci: "Tirumala limniace", level: "hard" },
  { slug: "forest-queen", name: "Forest Queen", sci: "Euxanthe wakefieldi", level: "hard" },
  { slug: "autumn-leaf", name: "Autumn Leaf", sci: "Doleschallia bisaltide", level: "hard" },
  { slug: "banded-king-shoemaker", name: "Banded King Shoemaker", sci: "Archaeoprepona demophon", level: "hard" },
  { slug: "orchard-swallowtail", name: "Orchard Swallowtail", sci: "Papilio aegeus", level: "hard" },
  { slug: "regal-moth", name: "Regal Moth", sci: "Citheronia regalis", level: "hard" },
  { slug: "green-dragontail", name: "Green Dragontail", sci: "Lamproptera meges", level: "hard" },
  { slug: "sylphina-angel", name: "Sylphina Angel", sci: "Chorinea sylphina", level: "hard" },
  { slug: "marpesia-daggerwing", name: "Waiter Daggerwing", sci: "Marpesia coresia", level: "hard" },
  { slug: "pipevine-swallowtail", name: "Pipevine Swallowtail", sci: "Battus philenor", level: "hard" },
  { slug: "spicebush-swallowtail", name: "Spicebush Swallowtail", sci: "Papilio troilus", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { slug: "cabbage-white", name: "Cabbage White", sci: "Pieris rapae", level: "impossible" },
  { slug: "orange-sulphur", name: "Orange Sulphur", sci: "Colias eurytheme", level: "impossible" },
  { slug: "clouded-yellow", name: "Clouded Yellow", sci: "Colias croceus", level: "impossible" },
  { slug: "brimstone", name: "Brimstone", sci: "Gonepteryx rhamni", level: "impossible" },
  { slug: "holly-blue", name: "Holly Blue", sci: "Celastrina argiolus", level: "impossible" },
  { slug: "julia", name: "Julia", sci: "Dryas iulia", level: "impossible" },
  { slug: "zebra-swallowtail", name: "Zebra Swallowtail", sci: "Protographium marcellus", level: "impossible" },
  { slug: "american-lady", name: "American Lady", sci: "Vanessa virginiensis", level: "impossible" },
  { slug: "common-wood-nymph", name: "Common Wood-Nymph", sci: "Cercyonis pegala", level: "impossible" },
  { slug: "pearl-crescent", name: "Pearl Crescent", sci: "Phyciodes tharos", level: "impossible" },
  { slug: "eastern-tailed-blue", name: "Eastern Tailed-Blue", sci: "Cupido comyntas", level: "impossible" },
  { slug: "silver-spotted-skipper", name: "Silver-spotted Skipper", sci: "Epargyreus clarus", level: "impossible" },
  { slug: "speckled-wood", name: "Speckled Wood", sci: "Pararge aegeria", level: "impossible" },
  { slug: "gatekeeper", name: "Gatekeeper", sci: "Pyronia tithonus", level: "impossible" },
  { slug: "meadow-brown", name: "Meadow Brown", sci: "Maniola jurtina", level: "impossible" },
  { slug: "common-blue", name: "Common Blue", sci: "Polyommatus icarus", level: "impossible" },
  { slug: "adonis-blue", name: "Adonis Blue", sci: "Polyommatus bellargus", level: "impossible" },
  { slug: "red-lacewing", name: "Red Lacewing", sci: "Cethosia biblis", level: "impossible" },
  { slug: "small-copper", name: "Small Copper", sci: "Lycaena phlaeas", level: "impossible" },
  { slug: "chalk-hill-blue", name: "Chalk Hill Blue", sci: "Polyommatus coridon", level: "impossible" },
  { slug: "hummingbird-hawk-moth", name: "Hummingbird Hawk-moth", sci: "Macroglossum stellatarum", level: "impossible" },
  { slug: "deaths-head-hawkmoth", name: "Death's-head Hawkmoth", sci: "Acherontia atropos", level: "impossible" },
  { slug: "comma", name: "Comma", sci: "Polygonia c-album", level: "impossible" },
  { slug: "giant-peacock-moth", name: "Giant Peacock Moth", sci: "Saturnia pyri", level: "impossible" },
  { slug: "question-mark", name: "Question Mark", sci: "Polygonia interrogationis", level: "impossible" },
];
