// «Guess the Cactus or Succulent» — GuessSync · E63 · 100 species (25/tier) · real photos from Wikimedia Commons
// Ranked by global recognizability: easy (Saguaro/Aloe Vera/Jade Plant) → impossible (Lithops/Peyote/Aztekium/Blossfeldia).
// Mix of iconic cacti + popular houseplant succulents + rare collector species. Distinct from E09 Flowers & E46 Trees.
export const CACTI = [
  // EASY (25) — household-name cacti & succulents
  { slug: "saguaro", name: "Saguaro", level: "easy" },
  { slug: "pricklypear", name: "Prickly Pear", level: "easy" },
  { slug: "aloevera", name: "Aloe Vera", level: "easy" },
  { slug: "barrelcactus", name: "Barrel Cactus", level: "easy" },
  { slug: "christmascactus", name: "Christmas Cactus", level: "easy" },
  { slug: "jadeplant", name: "Jade Plant", level: "easy" },
  { slug: "agave", name: "Agave", level: "easy" },
  { slug: "echeveria", name: "Echeveria", level: "easy" },
  { slug: "snakeplant", name: "Snake Plant", level: "easy" },
  { slug: "goldenbarrel", name: "Golden Barrel Cactus", level: "easy" },
  { slug: "bunnyear", name: "Bunny Ear Cactus", level: "easy" },
  { slug: "oldmancactus", name: "Old Man Cactus", level: "easy" },
  { slug: "cholla", name: "Cholla", level: "easy" },
  { slug: "organpipe", name: "Organ Pipe Cactus", level: "easy" },
  { slug: "sanpedro", name: "San Pedro Cactus", level: "easy" },
  { slug: "hensandchicks", name: "Hens and Chicks", level: "easy" },
  { slug: "zebrahaworthia", name: "Zebra Haworthia", level: "easy" },
  { slug: "stringofpearls", name: "String of Pearls", level: "easy" },
  { slug: "aeonium", name: "Aeonium", level: "easy" },
  { slug: "kalanchoe", name: "Kalanchoe", level: "easy" },
  { slug: "pincushioncactus", name: "Pincushion Cactus", level: "easy" },
  { slug: "burrostail", name: "Burro's Tail", level: "easy" },
  { slug: "pandaplant", name: "Panda Plant", level: "easy" },
  { slug: "crownofthorns", name: "Crown of Thorns", level: "easy" },
  { slug: "mooncactus", name: "Moon Cactus", level: "easy" },

  // MEDIUM (25) — common in cultivation, known to plant lovers
  { slug: "gasteria", name: "Gasteria", level: "medium" },
  { slug: "beavertail", name: "Beavertail Cactus", level: "medium" },
  { slug: "pencilcactus", name: "Pencil Cactus", level: "medium" },
  { slug: "desertrose", name: "Desert Rose", level: "medium" },
  { slug: "stringofhearts", name: "String of Hearts", level: "medium" },
  { slug: "stringofbananas", name: "String of Bananas", level: "medium" },
  { slug: "ghostplant", name: "Ghost Plant", level: "medium" },
  { slug: "flapjack", name: "Flapjack Plant", level: "medium" },
  { slug: "mexicanfencepost", name: "Mexican Fence Post Cactus", level: "medium" },
  { slug: "torchcactus", name: "Torch Cactus", level: "medium" },
  { slug: "rattailcactus", name: "Rat Tail Cactus", level: "medium" },
  { slug: "queenofthenight", name: "Queen of the Night", level: "medium" },
  { slug: "eastercactus", name: "Easter Cactus", level: "medium" },
  { slug: "mistletoecactus", name: "Mistletoe Cactus", level: "medium" },
  { slug: "dragonfruit", name: "Dragon Fruit Cactus", level: "medium" },
  { slug: "claretcup", name: "Claret Cup Cactus", level: "medium" },
  { slug: "hedgehogcactus", name: "Hedgehog Cactus", level: "medium" },
  { slug: "totempole", name: "Totem Pole Cactus", level: "medium" },
  { slug: "blueagave", name: "Blue Agave", level: "medium" },
  { slug: "foxtailagave", name: "Foxtail Agave", level: "medium" },
  { slug: "tigerjaws", name: "Tiger Jaws", level: "medium" },
  { slug: "moonstones", name: "Moonstones", level: "medium" },
  { slug: "bearpaw", name: "Bear Paw Succulent", level: "medium" },
  { slug: "elephantbush", name: "Elephant Bush", level: "medium" },
  { slug: "pigsear", name: "Pig's Ear", level: "medium" },

  // HARD (25) — collectors and enthusiasts know these
  { slug: "bishopscap", name: "Bishop's Cap Cactus", level: "hard" },
  { slug: "sanddollar", name: "Sand Dollar Cactus", level: "hard" },
  { slug: "braincactus", name: "Brain Cactus", level: "hard" },
  { slug: "peanutcactus", name: "Peanut Cactus", level: "hard" },
  { slug: "ladyfinger", name: "Lady Finger Cactus", level: "hard" },
  { slug: "powderpuff", name: "Powder Puff Cactus", level: "hard" },
  { slug: "feathercactus", name: "Feather Cactus", level: "hard" },
  { slug: "silvertorch", name: "Silver Torch Cactus", level: "hard" },
  { slug: "monkeytail", name: "Monkey Tail Cactus", level: "hard" },
  { slug: "fairycastle", name: "Fairy Castle Cactus", level: "hard" },
  { slug: "bluetorch", name: "Blue Torch Cactus", level: "hard" },
  { slug: "crestedeuphorbia", name: "Crested Euphorbia", level: "hard" },
  { slug: "africanmilktree", name: "African Milk Tree", level: "hard" },
  { slug: "medusahead", name: "Medusa's Head Euphorbia", level: "hard" },
  { slug: "tigeraloe", name: "Tiger Aloe", level: "hard" },
  { slug: "spiralaloe", name: "Spiral Aloe", level: "hard" },
  { slug: "treealoe", name: "Tree Aloe", level: "hard" },
  { slug: "torchaloe", name: "Torch Aloe", level: "hard" },
  { slug: "propellerplant", name: "Propeller Plant", level: "hard" },
  { slug: "watchchain", name: "Watch Chain Crassula", level: "hard" },
  { slug: "babynecklace", name: "Baby's Necklace", level: "hard" },
  { slug: "calicokitten", name: "Calico Kitten", level: "hard" },
  { slug: "rubynecklace", name: "Ruby Necklace", level: "hard" },
  { slug: "splitrock", name: "Split Rock", level: "hard" },
  { slug: "crinkleleaf", name: "Crinkle Leaf Plant", level: "hard" },

  // IMPOSSIBLE (25) — obscure & rare species
  { slug: "lithops", name: "Lithops", level: "impossible" },
  { slug: "baseballplant", name: "Baseball Plant", level: "impossible" },
  { slug: "peyote", name: "Peyote", level: "impossible" },
  { slug: "livingrock", name: "Living Rock Cactus", level: "impossible" },
  { slug: "stringofdolphins", name: "String of Dolphins", level: "impossible" },
  { slug: "babytoes", name: "Baby Toes", level: "impossible" },
  { slug: "conophytum", name: "Conophytum", level: "impossible" },
  { slug: "titanopsis", name: "Titanopsis", level: "impossible" },
  { slug: "dinteranthus", name: "Dinteranthus", level: "impossible" },
  { slug: "avonia", name: "Avonia", level: "impossible" },
  { slug: "gorgonshead", name: "Gorgon's Head Euphorbia", level: "impossible" },
  { slug: "corncobcactus", name: "Corncob Cactus", level: "impossible" },
  { slug: "blossfeldia", name: "Blossfeldia", level: "impossible" },
  { slug: "discocactus", name: "Discocactus", level: "impossible" },
  { slug: "turbinicarpus", name: "Turbinicarpus", level: "impossible" },
  { slug: "strombocactus", name: "Strombocactus", level: "impossible" },
  { slug: "aztekium", name: "Aztekium", level: "impossible" },
  { slug: "leuchtenbergia", name: "Agave Cactus", level: "impossible" },
  { slug: "copiapoa", name: "Copiapoa", level: "impossible" },
  { slug: "obregonia", name: "Artichoke Cactus", level: "impossible" },
  { slug: "pelecyphora", name: "Hatchet Cactus", level: "impossible" },
  { slug: "frailea", name: "Frailea", level: "impossible" },
  { slug: "euphorbiahorrida", name: "African Milk Barrel", level: "impossible" },
  { slug: "anacampseros", name: "Anacampseros", level: "impossible" },
  { slug: "tylecodon", name: "Butter Tree", level: "impossible" },
];
