// «Guess the Capital» — did-you-know facts, ≤70 chars each, verified. One per capital.
export const CAPITAL_FACTS = {
  // EASY (25)
  "us": "Home to the White House and the U.S. Capitol.",
  "gb": "Big Ben's clock tower stands beside the Thames.",
  "fr": "The Eiffel Tower has stood here since 1889.",
  "de": "The Brandenburg Gate is its famous landmark.",
  "it": "The Colosseum has stood here nearly 2,000 years.",
  "es": "One of Europe's highest capital cities.",
  "ca": "The Rideau Canal freezes into a skating rink.",
  "br": "A planned city shaped like an airplane.",
  "ar": "Known as the Paris of South America.",
  "jp": "The world's most populous metropolitan area.",
  "cn": "The Forbidden City sits at its heart.",
  "in": "India Gate stands in its heart.",
  "ru": "Red Square and the Kremlin sit here.",
  "au": "A planned city chosen as a compromise.",
  "mx": "Built on the ruins of Aztec Tenochtitlan.",
  "nl": "Famous for its canals and narrow houses.",
  "se": "Built across 14 islands linked by bridges.",
  "ch": "Its old town is a UNESCO heritage site.",
  "tr": "It replaced Istanbul as the capital in 1923.",
  "sa": "Its name comes from Arabic for gardens.",
  "eg": "The Great Pyramids of Giza rise nearby.",
  "kr": "The Han River flows through the city.",
  "pt": "One of western Europe's oldest cities.",
  "gr": "The Parthenon crowns its ancient Acropolis.",
  "ie": "The River Liffey splits the city in two.",
  // MEDIUM (25)
  "no": "It sits at the head of a long fjord.",
  "dk": "The Little Mermaid statue sits in its harbor.",
  "fi": "A seaside city facing the Baltic Sea.",
  "pl": "Its old town was rebuilt after World War II.",
  "at": "The waltz and coffee houses were born here.",
  "be": "Home to the tiny Manneken Pis statue.",
  "za": "Its jacaranda trees bloom purple in spring.",
  "ng": "A planned city built from the 1980s.",
  "ma": "It sits on the Atlantic coast of Morocco.",
  "ae": "Home to the grand Sheikh Zayed Mosque.",
  "qa": "A coastal city known for its skyline.",
  "kw": "Its Kuwait Towers rise above the bay.",
  "th": "Its full ceremonial name is the world's longest.",
  "vn": "One of Asia's oldest capital cities.",
  "id": "It sits on the island of Java.",
  "my": "The Petronas Twin Towers rise here.",
  "ph": "It sits on a large natural bay.",
  "nz": "Often called the world's windiest city.",
  "cl": "The snowy Andes rise on its edge.",
  "co": "One of the world's highest capital cities.",
  "pe": "It rarely rains in this coastal desert city.",
  "ua": "It sits on the Dnieper River.",
  "cz": "Its medieval astronomical clock still runs.",
  "hu": "The Danube splits it into Buda and Pest.",
  "ro": "Home to one of the world's largest buildings.",
  // HARD (25)
  "hr": "It has one of the world's shortest funiculars.",
  "rs": "It sits where the Sava meets the Danube.",
  "is": "The world's northernmost capital city.",
  "pk": "A planned city built in the 1960s.",
  "bd": "Known as the rickshaw capital of the world.",
  "ke": "It has a national park right beside it.",
  "gh": "A coastal city on the Gulf of Guinea.",
  "et": "One of the highest capital cities in Africa.",
  "jo": "It was once the Roman city of Philadelphia.",
  "lb": "One of the oldest cities in the world.",
  "iq": "It was once the world's largest city.",
  "ir": "The Alborz Mountains rise to its north.",
  "om": "Rugged mountains ring this coastal city.",
  "bh": "Its name means the place of rest in Arabic.",
  "kz": "One of the coldest capital cities on Earth.",
  "sg": "A city-state made up of one main island.",
  "cu": "Vintage 1950s cars still cruise its streets.",
  "ve": "It lies in a valley near the Caribbean coast.",
  "ec": "It sits almost right on the Equator.",
  "uy": "It sits on the wide Río de la Plata.",
  "sk": "It borders both Austria and Hungary.",
  "si": "A dragon is the symbol of this green city.",
  "bg": "Mount Vitosha rises just beyond the city.",
  "kh": "It sits where four river branches meet.",
  "lk": "Home to Sri Lanka's parliament complex.",
  // IMPOSSIBLE (25)
  "np": "A valley city ringed by Himalayan peaks.",
  "bt": "One of few capitals with no traffic lights.",
  "kg": "The Tian Shan mountains rise to its south.",
  "uz": "One of Central Asia's largest cities.",
  "tm": "Famed for its many white marble buildings.",
  "bn": "Home to a large water village on stilts.",
  "la": "It sits along the Mekong River.",
  "mn": "The world's coldest capital city.",
  "km": "A port city on a volcanic island.",
  "sc": "One of the world's smallest capital cities.",
  "mu": "A harbor city founded by the French in 1735.",
  "fj": "It sits on a peninsula on Viti Levu.",
  "ws": "The only city and main port of Samoa.",
  "to": "The main port on Tonga's largest island.",
  "ki": "An atoll of tiny islets around a lagoon.",
  "nr": "It is the de facto capital of tiny Nauru.",
  "pw": "One of the least populated capitals on Earth.",
  "mt": "The smallest capital city in the EU by area.",
  "cy": "It lies inland at the center of the island.",
  "lu": "Built on cliffs above deep river gorges.",
  "li": "A castle overlooks this small Alpine town.",
  "ad": "The highest capital city in Europe.",
  "me": "Two rivers meet in this small city.",
  "mk": "A 15th-century stone bridge crosses its river.",
  "sz": "It sits in the highland Highveld region.",
};
