// E17 «Guess the Car» — did-you-know facts, ≤70 chars each, verified.
export const CAR_FACTS = {
  // ---------- EASY ----------
  "ford-mustang": "Debuted in 1964 and created the 'pony car' class",
  "vw-beetle": "Designed by Ferdinand Porsche in the 1930s",
  "jeep-wrangler": "Descends from the WWII Willys military Jeep",
  "tesla-model-s": "Tesla's first mass-market sedan, launched in 2012",
  "lamborghini-aventador": "Named after a famous Spanish fighting bull",
  "ferrari-f40": "The last car personally approved by Enzo Ferrari",
  "rolls-royce-phantom": "Its 'Spirit of Ecstasy' mascot dates back to 1911",
  "toyota-corolla": "The best-selling car nameplate in history",
  "mini-cooper": "The sporty Mini tuned by racer John Cooper (1961)",
  "porsche-911": "A rear-engined sports car in production since 1964",
  "bugatti-chiron": "Named after Monaco racing driver Louis Chiron",
  "hummer-h2": "Civilian SUV styled after the military Humvee",
  "range-rover": "Launched in 1970 as a luxury off-roader",
  "ford-f150": "For decades the best-selling vehicle in the USA",
  "dodge-charger": "A muscle car that debuted in 1966",
  "volkswagen-golf": "The car that replaced the Beetle as VW's bestseller",
  "toyota-prius": "The world's first mass-produced hybrid car (1997)",
  "chevrolet-corvette": "America's first mass-produced sports car (1953)",
  "mercedes-g-wagon": "Originally built as a military vehicle in 1979",
  "cybertruck": "Its stainless-steel body needs no paint",
  "lamborghini-huracan": "'Huracan' means hurricane in Spanish",
  "fiat-500": "Tiny Italian city car launched in 1957",
  "vw-camper-van": "The Type 2, an icon of 1960s counterculture",
  "ford-model-t": "First car built on a moving assembly line",
  "bmw-i8": "A plug-in hybrid sports car with scissor doors",

  // ---------- MEDIUM ----------
  "mazda-mx5": "The best-selling two-seat sports car ever made",
  "nissan-gtr": "Nicknamed 'Godzilla' for dominating racing",
  "audi-r8": "Audi's first supercar, launched in 2006",
  "bmw-m3": "The high-performance version of the BMW 3 Series",
  "chevrolet-camaro": "Chevy's answer to the Ford Mustang, from 1966",
  "subaru-wrx": "Rally-bred sedan with symmetrical all-wheel drive",
  "dodge-viper": "Powered by a massive V10 engine",
  "toyota-supra": "Its 2JZ inline-six engine is legendary among tuners",
  "mclaren-p1": "A hybrid hypercar limited to 375 units",
  "aston-martin-db5": "James Bond's iconic car in 'Goldfinger' (1964)",
  "cadillac-eldorado": "A symbol of 1950s American luxury and tailfins",
  "delorean-dmc12": "Known for its stainless-steel body and gullwing doors",
  "pontiac-firebird": "The Trans Am starred in 'Smokey and the Bandit'",
  "chevrolet-bel-air": "A 1950s classic famous for its chrome and tailfins",
  "honda-nsx": "The everyday supercar developed with Ayrton Senna",
  "mazda-rx7": "Powered by a rotary Wankel engine",
  "ferrari-testarossa": "'Testarossa' means 'redhead' in Italian",
  "lamborghini-countach": "Its name comes from an Italian exclamation of awe",
  "jaguar-e-type": "Enzo Ferrari called it the most beautiful car ever",
  "land-rover-defender": "Its boxy shape barely changed for over 60 years",
  "porsche-cayenne": "Porsche's first SUV, which saved the company",
  "dodge-challenger": "A classic muscle car first sold in 1970",
  "vw-golf-gti": "The car that launched the 'hot hatch' craze",
  "mercedes-sls-amg": "A modern homage to the 300SL with gullwing doors",
  "volvo-p1800": "Driven by 'The Saint' TV hero Roger Moore",

  // ---------- HARD ----------
  "lancia-delta-integrale": "A rally legend that won six straight WRC titles",
  "alfa-romeo-giulia": "Alfa Romeo is Italy's sporting marque from Milan",
  "lexus-lfa": "Its V10 engine was tuned by Yamaha",
  "koenigsegg-agera": "Built by a Swedish maker founded in 1994",
  "pagani-zonda": "Founder Horacio Pagani once worked at Lamborghini",
  "datsun-240z": "The affordable sports car that conquered America",
  "alpine-a110": "A lightweight French rally car from the 1960s",
  "lotus-esprit": "Became a submarine car in a James Bond film",
  "nissan-skyline-r34": "A JDM icon made famous by 'Fast and Furious'",
  "bmw-2002-turbo": "Europe's first turbocharged production car",
  "citroen-ds": "Famous for its futuristic hydropneumatic suspension",
  "toyota-2000gt": "Japan's first supercar, featured in a Bond film",
  "mercedes-300sl-gullwing": "The first car with fuel injection, from 1954",
  "shelby-cobra": "A British roadster fitted with a big Ford V8",
  "audi-quattro": "Brought all-wheel drive to rally and won big",
  "de-tomaso-pantera": "An Italian body with an American Ford V8",
  "lotus-elise": "A featherweight sports car weighing under 800 kg",
  "peugeot-205-gti": "One of the greatest hot hatches of the 1980s",
  "ford-sierra-cosworth": "A road car built to win touring-car races",
  "buick-riviera": "A stylish American luxury coupe from 1963",
  "saab-900-turbo": "Built by a Swedish maker rooted in aircraft",
  "amc-gremlin": "A quirky American subcompact launched in 1970",
  "tvr-sagaris": "A raw British sports car with no driver aids",
  "maserati-ghibli": "Maserati's trident logo comes from a Bologna statue",
  "honda-s2000": "Its engine revved to a screaming 9,000 rpm",

  // ---------- IMPOSSIBLE ----------
  "tatra-603": "Czech sedan with a rear air-cooled V8 engine",
  "tucker-48": "Only 51 were built before the company collapsed",
  "bmw-isetta": "A bubble car you enter through a front door",
  "wartburg-353": "East German car with a two-stroke engine",
  "trabant-601": "Its body was made of a cotton-resin plastic",
  "marcos-gt": "Early models had a chassis made of plywood",
  "bizzarrini-5300": "Built by an ex-Ferrari engineer with a Chevy V8",
  "monteverdi-hai": "Swiss supercar with a mid-mounted Chrysler Hemi V8",
  "facel-vega": "A French luxury GT powered by a Chrysler V8",
  "vector-w8": "An American supercar with aerospace-style design",
  "gaz-volga": "A Soviet sedan often used by officials and taxis",
  "hindustan-ambassador": "An Indian icon based on Britain's Morris Oxford",
  "saab-sonett": "A rare Swedish sports car from the 1950s-70s",
  "panhard-24": "Made by Panhard, a pioneer of the car industry",
  "borgward-isabella": "A stylish 1950s sedan from West Germany",
  "nsu-ro80": "Named 1968 Car of the Year for its rotary engine",
  "iso-grifo": "An Italian GT powered by an American V8",
  "gordon-keeble": "This British car wore a tortoise as its badge",
  "jensen-interceptor": "One version had pioneering all-wheel drive",
  "amphicar-770": "An amphibious car that could drive on water",
  "stutz-blackhawk": "Elvis Presley bought the very first one built",
  "bricklin-sv1": "A safety sports car with gullwing doors",
  "matra-rancho": "An early crossover-style car from 1977",
  "zaz-965": "A tiny Soviet car with a rear-mounted engine",
  "auburn-speedster": "A 1930s American car with a boat-tail rear",
};
