// E25 «Guess the Car Logo» — 100 automotive brands · 25/tier · image: carlogos/<slug>.png | VO: sfx/nm-<slug>.wav
// Tiered by how globally recognizable the LOGO/brand is (logo-recognition quiz). Dedicated car episode: iconic global brands included.
export const CARLOGOS = [
  // ===== EASY (25) — logos almost everyone knows =====
  { slug: "toyota", name: "Toyota", level: "easy" },
  { slug: "ford", name: "Ford", level: "easy" },
  { slug: "bmw", name: "BMW", level: "easy" },
  { slug: "mercedes-benz", name: "Mercedes-Benz", level: "easy" },
  { slug: "audi", name: "Audi", level: "easy" },
  { slug: "honda", name: "Honda", level: "easy" },
  { slug: "volkswagen", name: "Volkswagen", level: "easy" },
  { slug: "nissan", name: "Nissan", level: "easy" },
  { slug: "hyundai", name: "Hyundai", level: "easy" },
  { slug: "kia", name: "Kia", level: "easy" },
  { slug: "chevrolet", name: "Chevrolet", level: "easy" },
  { slug: "ferrari", name: "Ferrari", level: "easy" },
  { slug: "lamborghini", name: "Lamborghini", level: "easy" },
  { slug: "porsche", name: "Porsche", level: "easy" },
  { slug: "tesla", name: "Tesla", level: "easy" },
  { slug: "jeep", name: "Jeep", level: "easy" },
  { slug: "mazda", name: "Mazda", level: "easy" },
  { slug: "jaguar", name: "Jaguar", level: "easy" },
  { slug: "land-rover", name: "Land Rover", level: "easy" },
  { slug: "lexus", name: "Lexus", level: "easy" },
  { slug: "mini", name: "Mini", level: "easy" },
  { slug: "volvo", name: "Volvo", level: "easy" },
  { slug: "subaru", name: "Subaru", level: "easy" },
  { slug: "fiat", name: "Fiat", level: "easy" },
  { slug: "dodge", name: "Dodge", level: "easy" },

  // ===== MEDIUM (25) — well-known =====
  { slug: "bentley", name: "Bentley", level: "medium" },
  { slug: "rolls-royce", name: "Rolls-Royce", level: "medium" },
  { slug: "bugatti", name: "Bugatti", level: "medium" },
  { slug: "maserati", name: "Maserati", level: "medium" },
  { slug: "aston-martin", name: "Aston Martin", level: "medium" },
  { slug: "alfa-romeo", name: "Alfa Romeo", level: "medium" },
  { slug: "peugeot", name: "Peugeot", level: "medium" },
  { slug: "renault", name: "Renault", level: "medium" },
  { slug: "citroen", name: "Citroen", level: "medium" },
  { slug: "skoda", name: "Skoda", level: "medium" },
  { slug: "seat", name: "SEAT", level: "medium" },
  { slug: "cadillac", name: "Cadillac", level: "medium" },
  { slug: "chrysler", name: "Chrysler", level: "medium" },
  { slug: "lincoln", name: "Lincoln", level: "medium" },
  { slug: "buick", name: "Buick", level: "medium" },
  { slug: "gmc", name: "GMC", level: "medium" },
  { slug: "acura", name: "Acura", level: "medium" },
  { slug: "infiniti", name: "Infiniti", level: "medium" },
  { slug: "suzuki", name: "Suzuki", level: "medium" },
  { slug: "mitsubishi", name: "Mitsubishi", level: "medium" },
  { slug: "opel", name: "Opel", level: "medium" },
  { slug: "mclaren", name: "McLaren", level: "medium" },
  { slug: "genesis", name: "Genesis", level: "medium" },
  { slug: "hummer", name: "Hummer", level: "medium" },
  { slug: "ram", name: "RAM", level: "medium" },

  // ===== HARD (25) — enthusiast / EV / regional =====
  { slug: "koenigsegg", name: "Koenigsegg", level: "hard" },
  { slug: "pagani", name: "Pagani", level: "hard" },
  { slug: "lotus", name: "Lotus", level: "hard" },
  { slug: "polestar", name: "Polestar", level: "hard" },
  { slug: "rivian", name: "Rivian", level: "hard" },
  { slug: "lucid", name: "Lucid", level: "hard" },
  { slug: "byd", name: "BYD", level: "hard" },
  { slug: "nio", name: "NIO", level: "hard" },
  { slug: "xpeng", name: "XPeng", level: "hard" },
  { slug: "geely", name: "Geely", level: "hard" },
  { slug: "chery", name: "Chery", level: "hard" },
  { slug: "great-wall", name: "Great Wall", level: "hard" },
  { slug: "haval", name: "Haval", level: "hard" },
  { slug: "tata", name: "Tata", level: "hard" },
  { slug: "mahindra", name: "Mahindra", level: "hard" },
  { slug: "vinfast", name: "VinFast", level: "hard" },
  { slug: "isuzu", name: "Isuzu", level: "hard" },
  { slug: "daihatsu", name: "Daihatsu", level: "hard" },
  { slug: "maybach", name: "Maybach", level: "hard" },
  { slug: "datsun", name: "Datsun", level: "hard" },
  { slug: "saab", name: "Saab", level: "hard" },
  { slug: "abarth", name: "Abarth", level: "hard" },
  { slug: "cupra", name: "Cupra", level: "hard" },
  { slug: "ds", name: "DS", level: "hard" },
  { slug: "dacia", name: "Dacia", level: "hard" },

  // ===== IMPOSSIBLE (25) — obscure / defunct / very regional =====
  { slug: "wartburg", name: "Wartburg", level: "impossible" },
  { slug: "horch", name: "Horch", level: "impossible" },
  { slug: "dkw", name: "DKW", level: "impossible" },
  { slug: "borgward", name: "Borgward", level: "impossible" },
  { slug: "tatra", name: "Tatra", level: "impossible" },
  { slug: "zastava", name: "Zastava", level: "impossible" },
  { slug: "bufori", name: "Bufori", level: "impossible" },
  { slug: "mastretta", name: "Mastretta", level: "impossible" },
  { slug: "tramontana", name: "Tramontana", level: "impossible" },
  { slug: "vencer", name: "Vencer", level: "impossible" },
  { slug: "zenvo", name: "Zenvo", level: "impossible" },
  { slug: "gumpert", name: "Gumpert", level: "impossible" },
  { slug: "ascari", name: "Ascari", level: "impossible" },
  { slug: "luxgen", name: "Luxgen", level: "impossible" },
  { slug: "qoros", name: "Qoros", level: "impossible" },
  { slug: "hongqi", name: "Hongqi", level: "impossible" },
  { slug: "wuling", name: "Wuling", level: "impossible" },
  { slug: "roewe", name: "Roewe", level: "impossible" },
  { slug: "jetour", name: "Jetour", level: "impossible" },
  { slug: "leapmotor", name: "Leapmotor", level: "impossible" },
  { slug: "nikola", name: "Nikola", level: "impossible" },
  { slug: "faraday-future", name: "Faraday Future", level: "impossible" },
  { slug: "zeekr", name: "Zeekr", level: "impossible" },
  { slug: "ssangyong", name: "SsangYong", level: "impossible" },
  { slug: "spyker", name: "Spyker", level: "impossible" },
];
