// E25 Car Logo facts — one verified ≤70-char fact per brand.
export const CARLOGO_FACTS = {
  // ===== EASY =====
  "toyota": "World's biggest carmaker; its three-ellipse logo debuted in 1989.",
  "ford": "American giant founded by Henry Ford in 1903; makes the F-150.",
  "bmw": "German marque founded in 1916; its badge nods to aircraft roots.",
  "mercedes-benz": "German luxury marque; its three-pointed star dates to 1909.",
  "audi": "German brand whose four rings mark a 1932 merger of four firms.",
  "honda": "Japanese maker; the world's largest producer of engines.",
  "volkswagen": "German 'people's car' brand founded in 1937.",
  "nissan": "Japanese carmaker founded in 1933; makes the GT-R and Leaf.",
  "hyundai": "South Korea's largest carmaker, founded in 1967.",
  "kia": "South Korea's oldest carmaker, founded in 1944.",
  "chevrolet": "American GM brand founded in 1911; the bowtie logo is iconic.",
  "ferrari": "Italian sports-car maker founded by Enzo Ferrari in 1939.",
  "lamborghini": "Italian supercar maker with a raging-bull badge, from 1963.",
  "porsche": "German sports-car maker founded in 1931; makes the 911.",
  "tesla": "American EV maker founded in 2003; led by Elon Musk.",
  "jeep": "American off-road brand born from a WWII military vehicle.",
  "mazda": "Japanese carmaker founded in 1920; known for rotary engines.",
  "jaguar": "British luxury brand founded in 1922 in Coventry.",
  "land-rover": "British 4x4 marque launched its first model in 1948.",
  "lexus": "Toyota's luxury brand, launched in the US in 1989.",
  "mini": "British small-car icon born in 1959, now owned by BMW.",
  "volvo": "Swedish brand founded in 1927, famed for car safety.",
  "subaru": "Japanese maker; its logo shows the Pleiades star cluster.",
  "fiat": "Italy's largest carmaker, founded in Turin in 1899.",
  "dodge": "American brand founded by the Dodge brothers in 1900.",

  // ===== MEDIUM =====
  "bentley": "British ultra-luxury marque founded in 1919; winged 'B' badge.",
  "rolls-royce": "British ultra-luxury marque founded in 1904.",
  "bugatti": "French hypercar maker founded by Ettore Bugatti in 1909.",
  "maserati": "Italian luxury marque founded in 1914; trident logo.",
  "aston-martin": "British sports-car maker founded in 1913; James Bond's car.",
  "alfa-romeo": "Italian sports brand founded in Milan in 1910.",
  "peugeot": "French carmaker founded in 1810; famous lion emblem.",
  "renault": "French carmaker founded in 1899; diamond-shaped logo.",
  "citroen": "French carmaker founded in 1919; double-chevron badge.",
  "skoda": "Czech carmaker founded in 1895, now part of Volkswagen.",
  "seat": "Spain's largest carmaker, founded in 1950.",
  "cadillac": "American luxury brand founded in 1902, a GM flagship.",
  "chrysler": "American carmaker founded by Walter Chrysler in 1925.",
  "lincoln": "Ford's luxury brand, founded in 1917.",
  "buick": "American brand founded in 1903, a GM cornerstone.",
  "gmc": "General Motors' truck and SUV brand, founded in 1911.",
  "acura": "Honda's luxury brand, launched in the US in 1986.",
  "infiniti": "Nissan's luxury brand, launched in the US in 1989.",
  "suzuki": "Japanese maker of small cars and bikes, founded in 1909.",
  "mitsubishi": "Japanese carmaker; its three-diamond logo dates to 1914.",
  "opel": "German carmaker founded in 1862, now part of Stellantis.",
  "mclaren": "British maker of racing-bred supercars, from Formula 1.",
  "genesis": "Hyundai's luxury brand, launched in 2015.",
  "hummer": "American off-road brand based on the military Humvee.",
  "ram": "American truck brand spun off from Dodge in 2010.",

  // ===== HARD =====
  "koenigsegg": "Swedish hypercar maker founded in 1994.",
  "pagani": "Italian hypercar maker founded by Horacio Pagani in 1992.",
  "lotus": "British sports-car maker founded by Colin Chapman in 1948.",
  "polestar": "Swedish electric brand under Volvo and Geely.",
  "rivian": "American electric truck maker founded in 2009.",
  "lucid": "American luxury EV maker known for the Air sedan.",
  "byd": "Chinese EV giant founded in 1995; a top global seller.",
  "nio": "Chinese premium EV maker founded in 2014.",
  "xpeng": "Chinese electric-car maker founded in 2014.",
  "geely": "Chinese carmaker that owns Volvo, founded in 1986.",
  "chery": "Chinese carmaker founded in 1997, a big exporter.",
  "great-wall": "Chinese SUV and pickup maker founded in 1984.",
  "haval": "Chinese SUV brand owned by Great Wall Motors.",
  "tata": "India's largest carmaker; owns Jaguar Land Rover.",
  "mahindra": "Indian maker famous for rugged SUVs, founded in 1945.",
  "vinfast": "Vietnam's first carmaker, founded in 2017.",
  "isuzu": "Japanese maker of trucks and diesel engines, from 1916.",
  "daihatsu": "Japan's oldest carmaker, founded in 1907; makes kei cars.",
  "maybach": "German ultra-luxury marque revived by Mercedes-Benz.",
  "datsun": "Japanese brand; a Nissan name revived and retired again.",
  "saab": "Swedish carmaker born from an aircraft firm in 1945.",
  "abarth": "Italian performance brand founded by Carlo Abarth in 1949.",
  "cupra": "Spanish performance brand spun off from SEAT in 2018.",
  "ds": "French luxury brand spun off from Citroen in 2014.",
  "dacia": "Romanian carmaker founded in 1966, owned by Renault.",

  // ===== IMPOSSIBLE =====
  "wartburg": "East German car brand made from 1956 to 1991.",
  "horch": "German luxury marque, a founder of Auto Union.",
  "dkw": "German marque, one of the four rings of Audi's logo.",
  "borgward": "German carmaker founded in 1929 in Bremen.",
  "tatra": "Czech maker of cars and trucks, founded in 1850.",
  "zastava": "Serbian carmaker founded in 1953.",
  "bufori": "Malaysian maker of hand-built retro-style cars.",
  "mastretta": "Mexican sports-car maker of the MXT.",
  "tramontana": "Spanish maker of open-top track hypercars.",
  "vencer": "Dutch sports-car maker of the Sarthe.",
  "zenvo": "Danish hypercar maker founded in 2007.",
  "gumpert": "German maker of the Apollo supercar.",
  "ascari": "British maker of racing-inspired supercars.",
  "luxgen": "Taiwanese carmaker founded in 2009.",
  "qoros": "Chinese carmaker founded in 2007.",
  "hongqi": "China's oldest luxury marque, founded in 1958.",
  "wuling": "Chinese maker of vans and cheap EVs, a GM partner.",
  "roewe": "Chinese brand launched by SAIC in 2006.",
  "jetour": "Chinese SUV brand under Chery, launched in 2018.",
  "leapmotor": "Chinese electric-car maker founded in 2015.",
  "nikola": "American electric and hydrogen truck maker.",
  "faraday-future": "American electric-car startup founded in 2014.",
  "zeekr": "Chinese premium EV brand launched by Geely in 2021.",
  "ssangyong": "South Korean SUV maker, now renamed KG Mobility.",
  "spyker": "Dutch luxury sports-car maker with an aviation heritage.",
};
