// CARS v2 — one true "did-you-know" per car, ≤70 chars each. Verified facts.
export const CARS2_FACTS = {
  "bugatti-veyron": "Its W16 engine made it the first road car past 400 km/h.",
  "lamborghini-urus": "Lamborghini's super-SUV became its best-selling model ever.",
  "ferrari-488": "The 488 marked Ferrari's return to turbocharged V8 power.",
  "ford-gt": "Built to honor the GT40 that beat Ferrari at Le Mans.",
  "mclaren-720s": "Its twin-turbo V8 makes 720 metric horsepower, hence the name.",
  "aston-martin-vantage": "The Vantage is Aston's smallest, sportiest two-seater.",
  "porsche-panamera": "Porsche's first four-door sports sedan, launched in 2009.",
  "tesla-model-3": "The best-selling electric car of all time worldwide.",
  "toyota-land-cruiser": "In production since 1951, Toyota's longest-running model.",
  "cadillac-escalade": "Cadillac's full-size SUV became a hip-hop culture icon.",
  "jeep-grand-cherokee": "One of the best-selling SUVs in American history.",
  "mercedes-s-class": "The S-Class debuts most of Mercedes' new technology first.",
  "bmw-x5": "BMW's first SUV, which it calls a Sports Activity Vehicle.",
  "toyota-hilux": "Famed for toughness, it survived extreme Top Gear abuse.",
  "chevrolet-silverado": "One of the best-selling vehicles in the United States.",
  "ram-1500": "It split from Dodge to become its own truck brand in 2010.",
  "mini-countryman": "The largest Mini ever, and the brand's first four-door.",
  "smart-fortwo": "At under 2.7 m long, it parks nose-in to the curb.",
  "citroen-2cv": "Designed to carry farmers and eggs across a plowed field.",
  "honda-civic": "In production since 1972, one of Honda's core models.",
  "toyota-camry": "For decades the best-selling car in the United States.",
  "toyota-rav4": "A pioneer of the compact crossover SUV segment.",
  "ford-focus": "One of the best-selling cars in the world in the 2000s.",
  "honda-accord": "First Japanese car built in the U.S., in Ohio from 1982.",
  "nissan-altima": "Nissan's best-selling model in the United States.",

  "ferrari-458": "Its naturally aspirated V8 revs to a screaming 9,000 rpm.",
  "lamborghini-gallardo": "Lamborghini's best-selling car until the Huracan arrived.",
  "porsche-boxster": "Its mid-engine layout helped save Porsche in the 1990s.",
  "audi-tt": "Its Bauhaus-inspired shape became a design icon.",
  "bmw-z4": "A two-seat roadster built to rival the Porsche Boxster.",
  "mercedes-sl": "SL stands for 'Sport Leicht' — sport lightweight.",
  "nissan-370z": "The Z badge traces back to the 1969 Datsun 240Z.",
  "chevrolet-impala": "One of the best-selling cars in America in the 1960s.",
  "ford-thunderbird": "Ford's stylish answer to the Corvette, launched in 1955.",
  "pontiac-gto": "Widely credited as the first true American muscle car.",
  "plymouth-barracuda": "It beat the Ford Mustang to market by two weeks in 1964.",
  "plymouth-road-runner": "It licensed the Looney Tunes bird and its 'beep beep' horn.",
  "toyota-celica": "A sporty coupe built by Toyota for over 35 years.",
  "mitsubishi-lancer-evo": "A rally-bred sedan legend, retired in 2016.",
  "mazda-rx8": "Powered by Mazda's unusual rotary Wankel engine.",
  "honda-prelude": "The first Honda offered with four-wheel steering.",
  "vw-scirocco": "A sporty coupe based on the Volkswagen Golf platform.",
  "bmw-m5": "The M5 helped invent the super-sedan segment in 1984.",
  "mercedes-amg-gt": "AMG's front-mid-engine sports car with a long hood.",
  "jaguar-f-type": "A spiritual successor to the legendary Jaguar E-Type.",
  "maserati-granturismo": "Its Ferrari-built V8 gave it a celebrated exhaust note.",
  "alfa-romeo-4c": "A lightweight sports car with a carbon-fiber tub.",
  "lexus-rc-f": "Lexus's V8 coupe rival to the BMW M4.",
  "subaru-brz": "Co-developed with Toyota as the twin of the GT86.",
  "audi-rs6": "A 600-hp super-wagon that hides supercar pace.",

  "ferrari-250-gto": "One of the most valuable cars ever, worth over $50 million.",
  "ferrari-dino-246": "Named after Enzo Ferrari's late son, Alfredino 'Dino'.",
  "lamborghini-miura": "Its mid-engine V12 layout stunned the 1966 car world.",
  "lamborghini-diablo": "Lamborghini's flagship supercar throughout the 1990s.",
  "maserati-bora": "Maserati's first mid-engine production car, from 1971.",
  "alfa-romeo-montreal": "Debuted at the 1967 Montreal Expo, giving it its name.",
  "lancia-stratos": "Built purely to win rallies, it took three world titles.",
  "lancia-037": "The last rear-wheel-drive car to win the rally championship.",
  "bmw-m1": "BMW's only mid-engine supercar, designed by Giugiaro.",
  "mercedes-190e": "Its Cosworth-tuned 16-valve version was a touring-car star.",
  "ford-escort-rs": "The Escort won countless rallies across the 1970s.",
  "renault-5-turbo": "A mid-engine hot hatch built for rally homologation.",
  "opel-manta": "A budget sporty coupe that became a German cult car.",
  "porsche-959": "One of the fastest and most advanced cars of the 1980s.",
  "porsche-550-spyder": "The lightweight racer James Dean died driving in 1955.",
  "nissan-silvia": "A rear-drive coupe beloved by the drifting scene.",
  "mazda-cosmo": "One of the first cars to use a rotary engine, from 1967.",
  "toyota-ae86": "The rear-drive 'Hachi-Roku' idolized in drift culture.",
  "honda-integra-type-r": "Praised as one of the best front-drive cars ever made.",
  "mitsubishi-3000gt": "A tech-packed grand tourer with all-wheel drive.",
  "datsun-510": "The affordable sedan that launched Datsun in America.",
  "aston-martin-db4": "The elegant grand tourer that inspired the DB5.",
  "jaguar-xj220": "Briefly the world's fastest car at 217 mph in 1992.",
  "ford-rs200": "A mid-engine monster built for Group B rallying.",
  "chevrolet-chevelle": "The SS 454 is one of the most prized muscle cars.",

  "cizeta-v16t": "It packed a unique transverse 16-cylinder engine.",
  "isdera-imperator": "A German supercar with roof-mounted 'periscope' mirror.",
  "autozam-az1": "A tiny kei sports car with gullwing doors.",
  "suzuki-cappuccino": "A featherweight kei roadster weighing under 700 kg.",
  "honda-beat": "The last car approved by Honda founder Soichiro Honda.",
  "jensen-ff": "The first non-4x4 production car with all-wheel drive.",
  "panther-deville": "A retro luxury car featured as Cruella de Vil's ride.",
  "reliant-robin": "A three-wheeler famous for tipping in Top Gear gags.",
  "bond-bug": "A wedge-shaped three-wheeler sold only in bright orange.",
  "marcos-mantis": "A rare British sports car with striking angular styling.",
  "bitter-sc": "A German luxury coupe built on Opel underpinnings.",
  "melkus-rs1000": "An East German sports car with gullwing doors.",
  "alpine-a310": "A rear-engine French coupe, successor to the A110.",
  "simca-1000": "A rear-engine French economy car of the 1960s.",
  "tatra-700": "The last of Tatra's rear-engine V8 luxury sedans.",
  "moskvitch-412": "A Soviet sedan exported across the Eastern Bloc.",
  "syrena-105": "A Polish economy car built from the 1950s onward.",
  "zil-114": "A Soviet state limousine used by Kremlin leaders.",
  "lada-niva": "A rugged 4x4 in production largely unchanged since 1977.",
  "ac-428": "A British grand tourer bodied by Italy's Frua.",
  "tatra-87": "A streamlined 1930s sedan with a rear V8 and dorsal fin.",
  "skoda-110r": "A rear-engine Czech sports coupe of the 1970s.",
  "autobianchi-a112": "A small Italian hatchback, cousin to the Fiat 127.",
  "daf-44": "A Dutch small car using the Variomatic belt gearbox.",
  "puma-gte": "A Brazilian sports coupe built on Volkswagen mechanicals.",
};
