// E179 cartoon-emoji facts — one true <=70-char fact per character, shown on reveal.
export const CARTOON_EMOJI_2_FACTS = {
  // EASY
  "daffy-duck": "Zany black duck and Bugs Bunny's Looney Tunes rival.",
  "porky-pig": "Stuttering Looney Tunes pig who says 'That's all folks!'",
  "brian-griffin": "The martini-loving talking dog of Family Guy.",
  "mr-krabs": "Money-obsessed crab who owns the Krusty Krab on SpongeBob.",
  "sandy-cheeks": "Karate squirrel in a diving suit on SpongeBob.",
  "plankton": "Tiny villain after the Krabby Patty formula on SpongeBob.",
  "bumblebee": "Yellow Autobot who transforms into a car in Transformers.",
  "pinkie-pie": "Party-loving pink pony from My Little Pony.",
  "leonardo": "Katana-wielding blue-masked Teenage Mutant Ninja Turtle.",
  "michelangelo": "Pizza-loving orange-masked Teenage Mutant Ninja Turtle.",
  "alvin": "Mischievous lead singer of Alvin and the Chipmunks.",
  "fry": "Pizza boy frozen 1000 years, the hero of Futurama.",
  "kenny-mccormick": "Orange-hooded South Park kid who always dies.",
  "bob-belcher": "Burger-flipping dad who runs Bob's Burgers.",
  "hank-hill": "Propane-selling Texan dad from King of the Hill.",
  "maggie-simpson": "Pacifier-sucking baby of The Simpsons.",
  "krusty-the-clown": "Cynical TV clown from The Simpsons.",
  "mr-burns": "Greedy old owner of Springfield's power plant on The Simpsons.",
  "ned-flanders": "The Simpsons' cheerful, pious next-door neighbor.",
  "milhouse": "Bart's nerdy, blue-haired best friend on The Simpsons.",
  "foghorn-leghorn": "Loud, blustering Looney Tunes rooster.",
  "yosemite-sam": "Short-tempered gunslinger who hates Bugs Bunny.",
  "casper": "The Friendly Ghost of classic cartoons.",
  "speedy-gonzales": "The fastest mouse in all Mexico from Looney Tunes.",
  "tasmanian-devil": "Ravenous, spinning Tasmanian Devil of Looney Tunes.",

  // MEDIUM
  "pepe-le-pew": "Romantic Looney Tunes skunk always chasing love.",
  "marvin-the-martian": "Looney Tunes alien plotting to destroy Earth.",
  "roger-american-dad": "Wisecracking alien in disguise on American Dad.",
  "stan-smith": "Gun-toting CIA dad from American Dad.",
  "glenn-quagmire": "Womanizing pilot neighbor on Family Guy. Giggity!",
  "ralph-wiggum": "Simple-minded, crayon-eating boy on The Simpsons.",
  "huckleberry-hound": "Blue Hanna-Barbera dog who sings off-key.",
  "snagglepuss": "Pink Hanna-Barbera lion who says 'Exit, stage left!'",
  "top-cat": "Scheming leader of a Hanna-Barbera alley-cat gang.",
  "magilla-gorilla": "Hanna-Barbera gorilla stuck in a pet-shop window.",
  "hong-kong-phooey": "Bumbling kung-fu crime-fighting dog of Hanna-Barbera.",
  "george-jetson": "Space-age dad from The Jetsons.",
  "rosie-the-robot": "The Jetsons' robot maid.",
  "wilma-flintstone": "Fred's level-headed Stone Age wife on The Flintstones.",
  "scrappy-doo": "Scooby-Doo's brave, pint-sized nephew.",
  "dick-dastardly": "Mustachioed cheating villain of Wacky Races.",
  "mordecai": "Blue jay slacker from Regular Show.",
  "rigby": "Raccoon slacker and Mordecai's pal on Regular Show.",
  "princess-bubblegum": "Candy Kingdom ruler on Adventure Time.",
  "marceline": "Bass-playing vampire queen of Adventure Time.",
  "bmo": "Living game console from Adventure Time.",
  "ice-king": "Crown-wearing ice wizard of Adventure Time.",
  "arnold": "Football-headed kid from Hey Arnold!",
  "helga-pataki": "Bow-wearing girl secretly in love with Arnold.",
  "reptar": "Godzilla-like dinosaur toy the Rugrats adore.",

  // HARD
  "zuko": "Scarred firebending prince from Avatar: The Last Airbender.",
  "katara": "Waterbending heroine of Avatar: The Last Airbender.",
  "sokka": "Boomerang-throwing warrior in Avatar: The Last Airbender.",
  "toph": "Blind earthbending prodigy in Avatar: The Last Airbender.",
  "appa": "Aang's flying sky bison in Avatar: The Last Airbender.",
  "steven-universe": "Half-gem boy hero of the show Steven Universe.",
  "garnet": "Stoic fusion-gem leader of the Crystal Gems.",
  "grim-billy-mandy": "The Reaper forced to befriend Billy and Mandy.",
  "mandy": "Cold, scheming girl from Billy & Mandy.",
  "ben-ten": "Boy whose Omnitrix watch turns him into aliens.",
  "danny-phantom": "Teen who is a half-ghost superhero in Danny Phantom.",
  "beast-boy": "Green shapeshifting Teen Titan who becomes animals.",
  "splinter": "Rat sensei who trains the Ninja Turtles.",
  "cosmo": "Dim-witted, green-haired fairy on The Fairly OddParents.",
  "wanda": "Pink-haired fairy godparent on The Fairly OddParents.",
  "professor-farnsworth": "Ancient mad scientist of Futurama.",
  "gary-the-snail": "SpongeBob's pet snail who meows like a cat.",
  "betty-boop": "Flapper cartoon star of the 1930s.",
  "underdog": "Superhero dog of the 1960s cartoon Underdog.",
  "mr-magoo": "Nearsighted old man of classic UPA cartoons.",
  "quick-draw-mcgraw": "Hanna-Barbera horse sheriff of the Old West.",
  "bullwinkle": "Dim but lovable moose from Rocky and Bullwinkle.",
  "droopy": "Deadpan basset hound from Tex Avery cartoons.",
  "astro-jetson": "The Jetsons' talking pet dog.",
  "mighty-mouse": "Superhero mouse of classic Terrytoons cartoons.",

  // IMPOSSIBLE
  "rocky-squirrel": "Flying squirrel from Rocky and Bullwinkle.",
  "slappy-squirrel": "Grumpy old cartoon squirrel from Animaniacs.",
  "buster-bunny": "Blue rabbit star of Tiny Toon Adventures.",
  "earthworm-jim": "Blaster-toting worm in a robotic super-suit.",
  "inspector-gadget": "Bumbling cyborg detective full of gadgets.",
  "dr-claw": "Unseen cat-stroking villain in Inspector Gadget.",
  "lion-o": "Sword-wielding leader of the ThunderCats.",
  "cheetara": "Super-fast cheetah warrior of the ThunderCats.",
  "she-ra": "Princess of Power and He-Man's twin sister.",
  "starscream": "Treacherous jet Decepticon from Transformers.",
  "megatron": "Leader of the evil Decepticons in Transformers.",
  "fluttershy": "Shy, animal-loving pony from My Little Pony.",
  "applejack": "Hardworking cowgirl pony from My Little Pony.",
  "gargamel": "Evil wizard who forever hunts the Smurfs.",
  "papa-smurf": "Red-hatted elder leader of the Smurfs.",
  "pinky-mouse": "Dim-witted lab mouse from Pinky and the Brain.",
  "the-brain": "Genius lab mouse plotting to rule the world.",
  "felix-the-cat": "Black cat with a magic bag from silent-era cartoons.",
  "penelope-pitstop": "Pink-clad racer heroine of Wacky Races.",
  "muttley": "Dick Dastardly's snickering cartoon dog.",
  "captain-caveman": "Prehistoric superhero from Hanna-Barbera.",
  "jenny-xj9": "Teenage robot girl of My Life as a Teenage Robot.",
  "static-shock": "Electricity-powered teen superhero.",
  "gumby": "Green clay figure of classic stop-motion cartoons.",
  "brainy-smurf": "Know-it-all, bespectacled Smurf.",
};
