// E137 «Guess the Cartoon Character by Emoji» — 100 characters · 25/tier · clue = plain Unicode emoji
// Non-Disney cartoon/TV/game characters (SpongeBob, Pikachu, Mario, Sonic, etc.).
// `title` = character name only (no art/logos — emoji-only clues keep this copyright-safe).
// Single-codepoint emojis only, no ZWJ/FE0F/skin-tone/flags. VO: sfx/e137-<id>.wav
export const CARTOON_EMOJI = [
  // ===== EASY (25) =====
  { id: "spongebob-squarepants", title: "SpongeBob SquarePants", emojis: "🧽🍍", level: "easy" },
  { id: "pikachu", title: "Pikachu", emojis: "⚡🐭", level: "easy" },
  { id: "bart-simpson", title: "Bart Simpson", emojis: "🛹🟡", level: "easy" },
  { id: "homer-simpson", title: "Homer Simpson", emojis: "🍩🟡", level: "easy" },
  { id: "scooby-doo", title: "Scooby-Doo", emojis: "🐕👻", level: "easy" },
  { id: "mario", title: "Mario", emojis: "🍄🔧", level: "easy" },
  { id: "sonic-the-hedgehog", title: "Sonic the Hedgehog", emojis: "⚡🦔", level: "easy" },
  { id: "tom", title: "Tom", emojis: "🐱🔨", level: "easy" },
  { id: "jerry", title: "Jerry", emojis: "🐭🧀", level: "easy" },
  { id: "bugs-bunny", title: "Bugs Bunny", emojis: "🐰🥕", level: "easy" },
  { id: "popeye", title: "Popeye", emojis: "⚓🥫", level: "easy" },
  { id: "garfield", title: "Garfield", emojis: "🐱🍝", level: "easy" },
  { id: "pac-man", title: "Pac-Man", emojis: "🟡👻", level: "easy" },
  { id: "shrek", title: "Shrek", emojis: "🟢🧅", level: "easy" },
  { id: "po", title: "Po", emojis: "🐼🥋", level: "easy" },
  { id: "goku", title: "Goku", emojis: "🐉👊", level: "easy" },
  { id: "naruto", title: "Naruto", emojis: "🍥🦊", level: "easy" },
  { id: "pink-panther", title: "Pink Panther", emojis: "🐆💗", level: "easy" },
  { id: "woody-woodpecker", title: "Woody Woodpecker", emojis: "🪵🐦", level: "easy" },
  { id: "donkey-kong", title: "Donkey Kong", emojis: "🦍🍌", level: "easy" },
  { id: "luigi", title: "Luigi", emojis: "🟢🍄", level: "easy" },
  { id: "peppa-pig", title: "Peppa Pig", emojis: "🐷💗", level: "easy" },
  { id: "hello-kitty", title: "Hello Kitty", emojis: "🐱🤍", level: "easy" },
  { id: "minion", title: "Minion", emojis: "🍌🟡", level: "easy" },
  { id: "charlie-brown", title: "Charlie Brown", emojis: "⚾😞", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "squidward-tentacles", title: "Squidward Tentacles", emojis: "🦑🎨", level: "medium" },
  { id: "patrick-star", title: "Patrick Star", emojis: "⭐🪨", level: "medium" },
  { id: "lisa-simpson", title: "Lisa Simpson", emojis: "📚🟡", level: "medium" },
  { id: "peter-griffin", title: "Peter Griffin", emojis: "🍺🐔", level: "medium" },
  { id: "stewie-griffin", title: "Stewie Griffin", emojis: "👶🔫", level: "medium" },
  { id: "tweety-bird", title: "Tweety Bird", emojis: "🐦🟡", level: "medium" },
  { id: "sylvester-the-cat", title: "Sylvester the Cat", emojis: "🐱⚫", level: "medium" },
  { id: "yogi-bear", title: "Yogi Bear", emojis: "🐻🎩", level: "medium" },
  { id: "fred-flintstone", title: "Fred Flintstone", emojis: "🦕🪨", level: "medium" },
  { id: "barney-rubble", title: "Barney Rubble", emojis: "🦣🪨", level: "medium" },
  { id: "wile-e-coyote", title: "Wile E. Coyote", emojis: "🐺💣", level: "medium" },
  { id: "road-runner", title: "Road Runner", emojis: "🐦💨", level: "medium" },
  { id: "elmer-fudd", title: "Elmer Fudd", emojis: "🔫🐇", level: "medium" },
  { id: "marge-simpson", title: "Marge Simpson", emojis: "🔵🟡", level: "medium" },
  { id: "velma-dinkley", title: "Velma Dinkley", emojis: "🔍🟠", level: "medium" },
  { id: "shaggy-rogers", title: "Shaggy Rogers", emojis: "🥪🐕", level: "medium" },
  { id: "kirby", title: "Kirby", emojis: "🍥⭐", level: "medium" },
  { id: "link", title: "Link", emojis: "⚔🍀", level: "medium" },
  { id: "master-chief", title: "Master Chief", emojis: "🪖🔫", level: "medium" },
  { id: "crash-bandicoot", title: "Crash Bandicoot", emojis: "🍎📦", level: "medium" },
  { id: "spyro-the-dragon", title: "Spyro the Dragon", emojis: "🐉🟣", level: "medium" },
  { id: "yoshi", title: "Yoshi", emojis: "🥚🟢", level: "medium" },
  { id: "toad", title: "Toad", emojis: "🍄🤍", level: "medium" },
  { id: "bowser", title: "Bowser", emojis: "🐢🔥", level: "medium" },
  { id: "snoopy", title: "Snoopy", emojis: "🐕📝", level: "medium" },

  // ===== HARD (25) =====
  { id: "zoidberg", title: "Zoidberg", emojis: "🦞🩸", level: "hard" },
  { id: "bender", title: "Bender", emojis: "🤖🍺", level: "hard" },
  { id: "rick-sanchez", title: "Rick Sanchez", emojis: "🧪🥃", level: "hard" },
  { id: "morty-smith", title: "Morty Smith", emojis: "🌀👦", level: "hard" },
  { id: "finn-the-human", title: "Finn the Human", emojis: "⚔🎒", level: "hard" },
  { id: "jake-the-dog", title: "Jake the Dog", emojis: "🐕🟡", level: "hard" },
  { id: "gumball-watterson", title: "Gumball Watterson", emojis: "🐱🔵", level: "hard" },
  { id: "ren-hoek", title: "Ren Höek", emojis: "🐕😡", level: "hard" },
  { id: "stimpy", title: "Stimpy", emojis: "🐱😊", level: "hard" },
  { id: "courage-the-cowardly-dog", title: "Courage the Cowardly Dog", emojis: "🐕🏚", level: "hard" },
  { id: "dexter", title: "Dexter", emojis: "🧪👦", level: "hard" },
  { id: "johnny-bravo", title: "Johnny Bravo", emojis: "🕶⚫", level: "hard" },
  { id: "eric-cartman", title: "Eric Cartman", emojis: "🔴🍔", level: "hard" },
  { id: "stan-marsh", title: "Stan Marsh", emojis: "🤢🔵", level: "hard" },
  { id: "beavis", title: "Beavis", emojis: "🔥😈", level: "hard" },
  { id: "butt-head", title: "Butt-Head", emojis: "😈🎸", level: "hard" },
  { id: "timmy-turner", title: "Timmy Turner", emojis: "🎩✨", level: "hard" },
  { id: "jimmy-neutron", title: "Jimmy Neutron", emojis: "🧠🚀", level: "hard" },
  { id: "aang", title: "Aang", emojis: "💨🔵", level: "hard" },
  { id: "vegeta", title: "Vegeta", emojis: "👑🟣", level: "hard" },
  { id: "luffy", title: "Luffy", emojis: "🎩👊", level: "hard" },
  { id: "kratos", title: "Kratos", emojis: "⚔🩸", level: "hard" },
  { id: "sub-zero", title: "Sub-Zero", emojis: "❄🔵", level: "hard" },
  { id: "lara-croft", title: "Lara Croft", emojis: "🏺🔫", level: "hard" },
  { id: "solid-snake", title: "Solid Snake", emojis: "🐍📦", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "space-ghost", title: "Space Ghost", emojis: "👻🚀", level: "impossible" },
  { id: "blossom", title: "Blossom", emojis: "🔴👧", level: "impossible" },
  { id: "bubbles", title: "Bubbles", emojis: "🔵👧", level: "impossible" },
  { id: "buttercup", title: "Buttercup", emojis: "🟢👧", level: "impossible" },
  { id: "mojo-jojo", title: "Mojo Jojo", emojis: "🐒🧠", level: "impossible" },
  { id: "samurai-jack", title: "Samurai Jack", emojis: "⚔🥋", level: "impossible" },
  { id: "invader-zim", title: "Invader Zim", emojis: "👽🟢", level: "impossible" },
  { id: "gir", title: "GIR", emojis: "🤖🐕", level: "impossible" },
  { id: "rocko", title: "Rocko", emojis: "🦘🏠", level: "impossible" },
  { id: "angelica-pickles", title: "Angelica Pickles", emojis: "👧😈", level: "impossible" },
  { id: "tommy-pickles", title: "Tommy Pickles", emojis: "👶🪖", level: "impossible" },
  { id: "chuckie-finster", title: "Chuckie Finster", emojis: "🟠👦", level: "impossible" },
  { id: "doug-funnie", title: "Doug Funnie", emojis: "🟢📓", level: "impossible" },
  { id: "arthur", title: "Arthur", emojis: "📚🟤", level: "impossible" },
  { id: "rainbow-dash", title: "Rainbow Dash", emojis: "🌈🐴", level: "impossible" },
  { id: "twilight-sparkle", title: "Twilight Sparkle", emojis: "🟣📚", level: "impossible" },
  { id: "he-man", title: "He-Man", emojis: "⚔🦁", level: "impossible" },
  { id: "skeletor", title: "Skeletor", emojis: "💀🟣", level: "impossible" },
  { id: "voltron", title: "Voltron", emojis: "🦁🤖", level: "impossible" },
  { id: "optimus-prime", title: "Optimus Prime", emojis: "🤖🔵", level: "impossible" },
  { id: "bulma", title: "Bulma", emojis: "🔵🧪", level: "impossible" },
  { id: "piccolo", title: "Piccolo", emojis: "🟢🥋", level: "impossible" },
  { id: "cloud-strife", title: "Cloud Strife", emojis: "⚔🔵", level: "impossible" },
  { id: "scorpion", title: "Scorpion", emojis: "🦂🔥", level: "impossible" },
  { id: "chun-li", title: "Chun-Li", emojis: "👊🥟", level: "impossible" },
];
