// E199 «Guess the Cartoon Character by Emoji 3» — 100 characters · 25/tier
// VO: sfx/e199-<id>.wav
export const CARTOON_EMOJI_3 = [
  // ===== EASY (25) =====
  { id: "chef-south-park", title: "Chef", emojis: "🎤🍳", level: "easy" },
  { id: "kyle-broflovski", title: "Kyle Broflovski", emojis: "💚🧢", level: "easy" },
  { id: "butters-stotch", title: "Butters Stotch", emojis: "😇🧈", level: "easy" },
  { id: "meg-griffin", title: "Meg Griffin", emojis: "😩🎀", level: "easy" },
  { id: "chris-griffin", title: "Chris Griffin", emojis: "🎮😶", level: "easy" },
  { id: "linda-belcher", title: "Linda Belcher", emojis: "🎤🍔", level: "easy" },
  { id: "tina-belcher", title: "Tina Belcher", emojis: "🦄📓", level: "easy" },
  { id: "gene-belcher", title: "Gene Belcher", emojis: "🎹🌭", level: "easy" },
  { id: "louise-belcher", title: "Louise Belcher", emojis: "🐰👑", level: "easy" },
  { id: "moe-szyslak", title: "Moe Szyslak", emojis: "🍺😠", level: "easy" },
  { id: "chief-wiggum", title: "Chief Wiggum", emojis: "🍩👮", level: "easy" },
  { id: "sideshow-bob", title: "Sideshow Bob", emojis: "🔪🦁", level: "easy" },
  { id: "comic-book-guy", title: "Comic Book Guy", emojis: "📚😤", level: "easy" },
  { id: "groundskeeper-willie", title: "Groundskeeper Willie", emojis: "🍺🔧", level: "easy" },
  { id: "bluto-popeye", title: "Bluto", emojis: "🥊😠", level: "easy" },
  { id: "olive-oyl", title: "Olive Oyl", emojis: "💃🎀", level: "easy" },
  { id: "buzz-buzzard", title: "Buzz Buzzard", emojis: "🦅😈", level: "easy" },
  { id: "baby-huey", title: "Baby Huey", emojis: "👶🦆", level: "easy" },
  { id: "ash-ketchum", title: "Ash Ketchum", emojis: "⚡🧢", level: "easy" },
  { id: "meowth", title: "Meowth", emojis: "🐱💰", level: "easy" },
  { id: "yakko-warner", title: "Yakko Warner", emojis: "🎩😜", level: "easy" },
  { id: "wakko-warner", title: "Wakko Warner", emojis: "🎒🤪", level: "easy" },
  { id: "dot-warner", title: "Dot Warner", emojis: "🎀😘", level: "easy" },
  { id: "nigel-thornberry", title: "Nigel Thornberry", emojis: "📷🦏", level: "easy" },
  { id: "eliza-thornberry", title: "Eliza Thornberry", emojis: "🐒🗨", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "randy-marsh", title: "Randy Marsh", emojis: "😱🍺", level: "medium" },
  { id: "wendy-testaburger", title: "Wendy Testaburger", emojis: "🎀📢", level: "medium" },
  { id: "mr-garrison", title: "Mr. Garrison", emojis: "📏😤", level: "medium" },
  { id: "mr-hankey", title: "Mr. Hankey", emojis: "💩🎄", level: "medium" },
  { id: "towelie", title: "Towelie", emojis: "🚿🌿", level: "medium" },
  { id: "francine-smith", title: "Francine Smith", emojis: "💇📷", level: "medium" },
  { id: "steve-smith", title: "Steve Smith", emojis: "🤓🎮", level: "medium" },
  { id: "hayley-smith", title: "Hayley Smith", emojis: "🥗😑", level: "medium" },
  { id: "klaus-heisler", title: "Klaus Heisler", emojis: "🐟🎿", level: "medium" },
  { id: "leela-futurama", title: "Leela", emojis: "👁🚀", level: "medium" },
  { id: "amy-wong", title: "Amy Wong", emojis: "💜👑", level: "medium" },
  { id: "hermes-conrad", title: "Hermes Conrad", emojis: "📋🏃", level: "medium" },
  { id: "nibbler-futurama", title: "Nibbler", emojis: "👾💩", level: "medium" },
  { id: "otto-mann", title: "Otto Mann", emojis: "🚌🤘", level: "medium" },
  { id: "principal-skinner", title: "Principal Skinner", emojis: "🏫🫡", level: "medium" },
  { id: "waylon-smithers", title: "Waylon Smithers", emojis: "🕶💼", level: "medium" },
  { id: "selma-bouvier", title: "Selma Bouvier", emojis: "🚬👵", level: "medium" },
  { id: "patty-bouvier", title: "Patty Bouvier", emojis: "👓👵", level: "medium" },
  { id: "apu-nahasapeemapetilon", title: "Apu Nahasapeemapetilon", emojis: "🏪🛍", level: "medium" },
  { id: "mermaid-man", title: "Mermaid Man", emojis: "🦸🌊", level: "medium" },
  { id: "barnacle-boy", title: "Barnacle Boy", emojis: "🦸🐚", level: "medium" },
  { id: "mrs-puff", title: "Mrs. Puff", emojis: "🐡🚗", level: "medium" },
  { id: "larry-lobster", title: "Larry the Lobster", emojis: "🦞💪", level: "medium" },
  { id: "karen-plankton", title: "Karen Plankton", emojis: "💻😏", level: "medium" },
  { id: "flying-dutchman-spongebob", title: "The Flying Dutchman", emojis: "👻⚓", level: "medium" },

  // ===== HARD (25) =====
  { id: "gaz-membrane", title: "Gaz", emojis: "🎮😠", level: "hard" },
  { id: "dib-membrane", title: "Dib Membrane", emojis: "👽🔭", level: "hard" },
  { id: "professor-membrane", title: "Professor Membrane", emojis: "🥽🔬", level: "hard" },
  { id: "cow-cartoon", title: "Cow", emojis: "🐄👗", level: "hard" },
  { id: "chicken-cartoon", title: "Chicken", emojis: "🐔🥋", level: "hard" },
  { id: "ir-baboon", title: "I.R. Baboon", emojis: "🐒😤", level: "hard" },
  { id: "mr-herriman", title: "Mr. Herriman", emojis: "🐰🎩", level: "hard" },
  { id: "bloo-fosters", title: "Bloo", emojis: "👻😜", level: "hard" },
  { id: "wilt-fosters", title: "Wilt", emojis: "🏀💪", level: "hard" },
  { id: "eduardo-fosters", title: "Eduardo", emojis: "😨🐂", level: "hard" },
  { id: "coco-fosters", title: "Coco", emojis: "🌴🐣", level: "hard" },
  { id: "numbuh-one", title: "Numbuh 1", emojis: "🥽🚀", level: "hard" },
  { id: "numbuh-two", title: "Numbuh 2", emojis: "✈🍔", level: "hard" },
  { id: "numbuh-three", title: "Numbuh 3", emojis: "🐰😊", level: "hard" },
  { id: "numbuh-four", title: "Numbuh 4", emojis: "🥊😤", level: "hard" },
  { id: "numbuh-five", title: "Numbuh 5", emojis: "🎩🕶", level: "hard" },
  { id: "double-d-eddy", title: "Double D", emojis: "🧢📏", level: "hard" },
  { id: "ed-eddy", title: "Ed", emojis: "🧀😁", level: "hard" },
  { id: "eddy-eddy", title: "Eddy", emojis: "💰😏", level: "hard" },
  { id: "sarah-eddy", title: "Sarah", emojis: "😡🎀", level: "hard" },
  { id: "rolf-eddy", title: "Rolf", emojis: "🐐🚜", level: "hard" },
  { id: "chowder-cartoon", title: "Chowder", emojis: "🍲🐱", level: "hard" },
  { id: "mung-daal", title: "Mung Daal", emojis: "🍳🧔", level: "hard" },
  { id: "schnitzel-cartoon", title: "Schnitzel", emojis: "🥕😤", level: "hard" },
  { id: "panini-chowder", title: "Panini", emojis: "🥪😍", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "robotboy-cartoon", title: "Robotboy", emojis: "🤖👦", level: "impossible" },
  { id: "tommy-turnbull-robotboy", title: "Tommy Turnbull", emojis: "🎮👦", level: "impossible" },
  { id: "kif-kroker", title: "Kif Kroker", emojis: "🐸💚", level: "impossible" },
  { id: "mom-futurama", title: "Mom", emojis: "👵🦹", level: "impossible" },
  { id: "calculon-futurama", title: "Calculon", emojis: "🤖🎭", level: "impossible" },
  { id: "scruffy-futurama", title: "Scruffy", emojis: "🧹😐", level: "impossible" },
  { id: "robot-devil-futurama", title: "Robot Devil", emojis: "😈🤖", level: "impossible" },
  { id: "lee-kanker", title: "Lee Kanker", emojis: "💋😏", level: "impossible" },
  { id: "may-kanker", title: "May Kanker", emojis: "💋🥰", level: "impossible" },
  { id: "marie-kanker", title: "Marie Kanker", emojis: "💋📖", level: "impossible" },
  { id: "jonny-quest", title: "Jonny Quest", emojis: "🧭👦", level: "impossible" },
  { id: "hadji-quest", title: "Hadji Singh", emojis: "🐍🧢", level: "impossible" },
  { id: "race-bannon", title: "Race Bannon", emojis: "🕶🔫", level: "impossible" },
  { id: "bandit-quest", title: "Bandit", emojis: "🐕🧭", level: "impossible" },
  { id: "dr-zin", title: "Dr. Zin", emojis: "🧪😈", level: "impossible" },
  { id: "zorak-cartoon", title: "Zorak", emojis: "🦗🎸", level: "impossible" },
  { id: "moltar-cartoon", title: "Moltar", emojis: "🌋🎬", level: "impossible" },
  { id: "brak-cartoon", title: "Brak", emojis: "😵🎤", level: "impossible" },
  { id: "harvey-birdman", title: "Harvey Birdman", emojis: "⚖🦅", level: "impossible" },
  { id: "master-shake", title: "Master Shake", emojis: "🥤😤", level: "impossible" },
  { id: "frylock", title: "Frylock", emojis: "🍟🧠", level: "impossible" },
  { id: "meatwad", title: "Meatwad", emojis: "🍖😊", level: "impossible" },
  { id: "carl-atlanta", title: "Carl Brutananadilewski", emojis: "🚬🏊", level: "impossible" },
  { id: "freakazoid", title: "Freakazoid", emojis: "🖥⚡", level: "impossible" },
  { id: "early-cuyler", title: "Early Cuyler", emojis: "🍺🎣", level: "impossible" },
];
