// E179 «Guess the Cartoon Character by Emoji 2» — 100 characters · 25/tier
// VO: sfx/e179-<id>.wav
export const CARTOON_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "daffy-duck", title: "Daffy Duck", emojis: "🦆🔫", level: "easy" },
  { id: "porky-pig", title: "Porky Pig", emojis: "🐷🎬", level: "easy" },
  { id: "brian-griffin", title: "Brian Griffin", emojis: "🐕🍸", level: "easy" },
  { id: "mr-krabs", title: "Mr. Krabs", emojis: "🦀💰", level: "easy" },
  { id: "sandy-cheeks", title: "Sandy Cheeks", emojis: "🐿🤿", level: "easy" },
  { id: "plankton", title: "Plankton", emojis: "🦠😈", level: "easy" },
  { id: "bumblebee", title: "Bumblebee", emojis: "🐝🚗", level: "easy" },
  { id: "pinkie-pie", title: "Pinkie Pie", emojis: "🎈🐴", level: "easy" },
  { id: "leonardo", title: "Leonardo", emojis: "🐢⚔", level: "easy" },
  { id: "michelangelo", title: "Michelangelo", emojis: "🐢🍕", level: "easy" },
  { id: "alvin", title: "Alvin", emojis: "🐿🎤", level: "easy" },
  { id: "fry", title: "Philip J. Fry", emojis: "🧊🚀", level: "easy" },
  { id: "kenny-mccormick", title: "Kenny McCormick", emojis: "🧡💀", level: "easy" },
  { id: "bob-belcher", title: "Bob Belcher", emojis: "🍔🧔", level: "easy" },
  { id: "hank-hill", title: "Hank Hill", emojis: "🔥🍖", level: "easy" },
  { id: "maggie-simpson", title: "Maggie Simpson", emojis: "👶🍼", level: "easy" },
  { id: "krusty-the-clown", title: "Krusty the Clown", emojis: "🤡📺", level: "easy" },
  { id: "mr-burns", title: "Mr. Burns", emojis: "👴💰", level: "easy" },
  { id: "ned-flanders", title: "Ned Flanders", emojis: "🙏👓", level: "easy" },
  { id: "milhouse", title: "Milhouse", emojis: "👦🤓", level: "easy" },
  { id: "foghorn-leghorn", title: "Foghorn Leghorn", emojis: "🐓💬", level: "easy" },
  { id: "yosemite-sam", title: "Yosemite Sam", emojis: "🤠🔫", level: "easy" },
  { id: "casper", title: "Casper", emojis: "👻😊", level: "easy" },
  { id: "speedy-gonzales", title: "Speedy Gonzales", emojis: "🐭💨", level: "easy" },
  { id: "tasmanian-devil", title: "Taz", emojis: "🌪😡", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "pepe-le-pew", title: "Pepé Le Pew", emojis: "🦨💕", level: "medium" },
  { id: "marvin-the-martian", title: "Marvin the Martian", emojis: "🪐💣", level: "medium" },
  { id: "roger-american-dad", title: "Roger", emojis: "👽🍹", level: "medium" },
  { id: "stan-smith", title: "Stan Smith", emojis: "🕴🔫", level: "medium" },
  { id: "glenn-quagmire", title: "Glenn Quagmire", emojis: "😏✈", level: "medium" },
  { id: "ralph-wiggum", title: "Ralph Wiggum", emojis: "👦🖍", level: "medium" },
  { id: "huckleberry-hound", title: "Huckleberry Hound", emojis: "🐶🎵", level: "medium" },
  { id: "snagglepuss", title: "Snagglepuss", emojis: "🦁🎭", level: "medium" },
  { id: "top-cat", title: "Top Cat", emojis: "🐱🎩", level: "medium" },
  { id: "magilla-gorilla", title: "Magilla Gorilla", emojis: "🦍🎀", level: "medium" },
  { id: "hong-kong-phooey", title: "Hong Kong Phooey", emojis: "🐶🥋", level: "medium" },
  { id: "george-jetson", title: "George Jetson", emojis: "🛸👔", level: "medium" },
  { id: "rosie-the-robot", title: "Rosie the Robot", emojis: "🤖🧹", level: "medium" },
  { id: "wilma-flintstone", title: "Wilma Flintstone", emojis: "🦴👩", level: "medium" },
  { id: "scrappy-doo", title: "Scrappy-Doo", emojis: "🐶💪", level: "medium" },
  { id: "dick-dastardly", title: "Dick Dastardly", emojis: "🏎😈", level: "medium" },
  { id: "mordecai", title: "Mordecai", emojis: "🐦☕", level: "medium" },
  { id: "rigby", title: "Rigby", emojis: "🦝🎮", level: "medium" },
  { id: "princess-bubblegum", title: "Princess Bubblegum", emojis: "👑🍬", level: "medium" },
  { id: "marceline", title: "Marceline", emojis: "🧛🎸", level: "medium" },
  { id: "bmo", title: "BMO", emojis: "🤖🎮", level: "medium" },
  { id: "ice-king", title: "Ice King", emojis: "👑❄", level: "medium" },
  { id: "arnold", title: "Arnold", emojis: "🏈👦", level: "medium" },
  { id: "helga-pataki", title: "Helga Pataki", emojis: "👧🎀", level: "medium" },
  { id: "reptar", title: "Reptar", emojis: "🦖🏙", level: "medium" },

  // ===== HARD (25) =====
  { id: "zuko", title: "Zuko", emojis: "🔥🤴", level: "hard" },
  { id: "katara", title: "Katara", emojis: "💧👧", level: "hard" },
  { id: "sokka", title: "Sokka", emojis: "🪃🌊", level: "hard" },
  { id: "toph", title: "Toph", emojis: "🪨👧", level: "hard" },
  { id: "appa", title: "Appa", emojis: "🦬☁", level: "hard" },
  { id: "steven-universe", title: "Steven Universe", emojis: "⭐💎", level: "hard" },
  { id: "garnet", title: "Garnet", emojis: "✊💎", level: "hard" },
  { id: "grim-billy-mandy", title: "Grim", emojis: "💀⏳", level: "hard" },
  { id: "mandy", title: "Mandy", emojis: "👧💢", level: "hard" },
  { id: "ben-ten", title: "Ben 10", emojis: "⌚👽", level: "hard" },
  { id: "danny-phantom", title: "Danny Phantom", emojis: "👻⚡", level: "hard" },
  { id: "beast-boy", title: "Beast Boy", emojis: "🦖💚", level: "hard" },
  { id: "splinter", title: "Splinter", emojis: "🐀🥋", level: "hard" },
  { id: "cosmo", title: "Cosmo", emojis: "🧚💚", level: "hard" },
  { id: "wanda", title: "Wanda", emojis: "🧚💗", level: "hard" },
  { id: "professor-farnsworth", title: "Professor Farnsworth", emojis: "🥼🔬", level: "hard" },
  { id: "gary-the-snail", title: "Gary the Snail", emojis: "🐌🐚", level: "hard" },
  { id: "betty-boop", title: "Betty Boop", emojis: "💋👗", level: "hard" },
  { id: "underdog", title: "Underdog", emojis: "🐶🦸", level: "hard" },
  { id: "mr-magoo", title: "Mr. Magoo", emojis: "👴👓", level: "hard" },
  { id: "quick-draw-mcgraw", title: "Quick Draw McGraw", emojis: "🐴🔫", level: "hard" },
  { id: "bullwinkle", title: "Bullwinkle", emojis: "🦌🎩", level: "hard" },
  { id: "droopy", title: "Droopy", emojis: "🐶😑", level: "hard" },
  { id: "astro-jetson", title: "Astro", emojis: "🐕🛸", level: "hard" },
  { id: "mighty-mouse", title: "Mighty Mouse", emojis: "🐭🦸", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "rocky-squirrel", title: "Rocky the Flying Squirrel", emojis: "🐿🪂", level: "impossible" },
  { id: "slappy-squirrel", title: "Slappy Squirrel", emojis: "🐿👵", level: "impossible" },
  { id: "buster-bunny", title: "Buster Bunny", emojis: "🐰📺", level: "impossible" },
  { id: "earthworm-jim", title: "Earthworm Jim", emojis: "🪱🔫", level: "impossible" },
  { id: "inspector-gadget", title: "Inspector Gadget", emojis: "🕵🔧", level: "impossible" },
  { id: "dr-claw", title: "Dr. Claw", emojis: "🦹🐱", level: "impossible" },
  { id: "lion-o", title: "Lion-O", emojis: "🦁👁", level: "impossible" },
  { id: "cheetara", title: "Cheetara", emojis: "🐆💨", level: "impossible" },
  { id: "she-ra", title: "She-Ra", emojis: "⚔👸", level: "impossible" },
  { id: "starscream", title: "Starscream", emojis: "🤖✈", level: "impossible" },
  { id: "megatron", title: "Megatron", emojis: "🤖🔫", level: "impossible" },
  { id: "fluttershy", title: "Fluttershy", emojis: "🦋🐴", level: "impossible" },
  { id: "applejack", title: "Applejack", emojis: "🍎🐴", level: "impossible" },
  { id: "gargamel", title: "Gargamel", emojis: "🧙😾", level: "impossible" },
  { id: "papa-smurf", title: "Papa Smurf", emojis: "👴🍄", level: "impossible" },
  { id: "pinky-mouse", title: "Pinky", emojis: "🐭🤪", level: "impossible" },
  { id: "the-brain", title: "The Brain", emojis: "🐭🧠", level: "impossible" },
  { id: "felix-the-cat", title: "Felix the Cat", emojis: "🐱👜", level: "impossible" },
  { id: "penelope-pitstop", title: "Penelope Pitstop", emojis: "🏎💄", level: "impossible" },
  { id: "muttley", title: "Muttley", emojis: "🐶😏", level: "impossible" },
  { id: "captain-caveman", title: "Captain Caveman", emojis: "🦸🏏", level: "impossible" },
  { id: "jenny-xj9", title: "Jenny", emojis: "🤖👧", level: "impossible" },
  { id: "static-shock", title: "Static Shock", emojis: "🦸⚡", level: "impossible" },
  { id: "gumby", title: "Gumby", emojis: "💚🧍", level: "impossible" },
  { id: "brainy-smurf", title: "Brainy Smurf", emojis: "🤓🍄", level: "impossible" },
];
