// E242 «Guess the Cartoon by Emoji 5» — 100 cartoon TV shows · 25/tier · clue = plain Unicode emoji
// Western/global animated TV cartoons (shows, not characters — see cartoonEmoji/2/3 for characters).
// Single-codepoint emojis only, no ZWJ/FE0F/skin-tone/flags. VO: sfx/e242-<id>.wav
export const CARTOON_EMOJI5 = [
  // ===== EASY (25) =====
  { id: "adventure-time", title: "Adventure Time", emojis: "🎒⚔", level: "easy" },
  { id: "bluey", title: "Bluey", emojis: "🐶🎾", level: "easy" },
  { id: "paw-patrol", title: "Paw Patrol", emojis: "🐶🚒", level: "easy" },
  { id: "gravity-falls", title: "Gravity Falls", emojis: "🌲🔮", level: "easy" },
  { id: "phineas-and-ferb", title: "Phineas and Ferb", emojis: "🌞🛠", level: "easy" },
  { id: "the-powerpuff-girls", title: "The Powerpuff Girls", emojis: "💓⚡", level: "easy" },
  { id: "teen-titans-go", title: "Teen Titans Go!", emojis: "🦸📺", level: "easy" },
  { id: "the-amazing-world-of-gumball", title: "The Amazing World of Gumball", emojis: "🐱🌈", level: "easy" },
  { id: "bobs-burgers", title: "Bob's Burgers", emojis: "🍔🎸", level: "easy" },
  { id: "futurama", title: "Futurama", emojis: "🚀🦞", level: "easy" },
  { id: "beavis-and-butt-head", title: "Beavis and Butt-Head", emojis: "🎸😆", level: "easy" },
  { id: "aqua-teen-hunger-force", title: "Aqua Teen Hunger Force", emojis: "🍟👽", level: "easy" },
  { id: "care-bears", title: "Care Bears", emojis: "🧸❤", level: "easy" },
  { id: "strawberry-shortcake", title: "Strawberry Shortcake", emojis: "🍓🎀", level: "easy" },
  { id: "jem-and-the-holograms", title: "Jem and the Holograms", emojis: "🎤💎", level: "easy" },
  { id: "thomas-and-friends", title: "Thomas & Friends", emojis: "🚂💨", level: "easy" },
  { id: "bob-the-builder", title: "Bob the Builder", emojis: "👷🔨", level: "easy" },
  { id: "masha-and-the-bear", title: "Masha and the Bear", emojis: "👧🐻", level: "easy" },
  { id: "oggy-and-the-cockroaches", title: "Oggy and the Cockroaches", emojis: "🐱🪳", level: "easy" },
  { id: "rainbow-brite", title: "Rainbow Brite", emojis: "🌈✨", level: "easy" },
  { id: "talespin", title: "TaleSpin", emojis: "✈🐻", level: "easy" },
  { id: "goof-troop", title: "Goof Troop", emojis: "🐶⛺", level: "easy" },
  { id: "the-new-adventures-of-winnie-the-pooh", title: "The New Adventures of Winnie the Pooh", emojis: "🍯🐻", level: "easy" },
  { id: "my-little-pony-n-friends", title: "My Little Pony 'n Friends", emojis: "🦄🌈", level: "easy" },
  { id: "bananas-in-pyjamas", title: "Bananas in Pyjamas", emojis: "🍌😴", level: "easy" },
  // ===== MEDIUM (25) =====
  { id: "batman-beyond", title: "Batman Beyond", emojis: "🦇🌃", level: "medium" },
  { id: "the-spectacular-spider-man", title: "The Spectacular Spider-Man", emojis: "🕷🏙", level: "medium" },
  { id: "justice-league-unlimited", title: "Justice League Unlimited", emojis: "🦸🌍", level: "medium" },
  { id: "x-men-evolution", title: "X-Men: Evolution", emojis: "🧬⚡", level: "medium" },
  { id: "avengers-earths-mightiest-heroes", title: "Avengers: Earth's Mightiest Heroes", emojis: "🛡⚡", level: "medium" },
  { id: "ben-10-alien-force", title: "Ben 10: Alien Force", emojis: "👽⌚", level: "medium" },
  { id: "generator-rex", title: "Generator Rex", emojis: "🦾🔧", level: "medium" },
  { id: "jackie-chan-adventures", title: "Jackie Chan Adventures", emojis: "🥋🗝", level: "medium" },
  { id: "sabrina-the-animated-series", title: "Sabrina: The Animated Series", emojis: "🐱✨", level: "medium" },
  { id: "motorcity", title: "Motorcity", emojis: "🏎💨", level: "medium" },
  { id: "my-life-as-a-teenage-robot", title: "My Life as a Teenage Robot", emojis: "🤖⚡", level: "medium" },
  { id: "fanboy-and-chum-chum", title: "Fanboy & Chum Chum", emojis: "🦸🍦", level: "medium" },
  { id: "class-of-the-titans", title: "Class of the Titans", emojis: "🏛⚡", level: "medium" },
  { id: "martin-mystery", title: "Martin Mystery", emojis: "👽🔍", level: "medium" },
  { id: "as-told-by-ginger", title: "As Told by Ginger", emojis: "📓💬", level: "medium" },
  { id: "rocket-power", title: "Rocket Power", emojis: "🛹🏄", level: "medium" },
  { id: "all-grown-up", title: "All Grown Up!", emojis: "🧒🎈", level: "medium" },
  { id: "6teen", title: "6teen", emojis: "🛍🍔", level: "medium" },
  { id: "grojband", title: "Grojband", emojis: "🎸🥁", level: "medium" },
  { id: "wow-wow-wubbzy", title: "Wow! Wow! Wubbzy!", emojis: "💛🎉", level: "medium" },
  { id: "the-weekenders", title: "The Weekenders", emojis: "🛼🌞", level: "medium" },
  { id: "braceface", title: "Braceface", emojis: "😬✨", level: "medium" },
  { id: "detentionaire", title: "Detentionaire", emojis: "📚🕵", level: "medium" },
  { id: "danger-mouse", title: "Danger Mouse", emojis: "🐭🕶", level: "medium" },
  { id: "the-mask-animated-series", title: "The Mask: Animated Series", emojis: "🎭💚", level: "medium" },
  // ===== HARD (25) =====
  { id: "chalkzone", title: "ChalkZone", emojis: "✏🌀", level: "hard" },
  { id: "catscratch", title: "Catscratch", emojis: "🐱💰", level: "hard" },
  { id: "el-tigre", title: "El Tigre: The Adventures of Manny Rivera", emojis: "🐯🎭", level: "hard" },
  { id: "making-fiends", title: "Making Fiends", emojis: "😈🎀", level: "hard" },
  { id: "skunk-fu", title: "Skunk Fu!", emojis: "🦨🥋", level: "hard" },
  { id: "the-mighty-b", title: "The Mighty B!", emojis: "🐝🏕", level: "hard" },
  { id: "histeria", title: "Histeria!", emojis: "📖🤪", level: "hard" },
  { id: "pinky-elmyra-and-the-brain", title: "Pinky, Elmyra & the Brain", emojis: "🐭👧", level: "hard" },
  { id: "toonsylvania", title: "Toonsylvania", emojis: "🧟⚡", level: "hard" },
  { id: "2-stupid-dogs", title: "2 Stupid Dogs", emojis: "🐕🦴", level: "hard" },
  { id: "eek-the-cat", title: "Eek! The Cat", emojis: "🐱😱", level: "hard" },
  { id: "ed-grimley", title: "The Completely Mental Misadventures of Ed Grimley", emojis: "🎻🌀", level: "hard" },
  { id: "widget-the-world-watcher", title: "Widget the World Watcher", emojis: "👽🌍", level: "hard" },
  { id: "denver-the-last-dinosaur", title: "Denver, the Last Dinosaur", emojis: "🦕🛹", level: "hard" },
  { id: "galaxy-high", title: "Galaxy High", emojis: "🚀🎓", level: "hard" },
  { id: "kidd-video", title: "Kidd Video", emojis: "🎸📼", level: "hard" },
  { id: "camp-candy", title: "Camp Candy", emojis: "🍬🏕", level: "hard" },
  { id: "yo-yogi", title: "Yo Yogi!", emojis: "🐻👮", level: "hard" },
  { id: "the-terrible-thunderlizards", title: "The Terrible Thunderlizards", emojis: "🦖⚡", level: "hard" },
  { id: "extreme-dinosaurs", title: "Extreme Dinosaurs", emojis: "🦖💪", level: "hard" },
  { id: "street-sharks", title: "Street Sharks", emojis: "🦈🛹", level: "hard" },
  { id: "biker-mice-from-mars", title: "Biker Mice from Mars", emojis: "🐭🏍", level: "hard" },
  { id: "exosquad", title: "Exosquad", emojis: "🚀🤖", level: "hard" },
  { id: "roswell-conspiracies", title: "Roswell Conspiracies", emojis: "👽🛸", level: "hard" },
  { id: "sky-dancers", title: "Sky Dancers", emojis: "🧚🎀", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { id: "dinosaucers", title: "Dinosaucers", emojis: "🦖🚀", level: "impossible" },
  { id: "visionaries", title: "Visionaries: Knights of the Magical Light", emojis: "🛡✨", level: "impossible" },
  { id: "jayce-and-the-wheeled-warriors", title: "Jayce and the Wheeled Warriors", emojis: "🌱⚙", level: "impossible" },
  { id: "inhumanoids", title: "Inhumanoids", emojis: "🗿🔥", level: "impossible" },
  { id: "mask-vehicles", title: "M.A.S.K.", emojis: "🚗🎭", level: "impossible" },
  { id: "bravestarr", title: "BraveStarr", emojis: "🤠🐴", level: "impossible" },
  { id: "silverhawks", title: "SilverHawks", emojis: "🦅🌌", level: "impossible" },
  { id: "the-get-along-gang", title: "The Get Along Gang", emojis: "🐰🚂", level: "impossible" },
  { id: "superted", title: "SuperTed", emojis: "🧸🦸", level: "impossible" },
  { id: "the-snorks", title: "The Snorks", emojis: "🐌🌊", level: "impossible" },
  { id: "pound-puppies", title: "Pound Puppies", emojis: "🐶🎀", level: "impossible" },
  { id: "the-raccoons", title: "The Raccoons", emojis: "🦝🌲", level: "impossible" },
  { id: "cops-1988", title: "C.O.P.S.", emojis: "🚔🚨", level: "impossible" },
  { id: "wildfire-1986", title: "Wildfire", emojis: "🐴🔥", level: "impossible" },
  { id: "galaxy-rangers", title: "Galaxy Rangers", emojis: "🤠🚀", level: "impossible" },
  { id: "pole-position", title: "Pole Position", emojis: "🏎🏁", level: "impossible" },
  { id: "the-plucky-duck-show", title: "The Plucky Duck Show", emojis: "🦆🎬", level: "impossible" },
  { id: "popples", title: "Popples", emojis: "🧸🎈", level: "impossible" },
  { id: "turbo-teen", title: "Turbo Teen", emojis: "🚗⚡", level: "impossible" },
  { id: "new-adventures-of-he-man", title: "The New Adventures of He-Man", emojis: "🗡🌌", level: "impossible" },
  { id: "james-bond-jr", title: "James Bond Jr.", emojis: "🕶🚔", level: "impossible" },
  { id: "cadillacs-and-dinosaurs", title: "Cadillacs and Dinosaurs", emojis: "🚗🦖", level: "impossible" },
  { id: "sonic-underground", title: "Sonic Underground", emojis: "🦔🎸", level: "impossible" },
  { id: "twisted-tales-of-felix-the-cat", title: "The Twisted Tales of Felix the Cat", emojis: "🐱🌀", level: "impossible" },
  { id: "cro", title: "Cro", emojis: "🦣🔧", level: "impossible" },
];
