// E199 cartoon-emoji facts — one true <=70-char fact per character, shown on reveal.
export const CARTOON_EMOJI_3_FACTS = {
  // EASY
  "chef-south-park": "South Park's school cook, famous for smooth soul songs.",
  "kyle-broflovski": "South Park's Jewish kid, known for his green ushanka hat.",
  "butters-stotch": "South Park's sweet, endlessly grounded good-boy character.",
  "meg-griffin": "Family Guy's teen daughter, the family's favorite punching bag.",
  "chris-griffin": "Family Guy's dim-witted, video-game-loving teen son.",
  "linda-belcher": "Bob's Burgers' wine-loving mom who bursts into song.",
  "tina-belcher": "Bob's Burgers' awkward teen who writes erotic zombie fanfic.",
  "gene-belcher": "Bob's Burgers' keyboard-loving middle child and prankster.",
  "louise-belcher": "Bob's Burgers' mischievous kid who wears pink bunny ears.",
  "moe-szyslak": "The gruff, lonely bartender of Moe's Tavern in Springfield.",
  "chief-wiggum": "Springfield's donut-loving, none-too-bright police chief.",
  "sideshow-bob": "Krusty's former sidekick turned Simpsons rake-stepping villain.",
  "comic-book-guy": "Springfield's condescending owner of the Android's Dungeon.",
  "groundskeeper-willie": "The short-tempered, kilt-wearing Scottish school janitor.",
  "bluto-popeye": "Popeye's brawny rival who's always after Olive Oyl.",
  "olive-oyl": "Popeye's tall, thin sweetheart in the classic cartoon.",
  "buzz-buzzard": "Woody Woodpecker's scheming, con-artist buzzard nemesis.",
  "baby-huey": "A giant, naive baby duckling from classic Paramount cartoons.",
  "ash-ketchum": "The Pokemon trainer who dreams of becoming a Pokemon Master.",
  "meowth": "The talking, greedy cat who travels with Team Rocket.",
  "yakko-warner": "The eldest, wisecracking Warner sibling in Animaniacs.",
  "wakko-warner": "The Animaniacs sibling famous for his bottomless gag bag.",
  "dot-warner": "The cute, sharp-tongued youngest Warner sibling.",
  "nigel-thornberry": "The booming British nature documentarian who yells 'Smashing!'",
  "eliza-thornberry": "The girl who can secretly talk to animals in the wild.",

  // MEDIUM
  "randy-marsh": "Stan's chaotic, often shirtless dad on South Park.",
  "wendy-testaburger": "South Park's smart, socially conscious activist student.",
  "mr-garrison": "South Park's eccentric, ever-changing elementary teacher.",
  "mr-hankey": "South Park's singing Christmas poo who visits kids in December.",
  "towelie": "South Park's stoned talking towel who forgets his towel.",
  "francine-smith": "American Dad's spirited, hairdresser mom of the Smith family.",
  "steve-smith": "American Dad's nerdy teen son, Roger's frequent target.",
  "hayley-smith": "American Dad's liberal, free-spirited college-age daughter.",
  "klaus-heisler": "American Dad's German fish, once a champion downhill skier.",
  "leela-futurama": "Futurama's one-eyed, tough starship captain.",
  "amy-wong": "Futurama's wealthy, purple-haired Martian intern.",
  "hermes-conrad": "Futurama's bureaucratic Jamaican limbo-champion accountant.",
  "nibbler-futurama": "Futurama's ancient, dark-matter-eating alien pet.",
  "otto-mann": "The Simpsons' laid-back, heavy-metal school bus driver.",
  "principal-skinner": "Springfield Elementary's rigid, mother-dominated principal.",
  "waylon-smithers": "Mr. Burns' devoted, sunglasses-wearing personal assistant.",
  "selma-bouvier": "Marge Simpson's raspy-voiced, chain-smoking twin sister.",
  "patty-bouvier": "Marge Simpson's other chain-smoking, sharp-tongued twin.",
  "apu-nahasapeemapetilon": "The hardworking owner of Springfield's Kwik-E-Mart.",
  "mermaid-man": "SpongeBob's aging, retired superhero idol in Bikini Bottom.",
  "barnacle-boy": "Mermaid Man's grumpy, loyal superhero sidekick.",
  "mrs-puff": "SpongeBob's exasperated pufferfish boating school teacher.",
  "larry-lobster": "Bikini Bottom's buff, gym-loving lifeguard lobster.",
  "karen-plankton": "Plankton's sarcastic computer wife and scheming partner.",
  "flying-dutchman-spongebob": "The ghost pirate who haunts Bikini Bottom's waters.",

  // HARD
  "gaz-membrane": "Invader Zim's fierce, video-game-obsessed little sister.",
  "dib-membrane": "Invader Zim's paranormal-obsessed kid trying to expose Zim.",
  "professor-membrane": "Invader Zim's oblivious scientist father figure.",
  "cow-cartoon": "Cartoon Network's dress-wearing farm cow sibling.",
  "chicken-cartoon": "Cartoon Network's karate-practicing farm chicken sibling.",
  "ir-baboon": "I Am Weasel's dim, jealous rival baboon.",
  "mr-herriman": "Foster's Home's strict, formal rabbit administrator.",
  "bloo-fosters": "Foster's Home's mischievous, blob-shaped imaginary friend.",
  "wilt-fosters": "Foster's Home's tall, gentle one-armed basketball star friend.",
  "eduardo-fosters": "Foster's Home's big, timid purple monster friend.",
  "coco-fosters": "Foster's Home's palm-tree-bird hybrid imaginary friend.",
  "numbuh-one": "Codename Kids Next Door's bald, goggle-wearing leader.",
  "numbuh-two": "Codename Kids Next Door's pilot and burger-loving gadget guy.",
  "numbuh-three": "Codename Kids Next Door's cheerful, rabbit-loving member.",
  "numbuh-four": "Codename Kids Next Door's short-tempered martial artist.",
  "numbuh-five": "Codename Kids Next Door's cool, hat-wearing tactician.",
  "double-d-eddy": "Ed, Edd n Eddy's smart, sock-hat-wearing member of the trio.",
  "ed-eddy": "Ed, Edd n Eddy's dim but loyal, gravy-loving giant of a kid.",
  "eddy-eddy": "Ed, Edd n Eddy's scheming, money-obsessed short leader.",
  "sarah-eddy": "Ed's bossy, easily-angered little sister.",
  "rolf-eddy": "Ed, Edd n Eddy's odd foreign farm-boy neighbor.",
  "chowder-cartoon": "A cat-bear-rabbit apprentice chef at Mung Daal's catering.",
  "mung-daal": "Chowder's grumpy but caring blue chef and mentor.",
  "schnitzel-cartoon": "Mung Daal's grumbling root-vegetable-creature sous chef.",
  "panini-chowder": "Chowder's love-struck sandwich-named cooking-school rival.",

  // IMPOSSIBLE
  "robotboy-cartoon": "A powerful robot posing as an ordinary schoolboy.",
  "tommy-turnbull-robotboy": "The boy who befriends and hides the robot Robotboy.",
  "kif-kroker": "Futurama's timid, green amphibian first officer.",
  "mom-futurama": "Futurama's sweet-seeming, ruthless robotics-company owner.",
  "calculon-futurama": "Futurama's melodramatic robot soap-opera actor.",
  "scruffy-futurama": "Futurama's indifferent, ever-sleeping Planet Express janitor.",
  "robot-devil-futurama": "Futurama's operatic, rule-bound ruler of Robot Hell.",
  "lee-kanker": "Ed, Edd n Eddy's toughest, cigar-loving Kanker sister.",
  "may-kanker": "Ed, Edd n Eddy's clingy Kanker sister who adores Ed.",
  "marie-kanker": "Ed, Edd n Eddy's book-loving Kanker sister obsessed with Edd.",
  "jonny-quest": "The adventurous boy hero of the classic 1960s action cartoon.",
  "hadji-quest": "Jonny Quest's adopted friend skilled in mysticism and languages.",
  "race-bannon": "Jonny Quest's tough bodyguard and secret agent.",
  "bandit-quest": "Jonny Quest's loyal pet bulldog companion.",
  "dr-zin": "Jonny Quest's recurring criminal mastermind villain.",
  "zorak-cartoon": "Space Ghost Coast to Coast's mantis bandleader villain.",
  "moltar-cartoon": "Space Ghost Coast to Coast's lava-dwelling director.",
  "brak-cartoon": "The dopey orange alien from Space Ghost's universe.",
  "harvey-birdman": "A washed-up superhero turned bumbling attorney at law.",
  "master-shake": "Aqua Teen Hunger Force's rude, self-centered milkshake cup.",
  "frylock": "Aqua Teen Hunger Force's smart, levitating box of fries.",
  "meatwad": "Aqua Teen Hunger Force's sweet, shape-shifting meatball.",
  "carl-atlanta": "Aqua Teen Hunger Force's crude, cigarette-smoking neighbor.",
  "freakazoid": "A hyperactive superhero created by a computer virus accident.",
  "early-cuyler": "Squidbillies' beer-loving, trouble-prone hillbilly squid.",
};
