// E97 «Guess the ZOOMED Car» — GuessSync "What the Zoom" hard-mode.
// Reuses the EXACT E17 car image set (cars/<slug>.png) and E17's CAR_FACTS + cm-<slug>.wav
// answer VOs (copied to cz-<slug>.wav — identical "It's the <name>!" line, zero new audio cost),
// but RE-TIERED by how hard each car is to name from an EXTREME off-center close-up crop
// (headlight / grille / badge area, scale 3.0). A random patch shows one surface/feature region
// only, so difficulty here tracks GRILLE/HEADLIGHT/BADGE distinctiveness, NOT general car fame:
//   EASY = unmistakable grille/headlight/badge shape survives any crop (round VW/Mini/911 lamps,
//          Jeep 7-slot grille, Rolls Parthenon grille, angular Lambo Y-lights, brushed DeLorean
//          steel, etc.)
//   IMPOSSIBLE = plain/generic sheet metal or ultra-obscure regional model — a crop gives no clue
// image: cars/<slug>.png | answer VO: sfx/cz-<slug>.wav (copied from E17's cm-<slug>.wav)
export const CARZOOM = [
  // ===== EASY (25) — grille/headlight/badge shape unmistakable from any close-up patch =====
  { slug: "vw-beetle", name: "Volkswagen Beetle", level: "easy" },
  { slug: "mini-cooper", name: "Mini Cooper", level: "easy" },
  { slug: "jeep-wrangler", name: "Jeep Wrangler", level: "easy" },
  { slug: "rolls-royce-phantom", name: "Rolls-Royce Phantom", level: "easy" },
  { slug: "bugatti-chiron", name: "Bugatti Chiron", level: "easy" },
  { slug: "porsche-911", name: "Porsche 911", level: "easy" },
  { slug: "ford-mustang", name: "Ford Mustang", level: "easy" },
  { slug: "chevrolet-corvette", name: "Chevrolet Corvette", level: "easy" },
  { slug: "mercedes-g-wagon", name: "Mercedes-Benz G-Wagon", level: "easy" },
  { slug: "hummer-h2", name: "Hummer H2", level: "easy" },
  { slug: "lamborghini-aventador", name: "Lamborghini Aventador", level: "easy" },
  { slug: "lamborghini-huracan", name: "Lamborghini Huracan", level: "easy" },
  { slug: "bmw-i8", name: "BMW i8", level: "easy" },
  { slug: "range-rover", name: "Range Rover", level: "easy" },
  { slug: "cybertruck", name: "Tesla Cybertruck", level: "easy" },
  { slug: "fiat-500", name: "Fiat 500", level: "easy" },
  { slug: "vw-camper-van", name: "Volkswagen Camper Van", level: "easy" },
  { slug: "ford-model-t", name: "Ford Model T", level: "easy" },
  { slug: "dodge-charger", name: "Dodge Charger", level: "easy" },
  { slug: "delorean-dmc12", name: "DeLorean DMC-12", level: "easy" },
  { slug: "citroen-ds", name: "Citroen DS", level: "easy" },
  { slug: "aston-martin-db5", name: "Aston Martin DB5", level: "easy" },
  { slug: "mercedes-300sl-gullwing", name: "Mercedes-Benz 300SL Gullwing", level: "easy" },
  { slug: "shelby-cobra", name: "Shelby Cobra 427", level: "easy" },
  { slug: "ferrari-f40", name: "Ferrari F40", level: "easy" },
  // ===== MEDIUM (25) — recognizable feature, but a random patch can be ambiguous =====
  { slug: "tesla-model-s", name: "Tesla Model S", level: "medium" },
  { slug: "toyota-corolla", name: "Toyota Corolla", level: "medium" },
  { slug: "ford-f150", name: "Ford F-150", level: "medium" },
  { slug: "volkswagen-golf", name: "Volkswagen Golf", level: "medium" },
  { slug: "toyota-prius", name: "Toyota Prius", level: "medium" },
  { slug: "mazda-mx5", name: "Mazda MX-5 Miata", level: "medium" },
  { slug: "nissan-gtr", name: "Nissan GT-R", level: "medium" },
  { slug: "audi-r8", name: "Audi R8", level: "medium" },
  { slug: "bmw-m3", name: "BMW M3", level: "medium" },
  { slug: "chevrolet-camaro", name: "Chevrolet Camaro", level: "medium" },
  { slug: "subaru-wrx", name: "Subaru WRX STI", level: "medium" },
  { slug: "dodge-viper", name: "Dodge Viper", level: "medium" },
  { slug: "toyota-supra", name: "Toyota Supra", level: "medium" },
  { slug: "mclaren-p1", name: "McLaren P1", level: "medium" },
  { slug: "cadillac-eldorado", name: "Cadillac Eldorado", level: "medium" },
  { slug: "pontiac-firebird", name: "Pontiac Firebird Trans Am", level: "medium" },
  { slug: "chevrolet-bel-air", name: "Chevrolet Bel Air", level: "medium" },
  { slug: "honda-nsx", name: "Honda NSX", level: "medium" },
  { slug: "mazda-rx7", name: "Mazda RX-7", level: "medium" },
  { slug: "ferrari-testarossa", name: "Ferrari Testarossa", level: "medium" },
  { slug: "lamborghini-countach", name: "Lamborghini Countach", level: "medium" },
  { slug: "jaguar-e-type", name: "Jaguar E-Type", level: "medium" },
  { slug: "land-rover-defender", name: "Land Rover Defender", level: "medium" },
  { slug: "porsche-cayenne", name: "Porsche Cayenne", level: "medium" },
  { slug: "dodge-challenger", name: "Dodge Challenger", level: "medium" },
  // ===== HARD (25) — plain/subtle grille & lamps; a close-up patch gives little away =====
  { slug: "lancia-delta-integrale", name: "Lancia Delta Integrale", level: "hard" },
  { slug: "alfa-romeo-giulia", name: "Alfa Romeo Giulia", level: "hard" },
  { slug: "lexus-lfa", name: "Lexus LFA", level: "hard" },
  { slug: "koenigsegg-agera", name: "Koenigsegg Agera", level: "hard" },
  { slug: "pagani-zonda", name: "Pagani Zonda", level: "hard" },
  { slug: "datsun-240z", name: "Datsun 240Z", level: "hard" },
  { slug: "alpine-a110", name: "Renault Alpine A110", level: "hard" },
  { slug: "lotus-esprit", name: "Lotus Esprit", level: "hard" },
  { slug: "nissan-skyline-r34", name: "Nissan Skyline GT-R R34", level: "hard" },
  { slug: "bmw-2002-turbo", name: "BMW 2002 Turbo", level: "hard" },
  { slug: "toyota-2000gt", name: "Toyota 2000GT", level: "hard" },
  { slug: "audi-quattro", name: "Audi Quattro", level: "hard" },
  { slug: "de-tomaso-pantera", name: "De Tomaso Pantera", level: "hard" },
  { slug: "lotus-elise", name: "Lotus Elise", level: "hard" },
  { slug: "peugeot-205-gti", name: "Peugeot 205 GTI", level: "hard" },
  { slug: "ford-sierra-cosworth", name: "Ford Sierra RS Cosworth", level: "hard" },
  { slug: "buick-riviera", name: "Buick Riviera", level: "hard" },
  { slug: "saab-900-turbo", name: "Saab 900 Turbo", level: "hard" },
  { slug: "amc-gremlin", name: "AMC Gremlin", level: "hard" },
  { slug: "tvr-sagaris", name: "TVR Sagaris", level: "hard" },
  { slug: "maserati-ghibli", name: "Maserati Ghibli", level: "hard" },
  { slug: "honda-s2000", name: "Honda S2000", level: "hard" },
  { slug: "vw-golf-gti", name: "Volkswagen Golf GTI", level: "hard" },
  { slug: "mercedes-sls-amg", name: "Mercedes-Benz SLS AMG", level: "hard" },
  { slug: "volvo-p1800", name: "Volvo P1800", level: "hard" },
  // ===== IMPOSSIBLE (25) — flat/generic sheet metal (crop = no clue) or ultra-obscure =====
  { slug: "tatra-603", name: "Tatra 603", level: "impossible" },
  { slug: "tucker-48", name: "Tucker 48", level: "impossible" },
  { slug: "bmw-isetta", name: "BMW Isetta", level: "impossible" },
  { slug: "wartburg-353", name: "Wartburg 353", level: "impossible" },
  { slug: "trabant-601", name: "Trabant 601", level: "impossible" },
  { slug: "marcos-gt", name: "Marcos GT", level: "impossible" },
  { slug: "bizzarrini-5300", name: "Bizzarrini 5300 GT", level: "impossible" },
  { slug: "monteverdi-hai", name: "Monteverdi Hai", level: "impossible" },
  { slug: "facel-vega", name: "Facel Vega HK500", level: "impossible" },
  { slug: "vector-w8", name: "Vector W8", level: "impossible" },
  { slug: "gaz-volga", name: "GAZ Volga", level: "impossible" },
  { slug: "hindustan-ambassador", name: "Hindustan Ambassador", level: "impossible" },
  { slug: "saab-sonett", name: "Saab Sonett", level: "impossible" },
  { slug: "panhard-24", name: "Panhard 24", level: "impossible" },
  { slug: "borgward-isabella", name: "Borgward Isabella", level: "impossible" },
  { slug: "nsu-ro80", name: "NSU Ro 80", level: "impossible" },
  { slug: "iso-grifo", name: "Iso Grifo", level: "impossible" },
  { slug: "gordon-keeble", name: "Gordon-Keeble GK1", level: "impossible" },
  { slug: "jensen-interceptor", name: "Jensen Interceptor", level: "impossible" },
  { slug: "amphicar-770", name: "Amphicar 770", level: "impossible" },
  { slug: "stutz-blackhawk", name: "Stutz Blackhawk", level: "impossible" },
  { slug: "bricklin-sv1", name: "Bricklin SV-1", level: "impossible" },
  { slug: "matra-rancho", name: "Matra Rancho", level: "impossible" },
  { slug: "zaz-965", name: "ZAZ 965 Zaporozhets", level: "impossible" },
  { slug: "auburn-speedster", name: "Auburn Speedster", level: "impossible" },
];
