// «Guess the Cat Breed» — GuessSync · E34 · 100 سلالة (25/مستوى) · صور حقيقية من Wikimedia Commons
// مصنّفة بصعوبة حقيقية (شهرة عالمية): سهل (Persian/Siamese) ← مستحيل (Genetta/Suphalak/Owyhee Bob).
export const CATS = [
  // EASY (25) — household-name breeds
  { slug: "persian", name: "Persian", level: "easy" },
  { slug: "siamese", name: "Siamese", level: "easy" },
  { slug: "mainecoon", name: "Maine Coon", level: "easy" },
  { slug: "bengal", name: "Bengal", level: "easy" },
  { slug: "sphynx", name: "Sphynx", level: "easy" },
  { slug: "britishshorthair", name: "British Shorthair", level: "easy" },
  { slug: "ragdoll", name: "Ragdoll", level: "easy" },
  { slug: "scottishfold", name: "Scottish Fold", level: "easy" },
  { slug: "russianblue", name: "Russian Blue", level: "easy" },
  { slug: "abyssinian", name: "Abyssinian", level: "easy" },
  { slug: "americanshorthair", name: "American Shorthair", level: "easy" },
  { slug: "norwegianforest", name: "Norwegian Forest Cat", level: "easy" },
  { slug: "birman", name: "Birman", level: "easy" },
  { slug: "burmese", name: "Burmese", level: "easy" },
  { slug: "munchkin", name: "Munchkin", level: "easy" },
  { slug: "turkishangora", name: "Turkish Angora", level: "easy" },
  { slug: "himalayan", name: "Himalayan", level: "easy" },
  { slug: "manx", name: "Manx", level: "easy" },
  { slug: "exoticshorthair", name: "Exotic Shorthair", level: "easy" },
  { slug: "savannah", name: "Savannah", level: "easy" },
  { slug: "bombay", name: "Bombay", level: "easy" },
  { slug: "devonrex", name: "Devon Rex", level: "easy" },
  { slug: "cornishrex", name: "Cornish Rex", level: "easy" },
  { slug: "somali", name: "Somali", level: "easy" },
  { slug: "tonkinese", name: "Tonkinese", level: "easy" },
  // MEDIUM (25)
  { slug: "ocicat", name: "Ocicat", level: "medium" },
  { slug: "balinese", name: "Balinese", level: "medium" },
  { slug: "chartreux", name: "Chartreux", level: "medium" },
  { slug: "korat", name: "Korat", level: "medium" },
  { slug: "singapura", name: "Singapura", level: "medium" },
  { slug: "turkishvan", name: "Turkish Van", level: "medium" },
  { slug: "selkirkrex", name: "Selkirk Rex", level: "medium" },
  { slug: "laperm", name: "LaPerm", level: "medium" },
  { slug: "americancurl", name: "American Curl", level: "medium" },
  { slug: "japanesebobtail", name: "Japanese Bobtail", level: "medium" },
  { slug: "egyptianmau", name: "Egyptian Mau", level: "medium" },
  { slug: "siberian", name: "Siberian", level: "medium" },
  { slug: "ragamuffin", name: "Ragamuffin", level: "medium" },
  { slug: "orientalshorthair", name: "Oriental Shorthair", level: "medium" },
  { slug: "snowshoe", name: "Snowshoe", level: "medium" },
  { slug: "pixiebob", name: "Pixie-bob", level: "medium" },
  { slug: "toyger", name: "Toyger", level: "medium" },
  { slug: "nebelung", name: "Nebelung", level: "medium" },
  { slug: "cymric", name: "Cymric", level: "medium" },
  { slug: "chausie", name: "Chausie", level: "medium" },
  { slug: "havanabrown", name: "Havana Brown", level: "medium" },
  { slug: "burmilla", name: "Burmilla", level: "medium" },
  { slug: "peterbald", name: "Peterbald", level: "medium" },
  { slug: "donskoy", name: "Donskoy", level: "medium" },
  { slug: "lykoi", name: "Lykoi", level: "medium" },
  // HARD (25)
  { slug: "khaomanee", name: "Khao Manee", level: "hard" },
  { slug: "kurilianbobtail", name: "Kurilian Bobtail", level: "hard" },
  { slug: "americanwirehair", name: "American Wirehair", level: "hard" },
  { slug: "americanbobtail", name: "American Bobtail", level: "hard" },
  { slug: "colorpointshorthair", name: "Colorpoint Shorthair", level: "hard" },
  { slug: "europeanshorthair", name: "European Shorthair", level: "hard" },
  { slug: "germanrex", name: "German Rex", level: "hard" },
  { slug: "ukrainianlevkoy", name: "Ukrainian Levkoy", level: "hard" },
  { slug: "serengeti", name: "Serengeti", level: "hard" },
  { slug: "cheetoh", name: "Cheetoh", level: "hard" },
  { slug: "highlander", name: "Highlander", level: "hard" },
  { slug: "thai", name: "Thai", level: "hard" },
  { slug: "australianmist", name: "Australian Mist", level: "hard" },
  { slug: "sokoke", name: "Sokoke", level: "hard" },
  { slug: "arabianmau", name: "Arabian Mau", level: "hard" },
  { slug: "aegean", name: "Aegean", level: "hard" },
  { slug: "brazilianshorthair", name: "Brazilian Shorthair", level: "hard" },
  { slug: "californiaspangled", name: "California Spangled", level: "hard" },
  { slug: "minuet", name: "Minuet", level: "hard" },
  { slug: "mekongbobtail", name: "Mekong Bobtail", level: "hard" },
  { slug: "ojosazules", name: "Ojos Azules", level: "hard" },
  { slug: "kanaani", name: "Kanaani", level: "hard" },
  { slug: "nevamasquerade", name: "Neva Masquerade", level: "hard" },
  { slug: "yorkchocolate", name: "York Chocolate", level: "hard" },
  { slug: "chantillytiffany", name: "Chantilly-Tiffany", level: "hard" },
  // IMPOSSIBLE (25) — experimental / ultra-rare
  { slug: "elf", name: "Elf", level: "impossible" },
  { slug: "lihua", name: "Dragon Li", level: "impossible" },
  { slug: "bambino", name: "Bambino", level: "impossible" },
  { slug: "minskin", name: "Minskin", level: "impossible" },
  { slug: "genetta", name: "Genetta", level: "impossible" },
  { slug: "uralrex", name: "Ural Rex", level: "impossible" },
  { slug: "seychellois", name: "Seychellois", level: "impossible" },
  { slug: "foldex", name: "Foldex", level: "impossible" },
  { slug: "kinkalow", name: "Kinkalow", level: "impossible" },
  { slug: "toybob", name: "Toybob", level: "impossible" },
  { slug: "karelianbobtail", name: "Karelian Bobtail", level: "impossible" },
  { slug: "aphrodite", name: "Aphrodite Giant", level: "impossible" },
  { slug: "suphalak", name: "Suphalak", level: "impossible" },
  { slug: "britishlonghair", name: "British Longhair", level: "impossible" },
  { slug: "serradepetit", name: "Serrade Petit", level: "impossible" },
  { slug: "raas", name: "Raas", level: "impossible" },
  { slug: "owyheebob", name: "Owyhee Bob", level: "impossible" },
  { slug: "chinchilla", name: "Chinchilla Longhair", level: "impossible" },
  { slug: "javanese", name: "Javanese", level: "impossible" },
  { slug: "orientallonghair", name: "Oriental Longhair", level: "impossible" },
  { slug: "americanringtail", name: "American Ringtail", level: "impossible" },
  { slug: "tiffanie", name: "Tiffanie", level: "impossible" },
  { slug: "poodlecat", name: "Poodle Cat", level: "impossible" },
  { slug: "asianshorthair", name: "Asian", level: "impossible" },
  { slug: "foreignwhite", name: "Foreign White", level: "impossible" },
];
