// «Guess the Cat» v2 — GuessSync · E-cats2 · did-you-know facts, ≤70 chars each, verified true.
export const CATS2_FACTS = {
  // EASY
  "blackcat": "Solid black coats come from a dominant melanism gene",
  "whitecat": "Many white cats with blue eyes are deaf in that ear",
  "tabbycat": "The 'M' mark on the forehead is the classic tabby sign",
  "calicocat": "Tri-colour calicoes are almost always female",
  "tuxedocat": "A bicolour pattern of black with white chest and paws",
  "gingercat": "About four in five ginger cats are male",
  "tortoiseshellcat": "Mottled black-and-red coat, nearly always female",
  "greycat": "A solid blue-grey coat is a diluted form of black",
  "orangetabby": "Its orange colour is carried on the X chromosome",
  "bicolorcat": "Any coat colour paired with clear patches of white",
  "sealpointsiamese": "Dark brown points, the original classic Siamese colour",
  "bluepointsiamese": "A dilute Siamese with soft blue-grey points",
  "flamepointsiamese": "A red-point Siamese with warm orange ears and face",
  "bluepersian": "A solid blue-grey Persian once loved by Queen Victoria",
  "whitepersian": "A pure white Persian with a flat face and round eyes",
  "blackpersian": "A glossy solid-black long-haired Persian",
  "calicopersian": "A Persian in the tri-colour calico pattern",
  "sealpointragdoll": "A Ragdoll with dark seal-brown points and blue eyes",
  "bluepointragdoll": "A Ragdoll with soft grey-blue points and blue eyes",
  "mittedragdoll": "A Ragdoll with white 'mittens' on all four paws",
  "britishblue": "The solid blue-grey British Shorthair, a plush teddy",
  "tabbymainecoon": "The brown tabby is the classic Maine Coon look",
  "silvertabby": "A pale silver ground coat with dark tabby stripes",
  "smokecat": "Looks solid but the hair roots are white, not coloured",
  "torbiecat": "A tortoiseshell cat that also carries tabby stripes",
  // MEDIUM
  "lynxpointsiamese": "A Siamese whose points carry faint tabby stripes",
  "chocolatepointsiamese": "A Siamese with warm milk-chocolate points",
  "lilacpointsiamese": "A Siamese with pale frosty grey-pink points",
  "tortiepointsiamese": "A Siamese with mottled tortoiseshell points",
  "redpersian": "A rich solid-red long-haired Persian",
  "creampersian": "A pale cream Persian, the dilute form of red",
  "silverpersian": "A silver Persian with black-tipped guard hairs",
  "goldenpersian": "A warm golden coat with a green-eyed Persian face",
  "tabbypersian": "A long-haired Persian in a classic tabby pattern",
  "smokepersian": "A Persian that looks solid until the coat parts to white",
  "bicolorragdoll": "A Ragdoll with an inverted white 'V' on the face",
  "lynxragdoll": "A Ragdoll whose points show tabby lynx striping",
  "sealpointbirman": "A Birman with seal points and pure white gloved paws",
  "bluepointbirman": "A Birman with blue points and white gloved paws",
  "silvermainecoon": "A Maine Coon with a shimmering silver tabby coat",
  "smokemainecoon": "A Maine Coon whose coat hides a white undercoat",
  "redmainecoon": "A large Maine Coon in solid or tabby red",
  "britishsilvertabby": "A British Shorthair in a crisp silver tabby coat",
  "britishcream": "A pale cream British Shorthair with a dense coat",
  "colorpointbritish": "A British Shorthair with Siamese-style dark points",
  "mackereltabby": "A tabby with narrow parallel stripes like fish bones",
  "classictabby": "A tabby with bold swirls and a bullseye on the flank",
  "spottedtabby": "A tabby whose stripes break up into rounded spots",
  "harlequincat": "A mostly white cat with a few large colour patches",
  "blueeyedwhite": "A white cat carrying two striking blue eyes",
  // HARD
  "chocolateragdoll": "A Ragdoll with warm chocolate-brown points",
  "lilacragdoll": "A Ragdoll with pale pinkish-grey lilac points",
  "flameragdoll": "A Ragdoll with bright red-orange points",
  "creampointragdoll": "A Ragdoll with pale creamy-orange points",
  "colorpointragdoll": "A Ragdoll with dark points and no white markings",
  "chocolatepointbirman": "A Birman with chocolate points and white gloves",
  "lilacpointbirman": "A Birman with frosty lilac points and white gloves",
  "redpointbirman": "A Birman with red-orange points and white gloves",
  "tabbypointbirman": "A Birman whose points show faint tabby striping",
  "shadedsilverpersian": "A Persian with dark shading tipping a white coat",
  "tortiepersian": "A Persian in the mottled black-and-red tortie coat",
  "bluecreampersian": "A Persian mottled in soft blue and cream",
  "pekefacepersian": "An ultra-flat-faced red Persian named after the Peke",
  "bicolorpersian": "A Persian with clear white patches over a colour",
  "tickedtabby": "A tabby whose stripes show only on the face and legs",
  "browntabby": "The most common tabby, brown-black stripes on tawny",
  "bluetabby": "A tabby whose stripes are a diluted blue-grey",
  "creamtabby": "A tabby in the palest dilute cream shade",
  "patchedtabby": "A tabby broken by red or cream tortoiseshell patches",
  "blacksmoke": "Looks solid black until the white undercoat shows",
  "redsmoke": "A red cat over a white undercoat, pale at the roots",
  "tabbywhite": "A tabby cat broken up with clear patches of white",
  "cypruscat": "An ancient large landrace cat from the island of Cyprus",
  "vanbicolor": "White cat with colour only on the head and tail",
  "dilutecalico": "A calico in soft blue and cream instead of black and red",
  // IMPOSSIBLE
  "chocolatetabby": "A tabby whose stripes are warm chocolate brown",
  "greytabby": "A tabby in cool grey tones rather than brown",
  "marbledtabby": "A tabby whose swirls smear into a marbled pattern",
  "cinnamontabby": "A tabby in a warm reddish cinnamon-brown shade",
  "bluecreampoint": "A cat with mottled blue-and-cream tortie points",
  "sealtortiepoint": "A cat with mottled seal-and-red tortoiseshell points",
  "chocolatebicolor": "A chocolate-brown cat with clear white patches",
  "bluebicolor": "A blue-grey cat with clear white patches",
  "redbicolor": "A red cat with clear white patches, ginger and white",
  "caramelpoint": "A cool-toned brownish point shade caused by a modifier",
  "fawnpoint": "The palest dilute of cinnamon, a warm pinkish point",
  "cinnamonpoint": "A warm reddish-brown point lighter than chocolate",
  "chocolatetortie": "A tortoiseshell mixing chocolate brown and red",
  "lilactortie": "A dilute tortie mixing pale lilac and cream",
  "bluetortie": "A dilute tortie of blue-grey mottled with cream",
  "apricotcat": "A warm pinkish-cream coat, a dilute of cinnamon",
  "bluesmoke": "A blue-grey cat over a white undercoat",
  "silvertorbie": "A silver tabby also carrying tortoiseshell patches",
  "dilutetortie": "A tortoiseshell in soft blue and cream tones",
  "calibycat": "A cat that is both calico and tabby at once",
  "cinnamonoriental": "A sleek Oriental in a warm cinnamon-brown coat",
  "fawnoriental": "A sleek Oriental in the palest dilute fawn shade",
  "chocolatepersian": "A rich solid milk-chocolate long-haired Persian",
  "lilacpersian": "A Persian in a pale frosty pinkish-grey lilac",
  "shadedgolden": "A golden coat lightly tipped in black at the ends",
};
