// «Guess the Cheese» — GuessSync · E60 · did-you-know facts, ≤70 chars, verified true.
export const CHEESE_FACTS = {
  // EASY
  "cheddar": "English cow's-milk cheese, aged and often sharp in flavour",
  "mozzarella": "Italian fresh cheese, traditionally from buffalo milk",
  "parmesan": "Hard Italian cheese aged at least 12 months; cow's milk",
  "brie": "Soft French cow's-milk cheese with an edible white rind",
  "gouda": "Dutch cow's-milk cheese named after the town of Gouda",
  "feta": "Greek brined cheese made from sheep and goat milk",
  "emmental": "Swiss cow's-milk cheese famous for its large holes",
  "bluecheese": "Cheese veined with blue mould; sharp and salty",
  "camembert": "Soft cow's-milk cheese from Normandy, France",
  "creamcheese": "Soft, mild fresh cheese made from milk and cream",
  "ricotta": "Italian whey cheese; its name means 'recooked'",
  "cottagecheese": "Fresh, lumpy curd cheese with a mild flavour",
  "halloumi": "Cypriot cheese with a high melting point; great grilled",
  "gruyere": "Swiss cow's-milk cheese from the town of Gruyères",
  "provolone": "Italian stretched-curd cheese, aged and often smoked",
  "montereyjack": "Mild semi-hard cheese from Monterey, California",
  "mascarpone": "Italian cream cheese used to make tiramisu",
  "colby": "Mild American cheese, like a moister cheddar",
  "edam": "Dutch cheese sold in balls coated with red wax",
  "pepperjack": "Monterey Jack cheese spiced with hot peppers",
  "paneer": "Fresh non-melting cheese common in South Asian food",
  "burrata": "Italian mozzarella shell filled with soft cream",
  "roquefort": "French blue cheese made from sheep's milk in caves",
  "manchego": "Spanish sheep's-milk cheese from La Mancha",
  "gorgonzola": "Italian blue cheese made from cow's milk",
  // MEDIUM
  "havarti": "Danish semi-soft cow's-milk cheese, buttery and mild",
  "muenster": "Mild American cheese with an orange edible rind",
  "fontina": "Italian cow's-milk cheese from the Aosta Valley",
  "pecorinoromano": "Hard, salty Italian cheese made from sheep's milk",
  "comte": "French cow's-milk cheese from the Jura mountains",
  "jarlsberg": "Norwegian cheese with holes, mild and nutty",
  "wensleydale": "Crumbly English cheese made in Yorkshire",
  "redleicester": "Orange English cheese coloured with annatto",
  "doublegloucester": "Full-flavoured orange English cow's-milk cheese",
  "asiago": "Italian cow's-milk cheese from the Veneto region",
  "taleggio": "Italian washed-rind cheese with a strong aroma",
  "granapadano": "Hard Italian grating cheese, similar to Parmesan",
  "reblochon": "French soft cheese from Savoy, made from cow's milk",
  "morbier": "French cheese with a thin ash line through the middle",
  "cheshire": "One of England's oldest cheeses; crumbly and salty",
  "caerphilly": "Crumbly white cheese originally from Wales",
  "stilton": "English blue cheese protected by law; from cow's milk",
  "boursin": "French soft cheese flavoured with garlic and herbs",
  "quesofresco": "Fresh, mild Mexican cheese that does not melt",
  "oaxaca": "Mexican stretched-curd cheese wound into a ball",
  "cotija": "Hard, salty Mexican cheese named after a town",
  "raclette": "Swiss cheese melted and scraped onto food",
  "portsalut": "French semi-soft cheese with an orange rind",
  "labneh": "Middle Eastern strained-yogurt cheese, soft and tangy",
  "quark": "Fresh German curd cheese, soft and mild",
  // HARD
  "beaufort": "French Alpine cheese from the Savoie region",
  "cantal": "One of France's oldest cheeses, from Auvergne",
  "saintnectaire": "French semi-soft cheese from the Auvergne region",
  "tommedesavoie": "Mild French mountain cheese with a grey rind",
  "ossauiraty": "French sheep's-milk cheese from the Pyrenees",
  "livarot": "Pungent French washed-rind cheese from Normandy",
  "pontleveque": "Soft French cheese from Normandy, square in shape",
  "chaource": "Soft French cheese from the Champagne region",
  "banon": "French goat cheese wrapped in chestnut leaves",
  "sellessurcher": "French goat cheese coated in edible ash",
  "crottin": "Small French goat cheese from Chavignol",
  "valencay": "French goat cheese shaped like a flat-topped pyramid",
  "gjetost": "Norwegian brown whey cheese with a sweet taste",
  "idiazabal": "Spanish sheep's-milk cheese from the Basque Country",
  "cabrales": "Spanish blue cheese matured in mountain caves",
  "mahon": "Spanish cow's-milk cheese from the island of Menorca",
  "tetilla": "Galician cheese shaped like a small breast",
  "caciocavallo": "Italian stretched-curd cheese hung in pairs to age",
  "scamorza": "Italian cheese like mozzarella, often smoked",
  "robiola": "Soft Italian cheese from the Piedmont region",
  "pecorinosardo": "Sardinian cheese made from sheep's milk",
  "belpaese": "Mild Italian cow's-milk cheese created in 1906",
  "limburger": "Strong-smelling cheese of Belgian origin",
  "tilsit": "Semi-hard cheese first made in Tilsit, Prussia",
  "appenzeller": "Swiss cheese cured with a secret herbal brine",
  // IMPOSSIBLE
  "casumarzu": "Sardinian sheep cheese containing live insect larvae",
  "vacherin": "Soft French/Swiss cheese sold in a wooden box",
  "tetedemoine": "Swiss cheese shaved into rosettes with a girolle",
  "mimolette": "French cheese with a bright orange, ball-shaped body",
  "stinkingbishop": "Pungent English washed-rind cheese from Gloucester",
  "leipajuusto": "Finnish 'bread cheese' that squeaks when eaten",
  "sulguni": "Georgian brined cheese with an elastic texture",
  "bandel": "Smoked cheese from West Bengal, India",
  "rubing": "Fresh goat cheese from Yunnan, China",
  "oscypek": "Polish smoked sheep cheese from the Tatra Mountains",
  "bryndza": "Soft sheep's-milk cheese from Slovakia",
  "korbacik": "Slovak string cheese braided by hand",
  "nabulsi": "Palestinian brined cheese from the city of Nablus",
  "shanklish": "Levantine cheese rolled into herb-covered balls",
  "chechil": "Armenian string cheese sold in braided bundles",
  "graviera": "Greek cow or sheep cheese similar to Gruyère",
  "anari": "Cypriot whey cheese similar to ricotta",
  "vastedda": "Sicilian stretched-curd cheese from sheep's milk",
  "olomouc": "Pungent Czech ripened cheese, very low in fat",
  "fossa": "Italian cheese aged in pits dug into rock",
  "puzzone": "Pungent Italian washed-rind cheese from Trentino",
  "bitto": "Italian Alpine cheese that can age for many years",
  "castelmagno": "Ancient semi-hard cheese from Piedmont, Italy",
  "gamalost": "Pungent Norwegian cheese made from sour milk",
  "harzer": "German sour-milk cheese, low in fat and pungent",
};
