// «Guess the Cheese» — GuessSync · E60 · 100 cheeses (25/tier) · real photos from Wikimedia Commons
// Tiered by global recognizability: easy (Cheddar/Mozzarella) → impossible (Casu Marzu/Gamalost).
export const CHEESES = [
  // EASY (25) — household-name cheeses
  { slug: "cheddar", name: "Cheddar", level: "easy" },
  { slug: "mozzarella", name: "Mozzarella", level: "easy" },
  { slug: "parmesan", name: "Parmesan", level: "easy" },
  { slug: "brie", name: "Brie", level: "easy" },
  { slug: "gouda", name: "Gouda", level: "easy" },
  { slug: "feta", name: "Feta", level: "easy" },
  { slug: "emmental", name: "Swiss (Emmental)", level: "easy" },
  { slug: "bluecheese", name: "Blue Cheese", level: "easy" },
  { slug: "camembert", name: "Camembert", level: "easy" },
  { slug: "creamcheese", name: "Cream Cheese", level: "easy" },
  { slug: "ricotta", name: "Ricotta", level: "easy" },
  { slug: "cottagecheese", name: "Cottage Cheese", level: "easy" },
  { slug: "halloumi", name: "Halloumi", level: "easy" },
  { slug: "gruyere", name: "Gruyère", level: "easy" },
  { slug: "provolone", name: "Provolone", level: "easy" },
  { slug: "montereyjack", name: "Monterey Jack", level: "easy" },
  { slug: "mascarpone", name: "Mascarpone", level: "easy" },
  { slug: "colby", name: "Colby", level: "easy" },
  { slug: "edam", name: "Edam", level: "easy" },
  { slug: "pepperjack", name: "Pepper Jack", level: "easy" },
  { slug: "paneer", name: "Paneer", level: "easy" },
  { slug: "burrata", name: "Burrata", level: "easy" },
  { slug: "roquefort", name: "Roquefort", level: "easy" },
  { slug: "manchego", name: "Manchego", level: "easy" },
  { slug: "gorgonzola", name: "Gorgonzola", level: "easy" },
  // MEDIUM (25)
  { slug: "havarti", name: "Havarti", level: "medium" },
  { slug: "muenster", name: "Muenster", level: "medium" },
  { slug: "fontina", name: "Fontina", level: "medium" },
  { slug: "pecorinoromano", name: "Pecorino Romano", level: "medium" },
  { slug: "comte", name: "Comté", level: "medium" },
  { slug: "jarlsberg", name: "Jarlsberg", level: "medium" },
  { slug: "wensleydale", name: "Wensleydale", level: "medium" },
  { slug: "redleicester", name: "Red Leicester", level: "medium" },
  { slug: "doublegloucester", name: "Double Gloucester", level: "medium" },
  { slug: "asiago", name: "Asiago", level: "medium" },
  { slug: "taleggio", name: "Taleggio", level: "medium" },
  { slug: "granapadano", name: "Grana Padano", level: "medium" },
  { slug: "reblochon", name: "Reblochon", level: "medium" },
  { slug: "morbier", name: "Morbier", level: "medium" },
  { slug: "cheshire", name: "Cheshire", level: "medium" },
  { slug: "caerphilly", name: "Caerphilly", level: "medium" },
  { slug: "stilton", name: "Stilton", level: "medium" },
  { slug: "boursin", name: "Boursin", level: "medium" },
  { slug: "quesofresco", name: "Queso Fresco", level: "medium" },
  { slug: "oaxaca", name: "Oaxaca", level: "medium" },
  { slug: "cotija", name: "Cotija", level: "medium" },
  { slug: "raclette", name: "Raclette", level: "medium" },
  { slug: "portsalut", name: "Port Salut", level: "medium" },
  { slug: "labneh", name: "Labneh", level: "medium" },
  { slug: "quark", name: "Quark", level: "medium" },
  // HARD (25)
  { slug: "beaufort", name: "Beaufort", level: "hard" },
  { slug: "cantal", name: "Cantal", level: "hard" },
  { slug: "saintnectaire", name: "Saint-Nectaire", level: "hard" },
  { slug: "tommedesavoie", name: "Tomme de Savoie", level: "hard" },
  { slug: "ossauiraty", name: "Ossau-Iraty", level: "hard" },
  { slug: "livarot", name: "Livarot", level: "hard" },
  { slug: "pontleveque", name: "Pont-l'Évêque", level: "hard" },
  { slug: "chaource", name: "Chaource", level: "hard" },
  { slug: "banon", name: "Banon", level: "hard" },
  { slug: "sellessurcher", name: "Selles-sur-Cher", level: "hard" },
  { slug: "crottin", name: "Crottin de Chavignol", level: "hard" },
  { slug: "valencay", name: "Valençay", level: "hard" },
  { slug: "gjetost", name: "Gjetost (Brunost)", level: "hard" },
  { slug: "idiazabal", name: "Idiazábal", level: "hard" },
  { slug: "cabrales", name: "Cabrales", level: "hard" },
  { slug: "mahon", name: "Mahón", level: "hard" },
  { slug: "tetilla", name: "Tetilla", level: "hard" },
  { slug: "caciocavallo", name: "Caciocavallo", level: "hard" },
  { slug: "scamorza", name: "Scamorza", level: "hard" },
  { slug: "robiola", name: "Robiola", level: "hard" },
  { slug: "pecorinosardo", name: "Pecorino Sardo", level: "hard" },
  { slug: "belpaese", name: "Bel Paese", level: "hard" },
  { slug: "limburger", name: "Limburger", level: "hard" },
  { slug: "tilsit", name: "Tilsit", level: "hard" },
  { slug: "appenzeller", name: "Appenzeller", level: "hard" },
  // IMPOSSIBLE (25) — obscure regional cheeses
  { slug: "casumarzu", name: "Casu Marzu", level: "impossible" },
  { slug: "vacherin", name: "Vacherin Mont d'Or", level: "impossible" },
  { slug: "tetedemoine", name: "Tête de Moine", level: "impossible" },
  { slug: "mimolette", name: "Mimolette", level: "impossible" },
  { slug: "stinkingbishop", name: "Stinking Bishop", level: "impossible" },
  { slug: "leipajuusto", name: "Leipäjuusto", level: "impossible" },
  { slug: "sulguni", name: "Sulguni", level: "impossible" },
  { slug: "bandel", name: "Bandel", level: "impossible" },
  { slug: "rubing", name: "Rubing", level: "impossible" },
  { slug: "oscypek", name: "Oscypek", level: "impossible" },
  { slug: "bryndza", name: "Bryndza", level: "impossible" },
  { slug: "korbacik", name: "Korbáčik", level: "impossible" },
  { slug: "nabulsi", name: "Nabulsi", level: "impossible" },
  { slug: "shanklish", name: "Shanklish", level: "impossible" },
  { slug: "chechil", name: "Chechil", level: "impossible" },
  { slug: "graviera", name: "Graviera", level: "impossible" },
  { slug: "anari", name: "Anari", level: "impossible" },
  { slug: "vastedda", name: "Vastedda", level: "impossible" },
  { slug: "olomouc", name: "Olomoucké Tvarůžky", level: "impossible" },
  { slug: "fossa", name: "Formaggio di Fossa", level: "impossible" },
  { slug: "puzzone", name: "Puzzone di Moena", level: "impossible" },
  { slug: "bitto", name: "Bitto", level: "impossible" },
  { slug: "castelmagno", name: "Castelmagno", level: "impossible" },
  { slug: "gamalost", name: "Gamalost", level: "impossible" },
  { slug: "harzer", name: "Harzer", level: "impossible" },
];
