// E148 «Guess the City by Emoji» — 100 world cities · 25/tier · clue = plain Unicode emoji (mirrors emoji rendering)
// Each city keyed to its globally-recognized landmark/symbol. No flags, no Israel cities. VO: sfx/e148-<id>.wav
export const CITY_EMOJI = [
  // ===== EASY (25) =====
  { id: "paris", title: "Paris", emojis: "🗼🥐", level: "easy" },
  { id: "london", title: "London", emojis: "🎡🕰", level: "easy" },
  { id: "new-york", title: "New York", emojis: "🗽🍎", level: "easy" },
  { id: "rome", title: "Rome", emojis: "🏛🐺", level: "easy" },
  { id: "cairo", title: "Cairo", emojis: "🐫🔺", level: "easy" },
  { id: "sydney", title: "Sydney", emojis: "🌉🌊", level: "easy" },
  { id: "rio-de-janeiro", title: "Rio de Janeiro", emojis: "🎉⛰", level: "easy" },
  { id: "moscow", title: "Moscow", emojis: "🏰⛄", level: "easy" },
  { id: "tokyo", title: "Tokyo", emojis: "🌸🍣", level: "easy" },
  { id: "amsterdam", title: "Amsterdam", emojis: "🚲🌷", level: "easy" },
  { id: "venice", title: "Venice", emojis: "🚤🎭", level: "easy" },
  { id: "athens", title: "Athens", emojis: "🏛🦉", level: "easy" },
  { id: "dubai", title: "Dubai", emojis: "🏜🏙", level: "easy" },
  { id: "beijing", title: "Beijing", emojis: "🏯🐼", level: "easy" },
  { id: "agra", title: "Agra", emojis: "🕌🤍", level: "easy" },
  { id: "singapore", title: "Singapore", emojis: "🦁🌊", level: "easy" },
  { id: "los-angeles", title: "Los Angeles", emojis: "🎬🌴", level: "easy" },
  { id: "las-vegas", title: "Las Vegas", emojis: "🎰🎲", level: "easy" },
  { id: "barcelona", title: "Barcelona", emojis: "⛪🎨", level: "easy" },
  { id: "mecca", title: "Mecca", emojis: "🕋🕌", level: "easy" },
  { id: "san-francisco", title: "San Francisco", emojis: "🌉🚋", level: "easy" },
  { id: "istanbul", title: "Istanbul", emojis: "🕌🧿", level: "easy" },
  { id: "vienna", title: "Vienna", emojis: "🎻🎼", level: "easy" },
  { id: "munich", title: "Munich", emojis: "🍺🥨", level: "easy" },
  { id: "honolulu", title: "Honolulu", emojis: "🌺🏄", level: "easy" },
  // ===== MEDIUM (25) =====
  { id: "pisa", title: "Pisa", emojis: "🏛↗", level: "medium" },
  { id: "berlin", title: "Berlin", emojis: "🐻🧱", level: "medium" },
  { id: "lisbon", title: "Lisbon", emojis: "🚊🌊", level: "medium" },
  { id: "prague", title: "Prague", emojis: "🏰🍺", level: "medium" },
  { id: "dublin", title: "Dublin", emojis: "🍀🍺", level: "medium" },
  { id: "nashville", title: "Nashville", emojis: "🎸🤠", level: "medium" },
  { id: "new-orleans", title: "New Orleans", emojis: "🎷⚜", level: "medium" },
  { id: "madrid", title: "Madrid", emojis: "🐻🍓", level: "medium" },
  { id: "seville", title: "Seville", emojis: "💃🍊", level: "medium" },
  { id: "milan", title: "Milan", emojis: "👗⛪", level: "medium" },
  { id: "naples", title: "Naples", emojis: "🍕🌋", level: "medium" },
  { id: "florence", title: "Florence", emojis: "🎨⚜", level: "medium" },
  { id: "copenhagen", title: "Copenhagen", emojis: "🧜🚲", level: "medium" },
  { id: "brussels", title: "Brussels", emojis: "🧇🍫", level: "medium" },
  { id: "zurich", title: "Zurich", emojis: "🏦🏔", level: "medium" },
  { id: "geneva", title: "Geneva", emojis: "⛲🏔", level: "medium" },
  { id: "monaco", title: "Monaco", emojis: "🏎🎰", level: "medium" },
  { id: "buenos-aires", title: "Buenos Aires", emojis: "💃🥩", level: "medium" },
  { id: "mexico-city", title: "Mexico City", emojis: "🦅🌵", level: "medium" },
  { id: "toronto", title: "Toronto", emojis: "🗼🍁", level: "medium" },
  { id: "vancouver", title: "Vancouver", emojis: "🚠🌲", level: "medium" },
  { id: "seattle", title: "Seattle", emojis: "☕🗼", level: "medium" },
  { id: "chicago", title: "Chicago", emojis: "🌆🌭", level: "medium" },
  { id: "boston", title: "Boston", emojis: "⚾🫖", level: "medium" },
  { id: "miami", title: "Miami", emojis: "🌴🦩", level: "medium" },
  // ===== HARD (25) =====
  { id: "jaipur", title: "Jaipur", emojis: "🐘👑", level: "hard" },
  { id: "marrakesh", title: "Marrakesh", emojis: "🐪🕌", level: "hard" },
  { id: "petra", title: "Petra", emojis: "🏛🏜", level: "hard" },
  { id: "santorini", title: "Santorini", emojis: "⛪🌅", level: "hard" },
  { id: "dubrovnik", title: "Dubrovnik", emojis: "🏰🌊", level: "hard" },
  { id: "reykjavik", title: "Reykjavik", emojis: "🌋♨", level: "hard" },
  { id: "nairobi", title: "Nairobi", emojis: "🦁🦒", level: "hard" },
  { id: "cape-town", title: "Cape Town", emojis: "🏔🐧", level: "hard" },
  { id: "bangkok", title: "Bangkok", emojis: "🛺🐘", level: "hard" },
  { id: "hanoi", title: "Hanoi", emojis: "🛵🍜", level: "hard" },
  { id: "kyoto", title: "Kyoto", emojis: "⛩🍵", level: "hard" },
  { id: "seoul", title: "Seoul", emojis: "🏯🌶", level: "hard" },
  { id: "shanghai", title: "Shanghai", emojis: "🌃🥟", level: "hard" },
  { id: "hong-kong", title: "Hong Kong", emojis: "🌃🚋", level: "hard" },
  { id: "delhi", title: "Delhi", emojis: "🛕🛺", level: "hard" },
  { id: "varanasi", title: "Varanasi", emojis: "🛕🌊", level: "hard" },
  { id: "helsinki", title: "Helsinki", emojis: "🧖⛪", level: "hard" },
  { id: "oslo", title: "Oslo", emojis: "🛳🏔", level: "hard" },
  { id: "stockholm", title: "Stockholm", emojis: "👑🏝", level: "hard" },
  { id: "bruges", title: "Bruges", emojis: "🦢🍫", level: "hard" },
  { id: "salzburg", title: "Salzburg", emojis: "🎻🏰", level: "hard" },
  { id: "edinburgh", title: "Edinburgh", emojis: "🏰🎇", level: "hard" },
  { id: "quebec-city", title: "Quebec City", emojis: "🏰⚜", level: "hard" },
  { id: "cusco", title: "Cusco", emojis: "🏔🦙", level: "hard" },
  { id: "marseille", title: "Marseille", emojis: "⚓🥘", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { id: "timbuktu", title: "Timbuktu", emojis: "🕌🐫", level: "impossible" },
  { id: "samarkand", title: "Samarkand", emojis: "🕌🌟", level: "impossible" },
  { id: "bukhara", title: "Bukhara", emojis: "🕌🧵", level: "impossible" },
  { id: "lhasa", title: "Lhasa", emojis: "🛕🏔", level: "impossible" },
  { id: "kathmandu", title: "Kathmandu", emojis: "🐒🛕", level: "impossible" },
  { id: "fez", title: "Fez", emojis: "🕌🎨", level: "impossible" },
  { id: "isfahan", title: "Isfahan", emojis: "🕌🌉", level: "impossible" },
  { id: "luang-prabang", title: "Luang Prabang", emojis: "🛕🌅", level: "impossible" },
  { id: "ushuaia", title: "Ushuaia", emojis: "🐧🚢", level: "impossible" },
  { id: "hoi-an", title: "Hoi An", emojis: "🏮🌊", level: "impossible" },
  { id: "valletta", title: "Valletta", emojis: "⚓🏰", level: "impossible" },
  { id: "bergen", title: "Bergen", emojis: "🐟🏔", level: "impossible" },
  { id: "tallinn", title: "Tallinn", emojis: "🏰🌲", level: "impossible" },
  { id: "riga", title: "Riga", emojis: "⛪🌊", level: "impossible" },
  { id: "vilnius", title: "Vilnius", emojis: "⛪🎈", level: "impossible" },
  { id: "antigua-guatemala", title: "Antigua", emojis: "⛪🌋", level: "impossible" },
  { id: "cartagena", title: "Cartagena", emojis: "🏰🌴", level: "impossible" },
  { id: "zanzibar", title: "Zanzibar", emojis: "🏝🌶", level: "impossible" },
  { id: "guilin", title: "Guilin", emojis: "🏞🎋", level: "impossible" },
  { id: "pokhara", title: "Pokhara", emojis: "🏔🪂", level: "impossible" },
  { id: "chefchaouen", title: "Chefchaouen", emojis: "🏘🎨", level: "impossible" },
  { id: "hallstatt", title: "Hallstatt", emojis: "🏔🦢", level: "impossible" },
  { id: "pamplona", title: "Pamplona", emojis: "🐂🎉", level: "impossible" },
  { id: "bath", title: "Bath", emojis: "♨🏛", level: "impossible" },
  { id: "mostar", title: "Mostar", emojis: "🌉🏊", level: "impossible" },
];
