// E219 «Guess the City by Emoji 2» — 100 cities · 25/tier
// VO: sfx/e219-<id>.wav
export const CITY_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "osaka", title: "Osaka", emojis: "🏯🐙", level: "easy" },
  { id: "havana", title: "Havana", emojis: "🚗🎺", level: "easy" },
  { id: "warsaw", title: "Warsaw", emojis: "🧜🏰", level: "easy" },
  { id: "budapest", title: "Budapest", emojis: "🛁⛪", level: "easy" },
  { id: "kuala-lumpur", title: "Kuala Lumpur", emojis: "🏙🌴", level: "easy" },
  { id: "mumbai", title: "Mumbai", emojis: "🚕🎥", level: "easy" },
  { id: "melbourne", title: "Melbourne", emojis: "☕🎨", level: "easy" },
  { id: "auckland", title: "Auckland", emojis: "⛵🌋", level: "easy" },
  { id: "doha", title: "Doha", emojis: "🐪🏙", level: "easy" },
  { id: "casablanca", title: "Casablanca", emojis: "🕌🎥", level: "easy" },
  { id: "johannesburg", title: "Johannesburg", emojis: "⛏💎", level: "easy" },
  { id: "lima", title: "Lima", emojis: "🦙🌊", level: "easy" },
  { id: "bogota", title: "Bogota", emojis: "🚠☕", level: "easy" },
  { id: "santiago", title: "Santiago", emojis: "🍷🏔", level: "easy" },
  { id: "quito", title: "Quito", emojis: "🌋🏛", level: "easy" },
  { id: "panama-city", title: "Panama City", emojis: "⚓🌉", level: "easy" },
  { id: "montreal", title: "Montreal", emojis: "🥯❄", level: "easy" },
  { id: "washington", title: "Washington", emojis: "🏛🦅", level: "easy" },
  { id: "philadelphia", title: "Philadelphia", emojis: "🔔🥪", level: "easy" },
  { id: "orlando", title: "Orlando", emojis: "🎢🐭", level: "easy" },
  { id: "st-petersburg", title: "St. Petersburg", emojis: "🏛❄", level: "easy" },
  { id: "kyiv", title: "Kyiv", emojis: "⛪🌻", level: "easy" },
  { id: "manila", title: "Manila", emojis: "🚌🌴", level: "easy" },
  { id: "jakarta", title: "Jakarta", emojis: "🕌🏙", level: "easy" },
  { id: "riyadh", title: "Riyadh", emojis: "🐪🏜", level: "easy" },
  // ===== MEDIUM (25) =====
  { id: "krakow", title: "Krakow", emojis: "🐉🏰", level: "medium" },
  { id: "bratislava", title: "Bratislava", emojis: "🏰🌉", level: "medium" },
  { id: "ljubljana", title: "Ljubljana", emojis: "🐉🌉", level: "medium" },
  { id: "zagreb", title: "Zagreb", emojis: "⛪🎄", level: "medium" },
  { id: "belgrade", title: "Belgrade", emojis: "🏰🎉", level: "medium" },
  { id: "sofia", title: "Sofia", emojis: "⛪🌹", level: "medium" },
  { id: "bucharest", title: "Bucharest", emojis: "🏛🌳", level: "medium" },
  { id: "gothenburg", title: "Gothenburg", emojis: "⚓🎡", level: "medium" },
  { id: "trondheim", title: "Trondheim", emojis: "⛪❄", level: "medium" },
  { id: "ottawa", title: "Ottawa", emojis: "🍁🏛", level: "medium" },
  { id: "calgary", title: "Calgary", emojis: "🤠🐎", level: "medium" },
  { id: "winnipeg", title: "Winnipeg", emojis: "🚂❄", level: "medium" },
  { id: "portland", title: "Portland", emojis: "🚲🌲", level: "medium" },
  { id: "denver", title: "Denver", emojis: "🏔🦬", level: "medium" },
  { id: "austin", title: "Austin", emojis: "🎸🦇", level: "medium" },
  { id: "detroit", title: "Detroit", emojis: "🚗🎵", level: "medium" },
  { id: "minneapolis", title: "Minneapolis", emojis: "❄🌊", level: "medium" },
  { id: "charlotte", title: "Charlotte", emojis: "🏁🐝", level: "medium" },
  { id: "memphis", title: "Memphis", emojis: "🎸🍖", level: "medium" },
  { id: "pittsburgh", title: "Pittsburgh", emojis: "🌉🏈", level: "medium" },
  { id: "baltimore", title: "Baltimore", emojis: "🦀🏠", level: "medium" },
  { id: "san-diego", title: "San Diego", emojis: "🐼🏖", level: "medium" },
  { id: "san-antonio", title: "San Antonio", emojis: "⭐🌵", level: "medium" },
  { id: "salt-lake-city", title: "Salt Lake City", emojis: "🏔🧂", level: "medium" },
  { id: "phoenix", title: "Phoenix", emojis: "🌵☀", level: "medium" },
  // ===== HARD (25) =====
  { id: "beirut", title: "Beirut", emojis: "🌲🌊", level: "hard" },
  { id: "amman", title: "Amman", emojis: "🏛🕌", level: "hard" },
  { id: "muscat", title: "Muscat", emojis: "🕌⛵", level: "hard" },
  { id: "manama", title: "Manama", emojis: "🏎🕌", level: "hard" },
  { id: "kuwait-city", title: "Kuwait City", emojis: "🗼🌊", level: "hard" },
  { id: "tehran", title: "Tehran", emojis: "🏔🕌", level: "hard" },
  { id: "karachi", title: "Karachi", emojis: "🕌🌊", level: "hard" },
  { id: "lahore", title: "Lahore", emojis: "🕌🍛", level: "hard" },
  { id: "colombo", title: "Colombo", emojis: "🐘🌊", level: "hard" },
  { id: "dhaka", title: "Dhaka", emojis: "🚲🌊", level: "hard" },
  { id: "yangon", title: "Yangon", emojis: "🛕✨", level: "hard" },
  { id: "phnom-penh", title: "Phnom Penh", emojis: "🛕🐟", level: "hard" },
  { id: "vientiane", title: "Vientiane", emojis: "🛕🍜", level: "hard" },
  { id: "ulaanbaatar", title: "Ulaanbaatar", emojis: "🐎⛺", level: "hard" },
  { id: "almaty", title: "Almaty", emojis: "🏔🍎", level: "hard" },
  { id: "tashkent", title: "Tashkent", emojis: "🍈🕌", level: "hard" },
  { id: "baku", title: "Baku", emojis: "🔥🏙", level: "hard" },
  { id: "tbilisi", title: "Tbilisi", emojis: "♨🏰", level: "hard" },
  { id: "yerevan", title: "Yerevan", emojis: "🏔🍑", level: "hard" },
  { id: "minsk", title: "Minsk", emojis: "🏛🌲", level: "hard" },
  { id: "addis-ababa", title: "Addis Ababa", emojis: "☕🏔", level: "hard" },
  { id: "accra", title: "Accra", emojis: "🌊🥁", level: "hard" },
  { id: "lagos", title: "Lagos", emojis: "🌊🎥", level: "hard" },
  { id: "dakar", title: "Dakar", emojis: "🐟🌊", level: "hard" },
  { id: "tunis", title: "Tunis", emojis: "🕌🐟", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { id: "djenne", title: "Djenné", emojis: "🕌🧱", level: "impossible" },
  { id: "shibam", title: "Shibam", emojis: "🏜🏢", level: "impossible" },
  { id: "harar", title: "Harar", emojis: "☕🧱", level: "impossible" },
  { id: "lalibela", title: "Lalibela", emojis: "⛪🪨", level: "impossible" },
  { id: "gondar", title: "Gondar", emojis: "🏰⛪", level: "impossible" },
  { id: "ouarzazate", title: "Ouarzazate", emojis: "🎥🏜", level: "impossible" },
  { id: "essaouira", title: "Essaouira", emojis: "⚓🌊", level: "impossible" },
  { id: "ghadames", title: "Ghadames", emojis: "🌴🏜", level: "impossible" },
  { id: "aleppo", title: "Aleppo", emojis: "🏰🧼", level: "impossible" },
  { id: "sanaa", title: "Sana'a", emojis: "🏢🕌", level: "impossible" },
  { id: "khiva", title: "Khiva", emojis: "🕌🏰", level: "impossible" },
  { id: "turpan", title: "Turpan", emojis: "🍇🏜", level: "impossible" },
  { id: "dali", title: "Dali", emojis: "⛰🏯", level: "impossible" },
  { id: "lijiang", title: "Lijiang", emojis: "🌉🏞", level: "impossible" },
  { id: "battambang", title: "Battambang", emojis: "🚂🎨", level: "impossible" },
  { id: "sapa", title: "Sapa", emojis: "🏔🌾", level: "impossible" },
  { id: "chiang-mai", title: "Chiang Mai", emojis: "🐘🏮", level: "impossible" },
  { id: "bagan", title: "Bagan", emojis: "🎈🛕", level: "impossible" },
  { id: "mandalay", title: "Mandalay", emojis: "🛕🌙", level: "impossible" },
  { id: "jodhpur", title: "Jodhpur", emojis: "🏰🐐", level: "impossible" },
  { id: "udaipur", title: "Udaipur", emojis: "🏰💧", level: "impossible" },
  { id: "pushkar", title: "Pushkar", emojis: "🐪🕉", level: "impossible" },
  { id: "leh", title: "Leh", emojis: "🏔🙏", level: "impossible" },
  { id: "paro", title: "Paro", emojis: "🛕⛰", level: "impossible" },
  { id: "thimphu", title: "Thimphu", emojis: "🐉🛕", level: "impossible" },
];
