export const CITY_EMOJI_2_FACTS = {
  "osaka": "Osaka is Japan's food capital, famed for takoyaki and its old castle",
  "havana": "Havana's streets are lined with classic 1950s American cars",
  "warsaw": "Warsaw was rebuilt brick by brick after WWII, guided by old paintings",
  "budapest": "Budapest sits atop Europe's largest thermal spring system",
  "kuala-lumpur": "Kuala Lumpur's Petronas Towers were the tallest buildings until 2004",
  "mumbai": "Mumbai is home to Bollywood, the world's largest film industry",
  "melbourne": "Melbourne ranks among the world's most livable cities, a coffee hub",
  "auckland": "Auckland sits among 53 volcanic cones, earning it City of Volcanoes",
  "doha": "Doha's skyline rose from desert sand into a Gulf megacity in decades",
  "casablanca": "Casablanca is Morocco's largest city, named for a 1942 film set there",
  "johannesburg": "Johannesburg grew from a 19th-century gold rush, not a natural harbor",
  "lima": "Lima is a UNESCO city and the culinary capital of South America",
  "bogota": "Bogota sits 2,640m high in the Andes, one of the highest capitals",
  "santiago": "Santiago lies in a valley ringed by the Andes, near wine country",
  "quito": "Quito's colonial center was one of the first UNESCO Heritage Sites",
  "panama-city": "Panama City sits beside the canal linking the Atlantic and Pacific",
  "montreal": "Montreal is the world's 2nd-largest French-speaking city after Paris",
  "washington": "Washington DC was purpose-built as the US capital, not a state's city",
  "philadelphia": "Philadelphia's Liberty Bell cracked marking Washington's birthday",
  "orlando": "Orlando hosts more theme parks than any other city on Earth",
  "st-petersburg": "St. Petersburg's Hermitage Museum holds over 3 million works of art",
  "kyiv": "Kyiv is over 1,500 years old, one of Eastern Europe's oldest cities",
  "manila": "Manila is one of the most densely populated cities in the world",
  "jakarta": "Jakarta is sinking faster than any other major city on Earth",
  "riyadh": "Riyadh sits in the Nejd desert plateau at the heart of Saudi Arabia",
  "krakow": "Krakow's Wawel Castle legend tells of a dragon in its cave below",
  "bratislava": "Bratislava is the only capital bordering two other countries",
  "ljubljana": "Ljubljana's Dragon Bridge dragons are the city's protective symbol",
  "zagreb": "Zagreb's Advent market has been voted Europe's best Christmas market",
  "belgrade": "Belgrade's Kalemegdan fortress has been fought over 100 times",
  "sofia": "Sofia is named after Saint Sofia and sits near Bulgaria's Rose Valley",
  "bucharest": "Bucharest's Palace of the Parliament is the world's heaviest building",
  "gothenburg": "Gothenburg is Scandinavia's largest port, home to Liseberg park",
  "trondheim": "Trondheim's Nidaros Cathedral is Scandinavia's biggest medieval church",
  "ottawa": "Ottawa's canal freezes each winter into a giant skating rink",
  "calgary": "Calgary hosts the Stampede, billed as the greatest outdoor show",
  "winnipeg": "Winnipeg sits at the historic meeting point of two major rivers",
  "portland": "Portland has one of the highest numbers of bike commuters in the US",
  "denver": "Denver's Mile High Stadium sits exactly 5,280 feet above sea level",
  "austin": "Austin's Congress bridge hosts North America's largest bat colony",
  "detroit": "Detroit earned the nickname Motor City, birthplace of the auto trade",
  "minneapolis": "Minneapolis has over 200 miles of dedicated bike paths and 13 lakes",
  "charlotte": "Charlotte is nicknamed the Queen City after Queen Charlotte of England",
  "memphis": "Memphis on the Mississippi is the birthplace of blues and rock",
  "pittsburgh": "Pittsburgh is called the City of Bridges with over 440 spans",
  "baltimore": "Baltimore's Chesapeake Bay blue crabs are a defining local dish",
  "san-diego": "San Diego's zoo was among the first to house giant pandas in the US",
  "san-antonio": "San Antonio's Alamo mission is one of the most visited sites in Texas",
  "salt-lake-city": "Salt Lake City sits beside the Great Salt Lake, saltier than the ocean",
  "phoenix": "Phoenix is the US's sunniest major city, named for rising from ruins",
  "beirut": "Beirut's coast is backed by cedar-covered mountains, Lebanon's symbol",
  "amman": "Amman was built across seven hills, much like ancient Rome",
  "muscat": "Muscat's Sultan Qaboos Grand Mosque can hold 20,000 worshippers",
  "manama": "Manama hosts the Bahrain International Circuit, a Formula 1 venue",
  "kuwait-city": "Kuwait City's iconic towers rise beside the Persian Gulf coastline",
  "tehran": "Tehran sits at the foot of the Alborz mountains in northern Iran",
  "karachi": "Karachi is Pakistan's largest city and its main Arabian Sea port",
  "lahore": "Lahore's Badshahi Mosque was once the largest mosque in the world",
  "colombo": "Colombo is Sri Lanka's commercial capital on the Indian Ocean coast",
  "dhaka": "Dhaka is called the rickshaw capital of the world, with hundreds",
  "yangon": "Yangon's Shwedagon Pagoda is gilded with real gold plates",
  "phnom-penh": "Phnom Penh sits where the Mekong and Tonle Sap rivers meet",
  "vientiane": "Vientiane is one of the world's least populated national capitals",
  "ulaanbaatar": "Ulaanbaatar is Earth's coldest capital by average temperature",
  "almaty": "Almaty's name derives from a word meaning father of apples",
  "tashkent": "Tashkent is Central Asia's largest city along the ancient Silk Road",
  "baku": "Baku's Flame Towers glow with fire-like LED patterns each night",
  "tbilisi": "Tbilisi means warm place, named for its natural sulfur hot springs",
  "yerevan": "Yerevan is older than Rome, founded in 782 BC near Mount Ararat",
  "minsk": "Minsk was almost entirely rebuilt after being flattened in WWII",
  "addis-ababa": "Addis Ababa sits in the Ethiopian highlands, birthplace of coffee",
  "accra": "Accra is Ghana's capital, a hub of West African music and drumming",
  "lagos": "Lagos is home to Nollywood, one of the world's largest film industries",
  "dakar": "Dakar is the finish line namesake of the famous Dakar off-road rally",
  "tunis": "Tunis overlooks the Mediterranean near the ancient ruins of Carthage",
  "djenne": "Djenne's Great Mosque is the world's largest mudbrick building",
  "shibam": "Shibam is called Manhattan of the desert for its mudbrick tower houses",
  "harar": "Harar is deemed Islam's fourth holiest city and a coffee birthplace",
  "lalibela": "Lalibela's churches were carved downward from solid volcanic rock",
  "gondar": "Gondar was Ethiopia's royal capital, filled with 17th-century castles",
  "ouarzazate": "Ouarzazate is nicknamed Moroccan Hollywood for its film studios",
  "essaouira": "Essaouira's windswept ramparts once defended a major Atlantic port",
  "ghadames": "Ghadames is a Saharan oasis town of mudbrick houses called old Ghat",
  "aleppo": "Aleppo's ancient citadel has overlooked the city for over 3,000 years",
  "sanaa": "Sana'a's Old City has multi-story tower houses over 400 years old",
  "khiva": "Khiva's walled old town Itchan Kala is a living open-air museum",
  "turpan": "Turpan sits in a desert basin famous for its sweet seedless grapes",
  "dali": "Dali's old town sits beside Erhai Lake, foot of the Cangshan range",
  "lijiang": "Lijiang's old town canals and bridges date back over 800 years",
  "battambang": "Battambang's bamboo train is a beloved improvised rail attraction",
  "sapa": "Sapa's mountain terraces of rice paddies climb the hillsides in layers",
  "chiang-mai": "Chiang Mai releases thousands of lanterns each Yi Peng festival",
  "bagan": "Bagan has over 2,000 ancient temples scattered across its plains",
  "mandalay": "Mandalay was Myanmar's last royal capital before British rule",
  "jodhpur": "Jodhpur is nicknamed the Blue City for its indigo-painted old houses",
  "udaipur": "Udaipur is called the City of Lakes, home to a palace on the water",
  "pushkar": "Pushkar hosts one of the world's largest camel fairs each year",
  "leh": "Leh sits over 3,500m high in the Ladakh Himalayas of northern India",
  "paro": "Paro is home to the cliffside Tiger's Nest monastery in Bhutan",
  "thimphu": "Thimphu is the world's only capital with no traffic lights"
};
