// E151 «Guess the Clothing by Emoji» — 100 clothing/accessory/fashion items · 25/tier
// clue = plain Unicode emoji (single-codepoint, no FE0F/ZWJ/flag), rendered via openmoji SVG
// VO: sfx/e151-<id>.wav  ("It's <Item>!")
export const CLOTHING_EMOJI = [
  // ===== EASY (25) — dedicated garment emoji =====
  { id: "dress", title: "Dress", emojis: "👗", level: "easy" },
  { id: "t-shirt", title: "T-Shirt", emojis: "👕", level: "easy" },
  { id: "jeans", title: "Jeans", emojis: "👖", level: "easy" },
  { id: "necktie", title: "Necktie", emojis: "👔", level: "easy" },
  { id: "high-heels", title: "High Heels", emojis: "👠", level: "easy" },
  { id: "coat", title: "Coat", emojis: "🧥", level: "easy" },
  { id: "top-hat", title: "Top Hat", emojis: "🎩", level: "easy" },
  { id: "baseball-cap", title: "Baseball Cap", emojis: "🧢", level: "easy" },
  { id: "socks", title: "Socks", emojis: "🧦", level: "easy" },
  { id: "sneaker", title: "Sneaker", emojis: "👟", level: "easy" },
  { id: "hiking-boot", title: "Hiking Boot", emojis: "🥾", level: "easy" },
  { id: "sun-hat", title: "Sun Hat", emojis: "👒", level: "easy" },
  { id: "shorts", title: "Shorts", emojis: "🩳", level: "easy" },
  { id: "gloves", title: "Gloves", emojis: "🧤", level: "easy" },
  { id: "scarf", title: "Scarf", emojis: "🧣", level: "easy" },
  { id: "kimono", title: "Kimono", emojis: "👘", level: "easy" },
  { id: "sari", title: "Sari", emojis: "🥻", level: "easy" },
  { id: "bikini", title: "Bikini", emojis: "👙", level: "easy" },
  { id: "swimsuit", title: "Swimsuit", emojis: "🩱", level: "easy" },
  { id: "crown", title: "Crown", emojis: "👑", level: "easy" },
  { id: "ring", title: "Ring", emojis: "💍", level: "easy" },
  { id: "coin-purse", title: "Coin Purse", emojis: "👛", level: "easy" },
  { id: "backpack", title: "Backpack", emojis: "🎒", level: "easy" },
  { id: "glasses", title: "Glasses", emojis: "👓", level: "easy" },
  { id: "sandal", title: "Sandal", emojis: "👡", level: "easy" },

  // ===== MEDIUM (25) — less-common dedicated emoji or clear 2-emoji =====
  { id: "handbag", title: "Handbag", emojis: "👜", level: "medium" },
  { id: "clutch-bag", title: "Clutch Bag", emojis: "👝", level: "medium" },
  { id: "wristwatch", title: "Wristwatch", emojis: "⌚", level: "medium" },
  { id: "lipstick", title: "Lipstick", emojis: "💄", level: "medium" },
  { id: "lab-coat", title: "Lab Coat", emojis: "🥼", level: "medium" },
  { id: "safety-vest", title: "Safety Vest", emojis: "🦺", level: "medium" },
  { id: "graduation-cap", title: "Graduation Cap", emojis: "🎓", level: "medium" },
  { id: "flip-flops", title: "Flip-Flops", emojis: "🩴", level: "medium" },
  { id: "ballet-shoes", title: "Ballet Shoes", emojis: "🩰", level: "medium" },
  { id: "swim-goggles", title: "Swim Goggles", emojis: "🥽", level: "medium" },
  { id: "ballet-flat", title: "Ballet Flat", emojis: "🥿", level: "medium" },
  { id: "briefs", title: "Briefs", emojis: "🩲", level: "medium" },
  { id: "knee-high-boot", title: "Knee-High Boot", emojis: "👢", level: "medium" },
  { id: "blouse", title: "Blouse", emojis: "👚", level: "medium" },
  { id: "sunglasses", title: "Sunglasses", emojis: "🕶", level: "medium" },
  { id: "turban", title: "Turban", emojis: "👳", level: "medium" },
  { id: "cowboy-hat", title: "Cowboy Hat", emojis: "🤠", level: "medium" },
  { id: "tuxedo", title: "Tuxedo", emojis: "🤵", level: "medium" },
  { id: "wedding-veil", title: "Wedding Veil", emojis: "👰", level: "medium" },
  { id: "hair-bow", title: "Hair Bow", emojis: "🎀", level: "medium" },
  { id: "prayer-beads", title: "Prayer Beads", emojis: "📿", level: "medium" },
  { id: "tank-top", title: "Tank Top", emojis: "🎽", level: "medium" },
  { id: "knit-sweater", title: "Knit Sweater", emojis: "🧶🧥", level: "medium" },
  { id: "denim-jacket", title: "Denim Jacket", emojis: "👖🧥", level: "medium" },
  { id: "raincoat", title: "Raincoat", emojis: "🌧🧥", level: "medium" },

  // ===== HARD (25) — no dedicated emoji, fair 2-emoji clue =====
  { id: "blazer", title: "Blazer", emojis: "👔🧥", level: "hard" },
  { id: "sombrero", title: "Sombrero", emojis: "🌵🎩", level: "hard" },
  { id: "beret", title: "Beret", emojis: "🥖🧢", level: "hard" },
  { id: "fedora", title: "Fedora", emojis: "🕵🎩", level: "hard" },
  { id: "clogs", title: "Clogs", emojis: "🌷👞", level: "hard" },
  { id: "cowboy-boots", title: "Cowboy Boots", emojis: "🤠🥾", level: "hard" },
  { id: "poncho", title: "Poncho", emojis: "🦙🧥", level: "hard" },
  { id: "overalls", title: "Overalls", emojis: "🌾👖", level: "hard" },
  { id: "trench-coat", title: "Trench Coat", emojis: "🕵🧥", level: "hard" },
  { id: "windbreaker", title: "Windbreaker", emojis: "💨🧥", level: "hard" },
  { id: "mittens", title: "Mittens", emojis: "🧤☃", level: "hard" },
  { id: "earmuffs", title: "Earmuffs", emojis: "🎧❄", level: "hard" },
  { id: "bowtie", title: "Bow Tie", emojis: "🎀👔", level: "hard" },
  { id: "chaps", title: "Chaps", emojis: "🤠👖", level: "hard" },
  { id: "rain-boots", title: "Rain Boots", emojis: "🌧🥾", level: "hard" },
  { id: "beanie", title: "Beanie", emojis: "🧶🧢", level: "hard" },
  { id: "shawl", title: "Shawl", emojis: "🧶🧣", level: "hard" },
  { id: "cape", title: "Cape", emojis: "🦸🧥", level: "hard" },
  { id: "cloak", title: "Cloak", emojis: "🧙🧥", level: "hard" },
  { id: "bathrobe", title: "Bathrobe", emojis: "🛁👘", level: "hard" },
  { id: "pajamas", title: "Pajamas", emojis: "🌙👕", level: "hard" },
  { id: "nightgown", title: "Nightgown", emojis: "🌙👗", level: "hard" },
  { id: "moccasin", title: "Moccasin", emojis: "🪶👞", level: "hard" },
  { id: "leg-warmers", title: "Leg Warmers", emojis: "🦵🧦", level: "hard" },
  { id: "wetsuit", title: "Wetsuit", emojis: "🌊🩱", level: "hard" },

  // ===== IMPOSSIBLE (25) — obscure / historical / cultural garments =====
  { id: "corset", title: "Corset", emojis: "⌛👗", level: "impossible" },
  { id: "toga", title: "Toga", emojis: "🏛👗", level: "impossible" },
  { id: "kilt", title: "Kilt", emojis: "🥃🩳", level: "impossible" },
  { id: "lederhosen", title: "Lederhosen", emojis: "🍺🩳", level: "impossible" },
  { id: "dirndl", title: "Dirndl", emojis: "🍺👗", level: "impossible" },
  { id: "qipao", title: "Qipao", emojis: "🐉👗", level: "impossible" },
  { id: "kaftan", title: "Kaftan", emojis: "🐫👘", level: "impossible" },
  { id: "abaya", title: "Abaya", emojis: "🕌👘", level: "impossible" },
  { id: "hanbok", title: "Hanbok", emojis: "🌸👘", level: "impossible" },
  { id: "sarong", title: "Sarong", emojis: "🌴🩳", level: "impossible" },
  { id: "loincloth", title: "Loincloth", emojis: "🍃🩳", level: "impossible" },
  { id: "spats", title: "Spats", emojis: "🎩🧦", level: "impossible" },
  { id: "muff", title: "Hand Muff", emojis: "🐰🧤", level: "impossible" },
  { id: "pinafore", title: "Pinafore", emojis: "🌾👗", level: "impossible" },
  { id: "yukata", title: "Yukata", emojis: "🎆👘", level: "impossible" },
  { id: "tutu", title: "Tutu", emojis: "🩰👗", level: "impossible" },
  { id: "leotard", title: "Leotard", emojis: "🤸🩱", level: "impossible" },
  { id: "fishnet-stockings", title: "Fishnet Stockings", emojis: "🎣🧦", level: "impossible" },
  { id: "doublet", title: "Doublet", emojis: "🤺👔", level: "impossible" },
  { id: "ruff-collar", title: "Ruff Collar", emojis: "🤡👔", level: "impossible" },
  { id: "espadrille", title: "Espadrille", emojis: "🌞👡", level: "impossible" },
  { id: "mukluk", title: "Mukluk", emojis: "🐻🥾", level: "impossible" },
  { id: "balaclava", title: "Balaclava", emojis: "🥷🧣", level: "impossible" },
  { id: "monocle", title: "Monocle", emojis: "🧐👓", level: "impossible" },
  { id: "pocket-watch", title: "Pocket Watch", emojis: "⌚⛓", level: "impossible" },
];
