// E151 clothing-emoji facts — one true <=70-char fact per item, shown on reveal.
export const CLOTHING_EMOJI_FACTS = {
  // EASY
  "dress": "A one-piece garment covering the body and often the legs.",
  "t-shirt": "Named for its T shape when laid flat with sleeves out.",
  "jeans": "Made from denim; named after Genoa, Italy (Genes in French).",
  "necktie": "Descended from cravats worn by 17th-century Croatian soldiers.",
  "high-heels": "Once worn by men; heels aided riders gripping stirrups.",
  "coat": "An outer garment with sleeves worn for warmth or style.",
  "top-hat": "A tall, flat-crowned formal hat popular in the 19th century.",
  "baseball-cap": "A soft cap with a rounded crown and a stiff front brim.",
  "socks": "Foot coverings; early Romans wore cloth 'udones'.",
  "sneaker": "Named 'sneaker' as its rubber sole let wearers move silently.",
  "hiking-boot": "Sturdy boots with lugged soles for grip on rough trails.",
  "sun-hat": "A wide-brimmed hat that shades the face and neck.",
  "shorts": "Trousers cut above the knee for warm weather or sport.",
  "gloves": "Hand coverings with a separate sheath for each finger.",
  "scarf": "A length of fabric worn around the neck for warmth or style.",
  "kimono": "A traditional Japanese wrapped robe tied with an obi sash.",
  "sari": "A long draped cloth worn across South Asia, often 5-9 yards.",
  "bikini": "A two-piece swimsuit named after Bikini Atoll in 1946.",
  "swimsuit": "A garment worn for swimming; one-piece styles are common.",
  "crown": "A headpiece of metal and jewels symbolizing royal power.",
  "ring": "A band worn on a finger, often as jewelry or a token.",
  "coin-purse": "A small pouch used to carry coins and small items.",
  "backpack": "A bag with shoulder straps, carried on the back.",
  "glasses": "Lenses in a frame worn to correct or protect vision.",
  "sandal": "An open shoe held on by straps across the foot.",

  // MEDIUM
  "handbag": "A bag held by hand or shoulder to carry personal items.",
  "clutch-bag": "A small, handleless bag held in the hand.",
  "wristwatch": "A clock worn on the wrist, popularized after World War I.",
  "lipstick": "A colored cosmetic applied to the lips.",
  "lab-coat": "A white knee-length coat worn by scientists and doctors.",
  "safety-vest": "A high-visibility vest with reflective strips for safety.",
  "graduation-cap": "The square 'mortarboard' cap worn at graduations.",
  "flip-flops": "Flat sandals held on by a strap between the toes.",
  "ballet-shoes": "Soft slippers worn by ballet dancers for practice.",
  "swim-goggles": "Sealed eyewear that keeps water out while swimming.",
  "ballet-flat": "A slip-on shoe with a very low heel, inspired by ballet.",
  "briefs": "Close-fitting underwear with no legs.",
  "knee-high-boot": "A boot whose shaft rises to just below the knee.",
  "blouse": "A loose upper garment, typically worn by women.",
  "sunglasses": "Tinted glasses that shield the eyes from bright sun.",
  "turban": "A cloth wound around the head, worn across many cultures.",
  "cowboy-hat": "A wide-brimmed, high-crowned hat linked with the American West.",
  "tuxedo": "A formal jacket named after Tuxedo Park, New York.",
  "wedding-veil": "A sheer cloth traditionally worn by a bride.",
  "hair-bow": "A looped ribbon worn as a decorative hair accessory.",
  "prayer-beads": "A strung loop of beads used to count prayers.",
  "tank-top": "A sleeveless shirt with shoulder straps.",
  "knit-sweater": "A knitted garment for the upper body, worn for warmth.",
  "denim-jacket": "A jacket made of sturdy denim, a wardrobe staple since the 1880s.",
  "raincoat": "A waterproof coat worn to stay dry in the rain.",

  // HARD
  "blazer": "A smart jacket less formal than a full suit coat.",
  "sombrero": "A wide-brimmed Mexican hat; 'sombra' means shade in Spanish.",
  "beret": "A soft, round, flat cap linked with France and the Basques.",
  "fedora": "A soft felt hat with a creased crown and a brim.",
  "clogs": "Shoes with a wooden sole, famous in the Netherlands.",
  "cowboy-boots": "Leather boots with a pointed toe and a raised heel.",
  "poncho": "A single cloth sheet with a head hole, from the Andes.",
  "overalls": "Trousers with a bib and shoulder straps, worn as workwear.",
  "trench-coat": "A belted raincoat first issued to soldiers in World War I.",
  "windbreaker": "A light jacket that blocks wind and light rain.",
  "mittens": "Hand coverings that group the four fingers together.",
  "earmuffs": "Padded coverings that keep the ears warm.",
  "bowtie": "A necktie tied into a bow, common with formal wear.",
  "chaps": "Leather leg coverings worn over trousers by cowboys.",
  "rain-boots": "Waterproof rubber boots, also called wellingtons.",
  "beanie": "A snug knitted cap that covers the head.",
  "shawl": "A large cloth draped over the shoulders or head.",
  "cape": "A sleeveless garment hanging from the shoulders.",
  "cloak": "A loose outer garment without sleeves, worn over clothes.",
  "bathrobe": "A loose absorbent robe worn before or after bathing.",
  "pajamas": "Loose sleepwear; the word comes from Persian/Urdu 'payjama'.",
  "nightgown": "A loose garment worn in bed, usually by women.",
  "moccasin": "A soft leather shoe of Native American origin.",
  "leg-warmers": "Tube-like coverings for the lower legs, popular in the 1980s.",
  "wetsuit": "A snug neoprene suit that keeps divers and surfers warm.",

  // IMPOSSIBLE
  "corset": "A stiffened garment laced to shape the torso and waist.",
  "toga": "A draped wool cloth worn by citizens of ancient Rome.",
  "kilt": "A pleated knee-length skirt from the Scottish Highlands.",
  "lederhosen": "Traditional Bavarian leather breeches with braces.",
  "dirndl": "A traditional Alpine dress with a bodice, blouse, and apron.",
  "qipao": "A fitted Chinese dress, also known as the cheongsam.",
  "kaftan": "A long, loose robe worn across the Middle East and Africa.",
  "abaya": "A loose full-length robe worn by some Muslim women.",
  "hanbok": "The colorful traditional dress of Korea.",
  "sarong": "A large cloth wrapped around the waist, worn in Southeast Asia.",
  "loincloth": "A simple cloth wrapped around the hips, one of the oldest garments.",
  "spats": "Cloth covers worn over the ankle and shoe, popular around 1900.",
  "muff": "A tube of fur or fabric that warms both hands at once.",
  "pinafore": "A sleeveless apron-like dress worn over other clothes.",
  "yukata": "A light cotton kimono worn in summer and at festivals.",
  "tutu": "A stiff layered skirt worn by ballerinas.",
  "leotard": "A tight one-piece named after acrobat Jules Leotard.",
  "fishnet-stockings": "Stockings knitted in a wide, open net pattern.",
  "doublet": "A snug buttoned jacket worn by men in the 15th-17th centuries.",
  "ruff-collar": "A stiff frilled collar fashionable in the 1500s and 1600s.",
  "espadrille": "A casual shoe with a woven rope sole, from the Pyrenees.",
  "mukluk": "A soft fur boot worn by Arctic peoples like the Inuit.",
  "balaclava": "A close-fitting hood that covers the head and most of the face.",
  "monocle": "A single lens worn in one eye, held by the eye socket.",
  "pocket-watch": "A watch carried in a pocket, often on a chain.",
};
