// E217 «Guess the Clothing by Emoji 2» — 100 items · 25/tier
// clue = plain Unicode emoji (single-codepoint, no FE0F/ZWJ/flag), rendered via openmoji SVG
// VO: sfx/e217-<id>.wav
export const CLOTHING_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "hoodie", title: "Hoodie", emojis: "\u{1F3C3}\u{1F9E5}", level: "easy" },
  { id: "sweater", title: "Sweater", emojis: "\u{1F9F6}\u{1F455}", level: "easy" },
  { id: "cardigan", title: "Cardigan", emojis: "\u{1F475}\u{1F9E5}", level: "easy" },
  { id: "vest", title: "Vest", emojis: "\u{1F3A9}\u{1F9BA}", level: "easy" },
  { id: "polo-shirt", title: "Polo Shirt", emojis: "\u{26F3}\u{1F455}", level: "easy" },
  { id: "skirt", title: "Skirt", emojis: "\u{1F302}\u{1F457}", level: "easy" },
  { id: "leggings", title: "Leggings", emojis: "\u{1F9D8}\u{1F456}", level: "easy" },
  { id: "sweatpants", title: "Sweatpants", emojis: "\u{1F3CB}\u{1F456}", level: "easy" },
  { id: "cargo-pants", title: "Cargo Pants", emojis: "\u{1F392}\u{1F456}", level: "easy" },
  { id: "trousers", title: "Trousers", emojis: "\u{1F4BC}\u{1F456}", level: "easy" },
  { id: "overcoat", title: "Overcoat", emojis: "\u{2744}\u{1F9E5}", level: "easy" },
  { id: "parka", title: "Parka", emojis: "\u{26C4}\u{1F9E5}", level: "easy" },
  { id: "bomber-jacket", title: "Bomber Jacket", emojis: "\u{2708}\u{1F9E5}", level: "easy" },
  { id: "denim-vest", title: "Denim Vest", emojis: "\u{1F3B8}\u{1F9BA}", level: "easy" },
  { id: "bowler-hat", title: "Bowler Hat", emojis: "\u{2602}\u{1F3A9}", level: "easy" },
  { id: "visor", title: "Visor", emojis: "\u{2600}\u{1F9E2}", level: "easy" },
  { id: "belt", title: "Belt", emojis: "\u{1F456}\u{1F517}", level: "easy" },
  { id: "wallet", title: "Wallet", emojis: "\u{1F4B5}\u{1F45B}", level: "easy" },
  { id: "necklace", title: "Necklace", emojis: "\u{1F48E}\u{1F4FF}", level: "easy" },
  { id: "bracelet", title: "Bracelet", emojis: "\u{1F48E}\u{231A}", level: "easy" },
  { id: "earrings", title: "Earrings", emojis: "\u{1F48E}\u{1F442}", level: "easy" },
  { id: "flat-cap", title: "Flat Cap", emojis: "\u{1F6B2}\u{1F9E2}", level: "easy" },
  { id: "rain-hat", title: "Rain Hat", emojis: "\u{2614}\u{1F9E2}", level: "easy" },
  { id: "nightcap", title: "Nightcap", emojis: "\u{1F319}\u{1F9E2}", level: "easy" },
  { id: "winter-boots", title: "Winter Boots", emojis: "\u{2744}\u{1F97E}", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "jodhpurs", title: "Jodhpurs", emojis: "\u{1F40E}\u{1F456}", level: "medium" },
  { id: "cummerbund", title: "Cummerbund", emojis: "\u{1F935}\u{1F397}", level: "medium" },
  { id: "cheongsam", title: "Cheongsam", emojis: "\u{1F95F}\u{1F457}", level: "medium" },
  { id: "ascot-tie", title: "Ascot Tie", emojis: "\u{1F40E}\u{1F454}", level: "medium" },
  { id: "pith-helmet", title: "Pith Helmet", emojis: "\u{1F981}\u{26D1}", level: "medium" },
  { id: "deerstalker-hat", title: "Deerstalker Hat", emojis: "\u{1F50D}\u{1F9E2}", level: "medium" },
  { id: "newsboy-cap", title: "Newsboy Cap", emojis: "\u{1F4F0}\u{1F9E2}", level: "medium" },
  { id: "trapper-hat", title: "Trapper Hat", emojis: "\u{1F43B}\u{1F9E2}", level: "medium" },
  { id: "bucket-hat", title: "Bucket Hat", emojis: "\u{1FAA3}\u{1F9E2}", level: "medium" },
  { id: "snapback-cap", title: "Snapback Cap", emojis: "\u{1F3A4}\u{1F9E2}", level: "medium" },
  { id: "trilby-hat", title: "Trilby Hat", emojis: "\u{1F3B7}\u{1F3A9}", level: "medium" },
  { id: "cloche-hat", title: "Cloche Hat", emojis: "\u{1F483}\u{1F3A9}", level: "medium" },
  { id: "boater-hat", title: "Boater Hat", emojis: "\u{1F6A3}\u{1F3A9}", level: "medium" },
  { id: "trucker-hat", title: "Trucker Hat", emojis: "\u{1F69A}\u{1F9E2}", level: "medium" },
  { id: "serape", title: "Serape", emojis: "\u{1F335}\u{1F9E3}", level: "medium" },
  { id: "bolero-jacket", title: "Bolero Jacket", emojis: "\u{1F483}\u{1F9E5}", level: "medium" },
  { id: "peacoat", title: "Peacoat", emojis: "\u{2693}\u{1F9E5}", level: "medium" },
  { id: "duffle-coat", title: "Duffle Coat", emojis: "\u{1FA79}\u{1F9E5}", level: "medium" },
  { id: "anorak", title: "Anorak", emojis: "\u{1F3D4}\u{1F9E5}", level: "medium" },
  { id: "onesie", title: "Onesie", emojis: "\u{1F43B}\u{1F455}", level: "medium" },
  { id: "romper", title: "Romper", emojis: "\u{1F476}\u{1FA73}", level: "medium" },
  { id: "jumpsuit", title: "Jumpsuit", emojis: "\u{1F680}\u{1F456}", level: "medium" },
  { id: "camisole", title: "Camisole", emojis: "\u{1F380}\u{1F455}", level: "medium" },
  { id: "halter-top", title: "Halter Top", emojis: "\u{2600}\u{1F459}", level: "medium" },
  { id: "tube-top", title: "Tube Top", emojis: "\u{1F32D}\u{1F455}", level: "medium" },

  // ===== HARD (25) =====
  { id: "culottes", title: "Culottes", emojis: "\u{1F6B2}\u{1FA73}", level: "hard" },
  { id: "palazzo-pants", title: "Palazzo Pants", emojis: "\u{1F3DB}\u{1F456}", level: "hard" },
  { id: "harem-pants", title: "Harem Pants", emojis: "\u{1F9DE}\u{1F456}", level: "hard" },
  { id: "capri-pants", title: "Capri Pants", emojis: "\u{1F34B}\u{1F456}", level: "hard" },
  { id: "pedal-pushers", title: "Pedal Pushers", emojis: "\u{1F6B2}\u{1F456}", level: "hard" },
  { id: "bell-bottoms", title: "Bell-Bottoms", emojis: "\u{1F514}\u{1F456}", level: "hard" },
  { id: "jeggings", title: "Jeggings", emojis: "\u{1F9EC}\u{1F456}", level: "hard" },
  { id: "sarafan", title: "Sarafan", emojis: "\u{1FA86}\u{1F457}", level: "hard" },
  { id: "guayabera", title: "Guayabera", emojis: "\u{1F334}\u{1F454}", level: "hard" },
  { id: "kurta", title: "Kurta", emojis: "\u{1F64F}\u{1F455}", level: "hard" },
  { id: "sherwani", title: "Sherwani", emojis: "\u{1F451}\u{1F454}", level: "hard" },
  { id: "bandana", title: "Bandana", emojis: "\u{1F920}\u{1F9E3}", level: "hard" },
  { id: "do-rag", title: "Do-Rag", emojis: "\u{1F488}\u{1F9E2}", level: "hard" },
  { id: "fez-hat", title: "Fez Hat", emojis: "\u{1F42B}\u{1F3A9}", level: "hard" },
  { id: "ushanka", title: "Ushanka", emojis: "\u{26C4}\u{1F9E2}", level: "hard" },
  { id: "ten-gallon-hat", title: "Ten-Gallon Hat", emojis: "\u{1F404}\u{1F3A9}", level: "hard" },
  { id: "fascinator", title: "Fascinator", emojis: "\u{1F389}\u{1F452}", level: "hard" },
  { id: "pillbox-hat", title: "Pillbox Hat", emojis: "\u{1F48A}\u{1F3A9}", level: "hard" },
  { id: "fanny-pack", title: "Fanny Pack", emojis: "\u{1F3C3}\u{1F45B}", level: "hard" },
  { id: "gaiters", title: "Gaiters", emojis: "\u{1F97E}\u{1F9E6}", level: "hard" },
  { id: "puttees", title: "Puttees", emojis: "\u{1FA96}\u{1F9E6}", level: "hard" },
  { id: "girdle", title: "Girdle", emojis: "\u{1F4AA}\u{1F459}", level: "hard" },
  { id: "duster-coat", title: "Duster Coat", emojis: "\u{1F335}\u{1F9E5}", level: "hard" },
  { id: "smoking-jacket", title: "Smoking Jacket", emojis: "\u{1F6AC}\u{1F9E5}", level: "hard" },
  { id: "peplum-top", title: "Peplum Top", emojis: "\u{1F338}\u{1F45A}", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "chiton", title: "Chiton", emojis: "\u{1F3DB}\u{1F97B}", level: "impossible" },
  { id: "peplos", title: "Peplos", emojis: "\u{1F3FA}\u{1F97B}", level: "impossible" },
  { id: "himation", title: "Himation", emojis: "\u{1F3DB}\u{1F9E3}", level: "impossible" },
  { id: "stola", title: "Stola", emojis: "\u{1F347}\u{1F97B}", level: "impossible" },
  { id: "dhoti", title: "Dhoti", emojis: "\u{1F549}\u{1FA73}", level: "impossible" },
  { id: "lungi", title: "Lungi", emojis: "\u{1F30A}\u{1FA73}", level: "impossible" },
  { id: "salwar-kameez", title: "Salwar Kameez", emojis: "\u{1F319}\u{1F45A}", level: "impossible" },
  { id: "changshan", title: "Changshan", emojis: "\u{1F409}\u{1F454}", level: "impossible" },
  { id: "hakama", title: "Hakama", emojis: "\u{26E9}\u{1F456}", level: "impossible" },
  { id: "obi", title: "Obi", emojis: "\u{1F38F}\u{1F457}", level: "impossible" },
  { id: "geta", title: "Geta", emojis: "\u{1F338}\u{1F45E}", level: "impossible" },
  { id: "gele", title: "Gele", emojis: "\u{1F451}\u{1F9E3}", level: "impossible" },
  { id: "dashiki", title: "Dashiki", emojis: "\u{1F941}\u{1F455}", level: "impossible" },
  { id: "boubou", title: "Boubou", emojis: "\u{1F981}\u{1F458}", level: "impossible" },
  { id: "huipil", title: "Huipil", emojis: "\u{1F33D}\u{1F45A}", level: "impossible" },
  { id: "djellaba", title: "Djellaba", emojis: "\u{1F319}\u{1F458}", level: "impossible" },
  { id: "thobe", title: "Thobe", emojis: "\u{1F54C}\u{1F454}", level: "impossible" },
  { id: "keffiyeh", title: "Keffiyeh", emojis: "\u{1F410}\u{1F9E3}", level: "impossible" },
  { id: "ghillie-suit", title: "Ghillie Suit", emojis: "\u{1F33F}\u{1F977}", level: "impossible" },
  { id: "bloomers", title: "Bloomers", emojis: "\u{1F6B2}\u{1FA72}", level: "impossible" },
  { id: "crinoline", title: "Crinoline", emojis: "\u{1F514}\u{1F457}", level: "impossible" },
  { id: "peignoir", title: "Peignoir", emojis: "\u{1F9A2}\u{1F458}", level: "impossible" },
  { id: "gambeson", title: "Gambeson", emojis: "\u{1F6E1}\u{1F9E5}", level: "impossible" },
  { id: "tabard", title: "Tabard", emojis: "\u{1F40E}\u{1F3BD}", level: "impossible" },
  { id: "sporran", title: "Sporran", emojis: "\u{1F411}\u{1F45B}", level: "impossible" },
];
