// E04 «Guess the Football Club» — did-you-know facts, ≤70 chars each, verified.
export const CLUB_FACTS = {
  // ── EASY ──────────────────────────────────────────────────────────
  "real-madrid": "Founded 1902; record UEFA Champions League titles",
  "barcelona": "Its motto is 'Més que un club' — More than a club",
  "manchester-united": "Play at Old Trafford, 'The Theatre of Dreams'",
  "liverpool": "Anthem 'You'll Never Walk Alone' rings out at Anfield",
  "bayern-munich": "Germany's most successful club; based in Munich",
  "juventus": "Italy's most-titled club; nicknamed 'The Old Lady'",
  "paris-saint-germain": "Founded 1970; based in the French capital, Paris",
  "manchester-city": "Play home games at the Etihad Stadium",
  "chelsea": "London club founded 1905; play at Stamford Bridge",
  "arsenal": "North London club nicknamed 'The Gunners'",
  "ac-milan": "Founded 1899; play at the San Siro stadium",
  "inter-milan": "Founded 1908 by a split from AC Milan",
  "borussia-dortmund": "Famed for the 'Yellow Wall' terrace at home",
  "ajax": "Amsterdam club renowned for its youth academy",
  "boca-juniors": "Buenos Aires club playing at 'La Bombonera'",
  "tottenham-hotspur": "North London club nicknamed 'Spurs'",
  "atletico-madrid": "Madrid club nicknamed 'Los Colchoneros'",
  "napoli": "Southern Italy club from the city of Naples",
  "roma": "Rome club with a she-wolf on its crest",
  "flamengo": "Rio de Janeiro club, one of Brazil's biggest",
  "river-plate": "Buenos Aires giant; arch-rival of Boca Juniors",
  "porto": "Portuguese club nicknamed 'Os Dragões' (Dragons)",
  "benfica": "Lisbon club with an eagle as its symbol",
  "olympique-marseille": "Marseille's motto is 'Droit au but' (Straight to Goal)",
  "sevilla": "Record winner of the UEFA Europa League",

  // ── MEDIUM ────────────────────────────────────────────────────────
  "valencia": "Founded 1919; play at the Mestalla stadium",
  "celtic": "Glasgow club; first British side to win the European Cup",
  "rangers": "Glasgow club; fierce 'Old Firm' rival of Celtic",
  "galatasaray": "Istanbul club; won the 2000 UEFA Cup",
  "fenerbahce": "Istanbul club founded in 1907",
  "olympique-lyonnais": "Won seven straight Ligue 1 titles (2002–2008)",
  "rb-leipzig": "Founded 2009; backed by Red Bull",
  "bayer-leverkusen": "Founded by workers of the Bayer drug company",
  "schalke-04": "Gelsenkirchen club founded in 1904",
  "sporting-cp": "Lisbon club that developed a young Cristiano Ronaldo",
  "psv-eindhoven": "Eindhoven club founded by Philips employees",
  "feyenoord": "Rotterdam club playing at 'De Kuip' stadium",
  "lazio": "Rome club with a sky-blue eagle badge",
  "fiorentina": "Florence club known as 'La Viola' (the purple)",
  "athletic-bilbao": "Famous policy of only signing Basque players",
  "villarreal": "Nicknamed 'The Yellow Submarine'",
  "santos": "The Brazilian club where Pelé became a legend",
  "corinthians": "São Paulo club with a huge fan base in Brazil",
  "palmeiras": "São Paulo club founded by Italian immigrants",
  "al-hilal": "Riyadh club; Asia's most successful team",
  "al-ahly": "Cairo club; record African Champions League winner",
  "west-ham-united": "East London club nicknamed 'The Hammers'",
  "newcastle-united": "Play at St James' Park, home since 1892",
  "aston-villa": "Founding member of the Football League in 1888",
  "everton": "Liverpool club nicknamed 'The Toffees'",

  // ── HARD ──────────────────────────────────────────────────────────
  "borussia-monchengladbach": "German club nicknamed 'Die Fohlen' (The Foals)",
  "real-betis": "Seville club; city rival of Sevilla FC",
  "real-sociedad": "Basque club based in San Sebastián",
  "celta-vigo": "Galician club from the city of Vigo",
  "eintracht-frankfurt": "Frankfurt club; won the 2022 Europa League",
  "vfb-stuttgart": "Stuttgart club; German champions in 2007",
  "vfl-wolfsburg": "Founded by Volkswagen car factory workers",
  "atalanta": "Club from the city of Bergamo in Italy",
  "torino": "Turin club; the 'Grande Torino' team of the 1940s",
  "lille": "French club from the northern city of Lille",
  "as-monaco": "Play in the tiny Principality of Monaco",
  "shakhtar-donetsk": "Ukrainian club originally based in Donetsk",
  "dynamo-kyiv": "Ukraine's most successful football club",
  "red-star-belgrade": "Serbian club; won the 1991 European Cup",
  "olympiacos": "Greece's most successful club, from Piraeus",
  "panathinaikos": "Athens club with a green shamrock badge",
  "club-brugge": "Belgian club playing in blue and black",
  "anderlecht": "Belgium's most successful club, from Brussels",
  "gremio": "Club from Porto Alegre in southern Brazil",
  "independiente": "Record seven Copa Libertadores titles",
  "penarol": "Uruguay's most successful club, from Montevideo",
  "urawa-red-diamonds": "Japanese club known for huge home crowds",
  "kaizer-chiefs": "One of South Africa's biggest football clubs",
  "zenit-saint-petersburg": "Russian club from the city of Saint Petersburg",
  "sparta-prague": "Czech Republic's most successful football club",

  // ── IMPOSSIBLE ────────────────────────────────────────────────────
  "randers-fc": "Danish club from the town of Randers",
  "sivasspor": "Turkish club from the city of Sivas",
  "cracovia": "Poland's oldest existing football club (1906)",
  "ludogorets-razgrad": "Bulgarian club from the town of Razgrad",
  "molde-fk": "Norwegian club once managed by Ole Gunnar Solskjær",
  "ifk-goteborg": "Swedish club; won the UEFA Cup in 1982 and 1987",
  "hjk-helsinki": "Finland's most successful football club",
  "qarabag": "Azerbaijani club originally from Agdam",
  "malmo-ff": "Swedish club; 1979 European Cup runners-up",
  "cfr-cluj": "Romanian club from the city of Cluj-Napoca",
  "slovan-bratislava": "Slovak club; won the 1969 Cup Winners' Cup",
  "riga-fc": "Latvian club founded in 2014",
  "dundalk": "Irish club from the town of Dundalk",
  "valletta": "Maltese club from the capital city, Valletta",
  "lech-poznan": "Polish club from the city of Poznań",
  "vitoria-guimaraes": "Portuguese club from the city of Guimarães",
  "gornik-zabrze": "Polish club; 14-time league champions from Zabrze",
  "aris-thessaloniki": "Greek club from the city of Thessaloniki",
  "buriram-united": "One of Thailand's most successful clubs",
  "melbourne-victory": "Australian club from Melbourne (A-League)",
  "mamelodi-sundowns": "South African club nicknamed 'The Brazilians'",
  "esperance-tunis": "Tunisian club; multiple-time African champions",
  "raja-casablanca": "Moroccan club from the city of Casablanca",
  "colo-colo": "Chile's most successful club; won 1991 Libertadores",
  "ldu-quito": "Ecuadorian club; won the 2008 Copa Libertadores",
};
