// E40 «Guess the Football Club Badge» — 100 club crests, 25/tier absolute difficulty.
// image: clubs/<slug>.png | VO: sfx/cb-<slug>.wav
// Difficulty judged by how recognizable the CREST/BADGE is to a random GLOBAL viewer
// (see quiz-difficulty-calibration): easy ~70-95%, medium ~35-70%, hard ~10-35%,
// impossible <10% (tail aimed <3%). Crest-only — no player faces, no kits, no sponsors.
// Global mix: Europe + South America + Asia/Africa/N.America. Zero Israeli clubs.
export const CLUBBADGES = [
  // ── EASY (25): globally-famous crests ──────────────────────────────
  { slug: "real-madrid", name: "Real Madrid", level: "easy" },
  { slug: "barcelona", name: "FC Barcelona", level: "easy" },
  { slug: "manchester-united", name: "Manchester United", level: "easy" },
  { slug: "liverpool", name: "Liverpool", level: "easy" },
  { slug: "bayern-munich", name: "Bayern Munich", level: "easy" },
  { slug: "juventus", name: "Juventus", level: "easy" },
  { slug: "paris-saint-germain", name: "Paris Saint-Germain", level: "easy" },
  { slug: "manchester-city", name: "Manchester City", level: "easy" },
  { slug: "chelsea", name: "Chelsea", level: "easy" },
  { slug: "arsenal", name: "Arsenal", level: "easy" },
  { slug: "ac-milan", name: "AC Milan", level: "easy" },
  { slug: "inter-milan", name: "Inter Milan", level: "easy" },
  { slug: "borussia-dortmund", name: "Borussia Dortmund", level: "easy" },
  { slug: "ajax", name: "Ajax", level: "easy" },
  { slug: "boca-juniors", name: "Boca Juniors", level: "easy" },
  { slug: "tottenham-hotspur", name: "Tottenham Hotspur", level: "easy" },
  { slug: "atletico-madrid", name: "Atlético Madrid", level: "easy" },
  { slug: "napoli", name: "Napoli", level: "easy" },
  { slug: "roma", name: "AS Roma", level: "easy" },
  { slug: "flamengo", name: "Flamengo", level: "easy" },
  { slug: "river-plate", name: "River Plate", level: "easy" },
  { slug: "porto", name: "FC Porto", level: "easy" },
  { slug: "benfica", name: "Benfica", level: "easy" },
  { slug: "olympique-marseille", name: "Olympique de Marseille", level: "easy" },
  { slug: "sevilla", name: "Sevilla", level: "easy" },

  // ── MEDIUM (25): well-known crests ─────────────────────────────────
  { slug: "celtic", name: "Celtic", level: "medium" },
  { slug: "rangers", name: "Rangers", level: "medium" },
  { slug: "galatasaray", name: "Galatasaray", level: "medium" },
  { slug: "fenerbahce", name: "Fenerbahçe", level: "medium" },
  { slug: "besiktas", name: "Beşiktaş", level: "medium" },
  { slug: "olympique-lyonnais", name: "Olympique Lyonnais", level: "medium" },
  { slug: "rb-leipzig", name: "RB Leipzig", level: "medium" },
  { slug: "bayer-leverkusen", name: "Bayer Leverkusen", level: "medium" },
  { slug: "sporting-cp", name: "Sporting CP", level: "medium" },
  { slug: "psv-eindhoven", name: "PSV Eindhoven", level: "medium" },
  { slug: "lazio", name: "Lazio", level: "medium" },
  { slug: "fiorentina", name: "Fiorentina", level: "medium" },
  { slug: "athletic-bilbao", name: "Athletic Bilbao", level: "medium" },
  { slug: "villarreal", name: "Villarreal", level: "medium" },
  { slug: "valencia", name: "Valencia", level: "medium" },
  { slug: "santos", name: "Santos", level: "medium" },
  { slug: "palmeiras", name: "Palmeiras", level: "medium" },
  { slug: "al-hilal", name: "Al Hilal", level: "medium" },
  { slug: "al-ahly", name: "Al Ahly", level: "medium" },
  { slug: "newcastle-united", name: "Newcastle United", level: "medium" },
  { slug: "leeds-united", name: "Leeds United", level: "medium" },
  { slug: "wolverhampton", name: "Wolverhampton Wanderers", level: "medium" },
  { slug: "leicester-city", name: "Leicester City", level: "medium" },
  { slug: "club-america", name: "Club América", level: "medium" },
  { slug: "al-nassr", name: "Al Nassr", level: "medium" },

  // ── HARD (25): serious-fan level ───────────────────────────────────
  { slug: "borussia-monchengladbach", name: "Borussia Mönchengladbach", level: "hard" },
  { slug: "real-betis", name: "Real Betis", level: "hard" },
  { slug: "real-sociedad", name: "Real Sociedad", level: "hard" },
  { slug: "eintracht-frankfurt", name: "Eintracht Frankfurt", level: "hard" },
  { slug: "atalanta", name: "Atalanta", level: "hard" },
  { slug: "torino", name: "Torino", level: "hard" },
  { slug: "lille", name: "Lille OSC", level: "hard" },
  { slug: "as-monaco", name: "AS Monaco", level: "hard" },
  { slug: "olympiacos", name: "Olympiacos", level: "hard" },
  { slug: "club-brugge", name: "Club Brugge", level: "hard" },
  { slug: "gremio", name: "Grêmio", level: "hard" },
  { slug: "independiente", name: "Independiente", level: "hard" },
  { slug: "corinthians", name: "Corinthians", level: "hard" },
  { slug: "red-bull-salzburg", name: "Red Bull Salzburg", level: "hard" },
  { slug: "zamalek", name: "Zamalek", level: "hard" },
  { slug: "wydad-casablanca", name: "Wydad Casablanca", level: "hard" },
  { slug: "al-ittihad", name: "Al-Ittihad", level: "hard" },
  { slug: "botafogo", name: "Botafogo", level: "hard" },
  { slug: "internacional", name: "Internacional", level: "hard" },
  { slug: "vasco-da-gama", name: "Vasco da Gama", level: "hard" },
  { slug: "racing-club", name: "Racing Club", level: "hard" },
  { slug: "atletico-mineiro", name: "Atlético Mineiro", level: "hard" },
  { slug: "monterrey", name: "Monterrey", level: "hard" },
  { slug: "persepolis", name: "Persepolis", level: "hard" },
  { slug: "nacional", name: "Club Nacional", level: "hard" },

  // ── IMPOSSIBLE (25): genuinely obscure, <5% recognize ──────────────
  { slug: "ludogorets-razgrad", name: "Ludogorets Razgrad", level: "impossible" },
  { slug: "molde-fk", name: "Molde FK", level: "impossible" },
  { slug: "hjk-helsinki", name: "HJK Helsinki", level: "impossible" },
  { slug: "qarabag", name: "Qarabağ FK", level: "impossible" },
  { slug: "malmo-ff", name: "Malmö FF", level: "impossible" },
  { slug: "cfr-cluj", name: "CFR Cluj", level: "impossible" },
  { slug: "slovan-bratislava", name: "Slovan Bratislava", level: "impossible" },
  { slug: "lech-poznan", name: "Lech Poznań", level: "impossible" },
  { slug: "buriram-united", name: "Buriram United", level: "impossible" },
  { slug: "melbourne-victory", name: "Melbourne Victory", level: "impossible" },
  { slug: "mamelodi-sundowns", name: "Mamelodi Sundowns", level: "impossible" },
  { slug: "esperance-tunis", name: "Espérance de Tunis", level: "impossible" },
  { slug: "colo-colo", name: "Colo-Colo", level: "impossible" },
  { slug: "ldu-quito", name: "LDU Quito", level: "impossible" },
  { slug: "tigres-uanl", name: "Tigres UANL", level: "impossible" },
  { slug: "estudiantes", name: "Estudiantes", level: "impossible" },
  { slug: "young-boys", name: "Young Boys", level: "impossible" },
  { slug: "rosenborg", name: "Rosenborg BK", level: "impossible" },
  { slug: "fc-copenhagen", name: "FC Copenhagen", level: "impossible" },
  { slug: "orlando-pirates", name: "Orlando Pirates", level: "impossible" },
  { slug: "al-sadd", name: "Al Sadd", level: "impossible" },
  { slug: "yokohama-f-marinos", name: "Yokohama F. Marinos", level: "impossible" },
  { slug: "ulsan-hyundai", name: "Ulsan HD", level: "impossible" },
  { slug: "tp-mazembe", name: "TP Mazembe", level: "impossible" },
  { slug: "barcelona-sc", name: "Barcelona SC", level: "impossible" },
];
