// E04 «Guess the Football Club» — 100 club crests, 25/tier absolute difficulty.
// image: clubs/<slug>.svg | VO: sfx/cb-<slug>.wav
// Difficulty judged by how recognizable the CREST/BADGE is to a random global viewer
// (see quiz-difficulty-calibration): easy ~70-95%, medium ~35-70%, hard ~10-35%,
// impossible <10% (tail aimed <3%). Crest-only — no player faces, no kits, no sponsors.
export const CLUBS = [
  // ── EASY (25): globally-famous crests ──────────────────────────────
  { slug: "real-madrid", name: "Real Madrid", level: "easy" },
  { slug: "barcelona", name: "FC Barcelona", level: "easy" },
  { slug: "manchester-united", name: "Manchester United", level: "easy" },
  { slug: "liverpool", name: "Liverpool", level: "easy" },
  { slug: "bayern-munich", name: "Bayern Munich", level: "easy" },
  { slug: "juventus", name: "Juventus", level: "easy" },
  { slug: "paris-saint-germain", name: "Paris Saint-Germain", level: "easy" },
  { slug: "manchester-city", name: "Manchester City", level: "easy" },
  { slug: "chelsea", name: "Chelsea", level: "easy" },
  { slug: "arsenal", name: "Arsenal", level: "easy" },
  { slug: "ac-milan", name: "AC Milan", level: "easy" },
  { slug: "inter-milan", name: "Inter Milan", level: "easy" },
  { slug: "borussia-dortmund", name: "Borussia Dortmund", level: "easy" },
  { slug: "ajax", name: "Ajax", level: "easy" },
  { slug: "boca-juniors", name: "Boca Juniors", level: "easy" },
  { slug: "tottenham-hotspur", name: "Tottenham Hotspur", level: "easy" },
  { slug: "atletico-madrid", name: "Atlético Madrid", level: "easy" },
  { slug: "napoli", name: "Napoli", level: "easy" },
  { slug: "roma", name: "AS Roma", level: "easy" },
  { slug: "flamengo", name: "Flamengo", level: "easy" },
  { slug: "river-plate", name: "River Plate", level: "easy" },
  { slug: "porto", name: "FC Porto", level: "easy" },
  { slug: "benfica", name: "Benfica", level: "easy" },
  { slug: "olympique-marseille", name: "Olympique de Marseille", level: "easy" },
  { slug: "sevilla", name: "Sevilla", level: "easy" },

  // ── MEDIUM (25): well-known crests ─────────────────────────────────
  { slug: "valencia", name: "Valencia", level: "medium" },
  { slug: "celtic", name: "Celtic", level: "medium" },
  { slug: "rangers", name: "Rangers", level: "medium" },
  { slug: "galatasaray", name: "Galatasaray", level: "medium" },
  { slug: "fenerbahce", name: "Fenerbahçe", level: "medium" },
  { slug: "olympique-lyonnais", name: "Olympique Lyonnais", level: "medium" },
  { slug: "rb-leipzig", name: "RB Leipzig", level: "medium" },
  { slug: "bayer-leverkusen", name: "Bayer Leverkusen", level: "medium" },
  { slug: "schalke-04", name: "Schalke 04", level: "medium" },
  { slug: "sporting-cp", name: "Sporting CP", level: "medium" },
  { slug: "psv-eindhoven", name: "PSV Eindhoven", level: "medium" },
  { slug: "feyenoord", name: "Feyenoord", level: "medium" },
  { slug: "lazio", name: "Lazio", level: "medium" },
  { slug: "fiorentina", name: "Fiorentina", level: "medium" },
  { slug: "athletic-bilbao", name: "Athletic Bilbao", level: "medium" },
  { slug: "villarreal", name: "Villarreal", level: "medium" },
  { slug: "santos", name: "Santos", level: "medium" },
  { slug: "corinthians", name: "Corinthians", level: "medium" },
  { slug: "palmeiras", name: "Palmeiras", level: "medium" },
  { slug: "al-hilal", name: "Al Hilal", level: "medium" },
  { slug: "al-ahly", name: "Al Ahly", level: "medium" },
  { slug: "west-ham-united", name: "West Ham United", level: "medium" },
  { slug: "newcastle-united", name: "Newcastle United", level: "medium" },
  { slug: "aston-villa", name: "Aston Villa", level: "medium" },
  { slug: "everton", name: "Everton", level: "medium" },

  // ── HARD (25): serious-fan level ───────────────────────────────────
  { slug: "borussia-monchengladbach", name: "Borussia Mönchengladbach", level: "hard" },
  { slug: "real-betis", name: "Real Betis", level: "hard" },
  { slug: "real-sociedad", name: "Real Sociedad", level: "hard" },
  { slug: "celta-vigo", name: "Celta Vigo", level: "hard" },
  { slug: "eintracht-frankfurt", name: "Eintracht Frankfurt", level: "hard" },
  { slug: "vfb-stuttgart", name: "VfB Stuttgart", level: "hard" },
  { slug: "vfl-wolfsburg", name: "VfL Wolfsburg", level: "hard" },
  { slug: "atalanta", name: "Atalanta", level: "hard" },
  { slug: "torino", name: "Torino", level: "hard" },
  { slug: "lille", name: "Lille OSC", level: "hard" },
  { slug: "as-monaco", name: "AS Monaco", level: "hard" },
  { slug: "shakhtar-donetsk", name: "Shakhtar Donetsk", level: "hard" },
  { slug: "dynamo-kyiv", name: "Dynamo Kyiv", level: "hard" },
  { slug: "red-star-belgrade", name: "Red Star Belgrade", level: "hard" },
  { slug: "olympiacos", name: "Olympiacos", level: "hard" },
  { slug: "panathinaikos", name: "Panathinaikos", level: "hard" },
  { slug: "club-brugge", name: "Club Brugge", level: "hard" },
  { slug: "anderlecht", name: "Anderlecht", level: "hard" },
  { slug: "gremio", name: "Grêmio", level: "hard" },
  { slug: "independiente", name: "Independiente", level: "hard" },
  { slug: "penarol", name: "Peñarol", level: "hard" },
  { slug: "urawa-red-diamonds", name: "Urawa Red Diamonds", level: "hard" },
  { slug: "kaizer-chiefs", name: "Kaizer Chiefs", level: "hard" },
  { slug: "zenit-saint-petersburg", name: "Zenit Saint Petersburg", level: "hard" },
  { slug: "sparta-prague", name: "Sparta Prague", level: "hard" },

  // ── IMPOSSIBLE (25): genuinely obscure, <5% recognize ──────────────
  { slug: "randers-fc", name: "Randers FC", level: "impossible" },
  { slug: "sivasspor", name: "Sivasspor", level: "impossible" },
  { slug: "cracovia", name: "Cracovia", level: "impossible" },
  { slug: "ludogorets-razgrad", name: "Ludogorets Razgrad", level: "impossible" },
  { slug: "molde-fk", name: "Molde FK", level: "impossible" },
  { slug: "ifk-goteborg", name: "IFK Göteborg", level: "impossible" },
  { slug: "hjk-helsinki", name: "HJK Helsinki", level: "impossible" },
  { slug: "qarabag", name: "Qarabağ FK", level: "impossible" },
  { slug: "malmo-ff", name: "Malmö FF", level: "impossible" },
  { slug: "cfr-cluj", name: "CFR Cluj", level: "impossible" },
  { slug: "slovan-bratislava", name: "Slovan Bratislava", level: "impossible" },
  { slug: "riga-fc", name: "Riga FC", level: "impossible" },
  { slug: "dundalk", name: "Dundalk FC", level: "impossible" },
  { slug: "valletta", name: "Valletta FC", level: "impossible" },
  { slug: "lech-poznan", name: "Lech Poznań", level: "impossible" },
  { slug: "vitoria-guimaraes", name: "Vitória de Guimarães", level: "impossible" },
  { slug: "gornik-zabrze", name: "Górnik Zabrze", level: "impossible" },
  { slug: "aris-thessaloniki", name: "Aris Thessaloniki", level: "impossible" },
  { slug: "buriram-united", name: "Buriram United", level: "impossible" },
  { slug: "melbourne-victory", name: "Melbourne Victory", level: "impossible" },
  { slug: "mamelodi-sundowns", name: "Mamelodi Sundowns", level: "impossible" },
  { slug: "esperance-tunis", name: "Espérance de Tunis", level: "impossible" },
  { slug: "raja-casablanca", name: "Raja Casablanca", level: "impossible" },
  { slug: "colo-colo", name: "Colo-Colo", level: "impossible" },
  { slug: "ldu-quito", name: "LDU Quito", level: "impossible" },
];
