// «Guess the Cocktail» — GuessSync · E64 · did-you-know facts, ≤70 chars, verified true.
// Informational trivia only: base spirit / origin. Not promoting alcohol.
export const COCKTAIL_FACTS = {
  // EASY
  "margarita": "Tequila-based classic served with a salted glass rim",
  "mojito": "A Cuban highball built on white rum, lime and mint",
  "martini": "Made from gin and dry vermouth; garnished with an olive",
  "cosmopolitan": "Vodka, triple sec, cranberry and lime; a 1990s icon",
  "pinacolada": "Puerto Rico's rum, coconut cream and pineapple blend",
  "daiquiri": "A simple Cuban mix of rum, lime juice and sugar",
  "bloodymary": "Vodka and spiced tomato juice, often a brunch drink",
  "oldfashioned": "One of the oldest cocktails: whiskey, sugar and bitters",
  "longislandicedtea": "Blends five spirits yet tastes like iced tea",
  "negroni": "Equal parts gin, Campari and sweet vermouth, from Italy",
  "manhattan": "Whiskey and sweet vermouth, stirred with bitters",
  "maitai": "A tiki classic built on rum and orgeat almond syrup",
  "whiskeysour": "Whiskey shaken with lemon juice and sugar",
  "moscowmule": "Vodka and ginger beer served in a copper mug",
  "gintonic": "Gin and tonic water, born from anti-malaria quinine",
  "tequilasunrise": "Tequila and orange juice with a grenadine 'sunrise'",
  "sexonthebeach": "Vodka, peach schnapps and fruit juices",
  "screwdriver": "Just vodka and orange juice; a simple highball",
  "mimosa": "Champagne topped up with orange juice, a brunch staple",
  "bellini": "Prosecco blended with white peach purée, from Venice",
  "sangria": "A Spanish punch of red wine, fruit and sweetener",
  "cubalibre": "Rum and cola with lime; 'Free Cuba' in Spanish",
  "espressomartini": "Vodka shaken with coffee liqueur and espresso",
  "aperolspritz": "Aperol, prosecco and soda; a bright Italian aperitif",
  "tomcollins": "A tall gin sour lengthened with soda water",
  // MEDIUM
  "caipirinha": "Brazil's national drink, made with cachaça and lime",
  "paloma": "A Mexican mix of tequila and grapefruit soda",
  "french75": "Gin and Champagne named for a WWI field gun",
  "darkandstormy": "Dark rum floated over spicy ginger beer",
  "whiterussian": "Vodka, coffee liqueur and cream over ice",
  "blackrussian": "Just vodka and coffee liqueur; no cream",
  "mintjulep": "Bourbon and mint; the drink of the Kentucky Derby",
  "singaporesling": "A gin sling created at Singapore's Raffles Hotel",
  "amarettosour": "Almond-flavored amaretto shaken with lemon",
  "kirroyale": "Champagne with a dash of crème de cassis",
  "gimlet": "Gin and lime cordial, once used to fight scurvy",
  "robroy": "A Manhattan made with Scotch instead of rye",
  "sidecar": "Cognac, orange liqueur and lemon in a sugared glass",
  "piscosour": "Peru's pisco brandy shaken with lime and egg white",
  "zombie": "A potent tiki blend of several rums and fruit juices",
  "bluehawaiian": "Rum and blue curaçao with pineapple, a tiki drink",
  "grasshopper": "A minty dessert cocktail with crème de menthe and cream",
  "mudslide": "Vodka, coffee liqueur and Irish cream over ice",
  "hurricane": "A rum punch that began in New Orleans bars",
  "painkiller": "Rum, pineapple, orange and coconut cream",
  "americano": "Campari and sweet vermouth lengthened with soda",
  "ginfizz": "A gin sour shaken with soda for a fizzy head",
  "harveywallbanger": "A Screwdriver topped with Galliano liqueur",
  "bramble": "Gin and lemon drizzled with blackberry liqueur",
  "midorisour": "Bright-green melon liqueur shaken with lemon",
  // HARD
  "boulevardier": "A whiskey Negroni: bourbon, Campari and vermouth",
  "penicillin": "A modern classic of Scotch, honey, lemon and ginger",
  "beesknees": "A Prohibition gin sour sweetened with honey",
  "cloverclub": "A pre-Prohibition gin sour with raspberry and egg white",
  "junglebird": "A tiki drink of dark rum and bitter Campari",
  "paperplane": "Equal parts bourbon, Aperol, Amaro and lemon",
  "martinez": "A gin-and-vermouth ancestor of the modern Martini",
  "southside": "A gin sour with mint, like a Mojito made with gin",
  "brandyalexander": "A creamy blend of cognac and crème de cacao",
  "rustynail": "Scotch whisky sweetened with Drambuie liqueur",
  "godfather": "Scotch whisky combined with almond amaretto",
  "bloodandsand": "Scotch, cherry liqueur and orange juice",
  "jackrose": "Applejack brandy with lime and grenadine",
  "marypickford": "A 1920s Havana drink of rum, pineapple and grenadine",
  "hemingwaydaiquiri": "A rum Daiquiri with grapefruit and maraschino",
  "goldrush": "A bourbon sour sweetened with honey syrup",
  "sherrycobbler": "Sherry shaken with sugar and citrus over crushed ice",
  "tuxedo": "A dry gin-and-vermouth cousin of the Martinez",
  "bijou": "Gin, sweet vermouth and green Chartreuse liqueur",
  "whiskeysmash": "Bourbon muddled with lemon and fresh mint",
  "vesper": "James Bond's mix of gin, vodka and Lillet aperitif",
  "tomandjerry": "A warm eggnog-like drink of rum and brandy",
  "scofflaw": "A Prohibition-era rye whiskey sour with grenadine",
  "rememberthemaine": "A rye cocktail flavored with absinthe and cherry",
  "betweenthesheets": "Rum, cognac and orange liqueur with lemon",
  // IMPOSSIBLE
  "sazerac": "New Orleans' rye whiskey drink rinsed with absinthe",
  "aviation": "A gin sour tinted violet by crème de violette",
  "lastword": "Equal parts gin, Chartreuse, maraschino and lime",
  "corpsereviver": "A gin cocktail once meant as a morning pick-me-up",
  "vieuxcarre": "A New Orleans blend of rye, cognac and vermouth",
  "hankypanky": "A gin Martini touched with bitter Fernet-Branca",
  "ramosginfizz": "A gin fizz shaken long with cream and egg white",
  "chartreuseswizzle": "Green Chartreuse swizzled with pineapple and lime",
  "bamboo": "A light aperitif of dry sherry and vermouth",
  "saturn": "A gin tiki drink with passion fruit and orgeat",
  "sufferingbastard": "A gin-and-brandy hangover cure with ginger beer",
  "queensparkswizzle": "A rum swizzle with mint from Trinidad",
  "armynavy": "A gin sour built on almond orgeat syrup",
  "brownderby": "Bourbon with grapefruit juice and honey",
  "twentiethcentury": "Gin, cocoa liqueur and Lillet, named for a train",
  "widowskiss": "An apple brandy drink with Chartreuse and Bénédictine",
  "cornandoil": "Blackstrap rum sweetened with falernum and lime",
  "trinidadsour": "An unusual sour built mostly on Angostura bitters",
  "nakedandfamous": "Equal parts mezcal, Chartreuse, Aperol and lime",
  "divisionbell": "A mezcal cousin of the Last Word with Aperol",
  "finalward": "A rye whiskey riff on the classic Last Word",
  "whitenegroni": "A Negroni with Suze and Lillet in place of Campari",
  "oaxacaoldfashioned": "An Old Fashioned made with tequila and mezcal",
  "ginbasilsmash": "Gin shaken hard with lemon and fresh basil",
  "airmail": "A rum-and-honey drink topped with Champagne",
};
