// «Guess the Cocktail» — GuessSync · E64 · 100 cocktails (25/tier) · real photos from Wikimedia Commons
// Informational trivia (not promoting alcohol). Tiered by real-world recognizability:
// easy (Margarita/Mojito/Martini) ← impossible (obscure classics like Corpse Reviver/Vieux Carré).
export const COCKTAILS = [
  // EASY (25) — household-name drinks
  { slug: "margarita", name: "Margarita", level: "easy" },
  { slug: "mojito", name: "Mojito", level: "easy" },
  { slug: "martini", name: "Martini", level: "easy" },
  { slug: "cosmopolitan", name: "Cosmopolitan", level: "easy" },
  { slug: "pinacolada", name: "Piña Colada", level: "easy" },
  { slug: "daiquiri", name: "Daiquiri", level: "easy" },
  { slug: "bloodymary", name: "Bloody Mary", level: "easy" },
  { slug: "oldfashioned", name: "Old Fashioned", level: "easy" },
  { slug: "longislandicedtea", name: "Long Island Iced Tea", level: "easy" },
  { slug: "negroni", name: "Negroni", level: "easy" },
  { slug: "manhattan", name: "Manhattan", level: "easy" },
  { slug: "maitai", name: "Mai Tai", level: "easy" },
  { slug: "whiskeysour", name: "Whiskey Sour", level: "easy" },
  { slug: "moscowmule", name: "Moscow Mule", level: "easy" },
  { slug: "gintonic", name: "Gin and Tonic", level: "easy" },
  { slug: "tequilasunrise", name: "Tequila Sunrise", level: "easy" },
  { slug: "sexonthebeach", name: "Sex on the Beach", level: "easy" },
  { slug: "screwdriver", name: "Screwdriver", level: "easy" },
  { slug: "mimosa", name: "Mimosa", level: "easy" },
  { slug: "bellini", name: "Bellini", level: "easy" },
  { slug: "sangria", name: "Sangria", level: "easy" },
  { slug: "cubalibre", name: "Cuba Libre", level: "easy" },
  { slug: "espressomartini", name: "Espresso Martini", level: "easy" },
  { slug: "aperolspritz", name: "Aperol Spritz", level: "easy" },
  { slug: "tomcollins", name: "Tom Collins", level: "easy" },
  // MEDIUM (25) — widely known, one step past the classics
  { slug: "caipirinha", name: "Caipirinha", level: "medium" },
  { slug: "paloma", name: "Paloma", level: "medium" },
  { slug: "french75", name: "French 75", level: "medium" },
  { slug: "darkandstormy", name: "Dark 'n' Stormy", level: "medium" },
  { slug: "whiterussian", name: "White Russian", level: "medium" },
  { slug: "blackrussian", name: "Black Russian", level: "medium" },
  { slug: "mintjulep", name: "Mint Julep", level: "medium" },
  { slug: "singaporesling", name: "Singapore Sling", level: "medium" },
  { slug: "amarettosour", name: "Amaretto Sour", level: "medium" },
  { slug: "kirroyale", name: "Kir Royale", level: "medium" },
  { slug: "gimlet", name: "Gimlet", level: "medium" },
  { slug: "robroy", name: "Rob Roy", level: "medium" },
  { slug: "sidecar", name: "Sidecar", level: "medium" },
  { slug: "piscosour", name: "Pisco Sour", level: "medium" },
  { slug: "zombie", name: "Zombie", level: "medium" },
  { slug: "bluehawaiian", name: "Blue Hawaiian", level: "medium" },
  { slug: "grasshopper", name: "Grasshopper", level: "medium" },
  { slug: "mudslide", name: "Mudslide", level: "medium" },
  { slug: "hurricane", name: "Hurricane", level: "medium" },
  { slug: "painkiller", name: "Painkiller", level: "medium" },
  { slug: "americano", name: "Americano", level: "medium" },
  { slug: "ginfizz", name: "Gin Fizz", level: "medium" },
  { slug: "harveywallbanger", name: "Harvey Wallbanger", level: "medium" },
  { slug: "bramble", name: "Bramble", level: "medium" },
  { slug: "midorisour", name: "Midori Sour", level: "medium" },
  // HARD (25) — classics known mainly to enthusiasts
  { slug: "boulevardier", name: "Boulevardier", level: "hard" },
  { slug: "penicillin", name: "Penicillin", level: "hard" },
  { slug: "beesknees", name: "Bee's Knees", level: "hard" },
  { slug: "cloverclub", name: "Clover Club", level: "hard" },
  { slug: "junglebird", name: "Jungle Bird", level: "hard" },
  { slug: "paperplane", name: "Paper Plane", level: "hard" },
  { slug: "martinez", name: "Martinez", level: "hard" },
  { slug: "southside", name: "Southside", level: "hard" },
  { slug: "brandyalexander", name: "Brandy Alexander", level: "hard" },
  { slug: "rustynail", name: "Rusty Nail", level: "hard" },
  { slug: "godfather", name: "Godfather", level: "hard" },
  { slug: "bloodandsand", name: "Blood and Sand", level: "hard" },
  { slug: "jackrose", name: "Jack Rose", level: "hard" },
  { slug: "marypickford", name: "Mary Pickford", level: "hard" },
  { slug: "hemingwaydaiquiri", name: "Hemingway Daiquiri", level: "hard" },
  { slug: "goldrush", name: "Gold Rush", level: "hard" },
  { slug: "sherrycobbler", name: "Sherry Cobbler", level: "hard" },
  { slug: "tuxedo", name: "Tuxedo", level: "hard" },
  { slug: "bijou", name: "Bijou", level: "hard" },
  { slug: "whiskeysmash", name: "Whiskey Smash", level: "hard" },
  { slug: "vesper", name: "Vesper", level: "hard" },
  { slug: "tomandjerry", name: "Tom and Jerry", level: "hard" },
  { slug: "scofflaw", name: "Scofflaw", level: "hard" },
  { slug: "rememberthemaine", name: "Remember the Maine", level: "hard" },
  { slug: "betweenthesheets", name: "Between the Sheets", level: "hard" },
  // IMPOSSIBLE (25) — obscure classic & modern-classic cocktails
  { slug: "sazerac", name: "Sazerac", level: "impossible" },
  { slug: "aviation", name: "Aviation", level: "impossible" },
  { slug: "lastword", name: "Last Word", level: "impossible" },
  { slug: "corpsereviver", name: "Corpse Reviver No. 2", level: "impossible" },
  { slug: "vieuxcarre", name: "Vieux Carré", level: "impossible" },
  { slug: "hankypanky", name: "Hanky Panky", level: "impossible" },
  { slug: "ramosginfizz", name: "Ramos Gin Fizz", level: "impossible" },
  { slug: "chartreuseswizzle", name: "Chartreuse Swizzle", level: "impossible" },
  { slug: "bamboo", name: "Bamboo", level: "impossible" },
  { slug: "saturn", name: "Saturn", level: "impossible" },
  { slug: "sufferingbastard", name: "Suffering Bastard", level: "impossible" },
  { slug: "queensparkswizzle", name: "Queen's Park Swizzle", level: "impossible" },
  { slug: "armynavy", name: "Army & Navy", level: "impossible" },
  { slug: "brownderby", name: "Brown Derby", level: "impossible" },
  { slug: "twentiethcentury", name: "Twentieth Century", level: "impossible" },
  { slug: "widowskiss", name: "Widow's Kiss", level: "impossible" },
  { slug: "cornandoil", name: "Corn 'n' Oil", level: "impossible" },
  { slug: "trinidadsour", name: "Trinidad Sour", level: "impossible" },
  { slug: "nakedandfamous", name: "Naked and Famous", level: "impossible" },
  { slug: "divisionbell", name: "Division Bell", level: "impossible" },
  { slug: "finalward", name: "Final Ward", level: "impossible" },
  { slug: "whitenegroni", name: "White Negroni", level: "impossible" },
  { slug: "oaxacaoldfashioned", name: "Oaxaca Old Fashioned", level: "impossible" },
  { slug: "ginbasilsmash", name: "Gin Basil Smash", level: "impossible" },
  { slug: "airmail", name: "Air Mail", level: "impossible" },
];
