// E91 «Guess the Country on the Map» — true facts, each ≤70 chars.
export const COUNTRYMAP_FACTS = {
  usa: "Has 50 states across 6 time zones.",
  brazil: "Home to most of the Amazon rainforest.",
  australia: "Both a country and a continent.",
  russia: "Spans 11 time zones, the most of any country.",
  china: "Home to the Great Wall, over 13,000 miles long.",
  egypt: "Home to the last surviving ancient world wonder.",
  canada: "Has the world's longest coastline.",
  india: "Home to over 1.4 billion people.",
  japan: "Made up of over 14,000 islands.",
  mexico: "Gave the world chocolate and chili peppers.",
  france: "The most visited country in the world.",
  "united-kingdom": "Made up of four nations in one country.",
  italy: "Shaped like a high-heeled boot.",
  spain: "Home to the world's oldest restaurant.",
  germany: "Has over 1,500 different types of sausage.",
  "saudi-arabia": "Holds the largest sand desert on Earth.",
  "south-africa": "Has three capital cities.",
  argentina: "Home to the widest river in the world.",
  greenland: "The world's largest island, mostly ice-covered.",
  madagascar: "Over 90% of its wildlife exists nowhere else.",
  "new-zealand": "Home to far more sheep than people.",
  turkey: "Sits on two continents, Europe and Asia.",
  norway: "Home to the fjords and the midnight sun.",
  sweden: "Has over 267,000 islands.",
  "south-korea": "One of the most wired countries on Earth.",
  chile: "The world's longest north-south country.",
  peru: "Home to the lost city of Machu Picchu.",
  colombia: "Produces more emeralds than any other country.",
  indonesia: "The world's largest archipelago nation.",
  thailand: "Its name means 'land of the free'; once called Siam.",
  vietnam: "Shaped like the letter S.",
  iran: "Formerly known as Persia.",
  iraq: "Home to ancient Mesopotamia.",
  pakistan: "Home to K2, the world's second-highest peak.",
  afghanistan: "Known as the crossroads of Central Asia.",
  kazakhstan: "The world's largest landlocked country.",
  mongolia: "Has the lowest population density on Earth.",
  nigeria: "Africa's most populous country.",
  kenya: "Home to the Great Rift Valley.",
  ethiopia: "Believed to be the birthplace of coffee.",
  morocco: "Home to North Africa's highest peak, Mount Toubkal.",
  algeria: "Africa's largest country by land area.",
  libya: "Holds one of the hottest recorded temperatures.",
  sudan: "Home to more pyramids than Egypt.",
  ukraine: "Europe's largest country by area.",
  poland: "Home to Europe's largest primeval forest.",
  finland: "Home to more saunas than cars.",
  greece: "Has more archaeological museums than any nation.",
  portugal: "Europe's oldest nation-state.",
  cuba: "Famous for classic 1950s American cars.",
  chad: "Named after Lake Chad, once one of Africa's largest.",
  niger: "Named after the Niger River.",
  mali: "Home to the ancient city of Timbuktu.",
  namibia: "Home to the world's oldest desert.",
  botswana: "Almost 40% of its land is protected wildlife.",
  zambia: "Home to Victoria Falls, shared with Zimbabwe.",
  mozambique: "Named after an early Arab trader, Musa Al Big.",
  tanzania: "Home to Africa's tallest peak, Kilimanjaro.",
  myanmar: "Formerly known as Burma.",
  nepal: "Home to Mount Everest, the world's tallest peak.",
  "sri-lanka": "Formerly known as Ceylon.",
  yemen: "Home to Socotra, an island of alien-looking trees.",
  oman: "One of the oldest independent states in Arabia.",
  uzbekistan: "One of only two doubly landlocked countries.",
  turkmenistan: "Home to the fiery Darvaza gas crater.",
  belarus: "Nearly 40% of its land is forest.",
  romania: "Home to Bran Castle, tied to the Dracula legend.",
  hungary: "Home to Europe's largest thermal lake.",
  "czech-republic": "Has more castles per square mile than anywhere.",
  austria: "Birthplace of composer Wolfgang Mozart.",
  switzerland: "Home to over 1,500 lakes.",
  ecuador: "Named for sitting on the Earth's equator.",
  bolivia: "Home to the world's largest salt flat.",
  paraguay: "One of only two landlocked South American nations.",
  "papua-new-guinea": "Home to over 800 native languages.",
  bhutan: "Measures success by Gross National Happiness.",
  brunei: "Almost entirely surrounded by Malaysia's Sarawak.",
  djibouti: "Home to one of the saltiest lakes on Earth.",
  eritrea: "Once part of Ethiopia until 1993.",
  gambia: "Africa's smallest mainland country.",
  "guinea-bissau": "Home to the Bijagos, an archipelago of 88 islands.",
  "equatorial-guinea": "The only African nation where Spanish is official.",
  togo: "One of Africa's narrowest countries.",
  benin: "Widely regarded as the birthplace of Vodun religion.",
  lesotho: "Entirely surrounded by South Africa.",
  eswatini: "One of the world's last absolute monarchies.",
  burundi: "One of the most densely populated African nations.",
  rwanda: "Known as the Land of a Thousand Hills.",
  moldova: "Home to the world's largest wine cellar.",
  montenegro: "Its name means 'Black Mountain'.",
  "north-macedonia": "Home to one of Europe's oldest lakes, Ohrid.",
  luxembourg: "One of the world's richest countries per person.",
  andorra: "Nestled entirely within the Pyrenees mountains.",
  liechtenstein: "One of only two doubly landlocked countries.",
  suriname: "South America's smallest independent country.",
  guyana: "The only English-speaking country in South America.",
  belize: "Home to the Great Blue Hole, a giant sinkhole.",
  "timor-leste": "One of Asia's youngest independent nations.",
  vanuatu: "Home to some of the world's most active volcanoes.",
  "solomon-islands": "A chain of nearly 1,000 Pacific islands.",
};
