// E149 «Guess the Dance by Emoji» — 100 dances · 25/tier · clue = plain Unicode emoji (mirrors E125 isEmoji rendering)
// VO: sfx/e149-<id>.wav ("It's <Dance>!"). Born FAIR: every emoji fairly leads via name-rebus or iconic prop/origin.
// No bare color-blob filler, no flags/ZWJ/FE0F/skin-tone; single codepoint only, each exists at public/openmoji/<HEX>.svg.
export const DANCE_EMOJI = [
  // ===== EASY (25) — globally known =====
  { id: "ballet", title: "Ballet", emojis: "🩰💃", level: "easy" },
  { id: "salsa", title: "Salsa", emojis: "🌶💃", level: "easy" },
  { id: "tango", title: "Tango", emojis: "🌹💃", level: "easy" },
  { id: "breakdance", title: "Breakdance", emojis: "🌀🕺", level: "easy" },
  { id: "hip-hop", title: "Hip-Hop", emojis: "🎤🕺", level: "easy" },
  { id: "moonwalk", title: "Moonwalk", emojis: "🌙🕺", level: "easy" },
  { id: "disco", title: "Disco", emojis: "🪩🕺", level: "easy" },
  { id: "twist", title: "Twist", emojis: "🌪🕺", level: "easy" },
  { id: "waltz", title: "Waltz", emojis: "🎼💃", level: "easy" },
  { id: "tap-dance", title: "Tap Dance", emojis: "👞🎵", level: "easy" },
  { id: "belly-dance", title: "Belly Dance", emojis: "🪙💃", level: "easy" },
  { id: "flamenco", title: "Flamenco", emojis: "🪭💃", level: "easy" },
  { id: "samba", title: "Samba", emojis: "🥁🕺", level: "easy" },
  { id: "line-dance", title: "Line Dance", emojis: "🤠👢", level: "easy" },
  { id: "ballroom", title: "Ballroom", emojis: "💃🕺", level: "easy" },
  { id: "macarena", title: "Macarena", emojis: "📻🕺", level: "easy" },
  { id: "conga", title: "Conga", emojis: "🐍💃", level: "easy" },
  { id: "cha-cha", title: "Cha-Cha", emojis: "👯💃", level: "easy" },
  { id: "zumba", title: "Zumba", emojis: "🔥💃", level: "easy" },
  { id: "charleston", title: "Charleston", emojis: "🎷💃", level: "easy" },
  { id: "can-can", title: "Can-Can", emojis: "🦵🎩", level: "easy" },
  { id: "jive", title: "Jive", emojis: "🎸🕺", level: "easy" },
  { id: "robot", title: "Robot", emojis: "🤖🕺", level: "easy" },
  { id: "limbo", title: "Limbo", emojis: "🎋💃", level: "easy" },
  { id: "hula", title: "Hula", emojis: "🌺🌴", level: "easy" },

  // ===== MEDIUM (25) — well-known styles =====
  { id: "foxtrot", title: "Foxtrot", emojis: "🦊👣", level: "medium" },
  { id: "rumba", title: "Rumba", emojis: "🪇💃", level: "medium" },
  { id: "mambo", title: "Mambo", emojis: "🎺🕺", level: "medium" },
  { id: "bhangra", title: "Bhangra", emojis: "🥁🌾", level: "medium" },
  { id: "bollywood", title: "Bollywood", emojis: "🎬🕺", level: "medium" },
  { id: "irish-stepdance", title: "Irish Stepdance", emojis: "👞☘", level: "medium" },
  { id: "polka", title: "Polka", emojis: "🪗💃", level: "medium" },
  { id: "capoeira", title: "Capoeira", emojis: "🥋🎶", level: "medium" },
  { id: "krump", title: "Krump", emojis: "💥🕺", level: "medium" },
  { id: "vogue", title: "Vogue", emojis: "📸💃", level: "medium" },
  { id: "jitterbug", title: "Jitterbug", emojis: "🐛🕺", level: "medium" },
  { id: "lindy-hop", title: "Lindy Hop", emojis: "🐰🕺", level: "medium" },
  { id: "swing", title: "Swing", emojis: "🎹🕺", level: "medium" },
  { id: "quickstep", title: "Quickstep", emojis: "⚡💃", level: "medium" },
  { id: "jazz-dance", title: "Jazz Dance", emojis: "🎷🕺", level: "medium" },
  { id: "contemporary", title: "Contemporary", emojis: "🎭💃", level: "medium" },
  { id: "clogging", title: "Clogging", emojis: "🪵👞", level: "medium" },
  { id: "square-dance", title: "Square Dance", emojis: "🤠🎻", level: "medium" },
  { id: "polonaise", title: "Polonaise", emojis: "👑💃", level: "medium" },
  { id: "mazurka", title: "Mazurka", emojis: "🐎💃", level: "medium" },
  { id: "gavotte", title: "Gavotte", emojis: "👑🎻", level: "medium" },
  { id: "minuet", title: "Minuet", emojis: "🕯💃", level: "medium" },
  { id: "bolero", title: "Bolero", emojis: "🥁💃", level: "medium" },
  { id: "paso-doble", title: "Paso Doble", emojis: "🐂💃", level: "medium" },
  { id: "viennese-waltz", title: "Viennese Waltz", emojis: "🏰💃", level: "medium" },

  // ===== HARD (25) — regional/folk, still nameable =====
  { id: "tarantella", title: "Tarantella", emojis: "🕷💃", level: "hard" },
  { id: "kathak", title: "Kathak", emojis: "🔔💃", level: "hard" },
  { id: "bharatanatyam", title: "Bharatanatyam", emojis: "🪔💃", level: "hard" },
  { id: "kabuki", title: "Kabuki", emojis: "🎭👘", level: "hard" },
  { id: "highland-fling", title: "Highland Fling", emojis: "🗡💃", level: "hard" },
  { id: "morris-dance", title: "Morris Dance", emojis: "🔔👣", level: "hard" },
  { id: "hornpipe", title: "Hornpipe", emojis: "⚓💃", level: "hard" },
  { id: "irish-jig", title: "Irish Jig", emojis: "🎻🍀", level: "hard" },
  { id: "scottish-reel", title: "Scottish Reel", emojis: "🎣💃", level: "hard" },
  { id: "hopak", title: "Hopak", emojis: "⚔💃", level: "hard" },
  { id: "kalinka", title: "Kalinka", emojis: "🪆💃", level: "hard" },
  { id: "troika", title: "Troika", emojis: "🐴💃", level: "hard" },
  { id: "sirtaki", title: "Sirtaki", emojis: "🍽💃", level: "hard" },
  { id: "haka", title: "Haka", emojis: "👅💃", level: "hard" },
  { id: "gumboot", title: "Gumboot", emojis: "👢🎶", level: "hard" },
  { id: "tinikling", title: "Tinikling", emojis: "🎋🐦", level: "hard" },
  { id: "dabke", title: "Dabke", emojis: "👣🕌", level: "hard" },
  { id: "zeibekiko", title: "Zeibekiko", emojis: "🦅💃", level: "hard" },
  { id: "fandango", title: "Fandango", emojis: "🪕💃", level: "hard" },
  { id: "seguidilla", title: "Seguidilla", emojis: "🪭🎵", level: "hard" },
  { id: "jarabe-tapatio", title: "Jarabe Tapatío", emojis: "🎩🌵", level: "hard" },
  { id: "quebradita", title: "Quebradita", emojis: "🤠🎺", level: "hard" },
  { id: "cumbia", title: "Cumbia", emojis: "🥁🕯", level: "hard" },
  { id: "merengue", title: "Merengue", emojis: "🍰💃", level: "hard" },
  { id: "carimbo", title: "Carimbó", emojis: "🥁🌴", level: "hard" },

  // ===== IMPOSSIBLE (25) — obscure but real & nameable =====
  { id: "furiant", title: "Furiant", emojis: "🔥🎻", level: "impossible" },
  { id: "czardas", title: "Csárdás", emojis: "🗡🎻", level: "impossible" },
  { id: "kolo", title: "Kolo", emojis: "🔗💃", level: "impossible" },
  { id: "hora", title: "Hora", emojis: "🤝💃", level: "impossible" },
  { id: "tamburica", title: "Tamburica", emojis: "🪕🎵", level: "impossible" },
  { id: "lezginka", title: "Lezginka", emojis: "🦅🗡", level: "impossible" },
  { id: "attan", title: "Attan", emojis: "⚔🌾", level: "impossible" },
  { id: "khattak", title: "Khattak", emojis: "🗡🌀", level: "impossible" },
  { id: "kuchipudi", title: "Kuchipudi", emojis: "🪔🎶", level: "impossible" },
  { id: "odissi", title: "Odissi", emojis: "🐚💃", level: "impossible" },
  { id: "manipuri", title: "Manipuri", emojis: "🥁🌸", level: "impossible" },
  { id: "mohiniyattam", title: "Mohiniyattam", emojis: "🌺💃", level: "impossible" },
  { id: "yangge", title: "Yangge", emojis: "🥁🏮", level: "impossible" },
  { id: "dragon-dance", title: "Dragon Dance", emojis: "🐉🎶", level: "impossible" },
  { id: "lion-dance", title: "Lion Dance", emojis: "🦁🥁", level: "impossible" },
  { id: "fan-dance", title: "Fan Dance", emojis: "🪭🌸", level: "impossible" },
  { id: "buchaechum", title: "Buchaechum", emojis: "🪭🌊", level: "impossible" },
  { id: "talchum", title: "Talchum", emojis: "🎭🥁", level: "impossible" },
  { id: "bon-odori", title: "Bon Odori", emojis: "🏮💃", level: "impossible" },
  { id: "eisa", title: "Eisa", emojis: "🥁🌺", level: "impossible" },
  { id: "adumu", title: "Adumu", emojis: "🦵🌍", level: "impossible" },
  { id: "agbadza", title: "Agbadza", emojis: "🥁🌍", level: "impossible" },
  { id: "kizomba", title: "Kizomba", emojis: "💞💃", level: "impossible" },
  { id: "kuduro", title: "Kuduro", emojis: "🔊💃", level: "impossible" },
  { id: "gwara-gwara", title: "Gwara Gwara", emojis: "🎧💃", level: "impossible" },
];
