// E149 emoji-dance facts — one verified <=70-char origin fact per dance, shown on reveal.
export const DANCE_EMOJI_FACTS = {
  // EASY
  "ballet": "Formal dance born in 15th-century Italian Renaissance courts.",
  "salsa": "Latin dance from 1970s New York, rooted in Cuban son.",
  "tango": "Born in 1880s Buenos Aires and Montevideo river ports.",
  "breakdance": "B-boying began in 1970s Bronx hip-hop block parties.",
  "hip-hop": "Street dance from 1970s Bronx, New York hip-hop culture.",
  "moonwalk": "Glide step popularized by Michael Jackson in 1983.",
  "disco": "Nightclub dance craze of the 1970s United States.",
  "twist": "1960s craze launched by Chubby Checker's hit song.",
  "waltz": "Ballroom dance from 18th-century Austria and Germany.",
  "tap-dance": "American style blending Irish jig and African rhythms.",
  "belly-dance": "Middle Eastern solo dance with coin-hip shimmies.",
  "flamenco": "Passionate art from Andalusia, southern Spain.",
  "samba": "Brazil's carnival dance with Afro-Brazilian roots.",
  "line-dance": "Rows of dancers step in unison; US country halls.",
  "ballroom": "Partner dances of European courts and salons.",
  "macarena": "1990s line dance from Spanish duo Los del Río.",
  "conga": "Cuban carnival line dance of African origin.",
  "cha-cha": "Cuban dance from the early 1950s, offshoot of mambo.",
  "zumba": "Fitness dance created in Colombia in the 1990s.",
  "charleston": "1920s Jazz Age craze named for Charleston, S.C.",
  "can-can": "High-kicking music-hall dance of 1840s Paris.",
  "jive": "Lively 1930s-40s swing dance from the USA.",
  "robot": "Miming dance style from 1960s-70s US funk scene.",
  "limbo": "Trinidad dance: bend back under a lowering bar.",
  "hula": "Native Hawaiian dance telling stories with the hands.",

  // MEDIUM
  "foxtrot": "Smooth 1910s American ballroom dance.",
  "rumba": "Slow, romantic ballroom dance of Cuban origin.",
  "mambo": "Cuban dance that swept 1950s dance halls.",
  "bhangra": "Punjabi harvest dance from northern India.",
  "bollywood": "Film-dance style from India's Hindi cinema.",
  "irish-stepdance": "Rigid-torso dance from Ireland, fast footwork.",
  "polka": "Bouncy couple dance from 19th-century Bohemia.",
  "capoeira": "Afro-Brazilian art blending dance and martial arts.",
  "krump": "Energetic street dance from 2000s Los Angeles.",
  "vogue": "Angular posing dance from 1980s Harlem ballrooms.",
  "jitterbug": "Bouncy swing dance of the 1930s-40s USA.",
  "lindy-hop": "Swing dance born in 1920s-30s Harlem, New York.",
  "swing": "Upbeat partner dances of the 1920s-40s USA.",
  "quickstep": "Fast, light ballroom dance from 1920s England.",
  "jazz-dance": "American style rooted in African-American vernacular.",
  "contemporary": "Expressive 20th-century concert dance style.",
  "clogging": "Footwork dance from Appalachian USA folk roots.",
  "square-dance": "Four couples in a square; US folk tradition.",
  "polonaise": "Stately processional dance from Poland.",
  "mazurka": "Lively triple-time folk dance from Poland.",
  "gavotte": "Old French folk dance of moderate tempo.",
  "minuet": "Elegant French court dance of the Baroque era.",
  "bolero": "Slow Spanish dance in triple time.",
  "paso-doble": "Spanish dance styled on the bullfight.",
  "viennese-waltz": "Fast, spinning waltz from 19th-century Vienna.",

  // HARD
  "tarantella": "Fast southern Italian dance named for the tarantula.",
  "kathak": "Classical storytelling dance of northern India.",
  "bharatanatyam": "Ancient classical dance from Tamil Nadu, India.",
  "kabuki": "Stylized dance-drama from 17th-century Japan.",
  "highland-fling": "Solo Scottish Highland dance of victory.",
  "morris-dance": "English folk dance with bells on the shins.",
  "hornpipe": "Lively solo dance linked to British sailors.",
  "irish-jig": "Quick Irish folk dance in compound time.",
  "scottish-reel": "Lively Scottish social dance for couples.",
  "hopak": "Athletic Ukrainian Cossack dance with leaps.",
  "kalinka": "Russian dance to the famous 1860 folk song.",
  "troika": "Russian dance mimicking a three-horse sleigh.",
  "sirtaki": "Greek dance created for the 1964 film Zorba.",
  "haka": "Māori ceremonial war dance of New Zealand.",
  "gumboot": "South African dance born in the gold mines.",
  "tinikling": "Filipino dance stepping between bamboo poles.",
  "dabke": "Levantine line dance of the Arab world.",
  "zeibekiko": "Solo Greek dance with an eagle-like stance.",
  "fandango": "Lively Spanish couple dance in triple time.",
  "seguidilla": "Quick Spanish dance from Castile.",
  "jarabe-tapatio": "Mexico's national hat dance from Jalisco.",
  "quebradita": "Fast Mexican dance of the 1990s.",
  "cumbia": "Colombian courtship dance of coastal origin.",
  "merengue": "National dance of the Dominican Republic.",
  "carimbo": "Afro-Brazilian dance from Pará in the Amazon.",

  // IMPOSSIBLE
  "furiant": "Fiery, whirling Czech folk dance.",
  "czardas": "Hungarian dance from slow to fast tempo.",
  "kolo": "Balkan circle dance of the South Slavs.",
  "hora": "Circle dance of the Balkans and beyond.",
  "tamburica": "Dance to the tamburica strings of the Balkans.",
  "lezginka": "Fiery Caucasus dance of the Lezgin people.",
  "attan": "National dance of Afghanistan, 3,000 years old.",
  "khattak": "Pashtun martial sword dance of the Khattak tribe.",
  "kuchipudi": "Classical dance-drama from Andhra Pradesh, India.",
  "odissi": "Ancient temple dance from Odisha, India.",
  "manipuri": "Gentle classical dance from Manipur, India.",
  "mohiniyattam": "Graceful solo dance from Kerala, India.",
  "yangge": "Popular folk dance of northern China.",
  "dragon-dance": "Chinese dance with a long dragon on poles.",
  "lion-dance": "Chinese dance mimicking a lion for good luck.",
  "fan-dance": "East Asian dance using painted folding fans.",
  "buchaechum": "Korean fan dance created by Kim Baek-bong, 1954.",
  "talchum": "Korean masked dance-drama satirizing society.",
  "bon-odori": "Japanese folk dance of the Obon festival.",
  "eisa": "Okinawan drum dance for the Obon spirits.",
  "adumu": "Maasai jumping dance of Kenya and Tanzania.",
  "agbadza": "Ewe war-turned-social dance from Ghana.",
  "kizomba": "Romantic partner dance from 1980s Angola.",
  "kuduro": "Energetic Angolan dance and music style.",
  "gwara-gwara": "South African dance popularized by DJ Bongz.",
};
