// E186 «Guess the Dessert by Emoji 2» — 100 desserts · 25/tier
// VO: sfx/e186-<id>.wav
export const DESSERT_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "chocolate-mousse", title: "Chocolate Mousse", emojis: "🍫🥣", level: "easy" },
  { id: "milkshake", title: "Milkshake", emojis: "🥤🍫", level: "easy" },
  { id: "sugar-cookie", title: "Sugar Cookie", emojis: "🍪🍬", level: "easy" },
  { id: "toffee", title: "Toffee", emojis: "🍬🧈", level: "easy" },
  { id: "marshmallow", title: "Marshmallow", emojis: "☁🔥", level: "easy" },
  { id: "caramel-apple", title: "Caramel Apple", emojis: "🍎🍬", level: "easy" },
  { id: "jam", title: "Jam", emojis: "🍓🫙", level: "easy" },
  { id: "peanut-butter-cookie", title: "Peanut Butter Cookie", emojis: "🍪🥜", level: "easy" },
  { id: "fruit-tart", title: "Fruit Tart", emojis: "🥧🍓", level: "easy" },
  { id: "lemon-tart", title: "Lemon Tart", emojis: "🥧🍋", level: "easy" },
  { id: "pumpkin-pie", title: "Pumpkin Pie", emojis: "🎃🥧", level: "easy" },
  { id: "banana-bread", title: "Banana Bread", emojis: "🍞🍌", level: "easy" },
  { id: "chocolate-fondue", title: "Chocolate Fondue", emojis: "🫕🍫", level: "easy" },
  { id: "chocolate-pudding", title: "Chocolate Pudding", emojis: "🍫🍮", level: "easy" },
  { id: "chocolate-covered-strawberry", title: "Chocolate-Covered Strawberry", emojis: "🍓🍫", level: "easy" },
  { id: "gummy-bears", title: "Gummy Bears", emojis: "🐻🍬", level: "easy" },
  { id: "jelly-beans", title: "Jelly Beans", emojis: "🫘🍬", level: "easy" },
  { id: "cotton-candy", title: "Cotton Candy", emojis: "🎡🍬", level: "easy" },
  { id: "cinnamon-roll", title: "Cinnamon Roll", emojis: "🌀🍞", level: "easy" },
  { id: "banana-pudding", title: "Banana Pudding", emojis: "🍌🍮", level: "easy" },
  { id: "apple-crumble", title: "Apple Crumble", emojis: "🍎🥣", level: "easy" },
  { id: "cake-pop", title: "Cake Pop", emojis: "🎂🍭", level: "easy" },
  { id: "smores", title: "S'mores", emojis: "🍫🏕", level: "easy" },
  { id: "popcorn-ball", title: "Popcorn Ball", emojis: "🍿🍬", level: "easy" },
  { id: "sorbet", title: "Sorbet", emojis: "🍧🍋", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "tarte-tatin", title: "Tarte Tatin", emojis: "🍎🥐", level: "medium" },
  { id: "apple-strudel", title: "Apple Strudel", emojis: "🍎🌀", level: "medium" },
  { id: "funnel-cake", title: "Funnel Cake", emojis: "🎡🍩", level: "medium" },
  { id: "crepe", title: "Crêpe", emojis: "🥞🍫", level: "medium" },
  { id: "baked-alaska", title: "Baked Alaska", emojis: "🍦🔥", level: "medium" },
  { id: "nougat", title: "Nougat", emojis: "🥜🍬", level: "medium" },
  { id: "praline", title: "Praline", emojis: "🌰🍫", level: "medium" },
  { id: "meringue", title: "Meringue", emojis: "🥚☁", level: "medium" },
  { id: "biscotti", title: "Biscotti", emojis: "🍪☕", level: "medium" },
  { id: "shortbread", title: "Shortbread", emojis: "🍪🧈", level: "medium" },
  { id: "scone", title: "Scone", emojis: "🫖🍞", level: "medium" },
  { id: "danish", title: "Danish Pastry", emojis: "🥐🫐", level: "medium" },
  { id: "pain-au-chocolat", title: "Pain au Chocolat", emojis: "🥐🍫", level: "medium" },
  { id: "palmier", title: "Palmier", emojis: "🥐🌴", level: "medium" },
  { id: "bundt-cake", title: "Bundt Cake", emojis: "🎂🍩", level: "medium" },
  { id: "pound-cake", title: "Pound Cake", emojis: "🍰🧈", level: "medium" },
  { id: "angel-food-cake", title: "Angel Food Cake", emojis: "🍰☁", level: "medium" },
  { id: "boston-cream-pie", title: "Boston Cream Pie", emojis: "🍰🍮", level: "medium" },
  { id: "victoria-sponge", title: "Victoria Sponge", emojis: "🍰🫙", level: "medium" },
  { id: "lemon-bar", title: "Lemon Bar", emojis: "🍋🧈", level: "medium" },
  { id: "rice-krispie-treat", title: "Rice Krispie Treat", emojis: "🍚🍬", level: "medium" },
  { id: "whoopie-pie", title: "Whoopie Pie", emojis: "🍪🍦", level: "medium" },
  { id: "snickerdoodle", title: "Snickerdoodle", emojis: "🍪🌀", level: "medium" },
  { id: "dulce-de-leche", title: "Dulce de Leche", emojis: "🥛🍯", level: "medium" },
  { id: "pineapple-upside-down-cake", title: "Pineapple Upside-Down Cake", emojis: "🍍🍰", level: "medium" },

  // ===== HARD (25) =====
  { id: "loukoumades", title: "Loukoumades", emojis: "🍩🍯", level: "hard" },
  { id: "kataifi", title: "Kataifi", emojis: "🍯🧵", level: "hard" },
  { id: "maamoul", title: "Maamoul", emojis: "🌰🍪", level: "hard" },
  { id: "sutlac", title: "Sütlaç", emojis: "🍚🔥", level: "hard" },
  { id: "tulumba", title: "Tulumba", emojis: "🍯🥖", level: "hard" },
  { id: "syrniki", title: "Syrniki", emojis: "🧀🥞", level: "hard" },
  { id: "kaiserschmarrn", title: "Kaiserschmarrn", emojis: "🥞🍎", level: "hard" },
  { id: "stollen", title: "Stollen", emojis: "🎄🍞", level: "hard" },
  { id: "panettone", title: "Panettone", emojis: "🍊🍞", level: "hard" },
  { id: "berliner", title: "Berliner", emojis: "🍩🍓", level: "hard" },
  { id: "kladdkaka", title: "Kladdkaka", emojis: "🍫🥄", level: "hard" },
  { id: "princess-cake", title: "Princess Cake", emojis: "👑🍰", level: "hard" },
  { id: "bakewell-tart", title: "Bakewell Tart", emojis: "🥧🌰", level: "hard" },
  { id: "treacle-tart", title: "Treacle Tart", emojis: "🥧🍯", level: "hard" },
  { id: "eton-mess", title: "Eton Mess", emojis: "🍓🥄", level: "hard" },
  { id: "spotted-dick", title: "Spotted Dick", emojis: "🍇🍮", level: "hard" },
  { id: "bread-pudding", title: "Bread Pudding", emojis: "🍞🍮", level: "hard" },
  { id: "clafoutis", title: "Clafoutis", emojis: "🍒🍮", level: "hard" },
  { id: "brigadeiro", title: "Brigadeiro", emojis: "🍫🎊", level: "hard" },
  { id: "tangyuan", title: "Tangyuan", emojis: "🍡🥣", level: "hard" },
  { id: "pandan-cake", title: "Pandan Cake", emojis: "🍰🍃", level: "hard" },
  { id: "hotteok", title: "Hotteok", emojis: "🥞🌰", level: "hard" },
  { id: "bingsu", title: "Bingsu", emojis: "🍧🥛", level: "hard" },
  { id: "rasmalai", title: "Rasmalai", emojis: "🧀🥛", level: "hard" },
  { id: "barfi", title: "Barfi", emojis: "🥛🍬", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "financier", title: "Financier", emojis: "🌰🍰", level: "impossible" },
  { id: "dobos-torte", title: "Dobos Torte", emojis: "🎂🍮", level: "impossible" },
  { id: "esterhazy", title: "Eszterházy Torte", emojis: "🌰🍮", level: "impossible" },
  { id: "croquembouche", title: "Croquembouche", emojis: "🍫🗼", level: "impossible" },
  { id: "opera-cake", title: "Opera Cake", emojis: "🎭🍰", level: "impossible" },
  { id: "dacquoise", title: "Dacquoise", emojis: "🌰☁", level: "impossible" },
  { id: "saint-honore", title: "Gâteau St-Honoré", emojis: "😇🍮", level: "impossible" },
  { id: "kazandibi", title: "Kazandibi", emojis: "🥛🔥", level: "impossible" },
  { id: "asure", title: "Aşure", emojis: "🌾🍇", level: "impossible" },
  { id: "bastani", title: "Bastani", emojis: "🍦🌸", level: "impossible" },
  { id: "umm-ali", title: "Umm Ali", emojis: "🍞🥥", level: "impossible" },
  { id: "mahalabia", title: "Mahalabia", emojis: "🥛🌹", level: "impossible" },
  { id: "quindim", title: "Quindim", emojis: "🥥🥚", level: "impossible" },
  { id: "picarones", title: "Picarones", emojis: "🎃🍩", level: "impossible" },
  { id: "cocada", title: "Cocada", emojis: "🥥🍬", level: "impossible" },
  { id: "koeksister", title: "Koeksister", emojis: "🍯🥨", level: "impossible" },
  { id: "makowiec", title: "Makowiec", emojis: "🌀🌰", level: "impossible" },
  { id: "paczki", title: "Pączki", emojis: "🍩🌹", level: "impossible" },
  { id: "babka", title: "Babka", emojis: "🍫🍞", level: "impossible" },
  { id: "rugelach", title: "Rugelach", emojis: "🥐🌰", level: "impossible" },
  { id: "chak-chak", title: "Chak-Chak", emojis: "🍯🌾", level: "impossible" },
  { id: "krumkake", title: "Krumkake", emojis: "🧇🌀", level: "impossible" },
  { id: "risalamande", title: "Risalamande", emojis: "🍚🍒", level: "impossible" },
  { id: "anmitsu", title: "Anmitsu", emojis: "🍨🫘", level: "impossible" },
  { id: "yokan", title: "Yōkan", emojis: "🫘🍮", level: "impossible" },
];
