// «Guess the Dessert» — GuessSync · E63 · 100 desserts (25/tier) · real photos from Wikimedia Commons
// Tiered by global recognizability: easy (Chocolate Cake/Donut) → impossible (obscure regional sweets).
export const DESSERTS = [
  // EASY (25) — household-name desserts, instantly recognizable worldwide
  { slug: "chocolatecake", name: "Chocolate Cake", level: "easy" },
  { slug: "cheesecake", name: "Cheesecake", level: "easy" },
  { slug: "icecream", name: "Ice Cream", level: "easy" },
  { slug: "donut", name: "Donut", level: "easy" },
  { slug: "brownie", name: "Brownie", level: "easy" },
  { slug: "applepie", name: "Apple Pie", level: "easy" },
  { slug: "tiramisu", name: "Tiramisu", level: "easy" },
  { slug: "macaron", name: "Macaron", level: "easy" },
  { slug: "waffle", name: "Waffle", level: "easy" },
  { slug: "pancake", name: "Pancakes", level: "easy" },
  { slug: "cupcake", name: "Cupcake", level: "easy" },
  { slug: "croissant", name: "Croissant", level: "easy" },
  { slug: "eclair", name: "Éclair", level: "easy" },
  { slug: "cookie", name: "Cookie", level: "easy" },
  { slug: "baklava", name: "Baklava", level: "easy" },
  { slug: "cremebrulee", name: "Crème Brûlée", level: "easy" },
  { slug: "churros", name: "Churros", level: "easy" },
  { slug: "muffin", name: "Muffin", level: "easy" },
  { slug: "gingerbread", name: "Gingerbread Man", level: "easy" },
  { slug: "marshmallow", name: "Marshmallow", level: "easy" },
  { slug: "popsicle", name: "Popsicle", level: "easy" },
  { slug: "cottoncandy", name: "Cotton Candy", level: "easy" },
  { slug: "swissroll", name: "Swiss Roll", level: "easy" },
  { slug: "pudding", name: "Chocolate Pudding", level: "easy" },
  { slug: "bananasplit", name: "Banana Split", level: "easy" },
  // MEDIUM (25) — well-known, a step up
  { slug: "pannacotta", name: "Panna Cotta", level: "medium" },
  { slug: "mochi", name: "Mochi", level: "medium" },
  { slug: "profiterole", name: "Profiterole", level: "medium" },
  { slug: "redvelvet", name: "Red Velvet Cake", level: "medium" },
  { slug: "carrotcake", name: "Carrot Cake", level: "medium" },
  { slug: "lemonmeringue", name: "Lemon Meringue Pie", level: "medium" },
  { slug: "pumpkinpie", name: "Pumpkin Pie", level: "medium" },
  { slug: "banoffee", name: "Banoffee Pie", level: "medium" },
  { slug: "trifle", name: "Trifle", level: "medium" },
  { slug: "custardtart", name: "Custard Tart", level: "medium" },
  { slug: "scone", name: "Scone", level: "medium" },
  { slug: "fudge", name: "Fudge", level: "medium" },
  { slug: "toffee", name: "Toffee", level: "medium" },
  { slug: "praline", name: "Praline", level: "medium" },
  { slug: "chocolatetruffle", name: "Chocolate Truffle", level: "medium" },
  { slug: "meringue", name: "Meringue", level: "medium" },
  { slug: "flan", name: "Flan", level: "medium" },
  { slug: "ricepudding", name: "Rice Pudding", level: "medium" },
  { slug: "bakedalaska", name: "Baked Alaska", level: "medium" },
  { slug: "strudel", name: "Apple Strudel", level: "medium" },
  { slug: "gelato", name: "Gelato", level: "medium" },
  { slug: "sorbet", name: "Sorbet", level: "medium" },
  { slug: "lavacake", name: "Molten Lava Cake", level: "medium" },
  { slug: "strawberryshortcake", name: "Strawberry Shortcake", level: "medium" },
  { slug: "blackforest", name: "Black Forest Cake", level: "medium" },
  // HARD (25) — regional / specialist, recognizable to enthusiasts
  { slug: "kanafeh", name: "Kanafeh", level: "hard" },
  { slug: "pavlova", name: "Pavlova", level: "hard" },
  { slug: "cannoli", name: "Cannoli", level: "hard" },
  { slug: "pasteldenata", name: "Pastel de Nata", level: "hard" },
  { slug: "millefeuille", name: "Mille-feuille", level: "hard" },
  { slug: "sachertorte", name: "Sachertorte", level: "hard" },
  { slug: "baumkuchen", name: "Baumkuchen", level: "hard" },
  { slug: "stollen", name: "Stollen", level: "hard" },
  { slug: "panettone", name: "Panettone", level: "hard" },
  { slug: "financier", name: "Financier", level: "hard" },
  { slug: "madeleine", name: "Madeleine", level: "hard" },
  { slug: "operacake", name: "Opera Cake", level: "hard" },
  { slug: "dobostorte", name: "Dobos Torte", level: "hard" },
  { slug: "basbousa", name: "Basbousa", level: "hard" },
  { slug: "gulabjamun", name: "Gulab Jamun", level: "hard" },
  { slug: "jalebi", name: "Jalebi", level: "hard" },
  { slug: "ladoo", name: "Ladoo", level: "hard" },
  { slug: "rasgulla", name: "Rasgulla", level: "hard" },
  { slug: "halva", name: "Halva", level: "hard" },
  { slug: "turkishdelight", name: "Turkish Delight", level: "hard" },
  { slug: "dango", name: "Dango", level: "hard" },
  { slug: "dorayaki", name: "Dorayaki", level: "hard" },
  { slug: "taiyaki", name: "Taiyaki", level: "hard" },
  { slug: "rugelach", name: "Rugelach", level: "hard" },
  { slug: "ummali", name: "Umm Ali", level: "hard" },
  // IMPOSSIBLE (25) — obscure regional sweets
  { slug: "kouignamann", name: "Kouign-amann", level: "impossible" },
  { slug: "cassata", name: "Cassata", level: "impossible" },
  { slug: "sfogliatella", name: "Sfogliatella", level: "impossible" },
  { slug: "zeppole", name: "Zeppole", level: "impossible" },
  { slug: "cannele", name: "Canelé", level: "impossible" },
  { slug: "galaktoboureko", name: "Galaktoboureko", level: "impossible" },
  { slug: "loukoumades", name: "Loukoumades", level: "impossible" },
  { slug: "revani", name: "Revani", level: "impossible" },
  { slug: "tulumba", name: "Tulumba", level: "impossible" },
  { slug: "maamoul", name: "Maamoul", level: "impossible" },
  { slug: "luqaimat", name: "Luqaimat", level: "impossible" },
  { slug: "qatayef", name: "Qatayef", level: "impossible" },
  { slug: "mooncake", name: "Mooncake", level: "impossible" },
  { slug: "tangyuan", name: "Tangyuan", level: "impossible" },
  { slug: "hotteok", name: "Hotteok", level: "impossible" },
  { slug: "bingsu", name: "Bingsu", level: "impossible" },
  { slug: "halohalo", name: "Halo-halo", level: "impossible" },
  { slug: "bibingka", name: "Bibingka", level: "impossible" },
  { slug: "klepon", name: "Klepon", level: "impossible" },
  { slug: "chimneycake", name: "Chimney Cake", level: "impossible" },
  { slug: "kulfi", name: "Kulfi", level: "impossible" },
  { slug: "barfi", name: "Barfi", level: "impossible" },
  { slug: "sandesh", name: "Sandesh", level: "impossible" },
  { slug: "mishtidoi", name: "Mishti Doi", level: "impossible" },
  { slug: "kladdkaka", name: "Kladdkaka", level: "impossible" },
];
