// E210 «Guess the Dessert by Emoji 3» — 100 desserts · 25/tier
// VO: sfx/e210-<id>.wav
export const DESSERT_EMOJI_3 = [
  // ===== EASY (25) =====
  { id: "chocolate-truffle", title: "Chocolate Truffle", emojis: "🍫🍬", level: "easy" },
  { id: "apple-turnover", title: "Apple Turnover", emojis: "🍎🥟", level: "easy" },
  { id: "key-lime-pie", title: "Key Lime Pie", emojis: "🍋🧊", level: "easy" },
  { id: "peanut-brittle", title: "Peanut Brittle", emojis: "🥜🔨", level: "easy" },
  { id: "butterscotch-pudding", title: "Butterscotch Pudding", emojis: "🧈🍮", level: "easy" },
  { id: "ice-cream-sandwich", title: "Ice Cream Sandwich", emojis: "🍦🥪", level: "easy" },
  { id: "root-beer-float", title: "Root Beer Float", emojis: "🥤🍦", level: "easy" },
  { id: "frozen-yogurt", title: "Frozen Yogurt", emojis: "🍦❄", level: "easy" },
  { id: "fruit-cake", title: "Fruit Cake", emojis: "🍇🍞", level: "easy" },
  { id: "marble-cake", title: "Marble Cake", emojis: "🍰🎨", level: "easy" },
  { id: "devils-food-cake", title: "Devil's Food Cake", emojis: "🍰😈", level: "easy" },
  { id: "german-chocolate-cake", title: "German Chocolate Cake", emojis: "🍫🌲", level: "easy" },
  { id: "coffee-cake", title: "Coffee Cake", emojis: "☕🍞", level: "easy" },
  { id: "candy-corn", title: "Candy Corn", emojis: "🍬🎃", level: "easy" },
  { id: "apple-fritter", title: "Apple Fritter", emojis: "🍎🍩", level: "easy" },
  { id: "vanilla-pudding", title: "Vanilla Pudding", emojis: "🍮🌼", level: "easy" },
  { id: "butter-cookie", title: "Butter Cookie", emojis: "🍪🐄", level: "easy" },
  { id: "almond-cookie", title: "Almond Cookie", emojis: "🍪🌸", level: "easy" },
  { id: "caramel-popcorn", title: "Caramel Popcorn", emojis: "🍿🧈", level: "easy" },
  { id: "chocolate-wafer", title: "Chocolate Wafer", emojis: "🍫🧇", level: "easy" },
  { id: "custard-tart", title: "Custard Tart", emojis: "🥧🍮", level: "easy" },
  { id: "jelly-roll", title: "Jelly Roll", emojis: "🍇🌀", level: "easy" },
  { id: "oatmeal-cookie", title: "Oatmeal Cookie", emojis: "🍪🌾", level: "easy" },
  { id: "neapolitan-ice-cream", title: "Neapolitan Ice Cream", emojis: "🍦🎨", level: "easy" },
  { id: "ice-cream-cone", title: "Ice Cream Cone", emojis: "🍦🔺", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "zeppole", title: "Zeppole", emojis: "🍩🍮", level: "medium" },
  { id: "beignet", title: "Beignet", emojis: "🍩❄", level: "medium" },
  { id: "cronut", title: "Cronut", emojis: "🥐🍩", level: "medium" },
  { id: "kolache", title: "Kolache", emojis: "🥟🍑", level: "medium" },
  { id: "amaretti", title: "Amaretti", emojis: "🍪🍷", level: "medium" },
  { id: "florentine", title: "Florentine", emojis: "🍪🍊", level: "medium" },
  { id: "speculoos", title: "Speculoos", emojis: "🍪🌶", level: "medium" },
  { id: "pfeffernusse", title: "Pfeffernüsse", emojis: "🍪❄", level: "medium" },
  { id: "lebkuchen", title: "Lebkuchen", emojis: "🍪🎄", level: "medium" },
  { id: "battenberg-cake", title: "Battenberg Cake", emojis: "🍰🎀", level: "medium" },
  { id: "simnel-cake", title: "Simnel Cake", emojis: "🍰🐑", level: "medium" },
  { id: "millionaires-shortbread", title: "Millionaire's Shortbread", emojis: "🍪💰", level: "medium" },
  { id: "chelsea-bun", title: "Chelsea Bun", emojis: "🍞🐝", level: "medium" },
  { id: "welsh-cake", title: "Welsh Cake", emojis: "🍪🔥", level: "medium" },
  { id: "jaffa-cake", title: "Jaffa Cake", emojis: "🍰🍊", level: "medium" },
  { id: "custard-cream", title: "Custard Cream", emojis: "🍪🍮", level: "medium" },
  { id: "marzipan", title: "Marzipan", emojis: "🌼🍬", level: "medium" },
  { id: "chiffon-cake", title: "Chiffon Cake", emojis: "🍰🪶", level: "medium" },
  { id: "sponge-toffee", title: "Sponge Toffee", emojis: "🍬🧽", level: "medium" },
  { id: "peanut-butter-cup", title: "Peanut Butter Cup", emojis: "🥜🍫", level: "medium" },
  { id: "malted-milk-ball", title: "Malted Milk Ball", emojis: "🥛🍫", level: "medium" },
  { id: "chocolate-bark", title: "Chocolate Bark", emojis: "🍫🔨", level: "medium" },
  { id: "pecan-pie", title: "Pecan Pie", emojis: "🥧🍂", level: "medium" },
  { id: "sweet-potato-pie", title: "Sweet Potato Pie", emojis: "🥧🍠", level: "medium" },
  { id: "mud-pie", title: "Mud Pie", emojis: "🥧🍫", level: "medium" },

  // ===== HARD (25) =====
  { id: "sanwin-makin", title: "Sanwin Makin", emojis: "🍮🌾", level: "hard" },
  { id: "puto", title: "Puto", emojis: "🍚🧁", level: "hard" },
  { id: "kutsinta", title: "Kutsinta", emojis: "🍚🍯", level: "hard" },
  { id: "polvorones", title: "Polvorones", emojis: "🍪💨", level: "hard" },
  { id: "gajar-halwa", title: "Gajar Halwa", emojis: "🥕🍮", level: "hard" },
  { id: "petit-four", title: "Petit Four", emojis: "🍰🎁", level: "hard" },
  { id: "cassava-cake", title: "Cassava Cake", emojis: "🥔🥥", level: "hard" },
  { id: "kue-lapis", title: "Kue Lapis", emojis: "🍰🌈", level: "hard" },
  { id: "klepon", title: "Klepon", emojis: "🍡🌿", level: "hard" },
  { id: "ondeh-ondeh", title: "Ondeh-Ondeh", emojis: "🍡🌴", level: "hard" },
  { id: "nian-gao", title: "Nian Gao", emojis: "🍚🧧", level: "hard" },
  { id: "egg-waffle", title: "Egg Waffle", emojis: "🥚🧇", level: "hard" },
  { id: "pineapple-bun", title: "Pineapple Bun", emojis: "🍍🍞", level: "hard" },
  { id: "kolaczki", title: "Kolaczki", emojis: "🍪🫐", level: "hard" },
  { id: "kouglof", title: "Kouglof", emojis: "🍞👑", level: "hard" },
  { id: "savarin", title: "Savarin", emojis: "🍩🍸", level: "hard" },
  { id: "frangipane-tart", title: "Frangipane Tart", emojis: "🥧🌸", level: "hard" },
  { id: "jam-roly-poly", title: "Jam Roly-Poly", emojis: "🍞🍓", level: "hard" },
  { id: "queen-of-puddings", title: "Queen of Puddings", emojis: "🍮👑", level: "hard" },
  { id: "cabinet-pudding", title: "Cabinet Pudding", emojis: "🍮📦", level: "hard" },
  { id: "knickerbocker-glory", title: "Knickerbocker Glory", emojis: "🍨🏆", level: "hard" },
  { id: "semifreddo", title: "Semifreddo", emojis: "🍦🧊", level: "hard" },
  { id: "zabaglione", title: "Zabaglione", emojis: "🍮🍷", level: "hard" },
  { id: "panforte", title: "Panforte", emojis: "🍪🍇", level: "hard" },
  { id: "mysore-pak", title: "Mysore Pak", emojis: "🧈🌟", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "sandesh", title: "Sandesh", emojis: "🧀🌸", level: "impossible" },
  { id: "chum-chum", title: "Chum Chum", emojis: "🧀🎀", level: "impossible" },
  { id: "pantua", title: "Pantua", emojis: "🍫🍯", level: "impossible" },
  { id: "ledikeni", title: "Ledikeni", emojis: "🧀🍇", level: "impossible" },
  { id: "petha", title: "Petha", emojis: "🎃🧊", level: "impossible" },
  { id: "sohan-papdi", title: "Sohan Papdi", emojis: "🧈🕸", level: "impossible" },
  { id: "imarti", title: "Imarti", emojis: "🍯🌸", level: "impossible" },
  { id: "balushahi", title: "Balushahi", emojis: "🥐🍯", level: "impossible" },
  { id: "shrikhand", title: "Shrikhand", emojis: "🥛🌼", level: "impossible" },
  { id: "modak", title: "Modak", emojis: "🥥🌙", level: "impossible" },
  { id: "peda", title: "Peda", emojis: "🥛🎊", level: "impossible" },
  { id: "kalakand", title: "Kalakand", emojis: "🧀🌾", level: "impossible" },
  { id: "gujiya", title: "Gujiya", emojis: "🥟🌰", level: "impossible" },
  { id: "malpua", title: "Malpua", emojis: "🥞🌟", level: "impossible" },
  { id: "putri-salju", title: "Putri Salju", emojis: "🍪👸", level: "impossible" },
  { id: "dadar-gulung", title: "Dadar Gulung", emojis: "🥞🍃", level: "impossible" },
  { id: "wingko", title: "Wingko", emojis: "🥥🔥", level: "impossible" },
  { id: "serabi", title: "Serabi", emojis: "🥞🥥", level: "impossible" },
  { id: "getuk", title: "Getuk", emojis: "🥔🍬", level: "impossible" },
  { id: "apam-balik", title: "Apam Balik", emojis: "🥞🧈", level: "impossible" },
  { id: "bika-ambon", title: "Bika Ambon", emojis: "🐝🥞", level: "impossible" },
  { id: "kue-cubit", title: "Kue Cubit", emojis: "🧁🍫", level: "impossible" },
  { id: "martabak-manis", title: "Martabak Manis", emojis: "🥞🍁", level: "impossible" },
  { id: "injeolmi", title: "Injeolmi", emojis: "🍡🫘", level: "impossible" },
  { id: "yaksik", title: "Yaksik", emojis: "🍚🎊", level: "impossible" },
];
