// E158 emoji-dessert facts — one true <=70-char fact per dessert (origin-focused), shown on reveal.
export const DESSERT_EMOJI_FACTS = {
  // EASY
  "ice-cream": "Frozen sweet treat; modern styles trace back to Italy.",
  "donut": "Ring-shaped fried dough popularized in the United States.",
  "cupcake": "Small single-serving cake from 19th-century America.",
  "cookie": "Sweet baked snack; the name comes from the Dutch koekje.",
  "chocolate-bar": "Britain's Fry's made the first solid eating bar in 1847.",
  "apple-pie": "Fruit-filled pastry with English and Dutch roots.",
  "birthday-cake": "Candle-topped cake tradition popularized in Germany.",
  "lollipop": "Hard candy on a stick, popularized in early-1900s America.",
  "candy": "Sugar confection eaten as a treat all over the world.",
  "honey": "Natural sweetener made by bees, eaten since ancient times.",
  "strawberry-shortcake": "Sponge cake with cream and strawberries, an American classic.",
  "sundae": "Ice cream with toppings, invented in the United States.",
  "waffle": "Crisp battered cake in a grid pattern, famous in Belgium.",
  "pancakes": "Flat fried batter cakes eaten worldwide for breakfast.",
  "flan": "Baked custard with caramel, popular across Spain.",
  "chocolate-cake": "Rich cocoa-flavored cake beloved in the United States.",
  "lemon-cake": "Light citrus-flavored sponge cake enjoyed worldwide.",
  "carrot-cake": "Spiced cake made with grated carrots, an English favorite.",
  "cheesecake": "Soft cheese dessert dating back to ancient Greece.",
  "shaved-ice": "Ice shavings with syrup; Japan's kakigori is famous.",
  "candy-cane": "Striped peppermint stick with roots in Germany.",
  "gingerbread": "Ginger-spiced sweet baked across medieval Europe.",
  "muffin": "Small quick-bread cake; the American style is often sweet.",
  "chocolate-chip-cookie": "Invented in 1938 at the Toll House inn in Massachusetts.",
  "ice-lolly": "Frozen flavored ice on a stick, invented in the USA.",

  // MEDIUM
  "tiramisu": "Coffee-soaked layered dessert from northern Italy.",
  "macaron": "Delicate meringue sandwich cookie perfected in France.",
  "brownie": "Dense fudgy chocolate square that began in the USA.",
  "churros": "Fried dough sticks dusted with sugar, popular in Spain.",
  "coconut-macaroon": "Chewy coconut cookie enjoyed in many countries.",
  "eclair": "Cream-filled choux pastry with icing, from France.",
  "cannoli": "Fried tube filled with sweet ricotta, from Sicily, Italy.",
  "panna-cotta": "Sweetened cream set with gelatin, from Italy.",
  "profiterole": "Choux puff filled with cream, a French classic.",
  "trifle": "Layered sponge, custard and cream dessert from England.",
  "pavlova": "Meringue cake with fruit, claimed by Australia and NZ.",
  "fudge": "Soft sugar-and-butter candy popular in the USA and UK.",
  "banoffee-pie": "Banana-and-toffee pie invented in England in 1971.",
  "tres-leches": "Sponge cake soaked in three milks, loved in Mexico.",
  "gelato": "Dense Italian ice cream churned slowly with less air.",
  "mochi": "Chewy pounded-rice cake from Japan.",
  "baklava": "Layered nut-and-syrup pastry linked to Turkey.",
  "halva": "Dense sweet made from nuts or seeds across the Mideast.",
  "rice-pudding": "Rice simmered in sweet milk, eaten around the world.",
  "creme-brulee": "Custard with a torched caramel crust, from France.",
  "red-velvet-cake": "Cocoa cake with red color and cream cheese, from the USA.",
  "swiss-roll": "Sponge rolled around cream or jam, a European classic.",
  "black-forest-cake": "Chocolate-and-cherry layer cake from Germany.",
  "banana-split": "Banana with ice cream scoops, created in the USA.",
  "peach-cobbler": "Baked peaches under biscuit topping, from the USA.",

  // HARD
  "kunafa": "Cheese pastry in sweet syrup from the Levant.",
  "gulab-jamun": "Fried milk balls soaked in syrup, from India.",
  "mooncake": "Dense filled pastry eaten at China's Mid-Autumn Festival.",
  "jalebi": "Deep-fried spirals soaked in syrup, popular in India.",
  "turkish-delight": "Soft gel candy dusted with sugar, from Turkey.",
  "madeleine": "Small shell-shaped sponge cake from France.",
  "dango": "Skewered sweet rice dumplings from Japan.",
  "mille-feuille": "Layered puff pastry with cream, from France.",
  "gingerbread-house": "Decorated edible house tradition rooted in Germany.",
  "fortune-cookie": "Crisp cookie with a paper slip, from the USA.",
  "stroopwafel": "Thin waffle with syrup filling, from the Netherlands.",
  "baumkuchen": "Spit-roasted layered ring cake from Germany.",
  "alfajor": "Two cookies filled with dulce de leche, from Argentina.",
  "kheer": "Rice pudding with nuts and cardamom, from India.",
  "pastel-de-nata": "Flaky egg-custard tart from Portugal.",
  "basbousa": "Semolina cake soaked in syrup, popular in Egypt.",
  "kulfi": "Dense frozen milk dessert from India.",
  "affogato": "Espresso poured over gelato, from Italy.",
  "sticky-toffee-pudding": "Sponge with dates and toffee sauce, from England.",
  "mont-blanc": "Dessert of sweet chestnut cream, from France.",
  "sachertorte": "Chocolate cake with apricot jam, from Austria.",
  "linzer-torte": "Lattice-topped jam tart from Linz, Austria.",
  "galaktoboureko": "Semolina custard in syrupy pastry, from Greece.",
  "egg-tart": "Custard tart in flaky pastry, famous in Hong Kong.",
  "qatayef": "Stuffed folded pancakes eaten in the Arab world at Ramadan.",

  // IMPOSSIBLE
  "lamington": "Sponge in chocolate and coconut, from Australia.",
  "sfogliatella": "Shell-shaped flaky pastry from Naples, Italy.",
  "cendol": "Iced dessert with green rice-jelly, from Southeast Asia.",
  "semla": "Cardamom bun filled with cream, from Sweden.",
  "bibingka": "Baked rice cake with coconut, from the Philippines.",
  "malva-pudding": "Sweet spongy baked pudding from South Africa.",
  "melktert": "Creamy milk tart from South Africa.",
  "kransekake": "Stacked almond ring cake from Norway and Denmark.",
  "cassata": "Ricotta and candied-fruit sponge from Sicily, Italy.",
  "kouign-amann": "Buttery caramelized pastry from Brittany, France.",
  "pineapple-tart": "Buttery pastry with pineapple jam, loved in Taiwan.",
  "castella": "Fluffy honey sponge cake from Nagasaki, Japan.",
  "dorayaki": "Two pancakes filled with red-bean paste, from Japan.",
  "taiyaki": "Fish-shaped filled cake from Japan.",
  "zerde": "Golden saffron rice pudding from Turkey.",
  "kaju-katli": "Diamond-shaped cashew fudge from India.",
  "paris-brest": "Ring choux pastry with praline cream, from France.",
  "canele": "Rum-and-vanilla custard cake from Bordeaux, France.",
  "spekkoek": "Spiced layered cake from Indonesia's Dutch era.",
  "rasgulla": "Spongy cheese balls in light syrup, from India.",
  "bienenstich": "Almond-topped cream cake from Germany.",
  "buche-de-noel": "Log-shaped chocolate Christmas cake from France.",
  "halo-halo": "Mixed shaved-ice dessert from the Philippines.",
  "faloodeh": "Frozen dessert with rose and vermicelli, from Iran.",
  "baba-au-rhum": "Small yeast cake soaked in rum, from France.",
};
