// E210 dessert-emoji facts — one true <=70-char fact per dessert, shown on reveal.
export const DESSERT_EMOJI_3_FACTS = {
  // EASY
  "chocolate-truffle": "A rich chocolate ganache ball rolled in cocoa powder.",
  "apple-turnover": "Puff pastry folded over spiced apple filling, then baked.",
  "key-lime-pie": "A tart Florida pie made with small, aromatic key limes.",
  "peanut-brittle": "A hard candy of caramelized sugar studded with peanuts.",
  "butterscotch-pudding": "A creamy pudding of brown sugar and butter.",
  "ice-cream-sandwich": "A scoop of ice cream pressed between two cookies.",
  "root-beer-float": "Root beer poured over vanilla ice cream, US classic.",
  "frozen-yogurt": "A tangy frozen treat made from cultured yogurt.",
  "fruit-cake": "A dense cake packed with candied fruit and nuts.",
  "marble-cake": "A cake swirled with plain and chocolate batter.",
  "devils-food-cake": "A dark, rich chocolate cake denser than red velvet.",
  "german-chocolate-cake": "A chocolate cake with pecan-coconut frosting, from the US.",
  "coffee-cake": "A crumb-topped cake meant to be eaten alongside coffee.",
  "candy-corn": "A tricolor waxy candy shaped like corn kernels, US Halloween.",
  "apple-fritter": "Fried dough studded with apple chunks and glazed.",
  "vanilla-pudding": "A smooth custard-style pudding flavored with vanilla.",
  "butter-cookie": "A simple crisp cookie made rich with butter.",
  "almond-cookie": "A crumbly cookie flavored with ground almonds.",
  "caramel-popcorn": "Popcorn coated in a crunchy caramel glaze.",
  "chocolate-wafer": "A thin crisp biscuit layered with chocolate.",
  "custard-tart": "A pastry shell filled with sweet baked egg custard.",
  "jelly-roll": "A sponge cake spread with jam and rolled into a spiral.",
  "oatmeal-cookie": "A chewy cookie made with rolled oats.",
  "neapolitan-ice-cream": "Vanilla, chocolate, and strawberry ice cream in one block.",
  "ice-cream-cone": "A scoop of ice cream served in a crisp edible cone.",
  // MEDIUM
  "zeppole": "Italian fried dough balls, often filled with custard.",
  "beignet": "A New Orleans fried square dusted with powdered sugar.",
  "cronut": "A trademarked croissant-doughnut hybrid pastry.",
  "kolache": "A Czech pastry pocket filled with fruit like apricot.",
  "amaretti": "A crisp Italian almond macaroon, often paired with liqueur.",
  "florentine": "A thin lacy cookie of nuts, candied fruit, and chocolate.",
  "speculoos": "A spiced, crunchy Belgian cinnamon cookie.",
  "pfeffernusse": "A German spiced Christmas cookie dusted with sugar.",
  "lebkuchen": "A soft German gingerbread-style Christmas cookie.",
  "battenberg-cake": "A pink-and-yellow checkered cake wrapped in marzipan.",
  "simnel-cake": "A British fruit cake topped with marzipan balls, for Easter.",
  "millionaires-shortbread": "Shortbread layered with caramel and chocolate.",
  "chelsea-bun": "A spiral British bun studded with dried fruit.",
  "welsh-cake": "A griddle-cooked Welsh cake studded with currants.",
  "jaffa-cake": "A British sponge cake with orange jelly and chocolate.",
  "custard-cream": "A British sandwich biscuit with vanilla custard filling.",
  "marzipan": "A sweet paste of ground almonds and sugar.",
  "chiffon-cake": "A very light American cake leavened with whipped eggs.",
  "sponge-toffee": "A honeycomb-textured toffee full of air bubbles.",
  "peanut-butter-cup": "A cup of peanut butter coated in chocolate.",
  "malted-milk-ball": "A malted candy center coated in chocolate.",
  "chocolate-bark": "Melted chocolate cooled flat and broken into shards.",
  "pecan-pie": "A Southern US pie of pecans set in a sweet syrup filling.",
  "sweet-potato-pie": "A spiced Southern US pie made from mashed sweet potato.",
  "mud-pie": "A rich chocolate pie resembling dark, dense mud.",
  // HARD
  "sanwin-makin": "A dense Burmese semolina cake baked with coconut milk.",
  "puto": "A small steamed Filipino rice cake, often eaten with cheese.",
  "kutsinta": "A sticky brown Filipino rice cake glazed and steamed.",
  "polvorones": "A crumbly Spanish shortbread that dissolves like powder.",
  "gajar-halwa": "An Indian carrot pudding slow-cooked in milk and ghee.",
  "petit-four": "A tiny, elaborately decorated French bite-sized cake.",
  "cassava-cake": "A Filipino baked cake made from grated cassava and coconut.",
  "kue-lapis": "An Indonesian steamed cake of colorful thin layers.",
  "klepon": "Indonesian rice balls filled with liquid palm sugar.",
  "ondeh-ondeh": "Malaysian pandan rice balls filled with palm sugar syrup.",
  "nian-gao": "A sticky Chinese rice cake eaten for Lunar New Year.",
  "egg-waffle": "A Hong Kong street snack of bubbly egg-batter waffle.",
  "pineapple-bun": "A Hong Kong bun with a sweet, cracked sugary crust.",
  "kolaczki": "A Polish cookie folded around a sweet fruit filling.",
  "kouglof": "An Alsatian brioche baked in a crown-shaped fluted mold.",
  "savarin": "A French ring cake soaked in rum syrup.",
  "frangipane-tart": "A French tart filled with sweet almond cream.",
  "jam-roly-poly": "A British steamed suet pudding rolled around jam.",
  "queen-of-puddings": "A British baked custard topped with jam and meringue.",
  "cabinet-pudding": "A British steamed pudding of sponge, fruit, and custard.",
  "knickerbocker-glory": "A tall British ice cream sundae served in a glass.",
  "semifreddo": "An Italian semi-frozen dessert, softer than ice cream.",
  "zabaglione": "An Italian whipped custard made with egg yolks and wine.",
  "panforte": "A dense Italian cake packed with nuts and dried fruit.",
  "mysore-pak": "A rich South Indian sweet made from gram flour and ghee.",
  // IMPOSSIBLE
  "sandesh": "A delicate Bengali sweet made from fresh paneer cheese.",
  "chum-chum": "An oblong Bengali sweet made from sweetened paneer.",
  "pantua": "A dark fried Bengali sweet, a rich cousin of gulab jamun.",
  "ledikeni": "A Bengali sweet named after a British governor's wife.",
  "petha": "An Indian candy made from candied ash gourd.",
  "sohan-papdi": "A flaky, web-textured Indian sweet made from gram flour.",
  "imarti": "A flower-shaped Indian sweet fried and soaked in syrup.",
  "balushahi": "A flaky Indian glazed sweet similar to a dense doughnut.",
  "shrikhand": "An Indian strained-yogurt dessert flavored with saffron.",
  "modak": "A steamed Indian dumpling filled with coconut and jaggery.",
  "peda": "A soft Indian sweet made from thickened milk solids.",
  "kalakand": "A grainy Indian milk-and-cheese fudge sweet.",
  "gujiya": "A fried Indian dumpling filled with khoya and dried fruit.",
  "malpua": "An Indian sweet pancake soaked in sugar syrup.",
  "putri-salju": "Indonesian crescent cookies dusted in powdered sugar.",
  "dadar-gulung": "An Indonesian pandan crepe rolled around coconut filling.",
  "wingko": "An Indonesian griddle cake made from sticky rice and coconut.",
  "serabi": "An Indonesian coconut-milk pancake with a spongy center.",
  "getuk": "An Indonesian sweet made from mashed cassava.",
  "apam-balik": "A Malaysian folded pancake filled with peanuts and sugar.",
  "bika-ambon": "An Indonesian cake with a distinctive honeycomb texture.",
  "kue-cubit": "Tiny Indonesian pinch cakes cooked on a mini griddle.",
  "martabak-manis": "A thick Indonesian sweet stuffed pancake with toppings.",
  "injeolmi": "Korean rice cakes coated in toasted soybean powder.",
  "yaksik": "A Korean sweet rice dish with chestnuts and jujubes.",
};
