// «Guess the Dessert» — GuessSync · E63 · did-you-know facts, ≤70 chars, verified true.
export const DESSERT_FACTS = {
  // EASY
  "chocolatecake": "Made rich with cocoa; popularized after cocoa powder arrived",
  "cheesecake": "Ancient Greeks served an early form to Olympic athletes",
  "icecream": "Frozen sweet cream; the cone was popularized around 1904",
  "donut": "Fried dough ring; the hole helps it cook through evenly",
  "brownie": "A dense American chocolate bar, first served around 1900",
  "applepie": "Baked apple filling in pastry; a classic English dessert",
  "tiramisu": "Italian layers of coffee-soaked ladyfingers and mascarpone",
  "macaron": "French almond-meringue sandwich cookie with a filling",
  "waffle": "Batter cooked between hot patterned plates to form a grid",
  "pancake": "Flat batter cakes fried in a pan, eaten across the world",
  "cupcake": "A single-serving cake baked in a small paper cup",
  "croissant": "Buttery French pastry with a flaky, crescent shape",
  "eclair": "French choux pastry filled with cream and topped with icing",
  "cookie": "Small sweet baked treat; the name comes from Dutch 'koekje'",
  "baklava": "Layered filo with nuts and syrup, from the Ottoman kitchen",
  "cremebrulee": "Custard topped with a hard, torched caramelized sugar crust",
  "churros": "Fried dough sticks dusted in sugar, popular in Spain",
  "muffin": "Individual quick-bread cake, often studded with fruit",
  "gingerbread": "Spiced ginger cookie, often cut in a human shape",
  "marshmallow": "Fluffy sweet once made from the marshmallow plant's root",
  "popsicle": "Frozen flavored ice on a stick, invented by accident in 1905",
  "cottoncandy": "Spun sugar; called 'fairy floss' when first sold in 1904",
  "swissroll": "Sponge cake spread with filling and rolled into a spiral",
  "pudding": "Soft, creamy dessert set with starch, milk and cocoa",
  "bananasplit": "Split banana served with ice cream, born in the US in 1904",
  // MEDIUM
  "pannacotta": "Italian 'cooked cream' set with gelatin into a soft pudding",
  "mochi": "Japanese chewy cake made from pounded glutinous rice",
  "profiterole": "Choux pastry balls filled with cream and topped with sauce",
  "redvelvet": "Cocoa cake tinted red, paired with cream-cheese frosting",
  "carrotcake": "Moist spiced cake made with grated carrot in the batter",
  "lemonmeringue": "Lemon-curd pie topped with a browned meringue peak",
  "pumpkinpie": "Spiced custard pie of pumpkin, tied to US Thanksgiving",
  "banoffee": "English pie of banana, toffee and cream, created in 1971",
  "trifle": "Layered English dessert of sponge, custard, fruit and cream",
  "custardtart": "Pastry shell filled with baked egg custard and nutmeg",
  "scone": "British quick bread often served with clotted cream and jam",
  "fudge": "Soft candy made by boiling sugar, butter and milk together",
  "toffee": "Hard candy made by caramelizing sugar with butter",
  "praline": "Confection of nuts cooked in sugar, from French cuisine",
  "chocolatetruffle": "Ganache ball rolled in cocoa, named after the fungus",
  "meringue": "Whipped egg whites and sugar, baked until light and crisp",
  "flan": "Baked custard turned out to show a soft caramel topping",
  "ricepudding": "Rice simmered in sweetened milk, eaten around the world",
  "bakedalaska": "Ice cream on sponge covered in meringue, briefly baked",
  "strudel": "Austrian pastry of thin dough rolled around apple filling",
  "gelato": "Italian ice cream, denser and lower in fat than the US kind",
  "sorbet": "Frozen dessert of fruit and sugar, made without any dairy",
  "lavacake": "Chocolate cake with a warm, deliberately molten liquid core",
  "strawberryshortcake": "Biscuit or sponge layered with strawberries and cream",
  "blackforest": "German cherry-and-cream chocolate cake, laced with kirsch",
  // HARD
  "kanafeh": "Levantine dessert of cheese in shredded pastry with syrup",
  "pavlova": "Meringue cake with fruit, named for a Russian ballerina",
  "cannoli": "Sicilian fried tube shell filled with sweet ricotta cream",
  "pasteldenata": "Portuguese egg-custard tart with a caramelized top",
  "millefeuille": "French 'thousand-leaf' pastry of puff layers and cream",
  "sachertorte": "Viennese chocolate cake with apricot jam, dated to 1832",
  "baumkuchen": "German 'tree cake' baked in layers on a rotating spit",
  "stollen": "German fruit bread dusted with sugar, eaten at Christmas",
  "panettone": "Tall Italian sweet bread with candied fruit, from Milan",
  "financier": "Small French almond cake baked in a gold-bar shape",
  "madeleine": "Small French sponge cake baked in a scallop-shell mould",
  "operacake": "French layered almond cake with coffee and chocolate",
  "dobostorte": "Hungarian sponge layered cake topped with hard caramel",
  "basbousa": "Middle Eastern semolina cake soaked in sweet syrup",
  "gulabjamun": "Indian fried milk-solid balls soaked in rose-cardamom syrup",
  "jalebi": "Fried batter spirals soaked in syrup, popular in South Asia",
  "ladoo": "Indian sweet ball made from flour, sugar and ghee",
  "rasgulla": "Indian cheese-curd balls boiled in light sugar syrup",
  "halva": "Dense sweet of sesame paste or semolina, made across Asia",
  "turkishdelight": "Gel candy of starch and sugar, dusted with icing sugar",
  "dango": "Japanese sweet rice dumplings served on a skewer",
  "dorayaki": "Japanese pancakes sandwiching sweet red-bean paste",
  "taiyaki": "Japanese fish-shaped cake filled with sweet red-bean paste",
  "rugelach": "Jewish rolled pastry filled with nuts, jam or chocolate",
  "ummali": "Egyptian bread pudding baked with milk, nuts and raisins",
  // IMPOSSIBLE
  "kouignamann": "Breton butter cake of caramelized folded layers of dough",
  "cassata": "Sicilian sponge cake with ricotta, marzipan and candied fruit",
  "sfogliatella": "Neapolitan shell-shaped pastry with a ricotta filling",
  "zeppole": "Italian fried dough puffs, dusted with powdered sugar",
  "cannele": "French pastry with a soft custard center and caramel crust",
  "galaktoboureko": "Greek dessert of semolina custard in filo with syrup",
  "loukoumades": "Greek fried dough balls soaked in honey syrup",
  "revani": "Turkish semolina sponge cake soaked in sugar syrup",
  "tulumba": "Fried ridged dough soaked in syrup, common in Turkey",
  "maamoul": "Middle Eastern shortbread filled with dates or nuts",
  "luqaimat": "Arabian fried dough balls drizzled with date syrup",
  "qatayef": "Arab stuffed pancakes eaten during the month of Ramadan",
  "mooncake": "Chinese pastry with dense filling, eaten at Mid-Autumn",
  "tangyuan": "Chinese glutinous rice balls served in a warm sweet soup",
  "hotteok": "Korean pan-fried pancake filled with brown sugar syrup",
  "bingsu": "Korean shaved-ice dessert topped with fruit and red bean",
  "halohalo": "Filipino shaved ice mixed with sweet beans, fruit and milk",
  "bibingka": "Filipino rice cake baked in banana leaf, eaten at Christmas",
  "klepon": "Indonesian rice balls with palm sugar, rolled in coconut",
  "chimneycake": "Hungarian spit-roasted dough cake with a caramel crust",
  "kulfi": "Indian dense frozen dairy dessert, richer than ice cream",
  "barfi": "Indian milk-based fudge sweet cut into diamond pieces",
  "sandesh": "Bengali sweet made from fresh chhena cheese and sugar",
  "mishtidoi": "Bengali sweetened yogurt fermented in earthen pots",
  "kladdkaka": "Swedish sticky chocolate cake with a gooey, undercooked core",
};
