// «Guess the Dinosaur by its Silhouette» — GuessSync E114 · did-you-know facts, <=70 chars, verified true.
export const DINO_SILHOUETTES_FACTS = {
  // EASY
  trex: "Its bite force was among the strongest of any land animal ever",
  triceratops: "Its huge skull frill was made of solid bone, not just skin",
  stegosaurus: "Had a brain roughly the size of a walnut inside its skull",
  velociraptor: "Was actually turkey-sized, not the movie's human-sized raptor",
  brachiosaurus: "Its front legs were longer than its back legs, unlike most dinosaurs",
  diplodocus: "Its whip-like tail held around 80 vertebrae",
  ankylosaurus: "Swung a heavy bone club on its tail to fend off predators",
  parasaurolophus: "Its long crest may have worked like a trombone to make sound",
  spinosaurus: "The first dinosaur known to have spent much of its life in water",
  iguanodon: "Its thumb was a sharp spike, not a fifth finger",
  pachycephalosaurus: "Had a skull dome up to 10 inches thick on top",
  styracosaurus: "Its frill had up to six long spikes ringing the edge",
  therizinosaurus: "Grew claws longer than a human arm on each hand",
  carnotaurus: "Had two thick horns above its eyes like a bull",
  compsognathus: "One of the smallest dinosaurs, about the size of a chicken",
  archaeopteryx: "One of the earliest known links between dinosaurs and birds",
  kentrosaurus: "Had spikes running down its back and tail for defense",
  corythosaurus: "Its tall, rounded head crest resembled a helmet",
  dilophosaurus: "Had a pair of thin bony crests on top of its head",
  allosaurus: "One of the top predators of the late Jurassic period",
  giganotosaurus: "Was even longer than Tyrannosaurus rex in body length",
  baryonyx: "Had huge curved claws and a snout shaped like a crocodile's",
  deinonychus: "Its name means terrible claw, for the sickle claw on each foot",
  protoceratops: "A small early relative of Triceratops with a short frill",
  edmontosaurus: "One of the largest duck-billed dinosaurs ever found",

  // MEDIUM
  apatosaurus: "Once wrongly called Brontosaurus before its name was fixed",
  camarasaurus: "The most common large sauropod fossil found in North America",
  camptosaurus: "Could walk on two legs or drop to four to graze",
  maiasaura: "Its name means good mother lizard, for caring for its nest",
  lambeosaurus: "Had a hollow, hatchet-shaped crest on its head",
  hadrosaurus: "The first dinosaur skeleton mounted upright in a museum",
  ouranosaurus: "Had a low sail of skin running along its spine",
  amargasaurus: "Sported two rows of tall spines along its neck",
  nigersaurus: "Had roughly 500 teeth for cropping low plants like a mower",
  irritator: "A fish-eating spinosaur named for the frustration of a faked skull",
  megalosaurus: "The first dinosaur ever given a scientific name, in 1824",
  ceratosaurus: "Had a single horn on its snout and bony ridges over its eyes",
  torosaurus: "May have had the largest skull of any land animal ever",
  chasmosaurus: "Had one of the largest frills among horned dinosaurs",
  pentaceratops: "Its name means five-horned face, though two are cheek horns",
  einiosaurus: "Had a nose horn curved forward like a bottle opener",
  edmontonia: "An armored dinosaur with long shoulder spikes for defense",
  sauropelta: "Had long spikes along its neck and shoulders for defense",
  euoplocephalus: "Its eyelids were even armored with bony plates",
  huayangosaurus: "One of the earliest known plated stegosaur relatives",
  tuojiangosaurus: "A Jurassic plated dinosaur found in Sichuan, China",
  homalocephale: "Had a flatter skull dome than most dome-headed dinosaurs",
  prenocephale: "Had a smooth, rounded bone dome likely used in head-butting",
  gigantoraptor: "One of the largest known feathered dinosaurs, toothless and beaked",
  citipati: "Found fossilized sitting on its nest, guarding its eggs",

  // HARD
  coelophysis: "One of the earliest known dinosaurs, from the late Triassic",
  herrerasaurus: "One of the oldest known dinosaur genera, found in Argentina",
  eoraptor: "Among the earliest dinosaurs, roughly the size of a fox",
  plateosaurus: "One of the first dinosaurs to grow to a truly large size",
  massospondylus: "An early long-necked dinosaur that likely ate both plants and meat",
  lesothosaurus: "A small, fast plant-eater from early Jurassic southern Africa",
  hypsilophodon: "A small, agile plant-eater once mistakenly thought tree-climbing",
  thescelosaurus: "One of the last non-avian dinosaurs before the extinction event",
  dryosaurus: "A small, swift plant-eater with a beak and no front teeth",
  tenontosaurus: "Fossils are often found alongside Deinonychus tooth marks",
  guaibasaurus: "A Late Triassic dinosaur from Brazil, an early saurischian",
  troodon: "Had unusually large eyes and one of the highest brain sizes",
  saurornitholestes: "A small, sharp-clawed raptor from Late Cretaceous Canada",
  utahraptor: "The largest known raptor, far bigger than Velociraptor",
  achillobator: "A large raptor from Mongolia named for its Achilles tendon claw",
  dromaeosaurus: "Gave its name to the whole raptor family, the dromaeosaurs",
  microraptor: "A small, feathered dinosaur with wings on all four limbs",
  sinosauropteryx: "The first non-avian dinosaur found with clear fossil feathers",
  yutyrannus: "The largest known feathered dinosaur, a relative of T. rex",
  majungasaurus: "A Madagascar predator with evidence of eating its own kind",
  alioramus: "A slender tyrannosaur relative with a long, narrow snout",
  daspletosaurus: "A hefty tyrannosaur relative that lived before T. rex",
  albertosaurus: "A smaller tyrannosaur relative found in large bonebed groups",
  yangchuanosaurus: "China's largest known Jurassic predator",
  torvosaurus: "One of the largest meat-eating dinosaurs of the Jurassic",

  // IMPOSSIBLE
  sinornithosaurus: "An early feathered dinosaur that may have had a venomous bite",
  anchiornis: "One of the earliest known feathered dinosaurs, the size of a crow",
  caudipteryx: "Had tail feathers but wings too short to fly",
  elaphrosaurus: "A long-necked, lightly built theropod, unusual for its kind",
  falcarius: "An early relative of Therizinosaurus, still mostly meat-eating",
  nothronychus: "A clawed plant-eater found far from its usual Asian relatives",
  beipiaosaurus: "Had unusually long, coarse feathers like quills",
  limusaurus: "Started life with teeth but lost them completely as an adult",
  erlikosaurus: "Named after Erlik, the Mongolian god of death",
  segnosaurus: "Gave its name to the therizinosaur group, the segnosaurs",
  deinocheirus: "Known for decades only from giant eight-foot-long arms",
  masiakasaurus: "Had bizarre forward-jutting front teeth for spearing prey",
  ornithomimus: "A fast, toothless runner that likely ate plants and insects",
  australovenator: "Australia's most complete predatory dinosaur skeleton",
  ekrixinatosaurus: "Its name means 'explosion-born lizard,' unearthed using dynamite",
  aucasaurus: "A horned Argentine predator related to Carnotaurus",
  eustreptospondylus: "A large Jurassic predator found on England's Oxford coast",
  concavenator: "Had a mysterious hump on its back just above the hips",
  neovenator: "One of the most complete large theropods found in Europe",
  acrocanthosaurus: "Had tall spines forming a low ridge along its back",
  carcharodontosaurus: "Its name means 'shark-toothed lizard' for its serrated teeth",
  tyrannotitan: "One of the largest predators ever found in South America",
  cryolophosaurus: "The first predatory dinosaur discovered in Antarctica",
  bahariasaurus: "Known from fossils destroyed in a World War Two bombing raid",
  sinovenator: "A small, sharp-eyed troodontid closely tied to bird origins",
};
