// E13 «Guess the Dinosaur» — did-you-know facts, ≤70 chars each, verified.
export const DINO_FACTS = {
  // ===== EASY =====
  "tyrannosaurus-rex": "Its name means tyrant lizard king in Greek and Latin",
  "triceratops": "Its name means three-horned face; the frill could span 1 m",
  "stegosaurus": "Its brain was tiny, only about the size of a walnut",
  "velociraptor": "In real life it was only about the size of a turkey",
  "brachiosaurus": "It held its neck high to browse treetops like a giraffe",
  "spinosaurus": "The longest known meat-eating dinosaur, roughly 15 m",
  "ankylosaurus": "Its clubbed tail could swing hard enough to break bone",
  "diplodocus": "One of the longest dinosaurs, stretching about 25 m",
  "parasaurolophus": "Its long hollow head crest may have worked like a horn",
  "pteranodon": "A flying reptile, not a dinosaur, with a toothless beak",
  "brontosaurus": "Its name means thunder lizard; long doubted as a genus",
  "apatosaurus": "Its name means deceptive lizard, given to muddled bones",
  "allosaurus": "The top predator of Jurassic North America",
  "pachycephalosaurus": "Its domed skull was up to 25 cm of solid bone",
  "iguanodon": "One of the first dinosaurs ever scientifically named",
  "mosasaurus": "A giant marine reptile, not a dinosaur, ruling the seas",
  "archaeopteryx": "A feathered link between dinosaurs and modern birds",
  "dilophosaurus": "Named for the pair of thin crests atop its head",
  "gallimimus": "Its name means chicken mimic; it was a fast runner",
  "compsognathus": "One of the smallest dinosaurs, about chicken-sized",
  "megalodon": "A giant shark, not a dinosaur; its teeth top 18 cm",
  "woolly-mammoth": "An Ice Age relative of elephants, not a dinosaur",
  "smilodon": "A prehistoric cat with canines up to about 18 cm long",
  "quetzalcoatlus": "A pterosaur with an 11 m wingspan, not a dinosaur",
  "carnotaurus": "Its name means meat-eating bull, for its bull-like horns",

  // ===== MEDIUM =====
  "giganotosaurus": "Slightly longer than T. rex, one of the biggest hunters",
  "therizinosaurus": "It had the longest claws of any animal, near 1 m",
  "deinonychus": "Its name means terrible claw, for its sickle toe claw",
  "utahraptor": "The largest raptor known, far bigger than Velociraptor",
  "styracosaurus": "Its frill bore a crown of long, dramatic spikes",
  "kentrosaurus": "A spiky cousin of Stegosaurus from Tanzania",
  "plesiosaurus": "A long-necked marine reptile, not a dinosaur",
  "ichthyosaurus": "A dolphin-shaped marine reptile, not a dinosaur",
  "baryonyx": "Its name means heavy claw; it likely ate fish",
  "coelophysis": "One of the earliest dinosaurs, slim and fast",
  "oviraptor": "Its name means egg thief, from a wrong early guess",
  "protoceratops": "An early horned dinosaur without the real horns",
  "maiasaura": "Its name means good mother lizard, found near nests",
  "troodon": "It had one of the largest brains for its body size",
  "elasmosaurus": "A marine reptile with an extremely long neck",
  "pliosaurus": "A short-necked marine reptile with a huge bite",
  "dimetrodon": "A sail-backed animal that lived before the dinosaurs",
  "microraptor": "It had four wings, with flight feathers on its legs",
  "ornithomimus": "Its name means bird mimic; it looked like an ostrich",
  "edmontosaurus": "A large duck-billed dinosaur that lived in big herds",
  "corythosaurus": "Its head crest resembled a Greek helmet",
  "pachyrhinosaurus": "It had a thick bony pad instead of a nose horn",
  "mononykus": "Each arm ended in a single stubby clawed finger",
  "dreadnoughtus": "Known from one of the most complete giant skeletons",
  "argentinosaurus": "Among the heaviest land animals ever to live",

  // ===== HARD =====
  "carcharodontosaurus": "Its name means shark-toothed lizard",
  "suchomimus": "Its name means crocodile mimic, for its long jaws",
  "concavenator": "It had a strange tall hump on its back",
  "cryolophosaurus": "The first meat-eating dinosaur named from Antarctica",
  "amargasaurus": "It had two rows of tall spines running along its neck",
  "nigersaurus": "It had around 500 teeth in a wide, straight mouth",
  "sauropelta": "An armored dinosaur with spikes along its neck",
  "einiosaurus": "Its nose horn curved forward like a can opener",
  "nasutoceratops": "It had unusually long, forward-curving brow horns",
  "yutyrannus": "A large tyrannosaur preserved with feathers",
  "guanlong": "An early, crested relative of Tyrannosaurus",
  "sinosauropteryx": "The first non-avian dinosaur found with feathers",
  "majungasaurus": "Evidence suggests it sometimes ate its own kind",
  "psittacosaurus": "Its name means parrot lizard, for its beak",
  "kosmoceratops": "It had fifteen horns and spikes on its head",
  "acrocanthosaurus": "It had tall spines forming a ridge down its back",
  "mapusaurus": "A giant hunter that may have lived in packs",
  "ouranosaurus": "It had a sail or humped ridge along its back",
  "gigantoraptor": "A giant feathered dinosaur, far bigger than most birds",
  "dracorex": "Its name honors Hogwarts from the Harry Potter books",
  "tarbosaurus": "An Asian cousin of T. rex from Mongolia",
  "kronosaurus": "A marine reptile named after the Greek god Kronos",
  "deinosuchus": "A giant prehistoric croc relative, not a dinosaur",
  "sarcosuchus": "A crocodile relative nicknamed SuperCroc",
  "helicoprion": "A ratfish relative with a spiral saw of teeth",

  // ===== IMPOSSIBLE =====
  "deinocheirus": "Known for 50 years only from its giant 2.4 m arms",
  "shuvuuia": "A tiny dinosaur that may have hunted after dark",
  "epidexipteryx": "It had four long ribbon-like tail feathers",
  "anzu": "Nicknamed the chicken from hell for its bird-like look",
  "kaprosuchus": "A prehistoric croc nicknamed BoarCroc for its tusks",
  "beipiaosaurus": "An early feathered relative of Therizinosaurus",
  "tanystropheus": "Its neck was longer than its body and tail combined",
  "incisivosaurus": "It had buck teeth like a rodent's",
  "halszkaraptor": "A duck-like raptor that may have swum after fish",
  "balaur": "This island raptor had double sickle claws on each foot",
  "austroraptor": "A large raptor with a long, crocodile-like snout",
  "yi-qi": "Its name means strange wing; it had bat-like membranes",
  "kulindadromeus": "It hints even plant-eaters could bear feathers",
  "falcarius": "An early relative of the giant clawed Therizinosaurus",
  "nothronychus": "One of the first therizinosaurs found in America",
  "khaan": "Its name means lord or ruler in Mongolian",
  "masiakasaurus": "It had strange forward-jutting front teeth",
  "bajadasaurus": "It had long neck spines that pointed forward",
  "qianzhousaurus": "A long-snouted tyrannosaur nicknamed Pinocchio rex",
  "erlikosaurus": "A therizinosaur named after a Mongolian death god",
  "alvarezsaurus": "It named a family of slim, one-clawed dinosaurs",
  "concavenator-jr-eoraptor": "One of the earliest known dinosaurs, from Argentina",
  "yamaceratops": "A small, early horned dinosaur from Mongolia",
  "linhenykus": "The only known dinosaur with a single finger per hand",
  "sinornithosaurus": "One of the first raptors found with feathers",
};
