// E20 · «Guess the Dinosaur» — 100 (25/مستوى) · صور paleoart مجانية من ويكيبيديا dinos/<slug>.jpg · صوت dn-<slug>.wav (edge-tts مجاني)
// wiki = عنوان مقالة ويكيبيديا (لجلب الصورة) · name = الإجابة
export const DINOS = [
  // ===== EASY (25) =====
  { slug: "tyrannosaurus-rex", name: "Tyrannosaurus Rex", wiki: "Tyrannosaurus", level: "easy" },
  { slug: "triceratops", name: "Triceratops", wiki: "Triceratops", level: "easy" },
  { slug: "stegosaurus", name: "Stegosaurus", wiki: "Stegosaurus", level: "easy" },
  { slug: "velociraptor", name: "Velociraptor", wiki: "Velociraptor", level: "easy" },
  { slug: "brachiosaurus", name: "Brachiosaurus", wiki: "Brachiosaurus", level: "easy" },
  { slug: "spinosaurus", name: "Spinosaurus", wiki: "Spinosaurus", level: "easy" },
  { slug: "ankylosaurus", name: "Ankylosaurus", wiki: "Ankylosaurus", level: "easy" },
  { slug: "diplodocus", name: "Diplodocus", wiki: "Diplodocus", level: "easy" },
  { slug: "parasaurolophus", name: "Parasaurolophus", wiki: "Parasaurolophus", level: "easy" },
  { slug: "pteranodon", name: "Pteranodon", wiki: "Pteranodon", level: "easy" },
  { slug: "brontosaurus", name: "Brontosaurus", wiki: "Brontosaurus", level: "easy" },
  { slug: "apatosaurus", name: "Apatosaurus", wiki: "Apatosaurus", level: "easy" },
  { slug: "allosaurus", name: "Allosaurus", wiki: "Allosaurus", level: "easy" },
  { slug: "pachycephalosaurus", name: "Pachycephalosaurus", wiki: "Pachycephalosaurus", level: "easy" },
  { slug: "iguanodon", name: "Iguanodon", wiki: "Iguanodon", level: "easy" },
  { slug: "mosasaurus", name: "Mosasaurus", wiki: "Mosasaurus", level: "easy" },
  { slug: "archaeopteryx", name: "Archaeopteryx", wiki: "Archaeopteryx", level: "easy" },
  { slug: "dilophosaurus", name: "Dilophosaurus", wiki: "Dilophosaurus", level: "easy" },
  { slug: "gallimimus", name: "Gallimimus", wiki: "Gallimimus", level: "easy" },
  { slug: "compsognathus", name: "Compsognathus", wiki: "Compsognathus", level: "easy" },
  { slug: "megalodon", name: "Megalodon", wiki: "Megalodon", level: "easy" },
  { slug: "woolly-mammoth", name: "Woolly Mammoth", wiki: "Woolly mammoth", level: "easy" },
  { slug: "smilodon", name: "Sabre-toothed Cat", wiki: "Smilodon", level: "easy" },
  { slug: "quetzalcoatlus", name: "Quetzalcoatlus", wiki: "Quetzalcoatlus", level: "easy" },
  { slug: "carnotaurus", name: "Carnotaurus", wiki: "Carnotaurus", level: "easy" },

  // ===== MEDIUM (25) =====
  { slug: "giganotosaurus", name: "Giganotosaurus", wiki: "Giganotosaurus", level: "medium" },
  { slug: "therizinosaurus", name: "Therizinosaurus", wiki: "Therizinosaurus", level: "medium" },
  { slug: "deinonychus", name: "Deinonychus", wiki: "Deinonychus", level: "medium" },
  { slug: "utahraptor", name: "Utahraptor", wiki: "Utahraptor", level: "medium" },
  { slug: "styracosaurus", name: "Styracosaurus", wiki: "Styracosaurus", level: "medium" },
  { slug: "kentrosaurus", name: "Kentrosaurus", wiki: "Kentrosaurus", level: "medium" },
  { slug: "plesiosaurus", name: "Plesiosaurus", wiki: "Plesiosaurus", level: "medium" },
  { slug: "ichthyosaurus", name: "Ichthyosaurus", wiki: "Ichthyosaurus", level: "medium" },
  { slug: "baryonyx", name: "Baryonyx", wiki: "Baryonyx", level: "medium" },
  { slug: "coelophysis", name: "Coelophysis", wiki: "Coelophysis", level: "medium" },
  { slug: "oviraptor", name: "Oviraptor", wiki: "Oviraptor", level: "medium" },
  { slug: "protoceratops", name: "Protoceratops", wiki: "Protoceratops", level: "medium" },
  { slug: "maiasaura", name: "Maiasaura", wiki: "Maiasaura", level: "medium" },
  { slug: "troodon", name: "Troodon", wiki: "Troodon", level: "medium" },
  { slug: "elasmosaurus", name: "Elasmosaurus", wiki: "Elasmosaurus", level: "medium" },
  { slug: "pliosaurus", name: "Pliosaurus", wiki: "Pliosaurus", level: "medium" },
  { slug: "dimetrodon", name: "Dimetrodon", wiki: "Dimetrodon", level: "medium" },
  { slug: "microraptor", name: "Microraptor", wiki: "Microraptor", level: "medium" },
  { slug: "ornithomimus", name: "Ornithomimus", wiki: "Ornithomimus", level: "medium" },
  { slug: "edmontosaurus", name: "Edmontosaurus", wiki: "Edmontosaurus", level: "medium" },
  { slug: "corythosaurus", name: "Corythosaurus", wiki: "Corythosaurus", level: "medium" },
  { slug: "pachyrhinosaurus", name: "Pachyrhinosaurus", wiki: "Pachyrhinosaurus", level: "medium" },
  { slug: "mononykus", name: "Mononykus", wiki: "Mononykus", level: "medium" },
  { slug: "dreadnoughtus", name: "Dreadnoughtus", wiki: "Dreadnoughtus", level: "medium" },
  { slug: "argentinosaurus", name: "Argentinosaurus", wiki: "Argentinosaurus", level: "medium" },

  // ===== HARD (25) =====
  { slug: "carcharodontosaurus", name: "Carcharodontosaurus", wiki: "Carcharodontosaurus", level: "hard" },
  { slug: "suchomimus", name: "Suchomimus", wiki: "Suchomimus", level: "hard" },
  { slug: "concavenator", name: "Concavenator", wiki: "Concavenator", level: "hard" },
  { slug: "cryolophosaurus", name: "Cryolophosaurus", wiki: "Cryolophosaurus", level: "hard" },
  { slug: "amargasaurus", name: "Amargasaurus", wiki: "Amargasaurus", level: "hard" },
  { slug: "nigersaurus", name: "Nigersaurus", wiki: "Nigersaurus", level: "hard" },
  { slug: "sauropelta", name: "Sauropelta", wiki: "Sauropelta", level: "hard" },
  { slug: "einiosaurus", name: "Einiosaurus", wiki: "Einiosaurus", level: "hard" },
  { slug: "nasutoceratops", name: "Nasutoceratops", wiki: "Nasutoceratops", level: "hard" },
  { slug: "yutyrannus", name: "Yutyrannus", wiki: "Yutyrannus", level: "hard" },
  { slug: "guanlong", name: "Guanlong", wiki: "Guanlong", level: "hard" },
  { slug: "sinosauropteryx", name: "Sinosauropteryx", wiki: "Sinosauropteryx", level: "hard" },
  { slug: "majungasaurus", name: "Majungasaurus", wiki: "Majungasaurus", level: "hard" },
  { slug: "psittacosaurus", name: "Psittacosaurus", wiki: "Psittacosaurus", level: "hard" },
  { slug: "kosmoceratops", name: "Kosmoceratops", wiki: "Kosmoceratops", level: "hard" },
  { slug: "acrocanthosaurus", name: "Acrocanthosaurus", wiki: "Acrocanthosaurus", level: "hard" },
  { slug: "mapusaurus", name: "Mapusaurus", wiki: "Mapusaurus", level: "hard" },
  { slug: "ouranosaurus", name: "Ouranosaurus", wiki: "Ouranosaurus", level: "hard" },
  { slug: "gigantoraptor", name: "Gigantoraptor", wiki: "Gigantoraptor", level: "hard" },
  { slug: "dracorex", name: "Dracorex", wiki: "Dracorex", level: "hard" },
  { slug: "tarbosaurus", name: "Tarbosaurus", wiki: "Tarbosaurus", level: "hard" },
  { slug: "kronosaurus", name: "Kronosaurus", wiki: "Kronosaurus", level: "hard" },
  { slug: "deinosuchus", name: "Deinosuchus", wiki: "Deinosuchus", level: "hard" },
  { slug: "sarcosuchus", name: "Sarcosuchus", wiki: "Sarcosuchus", level: "hard" },
  { slug: "helicoprion", name: "Helicoprion", wiki: "Helicoprion", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { slug: "deinocheirus", name: "Deinocheirus", wiki: "Deinocheirus", level: "impossible" },
  { slug: "shuvuuia", name: "Shuvuuia", wiki: "Shuvuuia", level: "impossible" },
  { slug: "epidexipteryx", name: "Epidexipteryx", wiki: "Epidexipteryx", level: "impossible" },
  { slug: "anzu", name: "Anzu", wiki: "Anzu (dinosaur)", level: "impossible" },
  { slug: "kaprosuchus", name: "Kaprosuchus", wiki: "Kaprosuchus", level: "impossible" },
  { slug: "beipiaosaurus", name: "Beipiaosaurus", wiki: "Beipiaosaurus", level: "impossible" },
  { slug: "tanystropheus", name: "Tanystropheus", wiki: "Tanystropheus", level: "impossible" },
  { slug: "incisivosaurus", name: "Incisivosaurus", wiki: "Incisivosaurus", level: "impossible" },
  { slug: "halszkaraptor", name: "Halszkaraptor", wiki: "Halszkaraptor", level: "impossible" },
  { slug: "balaur", name: "Balaur", wiki: "Balaur (dinosaur)", level: "impossible" },
  { slug: "austroraptor", name: "Austroraptor", wiki: "Austroraptor", level: "impossible" },
  { slug: "yi-qi", name: "Yi Qi", wiki: "Yi (dinosaur)", level: "impossible" },
  { slug: "kulindadromeus", name: "Kulindadromeus", wiki: "Kulindadromeus", level: "impossible" },
  { slug: "falcarius", name: "Falcarius", wiki: "Falcarius", level: "impossible" },
  { slug: "nothronychus", name: "Nothronychus", wiki: "Nothronychus", level: "impossible" },
  { slug: "khaan", name: "Khaan", wiki: "Khaan", level: "impossible" },
  { slug: "masiakasaurus", name: "Masiakasaurus", wiki: "Masiakasaurus", level: "impossible" },
  { slug: "bajadasaurus", name: "Bajadasaurus", wiki: "Bajadasaurus", level: "impossible" },
  { slug: "qianzhousaurus", name: "Qianzhousaurus", wiki: "Qianzhousaurus", level: "impossible" },
  { slug: "erlikosaurus", name: "Erlikosaurus", wiki: "Erlikosaurus", level: "impossible" },
  { slug: "alvarezsaurus", name: "Alvarezsaurus", wiki: "Alvarezsaurus", level: "impossible" },
  { slug: "concavenator-jr-eoraptor", name: "Eoraptor", wiki: "Eoraptor", level: "impossible" },
  { slug: "yamaceratops", name: "Yamaceratops", wiki: "Yamaceratops", level: "impossible" },
  { slug: "linhenykus", name: "Linhenykus", wiki: "Linhenykus", level: "impossible" },
  { slug: "sinornithosaurus", name: "Sinornithosaurus", wiki: "Sinornithosaurus", level: "impossible" },
];

export const DINO_LEVELS = ["easy", "medium", "hard", "impossible"];
