// E198 disney-emoji-3 facts — one true <=70-char fact per character, shown on reveal.
export const DISNEY_EMOJI_3_FACTS = {
  // EASY
  "winnie-the-pooh": "A honey-loving bear who lives in the Hundred Acre Wood.",
  "tigger": "A bouncy, energetic tiger who loves to bounce on his tail.",
  "piglet": "Pooh's small, timid pink piglet best friend.",
  "eeyore": "A gloomy, gray donkey who often loses his tail.",
  "owl-winnie": "The wise, long-winded owl of the Hundred Acre Wood.",
  "kanga": "A caring kangaroo mother in the Hundred Acre Wood.",
  "roo": "Kanga's playful young kangaroo joey.",
  "christopher-robin": "The boy who owns and plays with the Hundred Acre Wood toys.",
  "geppetto": "The woodcarver who wished upon a star for Pinocchio.",
  "fairy-godmother": "Grants Cinderella's wish with a wave of her magic wand.",
  "flora": "The red-clad good fairy who blesses Aurora with beauty.",
  "fauna": "The green-clad good fairy who blesses Aurora with song.",
  "merryweather": "The blue-clad good fairy who weakens Maleficent's curse.",
  "doc-dwarf": "The bespectacled, fumble-worded leader of the Seven Dwarfs.",
  "grumpy-dwarf": "The gruff dwarf who secretly cares for Snow White.",
  "happy-dwarf": "The cheeriest and roundest of the Seven Dwarfs.",
  "sleepy-dwarf": "The drowsy dwarf who's always about to doze off.",
  "bashful-dwarf": "The shy, blushing dwarf smitten with Snow White.",
  "sneezy-dwarf": "The allergy-prone dwarf famous for huge sneezes.",
  "gus": "A plump, bread-loving mouse who helps Cinderella.",
  "jaq": "A clever mouse who leads Cinderella's animal friends.",
  "lucifer-cat": "Lady Tremaine's spiteful cat who torments the mice.",
  "smee": "Captain Hook's bumbling, loyal pirate first mate.",
  "nana-dog": "The Darling family's Newfoundland dog and nursemaid.",
  "prince-charming": "The prince who searches the kingdom for Cinderella.",

  // MEDIUM
  "honest-john": "A con-artist fox who leads Pinocchio astray.",
  "monstro": "A gigantic whale that swallows Pinocchio and Geppetto.",
  "lefou": "Gaston's bumbling, cheering sidekick in the village.",
  "maurice": "Belle's inventive father who stumbles into the Beast's castle.",
  "friar-tuck": "A portly badger friar and Robin Hood's loyal friend.",
  "sheriff-of-nottingham": "The greedy wolf lawman who taxes Nottingham's poor.",
  "skippy-rabbit": "A boastful young rabbit who idolizes Robin Hood.",
  "jock": "A feisty Scottish terrier and Lady's neighborhood friend.",
  "trusty": "An elderly bloodhound who's lost his sense of smell.",
  "tony-restaurant": "The restaurant owner who serves Lady and Tramp spaghetti.",
  "tod": "A red fox raised alongside a hound as an unlikely friend.",
  "copper": "A hound puppy who grows up to hunt his best friend, Tod.",
  "big-mama-owl": "A wise old owl who watches over Tod in the forest.",
  "widow-tweed": "The kind widow who raises Tod as an orphaned fox kit.",
  "sergeant-calhoun": "A tough, no-nonsense soldier from the game Hero's Duty.",
  "taffyta-muttonfudge": "A candy-themed racer and rival in Sugar Rush.",
  "mr-big": "A tiny but feared Arctic shrew crime boss in Zootopia.",
  "gazelle": "Zootopia's pop-star gazelle famous for her hit songs.",
  "clawhauser": "The friendly, donut-loving cheetah at Zootopia PD.",
  "fred-bighero6": "A comic-loving mascot who dreams of being a monster hero.",
  "honey-lemon": "A Big Hero 6 chemist who fights with colorful compounds.",
  "wasabi-bighero6": "A neat-freak Big Hero 6 member who wields plasma blades.",
  "skinner": "Gusteau's scheming former sous-chef turned restaurant owner.",
  "anton-ego": "The feared food critic who reviews Gusteau's restaurant.",
  "chick-hicks": "The arrogant rival racer chasing Piston Cup glory.",

  // HARD
  "shenzi": "The scheming female leader of the hyena trio in the Pride Lands.",
  "banzai": "One of Scar's mischievous hyena henchmen.",
  "ed-hyena": "The giggling, silent hyena of Scar's trio.",
  "bianca": "A glamorous mouse agent of the Rescue Aid Society.",
  "bernard": "A timid janitor mouse who becomes a brave rescue agent.",
  "orville": "The albatross pilot who flies the Rescue Aid Society's agents.",
  "madame-medusa": "A greedy pawnshop owner hunting a giant diamond.",
  "penny-rescuers": "An orphan kidnapped to retrieve the Devil's Eye diamond.",
  "chicken-little": "A small chicken who warns everyone the sky is falling.",
  "abby-mallard": "A duckling with a honking voice who dreams of singing.",
  "runt-of-the-litter": "A nervous, oversized piglet in Chicken Little's group.",
  "fish-out-of-water": "A silent fish who wears a bowl helmet to breathe on land.",
  "lewis-meet-robinsons": "A young inventor searching for his birth family.",
  "wilbur-robinson": "A time-traveling boy who befriends young inventor Lewis.",
  "bowler-hat-guy": "A villain obsessed with stealing Lewis's memory scanner.",
  "kenai": "A young man transformed into a bear to learn a lesson.",
  "koda": "An orphaned bear cub who befriends Kenai.",
  "rutt": "One of the squabbling comic-relief moose brothers.",
  "tuke": "The other half of Brother Bear's bickering moose duo.",
  "maggie-cow": "A stubborn cow searching for a new home on the range.",
  "mrs-caloway": "A prim, proper dairy cow on Patch of Heaven farm.",
  "aladar": "An iguanodon raised among lemurs after a meteor strike.",
  "neera": "A dinosaur herd member who falls for outsider Aladar.",
  "flik": "An inventive ant who seeks warrior bugs to fight grasshoppers.",
  "hopper": "The tyrannical grasshopper who terrorizes Flik's ant colony.",

  // IMPOSSIBLE
  "atta": "The anxious princess ant preparing to lead the colony.",
  "dot-bugslife": "Atta's spirited little sister who befriends Flik.",
  "heimlich": "A hungry caterpillar dreaming of becoming a butterfly.",
  "francis-bugslife": "A short-tempered ladybug often mistaken for female.",
  "p-t-flea": "The gruff ringmaster of a traveling flea circus.",
  "manny-mantis": "A theatrical mantis magician in P.T. Flea's circus.",
  "gypsy-moth": "Manny's glamorous moth assistant in the circus act.",
  "rosie-spider": "A dry-witted black widow spider in the circus troupe.",
  "slim-stickbug": "A gentle walking stick insect in the circus troupe.",
  "dim-bugslife": "A gentle giant beetle who dreams of flying.",
  "tuck-and-roll": "Twin pill bug warriors who love to fight and roll.",
  "molt": "Hopper's dim-witted younger grasshopper brother.",
  "zurg": "Buzz Lightyear's arch-nemesis, Emperor of the planet Z.",
  "wheezy": "A squeaky penguin toy whose squeaker has broken.",
  "rocky-gibraltar": "A wrestling action-figure toy with a masked look.",
  "trixie-toystory": "A triceratops toy obsessed with video game role-play.",
  "mr-pricklepants": "A dramatic thespian hedgehog toy who loves theater.",
  "buttercup-toystory": "A vain unicorn toy who narrates fanciful stories.",
  "sid-phillips": "Andy's next-door neighbor who mutilates and blows up toys.",
  "andy-davis": "The boy who cherishes and eventually passes on his toys.",
  "bonnie-anderson": "The kind girl who inherits Andy's beloved toy collection.",
  "duke-caboom": "A daredevil stuntman toy modeled after a 1970s stunt star.",
  "combat-carl": "A gruff, battle-scarred action-figure toy soldier.",
  "stinky-pete": "A bitter prospector toy who was never sold as a gift.",
  "al-mcwhiggin": "The greedy toy store owner who kidnaps Woody to sell him.",
};
