// E250 «Guess the Disney Character by Emoji» — MILESTONE 250th episode, 5th Disney episode — 100 Disney/Pixar characters · 25/tier · clue = plain Unicode emoji
// VO: sfx/ed5-<id>.wav
export const DISNEY_EMOJI5 = [
  { id: "timon", title: "Timon", emojis: "🪱🎶", level: "easy" },
  { id: "jack-skellington", title: "Jack Skellington", emojis: "🎃💀", level: "easy" },
  { id: "sally-nightmare", title: "Sally", emojis: "🧵💜", level: "easy" },
  { id: "oogie-boogie", title: "Oogie Boogie", emojis: "🐛🎲", level: "easy" },
  { id: "bolt-dog", title: "Bolt", emojis: "⚡🐕", level: "easy" },
  { id: "mittens-bolt", title: "Mittens", emojis: "🐈🍤", level: "easy" },
  { id: "sox-lightyear", title: "Sox", emojis: "🤖🐈", level: "easy" },
  { id: "star-wish", title: "Star", emojis: "⭐🙌", level: "easy" },
  { id: "valentino-wish", title: "Valentino", emojis: "🐐✨", level: "easy" },
  { id: "terk-tarzan", title: "Terk", emojis: "🦍🎸", level: "easy" },
  { id: "tantor-tarzan", title: "Tantor", emojis: "🐘😨", level: "easy" },
  { id: "jane-porter", title: "Jane Porter", emojis: "🎨☂", level: "easy" },
  { id: "clayton-tarzan", title: "Clayton", emojis: "🔫🎩", level: "easy" },
  { id: "rajah-aladdin", title: "Rajah", emojis: "🐅🍇", level: "easy" },
  { id: "roger-radcliffe", title: "Roger Radcliffe", emojis: "🎹🐕", level: "easy" },
  { id: "anita-radcliffe", title: "Anita Radcliffe", emojis: "👗🐕", level: "easy" },
  { id: "perdita", title: "Perdita", emojis: "🐕🤍", level: "easy" },
  { id: "mrs-potato-head", title: "Mrs. Potato Head", emojis: "🥔👛", level: "easy" },
  { id: "luigi-cars", title: "Luigi", emojis: "🛞🍕", level: "easy" },
  { id: "guido-cars", title: "Guido", emojis: "🔧🏁", level: "easy" },
  { id: "flo-cars", title: "Flo", emojis: "⛽💃", level: "easy" },
  { id: "oaken-frozen", title: "Oaken", emojis: "🧖🛒", level: "easy" },
  { id: "grand-pabbie", title: "Grand Pabbie", emojis: "🗿🔮", level: "easy" },
  { id: "long-john-silver", title: "Long John Silver", emojis: "🦜🦿", level: "easy" },
  { id: "rhino-bolt", title: "Rhino", emojis: "🐹🛞", level: "easy" },
  { id: "kala-tarzan", title: "Kala", emojis: "🦍💞", level: "medium" },
  { id: "kerchak-tarzan", title: "Kerchak", emojis: "🦍👑", level: "medium" },
  { id: "basil-mousedetective", title: "Basil", emojis: "🔍🐭", level: "medium" },
  { id: "dodger-oliver", title: "Dodger", emojis: "🐕🕶", level: "medium" },
  { id: "fagin-oliver", title: "Fagin", emojis: "🎩🐕", level: "medium" },
  { id: "sykes-oliver", title: "Sykes", emojis: "🚔😈", level: "medium" },
  { id: "philippe-belle", title: "Philippe", emojis: "🐴📖", level: "medium" },
  { id: "duke-weaselton", title: "Duke Weaselton", emojis: "🦡👔", level: "medium" },
  { id: "bellwether-zootopia", title: "Bellwether", emojis: "🐑😈", level: "medium" },
  { id: "finnick-zootopia", title: "Finnick", emojis: "🦊🍦", level: "medium" },
  { id: "vanessa-mermaid", title: "Vanessa", emojis: "🐙💋", level: "medium" },
  { id: "max-mermaid-dog", title: "Max", emojis: "🐕🌊", level: "medium" },
  { id: "captain-amelia", title: "Captain Amelia", emojis: "🐱⚓", level: "medium" },
  { id: "ben-treasureplanet", title: "B.E.N.", emojis: "🤖🔋", level: "medium" },
  { id: "dr-doppler", title: "Dr. Doppler", emojis: "🔭🐶", level: "medium" },
  { id: "morph-treasureplanet", title: "Morph", emojis: "👾💫", level: "medium" },
  { id: "sparky-frankenweenie", title: "Sparky", emojis: "🔬🐕", level: "medium" },
  { id: "victor-frankenstein", title: "Victor Frankenstein", emojis: "⚡🧪", level: "medium" },
  { id: "elliot-petesdragon", title: "Elliot", emojis: "🐉🍏", level: "medium" },
  { id: "alan-a-dale", title: "Alan-a-Dale", emojis: "🐓🎻", level: "medium" },
  { id: "gopher-pooh", title: "Gopher", emojis: "🕳🌰", level: "medium" },
  { id: "king-of-hearts", title: "King of Hearts", emojis: "❤👑", level: "medium" },
  { id: "john-darling", title: "John Darling", emojis: "🎩👦", level: "medium" },
  { id: "izzy-hawthorne", title: "Izzy Hawthorne", emojis: "🚀👧", level: "medium" },
  { id: "yelena-frozen2", title: "Yelena", emojis: "🏹🍂", level: "medium" },
  { id: "ryder-frozen2", title: "Ryder", emojis: "🐴🛡", level: "hard" },
  { id: "honeymaren-frozen2", title: "Honeymaren", emojis: "🦌👩", level: "hard" },
  { id: "lieutenant-mattias", title: "Lieutenant Mattias", emojis: "🛡⚔", level: "hard" },
  { id: "rourke-atlantis", title: "Rourke", emojis: "💣😈", level: "hard" },
  { id: "helga-atlantis", title: "Helga", emojis: "🗡👩", level: "hard" },
  { id: "vinny-atlantis", title: "Vinny", emojis: "💣😄", level: "hard" },
  { id: "sweet-atlantis", title: "Sweet", emojis: "🩺😊", level: "hard" },
  { id: "cookie-atlantis", title: "Cookie", emojis: "🍳🤠", level: "hard" },
  { id: "franny-robinson", title: "Franny Robinson", emojis: "🎤👩", level: "hard" },
  { id: "buck-cluck", title: "Buck Cluck", emojis: "🐔👨", level: "hard" },
  { id: "eilonwy", title: "Eilonwy", emojis: "🔮👸", level: "hard" },
  { id: "fflewddur-fflam", title: "Fflewddur Fflam", emojis: "🎻🤥", level: "hard" },
  { id: "gurgi", title: "Gurgi", emojis: "🍗😜", level: "hard" },
  { id: "taran", title: "Taran", emojis: "🐷⚔", level: "hard" },
  { id: "chief-benja", title: "Chief Benja", emojis: "🐉🛡", level: "hard" },
  { id: "gramma-tala", title: "Gramma Tala", emojis: "🌊👵", level: "hard" },
  { id: "chief-tui", title: "Chief Tui", emojis: "🏝👑", level: "hard" },
  { id: "sina-moana", title: "Sina", emojis: "🌺👩", level: "hard" },
  { id: "pepita", title: "Pepita", emojis: "🐆✨", level: "hard" },
  { id: "django-ratatouille", title: "Django", emojis: "🐀🍳", level: "hard" },
  { id: "agustin-madrigal", title: "Agustín Madrigal", emojis: "🤧💕", level: "hard" },
  { id: "massimo-marcovaldo", title: "Massimo Marcovaldo", emojis: "🎣💪", level: "hard" },
  { id: "daniela-paguro", title: "Daniela Paguro", emojis: "🐟💙", level: "hard" },
  { id: "lorenzo-paguro", title: "Lorenzo Paguro", emojis: "🐟😰", level: "hard" },
  { id: "bernie-lumen", title: "Bernie Lumen", emojis: "🔥📋", level: "hard" },
  { id: "cinder-lumen", title: "Cinder Lumen", emojis: "🔥👵", level: "impossible" },
  { id: "clod-elemental", title: "Clod", emojis: "🌍😊", level: "impossible" },
  { id: "laurel-lightfoot", title: "Laurel Lightfoot", emojis: "🛡👩", level: "impossible" },
  { id: "blazey-onward", title: "Blazey", emojis: "🐉🔥", level: "impossible" },
  { id: "miriam-turningred", title: "Miriam", emojis: "😆🎸", level: "impossible" },
  { id: "priya-turningred", title: "Priya", emojis: "🖤😐", level: "impossible" },
  { id: "abby-park-turningred", title: "Abby Park", emojis: "🥊😆", level: "impossible" },
  { id: "tyler-turningred", title: "Tyler", emojis: "🐼😏", level: "impossible" },
  { id: "jin-lee-turningred", title: "Jin Lee", emojis: "🏮😌", level: "impossible" },
  { id: "grandma-wu-turningred", title: "Grandma Wu", emojis: "👵🐼", level: "impossible" },
  { id: "robaire-4town", title: "Robaire", emojis: "🎤💃", level: "impossible" },
  { id: "dorothea-williams-soul", title: "Dorothea Williams", emojis: "🎷👩", level: "impossible" },
  { id: "curley-soul", title: "Curley", emojis: "🥁😅", level: "impossible" },
  { id: "queen-amaya-wish", title: "Queen Amaya", emojis: "👑💫", level: "impossible" },
  { id: "ethan-clade", title: "Ethan Clade", emojis: "⚽🧭", level: "impossible" },
  { id: "meridian-clade", title: "Meridian Clade", emojis: "✈🌱", level: "impossible" },
  { id: "jaeger-clade", title: "Jaeger Clade", emojis: "🧭👴", level: "impossible" },
  { id: "legend-strangeworld", title: "Legend", emojis: "🐕🧭", level: "impossible" },
  { id: "splat-strangeworld", title: "Splat", emojis: "💠👾", level: "impossible" },
  { id: "searcher-clade", title: "Searcher Clade", emojis: "🌱🌵", level: "impossible" },
  { id: "oscar-and-felipe", title: "Óscar and Felipe", emojis: "👴🎻", level: "impossible" },
  { id: "jasper-101dalmatians", title: "Jasper", emojis: "🔦😈", level: "impossible" },
  { id: "patch-101dalmatians", title: "Patch", emojis: "🐕🎬", level: "impossible" },
  { id: "rolly-101dalmatians", title: "Rolly", emojis: "🐕🍔", level: "impossible" },
  { id: "trigger-robinhood", title: "Trigger", emojis: "🦅💰", level: "impossible" },
];
