// E198 «Guess the Disney Character by Emoji 3» — 100 characters · 25/tier
// VO: sfx/e198-<id>.wav
export const DISNEY_EMOJI_3 = [
  // ===== EASY (25) =====
  { id: "winnie-the-pooh", title: "Winnie the Pooh", emojis: "🐻🍯", level: "easy" },
  { id: "tigger", title: "Tigger", emojis: "🐯🌀", level: "easy" },
  { id: "piglet", title: "Piglet", emojis: "🐷🎈", level: "easy" },
  { id: "eeyore", title: "Eeyore", emojis: "🫏😔", level: "easy" },
  { id: "owl-winnie", title: "Owl", emojis: "🦉🍯", level: "easy" },
  { id: "kanga", title: "Kanga", emojis: "🦘👝", level: "easy" },
  { id: "roo", title: "Roo", emojis: "🦘👶", level: "easy" },
  { id: "christopher-robin", title: "Christopher Robin", emojis: "👦🌳", level: "easy" },
  { id: "geppetto", title: "Geppetto", emojis: "🧓🔨", level: "easy" },
  { id: "fairy-godmother", title: "Fairy Godmother", emojis: "🪄👵", level: "easy" },
  { id: "flora", title: "Flora", emojis: "🧚💗", level: "easy" },
  { id: "fauna", title: "Fauna", emojis: "🧚💚", level: "easy" },
  { id: "merryweather", title: "Merryweather", emojis: "🧚💙", level: "easy" },
  { id: "doc-dwarf", title: "Doc", emojis: "👓⛏", level: "easy" },
  { id: "grumpy-dwarf", title: "Grumpy", emojis: "😠⛏", level: "easy" },
  { id: "happy-dwarf", title: "Happy", emojis: "😄⛏", level: "easy" },
  { id: "sleepy-dwarf", title: "Sleepy", emojis: "😴⛏", level: "easy" },
  { id: "bashful-dwarf", title: "Bashful", emojis: "😳⛏", level: "easy" },
  { id: "sneezy-dwarf", title: "Sneezy", emojis: "🤧⛏", level: "easy" },
  { id: "gus", title: "Gus", emojis: "🐭🧀", level: "easy" },
  { id: "jaq", title: "Jaq", emojis: "🐭🧵", level: "easy" },
  { id: "lucifer-cat", title: "Lucifer", emojis: "🐈😼", level: "easy" },
  { id: "smee", title: "Smee", emojis: "⚓😅", level: "easy" },
  { id: "nana-dog", title: "Nana", emojis: "🐕👶", level: "easy" },
  { id: "prince-charming", title: "Prince Charming", emojis: "🤴👠", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "honest-john", title: "Honest John", emojis: "🦊🎩", level: "medium" },
  { id: "monstro", title: "Monstro", emojis: "🐳😱", level: "medium" },
  { id: "lefou", title: "LeFou", emojis: "😂🍻", level: "medium" },
  { id: "maurice", title: "Maurice", emojis: "🧓⚙", level: "medium" },
  { id: "friar-tuck", title: "Friar Tuck", emojis: "⛪🐻", level: "medium" },
  { id: "sheriff-of-nottingham", title: "Sheriff of Nottingham", emojis: "🐺👑", level: "medium" },
  { id: "skippy-rabbit", title: "Skippy", emojis: "🐰🎒", level: "medium" },
  { id: "jock", title: "Jock", emojis: "🐕🧢", level: "medium" },
  { id: "trusty", title: "Trusty", emojis: "🐕👃", level: "medium" },
  { id: "tony-restaurant", title: "Tony", emojis: "🍝🎶", level: "medium" },
  { id: "tod", title: "Tod", emojis: "🦊🐕", level: "medium" },
  { id: "copper", title: "Copper", emojis: "🐕🌲", level: "medium" },
  { id: "big-mama-owl", title: "Big Mama", emojis: "🦉🌰", level: "medium" },
  { id: "widow-tweed", title: "Widow Tweed", emojis: "👵🧡", level: "medium" },
  { id: "sergeant-calhoun", title: "Sergeant Calhoun", emojis: "🎖😠", level: "medium" },
  { id: "taffyta-muttonfudge", title: "Taffyta Muttonfudge", emojis: "🍭🏎", level: "medium" },
  { id: "mr-big", title: "Mr. Big", emojis: "🐹👑", level: "medium" },
  { id: "gazelle", title: "Gazelle", emojis: "🐐🎤", level: "medium" },
  { id: "clawhauser", title: "Clawhauser", emojis: "🐆🍩", level: "medium" },
  { id: "fred-bighero6", title: "Fred", emojis: "🦖🎭", level: "medium" },
  { id: "honey-lemon", title: "Honey Lemon", emojis: "🧪💛", level: "medium" },
  { id: "wasabi-bighero6", title: "Wasabi", emojis: "🔪🍤", level: "medium" },
  { id: "skinner", title: "Skinner", emojis: "🐀😾", level: "medium" },
  { id: "anton-ego", title: "Anton Ego", emojis: "📝🍽", level: "medium" },
  { id: "chick-hicks", title: "Chick Hicks", emojis: "🏎😈", level: "medium" },

  // ===== HARD (25) =====
  { id: "shenzi", title: "Shenzi", emojis: "🐺😈", level: "hard" },
  { id: "banzai", title: "Banzai", emojis: "🐺😆", level: "hard" },
  { id: "ed-hyena", title: "Ed", emojis: "🐺🤪", level: "hard" },
  { id: "bianca", title: "Bianca", emojis: "🐭✈", level: "hard" },
  { id: "bernard", title: "Bernard", emojis: "🐭🎗", level: "hard" },
  { id: "orville", title: "Orville", emojis: "🦅✈", level: "hard" },
  { id: "madame-medusa", title: "Madame Medusa", emojis: "💎😈", level: "hard" },
  { id: "penny-rescuers", title: "Penny", emojis: "👧💎", level: "hard" },
  { id: "chicken-little", title: "Chicken Little", emojis: "🐔📢", level: "hard" },
  { id: "abby-mallard", title: "Abby Mallard", emojis: "🦆🎤", level: "hard" },
  { id: "runt-of-the-litter", title: "Runt of the Litter", emojis: "🐷😰", level: "hard" },
  { id: "fish-out-of-water", title: "Fish Out of Water", emojis: "🐠🥽", level: "hard" },
  { id: "lewis-meet-robinsons", title: "Lewis", emojis: "🧢🔧", level: "hard" },
  { id: "wilbur-robinson", title: "Wilbur Robinson", emojis: "🎩⏳", level: "hard" },
  { id: "bowler-hat-guy", title: "Bowler Hat Guy", emojis: "🎩😈", level: "hard" },
  { id: "kenai", title: "Kenai", emojis: "🐻⭐", level: "hard" },
  { id: "koda", title: "Koda", emojis: "🐻🐾", level: "hard" },
  { id: "rutt", title: "Rutt", emojis: "🦌😂", level: "hard" },
  { id: "tuke", title: "Tuke", emojis: "🦌🤙", level: "hard" },
  { id: "maggie-cow", title: "Maggie", emojis: "🐄🤠", level: "hard" },
  { id: "mrs-caloway", title: "Mrs. Caloway", emojis: "🐄🎀", level: "hard" },
  { id: "aladar", title: "Aladar", emojis: "🦕🌋", level: "hard" },
  { id: "neera", title: "Neera", emojis: "🦕🌿", level: "hard" },
  { id: "flik", title: "Flik", emojis: "🐜🌾", level: "hard" },
  { id: "hopper", title: "Hopper", emojis: "🦗😈", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "atta", title: "Atta", emojis: "🐜👑", level: "impossible" },
  { id: "dot-bugslife", title: "Dot", emojis: "🐜✨", level: "impossible" },
  { id: "heimlich", title: "Heimlich", emojis: "🐛🍫", level: "impossible" },
  { id: "francis-bugslife", title: "Francis", emojis: "🐞😤", level: "impossible" },
  { id: "p-t-flea", title: "P.T. Flea", emojis: "🎪🦗", level: "impossible" },
  { id: "manny-mantis", title: "Manny", emojis: "🦋🎭", level: "impossible" },
  { id: "gypsy-moth", title: "Gypsy", emojis: "🦋💄", level: "impossible" },
  { id: "rosie-spider", title: "Rosie", emojis: "🕷🖤", level: "impossible" },
  { id: "slim-stickbug", title: "Slim", emojis: "🌿🐛", level: "impossible" },
  { id: "dim-bugslife", title: "Dim", emojis: "🪲💡", level: "impossible" },
  { id: "tuck-and-roll", title: "Tuck and Roll", emojis: "🐞⚔", level: "impossible" },
  { id: "molt", title: "Molt", emojis: "🦗😰", level: "impossible" },
  { id: "zurg", title: "Emperor Zurg", emojis: "🚀😈", level: "impossible" },
  { id: "wheezy", title: "Wheezy", emojis: "🐧🎺", level: "impossible" },
  { id: "rocky-gibraltar", title: "Rocky Gibraltar", emojis: "🤼💪", level: "impossible" },
  { id: "trixie-toystory", title: "Trixie", emojis: "🦕📱", level: "impossible" },
  { id: "mr-pricklepants", title: "Mr. Pricklepants", emojis: "🦔🎭", level: "impossible" },
  { id: "buttercup-toystory", title: "Buttercup", emojis: "🦄✨", level: "impossible" },
  { id: "sid-phillips", title: "Sid Phillips", emojis: "👦💣", level: "impossible" },
  { id: "andy-davis", title: "Andy Davis", emojis: "👦🤠", level: "impossible" },
  { id: "bonnie-anderson", title: "Bonnie", emojis: "👧🎨", level: "impossible" },
  { id: "duke-caboom", title: "Duke Caboom", emojis: "🏍🪖", level: "impossible" },
  { id: "combat-carl", title: "Combat Carl", emojis: "🪖💥", level: "impossible" },
  { id: "stinky-pete", title: "Stinky Pete", emojis: "🤠💰", level: "impossible" },
  { id: "al-mcwhiggin", title: "Al McWhiggin", emojis: "🐔🏪", level: "impossible" },
];
