// «Guess the Dog Breed» — did-you-know facts, ≤70 chars each, verified.
export const DOG_FACTS = {
  // EASY
  "labrador": "Bred in Newfoundland to help fishermen haul in their nets",
  "goldenretriever": "Developed in Scotland to retrieve waterfowl for hunters",
  "germanshepherd": "Created in 1899 Germany as a herding and police dog",
  "bulldog": "Once bred in England for the cruel sport of bull-baiting",
  "poodle": "A water retriever for ducks; its fancy cut once kept joints warm",
  "beagle": "A small scent hound bred in England to hunt rabbits",
  "rottweiler": "A Roman drover dog that guarded cattle and pulled carts",
  "boxer": "German breed developed from the extinct Bullenbeisser",
  "dachshund": "German 'badger dog' bred to dig into badger burrows",
  "chihuahua": "World's smallest dog breed, named after a Mexican state",
  "pug": "Ancient Chinese lapdog once prized by Buddhist monks",
  "husky": "Bred by the Chukchi people of Siberia to pull sleds",
  "bordercollie": "Widely rated the world's most intelligent dog breed",
  "dalmatian": "Ran beside carriages as a guard; born pure white",
  "corgi": "A Welsh herder; 'corgi' means 'dwarf dog' in Welsh",
  "greatdane": "A giant German breed once used to hunt wild boar",
  "doberman": "Bred by a German tax collector for personal protection",
  "shihtzu": "Tibetan-Chinese royal lapdog; the name means 'lion dog'",
  "pomeranian": "A tiny spitz shrunk down from big Arctic sled dogs",
  "yorkshireterrier": "Bred in England to catch rats in clothing mills",
  "saintbernard": "Alpine monks used them to rescue travelers lost in snow",
  "cockerspaniel": "Named for flushing woodcock birds out for hunters",
  "bassethound": "Its long ears sweep scent up toward its powerful nose",
  "jackrussell": "Bred by an English parson to chase foxes from dens",
  "maltese": "An ancient lapdog prized around the Mediterranean for ages",
  // MEDIUM
  "australianshepherd": "Despite its name, it was actually developed in the USA",
  "bernesemountaindog": "A Swiss farm dog bred to pull carts and herd cattle",
  "shibainu": "Japan's smallest native breed and an ancient hunting dog",
  "akita": "Loyal Japanese breed; Hachiko waited years for his owner",
  "samoyed": "A Siberian breed bred to herd reindeer and pull sleds",
  "weimaraner": "The 'Gray Ghost' bred for German nobility to hunt game",
  "vizsla": "A Hungarian pointer that bonds so closely it's a 'velcro dog'",
  "bloodhound": "Its nose is so accurate it can be used as court evidence",
  "newfoundland": "A powerful swimmer with webbed feet, bred for water rescue",
  "chowchow": "An ancient Chinese breed with a rare blue-black tongue",
  "whippet": "Once called the 'poor man's racehorse' for its speed",
  "bullterrier": "Instantly known for its unique egg-shaped head",
  "papillon": "Named for ears shaped like a butterfly's spread wings",
  "bichonfrise": "A cheerful lapdog long favored in French royal courts",
  "malamute": "An Arctic sled dog bred by Alaska's Mahlemut people",
  "canecorso": "An Italian mastiff descended from Roman war dogs",
  "sharpei": "A Chinese breed famous for its deep wrinkles and blue tongue",
  "havanese": "The national dog of Cuba, its only native breed",
  "irishsetter": "An Irish gundog known for its rich mahogany-red coat",
  "greyhound": "The fastest dog breed, able to sprint over 40 mph",
  "pekingese": "An ancient Chinese breed once kept only by royalty",
  "bullmastiff": "Bred in England to catch poachers on country estates",
  "staffordshirebullterrier": "An affectionate English breed once bred for fighting",
  "wheatenterrier": "An Irish farm terrier with a soft, wheat-colored coat",
  "englishsetter": "One of the oldest gundogs, bred to point game birds",
  // HARD
  "basenji": "The 'barkless dog' of Africa that yodels instead",
  "rhodesianridgeback": "African breed with a ridge of backward-growing hair",
  "keeshond": "A Dutch barge dog and symbol of an 18th-century revolt",
  "schipperke": "A small Belgian breed once kept aboard canal barges",
  "bedlingtonterrier": "An English terrier groomed to look like a lamb",
  "afghanhound": "An ancient sighthound bred to hunt in mountain terrain",
  "saluki": "One of the oldest breeds, prized by ancient Egyptians",
  "borzoi": "A Russian sighthound bred by nobles to course wolves",
  "leonberger": "A giant German breed said to resemble a lion",
  "tibetanmastiff": "An ancient guardian of Himalayan flocks and monasteries",
  "kuvasz": "A Hungarian guardian dog once owned only by royalty",
  "briard": "An ancient French sheepdog said to be kept by Napoleon",
  "beauceron": "A French herder with double dewclaws on each hind leg",
  "belgianmalinois": "A Belgian herder now widely used by military and police",
  "anatolianshepherd": "A Turkish breed that guards livestock from wolves",
  "doguedebordeaux": "A French mastiff with the largest head of any dog",
  "neapolitanmastiff": "An Italian guard dog descended from Roman war dogs",
  "puli": "A Hungarian herder with a coat of long natural dreadlocks",
  "komondor": "A Hungarian guardian with a heavy corded 'mop' coat",
  "norwegianelkhound": "An ancient Norse breed that hunted moose",
  "finnishspitz": "Finland's national dog, bred to bark at game birds",
  "lagottoromagnolo": "An Italian water dog now prized for hunting truffles",
  "wirefoxterrier": "An English terrier bred to drive foxes from their dens",
  "cairnterrier": "Toto in 'The Wizard of Oz' was a Cairn Terrier",
  "portuguesewaterdog": "Bred in Portugal to herd fish into fishermen's nets",
  // IMPOSSIBLE
  "azawakh": "A lean sighthound bred by nomads of the West African Sahel",
  "xoloitzcuintli": "An ancient Mexican hairless dog sacred to the Aztecs",
  "bergamasco": "An Italian sheepdog with a coat of matted felt-like flocks",
  "mudi": "A rare Hungarian farm dog that herds and hunts vermin",
  "otterhound": "A rare British scent hound bred to hunt otters in water",
  "sussexspaniel": "A rare English spaniel with a golden-liver coat",
  "skyeterrier": "From Scotland's Isle of Skye; long body on short legs",
  "sealyhamterrier": "A rare Welsh terrier bred to hunt badgers and otters",
  "ceskyterrier": "A Czech terrier from crossing Sealyham and Scottish",
  "kooikerhondje": "A Dutch dog that lured ducks into traps with its tail",
  "stabyhoun": "A rare Dutch farm dog from the region of Friesland",
  "lowchen": "The 'little lion dog,' groomed to resemble a tiny lion",
  "thairidgeback": "A Thai breed with a ridge of hair along its back",
  "peruvianincaorchid": "An ancient Peruvian hairless dog, older than the Inca Empire",
  "norwegianlundehund": "A puffin hunter with six toes on each foot",
  "chinook": "A rare American sled dog and New Hampshire's state dog",
  "cirnecodelletna": "A Sicilian hunting dog from the slopes of Mount Etna",
  "pumi": "A Hungarian herding breed with a curly, corkscrew coat",
  "lancashireheeler": "A tiny English dog bred to drive cattle and hunt rats",
  "braccoitaliano": "One of the oldest pointing breeds, hailing from Italy",
  "grandbassetgriffonvendeen": "A long, low French scent hound from the Vendée",
  "pyreneanshepherd": "A small French herder of the Pyrenees mountains",
  "swedishvallhund": "A Swedish cattle dog dating back to the Viking age",
  "carolinadog": "A wild American dog found roaming the rural Southeast",
  "finnishlapphund": "Bred by the Sámi people to herd reindeer in Lapland",
};
