// «Guess the Dog Breed v2» — did-you-know facts, ≤70 chars each, verified TRUE.
export const DOGS2_FACTS = {
  // EASY
  "frenchbulldog": "Bred as a companion; its bat ears are a breed hallmark",
  "cavalier": "Named after King Charles II, who adored the toy spaniels",
  "greatpyrenees": "Guarded sheep flocks high in the Pyrenees Mountains",
  "mastiff": "One of the heaviest breeds, weighing over 90 kilograms",
  "bostonterrier": "America's 'gentleman' in a natural tuxedo-like coat",
  "germanshorthairedpointer": "A versatile German gun dog that points and retrieves",
  "englishspringerspaniel": "Bred to 'spring' game birds from cover for hunters",
  "shetlandsheepdog": "A small herder from Scotland's rugged Shetland Islands",
  "miniatureschnauzer": "A German ratter with a signature beard and eyebrows",
  "westhighlandterrier": "A white Scottish terrier bred to hunt vermin",
  "blueheeler": "An Australian herder that nips cattle at their heels",
  "brittany": "A French pointing dog often born with a very short tail",
  "goldendoodle": "A Golden Retriever crossed with a Poodle",
  "labradoodle": "First bred in Australia as a hypoallergenic guide dog",
  "americanbulldog": "A farm working dog descended from old English bulldogs",
  "pitbull": "Bred from bulldogs and terriers; known for loyalty",
  "collie": "The long-coated breed made famous by Lassie",
  "pointer": "Freezes and 'points' with its nose toward hidden game",
  "irishwolfhound": "One of the tallest breeds, once used to hunt wolves",
  "scottishterrier": "A short-legged Scottish digger with a wiry coat",
  "cockapoo": "A Cocker Spaniel crossed with a Poodle",
  "giantschnauzer": "The largest schnauzer, bred to drive cattle in Germany",
  "oldenglishsheepdog": "A shaggy English herder with a distinctive bear-like gait",
  "flatcoatedretriever": "A cheerful gun dog with a glossy flat black or liver coat",
  "standardschnauzer": "The original schnauzer, a German farm and guard dog",
  // MEDIUM
  "germanwirehairedpointer": "A rugged German gun dog with a harsh weatherproof coat",
  "chesapeakebayretriever": "Bred to retrieve ducks from the icy Chesapeake Bay",
  "gordonsetter": "The heaviest setter, a black-and-tan Scottish gun dog",
  "airedaleterrier": "Called the 'King of Terriers', the largest terrier breed",
  "welshterrier": "A black-and-tan Welsh terrier bred to hunt fox and badger",
  "norwichterrier": "A tiny English ratter with upright prick ears",
  "norfolkterrier": "Like the Norwich but with folded drop ears",
  "australianterrier": "One of the smallest working terriers, bred in Australia",
  "silkyterrier": "A small Australian toy with a fine glossy blue coat",
  "manchesterterrier": "A sleek black-and-tan English rat-catching terrier",
  "americanstaffordshireterrier": "A muscular American terrier from bulldog stock",
  "dogoargentino": "A white Argentine breed developed for big-game hunting",
  "presacanario": "A large mastiff-type guard dog from the Canary Islands",
  "boerboel": "A powerful South African farm and guardian mastiff",
  "blackrussianterrier": "Bred by the Soviet army as a large working guard dog",
  "spinoneitaliano": "An ancient Italian pointing dog with a wiry coat",
  "ducktoller": "Lures ducks by playing at the shore, then retrieves them",
  "cardigancorgi": "The older corgi breed, with a long fox-like tail",
  "lhasaapso": "A Tibetan watchdog once kept inside Buddhist monasteries",
  "tibetanterrier": "A Tibetan good-luck dog, not actually a true terrier",
  "affenpinscher": "A small German 'monkey dog' with a mischievous face",
  "germanpinscher": "An old German ratter, ancestor of the Doberman",
  "americaneskimo": "A fluffy white spitz, once a popular circus performer",
  "japanesespitz": "A small pure-white companion spitz from Japan",
  "ratterrier": "An American farm dog bred to control rats and vermin",
  // HARD
  "clumberspaniel": "The heaviest spaniel, a slow but steady English gun dog",
  "fieldspaniel": "A rare medium English spaniel bred for the field",
  "irishwaterspaniel": "The tallest spaniel, with a curly coat and rat-like tail",
  "boykinspaniel": "The state dog of South Carolina, bred for turkey hunting",
  "curlycoatedretriever": "One of the oldest retrievers, covered in tight curls",
  "germanlonghairedpointer": "A German gun dog with a long silky feathered coat",
  "wirehairedpointinggriffon": "A Dutch-bred gun dog with a harsh wiry coat",
  "barbet": "An ancient French water dog with a dense curly coat",
  "bouvierdesflandres": "A Belgian cattle-driving dog with a rugged tousled coat",
  "dutchshepherd": "A Dutch herder known for its brindle striped coat",
  "bergerpicard": "One of France's oldest herding dogs, with a rustic look",
  "caucasianshepherd": "A giant flock guardian from the Caucasus Mountains",
  "centralasianshepherd": "An ancient Central Asian livestock guardian breed",
  "maremmasheepdog": "A white Italian sheepdog that guards flocks from wolves",
  "estrelamountaindog": "A large guardian from Portugal's Estrela Mountains",
  "spanishmastiff": "A huge Spanish livestock guardian used on the meseta",
  "pyreneanmastiff": "A giant flock-guarding mastiff from northern Spain",
  "plotthound": "The state dog of North Carolina, bred to hunt bears",
  "blackandtancoonhound": "An American scent hound bred to tree raccoons at night",
  "redbonecoonhound": "A solid-red American coonhound prized for its voice",
  "bluetickcoonhound": "Named for the blue mottled 'ticking' in its coat",
  "treeingwalkercoonhound": "A fast American hound that trees its quarry",
  "americanfoxhound": "A lean pack hound bred by American colonists to hunt fox",
  "englishfoxhound": "Bred in England to hunt fox in large packs on horseback",
  "harrier": "A medium pack hound bred to hunt hare, larger than a beagle",
  // IMPOSSIBLE
  "sloughi": "A lean North African sighthound bred to course game",
  "chartpolski": "An ancient Polish sighthound, larger and sturdier than most",
  "magyaragar": "A Hungarian coursing hound used by horseback nobles",
  "galgoespanol": "A Spanish sighthound related to the ancient Greyhound",
  "cretanhound": "One of Europe's oldest breeds, a hunter from Crete",
  "hokkaido": "A rare Japanese spitz kept by the indigenous Ainu people",
  "kaiken": "A Japanese hunting dog with a wild brindle 'tiger' coat",
  "kishuken": "A Japanese spitz bred to hunt boar and deer, usually white",
  "shikoku": "A rugged Japanese boar-hunting dog from mountain regions",
  "jindo": "A loyal Korean hunting dog and national treasure of Korea",
  "taiwandog": "A hardy hunting dog descended from Taiwan's native pariahs",
  "newguineasingingdog": "A rare wild dog famous for its melodic howl",
  "rajapalayam": "A white Indian sighthound once kept by royalty",
  "chippiparai": "A sleek South Indian sighthound bred for hunting hare",
  "kombai": "A fierce South Indian hunting dog used to guard homes",
  "mudholhound": "An Indian sighthound also called the Caravan Hound",
  "transylvanianhound": "An ancient Hungarian scent hound with tan facial spots",
  "segugioitaliano": "An ancient Italian scent hound depicted in Roman art",
  "porcelaine": "France's oldest scent hound, prized for its shiny white coat",
  "billy": "A large white French scent hound bred to hunt deer and boar",
  "grandbleudegascogne": "A large French hound with a distinctive blue-mottled coat",
  "drever": "A short-legged Swedish scent hound bred to hunt deer",
  "schillerhound": "A fast Swedish scent hound with a tan-and-black coat",
  "posavachound": "A Croatian scent hound from the Sava River valley",
  "alpinedachsbracke": "A short-legged Austrian hound that tracks wounded game",
};
