// E220 «Guess the Drink by Emoji 2» — facts (true, <=70 chars)
export const DRINK_EMOJI_2_FACTS = {
  "chocolate-milk": "Kids' favorite: milk mixed with cocoa or chocolate syrup.",
  "iced-coffee": "Chilled coffee served over ice, not just cooled hot coffee.",
  "orange-soda": "Bright orange-flavored carbonated soft drink.",
  "cherry-juice": "Tart cherry juice is popular for its antioxidants.",
  "fruit-punch": "A festive mix of several fruit juices, often served cold.",
  "peach-juice": "Sweet nectar pressed from ripe peaches.",
  "kiwi-juice": "Tangy green juice packed with vitamin C.",
  "carrot-juice": "Bright orange juice pressed straight from carrots.",
  "tomato-juice": "Savory juice, a classic base for the Bloody Mary.",
  "berry-smoothie": "Blended mixed berries, often with yogurt or milk.",
  "buttermilk": "Tangy leftover liquid from churning butter into cream.",
  "rice-milk": "Plant milk made by soaking and blending cooked rice.",
  "soy-milk": "Plant milk pressed from soaked, ground soybeans.",
  "oat-milk": "Creamy plant milk made by blending oats with water.",
  "ginger-tea": "Spicy hot tea steeped from fresh ginger root.",
  "peppermint-tea": "Caffeine-free herbal tea steeped from mint leaves.",
  "chamomile-tea": "Calming herbal tea brewed from daisy-like flowers.",
  "hibiscus-tea": "Tart, ruby-red tea steeped from hibiscus petals.",
  "barley-tea": "Roasted barley steeped into a nutty, caffeine-free tea.",
  "sweet-lassi": "Indian yogurt drink blended with sugar or honey.",
  "milk-tea": "Black tea brewed strong and mixed with milk.",
  "coconut-milk": "Rich, creamy liquid pressed from grated coconut flesh.",
  "watermelon-slush": "Blended icy watermelon drink, sweet and refreshing.",
  "grape-soda": "Purple carbonated soda flavored like grapes.",
  "pineapple-smoothie": "Blended pineapple drink, tropical and tangy-sweet.",
  "long-island-iced-tea": "A strong cocktail of five spirits topped with cola.",
  "tom-collins": "A gin, lemon, and soda cocktail served over ice.",
  "mai-tai": "Tiki cocktail of rum, orgeat, and lime, invented in 1944.",
  "whiskey-sour": "Whiskey shaken with lemon juice and a touch of sugar.",
  "manhattan": "Classic cocktail of whiskey, sweet vermouth, and bitters.",
  "bourbon": "American whiskey that must be made mostly from corn.",
  "prosecco": "Italian sparkling white wine from the Glera grape.",
  "white-wine": "Wine fermented without grape skins, usually dry and crisp.",
  "stout": "Dark, roasty beer style made famous by Guinness.",
  "lager": "The world's most-consumed beer, cold-fermented and crisp.",
  "ipa": "India Pale Ale: a hoppy, bitter beer style.",
  "shandy": "Beer mixed with lemonade or citrus soda, low in alcohol.",
  "radler": "German beer-and-citrus-soda mix, lighter than shandy's cousin.",
  "grog": "Rum diluted with water, once rationed to sailors.",
  "hot-toddy": "Warm whiskey drink with honey, lemon, and spices.",
  "mint-julep": "Bourbon, mint, and sugar cocktail tied to the Kentucky Derby.",
  "sidecar": "Cognac cocktail shaken with orange liqueur and lemon.",
  "french-75": "Gin, lemon, and sugar topped with champagne.",
  "kir-royale": "Champagne with a splash of blackcurrant liqueur.",
  "michelada": "Mexican beer cocktail with lime, spices, and chili.",
  "paloma": "Tequila mixed with grapefruit soda, Mexico's favorite.",
  "tequila-sunrise": "Tequila and orange juice that layer like a sunrise.",
  "espresso-martini": "Vodka shaken with espresso and coffee liqueur.",
  "white-russian": "Vodka, coffee liqueur, and cream over ice.",
  "black-russian": "Vodka and coffee liqueur, the Russian without cream.",
  "campari": "Bright red-orange Italian bitter aperitif.",
  "fernet": "Intensely bitter Italian herbal digestif.",
  "ouzo": "Greek anise spirit that turns cloudy when mixed with water.",
  "calvados": "French brandy distilled from apples in Normandy.",
  "pisco-sour": "Peruvian brandy shaken with lime and egg white.",
  "cachaca": "Brazilian spirit distilled from fresh sugarcane juice.",
  "arak": "Middle Eastern anise spirit, clouds when mixed with water.",
  "poitin": "Traditional Irish moonshine spirit, once distilled illegally.",
  "moonshine": "Homemade, unaged spirit, historically distilled illegally.",
  "aquavit": "Scandinavian spirit flavored with caraway and dill.",
  "jagermeister": "German herbal liqueur with a stag on its label.",
  "sambuca": "Italian anise liqueur, sometimes served flaming.",
  "baijiu": "China's most-consumed spirit, distilled from sorghum.",
  "vin-santo": "Sweet Italian dessert wine made from dried grapes.",
  "chicha-morada": "Peruvian purple-corn drink, sweet and non-alcoholic.",
  "turkish-coffee": "Unfiltered coffee simmered in a small copper pot.",
  "vietnamese-egg-coffee": "Coffee topped with whipped egg yolk and condensed milk.",
  "ratafia": "French liqueur made by infusing spirit with fruit.",
  "water-kefir": "Fermented, fizzy drink made with water kefir grains.",
  "sima": "Finnish lemon mead traditionally drunk on May Day.",
  "basi": "Filipino wine fermented from sugarcane juice.",
  "tuba": "Filipino wine tapped from coconut palm sap.",
  "kumis": "Central Asian drink of fermented mare's milk.",
  "shubat": "Fermented camel milk drunk across Central Asia.",
  "sgroppino": "Italian dessert drink of lemon sorbet and prosecco.",
  "tesguino": "Fermented corn beer brewed by Indigenous Mexican peoples.",
  "pox": "Mayan corn spirit from Chiapas, Mexico, used in rituals.",
  "zutho": "Fermented rice beer of the Naga people in India.",
  "tongba": "Fermented millet drink sipped hot through a bamboo straw.",
  "xtabentun": "Mayan liqueur made from honey and anise.",
  "sotol": "Mexican spirit distilled from the desert spoon plant.",
  "rakomelo": "Greek spirit raki infused with honey and cinnamon.",
  "perry": "Fermented cider-style drink made from pears, not apples.",
  "poire-williams": "Clear French brandy distilled from Williams pears.",
  "retsina": "Greek wine resinated with pine, a tradition since antiquity.",
  "switchel": "Colonial American drink of ginger, vinegar, and sweetener.",
  "tarhun": "Bright green Georgian soda flavored with tarragon.",
  "zubrowka": "Polish vodka infused with bison grass.",
  "riga-black-balsam": "Bitter Latvian herbal liqueur, nearly black in color.",
  "malort": "Notoriously bitter Chicago wormwood liqueur.",
  "kilju": "Simple Finnish home-fermented sugar wine.",
  "suanmeitang": "Chinese sour plum drink, smoky-sweet and tangy.",
  "sekanjabin": "Ancient Persian syrup of mint and vinegar, served chilled.",
  "cascara": "Tea brewed from the dried skin of coffee cherries.",
  "cha-yen": "Thai iced tea, sweet, spiced, and topped with milk.",
  "salgam": "Turkish fermented drink made from purple carrots and turnip.",
  "kykeon": "Barley-and-herb drink from ancient Greek mythology.",
  "kalimotxo": "Basque mix of red wine and cola, served over ice.",
  "snakebite": "British pub mix of beer and cider in equal parts.",
  "frose": "Frozen blended rosé wine, a summer slushy cocktail.",
};
