// E152 «Guess the Drink by Emoji» — 100 drinks · 25/tier · clue = plain Unicode emoji (mirrors movieEmoji2 isEmoji rendering)
// VO: sfx/e152-<id>.wav ("It's <Drink>!"). Born fair: every clue leads honestly to the drink; harder tiers use ingredient-honest 2-emoji hints.
export const DRINK_EMOJI = [
  // ===== EASY (25) =====
  { id: "water", title: "Water", emojis: "💧🥤", level: "easy" },
  { id: "coffee", title: "Coffee", emojis: "☕🫘", level: "easy" },
  { id: "tea", title: "Tea", emojis: "🍵🫖", level: "easy" },
  { id: "milk", title: "Milk", emojis: "🥛🐄", level: "easy" },
  { id: "orange-juice", title: "Orange Juice", emojis: "🍊🧃", level: "easy" },
  { id: "soda", title: "Soda", emojis: "🥤🫧", level: "easy" },
  { id: "beer", title: "Beer", emojis: "🍺🌾", level: "easy" },
  { id: "wine", title: "Wine", emojis: "🍷🍇", level: "easy" },
  { id: "lemonade", title: "Lemonade", emojis: "🍋🥤", level: "easy" },
  { id: "hot-chocolate", title: "Hot Chocolate", emojis: "🍫🥛", level: "easy" },
  { id: "milkshake", title: "Milkshake", emojis: "🍦🥤", level: "easy" },
  { id: "smoothie", title: "Smoothie", emojis: "🍓🥤", level: "easy" },
  { id: "apple-juice", title: "Apple Juice", emojis: "🍎🧃", level: "easy" },
  { id: "iced-tea", title: "Iced Tea", emojis: "🧊🍵", level: "easy" },
  { id: "cola", title: "Cola", emojis: "⚫🥤", level: "easy" },
  { id: "coconut-water", title: "Coconut Water", emojis: "🥥💧", level: "easy" },
  { id: "champagne", title: "Champagne", emojis: "🍾🥂", level: "easy" },
  { id: "bubble-tea", title: "Bubble Tea", emojis: "🧋🫧", level: "easy" },
  { id: "cocktail", title: "Cocktail", emojis: "🍸🫒", level: "easy" },
  { id: "green-tea", title: "Green Tea", emojis: "🍵🎋", level: "easy" },
  { id: "mango-juice", title: "Mango Juice", emojis: "🥭🧃", level: "easy" },
  { id: "pineapple-juice", title: "Pineapple Juice", emojis: "🍍🧃", level: "easy" },
  { id: "banana-smoothie", title: "Banana Smoothie", emojis: "🍌🥤", level: "easy" },
  { id: "watermelon-juice", title: "Watermelon Juice", emojis: "🍉🧃", level: "easy" },
  { id: "grape-juice", title: "Grape Juice", emojis: "🍇🧃", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "espresso", title: "Espresso", emojis: "☕⚡", level: "medium" },
  { id: "cappuccino", title: "Cappuccino", emojis: "☕☁", level: "medium" },
  { id: "latte", title: "Latte", emojis: "☕🥛", level: "medium" },
  { id: "mojito", title: "Mojito", emojis: "🌿🍹", level: "medium" },
  { id: "margarita", title: "Margarita", emojis: "🧂🍹", level: "medium" },
  { id: "pina-colada", title: "Pina Colada", emojis: "🍍🥥", level: "medium" },
  { id: "sangria", title: "Sangria", emojis: "🍷🍊", level: "medium" },
  { id: "whiskey", title: "Whiskey", emojis: "🥃🌾", level: "medium" },
  { id: "vodka", title: "Vodka", emojis: "🥔🥃", level: "medium" },
  { id: "gin", title: "Gin", emojis: "🌲🥃", level: "medium" },
  { id: "rum", title: "Rum", emojis: "🦜🥃", level: "medium" },
  { id: "cider", title: "Cider", emojis: "🍎🍺", level: "medium" },
  { id: "matcha", title: "Matcha", emojis: "🍵🍃", level: "medium" },
  { id: "chai", title: "Chai", emojis: "🫖🍂", level: "medium" },
  { id: "ginger-ale", title: "Ginger Ale", emojis: "🫚🥤", level: "medium" },
  { id: "root-beer", title: "Root Beer", emojis: "🌳🍺", level: "medium" },
  { id: "eggnog", title: "Eggnog", emojis: "🥚🥛", level: "medium" },
  { id: "mulled-wine", title: "Mulled Wine", emojis: "🍷🔥", level: "medium" },
  { id: "kombucha", title: "Kombucha", emojis: "🍵🫧", level: "medium" },
  { id: "horchata", title: "Horchata", emojis: "🌾🥛", level: "medium" },
  { id: "sake", title: "Sake", emojis: "🍶🌾", level: "medium" },
  { id: "mate", title: "Mate", emojis: "🧉🌿", level: "medium" },
  { id: "energy-drink", title: "Energy Drink", emojis: "⚡🥤", level: "medium" },
  { id: "sparkling-water", title: "Sparkling Water", emojis: "🫧💧", level: "medium" },
  { id: "aperol-spritz", title: "Aperol Spritz", emojis: "🍊🧊", level: "medium" },

  // ===== HARD (25) =====
  { id: "bloody-mary", title: "Bloody Mary", emojis: "🍅🥃", level: "hard" },
  { id: "irish-coffee", title: "Irish Coffee", emojis: "☕🥃", level: "hard" },
  { id: "affogato", title: "Affogato", emojis: "☕🍨", level: "hard" },
  { id: "americano", title: "Americano", emojis: "☕💧", level: "hard" },
  { id: "tequila", title: "Tequila", emojis: "🌵🥃", level: "hard" },
  { id: "brandy", title: "Brandy", emojis: "🍇🥃", level: "hard" },
  { id: "absinthe", title: "Absinthe", emojis: "🌿🥃", level: "hard" },
  { id: "gin-and-tonic", title: "Gin and Tonic", emojis: "🌲🫧", level: "hard" },
  { id: "bellini", title: "Bellini", emojis: "🍑🥂", level: "hard" },
  { id: "mimosa", title: "Mimosa", emojis: "🍊🥂", level: "hard" },
  { id: "screwdriver", title: "Screwdriver", emojis: "🍊🥃", level: "hard" },
  { id: "old-fashioned", title: "Old Fashioned", emojis: "🥃🍒", level: "hard" },
  { id: "daiquiri", title: "Daiquiri", emojis: "🍋🍹", level: "hard" },
  { id: "cosmopolitan", title: "Cosmopolitan", emojis: "🍸🩷", level: "hard" },
  { id: "negroni", title: "Negroni", emojis: "🍸🍊", level: "hard" },
  { id: "rakia", title: "Rakia", emojis: "🍑🥃", level: "hard" },
  { id: "soju", title: "Soju", emojis: "🍚🥃", level: "hard" },
  { id: "limoncello", title: "Limoncello", emojis: "🍋🥃", level: "hard" },
  { id: "amaretto", title: "Amaretto", emojis: "🌰🥃", level: "hard" },
  { id: "baileys", title: "Baileys", emojis: "🥛🥃", level: "hard" },
  { id: "kahlua", title: "Kahlua", emojis: "☕🍫", level: "hard" },
  { id: "vermouth", title: "Vermouth", emojis: "🍷🌿", level: "hard" },
  { id: "port-wine", title: "Port Wine", emojis: "🍷🥃", level: "hard" },
  { id: "mead", title: "Mead", emojis: "🍯🍺", level: "hard" },
  { id: "caipirinha", title: "Caipirinha", emojis: "🍋🍸", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "ayran", title: "Ayran", emojis: "🥛🧂", level: "impossible" },
  { id: "mango-lassi", title: "Mango Lassi", emojis: "🥛🥭", level: "impossible" },
  { id: "kefir", title: "Kefir", emojis: "🥛🦠", level: "impossible" },
  { id: "kvass", title: "Kvass", emojis: "🍞🍺", level: "impossible" },
  { id: "sbiten", title: "Sbiten", emojis: "🍯🔥", level: "impossible" },
  { id: "chicha", title: "Chicha", emojis: "🌽🍺", level: "impossible" },
  { id: "pulque", title: "Pulque", emojis: "🌵🥛", level: "impossible" },
  { id: "mezcal", title: "Mezcal", emojis: "🌵🔥", level: "impossible" },
  { id: "makgeolli", title: "Makgeolli", emojis: "🍚🥛", level: "impossible" },
  { id: "amazake", title: "Amazake", emojis: "🍚🔥", level: "impossible" },
  { id: "umeshu", title: "Umeshu", emojis: "🍑🍶", level: "impossible" },
  { id: "shochu", title: "Shochu", emojis: "🍠🥃", level: "impossible" },
  { id: "feni", title: "Feni", emojis: "🥥🥃", level: "impossible" },
  { id: "palm-wine", title: "Palm Wine", emojis: "🌴🍺", level: "impossible" },
  { id: "kava", title: "Kava", emojis: "🪵🥥", level: "impossible" },
  { id: "guarana", title: "Guarana", emojis: "🥤🍒", level: "impossible" },
  { id: "irn-bru", title: "Irn-Bru", emojis: "🧡🥤", level: "impossible" },
  { id: "barley-water", title: "Barley Water", emojis: "🌾💧", level: "impossible" },
  { id: "tepache", title: "Tepache", emojis: "🍍🍺", level: "impossible" },
  { id: "boza", title: "Boza", emojis: "🌾🥤", level: "impossible" },
  { id: "salep", title: "Salep", emojis: "🌸🥛", level: "impossible" },
  { id: "atole", title: "Atole", emojis: "🌽🥛", level: "impossible" },
  { id: "tejate", title: "Tejate", emojis: "🌽🍫", level: "impossible" },
  { id: "cendol", title: "Cendol", emojis: "🍧🥥", level: "impossible" },
  { id: "jamu", title: "Jamu", emojis: "🫚🌿", level: "impossible" },
];
