// «Guess the Coffee or Tea Drink» — GuessSync · E68 · did-you-know facts, ≤70 chars, verified true.
// Base/origin trivia only. Coffee drinks + world teas.
export const DRINK_FACTS = {
  // EASY
  "espresso": "Concentrated coffee forced through grounds under pressure",
  "cappuccino": "Italian coffee of espresso with steamed and foamed milk",
  "latte": "Espresso with lots of steamed milk and a little foam",
  "americano": "Espresso diluted with hot water for a lighter cup",
  "macchiato": "Espresso 'stained' with just a dash of foamed milk",
  "mocha": "A latte flavored with chocolate; also called mochaccino",
  "flatwhite": "Espresso with steamed milk; born in Australia or NZ",
  "cortado": "Spanish drink of espresso cut with equal warm milk",
  "icedcoffee": "Brewed coffee served chilled over ice",
  "frappe": "A Greek iced coffee made by frothing instant coffee",
  "turkishcoffee": "Finely ground coffee simmered unfiltered in a cezve",
  "coldbrew": "Coffee steeped in cold water for many hours, not heated",
  "greentea": "Unoxidized tea leaves, widely drunk across East Asia",
  "blacktea": "Fully oxidized tea leaves giving a dark, bold brew",
  "matcha": "Stone-ground green tea powder whisked into hot water",
  "chai": "Indian spiced tea brewed with milk, sugar and spices",
  "bubbletea": "Taiwanese tea drink with chewy tapioca pearls",
  "icedtea": "Chilled brewed tea, often sweetened and served with ice",
  "earlgrey": "Black tea flavored with oil of bergamot citrus",
  "oolong": "Partly oxidized tea, between green and black in style",
  "herbaltea": "A tisane brewed from herbs, not the tea plant",
  "pepperminttea": "A caffeine-free tisane made from peppermint leaves",
  "chamomiletea": "A soothing herbal tea brewed from chamomile flowers",
  "jasminetea": "Green tea scented with jasmine blossoms",
  "irishcoffee": "Hot coffee with whiskey, topped with cream",
  // MEDIUM
  "cafeaulait": "French coffee served with an equal part of hot milk",
  "redeye": "Drip coffee spiked with a shot of espresso",
  "breve": "Espresso made creamy with steamed half-and-half",
  "dalgona": "Whipped instant coffee foam over milk; a viral hit",
  "viennese": "Vienna coffee topped with whipped cream",
  "cafecubano": "Cuban espresso sweetened with sugar as it brews",
  "galao": "Portuguese drink of espresso with lots of foamed milk",
  "pumpkinspicelatte": "Autumn latte with pumpkin and warm spice flavors",
  "thaiicedtea": "Sweet spiced black tea with milk, served orange and iced",
  "moroccanmint": "Green tea brewed with fresh mint and plenty of sugar",
  "sencha": "The most popular Japanese steamed green tea",
  "darjeeling": "Prized black tea from India's Darjeeling hills",
  "assam": "Malty black tea from the Assam region of India",
  "ceylon": "Black tea grown in Sri Lanka, once called Ceylon",
  "hibiscustea": "Tart red tisane brewed from dried hibiscus flowers",
  "hkmilktea": "Hong Kong black tea with evaporated milk, strong and smooth",
  "gingertea": "A warming tisane brewed from fresh ginger root",
  "whitetea": "The least processed tea, made from young buds",
  "lemontea": "Black tea served with a slice or squeeze of lemon",
  "tehtarik": "Malaysian 'pulled' milk tea poured to make foam",
  "yerbamate": "South American herb tea sipped through a metal straw",
  "lungo": "A longer espresso pulled with more water",
  "nitrocoldbrew": "Cold brew charged with nitrogen for a creamy head",
  "londonfog": "Earl Grey tea latte with steamed milk and vanilla",
  "kombucha": "Fizzy fermented tea made with a culture of yeast",
  // HARD
  "vietnamesecoffee": "Strong drip coffee over sweetened condensed milk",
  "eggcoffee": "Vietnamese coffee topped with whipped egg yolk cream",
  "mazagran": "Cold coffee with lemon, an old Algerian-Portuguese drink",
  "marocchino": "Italian espresso with cocoa and milk foam",
  "bicerin": "Turin drink layering espresso, chocolate and cream",
  "cafedeolla": "Mexican coffee brewed with cinnamon and raw cane sugar",
  "cafetouba": "Senegalese coffee spiced with grains of Selim pepper",
  "espressotonic": "Espresso poured over tonic water and ice",
  "doppio": "A double shot of espresso in one cup",
  "corretto": "Italian espresso 'corrected' with a shot of liquor",
  "puerh": "Fermented, aged dark tea from Yunnan, China",
  "hojicha": "Japanese green tea roasted to a reddish-brown color",
  "arnoldpalmer": "Half iced tea and half lemonade, named for the golfer",
  "chrysanthemumtea": "Floral tisane brewed from dried chrysanthemum blooms",
  "barleytea": "Roasted barley tisane popular in Korea and Japan",
  "tulsitea": "Herbal tea made from holy basil, revered in India",
  "sweettea": "Heavily sweetened iced black tea of the US South",
  "gyokuro": "Shade-grown Japanese green tea prized for sweetness",
  "kashmirichai": "Pink salted tea from Kashmir, colored by baking soda",
  "bloomingtea": "Tied tea leaves that unfurl into a flower in water",
  "butterflypeatea": "Blue herbal tea from butterfly pea flowers",
  "gunpowdertea": "Green tea rolled into tight pellets that unfurl",
  "karak": "Strong Gulf spiced milk tea, brewed dark and sweet",
  "lemongrasstea": "A citrusy tisane brewed from lemongrass stalks",
  "espressoconpanna": "Espresso topped with a dollop of whipped cream",
  // IMPOSSIBLE
  "affogato": "Italian dessert of espresso poured over ice cream",
  "ristretto": "A short, restricted espresso with less water",
  "cascara": "Tea brewed from the dried skins of coffee cherries",
  "yuenyeung": "Hong Kong mix of coffee and milk tea",
  "buttertea": "Tibetan tea churned with yak butter and salt",
  "genmaicha": "Japanese green tea blended with roasted brown rice",
  "rooibos": "Caffeine-free red bush tea from South Africa",
  "lapsangsouchong": "Chinese black tea dried over smoky pinewood fires",
  "saltcoffee": "Vietnamese iced coffee topped with a salty cream foam",
  "cafebombon": "Spanish espresso layered over sweetened condensed milk",
  "cafezinho": "Small, sweet black coffee served across Brazil",
  "kopi": "Southeast Asian coffee brewed in a cloth sock filter",
  "shakerato": "Italian espresso shaken with ice into a cold foam",
  "mirra": "Bitter, unsweetened Arabic coffee of the Levant",
  "tehtalua": "Minangkabau tea whisked with egg yolk and sugar",
  "yujatea": "Korean tea of honeyed citron marmalade in hot water",
  "ipohwhitecoffee": "Malaysian coffee roasted with margarine, served milky",
  "kukicha": "Japanese tea made from tea twigs and stems",
  "sobacha": "Caffeine-free Japanese tea brewed from buckwheat",
  "coconutcoffee": "Vietnamese iced coffee blended with coconut cream",
  "yaupon": "The only caffeinated plant native to North America",
  "leicha": "Hakka 'thunder tea' of ground tea, nuts and herbs",
  "kahwah": "Kashmiri green tea with saffron, cardamom and almond",
  "bandrek": "Indonesian hot ginger tea spiced with palm sugar",
  "cortadito": "Cuban espresso cut with steamed, sweetened milk",
};
