// «Guess the Coffee or Tea Drink» — GuessSync · E68 · 100 drinks (25/tier) · real photos from Wikimedia Commons
// Mixes coffee drinks + world teas. Tiered by real-world recognizability:
// easy (Espresso/Latte/Green Tea) ← impossible (obscure ones: Cascara/Yuenyeung/Butter Tea/Kopi Luwak).
export const DRINKS = [
  // EASY (25) — household-name coffees & teas
  { slug: "espresso", name: "Espresso", level: "easy" },
  { slug: "cappuccino", name: "Cappuccino", level: "easy" },
  { slug: "latte", name: "Latte", level: "easy" },
  { slug: "americano", name: "Americano", level: "easy" },
  { slug: "macchiato", name: "Macchiato", level: "easy" },
  { slug: "mocha", name: "Mocha", level: "easy" },
  { slug: "flatwhite", name: "Flat White", level: "easy" },
  { slug: "cortado", name: "Cortado", level: "easy" },
  { slug: "icedcoffee", name: "Iced Coffee", level: "easy" },
  { slug: "frappe", name: "Frappé", level: "easy" },
  { slug: "turkishcoffee", name: "Turkish Coffee", level: "easy" },
  { slug: "coldbrew", name: "Cold Brew", level: "easy" },
  { slug: "greentea", name: "Green Tea", level: "easy" },
  { slug: "blacktea", name: "Black Tea", level: "easy" },
  { slug: "matcha", name: "Matcha", level: "easy" },
  { slug: "chai", name: "Masala Chai", level: "easy" },
  { slug: "bubbletea", name: "Bubble Tea", level: "easy" },
  { slug: "icedtea", name: "Iced Tea", level: "easy" },
  { slug: "earlgrey", name: "Earl Grey", level: "easy" },
  { slug: "oolong", name: "Oolong Tea", level: "easy" },
  { slug: "herbaltea", name: "Herbal Tea", level: "easy" },
  { slug: "pepperminttea", name: "Peppermint Tea", level: "easy" },
  { slug: "chamomiletea", name: "Chamomile Tea", level: "easy" },
  { slug: "jasminetea", name: "Jasmine Tea", level: "easy" },
  { slug: "irishcoffee", name: "Irish Coffee", level: "easy" },
  // MEDIUM (25)
  { slug: "cafeaulait", name: "Café au Lait", level: "medium" },
  { slug: "redeye", name: "Red Eye", level: "medium" },
  { slug: "breve", name: "Caffè Breve", level: "medium" },
  { slug: "dalgona", name: "Dalgona Coffee", level: "medium" },
  { slug: "viennese", name: "Vienna Coffee", level: "medium" },
  { slug: "cafecubano", name: "Cuban Coffee", level: "medium" },
  { slug: "galao", name: "Galão", level: "medium" },
  { slug: "pumpkinspicelatte", name: "Pumpkin Spice Latte", level: "medium" },
  { slug: "thaiicedtea", name: "Thai Iced Tea", level: "medium" },
  { slug: "moroccanmint", name: "Moroccan Mint Tea", level: "medium" },
  { slug: "sencha", name: "Sencha", level: "medium" },
  { slug: "darjeeling", name: "Darjeeling", level: "medium" },
  { slug: "assam", name: "Assam Tea", level: "medium" },
  { slug: "ceylon", name: "Ceylon Tea", level: "medium" },
  { slug: "hibiscustea", name: "Hibiscus Tea", level: "medium" },
  { slug: "hkmilktea", name: "Hong Kong Milk Tea", level: "medium" },
  { slug: "gingertea", name: "Ginger Tea", level: "medium" },
  { slug: "whitetea", name: "White Tea", level: "medium" },
  { slug: "lemontea", name: "Lemon Tea", level: "medium" },
  { slug: "tehtarik", name: "Teh Tarik", level: "medium" },
  { slug: "yerbamate", name: "Yerba Mate", level: "medium" },
  { slug: "lungo", name: "Caffè Lungo", level: "medium" },
  { slug: "nitrocoldbrew", name: "Nitro Cold Brew", level: "medium" },
  { slug: "londonfog", name: "London Fog", level: "medium" },
  { slug: "kombucha", name: "Kombucha", level: "medium" },
  // HARD (25)
  { slug: "vietnamesecoffee", name: "Vietnamese Iced Coffee", level: "hard" },
  { slug: "eggcoffee", name: "Egg Coffee", level: "hard" },
  { slug: "mazagran", name: "Mazagran", level: "hard" },
  { slug: "marocchino", name: "Marocchino", level: "hard" },
  { slug: "bicerin", name: "Bicerin", level: "hard" },
  { slug: "cafedeolla", name: "Café de Olla", level: "hard" },
  { slug: "cafetouba", name: "Café Touba", level: "hard" },
  { slug: "espressotonic", name: "Espresso Tonic", level: "hard" },
  { slug: "doppio", name: "Doppio", level: "hard" },
  { slug: "corretto", name: "Caffè Corretto", level: "hard" },
  { slug: "puerh", name: "Pu-erh Tea", level: "hard" },
  { slug: "hojicha", name: "Hojicha", level: "hard" },
  { slug: "arnoldpalmer", name: "Arnold Palmer", level: "hard" },
  { slug: "chrysanthemumtea", name: "Chrysanthemum Tea", level: "hard" },
  { slug: "barleytea", name: "Barley Tea", level: "hard" },
  { slug: "tulsitea", name: "Tulsi Tea", level: "hard" },
  { slug: "sweettea", name: "Sweet Tea", level: "hard" },
  { slug: "gyokuro", name: "Gyokuro", level: "hard" },
  { slug: "kashmirichai", name: "Kashmiri Pink Tea", level: "hard" },
  { slug: "bloomingtea", name: "Blooming Tea", level: "hard" },
  { slug: "butterflypeatea", name: "Butterfly Pea Tea", level: "hard" },
  { slug: "gunpowdertea", name: "Gunpowder Tea", level: "hard" },
  { slug: "karak", name: "Karak Chai", level: "hard" },
  { slug: "lemongrasstea", name: "Lemongrass Tea", level: "hard" },
  { slug: "espressoconpanna", name: "Espresso con Panna", level: "hard" },
  // IMPOSSIBLE (25) — obscure coffees & teas
  { slug: "affogato", name: "Affogato", level: "impossible" },
  { slug: "ristretto", name: "Ristretto", level: "impossible" },
  { slug: "cascara", name: "Cascara Tea", level: "impossible" },
  { slug: "yuenyeung", name: "Yuenyeung", level: "impossible" },
  { slug: "buttertea", name: "Butter Tea", level: "impossible" },
  { slug: "genmaicha", name: "Genmaicha", level: "impossible" },
  { slug: "rooibos", name: "Rooibos", level: "impossible" },
  { slug: "lapsangsouchong", name: "Lapsang Souchong", level: "impossible" },
  { slug: "saltcoffee", name: "Salt Coffee", level: "impossible" },
  { slug: "cafebombon", name: "Café Bombón", level: "impossible" },
  { slug: "cafezinho", name: "Cafézinho", level: "impossible" },
  { slug: "kopi", name: "Kopi", level: "impossible" },
  { slug: "shakerato", name: "Caffè Shakerato", level: "impossible" },
  { slug: "mirra", name: "Mırra", level: "impossible" },
  { slug: "tehtalua", name: "Teh Talua", level: "impossible" },
  { slug: "yujatea", name: "Yuja Tea", level: "impossible" },
  { slug: "ipohwhitecoffee", name: "Ipoh White Coffee", level: "impossible" },
  { slug: "kukicha", name: "Kukicha", level: "impossible" },
  { slug: "sobacha", name: "Sobacha", level: "impossible" },
  { slug: "coconutcoffee", name: "Coconut Coffee", level: "impossible" },
  { slug: "yaupon", name: "Yaupon Tea", level: "impossible" },
  { slug: "leicha", name: "Lei Cha", level: "impossible" },
  { slug: "kahwah", name: "Kahwah", level: "impossible" },
  { slug: "bandrek", name: "Bandrek", level: "impossible" },
  { slug: "cortadito", name: "Cortadito", level: "impossible" },
];
