// E162 «Guess the Famous Duo by Emoji» — 100 famous duos/pairs · 25/tier · clue = plain Unicode emoji
// Each emoji pair fairly evokes BOTH members of the duo. Single-codepoint emojis only
// (no FE0F/ZWJ/keycap/skin-tone/flags). `title` = duo name only. VO: sfx/e162-<id>.wav
export const DUO_EMOJI = [
  // ===== EASY (25) — globally famous =====
  { id: "tom-and-jerry", title: "Tom & Jerry", emojis: "🐱🐭", level: "easy" },
  { id: "batman-and-robin", title: "Batman & Robin", emojis: "🦇🐦", level: "easy" },
  { id: "spongebob-and-patrick", title: "SpongeBob & Patrick", emojis: "🧽⭐", level: "easy" },
  { id: "woody-and-buzz", title: "Woody & Buzz", emojis: "🤠🚀", level: "easy" },
  { id: "mickey-and-minnie", title: "Mickey & Minnie", emojis: "🐭🎀", level: "easy" },
  { id: "shrek-and-donkey", title: "Shrek & Donkey", emojis: "👹🫏", level: "easy" },
  { id: "bert-and-ernie", title: "Bert & Ernie", emojis: "🛁🐦", level: "easy" },
  { id: "han-and-chewie", title: "Han & Chewie", emojis: "🚀🐻", level: "easy" },
  { id: "calvin-and-hobbes", title: "Calvin & Hobbes", emojis: "👦🐯", level: "easy" },
  { id: "bonnie-and-clyde", title: "Bonnie & Clyde", emojis: "🔫💑", level: "easy" },
  { id: "sherlock-and-watson", title: "Sherlock & Watson", emojis: "🔍🎩", level: "easy" },
  { id: "simon-and-garfunkel", title: "Simon & Garfunkel", emojis: "🌉🎸", level: "easy" },
  { id: "salt-and-pepper", title: "Salt & Pepper", emojis: "🧂🌶", level: "easy" },
  { id: "peanut-butter-and-jelly", title: "Peanut Butter & Jelly", emojis: "🥜🍇", level: "easy" },
  { id: "mario-and-luigi", title: "Mario & Luigi", emojis: "🍄👨", level: "easy" },
  { id: "pinky-and-the-brain", title: "Pinky & the Brain", emojis: "🐭🧠", level: "easy" },
  { id: "chip-and-dale", title: "Chip & Dale", emojis: "🐿🌰", level: "easy" },
  { id: "scooby-and-shaggy", title: "Scooby & Shaggy", emojis: "🐕🍔", level: "easy" },
  { id: "beavis-and-butthead", title: "Beavis & Butt-Head", emojis: "🤘📺", level: "easy" },
  { id: "ren-and-stimpy", title: "Ren & Stimpy", emojis: "🐈🐶", level: "easy" },
  { id: "fred-and-barney", title: "Fred & Barney", emojis: "🦕🪨", level: "easy" },
  { id: "wallace-and-gromit", title: "Wallace & Gromit", emojis: "🧀🐶", level: "easy" },
  { id: "rick-and-morty", title: "Rick & Morty", emojis: "🧪👦", level: "easy" },
  { id: "sonic-and-tails", title: "Sonic & Tails", emojis: "🦔🦊", level: "easy" },
  { id: "bugs-and-daffy", title: "Bugs & Daffy", emojis: "🐰🦆", level: "easy" },

  // ===== MEDIUM (25) — well known, a beat harder =====
  { id: "dory-and-marlin", title: "Dory & Marlin", emojis: "🐠🔍", level: "medium" },
  { id: "jake-and-finn", title: "Jake & Finn", emojis: "🗡🐶", level: "medium" },
  { id: "asterix-and-obelix", title: "Asterix & Obelix", emojis: "🧪🗿", level: "medium" },
  { id: "thelma-and-louise", title: "Thelma & Louise", emojis: "🚗🌵", level: "medium" },
  { id: "wayne-and-garth", title: "Wayne & Garth", emojis: "🎸📺", level: "medium" },
  { id: "bill-and-ted", title: "Bill & Ted", emojis: "⏳☎", level: "medium" },
  { id: "jay-and-silent-bob", title: "Jay & Silent Bob", emojis: "🏪🚬", level: "medium" },
  { id: "cheech-and-chong", title: "Cheech & Chong", emojis: "🌿🚬", level: "medium" },
  { id: "romeo-and-juliet", title: "Romeo & Juliet", emojis: "💔🗡", level: "medium" },
  { id: "starsky-and-hutch", title: "Starsky & Hutch", emojis: "🍅🚗", level: "medium" },
  { id: "mulder-and-scully", title: "Mulder & Scully", emojis: "🛸🔦", level: "medium" },
  { id: "ross-and-rachel", title: "Ross & Rachel", emojis: "☕💔", level: "medium" },
  { id: "sam-and-frodo", title: "Sam & Frodo", emojis: "💍🌋", level: "medium" },
  { id: "c3po-and-r2d2", title: "C-3PO & R2-D2", emojis: "🤖🔩", level: "medium" },
  { id: "jules-and-vincent", title: "Jules & Vincent", emojis: "🔫💼", level: "medium" },
  { id: "harold-and-kumar", title: "Harold & Kumar", emojis: "🍔🌿", level: "medium" },
  { id: "dumb-and-dumber", title: "Dumb & Dumber", emojis: "🤪🚐", level: "medium" },
  { id: "bebop-and-rocksteady", title: "Bebop & Rocksteady", emojis: "🐗🦏", level: "medium" },
  { id: "statler-and-waldorf", title: "Statler & Waldorf", emojis: "👴🎭", level: "medium" },
  { id: "jekyll-and-hyde", title: "Jekyll & Hyde", emojis: "🧪👿", level: "medium" },
  { id: "laurel-and-hardy", title: "Laurel & Hardy", emojis: "🎩🤵", level: "medium" },
  { id: "abbott-and-costello", title: "Abbott & Costello", emojis: "⚾🎙", level: "medium" },
  { id: "penn-and-teller", title: "Penn & Teller", emojis: "🃏🤐", level: "medium" },
  { id: "siegfried-and-roy", title: "Siegfried & Roy", emojis: "🐅✨", level: "medium" },
  { id: "ben-and-jerry", title: "Ben & Jerry", emojis: "🍦🐄", level: "medium" },

  // ===== HARD (25) — real duos fans know, trickier =====
  { id: "vladimir-and-estragon", title: "Vladimir & Estragon", emojis: "🌳👢", level: "hard" },
  { id: "rosencrantz-and-guildenstern", title: "Rosencrantz & Guildenstern", emojis: "🎭🪙", level: "hard" },
  { id: "sam-and-dean", title: "Sam & Dean", emojis: "🚗👻", level: "hard" },
  { id: "crockett-and-tubbs", title: "Crockett & Tubbs", emojis: "🌴🔫", level: "hard" },
  { id: "turner-and-hooch", title: "Turner & Hooch", emojis: "🚓🐕", level: "hard" },
  { id: "bud-and-terence", title: "Bud Spencer & Terence Hill", emojis: "👊🤠", level: "hard" },
  { id: "hall-and-oates", title: "Hall & Oates", emojis: "🌾🎤", level: "hard" },
  { id: "daft-punk", title: "Daft Punk", emojis: "🤖🎧", level: "hard" },
  { id: "sonny-and-cher", title: "Sonny & Cher", emojis: "☀🎤", level: "hard" },
  { id: "chandler-and-joey", title: "Chandler & Joey", emojis: "🐤🦆", level: "hard" },
  { id: "spock-and-kirk", title: "Spock & Kirk", emojis: "🖖🚀", level: "hard" },
  { id: "bilbo-and-gandalf", title: "Bilbo & Gandalf", emojis: "🧙🐉", level: "hard" },
  { id: "merry-and-pippin", title: "Merry & Pippin", emojis: "🍺🌿", level: "hard" },
  { id: "fred-and-george", title: "Fred & George Weasley", emojis: "🧨🪄", level: "hard" },
  { id: "harry-and-ron", title: "Harry & Ron", emojis: "🧹🐀", level: "hard" },
  { id: "fry-and-bender", title: "Fry & Bender", emojis: "🍕🤖", level: "hard" },
  { id: "jake-and-elwood", title: "The Blues Brothers", emojis: "🕶🎷", level: "hard" },
  { id: "jayz-and-kanye", title: "Jay-Z & Kanye", emojis: "👑🪑", level: "hard" },
  { id: "doc-and-marty", title: "Doc & Marty", emojis: "⏰⚡", level: "hard" },
  { id: "butch-and-sundance", title: "Butch & Sundance", emojis: "🤠🚂", level: "hard" },
  { id: "maverick-and-goose", title: "Maverick & Goose", emojis: "✈🕶", level: "hard" },
  { id: "gimli-and-legolas", title: "Gimli & Legolas", emojis: "🪓🏹", level: "hard" },
  { id: "xena-and-gabrielle", title: "Xena & Gabrielle", emojis: "⚔📜", level: "hard" },
  { id: "tarzan-and-jane", title: "Tarzan & Jane", emojis: "🦍👩", level: "hard" },
  { id: "jeeves-and-wooster", title: "Jeeves & Wooster", emojis: "🍸🤵", level: "hard" },

  // ===== IMPOSSIBLE (25) — real-but-tricky duos fans know =====
  { id: "timon-and-pumbaa", title: "Timon & Pumbaa", emojis: "🦡🐗", level: "impossible" },
  { id: "quixote-and-sancho", title: "Quixote & Sancho", emojis: "🐴🫏", level: "impossible" },
  { id: "tristan-and-isolde", title: "Tristan & Isolde", emojis: "🍷⛵", level: "impossible" },
  { id: "phineas-and-ferb", title: "Phineas & Ferb", emojis: "📐⚙", level: "impossible" },
  { id: "gilgamesh-and-enkidu", title: "Gilgamesh & Enkidu", emojis: "👑🌿", level: "impossible" },
  { id: "castor-and-pollux", title: "Castor & Pollux", emojis: "✨♊", level: "impossible" },
  { id: "scylla-and-charybdis", title: "Scylla & Charybdis", emojis: "🐙🌀", level: "impossible" },
  { id: "tom-and-huck", title: "Tom & Huck", emojis: "🪵🎣", level: "impossible" },
  { id: "lewis-and-clark", title: "Lewis & Clark", emojis: "🧭🛶", level: "impossible" },
  { id: "gilbert-and-sullivan", title: "Gilbert & Sullivan", emojis: "⚓🎭", level: "impossible" },
  { id: "rodgers-and-hammerstein", title: "Rodgers & Hammerstein", emojis: "🌽🎼", level: "impossible" },
  { id: "currier-and-ives", title: "Currier & Ives", emojis: "🖼❄", level: "impossible" },
  { id: "wozniak-and-jobs", title: "Wozniak & Jobs", emojis: "💻🍎", level: "impossible" },
  { id: "hewlett-and-packard", title: "Hewlett & Packard", emojis: "🖨💡", level: "impossible" },
  { id: "rolls-and-royce", title: "Rolls & Royce", emojis: "🚗✈", level: "impossible" },
  { id: "mike-and-sulley", title: "Mike & Sulley", emojis: "👁🐲", level: "impossible" },
  { id: "procter-and-gamble", title: "Procter & Gamble", emojis: "🧼🕯", level: "impossible" },
  { id: "antony-and-cleopatra", title: "Antony & Cleopatra", emojis: "🐍👑", level: "impossible" },
  { id: "barnum-and-bailey", title: "Barnum & Bailey", emojis: "🎪🐘", level: "impossible" },
  { id: "kenan-and-kel", title: "Kenan & Kel", emojis: "🍊🥤", level: "impossible" },
  { id: "astaire-and-rogers", title: "Astaire & Rogers", emojis: "🎩👠", level: "impossible" },
  { id: "ash-and-pikachu", title: "Ash & Pikachu", emojis: "🧢⚡", level: "impossible" },
  { id: "crick-and-watson", title: "Crick & Watson", emojis: "🧬🔬", level: "impossible" },
  { id: "stanley-and-livingstone", title: "Stanley & Livingstone", emojis: "🌴🧭", level: "impossible" },
  { id: "punch-and-judy", title: "Punch & Judy", emojis: "🎭👊", level: "impossible" },
];
