// E27 emoji-food facts — one verified ≤70-char fact per dish, shown on reveal.
export const EMOJI_FOOD_FACTS = {
  // EASY
  "pizza": "Naples-born flatbread topped with tomato, cheese and more.",
  "hamburger": "A beef patty in a bun; a global fast-food icon.",
  "sushi": "Japanese dish of vinegared rice with fish or veg.",
  "tacos": "Mexican folded tortilla filled with meat and salsa.",
  "spaghetti": "Long thin Italian pasta, often served with tomato sauce.",
  "hot-dog": "A cooked sausage served in a sliced bun.",
  "pancakes": "Flat batter cakes fried and stacked, often with syrup.",
  "fried-chicken": "Chicken pieces coated and deep-fried until crispy.",
  "ice-cream": "Sweet frozen dessert made from cream and sugar.",
  "french-fries": "Potatoes cut into strips and deep-fried.",
  "ramen": "Japanese wheat noodles served in a savory broth.",
  "donut": "A sweet fried ring of dough, often glazed.",
  "popcorn": "Corn kernels heated until they puff open.",
  "sandwich": "Fillings placed between two slices of bread.",
  "salad": "A mix of raw vegetables, often with dressing.",
  "burrito": "A Mexican wheat tortilla wrapped around a filling.",
  "curry": "A spiced sauce dish popular across South Asia.",
  "dumplings": "Dough parcels wrapped around a savory filling.",
  "waffles": "Batter cooked in a griddle to form a gridded cake.",
  "croissant": "A buttery, flaky French crescent-shaped pastry.",
  "steak": "A thick slice of beef, usually grilled or pan-fried.",
  "bacon-and-eggs": "A classic breakfast of fried bacon and eggs.",
  "cheese": "A dairy food made by curdling milk.",
  "soup": "A savory liquid dish, often served hot.",
  "kebab": "Grilled meat, often cooked on a skewer.",

  // MEDIUM
  "lasagna": "Italian dish of layered pasta, sauce and cheese.",
  "paella": "Spanish rice dish from Valencia with seafood or meat.",
  "pad-thai": "Thailand's stir-fried rice noodles with peanuts.",
  "gnocchi": "Soft Italian dumplings made from potato and flour.",
  "falafel": "Deep-fried balls of ground chickpeas or fava beans.",
  "hummus": "A Middle Eastern dip of blended chickpeas and tahini.",
  "guacamole": "A Mexican dip made from mashed avocado.",
  "pretzel": "A baked dough knot, usually salted.",
  "bagel": "A dense ring of boiled-then-baked bread dough.",
  "risotto": "An Italian rice dish cooked slowly in broth.",
  "pho": "A Vietnamese noodle soup with broth and herbs.",
  "bibimbap": "A Korean bowl of rice topped with veg and egg.",
  "tempura": "Japanese seafood or veg fried in a light batter.",
  "gyros": "Greek meat roasted on a spit and served in bread.",
  "samosa": "A fried pastry with a spiced potato or meat filling.",
  "nachos": "Tortilla chips topped with melted cheese.",
  "quesadilla": "A tortilla folded around melted cheese and grilled.",
  "tiramisu": "An Italian dessert of coffee-soaked sponge and cream.",
  "cheesecake": "A dessert of soft cheese set on a crumb base.",
  "churros": "Fried dough sticks dusted with sugar.",
  "baklava": "A pastry of nuts and syrup in thin flaky layers.",
  "crepe": "A very thin French pancake, sweet or savory.",
  "meatballs": "Balls of ground meat, often served with sauce.",
  "sushi-roll": "Rice and fillings rolled in seaweed, then sliced.",
  "dim-sum": "Small Cantonese dishes served alongside tea.",

  // HARD
  "goulash": "A Hungarian stew of meat seasoned with paprika.",
  "moussaka": "A Greek baked dish of eggplant and minced meat.",
  "ratatouille": "A French stew of summer vegetables from Provence.",
  "borscht": "An Eastern European beet soup, served hot or cold.",
  "pierogi": "Polish dumplings filled with potato, cheese or meat.",
  "schnitzel": "A thin cut of meat breaded and pan-fried.",
  "poutine": "A Canadian dish of fries, cheese curds and gravy.",
  "jambalaya": "A Louisiana rice dish with meat and seafood.",
  "ceviche": "Raw fish cured in citrus juice, a Peruvian classic.",
  "empanada": "A stuffed pastry of Spanish origin, loved Latin-America-wide.",
  "biryani": "A South Asian spiced rice dish layered with meat.",
  "tandoori": "Meat marinated in yogurt and roasted in a clay oven.",
  "shakshuka": "Eggs poached in a spiced tomato and pepper sauce.",
  "tabbouleh": "A Levantine salad of parsley, bulgur and tomato.",
  "congee": "A thick Asian rice porridge, often eaten at breakfast.",
  "laksa": "A spicy Southeast Asian noodle soup with coconut.",
  "satay": "Skewered grilled meat served with peanut sauce.",
  "rendang": "An Indonesian beef slow-cooked in coconut and spice.",
  "bulgogi": "Korean thin beef, marinated and then grilled.",
  "okonomiyaki": "A savory Japanese pancake with cabbage and toppings.",
  "banh-mi": "A Vietnamese baguette sandwich with meat and veg.",
  "arepa": "A cornmeal cake from Venezuela and Colombia.",
  "feijoada": "A Brazilian stew of black beans and pork.",
  "full-english-breakfast": "A fry-up of eggs, bacon, sausage, beans and toast.",
  "clam-chowder": "A creamy American soup of clams and potato.",

  // IMPOSSIBLE
  "haggis": "A Scottish pudding of sheep offal, oats and spice.",
  "kimchi": "Korean fermented, spiced cabbage side dish.",
  "khachapuri": "A Georgian cheese-filled bread, often boat-shaped.",
  "injera": "A spongy Ethiopian flatbread made from teff.",
  "fufu": "A West African dough eaten with soups and stews.",
  "pupusa": "A stuffed corn flatbread from El Salvador.",
  "cachapa": "A sweet Venezuelan corn pancake, often with cheese.",
  "natto": "Japanese fermented soybeans with a sticky texture.",
  "vegemite-toast": "Toast spread with Australia's dark yeast paste.",
  "marmite": "A dark, salty British spread made from yeast.",
  "poi": "A Hawaiian paste made from pounded taro root.",
  "lutefisk": "Nordic dried fish soaked in lye before cooking.",
  "kishka": "An Eastern European sausage filled with grain.",
  "cullen-skink": "A Scottish soup of smoked haddock and potato.",
  "bobotie": "A South African baked dish of spiced minced meat.",
  "kedgeree": "A British dish of flaked fish, rice and egg.",
  "gado-gado": "An Indonesian salad with a peanut sauce dressing.",
  "khinkali": "Georgian dumplings filled with spiced meat and broth.",
  "manti": "Small spiced-meat dumplings served with garlic yogurt.",
  "borek": "A Turkish filled pastry made with thin layered dough.",
  "dolma": "Grape leaves stuffed with rice, common in the region.",
  "surstromming": "Sweden's notoriously smelly fermented herring.",
  "balut": "A cooked fertilized duck egg from the Philippines.",
  "hangikjot": "Iceland's smoked lamb, a festive holiday dish.",
  "hakarl": "Iceland's fermented shark, famed for its strong smell.",
};
