// E35 «Guess the Brand by Emoji» — 100 brands · 25/tier · clue via OpenMoji · VO: sfx/em-<id>.wav
export const EMOJI_BRANDS = [
  // ===== EASY (25) =====
  { id: "mcdonalds", title: "McDonald's", emojis: "🍟🤡", level: "easy" },
  { id: "coca-cola", title: "Coca-Cola", emojis: "🥤🔴", level: "easy" },
  { id: "nike", title: "Nike", emojis: "👟💨", level: "easy" },
  { id: "apple", title: "Apple", emojis: "🍎💻", level: "easy" },
  { id: "google", title: "Google", emojis: "🔍🌈", level: "easy" },
  { id: "amazon", title: "Amazon", emojis: "📦😊", level: "easy" },
  { id: "youtube", title: "YouTube", emojis: "📺▶", level: "easy" },
  { id: "netflix", title: "Netflix", emojis: "🎬🔴", level: "easy" },
  { id: "starbucks", title: "Starbucks", emojis: "☕🧜", level: "easy" },
  { id: "pepsi", title: "Pepsi", emojis: "🥤🔵", level: "easy" },
  { id: "spotify", title: "Spotify", emojis: "🎧🟢", level: "easy" },
  { id: "instagram", title: "Instagram", emojis: "📷🌈", level: "easy" },
  { id: "facebook", title: "Facebook", emojis: "👍🔵", level: "easy" },
  { id: "whatsapp", title: "WhatsApp", emojis: "💬🟢", level: "easy" },
  { id: "disney", title: "Disney", emojis: "🏰🐭", level: "easy" },
  { id: "lego", title: "Lego", emojis: "🧱🧑", level: "easy" },
  { id: "burger-king", title: "Burger King", emojis: "🍔👑", level: "easy" },
  { id: "kfc", title: "KFC", emojis: "🍗👴", level: "easy" },
  { id: "ferrari", title: "Ferrari", emojis: "🐎🔴", level: "easy" },
  { id: "twitter", title: "Twitter", emojis: "🐦🔵", level: "easy" },
  { id: "snapchat", title: "Snapchat", emojis: "👻📸", level: "easy" },
  { id: "tiktok", title: "TikTok", emojis: "🎵🎬", level: "easy" },
  { id: "samsung", title: "Samsung", emojis: "📱🌌", level: "easy" },
  { id: "adidas", title: "Adidas", emojis: "👟🔺", level: "easy" },
  { id: "visa", title: "Visa", emojis: "💳🔵", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "shell", title: "Shell", emojis: "🐚⛽", level: "medium" },
  { id: "airbnb", title: "Airbnb", emojis: "🏠🛏", level: "medium" },
  { id: "ikea", title: "IKEA", emojis: "🪑🔧", level: "medium" },
  { id: "pringles", title: "Pringles", emojis: "🥔🥫", level: "medium" },
  { id: "redbull", title: "Red Bull", emojis: "🐂🪽", level: "medium" },
  { id: "gucci", title: "Gucci", emojis: "👜💚", level: "medium" },
  { id: "rolex", title: "Rolex", emojis: "⌚👑", level: "medium" },
  { id: "lamborghini", title: "Lamborghini", emojis: "🐂💛", level: "medium" },
  { id: "mercedes", title: "Mercedes-Benz", emojis: "⭐🚗", level: "medium" },
  { id: "bmw", title: "BMW", emojis: "🚗💙", level: "medium" },
  { id: "tesla", title: "Tesla", emojis: "⚡🚗", level: "medium" },
  { id: "playstation", title: "PlayStation", emojis: "🎮🔵", level: "medium" },
  { id: "xbox", title: "Xbox", emojis: "🎮🟢", level: "medium" },
  { id: "nintendo", title: "Nintendo", emojis: "🎮🍄", level: "medium" },
  { id: "android", title: "Android", emojis: "🤖🟢", level: "medium" },
  { id: "microsoft", title: "Microsoft", emojis: "🪟💻", level: "medium" },
  { id: "oreo", title: "Oreo", emojis: "🍪⚫", level: "medium" },
  { id: "kitkat", title: "KitKat", emojis: "🍫✋", level: "medium" },
  { id: "nutella", title: "Nutella", emojis: "🍫🫙", level: "medium" },
  { id: "heineken", title: "Heineken", emojis: "🍺⭐", level: "medium" },
  { id: "paypal", title: "PayPal", emojis: "💰🔵", level: "medium" },
  { id: "ebay", title: "eBay", emojis: "🛒🌈", level: "medium" },
  { id: "fedex", title: "FedEx", emojis: "📦🟣", level: "medium" },
  { id: "dhl", title: "DHL", emojis: "📦🟡", level: "medium" },
  { id: "gopro", title: "GoPro", emojis: "📷🪂", level: "medium" },

  // ===== HARD (25) =====
  { id: "rolls-royce", title: "Rolls-Royce", emojis: "🚗👼", level: "hard" },
  { id: "porsche", title: "Porsche", emojis: "🐎🏁", level: "hard" },
  { id: "chanel", title: "Chanel", emojis: "🌸🖤", level: "hard" },
  { id: "louis-vuitton", title: "Louis Vuitton", emojis: "👜🤎", level: "hard" },
  { id: "prada", title: "Prada", emojis: "👜🎩", level: "hard" },
  { id: "rayban", title: "Ray-Ban", emojis: "😎🌞", level: "hard" },
  { id: "gillette", title: "Gillette", emojis: "🪒👨", level: "hard" },
  { id: "duracell", title: "Duracell", emojis: "🔋🐰", level: "hard" },
  { id: "energizer", title: "Energizer", emojis: "🔋🥁", level: "hard" },
  { id: "colgate", title: "Colgate", emojis: "🪥✨", level: "hard" },
  { id: "nescafe", title: "Nescafé", emojis: "☕🫙", level: "hard" },
  { id: "lipton", title: "Lipton", emojis: "🍵🟡", level: "hard" },
  { id: "heinz", title: "Heinz", emojis: "🍅🍶", level: "hard" },
  { id: "barbie", title: "Barbie", emojis: "👧💗", level: "hard" },
  { id: "hotwheels", title: "Hot Wheels", emojis: "🚗🔥", level: "hard" },
  { id: "dyson", title: "Dyson", emojis: "🌀🧹", level: "hard" },
  { id: "bose", title: "Bose", emojis: "🎧🤫", level: "hard" },
  { id: "jbl", title: "JBL", emojis: "🔊🎶", level: "hard" },
  { id: "canon", title: "Canon", emojis: "📷🔴", level: "hard" },
  { id: "nikon", title: "Nikon", emojis: "📷🟡", level: "hard" },
  { id: "casio", title: "Casio", emojis: "⌚🧮", level: "hard" },
  { id: "fitbit", title: "Fitbit", emojis: "⌚👟", level: "hard" },
  { id: "nespresso", title: "Nespresso", emojis: "☕🟤", level: "hard" },
  { id: "omega", title: "Omega", emojis: "⌚🌙", level: "hard" },
  { id: "versace", title: "Versace", emojis: "👗🐍", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "michelin", title: "Michelin", emojis: "🛞🤍", level: "impossible" },
  { id: "lacoste", title: "Lacoste", emojis: "👕🐊", level: "impossible" },
  { id: "jaguar", title: "Jaguar", emojis: "🐆🚗", level: "impossible" },
  { id: "puma", title: "Puma", emojis: "🐈👟", level: "impossible" },
  { id: "lindt", title: "Lindt", emojis: "🍫🐇", level: "impossible" },
  { id: "toblerone", title: "Toblerone", emojis: "🍫🔺", level: "impossible" },
  { id: "evian", title: "Evian", emojis: "💧🗻", level: "impossible" },
  { id: "perrier", title: "Perrier", emojis: "💧🫧", level: "impossible" },
  { id: "quaker", title: "Quaker Oats", emojis: "🌾🥣", level: "impossible" },
  { id: "twix", title: "Twix", emojis: "🍫👯", level: "impossible" },
  { id: "mms", title: "M&M's", emojis: "🍫🌈", level: "impossible" },
  { id: "skittles", title: "Skittles", emojis: "🌈🍬", level: "impossible" },
  { id: "haribo", title: "Haribo", emojis: "🐻🍬", level: "impossible" },
  { id: "goodyear", title: "Goodyear", emojis: "🛞🪽", level: "impossible" },
  { id: "caterpillar", title: "Caterpillar", emojis: "🚜🐛", level: "impossible" },
  { id: "johndeere", title: "John Deere", emojis: "🚜🦌", level: "impossible" },
  { id: "polaroid", title: "Polaroid", emojis: "📸🌈", level: "impossible" },
  { id: "vans", title: "Vans", emojis: "👟🛹", level: "impossible" },
  { id: "converse", title: "Converse", emojis: "👟⭐", level: "impossible" },
  { id: "firestone", title: "Firestone", emojis: "🛞🔥", level: "impossible" },
  { id: "bridgestone", title: "Bridgestone", emojis: "🛞🌉", level: "impossible" },
  { id: "monster-energy", title: "Monster Energy", emojis: "🐉🔋", level: "impossible" },
  { id: "corona", title: "Corona", emojis: "🍺🍋", level: "impossible" },
  { id: "guinness", title: "Guinness", emojis: "🍺⬛", level: "impossible" },
  { id: "fanta", title: "Fanta", emojis: "🍊🥤", level: "impossible" },
];
