// E28 emoji-song facts — one verified ≤70-char fact per song, shown on reveal.
export const EMOJI_SONG_FACTS = {
  // EASY
  "billie-jean": "1983 Michael Jackson hit with an iconic bassline.",
  "thriller": "1982 Michael Jackson song with a famous zombie dance.",
  "bohemian-rhapsody": "1975 Queen epic blending rock and opera.",
  "imagine": "1971 John Lennon anthem of peace and hope.",
  "shape-of-you": "2017 Ed Sheeran hit, a global streaming record-setter.",
  "despacito": "2017 Luis Fonsi hit, a massively streamed Spanish song.",
  "rolling-in-the-deep": "2010 Adele hit from her album 21.",
  "let-it-go": "2013 Frozen anthem that won an Academy Award.",
  "gangnam-style": "2012 PSY hit, first video to reach a billion views.",
  "baby-shark": "Kids' song that became a record-breaking viral video.",
  "happy": "2013 Pharrell Williams upbeat global No. 1 hit.",
  "uptown-funk": "2014 Mark Ronson and Bruno Mars funk smash.",
  "wrecking-ball": "2013 Miley Cyrus power ballad and No. 1 hit.",
  "someone-like-you": "2011 Adele piano ballad from the album 21.",
  "hey-jude": "1968 Beatles ballad with a long sing-along coda.",
  "we-will-rock-you": "1977 Queen stomp-stomp-clap stadium anthem.",
  "sweet-child-o-mine": "1987 Guns N' Roses hit with a famous guitar riff.",
  "smells-like-teen-spirit": "1991 Nirvana anthem that defined grunge.",
  "waka-waka": "2010 Shakira song for the FIFA World Cup.",
  "old-town-road": "2019 Lil Nas X hit with a record US No. 1 run.",
  "shake-it-off": "2014 Taylor Swift pop hit from the album 1989.",
  "bad-guy": "2019 Billie Eilish hit that topped charts worldwide.",
  "dance-monkey": "2019 Tones and I hit, a huge global chart-topper.",
  "wonderwall": "1995 Oasis song, their best-known worldwide.",
  "viva-la-vida": "2008 Coldplay hit and their first US No. 1.",

  // MEDIUM
  "hotel-california": "1976 Eagles classic with a famous guitar solo.",
  "stairway-to-heaven": "1971 Led Zeppelin rock epic that builds slowly.",
  "sweet-caroline": "1969 Neil Diamond sing-along crowd favorite.",
  "purple-rain": "1984 Prince ballad and title of his hit film.",
  "like-a-prayer": "1989 Madonna hit blending pop and gospel.",
  "livin-on-a-prayer": "1986 Bon Jovi rock anthem about Tommy and Gina.",
  "i-will-always-love-you": "1992 Whitney Houston hit from The Bodyguard.",
  "my-heart-will-go-on": "1997 Celine Dion theme from the film Titanic.",
  "every-breath-you-take": "1983 The Police hit about obsessive watching.",
  "take-on-me": "1985 a-ha hit with a famous sketch-style video.",
  "november-rain": "1991 Guns N' Roses power ballad with a long solo.",
  "nothing-else-matters": "1991 Metallica ballad, softer than their norm.",
  "zombie": "1994 Cranberries protest-rock hit sung by Dolores.",
  "africa": "1982 Toto hit, a beloved soft-rock sing-along.",
  "sweet-home-alabama": "1974 Lynyrd Skynyrd Southern rock anthem.",
  "careless-whisper": "1984 George Michael hit with a famous sax line.",
  "dancing-queen": "1976 ABBA disco hit and their only US No. 1.",
  "dont-stop-believin": "1981 Journey anthem, a karaoke favorite.",
  "toxic": "2003 Britney Spears hit that won a Grammy.",
  "umbrella": "2007 Rihanna hit with its 'ella, ella' hook.",
  "poker-face": "2008 Lady Gaga dance-pop worldwide No. 1.",
  "enter-sandman": "1991 Metallica hit about a child's nightmares.",
  "radioactive": "2012 Imagine Dragons hit with a huge chart run.",
  "counting-stars": "2013 OneRepublic global pop-rock hit.",
  "numb": "2003 Linkin Park hit, one of their signature songs.",

  // HARD
  "smooth-criminal": "1988 Michael Jackson hit known for its lean move.",
  "paint-it-black": "1966 Rolling Stones hit with a sitar riff.",
  "comfortably-numb": "1979 Pink Floyd song with two famous solos.",
  "losing-my-religion": "1991 R.E.M. hit driven by a mandolin.",
  "wish-you-were-here": "1975 Pink Floyd song about absence and loss.",
  "creep": "1992 Radiohead's breakthrough debut hit.",
  "boulevard-of-broken-dreams": "2004 Green Day hit from American Idiot.",
  "mr-brightside": "2003 The Killers hit that charted for years.",
  "seven-nation-army": "2003 White Stripes hit with a chant-along riff.",
  "chandelier": "2014 Sia hit with a soaring, powerful chorus.",
  "somebody-that-i-used-to-know": "2011 Gotye duet with Kimbra, a No. 1 hit.",
  "sultans-of-swing": "1978 Dire Straits hit praised for its guitar.",
  "hallelujah": "1984 Leonard Cohen song, covered countless times.",
  "hurt": "Johnny Cash's 2002 cover of the Nine Inch Nails song.",
  "under-the-bridge": "1991 Red Hot Chili Peppers hit about Los Angeles.",
  "layla": "1970 Derek and the Dominos hit led by Eric Clapton.",
  "sweet-dreams": "1983 Eurythmics synth-pop hit by Annie Lennox.",
  "tainted-love": "1981 Soft Cell synth-pop cover, a global hit.",
  "blinding-lights": "2019 The Weeknd hit, a huge streaming smash.",
  "bitter-sweet-symphony": "1997 The Verve hit with a sweeping string loop.",
  "karma-police": "1997 Radiohead hit from OK Computer.",
  "fix-you": "2005 Coldplay ballad with a big anthemic finish.",
  "clocks": "2002 Coldplay hit with a repeating piano riff.",
  "in-the-end": "2000 Linkin Park hit mixing rap and rock.",
  "californication": "1999 Red Hot Chili Peppers hit about Hollywood.",

  // IMPOSSIBLE
  "riders-on-the-storm": "1971 The Doors song with rain and thunder sounds.",
  "a-whiter-shade-of-pale": "1967 Procol Harum hit with a Bach-like organ.",
  "space-oddity": "1969 David Bowie song about astronaut Major Tom.",
  "good-vibrations": "1966 Beach Boys hit called a 'pocket symphony'.",
  "god-only-knows": "1966 Beach Boys ballad from Pet Sounds.",
  "waterloo-sunset": "1967 Kinks song about a London river view.",
  "both-sides-now": "1969 Joni Mitchell song on seeing life two ways.",
  "wichita-lineman": "1968 Glen Campbell hit about a lonely worker.",
  "tangled-up-in-blue": "1975 Bob Dylan song from Blood on the Tracks.",
  "like-a-rolling-stone": "1965 Bob Dylan hit that reshaped rock music.",
  "the-sound-of-silence": "1964 Simon & Garfunkel folk classic.",
  "bridge-over-troubled-water": "1970 Simon & Garfunkel hit about comfort.",
  "a-day-in-the-life": "1967 Beatles song closing Sgt. Pepper's album.",
  "strawberry-fields-forever": "1967 Beatles song about a Liverpool spot.",
  "gimme-shelter": "1969 Rolling Stones song opening Let It Bleed.",
  "london-calling": "1979 The Clash hit and their best-known song.",
  "heroes": "1977 David Bowie song about lovers by a wall.",
  "born-to-run": "1975 Bruce Springsteen anthem of escape.",
  "free-bird": "1973 Lynyrd Skynyrd hit famed for its long solo.",
  "purple-haze": "1967 Jimi Hendrix hit with a distinctive riff.",
  "light-my-fire": "1967 The Doors hit with a long organ solo.",
  "whole-lotta-love": "1969 Led Zeppelin hit with a heavy riff.",
  "wont-get-fooled-again": "1971 The Who anthem with a synth pulse.",
  "sympathy-for-the-devil": "1968 Rolling Stones song narrated by the Devil.",
  "blowin-in-the-wind": "1963 Bob Dylan folk song of open questions.",
};
