// E32 «Guess the Country by Emoji» — 100 countries · 25/tier · clue via OpenMoji · VO: sfx/em-<id>.wav
// Clues hint the COUNTRY via landmarks/animals/food/symbols — never its flag. Single-codepoint emojis only.
export const EMOJI_COUNTRIES = [
  // ===== EASY (25) =====
  { id: "france", title: "France", emojis: "🗼🥐", level: "easy" },
  { id: "japan", title: "Japan", emojis: "🗻🍣", level: "easy" },
  { id: "usa", title: "United States", emojis: "🗽🍔", level: "easy" },
  { id: "italy", title: "Italy", emojis: "🍕🍝", level: "easy" },
  { id: "egypt", title: "Egypt", emojis: "🐫🔺", level: "easy" },
  { id: "australia", title: "Australia", emojis: "🐨🦘", level: "easy" },
  { id: "brazil", title: "Brazil", emojis: "⚽🌴", level: "easy" },
  { id: "china", title: "China", emojis: "🐼🥢", level: "easy" },
  { id: "india", title: "India", emojis: "🐘🕌", level: "easy" },
  { id: "mexico", title: "Mexico", emojis: "🌮🌵", level: "easy" },
  { id: "spain", title: "Spain", emojis: "💃🐂", level: "easy" },
  { id: "germany", title: "Germany", emojis: "🍺🥨", level: "easy" },
  { id: "canada", title: "Canada", emojis: "🍁🦫", level: "easy" },
  { id: "russia", title: "Russia", emojis: "🐻🪆", level: "easy" },
  { id: "uk", title: "United Kingdom", emojis: "👑☕", level: "easy" },
  { id: "greece", title: "Greece", emojis: "🏺🫒", level: "easy" },
  { id: "netherlands", title: "Netherlands", emojis: "🌷🧀", level: "easy" },
  { id: "south-korea", title: "South Korea", emojis: "🥋🎤", level: "easy" },
  { id: "saudi-arabia", title: "Saudi Arabia", emojis: "🐫🕋", level: "easy" },
  { id: "argentina", title: "Argentina", emojis: "🥩⚽", level: "easy" },
  { id: "turkey", title: "Turkey", emojis: "🧿🕌", level: "easy" },
  { id: "thailand", title: "Thailand", emojis: "🐘🛕", level: "easy" },
  { id: "switzerland", title: "Switzerland", emojis: "🧀🎿", level: "easy" },
  { id: "sweden", title: "Sweden", emojis: "🪑🌲", level: "easy" },
  { id: "indonesia", title: "Indonesia", emojis: "🦎🌋", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "kenya", title: "Kenya", emojis: "🦁🦓", level: "medium" },
  { id: "peru", title: "Peru", emojis: "🦙🌄", level: "medium" },
  { id: "vietnam", title: "Vietnam", emojis: "🍜🛵", level: "medium" },
  { id: "south-africa", title: "South Africa", emojis: "🦁💎", level: "medium" },
  { id: "norway", title: "Norway", emojis: "🐳🎣", level: "medium" },
  { id: "portugal", title: "Portugal", emojis: "🐓🍷", level: "medium" },
  { id: "ireland", title: "Ireland", emojis: "🍀🎻", level: "medium" },
  { id: "austria", title: "Austria", emojis: "🎼🎿", level: "medium" },
  { id: "belgium", title: "Belgium", emojis: "🍫🧇", level: "medium" },
  { id: "denmark", title: "Denmark", emojis: "🧜🚲", level: "medium" },
  { id: "new-zealand", title: "New Zealand", emojis: "🥝🐑", level: "medium" },
  { id: "poland", title: "Poland", emojis: "🥟🦅", level: "medium" },
  { id: "nigeria", title: "Nigeria", emojis: "🥁🎶", level: "medium" },
  { id: "colombia", title: "Colombia", emojis: "☕💃", level: "medium" },
  { id: "chile", title: "Chile", emojis: "🍷🗿", level: "medium" },
  { id: "cuba", title: "Cuba", emojis: "🚬🚗", level: "medium" },
  { id: "jamaica", title: "Jamaica", emojis: "🥁🌴", level: "medium" },
  { id: "morocco", title: "Morocco", emojis: "🫖🐪", level: "medium" },
  { id: "finland", title: "Finland", emojis: "🧖🌲", level: "medium" },
  { id: "ukraine", title: "Ukraine", emojis: "🌻🌾", level: "medium" },
  { id: "iceland", title: "Iceland", emojis: "🌋🧊", level: "medium" },
  { id: "philippines", title: "Philippines", emojis: "🏄🥥", level: "medium" },
  { id: "malaysia", title: "Malaysia", emojis: "🦧🌴", level: "medium" },
  { id: "uae", title: "United Arab Emirates", emojis: "🏢🐪", level: "medium" },
  { id: "cambodia", title: "Cambodia", emojis: "🛕🥭", level: "medium" },

  // ===== HARD (25) =====
  { id: "nepal", title: "Nepal", emojis: "🗻🙏", level: "hard" },
  { id: "mongolia", title: "Mongolia", emojis: "🐎🏹", level: "hard" },
  { id: "kazakhstan", title: "Kazakhstan", emojis: "🦅🐎", level: "hard" },
  { id: "madagascar", title: "Madagascar", emojis: "🐒🌴", level: "hard" },
  { id: "ethiopia", title: "Ethiopia", emojis: "🦁☕", level: "hard" },
  { id: "ghana", title: "Ghana", emojis: "🥁🍫", level: "hard" },
  { id: "tanzania", title: "Tanzania", emojis: "🦒🗻", level: "hard" },
  { id: "iran", title: "Iran", emojis: "🐈🕌", level: "hard" },
  { id: "iraq", title: "Iraq", emojis: "🕌🌴", level: "hard" },
  { id: "sri-lanka", title: "Sri Lanka", emojis: "🐘🍵", level: "hard" },
  { id: "bangladesh", title: "Bangladesh", emojis: "🐅🌊", level: "hard" },
  { id: "croatia", title: "Croatia", emojis: "⛵🏰", level: "hard" },
  { id: "hungary", title: "Hungary", emojis: "🛁🎻", level: "hard" },
  { id: "czechia", title: "Czechia", emojis: "🍺🏰", level: "hard" },
  { id: "romania", title: "Romania", emojis: "🧛🏰", level: "hard" },
  { id: "cyprus", title: "Cyprus", emojis: "🍋⛵", level: "hard" },
  { id: "lebanon", title: "Lebanon", emojis: "🌲🧆", level: "hard" },
  { id: "jordan", title: "Jordan", emojis: "🐪🌹", level: "hard" },
  { id: "qatar", title: "Qatar", emojis: "🏢🐫", level: "hard" },
  { id: "kuwait", title: "Kuwait", emojis: "🏢🕌", level: "hard" },
  { id: "oman", title: "Oman", emojis: "⚓🐪", level: "hard" },
  { id: "singapore", title: "Singapore", emojis: "🦁🌆", level: "hard" },
  { id: "fiji", title: "Fiji", emojis: "🌴🐠", level: "hard" },
  { id: "panama", title: "Panama", emojis: "🚢🌊", level: "hard" },
  { id: "costa-rica", title: "Costa Rica", emojis: "🦥🌴", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "bhutan", title: "Bhutan", emojis: "🐉🗻", level: "impossible" },
  { id: "laos", title: "Laos", emojis: "🐘🌾", level: "impossible" },
  { id: "malta", title: "Malta", emojis: "🏰🌊", level: "impossible" },
  { id: "suriname", title: "Suriname", emojis: "🌴🦜", level: "impossible" },
  { id: "brunei", title: "Brunei", emojis: "🕌👑", level: "impossible" },
  { id: "djibouti", title: "Djibouti", emojis: "🐫🧂", level: "impossible" },
  { id: "tuvalu", title: "Tuvalu", emojis: "🌊🐠", level: "impossible" },
  { id: "san-marino", title: "San Marino", emojis: "🏰🗻", level: "impossible" },
  { id: "belize", title: "Belize", emojis: "🐠🤿", level: "impossible" },
  { id: "eswatini", title: "Eswatini", emojis: "🦏🌍", level: "impossible" },
  { id: "kyrgyzstan", title: "Kyrgyzstan", emojis: "🐎🗻", level: "impossible" },
  { id: "moldova", title: "Moldova", emojis: "🍇🍷", level: "impossible" },
  { id: "comoros", title: "Comoros", emojis: "🌋🌴", level: "impossible" },
  { id: "vanuatu", title: "Vanuatu", emojis: "🌋🐚", level: "impossible" },
  { id: "lesotho", title: "Lesotho", emojis: "🗻🐴", level: "impossible" },
  { id: "bolivia", title: "Bolivia", emojis: "🧂🦙", level: "impossible" },
  { id: "paraguay", title: "Paraguay", emojis: "🎶🌿", level: "impossible" },
  { id: "uruguay", title: "Uruguay", emojis: "🥩🧉", level: "impossible" },
  { id: "georgia", title: "Georgia", emojis: "🍷🗻", level: "impossible" },
  { id: "armenia", title: "Armenia", emojis: "🗻🍑", level: "impossible" },
  { id: "azerbaijan", title: "Azerbaijan", emojis: "🔥🕌", level: "impossible" },
  { id: "uzbekistan", title: "Uzbekistan", emojis: "🕌🐫", level: "impossible" },
  { id: "tunisia", title: "Tunisia", emojis: "🐫🫒", level: "impossible" },
  { id: "senegal", title: "Senegal", emojis: "🥁🦁", level: "impossible" },
  { id: "zambia", title: "Zambia", emojis: "💧🐘", level: "impossible" },
];
