// E31 emoji-game facts — one verified ≤70-char fact per game, shown on reveal.
export const EMOJI_GAME_FACTS = {
  // EASY
  "minecraft": "2011 sandbox game; best-selling video game ever.",
  "tetris": "1984 Soviet puzzle of falling blocks by Alexey Pajitnov.",
  "pac-man": "1980 Namco arcade maze game with a dot-eating hero.",
  "super-mario-bros": "1985 Nintendo platformer starring Mario and Luigi.",
  "pokemon": "1996 Nintendo RPG about catching and battling creatures.",
  "fortnite": "2017 Epic battle royale famous for building and skins.",
  "among-us": "2018 party game about finding impostors on a ship.",
  "angry-birds": "2009 mobile hit; birds slingshot at green pigs.",
  "sonic-the-hedgehog": "1991 Sega mascot; a blue hedgehog runs at high speed.",
  "candy-crush": "2012 match-three mobile puzzle by King.",
  "roblox": "2006 online platform where users make and play games.",
  "call-of-duty": "Military first-person shooter series that began in 2003.",
  "grand-theft-auto": "Open-world crime series; first game launched in 1997.",
  "fifa": "EA's football video game series; annual titles since 1993.",
  "space-invaders": "1978 Taito arcade shooter with descending aliens.",
  "mario-kart": "Nintendo kart-racing series that started in 1992.",
  "the-sims": "2000 life-simulation game designed by Will Wright.",
  "pubg": "2017 battle royale that popularized the genre.",
  "flappy-bird": "2013 mobile game infamous for its brutal difficulty.",
  "fruit-ninja": "2010 mobile game; swipe to slice flying fruit.",
  "snake": "Classic game made famous on 1997 Nokia phones.",
  "pong": "1972 Atari table-tennis game, an arcade pioneer.",
  "solitaire": "Card game bundled with Windows since 1990.",
  "wii-sports": "2006 Wii pack-in with tennis, bowling and more.",
  "rocket-league": "2015 game of soccer played with rocket-powered cars.",

  // MEDIUM
  "the-legend-of-zelda": "1986 Nintendo adventure; hero Link saves Zelda.",
  "fall-guys": "2020 battle royale with clumsy jellybean characters.",
  "cut-the-rope": "2010 puzzle; feed candy to a creature named Om Nom.",
  "temple-run": "2011 endless runner fleeing from demon monkeys.",
  "subway-surfers": "2012 endless runner set on subway train tracks.",
  "plants-vs-zombies": "2009 tower defense; plants fend off zombies.",
  "clash-of-clans": "2012 mobile strategy game by Supercell.",
  "doom": "1993 id Software shooter that defined the FPS genre.",
  "street-fighter": "Capcom fighting series; Street Fighter II hit in 1991.",
  "mortal-kombat": "1992 fighting game known for its bloody finishers.",
  "assassins-creed": "Ubisoft stealth-action series launched in 2007.",
  "counter-strike": "Tactical shooter born as a 1999 Half-Life mod.",
  "overwatch": "2016 Blizzard team-based hero shooter.",
  "cyberpunk-2077": "2020 open-world RPG set in futuristic Night City.",
  "world-of-warcraft": "2004 Blizzard MMORPG set in the Warcraft world.",
  "clash-royale": "2016 Supercell real-time card battle game.",
  "hay-day": "2012 farming simulation game by Supercell.",
  "diablo": "1996 Blizzard action RPG of dungeon crawling.",
  "just-dance": "Ubisoft dance game series that began in 2009.",
  "guitar-hero": "2005 rhythm game played on a guitar controller.",
  "crossy-road": "2014 mobile game about crossing endless roads.",
  "geometry-dash": "2013 rhythm-based platform jumping game.",
  "five-nights-at-freddys": "2014 horror game set at a haunted pizzeria.",
  "bejeweled": "2001 match-three gem puzzle by PopCap.",
  "halo": "2001 Xbox sci-fi shooter starring Master Chief.",

  // HARD
  "half-life": "1998 Valve shooter starring scientist Gordon Freeman.",
  "portal": "2007 Valve puzzle game built around a portal gun.",
  "bioshock": "2007 shooter set in the undersea city of Rapture.",
  "dark-souls": "2011 action RPG famed for its punishing difficulty.",
  "metroid": "1986 Nintendo series starring bounty hunter Samus.",
  "castlevania": "1986 Konami series of vampire-hunting Belmonts.",
  "silent-hill": "1999 Konami survival horror in a foggy town.",
  "resident-evil": "1996 Capcom survival horror full of zombies.",
  "metal-gear-solid": "1998 stealth game directed by Hideo Kojima.",
  "god-of-war": "2005 series; Kratos wages war on the gods.",
  "the-witcher": "RPG series about monster hunter Geralt; from 2007.",
  "hollow-knight": "2017 hand-drawn action game in a bug kingdom.",
  "celeste": "2018 platformer about climbing a tough mountain.",
  "cuphead": "2017 run-and-gun with 1930s cartoon artwork.",
  "stardew-valley": "2016 farming RPG made by one developer.",
  "devil-may-cry": "2001 Capcom action series starring Dante.",
  "skyrim": "2011 open-world RPG, The Elder Scrolls V.",
  "red-dead-redemption": "2010 Rockstar open-world western starring John Marston.",
  "the-last-of-us": "2013 game; survive a deadly fungal zombie plague.",
  "uncharted": "Naughty Dog treasure-hunting series from 2007.",
  "tomb-raider": "1996 series starring explorer Lara Croft.",
  "far-cry": "Ubisoft open-world shooter series from 2004.",
  "borderlands": "2009 shooter-looter with cel-shaded art.",
  "sekiro": "2019 FromSoftware game set in feudal Japan.",
  "bloodborne": "2015 gothic action RPG by FromSoftware.",

  // IMPOSSIBLE
  "myst": "1993 puzzle game set on a mysterious island.",
  "katamari-damacy": "2004 game; roll a ball that gathers up objects.",
  "shadow-of-the-colossus": "2005 game; topple sixteen giant colossi.",
  "braid": "2008 puzzle-platformer built on rewinding time.",
  "journey": "2012 game; travel to a mountain with strangers.",
  "limbo": "2010 dark puzzle game rendered in black and white.",
  "ico": "2001 game; a boy leads a girl out of a castle.",
  "okami": "2006 game; a wolf goddess wields a paintbrush.",
  "earthbound": "1994 quirky RPG about kids battling aliens.",
  "chrono-trigger": "1995 Square RPG about traveling through time.",
  "deus-ex": "2000 cyberpunk RPG-shooter about conspiracies.",
  "planescape-torment": "1999 RPG praised for its deep storytelling.",
  "beat-saber": "2018 VR rhythm game; slice beats with sabers.",
  "untitled-goose-game": "2019 game; play a goose pestering a village.",
  "getting-over-it": "2017 game; climb with a hammer while in a pot.",
  "disco-elysium": "2019 detective RPG with no traditional combat.",
  "outer-wilds": "2019 game set within a 22-minute time loop.",
  "hades": "2020 roguelike; escape the Greek underworld.",
  "return-of-the-obra-dinn": "2018 mystery of a lost ship's crew.",
  "papers-please": "2013 game; inspect papers at a border post.",
  "bastion": "2011 action RPG with a live-reacting narrator.",
  "fez": "2012 puzzle game rotating 2D worlds in 3D.",
  "spelunky": "2008 roguelike of randomized cave exploration.",
  "dwarf-fortress": "2006 deep colony simulation of dwarves.",
  "baba-is-you": "2019 puzzle game where you rewrite the rules.",
};
