// E35 emoji-brand facts — one verified ≤70-char fact per brand, shown on reveal.
export const EMOJI_BRAND_FACTS = {
  // EASY
  "mcdonalds": "World's largest fast-food chain by revenue; born in 1940.",
  "coca-cola": "Invented in Atlanta in 1886; its recipe is a famous secret.",
  "nike": "Named after the Greek goddess of victory; the 'swoosh' logo.",
  "apple": "Founded in 1976; became the first $3-trillion company.",
  "google": "Founded in 1998; its name plays on the number googol.",
  "amazon": "Started in 1994 selling books from Jeff Bezos's garage.",
  "youtube": "Launched in 2005; now the world's biggest video site.",
  "netflix": "Began in 1997 mailing DVDs before it streamed online.",
  "starbucks": "Coffee chain founded in Seattle in 1971; twin-tailed siren.",
  "pepsi": "Created in 1893; the longtime rival of Coca-Cola.",
  "spotify": "Swedish music-streaming service launched in 2008.",
  "instagram": "Photo app launched in 2010; bought by Facebook in 2012.",
  "facebook": "Social network Mark Zuckerberg started at Harvard in 2004.",
  "whatsapp": "Messaging app founded in 2009; bought by Facebook in 2014.",
  "disney": "Founded in 1923; Mickey Mouse debuted in 1928.",
  "lego": "Danish toy-brick maker; its name means 'play well'.",
  "burger-king": "Fast-food chain founded in 1954; known for the Whopper.",
  "kfc": "Fried chicken chain founded by Colonel Sanders in the 1930s.",
  "ferrari": "Italian sports-car maker founded by Enzo Ferrari in 1939.",
  "twitter": "Microblog launched in 2006; later rebranded as X.",
  "snapchat": "App launched in 2011 known for disappearing photos.",
  "tiktok": "Short-video app launched globally in 2018 by ByteDance.",
  "samsung": "South Korean giant founded in 1938; name means 'three stars'.",
  "adidas": "German sportswear brand founded by Adi Dassler in 1949.",
  "visa": "Global payment network that began as BankAmericard in 1958.",

  // MEDIUM
  "shell": "Oil giant whose logo is a yellow-and-red scallop shell.",
  "airbnb": "Home-rental platform founded in 2008 in San Francisco.",
  "ikea": "Swedish furniture chain founded in 1943; flat-pack design.",
  "pringles": "Stackable chips sold in a tube; launched by P&G in 1968.",
  "redbull": "Austrian energy drink launched in 1987; 'gives you wings'.",
  "gucci": "Italian luxury fashion house founded in Florence in 1921.",
  "rolex": "Swiss luxury watchmaker founded in 1905; a crown logo.",
  "lamborghini": "Italian supercar maker with a charging-bull emblem.",
  "mercedes": "German luxury cars with a three-pointed star badge.",
  "bmw": "German car maker with a blue-and-white roundel badge.",
  "tesla": "Electric-car maker named after inventor Nikola Tesla.",
  "playstation": "Sony's video-game console brand launched in 1994.",
  "xbox": "Microsoft's video-game console brand launched in 2001.",
  "nintendo": "Japanese game giant founded in 1889 making playing cards.",
  "android": "Google's mobile OS; its mascot is a green robot.",
  "microsoft": "Software giant founded by Gates and Allen in 1975.",
  "oreo": "Sandwich cookie first sold in 1912; twist, lick, dunk.",
  "kitkat": "Chocolate wafer bar with the slogan 'have a break'.",
  "nutella": "Italian hazelnut-and-cocoa spread launched in 1964.",
  "heineken": "Dutch lager brand founded in Amsterdam in 1864.",
  "paypal": "Online payments service that spun off from eBay in 2015.",
  "ebay": "Online auction site founded in 1995 by Pierre Omidyar.",
  "fedex": "Delivery firm with a hidden arrow between its E and x.",
  "dhl": "German courier founded in 1969; letters are founders' names.",
  "gopro": "Action-camera brand founded by Nick Woodman in 2002.",

  // HARD
  "rolls-royce": "British luxury cars; 'Spirit of Ecstasy' hood ornament.",
  "porsche": "German sports-car maker founded by Ferdinand Porsche.",
  "chanel": "French fashion house founded by Coco Chanel in 1910.",
  "louis-vuitton": "French luxury brand known for its monogram luggage.",
  "prada": "Italian luxury label founded in Milan in 1913.",
  "rayban": "Sunglasses brand created for US pilots in 1936.",
  "gillette": "Razor brand with 'the best a man can get' slogan.",
  "duracell": "Alkaline battery brand known for its copper-top cells.",
  "energizer": "Battery brand famous for its drumming pink bunny.",
  "colgate": "Oral-care brand; sold toothpaste in a tube from the 1890s.",
  "nescafe": "Instant coffee launched by Nestlé in 1938.",
  "lipton": "Tea brand founded by Thomas Lipton in the 1890s.",
  "heinz": "Food brand famous for ketchup and '57 varieties'.",
  "barbie": "Mattel fashion doll first sold in 1959.",
  "hotwheels": "Mattel die-cast toy cars launched in 1968.",
  "dyson": "British brand known for bagless vacuum cleaners.",
  "bose": "US audio brand known for noise-cancelling headphones.",
  "jbl": "US speaker and audio brand founded in 1946.",
  "canon": "Japanese camera maker founded in 1937.",
  "nikon": "Japanese camera brand; name from 'Nippon Kogaku'.",
  "casio": "Japanese firm known for watches and calculators.",
  "fitbit": "Fitness tracker brand launched in 2009; bought by Google.",
  "nespresso": "Nestlé coffee-capsule system launched in 1986.",
  "omega": "Swiss watch brand worn on the Moon and by James Bond.",
  "versace": "Italian fashion house with a Medusa-head logo.",

  // IMPOSSIBLE
  "michelin": "Tire maker whose mascot Bibendum is made of tires.",
  "lacoste": "French clothing brand with a green crocodile logo.",
  "jaguar": "British luxury car brand founded in 1922.",
  "puma": "German sportswear brand founded by Rudolf Dassler in 1948.",
  "lindt": "Swiss chocolatier known for its gold-foil bunny.",
  "toblerone": "Swiss triangular chocolate bar created in 1908.",
  "evian": "French bottled water sourced from the Alps.",
  "perrier": "French sparkling mineral water in a green bottle.",
  "quaker": "Oat brand using a smiling Quaker man as its mascot.",
  "twix": "Caramel-and-biscuit chocolate bar sold as twin sticks.",
  "mms": "Colorful candy-shell chocolates first sold in 1941.",
  "skittles": "Fruit candy with the slogan 'taste the rainbow'.",
  "haribo": "German brand that invented the gummy bear in 1922.",
  "goodyear": "US tire maker; its logo is a winged foot for Mercury.",
  "caterpillar": "US maker of heavy machinery, known as CAT.",
  "johndeere": "US tractor maker with a leaping-deer logo.",
  "polaroid": "Brand famous for instant-print cameras from 1948.",
  "vans": "US skate-shoe brand founded in California in 1966.",
  "converse": "US sneaker brand; the star-logo Chuck Taylor All Star.",
  "firestone": "US tire brand founded by Harvey Firestone in 1900.",
  "bridgestone": "Japanese tire giant; founder's name means 'stone bridge'.",
  "monster-energy": "Energy drink launched in 2002; a claw-mark logo.",
  "corona": "Mexican beer often served with a wedge of lime.",
  "guinness": "Irish dry stout brewed in Dublin since 1759.",
  "fanta": "Fruit soda created in Germany in 1940; owned by Coca-Cola.",
};
