// E26 emoji-movie facts — one verified ≤70-char fact per movie, shown on reveal.
export const EMOJI_MOVIE_FACTS = {
  // EASY
  "lion-king": "Disney's 1994 hit, partly inspired by Shakespeare's Hamlet.",
  "titanic": "1997 epic that was long the top-grossing film ever made.",
  "frozen": "2013 Disney smash built around the song 'Let It Go'.",
  "jaws": "Spielberg's 1975 film that invented the summer blockbuster.",
  "up": "Pixar's 2009 film opens with a famous wordless montage.",
  "cars": "Pixar's 2006 racing film set in Radiator Springs.",
  "shrek": "2001 hit; first winner of the Best Animated Feature Oscar.",
  "finding-nemo": "Pixar's 2003 tale of a clownfish searching for his son.",
  "toy-story": "1995 Pixar film, the first fully computer-animated feature.",
  "jurassic-park": "1993 Spielberg film revived dinosaurs from cloned DNA.",
  "king-kong": "Giant ape first scaled the Empire State Building in 1933.",
  "et": "Spielberg's 1982 story of a boy and a stranded alien.",
  "harry-potter": "Wizard saga began with 2001's Philosopher's Stone film.",
  "batman": "The Dark Knight (2008) won Heath Ledger a posthumous Oscar.",
  "spider-man": "2002 film; a genetically altered spider grants Peter powers.",
  "the-avengers": "2012 Marvel team-up became a billion-dollar hit.",
  "star-wars": "1977 space saga created by George Lucas.",
  "minions": "2015 spin-off starring the yellow Despicable Me sidekicks.",
  "despicable-me": "2010 film; villain Gru plots to steal the Moon.",
  "kung-fu-panda": "2008 DreamWorks film about a clumsy panda named Po.",
  "madagascar": "2005 film; zoo animals escape to a wild island.",
  "ice-age": "2002 film; a mammoth, sloth and tiger return a lost baby.",
  "the-incredibles": "Pixar's 2004 film about a family of superheroes.",
  "moana": "2016 Disney film; a Polynesian girl sails to save her isle.",
  "aladdin": "1992 Disney film; Robin Williams voiced the Genie.",

  // MEDIUM
  "inception": "2010 Nolan film about thieves who steal ideas in dreams.",
  "the-matrix": "1999 film; the red pill reveals reality is a simulation.",
  "gladiator": "2000 epic won Best Picture; Russell Crowe starred.",
  "the-terminator": "1984 film; a cyborg is sent back in time to kill.",
  "avatar": "2009 Cameron epic set on Pandora; home of the blue Na'vi.",
  "pirates-of-the-caribbean": "2003 film; Depp plays Captain Jack Sparrow.",
  "the-lord-of-the-rings": "A ring must be destroyed in Mount Doom's fire.",
  "back-to-the-future": "1985 film; a DeLorean time machine hits 88 mph.",
  "forrest-gump": "1994 film; Tom Hanks as a man who witnesses history.",
  "the-godfather": "1972 mafia epic based on Mario Puzo's novel.",
  "rocky": "1976 boxing film; Stallone's underdog won Best Picture.",
  "jurassic-world": "2015 sequel; a park's hybrid dinosaur breaks loose.",
  "the-hunger-games": "2012 film; teens fight to the death on live TV.",
  "pulp-fiction": "1994 Tarantino film with interwoven crime stories.",
  "the-lego-movie": "2014 film; an ordinary minifigure saves the world.",
  "deadpool": "2016 film; a wisecracking, red-suited Marvel antihero.",
  "the-wizard-of-oz": "1939 classic; Dorothy follows the yellow brick road.",
  "wall-e": "Pixar's 2008 film; a lonely robot cleans a trashed Earth.",
  "ratatouille": "Pixar's 2007 film; a rat dreams of cooking in Paris.",
  "coco": "Pixar's 2017 film set on Mexico's Day of the Dead.",
  "zootopia": "2016 Disney film; a bunny cop teams with a sly fox.",
  "the-jungle-book": "Disney tale of Mowgli, a boy raised by wolves.",
  "beauty-and-the-beast": "1991 film; first animation up for Best Picture.",
  "tangled": "2010 Disney film based on the Rapunzel fairy tale.",
  "the-little-mermaid": "1989 Disney film; Ariel trades her voice for legs.",

  // HARD
  "joker": "2019 film; Joaquin Phoenix won an Oscar as the villain.",
  "parasite": "2019 Korean film; first non-English Best Picture winner.",
  "whiplash": "2014 film; a drummer is pushed by a brutal teacher.",
  "interstellar": "2014 Nolan film; a pilot leaves a dying Earth for the stars.",
  "the-shining": "1980 Kubrick horror from a Stephen King novel.",
  "fight-club": "1999 film; its first rule is you don't talk about it.",
  "django-unchained": "2012 Tarantino western; a freed slave seeks his wife.",
  "the-silence-of-the-lambs": "1991 film; Hopkins plays Hannibal Lecter.",
  "no-country-for-old-men": "2007 Coen film; a hitman hunts stolen cash.",
  "mad-max-fury-road": "2015 film; a desert car chase for freedom.",
  "la-la-land": "2016 musical; a jazzman and actress fall in love in LA.",
  "slumdog-millionaire": "2008 film; a poor boy wins India's quiz show.",
  "black-swan": "2010 film; Portman won an Oscar as a driven ballerina.",
  "the-revenant": "2015 film; DiCaprio survives a bear attack in the wild.",
  "the-pianist": "2002 film; a Polish pianist survives WWII in Warsaw.",
  "schindlers-list": "1993 Spielberg film; a man saves Jews in the Holocaust.",
  "saving-private-ryan": "1998 war film opens with the D-Day landings.",
  "the-departed": "2006 Scorsese film won Best Picture; cops and moles.",
  "oldboy": "2003 Korean film; a man is jailed 15 years, then freed.",
  "amelie": "2001 French film; a shy waitress spreads small joys.",
  "pans-labyrinth": "2006 film; a girl escapes war into a dark fairy world.",
  "city-of-god": "2002 Brazilian film set in a violent Rio slum.",
  "requiem-for-a-dream": "2000 film; four lives spiral into addiction.",
  "the-grand-budapest-hotel": "2014 Wes Anderson film about a fabled hotel.",
  "birdman": "2014 film shot to look like one take; won Best Picture.",

  // IMPOSSIBLE
  "citizen-kane": "1941 Welles film; 'Rosebud' is its famous last word.",
  "casablanca": "1942 classic; 'Here's looking at you, kid.'",
  "psycho": "1960 Hitchcock film with a shocking shower scene.",
  "vertigo": "1958 Hitchcock film about a detective's fear of heights.",
  "metropolis": "1927 German sci-fi set in a divided future city.",
  "2001-a-space-odyssey": "1968 Kubrick film with the computer HAL 9000.",
  "the-seventh-seal": "1957 Bergman film; a knight plays chess with Death.",
  "seven-samurai": "1954 Kurosawa epic; warriors defend a farm village.",
  "bicycle-thieves": "1948 Italian film; a man hunts his stolen bicycle.",
  "the-good-the-bad-and-the-ugly": "1966 Leone western; three men seek gold.",
  "singin-in-the-rain": "1952 musical with a famous rain dance number.",
  "a-clockwork-orange": "1971 Kubrick film about a violent youth's reform.",
  "apocalypse-now": "1979 Vietnam War epic by Francis Ford Coppola.",
  "taxi-driver": "1976 Scorsese film; 'You talkin' to me?'",
  "the-third-man": "1949 noir set in postwar Vienna's shadows.",
  "rear-window": "1954 Hitchcock film; a man spies a possible murder.",
  "blade-runner": "1982 sci-fi; a cop hunts rogue androids in 2019 LA.",
  "chinatown": "1974 noir about corruption over Los Angeles water.",
  "modern-times": "1936 Chaplin film mocking the industrial age.",
  "nosferatu": "1922 German film; one of the first vampire movies.",
  "the-great-dictator": "1940 Chaplin film satirizing Adolf Hitler.",
  "dr-strangelove": "1964 Kubrick satire about accidental nuclear war.",
  "the-400-blows": "1959 Truffaut film; a boy's troubled Paris childhood.",
  "la-dolce-vita": "1960 Fellini film; a reporter's restless nights in Rome.",
  "m": "1931 Fritz Lang film; a city hunts a child killer.",
};
