// E122 facts — one short did-you-know per word, keyed by slug. Each ≤70 chars.
export const EMOJI_WORD_FACTS = {
  // EASY
  honeymoon: "The word comes from the 'sweet' first month of marriage.",
  sunflower: "Young sunflowers turn to follow the sun across the sky.",
  starfish: "A starfish can regrow a whole arm if it loses one.",
  rainbow: "A rainbow is always a full circle — the ground hides half.",
  football: "The World Cup final is the most-watched sports event ever.",
  snowman: "The tallest snowperson ever built topped 122 feet.",
  butterfly: "Butterflies taste with sensors on their feet.",
  watermelon: "A watermelon is about 92% water by weight.",
  cupcake: "The first cupcake recipe appeared back in 1796.",
  seahorse: "It's the dad seahorse that gets pregnant, not the mum.",
  seashell: "Most seashells spiral in a clockwise direction.",
  cowboy: "The word 'cowboy' dates to the American West of the 1860s.",
  raincoat: "The first rubber raincoat was the 1820s 'mackintosh'.",
  pancake: "The largest pancake ever was over 15 metres wide.",
  snowball: "No two snowflakes in a snowball are exactly alike.",
  sunglasses: "Roman emperor Nero watched fights through polished gems.",
  catfish: "Catfish have more taste buds than any other animal.",
  doghouse: "'In the doghouse' means you're in a spot of trouble.",
  mailbox: "The first public mailboxes appeared in Paris in 1653.",
  earring: "Earrings are one of the oldest forms of jewellery.",
  handbag: "The word 'handbag' first appeared in the early 1900s.",
  fireman: "'Firefighter' is now preferred over the older 'fireman'.",
  bookworm: "Real bookworms are beetle larvae that tunnel through pages.",
  ladybug: "A ladybug can eat 5,000 aphids in its lifetime.",
  eyeball: "Your eyeballs stay roughly the same size from birth.",

  // MEDIUM
  eggplant: "The eggplant is botanically a berry, not a vegetable.",
  pineapple: "A pineapple takes about two years to grow one fruit.",
  moonwalk: "Michael Jackson debuted the moonwalk on TV in 1983.",
  keyboard: "The QWERTY layout was designed to slow typists down.",
  seaweed: "Some seaweed can grow up to 30 cm in a single day.",
  milkman: "Home milk delivery peaked in the 1950s and 60s.",
  toothbrush: "The first nylon-bristle toothbrush arrived in 1938.",
  horseshoe: "A hanging horseshoe is a worldwide symbol of good luck.",
  firefly: "Fireflies glow using a chemical reaction, not heat.",
  dragonfly: "Dragonflies have existed for over 300 million years.",
  cheeseburger: "The cheeseburger was reportedly invented in the 1920s.",
  moonlight: "Moonlight is just sunlight reflected off the Moon.",
  keyhole: "Old keyhole shapes inspired the classic 'keyhole' arch.",
  footprint: "Astronaut footprints on the Moon could last millions of years.",
  cupboard: "'Cupboard' once literally meant a board to store cups.",
  fishbowl: "A round fishbowl distorts a fish's view of the world.",
  bulldog: "Bulldogs were bred in England for the sport of bull-baiting.",
  catwalk: "The fashion 'catwalk' is named for a narrow raised path.",
  doorbell: "The electric doorbell was invented in the 1830s.",
  mooncake: "Mooncakes are eaten at China's Mid-Autumn Festival.",
  starlight: "Starlight you see may have left its star long ago.",
  keychain: "The split-ring keychain was patented in the 1890s.",
  rainwater: "Rainwater is naturally slightly acidic.",
  firewood: "Dry, seasoned firewood burns far cleaner than green wood.",
  cornbread: "Cornbread is a staple of the American South.",

  // HARD
  belief: "Sounds like 'bee' plus 'leaf' — a phonetic rebus!",
  carpet: "The world's oldest carpet is over 2,000 years old.",
  handball: "Handball debuted at the 1936 Berlin Olympics.",
  moonshine: "'Moonshine' means liquor made secretly at night.",
  sunshine: "Sunshine helps your skin make vitamin D.",
  earthworm: "Earthworms have no lungs — they breathe through skin.",
  seesaw: "Sounds like 'sea' plus 'saw' — a playground classic.",
  keynote: "A keynote speech sets the theme for a whole event.",
  footnote: "Footnotes let writers add notes without breaking the flow.",
  milkweed: "Monarch butterflies lay eggs only on milkweed plants.",
  catnap: "A catnap is a short, light sleep — just like a cat's.",
  dogwood: "Dogwood trees burst into bloom in early spring.",
  firecracker: "Firecrackers were invented in ancient China.",
  rainstorm: "A single rainstorm can drop billions of litres of water.",
  seabed: "Most of the world's seabed has never been mapped in detail.",
  horsepower: "One horsepower was defined by the work of a real horse.",
  butterball: "'Butterball' is an affectionate word for something chubby.",
  gingerbread: "Gingerbread houses were popularised by the Brothers Grimm.",
  moonstone: "Moonstone shimmers with a glow called adularescence.",
  firebird: "The Firebird is a magical creature from Russian folklore.",
  seahawk: "'Seahawk' is another name for the fish-hunting osprey.",
  eyebrow: "Eyebrows help keep sweat and rain out of your eyes.",
  buttercup: "Hold a buttercup under your chin — do you like butter?",
  horsefly: "A horsefly's bite is famously painful.",
  ladybird: "'Ladybird' is the British name for the ladybug.",

  // IMPOSSIBLE
  carpool: "Carpooling can cut a commuter's fuel costs in half.",
  hamburger: "The hamburger is named after Hamburg, Germany.",
  wheelchair: "The folding wheelchair was invented in 1933.",
  crossbow: "The crossbow was a feared weapon of the Middle Ages.",
  keystone: "The keystone locks every stone in an arch in place.",
  sweetheart: "'Sweetheart' has been a term of love since the 1300s.",
  brainstorm: "The term 'brainstorm' for idea-storms dates to the 1940s.",
  nightmare: "'Mare' once meant a demon believed to cause bad dreams.",
  penknife: "Penknives were first used to sharpen quill pens.",
  snowmobile: "The modern snowmobile was invented in Canada in 1935.",
  eardrum: "Your eardrum is thinner than a sheet of paper.",
  handprint: "Ancient cave art often features stencilled handprints.",
  cardboard: "Corrugated cardboard was first patented in 1856.",
  teaspoon: "A teaspoon holds about 5 millilitres of liquid.",
  spearfish: "Spearfishing is one of the oldest ways to catch fish.",
  paintbrush: "The finest brushes are still made with natural hair.",
  handbook: "A handbook is a small guide meant to fit in the hand.",
  notebook: "The Moleskine notebook brand launched in 1997.",
  cakewalk: "'Cakewalk' means something very easy — the prize was a cake.",
  boardwalk: "Atlantic City built the first US boardwalk in 1870.",
  watchdog: "A 'watchdog' can also mean a group that guards the public.",
  starboard: "'Starboard' is the right side of a ship, facing forward.",
  birdhouse: "Purple martins in the US nest almost only in birdhouses.",
  lighthouse: "The Lighthouse of Alexandria was an ancient wonder.",
  hamstring: "Your hamstrings are the muscles at the back of your thigh.",
};
