// E33 emoji-country v2 facts — one verified ≤70-char fact per country, shown on reveal.
export const EMOJI_COUNTRIES2_FACTS = {
  // EASY
  "pakistan": "Home to K2, the world's second-highest mountain.",
  "venezuela": "Angel Falls here is the world's tallest waterfall.",
  "estonia": "Skype was born in its capital, Tallinn.",
  "lithuania": "Basketball is its unofficial national religion.",
  "latvia": "Riga is famed for its Art Nouveau architecture.",
  "slovakia": "Bratislava is the only capital bordering two nations.",
  "slovenia": "A dragon guards the bridge in capital Ljubljana.",
  "serbia": "Belgrade sits where the Sava meets the Danube.",
  "ecuador": "The Galapagos Islands belong to this equator nation.",
  "guatemala": "Ancient Maya city Tikal rises from its jungle.",
  "honduras": "Home to the Maya ruins of Copan.",
  "monaco": "Second-smallest country; hosts a Formula 1 Grand Prix.",
  "luxembourg": "A tiny grand duchy and major banking hub.",
  "maldives": "Nation of 1,000+ coral islands and turquoise seas.",
  "myanmar": "Bagan's plain holds thousands of ancient temples.",
  "uganda": "Half the world's mountain gorillas live here.",
  "belarus": "Landlocked nation nicknamed 'land of lakes'.",
  "taiwan": "Taipei 101 was once the world's tallest building.",
  "cameroon": "Called 'Africa in miniature' for its diversity.",
  "libya": "Vast Sahara desert nation on the Mediterranean.",
  "sudan": "Has more ancient pyramids than Egypt.",
  "haiti": "First nation founded by a successful slave revolt.",
  "dominican-republic": "Shares Hispaniola island with Haiti.",
  "bulgaria": "World's top producer of rose oil for perfume.",
  "bahamas": "Its Exuma isles have famous swimming pigs.",

  // MEDIUM
  "albania": "Its name means 'Land of the Eagles'.",
  "algeria": "Africa's largest country, mostly Sahara desert.",
  "angola": "Oil-rich nation on the southwest African coast.",
  "mozambique": "Long Indian Ocean coastline famed for prawns.",
  "namibia": "The Namib is Earth's oldest desert.",
  "botswana": "The Okavango Delta floods its Kalahari sands.",
  "zimbabwe": "Named after the stone ruins of Great Zimbabwe.",
  "north-korea": "One of the world's most isolated nations.",
  "syria": "Damascus is among the oldest inhabited cities.",
  "yemen": "The port of Mocha gave coffee its name.",
  "bahrain": "An island kingdom in the Persian Gulf.",
  "nicaragua": "Largest Central American country, full of volcanoes.",
  "el-salvador": "Smallest Central American nation, 'Land of Volcanoes'.",
  "rwanda": "The 'Land of a Thousand Hills' in East Africa.",
  "mali": "Timbuktu was a great center of learning here.",
  "niger": "Named after the great river crossing its south.",
  "mauritius": "The extinct dodo bird once lived only here.",
  "montenegro": "Its name means 'Black Mountain'.",
  "north-macedonia": "Lake Ohrid is among Europe's oldest and deepest lakes.",
  "papua-new-guinea": "Home to over 800 distinct languages.",
  "tajikistan": "Over 90% of it is mountainous terrain.",
  "turkmenistan": "The Darvaza 'Door to Hell' gas crater burns here.",
  "samoa": "A Polynesian nation just west of the date line.",
  "tonga": "The last Polynesian kingdom, never colonized.",
  "bosnia-and-herzegovina": "Mostar's arched Old Bridge spans the Neretva.",

  // HARD
  "benin": "Birthplace of the Vodun (voodoo) religion.",
  "togo": "A narrow West African strip on the Gulf of Guinea.",
  "burkina-faso": "Its name means 'Land of Honest People'.",
  "guinea": "Holds huge reserves of bauxite, the aluminium ore.",
  "sierra-leone": "Freetown was founded by freed enslaved people.",
  "liberia": "Africa's oldest republic, settled by freed slaves.",
  "gambia": "Africa's smallest mainland country, hugging a river.",
  "eritrea": "Asmara, a UNESCO Art Deco city in Eritrea's highlands.",
  "malawi": "Lake Malawi holds the most fish species of any lake.",
  "burundi": "Famed for its sacred royal drummers.",
  "equatorial-guinea": "Only African country with Spanish as official.",
  "central-african-republic": "Landlocked heart of the continent, rich in diamonds.",
  "congo-republic": "Its capital Brazzaville faces Kinshasa across a river.",
  "dr-congo": "The Congo River is the world's deepest.",
  "ivory-coast": "The world's largest producer of cocoa beans.",
  "guinea-bissau": "A major world exporter of cashew nuts.",
  "cape-verde": "Island nation and birthplace of morna music.",
  "barbados": "Singer Rihanna's Caribbean island homeland.",
  "trinidad-and-tobago": "Birthplace of the steelpan and calypso.",
  "grenada": "The 'Spice Isle', a top nutmeg producer.",
  "guyana": "Kaieteur is one of the world's most powerful falls.",
  "dominica": "The 'Nature Isle' of the Caribbean.",
  "saint-lucia": "The twin Piton peaks rise from its sea.",
  "gabon": "Nearly 90% of this land is tropical rainforest.",
  "mauritania": "Vast Saharan nation on the Atlantic coast.",

  // IMPOSSIBLE
  "andorra": "A tiny principality high in the Pyrenees.",
  "liechtenstein": "A doubly landlocked alpine principality.",
  "vatican-city": "The world's smallest country, home of the Pope.",
  "kosovo": "One of Europe's youngest countries, born 2008.",
  "palestine": "Bethlehem and old Jericho lie within its lands.",
  "cook-islands": "A self-governing Polynesian isle group.",
  "hong-kong": "A dense harbor city of towering skyscrapers.",
  "puerto-rico": "A Caribbean island and cradle of reggaeton.",
  "kiribati": "Straddles the equator and the date line.",
  "nauru": "The world's smallest island nation.",
  "palau": "Its Jellyfish Lake teems with stingless jellyfish.",
  "micronesia": "Home to the ancient stone ruins of Nan Madol.",
  "marshall-islands": "Bikini Atoll was a Cold War nuclear test site.",
  "solomon-islands": "A Pacific chain of nearly 1,000 islands.",
  "antigua-and-barbuda": "Said to have a beach for every day of the year.",
  "saint-kitts-and-nevis": "Smallest nation in the Americas by area.",
  "saint-vincent": "Its Soufriere volcano erupted as recently as 2021.",
  "seychelles": "Home to the giant Aldabra tortoise.",
  "timor-leste": "Asia's youngest nation, on Timor's east half.",
  "greenland": "The world's largest island, mostly ice sheet.",
  "afghanistan": "Landlocked and crossed by the Hindu Kush range.",
  "chad": "Named after its shrinking Lake Chad.",
  "somalia": "Has the longest coastline on mainland Africa.",
  "south-sudan": "The world's youngest nation, born in 2011.",
  "sao-tome": "A cocoa-growing island nation on the equator.",
};
