// E27 «Guess the Food by Emoji» — 100 foods · 25/tier · clue via OpenMoji · VO: sfx/em-<id>.wav
export const EMOJI_FOODS = [
  // ===== EASY (25) =====
  { id: "pizza", title: "Pizza", emojis: "🍕🧀", level: "easy" },
  { id: "hamburger", title: "Hamburger", emojis: "🍔🥩", level: "easy" },
  { id: "sushi", title: "Sushi", emojis: "🍚🐟", level: "easy" },
  { id: "tacos", title: "Tacos", emojis: "🌮🥑", level: "easy" },
  { id: "spaghetti", title: "Spaghetti", emojis: "🍝🍅", level: "easy" },
  { id: "hot-dog", title: "Hot Dog", emojis: "🌭🍞", level: "easy" },
  { id: "pancakes", title: "Pancakes", emojis: "🥞🍯", level: "easy" },
  { id: "fried-chicken", title: "Fried Chicken", emojis: "🍗🔥", level: "easy" },
  { id: "ice-cream", title: "Ice Cream", emojis: "🍦🍨", level: "easy" },
  { id: "french-fries", title: "French Fries", emojis: "🍟🥔", level: "easy" },
  { id: "ramen", title: "Ramen", emojis: "🍜🥚", level: "easy" },
  { id: "donut", title: "Donut", emojis: "🍩☕", level: "easy" },
  { id: "popcorn", title: "Popcorn", emojis: "🍿🎬", level: "easy" },
  { id: "sandwich", title: "Sandwich", emojis: "🥪🍞", level: "easy" },
  { id: "salad", title: "Salad", emojis: "🥗🥬", level: "easy" },
  { id: "burrito", title: "Burrito", emojis: "🌯🫘", level: "easy" },
  { id: "curry", title: "Curry", emojis: "🍛🥘", level: "easy" },
  { id: "dumplings", title: "Dumplings", emojis: "🥟🥢", level: "easy" },
  { id: "waffles", title: "Waffles", emojis: "🧇🍓", level: "easy" },
  { id: "croissant", title: "Croissant", emojis: "🥐☕", level: "easy" },
  { id: "steak", title: "Steak", emojis: "🥩🔥", level: "easy" },
  { id: "bacon-and-eggs", title: "Bacon and Eggs", emojis: "🥓🍳", level: "easy" },
  { id: "cheese", title: "Cheese", emojis: "🧀🥛", level: "easy" },
  { id: "soup", title: "Soup", emojis: "🥣🥕", level: "easy" },
  { id: "kebab", title: "Kebab", emojis: "🍢🔥", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "lasagna", title: "Lasagna", emojis: "🧀🍅🍝", level: "medium" },
  { id: "paella", title: "Paella", emojis: "🥘🦐🍚", level: "medium" },
  { id: "pad-thai", title: "Pad Thai", emojis: "🍜🥜🦐", level: "medium" },
  { id: "gnocchi", title: "Gnocchi", emojis: "🥔🍝", level: "medium" },
  { id: "falafel", title: "Falafel", emojis: "🧆🫓", level: "medium" },
  { id: "hummus", title: "Hummus", emojis: "🫘🥣", level: "medium" },
  { id: "guacamole", title: "Guacamole", emojis: "🥑🥣", level: "medium" },
  { id: "pretzel", title: "Pretzel", emojis: "🥨🧂", level: "medium" },
  { id: "bagel", title: "Bagel", emojis: "🥯🧀", level: "medium" },
  { id: "risotto", title: "Risotto", emojis: "🍚🧀🍷", level: "medium" },
  { id: "pho", title: "Pho", emojis: "🍜🐄", level: "medium" },
  { id: "bibimbap", title: "Bibimbap", emojis: "🍚🥚🥬", level: "medium" },
  { id: "tempura", title: "Tempura", emojis: "🍤🥢", level: "medium" },
  { id: "gyros", title: "Gyros", emojis: "🥙🍖", level: "medium" },
  { id: "samosa", title: "Samosa", emojis: "🔺🥔", level: "medium" },
  { id: "nachos", title: "Nachos", emojis: "🧀🌽", level: "medium" },
  { id: "quesadilla", title: "Quesadilla", emojis: "🫓🧀", level: "medium" },
  { id: "tiramisu", title: "Tiramisu", emojis: "☕🍰", level: "medium" },
  { id: "cheesecake", title: "Cheesecake", emojis: "🧀🍰", level: "medium" },
  { id: "churros", title: "Churros", emojis: "🍩🍫", level: "medium" },
  { id: "baklava", title: "Baklava", emojis: "🍯🥜", level: "medium" },
  { id: "crepe", title: "Crepe", emojis: "🥞🍋", level: "medium" },
  { id: "meatballs", title: "Meatballs", emojis: "🍝🔴", level: "medium" },
  { id: "sushi-roll", title: "Sushi Roll", emojis: "🍚🐟🥢", level: "medium" },
  { id: "dim-sum", title: "Dim Sum", emojis: "🥟🍵", level: "medium" },

  // ===== HARD (25) =====
  { id: "goulash", title: "Goulash", emojis: "🥘🐄", level: "hard" },
  { id: "moussaka", title: "Moussaka", emojis: "🍆🥩🧀", level: "hard" },
  { id: "ratatouille", title: "Ratatouille", emojis: "🍆🍅🥒", level: "hard" },
  { id: "borscht", title: "Borscht", emojis: "🥣🔴", level: "hard" },
  { id: "pierogi", title: "Pierogi", emojis: "🥟🥔", level: "hard" },
  { id: "schnitzel", title: "Schnitzel", emojis: "🐷🍞", level: "hard" },
  { id: "poutine", title: "Poutine", emojis: "🍟🧀🥣", level: "hard" },
  { id: "jambalaya", title: "Jambalaya", emojis: "🍚🦐🍗", level: "hard" },
  { id: "ceviche", title: "Ceviche", emojis: "🐟🍋", level: "hard" },
  { id: "empanada", title: "Empanada", emojis: "🥟🌽", level: "hard" },
  { id: "biryani", title: "Biryani", emojis: "🍚🍗", level: "hard" },
  { id: "tandoori", title: "Tandoori Chicken", emojis: "🍗🔥🧅", level: "hard" },
  { id: "shakshuka", title: "Shakshuka", emojis: "🍅🥚🍳", level: "hard" },
  { id: "tabbouleh", title: "Tabbouleh", emojis: "🥬🍅🍋", level: "hard" },
  { id: "congee", title: "Congee", emojis: "🍚🥣", level: "hard" },
  { id: "laksa", title: "Laksa", emojis: "🍜🦐🥥", level: "hard" },
  { id: "satay", title: "Satay", emojis: "🍢🥜", level: "hard" },
  { id: "rendang", title: "Rendang", emojis: "🐄🥥", level: "hard" },
  { id: "bulgogi", title: "Bulgogi", emojis: "🥩🔥🍚", level: "hard" },
  { id: "okonomiyaki", title: "Okonomiyaki", emojis: "🥞🐙🥬", level: "hard" },
  { id: "banh-mi", title: "Banh Mi", emojis: "🥖🥩🥕", level: "hard" },
  { id: "arepa", title: "Arepa", emojis: "🌽🧀", level: "hard" },
  { id: "feijoada", title: "Feijoada", emojis: "🫘🐷🍚", level: "hard" },
  { id: "full-english-breakfast", title: "Full English Breakfast", emojis: "🥓🍳🍞", level: "hard" },
  { id: "clam-chowder", title: "Clam Chowder", emojis: "🦪🥣🥔", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "haggis", title: "Haggis", emojis: "🐑🥣", level: "impossible" },
  { id: "kimchi", title: "Kimchi", emojis: "🥬🔴", level: "impossible" },
  { id: "khachapuri", title: "Khachapuri", emojis: "🍞🧀🥚", level: "impossible" },
  { id: "injera", title: "Injera", emojis: "🫓🥘", level: "impossible" },
  { id: "fufu", title: "Fufu", emojis: "🥣🍠", level: "impossible" },
  { id: "pupusa", title: "Pupusa", emojis: "🫓🧀🌽", level: "impossible" },
  { id: "cachapa", title: "Cachapa", emojis: "🌽🧀🥛", level: "impossible" },
  { id: "natto", title: "Natto", emojis: "🫘🥢", level: "impossible" },
  { id: "vegemite-toast", title: "Vegemite Toast", emojis: "🍞🟤", level: "impossible" },
  { id: "marmite", title: "Marmite", emojis: "🟤🥄", level: "impossible" },
  { id: "poi", title: "Poi", emojis: "🟣🥣", level: "impossible" },
  { id: "lutefisk", title: "Lutefisk", emojis: "🐟🧊", level: "impossible" },
  { id: "kishka", title: "Kishka", emojis: "🌭🍚", level: "impossible" },
  { id: "cullen-skink", title: "Cullen Skink", emojis: "🐟🥣🥔", level: "impossible" },
  { id: "bobotie", title: "Bobotie", emojis: "🥩🥚🍛", level: "impossible" },
  { id: "kedgeree", title: "Kedgeree", emojis: "🍚🐟🥚", level: "impossible" },
  { id: "gado-gado", title: "Gado-Gado", emojis: "🥗🥜", level: "impossible" },
  { id: "khinkali", title: "Khinkali", emojis: "🥟🍖", level: "impossible" },
  { id: "manti", title: "Manti", emojis: "🥟🥛", level: "impossible" },
  { id: "borek", title: "Borek", emojis: "🥐🧀🥬", level: "impossible" },
  { id: "dolma", title: "Dolma", emojis: "🍇🍚", level: "impossible" },
  { id: "surstromming", title: "Surstromming", emojis: "🐟🥫", level: "impossible" },
  { id: "balut", title: "Balut", emojis: "🥚🐤", level: "impossible" },
  { id: "hangikjot", title: "Hangikjot", emojis: "🐑🔥", level: "impossible" },
  { id: "hakarl", title: "Hakarl", emojis: "🦈🧊", level: "impossible" },
];
