// E37 «Guess the Book by Emoji» — 100 books · 25/tier · clue via OpenMoji · VO: sfx/em-<id>.wav
export const EMOJI_BOOKS = [
  // ===== EASY (25) =====
  { id: "harry-potter", title: "Harry Potter", emojis: "🧙⚡", level: "easy" },
  { id: "the-bible", title: "The Bible", emojis: "📖🙏", level: "easy" },
  { id: "romeo-and-juliet", title: "Romeo and Juliet", emojis: "💑💔", level: "easy" },
  { id: "dracula", title: "Dracula", emojis: "🧛🦇", level: "easy" },
  { id: "alice-in-wonderland", title: "Alice in Wonderland", emojis: "🐇🍄", level: "easy" },
  { id: "the-little-prince", title: "The Little Prince", emojis: "🤴🌹", level: "easy" },
  { id: "charlottes-web", title: "Charlotte's Web", emojis: "🕷🐷", level: "easy" },
  { id: "frankenstein", title: "Frankenstein", emojis: "⚡🧟", level: "easy" },
  { id: "peter-pan", title: "Peter Pan", emojis: "🧚⏳", level: "easy" },
  { id: "moby-dick", title: "Moby Dick", emojis: "🐋⛵", level: "easy" },
  { id: "the-hobbit", title: "The Hobbit", emojis: "🧝💍", level: "easy" },
  { id: "pinocchio", title: "Pinocchio", emojis: "🤥🪵", level: "easy" },
  { id: "cinderella", title: "Cinderella", emojis: "👠🎃", level: "easy" },
  { id: "winnie-the-pooh", title: "Winnie-the-Pooh", emojis: "🐻🍯", level: "easy" },
  { id: "the-cat-in-the-hat", title: "The Cat in the Hat", emojis: "🐱🎩", level: "easy" },
  { id: "treasure-island", title: "Treasure Island", emojis: "🗺💰", level: "easy" },
  { id: "the-jungle-book", title: "The Jungle Book", emojis: "🐅🐍", level: "easy" },
  { id: "snow-white", title: "Snow White", emojis: "🍎👸", level: "easy" },
  { id: "the-wizard-of-oz", title: "The Wonderful Wizard of Oz", emojis: "🌈👠", level: "easy" },
  { id: "the-very-hungry-caterpillar", title: "The Very Hungry Caterpillar", emojis: "🐛🍎", level: "easy" },
  { id: "matilda", title: "Matilda", emojis: "👧📚", level: "easy" },
  { id: "the-old-man-and-the-sea", title: "The Old Man and the Sea", emojis: "👴🐟", level: "easy" },
  { id: "the-three-musketeers", title: "The Three Musketeers", emojis: "🤺👑", level: "easy" },
  { id: "the-call-of-the-wild", title: "The Call of the Wild", emojis: "🐺🏔", level: "easy" },
  { id: "twenty-thousand-leagues", title: "Twenty Thousand Leagues Under the Sea", emojis: "🐙🌊", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "the-lord-of-the-rings", title: "The Lord of the Rings", emojis: "💍🌋", level: "medium" },
  { id: "pride-and-prejudice", title: "Pride and Prejudice", emojis: "💃💌", level: "medium" },
  { id: "the-great-gatsby", title: "The Great Gatsby", emojis: "🥂🎉", level: "medium" },
  { id: "nineteen-eighty-four", title: "1984", emojis: "👁📺", level: "medium" },
  { id: "animal-farm", title: "Animal Farm", emojis: "🐷🚜", level: "medium" },
  { id: "the-count-of-monte-cristo", title: "The Count of Monte Cristo", emojis: "🏰💰", level: "medium" },
  { id: "a-christmas-carol", title: "A Christmas Carol", emojis: "🎄👻", level: "medium" },
  { id: "gone-with-the-wind", title: "Gone with the Wind", emojis: "🌪💃", level: "medium" },
  { id: "the-hunchback-of-notre-dame", title: "The Hunchback of Notre-Dame", emojis: "🔔⛪", level: "medium" },
  { id: "the-picture-of-dorian-gray", title: "The Picture of Dorian Gray", emojis: "🖼👨", level: "medium" },
  { id: "dr-jekyll-and-mr-hyde", title: "Dr Jekyll and Mr Hyde", emojis: "🧪👿", level: "medium" },
  { id: "the-time-machine", title: "The Time Machine", emojis: "⏳🚀", level: "medium" },
  { id: "the-war-of-the-worlds", title: "The War of the Worlds", emojis: "👽🌍", level: "medium" },
  { id: "around-the-world-in-eighty-days", title: "Around the World in Eighty Days", emojis: "🎈🌍", level: "medium" },
  { id: "the-secret-garden", title: "The Secret Garden", emojis: "🌷🔑", level: "medium" },
  { id: "black-beauty", title: "Black Beauty", emojis: "🐴🖤", level: "medium" },
  { id: "the-wind-in-the-willows", title: "The Wind in the Willows", emojis: "🐸🚗", level: "medium" },
  { id: "les-miserables", title: "Les Misérables", emojis: "🍞⛓", level: "medium" },
  { id: "oliver-twist", title: "Oliver Twist", emojis: "🍲👦", level: "medium" },
  { id: "huckleberry-finn", title: "The Adventures of Huckleberry Finn", emojis: "🛶🏞", level: "medium" },
  { id: "sherlock-holmes", title: "The Adventures of Sherlock Holmes", emojis: "🔍🕵", level: "medium" },
  { id: "gullivers-travels", title: "Gulliver's Travels", emojis: "🚢🧍", level: "medium" },
  { id: "robinson-crusoe", title: "Robinson Crusoe", emojis: "🌴⛵", level: "medium" },
  { id: "journey-to-the-center-of-the-earth", title: "Journey to the Center of the Earth", emojis: "🌋⛏", level: "medium" },
  { id: "the-legend-of-sleepy-hollow", title: "The Legend of Sleepy Hollow", emojis: "🎃🐎", level: "medium" },

  // ===== HARD (25) =====
  { id: "to-kill-a-mockingbird", title: "To Kill a Mockingbird", emojis: "🐦🏛", level: "hard" },
  { id: "the-catcher-in-the-rye", title: "The Catcher in the Rye", emojis: "🧢🌾", level: "hard" },
  { id: "lord-of-the-flies", title: "Lord of the Flies", emojis: "🐚🔥", level: "hard" },
  { id: "of-mice-and-men", title: "Of Mice and Men", emojis: "🐭👬", level: "hard" },
  { id: "brave-new-world", title: "Brave New World", emojis: "💊🧬", level: "hard" },
  { id: "fahrenheit-451", title: "Fahrenheit 451", emojis: "🔥📚", level: "hard" },
  { id: "the-grapes-of-wrath", title: "The Grapes of Wrath", emojis: "🍇🚜", level: "hard" },
  { id: "jane-eyre", title: "Jane Eyre", emojis: "👰🔥", level: "hard" },
  { id: "wuthering-heights", title: "Wuthering Heights", emojis: "🌬🏔", level: "hard" },
  { id: "the-scarlet-letter", title: "The Scarlet Letter", emojis: "🔴✉", level: "hard" },
  { id: "heart-of-darkness", title: "Heart of Darkness", emojis: "🌑🚢", level: "hard" },
  { id: "doctor-zhivago", title: "Doctor Zhivago", emojis: "🚂🌨", level: "hard" },
  { id: "the-metamorphosis", title: "The Metamorphosis", emojis: "🪳🛏", level: "hard" },
  { id: "slaughterhouse-five", title: "Slaughterhouse-Five", emojis: "🛸💣", level: "hard" },
  { id: "catch-22", title: "Catch-22", emojis: "🪂💣", level: "hard" },
  { id: "one-flew-over-the-cuckoos-nest", title: "One Flew Over the Cuckoo's Nest", emojis: "🐦🏥", level: "hard" },
  { id: "the-color-purple", title: "The Color Purple", emojis: "💜✉", level: "hard" },
  { id: "rebecca", title: "Rebecca", emojis: "🏰🔥", level: "hard" },
  { id: "dune", title: "Dune", emojis: "🏜🐛", level: "hard" },
  { id: "the-godfather", title: "The Godfather", emojis: "🤵🐴", level: "hard" },
  { id: "a-tale-of-two-cities", title: "A Tale of Two Cities", emojis: "🏙🗼", level: "hard" },
  { id: "a-farewell-to-arms", title: "A Farewell to Arms", emojis: "💔🎖", level: "hard" },
  { id: "the-bell-jar", title: "The Bell Jar", emojis: "🔔🫙", level: "hard" },
  { id: "beloved", title: "Beloved", emojis: "👶⛓", level: "hard" },
  { id: "the-sun-also-rises", title: "The Sun Also Rises", emojis: "🌅🐂", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "ulysses", title: "Ulysses", emojis: "📚🏙", level: "impossible" },
  { id: "don-quixote", title: "Don Quixote", emojis: "🤺🌬", level: "impossible" },
  { id: "war-and-peace", title: "War and Peace", emojis: "🎖🤝", level: "impossible" },
  { id: "crime-and-punishment", title: "Crime and Punishment", emojis: "🪓⛓", level: "impossible" },
  { id: "the-odyssey", title: "The Odyssey", emojis: "🏛🌊", level: "impossible" },
  { id: "the-brothers-karamazov", title: "The Brothers Karamazov", emojis: "👨🔪", level: "impossible" },
  { id: "anna-karenina", title: "Anna Karenina", emojis: "🚂💔", level: "impossible" },
  { id: "the-divine-comedy", title: "The Divine Comedy", emojis: "🔥👹", level: "impossible" },
  { id: "the-iliad", title: "The Iliad", emojis: "🏹🐴", level: "impossible" },
  { id: "faust", title: "Faust", emojis: "📜😈", level: "impossible" },
  { id: "the-trial", title: "The Trial", emojis: "🏛🔒", level: "impossible" },
  { id: "madame-bovary", title: "Madame Bovary", emojis: "💔💊", level: "impossible" },
  { id: "the-stranger", title: "The Stranger", emojis: "🌞🔫", level: "impossible" },
  { id: "tess-of-the-durbervilles", title: "Tess of the d'Urbervilles", emojis: "🌾💔", level: "impossible" },
  { id: "great-expectations", title: "Great Expectations", emojis: "⛓🎩", level: "impossible" },
  { id: "one-hundred-years-of-solitude", title: "One Hundred Years of Solitude", emojis: "🦋🏘", level: "impossible" },
  { id: "the-sound-and-the-fury", title: "The Sound and the Fury", emojis: "🔔🌀", level: "impossible" },
  { id: "lolita", title: "Lolita", emojis: "🦋🚗", level: "impossible" },
  { id: "the-magic-mountain", title: "The Magic Mountain", emojis: "🏔😷", level: "impossible" },
  { id: "the-name-of-the-rose", title: "The Name of the Rose", emojis: "🔍📕", level: "impossible" },
  { id: "the-idiot", title: "The Idiot", emojis: "🤴🎴", level: "impossible" },
  { id: "the-master-and-margarita", title: "The Master and Margarita", emojis: "😈🐈", level: "impossible" },
  { id: "the-canterbury-tales", title: "The Canterbury Tales", emojis: "🐴📜", level: "impossible" },
  { id: "bleak-house", title: "Bleak House", emojis: "🏛🌫", level: "impossible" },
  { id: "middlemarch", title: "Middlemarch", emojis: "💒🏘", level: "impossible" },
];
