// E122 «Guess the Word by Emoji» (emoji REBUS) — 100 words · 25/tier.
// Each item's clue is a SEQUENCE of Microsoft Fluent 3D emojis (public/emoji3d/<slug>.png) whose
// names phonetically/conceptually combine into `answer`. VO: sfx/ew-<slug>.wav ("It's <answer>!").
// Every rebus is fair and unambiguously solvable. emojis = array of emoji3d slugs (see fetch-fluent3d.mjs).
export const EMOJI_WORD = [
  // ===== EASY (25) — obvious 2-emoji compounds =====
  { slug: "honeymoon", answer: "Honeymoon", emojis: ["honey", "moon"], level: "easy" },
  { slug: "sunflower", answer: "Sunflower", emojis: ["sun", "flower"], level: "easy" },
  { slug: "starfish", answer: "Starfish", emojis: ["star", "fish"], level: "easy" },
  { slug: "rainbow", answer: "Rainbow", emojis: ["rain", "bow"], level: "easy" },
  { slug: "football", answer: "Football", emojis: ["foot", "ball"], level: "easy" },
  { slug: "snowman", answer: "Snowman", emojis: ["snow", "man"], level: "easy" },
  { slug: "butterfly", answer: "Butterfly", emojis: ["butter", "fly"], level: "easy" },
  { slug: "watermelon", answer: "Watermelon", emojis: ["water", "melon"], level: "easy" },
  { slug: "cupcake", answer: "Cupcake", emojis: ["cup", "cake"], level: "easy" },
  { slug: "seahorse", answer: "Seahorse", emojis: ["sea", "horse"], level: "easy" },
  { slug: "seashell", answer: "Seashell", emojis: ["sea", "shell"], level: "easy" },
  { slug: "cowboy", answer: "Cowboy", emojis: ["cow", "boy"], level: "easy" },
  { slug: "raincoat", answer: "Raincoat", emojis: ["rain", "coat"], level: "easy" },
  { slug: "pancake", answer: "Pancake", emojis: ["pan", "cake"], level: "easy" },
  { slug: "snowball", answer: "Snowball", emojis: ["snow", "ball"], level: "easy" },
  { slug: "sunglasses", answer: "Sunglasses", emojis: ["sun", "glasses"], level: "easy" },
  { slug: "catfish", answer: "Catfish", emojis: ["cat", "fish"], level: "easy" },
  { slug: "doghouse", answer: "Doghouse", emojis: ["dog", "house"], level: "easy" },
  { slug: "mailbox", answer: "Mailbox", emojis: ["mail", "box"], level: "easy" },
  { slug: "earring", answer: "Earring", emojis: ["ear", "ring"], level: "easy" },
  { slug: "handbag", answer: "Handbag", emojis: ["hand", "bag"], level: "easy" },
  { slug: "fireman", answer: "Fireman", emojis: ["fire", "man"], level: "easy" },
  { slug: "bookworm", answer: "Bookworm", emojis: ["book", "worm"], level: "easy" },
  { slug: "ladybug", answer: "Ladybug", emojis: ["lady", "bug"], level: "easy" },
  { slug: "eyeball", answer: "Eyeball", emojis: ["eye", "ball"], level: "easy" },

  // ===== MEDIUM (25) =====
  { slug: "eggplant", answer: "Eggplant", emojis: ["egg", "plant"], level: "medium" },
  { slug: "pineapple", answer: "Pineapple", emojis: ["pine", "apple"], level: "medium" },
  { slug: "moonwalk", answer: "Moonwalk", emojis: ["moon", "walk"], level: "medium" },
  { slug: "keyboard", answer: "Keyboard", emojis: ["key", "board"], level: "medium" },
  { slug: "seaweed", answer: "Seaweed", emojis: ["sea", "weed"], level: "medium" },
  { slug: "milkman", answer: "Milkman", emojis: ["milk", "man"], level: "medium" },
  { slug: "toothbrush", answer: "Toothbrush", emojis: ["tooth", "brush"], level: "medium" },
  { slug: "horseshoe", answer: "Horseshoe", emojis: ["horse", "shoe"], level: "medium" },
  { slug: "firefly", answer: "Firefly", emojis: ["fire", "fly"], level: "medium" },
  { slug: "dragonfly", answer: "Dragonfly", emojis: ["dragon", "fly"], level: "medium" },
  { slug: "cheeseburger", answer: "Cheeseburger", emojis: ["cheese", "burger"], level: "medium" },
  { slug: "moonlight", answer: "Moonlight", emojis: ["moon", "light"], level: "medium" },
  { slug: "keyhole", answer: "Keyhole", emojis: ["key", "hole"], level: "medium" },
  { slug: "footprint", answer: "Footprint", emojis: ["foot", "print"], level: "medium" },
  { slug: "cupboard", answer: "Cupboard", emojis: ["cup", "board"], level: "medium" },
  { slug: "fishbowl", answer: "Fishbowl", emojis: ["fish", "bowl"], level: "medium" },
  { slug: "bulldog", answer: "Bulldog", emojis: ["bull", "dog"], level: "medium" },
  { slug: "catwalk", answer: "Catwalk", emojis: ["cat", "walk"], level: "medium" },
  { slug: "doorbell", answer: "Doorbell", emojis: ["door", "bell"], level: "medium" },
  { slug: "mooncake", answer: "Mooncake", emojis: ["moon", "cake"], level: "medium" },
  { slug: "starlight", answer: "Starlight", emojis: ["star", "light"], level: "medium" },
  { slug: "keychain", answer: "Keychain", emojis: ["key", "chain"], level: "medium" },
  { slug: "rainwater", answer: "Rainwater", emojis: ["rain", "water"], level: "medium" },
  { slug: "firewood", answer: "Firewood", emojis: ["fire", "wood"], level: "medium" },
  { slug: "cornbread", answer: "Cornbread", emojis: ["corn", "bread"], level: "medium" },

  // ===== HARD (25) — phonetic / less obvious =====
  { slug: "belief", answer: "Belief", emojis: ["bee", "leaf"], level: "hard" },
  { slug: "carpet", answer: "Carpet", emojis: ["car", "pet"], level: "hard" },
  { slug: "handball", answer: "Handball", emojis: ["hand", "ball"], level: "hard" },
  { slug: "moonshine", answer: "Moonshine", emojis: ["moon", "shine"], level: "hard" },
  { slug: "sunshine", answer: "Sunshine", emojis: ["sun", "shine"], level: "hard" },
  { slug: "earthworm", answer: "Earthworm", emojis: ["earth", "worm"], level: "hard" },
  { slug: "seesaw", answer: "Seesaw", emojis: ["sea", "saw"], level: "hard" },
  { slug: "keynote", answer: "Keynote", emojis: ["key", "note"], level: "hard" },
  { slug: "footnote", answer: "Footnote", emojis: ["foot", "note"], level: "hard" },
  { slug: "milkweed", answer: "Milkweed", emojis: ["milk", "weed"], level: "hard" },
  { slug: "catnap", answer: "Catnap", emojis: ["cat", "nap"], level: "hard" },
  { slug: "dogwood", answer: "Dogwood", emojis: ["dog", "wood"], level: "hard" },
  { slug: "firecracker", answer: "Firecracker", emojis: ["fire", "cracker"], level: "hard" },
  { slug: "rainstorm", answer: "Rainstorm", emojis: ["rain", "storm"], level: "hard" },
  { slug: "seabed", answer: "Seabed", emojis: ["sea", "bed"], level: "hard" },
  { slug: "horsepower", answer: "Horsepower", emojis: ["horse", "power"], level: "hard" },
  { slug: "butterball", answer: "Butterball", emojis: ["butter", "ball"], level: "hard" },
  { slug: "gingerbread", answer: "Gingerbread", emojis: ["ginger", "bread"], level: "hard" },
  { slug: "moonstone", answer: "Moonstone", emojis: ["moon", "stone"], level: "hard" },
  { slug: "firebird", answer: "Firebird", emojis: ["fire", "bird"], level: "hard" },
  { slug: "seahawk", answer: "Seahawk", emojis: ["sea", "hawk"], level: "hard" },
  { slug: "eyebrow", answer: "Eyebrow", emojis: ["eye", "bow"], level: "hard" },
  { slug: "buttercup", answer: "Buttercup", emojis: ["butter", "cup"], level: "hard" },
  { slug: "horsefly", answer: "Horsefly", emojis: ["horse", "fly"], level: "hard" },
  { slug: "ladybird", answer: "Ladybird", emojis: ["lady", "bird"], level: "hard" },

  // ===== IMPOSSIBLE (25) — hardest phonetic / 3-emoji / abstract =====
  { slug: "carpool", answer: "Carpool", emojis: ["car", "pool"], level: "impossible" },
  { slug: "hamburger", answer: "Hamburger", emojis: ["ham", "burger"], level: "impossible" },
  { slug: "wheelchair", answer: "Wheelchair", emojis: ["wheel", "chair"], level: "impossible" },
  { slug: "crossbow", answer: "Crossbow", emojis: ["cross", "bow"], level: "impossible" },
  { slug: "keystone", answer: "Keystone", emojis: ["key", "stone"], level: "impossible" },
  { slug: "sweetheart", answer: "Sweetheart", emojis: ["sweet", "heart"], level: "impossible" },
  { slug: "brainstorm", answer: "Brainstorm", emojis: ["brain", "storm"], level: "impossible" },
  { slug: "nightmare", answer: "Nightmare", emojis: ["night", "horse"], level: "impossible" },
  { slug: "penknife", answer: "Penknife", emojis: ["pen", "knife"], level: "impossible" },
  { slug: "snowmobile", answer: "Snowmobile", emojis: ["snow", "mobile"], level: "impossible" },
  { slug: "eardrum", answer: "Eardrum", emojis: ["ear", "drum"], level: "impossible" },
  { slug: "handprint", answer: "Handprint", emojis: ["hand", "print"], level: "impossible" },
  { slug: "cardboard", answer: "Cardboard", emojis: ["card", "board"], level: "impossible" },
  { slug: "teaspoon", answer: "Teaspoon", emojis: ["tea", "spoon"], level: "impossible" },
  { slug: "spearfish", answer: "Spearfish", emojis: ["spear", "fish"], level: "impossible" },
  { slug: "paintbrush", answer: "Paintbrush", emojis: ["paint", "brush"], level: "impossible" },
  { slug: "handbook", answer: "Handbook", emojis: ["hand", "book"], level: "impossible" },
  { slug: "notebook", answer: "Notebook", emojis: ["note", "book"], level: "impossible" },
  { slug: "cakewalk", answer: "Cakewalk", emojis: ["cake", "walk"], level: "impossible" },
  { slug: "boardwalk", answer: "Boardwalk", emojis: ["board", "walk"], level: "impossible" },
  { slug: "watchdog", answer: "Watchdog", emojis: ["watch", "dog"], level: "impossible" },
  { slug: "starboard", answer: "Starboard", emojis: ["star", "board"], level: "impossible" },
  { slug: "birdhouse", answer: "Birdhouse", emojis: ["bird", "house"], level: "impossible" },
  { slug: "lighthouse", answer: "Lighthouse", emojis: ["light", "house"], level: "impossible" },
  { slug: "hamstring", answer: "Hamstring", emojis: ["ham", "string"], level: "impossible" },
];
