// E33 «Guess the Country by Emoji v2» — 100 NEW countries · 25/tier · clue via OpenMoji · VO: sfx/ce-<id>.wav
// 100% distinct from E32 (emojiCountriesData.js). Clues hint the COUNTRY via landmarks/animals/food/symbols — never its flag.
// No Israeli flag / Israel-specific emojis. Single-emoji glyphs only (no ZWJ sequences), mirroring E32.
export const EMOJI_COUNTRIES2 = [
  // ===== EASY (25) =====
  { id: "pakistan", title: "Pakistan", emojis: "🏏🕌", level: "easy" },
  { id: "venezuela", title: "Venezuela", emojis: "👑🛢", level: "easy" },
  { id: "estonia", title: "Estonia", emojis: "💻🏰", level: "easy" },
  { id: "lithuania", title: "Lithuania", emojis: "🏀🌲", level: "easy" },
  { id: "latvia", title: "Latvia", emojis: "🌲🏒", level: "easy" },
  { id: "slovakia", title: "Slovakia", emojis: "⛰🏒", level: "easy" },
  { id: "slovenia", title: "Slovenia", emojis: "🐉⛰", level: "easy" },
  { id: "serbia", title: "Serbia", emojis: "🎾🍑", level: "easy" },
  { id: "ecuador", title: "Ecuador", emojis: "🐢🌋", level: "easy" },
  { id: "guatemala", title: "Guatemala", emojis: "🌋🫓", level: "easy" },
  { id: "honduras", title: "Honduras", emojis: "🍌🌴", level: "easy" },
  { id: "monaco", title: "Monaco", emojis: "🏎🎰", level: "easy" },
  { id: "luxembourg", title: "Luxembourg", emojis: "🏰🏦", level: "easy" },
  { id: "maldives", title: "Maldives", emojis: "🏝🤿", level: "easy" },
  { id: "myanmar", title: "Myanmar", emojis: "🛕🐘", level: "easy" },
  { id: "uganda", title: "Uganda", emojis: "🦍🌍", level: "easy" },
  { id: "belarus", title: "Belarus", emojis: "🥔🌾", level: "easy" },
  { id: "taiwan", title: "Taiwan", emojis: "💻🧋", level: "easy" },
  { id: "cameroon", title: "Cameroon", emojis: "⚽🦁", level: "easy" },
  { id: "libya", title: "Libya", emojis: "🏜🛢", level: "easy" },
  { id: "sudan", title: "Sudan", emojis: "🏜🐫", level: "easy" },
  { id: "haiti", title: "Haiti", emojis: "🥁🌴", level: "easy" },
  { id: "dominican-republic", title: "Dominican Republic", emojis: "🏖⚾", level: "easy" },
  { id: "bulgaria", title: "Bulgaria", emojis: "🌹💃", level: "easy" },
  { id: "bahamas", title: "Bahamas", emojis: "🏝🐷", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "albania", title: "Albania", emojis: "🦅⛰", level: "medium" },
  { id: "algeria", title: "Algeria", emojis: "🐪🕌", level: "medium" },
  { id: "angola", title: "Angola", emojis: "💎🛢", level: "medium" },
  { id: "mozambique", title: "Mozambique", emojis: "🦐🌊", level: "medium" },
  { id: "namibia", title: "Namibia", emojis: "🏜🦏", level: "medium" },
  { id: "botswana", title: "Botswana", emojis: "🐘💎", level: "medium" },
  { id: "zimbabwe", title: "Zimbabwe", emojis: "🏛🐘", level: "medium" },
  { id: "north-korea", title: "North Korea", emojis: "🚀⛰", level: "medium" },
  { id: "syria", title: "Syria", emojis: "🏛🕌", level: "medium" },
  { id: "yemen", title: "Yemen", emojis: "☕🏜", level: "medium" },
  { id: "bahrain", title: "Bahrain", emojis: "🏝🛢", level: "medium" },
  { id: "nicaragua", title: "Nicaragua", emojis: "🌋🦜", level: "medium" },
  { id: "el-salvador", title: "El Salvador", emojis: "🌋🏄", level: "medium" },
  { id: "rwanda", title: "Rwanda", emojis: "🦍⛰", level: "medium" },
  { id: "mali", title: "Mali", emojis: "🏜🎶", level: "medium" },
  { id: "niger", title: "Niger", emojis: "🏜🦒", level: "medium" },
  { id: "mauritius", title: "Mauritius", emojis: "🏝🦤", level: "medium" },
  { id: "montenegro", title: "Montenegro", emojis: "🏔🌊", level: "medium" },
  { id: "north-macedonia", title: "North Macedonia", emojis: "🏛☀", level: "medium" },
  { id: "papua-new-guinea", title: "Papua New Guinea", emojis: "🦜🌋", level: "medium" },
  { id: "tajikistan", title: "Tajikistan", emojis: "🏔🐐", level: "medium" },
  { id: "turkmenistan", title: "Turkmenistan", emojis: "🔥🐎", level: "medium" },
  { id: "samoa", title: "Samoa", emojis: "🌺🏝", level: "medium" },
  { id: "tonga", title: "Tonga", emojis: "🐋🏝", level: "medium" },
  { id: "bosnia-and-herzegovina", title: "Bosnia and Herzegovina", emojis: "🌉⛰", level: "medium" },

  // ===== HARD (25) =====
  { id: "benin", title: "Benin", emojis: "🐍🥁", level: "hard" },
  { id: "togo", title: "Togo", emojis: "🌴🥁", level: "hard" },
  { id: "burkina-faso", title: "Burkina Faso", emojis: "🏍🏜", level: "hard" },
  { id: "guinea", title: "Guinea", emojis: "⛏🌴", level: "hard" },
  { id: "sierra-leone", title: "Sierra Leone", emojis: "💎🦁", level: "hard" },
  { id: "liberia", title: "Liberia", emojis: "⚓🌴", level: "hard" },
  { id: "gambia", title: "Gambia", emojis: "🐊🌍", level: "hard" },
  { id: "eritrea", title: "Eritrea", emojis: "⚓🏜", level: "hard" },
  { id: "malawi", title: "Malawi", emojis: "🐟🌊", level: "hard" },
  { id: "burundi", title: "Burundi", emojis: "🥁🌍", level: "hard" },
  { id: "equatorial-guinea", title: "Equatorial Guinea", emojis: "🛢🌴", level: "hard" },
  { id: "central-african-republic", title: "Central African Republic", emojis: "💎🌳", level: "hard" },
  { id: "congo-republic", title: "Republic of Congo", emojis: "🦍🌴", level: "hard" },
  { id: "dr-congo", title: "DR Congo", emojis: "🌋🦍", level: "hard" },
  { id: "ivory-coast", title: "Ivory Coast", emojis: "🐘🍫", level: "hard" },
  { id: "guinea-bissau", title: "Guinea-Bissau", emojis: "🌴🥜", level: "hard" },
  { id: "cape-verde", title: "Cape Verde", emojis: "🏝🎶", level: "hard" },
  { id: "barbados", title: "Barbados", emojis: "🏝🥁", level: "hard" },
  { id: "trinidad-and-tobago", title: "Trinidad and Tobago", emojis: "🥁🎉", level: "hard" },
  { id: "grenada", title: "Grenada", emojis: "🌶🏝", level: "hard" },
  { id: "guyana", title: "Guyana", emojis: "💦🌴", level: "hard" },
  { id: "dominica", title: "Dominica", emojis: "🌿🦜", level: "hard" },
  { id: "saint-lucia", title: "Saint Lucia", emojis: "🏔🏝", level: "hard" },
  { id: "gabon", title: "Gabon", emojis: "🦍🌳", level: "hard" },
  { id: "mauritania", title: "Mauritania", emojis: "🏜⚓", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "andorra", title: "Andorra", emojis: "🏔🎿", level: "impossible" },
  { id: "liechtenstein", title: "Liechtenstein", emojis: "🏔🏰", level: "impossible" },
  { id: "vatican-city", title: "Vatican City", emojis: "⛪🙏", level: "impossible" },
  { id: "kosovo", title: "Kosovo", emojis: "🏔🕌", level: "impossible" },
  { id: "palestine", title: "Palestine", emojis: "🕊🫒", level: "impossible" },
  { id: "cook-islands", title: "Cook Islands", emojis: "🏝🌺", level: "impossible" },
  { id: "hong-kong", title: "Hong Kong", emojis: "🏙🥟", level: "impossible" },
  { id: "puerto-rico", title: "Puerto Rico", emojis: "🏝🎤", level: "impossible" },
  { id: "kiribati", title: "Kiribati", emojis: "🌊📆", level: "impossible" },
  { id: "nauru", title: "Nauru", emojis: "🪨🌊", level: "impossible" },
  { id: "palau", title: "Palau", emojis: "🪼🌊", level: "impossible" },
  { id: "micronesia", title: "Micronesia", emojis: "🗿🌴", level: "impossible" },
  { id: "marshall-islands", title: "Marshall Islands", emojis: "⚛🌊", level: "impossible" },
  { id: "solomon-islands", title: "Solomon Islands", emojis: "🐚🌴", level: "impossible" },
  { id: "antigua-and-barbuda", title: "Antigua and Barbuda", emojis: "⛵🏖", level: "impossible" },
  { id: "saint-kitts-and-nevis", title: "Saint Kitts and Nevis", emojis: "🚂🌴", level: "impossible" },
  { id: "saint-vincent", title: "Saint Vincent", emojis: "🌋🏝", level: "impossible" },
  { id: "seychelles", title: "Seychelles", emojis: "🐢🏝", level: "impossible" },
  { id: "timor-leste", title: "Timor-Leste", emojis: "☕🏝", level: "impossible" },
  { id: "greenland", title: "Greenland", emojis: "🧊🐋", level: "impossible" },
  { id: "afghanistan", title: "Afghanistan", emojis: "🏔🕌", level: "impossible" },
  { id: "chad", title: "Chad", emojis: "🌊🏜", level: "impossible" },
  { id: "somalia", title: "Somalia", emojis: "🐐🌊", level: "impossible" },
  { id: "south-sudan", title: "South Sudan", emojis: "🐘🌾", level: "impossible" },
  { id: "sao-tome", title: "Sao Tome and Principe", emojis: "🍫🏝", level: "impossible" },
];
