// E37 emoji-book facts — one verified ≤70-char fact per book, shown on reveal.
export const EMOJI_BOOK_FACTS = {
  // EASY
  "harry-potter": "J.K. Rowling's wizard series began in 1997.",
  "the-bible": "The world's best-selling book, written over many centuries.",
  "romeo-and-juliet": "Shakespeare's tragedy of star-crossed lovers, c.1595.",
  "dracula": "Bram Stoker's 1897 vampire novel set partly in Transylvania.",
  "alice-in-wonderland": "Lewis Carroll's 1865 tale of a girl down a rabbit hole.",
  "the-little-prince": "Antoine de Saint-Exupéry's 1943 illustrated fable.",
  "charlottes-web": "E.B. White's 1952 tale of a pig and a clever spider.",
  "frankenstein": "Mary Shelley's 1818 novel about a man-made creature.",
  "peter-pan": "J.M. Barrie's 1911 story of the boy who never grows up.",
  "moby-dick": "Herman Melville's 1851 hunt for a great white whale.",
  "the-hobbit": "J.R.R. Tolkien's 1937 tale of Bilbo and a dragon's gold.",
  "pinocchio": "Carlo Collodi's 1883 tale of a wooden puppet who lies.",
  "cinderella": "A fairy tale popularized by Charles Perrault in 1697.",
  "winnie-the-pooh": "A.A. Milne's 1926 stories of a honey-loving bear.",
  "the-cat-in-the-hat": "Dr. Seuss's 1957 rhyming children's classic.",
  "treasure-island": "Robert Louis Stevenson's 1883 pirate adventure.",
  "the-jungle-book": "Rudyard Kipling's 1894 tales of Mowgli in the wild.",
  "snow-white": "A Brothers Grimm fairy tale published in 1812.",
  "the-wizard-of-oz": "L. Frank Baum's 1900 tale of a girl in a magic land.",
  "the-very-hungry-caterpillar": "Eric Carle's 1969 picture book classic.",
  "matilda": "Roald Dahl's 1988 tale of a gifted, book-loving girl.",
  "the-old-man-and-the-sea": "Hemingway's 1952 novel of a fisherman's marlin.",
  "the-three-musketeers": "Alexandre Dumas's 1844 swashbuckling adventure.",
  "the-call-of-the-wild": "Jack London's 1903 tale of a dog in the Yukon.",
  "twenty-thousand-leagues": "Jules Verne's 1870 undersea voyage on the Nautilus.",

  // MEDIUM
  "the-lord-of-the-rings": "Tolkien's epic; the One Ring must burn in Mount Doom.",
  "pride-and-prejudice": "Jane Austen's 1813 romance of Elizabeth and Darcy.",
  "the-great-gatsby": "F. Scott Fitzgerald's 1925 Jazz Age tragedy.",
  "nineteen-eighty-four": "George Orwell's 1949 novel of Big Brother's watch.",
  "animal-farm": "Orwell's 1945 fable of farm animals who revolt.",
  "the-count-of-monte-cristo": "Dumas's 1844 tale of imprisonment and revenge.",
  "a-christmas-carol": "Dickens's 1843 tale of Scrooge and three ghosts.",
  "gone-with-the-wind": "Margaret Mitchell's 1936 US Civil War epic.",
  "the-hunchback-of-notre-dame": "Victor Hugo's 1831 novel set at the cathedral.",
  "the-picture-of-dorian-gray": "Oscar Wilde's 1890 novel of a portrait that ages.",
  "dr-jekyll-and-mr-hyde": "Stevenson's 1886 tale of a split personality.",
  "the-time-machine": "H.G. Wells's 1895 novel of travel to the far future.",
  "the-war-of-the-worlds": "H.G. Wells's 1898 tale of a Martian invasion.",
  "around-the-world-in-eighty-days": "Jules Verne's 1873 race around the globe.",
  "the-secret-garden": "F.H. Burnett's 1911 tale of a hidden walled garden.",
  "black-beauty": "Anna Sewell's 1877 story told by a horse.",
  "the-wind-in-the-willows": "Kenneth Grahame's 1908 tale of Toad and friends.",
  "les-miserables": "Victor Hugo's 1862 epic of Jean Valjean in France.",
  "oliver-twist": "Dickens's 1838 tale of an orphan in London's slums.",
  "huckleberry-finn": "Mark Twain's 1884 raft journey down the Mississippi.",
  "sherlock-holmes": "Arthur Conan Doyle's 1892 detective story collection.",
  "gullivers-travels": "Jonathan Swift's 1726 satire of fantastic voyages.",
  "robinson-crusoe": "Daniel Defoe's 1719 tale of a castaway on an island.",
  "journey-to-the-center-of-the-earth": "Jules Verne's 1864 underground adventure.",
  "the-legend-of-sleepy-hollow": "Washington Irving's 1820 Headless Horseman tale.",

  // HARD
  "to-kill-a-mockingbird": "Harper Lee's 1960 novel of racial injustice in the US.",
  "the-catcher-in-the-rye": "J.D. Salinger's 1951 novel of teenage Holden Caulfield.",
  "lord-of-the-flies": "William Golding's 1954 tale of boys stranded on an isle.",
  "of-mice-and-men": "John Steinbeck's 1937 novel of two migrant workers.",
  "brave-new-world": "Aldous Huxley's 1932 dystopia of engineered people.",
  "fahrenheit-451": "Ray Bradbury's 1953 novel where books are burned.",
  "the-grapes-of-wrath": "Steinbeck's 1939 novel of the Dust Bowl migration.",
  "jane-eyre": "Charlotte Brontë's 1847 novel of a governess in love.",
  "wuthering-heights": "Emily Brontë's 1847 tale of Heathcliff on the moors.",
  "the-scarlet-letter": "Hawthorne's 1850 novel of a woman shamed with an 'A'.",
  "heart-of-darkness": "Joseph Conrad's 1899 voyage up the Congo River.",
  "doctor-zhivago": "Boris Pasternak's 1957 love story amid revolution.",
  "the-metamorphosis": "Franz Kafka's 1915 tale of a man turned into an insect.",
  "slaughterhouse-five": "Kurt Vonnegut's 1969 anti-war novel with time jumps.",
  "catch-22": "Joseph Heller's 1961 satire of WWII bomber crews.",
  "one-flew-over-the-cuckoos-nest": "Ken Kesey's 1962 novel set in a mental ward.",
  "the-color-purple": "Alice Walker's 1982 novel told through letters.",
  "rebecca": "Daphne du Maurier's 1938 novel haunted by a first wife.",
  "dune": "Frank Herbert's 1965 sci-fi epic on a desert planet.",
  "the-godfather": "Mario Puzo's 1969 novel of a mafia crime family.",
  "a-tale-of-two-cities": "Dickens's 1859 novel of London and Paris in revolt.",
  "a-farewell-to-arms": "Hemingway's 1929 love story set in World War I.",
  "the-bell-jar": "Sylvia Plath's 1963 novel of a young woman's descent.",
  "beloved": "Toni Morrison's 1987 novel of slavery's haunting legacy.",
  "the-sun-also-rises": "Hemingway's 1926 novel of the Lost Generation.",

  // IMPOSSIBLE
  "ulysses": "James Joyce's 1922 novel of one day in Dublin.",
  "don-quixote": "Cervantes's 1605 tale of a knight tilting at windmills.",
  "war-and-peace": "Leo Tolstoy's 1869 epic of Russia in the Napoleonic era.",
  "crime-and-punishment": "Dostoevsky's 1866 novel of a murderer's guilt.",
  "the-odyssey": "Homer's ancient epic of Odysseus's long voyage home.",
  "the-brothers-karamazov": "Dostoevsky's 1880 novel of a father's murder.",
  "anna-karenina": "Tolstoy's 1877 tragedy of a woman's doomed affair.",
  "the-divine-comedy": "Dante's c.1320 poem journeying through the afterlife.",
  "the-iliad": "Homer's ancient epic of the Trojan War's final year.",
  "faust": "Goethe's drama of a scholar's pact with the devil, 1808.",
  "the-trial": "Kafka's 1925 novel of a man arrested for no known crime.",
  "madame-bovary": "Flaubert's 1857 novel of a doctor's restless wife.",
  "the-stranger": "Albert Camus's 1942 novel of an indifferent killer.",
  "tess-of-the-durbervilles": "Thomas Hardy's 1891 tragedy of a wronged woman.",
  "great-expectations": "Dickens's 1861 novel of the orphan Pip's rise.",
  "one-hundred-years-of-solitude": "García Márquez's 1967 Macondo family saga.",
  "the-sound-and-the-fury": "Faulkner's 1929 novel of a fading Southern family.",
  "lolita": "Vladimir Nabokov's controversial 1955 novel.",
  "the-magic-mountain": "Thomas Mann's 1924 novel set in an Alpine sanatorium.",
  "the-name-of-the-rose": "Umberto Eco's 1980 murder mystery in an abbey.",
  "the-idiot": "Dostoevsky's 1869 novel of a kind-hearted prince.",
  "the-master-and-margarita": "Bulgakov's novel of the devil in Soviet Moscow.",
  "the-canterbury-tales": "Chaucer's c.1387 tales told by pilgrims.",
  "bleak-house": "Dickens's 1853 novel of an endless court case.",
  "middlemarch": "George Eliot's 1871 novel of English provincial life.",
};
