// E138 «Guess the Fairy Tale by Emoji» — 100 public-domain fairy/folk tales · 25/tier
// clue = plain single-codepoint Unicode emoji (mirrors emoji rendering; every glyph exists at public/openmoji/<HEX>.svg)
// FAIRNESS: every emoji pair fairly points to its tale for a person who knows it. No color-blob filler. No duplicate emoji sets.
// VO: public/sfx/e138-<id>.wav — "It's <Tale>!"
export const FAIRYTALE_EMOJI = [
  // ===== EASY (25) — globally known =====
  { id: "cinderella", title: "Cinderella", emojis: "👠🎃", level: "easy" },
  { id: "little-red-riding-hood", title: "Little Red Riding Hood", emojis: "👧🐺", level: "easy" },
  { id: "snow-white", title: "Snow White", emojis: "🍎👸", level: "easy" },
  { id: "hansel-and-gretel", title: "Hansel and Gretel", emojis: "🍬🏠", level: "easy" },
  { id: "the-three-little-pigs", title: "The Three Little Pigs", emojis: "🐷🏠", level: "easy" },
  { id: "goldilocks-and-the-three-bears", title: "Goldilocks and the Three Bears", emojis: "👧🐻", level: "easy" },
  { id: "jack-and-the-beanstalk", title: "Jack and the Beanstalk", emojis: "🌱☁", level: "easy" },
  { id: "the-ugly-duckling", title: "The Ugly Duckling", emojis: "🦆🦢", level: "easy" },
  { id: "the-little-mermaid", title: "The Little Mermaid", emojis: "🧜🌊", level: "easy" },
  { id: "the-frog-prince", title: "The Frog Prince", emojis: "🐸👑", level: "easy" },
  { id: "sleeping-beauty", title: "Sleeping Beauty", emojis: "👸😴", level: "easy" },
  { id: "rapunzel", title: "Rapunzel", emojis: "👸💇", level: "easy" },
  { id: "beauty-and-the-beast", title: "Beauty and the Beast", emojis: "🌹👹", level: "easy" },
  { id: "rumpelstiltskin", title: "Rumpelstiltskin", emojis: "🌾👑", level: "easy" },
  { id: "pinocchio", title: "Pinocchio", emojis: "🪵👃", level: "easy" },
  { id: "the-gingerbread-man", title: "The Gingerbread Man", emojis: "🍪🏃", level: "easy" },
  { id: "puss-in-boots", title: "Puss in Boots", emojis: "🐱👢", level: "easy" },
  { id: "thumbelina", title: "Thumbelina", emojis: "👧🌷", level: "easy" },
  { id: "the-emperors-new-clothes", title: "The Emperor's New Clothes", emojis: "👑🧵", level: "easy" },
  { id: "the-princess-and-the-pea", title: "The Princess and the Pea", emojis: "👸🛏", level: "easy" },
  { id: "the-tortoise-and-the-hare", title: "The Tortoise and the Hare", emojis: "🐢🐇", level: "easy" },
  { id: "the-boy-who-cried-wolf", title: "The Boy Who Cried Wolf", emojis: "👦🐺", level: "easy" },
  { id: "the-lion-and-the-mouse", title: "The Lion and the Mouse", emojis: "🦁🐭", level: "easy" },
  { id: "the-ant-and-the-grasshopper", title: "The Ant and the Grasshopper", emojis: "🐜🦗", level: "easy" },
  { id: "the-steadfast-tin-soldier", title: "The Steadfast Tin Soldier", emojis: "🪖❤", level: "easy" },

  // ===== MEDIUM (25) — well known =====
  { id: "the-pied-piper-of-hamelin", title: "The Pied Piper of Hamelin", emojis: "🎶🐀", level: "medium" },
  { id: "the-elves-and-the-shoemaker", title: "The Elves and the Shoemaker", emojis: "🧝👞", level: "medium" },
  { id: "the-twelve-dancing-princesses", title: "The Twelve Dancing Princesses", emojis: "👑💃", level: "medium" },
  { id: "the-snow-queen", title: "The Snow Queen", emojis: "❄👸", level: "medium" },
  { id: "the-little-match-girl", title: "The Little Match Girl", emojis: "🔥🧣", level: "medium" },
  { id: "the-nutcracker", title: "The Nutcracker", emojis: "🥜🩰", level: "medium" },
  { id: "the-goose-that-laid-the-golden-eggs", title: "The Goose That Laid the Golden Eggs", emojis: "🪿🥚", level: "medium" },
  { id: "bluebeard", title: "Bluebeard", emojis: "🧔🔑", level: "medium" },
  { id: "aladdin", title: "Aladdin", emojis: "🪔🧞", level: "medium" },
  { id: "ali-baba-and-the-forty-thieves", title: "Ali Baba and the Forty Thieves", emojis: "🏺💰", level: "medium" },
  { id: "sindbad-the-sailor", title: "Sindbad the Sailor", emojis: "⛵🧭", level: "medium" },
  { id: "the-snow-maiden", title: "The Snow Maiden", emojis: "⛄👧", level: "medium" },
  { id: "the-firebird", title: "The Firebird", emojis: "🔥🐦", level: "medium" },
  { id: "baba-yaga", title: "Baba Yaga", emojis: "🧙🏚", level: "medium" },
  { id: "the-bremen-town-musicians", title: "The Bremen Town Musicians", emojis: "🐴🐓", level: "medium" },
  { id: "the-wolf-and-the-seven-young-kids", title: "The Wolf and the Seven Young Kids", emojis: "🐺🐐", level: "medium" },
  { id: "brer-rabbit", title: "Brer Rabbit", emojis: "🐰🌿", level: "medium" },
  { id: "the-fisherman-and-his-wife", title: "The Fisherman and His Wife", emojis: "🎣🐟", level: "medium" },
  { id: "the-six-swans", title: "The Six Swans", emojis: "🦢🧵", level: "medium" },
  { id: "the-nightingale", title: "The Nightingale", emojis: "🐦👑", level: "medium" },
  { id: "chicken-little", title: "Chicken Little", emojis: "🐔🌰", level: "medium" },
  { id: "the-little-red-hen", title: "The Little Red Hen", emojis: "🐔🌾", level: "medium" },
  { id: "stone-soup", title: "Stone Soup", emojis: "🪨🍲", level: "medium" },
  { id: "the-town-mouse-and-the-country-mouse", title: "The Town Mouse and the Country Mouse", emojis: "🐭🏙", level: "medium" },
  { id: "the-fox-and-the-grapes", title: "The Fox and the Grapes", emojis: "🦊🍇", level: "medium" },

  // ===== HARD (25) — lesser-known but gettable =====
  { id: "the-twelve-months", title: "The Twelve Months", emojis: "🗓❄", level: "hard" },
  { id: "east-of-the-sun-and-west-of-the-moon", title: "East of the Sun and West of the Moon", emojis: "🐻🌙", level: "hard" },
  { id: "the-wild-swans", title: "The Wild Swans", emojis: "🦢👑", level: "hard" },
  { id: "vasilisa-the-beautiful", title: "Vasilisa the Beautiful", emojis: "👧🔥", level: "hard" },
  { id: "the-golden-bird", title: "The Golden Bird", emojis: "🐦🌟", level: "hard" },
  { id: "snow-white-and-rose-red", title: "Snow-White and Rose-Red", emojis: "🌹🐻", level: "hard" },
  { id: "king-thrushbeard", title: "King Thrushbeard", emojis: "👑🎻", level: "hard" },
  { id: "mother-holle", title: "Mother Holle", emojis: "🪶❄", level: "hard" },
  { id: "the-golden-key", title: "The Golden Key", emojis: "🗝📦", level: "hard" },
  { id: "the-juniper-tree", title: "The Juniper Tree", emojis: "🌳🐦", level: "hard" },
  { id: "the-water-of-life", title: "The Water of Life", emojis: "💧🏰", level: "hard" },
  { id: "iron-john", title: "Iron John", emojis: "🧔🌲", level: "hard" },
  { id: "godfather-death", title: "Godfather Death", emojis: "💀🕯", level: "hard" },
  { id: "the-star-money", title: "The Star Money", emojis: "⭐💰", level: "hard" },
  { id: "brother-and-sister", title: "Brother and Sister", emojis: "🦌👧", level: "hard" },
  { id: "the-goose-girl", title: "The Goose Girl", emojis: "🪿👸", level: "hard" },
  { id: "molly-whuppie", title: "Molly Whuppie", emojis: "👧👹", level: "hard" },
  { id: "the-three-billy-goats-gruff", title: "The Three Billy Goats Gruff", emojis: "🐐🌉", level: "hard" },
  { id: "the-magic-porridge-pot", title: "The Magic Porridge Pot", emojis: "🍲✨", level: "hard" },
  { id: "tom-thumb", title: "Tom Thumb", emojis: "👦👍", level: "hard" },
  { id: "the-brave-little-tailor", title: "The Brave Little Tailor", emojis: "✂🪰", level: "hard" },
  { id: "the-fisherman-and-the-jinni", title: "The Fisherman and the Jinni", emojis: "🏺🧞", level: "hard" },
  { id: "the-ebony-horse", title: "The Ebony Horse", emojis: "🐴🌙", level: "hard" },
  { id: "the-little-humpbacked-horse", title: "The Little Humpbacked Horse", emojis: "🐎🌟", level: "hard" },
  { id: "koschei-the-deathless", title: "Koschei the Deathless", emojis: "💀🥚", level: "hard" },

  // ===== IMPOSSIBLE (25) — real but obscure; still gettable by a knower =====
  { id: "the-nix-of-the-mill-pond", title: "The Nix of the Mill-Pond", emojis: "🧜💧", level: "impossible" },
  { id: "fitchers-bird", title: "Fitcher's Bird", emojis: "🧙🐦", level: "impossible" },
  { id: "the-twelve-brothers", title: "The Twelve Brothers", emojis: "👑🌸", level: "impossible" },
  { id: "jorinde-and-joringel", title: "Jorinde and Joringel", emojis: "🌸🐦", level: "impossible" },
  { id: "the-singing-bone", title: "The Singing Bone", emojis: "🎵🦴", level: "impossible" },
  { id: "all-kinds-of-fur", title: "All-Kinds-of-Fur", emojis: "🧥👑", level: "impossible" },
  { id: "the-golden-goose", title: "The Golden Goose", emojis: "🪿✨", level: "impossible" },
  { id: "bearskin", title: "Bearskin", emojis: "🐻🧥", level: "impossible" },
  { id: "the-devil-with-the-three-golden-hairs", title: "The Devil with the Three Golden Hairs", emojis: "😈💇", level: "impossible" },
  { id: "the-riddle", title: "The Riddle", emojis: "🧩💍", level: "impossible" },
  { id: "sweetheart-roland", title: "Sweetheart Roland", emojis: "🪄🌹", level: "impossible" },
  { id: "the-three-spinners", title: "The Three Spinners", emojis: "🧵🕸", level: "impossible" },
  { id: "the-white-snake", title: "The White Snake", emojis: "🐍👑", level: "impossible" },
  { id: "ferdinand-the-faithful", title: "Ferdinand the Faithful", emojis: "🐴🐟", level: "impossible" },
  { id: "the-drummer", title: "The Drummer", emojis: "🥁⛰", level: "impossible" },
  { id: "maid-maleen", title: "Maid Maleen", emojis: "👰🧱", level: "impossible" },
  { id: "the-two-brothers", title: "The Two Brothers", emojis: "🐉👬", level: "impossible" },
  { id: "the-crystal-ball", title: "The Crystal Ball", emojis: "🔮🏰", level: "impossible" },
  { id: "cap-o-rushes", title: "Cap o' Rushes", emojis: "🌾👗", level: "impossible" },
  { id: "the-black-bull-of-norroway", title: "The Black Bull of Norroway", emojis: "🐂🌙", level: "impossible" },
  { id: "tam-lin", title: "Tam Lin", emojis: "🌹🐴", level: "impossible" },
  { id: "dick-whittington-and-his-cat", title: "Dick Whittington and His Cat", emojis: "🐱🔔", level: "impossible" },
  { id: "the-fish-and-the-ring", title: "The Fish and the Ring", emojis: "🐟💍", level: "impossible" },
  { id: "kate-crackernuts", title: "Kate Crackernuts", emojis: "🥜👑", level: "impossible" },
  { id: "the-master-maid", title: "The Master Maid", emojis: "🗝🌲", level: "impossible" },
];
