// E69 Fast-Food Logo facts — one verified TRUE fact per brand (≤70 chars): founding year / country / origin.
export const FASTFOOD_FACTS = {
  // ===== EASY =====
  "mcdonalds": "US burger giant; started 1940 in San Bernardino, California.",
  "kfc": "Fried chicken chain founded 1952 by Colonel Sanders.",
  "burgerking": "US burger chain founded 1954 in Miami, Florida.",
  "subway": "US sandwich chain founded 1965 in Connecticut.",
  "starbucks": "Coffee giant founded 1971 in Seattle, Washington.",
  "pizzahut": "US pizza chain founded 1958 in Wichita, Kansas.",
  "dominos": "US pizza chain founded 1960 in Michigan.",
  "dunkin": "US coffee & donut chain founded 1950 in Massachusetts.",
  "wendys": "US burger chain founded 1969 by Dave Thomas in Ohio.",
  "tacobell": "US Tex-Mex chain founded 1962 in California.",
  "dairyqueen": "US soft-serve chain founded 1940 in Illinois.",
  "papajohns": "US pizza chain founded 1984 in Jeffersonville, Indiana.",
  "baskinrobbins": "Ice cream chain founded 1945; famed for 31 flavors.",
  "littlecaesars": "US pizza chain founded 1959 in Michigan.",
  "cinnabon": "Cinnamon-roll chain founded 1985 in Seattle.",
  "hardees": "US burger chain founded 1960 in North Carolina.",
  "carlsjr": "US burger chain founded 1941 in California.",
  "sonic": "US drive-in chain founded 1953 in Oklahoma.",
  "chilis": "US Tex-Mex grill founded 1975 in Dallas, Texas.",
  "dennys": "US diner chain founded 1953 in California.",
  "ihop": "US pancake-house chain founded 1958 in California.",
  "pandaexpress": "US Chinese-food chain founded 1983 in California.",
  "wimpy": "Burger chain born 1934 in the US, now big in the UK.",
  "tgifridays": "US bar & grill founded 1965 in New York City.",
  "hooters": "US wings chain founded 1983 in Clearwater, Florida.",
  // ===== MEDIUM =====
  "chipotle": "US burrito chain founded 1993 in Denver, Colorado.",
  "fiveguys": "US burger chain founded 1986 in Arlington, Virginia.",
  "popeyes": "Louisiana fried-chicken chain founded 1972.",
  "nandos": "Peri-peri chicken chain founded 1987 in South Africa.",
  "krispykreme": "US doughnut chain founded 1937 in North Carolina.",
  "timhortons": "Canadian coffee chain founded 1964 in Ontario.",
  "costa": "UK coffee chain founded 1971 in London.",
  "jollibee": "Filipino fast-food giant founded 1978 in Manila.",
  "shakeshack": "US burger chain founded 2004 in New York City.",
  "wingstop": "US chicken-wing chain founded 1994 in Texas.",
  "panerabread": "US bakery-café chain founded 1987 in Missouri.",
  "olivegarden": "US Italian-food chain founded 1982 in Florida.",
  "redlobster": "US seafood chain founded 1968 in Florida.",
  "buffalowildwings": "US wings & sports-bar chain founded 1982 in Ohio.",
  "arbys": "US roast-beef chain founded 1964 in Ohio.",
  "jackinthebox": "US burger chain founded 1951 in San Diego.",
  "auntieannes": "US soft-pretzel chain founded 1988 in Pennsylvania.",
  "quiznos": "US toasted-sub chain founded 1981 in Denver.",
  "outback": "Australian-themed US steakhouse founded 1988.",
  "pfchangs": "US Asian-bistro chain founded 1993 in Arizona.",
  "yoshinoya": "Japanese beef-bowl chain founded 1899 in Tokyo.",
  "lotteria": "Fast-food chain founded 1972; big in Japan & Korea.",
  "bostonmarket": "US rotisserie-chicken chain founded 1985.",
  "crackerbarrel": "US country-style chain founded 1969 in Tennessee.",
  "raisingcanes": "US chicken-finger chain founded 1996 in Louisiana.",
  // ===== HARD =====
  "innout": "US burger chain founded 1948 in Baldwin Park, California.",
  "whataburger": "US burger chain founded 1950 in Corpus Christi, Texas.",
  "greggs": "UK bakery chain founded 1939 in Newcastle.",
  "pret": "UK sandwich chain founded 1986 in London.",
  "wagamama": "UK-based Asian-noodle chain founded 1992 in London.",
  "guzmanygomez": "Mexican-food chain founded 2006 in Australia.",
  "hungryjacks": "Australian Burger King brand founded 1971.",
  "pizzaexpress": "UK pizza chain founded 1965 in London.",
  "leon": "UK healthy fast-food chain founded 2004 in London.",
  "wetherspoons": "UK pub chain founded 1979 in London.",
  "zaxbys": "US chicken chain founded 1990 in Georgia.",
  "bojangles": "US chicken & biscuits chain founded 1977 in N. Carolina.",
  "culvers": "US burger chain founded 1984 in Wisconsin.",
  "whitecastle": "US slider chain founded 1921 in Wichita, Kansas.",
  "deltaco": "US Tex-Mex chain founded 1964 in California.",
  "elpolloloco": "Mexican-origin chicken chain; US debut 1980.",
  "churchschicken": "US fried-chicken chain founded 1952 in Texas.",
  "maxburgers": "Sweden's oldest burger chain, founded 1968.",
  "quick": "European burger chain founded 1971 in Belgium.",
  "telepizza": "Spanish pizza chain founded 1988 in Madrid.",
  "vapiano": "German-Italian restaurant chain founded 2002.",
  "nordsee": "German seafood fast-food chain founded 1896.",
  "supermacs": "Irish fast-food chain founded 1978 in Ballinasloe.",
  "chowking": "Filipino Chinese fast-food chain founded 1985.",
  "mosburger": "Japanese burger chain founded 1972 in Tokyo.",
  // ===== IMPOSSIBLE =====
  "dodopizza": "Russia's biggest pizza chain, founded 2011.",
  "teremok": "Russian chain founded 1998, famous for blini.",
  "wienerwald": "German rotisserie-chicken chain founded 1955.",
  "hesburger": "Finland's biggest burger chain, founded 1966.",
  "juanvaldez": "Colombian coffee chain founded 2002 in Bogotá.",
  "bembos": "Peruvian burger chain founded 1988 in Lima.",
  "mostaza": "Argentine burger chain founded 2000.",
  "vips": "Mexican diner chain founded 1964.",
  "redrooster": "Australian roast-chicken chain founded 1972.",
  "oporto": "Australian Portuguese-chicken chain founded 1986.",
  "grilld": "Australian burger chain founded 2004 in Melbourne.",
  "wienerschnitzel": "US hot-dog chain founded 1961 in California.",
  "runza": "US chain founded 1949 in Nebraska; famed for runzas.",
  "skyline": "US chili chain founded 1949 in Cincinnati, Ohio.",
  "whitespot": "Canadian burger chain founded 1928 in Vancouver.",
  "harveys": "Canadian burger chain founded 1959 in Ontario.",
  "marybrowns": "Canadian fried-chicken chain founded 1969.",
  "caffenero": "UK-Italian coffee chain founded 1997 in London.",
  "pollotropical": "US Caribbean-chicken chain founded 1988 in Miami.",
  "pollocampero": "Guatemalan fried-chicken chain founded 1971.",
  "cocoichibanya": "Japanese curry-house chain founded 1978.",
  "freshnessburger": "Japanese burger chain founded 1992 in Tokyo.",
  "eljannah": "Australian charcoal-chicken chain founded 1998.",
  "farmerboys": "US burger chain founded 1981 in California.",
  "huddlehouse": "US Southern diner chain founded 1964 in Georgia.",
};
