// E-fish2 «Guess the Fish (Vol. 2)» — GuessSync · 100 fish (25/tier) · real photos fish2/<slug>.jpg · VO fs-<slug>.wav
// Colorful & recognizable true fish. 100% DISTINCT from E36 (fishData.js) and E20 (seaData.js) — unique slug AND name.
// Difficulty by absolute recognition: easy (Flounder/Yellow Tang) → impossible (Football Fish/deep-sea oddities).
export const FISH2 = [
  // ===== EASY (25) =====
  { slug: "flounder", name: "Flounder", level: "easy" },
  { slug: "molly", name: "Molly", level: "easy" },
  { slug: "gourami", name: "Gourami", level: "easy" },
  { slug: "anchovy", name: "Anchovy", level: "easy" },
  { slug: "bluegill", name: "Bluegill", level: "easy" },
  { slug: "walleye", name: "Walleye", level: "easy" },
  { slug: "yellow-tang", name: "Yellow Tang", level: "easy" },
  { slug: "rainbow-trout", name: "Rainbow Trout", level: "easy" },
  { slug: "sea-bass", name: "Sea Bass", level: "easy" },
  { slug: "mullet", name: "Mullet", level: "easy" },
  { slug: "haddock", name: "Haddock", level: "easy" },
  { slug: "tarpon", name: "Tarpon", level: "easy" },
  { slug: "bluefish", name: "Bluefish", level: "easy" },
  { slug: "crappie", name: "Crappie", level: "easy" },
  { slug: "sole", name: "Sole", level: "easy" },
  { slug: "smallmouth-bass", name: "Smallmouth Bass", level: "easy" },
  { slug: "striped-bass", name: "Striped Bass", level: "easy" },
  { slug: "sea-bream", name: "Sea Bream", level: "easy" },
  { slug: "tiger-shark", name: "Tiger Shark", level: "easy" },
  { slug: "bull-shark", name: "Bull Shark", level: "easy" },
  { slug: "nurse-shark", name: "Nurse Shark", level: "easy" },
  { slug: "mako-shark", name: "Mako Shark", level: "easy" },
  { slug: "eagle-ray", name: "Eagle Ray", level: "easy" },
  { slug: "swordtail", name: "Swordtail", level: "easy" },
  { slug: "platy", name: "Platy", level: "easy" },
  // ===== MEDIUM (25) =====
  { slug: "emperor-angelfish", name: "Emperor Angelfish", level: "medium" },
  { slug: "queen-angelfish", name: "Queen Angelfish", level: "medium" },
  { slug: "royal-gramma", name: "Royal Gramma", level: "medium" },
  { slug: "copperband-butterflyfish", name: "Copperband Butterflyfish", level: "medium" },
  { slug: "foxface-rabbitfish", name: "Foxface Rabbitfish", level: "medium" },
  { slug: "powder-blue-tang", name: "Powder Blue Tang", level: "medium" },
  { slug: "tiger-barb", name: "Tiger Barb", level: "medium" },
  { slug: "cardinal-tetra", name: "Cardinal Tetra", level: "medium" },
  { slug: "german-blue-ram", name: "German Blue Ram", level: "medium" },
  { slug: "clown-loach", name: "Clown Loach", level: "medium" },
  { slug: "plecostomus", name: "Plecostomus", level: "medium" },
  { slug: "corydoras", name: "Corydoras", level: "medium" },
  { slug: "dwarf-gourami", name: "Dwarf Gourami", level: "medium" },
  { slug: "harlequin-rasbora", name: "Harlequin Rasbora", level: "medium" },
  { slug: "jack-dempsey", name: "Jack Dempsey", level: "medium" },
  { slug: "convict-cichlid", name: "Convict Cichlid", level: "medium" },
  { slug: "silver-dollar", name: "Silver Dollar", level: "medium" },
  { slug: "peacock-bass", name: "Peacock Bass", level: "medium" },
  { slug: "rainbow-shark", name: "Rainbow Shark", level: "medium" },
  { slug: "paradise-fish", name: "Paradise Fish", level: "medium" },
  { slug: "lingcod", name: "Lingcod", level: "medium" },
  { slug: "lemon-shark", name: "Lemon Shark", level: "medium" },
  { slug: "blacktip-reef-shark", name: "Blacktip Reef Shark", level: "medium" },
  { slug: "guitarfish", name: "Guitarfish", level: "medium" },
  { slug: "red-drum", name: "Red Drum", level: "medium" },
  // ===== HARD (25) =====
  { slug: "regal-angelfish", name: "Regal Angelfish", level: "hard" },
  { slug: "flame-angelfish", name: "Flame Angelfish", level: "hard" },
  { slug: "coral-beauty", name: "Coral Beauty", level: "hard" },
  { slug: "lyretail-anthias", name: "Lyretail Anthias", level: "hard" },
  { slug: "flame-hawkfish", name: "Flame Hawkfish", level: "hard" },
  { slug: "harlequin-tuskfish", name: "Harlequin Tuskfish", level: "hard" },
  { slug: "sixline-wrasse", name: "Sixline Wrasse", level: "hard" },
  { slug: "firefish", name: "Firefish", level: "hard" },
  { slug: "yellow-boxfish", name: "Yellow Boxfish", level: "hard" },
  { slug: "picasso-triggerfish", name: "Picasso Triggerfish", level: "hard" },
  { slug: "niger-triggerfish", name: "Niger Triggerfish", level: "hard" },
  { slug: "longfin-bannerfish", name: "Longfin Bannerfish", level: "hard" },
  { slug: "raccoon-butterflyfish", name: "Raccoon Butterflyfish", level: "hard" },
  { slug: "bumphead-parrotfish", name: "Bumphead Parrotfish", level: "hard" },
  { slug: "unicornfish", name: "Unicornfish", level: "hard" },
  { slug: "harlequin-sweetlips", name: "Harlequin Sweetlips", level: "hard" },
  { slug: "pajama-cardinalfish", name: "Pajama Cardinalfish", level: "hard" },
  { slug: "green-chromis", name: "Green Chromis", level: "hard" },
  { slug: "blue-devil-damsel", name: "Blue Devil Damsel", level: "hard" },
  { slug: "elephantnose-fish", name: "Elephantnose Fish", level: "hard" },
  { slug: "black-ghost-knifefish", name: "Ghost Knifefish", level: "hard" },
  { slug: "congo-tetra", name: "Congo Tetra", level: "hard" },
  { slug: "flowerhorn", name: "Flowerhorn", level: "hard" },
  { slug: "epaulette-shark", name: "Epaulette Shark", level: "hard" },
  { slug: "ribbontail-ray", name: "Ribbontail Ray", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { slug: "football-fish", name: "Football Fish", level: "impossible" },
  { slug: "lancetfish", name: "Lancetfish", level: "impossible" },
  { slug: "lizardfish", name: "Lizardfish", level: "impossible" },
  { slug: "monkfish", name: "Monkfish", level: "impossible" },
  { slug: "oyster-toadfish", name: "Oyster Toadfish", level: "impossible" },
  { slug: "midshipman", name: "Midshipman", level: "impossible" },
  { slug: "cusk-eel", name: "Cusk Eel", level: "impossible" },
  { slug: "lumpsucker", name: "Lumpsucker", level: "impossible" },
  { slug: "ribbonfish", name: "Ribbonfish", level: "impossible" },
  { slug: "slickhead", name: "Slickhead", level: "impossible" },
  { slug: "grunt-sculpin", name: "Grunt Sculpin", level: "impossible" },
  { slug: "daggertooth", name: "Daggertooth", level: "impossible" },
  { slug: "sea-robin", name: "Sea Robin", level: "impossible" },
  { slug: "elephant-shark", name: "Elephant Shark", level: "impossible" },
  { slug: "cookiecutter-shark", name: "Cookiecutter Shark", level: "impossible" },
  { slug: "megamouth-shark", name: "Megamouth Shark", level: "impossible" },
  { slug: "sawshark", name: "Sawshark", level: "impossible" },
  { slug: "angel-shark", name: "Angel Shark", level: "impossible" },
  { slug: "electric-ray", name: "Electric Ray", level: "impossible" },
  { slug: "sea-toad", name: "Sea Toad", level: "impossible" },
  { slug: "john-dory", name: "John Dory", level: "impossible" },
  { slug: "cornetfish", name: "Cornetfish", level: "impossible" },
  { slug: "wolf-eel", name: "Wolf-eel", level: "impossible" },
  { slug: "greeneye", name: "Greeneye", level: "impossible" },
  { slug: "opah", name: "Opah", level: "impossible" },
];
export const FISH2_LEVELS = ["easy", "medium", "hard", "impossible"];
