// E36 «Guess the Fish» — one true ≤70-char fact per fish, shown on the reveal.
export const FISH_FACTS = {
  // ===== EASY =====
  "clownfish": "Born male, it can switch to female to lead the group.",
  "goldfish": "A domesticated carp that can see more colors than we do.",
  "great-white-shark": "Its keen nose can detect blood diluted in seawater.",
  "salmon": "It returns to the exact river where it was born to spawn.",
  "tuna": "Warm-blooded and fast, it can sprint over 40 mph.",
  "piranha": "Its jaws are among the strongest of any fish its size.",
  "pufferfish": "It gulps water to balloon up when it feels threatened.",
  "seahorse": "The male, not the female, carries and births the young.",
  "swordfish": "It heats its eyes and brain to hunt in cold depths.",
  "betta": "Males flare and fight, so they are kept alone.",
  "angelfish": "This freshwater fish often pairs up for life.",
  "manta-ray": "It has the largest brain of any fish.",
  "hammerhead-shark": "Its wide head gives it nearly 360-degree vision.",
  "catfish": "Its whole body is covered in taste buds.",
  "stingray": "Its tail spine carries venom for defense.",
  "whale-shark": "The biggest fish alive, yet it eats tiny plankton.",
  "koi": "Well-kept koi can live for many decades.",
  "carp": "It can survive in low-oxygen water others cannot.",
  "trout": "It senses tiny water vibrations to track its food.",
  "cod": "A single female can lay millions of eggs at once.",
  "barracuda": "It ambushes prey in fast bursts up to 35 mph.",
  "marlin": "One of the fastest fish, it can top 50 mph.",
  "guppy": "Females give birth to live young, not eggs.",
  "moray-eel": "It has a second set of jaws inside its throat.",
  "sardine": "It swims in huge schools that move as one.",

  // ===== MEDIUM =====
  "lionfish": "Its beautiful fins hide venomous spines.",
  "mahi-mahi": "It grows incredibly fast, over 4 feet in a year.",
  "blue-tang": "This is the fish that played Dory in Finding Nemo.",
  "anglerfish": "It dangles a glowing lure to bait prey in the dark.",
  "flying-fish": "It glides above the waves to escape predators.",
  "sturgeon": "An ancient fish whose eggs are sold as caviar.",
  "halibut": "Both of its eyes sit on one side of its flat body.",
  "red-snapper": "It can live for more than 50 years.",
  "grouper": "It can change color and even its sex as it grows.",
  "mackerel": "Its striped back helps it hide in open water.",
  "herring": "It gathers in ocean schools of billions of fish.",
  "largemouth-bass": "A favorite catch, it strikes lures aggressively.",
  "perch": "Its spiny dorsal fin deters would-be predators.",
  "tilapia": "One of the most farmed food fish on Earth.",
  "pike": "A stealth hunter that ambushes from the weeds.",
  "sailfish": "Often called the fastest fish in the ocean.",
  "electric-eel": "It can deliver a shock of up to 600 volts.",
  "parrotfish": "It makes sand by grinding up the coral it eats.",
  "triggerfish": "It locks a spine upright to wedge into crevices.",
  "mandarinfish": "One of very few animals with true blue pigment.",
  "ocean-sunfish": "The heaviest bony fish, it can top two tons.",
  "zebrafish": "A lab favorite that can regrow its own heart.",
  "discus": "Parents feed their young a slime from their skin.",
  "sawfish": "Its saw-like snout senses and stuns its prey.",
  "reef-shark": "It patrols coral reefs and rarely bothers people.",

  // ===== HARD =====
  "wels-catfish": "Europe's giant catfish can top 9 feet long.",
  "arapaima": "A huge freshwater fish that gulps air to breathe.",
  "mudskipper": "A fish that walks on land and breathes through skin.",
  "archerfish": "It shoots water to knock insects into the water.",
  "napoleon-wrasse": "A huge reef fish with a bump on its forehead.",
  "moorish-idol": "Its long trailing fin makes it unmistakable.",
  "boxfish": "Its body is a rigid box of fused bony plates.",
  "cowfish": "It has two horns above its eyes, like a cow.",
  "scorpionfish": "A master of camouflage with venomous spines.",
  "stonefish": "The most venomous fish, disguised as a rock.",
  "frogfish": "It walks on fin-legs and swallows prey whole.",
  "wobbegong": "A flat, carpet-like shark that hides on the seabed.",
  "tigerfish": "Africa's fanged predator that even snaps at birds.",
  "alligator-gar": "A living fossil armored in tough, hard scales.",
  "bowfin": "A living fossil that gulps air to survive.",
  "paddlefish": "It sweeps its paddle snout to sense plankton.",
  "snakehead": "It can breathe air and wriggle across land.",
  "bichir": "An ancient fish with lungs that gulps air.",
  "lungfish": "It can survive drought buried in mud for months.",
  "neon-tetra": "Its glowing blue stripe shines in dark water.",
  "oscar": "A smart cichlid that can recognize its owner.",
  "weedy-seadragon": "Its leafy flaps disguise it as drifting weed.",
  "leafy-seadragon": "It looks almost exactly like floating seaweed.",
  "pipefish": "A straightened-out relative of the seahorse.",
  "remora": "It hitches rides by suckering onto sharks.",

  // ===== IMPOSSIBLE =====
  "coelacanth": "A living fossil once thought extinct for ages.",
  "oarfish": "The longest bony fish, it can reach 30 feet.",
  "blobfish": "Its jelly-like body holds shape in deep-sea pressure.",
  "goblin-shark": "It shoots its jaws forward to snatch prey.",
  "frilled-shark": "A deep-sea shark with 300 needle-like teeth.",
  "viperfish": "Its fangs are too long to fit inside its mouth.",
  "fangtooth": "It has the largest teeth for its size of any fish.",
  "hatchetfish": "It glows on its belly to erase its own shadow.",
  "barreleye": "Its see-through head reveals tube-shaped eyes.",
  "pelican-eel": "It unhinges a huge mouth to swallow big prey.",
  "dragonfish": "It makes red light no other deep fish can see.",
  "lanternfish": "It lights up its body to blend into faint light.",
  "stargazer": "It buries itself with eyes and mouth facing up.",
  "handfish": "It uses hand-shaped fins to walk the seafloor.",
  "sarcastic-fringehead": "It flares a huge mouth to battle rivals.",
  "sheepshead": "It has human-like teeth for crushing shellfish.",
  "pineapplefish": "It glows from bacteria housed under its jaw.",
  "red-lipped-batfish": "It walks the seabed on fins instead of swimming.",
  "ratfish": "A relative of sharks with a long, rat-like tail.",
  "black-swallower": "It can swallow prey larger than itself.",
  "tripod-fish": "It perches on long fin stilts on the deep seabed.",
  "grenadier": "This deep-sea fish has a long, tapering rat tail.",
  "pacu": "A piranha cousin with oddly human-like teeth.",
  "wolffish": "Its strong jaws crush crabs and sea urchins.",
  "telescopefish": "Its tube eyes point up to spot prey overhead.",
};
