// E-fish2 «Guess the Fish (Vol. 2)» — one true ≤70-char fact per fish, shown on the reveal.
export const FISH2_FACTS = {
  // ===== EASY =====
  "flounder": "Both eyes migrate to one side as this flatfish grows up.",
  "molly": "This livebearer gives birth to free-swimming young, not eggs.",
  "gourami": "It gulps air at the surface using a labyrinth breathing organ.",
  "anchovy": "These tiny fish swim in huge shimmering schools for safety.",
  "bluegill": "A panfish named for the blue flap on its gill cover.",
  "walleye": "Its mirror-like eyes help it hunt in dim, murky water.",
  "yellow-tang": "This bright reef fish has a white scalpel near its tail.",
  "rainbow-trout": "A pink stripe runs along its speckled, silvery body.",
  "sea-bass": "A prized food fish that can change sex as it matures.",
  "mullet": "Famous for leaping repeatedly clear out of the water.",
  "haddock": "A dark 'thumbprint' spot marks each side of this cod cousin.",
  "tarpon": "This silver giant can gulp air to survive murky water.",
  "bluefish": "A fierce feeder that hunts in aggressive, slashing packs.",
  "crappie": "A speckled panfish popular with freshwater anglers.",
  "sole": "A flatfish that lies camouflaged on the sandy seabed.",
  "smallmouth-bass": "A hard-fighting bass with reddish eyes and dark bars.",
  "striped-bass": "Dark horizontal stripes run along its silvery sides.",
  "sea-bream": "A deep-bodied coastal fish prized on the dinner plate.",
  "tiger-shark": "Dark bars like a tiger's fade as this shark grows up.",
  "bull-shark": "One of few sharks that can thrive in freshwater rivers.",
  "nurse-shark": "A slow, docile bottom-dweller that rests by day.",
  "mako-shark": "The fastest shark, able to burst over 40 mph.",
  "eagle-ray": "It 'flies' through open water flapping wing-like fins.",
  "swordtail": "The male sports a long sword-like extension on its tail.",
  "platy": "A hardy, colorful livebearer loved by aquarium keepers.",
  // ===== MEDIUM =====
  "emperor-angelfish": "Its stripes completely change pattern as it matures.",
  "queen-angelfish": "A blue-ringed 'crown' spot marks this golden reef beauty.",
  "royal-gramma": "Half purple, half gold, split neatly down the middle.",
  "copperband-butterflyfish": "A long snout plucks food from tight crevices.",
  "foxface-rabbitfish": "Its spines carry venom, so handle this fish with care.",
  "powder-blue-tang": "A pale blue body with a bright yellow dorsal fin.",
  "tiger-barb": "It nips fins, so keep this striped barb in a group.",
  "cardinal-tetra": "A neon red-and-blue stripe glows down its whole body.",
  "german-blue-ram": "A tiny, peaceful cichlid shimmering with blue speckles.",
  "clown-loach": "Orange with black bands, it can make audible clicks.",
  "plecostomus": "This armored catfish clings to glass and eats algae.",
  "corydoras": "A small armored catfish that darts up for a gulp of air.",
  "dwarf-gourami": "The male builds a floating nest out of bubbles.",
  "harlequin-rasbora": "A black triangle marks the rear of its coppery body.",
  "jack-dempsey": "Named for a boxer, this cichlid is a scrappy fighter.",
  "convict-cichlid": "Black-and-white bars give this feisty cichlid its name.",
  "silver-dollar": "A round, coin-shaped relative of the piranha.",
  "peacock-bass": "A prized game fish with a bold eye-spot on its tail.",
  "rainbow-shark": "A dark shark-shaped fish with fiery red fins.",
  "paradise-fish": "One of the first tropical fish ever kept in aquariums.",
  "lingcod": "Its flesh is sometimes a startling blue-green color.",
  "lemon-shark": "Its yellowish skin blends with sandy tropical shallows.",
  "blacktip-reef-shark": "Black-tipped fins mark this shy tropical reef shark.",
  "guitarfish": "A ray with a shark-like body shaped like a guitar.",
  "red-drum": "A black tail spot and a low, croaking drum sound.",
  // ===== HARD =====
  "regal-angelfish": "Bold blue and orange bars make it a reef showpiece.",
  "flame-angelfish": "A fiery red-orange dwarf angel with black bars.",
  "coral-beauty": "A hardy dwarf angel washed in blue and orange.",
  "lyretail-anthias": "Males shift color to rule a harem of females.",
  "flame-hawkfish": "Bright red, it perches on coral to watch for prey.",
  "harlequin-tuskfish": "It shows off bold blue teeth against orange bands.",
  "sixline-wrasse": "Six blue lines run along its orange-purple body.",
  "firefish": "A skittish fish that darts into holes when startled.",
  "yellow-boxfish": "A boxy yellow cube that releases toxin when stressed.",
  "picasso-triggerfish": "Its wild markings inspired the name of a painter.",
  "niger-triggerfish": "Its color shifts from green to blue with its mood.",
  "longfin-bannerfish": "A trailing white banner streams from its dorsal fin.",
  "raccoon-butterflyfish": "A black eye mask gives this reef fish its name.",
  "bumphead-parrotfish": "It headbutts coral and grows a bulging forehead.",
  "unicornfish": "A horn-like spike juts from the forehead of adults.",
  "harlequin-sweetlips": "Bold spots replace the stripes it wore as a baby.",
  "pajama-cardinalfish": "Spots and bands look like mismatched pajamas.",
  "green-chromis": "Shimmering green schools hover above branching coral.",
  "blue-devil-damsel": "A tiny, electric-blue fish with a big attitude.",
  "elephantnose-fish": "It uses a weak electric field to navigate murky water.",
  "black-ghost-knifefish": "It swims by rippling one long fin along its belly.",
  "congo-tetra": "Its scales flash rainbow colors in bright light.",
  "flowerhorn": "A man-made hybrid famed for its huge head hump.",
  "epaulette-shark": "It 'walks' on its fins across exposed reef flats.",
  "ribbontail-ray": "Blue spots warn that its tail carries a venomous spine.",
  // ===== IMPOSSIBLE =====
  "football-fish": "A deep-sea angler that lures prey with a glowing bulb.",
  "lancetfish": "A fanged predator with a tall sail-like dorsal fin.",
  "lizardfish": "It rests on the seabed, then ambushes passing prey.",
  "monkfish": "A huge mouth and a lure make this flat ambush hunter.",
  "oyster-toadfish": "The male 'hums' loudly to call females to its nest.",
  "midshipman": "Rows of light organs glow like a uniform's buttons.",
  "cusk-eel": "Some live deeper than almost any other fish known.",
  "lumpsucker": "Its pelvic fins fuse into a sucker that grips rocks.",
  "ribbonfish": "A long, flat, silvery fish that drifts upright.",
  "slickhead": "A deep-sea fish with loose, easily shed skin.",
  "grunt-sculpin": "It 'hops' on its fins and grunts when handled.",
  "daggertooth": "Curved fangs let it grip slippery deep-sea prey.",
  "sea-robin": "Wing-like fins and leg-like rays let it walk the seabed.",
  "elephant-shark": "A chimaera with a trunk-like snout, not a true shark.",
  "cookiecutter-shark": "It bites round plugs of flesh from larger animals.",
  "megamouth-shark": "A rare giant that filters plankton with a huge mouth.",
  "sawshark": "A long toothed snout slashes through schools of fish.",
  "angel-shark": "A flattened shark that buries itself to ambush prey.",
  "electric-ray": "It stuns prey with a powerful built-in electric shock.",
  "sea-toad": "A balloon-like angler that 'walks' on leg-like fins.",
  "john-dory": "A dark eye-spot on each side may startle predators.",
  "cornetfish": "A slender fish with a long, trailing tail filament.",
  "wolf-eel": "Not a true eel; strong jaws crush crabs and urchins.",
  "greeneye": "Reflective green eyes glow in the deep-sea gloom.",
  "opah": "A warm-blooded fish that heats its whole body to hunt.",
};
