// E02 — one verified ≤70-char fact per country, shown on the flag reveal.
export const FLAG_FACTS = {
  // ===== EASY =====
  "us": "Its 50 stars stand for the 50 states.",
  "jp": "The red disc on the flag represents the sun.",
  "ca": "The red maple leaf has 11 points.",
  "gb": "The Union Jack combines three older crosses.",
  "br": "The stars show the sky over Rio on Nov 15, 1889.",
  "fr": "The blue-white-red tricolour dates to the Revolution.",
  "cn": "The big star leads four smaller stars.",
  "de": "Berlin sits on the River Spree.",
  "in": "The wheel in the center is the Ashoka Chakra.",
  "it": "Rome's Colosseum could hold 50,000 spectators.",
  "ch": "One of only two square national flags.",
  "kr": "The central circle is the taeguk yin-yang symbol.",
  "ar": "The yellow face is called the Sun of May.",
  "mx": "The emblem shows an eagle eating a snake.",
  "ru": "It is the largest country on Earth.",
  "au": "The big star has seven points for its states.",
  "es": "Madrid is the highest capital city in the European Union.",
  "tr": "The star and crescent are a national emblem.",
  "gr": "The nine stripes match nine syllables of a motto.",
  "se": "The blue and yellow form a Nordic cross.",
  "za": "It has six colours, more than most flags.",
  "sa": "The script reads the Islamic declaration of faith.",
  "ie": "The green, white, orange stand for peace between two.",
  "nl": "The oldest tricolour flag still in use.",
  "pt": "Lisbon is older than Rome.",
  // ===== MEDIUM =====
  "eg": "The eagle is the Eagle of Saladin.",
  "dk": "The world's oldest continuously used national flag.",
  "no": "It has a Nordic cross with a cross inside it.",
  "ua": "Blue over yellow: sky above wheat fields.",
  "fi": "The blue cross stands for its many lakes.",
  "jm": "One of few flags with no red, white, or blue.",
  "pl": "White over red, its national colours.",
  "be": "Its vertical stripes echo the French tricolour.",
  "kp": "The red star sits inside a white circle.",
  "vn": "The gold star has five points on red.",
  "at": "One of the world's oldest flag designs.",
  "cu": "The single white star is the Lone Star.",
  "ir": "The emblem is a stylized word for God.",
  "ma": "The green star is a pentagram, Solomon's Seal.",
  "id": "Its red-white flag is nearly identical to Monaco's.",
  "nz": "The Southern Cross stars appear in red.",
  "ph": "Flown red-up to signal a state of war.",
  "th": "The central blue band is double width.",
  "co": "Yellow is half the flag: the nation's gold.",
  "cz": "The blue triangle sets it apart from Poland.",
  "my": "Its 14 stripes stand for 13 states and the federal union.",
  "hu": "Green here stands for hope.",
  "ae": "Its colours are the Pan-Arab colours.",
  "cl": "Its flag is nicknamed 'La Estrella Solitaria'.",
  "hr": "Famous for its red-and-white checkerboard shield.",
  // ===== HARD =====
  "ke": "The center shows a Maasai shield and two spears.",
  "lb": "The green cedar tree is a symbol of Lebanon.",
  "np": "The only national flag that isn't a rectangle.",
  "pe": "Home to Machu Picchu, an Inca citadel.",
  "ng": "Green-white-green: the white stands for peace.",
  "pk": "The crescent and star sit beside a white stripe.",
  "is": "One of the world's most volcanically active countries.",
  "ps": "Its colours are the four Pan-Arab colours.",
  "ro": "Nearly identical to Chad's flag.",
  "sg": "The crescent and five stars sit on red.",
  "ve": "The eight stars stand for eight provinces.",
  "bd": "The red disc sits off-center toward the hoist.",
  "bg": "White, green and red run in horizontal bands.",
  "lk": "The gold lion holds a sword.",
  "qa": "The only national flag wider than twice its height.",
  "rs": "Its double-headed eagle is a national symbol.",
  "et": "Its colours inspired many African flags.",
  "gh": "The black star gave its name to a football team.",
  "iq": "Bears the Arabic phrase for God is Greatest.",
  "kh": "Its flag depicts the temple of Angkor Wat.",
  "si": "Its emblem shows Mount Triglav, the highest peak.",
  "sk": "Its shield shows a double cross on three hills.",
  "sy": "Its colours are the Pan-Arab colours.",
  "ec": "The condor crowns its coat of arms.",
  "jo": "The seven-pointed star marks seven verses of a prayer.",
  // ===== IMPOSSIBLE =====
  "ws": "The Southern Cross shines on its flag.",
  "ag": "Its rising sun marks the dawn of a new era.",
  "aw": "The four-pointed star sits on a light-blue field.",
  "dj": "It sits by one of the world's busiest shipping lanes.",
  "gq": "Africa's only country with Spanish as official language.",
  "je": "A British island closer to France than to Britain.",
  "km": "Four stars stand for its four islands.",
  "lc": "Its triangles represent the twin Piton peaks.",
  "li": "It added a crown after sharing Haiti's flag.",
  "mh": "The star's 24 points stand for its municipalities.",
  "sb": "Its five stars stand for island groups.",
  "tl": "The first new sovereign nation of the 21st century.",
  "tv": "Its nine stars stand for its nine islands.",
  "vu": "The emblem is a boar's tusk, a sign of prosperity.",
  "ck": "Its 15 stars stand for its 15 islands.",
  "cw": "The two stars stand for Curacao and Klein Curacao.",
  "fm": "Its four stars stand for four island states.",
  "gg": "The gold cross recalls William the Conqueror.",
  "kn": "Its two stars stand for hope and liberty.",
  "nr": "The star sits just south of the Equator, like the isle.",
  "st": "Its two stars stand for its two main islands.",
  "vc": "The green diamonds are known as the Gems of the Antilles.",
  "nu": "One of the world's largest raised coral atolls.",
  "sx": "It shares one island with Saint Martin.",
  "bq": "Three Dutch islands in the Caribbean Sea.",
};
