// E73 «Guess the ZOOMED Flag» — GuessSync "What the Zoom" hard-mode. Reuses the E02 flag image set
// (flags/<slug>.svg) but re-tiered by how hard each flag is to name from an EXTREME off-center crop.
// EASY = big unique emblem/pattern survives any crop · IMPOSSIBLE = plain solid bands (a crop = one colour).
// image: flags/<slug>.svg | answer VO: sfx/fz-<slug>.wav  (slug === ISO code, same files as E02)
export const FLAGZOOM = [
  // ===== EASY (25) — dominant emblem/device, recognisable even zoomed =====
  { slug: "ca", name: "Canada", level: "easy" },
  { slug: "jp", name: "Japan", level: "easy" },
  { slug: "gb", name: "United Kingdom", level: "easy" },
  { slug: "us", name: "United States", level: "easy" },
  { slug: "br", name: "Brazil", level: "easy" },
  { slug: "ch", name: "Switzerland", level: "easy" },
  { slug: "cn", name: "China", level: "easy" },
  { slug: "kr", name: "South Korea", level: "easy" },
  { slug: "in", name: "India", level: "easy" },
  { slug: "mx", name: "Mexico", level: "easy" },
  { slug: "tr", name: "Turkey", level: "easy" },
  { slug: "sa", name: "Saudi Arabia", level: "easy" },
  { slug: "ar", name: "Argentina", level: "easy" },
  { slug: "za", name: "South Africa", level: "easy" },
  { slug: "gr", name: "Greece", level: "easy" },
  { slug: "pt", name: "Portugal", level: "easy" },
  { slug: "np", name: "Nepal", level: "easy" },
  { slug: "lk", name: "Sri Lanka", level: "easy" },
  { slug: "ke", name: "Kenya", level: "easy" },
  { slug: "kh", name: "Cambodia", level: "easy" },
  { slug: "lb", name: "Lebanon", level: "easy" },
  { slug: "eg", name: "Egypt", level: "easy" },
  { slug: "cu", name: "Cuba", level: "easy" },
  { slug: "kp", name: "North Korea", level: "easy" },
  { slug: "au", name: "Australia", level: "easy" },
  // ===== MEDIUM (25) — a clear distinctive element (cross/star/crescent/crest) to hunt for =====
  { slug: "dk", name: "Denmark", level: "medium" },
  { slug: "no", name: "Norway", level: "medium" },
  { slug: "fi", name: "Finland", level: "medium" },
  { slug: "is", name: "Iceland", level: "medium" },
  { slug: "se", name: "Sweden", level: "medium" },
  { slug: "es", name: "Spain", level: "medium" },
  { slug: "ph", name: "Philippines", level: "medium" },
  { slug: "rs", name: "Serbia", level: "medium" },
  { slug: "si", name: "Slovenia", level: "medium" },
  { slug: "sk", name: "Slovakia", level: "medium" },
  { slug: "hr", name: "Croatia", level: "medium" },
  { slug: "ec", name: "Ecuador", level: "medium" },
  { slug: "ve", name: "Venezuela", level: "medium" },
  { slug: "my", name: "Malaysia", level: "medium" },
  { slug: "sg", name: "Singapore", level: "medium" },
  { slug: "pk", name: "Pakistan", level: "medium" },
  { slug: "ma", name: "Morocco", level: "medium" },
  { slug: "ir", name: "Iran", level: "medium" },
  { slug: "vn", name: "Vietnam", level: "medium" },
  { slug: "sy", name: "Syria", level: "medium" },
  { slug: "iq", name: "Iraq", level: "medium" },
  { slug: "jo", name: "Jordan", level: "medium" },
  { slug: "jm", name: "Jamaica", level: "medium" },
  { slug: "cz", name: "Czechia", level: "medium" },
  { slug: "nz", name: "New Zealand", level: "medium" },
  // ===== HARD (25) — bicolour/tricolour with a subtle mark or unusual colours =====
  { slug: "ua", name: "Ukraine", level: "hard" },
  { slug: "pl", name: "Poland", level: "hard" },
  { slug: "id", name: "Indonesia", level: "hard" },
  { slug: "at", name: "Austria", level: "hard" },
  { slug: "co", name: "Colombia", level: "hard" },
  { slug: "pe", name: "Peru", level: "hard" },
  { slug: "ng", name: "Nigeria", level: "hard" },
  { slug: "gh", name: "Ghana", level: "hard" },
  { slug: "et", name: "Ethiopia", level: "hard" },
  { slug: "bd", name: "Bangladesh", level: "hard" },
  { slug: "bg", name: "Bulgaria", level: "hard" },
  { slug: "ro", name: "Romania", level: "hard" },
  { slug: "th", name: "Thailand", level: "hard" },
  { slug: "cl", name: "Chile", level: "hard" },
  { slug: "be", name: "Belgium", level: "hard" },
  { slug: "hu", name: "Hungary", level: "hard" },
  { slug: "ie", name: "Ireland", level: "hard" },
  { slug: "nl", name: "Netherlands", level: "hard" },
  { slug: "ae", name: "United Arab Emirates", level: "hard" },
  { slug: "ps", name: "Palestine", level: "hard" },
  { slug: "qa", name: "Qatar", level: "hard" },
  { slug: "ws", name: "Samoa", level: "hard" },
  { slug: "tl", name: "Timor-Leste", level: "hard" },
  { slug: "dj", name: "Djibouti", level: "hard" },
  { slug: "vu", name: "Vanuatu", level: "hard" },
  // ===== IMPOSSIBLE (25) — plain solid bands (a crop = one colour) or ultra-obscure =====
  { slug: "fr", name: "France", level: "impossible" },
  { slug: "de", name: "Germany", level: "impossible" },
  { slug: "ru", name: "Russia", level: "impossible" },
  { slug: "it", name: "Italy", level: "impossible" },
  { slug: "ag", name: "Antigua and Barbuda", level: "impossible" },
  { slug: "aw", name: "Aruba", level: "impossible" },
  { slug: "gq", name: "Equatorial Guinea", level: "impossible" },
  { slug: "je", name: "Jersey", level: "impossible" },
  { slug: "km", name: "Comoros", level: "impossible" },
  { slug: "lc", name: "Saint Lucia", level: "impossible" },
  { slug: "li", name: "Liechtenstein", level: "impossible" },
  { slug: "mh", name: "Marshall Islands", level: "impossible" },
  { slug: "sb", name: "Solomon Islands", level: "impossible" },
  { slug: "ck", name: "Cook Islands", level: "impossible" },
  { slug: "cw", name: "Curacao", level: "impossible" },
  { slug: "fm", name: "Micronesia", level: "impossible" },
  { slug: "gg", name: "Guernsey", level: "impossible" },
  { slug: "kn", name: "Saint Kitts and Nevis", level: "impossible" },
  { slug: "nr", name: "Nauru", level: "impossible" },
  { slug: "st", name: "Sao Tome and Principe", level: "impossible" },
  { slug: "vc", name: "Saint Vincent and the Grenadines", level: "impossible" },
  { slug: "nu", name: "Niue", level: "impossible" },
  { slug: "sx", name: "Sint Maarten", level: "impossible" },
  { slug: "bq", name: "Caribbean Netherlands", level: "impossible" },
  { slug: "tv", name: "Tuvalu", level: "impossible" },
];
