// E06 «Guess the Flag 2» — did-you-know facts, ≤70 chars each, verified. No il.
export const FLAG2_FACTS = {
  // ===== EASY (25) =====
  "tn": "Ancient Carthage, a rival of Rome, stood here.",
  "ly": "Almost entirely covered by the Sahara Desert.",
  "sd": "The Nile River flows north right through it.",
  "kw": "A small, oil-rich country at the head of the Gulf.",
  "om": "Its capital city is Muscat, by the Arabian Sea.",
  "bh": "An island linked to Saudi Arabia by a causeway.",
  "af": "A landlocked land of high mountain passes.",
  "mm": "Its largest city is Yangon, once called Rangoon.",
  "kz": "The world's largest landlocked country.",
  "uz": "Home to the Silk Road city of Samarkand.",
  "by": "A landlocked country to the east of Poland.",
  "ge": "It sits where Europe meets Asia by the Black Sea.",
  "am": "One of the world's oldest Christian nations.",
  "az": "Its capital Baku sits on the Caspian Sea.",
  "lt": "The largest of the three Baltic states.",
  "lv": "Its capital Riga lies on the Baltic Sea.",
  "ee": "The northernmost of the three Baltic states.",
  "al": "Its flag shows a black double-headed eagle.",
  "ba": "Its capital city is Sarajevo.",
  "md": "A landlocked land between Romania and Ukraine.",
  "do": "It shares an island with Haiti.",
  "pa": "Its famous canal links two oceans.",
  "bo": "Home to the world's largest salt flat.",
  "py": "A landlocked country in South America.",
  "uy": "South America's smallest Spanish-speaking country.",
  // ===== MEDIUM (25) =====
  "tw": "Its capital is Taipei, home to a huge tech industry.",
  "ht": "It shares an island with the Dominican Republic.",
  "cr": "It has had no standing army since 1948.",
  "gt": "Home to ancient Maya ruins like Tikal.",
  "hn": "The ancient Maya ruins of Copan lie here.",
  "ni": "The largest country in Central America.",
  "sv": "The smallest country in Central America.",
  "me": "Its name means 'Black Mountain' in Italian.",
  "mk": "A landlocked country in the Balkans.",
  "xk": "A landlocked region in the Balkans, capital Pristina.",
  "cy": "An island in the eastern Mediterranean Sea.",
  "mt": "A small island nation south of Sicily.",
  "lu": "One of the world's wealthiest countries per person.",
  "la": "The only landlocked country in Southeast Asia.",
  "bn": "A small, oil-rich nation on Borneo island.",
  "bt": "Its flag features a white dragon.",
  "mv": "A nation of nearly 1,200 low-lying coral islands.",
  "kg": "A mountainous country in Central Asia.",
  "tj": "Nearly half its land lies above 3,000 metres.",
  "tm": "The Karakum Desert covers most of it.",
  "ci": "The world's top cocoa bean producer.",
  "sn": "The westernmost country of mainland Africa.",
  "cm": "Often nicknamed 'Africa in miniature'.",
  "mz": "A long coastline on the Indian Ocean.",
  "ao": "Its capital Luanda sits on the Atlantic coast.",
  // ===== HARD (25) =====
  "zm": "Home to part of the mighty Victoria Falls.",
  "zw": "It shares Victoria Falls with Zambia.",
  "ug": "It sits on the shores of Lake Victoria.",
  "tz": "Mount Kilimanjaro is Africa's highest peak.",
  "rw": "Known as the land of a thousand hills.",
  "mg": "A huge island off Africa's east coast.",
  "na": "Home to the towering dunes of the Namib Desert.",
  "bw": "The Okavango Delta spreads across its north.",
  "bf": "A landlocked country in West Africa.",
  "ml": "The ancient city of Timbuktu lies here.",
  "ne": "Mostly covered by the Sahara Desert.",
  "td": "Named after Lake Chad on its western edge.",
  "mr": "Mostly desert, on Africa's Atlantic coast.",
  "gn": "Its capital city is Conakry.",
  "bj": "Its largest city is Cotonou.",
  "tg": "A narrow strip of land in West Africa.",
  "ga": "Its capital Libreville sits on the coast.",
  "cd": "The Congo River winds through it.",
  "cg": "Its capital is Brazzaville.",
  "cf": "Landlocked in the heart of Africa.",
  "so": "It has the longest coastline in mainland Africa.",
  "er": "It lies along the Red Sea coast.",
  "ss": "The world's youngest nation, formed in 2011.",
  "sl": "Its capital city is Freetown.",
  "mn": "Home to the vast Gobi Desert.",
  // ===== IMPOSSIBLE (25) =====
  "gm": "Africa's smallest mainland country.",
  "gw": "It includes the Bijagos island group.",
  "mw": "Lake Malawi runs along much of its border.",
  "ls": "A mountain kingdom encircled by South Africa.",
  "sz": "A small kingdom, formerly called Swaziland.",
  "sc": "An island nation in the Indian Ocean.",
  "mu": "An island nation east of Madagascar.",
  "bb": "The easternmost island of the Caribbean.",
  "bs": "An archipelago of about 700 islands.",
  "tt": "Two islands just off the coast of Venezuela.",
  "dm": "A mountainous island in the Caribbean Sea.",
  "gd": "Known as the 'Isle of Spice' for its nutmeg.",
  "sr": "The smallest country in South America.",
  "gy": "Home to the towering Kaieteur Falls.",
  "bz": "Home to the Great Blue Hole, a giant sinkhole.",
  "fj": "A Pacific archipelago of over 300 islands.",
  "ki": "Its islands straddle the equator in the Pacific.",
  "pw": "A small island nation in the western Pacific.",
  "pg": "It shares an island with Indonesia.",
  "to": "A Pacific kingdom of about 170 islands.",
  "ad": "A tiny country in the Pyrenees mountains.",
  "im": "A self-governing island in the Irish Sea.",
  "va": "The smallest country in the world.",
  "sm": "One of the world's oldest republics.",
  "cv": "Volcanic islands off West Africa's coast.",
};
