// E02 «Guess the Flag» — GuessSync · 100 علم · صعوبة مطلقة (أشهر ← أغمض <5%). لا علم إسرائيل. image: flags/<iso>.svg | VO: sfx/fl-<iso>.wav
export const FLAGS = [
  // ===== EASY (25) =====
  { iso: "us", name: "United States", level: "easy" },
  { iso: "jp", name: "Japan", level: "easy" },
  { iso: "ca", name: "Canada", level: "easy" },
  { iso: "gb", name: "United Kingdom", level: "easy" },
  { iso: "br", name: "Brazil", level: "easy" },
  { iso: "fr", name: "France", level: "easy" },
  { iso: "cn", name: "China", level: "easy" },
  { iso: "de", name: "Germany", level: "easy" },
  { iso: "in", name: "India", level: "easy" },
  { iso: "it", name: "Italy", level: "easy" },
  { iso: "ch", name: "Switzerland", level: "easy" },
  { iso: "kr", name: "South Korea", level: "easy" },
  { iso: "ar", name: "Argentina", level: "easy" },
  { iso: "mx", name: "Mexico", level: "easy" },
  { iso: "ru", name: "Russia", level: "easy" },
  { iso: "au", name: "Australia", level: "easy" },
  { iso: "es", name: "Spain", level: "easy" },
  { iso: "tr", name: "Turkey", level: "easy" },
  { iso: "gr", name: "Greece", level: "easy" },
  { iso: "se", name: "Sweden", level: "easy" },
  { iso: "za", name: "South Africa", level: "easy" },
  { iso: "sa", name: "Saudi Arabia", level: "easy" },
  { iso: "ie", name: "Ireland", level: "easy" },
  { iso: "nl", name: "Netherlands", level: "easy" },
  { iso: "pt", name: "Portugal", level: "easy" },
  // ===== MEDIUM (25) =====
  { iso: "eg", name: "Egypt", level: "medium" },
  { iso: "dk", name: "Denmark", level: "medium" },
  { iso: "no", name: "Norway", level: "medium" },
  { iso: "ua", name: "Ukraine", level: "medium" },
  { iso: "fi", name: "Finland", level: "medium" },
  { iso: "jm", name: "Jamaica", level: "medium" },
  { iso: "pl", name: "Poland", level: "medium" },
  { iso: "be", name: "Belgium", level: "medium" },
  { iso: "kp", name: "North Korea", level: "medium" },
  { iso: "vn", name: "Vietnam", level: "medium" },
  { iso: "at", name: "Austria", level: "medium" },
  { iso: "cu", name: "Cuba", level: "medium" },
  { iso: "ir", name: "Iran", level: "medium" },
  { iso: "ma", name: "Morocco", level: "medium" },
  { iso: "id", name: "Indonesia", level: "medium" },
  { iso: "nz", name: "New Zealand", level: "medium" },
  { iso: "ph", name: "Philippines", level: "medium" },
  { iso: "th", name: "Thailand", level: "medium" },
  { iso: "co", name: "Colombia", level: "medium" },
  { iso: "cz", name: "Czechia", level: "medium" },
  { iso: "my", name: "Malaysia", level: "medium" },
  { iso: "hu", name: "Hungary", level: "medium" },
  { iso: "ae", name: "United Arab Emirates", level: "medium" },
  { iso: "cl", name: "Chile", level: "medium" },
  { iso: "hr", name: "Croatia", level: "medium" },
  // ===== HARD (25) =====
  { iso: "ke", name: "Kenya", level: "hard" },
  { iso: "lb", name: "Lebanon", level: "hard" },
  { iso: "np", name: "Nepal", level: "hard" },
  { iso: "pe", name: "Peru", level: "hard" },
  { iso: "ng", name: "Nigeria", level: "hard" },
  { iso: "pk", name: "Pakistan", level: "hard" },
  { iso: "is", name: "Iceland", level: "hard" },
  { iso: "ps", name: "Palestine", level: "hard" },
  { iso: "ro", name: "Romania", level: "hard" },
  { iso: "sg", name: "Singapore", level: "hard" },
  { iso: "ve", name: "Venezuela", level: "hard" },
  { iso: "bd", name: "Bangladesh", level: "hard" },
  { iso: "bg", name: "Bulgaria", level: "hard" },
  { iso: "lk", name: "Sri Lanka", level: "hard" },
  { iso: "qa", name: "Qatar", level: "hard" },
  { iso: "rs", name: "Serbia", level: "hard" },
  { iso: "et", name: "Ethiopia", level: "hard" },
  { iso: "gh", name: "Ghana", level: "hard" },
  { iso: "iq", name: "Iraq", level: "hard" },
  { iso: "kh", name: "Cambodia", level: "hard" },
  { iso: "si", name: "Slovenia", level: "hard" },
  { iso: "sk", name: "Slovakia", level: "hard" },
  { iso: "sy", name: "Syria", level: "hard" },
  { iso: "ec", name: "Ecuador", level: "hard" },
  { iso: "jo", name: "Jordan", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { iso: "ws", name: "Samoa", level: "impossible" },
  { iso: "ag", name: "Antigua and Barbuda", level: "impossible" },
  { iso: "aw", name: "Aruba", level: "impossible" },
  { iso: "dj", name: "Djibouti", level: "impossible" },
  { iso: "gq", name: "Equatorial Guinea", level: "impossible" },
  { iso: "je", name: "Jersey", level: "impossible" },
  { iso: "km", name: "Comoros", level: "impossible" },
  { iso: "lc", name: "Saint Lucia", level: "impossible" },
  { iso: "li", name: "Liechtenstein", level: "impossible" },
  { iso: "mh", name: "Marshall Islands", level: "impossible" },
  { iso: "sb", name: "Solomon Islands", level: "impossible" },
  { iso: "tl", name: "Timor-Leste", level: "impossible" },
  { iso: "tv", name: "Tuvalu", level: "impossible" },
  { iso: "vu", name: "Vanuatu", level: "impossible" },
  { iso: "ck", name: "Cook Islands", level: "impossible" },
  { iso: "cw", name: "Curacao", level: "impossible" },
  { iso: "fm", name: "Micronesia", level: "impossible" },
  { iso: "gg", name: "Guernsey", level: "impossible" },
  { iso: "kn", name: "Saint Kitts and Nevis", level: "impossible" },
  { iso: "nr", name: "Nauru", level: "impossible" },
  { iso: "st", name: "Sao Tome and Principe", level: "impossible" },
  { iso: "vc", name: "Saint Vincent and the Grenadines", level: "impossible" },
  { iso: "nu", name: "Niue", level: "impossible" },
  { iso: "sx", name: "Sint Maarten", level: "impossible" },
  { iso: "bq", name: "Caribbean Netherlands", level: "impossible" },
];
