// E09 «Guess the Flower» — did-you-know facts, ≤70 chars each, verified.
export const FLOWER_FACTS = {
  // ===== EASY =====
  "rose": "In the rose family, alongside apples, pears and cherries.",
  "sunflower": "Young plants track the sun; mature blooms face east.",
  "tulip": "It sparked tulip mania, one of history's first bubbles.",
  "oxeye-daisy": "Its name comes from 'day's eye,' as it opens at dawn.",
  "dandelion": "Every part of the plant is edible, from root to flower.",
  "lavender": "Its name comes from the Latin 'lavare,' meaning to wash.",
  "orchid": "Orchids form one of the largest of all plant families.",
  "lily": "True lilies are highly toxic to cats, even in traces.",
  "daffodil": "The national flower of Wales, worn on St David's Day.",
  "common-poppy": "A worldwide symbol of remembrance for fallen soldiers.",
  "carnation": "A traditional Mother's Day flower around the world.",
  "marigold": "Central to Mexico's Day of the Dead celebrations.",
  "hibiscus": "Its flowers are brewed into a tart, ruby-red tea.",
  "lotus": "Its seeds can still sprout after a thousand-plus years.",
  "cherry-blossom": "Japan marks its bloom with 'hanami' viewing parties.",
  "chrysanthemum": "The royal and imperial symbol of Japan.",
  "iris": "Named after the Greek goddess of the rainbow.",
  "sweet-violet": "Its scent briefly numbs the nose's smell receptors.",
  "bluebell": "Carpets of it can signal ancient, undisturbed woodland.",
  "pansy": "Its name comes from the French 'pensée,' meaning thought.",
  "peony": "A traditional flower of China, symbol of wealth and honor.",
  "hydrangea": "Its flower color shifts with the acidity of the soil.",
  "geranium": "Garden 'geraniums' are actually of the genus Pelargonium.",
  "buttercup": "Its glossy petals reflect a yellow glow onto your chin.",
  "water-lily": "Claude Monet painted his water lilies around 250 times.",

  // ===== MEDIUM =====
  "foxglove": "The source of digitalis, a powerful heart medicine.",
  "snapdragon": "Squeeze the bloom and it opens like a dragon's jaws.",
  "zinnia": "Zinnias bloomed aboard the space station back in 2016.",
  "petunia": "A close relative of the tomato and the potato.",
  "begonia": "Named after Michel Bégon, a French colonial official.",
  "cosmos": "Its name is Greek for order and harmony.",
  "anemone": "Called the windflower, from the Greek word for wind.",
  "camellia": "A cousin of this plant gives us black and green tea.",
  "magnolia": "Older than bees, it is pollinated mainly by beetles.",
  "wisteria": "A single Japanese wisteria can live for over 100 years.",
  "azalea": "A type of rhododendron; all parts are toxic if eaten.",
  "freesia": "Prized by florists for its sweet, citrusy scent.",
  "gardenia": "Its rich scent made it a classic buttonhole flower.",
  "hollyhock": "A cottage-garden favorite that can top two metres.",
  "ranunculus": "Its many layered petals look like crepe paper.",
  "aster": "Its name is simply the Greek word for star.",
  "crocus": "Saffron is harvested from the stigmas of a crocus.",
  "hyacinth": "Named for a youth in Greek myth loved by Apollo.",
  "lilac": "A member of the olive family, prized for its scent.",
  "forget-me-not": "The state flower of Alaska in the United States.",
  "morning-glory": "Its blooms open at dawn and wilt by the afternoon.",
  "sweet-pea": "Grown for its scent, but its seeds are mildly toxic.",
  "nasturtium": "Its leaves and flowers add a peppery kick to salads.",
  "gerbera": "One of the world's most popular cut flowers.",
  "calla-lily": "Not a true lily; its 'petal' is a single leaf-like bract.",

  // ===== HARD =====
  "delphinium": "Named for its buds' resemblance to a dolphin.",
  "gladiolus": "Its name comes from the Latin for 'little sword.'",
  "amaryllis": "Often grown indoors to bloom in the depths of winter.",
  "bird-of-paradise": "Its bloom mimics a tropical bird in flight.",
  "protea": "South Africa's national flower, named after a Greek god.",
  "bleeding-heart": "Its pink blooms hang like tiny valentine hearts.",
  "columbine": "Its name comes from the Latin word for dove.",
  "lupine": "It enriches the soil by fixing nitrogen from the air.",
  "bee-balm": "Its leaves brew into a fragrant, minty herbal tea.",
  "verbena": "It was treated as a sacred herb by the ancient Romans.",
  "scabiosa": "Called the pincushion flower for its tufted stamens.",
  "astilbe": "Its feathery plumes brighten shady garden corners.",
  "celosia": "Its velvety bloom can look like a rooster's comb.",
  "lantana": "Its flower clusters change color as they age.",
  "bougainvillea": "Its 'petals' are bracts around the tiny true flowers.",
  "plumeria": "Its fragrant blooms are strung into Hawaiian leis.",
  "passionflower": "Missionaries saw the passion of Christ in its parts.",
  "fuchsia": "Its vivid blooms lend their name to a shade of pink.",
  "heather": "It blankets Scotland's moorlands in purple bloom.",
  "statice": "It keeps its color when dried, a florist's favorite.",
  "alstroemeria": "Called the Peruvian lily, though not a true lily.",
  "lisianthus": "Its rose-like blooms are prized in wedding bouquets.",
  "coreopsis": "Its name is Greek for 'bug-like,' from its seeds.",
  "gaillardia": "Called the blanket flower for its warm, fiery colors.",
  "coneflower": "Its extract, echinacea, is a popular herbal cold remedy.",

  // ===== IMPOSSIBLE =====
  "ghost-orchid": "Leafless and rare, it seems to float in the air.",
  "corpse-flower": "It reeks of rotting flesh to lure in pollinators.",
  "jade-vine": "Its claw-shaped blooms are a rare turquoise color.",
  "bat-flower": "Its black blooms trail whiskers up to 30 cm long.",
  "crown-imperial": "A ring of blooms sits beneath a crown of leaves.",
  "bee-orchid": "It mimics a female bee to lure males into pollinating.",
  "parrots-beak": "Its curved red blooms resemble a parrot's beak.",
  "snakes-head-fritillary": "Its checkered petals recall a snake's skin.",
  "himalayan-blue-poppy": "One of the few truly blue flowers in nature.",
  "chocolate-lily": "Named for its mottled, chocolate-brown nodding bells.",
  "voodoo-lily": "It gives off a foul odor to attract pollinating flies.",
  "sea-holly": "A spiny, thistle-like plant that thrives by the sea.",
  "naked-man-orchid": "Its tiny florets resemble little hanging men.",
  "kangaroo-paw": "Its fuzzy blooms are shaped like a kangaroo's paw.",
  "naked-lady": "Its blooms appear on bare stems after the leaves die.",
  "flame-lily": "The national flower of Zimbabwe, and highly poisonous.",
  "torch-ginger": "Its towering red bloom flavors Southeast Asian dishes.",
  "pincushion-protea": "Its stamens stick out like pins in a cushion.",
  "angels-trumpet": "Its huge trumpet blooms are beautiful but toxic.",
  "balloon-flower": "Its buds puff up like balloons before they open.",
  "turtlehead": "Its blooms are shaped like a turtle's open head.",
  "toad-lily": "Its orchid-like speckled blooms thrive in shade.",
  "blackberry-lily": "Its seed clusters look just like ripe blackberries.",
  "foxtail-lily": "Its tall flower spires can reach up to three metres.",
  "desert-rose": "A succulent with a swollen trunk that stores water.",
};
