// E175 food-emoji facts — one true <=70-char fact per food, shown on reveal.
export const FOOD_EMOJI_3_FACTS = {
  // EASY
  "tomato-soup": "Smooth soup made from cooked, blended tomatoes.",
  "chicken-soup": "Comforting broth simmered with chicken and vegetables.",
  "garlic-bread": "Bread topped with garlic butter and toasted.",
  "chocolate-chip-cookie": "Sweet cookie studded with chocolate chips.",
  "strawberry-cake": "Sponge cake flavored and topped with strawberries.",
  "lemonade": "Refreshing drink of lemon juice, water and sugar.",
  "orange-juice": "Juice squeezed from fresh oranges.",
  "iced-tea": "Chilled tea served over ice.",
  "banana-split": "Dessert of a split banana with ice cream scoops.",
  "cherry-pie": "Baked pie filled with sweet cherries.",
  "pumpkin-pie": "Spiced pumpkin custard baked in a pastry crust.",
  "blueberry-muffin": "Sweet baked muffin dotted with blueberries.",
  "coconut-water": "Clear refreshing liquid from young coconuts.",
  "mango-smoothie": "Blended cold drink made from ripe mango.",
  "buttered-toast": "Toasted bread spread with butter.",
  "peanut-butter-cookie": "Cookie made rich with peanut butter.",
  "lemon-cake": "Moist cake flavored with tangy lemon.",
  "carrot-cake": "Spiced cake made with grated carrots.",
  "cheese-omelette": "Beaten eggs cooked and folded around cheese.",
  "grilled-shrimp": "Shrimp cooked over an open flame or grill.",
  "grilled-salmon": "Salmon fillet cooked on a grill.",
  "roast-chicken": "Whole chicken roasted until golden.",
  "roast-turkey": "Whole turkey roasted, a holiday classic.",
  "bbq-ribs": "Ribs grilled and glazed with barbecue sauce.",
  "lobster-roll": "Lobster meat served in a buttered bun.",
  // MEDIUM
  "beef-stew": "Beef simmered slowly with vegetables.",
  "chicken-pot-pie": "Creamy chicken filling baked under pastry.",
  "fish-taco": "Grilled or fried fish served in a tortilla.",
  "shrimp-cocktail": "Chilled shrimp served with tangy sauce.",
  "calamari": "Squid rings battered and deep-fried.",
  "oysters": "Raw shellfish often served with lemon.",
  "lobster-bisque": "Creamy soup made from lobster.",
  "teriyaki-chicken": "Chicken glazed in sweet Japanese teriyaki sauce.",
  "wonton-soup": "Chinese soup with filled dumplings in broth.",
  "scallion-pancake": "Savory Chinese pancake layered with scallions.",
  "egg-tart": "Pastry shell filled with baked egg custard.",
  "banana-bread": "Moist quick bread made from ripe bananas.",
  "cornbread": "Crumbly bread made from cornmeal.",
  "flan": "Creamy custard topped with soft caramel.",
  "creme-brulee": "Custard with a hard torched caramel top.",
  "rice-pudding": "Sweet pudding of rice cooked in milk.",
  "bread-pudding": "Baked dessert of bread soaked in custard.",
  "chocolate-mousse": "Light, airy whipped chocolate dessert.",
  "chocolate-fondue": "Melted chocolate for dipping fruit and treats.",
  "eclair": "Choux pastry filled with cream and iced.",
  "cannoli": "Italian fried pastry tube filled with ricotta.",
  "sorbet": "Frozen dessert made from fruit and sugar.",
  "affogato": "Vanilla ice cream drowned in hot espresso.",
  "cappuccino": "Espresso topped with steamed, foamed milk.",
  "macaron": "French almond meringue sandwich cookie.",
  // HARD
  "pastrami": "Cured, smoked, spiced beef served sliced.",
  "corned-beef-hash": "Fried mix of corned beef and diced potatoes.",
  "bubble-and-squeak": "British fry-up of leftover cabbage and potato.",
  "welsh-rarebit": "Savory melted cheese sauce over toast.",
  "eggs-benedict": "Poached eggs and ham on a muffin with hollandaise.",
  "huevos-rancheros": "Fried eggs on tortillas with spicy salsa.",
  "chilaquiles": "Fried tortilla chips simmered in salsa.",
  "tamale": "Corn dough steamed in a husk with filling.",
  "chiles-rellenos": "Roasted peppers stuffed with cheese, then fried.",
  "pozole": "Mexican stew of hominy corn and meat.",
  "carnitas": "Slow-cooked, shredded Mexican pork.",
  "birria": "Spiced Mexican braised meat stew.",
  "elote": "Grilled Mexican street corn with toppings.",
  "horchata": "Sweet drink of rice, cinnamon and milk.",
  "tres-leches": "Sponge cake soaked in three kinds of milk.",
  "drunken-noodles": "Spicy stir-fried Thai wide noodles.",
  "green-curry": "Thai curry made with green chili paste.",
  "massaman-curry": "Mild Thai curry rich with peanuts.",
  "tom-yum": "Hot and sour Thai shrimp soup.",
  "tom-kha": "Thai coconut soup with galangal.",
  "larb": "Spicy Thai minced meat salad with herbs.",
  "mango-sticky-rice": "Thai dessert of mango and sweet coconut rice.",
  "papaya-salad": "Spicy Thai salad of shredded green papaya.",
  "bun-cha": "Vietnamese grilled pork with noodles.",
  "summer-roll": "Fresh Vietnamese rice-paper roll, not fried.",
  // IMPOSSIBLE
  "rosti": "Swiss pan-fried grated potato cake.",
  "raclette": "Melted Swiss cheese scraped over potatoes.",
  "tartiflette": "French bake of potato, bacon and cheese.",
  "quiche-lorraine": "Savory tart of eggs, cream and bacon.",
  "bouillabaisse": "Provencal French fish and seafood stew.",
  "cassoulet": "French slow-cooked bean and meat stew.",
  "tarte-tatin": "French upside-down caramelized apple tart.",
  "kouign-amann": "Buttery, caramelized Breton pastry.",
  "stroopwafel": "Dutch waffle wafers filled with syrup.",
  "dorayaki": "Japanese pancakes filled with red bean paste.",
  "taiyaki": "Fish-shaped Japanese cake with sweet filling.",
  "mochi": "Chewy Japanese cake of pounded rice.",
  "matcha-latte": "Green tea whisked with steamed milk.",
  "bibingka": "Filipino baked coconut rice cake.",
  "halo-halo": "Filipino shaved-ice dessert with mix-ins.",
  "ube": "Filipino sweet purple yam dessert.",
  "sundubu-jjigae": "Korean spicy soft tofu stew.",
  "bindaetteok": "Korean savory mung bean pancake.",
  "hotteok": "Korean sweet syrup-filled pancake.",
  "patbingsu": "Korean shaved ice with sweet red beans.",
  "cochinita-pibil": "Yucatan slow-roasted marinated pork.",
  "mofongo": "Puerto Rican mashed fried plantains.",
  "ackee-and-saltfish": "Jamaica's national dish of ackee and cod.",
  "jerk-chicken": "Jamaican chicken in fiery jerk spice.",
  "doubles": "Trinidadian flatbread with curried chickpeas.",
};
