// E213 food-emoji facts — one true <=70-char fact per dish, shown on reveal.
export const FOOD_EMOJI_5_FACTS = {
  // EASY
  "shrimp-po-boy": "A New Orleans sandwich of fried shrimp on a crusty baguette roll.",
  "beef-tibs": "Ethiopian beef cubes sauteed with onions, peppers, and spices.",
  "chicken-tinola": "A Filipino ginger chicken soup with green papaya and chili leaves.",
  "lumpia": "Filipino spring rolls filled with meat and vegetables, deep-fried.",
  "mandi": "A Yemeni dish of spiced rice slow-cooked with tender goat meat.",
  "maqluba": "A Palestinian upside-down rice dish layered with eggplant and meat.",
  "fatteh": "Levantine crispy bread layered with yogurt, chickpeas, and spices.",
  "mujadara": "A Levantine dish of lentils and rice topped with fried onions.",
  "chicken-tikka": "Indian chicken chunks marinated in yogurt and spices, then roasted.",
  "aloo-paratha": "An Indian flatbread stuffed with spiced mashed potato filling.",
  "keema-curry": "A South Asian curry of spiced minced meat, often mutton or beef.",
  "prawn-toast": "Chinese toast topped with minced shrimp paste and deep-fried.",
  "chicken-noodle-soup": "A comforting soup of chicken, noodles, and vegetables in broth.",
  "doner-kebab": "Turkish meat roasted on a vertical spit, served in bread.",
  "beef-noodle-soup": "A Taiwanese soup of braised beef and noodles in rich broth.",
  "shashlik": "Marinated meat grilled on skewers, popular across Central Asia.",
  "pork-belly-rice-bowl": "Chinese-style pork belly braised in a sweet soy glaze over rice.",
  "chicken-fried-steak": "Breaded, pan-fried beef steak served smothered in creamy gravy.",
  "kimchi-jjigae": "A spicy Korean stew made with fermented kimchi.",
  "beef-kabob": "Skewered, marinated cubes of beef grilled over an open flame.",
  "prawn-masala": "Shrimp simmered in a spiced tomato-based Indian masala sauce.",
  "duck-rice": "A Singaporean and Malaysian dish of braised duck served with rice.",
  "goat-curry": "A richly spiced curry of tender goat meat, popular in the Caribbean.",
  "gumbo": "A Louisiana stew thickened with roux, okra, or file.",
  "meat-pie": "A handheld Australian pastry filled with minced meat and gravy.",
  // MEDIUM
  "chicken-piri-piri": "Grilled chicken marinated in spicy Portuguese-African piri piri.",
  "shchi": "A traditional Russian cabbage soup, often simmered with meat.",
  "solyanka": "A tangy Russian soup with meat or fish, olives, and pickles.",
  "pelmeni": "Russian dumplings filled with minced meat, boiled or fried.",
  "khoresh-gheimeh": "A Persian stew of split peas, meat, and tangy dried lime.",
  "plov": "A Central Asian rice dish cooked with lamb and carrots.",
  "chakhokhbili": "A Georgian chicken stew simmered with tomatoes and herbs.",
  "lahmacun": "A thin Turkish flatbread topped with minced meat and spices.",
  "muhammara": "A Syrian dip of roasted red peppers, walnuts, and spices.",
  "ful-medames": "An Egyptian dish of stewed fava beans with lemon and oil.",
  "koshari": "An Egyptian mix of rice, lentils, pasta, and tomato sauce.",
  "mansaf": "A Jordanian dish of lamb cooked in fermented dried yogurt.",
  "kabsa": "A Saudi spiced rice dish usually served with chicken.",
  "aloo-gobi": "A North Indian dry curry of potatoes and cauliflower with spices.",
  "currywurst": "A German fast food of sliced sausage with curry ketchup.",
  "sauerbraten": "A German pot roast marinated for days before cooking.",
  "baingan-bharta": "A North Indian dish of smoky mashed roasted eggplant with spices.",
  "sancocho": "A hearty Latin American stew of meat with root vegetables.",
  "baba-ganoush": "A Levantine dip of roasted, mashed eggplant and tahini.",
  "chana-masala": "A North Indian curry made with chickpeas in spiced tomato sauce.",
  "rogan-josh": "A rich, spicy Kashmiri curry traditionally made with lamb.",
  "korma": "A mild curry made creamy with yogurt, cream, or coconut.",
  "dal-makhani": "A Punjabi dish of black lentils simmered with butter and cream.",
  "coconut-fish-curry": "A South Indian curry of fish simmered in spiced coconut milk.",
  "chimichurri-steak": "Argentine grilled steak served with a tangy garlic herb sauce.",
  // HARD
  "yukhoe": "Korean seasoned raw beef, often topped with a raw egg yolk.",
  "japchae": "Korean stir-fried glass noodles with vegetables and beef.",
  "galbi": "Korean marinated beef short ribs, grilled over an open flame.",
  "kimbap": "Korean rice and fillings rolled in seaweed, sliced into rounds.",
  "naengmyeon": "Korean cold buckwheat noodles served in an icy tangy broth.",
  "haemul-pajeon": "A Korean savory pancake packed with seafood and scallions.",
  "panang-curry": "A rich, mild Thai curry made with coconut milk and chilies.",
  "pancit-canton": "A Filipino stir-fried wheat noodle dish with vegetables and meat.",
  "sisig": "A sizzling Filipino dish of chopped pork seasoned with calamansi.",
  "lomo-saltado": "A Peruvian stir-fry of beef, onions, tomatoes, and fries.",
  "bo-luc-lac": "A Vietnamese dish of cubed beef stir-fried with garlic and greens.",
  "canh-chua": "A Vietnamese sweet and sour fish soup with pineapple and herbs.",
  "pabellon-criollo": "Venezuela's national dish of shredded beef, rice, and beans.",
  "causa-limena": "A Peruvian layered dish of mashed potato with avocado and chicken.",
  "khichdi": "A South Asian comfort dish of rice cooked with lentils.",
  "tagine": "A North African stew slow-cooked in a cone-shaped clay pot.",
  "merguez": "A spicy North African lamb sausage flavored with harissa.",
  "manakish": "A Levantine flatbread topped with za'atar herbs and oil.",
  "tacu-tacu": "A Peruvian dish of pan-fried mashed rice and beans, with egg.",
  "chorizo": "A seasoned pork sausage, spicy and paprika-rich in Spain.",
  "cevapi": "Grilled minced meat sausages, a Balkan barbecue staple.",
  "khao-soi": "A Northern Thai curry noodle soup topped with crispy noodles.",
  "koobideh": "Iranian minced meat kebabs grilled on flat skewers.",
  "fesenjan": "A Persian stew of chicken in walnut and pomegranate sauce.",
  "encebollado": "An Ecuadorian fish soup with cassava and pickled red onions.",
  // IMPOSSIBLE
  "rakfisk": "Norwegian fermented trout, cured for months before eating raw.",
  "tuna-eyeball": "A Japanese delicacy of boiled or grilled tuna eyeballs.",
  "rocky-mountain-oysters": "American deep-fried bull or bison testicles, a rustic dish.",
  "torisashi": "Japanese raw or lightly seared chicken, served thinly sliced.",
  "tiet-canh": "A Vietnamese dish of raw blood pudding topped with peanuts.",
  "prahok": "Cambodian fermented fish paste with an intensely pungent aroma.",
  "stinky-tofu": "Chinese fermented tofu known for its pungent odor.",
  "drunken-shrimp": "A Chinese dish of live shrimp soaked in strong liquor.",
  "morcilla": "A Spanish blood sausage often made with rice or onion.",
  "mopane-worms": "Dried caterpillars, a protein-rich snack in Southern Africa.",
  "sea-cucumber": "A marine animal prized in Chinese cuisine for its texture.",
  "blood-clam": "A clam species eaten raw or blanched, valued in East Asia.",
  "kiviak": "A Greenlandic Inuit dish of birds fermented inside a sealskin.",
  "turtle-soup": "A once-popular soup made from turtle meat.",
  "khash": "An Armenian and Caucasian soup made from boiled cow's feet.",
  "tteok-guk": "A Korean soup of sliced rice cakes, eaten on New Year's Day.",
  "otak-otak": "Southeast Asian spiced fish paste grilled in banana leaf.",
  "kaeng-tai-pla": "An intensely pungent Southern Thai curry made with fish kidney.",
  "muktuk": "Inuit traditional food of whale skin and blubber.",
  "frog-legs": "A French delicacy of frog legs, often sauteed in garlic butter.",
  "lengua-tacos": "Mexican tacos filled with tender braised beef tongue.",
  "boodog": "A Mongolian dish of goat cooked from the inside with hot stones.",
  "sop-buntut": "An Indonesian oxtail soup simmered until tender.",
  "percebes": "Spanish goose barnacles harvested from rocky Atlantic shores.",
  "hormigas-culonas": "Colombian toasted giant ants, a crunchy traditional snack.",
};
