// E190 food-emoji facts — one true <=70-char fact per dish, shown on reveal.
export const FOOD_EMOJI_4_FACTS = {
  // EASY
  "chicken-shawarma": "Spit-roasted marinated chicken shaved into a wrap, Levantine classic.",
  "margherita-pizza": "A Naples pizza topped with tomato, mozzarella, and basil leaves.",
  "peking-duck": "A Beijing dish of roasted duck with crackling skin, sliced tableside.",
  "chicken-katsu": "A Japanese breaded, deep-fried chicken cutlet served sliced.",
  "sashimi": "Thin slices of raw fish served without rice, a Japanese staple.",
  "nigiri": "Hand-pressed vinegared rice topped with a slice of raw fish or shrimp.",
  "california-roll": "A sushi roll of crab, avocado, and cucumber rolled rice-side out.",
  "poke-bowl": "A Hawaiian bowl of diced raw fish over rice with toppings.",
  "chow-mein": "Stir-fried Chinese noodles tossed with vegetables and meat.",
  "fried-wontons": "Crispy deep-fried dumplings filled with pork or shrimp.",
  "club-sandwich": "A triple-decker sandwich of turkey, bacon, lettuce, and tomato.",
  "blt-sandwich": "A sandwich of bacon, lettuce, and tomato on toasted bread.",
  "tuna-sandwich": "A sandwich of tuna mixed with mayonnaise between bread slices.",
  "egg-salad-sandwich": "A sandwich filled with chopped hard-boiled eggs and mayonnaise.",
  "pork-chops": "Thick-cut pork slices from the loin, usually grilled or pan-fried.",
  "lamb-chops": "Tender rib cuts of lamb, typically grilled over high heat.",
  "prawn-skewers": "Marinated prawns threaded on skewers and grilled.",
  "veggie-stir-fry": "Mixed vegetables quickly cooked in a hot wok with oil.",
  "sweet-potato-fries": "Sweet potato strips cut and fried until crisp outside.",
  "chicken-caesar-wrap": "Grilled chicken, romaine, and Caesar dressing rolled in a tortilla.",
  "shrimp-scampi": "Shrimp sauteed in butter, garlic, and white wine sauce.",
  "beef-stroganoff": "A Russian dish of sauteed beef in a sour cream mushroom sauce.",
  "chicken-parmesan": "Breaded chicken topped with tomato sauce and melted cheese.",
  "caprese-salad": "An Italian salad of tomato, mozzarella, and fresh basil.",
  "fettuccine-alfredo": "Flat pasta tossed in a rich butter and parmesan cream sauce.",

  // MEDIUM
  "steak-quesadilla": "A grilled tortilla folded around melted cheese and sliced steak.",
  "chicken-marsala": "Chicken cutlets in a Marsala wine and mushroom sauce.",
  "veal-piccata": "Veal cutlets in a lemon, caper, and white wine pan sauce.",
  "osso-buco": "Italian braised veal shanks cooked with vegetables and broth.",
  "saltimbocca": "Veal or chicken topped with prosciutto and sage, pan-seared.",
  "arancini": "Sicilian fried rice balls stuffed with cheese or ragu.",
  "panzanella": "A Tuscan salad of stale bread, tomatoes, and fresh herbs.",
  "minestrone": "A hearty Italian vegetable soup often with beans and pasta.",
  "polenta": "Boiled cornmeal porridge, often served creamy or grilled.",
  "ravioli": "Small pasta pockets filled with cheese, meat, or vegetables.",
  "tortellini": "Ring-shaped stuffed pasta from Emilia-Romagna, Italy.",
  "cacio-e-pepe": "A Roman pasta of just pecorino cheese and cracked black pepper.",
  "aglio-e-olio": "A simple pasta of garlic sauteed in olive oil with chili flakes.",
  "puttanesca": "A bold Italian pasta sauce of olives, capers, and anchovies.",
  "vitello-tonnato": "Cold sliced veal draped in a creamy tuna caper sauce.",
  "prosciutto-e-melone": "An Italian starter pairing salty cured ham with sweet melon.",
  "duck-confit": "Duck legs slow-cooked and preserved in their own fat.",
  "steak-tartare": "Finely chopped raw beef seasoned and served with a raw egg yolk.",
  "beef-carpaccio": "Thin raw beef slices drizzled with olive oil and shavings of cheese.",
  "french-onion-soup": "Caramelized onion soup topped with toasted bread and melted cheese.",
  "croque-madame": "A grilled ham and cheese sandwich topped with a fried egg.",
  "chicken-kiev": "A breaded chicken breast stuffed with garlic herb butter.",
  "chicken-cordon-bleu": "Chicken rolled around ham and cheese, breaded and fried.",
  "moules-frites": "Steamed mussels served with a side of crispy fries, Belgian style.",
  "katsu-curry": "A breaded fried cutlet served over Japanese-style curry sauce.",

  // HARD
  "tlayuda": "A large crispy Oaxacan tortilla topped with beans, cheese, and meat.",
  "sopes": "Thick fried masa cakes topped with beans, meat, and salsa.",
  "aguachile": "Mexican raw shrimp cured in lime juice and green chili sauce.",
  "picanha": "A prized Brazilian beef cut, salt-crusted and grilled over fire.",
  "coxinha": "A Brazilian teardrop-shaped fritter filled with shredded chicken.",
  "pao-de-queijo": "Brazilian baked cheese bread made with tapioca flour.",
  "moqueca": "A Brazilian fish stew simmered in coconut milk and palm oil.",
  "choripan": "A grilled chorizo sausage served in a crusty bread roll.",
  "asado": "An Argentine barbecue tradition of slow-grilled meats over open fire.",
  "bunny-chow": "A hollowed bread loaf filled with curry, a South African street food.",
  "biltong": "South African air-dried, spiced, and cured strips of meat.",
  "potjiekos": "A South African stew slow-cooked in a cast-iron pot over coals.",
  "doro-wat": "A spicy Ethiopian chicken stew eaten scooped up with injera bread.",
  "kitfo": "An Ethiopian dish of minced raw beef seasoned with spiced butter.",
  "jollof-rice": "A West African one-pot rice dish cooked in a spiced tomato base.",
  "suya": "Nigerian skewered grilled beef coated in a spicy peanut spice rub.",
  "egusi-soup": "A West African soup thickened with ground melon seeds.",
  "waakye": "A Ghanaian dish of rice and beans cooked with dried sorghum leaves.",
  "kelewele": "Ghanaian spiced and fried ripe plantain cubes.",
  "attieke": "Ivorian fermented cassava couscous, often served with fried fish.",
  "thieboudienne": "Senegal's national dish of fish, rice, and vegetables in tomato sauce.",
  "chicken-yassa": "Senegalese chicken marinated in lemon, onions, and mustard.",
  "maafe": "A West African peanut stew simmered with meat and vegetables.",
  "couscous-royale": "A North African couscous dish piled with grilled meats.",
  "harira": "A Moroccan soup of tomatoes, lentils, and chickpeas, eaten at Ramadan.",

  // IMPOSSIBLE
  "stargazy-pie": "A Cornish pie with whole pilchards poking through the crust.",
  "callos": "A Spanish stew of tripe simmered with chorizo and paprika.",
  "basashi": "Japanese raw horse meat sliced thin and served as sashimi.",
  "escamoles": "Mexican edible ant larvae, sometimes called insect caviar.",
  "chapulines": "Toasted, spiced grasshoppers eaten as a Oaxacan snack.",
  "witchetty-grub": "A large white Australian moth larva, traditionally roasted.",
  "hongeohoe": "Korean fermented skate with a famously pungent ammonia smell.",
  "fugu": "Japanese pufferfish, prepared only by licensed chefs to remove poison.",
  "sannakji": "A Korean dish of live octopus served still moving on the plate.",
  "pigs-feet": "Pork trotters slow-braised or pickled until tender and gelatinous.",
  "chicken-feet": "Chicken feet braised or steamed, popular in dim sum.",
  "beondegi": "Steamed or boiled silkworm pupae, a Korean street snack.",
  "andouillette": "A French sausage made from coarsely chopped pork intestines.",
  "birds-nest-soup": "A Chinese delicacy made from hardened swiftlet saliva nests.",
  "shark-fin-soup": "A controversial Chinese soup traditionally thickened with shark fin.",
  "snake-soup": "A Cantonese winter soup made from simmered snake meat.",
  "fried-tarantula": "Deep-fried whole tarantulas, a Cambodian delicacy.",
  "jellyfish-salad": "Chinese salad of shredded, brined jellyfish in a savory dressing.",
  "jamon-iberico": "Spanish cured ham from acorn-fed black Iberian pigs.",
  "foie-gras": "A French delicacy of fattened duck or goose liver.",
  "ant-egg-soup": "A Laotian soup made with weaver ant eggs and larvae.",
  "scorpion-skewers": "Whole scorpions skewered and fried, a Beijing street snack.",
  "cuy": "Roasted whole guinea pig, a traditional Andean delicacy.",
  "locro": "A thick Andean stew of corn, potatoes, and squash.",
  "reindeer-stew": "A Scandinavian stew of reindeer meat, a Sami tradition.",
};
