// E83 «Guess the ZOOMED Food» — GuessSync "What the Zoom" hard-mode.
// Reuses the EXACT E14 food image set (foods/<slug>.png) and E14's FOOD_FACTS
// (keyed by the same slug), but the items are RE-TIERED by how hard each dish is to
// name from an EXTREME off-center close-up crop (scale 3.0). A random patch shows one
// surface region only, so:
//   EASY  = an unmistakable texture/colour/pattern survives any crop
//           (watermelon flesh+seeds, pizza cheese+sauce, golden fries, corn kernels…)
//   IMPOSSIBLE = generic mush/texture on the crop OR an ultra-obscure dish
// slug = image filename (foods/<slug>.png, = E14 key) | answer VO: sfx/fz2-<slug>.wav
export const FOODZOOM = [
  // ===== EASY (25) — distinctive texture / colour / pattern recognisable from any patch =====
  { slug: "pizza",          name: "Pizza",             level: "easy" },
  { slug: "sushi",          name: "Sushi",             level: "easy" },
  { slug: "frenchfries",    name: "French Fries",      level: "easy" },
  { slug: "donut",          name: "Donut",             level: "easy" },
  { slug: "icecream",       name: "Ice Cream",         level: "easy" },
  { slug: "popcorn",        name: "Popcorn",           level: "easy" },
  { slug: "waffle",         name: "Waffle",            level: "easy" },
  { slug: "pretzel",        name: "Pretzel",           level: "easy" },
  { slug: "cupcake",        name: "Cupcake",           level: "easy" },
  { slug: "nachos",         name: "Nachos",            level: "easy" },
  { slug: "cornonthecob",   name: "Corn on the Cob",   level: "easy" },
  { slug: "steak",          name: "Steak",             level: "easy" },
  { slug: "friedegg",       name: "Fried Egg",         level: "easy" },
  { slug: "watermelon",     name: "Watermelon Slice",  level: "easy" },
  { slug: "paella",         name: "Paella",            level: "easy" },
  { slug: "guacamole",      name: "Guacamole",         level: "easy" },
  { slug: "churros",        name: "Churros",           level: "easy" },
  { slug: "macaron",        name: "Macaron",           level: "easy" },
  { slug: "sashimi",        name: "Sashimi",           level: "easy" },
  { slug: "onionrings",     name: "Onion Rings",       level: "easy" },
  { slug: "caprese",        name: "Caprese Salad",     level: "easy" },
  { slug: "bibimbap",       name: "Bibimbap",          level: "easy" },
  { slug: "shakshuka",      name: "Shakshuka",         level: "easy" },
  { slug: "tandoorichicken", name: "Tandoori Chicken", level: "easy" },
  { slug: "kanafeh",        name: "Kanafeh",           level: "easy" },

  // ===== MEDIUM (25) — recognisable, but the close-up detail is less unique =====
  { slug: "hamburger",      name: "Hamburger",         level: "medium" },
  { slug: "taco",           name: "Taco",              level: "medium" },
  { slug: "spaghetti",      name: "Spaghetti",         level: "medium" },
  { slug: "pancakes",       name: "Pancakes",          level: "medium" },
  { slug: "hotdog",         name: "Hot Dog",           level: "medium" },
  { slug: "friedchicken",   name: "Fried Chicken",     level: "medium" },
  { slug: "ramen",          name: "Ramen",             level: "medium" },
  { slug: "croissant",      name: "Croissant",         level: "medium" },
  { slug: "corndog",        name: "Corn Dog",          level: "medium" },
  { slug: "pho",            name: "Pho",               level: "medium" },
  { slug: "falafel",        name: "Falafel",           level: "medium" },
  { slug: "lasagna",        name: "Lasagna",           level: "medium" },
  { slug: "tiramisu",       name: "Tiramisu",          level: "medium" },
  { slug: "samosa",         name: "Samosa",            level: "medium" },
  { slug: "springroll",     name: "Spring Roll",       level: "medium" },
  { slug: "bagel",          name: "Bagel",             level: "medium" },
  { slug: "crepe",          name: "Crepe",             level: "medium" },
  { slug: "fishandchips",   name: "Fish and Chips",    level: "medium" },
  { slug: "padthai",        name: "Pad Thai",          level: "medium" },
  { slug: "baklava",        name: "Baklava",           level: "medium" },
  { slug: "cannoli",        name: "Cannoli",           level: "medium" },
  { slug: "eclair",         name: "Eclair",            level: "medium" },
  { slug: "tteokbokki",     name: "Tteokbokki",        level: "medium" },
  { slug: "pavlova",        name: "Pavlova",           level: "medium" },
  { slug: "takoyaki",       name: "Takoyaki",          level: "medium" },

  // ===== HARD (25) — obscure dish OR distinctive only when seen whole =====
  { slug: "burrito",        name: "Burrito",           level: "hard" },
  { slug: "grilledcheese",  name: "Grilled Cheese",    level: "hard" },
  { slug: "dumplings",      name: "Dumplings",         level: "hard" },
  { slug: "gyro",           name: "Gyro",              level: "hard" },
  { slug: "quesadilla",     name: "Quesadilla",        level: "hard" },
  { slug: "hummus",         name: "Hummus",            level: "hard" },
  { slug: "risotto",        name: "Risotto",           level: "hard" },
  { slug: "poutine",        name: "Poutine",           level: "hard" },
  { slug: "borscht",        name: "Borscht",           level: "hard" },
  { slug: "pierogi",        name: "Pierogi",           level: "hard" },
  { slug: "empanada",       name: "Empanada",          level: "hard" },
  { slug: "bruschetta",     name: "Bruschetta",        level: "hard" },
  { slug: "ceviche",        name: "Ceviche",           level: "hard" },
  { slug: "okonomiyaki",    name: "Okonomiyaki",       level: "hard" },
  { slug: "banhmi",         name: "Banh Mi",           level: "hard" },
  { slug: "jollofrice",     name: "Jollof Rice",       level: "hard" },
  { slug: "moussaka",       name: "Moussaka",          level: "hard" },
  { slug: "katsu",          name: "Katsu",             level: "hard" },
  { slug: "arepa",          name: "Arepa",             level: "hard" },
  { slug: "gnocchi",        name: "Gnocchi",           level: "hard" },
  { slug: "ratatouille",    name: "Ratatouille",       level: "hard" },
  { slug: "tabbouleh",      name: "Tabbouleh",         level: "hard" },
  { slug: "wellington",     name: "Beef Wellington",   level: "hard" },
  { slug: "dolma",          name: "Dolma",             level: "hard" },
  { slug: "pasteldenata",   name: "Pastel de Nata",    level: "hard" },

  // ===== IMPOSSIBLE (25) — generic texture on crop OR ultra-obscure worldwide =====
  { slug: "injera",         name: "Injera",            level: "impossible" },
  { slug: "surstromming",   name: "Surstromming",      level: "impossible" },
  { slug: "smorrebrod",     name: "Smorrebrod",        level: "impossible" },
  { slug: "haggis",         name: "Haggis",            level: "impossible" },
  { slug: "lutefisk",       name: "Lutefisk",          level: "impossible" },
  { slug: "centuryegg",     name: "Century Egg",       level: "impossible" },
  { slug: "natto",          name: "Natto",             level: "impossible" },
  { slug: "chapulines",     name: "Chapulines",        level: "impossible" },
  { slug: "casumarzu",      name: "Casu Marzu",        level: "impossible" },
  { slug: "fufu",           name: "Fufu",              level: "impossible" },
  { slug: "poi",            name: "Poi",               level: "impossible" },
  { slug: "ackee",          name: "Ackee and Saltfish", level: "impossible" },
  { slug: "larb",           name: "Larb",              level: "impossible" },
  { slug: "bunnychow",      name: "Bunny Chow",        level: "impossible" },
  { slug: "rendang",        name: "Rendang",           level: "impossible" },
  { slug: "khachapuri",     name: "Khachapuri",        level: "impossible" },
  { slug: "manti",          name: "Manti",             level: "impossible" },
  { slug: "bibingka",       name: "Bibingka",          level: "impossible" },
  { slug: "khinkali",       name: "Khinkali",          level: "impossible" },
  { slug: "zongzi",         name: "Zongzi",            level: "impossible" },
  { slug: "lechon",         name: "Lechon",            level: "impossible" },
  { slug: "smalahove",      name: "Smalahove",         level: "impossible" },
  { slug: "jelliedeels",    name: "Jellied Eels",      level: "impossible" },
  { slug: "khash",          name: "Khash",             level: "impossible" },
  { slug: "escamoles",      name: "Escamoles",         level: "impossible" },
];

export const FOODZOOM_LEVELS = ["easy", "medium", "hard", "impossible"];
