// E213 «Guess the Food by Emoji 5» — 100 dishes · 25/tier
// VO: sfx/e213-<id>.wav
export const FOOD_EMOJI_5 = [
  // ===== EASY (25) =====
  { id: "ramen", title: "Ramen", emojis: "🍜🥚", level: "easy" },
  { id: "pho", title: "Pho", emojis: "🍜🌿", level: "easy" },
  { id: "pad-thai", title: "Pad Thai", emojis: "🍜🥜", level: "easy" },
  { id: "tempura", title: "Tempura", emojis: "🍤🔥", level: "easy" },
  { id: "burrito", title: "Burrito", emojis: "🌯🥩", level: "easy" },
  { id: "hot-dog", title: "Hot Dog", emojis: "🌭🍅", level: "easy" },
  { id: "falafel", title: "Falafel", emojis: "🧆🫓", level: "easy" },
  { id: "hummus", title: "Hummus", emojis: "🫘🫒", level: "easy" },
  { id: "gyro", title: "Gyro", emojis: "🥙🥒", level: "easy" },
  { id: "paella", title: "Paella", emojis: "🥘🦐", level: "easy" },
  { id: "risotto", title: "Risotto", emojis: "🍚🧈", level: "easy" },
  { id: "lasagna", title: "Lasagna", emojis: "🍝🍅", level: "easy" },
  { id: "schnitzel", title: "Schnitzel", emojis: "🐷🍋", level: "easy" },
  { id: "doner-kebab", title: "Döner Kebab", emojis: "🥙🔥", level: "easy" },
  { id: "tandoori-chicken", title: "Tandoori Chicken", emojis: "🍗🔥", level: "easy" },
  { id: "biryani", title: "Biryani", emojis: "🍚🍗", level: "easy" },
  { id: "samosa", title: "Samosa", emojis: "🥟🥔", level: "easy" },
  { id: "bibimbap", title: "Bibimbap", emojis: "🍚🥕", level: "easy" },
  { id: "kimchi-jjigae", title: "Kimchi Jjigae", emojis: "🥬🌶", level: "easy" },
  { id: "banh-mi", title: "Banh Mi", emojis: "🥖🥕", level: "easy" },
  { id: "satay", title: "Satay", emojis: "🍢🥜", level: "easy" },
  { id: "clam-chowder", title: "Clam Chowder", emojis: "🥣🦪", level: "easy" },
  { id: "jambalaya", title: "Jambalaya", emojis: "🍚🦐", level: "easy" },
  { id: "gumbo", title: "Gumbo", emojis: "🥣🦀", level: "easy" },
  { id: "poutine", title: "Poutine", emojis: "🍟🧀", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "goulash", title: "Goulash", emojis: "🍲🧅", level: "medium" },
  { id: "pierogi", title: "Pierogi", emojis: "🥟🧈", level: "medium" },
  { id: "borscht", title: "Borscht", emojis: "🥣🐄", level: "medium" },
  { id: "pelmeni", title: "Pelmeni", emojis: "🥟🧊", level: "medium" },
  { id: "khachapuri", title: "Khachapuri", emojis: "🧀🥣", level: "medium" },
  { id: "plov", title: "Plov", emojis: "🍚🐑", level: "medium" },
  { id: "manti", title: "Manti", emojis: "🥟🍶", level: "medium" },
  { id: "lahmacun", title: "Lahmacun", emojis: "🫓🍅", level: "medium" },
  { id: "muhammara", title: "Muhammara", emojis: "🫑🌰", level: "medium" },
  { id: "ful-medames", title: "Ful Medames", emojis: "🫘🍋", level: "medium" },
  { id: "koshari", title: "Koshari", emojis: "🍚🍅", level: "medium" },
  { id: "mansaf", title: "Mansaf", emojis: "🐑🥛", level: "medium" },
  { id: "kabsa", title: "Kabsa", emojis: "🐔🍚", level: "medium" },
  { id: "shakshuka", title: "Shakshuka", emojis: "🍳🍅", level: "medium" },
  { id: "currywurst", title: "Currywurst", emojis: "🌭🍛", level: "medium" },
  { id: "sauerbraten", title: "Sauerbraten", emojis: "🐄🍷", level: "medium" },
  { id: "moussaka", title: "Moussaka", emojis: "🍆🥩", level: "medium" },
  { id: "dolma", title: "Dolma", emojis: "🍇🍚", level: "medium" },
  { id: "baba-ganoush", title: "Baba Ganoush", emojis: "🍆🫒", level: "medium" },
  { id: "chana-masala", title: "Chana Masala", emojis: "🫘🍅", level: "medium" },
  { id: "rogan-josh", title: "Rogan Josh", emojis: "🐑🌶", level: "medium" },
  { id: "korma", title: "Korma", emojis: "🍛🥥", level: "medium" },
  { id: "dal-makhani", title: "Dal Makhani", emojis: "🫘🧈", level: "medium" },
  { id: "empanada", title: "Empanada", emojis: "🥟🍖", level: "medium" },
  { id: "ceviche", title: "Ceviche", emojis: "🐟🍋", level: "medium" },

  // ===== HARD (25) =====
  { id: "bulgogi", title: "Bulgogi", emojis: "🐄🍯", level: "hard" },
  { id: "japchae", title: "Japchae", emojis: "🍜🥕", level: "hard" },
  { id: "galbi", title: "Galbi", emojis: "🍖🍯", level: "hard" },
  { id: "kimbap", title: "Kimbap", emojis: "🍚🌿", level: "hard" },
  { id: "congee", title: "Congee", emojis: "🍚🫚", level: "hard" },
  { id: "laksa", title: "Laksa", emojis: "🍜🥥", level: "hard" },
  { id: "rendang", title: "Rendang", emojis: "🥩🥥", level: "hard" },
  { id: "gado-gado", title: "Gado-Gado", emojis: "🥗🥜", level: "hard" },
  { id: "khinkali", title: "Khinkali", emojis: "🥟🌶", level: "hard" },
  { id: "lomo-saltado", title: "Lomo Saltado", emojis: "🥩🍟", level: "hard" },
  { id: "anticuchos", title: "Anticuchos", emojis: "🥩🔥", level: "hard" },
  { id: "arepa", title: "Arepa", emojis: "🌽🧀", level: "hard" },
  { id: "pupusa", title: "Pupusa", emojis: "🫓🧀", level: "hard" },
  { id: "feijoada", title: "Feijoada", emojis: "🫘🐷", level: "hard" },
  { id: "khichdi", title: "Khichdi", emojis: "🍚🧅", level: "hard" },
  { id: "tagine", title: "Tagine", emojis: "🍲🍯", level: "hard" },
  { id: "merguez", title: "Merguez", emojis: "🌭🌶", level: "hard" },
  { id: "manakish", title: "Manakish", emojis: "🫓🌿", level: "hard" },
  { id: "tabbouleh", title: "Tabbouleh", emojis: "🍅🌾", level: "hard" },
  { id: "chorizo", title: "Chorizo", emojis: "🌭🧀", level: "hard" },
  { id: "cevapi", title: "Ćevapi", emojis: "🍢🧅", level: "hard" },
  { id: "khao-soi", title: "Khao Soi", emojis: "🍜🍗", level: "hard" },
  { id: "koobideh", title: "Koobideh", emojis: "🥩🥖", level: "hard" },
  { id: "fesenjan", title: "Fesenjan", emojis: "🍗🌰", level: "hard" },
  { id: "kibbeh", title: "Kibbeh", emojis: "🥩🍢", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "haggis", title: "Haggis", emojis: "🐑🌾", level: "impossible" },
  { id: "surstromming", title: "Surströmming", emojis: "🐟🧂", level: "impossible" },
  { id: "balut", title: "Balut", emojis: "🥚🐣", level: "impossible" },
  { id: "natto", title: "Natto", emojis: "🫘🥢", level: "impossible" },
  { id: "lutefisk", title: "Lutefisk", emojis: "🐟🥄", level: "impossible" },
  { id: "hakarl", title: "Hákarl", emojis: "🦈🧊", level: "impossible" },
  { id: "stinky-tofu", title: "Stinky Tofu", emojis: "🥣👃", level: "impossible" },
  { id: "drunken-shrimp", title: "Drunken Shrimp", emojis: "🦐🍷", level: "impossible" },
  { id: "morcilla", title: "Morcilla", emojis: "🩸🍚", level: "impossible" },
  { id: "mopane-worms", title: "Mopane Worms", emojis: "🐛🍢", level: "impossible" },
  { id: "sea-cucumber", title: "Sea Cucumber", emojis: "🥒🥢", level: "impossible" },
  { id: "blood-clam", title: "Blood Clam", emojis: "🐚🩸", level: "impossible" },
  { id: "kiviak", title: "Kiviak", emojis: "🐦🧊", level: "impossible" },
  { id: "turtle-soup", title: "Turtle Soup", emojis: "🐢🥣", level: "impossible" },
  { id: "khash", title: "Khash", emojis: "🐄🦶", level: "impossible" },
  { id: "tteok-guk", title: "Tteok-guk", emojis: "🍢🥣", level: "impossible" },
  { id: "otak-otak", title: "Otak-Otak", emojis: "🐟🍃", level: "impossible" },
  { id: "sikhae", title: "Sikhae", emojis: "🐟🍚", level: "impossible" },
  { id: "muktuk", title: "Muktuk", emojis: "🐋🧊", level: "impossible" },
  { id: "yak-butter-tea", title: "Yak Butter Tea", emojis: "🧈🍵", level: "impossible" },
  { id: "airag", title: "Airag", emojis: "🥛🐴", level: "impossible" },
  { id: "boodog", title: "Boodog", emojis: "🐐🔥", level: "impossible" },
  { id: "sop-buntut", title: "Sop Buntut", emojis: "🥣🦴", level: "impossible" },
  { id: "percebes", title: "Percebes", emojis: "🦐🪨", level: "impossible" },
  { id: "kvass", title: "Kvass", emojis: "🍞🍺", level: "impossible" },
];
