// E190 «Guess the Food by Emoji 4» — 100 dishes · 25/tier
// VO: sfx/e190-<id>.wav
export const FOOD_EMOJI_4 = [
  // ===== EASY (25) =====
  { id: "chicken-shawarma", title: "Chicken Shawarma", emojis: "🥙🍗", level: "easy" },
  { id: "margherita-pizza", title: "Margherita Pizza", emojis: "🍕🌿", level: "easy" },
  { id: "peking-duck", title: "Peking Duck", emojis: "🦆🥢", level: "easy" },
  { id: "chicken-katsu", title: "Chicken Katsu", emojis: "🍗🍞", level: "easy" },
  { id: "sashimi", title: "Sashimi", emojis: "🐟🔪", level: "easy" },
  { id: "nigiri", title: "Nigiri", emojis: "🍣🦐", level: "easy" },
  { id: "california-roll", title: "California Roll", emojis: "🥑🍚", level: "easy" },
  { id: "poke-bowl", title: "Poke Bowl", emojis: "🐟🥣", level: "easy" },
  { id: "chow-mein", title: "Chow Mein", emojis: "🍜🥢", level: "easy" },
  { id: "fried-wontons", title: "Fried Wontons", emojis: "🥟🔥", level: "easy" },
  { id: "club-sandwich", title: "Club Sandwich", emojis: "🥪🦃", level: "easy" },
  { id: "blt-sandwich", title: "BLT Sandwich", emojis: "🥪🥓", level: "easy" },
  { id: "tuna-sandwich", title: "Tuna Sandwich", emojis: "🥪🐟", level: "easy" },
  { id: "egg-salad-sandwich", title: "Egg Salad Sandwich", emojis: "🥪🥚", level: "easy" },
  { id: "pork-chops", title: "Pork Chops", emojis: "🐷🍖", level: "easy" },
  { id: "lamb-chops", title: "Lamb Chops", emojis: "🐑🍖", level: "easy" },
  { id: "prawn-skewers", title: "Prawn Skewers", emojis: "🦐🍢", level: "easy" },
  { id: "veggie-stir-fry", title: "Vegetable Stir Fry", emojis: "🥦🥕", level: "easy" },
  { id: "sweet-potato-fries", title: "Sweet Potato Fries", emojis: "🍠🍟", level: "easy" },
  { id: "chicken-caesar-wrap", title: "Chicken Caesar Wrap", emojis: "🌯🥬", level: "easy" },
  { id: "shrimp-scampi", title: "Shrimp Scampi", emojis: "🦐🧈", level: "easy" },
  { id: "beef-stroganoff", title: "Beef Stroganoff", emojis: "🥩🍄", level: "easy" },
  { id: "chicken-parmesan", title: "Chicken Parmesan", emojis: "🍗🧀", level: "easy" },
  { id: "caprese-salad", title: "Caprese Salad", emojis: "🍅🧀", level: "easy" },
  { id: "fettuccine-alfredo", title: "Fettuccine Alfredo", emojis: "🍝🧈", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "steak-quesadilla", title: "Steak Quesadilla", emojis: "🫓🥩", level: "medium" },
  { id: "chicken-marsala", title: "Chicken Marsala", emojis: "🍗🍄", level: "medium" },
  { id: "veal-piccata", title: "Veal Piccata", emojis: "🍋🥩", level: "medium" },
  { id: "osso-buco", title: "Osso Buco", emojis: "🥩🦴", level: "medium" },
  { id: "saltimbocca", title: "Saltimbocca", emojis: "🐷🌿", level: "medium" },
  { id: "arancini", title: "Arancini", emojis: "🍚🧀", level: "medium" },
  { id: "panzanella", title: "Panzanella", emojis: "🍞🍅", level: "medium" },
  { id: "minestrone", title: "Minestrone", emojis: "🍅🥕", level: "medium" },
  { id: "polenta", title: "Polenta", emojis: "🌽🥣", level: "medium" },
  { id: "ravioli", title: "Ravioli", emojis: "🥟🧀", level: "medium" },
  { id: "tortellini", title: "Tortellini", emojis: "🍝🥩", level: "medium" },
  { id: "cacio-e-pepe", title: "Cacio e Pepe", emojis: "🍝🧂", level: "medium" },
  { id: "aglio-e-olio", title: "Aglio e Olio", emojis: "🍝🧄", level: "medium" },
  { id: "puttanesca", title: "Puttanesca", emojis: "🍝🫒", level: "medium" },
  { id: "vitello-tonnato", title: "Vitello Tonnato", emojis: "🥩🐟", level: "medium" },
  { id: "prosciutto-e-melone", title: "Prosciutto and Melon", emojis: "🍈🥓", level: "medium" },
  { id: "duck-confit", title: "Duck Confit", emojis: "🦆🧈", level: "medium" },
  { id: "steak-tartare", title: "Steak Tartare", emojis: "🥩🔪", level: "medium" },
  { id: "beef-carpaccio", title: "Beef Carpaccio", emojis: "🥩🫒", level: "medium" },
  { id: "french-onion-soup", title: "French Onion Soup", emojis: "🧅🥣", level: "medium" },
  { id: "croque-madame", title: "Croque Madame", emojis: "🥪🍳", level: "medium" },
  { id: "chicken-kiev", title: "Chicken Kiev", emojis: "🍗🧈", level: "medium" },
  { id: "chicken-cordon-bleu", title: "Chicken Cordon Bleu", emojis: "🍗🥓", level: "medium" },
  { id: "moules-frites", title: "Moules Frites", emojis: "🦪🍟", level: "medium" },
  { id: "katsu-curry", title: "Katsu Curry", emojis: "🍛🍞", level: "medium" },

  // ===== HARD (25) =====
  { id: "tlayuda", title: "Tlayuda", emojis: "🫓🥑", level: "hard" },
  { id: "sopes", title: "Sopes", emojis: "🫓🧅", level: "hard" },
  { id: "aguachile", title: "Aguachile", emojis: "🦐🍋", level: "hard" },
  { id: "picanha", title: "Picanha", emojis: "🥩🧂", level: "hard" },
  { id: "coxinha", title: "Coxinha", emojis: "🍗🥟", level: "hard" },
  { id: "pao-de-queijo", title: "Pão de Queijo", emojis: "🧀🥖", level: "hard" },
  { id: "moqueca", title: "Moqueca", emojis: "🐟🥥", level: "hard" },
  { id: "choripan", title: "Choripan", emojis: "🌭🥖", level: "hard" },
  { id: "asado", title: "Asado", emojis: "🥩🍷", level: "hard" },
  { id: "bunny-chow", title: "Bunny Chow", emojis: "🍞🍲", level: "hard" },
  { id: "biltong", title: "Biltong", emojis: "🥩🌬", level: "hard" },
  { id: "potjiekos", title: "Potjiekos", emojis: "🍲🔥", level: "hard" },
  { id: "doro-wat", title: "Doro Wat", emojis: "🍗🫓", level: "hard" },
  { id: "kitfo", title: "Kitfo", emojis: "🥩🌶", level: "hard" },
  { id: "jollof-rice", title: "Jollof Rice", emojis: "🍚🌶", level: "hard" },
  { id: "suya", title: "Suya", emojis: "🥩🥜", level: "hard" },
  { id: "egusi-soup", title: "Egusi Soup", emojis: "🍲🥜", level: "hard" },
  { id: "waakye", title: "Waakye", emojis: "🍚🫘", level: "hard" },
  { id: "kelewele", title: "Kelewele", emojis: "🍌🌶", level: "hard" },
  { id: "attieke", title: "Attieke", emojis: "🐟🌾", level: "hard" },
  { id: "thieboudienne", title: "Thieboudienne", emojis: "🐟🍆", level: "hard" },
  { id: "chicken-yassa", title: "Chicken Yassa", emojis: "🍗🍋", level: "hard" },
  { id: "maafe", title: "Maafe", emojis: "🍗🥜", level: "hard" },
  { id: "couscous-royale", title: "Couscous Royale", emojis: "🌾🍗", level: "hard" },
  { id: "harira", title: "Harira", emojis: "🍲🍅", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "stargazy-pie", title: "Stargazy Pie", emojis: "🐟🥧", level: "impossible" },
  { id: "callos", title: "Callos", emojis: "🐄🍲", level: "impossible" },
  { id: "basashi", title: "Basashi", emojis: "🐴🔪", level: "impossible" },
  { id: "escamoles", title: "Escamoles", emojis: "🐜🫔", level: "impossible" },
  { id: "chapulines", title: "Chapulines", emojis: "🦗🌶", level: "impossible" },
  { id: "witchetty-grub", title: "Witchetty Grub", emojis: "🐛🔥", level: "impossible" },
  { id: "hongeohoe", title: "Hongeohoe", emojis: "🐟🤢", level: "impossible" },
  { id: "fugu", title: "Fugu", emojis: "🐡☠", level: "impossible" },
  { id: "sannakji", title: "Sannakji", emojis: "🐙🥢", level: "impossible" },
  { id: "pigs-feet", title: "Pig's Feet", emojis: "🐷🦶", level: "impossible" },
  { id: "chicken-feet", title: "Chicken Feet", emojis: "🐔🦶", level: "impossible" },
  { id: "beondegi", title: "Beondegi", emojis: "🐛🥣", level: "impossible" },
  { id: "andouillette", title: "Andouillette", emojis: "🐄🍖", level: "impossible" },
  { id: "birds-nest-soup", title: "Bird's Nest Soup", emojis: "🥣🐦", level: "impossible" },
  { id: "shark-fin-soup", title: "Shark Fin Soup", emojis: "🦈🥣", level: "impossible" },
  { id: "snake-soup", title: "Snake Soup", emojis: "🐍🥣", level: "impossible" },
  { id: "fried-tarantula", title: "Fried Tarantula", emojis: "🕷🍟", level: "impossible" },
  { id: "jellyfish-salad", title: "Jellyfish Salad", emojis: "🪼🥗", level: "impossible" },
  { id: "jamon-iberico", title: "Jamón Ibérico", emojis: "🐷🌰", level: "impossible" },
  { id: "foie-gras", title: "Foie Gras", emojis: "🦆🍷", level: "impossible" },
  { id: "ant-egg-soup", title: "Ant Egg Soup", emojis: "🐜🥣", level: "impossible" },
  { id: "scorpion-skewers", title: "Scorpion Skewers", emojis: "🦂🍢", level: "impossible" },
  { id: "cuy", title: "Cuy (Roasted Guinea Pig)", emojis: "🐹🔥", level: "impossible" },
  { id: "locro", title: "Locro", emojis: "🥔🥣", level: "impossible" },
  { id: "reindeer-stew", title: "Reindeer Stew", emojis: "🦌🍲", level: "impossible" },
];
