// E247 «Guess the Food by Emoji 7» — facts, ≤70 chars, one per id
export const FOOD_EMOJI7_FACTS = {
  "bacon": "Bacon comes from cured pork belly or back cuts.",
  "turkey-dinner": "Roast turkey is the centerpiece of US Thanksgiving.",
  "meat-pie": "Meat pies date back to ancient Egyptian and Roman cooking.",
  "roast-beef": "Roast beef became England's Sunday roast tradition.",
  "cheese-toastie": "A cheese toastie is grilled bread with melted cheese inside.",
  "veggie-burger": "The VegeBurger launched in 1982 in London, UK.",
  "fish-burger": "The Filet-O-Fish was created for Catholic Fridays in 1962.",
  "shrimp-tacos": "Baja shrimp tacos originated on Mexico's Pacific coast.",
  "steak-tacos": "Tacos de carne asada use grilled, chopped steak.",
  "chicken-wrap": "Wraps became a fast-food staple in the 1990s US.",
  "baked-beans": "Boston baked beans are slow-cooked with molasses.",
  "boiled-egg": "A boiled egg cooks fully in about 9 to 12 minutes.",
  "yogurt-parfait": "Parfait means 'perfect' in French, for layered desserts.",
  "granola-bowl": "Granola was invented in New York in the 1860s.",
  "oatmeal": "Oats were a staple grain in ancient Scotland.",
  "banana-pancakes": "Banana pancakes are a Southeast Asia backpacker classic.",
  "blueberry-pancakes": "Wild blueberries are native to North America.",
  "chocolate-pancakes": "Cocoa was first cultivated by Mesoamerican civilizations.",
  "honey-toast": "Honey toast is a popular Japanese dessert cafe dish.",
  "peanut-butter-toast": "Peanut butter was patented in the US in 1884.",
  "grilled-corn": "Elote is Mexican grilled corn with mayo and chili.",
  "rice-and-beans": "Rice and beans is a staple across Latin America.",
  "egg-fried-rice": "Egg fried rice began as a way to use leftover rice.",
  "cheese-platter": "France alone produces over 1,000 named cheese varieties.",
  "fruit-tart": "French fruit tarts use a pastry cream base called crème pâtissière.",
  "lentil-soup": "Lentils are among the oldest cultivated legumes on Earth.",
  "pumpkin-soup": "Pumpkin soup is popular across Europe in autumn.",
  "corn-chowder": "Chowder gets its name from the French word chaudière.",
  "potato-soup": "Potato soup is a German and Irish comfort food staple.",
  "vegetable-soup": "Minestrone-style vegetable soups date to ancient Rome.",
  "grilled-octopus": "Grilled octopus is a staple of Greek taverna menus.",
  "garlic-shrimp": "Gambas al ajillo is a classic Spanish tapas dish.",
  "lemon-chicken": "Lemon chicken is a popular Cantonese restaurant dish.",
  "honey-glazed-ham": "Honey-baked ham is a US holiday centerpiece dish.",
  "duck-breast": "Duck breast is often served pan-seared, skin-side down.",
  "crab-cakes": "Maryland crab cakes use blue crab and little filler.",
  "lobster-tail": "Lobster was once so common it fed prisoners in colonial US.",
  "oyster-stew": "Oyster stew is a traditional US Christmas Eve dish.",
  "squid-ink-pasta": "Squid ink pasta gets its black color from cephalopod ink.",
  "mango-salsa": "Mango salsa pairs tropical fruit with chili and lime.",
  "avocado-toast": "Avocado toast became a cafe trend in the 2010s.",
  "stuffed-peppers": "Stuffed peppers appear in Balkan, Mexican, and US kitchens.",
  "pickled-vegetables": "Pickling preserves vegetables in salt or vinegar brine.",
  "garlic-noodles": "Garlic noodles rose to fame at San Francisco's Thanh Long.",
  "peanut-noodles": "Cold peanut noodles are a Sichuan-inspired dish.",
  "onion-tart": "Alsatian onion tart, tarte à l'oignon, uses a custard base.",
  "grilled-squid": "Grilled squid is a common Mediterranean seafood dish.",
  "prawn-curry": "Prawn curry is a coastal favorite across South Asia.",
  "beef-curry": "Japanese beef curry became popular after British influence.",
  "vegetable-curry": "Vegetable curry varies widely by region across South Asia.",
  "momos": "Momos are steamed dumplings from Tibet and Nepal.",
  "thukpa": "Thukpa is a Tibetan noodle soup often eaten in winter.",
  "mohinga": "Mohinga is often called Myanmar's national dish.",
  "laphet": "Laphet is Myanmar's fermented tea leaf salad.",
  "rasam": "Rasam is a tangy, peppery South Indian soup.",
  "sambar": "Sambar blends lentils with tamarind and vegetables.",
  "paneer-tikka": "Paneer tikka is marinated cheese grilled in a tandoor.",
  "litti-chokha": "Litti chokha is a Bihar dish of wheat balls and mashed veg.",
  "dhansak": "Dhansak blends lentils and meat in Parsi cuisine.",
  "idiyappam": "Idiyappam is steamed rice noodles shaped into disks.",
  "appam": "Appam is a South Indian pancake with a fermented rice batter.",
  "bo-kho": "Bo kho is a Vietnamese beef stew with warm spices.",
  "hu-tieu": "Hu tieu is a noodle soup popular in southern Vietnam.",
  "ca-kho-to": "Ca kho to is fish caramelized in a Vietnamese clay pot.",
  "bicol-express": "Bicol express is a spicy Filipino pork and coconut stew.",
  "pinakbet": "Pinakbet is a Filipino vegetable dish with shrimp paste.",
  "kaldereta": "Kaldereta is a Filipino stew often made with goat meat.",
  "nasi-padang": "Nasi padang serves many dishes buffet-style over rice.",
  "ketoprak": "Ketoprak is a Jakarta street dish with peanut sauce.",
  "bakmi": "Bakmi is an Indonesian noodle dish of Chinese origin.",
  "murtabak": "Murtabak is a stuffed, pan-fried flatbread from Southeast Asia.",
  "roti-john": "Roti John is a Singaporean egg and meat sandwich.",
  "ayam-goreng": "Ayam goreng is Indonesian and Malaysian fried chicken.",
  "banku": "Banku is a fermented corn and cassava dough from Ghana.",
  "kenkey": "Kenkey is a fermented corn dumpling eaten in Ghana.",
  "kopi-luwak": "Kopi luwak beans pass through a civet before roasting.",
  "nem-chua": "Nem chua is Vietnamese fermented pork wrapped in leaves.",
  "stinkhead": "Stinkhead is fermented salmon heads eaten in Alaska.",
  "fried-locusts": "Fried locusts are a protein-rich snack in parts of Africa.",
  "kangaroo-tail-stew": "Kangaroo tail stew is a traditional Aboriginal Australian dish.",
  "huhu-grub": "Huhu grub is a beetle larva eaten by New Zealand Maori.",
  "douzhi": "Douzhi is a fermented mung bean drink from Beijing.",
  "bagoong": "Bagoong is Filipino fermented shrimp or fish paste.",
  "garum": "Garum was a fermented fish sauce prized in ancient Rome.",
  "sambal-petai": "Sambal petai pairs chili paste with pungent stink beans.",
  "salted-duck-egg": "Salted duck eggs are cured in brine for weeks.",
  "preserved-lemons": "Preserved lemons are salt-cured in Moroccan cooking.",
  "duck-blood-soup": "Duck blood soup is a Taiwanese night-market staple.",
  "pickled-herring": "Pickled herring is a Nordic and Baltic holiday staple.",
  "tripe-soup": "Tripe soup is made from the lining of a cow's stomach.",
  "bheja-fry": "Bheja fry is a spiced South Asian goat-brain curry.",
  "snake-wine": "Snake wine steeps a whole snake in rice liquor.",
  "yak-butter-tea": "Yak butter tea is a salty staple across the Himalayas.",
  "kumis": "Kumis is fermented mare's milk from Central Asia.",
  "chicha-de-jora": "Chicha de jora is a traditional fermented Andean corn beer.",
  "fried-piranha": "Fried piranha is eaten along parts of the Amazon River.",
  "giant-water-bug": "Fried giant water bugs are a crunchy Thai street snack.",
  "suri-larvae": "Suri larvae are palm weevil grubs eaten in the Amazon.",
  "mannish-water": "Mannish water is a Jamaican goat-head soup.",
  "tete-de-veau": "Tête de veau is a classic French calf's-head dish.",
};
