// «Guess the Dish» — GuessSync · World Foods v2 · 100 iconic savory dishes (25/tier) · real photos from Wikimedia Commons
// Second food episode (repeat-the-winner). ANSWER = the DISH name. Zero overlap with E14 foods / E21 fruits /
// desserts / breads / pasta / cheeses / cocktails / drinks. No Israeli national dishes (standing rule).
// Absolute difficulty by global recognisability: easy (Fried Rice/Kebab/Curry) ← impossible (Ghormeh Sabzi/Rawon/Cullen Skink).
export const FOODS2 = [
  // EASY (25) — savory dishes almost everyone recognizes on a plate
  { slug: "friedrice", name: "Fried Rice", level: "easy" },
  { slug: "chowmein", name: "Chow Mein", level: "easy" },
  { slug: "chickencurry", name: "Chicken Curry", level: "easy" },
  { slug: "kebab", name: "Kebab", level: "easy" },
  { slug: "shawarma", name: "Shawarma", level: "easy" },
  { slug: "macandcheese", name: "Mac and Cheese", level: "easy" },
  { slug: "meatballs", name: "Meatballs", level: "easy" },
  { slug: "chickenwings", name: "Chicken Wings", level: "easy" },
  { slug: "caesarsalad", name: "Caesar Salad", level: "easy" },
  { slug: "greeksalad", name: "Greek Salad", level: "easy" },
  { slug: "mashedpotatoes", name: "Mashed Potatoes", level: "easy" },
  { slug: "roastchicken", name: "Roast Chicken", level: "easy" },
  { slug: "omelette", name: "Omelette", level: "easy" },
  { slug: "clubsandwich", name: "Club Sandwich", level: "easy" },
  { slug: "bbqribs", name: "BBQ Ribs", level: "easy" },
  { slug: "chickennuggets", name: "Chicken Nuggets", level: "easy" },
  { slug: "coleslaw", name: "Coleslaw", level: "easy" },
  { slug: "quiche", name: "Quiche", level: "easy" },
  { slug: "friedcalamari", name: "Fried Calamari", level: "easy" },
  { slug: "baconandeggs", name: "Bacon and Eggs", level: "easy" },
  { slug: "meatloaf", name: "Meatloaf", level: "easy" },
  { slug: "porkchop", name: "Pork Chop", level: "easy" },
  { slug: "chili", name: "Chili con Carne", level: "easy" },
  { slug: "misosoup", name: "Miso Soup", level: "easy" },
  { slug: "kimchi", name: "Kimchi", level: "easy" },
  // MEDIUM (25) — well known, one step past the classics
  { slug: "wontonsoup", name: "Wonton Soup", level: "medium" },
  { slug: "schnitzel", name: "Schnitzel", level: "medium" },
  { slug: "goulash", name: "Goulash", level: "medium" },
  { slug: "carbonara", name: "Carbonara", level: "medium" },
  { slug: "kungpao", name: "Kung Pao Chicken", level: "medium" },
  { slug: "sweetandsour", name: "Sweet and Sour Pork", level: "medium" },
  { slug: "pekingduck", name: "Peking Duck", level: "medium" },
  { slug: "dimsum", name: "Dim Sum", level: "medium" },
  { slug: "tempura", name: "Tempura", level: "medium" },
  { slug: "teriyaki", name: "Teriyaki Chicken", level: "medium" },
  { slug: "bulgogi", name: "Bulgogi", level: "medium" },
  { slug: "butterchicken", name: "Butter Chicken", level: "medium" },
  { slug: "biryani", name: "Biryani", level: "medium" },
  { slug: "enchilada", name: "Enchilada", level: "medium" },
  { slug: "fajitas", name: "Fajitas", level: "medium" },
  { slug: "tamale", name: "Tamale", level: "medium" },
  { slug: "gumbo", name: "Gumbo", level: "medium" },
  { slug: "jambalaya", name: "Jambalaya", level: "medium" },
  { slug: "clamchowder", name: "Clam Chowder", level: "medium" },
  { slug: "philly", name: "Philly Cheesesteak", level: "medium" },
  { slug: "souvlaki", name: "Souvlaki", level: "medium" },
  { slug: "spanakopita", name: "Spanakopita", level: "medium" },
  { slug: "calzone", name: "Calzone", level: "medium" },
  { slug: "minestrone", name: "Minestrone", level: "medium" },
  { slug: "gazpacho", name: "Gazpacho", level: "medium" },
  // HARD (25) — regional, foodie territory
  { slug: "currywurst", name: "Currywurst", level: "hard" },
  { slug: "yakitori", name: "Yakitori", level: "hard" },
  { slug: "japchae", name: "Japchae", level: "hard" },
  { slug: "laksa", name: "Laksa", level: "hard" },
  { slug: "nasigoreng", name: "Nasi Goreng", level: "hard" },
  { slug: "satay", name: "Satay", level: "hard" },
  { slug: "tomyum", name: "Tom Yum", level: "hard" },
  { slug: "greencurry", name: "Green Curry", level: "hard" },
  { slug: "massaman", name: "Massaman Curry", level: "hard" },
  { slug: "vindaloo", name: "Vindaloo", level: "hard" },
  { slug: "roganjosh", name: "Rogan Josh", level: "hard" },
  { slug: "dosa", name: "Masala Dosa", level: "hard" },
  { slug: "congee", name: "Congee", level: "hard" },
  { slug: "pelmeni", name: "Pelmeni", level: "hard" },
  { slug: "bratwurst", name: "Bratwurst", level: "hard" },
  { slug: "cassoulet", name: "Cassoulet", level: "hard" },
  { slug: "coqauvin", name: "Coq au Vin", level: "hard" },
  { slug: "bouillabaisse", name: "Bouillabaisse", level: "hard" },
  { slug: "croquemonsieur", name: "Croque Monsieur", level: "hard" },
  { slug: "escargot", name: "Escargot", level: "hard" },
  { slug: "chilaquiles", name: "Chilaquiles", level: "hard" },
  { slug: "pozole", name: "Pozole", level: "hard" },
  { slug: "feijoada", name: "Feijoada", level: "hard" },
  { slug: "galbi", name: "Galbi", level: "hard" },
  { slug: "padseeew", name: "Pad See Ew", level: "hard" },
  // IMPOSSIBLE (25) — obscure regional dishes
  { slug: "khaosoi", name: "Khao Soi", level: "impossible" },
  { slug: "banhxeo", name: "Banh Xeo", level: "impossible" },
  { slug: "bunbohue", name: "Bun Bo Hue", level: "impossible" },
  { slug: "rawon", name: "Rawon", level: "impossible" },
  { slug: "sotoayam", name: "Soto Ayam", level: "impossible" },
  { slug: "nasilemak", name: "Nasi Lemak", level: "impossible" },
  { slug: "charkwayteow", name: "Char Kway Teow", level: "impossible" },
  { slug: "hainanchicken", name: "Hainanese Chicken", level: "impossible" },
  { slug: "mansaf", name: "Mansaf", level: "impossible" },
  { slug: "maqluba", name: "Maqluba", level: "impossible" },
  { slug: "kabsa", name: "Kabsa", level: "impossible" },
  { slug: "mandi", name: "Mandi", level: "impossible" },
  { slug: "fesenjan", name: "Fesenjan", level: "impossible" },
  { slug: "ghormehsabzi", name: "Ghormeh Sabzi", level: "impossible" },
  { slug: "kibbeh", name: "Kibbeh", level: "impossible" },
  { slug: "mujadara", name: "Mujadara", level: "impossible" },
  { slug: "bobotie", name: "Bobotie", level: "impossible" },
  { slug: "bigos", name: "Bigos", level: "impossible" },
  { slug: "golabki", name: "Golabki", level: "impossible" },
  { slug: "janssons", name: "Janssons Temptation", level: "impossible" },
  { slug: "frikadeller", name: "Frikadeller", level: "impossible" },
  { slug: "maultaschen", name: "Maultaschen", level: "impossible" },
  { slug: "sauerbraten", name: "Sauerbraten", level: "impossible" },
  { slug: "stamppot", name: "Stamppot", level: "impossible" },
  { slug: "cullenskink", name: "Cullen Skink", level: "impossible" },
];
export const FOODS2_LEVELS = ["easy", "medium", "hard", "impossible"];
