// E130 «Guess the Food by Emoji 2» — 100 foods · 25/tier · clue via OpenMoji · VO: sfx/ef2-<id>.wav
export const FOOD_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "cheeseburger", title: "Cheeseburger", emojis: "🍔🧀", level: "easy" },
  { id: "fish-and-chips", title: "Fish and Chips", emojis: "🐟🍟", level: "easy" },
  { id: "mac-and-cheese", title: "Mac and Cheese", emojis: "🍝🧀", level: "easy" },
  { id: "apple-pie", title: "Apple Pie", emojis: "🍎🍰", level: "easy" },
  { id: "chocolate-cake", title: "Chocolate Cake", emojis: "🍫🎂", level: "easy" },
  { id: "scrambled-eggs", title: "Scrambled Eggs", emojis: "🥚🍳", level: "easy" },
  { id: "fried-rice", title: "Fried Rice", emojis: "🍚🍳", level: "easy" },
  { id: "grilled-cheese", title: "Grilled Cheese Sandwich", emojis: "🧀🥪", level: "easy" },
  { id: "milkshake", title: "Milkshake", emojis: "🥛🥤", level: "easy" },
  { id: "hot-chocolate", title: "Hot Chocolate", emojis: "🍫☕", level: "easy" },
  { id: "buffalo-wings", title: "Buffalo Wings", emojis: "🍗🌶", level: "easy" },
  { id: "onion-rings", title: "Onion Rings", emojis: "🧅🍟", level: "easy" },
  { id: "coleslaw", title: "Coleslaw", emojis: "🥬🥕", level: "easy" },
  { id: "corn-on-the-cob", title: "Corn on the Cob", emojis: "🌽🔥", level: "easy" },
  { id: "mashed-potatoes", title: "Mashed Potatoes", emojis: "🥔🥛", level: "easy" },
  { id: "baked-potato", title: "Baked Potato", emojis: "🥔🧀", level: "easy" },
  { id: "french-toast", title: "French Toast", emojis: "🍞🥚", level: "easy" },
  { id: "pb-sandwich", title: "Peanut Butter Sandwich", emojis: "🥪🥜", level: "easy" },
  { id: "fruit-salad", title: "Fruit Salad", emojis: "🍇🍓", level: "easy" },
  { id: "meatloaf", title: "Meatloaf", emojis: "🥩🍞", level: "easy" },
  { id: "spring-rolls", title: "Spring Rolls", emojis: "🥬🥢", level: "easy" },
  { id: "deviled-eggs", title: "Deviled Eggs", emojis: "🥚🌶", level: "easy" },
  { id: "potato-chips", title: "Potato Chips", emojis: "🥔🧂", level: "easy" },
  { id: "naan-bread", title: "Naan Bread", emojis: "🫓🔥", level: "easy" },
  { id: "caesar-salad", title: "Caesar Salad", emojis: "🥗🧀", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "carbonara", title: "Spaghetti Carbonara", emojis: "🍝🥓🥚", level: "medium" },
  { id: "bolognese", title: "Spaghetti Bolognese", emojis: "🍝🥩🧀", level: "medium" },
  { id: "chicken-tikka-masala", title: "Chicken Tikka Masala", emojis: "🍗🔥🍅", level: "medium" },
  { id: "butter-chicken", title: "Butter Chicken", emojis: "🍗🍅🥛", level: "medium" },
  { id: "miso-soup", title: "Miso Soup", emojis: "🍵🥣", level: "medium" },
  { id: "tonkatsu", title: "Tonkatsu", emojis: "🐷🍞🥢", level: "medium" },
  { id: "takoyaki", title: "Takoyaki", emojis: "🐙🥟", level: "medium" },
  { id: "onigiri", title: "Onigiri", emojis: "🍚🔺🌿", level: "medium" },
  { id: "udon", title: "Udon Noodles", emojis: "🍜🍢", level: "medium" },
  { id: "croque-monsieur", title: "Croque Monsieur", emojis: "🍞🧀🥓", level: "medium" },
  { id: "waldorf-salad", title: "Waldorf Salad", emojis: "🍎🥜🥗", level: "medium" },
  { id: "cobb-salad", title: "Cobb Salad", emojis: "🥗🥚🥓", level: "medium" },
  { id: "reuben-sandwich", title: "Reuben Sandwich", emojis: "🥪🥩🧀", level: "medium" },
  { id: "philly-cheesesteak", title: "Philly Cheesesteak", emojis: "🥖🥩🧀", level: "medium" },
  { id: "corn-dog", title: "Corn Dog", emojis: "🌭🌽", level: "medium" },
  { id: "sloppy-joe", title: "Sloppy Joe", emojis: "🥪🥩🍅", level: "medium" },
  { id: "fajitas", title: "Fajitas", emojis: "🌶🧅🥩", level: "medium" },
  { id: "enchiladas", title: "Enchiladas", emojis: "🌯🌶🧀", level: "medium" },
  { id: "escargot", title: "Escargot", emojis: "🐌🥖", level: "medium" },
  { id: "cheese-fondue", title: "Cheese Fondue", emojis: "🧀🍞🔥", level: "medium" },
  { id: "bruschetta", title: "Bruschetta", emojis: "🍞🍅🌿", level: "medium" },
  { id: "focaccia", title: "Focaccia", emojis: "🍞🫒", level: "medium" },
  { id: "gazpacho", title: "Gazpacho", emojis: "🍅🥣🧊", level: "medium" },
  { id: "beef-wellington", title: "Beef Wellington", emojis: "🥩🥖🍄", level: "medium" },
  { id: "scotch-egg", title: "Scotch Egg", emojis: "🥚🥩🍞", level: "medium" },

  // ===== HARD (25) =====
  { id: "coq-au-vin", title: "Coq au Vin", emojis: "🐔🍷", level: "hard" },
  { id: "beef-bourguignon", title: "Beef Bourguignon", emojis: "🥩🍷🥕", level: "hard" },
  { id: "shepherds-pie", title: "Shepherd's Pie", emojis: "🐑🥔", level: "hard" },
  { id: "cottage-pie", title: "Cottage Pie", emojis: "🐄🥔", level: "hard" },
  { id: "bangers-and-mash", title: "Bangers and Mash", emojis: "🌭🥔", level: "hard" },
  { id: "toad-in-the-hole", title: "Toad in the Hole", emojis: "🌭🍞", level: "hard" },
  { id: "cornish-pasty", title: "Cornish Pasty", emojis: "🥟🥩🥔", level: "hard" },
  { id: "yorkshire-pudding", title: "Yorkshire Pudding", emojis: "🎈🍞", level: "hard" },
  { id: "spanakopita", title: "Spanakopita", emojis: "🥬🧀🥐", level: "hard" },
  { id: "souvlaki", title: "Souvlaki", emojis: "🍢🥙", level: "hard" },
  { id: "hainanese-chicken-rice", title: "Hainanese Chicken Rice", emojis: "🍗🍚🥒", level: "hard" },
  { id: "nasi-goreng", title: "Nasi Goreng", emojis: "🍚🌶🥚", level: "hard" },
  { id: "char-kway-teow", title: "Char Kway Teow", emojis: "🍜🦐🥚", level: "hard" },
  { id: "vindaloo", title: "Vindaloo", emojis: "🌶🥩🍛", level: "hard" },
  { id: "saag-paneer", title: "Saag Paneer", emojis: "🥬🧀", level: "hard" },
  { id: "chicken-65", title: "Chicken 65", emojis: "🍗🌶🍋", level: "hard" },
  { id: "dal-tadka", title: "Dal Tadka", emojis: "🫘🌶", level: "hard" },
  { id: "kofta", title: "Kofta", emojis: "🥩🍢", level: "hard" },
  { id: "gyoza", title: "Gyoza", emojis: "🥟🐷", level: "hard" },
  { id: "char-siu", title: "Char Siu", emojis: "🐷🍯", level: "hard" },
  { id: "kung-pao-chicken", title: "Kung Pao Chicken", emojis: "🍗🌶🥜", level: "hard" },
  { id: "mapo-tofu", title: "Mapo Tofu", emojis: "🌶🥣🐷", level: "hard" },
  { id: "sweet-and-sour-pork", title: "Sweet and Sour Pork", emojis: "🐷🍍", level: "hard" },
  { id: "general-tsos-chicken", title: "General Tso's Chicken", emojis: "🍗🌶🍯", level: "hard" },
  { id: "egg-drop-soup", title: "Egg Drop Soup", emojis: "🥚🥣", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "century-egg", title: "Century Egg", emojis: "🥚⚫", level: "impossible" },
  { id: "casu-marzu", title: "Casu Marzu", emojis: "🧀🐛", level: "impossible" },
  { id: "kare-kare", title: "Kare-Kare", emojis: "🥩🥜🍆", level: "impossible" },
  { id: "sinigang", title: "Sinigang", emojis: "🍅🥣🐟", level: "impossible" },
  { id: "chicken-adobo", title: "Chicken Adobo", emojis: "🍗🍶🍁", level: "impossible" },
  { id: "lechon", title: "Lechon", emojis: "🐷🔥", level: "impossible" },
  { id: "tteokbokki", title: "Tteokbokki", emojis: "🍢🌶", level: "impossible" },
  { id: "soondae", title: "Soondae", emojis: "🌭🩸", level: "impossible" },
  { id: "kaya-toast", title: "Kaya Toast", emojis: "🍞🥥🍯", level: "impossible" },
  { id: "rojak", title: "Rojak", emojis: "🍍🥒🌶", level: "impossible" },
  { id: "nasi-lemak", title: "Nasi Lemak", emojis: "🍚🥥🌶", level: "impossible" },
  { id: "laverbread", title: "Laverbread", emojis: "🌿🍞", level: "impossible" },
  { id: "eton-mess", title: "Eton Mess", emojis: "🍓🍦", level: "impossible" },
  { id: "jellied-eels", title: "Jellied Eels", emojis: "🐟🧊", level: "impossible" },
  { id: "black-pudding", title: "Black Pudding", emojis: "🐷🩸", level: "impossible" },
  { id: "menudo", title: "Menudo", emojis: "🐄🥣🌶", level: "impossible" },
  { id: "mole-poblano", title: "Mole Poblano", emojis: "🍫🌶🍗", level: "impossible" },
  { id: "huitlacoche", title: "Huitlacoche", emojis: "🌽🍄", level: "impossible" },
  { id: "kaymak", title: "Kaymak", emojis: "🥛🍯", level: "impossible" },
  { id: "fish-head-curry", title: "Fish Head Curry", emojis: "🐟🍛🌶", level: "impossible" },
  { id: "salo", title: "Salo", emojis: "🐷🧂", level: "impossible" },
  { id: "chicharron", title: "Chicharron", emojis: "🐷🍟", level: "impossible" },
  { id: "head-cheese", title: "Head Cheese", emojis: "🐷🧊", level: "impossible" },
  { id: "kibbeh-nayyeh", title: "Kibbeh Nayyeh", emojis: "🥩🌾", level: "impossible" },
  { id: "umeboshi", title: "Umeboshi", emojis: "🍑🔴", level: "impossible" },
];
