// Guess the Food — one verified ≤70-char fact per dish, shown on reveal.
export const FOOD_FACTS = {
  // EASY
  "pizza": "Modern pizza was born in Naples, Italy.",
  "hamburger": "The patty-in-a-bun took its name from Hamburg, Germany.",
  "sushi": "It began as a way to preserve fish in fermented rice.",
  "taco": "A Mexican classic: a folded tortilla around a filling.",
  "spaghetti": "Its name comes from the Italian for 'little strings'.",
  "frenchfries": "Belgium and France both claim these fried potatoes.",
  "pancakes": "One of the oldest cooked breakfasts, eaten for millennia.",
  "hotdog": "Its sausage descends from the German frankfurter.",
  "donut": "The ring shape helps the sweet dough fry evenly.",
  "friedchicken": "Chicken pieces coated in seasoned flour, then fried.",
  "icecream": "A frozen sweet of cream, sugar, and flavorings.",
  "popcorn": "These kernels puff when trapped water turns to steam.",
  "waffle": "Its grid pattern comes from a hinged hot iron.",
  "burrito": "A Mexican wrap; 'burrito' means 'little donkey'.",
  "ramen": "Japan adopted these wheat noodles from China.",
  "croissant": "Its crescent shape came from Austria, not France.",
  "pretzel": "Its knot may represent arms folded in prayer.",
  "cupcake": "Named for cakes once baked in individual cups.",
  "nachos": "Invented in Mexico by a cook named Ignacio 'Nacho'.",
  "corndog": "A hot dog dipped in cornmeal batter, then fried.",
  "cornonthecob": "Corn was first domesticated in ancient Mexico.",
  "steak": "A thick slice of beef, usually grilled or seared.",
  "grilledcheese": "Melted cheese griddled between buttered bread.",
  "friedegg": "Cooked sunny-side up, the yolk stays soft and runny.",
  "watermelon": "This juicy fruit is about 90% water.",
  // MEDIUM
  "paella": "This rice dish comes from Valencia, Spain.",
  "pho": "This noodle soup arose in northern Vietnam around 1900.",
  "falafel": "Deep-fried balls of ground chickpeas or fava beans.",
  "dumplings": "Dough parcels wrapped around a savory filling.",
  "guacamole": "An Aztec avocado dip; the name means 'avocado sauce'.",
  "lasagna": "Layers of flat pasta, sauce, and cheese, from Italy.",
  "tiramisu": "Created in Treviso, Italy in 1969.",
  "gyro": "Greek meat roasted on a vertical spit, in pita.",
  "samosa": "A fried pastry filled with spiced potatoes or meat.",
  "springroll": "An East Asian roll wrapped in a thin pastry skin.",
  "churros": "Fried dough sticks dusted in cinnamon sugar.",
  "bagel": "A boiled-then-baked ring rooted in Polish Jewish baking.",
  "macaron": "A French almond-meringue sandwich cookie.",
  "crepe": "A very thin pancake from Brittany, France.",
  "quesadilla": "A Mexican tortilla folded over melted cheese.",
  "fishandchips": "A British classic of battered fish with fried chips.",
  "hummus": "A Middle Eastern dip of chickpeas and tahini.",
  "risotto": "An Italian rice dish stirred until creamy.",
  "padthai": "Thailand's famous stir-fried rice noodle dish.",
  "baklava": "Layered phyllo with nuts, soaked in syrup or honey.",
  "cannoli": "A Sicilian fried tube filled with sweet ricotta.",
  "sashimi": "Thinly sliced raw fish, served without rice.",
  "eclair": "A French choux pastry filled with cream.",
  "onionrings": "Onion slices battered and deep-fried into rings.",
  "caprese": "An Italian salad in the colors of its flag.",
  // HARD
  "bibimbap": "A Korean rice bowl; the name means 'mixed rice'.",
  "poutine": "Fries with cheese curds and gravy, from Quebec.",
  "borscht": "A beet soup rooted in Ukrainian cuisine.",
  "pierogi": "Boiled dough dumplings popular across Poland.",
  "empanada": "A stuffed, baked or fried pastry from Spain.",
  "bruschetta": "Toasted bread rubbed with garlic, from Italy.",
  "ceviche": "Peru's national dish: raw fish cured in citrus.",
  "shakshuka": "Eggs poached in a spiced tomato and pepper sauce.",
  "okonomiyaki": "A Japanese savory pancake; 'okonomi' means 'as you like'.",
  "banhmi": "A Vietnamese sandwich on a French colonial baguette.",
  "tandoorichicken": "Chicken roasted in a clay tandoor oven.",
  "jollofrice": "A one-pot spiced rice beloved across West Africa.",
  "injera": "An Ethiopian sourdough flatbread made from teff.",
  "moussaka": "A baked eggplant dish famous in Greece.",
  "katsu": "A Japanese breaded, deep-fried cutlet.",
  "arepa": "A cornmeal cake staple in Venezuela and Colombia.",
  "tteokbokki": "Korean rice cakes in a sweet, spicy chili sauce.",
  "gnocchi": "Soft Italian dumplings often made from potato.",
  "ratatouille": "A vegetable stew from Nice, in southern France.",
  "tabbouleh": "A Levantine parsley salad with bulgur wheat.",
  "pavlova": "A meringue dessert named after ballerina Anna Pavlova.",
  "wellington": "Beef wrapped in pastry, a British showpiece.",
  "takoyaki": "Japanese batter balls filled with octopus.",
  "dolma": "Vine leaves or vegetables stuffed with rice.",
  "kanafeh": "A cheese pastry linked to Nablus, Palestine.",
  // IMPOSSIBLE
  "surstromming": "Sweden's notoriously smelly fermented herring.",
  "smorrebrod": "A Danish open-faced sandwich on rye bread.",
  "haggis": "Scotland's dish of sheep offal in a stomach lining.",
  "lutefisk": "Dried fish soaked in lye, a Nordic tradition.",
  "centuryegg": "A Chinese egg cured in alkaline clay for weeks.",
  "natto": "Japanese fermented soybeans, sticky and pungent.",
  "chapulines": "Toasted grasshoppers, a snack from Oaxaca, Mexico.",
  "casumarzu": "A Sardinian cheese ripened with live maggots.",
  "fufu": "A soft, pounded dough staple across West Africa.",
  "poi": "A Hawaiian paste made from pounded taro root.",
  "ackee": "Jamaica's national fruit, paired with saltfish.",
  "larb": "A spiced minced-meat salad from Laos and Thailand.",
  "bunnychow": "A hollowed bread loaf filled with curry, from Durban.",
  "rendang": "A slow-cooked coconut beef from West Sumatra.",
  "pasteldenata": "A Portuguese custard tart created by monks in Belém.",
  "khachapuri": "Georgia's boat-shaped cheese bread with an egg.",
  "manti": "Small spiced-meat dumplings across Turkey and Central Asia.",
  "bibingka": "A Filipino rice cake baked around Christmas.",
  "khinkali": "Twisted Georgian dumplings filled with juicy meat.",
  "zongzi": "Sticky rice wrapped in leaves, eaten in China.",
  "lechon": "A whole roasted pig, a Filipino feast centerpiece.",
  "smalahove": "A Norwegian dish of a whole smoked sheep's head.",
  "jelliedeels": "Chopped eels set in jelly, an old East London food.",
  "khash": "A hearty boiled-hoof soup from the Caucasus region.",
  "escamoles": "Edible ant larvae, a delicacy from central Mexico.",
};
