// E213 food-emoji facts — one true <=70-char fact per dish, shown on reveal.
export const FOOD_EMOJI_5_FACTS = {
  // EASY
  "ramen": "A Japanese noodle soup adapted from Chinese wheat noodles.",
  "pho": "A Vietnamese noodle soup of broth, herbs, and rice noodles.",
  "pad-thai": "A Thai stir-fried rice noodle dish with tamarind sauce.",
  "tempura": "Japanese seafood or vegetables battered and deep-fried.",
  "burrito": "A Mexican dish of fillings wrapped in a flour tortilla.",
  "hot-dog": "A grilled sausage served in a sliced bun with toppings.",
  "falafel": "Fried balls of ground chickpeas, popular across the Middle East.",
  "hummus": "A dip of blended chickpeas, tahini, lemon, and olive oil.",
  "gyro": "A Greek dish of meat, vegetables, and sauce in pita bread.",
  "paella": "A Spanish rice dish from Valencia, often made with seafood.",
  "risotto": "A creamy Italian rice dish stirred slowly with broth.",
  "lasagna": "Layered pasta sheets baked with sauce, cheese, and filling.",
  "schnitzel": "A thin breaded and fried cutlet, a classic Austrian dish.",
  "doner-kebab": "Turkish meat roasted on a vertical spit, served in bread.",
  "tandoori-chicken": "Chicken marinated in yogurt and spices, roasted in a tandoor.",
  "biryani": "A South Asian dish of spiced rice layered with meat.",
  "samosa": "A fried pastry filled with spiced potatoes or meat.",
  "bibimbap": "A Korean bowl of rice topped with vegetables and egg.",
  "kimchi-jjigae": "A spicy Korean stew made with fermented kimchi.",
  "banh-mi": "A Vietnamese sandwich on a baguette with pickled veggies.",
  "satay": "Skewered, grilled meat served with peanut sauce in Southeast Asia.",
  "clam-chowder": "A creamy New England soup made with clams and potatoes.",
  "jambalaya": "A Louisiana rice dish with meat, seafood, and spices.",
  "gumbo": "A Louisiana stew thickened with roux, okra, or filé.",
  "poutine": "A Canadian dish of fries topped with cheese curds and gravy.",
  // MEDIUM
  "goulash": "A Hungarian stew of meat and vegetables seasoned with paprika.",
  "pierogi": "Polish dumplings filled with potato, cheese, or meat.",
  "borscht": "A tangy Eastern European soup made with beets.",
  "pelmeni": "Russian dumplings filled with minced meat, boiled or fried.",
  "khachapuri": "A Georgian cheese-filled bread, often boat-shaped with egg.",
  "plov": "A Central Asian rice dish cooked with lamb and carrots.",
  "manti": "Small Turkish dumplings served with garlicky yogurt sauce.",
  "lahmacun": "A thin Turkish flatbread topped with minced meat and spices.",
  "muhammara": "A Syrian dip of roasted red peppers, walnuts, and spices.",
  "ful-medames": "An Egyptian dish of stewed fava beans with lemon and oil.",
  "koshari": "An Egyptian mix of rice, lentils, pasta, and tomato sauce.",
  "mansaf": "A Jordanian dish of lamb cooked in fermented dried yogurt.",
  "kabsa": "A Saudi spiced rice dish usually served with chicken.",
  "shakshuka": "Eggs poached in a spiced tomato and pepper sauce.",
  "currywurst": "A German fast food of sliced sausage with curry ketchup.",
  "sauerbraten": "A German pot roast marinated for days before cooking.",
  "moussaka": "A Greek baked dish of eggplant layered with spiced meat.",
  "dolma": "Grape leaves stuffed with rice, herbs, and sometimes meat.",
  "baba-ganoush": "A Levantine dip of roasted, mashed eggplant and tahini.",
  "chana-masala": "A North Indian curry made with chickpeas in spiced tomato sauce.",
  "rogan-josh": "A rich, spicy Kashmiri curry traditionally made with lamb.",
  "korma": "A mild curry made creamy with yogurt, cream, or coconut.",
  "dal-makhani": "A Punjabi dish of black lentils simmered with butter and cream.",
  "empanada": "A stuffed pastry, baked or fried, popular across Latin America.",
  "ceviche": "Raw fish cured in citrus juice, a Latin American classic.",
  // HARD
  "bulgogi": "Korean thinly sliced beef marinated in a sweet soy sauce.",
  "japchae": "Korean stir-fried glass noodles with vegetables and beef.",
  "galbi": "Korean marinated beef short ribs, grilled over an open flame.",
  "kimbap": "Korean rice and fillings rolled in seaweed, sliced into rounds.",
  "congee": "An Asian rice porridge, often eaten as breakfast or when ill.",
  "laksa": "A spicy Southeast Asian noodle soup with a coconut curry base.",
  "rendang": "An Indonesian slow-cooked beef dish in coconut and spices.",
  "gado-gado": "An Indonesian salad of vegetables in peanut sauce.",
  "khinkali": "Georgian soup dumplings twisted at the top and pinched shut.",
  "lomo-saltado": "A Peruvian stir-fry of beef, onions, tomatoes, and fries.",
  "anticuchos": "Peruvian grilled skewers, traditionally made from beef heart.",
  "arepa": "A Venezuelan and Colombian cornmeal cake, often filled with cheese.",
  "pupusa": "A thick Salvadoran cornmeal flatbread stuffed with cheese.",
  "feijoada": "A Brazilian stew of black beans and various cuts of pork.",
  "khichdi": "A South Asian comfort dish of rice cooked with lentils.",
  "tagine": "A North African stew slow-cooked in a cone-shaped clay pot.",
  "merguez": "A spicy North African lamb sausage flavored with harissa.",
  "manakish": "A Levantine flatbread topped with za'atar herbs and oil.",
  "tabbouleh": "A Levantine salad of bulgur, parsley, tomato, and lemon.",
  "chorizo": "A seasoned pork sausage, spicy and paprika-rich in Spain.",
  "cevapi": "Grilled minced meat sausages, a Balkan barbecue staple.",
  "khao-soi": "A Northern Thai curry noodle soup topped with crispy noodles.",
  "koobideh": "Iranian minced meat kebabs grilled on flat skewers.",
  "fesenjan": "A Persian stew of chicken in walnut and pomegranate sauce.",
  "kibbeh": "A Levantine dish of spiced meat mixed with bulgur, fried or baked.",
  // IMPOSSIBLE
  "haggis": "A Scottish dish of minced offal, oats, and spices in a casing.",
  "surstromming": "Swedish fermented herring, notorious for its strong smell.",
  "balut": "A Southeast Asian fertilized duck egg, boiled and eaten in the shell.",
  "natto": "Japanese fermented soybeans with a sticky, stringy texture.",
  "lutefisk": "Scandinavian dried whitefish rehydrated in lye, then cooked.",
  "hakarl": "Icelandic fermented shark, cured and hung to dry for months.",
  "stinky-tofu": "Chinese fermented tofu known for its pungent odor.",
  "drunken-shrimp": "A Chinese dish of live shrimp soaked in strong liquor.",
  "morcilla": "A Spanish blood sausage often made with rice or onion.",
  "mopane-worms": "Dried caterpillars, a protein-rich snack in Southern Africa.",
  "sea-cucumber": "A marine animal prized in Chinese cuisine for its texture.",
  "blood-clam": "A clam species eaten raw or blanched, valued in East Asia.",
  "kiviak": "A Greenlandic Inuit dish of birds fermented inside a sealskin.",
  "turtle-soup": "A once-popular soup made from turtle meat.",
  "khash": "An Armenian and Caucasian soup made from boiled cow's feet.",
  "tteok-guk": "A Korean soup of sliced rice cakes, eaten on New Year's Day.",
  "otak-otak": "Southeast Asian spiced fish paste grilled in banana leaf.",
  "sikhae": "A Korean fermented dish of fish mixed with grains.",
  "muktuk": "Inuit traditional food of whale skin and blubber.",
  "yak-butter-tea": "A Tibetan drink of tea churned with yak butter and salt.",
  "airag": "Mongolian fermented mare's milk, mildly alcoholic.",
  "boodog": "A Mongolian dish of goat cooked from the inside with hot stones.",
  "sop-buntut": "An Indonesian oxtail soup simmered until tender.",
  "percebes": "Spanish goose barnacles harvested from rocky Atlantic shores.",
  "kvass": "A mildly fermented Eastern European drink made from rye bread.",
};
