// E140 «Guess the Fruit or Vegetable by Emoji» — 100 items · 25/tier · single Unicode emoji clues (EASY) or fair 2-emoji clues (MEDIUM+)
// VO: sfx/e140-<id>.wav ("It's <Name>!")
// EASY = the fruit/veg HAS a direct dedicated emoji (apple->apple emoji). MEDIUM/HARD/IMPOSSIBLE = fruits/veg with
// NO direct emoji of their own; clued fairly via 2 real emoji (defining trait / wordplay / shape+color), never bare color alone.
export const FRUIT_EMOJI = [
  // ===== EASY (25) — direct single-emoji produce =====
  { id: "apple", title: "Apple", emojis: "🍎", level: "easy" },
  { id: "banana", title: "Banana", emojis: "🍌", level: "easy" },
  { id: "orange", title: "Orange", emojis: "🍊", level: "easy" },
  { id: "strawberry", title: "Strawberry", emojis: "🍓", level: "easy" },
  { id: "carrot", title: "Carrot", emojis: "🥕", level: "easy" },
  { id: "tomato", title: "Tomato", emojis: "🍅", level: "easy" },
  { id: "potato", title: "Potato", emojis: "🥔", level: "easy" },
  { id: "grapes", title: "Grapes", emojis: "🍇", level: "easy" },
  { id: "watermelon", title: "Watermelon", emojis: "🍉", level: "easy" },
  { id: "pineapple", title: "Pineapple", emojis: "🍍", level: "easy" },
  { id: "lemon", title: "Lemon", emojis: "🍋", level: "easy" },
  { id: "broccoli", title: "Broccoli", emojis: "🥦", level: "easy" },
  { id: "corn", title: "Corn", emojis: "🌽", level: "easy" },
  { id: "onion", title: "Onion", emojis: "🧅", level: "easy" },
  { id: "cucumber", title: "Cucumber", emojis: "🥒", level: "easy" },
  { id: "pumpkin", title: "Pumpkin", emojis: "🎃", level: "easy" },
  { id: "cherries", title: "Cherries", emojis: "🍒", level: "easy" },
  { id: "peach", title: "Peach", emojis: "🍑", level: "easy" },
  { id: "mango", title: "Mango", emojis: "🥭", level: "easy" },
  { id: "avocado", title: "Avocado", emojis: "🥑", level: "easy" },
  { id: "pear", title: "Pear", emojis: "🍐", level: "easy" },
  { id: "coconut", title: "Coconut", emojis: "🥥", level: "easy" },
  { id: "bell-pepper", title: "Bell Pepper", emojis: "🫑", level: "easy" },
  { id: "garlic", title: "Garlic", emojis: "🧄", level: "easy" },
  { id: "eggplant", title: "Eggplant", emojis: "🍆", level: "easy" },

  // ===== MEDIUM (25) — no dedicated emoji, fair 2-emoji clue =====
  { id: "dragonfruit", title: "Dragonfruit", emojis: "🐉🍈", level: "medium" },
  { id: "passionfruit", title: "Passionfruit", emojis: "💜🍈", level: "medium" },
  { id: "starfruit", title: "Starfruit", emojis: "⭐🍈", level: "medium" },
  { id: "persimmon", title: "Persimmon", emojis: "🏮🍊", level: "medium" },
  { id: "guava", title: "Guava", emojis: "🍐🌴", level: "medium" },
  { id: "papaya", title: "Papaya", emojis: "🍈🌴", level: "medium" },
  { id: "pomegranate", title: "Pomegranate", emojis: "👑🍎", level: "medium" },
  { id: "fig", title: "Fig", emojis: "💧🍇", level: "medium" },
  { id: "kumquat", title: "Kumquat", emojis: "🔍🍊", level: "medium" },
  { id: "custard-apple", title: "Custard Apple", emojis: "🍦🍏", level: "medium" },
  { id: "mangosteen", title: "Mangosteen", emojis: "🌸🍈", level: "medium" },
  { id: "blood-orange", title: "Blood Orange", emojis: "🩸🍊", level: "medium" },
  { id: "blackberry", title: "Blackberry", emojis: "⚫🍇", level: "medium" },
  { id: "mulberry", title: "Mulberry", emojis: "🐛🍇", level: "medium" },
  { id: "cranberry", title: "Cranberry", emojis: "🦃🔴", level: "medium" },
  { id: "gooseberry", title: "Gooseberry", emojis: "🦢🍈", level: "medium" },
  { id: "elderberry", title: "Elderberry", emojis: "👵🍇", level: "medium" },
  { id: "rhubarb", title: "Rhubarb", emojis: "🥧🌿", level: "medium" },
  { id: "kohlrabi", title: "Kohlrabi", emojis: "🛸🌿", level: "medium" },
  { id: "okra", title: "Okra", emojis: "⭐🌿", level: "medium" },
  { id: "artichoke", title: "Artichoke", emojis: "🌹🌿", level: "medium" },
  { id: "radish", title: "Radish", emojis: "🐰🔴", level: "medium" },
  { id: "parsnip", title: "Parsnip", emojis: "🥕⚪", level: "medium" },
  { id: "jicama", title: "Jicama", emojis: "🌮🥔", level: "medium" },
  { id: "celeriac", title: "Celeriac", emojis: "🎾🌿", level: "medium" },

  // ===== HARD (25) — no dedicated emoji, fair 2-emoji clue =====
  { id: "rambutan", title: "Rambutan", emojis: "🦔🔴", level: "hard" },
  { id: "durian", title: "Durian", emojis: "🤢🌰", level: "hard" },
  { id: "lychee", title: "Lychee", emojis: "🌸🍇", level: "hard" },
  { id: "longan", title: "Longan", emojis: "👀🍇", level: "hard" },
  { id: "jackfruit", title: "Jackfruit", emojis: "🦔🌳", level: "hard" },
  { id: "breadfruit", title: "Breadfruit", emojis: "🍞🌳", level: "hard" },
  { id: "cherimoya", title: "Cherimoya", emojis: "🐍🍏", level: "hard" },
  { id: "soursop", title: "Soursop", emojis: "🦔🍏", level: "hard" },
  { id: "feijoa", title: "Feijoa", emojis: "🥝🍏", level: "hard" },
  { id: "physalis", title: "Physalis (Golden Berry)", emojis: "🥇🍇", level: "hard" },
  { id: "ugli-fruit", title: "Ugli Fruit", emojis: "🤪🍊", level: "hard" },
  { id: "yuzu", title: "Yuzu", emojis: "🍋🌸", level: "hard" },
  { id: "makrut-lime", title: "Makrut Lime", emojis: "🍃🍈", level: "hard" },
  { id: "tamarillo", title: "Tamarillo", emojis: "🌳🍅", level: "hard" },
  { id: "prickly-pear", title: "Prickly Pear", emojis: "🌵🍐", level: "hard" },
  { id: "kiwano", title: "Kiwano", emojis: "🦕🍈", level: "hard" },
  { id: "salak", title: "Salak", emojis: "🐍🍈", level: "hard" },
  { id: "loquat", title: "Loquat", emojis: "🍐🟡", level: "hard" },
  { id: "quince", title: "Quince", emojis: "🍯🍐", level: "hard" },
  { id: "sapodilla", title: "Sapodilla", emojis: "🍈🟤", level: "hard" },
  { id: "chayote", title: "Chayote", emojis: "🍐🥒", level: "hard" },
  { id: "bitter-melon", title: "Bitter Melon", emojis: "😬🥒", level: "hard" },
  { id: "daikon", title: "Daikon", emojis: "🐘🥕", level: "hard" },
  { id: "fiddlehead", title: "Fiddlehead Fern", emojis: "🎻🌿", level: "hard" },
  { id: "water-chestnut", title: "Water Chestnut", emojis: "🌊🌰", level: "hard" },

  // ===== IMPOSSIBLE (25) — no dedicated emoji, fair 2-emoji clue =====
  { id: "cempedak", title: "Cempedak", emojis: "🦔🍯", level: "impossible" },
  { id: "ulluco", title: "Ulluco", emojis: "🌈🥔", level: "impossible" },
  { id: "skirret", title: "Skirret", emojis: "🍬🥕", level: "impossible" },
  { id: "yacon", title: "Yacon", emojis: "🍐🥔", level: "impossible" },
  { id: "salsify", title: "Salsify", emojis: "🦪🥕", level: "impossible" },
  { id: "cardoon", title: "Cardoon", emojis: "🌸🥬", level: "impossible" },
  { id: "romanesco", title: "Romanesco", emojis: "🌀🥦", level: "impossible" },
  { id: "kabocha", title: "Kabocha", emojis: "🟢🎃", level: "impossible" },
  { id: "delicata-squash", title: "Delicata Squash", emojis: "🦓🎃", level: "impossible" },
  { id: "buddhas-hand", title: "Buddha's Hand", emojis: "✋🍋", level: "impossible" },
  { id: "cucamelon", title: "Cucamelon", emojis: "🐭🍉", level: "impossible" },
  { id: "miracle-fruit", title: "Miracle Fruit", emojis: "✨🍇", level: "impossible" },
  { id: "ackee", title: "Ackee", emojis: "👀🌳", level: "impossible" },
  { id: "noni", title: "Noni", emojis: "🤢🥔", level: "impossible" },
  { id: "pepino-melon", title: "Pepino Melon", emojis: "🍈🟣", level: "impossible" },
  { id: "naranjilla", title: "Naranjilla (Lulo)", emojis: "🍅🟠", level: "impossible" },
  { id: "jabuticaba", title: "Jabuticaba", emojis: "🌳🍇", level: "impossible" },
  { id: "cloudberry", title: "Cloudberry", emojis: "🌥🍇", level: "impossible" },
  { id: "marula", title: "Marula", emojis: "🐘🍈", level: "impossible" },
  { id: "medlar", title: "Medlar", emojis: "🍂🍐", level: "impossible" },
  { id: "spanish-lime", title: "Spanish Lime (Genip)", emojis: "🍇🟢", level: "impossible" },
  { id: "wax-apple", title: "Wax Apple", emojis: "🔔🍎", level: "impossible" },
  { id: "monstera-fruit", title: "Monstera Fruit", emojis: "🐉🍍", level: "impossible" },
  { id: "achacha", title: "Achacha", emojis: "🌳🍊", level: "impossible" },
  { id: "loofah", title: "Loofah", emojis: "🧽🥒", level: "impossible" },
];
