// «Guess the Fruit or Vegetable» — GuessSync · Fruits & Veg v2 · 100 items (25/tier) · real photos from Wikimedia Commons
// Second fruits/veg episode (repeat-the-winner). ANSWER = the fruit/vegetable name.
// Zero overlap with E21 fruitsData (unique slug AND name). Mix of fruits + vegetables.
// Absolute difficulty by universal recognisability:
//   easy (Raspberry/Cabbage/Lime) → impossible (Ulluco/Cempedak/Skirret).
export const FRUITS2 = [
  // ===== EASY (25) — common produce almost everyone recognizes on sight =====
  { slug: "raspberry", name: "Raspberry", level: "easy" },
  { slug: "blueberry", name: "Blueberry", level: "easy" },
  { slug: "lime", name: "Lime", level: "easy" },
  { slug: "grapefruit", name: "Grapefruit", level: "easy" },
  { slug: "cabbage", name: "Cabbage", level: "easy" },
  { slug: "spinach", name: "Spinach", level: "easy" },
  { slug: "kale", name: "Kale", level: "easy" },
  { slug: "greenbeans", name: "Green Beans", level: "easy" },
  { slug: "peas", name: "Peas", level: "easy" },
  { slug: "nectarine", name: "Nectarine", level: "easy" },
  { slug: "tangerine", name: "Tangerine", level: "easy" },
  { slug: "mandarin", name: "Mandarin", level: "easy" },
  { slug: "chilipepper", name: "Chili Pepper", level: "easy" },
  { slug: "greenonion", name: "Green Onion", level: "easy" },
  { slug: "honeydew", name: "Honeydew", level: "easy" },
  { slug: "butternutsquash", name: "Butternut Squash", level: "easy" },
  { slug: "redcabbage", name: "Red Cabbage", level: "easy" },
  { slug: "jalapeno", name: "Jalapeno", level: "easy" },
  { slug: "clementine", name: "Clementine", level: "easy" },
  { slug: "pomelo", name: "Pomelo", level: "easy" },
  { slug: "yam", name: "Yam", level: "easy" },
  { slug: "snappeas", name: "Snap Peas", level: "easy" },
  { slug: "beansprouts", name: "Bean Sprouts", level: "easy" },
  { slug: "arugula", name: "Arugula", level: "easy" },
  { slug: "cornsalad", name: "Corn Salad", level: "easy" },

  // ===== MEDIUM (25) — familiar but not everyone names them =====
  { slug: "collardgreens", name: "Collard Greens", level: "medium" },
  { slug: "mustardgreens", name: "Mustard Greens", level: "medium" },
  { slug: "acornsquash", name: "Acorn Squash", level: "medium" },
  { slug: "spaghettisquash", name: "Spaghetti Squash", level: "medium" },
  { slug: "endive", name: "Endive", level: "medium" },
  { slug: "boysenberry", name: "Boysenberry", level: "medium" },
  { slug: "mulberry", name: "Mulberry", level: "medium" },
  { slug: "redcurrant", name: "Redcurrant", level: "medium" },
  { slug: "satsuma", name: "Satsuma", level: "medium" },
  { slug: "snowpeas", name: "Snow Peas", level: "medium" },
  { slug: "celeriac", name: "Celeriac", level: "medium" },
  { slug: "jicama", name: "Jicama", level: "medium" },
  { slug: "taro", name: "Taro", level: "medium" },
  { slug: "cassava", name: "Cassava", level: "medium" },
  { slug: "lotusroot", name: "Lotus Root", level: "medium" },
  { slug: "waterchestnut", name: "Water Chestnut", level: "medium" },
  { slug: "napacabbage", name: "Napa Cabbage", level: "medium" },
  { slug: "savoycabbage", name: "Savoy Cabbage", level: "medium" },
  { slug: "broccolini", name: "Broccolini", level: "medium" },
  { slug: "frisee", name: "Frisee", level: "medium" },
  { slug: "sorrel", name: "Sorrel", level: "medium" },
  { slug: "lingonberry", name: "Lingonberry", level: "medium" },
  { slug: "huckleberry", name: "Huckleberry", level: "medium" },
  { slug: "wintermelon", name: "Winter Melon", level: "medium" },
  { slug: "dandeliongreens", name: "Dandelion Greens", level: "medium" },

  // ===== HARD (25) — uncommon; few recognize on sight =====
  { slug: "cloudberry", name: "Cloudberry", level: "hard" },
  { slug: "loganberry", name: "Loganberry", level: "hard" },
  { slug: "tayberry", name: "Tayberry", level: "hard" },
  { slug: "barberry", name: "Barberry", level: "hard" },
  { slug: "seabuckthorn", name: "Sea Buckthorn", level: "hard" },
  { slug: "mirabelle", name: "Mirabelle", level: "hard" },
  { slug: "greengage", name: "Greengage", level: "hard" },
  { slug: "damson", name: "Damson", level: "hard" },
  { slug: "sloe", name: "Sloe", level: "hard" },
  { slug: "jujube", name: "Jujube", level: "hard" },
  { slug: "sapodilla", name: "Sapodilla", level: "hard" },
  { slug: "serviceberry", name: "Serviceberry", level: "hard" },
  { slug: "chokeberry", name: "Chokeberry", level: "hard" },
  { slug: "samphire", name: "Samphire", level: "hard" },
  { slug: "chicory", name: "Chicory", level: "hard" },
  { slug: "puntarelle", name: "Puntarelle", level: "hard" },
  { slug: "seakale", name: "Sea Kale", level: "hard" },
  { slug: "mizuna", name: "Mizuna", level: "hard" },
  { slug: "tatsoi", name: "Tatsoi", level: "hard" },
  { slug: "gailan", name: "Gai Lan", level: "hard" },
  { slug: "choysum", name: "Choy Sum", level: "hard" },
  { slug: "fiddleheads", name: "Fiddleheads", level: "hard" },
  { slug: "purslane", name: "Purslane", level: "hard" },
  { slug: "amaranth", name: "Amaranth", level: "hard" },
  { slug: "rosehip", name: "Rose Hip", level: "hard" },

  // ===== IMPOSSIBLE (25) — exotic/rare; almost nobody names them =====
  { slug: "pitanga", name: "Pitanga", level: "impossible" },
  { slug: "langsat", name: "Langsat", level: "impossible" },
  { slug: "marang", name: "Marang", level: "impossible" },
  { slug: "bilimbi", name: "Bilimbi", level: "impossible" },
  { slug: "santol", name: "Santol", level: "impossible" },
  { slug: "mamey", name: "Mamey", level: "impossible" },
  { slug: "abiu", name: "Abiu", level: "impossible" },
  { slug: "jocote", name: "Jocote", level: "impossible" },
  { slug: "nance", name: "Nance", level: "impossible" },
  { slug: "lucuma", name: "Lucuma", level: "impossible" },
  { slug: "pepino", name: "Pepino", level: "impossible" },
  { slug: "tamarillo", name: "Tamarillo", level: "impossible" },
  { slug: "gac", name: "Gac", level: "impossible" },
  { slug: "noni", name: "Noni", level: "impossible" },
  { slug: "cempedak", name: "Cempedak", level: "impossible" },
  { slug: "wampee", name: "Wampee", level: "impossible" },
  { slug: "sugarapple", name: "Sugar Apple", level: "impossible" },
  { slug: "rollinia", name: "Rollinia", level: "impossible" },
  { slug: "oca", name: "Oca", level: "impossible" },
  { slug: "ulluco", name: "Ulluco", level: "impossible" },
  { slug: "mashua", name: "Mashua", level: "impossible" },
  { slug: "arracacha", name: "Arracacha", level: "impossible" },
  { slug: "crosne", name: "Crosne", level: "impossible" },
  { slug: "yacon", name: "Yacon", level: "impossible" },
  { slug: "skirret", name: "Skirret", level: "impossible" },
];

export const FRUITS2_LEVELS = ["easy", "medium", "hard", "impossible"];
