// E204 «Guess the Fruit or Vegetable by Emoji 2» — 100 items · 25/tier
// VO: sfx/e204-<id>.wav
export const FRUIT_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "kiwi", title: "Kiwi", emojis: "🥝🌿", level: "easy" },
  { id: "blueberry", title: "Blueberry", emojis: "🫐🧁", level: "easy" },
  { id: "olive", title: "Olive", emojis: "🫒🌳", level: "easy" },
  { id: "chestnut", title: "Chestnut", emojis: "🌰🔥", level: "easy" },
  { id: "peanut", title: "Peanut", emojis: "🥜🐘", level: "easy" },
  { id: "ginger", title: "Ginger", emojis: "🫚🍵", level: "easy" },
  { id: "green-beans", title: "Green Beans", emojis: "🫘🌱", level: "easy" },
  { id: "chili-pepper", title: "Chili Pepper", emojis: "🌶🔥", level: "easy" },
  { id: "snap-pea", title: "Snap Pea", emojis: "🫛🌱", level: "easy" },
  { id: "cabbage", title: "Cabbage", emojis: "🥬🐛", level: "easy" },
  { id: "spinach", title: "Spinach", emojis: "🥬💪", level: "easy" },
  { id: "zucchini", title: "Zucchini", emojis: "🥒🍝", level: "easy" },
  { id: "cauliflower", title: "Cauliflower", emojis: "🥦🧠", level: "easy" },
  { id: "leek", title: "Leek", emojis: "🧅🌿", level: "easy" },
  { id: "scallion", title: "Scallion", emojis: "🧅🌱", level: "easy" },
  { id: "celery", title: "Celery", emojis: "🥬🥤", level: "easy" },
  { id: "beetroot", title: "Beetroot", emojis: "🩸🥔", level: "easy" },
  { id: "sweet-potato", title: "Sweet Potato", emojis: "🍠🔥", level: "easy" },
  { id: "yam", title: "Yam", emojis: "🍠🌱", level: "easy" },
  { id: "brussels-sprouts", title: "Brussels Sprouts", emojis: "🥦👶", level: "easy" },
  { id: "kale", title: "Kale", emojis: "🥬🦸", level: "easy" },
  { id: "fennel", title: "Fennel", emojis: "🌿🍬", level: "easy" },
  { id: "turnip", title: "Turnip", emojis: "🥔👻", level: "easy" },
  { id: "plum", title: "Plum", emojis: "🍑💜", level: "easy" },
  { id: "asparagus", title: "Asparagus", emojis: "🌱🥢", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "horseradish", title: "Horseradish", emojis: "🐴🌶", level: "medium" },
  { id: "wasabi", title: "Wasabi", emojis: "🍣🌶", level: "medium" },
  { id: "taro", title: "Taro", emojis: "🐘👂", level: "medium" },
  { id: "cassava", title: "Cassava", emojis: "🌍🥔", level: "medium" },
  { id: "fava-bean", title: "Fava Bean", emojis: "🫘🌿", level: "medium" },
  { id: "rutabaga", title: "Rutabaga", emojis: "🥬🥔", level: "medium" },
  { id: "watercress", title: "Watercress", emojis: "💧🥬", level: "medium" },
  { id: "arugula", title: "Arugula", emojis: "🚀🥬", level: "medium" },
  { id: "endive", title: "Endive", emojis: "❄🥬", level: "medium" },
  { id: "radicchio", title: "Radicchio", emojis: "🍷🥬", level: "medium" },
  { id: "bok-choy", title: "Bok Choy", emojis: "🥢🥬", level: "medium" },
  { id: "napa-cabbage", title: "Napa Cabbage", emojis: "🍲🥬", level: "medium" },
  { id: "plantain", title: "Plantain", emojis: "🍌🍳", level: "medium" },
  { id: "galangal", title: "Galangal", emojis: "🫚🍜", level: "medium" },
  { id: "lotus-root", title: "Lotus Root", emojis: "🪷🥔", level: "medium" },
  { id: "samphire", title: "Samphire", emojis: "🌊🌿", level: "medium" },
  { id: "sea-kale", title: "Sea Kale", emojis: "🌊🥬", level: "medium" },
  { id: "scorzonera", title: "Scorzonera", emojis: "🖤🥕", level: "medium" },
  { id: "malanga", title: "Malanga", emojis: "🌴🥔", level: "medium" },
  { id: "yautia", title: "Yautia", emojis: "🏝🥔", level: "medium" },
  { id: "oca", title: "Oca", emojis: "🏔🥔", level: "medium" },
  { id: "mashua", title: "Mashua", emojis: "🏔🌶", level: "medium" },
  { id: "achira", title: "Achira", emojis: "🏹🥔", level: "medium" },
  { id: "elephant-foot-yam", title: "Elephant Foot Yam", emojis: "🐘🥔", level: "medium" },
  { id: "swiss-chard", title: "Swiss Chard", emojis: "🌈🥬", level: "medium" },

  // ===== HARD (25) =====
  { id: "tomatillo", title: "Tomatillo", emojis: "🍏📜", level: "hard" },
  { id: "acorn-squash", title: "Acorn Squash", emojis: "🌰🎃", level: "hard" },
  { id: "butternut-squash", title: "Butternut Squash", emojis: "🧈🎃", level: "hard" },
  { id: "spaghetti-squash", title: "Spaghetti Squash", emojis: "🍝🎃", level: "hard" },
  { id: "pattypan-squash", title: "Pattypan Squash", emojis: "🛸🎃", level: "hard" },
  { id: "winter-melon", title: "Winter Melon", emojis: "❄🍈", level: "hard" },
  { id: "bottle-gourd", title: "Bottle Gourd", emojis: "🍼🥒", level: "hard" },
  { id: "snake-gourd", title: "Snake Gourd", emojis: "🐍🥒", level: "hard" },
  { id: "ridge-gourd", title: "Ridge Gourd", emojis: "📏🥒", level: "hard" },
  { id: "ivy-gourd", title: "Ivy Gourd", emojis: "🌿🍈", level: "hard" },
  { id: "pointed-gourd", title: "Pointed Gourd", emojis: "☝🍈", level: "hard" },
  { id: "tinda", title: "Tinda", emojis: "🏐🍈", level: "hard" },
  { id: "burdock-root", title: "Burdock Root", emojis: "🪵🥕", level: "hard" },
  { id: "chicory-root", title: "Chicory Root", emojis: "☕🥕", level: "hard" },
  { id: "water-spinach", title: "Water Spinach", emojis: "🐊🥬", level: "hard" },
  { id: "malabar-spinach", title: "Malabar Spinach", emojis: "🍇🥬", level: "hard" },
  { id: "purslane", title: "Purslane", emojis: "🐷🥬", level: "hard" },
  { id: "sorrel", title: "Sorrel", emojis: "🍋🥬", level: "hard" },
  { id: "dandelion-greens", title: "Dandelion Greens", emojis: "🌼🥬", level: "hard" },
  { id: "mustard-greens", title: "Mustard Greens", emojis: "🌭🥬", level: "hard" },
  { id: "collard-greens", title: "Collard Greens", emojis: "🍖🥬", level: "hard" },
  { id: "turnip-greens", title: "Turnip Greens", emojis: "🥔🌿", level: "hard" },
  { id: "beet-greens", title: "Beet Greens", emojis: "🩸🌿", level: "hard" },
  { id: "amaranth-greens", title: "Amaranth Greens", emojis: "🌾🥬", level: "hard" },
  { id: "ramps", title: "Ramps", emojis: "🌲🧅", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "tamarind", title: "Tamarind", emojis: "🌳🍬", level: "impossible" },
  { id: "carob", title: "Carob", emojis: "🍫🌳", level: "impossible" },
  { id: "acerola", title: "Acerola", emojis: "🍒💊", level: "impossible" },
  { id: "mamey-sapote", title: "Mamey Sapote", emojis: "🥭🍠", level: "impossible" },
  { id: "white-sapote", title: "White Sapote", emojis: "👻🍮", level: "impossible" },
  { id: "black-sapote", title: "Black Sapote", emojis: "🍫🍮", level: "impossible" },
  { id: "lucuma", title: "Lucuma", emojis: "🥭🍦", level: "impossible" },
  { id: "canistel", title: "Canistel", emojis: "🥚🍮", level: "impossible" },
  { id: "sugar-apple", title: "Sugar Apple", emojis: "🍬🍏", level: "impossible" },
  { id: "biriba", title: "Biriba", emojis: "🌟🍏", level: "impossible" },
  { id: "kiwi-berry", title: "Kiwi Berry", emojis: "🥝👶", level: "impossible" },
  { id: "surinam-cherry", title: "Surinam Cherry", emojis: "🍒🎃", level: "impossible" },
  { id: "ice-cream-bean", title: "Ice Cream Bean", emojis: "🍨🫘", level: "impossible" },
  { id: "safou", title: "Safou", emojis: "🍐🌍", level: "impossible" },
  { id: "wampee", title: "Wampee", emojis: "🍇🥡", level: "impossible" },
  { id: "santol", title: "Santol", emojis: "🧶🍑", level: "impossible" },
  { id: "duku-langsat", title: "Duku (Langsat)", emojis: "🍈🐚", level: "impossible" },
  { id: "bilimbi", title: "Bilimbi", emojis: "💧🥒", level: "impossible" },
  { id: "otaheite-gooseberry", title: "Otaheite Gooseberry", emojis: "⭐🍇", level: "impossible" },
  { id: "governors-plum", title: "Governor's Plum", emojis: "👑🍑", level: "impossible" },
  { id: "monkey-orange", title: "Monkey Orange", emojis: "🐒🍊", level: "impossible" },
  { id: "kei-apple", title: "Kei Apple", emojis: "🔑🍏", level: "impossible" },
  { id: "mabolo", title: "Mabolo", emojis: "🧸🍎", level: "impossible" },
  { id: "cupuacu", title: "Cupuaçu", emojis: "🍫🥥", level: "impossible" },
  { id: "camu-camu", title: "Camu Camu", emojis: "💊🍇", level: "impossible" },
];
