// E21 «Guess the Fruit or Veg» — did-you-know facts, ≤70 chars each, verified.
export const FRUIT_FACTS = {
  // ===== EASY =====
  "apple": "There are over 7,500 apple varieties grown worldwide",
  "banana": "Botanically a berry; grows on the world's largest herb",
  "orange": "A hybrid of pomelo and mandarin, not a wild fruit",
  "strawberry": "Not a true berry; its seeds sit on the outside",
  "carrot": "The original cultivated carrots were purple, not orange",
  "tomato": "Botanically a fruit, but legally a vegetable in the US",
  "potato": "The first vegetable ever grown in space, back in 1995",
  "grape": "There are more than 10,000 grape varieties worldwide",
  "watermelon": "About 92% water, and a relative of cucumber and squash",
  "pineapple": "It can take about two years to grow a single pineapple",
  "lemon": "A hybrid of bitter orange and citron",
  "broccoli": "A human invention, bred from wild cabbage",
  "corn": "Corn ears almost always have an even number of rows",
  "onion": "Onions release a gas that makes your eyes water",
  "cucumber": "Botanically a fruit, and about 96% water",
  "pumpkin": "Botanically a fruit; it's a type of berry called a pepo",
  "cherry": "A member of the rose family, like plums and peaches",
  "peach": "Nectarines are simply peaches without the fuzz",
  "mango": "One of the world's most popular fruits; a cashew relative",
  "avocado": "Botanically a berry with a single large seed",
  "lettuce": "A relative of the sunflower and the daisy",
  "pear": "One of the oldest cultivated fruits, grown for millennia",
  "coconut": "Botanically a drupe, not a true nut",
  "bell-pepper": "Botanically a fruit; the only pepper with no heat",
  "garlic": "Closely related to onions, leeks, and chives",

  // ===== MEDIUM =====
  "pomegranate": "A single fruit can hold over 600 seeds",
  "kiwifruit": "From China, once called the Chinese gooseberry",
  "eggplant": "Botanically a berry, related to tomato and potato",
  "cauliflower": "Bred from wild cabbage, like broccoli and kale",
  "ginger": "The edible part is a rhizome, an underground stem",
  "papaya": "Its seeds are edible and taste peppery",
  "fig": "Not really a fruit but an inverted cluster of flowers",
  "cranberry": "Ripe cranberries bounce and float in water",
  "artichoke": "The part we eat is an unbloomed flower bud",
  "beetroot": "Its pigment can turn urine pink, called beeturia",
  "radish": "A root vegetable in the same family as cabbage",
  "asparagus": "Can make your urine smell odd within minutes",
  "zucchini": "Botanically a fruit, picked as an immature squash",
  "blackberry": "Not a true berry but a cluster of tiny drupelets",
  "passion-fruit": "Named by missionaries for the passion of Christ",
  "cantaloupe": "A melon named after Cantalupo, a town near Rome",
  "leek": "A relative of onion and garlic; the emblem of Wales",
  "turnip": "Carved into lanterns long before pumpkins were",
  "plum": "Dried plums are simply known as prunes",
  "apricot": "Its seed kernel tastes like a bitter almond",
  "sweet-potato": "Not related to the potato; it's a morning glory",
  "celery": "Grown and eaten since ancient Greek and Roman times",
  "okra": "In the same plant family as cotton and hibiscus",
  "brussels-sprout": "Named after the Belgian capital, Brussels",
  "date": "One of the oldest cultivated fruits, grown for 6,000 years",

  // ===== HARD =====
  "dragon-fruit": "Grows on a climbing cactus that blooms only at night",
  "lychee": "Cultivated in China for more than 2,000 years",
  "persimmon": "Unripe fruit is astringent and puckers the mouth",
  "guava": "Its seeds and rind are entirely edible",
  "star-fruit": "Sliced crosswise, it forms a five-pointed star",
  "kohlrabi": "Its name means cabbage-turnip in German",
  "fennel": "Every part is edible and tastes of licorice",
  "rutabaga": "A cross between a cabbage and a turnip",
  "plantain": "A starchy banana relative, cooked rather than eaten raw",
  "quince": "Too hard and sour to eat raw; usually cooked into paste",
  "gooseberry": "Its skin can be smooth or covered in fine hairs",
  "kumquat": "The only citrus eaten whole, peel and all",
  "radicchio": "A red-and-white Italian chicory with a pleasantly bitter taste",
  "daikon": "A large white radish central to Japanese cooking",
  "bok-choy": "A type of Chinese cabbage eaten stem and leaf",
  "chard": "The same species as beetroot, grown for its leaves",
  "tamarind": "A tangy pod used in sauces from Worcestershire to pad thai",
  "rhubarb": "A vegetable eaten as fruit; its leaves are poisonous",
  "shallot": "A small, mild onion relative prized in French cooking",
  "watercress": "A peppery leaf that grows in flowing water",
  "romanesco": "Its spiraling buds form a natural fractal pattern",
  "currant": "Tiny berries with more vitamin C than oranges",
  "elderberry": "Raw berries and the rest of the plant are toxic",
  "parsnip": "A sweet root closely related to the carrot",
  "edamame": "Immature green soybeans, boiled and served in the pod",

  // ===== IMPOSSIBLE =====
  "salak": "Called snake fruit for its reddish-brown scaly skin",
  "jabuticaba": "Its fruit grows directly on the tree trunk",
  "rambutan": "Its name comes from the Malay word for hair",
  "mangosteen": "Prized as the queen of fruits in Southeast Asia",
  "durian": "Banned on much transit for its powerful smell",
  "cherimoya": "Mark Twain called it the most delicious fruit known",
  "soursop": "A spiny green fruit tasting of pineapple and cream",
  "ackee": "Jamaica's national fruit, toxic until fully ripe",
  "cupuacu": "An Amazonian relative of cacao used in desserts",
  "longan": "Named dragon's eye for its translucent white flesh",
  "jackfruit": "The largest fruit that grows on any tree",
  "breadfruit": "Roasted, it tastes like freshly baked bread",
  "feijoa": "Also called pineapple guava for its tropical flavor",
  "loquat": "A yellow fruit that ripens in spring, unlike most",
  "medlar": "Eaten only after it softens and half-rots, called bletting",
  "salsify": "A root said to taste faintly of oysters",
  "chayote": "A wrinkled squash with a single soft edible seed",
  "sunchoke": "The tuber of a sunflower, not an artichoke at all",
  "yardlong-bean": "Its slender pods can grow up to about 75 cm long",
  "bitter-melon": "One of the most bitter foods eaten anywhere",
  "buddhas-hand": "A citron split into finger-like sections, all rind",
  "physalis": "Wrapped in a papery husk; also the cape gooseberry",
  "miracle-fruit": "Makes sour foods taste sweet for up to an hour",
  "pawpaw": "North America's largest native edible fruit",
  "ugli-fruit": "A Jamaican hybrid of grapefruit, orange and tangerine",
};
