// E204 fruit/vegetable-emoji-2 facts — one true <=70-char fact per item, shown on reveal.
export const FRUIT_EMOJI_2_FACTS = {
  // EASY
  "kiwi": "A fuzzy-skinned berry from China, also called Chinese gooseberry.",
  "blueberry": "A small blue-purple berry native to North America.",
  "olive": "A small stone fruit pressed into oil across the Mediterranean.",
  "chestnut": "A starchy tree nut often roasted over an open fire.",
  "peanut": "A legume that grows underground, not a true nut.",
  "ginger": "A spicy flowering root used fresh, dried, or in tea.",
  "green-beans": "Young, tender pods of the common bean plant.",
  "chili-pepper": "A spicy pepper that gets its heat from capsaicin.",
  "snap-pea": "A pea with a crisp, edible pod eaten whole.",
  "cabbage": "A leafy head vegetable in the same family as broccoli.",
  "spinach": "A dark leafy green rich in iron, popular since ancient Persia.",
  "zucchini": "A summer squash, called courgette in British English.",
  "cauliflower": "A cruciferous vegetable with a dense white edible head.",
  "leek": "A mild onion relative with long, layered white-green stalks.",
  "scallion": "A young onion harvested before the bulb fully forms.",
  "celery": "A crunchy stalk vegetable often used in soups and juices.",
  "beetroot": "A deep red root vegetable with naturally sweet flesh.",
  "sweet-potato": "A sweet, starchy root, unrelated to the true potato.",
  "yam": "A starchy tropical tuber often confused with sweet potato.",
  "brussels-sprouts": "Small cabbage-like buds named after Belgium's capital.",
  "kale": "A hardy leafy green prized as a nutrient-dense superfood.",
  "fennel": "A crunchy bulb vegetable with a mild licorice flavor.",
  "turnip": "A round root vegetable once carved as the first jack-o'-lantern.",
  "plum": "A stone fruit that becomes a prune when dried.",
  "asparagus": "A slender green spear vegetable harvested in early spring.",
  // MEDIUM
  "horseradish": "A pungent root grated raw into a sharp, spicy condiment.",
  "wasabi": "A Japanese root famous for its intense, fleeting heat.",
  "taro": "A starchy tropical root with large, heart-shaped leaves.",
  "cassava": "A starchy tropical root, staple food across Africa and Asia.",
  "jerusalem-artichoke": "A sunflower-family tuber also called the sunchoke.",
  "rutabaga": "A root cross between cabbage and turnip, called swede in the UK.",
  "watercress": "A peppery aquatic leafy green grown in flowing water.",
  "arugula": "A peppery salad green also known as rocket.",
  "endive": "A slightly bitter leafy vegetable often grown in darkness.",
  "radicchio": "A bitter Italian chicory with deep red-purple leaves.",
  "bok-choy": "A Chinese cabbage with crisp white stalks and green leaves.",
  "napa-cabbage": "A mild, crinkly-leaved Chinese cabbage used in kimchi.",
  "plantain": "A starchy banana relative usually cooked before eating.",
  "galangal": "A ginger-family root common in Thai and Indonesian cooking.",
  "lotus-root": "A crunchy aquatic root with a distinctive holey pattern.",
  "samphire": "A salty coastal plant nicknamed sea asparagus.",
  "sea-kale": "A hardy coastal vegetable with edible blanched shoots.",
  "scorzonera": "A black-skinned root vegetable also called black salsify.",
  "malanga": "A starchy tropical root similar to taro, popular in the Caribbean.",
  "yautia": "A Caribbean root vegetable also known as tannia.",
  "oca": "A tangy Andean tuber cultivated in Peru for centuries.",
  "mashua": "A peppery Andean tuber traditionally grown with potatoes.",
  "achira": "An Andean root with edible starch, also called canna lily.",
  "elephant-foot-yam": "A large starchy tuber common in South and Southeast Asia.",
  "swiss-chard": "A leafy green with colorful stems, related to the beet.",
  // HARD
  "tomatillo": "A tart green fruit wrapped in a papery husk, key to salsa verde.",
  "acorn-squash": "A ribbed winter squash shaped like a giant acorn.",
  "butternut-squash": "A sweet, tan-skinned squash with a bulbous end.",
  "spaghetti-squash": "A squash whose baked flesh separates into noodle-like strands.",
  "pattypan-squash": "A small, scallop-edged summer squash shaped like a disc.",
  "winter-melon": "A large, waxy-skinned gourd used in East Asian soups.",
  "bottle-gourd": "A pale green gourd shaped like a bottle, used as a vegetable.",
  "snake-gourd": "A long, slender, curling gourd popular in South Asian cooking.",
  "ridge-gourd": "An angular, ridged gourd also called luffa when young.",
  "ivy-gourd": "A small vine-grown gourd popular in Indian and Thai dishes.",
  "pointed-gourd": "A small oval gourd known as parwal in South Asia.",
  "tinda": "A round Indian gourd also called apple gourd.",
  "burdock-root": "A long, earthy woody-tasting root used in Japanese cooking.",
  "chicory-root": "A bitter root roasted and used as a coffee substitute.",
  "water-spinach": "A leafy aquatic vegetable also called kangkong.",
  "malabar-spinach": "A vine spinach with small purple berries, not a true spinach.",
  "purslane": "A tangy succulent green nicknamed pigweed.",
  "sorrel": "A leafy green with a sharp, lemony tang.",
  "dandelion-greens": "Peppery leaves from the common yellow-flowered weed.",
  "mustard-greens": "Spicy leafy greens from the same plant as mustard seed.",
  "collard-greens": "Sturdy leafy greens central to Southern US cooking.",
  "turnip-greens": "The edible leafy tops of the turnip root plant.",
  "beet-greens": "The edible leafy tops of the beetroot plant.",
  "amaranth-greens": "Leafy tops of a grain plant, eaten across Asia and Africa.",
  "ramps": "A wild forest onion with a strong garlicky-oniony flavor.",
  // IMPOSSIBLE
  "tamarind": "A sour-sweet pod fruit used in chutneys and pad thai.",
  "carob": "A sweet tree pod often used as a chocolate substitute.",
  "acerola": "A tiny cherry-like fruit with extremely high vitamin C.",
  "mamey-sapote": "A tropical fruit with sweet orange flesh, popular in Cuba.",
  "white-sapote": "A custardy fruit with sweet, creamy pale flesh.",
  "black-sapote": "A fruit nicknamed the chocolate pudding fruit.",
  "lucuma": "A Peruvian fruit prized for its maple-like ice cream flavor.",
  "canistel": "A fruit with dense, egg-yolk-like flesh, nicknamed egg fruit.",
  "sugar-apple": "A knobbly-skinned fruit with sweet, custardy segments.",
  "biriba": "A soft-spined relative of the sugar apple from South America.",
  "kiwi-berry": "A smooth, grape-sized cousin of the fuzzy kiwi.",
  "surinam-cherry": "A ribbed, pumpkin-shaped cherry relative from Brazil.",
  "ice-cream-bean": "A tropical bean pod with sweet, fluffy white pulp.",
  "safou": "An oily African fruit also called the African pear.",
  "wampee": "A small citrus relative with grape-like clustered fruit.",
  "santol": "A Southeast Asian fruit with cottony, tangy-sweet flesh.",
  "duku-langsat": "A Southeast Asian fruit with translucent segments under a peel.",
  "bilimbi": "An intensely sour, ridged tropical fruit used in pickles.",
  "otaheite-gooseberry": "A small star-shaped sour fruit, also called star gooseberry.",
  "governors-plum": "A tart plum-like fruit from Madagascar, used in preserves.",
  "monkey-orange": "A hard-shelled African fruit with sweet, aromatic pulp.",
  "kei-apple": "A tart South African fruit named after the Kei River.",
  "mabolo": "A fuzzy-skinned Southeast Asian fruit called velvet apple.",
  "cupuacu": "A cacao relative from the Amazon used in chocolate-like treats.",
  "camu-camu": "An Amazonian berry with one of the highest vitamin C levels known.",
};
