// «Guess the Fruit or Vegetable» v2 — did-you-know facts, ≤70 chars each, verified true.
export const FRUITS2_FACTS = {
  // ===== EASY =====
  raspberry: "An aggregate fruit made of many tiny connected drupelets",
  blueberry: "One of the very few naturally blue foods in nature",
  lime: "Picked while green; it turns yellow when fully ripe",
  grapefruit: "A cross between a sweet orange and a pomelo",
  cabbage: "Closely related to broccoli, kale and cauliflower",
  spinach: "Rich in iron and Popeye's favorite power food",
  kale: "A form of cabbage whose leaves never form a head",
  greenbeans: "Eaten whole, pod and all, unlike most other beans",
  peas: "One of the first crops ever domesticated by humans",
  nectarine: "Basically a peach with smooth, fuzz-free skin",
  tangerine: "A type of mandarin orange with a reddish skin",
  mandarin: "Smaller and sweeter than an orange, with loose skin",
  chilipepper: "Its heat comes from a compound called capsaicin",
  greenonion: "Young onions harvested before the bulb swells",
  honeydew: "A melon with pale green flesh and a smooth rind",
  butternutsquash: "A winter squash with sweet, nutty orange flesh",
  redcabbage: "Its juice can act as a natural pH indicator",
  jalapeno: "A chili pepper named after the Mexican city Xalapa",
  clementine: "A seedless hybrid of mandarin and sweet orange",
  pomelo: "The largest citrus fruit and ancestor of grapefruit",
  yam: "A starchy tuber often confused with sweet potato",
  snappeas: "A pea bred to be eaten whole, pod and all",
  beansprouts: "Germinated seeds, often from mung or soybeans",
  arugula: "A peppery salad green also known as rocket",
  cornsalad: "A mild salad green also called lamb's lettuce",

  // ===== MEDIUM =====
  collardgreens: "A loose-leaf cabbage cousin and Southern US staple",
  mustardgreens: "Peppery leaves from the same plant as mustard seed",
  acornsquash: "A ridged winter squash shaped like an acorn",
  spaghettisquash: "Cooked, its flesh pulls into spaghetti-like strands",
  endive: "A leafy chicory often grown in the dark to stay pale",
  boysenberry: "A cross of raspberry, blackberry and loganberry",
  mulberry: "Grows on trees and stains fingers deep purple",
  redcurrant: "Tart translucent red berries growing in clusters",
  satsuma: "A seedless, easy-peel mandarin from Japan",
  snowpeas: "Flat pods eaten whole before the peas swell",
  celeriac: "The knobby edible root of a celery variety",
  jicama: "A crunchy Mexican root eaten raw like an apple",
  taro: "A starchy root that must be cooked before eating",
  cassava: "A tropical root and the source of tapioca",
  lotusroot: "The crunchy stem of the lotus, full of holes",
  waterchestnut: "An aquatic corm that stays crunchy after cooking",
  napacabbage: "A mild Chinese cabbage used to make kimchi",
  savoycabbage: "A cabbage with crinkled, tender green leaves",
  broccolini: "A hybrid of broccoli and Chinese broccoli",
  frisee: "A curly, slightly bitter type of endive",
  sorrel: "A leafy green with a sharp, lemony taste",
  lingonberry: "A tart red berry popular across Scandinavia",
  huckleberry: "A wild blue-black berry resembling a blueberry",
  wintermelon: "A large gourd used in Asian soups and candies",
  dandeliongreens: "The edible bitter leaves of the dandelion plant",

  // ===== HARD =====
  cloudberry: "An amber Arctic berry prized in Nordic cuisine",
  loganberry: "A cross between a raspberry and a blackberry",
  tayberry: "A raspberry-blackberry cross bred in Scotland",
  barberry: "Tiny tart red berries used in Persian rice",
  seabuckthorn: "A tart orange berry rich in vitamin C",
  mirabelle: "A small, sweet yellow plum from Lorraine",
  greengage: "A sweet green-skinned variety of plum",
  damson: "A small dark plum used mostly for jam",
  sloe: "The tart wild fruit of the blackthorn bush",
  jujube: "Also called red date; sweet when dried",
  sapodilla: "A brown tropical fruit that tastes of brown sugar",
  serviceberry: "A sweet purple berry from a flowering shrub",
  chokeberry: "An astringent dark berry also called aronia",
  samphire: "A crunchy, salty green that grows by the sea",
  chicory: "Its roasted root is used as a coffee substitute",
  puntarelle: "A bitter Italian chicory eaten in salads",
  seakale: "A coastal cabbage relative with edible shoots",
  mizuna: "A feathery Japanese mustard green",
  tatsoi: "An Asian green with spoon-shaped dark leaves",
  gailan: "Chinese broccoli, grown for its leafy stems",
  choysum: "A leafy Asian green with edible yellow flowers",
  fiddleheads: "The curled young shoots of edible ferns",
  purslane: "A succulent green weed rich in omega-3 fats",
  amaranth: "Its leaves and tiny seeds are both edible",
  rosehip: "The fruit of the rose, packed with vitamin C",

  // ===== IMPOSSIBLE =====
  pitanga: "A ribbed tropical cherry native to Brazil",
  langsat: "A translucent Southeast Asian fruit in clusters",
  marang: "A sweet cousin of jackfruit from the Philippines",
  bilimbi: "An extremely sour relative of the starfruit",
  santol: "A tangy tropical fruit with a thick rind",
  mamey: "A tropical fruit with sweet orange-red flesh",
  abiu: "A yellow Amazonian fruit with jelly-like flesh",
  jocote: "A small tropical plum from Central America",
  nance: "A tiny yellow tropical fruit with a strong smell",
  lucuma: "A Peruvian fruit with dry, sweet golden flesh",
  pepino: "A striped melon-pear from the Andes",
  tamarillo: "The tart tree tomato of South America",
  gac: "A spiky red-orange gourd from Vietnam",
  noni: "A pungent tropical fruit used in health drinks",
  cempedak: "A stronger-flavored relative of the jackfruit",
  wampee: "A grape-sized citrus relative from China",
  sugarapple: "A knobby green fruit with sweet custard flesh",
  rollinia: "An Amazonian fruit that tastes of lemon custard",
  oca: "An Andean tuber eaten much like a potato",
  ulluco: "A colorful Andean tuber with waxy flesh",
  mashua: "An Andean root crop related to nasturtium",
  arracacha: "An Andean root between carrot and celery",
  crosne: "A tiny tuber also called Chinese artichoke",
  yacon: "A sweet, crunchy Andean tuber eaten raw",
  skirret: "An old European vegetable of sweet white roots",
};
