// E140 fruit/veg emoji facts — one verified <=70-char fact per item, shown on reveal.
export const FRUIT_EMOJI_FACTS = {
  // ===== EASY =====
  apple: "There are over 7,500 known varieties grown worldwide.",
  banana: "Botanically a berry; grows on a giant herb, not a tree.",
  orange: "The world's most cultivated citrus fruit by volume.",
  strawberry: "The only fruit with its seeds on the outside.",
  carrot: "Wild carrots were originally purple, not orange.",
  tomato: "Botanically a fruit, legally a vegetable in the US.",
  potato: "First domesticated in the Andes over 7,000 years ago.",
  grapes: "Used to make wine, raisins, jelly and juice.",
  watermelon: "About 92 percent water by weight.",
  pineapple: "Takes nearly two years to grow to full ripeness.",
  lemon: "One lemon can contain up to 30 mg of vitamin C.",
  broccoli: "A cultivated descendant of wild cabbage.",
  corn: "The most widely grown grain crop in the Americas.",
  onion: "Cutting one releases a gas that irritates the eyes.",
  cucumber: "Actually a fruit, made of about 95 percent water.",
  pumpkin: "A type of winter squash, mostly water by weight.",
  cherries: "A stone fruit related to plums and almonds.",
  peach: "Native to China, cultivated for thousands of years.",
  mango: "Called the king of fruits across South Asia.",
  avocado: "A single-seed berry, unusually high in healthy fat.",
  pear: "Ripens from the inside out, unlike most fruit.",
  coconut: "Its water was once used as an emergency IV fluid.",
  "bell-pepper": "A pepper variety bred to have no capsaicin heat.",
  garlic: "A close relative of onions, leeks and chives.",
  eggplant: "Botanically a berry in the nightshade family.",

  // ===== MEDIUM =====
  dragonfruit: "Blooms only at night on a climbing cactus plant.",
  passionfruit: "Named for symbolism in the passion of Christ, not taste.",
  starfruit: "Slices naturally form a five-pointed star shape.",
  persimmon: "Astringent varieties turn sweet only once fully soft.",
  guava: "A single fruit can hold four times a lemon's vitamin C.",
  papaya: "Contains papain, an enzyme used to tenderize meat.",
  pomegranate: "A single fruit can hold over 600 juicy seeds.",
  fig: "Technically an inverted cluster of tiny flowers.",
  kumquat: "Eaten whole, peel and all, unlike most citrus.",
  "custard-apple": "Its creamy flesh is often eaten straight with a spoon.",
  mangosteen: "Called the queen of fruits in Southeast Asia.",
  "blood-orange": "Gets its red flesh from anthocyanin pigments.",
  blackberry: "Not a true berry; it's a cluster of tiny drupelets.",
  mulberry: "Its leaves are the main food source for silkworms.",
  cranberry: "Farmers flood bogs with water to harvest it by floating.",
  gooseberry: "Grows on a thorny shrub, tart until fully ripe.",
  elderberry: "Must be cooked before eating; raw berries are toxic.",
  rhubarb: "Its leaves are toxic; only the stalks are eaten.",
  kohlrabi: "Its name means cabbage-turnip in German.",
  okra: "Its pods release a sticky texture used to thicken stews.",
  artichoke: "The edible part is an unopened flower bud.",
  radish: "A fast-growing root ready to harvest in under a month.",
  parsnip: "Tastes sweeter after being exposed to frost.",
  jicama: "Its skin and seeds are toxic; only the root is eaten.",
  celeriac: "Grown for its knobby root, not its stalks.",

  // ===== HARD =====
  rambutan: "Its name means hairy in Malay, for its spiky skin.",
  durian: "Banned on public transit in parts of Asia for its smell.",
  lychee: "Its bumpy red shell hides sweet, translucent flesh.",
  longan: "Its name means dragon eye, for its dark shiny seed.",
  jackfruit: "Can weigh over 40 kilograms, the largest tree fruit.",
  breadfruit: "Tastes like fresh bread when roasted or baked.",
  cherimoya: "Mark Twain called it the most delicious fruit known.",
  soursop: "Its flesh is used to make creamy tropical drinks.",
  feijoa: "Tastes like a mix of pineapple, guava and mint.",
  physalis: "Wrapped in its own papery, lantern-shaped husk.",
  "ugli-fruit": "A citrus hybrid named literally for its bumpy looks.",
  yuzu: "Prized in Japan for its zest more than its juice.",
  "makrut-lime": "Its leaves flavor curries more than its bumpy fruit.",
  tamarillo: "Nicknamed the tree tomato for its shape and tang.",
  "prickly-pear": "The edible fruit of certain cactus pads.",
  kiwano: "Its jelly-like green flesh tastes like cucumber-lime.",
  salak: "Called snake fruit for its reddish-brown scaly skin.",
  loquat: "A small orange fruit that ripens in early spring.",
  quince: "Too hard and tart to eat raw; usually cooked into paste.",
  sapodilla: "Its sap was once the original source of chicle gum.",
  chayote: "A wrinkly, pear-shaped squash eaten raw or cooked.",
  "bitter-melon": "Named for its intensely bitter, warty green skin.",
  daikon: "A giant white radish common in East Asian cooking.",
  fiddlehead: "The tightly coiled young shoot of an ostrich fern.",
  "water-chestnut": "An aquatic vegetable that stays crunchy when cooked.",

  // ===== IMPOSSIBLE =====
  cempedak: "A smaller, sweeter cousin of the jackfruit.",
  ulluco: "An Andean tuber that comes in vivid rainbow colors.",
  skirret: "A once-popular sweet root now rarely grown.",
  yacon: "An Andean tuber that tastes like a crisp, juicy pear.",
  salsify: "Nicknamed the oyster plant for its briny flavor.",
  cardoon: "A thistle related to the artichoke, grown for its stalks.",
  romanesco: "Its florets form a natural, self-repeating spiral pattern.",
  kabocha: "A Japanese winter squash with dense, sweet orange flesh.",
  "delicata-squash": "Named for its thin, easy-to-eat striped skin.",
  "buddhas-hand": "A citrus that splits into finger-like segments.",
  cucamelon: "Looks like a tiny watermelon, tastes like cucumber.",
  "miracle-fruit": "Its berry makes sour foods taste sweet afterward.",
  ackee: "Jamaica's national fruit; toxic until it opens naturally.",
  noni: "Known for its strong smell and use in folk medicine.",
  "pepino-melon": "A melon-pear with faint purple stripes on cream skin.",
  naranjilla: "A tart Andean fruit used to make green juice.",
  jabuticaba: "A Brazilian fruit that grows straight on the tree trunk.",
  cloudberry: "A golden Nordic berry that ripens in short summers.",
  marula: "Elephants famously seek out its fallen, fermenting fruit.",
  medlar: "Traditionally eaten only after it has softened, or bletted.",
  "spanish-lime": "Small green Caribbean fruit eaten by sucking the pulp.",
  "wax-apple": "Its crisp, watery flesh has a mild rose-like scent.",
  "monstera-fruit": "Must ripen slowly; unripe fruit can irritate the mouth.",
  achacha: "A Bolivian fruit you squeeze open to pop out the flesh.",
  loofah: "Left to mature, its fibrous inside becomes a scrub sponge.",
};
