// E21 — Guess the Fruit or Vegetable. 100 items, 25 per difficulty tier.
// image: fruits/<slug>.jpg (objectFit cover)  |  VO: sfx/fr-<slug>.wav  ("It's the <name>!")
export const FRUITS = [
  // ===== EASY (25) — 90%+ recognize on sight =====
  { slug: "apple", name: "Apple", wiki: "Apple", level: "easy" },
  { slug: "banana", name: "Banana", wiki: "Banana", level: "easy" },
  { slug: "orange", name: "Orange", wiki: "Orange (fruit)", level: "easy" },
  { slug: "strawberry", name: "Strawberry", wiki: "Strawberry", level: "easy" },
  { slug: "carrot", name: "Carrot", wiki: "Carrot", level: "easy" },
  { slug: "tomato", name: "Tomato", wiki: "Tomato", level: "easy" },
  { slug: "potato", name: "Potato", wiki: "Potato", level: "easy" },
  { slug: "grape", name: "Grape", wiki: "Grape", level: "easy" },
  { slug: "watermelon", name: "Watermelon", wiki: "Watermelon", level: "easy" },
  { slug: "pineapple", name: "Pineapple", wiki: "Pineapple", level: "easy" },
  { slug: "lemon", name: "Lemon", wiki: "Lemon", level: "easy" },
  { slug: "broccoli", name: "Broccoli", wiki: "Broccoli", level: "easy" },
  { slug: "corn", name: "Corn", wiki: "Maize", level: "easy" },
  { slug: "onion", name: "Onion", wiki: "Onion", level: "easy" },
  { slug: "cucumber", name: "Cucumber", wiki: "Cucumber", level: "easy" },
  { slug: "pumpkin", name: "Pumpkin", wiki: "Pumpkin", level: "easy" },
  { slug: "cherry", name: "Cherry", wiki: "Cherry", level: "easy" },
  { slug: "peach", name: "Peach", wiki: "Peach", level: "easy" },
  { slug: "mango", name: "Mango", wiki: "Mango", level: "easy" },
  { slug: "avocado", name: "Avocado", wiki: "Avocado", level: "easy" },
  { slug: "lettuce", name: "Lettuce", wiki: "Lettuce", level: "easy" },
  { slug: "pear", name: "Pear", wiki: "Pear", level: "easy" },
  { slug: "coconut", name: "Coconut", wiki: "Coconut", level: "easy" },
  { slug: "bell-pepper", name: "Bell Pepper", wiki: "Bell pepper", level: "easy" },
  { slug: "garlic", name: "Garlic", wiki: "Garlic", level: "easy" },

  // ===== MEDIUM (25) — ~50% recognize =====
  { slug: "pomegranate", name: "Pomegranate", wiki: "Pomegranate", level: "medium" },
  { slug: "kiwifruit", name: "Kiwifruit", wiki: "Kiwifruit", level: "medium" },
  { slug: "eggplant", name: "Eggplant", wiki: "Eggplant", level: "medium" },
  { slug: "cauliflower", name: "Cauliflower", wiki: "Cauliflower", level: "medium" },
  { slug: "ginger", name: "Ginger", wiki: "Ginger", level: "medium" },
  { slug: "papaya", name: "Papaya", wiki: "Papaya", level: "medium" },
  { slug: "fig", name: "Fig", wiki: "Fig", level: "medium" },
  { slug: "cranberry", name: "Cranberry", wiki: "Cranberry", level: "medium" },
  { slug: "artichoke", name: "Artichoke", wiki: "Artichoke", level: "medium" },
  { slug: "beetroot", name: "Beetroot", wiki: "Beetroot", level: "medium" },
  { slug: "radish", name: "Radish", wiki: "Radish", level: "medium" },
  { slug: "asparagus", name: "Asparagus", wiki: "Asparagus", level: "medium" },
  { slug: "zucchini", name: "Zucchini", wiki: "Zucchini", level: "medium" },
  { slug: "blackberry", name: "Blackberry", wiki: "Blackberry", level: "medium" },
  { slug: "passion-fruit", name: "Passion Fruit", wiki: "Passiflora edulis", level: "medium" },
  { slug: "cantaloupe", name: "Cantaloupe", wiki: "Cantaloupe", level: "medium" },
  { slug: "leek", name: "Leek", wiki: "Leek", level: "medium" },
  { slug: "turnip", name: "Turnip", wiki: "Turnip", level: "medium" },
  { slug: "plum", name: "Plum", wiki: "Plum", level: "medium" },
  { slug: "apricot", name: "Apricot", wiki: "Apricot", level: "medium" },
  { slug: "sweet-potato", name: "Sweet Potato", wiki: "Sweet potato", level: "medium" },
  { slug: "celery", name: "Celery", wiki: "Celery", level: "medium" },
  { slug: "okra", name: "Okra", wiki: "Okra", level: "medium" },
  { slug: "brussels-sprout", name: "Brussels Sprout", wiki: "Brussels sprout", level: "medium" },
  { slug: "date", name: "Date", wiki: "Date palm", level: "medium" },

  // ===== HARD (25) — ~15% recognize =====
  { slug: "dragon-fruit", name: "Dragon Fruit", wiki: "Dragon fruit", level: "hard" },
  { slug: "lychee", name: "Lychee", wiki: "Lychee", level: "hard" },
  { slug: "persimmon", name: "Persimmon", wiki: "Persimmon", level: "hard" },
  { slug: "guava", name: "Guava", wiki: "Guava", level: "hard" },
  { slug: "star-fruit", name: "Star Fruit", wiki: "Carambola", level: "hard" },
  { slug: "kohlrabi", name: "Kohlrabi", wiki: "Kohlrabi", level: "hard" },
  { slug: "fennel", name: "Fennel", wiki: "Fennel", level: "hard" },
  { slug: "rutabaga", name: "Rutabaga", wiki: "Rutabaga", level: "hard" },
  { slug: "plantain", name: "Plantain", wiki: "Cooking banana", level: "hard" },
  { slug: "quince", name: "Quince", wiki: "Quince", level: "hard" },
  { slug: "gooseberry", name: "Gooseberry", wiki: "Gooseberry", level: "hard" },
  { slug: "kumquat", name: "Kumquat", wiki: "Kumquat", level: "hard" },
  { slug: "radicchio", name: "Radicchio", wiki: "Radicchio", level: "hard" },
  { slug: "daikon", name: "Daikon", wiki: "Daikon", level: "hard" },
  { slug: "bok-choy", name: "Bok Choy", wiki: "Bok choy", level: "hard" },
  { slug: "chard", name: "Chard", wiki: "Chard", level: "hard" },
  { slug: "tamarind", name: "Tamarind", wiki: "Tamarind", level: "hard" },
  { slug: "rhubarb", name: "Rhubarb", wiki: "Rhubarb", level: "hard" },
  { slug: "shallot", name: "Shallot", wiki: "Shallot", level: "hard" },
  { slug: "watercress", name: "Watercress", wiki: "Watercress", level: "hard" },
  { slug: "romanesco", name: "Romanesco", wiki: "Romanesco broccoli", level: "hard" },
  { slug: "currant", name: "Currant", wiki: "Blackcurrant", level: "hard" },
  { slug: "elderberry", name: "Elderberry", wiki: "Elderberry", level: "hard" },
  { slug: "parsnip", name: "Parsnip", wiki: "Parsnip", level: "hard" },
  { slug: "edamame", name: "Edamame", wiki: "Edamame", level: "hard" },

  // ===== IMPOSSIBLE (25) — <3% recognize =====
  { slug: "salak", name: "Salak", wiki: "Salak", level: "impossible" },
  { slug: "jabuticaba", name: "Jabuticaba", wiki: "Jabuticaba", level: "impossible" },
  { slug: "rambutan", name: "Rambutan", wiki: "Rambutan", level: "impossible" },
  { slug: "mangosteen", name: "Mangosteen", wiki: "Mangosteen", level: "impossible" },
  { slug: "durian", name: "Durian", wiki: "Durian", level: "impossible" },
  { slug: "cherimoya", name: "Cherimoya", wiki: "Cherimoya", level: "impossible" },
  { slug: "soursop", name: "Soursop", wiki: "Soursop", level: "impossible" },
  { slug: "ackee", name: "Ackee", wiki: "Ackee", level: "impossible" },
  { slug: "cupuacu", name: "Cupuacu", wiki: "Cupuaçu", level: "impossible" },
  { slug: "longan", name: "Longan", wiki: "Longan", level: "impossible" },
  { slug: "jackfruit", name: "Jackfruit", wiki: "Jackfruit", level: "impossible" },
  { slug: "breadfruit", name: "Breadfruit", wiki: "Breadfruit", level: "impossible" },
  { slug: "feijoa", name: "Feijoa", wiki: "Feijoa", level: "impossible" },
  { slug: "loquat", name: "Loquat", wiki: "Loquat", level: "impossible" },
  { slug: "medlar", name: "Medlar", wiki: "Mespilus germanica", level: "impossible" },
  { slug: "salsify", name: "Salsify", wiki: "Tragopogon porrifolius", level: "impossible" },
  { slug: "chayote", name: "Chayote", wiki: "Chayote", level: "impossible" },
  { slug: "sunchoke", name: "Sunchoke", wiki: "Jerusalem artichoke", level: "impossible" },
  { slug: "yardlong-bean", name: "Yardlong Bean", wiki: "Yardlong bean", level: "impossible" },
  { slug: "bitter-melon", name: "Bitter Melon", wiki: "Bitter melon", level: "impossible" },
  { slug: "buddhas-hand", name: "Buddha's Hand", wiki: "Buddha's hand", level: "impossible" },
  { slug: "physalis", name: "Physalis", wiki: "Physalis peruviana", level: "impossible" },
  { slug: "miracle-fruit", name: "Miracle Fruit", wiki: "Synsepalum dulcificum", level: "impossible" },
  { slug: "pawpaw", name: "Pawpaw", wiki: "Asimina triloba", level: "impossible" },
  { slug: "ugli-fruit", name: "Ugli Fruit", wiki: "Jamaican tangelo", level: "impossible" },
];
