// E126 «Guess the Video Game by Emoji 2» — 100 games · 25/tier · clue via OpenMoji · VO: sfx/eg2-<id>.wav
export const GAME_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "super-smash-bros", title: "Super Smash Bros.", emojis: "👊⭐", level: "easy" },
  { id: "donkey-kong", title: "Donkey Kong", emojis: "🐵🍌", level: "easy" },
  { id: "kirby", title: "Kirby", emojis: "💗💨", level: "easy" },
  { id: "frogger", title: "Frogger", emojis: "🐸🚗", level: "easy" },
  { id: "galaga", title: "Galaga", emojis: "👾🚀", level: "easy" },
  { id: "asteroids", title: "Asteroids", emojis: "🚀🌑", level: "easy" },
  { id: "centipede", title: "Centipede", emojis: "🐛🔫", level: "easy" },
  { id: "qbert", title: "Q*bert", emojis: "🟠🔺", level: "easy" },
  { id: "breakout", title: "Breakout", emojis: "🧱⚪", level: "easy" },
  { id: "2048", title: "2048", emojis: "🔢🟦", level: "easy" },
  { id: "cookie-clicker", title: "Cookie Clicker", emojis: "🍪💰", level: "easy" },
  { id: "slitherio", title: "Slither.io", emojis: "🐍🟢", level: "easy" },
  { id: "agario", title: "Agar.io", emojis: "🔵🟣", level: "easy" },
  { id: "doodle-jump", title: "Doodle Jump", emojis: "🟢👾", level: "easy" },
  { id: "piano-tiles-2", title: "Piano Tiles 2", emojis: "🎹⬛", level: "easy" },
  { id: "color-switch", title: "Color Switch", emojis: "🔴🔵", level: "easy" },
  { id: "helix-jump", title: "Helix Jump", emojis: "🌀⚪", level: "easy" },
  { id: "jetpack-joyride", title: "Jetpack Joyride", emojis: "🏃🚀", level: "easy" },
  { id: "farmville", title: "FarmVille", emojis: "🚜🌽", level: "easy" },
  { id: "trivia-crack", title: "Trivia Crack", emojis: "🧠❓", level: "easy" },
  { id: "ludo-king", title: "Ludo King", emojis: "🎲👑", level: "easy" },
  { id: "minesweeper", title: "Minesweeper", emojis: "💣🟦", level: "easy" },
  { id: "talking-tom", title: "Talking Tom", emojis: "🐱🎤", level: "easy" },
  { id: "animal-crossing", title: "Animal Crossing", emojis: "🍁🏝", level: "easy" },
  { id: "splatoon", title: "Splatoon", emojis: "🦑🎨", level: "easy" },
  // ===== MEDIUM (25) =====
  { id: "kingdom-hearts", title: "Kingdom Hearts", emojis: "🔑❤", level: "medium" },
  { id: "persona-5", title: "Persona 5", emojis: "🎭🔥", level: "medium" },
  { id: "final-fantasy-vii", title: "Final Fantasy VII", emojis: "⚔🌌", level: "medium" },
  { id: "apex-legends", title: "Apex Legends", emojis: "👑🔫", level: "medium" },
  { id: "valorant", title: "Valorant", emojis: "🎯💥", level: "medium" },
  { id: "league-of-legends", title: "League of Legends", emojis: "🐉⚔", level: "medium" },
  { id: "dota-2", title: "Dota 2", emojis: "🧙⚔", level: "medium" },
  { id: "terraria", title: "Terraria", emojis: "⛏🟩", level: "medium" },
  { id: "rust", title: "Rust", emojis: "🏚🔫", level: "medium" },
  { id: "dead-by-daylight", title: "Dead by Daylight", emojis: "🔦🌙", level: "medium" },
  { id: "phasmophobia", title: "Phasmophobia", emojis: "👻🔦", level: "medium" },
  { id: "payday-2", title: "PAYDAY 2", emojis: "🎭💰", level: "medium" },
  { id: "need-for-speed", title: "Need for Speed", emojis: "🚗🏁", level: "medium" },
  { id: "forza-horizon", title: "Forza Horizon", emojis: "🚗🌄", level: "medium" },
  { id: "nba-2k", title: "NBA 2K", emojis: "🏀🎮", level: "medium" },
  { id: "tony-hawks-pro-skater", title: "Tony Hawk's Pro Skater", emojis: "🛹🏆", level: "medium" },
  { id: "crash-bandicoot", title: "Crash Bandicoot", emojis: "🦘📦", level: "medium" },
  { id: "spyro-the-dragon", title: "Spyro the Dragon", emojis: "🐉🔥", level: "medium" },
  { id: "banjo-kazooie", title: "Banjo-Kazooie", emojis: "🐻🐦", level: "medium" },
  { id: "rayman", title: "Rayman", emojis: "👊🌀", level: "medium" },
  { id: "dying-light", title: "Dying Light", emojis: "🧟🌃", level: "medium" },
  { id: "dead-space", title: "Dead Space", emojis: "🩸👽", level: "medium" },
  { id: "alien-isolation", title: "Alien: Isolation", emojis: "👽🔦", level: "medium" },
  { id: "poppy-playtime", title: "Poppy Playtime", emojis: "🧸✋", level: "medium" },
  { id: "gang-beasts", title: "Gang Beasts", emojis: "👊🟣", level: "medium" },
  // ===== HARD (25) =====
  { id: "nier-automata", title: "NieR:Automata", emojis: "🤖⚔", level: "hard" },
  { id: "death-stranding", title: "Death Stranding", emojis: "📦🏃", level: "hard" },
  { id: "control", title: "Control", emojis: "🏢🌀", level: "hard" },
  { id: "katana-zero", title: "Katana Zero", emojis: "⚔⏳", level: "hard" },
  { id: "hotline-miami", title: "Hotline Miami", emojis: "🎭🔫", level: "hard" },
  { id: "the-binding-of-isaac", title: "The Binding of Isaac", emojis: "😢👶", level: "hard" },
  { id: "undertale", title: "Undertale", emojis: "💛⚔", level: "hard" },
  { id: "cave-story", title: "Cave Story", emojis: "🦇🔫", level: "hard" },
  { id: "inside", title: "Inside", emojis: "👦🌫", level: "hard" },
  { id: "machinarium", title: "Machinarium", emojis: "🤖🔧", level: "hard" },
  { id: "world-of-goo", title: "World of Goo", emojis: "🟢🌉", level: "hard" },
  { id: "monument-valley", title: "Monument Valley", emojis: "🏛🔺", level: "hard" },
  { id: "gris", title: "GRIS", emojis: "😢🌈", level: "hard" },
  { id: "abzu", title: "ABZU", emojis: "🌊🐋", level: "hard" },
  { id: "flower", title: "Flower", emojis: "🌸🌬", level: "hard" },
  { id: "the-stanley-parable", title: "The Stanley Parable", emojis: "💼❓", level: "hard" },
  { id: "firewatch", title: "Firewatch", emojis: "🔥🗼", level: "hard" },
  { id: "what-remains-of-edith-finch", title: "What Remains of Edith Finch", emojis: "🏚📖", level: "hard" },
  { id: "kentucky-route-zero", title: "Kentucky Route Zero", emojis: "🚗🌌", level: "hard" },
  { id: "oxenfree", title: "Oxenfree", emojis: "👻🏝", level: "hard" },
  { id: "superhot", title: "SUPERHOT", emojis: "⏳🔴", level: "hard" },
  { id: "inscryption", title: "Inscryption", emojis: "🃏🕯", level: "hard" },
  { id: "subnautica", title: "Subnautica", emojis: "🌊🐟", level: "hard" },
  { id: "no-mans-sky", title: "No Man's Sky", emojis: "🪐🚀", level: "hard" },
  { id: "a-short-hike", title: "A Short Hike", emojis: "⛰🦅", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { id: "the-witness", title: "The Witness", emojis: "🏝🧩", level: "impossible" },
  { id: "antichamber", title: "Antichamber", emojis: "🔲🌀", level: "impossible" },
  { id: "the-talos-principle", title: "The Talos Principle", emojis: "🤖🏛", level: "impossible" },
  { id: "gorogoa", title: "Gorogoa", emojis: "🧩🖼", level: "impossible" },
  { id: "hyper-light-drifter", title: "Hyper Light Drifter", emojis: "⚔🌆", level: "impossible" },
  { id: "titan-souls", title: "Titan Souls", emojis: "🏹🗿", level: "impossible" },
  { id: "rain-world", title: "Rain World", emojis: "🌧🦎", level: "impossible" },
  { id: "tunic", title: "TUNIC", emojis: "🦊⚔", level: "impossible" },
  { id: "sable", title: "Sable", emojis: "🏍🏜", level: "impossible" },
  { id: "pathologic", title: "Pathologic", emojis: "😷🩸", level: "impossible" },
  { id: "signalis", title: "SIGNALIS", emojis: "🤖🌙", level: "impossible" },
  { id: "iconoclasts", title: "Iconoclasts", emojis: "🔧👧", level: "impossible" },
  { id: "axiom-verge", title: "Axiom Verge", emojis: "👾🧬", level: "impossible" },
  { id: "the-swapper", title: "The Swapper", emojis: "👥🌌", level: "impossible" },
  { id: "duskers", title: "Duskers", emojis: "🚁🌑", level: "impossible" },
  { id: "the-vanishing-of-ethan-carter", title: "The Vanishing of Ethan Carter", emojis: "🕵🌲", level: "impossible" },
  { id: "her-story", title: "Her Story", emojis: "🎥❓", level: "impossible" },
  { id: "twelve-minutes", title: "Twelve Minutes", emojis: "⏰🔄", level: "impossible" },
  { id: "opus-magnum", title: "Opus Magnum", emojis: "🧪🔧", level: "impossible" },
  { id: "human-fall-flat", title: "Human: Fall Flat", emojis: "🧍🌀", level: "impossible" },
  { id: "the-room", title: "The Room", emojis: "🔑📦", level: "impossible" },
  { id: "lumines", title: "Lumines", emojis: "🎵🟦", level: "impossible" },
  { id: "thumper", title: "Thumper", emojis: "🎵💥", level: "impossible" },
  { id: "n-plus-plus", title: "N++", emojis: "🏃🔺", level: "impossible" },
  { id: "downwell", title: "Downwell", emojis: "🔫⬛", level: "impossible" },
];
