// E126 emoji-game-2 facts — one verified <=70-char fact per game, shown on reveal.
export const GAME_EMOJI_2_FACTS = {
  // EASY
  "super-smash-bros": "First Smash Bros. launched on N64 in Japan in January 1999.",
  "donkey-kong": "1981 Nintendo arcade game; Mario's first appearance as 'Jumpman'.",
  "kirby": "Kirby's Dream Land launched on Game Boy in April 1992.",
  "frogger": "1981 Konami arcade classic; hop the frog across traffic and a river.",
  "galaga": "Namco's 1981 sequel to Galaxian; became an arcade shoot-'em-up icon.",
  "asteroids": "Atari's 1979 vector arcade game; one of the era's biggest hits.",
  "centipede": "Atari arcade game released June 6, 1981; used a trackball control.",
  "guitar-hero": "Harmonix's plastic-guitar rhythm game debuted on PS2 in Nov. 2005.",
  "breakout": "Atari's 1976 brick-breaking game, co-designed by Steve Wozniak.",
  "2048": "Gabriele Cirulli released the sliding number puzzle in March 2014.",
  "cookie-clicker": "Orteil's idle clicker launched free in the browser in August 2013.",
  "slitherio": "Steve Howse's browser snake game went viral in March 2016.",
  "fall-guys": "Mediatonic's jellybean battle royale launched in August 2020.",
  "geometry-dash": "RobTop's rhythm-based platformer launched on mobile in August 2013.",
  "piano-tiles-2": "Cheetah Mobile's rhythm-tap sequel launched worldwide in 2015.",
  "color-switch": "Fortafy Games' one-tap arcade hit topped charts in 2015.",
  "helix-jump": "Voodoo's spiral-tower tapper became a global hit in 2018.",
  "jetpack-joyride": "Halfbrick's 2011 side-scrolling jetpack endless runner.",
  "farmville": "Zynga's Facebook farming game launched June 19, 2009.",
  "trivia-crack": "Etermax's quiz app topped app store charts in 2013.",
  "ludo-king": "Gametion's board game app crossed a billion downloads by 2023.",
  "minesweeper": "Microsoft first bundled this logic game with Windows 3.1 in 1992.",
  "talking-tom": "Outfit7's mimicking cat app launched on iOS on June 26, 2010.",
  "animal-crossing": "The life-sim series debuted on Nintendo 64 in Japan in 2001.",
  "splatoon": "Nintendo's ink-shooter debuted on Wii U in May 2015.",

  // MEDIUM
  "kingdom-hearts": "Square and Disney's crossover RPG launched in Japan in March 2002.",
  "persona-5": "Atlus RPG released in Japan in September 2016; famed for its style.",
  "final-fantasy-vii": "Square's 1997 RPG sold over 15 million copies worldwide.",
  "apex-legends": "Respawn's battle royale launched as a surprise release in Feb. 2019.",
  "valorant": "Riot Games' tactical shooter launched worldwide in June 2020.",
  "league-of-legends": "Riot Games' MOBA launched in October 2009; still hugely popular.",
  "dota-2": "Valve's MOBA launched in July 2013, sequel to a Warcraft III mod.",
  "terraria": "Re-Logic's 2D sandbox launched May 2011; sold 58M+ copies.",
  "rust": "Facepunch Studios' survival game left early access in Feb. 2018.",
  "dead-by-daylight": "Behaviour Interactive's asymmetric horror launched in June 2016.",
  "phasmophobia": "Kinetic Games' co-op ghost hunter launched in early access in 2020.",
  "payday-2": "Overkill Software's heist shooter launched in August 2013.",
  "need-for-speed": "The racing series debuted on 3DO in 1994 under Electronic Arts.",
  "forza-horizon": "Playground Games' open-world racer debuted on Xbox 360 in 2012.",
  "nba-2k": "Visual Concepts' basketball series debuted on Dreamcast in 1999.",
  "tony-hawks-pro-skater": "Neversoft's skating game launched on PlayStation in Sept. 1999.",
  "crash-bandicoot": "Naughty Dog's marsupial platformer debuted on PS1 in Sept. 1996.",
  "spyro-the-dragon": "Insomniac Games' dragon platformer launched on PS1 in Sept. 1998.",
  "banjo-kazooie": "Rare's bear-and-bird platformer launched on N64 in June 1998.",
  "rayman": "Ubisoft's limbless hero debuted on PlayStation in September 1995.",
  "dying-light": "Techland's parkour zombie game launched in January 2015.",
  "dead-space": "Visceral Games' sci-fi horror game launched in October 2008.",
  "alien-isolation": "Creative Assembly's stealth horror game launched in October 2014.",
  "poppy-playtime": "Mob Entertainment's horror game launched on Steam October 12, 2021.",
  "gang-beasts": "Boneloaf's floppy-physics brawler launched fully in Dec. 2017.",

  // HARD
  "nier-automata": "PlatinumGames' action RPG launched worldwide in Feb.-March 2017.",
  "death-stranding": "Kojima Productions' delivery game launched in November 2019.",
  "control": "Remedy Entertainment's supernatural shooter launched in August 2019.",
  "katana-zero": "Askiisoft's neo-noir action game launched in April 2019.",
  "hotline-miami": "Dennaton Games' top-down brawler launched in October 2012.",
  "the-binding-of-isaac": "Edmund McMillen's roguelike launched on Steam in Sept. 2011.",
  "undertale": "Toby Fox's RPG launched on Steam on September 15, 2015.",
  "cave-story": "Daisuke Amaya (Pixel) released this indie freeware game in 2004.",
  "inside": "Playdead's dark puzzle-platformer launched worldwide in June 2016.",
  "ori": "Moon Studios' Ori and the Blind Forest launched in March 2015.",
  "world-of-goo": "2D Boy's physics puzzle game launched independently in October 2008.",
  "monument-valley": "Ustwo Games' optical-illusion puzzler launched in April 2014.",
  "celeste": "Pixel platformer about climbing Celeste Mountain; out Jan. 2018.",
  "abzu": "Giant Squid's underwater exploration game launched in August 2016.",
  "flower": "Thatgamecompany's petal-blowing game launched on PS3 in Feb. 2009.",
  "the-stanley-parable": "Davey Wreden's narrative game launched in full in Oct. 2013.",
  "firewatch": "Campo Santo's first-person mystery launched in February 2016.",
  "what-remains-of-edith-finch": "Giant Sparrow's story game launched in April 2017.",
  "kentucky-route-zero": "Cardboard Computer's magical-realist game began releasing in 2013.",
  "oxenfree": "Night School Studio's supernatural teen mystery launched in Jan. 2016.",
  "superhot": "Superhot Team's time-bends-with-motion shooter launched Feb. 2016.",
  "inscryption": "Daniel Mullins Games' card-horror hybrid launched Oct. 19, 2021.",
  "subnautica": "Unknown Worlds' underwater survival game left early access in 2018.",
  "no-mans-sky": "Hello Games' procedural space explorer launched in August 2016.",
  "a-short-hike": "Adam Robinson-Yu's solo-developed climbing game launched in 2019.",

  // IMPOSSIBLE
  "the-witness": "Jonathan Blow's maze-puzzle island game launched in Jan. 2016.",
  "outer-wilds": "Mobius Digital's time-loop space mystery launched in May 2019.",
  "the-talos-principle": "Croteam's philosophical puzzle game launched in Dec. 2014.",
  "journey": "Thatgamecompany's wordless desert adventure launched on PS3 in 2012.",
  "hades": "Supergiant Games' underworld roguelike launched fully in Sept. 2020.",
  "titan-souls": "Acid Nerve's one-hit-kill boss-rush game launched in April 2015.",
  "rain-world": "Videocult's slugcat survival game launched in March 2017.",
  "tunic": "Andrew Shouldice's fox-adventure game launched March 16, 2022.",
  "stray": "BlueTwelve Studio's cyberpunk cat adventure launched in July 2022.",
  "papers-please": "Lucas Pope's dystopian border-checkpoint game launched Aug. 2013.",
  "spiritfarer": "Thunder Lotus' cozy afterlife ferry game launched in August 2020.",
  "disco-elysium": "ZA/UM's detective RPG launched in 2019; famed for its writing.",
  "slay-the-spire": "MegaCrit's deckbuilding roguelike left early access in Jan. 2019.",
  "the-swapper": "Facepalm Games' cloning puzzle game launched in May 2013.",
  "untitled-goose-game": "House House's mischievous goose sandbox launched in Sept. 2019.",
  "the-vanishing-of-ethan-carter": "The Astronauts' detective game launched in Sept. 2014.",
  "her-story": "Sam Barlow's FMV detective game launched on Steam in June 2015.",
  "twelve-minutes": "Luis Antonio's time-loop thriller launched August 19, 2021.",
  "stardew-valley": "ConcernedApe solo-made this farming sim, released Feb. 2016.",
  "human-fall-flat": "No Brakes Games' ragdoll physics puzzler launched in July 2016.",
  "the-room": "Fireproof Games' puzzle-box game launched on iOS in Sept. 2012.",
  "cuphead": "StudioMDHR's 1930s-cartoon run-and-gun launched in September 2017.",
  "braid": "Jonathan Blow's time-bending puzzle-platformer launched in 2008.",
  "spelunky": "Derek Yu's cave-diving roguelike first launched free in 2008.",
  "downwell": "Ojiro Fumoto's gun-boots roguelike launched in October 2015.",
};
