// E153 «Guess the Video Game Character by Emoji» — 100 characters · 25/tier · clue = plain Unicode emoji
// Every emoji fairly leads to the CHARACTER via iconic look/power. Single-codepoint only (no FE0F/ZWJ/keycap).
// VO: sfx/e153-<id>.wav ("It's <Character>!") — distinct prefix, no collisions.
export const GAMECHAR_EMOJI = [
  // ===== EASY (25) — globally famous mascots =====
  { id: "mario", title: "Mario", emojis: "🍄👨", level: "easy" },
  { id: "luigi", title: "Luigi", emojis: "💚👨", level: "easy" },
  { id: "pikachu", title: "Pikachu", emojis: "⚡🐭", level: "easy" },
  { id: "sonic", title: "Sonic", emojis: "💙🦔", level: "easy" },
  { id: "kirby", title: "Kirby", emojis: "🩷⭐", level: "easy" },
  { id: "pac-man", title: "Pac-Man", emojis: "🟡👻", level: "easy" },
  { id: "yoshi", title: "Yoshi", emojis: "🥚🦖", level: "easy" },
  { id: "bowser", title: "Bowser", emojis: "🐢🔥", level: "easy" },
  { id: "donkey-kong", title: "Donkey Kong", emojis: "🦍👔", level: "easy" },
  { id: "link", title: "Link", emojis: "🗡🛡", level: "easy" },
  { id: "zelda", title: "Zelda", emojis: "👑🧝", level: "easy" },
  { id: "steve", title: "Steve (Minecraft)", emojis: "🧱⛏", level: "easy" },
  { id: "creeper", title: "Creeper", emojis: "🟢💥", level: "easy" },
  { id: "master-chief", title: "Master Chief", emojis: "🪖🔫", level: "easy" },
  { id: "samus", title: "Samus Aran", emojis: "🚀🔫", level: "easy" },
  { id: "mega-man", title: "Mega Man", emojis: "🔵🤖", level: "easy" },
  { id: "crash-bandicoot", title: "Crash Bandicoot", emojis: "🍎📦", level: "easy" },
  { id: "spyro", title: "Spyro", emojis: "💜🐉", level: "easy" },
  { id: "lara-croft", title: "Lara Croft", emojis: "🏹🏺", level: "easy" },
  { id: "kratos", title: "Kratos", emojis: "⚔🏛", level: "easy" },
  { id: "ryu", title: "Ryu", emojis: "🥋👊", level: "easy" },
  { id: "sub-zero", title: "Sub-Zero", emojis: "❄🥷", level: "easy" },
  { id: "scorpion", title: "Scorpion", emojis: "🔥🥷", level: "easy" },
  { id: "red-angry-birds", title: "Red (Angry Birds)", emojis: "🔴🐦", level: "easy" },
  { id: "princess-peach", title: "Princess Peach", emojis: "👑🍑", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "tails", title: "Tails", emojis: "🦊✈", level: "medium" },
  { id: "knuckles", title: "Knuckles", emojis: "🥊🔴", level: "medium" },
  { id: "cloud-strife", title: "Cloud Strife", emojis: "⚔🌩", level: "medium" },
  { id: "geralt", title: "Geralt of Rivia", emojis: "🐺🗡", level: "medium" },
  { id: "ezio", title: "Ezio Auditore", emojis: "🦅🔪", level: "medium" },
  { id: "nathan-drake", title: "Nathan Drake", emojis: "🗺🔫", level: "medium" },
  { id: "gordon-freeman", title: "Gordon Freeman", emojis: "🔬🦺", level: "medium" },
  { id: "solid-snake", title: "Solid Snake", emojis: "🚬📦", level: "medium" },
  { id: "chun-li", title: "Chun-Li", emojis: "🥋🦵", level: "medium" },
  { id: "ken-masters", title: "Ken Masters", emojis: "🔥👊", level: "medium" },
  { id: "dragonborn", title: "Dragonborn", emojis: "🐉🗡", level: "medium" },
  { id: "ellie", title: "Ellie", emojis: "🦋🔫", level: "medium" },
  { id: "aloy", title: "Aloy", emojis: "🏹🤖", level: "medium" },
  { id: "doomguy", title: "Doom Slayer", emojis: "👿🔫", level: "medium" },
  { id: "leon-kennedy", title: "Leon Kennedy", emojis: "🧟🔫", level: "medium" },
  { id: "dante", title: "Dante", emojis: "⚔😈", level: "medium" },
  { id: "bayonetta", title: "Bayonetta", emojis: "🔫💋", level: "medium" },
  { id: "sephiroth", title: "Sephiroth", emojis: "⚔👼", level: "medium" },
  { id: "pyramid-head", title: "Pyramid Head", emojis: "🔺🗡", level: "medium" },
  { id: "bomberman", title: "Bomberman", emojis: "💣🤖", level: "medium" },
  { id: "simon-belmont", title: "Simon Belmont", emojis: "🧛⛓", level: "medium" },
  { id: "sackboy", title: "Sackboy", emojis: "🧶🤎", level: "medium" },
  { id: "rayman", title: "Rayman", emojis: "👊🌀", level: "medium" },
  { id: "earthworm-jim", title: "Earthworm Jim", emojis: "🪱🔫", level: "medium" },
  { id: "olimar", title: "Captain Olimar", emojis: "🌱🚀", level: "medium" },

  // ===== HARD (25) =====
  { id: "ganondorf", title: "Ganondorf", emojis: "👑🐗", level: "hard" },
  { id: "vault-boy", title: "Vault Boy", emojis: "👍⚛", level: "hard" },
  { id: "big-daddy", title: "Big Daddy", emojis: "🤿⚙", level: "hard" },
  { id: "claptrap", title: "Claptrap", emojis: "🤖🛞", level: "hard" },
  { id: "kazuya", title: "Kazuya Mishima", emojis: "👿🥋", level: "hard" },
  { id: "shovel-knight", title: "Shovel Knight", emojis: "⛏🛡", level: "hard" },
  { id: "hollow-knight", title: "The Knight (Hollow Knight)", emojis: "🐛⚔", level: "hard" },
  { id: "ori", title: "Ori", emojis: "👻🌳", level: "hard" },
  { id: "madeline", title: "Madeline (Celeste)", emojis: "🧗⛰", level: "hard" },
  { id: "shadow-hedgehog", title: "Shadow the Hedgehog", emojis: "🖤🦔", level: "hard" },
  { id: "amaterasu", title: "Amaterasu (Okami)", emojis: "🐺🖌", level: "hard" },
  { id: "alucard", title: "Alucard", emojis: "🧛⚔", level: "hard" },
  { id: "2b", title: "2B (NieR: Automata)", emojis: "⚔🤖", level: "hard" },
  { id: "joel", title: "Joel", emojis: "🎸🔫", level: "hard" },
  { id: "arthur-morgan", title: "Arthur Morgan", emojis: "🤠🐴", level: "hard" },
  { id: "kk-slider", title: "K.K. Slider", emojis: "🐶🎸", level: "hard" },
  { id: "sans", title: "Sans", emojis: "💀🔵", level: "hard" },
  { id: "isabelle", title: "Isabelle", emojis: "🐕🔔", level: "hard" },
  { id: "cuphead", title: "Cuphead", emojis: "☕🔫", level: "hard" },
  { id: "shantae", title: "Shantae", emojis: "🧞💜", level: "hard" },
  { id: "bub-bubble-bobble", title: "Bub (Bubble Bobble)", emojis: "🐉🫧", level: "hard" },
  { id: "qbert", title: "Q*bert", emojis: "👽🔺", level: "hard" },
  { id: "frogger", title: "Frogger", emojis: "🐸🚗", level: "hard" },
  { id: "banjo-kazooie", title: "Banjo & Kazooie", emojis: "🐻🐦", level: "hard" },
  { id: "conker", title: "Conker", emojis: "🐿🍺", level: "hard" },

  // ===== IMPOSSIBLE (25) — deep cuts fans adore =====
  { id: "guybrush", title: "Guybrush Threepwood", emojis: "🐵🗡", level: "impossible" },
  { id: "katamari-prince", title: "The Prince (Katamari)", emojis: "🌈🎱", level: "impossible" },
  { id: "chell", title: "Chell", emojis: "🧪🌀", level: "impossible" },
  { id: "glados", title: "GLaDOS", emojis: "🤖🍰", level: "impossible" },
  { id: "wander", title: "Wander (Shadow of the Colossus)", emojis: "🐴🗡", level: "impossible" },
  { id: "chosen-undead", title: "The Chosen Undead", emojis: "💀🔥", level: "impossible" },
  { id: "solaire", title: "Solaire of Astora", emojis: "☀🛡", level: "impossible" },
  { id: "binding-isaac", title: "Isaac (Binding of Isaac)", emojis: "👶😢", level: "impossible" },
  { id: "cadence", title: "Cadence (Crypt of the NecroDancer)", emojis: "💃🎵", level: "impossible" },
  { id: "the-kid-bastion", title: "The Kid (Bastion)", emojis: "🔨🏝", level: "impossible" },
  { id: "red-transistor", title: "Red (Transistor)", emojis: "🎤⚔", level: "impossible" },
  { id: "henry-firewatch", title: "Henry (Firewatch)", emojis: "🔥🌲", level: "impossible" },
  { id: "max-caulfield", title: "Max Caulfield", emojis: "📷⏳", level: "impossible" },
  { id: "jin-sakai", title: "Jin Sakai", emojis: "🗡🍃", level: "impossible" },
  { id: "v-cyberpunk", title: "V (Cyberpunk 2077)", emojis: "🌃🔫", level: "impossible" },
  { id: "sam-porter", title: "Sam Porter Bridges", emojis: "📦👶", level: "impossible" },
  { id: "senua", title: "Senua", emojis: "⚔🧠", level: "impossible" },
  { id: "faith-connors", title: "Faith Connors", emojis: "🏃🏙", level: "impossible" },
  { id: "commander-shepard", title: "Commander Shepard", emojis: "🚀🌌", level: "impossible" },
  { id: "ciri", title: "Ciri", emojis: "⚔🌀", level: "impossible" },
  { id: "jak", title: "Jak", emojis: "🦦🔫", level: "impossible" },
  { id: "ratchet", title: "Ratchet & Clank", emojis: "🔧🤖", level: "impossible" },
  { id: "sly-cooper", title: "Sly Cooper", emojis: "🦝🎩", level: "impossible" },
  { id: "ecco", title: "Ecco the Dolphin", emojis: "🐬🌊", level: "impossible" },
  { id: "parappa", title: "PaRappa the Rapper", emojis: "🐶🎤", level: "impossible" },
];
