// E153 emoji video-game-character facts — one verified <=70-char fact per character, shown on reveal.
export const GAMECHAR_EMOJI_FACTS = {
  // EASY
  "mario": "Nintendo's plumber mascot; debuted in Donkey Kong (1981).",
  "luigi": "Mario's taller green brother; first appeared in 1983.",
  "pikachu": "Electric mouse; Pokemon mascot since 1996.",
  "sonic": "Sega's blue hedgehog; debuted in 1991.",
  "kirby": "Pink puffball who inhales foes; debuted 1992.",
  "pac-man": "Yellow maze-muncher; arcade hit from 1980.",
  "yoshi": "Mario's dinosaur; debuted in Super Mario World (1990).",
  "bowser": "Spiky Koopa king who kidnaps Peach; debuted 1985.",
  "donkey-kong": "Tie-wearing gorilla; star of the 1981 arcade classic.",
  "link": "Hero of Zelda with sword and shield; debuted 1986.",
  "zelda": "Hyrule's princess; series namesake since 1986.",
  "steve": "Minecraft's default miner; game launched 2011.",
  "creeper": "Green Minecraft mob that explodes near players.",
  "master-chief": "Halo's armored Spartan super-soldier; debuted 2001.",
  "samus": "Bounty hunter in power armor; Metroid star since 1986.",
  "mega-man": "Blue robot with an arm cannon; Capcom hero since 1987.",
  "crash-bandicoot": "Spinning marsupial; PlayStation mascot since 1996.",
  "spyro": "Purple dragon who breathes fire; debuted 1998.",
  "lara-croft": "Tomb Raider archaeologist; debuted 1996.",
  "kratos": "Spartan warrior of God of War; debuted 2005.",
  "ryu": "Wandering karateka; Street Fighter icon since 1987.",
  "sub-zero": "Ice ninja of Mortal Kombat; debuted 1992.",
  "scorpion": "Fiery 'Get over here!' ninja; Mortal Kombat, 1992.",
  "red-angry-birds": "Leader of the flock; Angry Birds launched 2009.",
  "princess-peach": "Ruler of the Mushroom Kingdom; debuted 1985.",

  // MEDIUM
  "tails": "Two-tailed fox who flies; Sonic's sidekick since 1992.",
  "knuckles": "Red echidna who glides and punches; debuted 1994.",
  "cloud-strife": "Buster Sword hero of Final Fantasy VII (1997).",
  "geralt": "Monster-hunting Witcher; game series began 2007.",
  "ezio": "Assassin's Creed hero; debuted in AC II (2009).",
  "nathan-drake": "Treasure hunter of Uncharted; debuted 2007.",
  "gordon-freeman": "Crowbar-wielding scientist; Half-Life, 1998.",
  "solid-snake": "Stealth soldier of Metal Gear; debuted 1987.",
  "chun-li": "Lightning-kick fighter; Street Fighter II, 1991.",
  "ken-masters": "Ryu's blond rival in a red gi; debuted 1987.",
  "dragonborn": "Dragon-souled hero of Skyrim (2011).",
  "ellie": "The Last of Us survivor; debuted 2013.",
  "aloy": "Bow-hunter of robot beasts; Horizon Zero Dawn, 2017.",
  "doomguy": "Demon-slaying marine; Doom debuted 1993.",
  "leon-kennedy": "Rookie cop battling zombies; Resident Evil 2, 1998.",
  "dante": "Demon hunter of Devil May Cry; debuted 2001.",
  "bayonetta": "Gun-heeled Umbra Witch; debuted 2009.",
  "sephiroth": "One-winged villain of Final Fantasy VII (1997).",
  "pyramid-head": "Silent Hill 2's knife-dragging monster; 2001.",
  "bomberman": "Bomb-planting hero; series began 1983.",
  "simon-belmont": "Whip-wielding vampire hunter; Castlevania, 1986.",
  "sackboy": "Knitted hero of LittleBigPlanet; debuted 2008.",
  "rayman": "Limbless hero with floating fists; debuted 1995.",
  "earthworm-jim": "Worm in a robotic suit; debuted 1994.",
  "olimar": "Spaceman who commands Pikmin; debuted 2001.",

  // HARD
  "ganondorf": "Boar-like Gerudo king; Zelda's villain since 1998.",
  "vault-boy": "Fallout's grinning mascot; series began 1997.",
  "big-daddy": "Diving-suited protector in BioShock (2007).",
  "claptrap": "One-wheeled robot of Borderlands; debuted 2009.",
  "kazuya": "Devil-powered Tekken fighter; debuted 1994.",
  "shovel-knight": "Shovel-wielding knight; debuted 2014.",
  "hollow-knight": "Nail-fighting bug in Hallownest; game out 2017.",
  "ori": "Glowing forest spirit; Ori and the Blind Forest, 2015.",
  "madeline": "Climber of Celeste Mountain; game out 2018.",
  "shadow-hedgehog": "Black-red hedgehog; debuted in Sonic Adventure 2 (2001).",
  "amaterasu": "Sun-goddess wolf who paints; Okami, 2006.",
  "alucard": "Dhampir son of Dracula; Symphony of the Night, 1997.",
  "2b": "Blindfolded combat android; NieR: Automata, 2017.",
  "joel": "Smuggler protecting Ellie; The Last of Us, 2013.",
  "arthur-morgan": "Outlaw of Red Dead Redemption 2 (2018).",
  "kk-slider": "Guitar-playing dog musician in Animal Crossing.",
  "sans": "Bone-throwing skeleton of Undertale (2015).",
  "isabelle": "Cheerful dog secretary in Animal Crossing.",
  "cuphead": "Cup-headed run-and-gunner; game out 2017.",
  "shantae": "Hair-whipping half-genie; debuted 2002.",
  "bub-bubble-bobble": "Bubble-blowing dragon; Bubble Bobble, 1986.",
  "qbert": "Orange creature hopping pyramids; arcade, 1982.",
  "frogger": "Frog dodging traffic; arcade classic from 1981.",
  "banjo-kazooie": "Bear and bird duo; debuted 1998.",
  "conker": "Foul-mouthed squirrel; Bad Fur Day, 2001.",

  // IMPOSSIBLE
  "guybrush": "Wannabe pirate of Monkey Island; debuted 1990.",
  "katamari-prince": "Tiny prince rolling a katamari ball; debuted 2004.",
  "chell": "Silent portal-gun tester; Portal, 2007.",
  "glados": "Rogue AI who promises cake; Portal, 2007.",
  "wander": "Colossi-slayer on horse Agro; SotC, 2005.",
  "chosen-undead": "Bonfire-lighting hero of Dark Souls (2011).",
  "solaire": "Sun-praising knight of Dark Souls (2011).",
  "binding-isaac": "Crying child in a cursed basement; game out 2011.",
  "cadence": "Beat-matching dungeon hero; NecroDancer, 2015.",
  "the-kid-bastion": "Hammer-swinging hero of Bastion (2011).",
  "red-transistor": "Mute singer wielding the Transistor; 2014.",
  "henry-firewatch": "Fire lookout in the woods; Firewatch, 2016.",
  "max-caulfield": "Time-rewinding photographer; Life is Strange, 2015.",
  "jin-sakai": "Samurai turned Ghost; Ghost of Tsushima, 2020.",
  "v-cyberpunk": "Merc in Night City; Cyberpunk 2077, 2020.",
  "sam-porter": "Courier carrying a BB; Death Stranding, 2019.",
  "senua": "Warrior facing psychosis; Hellblade, 2017.",
  "faith-connors": "Rooftop free-runner; Mirror's Edge, 2008.",
  "commander-shepard": "Galaxy-saving hero of Mass Effect (2007).",
  "ciri": "Sword-wielding, teleporting Witcher heir; 2015.",
  "jak": "Otsel-paired hero of Jak and Daxter; 2001.",
  "ratchet": "Lombax mechanic with robot Clank; debuted 2002.",
  "sly-cooper": "Raccoon master thief; debuted 2002.",
  "ecco": "Time-traveling dolphin; debuted 1992.",
  "parappa": "Rapping dog who believes; debuted 1996.",
};
