// E29 gaming-logo facts — one verified ≤70-char fact per logo, shown on reveal.
export const GAMINGLOGO_FACTS = {
  // ===== EASY =====
  "atari": "Video game pioneer; released Pong in 1972.",
  "oculus": "VR headset maker Meta bought in 2014.",
  "steamdeck": "Valve's handheld gaming PC, launched in 2022.",
  "squareenix": "Japanese studio behind Final Fantasy.",
  "2k": "Publisher of NBA 2K and BioShock.",
  "gameloft": "French mobile game maker founded in 1999.",
  "counterstrike": "Valve's team shooter, born as a 1999 mod.",
  "dota2": "Valve's free-to-play MOBA, released in 2013.",
  "osu": "Free rhythm game first released in 2007.",
  "vrchat": "Social VR platform launched in 2017.",
  "obsstudio": "Free open-source live-streaming software.",
  "streamlabs": "Live-streaming toolkit popular with gamers.",
  "kick": "Live-streaming platform launched in 2022.",
  "ign": "Video game news site founded in 1996.",
  "metacritic": "Aggregator scoring games out of 100.",
  "chessdotcom": "World's largest online chess platform.",
  "lichess": "Free open-source online chess server.",
  "dungeonsanddragons": "Tabletop role-playing game first sold in 1974.",
  "curseforge": "Popular hub for game and Minecraft mods.",
  "retroarch": "Front-end that runs many game emulators.",
  "corsair": "Maker of gaming PCs, keyboards and RAM.",
  "steelseries": "Danish gaming peripherals brand.",
  "hyperx": "Gaming headset and keyboard brand.",
  "alienware": "Dell's high-end gaming PC brand.",
  "battledotnet": "Blizzard's online gaming platform.",
  // ===== MEDIUM =====
  "htcvive": "VR headset made with Valve, launched 2016.",
  "gogdotcom": "DRM-free PC game store run by CD Projekt.",
  "itchdotio": "Marketplace for indie games and assets.",
  "humblebundle": "Pay-what-you-want game bundles for charity.",
  "steamdb": "Tracks prices and data for Steam games.",
  "steamworks": "Valve's toolkit for Steam developers.",
  "playstationvita": "Sony's handheld console, launched in 2011.",
  "playstationportable": "Sony's PSP handheld, released in 2004.",
  "robloxstudio": "Tool for building games on Roblox.",
  "nzxt": "Maker of PC cases and gaming rigs.",
  "coolermaster": "PC cooling and case brand since 1992.",
  "elgato": "Capture cards and gear for streamers.",
  "redragon": "Budget gaming keyboards and mice brand.",
  "republicofgamers": "Asus's gaming hardware brand, aka ROG.",
  "nexon": "Korean studio behind MapleStory.",
  "paradoxinteractive": "Swedish maker of grand strategy games.",
  "treyarch": "Studio behind many Call of Duty games.",
  "bungie": "Studio that created Halo and Destiny.",
  "gamemaker": "2D game engine by YoYo Games.",
  "cryengine": "Crytek's engine used in Crysis.",
  "playcanvas": "Web-based 3D game engine.",
  "opengl": "Cross-platform graphics API for games.",
  "vulkan": "Low-overhead graphics API for games.",
  "undertale": "Indie RPG released by Toby Fox in 2015.",
  "faceit": "Competitive matchmaking platform for esports.",
  // ===== HARD =====
  "shadow": "Cloud gaming PC you stream from anywhere.",
  "g2a": "Marketplace for cheap game keys.",
  "stadia": "Google's cloud gaming service, 2019-2023.",
  "analogue": "Maker of premium retro game consoles.",
  "commodore": "Made the best-selling Commodore 64.",
  "deepcool": "PC cooling and case brand from China.",
  "privatedivision": "Take-Two's indie publishing label.",
  "construct3": "Browser-based 2D game maker.",
  "renpy": "Free engine for visual novel games.",
  "monogame": "Open-source C# framework for games.",
  "cocos": "Engine popular for mobile games.",
  "coronaengine": "Lua game engine, now called Solar2D.",
  "aseprite": "Tool for making pixel art and sprites.",
  "spine": "2D skeletal animation tool for games.",
  "fmod": "Audio engine used in many games.",
  "wwise": "Interactive audio middleware for games.",
  "blockbench": "Free 3D model editor for Minecraft.",
  "sourceengine": "Valve engine behind Half-Life 2.",
  "decentraland": "Blockchain-based virtual world game.",
  "ingress": "Niantic's AR game that led to Pokemon Go.",
  "xsplit": "Live streaming and recording software.",
  "guilded": "Chat app for gaming communities.",
  "eslgaming": "One of the oldest esports companies.",
  "opencritic": "Game review aggregator launched in 2015.",
  "igdb": "Internet Game Database owned by Twitch.",
  // ===== IMPOSSIBLE =====
  "gamejolt": "Community and store for indie games.",
  "newgrounds": "Site famous for Flash games and animation.",
  "gamebanana": "Hub for game mods and skins.",
  "kongregate": "Portal for free browser games.",
  "bevy": "Open-source game engine built in Rust.",
  "raylib": "Simple C library for making games.",
  "sfml": "C++ multimedia library for games.",
  "luanti": "Open-source voxel engine, formerly Minetest.",
  "mumble": "Low-latency voice chat for gamers.",
  "teamspeak": "Voice chat long used by gaming clans.",
  "roll20": "Virtual tabletop for role-playing games.",
  "boardgamegeek": "Huge online database of board games.",
  "modrinth": "Open-source host for Minecraft mods.",
  "spigotmc": "Popular Minecraft server software.",
  "namemc": "Search site for Minecraft names and skins.",
  "thunderstore": "Mod database for games like Risk of Rain 2.",
  "retropie": "Turns a Raspberry Pi into a retro console.",
  "lutris": "Open-source game manager for Linux.",
  "protondb": "Reports how well games run on Linux.",
  "heroicgameslauncher": "Open-source launcher for Epic and GOG games.",
  "wine": "Runs Windows games and apps on Linux.",
  "retroachievements": "Adds achievements to retro games.",
  "dolphin": "Emulator for GameCube and Wii games.",
  "bisecthosting": "Minecraft and game server hosting.",
  "pterodactyl": "Open-source game server control panel.",
};
