// E29 «Guess the Gaming Logo» — ≤70-char TRUE "did-you-know" facts, keyed by slug.
export const GAMINGLOGO_FACTS = {
  // easy
  minecraft: "2011 sandbox by Mojang; best-selling video game ever.",
  fortnite: "2017 Epic battle royale; free-to-play global hit.",
  xbox: "Microsoft's game console brand, launched in 2001.",
  playstation: "Sony console brand; debuted in Japan in 1994.",
  nintendo: "Japanese game giant founded in 1889 as a card maker.",
  pokemon: "1996 Nintendo franchise; top-grossing media brand.",
  supermario: "Nintendo's mascot platformer; debuted in 1985.",
  roblox: "2006 platform where users build and play games.",
  amongus: "2018 social deduction game; went viral in 2020.",
  callofduty: "Activision's blockbuster military shooter series.",
  gta: "Open-world crime series that debuted in 1997; now Rockstar's.",
  fifa: "EA's football sim; long best-selling sports series.",
  tetris: "1984 Soviet puzzle game by Alexey Pajitnov.",
  pacman: "1980 Namco maze arcade classic.",
  sonic: "Sega's speedy blue hedgehog mascot since 1991.",
  angrybirds: "2009 Rovio mobile hit; slingshot birds at pigs.",
  candycrush: "2012 King match-three mobile mega-hit.",
  thesims: "EA's life-simulation series; launched in 2000.",
  steam: "Valve's PC game store and platform, since 2003.",
  zelda: "Nintendo's fantasy adventure series since 1986.",
  mariokart: "Nintendo's kart-racing series; started in 1992.",
  gameboy: "Nintendo's 1989 handheld; the Game Boy family sold 118M.",
  wii: "Nintendo's 2006 motion-control console.",
  subwaysurfers: "2012 endless runner; billions of downloads.",
  templerun: "2011 endless-runner mobile hit by Imangi.",
  // medium
  halo: "Xbox's sci-fi shooter; launched with the console.",
  assassinscreed: "Ubisoft's historical stealth-action series.",
  overwatch: "2016 Blizzard team hero shooter.",
  fallguys: "2020 battle-royale party game of jellybeans.",
  clashofclans: "2012 Supercell mobile strategy hit.",
  doom: "1993 id Software shooter; defined the FPS genre.",
  streetfighter: "Capcom's fighting series since 1987.",
  mortalkombat: "1992 fighting game known for brutal fatalities.",
  counterstrike: "Valve shooter; born as a Half-Life mod in 1999.",
  leagueoflegends: "2009 Riot MOBA; a top esport worldwide.",
  valorant: "2020 Riot tactical hero shooter.",
  apexlegends: "2019 EA battle royale in the Titanfall world.",
  pubg: "2017 battle royale that popularized the genre.",
  cyberpunk2077: "2020 CD Projekt open-world RPG in Night City.",
  eldenring: "2022 FromSoftware hit; world by G.R.R. Martin.",
  nintendoswitch: "2017 hybrid handheld-and-home console.",
  ea: "Electronic Arts; major US game publisher since 1982.",
  ubisoft: "French publisher of Assassin's Creed, founded 1986.",
  rockstargames: "Studio behind GTA and Red Dead Redemption.",
  crashbandicoot: "1996 mascot platformer; early PlayStation star.",
  needforspeed: "EA's racing series since 1994.",
  battlefield: "EA/DICE large-scale military shooter series.",
  gearsofwar: "Xbox cover-shooter series; debuted in 2006.",
  worldofwarcraft: "2004 Blizzard MMORPG; genre-defining hit.",
  rocketleague: "2015 game of soccer played with rocket cars.",
  // hard
  halflife: "Valve's 1998 shooter; revolutionized storytelling.",
  portal: "2007 Valve puzzle game with a portal gun.",
  darksouls: "FromSoftware's brutally hard 2011 action-RPG.",
  metroid: "Nintendo sci-fi series; hero is Samus Aran.",
  residentevil: "Capcom's survival-horror series since 1996.",
  metalgear: "Kojima's stealth-action series; began in 1987.",
  godofwar: "Sony series following Spartan warrior Kratos.",
  thewitcher: "CD Projekt RPGs based on Polish fantasy novels.",
  hollowknight: "2017 Team Cherry indie Metroidvania hit.",
  cuphead: "2017 run-and-gun with 1930s cartoon art.",
  deadcells: "2018 roguelike Metroidvania by Motion Twin.",
  bioshock: "2007 shooter set in undersea city Rapture.",
  farcry: "Ubisoft's open-world FPS series since 2004.",
  borderlands: "Gearbox looter-shooter with cel-shaded art.",
  bloodborne: "2015 FromSoftware gothic action-RPG for PS4.",
  deadbydaylight: "2016 asymmetric horror: survivors vs killer.",
  rainbowsix: "Tom Clancy tactical shooter series by Ubisoft.",
  fallout: "Post-apocalyptic RPG series since 1997.",
  elderscrolls: "Bethesda's fantasy RPGs, including Skyrim.",
  warframe: "2013 free-to-play co-op shooter, Digital Extremes.",
  genshinimpact: "2020 open-world action RPG by miHoYo.",
  epicgames: "Maker of Unreal Engine and Fortnite.",
  activision: "US publisher founded 1979; oldest third-party.",
  blizzard: "Studio behind Warcraft, Diablo and Overwatch.",
  sega: "Japanese firm; made the Genesis and Dreamcast.",
  // impossible
  myst: "1993 puzzle adventure; best-seller of the 1990s.",
  katamaridamacy: "2004 quirky game of rolling stuff into a ball.",
  shadowofthecolossus: "2005 PS2 game of felling 16 giant colossi.",
  journey: "2012 wordless adventure through desert ruins.",
  limbo: "2010 eerie black-and-white puzzle-platformer.",
  okami: "2006 game inspired by Japanese ink painting.",
  earthbound: "1994 quirky RPG set in a parody of America.",
  chronotrigger: "1995 time-travel RPG hailed as an all-time great.",
  deusex: "2000 cyberpunk RPG-shooter praised for choice.",
  discoelysium: "2019 detective RPG with no combat, only talk.",
  fez: "2012 indie puzzle-platformer that shifts 2D and 3D.",
  hades: "2020 roguelike by Supergiant based on Greek myth.",
  obradinn: "2018 ghost-ship mystery drawn in 1-bit art.",
  papersplease: "2013 game as a dystopian border checkpoint guard.",
  babaisyou: "2019 puzzle game where you rewrite the rules.",
  kingdomhearts: "Square-Disney crossover action-RPG since 2002.",
  persona: "Atlus RPGs blending school life and demon battles.",
  ori: "Moon Studios' lush platformers since 2015.",
  bastion: "2011 action-RPG with a reactive live narrator.",
  braid: "2008 time-bending puzzle-platformer by Jon Blow.",
  celeste: "2018 platformer about climbing a mountain.",
  undertale: "2015 RPG where you can spare every foe.",
  spelunky: "2008 roguelike platformer set in caves.",
  hearthstone: "2014 Blizzard digital collectible card game.",
  bethesda: "Studio behind Fallout and The Elder Scrolls.",
};
