// «Guess the Gemstone» — GuessSync · E44 · did-you-know facts, ≤70 chars, verified true.
export const GEM_FACTS = {
  // EASY
  "diamond": "Hardest natural material, a perfect 10 on the Mohs scale",
  "ruby": "The red variety of corundum; colored by chromium",
  "emerald": "Green variety of beryl; prized despite frequent inclusions",
  "sapphire": "Any non-red corundum; the classic color is deep blue",
  "amethyst": "The purple variety of quartz, colored by iron and radiation",
  "quartz": "One of Earth's most common minerals; hardness 7",
  "topaz": "Aluminum silicate mineral with a hardness of 8",
  "opal": "Hydrated silica famous for its flashing play-of-color",
  "turquoise": "Blue-green copper mineral, one of the oldest known gems",
  "jade": "Name covers two tough stones: jadeite and nephrite",
  "garnet": "A group of silicate minerals, most often deep red",
  "pearl": "Organic gem grown inside oysters and other mollusks",
  "amber": "Fossilized tree resin, sometimes trapping ancient insects",
  "aquamarine": "The blue-to-cyan variety of beryl, colored by iron",
  "onyx": "A banded chalcedony, most valued in solid black",
  "citrine": "The yellow-to-orange variety of quartz",
  "peridot": "Olive-green gem, the gem variety of the mineral olivine",
  "rosequartz": "The soft pink variety of quartz, often cloudy",
  "lapislazuli": "Deep blue rock prized since antiquity, often flecked gold",
  "malachite": "Green copper carbonate known for banded patterns",
  "obsidian": "Natural volcanic glass, usually jet black",
  "tigerseye": "Golden-brown quartz with a silky chatoyant sheen",
  "agate": "A banded form of chalcedony quartz",
  "jasper": "An opaque, often multicolored variety of chalcedony",
  "moonstone": "Feldspar gem with a floating blue-white glow (adularescence)",
  // MEDIUM
  "tourmaline": "Boron silicate that occurs in nearly every color",
  "zircon": "Ancient mineral; some crystals are billions of years old",
  "spinel": "Long mistaken for ruby; forms brilliant red octahedra",
  "tanzanite": "Blue-violet zoisite found only near Mount Kilimanjaro",
  "morganite": "The soft pink-to-peach variety of beryl",
  "kunzite": "Pink-to-lilac spodumene, colored by manganese",
  "carnelian": "Reddish-orange chalcedony used since ancient times",
  "bloodstone": "Dark green chalcedony spotted with red jasper",
  "rhodonite": "Pink manganese silicate, often veined with black",
  "sodalite": "Rich blue mineral, often mistaken for lapis lazuli",
  "fluorite": "Calcium fluoride prized for its many glowing colors",
  "pyrite": "Brassy iron sulfide nicknamed fool's gold",
  "hematite": "Iron oxide with a metallic gray-black luster",
  "labradorite": "Feldspar that flashes blue-green (labradorescence)",
  "sunstone": "Feldspar with a glittery metallic shimmer (aventurescence)",
  "aventurine": "Green quartz sparkling from tiny mica inclusions",
  "chrysoprase": "Apple-green chalcedony colored by nickel",
  "smokyquartz": "Brown-to-gray quartz colored by natural radiation",
  "amazonite": "Blue-green variety of the feldspar microcline",
  "iolite": "Violet-blue cordierite that shifts color when turned",
  "apatite": "Phosphate mineral; hardness 5 defines that Mohs step",
  "azurite": "Deep blue copper mineral, often found with malachite",
  "chrysocolla": "Blue-green copper silicate with a hardness around 3",
  "prehnite": "Pale green-yellow mineral with a botryoidal form",
  "chalcedony": "Microcrystalline quartz with a waxy luster",
  // HARD
  "alexandrite": "Chrysoberyl that shifts green in day, red in lamplight",
  "rhodochrosite": "Rose-pink manganese carbonate, soft at hardness 4",
  "tsavorite": "Bright green grossular garnet from East Africa",
  "demantoid": "Rare green andradite garnet with fiery brilliance",
  "sphalerite": "Zinc sulfide with dispersion greater than diamond",
  "vanadinite": "Bright red-orange lead mineral forming hexagonal crystals",
  "wulfenite": "Orange-yellow lead molybdate in thin tabular crystals",
  "dioptase": "Intense emerald-green copper silicate, quite fragile",
  "vesuvianite": "Silicate first found on Mount Vesuvius, Italy",
  "epidote": "Pistachio-green silicate common in metamorphic rocks",
  "kyanite": "Blue silicate with hardness that varies by direction",
  "andalusite": "Silicate that shows different colors from each angle",
  "danburite": "Usually colorless silicate, often mistaken for topaz",
  "scapolite": "Silicate gem ranging from yellow to violet",
  "sphene": "Titanite gem with rainbow fire rivaling diamond",
  "zoisite": "Silicate whose blue variety is known as tanzanite",
  "hackmanite": "Sodalite that changes color in sunlight (tenebrescence)",
  "ametrine": "Natural quartz blending amethyst purple and citrine gold",
  "variscite": "Green phosphate mineral resembling turquoise",
  "charoite": "Swirling violet silicate found only in Siberia, Russia",
  "larimar": "Sky-blue pectolite found only in the Dominican Republic",
  "cerussite": "Lead carbonate that is heavy with high luster",
  "crocoite": "Bright orange lead chromate in slender crystals",
  "seraphinite": "Dark green clinochlore with silvery feather patterns",
  "sugilite": "Rare purple manganese silicate popular in jewelry",
  // IMPOSSIBLE
  "painite": "Once the rarest gem mineral; brownish-red borate",
  "benitoite": "Blue barium titanium silicate; state gem of California",
  "grandidierite": "Bluish-green silicate, first found in Madagascar",
  "musgravite": "Extremely rare relative of taaffeite; grayish-green",
  "jeremejevite": "Rare borate gem, usually colorless to pale blue",
  "taaffeite": "First gem identified only after being cut, not in rock",
  "poudretteite": "Very rare pink borosilicate from Mont Saint-Hilaire",
  "serendibite": "Extremely rare dark blue-green silicate from Sri Lanka",
  "moldavite": "Green glass formed by an ancient meteorite impact",
  "sinhalite": "Brown-yellow borate gem first identified in Sri Lanka",
  "ekanite": "Rare green gem that is weakly radioactive",
  "phenakite": "Colorless beryllium silicate, harder than quartz",
  "euclase": "Fragile beryllium silicate, often pale blue-green",
  "hambergite": "Rare colorless beryllium borate with low density",
  "brazilianite": "Yellow-green phosphate first found in Brazil",
  "clinohumite": "Rare orange silicate, sometimes called the fire gem",
  "pezzottaite": "Raspberry-pink beryl relative from Madagascar",
  "redberyl": "Rare red beryl found mainly in Utah, USA",
  "axinite": "Brown-violet silicate forming sharp axe-like crystals",
  "kornerupine": "Green-to-brown silicate that can shift color when turned",
  "cavansite": "Bright blue calcium vanadium silicate on white matrix",
  "proustite": "Ruby-red silver mineral that darkens in light",
  "vivianite": "Iron phosphate that turns deep blue-green on exposure",
  "legrandite": "Rare golden-yellow zinc arsenate from Mexico",
  "cuprite": "Deep red copper oxide with a brilliant luster",
};
