// «Guess the Hat» — GuessSync · E67 · did-you-know facts, ≤70 chars, verified true (origin / use).
export const HAT_FACTS = {
  // EASY
  "baseballcap": "Curved-brim cap born on the American baseball field",
  "tophat": "Tall cylinder hat, a 19th-century formal menswear icon",
  "cowboyhat": "Wide-brim hat of American ranchers and cowboys",
  "beret": "Soft round flat cap linked to France and the Basques",
  "sombrero": "Wide-brim Mexican hat shading against the strong sun",
  "fedora": "Soft felt hat with a creased crown and pinched front",
  "beanie": "Snug knitted cap worn for warmth in cold weather",
  "bowlerhat": "Hard round-crowned felt hat, invented in 1849 London",
  "panamahat": "Woven straw hat actually made in Ecuador, not Panama",
  "turban": "Long cloth wound around the head across many cultures",
  "fez": "Red truncated-cone felt hat tied to Ottoman lands",
  "chefhat": "Tall white pleated 'toque' worn in pro kitchens",
  "graduationcap": "Flat square 'mortarboard' worn at graduations",
  "partyhat": "Cone-shaped festive hat worn at birthday parties",
  "strawhat": "Woven straw hat for shade in sun and summer",
  "sunhat": "Wide-brim hat made to shade the face from sun",
  "buckethat": "Soft downward-sloping brim hat of 1900s Irish origin",
  "flatcap": "Rounded low-profile cap with a small stiff brim",
  "hardhat": "Rigid helmet protecting workers on building sites",
  "santahat": "Red-and-white cap worn at Christmas as Santa Claus",
  "witchhat": "Tall pointed black hat linked to storybook witches",
  "crown": "Jewelled headpiece symbolizing a monarch's power",
  "truckerhat": "Foam-front mesh-back cap once given away by firms",
  "visor": "Brimmed band shading the eyes, open at the top",
  "sailorhat": "Round white cotton 'Dixie cup' cap of navy sailors",
  // MEDIUM
  "trilby": "Short-brim felt hat, a narrower cousin of the fedora",
  "boater": "Stiff flat-top straw hat for summer and rowing",
  "porkpiehat": "Flat-topped hat with a short upturned brim",
  "newsboycap": "Full rounded flat cap with a button on top",
  "cloche": "Bell-shaped women's hat popular in the 1920s",
  "snapback": "Flat-brim cap with an adjustable snap strap",
  "coonskincap": "Fur cap with a hanging tail, worn by frontiersmen",
  "pithhelmet": "Lightweight sun helmet of colonial-era explorers",
  "nursecap": "White cap once worn to hold a nurse's hair back",
  "peakedcap": "Stiff-brim cap of military and police uniforms",
  "aviatorhat": "Leather flying cap with ear flaps for open cockpits",
  "bandana": "Square cloth folded and tied around the head",
  "bonnet": "Brimmed hat tied under the chin with ribbons",
  "balaclava": "Knitted hood covering the head and most of the face",
  "nightcap": "Soft cloth cap once worn in bed for warmth",
  "jesterhat": "Floppy multi-point cap with bells worn by jesters",
  "souwester": "Waterproof hat with a long back brim for sailors",
  "headscarf": "Cloth tied over the hair and around the head",
  "tiara": "Small jewelled crown worn by women at formal events",
  "booniehat": "Wide soft-brim bush hat used by armed forces",
  "ascotcap": "Hard rounded flat cap of one-piece stiff design",
  "slouchhat": "Soft wide-brim hat with one side pinned up",
  "kufi": "Short rounded cap worn across Africa and by Muslims",
  "kippah": "Small skullcap worn by Jewish men and boys",
  "durag": "Cloth tied over the head to hold hairstyles in place",
  // HARD
  "bicorne": "Two-cornered hat famously worn by Napoleon",
  "capotain": "Tall conical hat linked to Puritans and Pilgrims",
  "homburg": "Stiff felt hat with a curled brim and centre dent",
  "cordobeshat": "Flat-brimmed round-crown black hat of Córdoba, Spain",
  "tyroleanhat": "Alpine felt hat with a feather, from the Tyrol",
  "akubra": "Wide-brim Australian bush hat of rabbit-fur felt",
  "chullo": "Andean knitted cap with ear flaps, from Peru",
  "songkok": "Flat-topped cap worn by Muslim men in SE Asia",
  "keffiyeh": "Checkered Arab headscarf held by a corded ring",
  "doppa": "Square embroidered skullcap of Central Asia",
  "bearskin": "Tall black fur cap of British royal guards",
  "warbonnet": "Feathered ceremonial headdress of Plains tribes",
  "coif": "Close-fitting medieval cloth cap tied under the chin",
  "wimple": "Cloth covering the head and neck, worn by nuns",
  "hennin": "Tall cone hat of medieval European noblewomen",
  "phrygiancap": "Soft peaked cap, an ancient symbol of liberty",
  "mitre": "Tall pointed hat worn by bishops in the church",
  "zucchetto": "Small round skullcap worn by Catholic clergy",
  "biretta": "Square ridged cap with tufts worn by clergy",
  "kalpak": "Tall felt hat of Central Asian herders",
  "karakul": "Curly lambskin cap of Central and South Asia",
  "taqiyah": "Short rounded cap worn by Muslim men in prayer",
  "rastacap": "Tall knitted cap holding the dreadlocks of Rastafari",
  "montera": "Black ornate hat worn by Spanish bullfighters",
  "gat": "Cylindrical horsehair hat of old Korean scholars",
  // IMPOSSIBLE
  "ushanka": "Russian fur cap with fold-down ear flaps",
  "tricorne": "Three-cornered hat of the 18th-century West",
  "deerstalker": "Twin-brim cap forever tied to Sherlock Holmes",
  "pillboxhat": "Small flat-topped hat with straight sides, no brim",
  "fascinator": "Ornate headpiece on a band, worn at formal events",
  "balmoral": "Flat Scottish bonnet with a centre dimple",
  "nonla": "Conical leaf hat of Vietnam, shade from sun and rain",
  "tamoshanter": "Floppy woolen Scottish bonnet with a pom-pom",
  "kepi": "Flat-top cap with a straight peak, French military",
  "shako": "Tall cylindrical military hat topped with a plume",
  "gele": "Elaborately tied cloth head wrap of Nigerian women",
  "glengarry": "Boat-shaped Scottish cap with ribbons at the back",
  "papakha": "Tall wool fleece hat of the Caucasus mountains",
  "kokoshnik": "Ornate traditional Russian women's headdress",
  "capirote": "Tall pointed hood worn in Spanish Easter marches",
  "bycocket": "Peaked medieval hat linked to Robin Hood",
  "chaperon": "Draped medieval European hood-turban hat",
  "eboshi": "Tall black lacquered cap of old Japanese nobles",
  "tubeteika": "Embroidered skullcap of Central Asian peoples",
  "fila": "Soft folded cap worn by Yoruba men in Nigeria",
  "chupalla": "Straw hat of the Chilean huaso horseman",
  "barretina": "Soft red floppy cap of traditional Catalonia",
  "kabuto": "Ornate helmet worn by Japanese samurai warriors",
  "mobcap": "Round gathered cloth cap of 18th-century women",
  "salakot": "Wide dome-shaped sun hat of the Philippines",
};
