// «Guess the Hat» — GuessSync · E67 · 100 hats & headwear (25/tier) · صور حقيقية من Wikimedia Commons
// Classified by real-world global recognizability: easy (Baseball Cap/Top Hat) ← impossible (Gele/Bycocket/Chaperon).
// Global mix of cultural + fashion + functional headwear.
export const HATS = [
  // EASY (25) — household-name hats everyone knows
  { slug: "baseballcap", name: "Baseball Cap", level: "easy" },
  { slug: "tophat", name: "Top Hat", level: "easy" },
  { slug: "cowboyhat", name: "Cowboy Hat", level: "easy" },
  { slug: "beret", name: "Beret", level: "easy" },
  { slug: "sombrero", name: "Sombrero", level: "easy" },
  { slug: "fedora", name: "Fedora", level: "easy" },
  { slug: "beanie", name: "Beanie", level: "easy" },
  { slug: "bowlerhat", name: "Bowler Hat", level: "easy" },
  { slug: "panamahat", name: "Panama Hat", level: "easy" },
  { slug: "turban", name: "Turban", level: "easy" },
  { slug: "fez", name: "Fez", level: "easy" },
  { slug: "chefhat", name: "Chef's Hat", level: "easy" },
  { slug: "graduationcap", name: "Graduation Cap", level: "easy" },
  { slug: "partyhat", name: "Party Hat", level: "easy" },
  { slug: "strawhat", name: "Straw Hat", level: "easy" },
  { slug: "sunhat", name: "Sun Hat", level: "easy" },
  { slug: "buckethat", name: "Bucket Hat", level: "easy" },
  { slug: "flatcap", name: "Flat Cap", level: "easy" },
  { slug: "hardhat", name: "Hard Hat", level: "easy" },
  { slug: "santahat", name: "Santa Hat", level: "easy" },
  { slug: "witchhat", name: "Witch Hat", level: "easy" },
  { slug: "crown", name: "Crown", level: "easy" },
  { slug: "truckerhat", name: "Trucker Hat", level: "easy" },
  { slug: "visor", name: "Visor", level: "easy" },
  { slug: "sailorhat", name: "Sailor Hat", level: "easy" },
  // MEDIUM (25) — recognizable but you have to think
  { slug: "trilby", name: "Trilby", level: "medium" },
  { slug: "boater", name: "Boater", level: "medium" },
  { slug: "porkpiehat", name: "Pork Pie Hat", level: "medium" },
  { slug: "newsboycap", name: "Newsboy Cap", level: "medium" },
  { slug: "cloche", name: "Cloche", level: "medium" },
  { slug: "snapback", name: "Snapback", level: "medium" },
  { slug: "coonskincap", name: "Coonskin Cap", level: "medium" },
  { slug: "pithhelmet", name: "Pith Helmet", level: "medium" },
  { slug: "nursecap", name: "Nurse Cap", level: "medium" },
  { slug: "peakedcap", name: "Peaked Cap", level: "medium" },
  { slug: "aviatorhat", name: "Aviator Hat", level: "medium" },
  { slug: "bandana", name: "Bandana", level: "medium" },
  { slug: "bonnet", name: "Bonnet", level: "medium" },
  { slug: "balaclava", name: "Balaclava", level: "medium" },
  { slug: "nightcap", name: "Nightcap", level: "medium" },
  { slug: "jesterhat", name: "Jester Hat", level: "medium" },
  { slug: "souwester", name: "Sou'wester", level: "medium" },
  { slug: "headscarf", name: "Headscarf", level: "medium" },
  { slug: "tiara", name: "Tiara", level: "medium" },
  { slug: "booniehat", name: "Boonie Hat", level: "medium" },
  { slug: "ascotcap", name: "Ascot Cap", level: "medium" },
  { slug: "slouchhat", name: "Slouch Hat", level: "medium" },
  { slug: "kufi", name: "Kufi", level: "medium" },
  { slug: "kippah", name: "Kippah", level: "medium" },
  { slug: "durag", name: "Durag", level: "medium" },
  // HARD (25) — cultural / traditional / specialist headwear
  { slug: "bicorne", name: "Bicorne", level: "hard" },
  { slug: "capotain", name: "Capotain", level: "hard" },
  { slug: "homburg", name: "Homburg", level: "hard" },
  { slug: "cordobeshat", name: "Cordobés Hat", level: "hard" },
  { slug: "tyroleanhat", name: "Tyrolean Hat", level: "hard" },
  { slug: "akubra", name: "Akubra", level: "hard" },
  { slug: "chullo", name: "Chullo", level: "hard" },
  { slug: "songkok", name: "Songkok", level: "hard" },
  { slug: "keffiyeh", name: "Keffiyeh", level: "hard" },
  { slug: "doppa", name: "Doppa", level: "hard" },
  { slug: "nemes", name: "Nemes", level: "hard" },
  { slug: "warbonnet", name: "War Bonnet", level: "hard" },
  { slug: "coif", name: "Coif", level: "hard" },
  { slug: "wimple", name: "Wimple", level: "hard" },
  { slug: "hennin", name: "Hennin", level: "hard" },
  { slug: "phrygiancap", name: "Phrygian Cap", level: "hard" },
  { slug: "mitre", name: "Mitre", level: "hard" },
  { slug: "zucchetto", name: "Zucchetto", level: "hard" },
  { slug: "biretta", name: "Biretta", level: "hard" },
  { slug: "kalpak", name: "Kalpak", level: "hard" },
  { slug: "karakul", name: "Karakul", level: "hard" },
  { slug: "taqiyah", name: "Taqiyah", level: "hard" },
  { slug: "rastacap", name: "Rasta Cap", level: "hard" },
  { slug: "montera", name: "Montera", level: "hard" },
  { slug: "gat", name: "Gat", level: "hard" },
  // IMPOSSIBLE (25) — obscure / ancient / deep-cultural
  { slug: "ushanka", name: "Ushanka", level: "impossible" },
  { slug: "tricorne", name: "Tricorne", level: "impossible" },
  { slug: "deerstalker", name: "Deerstalker", level: "impossible" },
  { slug: "pillboxhat", name: "Pillbox Hat", level: "impossible" },
  { slug: "fascinator", name: "Fascinator", level: "impossible" },
  { slug: "balmoral", name: "Balmoral Bonnet", level: "impossible" },
  { slug: "nonla", name: "Nón Lá", level: "impossible" },
  { slug: "tamoshanter", name: "Tam o' Shanter", level: "impossible" },
  { slug: "kepi", name: "Kepi", level: "impossible" },
  { slug: "shako", name: "Shako", level: "impossible" },
  { slug: "gele", name: "Gele", level: "impossible" },
  { slug: "glengarry", name: "Glengarry", level: "impossible" },
  { slug: "papakha", name: "Papakha", level: "impossible" },
  { slug: "kokoshnik", name: "Kokoshnik", level: "impossible" },
  { slug: "capirote", name: "Capirote", level: "impossible" },
  { slug: "bycocket", name: "Bycocket", level: "impossible" },
  { slug: "chaperon", name: "Chaperon", level: "impossible" },
  { slug: "eboshi", name: "Eboshi", level: "impossible" },
  { slug: "tubeteika", name: "Tubeteika", level: "impossible" },
  { slug: "fila", name: "Fila", level: "impossible" },
  { slug: "chupalla", name: "Chupalla", level: "impossible" },
  { slug: "barretina", name: "Barretina", level: "impossible" },
  { slug: "kabuto", name: "Kabuto", level: "impossible" },
  { slug: "mobcap", name: "Mob Cap", level: "impossible" },
  { slug: "salakot", name: "Salakot", level: "impossible" },
];
