// E176 «Guess the Superhero by Emoji 2» — 100 superheroes · 25/tier
// VO: sfx/e176-<id>.wav
export const HERO_EMOJI_2_FACTS = {
  // EASY
  "ant-man": "Marvel hero Scott Lang who shrinks with Pym Particles.",
  "wasp": "Marvel's Janet van Dyne shrinks, flies and fires stings.",
  "cyborg": "DC hero Victor Stone, half-man and half-machine.",
  "supergirl": "DC's Kara Zor-El, Superman's Kryptonian cousin.",
  "green-arrow": "DC hero Oliver Queen, a master archer.",
  "scarlet-witch": "Marvel's Wanda Maximoff wields chaos magic.",
  "winter-soldier": "Marvel's Bucky Barnes with a metal arm.",
  "silver-surfer": "Marvel's Norrin Radd surfs the cosmos on a board.",
  "the-thing": "Marvel's Ben Grimm, the rocky Fantastic Four bruiser.",
  "mister-fantastic": "Marvel's Reed Richards, a stretchable genius.",
  "invisible-woman": "Marvel's Sue Storm turns invisible with force fields.",
  "human-torch": "Marvel's Johnny Storm bursts into flame and flies.",
  "miles-morales": "Marvel's Brooklyn Spider-Man with a venom blast.",
  "spider-gwen": "Marvel's Gwen Stacy, a spider-powered drummer.",
  "iceman": "Marvel X-Man Bobby Drake controls ice.",
  "angel": "Marvel X-Man Warren Worthington with feathered wings.",
  "hercules": "Marvel's mighty demigod son of Zeus.",
  "nova": "Marvel's Richard Rider, a helmeted space cop.",
  "kid-flash": "DC's Wally West, the speedster sidekick.",
  "batwoman": "DC's Kate Kane fights crime as a bat vigilante.",
  "hawkgirl": "DC's winged warrior with an Nth-metal mace.",
  "firestorm": "DC's nuclear man merged from two hosts.",
  "nightcrawler": "Marvel X-Man Kurt Wagner teleports in smoke.",
  "starfire": "DC's Koriand'r, an alien who fires starbolts.",
  "vixen": "DC's Mari McCabe channels animal powers.",
  // MEDIUM
  "beast-boy": "DC's Garfield Logan morphs into green animals.",
  "raven": "DC's Rachel Roth wields dark empathic magic.",
  "psylocke": "Marvel's Betsy Braddock forms a psychic knife.",
  "cannonball": "Marvel's Sam Guthrie blasts along invulnerably.",
  "banshee": "Marvel's Sean Cassidy has a sonic scream.",
  "polaris": "Marvel's Lorna Dane controls magnetism.",
  "havok": "Marvel's Alex Summers fires plasma blasts.",
  "sunfire": "Marvel's Shiro Yoshida, a Japanese fire mutant.",
  "spider-woman": "Marvel's Jessica Drew fires venom blasts.",
  "mockingbird": "Marvel's Bobbi Morse, a spy with battle staves.",
  "jubilee": "Marvel X-Man who shoots fireworks bursts.",
  "forge": "Marvel mutant inventor of amazing machines.",
  "multiple-man": "Marvel's Jamie Madrox creates duplicates of himself.",
  "songbird": "Marvel's Melissa Gold builds sonic constructs.",
  "wonder-girl": "DC's Cassie Sandsmark with Amazonian strength.",
  "mera": "DC's Atlantean queen who controls water.",
  "bishop": "Marvel mutant soldier who absorbs energy.",
  "animal-man": "DC's Buddy Baker taps the animal life-web.",
  "hawkman": "DC's reincarnated warrior with Nth-metal wings.",
  "ironheart": "Marvel's Riri Williams built her own armor.",
  "ms-marvel": "Marvel's Kamala Khan, a shape-changing fangirl.",
  "shang-chi": "Marvel's master martial artist of the Ten Rings.",
  "jessica-jones": "Marvel's super-strong private investigator.",
  "white-tiger": "Marvel hero empowered by a jade amulet.",
  "valkyrie": "Marvel's Asgardian warrior on a winged steed.",
  // HARD
  "black-lightning": "DC's Jefferson Pierce generates electricity.",
  "misty-knight": "Marvel detective with a bionic arm.",
  "wiccan": "Marvel's Billy Kaplan casts reality-bending spells.",
  "speed": "Marvel's Tommy Shepherd, a super-fast twin.",
  "hellcat": "Marvel's Patsy Walker, an agile cat hero.",
  "firestar": "Marvel's Angelica Jones controls microwaves.",
  "shatterstar": "Marvel warrior from Mojoworld with twin blades.",
  "warpath": "Marvel's James Proudstar, a super-strong mutant.",
  "sersi": "Marvel Eternal who transmutes matter.",
  "ikaris": "Marvel Eternal who flies and fires eye beams.",
  "gilgamesh": "Marvel's Forgotten One, a mighty Eternal.",
  "blue-marvel": "Marvel's Adam Brashear, an antimatter scientist.",
  "sentry": "Marvel's Bob Reynolds, power of a million suns.",
  "wonder-man": "Marvel's Simon Williams, an ionic actor hero.",
  "hyperion": "Marvel's Superman-like Squadron Supreme hero.",
  "adam-warlock": "Marvel's golden cosmic being who wields the Soul Gem.",
  "quasar": "Marvel's Wendell Vaughn wields quantum bands.",
  "spectre": "DC's spirit of divine vengeance.",
  "doctor-fate": "DC sorcerer wearing the Helmet of Fate.",
  "sasquatch": "Marvel Alpha Flight's huge orange strongman.",
  "northstar": "Marvel's Jean-Paul Beaubier, a Canadian speedster.",
  "big-barda": "DC's New Gods warrior, Mister Miracle's wife.",
  "orion": "DC New God who is the son of Darkseid.",
  "bloodshot": "Valiant's nanite-powered super-soldier.",
  "savage-dragon": "Image's green-finned superhero cop.",
  // IMPOSSIBLE
  "invincible": "Image's Mark Grayson, a half-Viltrumite hero.",
  "omni-man": "Image's Nolan, a powerful Viltrumite warrior.",
  "atom-eve": "Image hero who reshapes matter at will.",
  "x-o-manowar": "Valiant hero clad in sentient alien armor.",
  "midnighter": "Wildstorm's combat-computer brawler.",
  "apollo": "Wildstorm's solar-powered Superman analog.",
  "jenny-sparks": "Wildstorm's electric spirit of the century.",
  "the-engineer": "Wildstorm hero with nanotech-laced blood.",
  "mister-terrific": "DC genius with floating T-spheres.",
  "vibe": "DC's Cisco Ramon emits vibrational blasts.",
  "bunker": "DC's Miguel Barragan builds psionic constructs.",
  "ragman": "DC hero in a suit woven of lost souls.",
  "sleepwalker": "Marvel alien guardian of the dream realm.",
  "aurora": "Marvel's Alpha Flight light-speed heroine.",
  "guardian": "Marvel's James Hudson leads Alpha Flight.",
  "puck": "Marvel's acrobatic Alpha Flight strongman.",
  "lightray": "DC New God who wields solar light.",
  "shadowman": "Valiant hero channeling loa spirit power.",
  "jack-hawksmoor": "Wildstorm hero powered by living cities.",
  "speedball": "Marvel's Robbie Baldwin bounces on kinetic energy.",
  "darkhawk": "Marvel's Chris Powell, an armored amulet hero.",
  "cloak": "Marvel hero who engulfs foes in darkforce.",
  "dagger": "Marvel heroine who throws daggers of light.",
  "blue-devil": "DC stuntman fused into a trident-wielding demon.",
  "red-tornado": "DC android hero who controls wind.",
};
