// E131 «Guess the Superhero by Emoji» — 100 characters · 25/tier · clue via OpenMoji · VO: sfx/eh2-<id>.wav
// Mix of Marvel, DC and other publishers. `title` = character name only (no actor names, no logos/art —
// emoji-only clues keep this copyright-safe). Single-codepoint emojis only, no ZWJ/FE0F/skin-tone/flags.
export const HERO_EMOJI = [
  // ===== EASY (25) =====
  { id: "batman", title: "Batman", emojis: "🦇🌙", level: "easy" },
  { id: "spider-man", title: "Spider-Man", emojis: "🕷🕸", level: "easy" },
  { id: "superman", title: "Superman", emojis: "🏙🦸", level: "easy" },
  { id: "wonder-woman", title: "Wonder Woman", emojis: "👑⛓", level: "easy" },
  { id: "hulk", title: "Hulk", emojis: "🟢👊", level: "easy" },
  { id: "thor", title: "Thor", emojis: "⚡🔨", level: "easy" },
  { id: "iron-man", title: "Iron Man", emojis: "🤖🔴", level: "easy" },
  { id: "captain-america", title: "Captain America", emojis: "⭐🔵", level: "easy" },
  { id: "joker", title: "Joker", emojis: "🤡💜", level: "easy" },
  { id: "batgirl", title: "Batgirl", emojis: "🦇👧", level: "easy" },
  { id: "wolverine", title: "Wolverine", emojis: "🐺🔪", level: "easy" },
  { id: "black-panther", title: "Black Panther", emojis: "🐆⚫", level: "easy" },
  { id: "the-flash", title: "The Flash", emojis: "⚡👟", level: "easy" },
  { id: "green-lantern", title: "Green Lantern", emojis: "💍🟢", level: "easy" },
  { id: "aquaman", title: "Aquaman", emojis: "🌊👑", level: "easy" },
  { id: "catwoman", title: "Catwoman", emojis: "🐈🖤", level: "easy" },
  { id: "venom", title: "Venom", emojis: "🕷👹", level: "easy" },
  { id: "thanos", title: "Thanos", emojis: "💜👊", level: "easy" },
  { id: "deadpool", title: "Deadpool", emojis: "🔴⚔", level: "easy" },
  { id: "captain-marvel", title: "Captain Marvel", emojis: "⭐✨", level: "easy" },
  { id: "black-widow", title: "Black Widow", emojis: "🕷🖤", level: "easy" },
  { id: "hawkeye", title: "Hawkeye", emojis: "🏹🎯", level: "easy" },
  { id: "robin", title: "Robin", emojis: "🐦🔴", level: "easy" },
  { id: "harley-quinn", title: "Harley Quinn", emojis: "🃏❤", level: "easy" },
  { id: "doctor-strange", title: "Doctor Strange", emojis: "🔮🧙", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "green-goblin", title: "Green Goblin", emojis: "🟢🎃", level: "medium" },
  { id: "two-face", title: "Two-Face", emojis: "🪙🎭", level: "medium" },
  { id: "bane", title: "Bane", emojis: "💉👊", level: "medium" },
  { id: "mystique", title: "Mystique", emojis: "🔵🎭", level: "medium" },
  { id: "magneto", title: "Magneto", emojis: "🪖⛓", level: "medium" },
  { id: "professor-x", title: "Professor X", emojis: "🧠🪑", level: "medium" },
  { id: "cyclops", title: "Cyclops", emojis: "👁🔴", level: "medium" },
  { id: "storm", title: "Storm", emojis: "⚡🌪", level: "medium" },
  { id: "beast", title: "Beast", emojis: "🔵🦍", level: "medium" },
  { id: "deathstroke", title: "Deathstroke", emojis: "👁⚔", level: "medium" },
  { id: "lex-luthor", title: "Lex Luthor", emojis: "🧠💚", level: "medium" },
  { id: "riddler", title: "Riddler", emojis: "❓🟢", level: "medium" },
  { id: "penguin", title: "Penguin", emojis: "🎩☂", level: "medium" },
  { id: "mr-freeze", title: "Mr. Freeze", emojis: "🧊🔫", level: "medium" },
  { id: "poison-ivy", title: "Poison Ivy", emojis: "🌿💚", level: "medium" },
  { id: "scarecrow", title: "Scarecrow", emojis: "🎃🌾", level: "medium" },
  { id: "loki", title: "Loki", emojis: "🐍👑", level: "medium" },
  { id: "black-canary", title: "Black Canary", emojis: "🎤🖤", level: "medium" },
  { id: "nightwing", title: "Nightwing", emojis: "🐦🔵", level: "medium" },
  { id: "daredevil", title: "Daredevil", emojis: "⚖👁", level: "medium" },
  { id: "punisher", title: "Punisher", emojis: "💀🔫", level: "medium" },
  { id: "ghost-rider", title: "Ghost Rider", emojis: "💀🔥", level: "medium" },
  { id: "iron-fist", title: "Iron Fist", emojis: "🥋🟡", level: "medium" },
  { id: "luke-cage", title: "Luke Cage", emojis: "🟡🧱", level: "medium" },
  { id: "she-hulk", title: "She-Hulk", emojis: "🟢👩", level: "medium" },

  // ===== HARD (25) =====
  { id: "moon-knight", title: "Moon Knight", emojis: "🌙⚪", level: "hard" },
  { id: "gambit", title: "Gambit", emojis: "🃏🔴", level: "hard" },
  { id: "mister-sinister", title: "Mister Sinister", emojis: "🧬🔴", level: "hard" },
  { id: "sabretooth", title: "Sabretooth", emojis: "🐯🔪", level: "hard" },
  { id: "juggernaut", title: "Juggernaut", emojis: "🪖🦏", level: "hard" },
  { id: "colossus", title: "Colossus", emojis: "🦾⚪", level: "hard" },
  { id: "rogue", title: "Rogue", emojis: "✋🌀", level: "hard" },
  { id: "jean-grey", title: "Jean Grey", emojis: "🔥🐦", level: "hard" },
  { id: "quicksilver", title: "Quicksilver", emojis: "⚡🌀", level: "hard" },
  { id: "vision", title: "Vision", emojis: "🤖💎", level: "hard" },
  { id: "falcon", title: "Falcon", emojis: "🦅🔴", level: "hard" },
  { id: "war-machine", title: "War Machine", emojis: "🤖⚫", level: "hard" },
  { id: "black-bolt", title: "Black Bolt", emojis: "🤫👑", level: "hard" },
  { id: "star-lord", title: "Star-Lord", emojis: "🚀🎧", level: "hard" },
  { id: "gamora", title: "Gamora", emojis: "🟢⚔", level: "hard" },
  { id: "rocket-raccoon", title: "Rocket Raccoon", emojis: "🚀🔫", level: "hard" },
  { id: "groot", title: "Groot", emojis: "🌳🟤", level: "hard" },
  { id: "drax", title: "Drax", emojis: "🔪🔴", level: "hard" },
  { id: "king-shark", title: "King Shark", emojis: "🦈👑", level: "hard" },
  { id: "gorilla-grodd", title: "Gorilla Grodd", emojis: "🦍🧠", level: "hard" },
  { id: "doctor-octopus", title: "Doctor Octopus", emojis: "🐙🦾", level: "hard" },
  { id: "lizard", title: "Lizard", emojis: "🦎🧪", level: "hard" },
  { id: "sandman", title: "Sandman", emojis: "🏜🟡", level: "hard" },
  { id: "mysterio", title: "Mysterio", emojis: "🔮🌫", level: "hard" },
  { id: "shocker", title: "Shocker", emojis: "👊⚡", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "moon-girl", title: "Moon Girl", emojis: "🌙🦖", level: "impossible" },
  { id: "squirrel-girl", title: "Squirrel Girl", emojis: "🐭🥜", level: "impossible" },
  { id: "darkseid", title: "Darkseid", emojis: "👊🪨", level: "impossible" },
  { id: "mister-miracle", title: "Mister Miracle", emojis: "🔑⛓", level: "impossible" },
  { id: "martian-manhunter", title: "Martian Manhunter", emojis: "👽🔴", level: "impossible" },
  { id: "plastic-man", title: "Plastic Man", emojis: "🔴🌀", level: "impossible" },
  { id: "the-atom", title: "The Atom", emojis: "⚛🔍", level: "impossible" },
  { id: "swamp-thing", title: "Swamp Thing", emojis: "🌳🟢", level: "impossible" },
  { id: "etrigan", title: "Etrigan", emojis: "😈🔥", level: "impossible" },
  { id: "zatanna", title: "Zatanna", emojis: "🎩🔮", level: "impossible" },
  { id: "booster-gold", title: "Booster Gold", emojis: "🟡⏳", level: "impossible" },
  { id: "blue-beetle", title: "Blue Beetle", emojis: "🔵🐛", level: "impossible" },
  { id: "static-shock", title: "Static Shock", emojis: "⚡🔵", level: "impossible" },
  { id: "spawn", title: "Spawn", emojis: "⛓🔥", level: "impossible" },
  { id: "hellboy", title: "Hellboy", emojis: "😈🪨", level: "impossible" },
  { id: "the-shadow", title: "The Shadow", emojis: "🎩⚫", level: "impossible" },
  { id: "blade", title: "Blade", emojis: "🩸🧛", level: "impossible" },
  { id: "elektra", title: "Elektra", emojis: "🥷🔴", level: "impossible" },
  { id: "namor", title: "Namor", emojis: "🌊🪽", level: "impossible" },
  { id: "black-adam", title: "Black Adam", emojis: "⚡⚫", level: "impossible" },
  { id: "shazam", title: "Shazam", emojis: "⚡🔴", level: "impossible" },
  { id: "john-constantine", title: "John Constantine", emojis: "🚬🔮", level: "impossible" },
  { id: "red-hood", title: "Red Hood", emojis: "🔴🔫", level: "impossible" },
  { id: "azrael", title: "Azrael", emojis: "😇⚔", level: "impossible" },
  { id: "ultron", title: "Ultron", emojis: "🤖🧠", level: "impossible" },
];
