// E195 hero-emoji facts — one true <=70-char fact per hero, shown on reveal.
export const HERO_EMOJI_3_FACTS = {
  // EASY
  "superboy": "A DC clone hero combining Superman and Lex Luthor's DNA.",
  "power-girl": "Supergirl's Earth-2 counterpart, a powerful Kryptonian heroine.",
  "huntress": "Batman-family vigilante Helena Bertinelli, skilled with a crossbow.",
  "red-robin": "Tim Drake's identity after leaving the Robin mantle behind.",
  "batwing": "A Batman-family hero wearing armored, tech-powered bat suits.",
  "steel": "John Henry Irons, a genius engineer in a DC armored suit.",
  "captain-atom": "A DC hero powered by a quantum-energy-charged metal skin.",
  "mary-marvel": "Mary Batson, Billy's twin who also says the word Shazam.",
  "impulse": "Bart Allen, a speedster hero from the future, later Kid Flash.",
  "stargirl": "Courtney Whitmore, a JSA hero wielding the Cosmic Staff.",
  "wildcat": "Ted Grant, a JSA hero and champion boxer with nine lives.",
  "fire": "Beatriz da Costa, a Justice League hero of green flame.",
  "ice": "Tora Olafsdotter, a Justice League hero who generates ice.",
  "gypsy": "A Justice League Detroit-era hero with illusion and stealth.",
  "terra": "Tara Markov, a Teen Titans hero with earth-moving powers.",
  "bumblebee": "Karen Beecher, a Teen Titans hero who shrinks and flies.",
  "aqualad": "Garth, Aquaman's protege and a founding Teen Titans member.",
  "speedy": "Roy Harper, Green Arrow's archery-trained sidekick.",
  "yellowjacket": "Hank Pym's Avengers identity, size-changing with sting blasts.",
  "goliath": "Bill Foster, an Avengers hero who grows to giant size.",
  "stature": "Cassie Lang, Ant-Man's daughter, who also grows giant-sized.",
  "patriot": "Eli Bradley, a Young Avenger and Captain America's grandson.",
  "hulkling": "Teddy Altman, a Young Avengers shapeshifting Kree-Skrull hybrid.",
  "miss-america": "America Chavez, a Young Avenger who punches star portals.",
  "scarlet-spider": "Ben Reilly, Spider-Man's clone in a red-and-blue suit.",

  // MEDIUM
  "silk": "Cindy Moon, bitten by the same spider that empowered Peter Parker.",
  "prowler": "Hobie Brown, a Spider-Man ally turned tech-suited hero.",
  "jackpot": "Alana Jobson, a Marvel hero with spider-like enhanced strength.",
  "toxin": "Patrick Mulligan, a symbiote host bonded to Carnage's offspring.",
  "anti-venom": "Eddie Brock's cured, white-symbiote hero identity.",
  "agent-venom": "Flash Thompson, a soldier who bonded with the Venom symbiote.",
  "prodigy": "David Alleyne, a Young Avenger who can absorb others' skills.",
  "photon": "Monica Rambeau, an Avenger who converts her body into light.",
  "longshot": "A Marvel hero from Mojoworld whose luck always favors him.",
  "dazzler": "Alison Blaire, a mutant disco singer who turns sound into light.",
  "sunspot": "Roberto da Costa, a New Mutants hero powered by solar energy.",
  "cypher": "Doug Ramsey, a New Mutants hero who can decode any language.",
  "magik": "Illyana Rasputin, Colossus's sister, who wields the Soulsword.",
  "wolfsbane": "Rahne Sinclair, a New Mutant who transforms into a wolf.",
  "karma": "Xi'an Coy Manh, a New Mutant who can possess others' minds.",
  "rictor": "Julio Richter, an X-Force mutant who causes seismic tremors.",
  "boom-boom": "Tabitha Smith, an X-Force mutant who throws explosive time bombs.",
  "chamber": "Jonothon Starsmore, a mutant with a plasma-blast chest.",
  "thunderbird": "John Proudstar, an original X-Men hero, strong and fast.",
  "sabra": "Ruth Bat-Seraph, Marvel's Israeli super-soldier and agent.",
  "living-lightning": "Miguel Santos, an Avenger who becomes living electricity.",
  "darkstar": "Laynia Petrovna, a Soviet hero wielding darkforce energy.",
  "justice": "Vance Astrovik, a young Avenger with telekinetic powers.",
  "triathlon": "Delroy Garrett Jr., an Avenger who splits into three duplicates.",
  "ultragirl": "Suzy Sherman, a Marvel hero with Kryptonian-like powers.",

  // HARD
  "amadeus-cho": "A teen genius who became the Totally Awesome Hulk.",
  "red-hulk": "General Thaddeus Ross, transformed into a red-skinned Hulk.",
  "skaar": "Hulk's son, raised as a warrior gladiator on planet Sakaar.",
  "xombi": "David Kim, a Milestone Comics hero powered by living nanomachines.",
  "hardware": "Curtis Metcalf, a Milestone Comics hero in a high-tech battlesuit.",
  "icon": "Augustus Freeman, a Milestone alien posing as a wealthy human.",
  "firebird": "Bonita Juarez, a Marvel hero granted fire and flight by a vision.",
  "signal": "Duke Thomas, a Batman-family hero with light-based tech gear.",
  "spoiler": "Stephanie Brown, a Batman-family hero who briefly was Batgirl.",
  "batman-beyond": "Terry McGinnis, a futuristic Batman mentored by aging Bruce Wayne.",
  "doctor-mid-nite": "Charles McNider, a JSA hero blind by day, sees in darkness.",
  "hourman": "Rex Tyler, a JSA hero whose Miraclo drug grants an hour of power.",
  "atom-smasher": "Al Rothstein, a JSA hero who can grow to giant size.",
  "talisman": "Elizabeth Twoyoungmen, an Alpha Flight shaman with mystic power.",
  "timber-wolf": "Brin Londo, a Legion of Super-Heroes member, feral and fast.",
  "ultra-boy": "Jo Nah, a Legion of Super-Heroes hero using one power at a time.",
  "element-lad": "Jan Arrah, a Legion of Super-Heroes hero who transmutes matter.",
  "cosmic-boy": "Rokk Krinn, a founding Legion of Super-Heroes hero with magnetism.",
  "saturn-girl": "Imra Ardeen, a founding Legion of Super-Heroes telepath.",
  "lightning-lad": "Garth Ranzz, a founding Legion of Super-Heroes hero with bolts.",
  "brainiac-5": "Querl Dox, a genius Legion hero descended from Brainiac.",
  "mon-el": "A Daxamite hero and close ally of Superman with similar powers.",
  "chameleon-boy": "Reep Daggle, a shapeshifting Legion of Super-Heroes member.",
  "ravager": "Rose Wilson, Deathstroke's daughter turned mercenary hero.",
  "kid-devil": "Eddie Bloomberg, a Teen Titans hero with a fiery devil-like form.",

  // IMPOSSIBLE
  "nite-owl": "Watchmen's gadget-driven vigilante who pilots the ship Archie.",
  "rorschach": "Watchmen's detective with an ever-shifting inkblot mask.",
  "silk-spectre": "Watchmen's acrobatic heroine, a mother-daughter legacy in purple.",
  "doctor-manhattan": "Watchmen's blue-skinned physicist with godlike quantum powers.",
  "miracleman": "A British comic hero who transforms into a godlike being.",
  "the-tick": "A blue, super-strong parody superhero known for his antennae.",
  "atomic-robo": "An indie comic robot built by Nikola Tesla, fighting pulp menaces.",
  "concrete": "Paul Chadwick's hero, a man's brain in a living stone body.",
  "ninjak": "Colin King, a Valiant Comics master spy and ninja assassin.",
  "archer": "Obadiah Archer, an archer half of Valiant duo Archer & Armstrong.",
  "armstrong": "A near-immortal, hard-drinking Valiant hero thousands of years old.",
  "faith": "Faith Herbert, a Valiant hero called Zephyr who can fly.",
  "quantum": "Eric Henderson, half of Valiant's size-shifting duo Quantum and Woody.",
  "woody": "Woody Henderson, the wisecracking half of Quantum and Woody.",
  "rai": "A futuristic Valiant samurai guided by an orbiting AI called Father.",
  "divinity": "A Soviet cosmonaut granted godlike cosmic powers in deep space.",
  "nemesis": "Tom Tresser, a DC undercover agent skilled in disguise and combat.",
  "peacemaker": "A DC soldier who loves peace so much he'll kill for it.",
  "judomaster": "Rip Jagger, a Charlton Comics hero and judo combat master.",
  "question": "A DC detective hero who wears a featureless, faceless mask.",
  "vigilante": "Adrian Chase, a DC hero with a western gunslinger fighting style.",
  "metamorpho": "Rex Mason, a DC hero who can transform into any element.",
  "elongated-man": "Ralph Dibny, a DC detective hero who stretches his whole body.",
  "doop": "A strange yellow blob creature, an X-Force member of unknown origin.",
  "icarus": "Josiah X, a Young Avenger with feathered wings who can fly.",
};
