// E195 «Guess the Superhero by Emoji 3» — 100 heroes · 25/tier
// VO: sfx/e195-<id>.wav
export const HERO_EMOJI_3 = [
  // ===== EASY (25) =====
  { id: "superboy", title: "Superboy", emojis: "🦸👦", level: "easy" },
  { id: "power-girl", title: "Power Girl", emojis: "🦸👩", level: "easy" },
  { id: "huntress", title: "Huntress", emojis: "🏹🖤", level: "easy" },
  { id: "red-robin", title: "Red Robin", emojis: "🦇❤", level: "easy" },
  { id: "batwing", title: "Batwing", emojis: "🦇🖤", level: "easy" },
  { id: "steel", title: "Steel", emojis: "🔨⚙", level: "easy" },
  { id: "captain-atom", title: "Captain Atom", emojis: "⚛🎖", level: "easy" },
  { id: "mary-marvel", title: "Mary Marvel", emojis: "⚡👧", level: "easy" },
  { id: "impulse", title: "Impulse", emojis: "⚡🏃", level: "easy" },
  { id: "stargirl", title: "Stargirl", emojis: "⭐🪄", level: "easy" },
  { id: "wildcat", title: "Wildcat", emojis: "🐱🥊", level: "easy" },
  { id: "fire", title: "Fire", emojis: "🔥👩", level: "easy" },
  { id: "ice", title: "Ice", emojis: "❄👩", level: "easy" },
  { id: "gypsy", title: "Gypsy", emojis: "🔮👤", level: "easy" },
  { id: "terra", title: "Terra", emojis: "🌍🪨", level: "easy" },
  { id: "bumblebee", title: "Bumblebee", emojis: "🐝🔫", level: "easy" },
  { id: "aqualad", title: "Aqualad", emojis: "🌊👦", level: "easy" },
  { id: "speedy", title: "Speedy", emojis: "🏹💨", level: "easy" },
  { id: "yellowjacket", title: "Yellowjacket", emojis: "🐝🔬", level: "easy" },
  { id: "goliath", title: "Goliath", emojis: "🧍📏", level: "easy" },
  { id: "stature", title: "Stature", emojis: "📏👧", level: "easy" },
  { id: "patriot", title: "Patriot", emojis: "🎖🛡", level: "easy" },
  { id: "hulkling", title: "Hulkling", emojis: "💚🐉", level: "easy" },
  { id: "miss-america", title: "Miss America", emojis: "👊⭐", level: "easy" },
  { id: "scarlet-spider", title: "Scarlet Spider", emojis: "🕷❤", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "silk", title: "Silk", emojis: "🕷🧶", level: "medium" },
  { id: "prowler", title: "Prowler", emojis: "🐆🔧", level: "medium" },
  { id: "jackpot", title: "Jackpot", emojis: "🎰💪", level: "medium" },
  { id: "toxin", title: "Toxin", emojis: "🧪🖤", level: "medium" },
  { id: "anti-venom", title: "Anti-Venom", emojis: "🤍🕷", level: "medium" },
  { id: "agent-venom", title: "Agent Venom", emojis: "🪖🕷", level: "medium" },
  { id: "prodigy", title: "Prodigy", emojis: "🧠🎓", level: "medium" },
  { id: "photon", title: "Photon", emojis: "💡✨", level: "medium" },
  { id: "longshot", title: "Longshot", emojis: "🎲🍀", level: "medium" },
  { id: "dazzler", title: "Dazzler", emojis: "🎤💫", level: "medium" },
  { id: "sunspot", title: "Sunspot", emojis: "☀🖤", level: "medium" },
  { id: "cypher", title: "Cypher", emojis: "🔤🧬", level: "medium" },
  { id: "magik", title: "Magik", emojis: "⚔🔥", level: "medium" },
  { id: "wolfsbane", title: "Wolfsbane", emojis: "🐺🌿", level: "medium" },
  { id: "karma", title: "Karma", emojis: "🧠🕹", level: "medium" },
  { id: "rictor", title: "Rictor", emojis: "🏚📳", level: "medium" },
  { id: "boom-boom", title: "Boom-Boom", emojis: "💣💥", level: "medium" },
  { id: "chamber", title: "Chamber", emojis: "💥👄", level: "medium" },
  { id: "thunderbird", title: "Thunderbird", emojis: "🦅⛈", level: "medium" },
  { id: "gladiator", title: "Gladiator", emojis: "👽⚔", level: "medium" },
  { id: "living-lightning", title: "Living Lightning", emojis: "⚡👻", level: "medium" },
  { id: "darkstar", title: "Darkstar", emojis: "🌑✨", level: "medium" },
  { id: "justice", title: "Justice", emojis: "⚖💪", level: "medium" },
  { id: "triathlon", title: "Triathlon", emojis: "🏊🥇", level: "medium" },
  { id: "ultragirl", title: "Ultragirl", emojis: "💪👧", level: "medium" },

  // ===== HARD (25) =====
  { id: "amadeus-cho", title: "Amadeus Cho", emojis: "🧠👊", level: "hard" },
  { id: "red-hulk", title: "Red Hulk", emojis: "👊❤", level: "hard" },
  { id: "skaar", title: "Skaar", emojis: "🪓👦", level: "hard" },
  { id: "xombi", title: "Xombi", emojis: "🧟🔬", level: "hard" },
  { id: "hardware", title: "Hardware", emojis: "🤖🔧", level: "hard" },
  { id: "icon", title: "Icon", emojis: "👽🎩", level: "hard" },
  { id: "firebird", title: "Firebird", emojis: "🔥🕊", level: "hard" },
  { id: "signal", title: "Signal", emojis: "📡🦇", level: "hard" },
  { id: "spoiler", title: "Spoiler", emojis: "🎭🦇", level: "hard" },
  { id: "batman-beyond", title: "Batman Beyond", emojis: "🦇🌃", level: "hard" },
  { id: "doctor-mid-nite", title: "Doctor Mid-Nite", emojis: "🦉🌑", level: "hard" },
  { id: "hourman", title: "Hourman", emojis: "⏳💊", level: "hard" },
  { id: "atom-smasher", title: "Atom Smasher", emojis: "⚛👊", level: "hard" },
  { id: "talisman", title: "Talisman", emojis: "🪶🔮", level: "hard" },
  { id: "timber-wolf", title: "Timber Wolf", emojis: "🐺🌲", level: "hard" },
  { id: "ultra-boy", title: "Ultra Boy", emojis: "💥👦", level: "hard" },
  { id: "element-lad", title: "Element Lad", emojis: "🧪👦", level: "hard" },
  { id: "cosmic-boy", title: "Cosmic Boy", emojis: "🧲👦", level: "hard" },
  { id: "saturn-girl", title: "Saturn Girl", emojis: "🪐👧", level: "hard" },
  { id: "lightning-lad", title: "Lightning Lad", emojis: "⚡👦", level: "hard" },
  { id: "brainiac-5", title: "Brainiac 5", emojis: "🧠🤖", level: "hard" },
  { id: "mon-el", title: "Mon-El", emojis: "🪐🦸", level: "hard" },
  { id: "chameleon-boy", title: "Chameleon Boy", emojis: "🦎👦", level: "hard" },
  { id: "ravager", title: "Ravager", emojis: "⚔🗡", level: "hard" },
  { id: "kid-devil", title: "Kid Devil", emojis: "😈🧒", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "nite-owl", title: "Nite Owl", emojis: "🦉🌃", level: "impossible" },
  { id: "rorschach", title: "Rorschach", emojis: "🎭🖤", level: "impossible" },
  { id: "silk-spectre", title: "Silk Spectre", emojis: "🎭💜", level: "impossible" },
  { id: "doctor-manhattan", title: "Doctor Manhattan", emojis: "💙🧑", level: "impossible" },
  { id: "miracleman", title: "Miracleman", emojis: "✨🦸", level: "impossible" },
  { id: "the-tick", title: "The Tick", emojis: "🦟💪", level: "impossible" },
  { id: "atomic-robo", title: "Atomic Robo", emojis: "⚛🤖", level: "impossible" },
  { id: "concrete", title: "Concrete", emojis: "🗿💪", level: "impossible" },
  { id: "ninjak", title: "Ninjak", emojis: "🥷⚔", level: "impossible" },
  { id: "archer", title: "Archer", emojis: "🏹🗡", level: "impossible" },
  { id: "armstrong", title: "Armstrong", emojis: "🍺💪", level: "impossible" },
  { id: "faith", title: "Faith", emojis: "🦋💫", level: "impossible" },
  { id: "quantum", title: "Quantum", emojis: "⚛🎈", level: "impossible" },
  { id: "woody", title: "Woody", emojis: "🪵🔫", level: "impossible" },
  { id: "rai", title: "Rai", emojis: "⚔🛰", level: "impossible" },
  { id: "divinity", title: "Divinity", emojis: "🌌🧘", level: "impossible" },
  { id: "nemesis", title: "Nemesis", emojis: "🎭🔫", level: "impossible" },
  { id: "peacemaker", title: "Peacemaker", emojis: "🕊🪖", level: "impossible" },
  { id: "judomaster", title: "Judomaster", emojis: "🥋🎗", level: "impossible" },
  { id: "question", title: "Question", emojis: "❓🎭", level: "impossible" },
  { id: "vigilante", title: "Vigilante", emojis: "🤠🔫", level: "impossible" },
  { id: "metamorpho", title: "Metamorpho", emojis: "🧪🔀", level: "impossible" },
  { id: "elongated-man", title: "Elongated Man", emojis: "👃🌀", level: "impossible" },
  { id: "doop", title: "Doop", emojis: "💛👾", level: "impossible" },
  { id: "icarus", title: "Icarus", emojis: "🪽☀", level: "impossible" },
];
