// E147 hobby-emoji facts — one TRUE ≤70-char fact per hobby, shown on reveal.
export const HOBBY_EMOJI_FACTS = {
  // EASY
  "painting": "Cave paintings in Spain and France are over 30,000 years old.",
  "fishing": "Recreational angling is one of the world's most popular pastimes.",
  "cooking": "Home cooking uses heat to make food safer and easier to digest.",
  "gardening": "Gardening is a top outdoor hobby and a form of light exercise.",
  "photography": "The word photography means 'drawing with light' in Greek.",
  "reading": "Regular reading can lower stress and build vocabulary.",
  "dancing": "Dancing improves balance, coordination, and heart health.",
  "singing": "Singing releases endorphins and can boost your mood.",
  "drawing": "Drawing is one of the oldest forms of human expression.",
  "swimming": "Swimming is a full-body, low-impact form of exercise.",
  "cycling": "Cycling is both a hobby and a low-cost way to commute.",
  "running": "A 'runner's high' comes from endorphins released while running.",
  "gaming": "Video gaming is now a hobby for billions of people worldwide.",
  "baking": "Baking uses dry heat in an oven to cook breads and cakes.",
  "hiking": "Hiking is walking in nature, often on trails or hills.",
  "camping": "Camping means staying overnight outdoors, often in a tent.",
  "yoga": "Yoga began in ancient India and blends poses with breathing.",
  "knitting": "Knitting turns a single yarn into fabric using two needles.",
  "sewing": "Sewing joins fabric with stitches using a needle and thread.",
  "chess": "Chess likely began in India around the 6th century.",
  "bowling": "Ten-pin bowling knocks down pins with a rolled ball.",
  "darts": "Darts is a popular pub game of throwing at a numbered board.",
  "playing-guitar": "The guitar is one of the world's most popular instruments.",
  "puzzles": "Solving puzzles can sharpen memory and problem-solving.",
  "skateboarding": "Skateboarding grew from 1950s California surf culture.",
  // MEDIUM
  "pottery": "Potters shape wet clay, then harden it with heat in a kiln.",
  "calligraphy": "Calligraphy is the art of beautiful, decorative handwriting.",
  "origami": "Origami is the Japanese art of folding paper into shapes.",
  "woodworking": "Woodworking shapes wood into furniture and other objects.",
  "birdwatching": "Birdwatchers observe and identify birds in the wild.",
  "astronomy": "Amateur astronomers study stars and planets with telescopes.",
  "surfing": "Surfing means riding ocean waves on a board.",
  "skiing": "Skiing lets people glide over snow on a pair of skis.",
  "snowboarding": "Snowboarding became an Olympic sport in 1998.",
  "ice-skating": "Ice skating glides across ice on bladed boots.",
  "roller-skating": "Roller skating boomed as a pastime in the 1970s.",
  "archery": "Archery is the skill of shooting arrows with a bow.",
  "tennis": "Modern tennis was codified in England in the 1870s.",
  "table-tennis": "Table tennis is also widely known as ping-pong.",
  "badminton": "Badminton is played with a feathered shuttlecock.",
  "golf": "Golf as we know it began in 15th-century Scotland.",
  "boxing": "Boxing is a combat sport contested with padded gloves.",
  "martial-arts": "Martial arts blend self-defense with discipline and fitness.",
  "weightlifting": "Lifting weights builds muscle strength and bone density.",
  "kayaking": "The kayak was invented by the Inuit for Arctic hunting.",
  "sailing": "Sailing uses wind in sails to move a boat across water.",
  "rock-climbing": "Rock climbers ascend walls using grip, balance, and ropes.",
  "juggling": "Juggling keeps several objects in the air at once.",
  "magic-tricks": "Stage magic entertains through illusion and sleight of hand.",
  "scuba-diving": "SCUBA stands for self-contained underwater breathing apparatus.",
  // HARD
  "fencing": "Fencing is sword sport with foil, epee, or sabre.",
  "gymnastics": "Gymnastics combines strength, flexibility, and balance.",
  "horse-riding": "Horse riding, or equestrianism, dates back thousands of years.",
  "rowing": "Rowers propel a boat with oars, often as a team.",
  "snorkeling": "Snorkeling views underwater life using a mask and tube.",
  "skydiving": "Skydivers free-fall before opening a parachute to land.",
  "beekeeping": "Beekeepers raise honeybees to harvest honey and beeswax.",
  "stamp-collecting": "Collecting stamps is known as philately.",
  "coin-collecting": "Coin collecting is called numismatics.",
  "model-trains": "Model railways recreate trains and scenery in miniature.",
  "model-building": "Scale models replicate planes, cars, or ships in miniature.",
  "brewing-beer": "Home brewing ferments grains and hops to make beer.",
  "winemaking": "Winemaking ferments grape juice into wine.",
  "cheesemaking": "Cheesemaking curdles milk, then ages the curds into cheese.",
  "embroidery": "Embroidery decorates fabric with needle and thread designs.",
  "crochet": "Crochet builds fabric from yarn using a single hook.",
  "quilting": "Quilting stitches layers of fabric into a padded blanket.",
  "candle-making": "Candle makers pour melted wax around a wick.",
  "soap-making": "Handmade soap is made by mixing oils with lye.",
  "mixology": "Mixology is the craft of creating mixed drinks and cocktails.",
  "latte-art": "Latte art pours steamed milk into patterns on coffee.",
  "sushi-making": "Sushi pairs vinegared rice with fish or vegetables.",
  "grilling": "Grilling cooks food over direct heat from flame or coals.",
  "foraging": "Foraging gathers wild edible plants, berries, and mushrooms.",
  "metal-detecting": "Metal detectorists hunt for buried coins and relics.",
  // IMPOSSIBLE
  "vexillology": "Vexillology is the scholarly study of flags.",
  "lepidoptery": "Lepidoptery is the study or collecting of butterflies and moths.",
  "entomology": "Entomology is the scientific study of insects.",
  "mycology": "Mycology is the study of fungi, including mushrooms.",
  "herbalism": "Herbalism uses plants for remedies and wellness.",
  "ikebana": "Ikebana is the Japanese art of flower arranging.",
  "bonsai": "Bonsai grows miniature trees in shallow trays.",
  "topiary": "Topiary is the art of clipping shrubs into shapes.",
  "terrarium-making": "A terrarium is a tiny garden grown inside a glass container.",
  "aquascaping": "Aquascaping is the art of landscaping planted aquariums.",
  "macrame": "Macrame creates textiles by knotting cord by hand.",
  "taxidermy": "Taxidermy preserves and mounts animals in lifelike poses.",
  "lapidary": "Lapidary is the craft of cutting and polishing gemstones.",
  "gemology": "Gemology is the science of identifying gemstones.",
  "fossil-hunting": "Fossil hunters search rock for remains of ancient life.",
  "glassblowing": "Glassblowing shapes molten glass by blowing air into it.",
  "blacksmithing": "Blacksmiths forge iron and steel with heat and a hammer.",
  "leatherworking": "Leatherworking crafts items from tanned animal hide.",
  "bookbinding": "Bookbinding assembles pages into a finished bound book.",
  "pyrography": "Pyrography burns designs into wood with a hot tool.",
  "falconry": "Falconry is hunting with trained birds of prey.",
  "spelunking": "Spelunking is the hobby of exploring caves.",
  "fermentation": "Fermentation uses microbes to make foods like kimchi.",
  "quilling": "Quilling rolls thin paper strips into decorative shapes.",
  "model-rocketry": "Model rocketry launches small rockets with solid motors.",
};
