// E143 «Guess the Holiday by Emoji» facts — one verified <=70-char fact per
// holiday, shown on reveal. Origin/date/country. No Israel/political-state content.
export const HOLIDAY_EMOJI_FACTS = {
  // EASY
  "christmas": "Christian feast on Dec 25 marking the birth of Jesus.",
  "halloween": "Oct 31 eve of costumes and trick-or-treating; from Samhain.",
  "valentines-day": "Feb 14; a day of romance named for St. Valentine.",
  "easter": "Christian spring feast celebrating the resurrection of Jesus.",
  "thanksgiving": "US autumn feast of gratitude, the 4th Thursday of November.",
  "new-years-eve": "Dec 31 night; the world counts down to the new year.",
  "chinese-new-year": "Lunar New Year, the biggest festival in China.",
  "mothers-day": "A day honoring mothers, held in May in many countries.",
  "fathers-day": "A day honoring fathers, often the 3rd Sunday of June.",
  "st-patricks-day": "Mar 17; Ireland's patron saint, marked by wearing green.",
  "ramadan": "Islamic holy month of daytime fasting from dawn to sunset.",
  "diwali": "Hindu festival of lights celebrated across India.",
  "hanukkah": "Jewish eight-day Festival of Lights with a lit menorah.",
  "oktoberfest": "Munich's giant beer festival, held Sept into October.",
  "carnival": "Pre-Lent festival of parades and costumes; famed in Brazil.",
  "day-of-the-dead": "Mexican Dia de Muertos honoring the dead on Nov 1-2.",
  "independence-day-usa": "US July 4 marks the 1776 Declaration of Independence.",
  "eid-al-fitr": "Islamic feast ending the fasting month of Ramadan.",
  "earth-day": "Apr 22; a global day promoting protection of the planet.",
  "april-fools-day": "Apr 1; a day of pranks and hoaxes worldwide.",
  "mardi-gras": "Fat Tuesday carnival before Lent; famed in New Orleans.",
  "holi": "Hindu spring festival where people throw colored powders.",
  "labor-day": "Workers' holiday; May 1 globally or September in the US.",
  "new-years-day": "Jan 1; the first day of the Gregorian calendar year.",
  "cinco-de-mayo": "May 5 marks Mexico's 1862 victory at the Battle of Puebla.",

  // MEDIUM
  "bastille-day": "France's national day, July 14, marking the 1789 revolution.",
  "groundhog-day": "US Feb 2; a groundhog is said to predict spring weather.",
  "lantern-festival": "Ends Chinese New Year; lanterns light the 15th lunar day.",
  "songkran": "Thai New Year in April, famous for public water fights.",
  "dragon-boat-festival": "Chinese festival with boat races and rice dumplings.",
  "mid-autumn-festival": "East Asian harvest festival with mooncakes and full moon.",
  "nowruz": "Persian New Year at the spring equinox, around March 21.",
  "boxing-day": "Dec 26 holiday in the UK and Commonwealth countries.",
  "international-womens-day": "Mar 8; a global day celebrating women's achievements.",
  "hina-matsuri": "Japan's Doll Festival displays hina dolls for girls each March.",
  "kwanzaa": "African-American culture festival held Dec 26 to Jan 1.",
  "eid-al-adha": "Islamic Feast of Sacrifice during the Hajj pilgrimage.",
  "midsummer": "Nordic summer solstice festival with bonfires and dancing.",
  "cherry-blossom-festival": "Japanese hanami; spring viewing of blooming cherry trees.",
  "epiphany": "Jan 6 Christian feast of the Three Kings visiting Jesus.",
  "st-nicholas-day": "Dec 6; children get gifts in shoes across much of Europe.",
  "remembrance-day": "Nov 11 honors war dead; a red poppy is worn.",
  "veterans-day": "US Nov 11 honoring all who served in the armed forces.",
  "chuseok": "Korean autumn harvest festival honoring ancestors.",
  "tanabata": "Japanese star festival in July with wishes tied to bamboo.",
  "la-tomatina": "Spanish festival in Bunol where crowds hurl ripe tomatoes.",
  "running-of-the-bulls": "Pamplona's San Fermin; runners flee bulls through streets.",
  "walpurgis-night": "Apr 30 North European night of bonfires against witches.",
  "all-souls-day": "Nov 2 Christian day of prayer for the departed.",
  "guy-fawkes-night": "UK Nov 5 bonfires mark the foiled 1605 Gunpowder Plot.",

  // HARD
  "vesak": "Buddhist festival marking the Buddha's birth and awakening.",
  "ganesh-chaturthi": "Hindu festival honoring the elephant-headed god Ganesha.",
  "navratri": "Nine-night Hindu festival of dance honoring goddess Durga.",
  "raksha-bandhan": "Hindu day; sisters tie a rakhi thread on brothers' wrists.",
  "pongal": "Tamil harvest festival thanking the sun, held in January.",
  "onam": "Kerala harvest festival with flower art and boat races.",
  "obon": "Japanese Buddhist festival honoring ancestral spirits.",
  "setsubun": "Japanese bean-throwing rite to drive out demons in February.",
  "saint-lucia-day": "Dec 13 Swedish feast; girls wear crowns of candles.",
  "sinterklaas": "Dutch feast; St. Nicholas arrives by steamboat in December.",
  "loy-krathong": "Thai night when floats with candles drift on the water.",
  "yi-peng": "Northern Thai festival releasing glowing sky lanterns.",
  "las-fallas": "Valencia's March festival burning giant papier-mache figures.",
  "up-helly-aa": "Shetland Viking fire festival ending in a burning longship.",
  "sant-jordi": "Catalan Apr 23; people exchange roses and books.",
  "krampusnacht": "Alpine Dec 5 night when the horned Krampus scares children.",
  "gion-matsuri": "Kyoto's July festival with towering wooden floats.",
  "inti-raymi": "Inca Festival of the Sun held in Cusco, Peru, in June.",
  "fasnacht": "Swiss carnival with masks, drums and early-morning parades.",
  "junkanoo": "Bahamian street parade with drums and costumes at Christmas.",
  "holy-week": "Christian week before Easter with processions and palms.",
  "timkat": "Ethiopian Orthodox Epiphany with water blessings in January.",
  "baisakhi": "Punjabi spring harvest festival, also a Sikh new year.",
  "naadam": "Mongolian games of wrestling, horse racing and archery.",
  "palio-di-siena": "Bareback horse race around Siena's main square in Italy.",

  // IMPOSSIBLE
  "cheese-rolling": "English race chasing a wheel of cheese down a steep hill.",
  "battle-of-the-oranges": "Italy's Ivrea carnival with a huge orange-throwing fight.",
  "wife-carrying": "Finnish sport where men race carrying their partners.",
  "monkey-buffet": "Thai feast in Lopburi laying out fruit for wild monkeys.",
  "baby-jumping": "Spanish rite where men leap over rows of babies on mats.",
  "boryeong-mud": "Korean summer festival of mud pools and mud wrestling.",
  "sapporo-snow": "Japanese festival of giant ice and snow sculptures.",
  "elephant-festival": "Jaipur, India event with painted, decorated elephants.",
  "camel-wrestling": "Turkish winter contest pitting two male camels together.",
  "bog-snorkelling": "Welsh race snorkeling through a muddy peat bog trench.",
  "frozen-dead-guy": "Colorado festival themed on a cryogenically frozen corpse.",
  "night-of-the-radishes": "Oaxaca, Mexico Dec 23 contest carving large radishes.",
  "tar-barrels": "Devon town where people run carrying flaming tar barrels.",
  "hair-freezing": "Yukon contest for the best hairstyle frozen in cold air.",
  "world-gurning": "English contest for pulling the ugliest face through a collar.",
  "toe-wrestling": "English pub sport locking toes to pin an opponent's foot.",
  "nyepi": "Balinese Hindu New Year; a full day of silence and stillness.",
  "pchum-ben": "Cambodian festival honoring ancestors with rice offerings.",
  "gai-jatra": "Nepali cow procession honoring those who died that year.",
  "thaipusam": "Tamil Hindu festival of devotion to the god Murugan.",
  "wianki": "Polish midsummer night floating flower wreaths on rivers.",
  "kukeri": "Bulgarian rite; masked dancers in bells chase off evil.",
  "cascamorras": "Spanish festival where crowds cover a runner in black paint.",
  "haro-wine": "Spanish battle in Haro where people drench each other in wine.",
  "cheung-chau-bun": "Hong Kong festival with bun towers and a climbing race.",
};
