// «Guess the Horse Breed» — GuessSync · E43 · 100 breeds (25/tier) · real photos from Wikimedia Commons
// Sorted by global recognizability: easy (Arabian/Thoroughbred) → impossible (Sorraia/Nokota/Yakutian).
export const HORSES = [
  // EASY (25) — household-name breeds
  { slug: "arabian", name: "Arabian", level: "easy" },
  { slug: "thoroughbred", name: "Thoroughbred", level: "easy" },
  { slug: "mustang", name: "Mustang", level: "easy" },
  { slug: "clydesdale", name: "Clydesdale", level: "easy" },
  { slug: "shetland", name: "Shetland Pony", level: "easy" },
  { slug: "appaloosa", name: "Appaloosa", level: "easy" },
  { slug: "friesian", name: "Friesian", level: "easy" },
  { slug: "shire", name: "Shire", level: "easy" },
  { slug: "quarterhorse", name: "American Quarter Horse", level: "easy" },
  { slug: "palomino", name: "Palomino", level: "easy" },
  { slug: "andalusian", name: "Andalusian", level: "easy" },
  { slug: "lipizzaner", name: "Lipizzaner", level: "easy" },
  { slug: "percheron", name: "Percheron", level: "easy" },
  { slug: "welshpony", name: "Welsh Pony", level: "easy" },
  { slug: "icelandic", name: "Icelandic Horse", level: "easy" },
  { slug: "haflinger", name: "Haflinger", level: "easy" },
  { slug: "morgan", name: "Morgan", level: "easy" },
  { slug: "paint", name: "American Paint Horse", level: "easy" },
  { slug: "belgian", name: "Belgian", level: "easy" },
  { slug: "hanoverian", name: "Hanoverian", level: "easy" },
  { slug: "connemara", name: "Connemara Pony", level: "easy" },
  { slug: "gypsyvanner", name: "Gypsy Vanner", level: "easy" },
  { slug: "miniature", name: "Miniature Horse", level: "easy" },
  { slug: "standardbred", name: "Standardbred", level: "easy" },
  { slug: "americansaddlebred", name: "American Saddlebred", level: "easy" },
  // MEDIUM (25)
  { slug: "tennesseewalker", name: "Tennessee Walking Horse", level: "medium" },
  { slug: "dutchwarmblood", name: "Dutch Warmblood", level: "medium" },
  { slug: "trakehner", name: "Trakehner", level: "medium" },
  { slug: "oldenburg", name: "Oldenburg", level: "medium" },
  { slug: "holsteiner", name: "Holsteiner", level: "medium" },
  { slug: "sellefrancais", name: "Selle Français", level: "medium" },
  { slug: "irishsporthorse", name: "Irish Sport Horse", level: "medium" },
  { slug: "clevelandbay", name: "Cleveland Bay", level: "medium" },
  { slug: "suffolkpunch", name: "Suffolk Punch", level: "medium" },
  { slug: "fellpony", name: "Fell Pony", level: "medium" },
  { slug: "dalespony", name: "Dales Pony", level: "medium" },
  { slug: "highlandpony", name: "Highland Pony", level: "medium" },
  { slug: "newforest", name: "New Forest Pony", level: "medium" },
  { slug: "exmoor", name: "Exmoor Pony", level: "medium" },
  { slug: "missourifoxtrotter", name: "Missouri Fox Trotter", level: "medium" },
  { slug: "rockymountain", name: "Rocky Mountain Horse", level: "medium" },
  { slug: "pasofino", name: "Paso Fino", level: "medium" },
  { slug: "peruvianpaso", name: "Peruvian Paso", level: "medium" },
  { slug: "azteca", name: "Azteca", level: "medium" },
  { slug: "criollo", name: "Criollo", level: "medium" },
  { slug: "mangalarga", name: "Mangalarga Marchador", level: "medium" },
  { slug: "knabstrupper", name: "Knabstrupper", level: "medium" },
  { slug: "gelderland", name: "Gelderland", level: "medium" },
  { slug: "dartmoor", name: "Dartmoor Pony", level: "medium" },
  { slug: "hackney", name: "Hackney", level: "medium" },
  // HARD (25)
  { slug: "lusitano", name: "Lusitano", level: "hard" },
  { slug: "barb", name: "Barb", level: "hard" },
  { slug: "orlovtrotter", name: "Orlov Trotter", level: "hard" },
  { slug: "dolehorse", name: "Døle", level: "hard" },
  { slug: "finnhorse", name: "Finnhorse", level: "hard" },
  { slug: "noriker", name: "Noriker", level: "hard" },
  { slug: "murgese", name: "Murgese", level: "hard" },
  { slug: "maremmano", name: "Maremmano", level: "hard" },
  { slug: "boulonnais", name: "Boulonnais", level: "hard" },
  { slug: "breton", name: "Breton", level: "hard" },
  { slug: "ardennes", name: "Ardennes", level: "hard" },
  { slug: "jutland", name: "Jutland", level: "hard" },
  { slug: "przewalski", name: "Przewalski’s Horse", level: "hard" },
  { slug: "kathiawari", name: "Kathiawari", level: "hard" },
  { slug: "dulmen", name: "Dülmen Pony", level: "hard" },
  { slug: "pottok", name: "Pottok", level: "hard" },
  { slug: "hucul", name: "Hucul Pony", level: "hard" },
  { slug: "konik", name: "Konik", level: "hard" },
  { slug: "shagya", name: "Shagya Arabian", level: "hard" },
  { slug: "wielkopolski", name: "Wielkopolski", level: "hard" },
  { slug: "furioso", name: "Furioso-North Star", level: "hard" },
  { slug: "nonius", name: "Nonius", level: "hard" },
  { slug: "kabardian", name: "Kabarda", level: "hard" },
  { slug: "karabakh", name: "Karabakh", level: "hard" },
  { slug: "budyonny", name: "Budyonny", level: "hard" },
  // IMPOSSIBLE (25) — rare real breeds
  { slug: "akhalteke", name: "Akhal-Teke", level: "impossible" },
  { slug: "marwari", name: "Marwari", level: "impossible" },
  { slug: "falabella", name: "Falabella", level: "impossible" },
  { slug: "fjord", name: "Norwegian Fjord", level: "impossible" },
  { slug: "camargue", name: "Camargue", level: "impossible" },
  { slug: "sorraia", name: "Sorraia", level: "impossible" },
  { slug: "kladruber", name: "Kladruber", level: "impossible" },
  { slug: "nokota", name: "Nokota", level: "impossible" },
  { slug: "caspian", name: "Caspian", level: "impossible" },
  { slug: "americancreamdraft", name: "American Cream Draft", level: "impossible" },
  { slug: "galiceno", name: "Galiceño", level: "impossible" },
  { slug: "losino", name: "Losino", level: "impossible" },
  { slug: "kinsky", name: "Kinsky", level: "impossible" },
  { slug: "giara", name: "Giara", level: "impossible" },
  { slug: "asturcon", name: "Asturcón", level: "impossible" },
  { slug: "garrano", name: "Garrano", level: "impossible" },
  { slug: "misaki", name: "Misaki", level: "impossible" },
  { slug: "tokara", name: "Tokara", level: "impossible" },
  { slug: "kiso", name: "Kiso", level: "impossible" },
  { slug: "yakutian", name: "Yakutian", level: "impossible" },
  { slug: "bhutia", name: "Bhutia", level: "impossible" },
  { slug: "pleven", name: "Pleven", level: "impossible" },
  { slug: "sableisland", name: "Sable Island", level: "impossible" },
  { slug: "banker", name: "Banker", level: "impossible" },
  { slug: "floridacracker", name: "Florida Cracker Horse", level: "impossible" },
];
