// «Guess the Horse Breed» — GuessSync · E43 · did-you-know facts, ≤70 chars, verified true.
export const HORSE_FACTS = {
  // EASY
  "arabian": "Ancient desert breed with a dished face and high tail",
  "thoroughbred": "The fast, hot-blooded breed of horse racing",
  "mustang": "Free-roaming horse of the American West",
  "clydesdale": "Scottish draft giant with feathered white legs",
  "shetland": "Tiny, hardy pony from Scotland’s Shetland Isles",
  "appaloosa": "Famous for its spotted, leopard-like coat",
  "friesian": "Jet-black Dutch breed with long, flowing mane",
  "shire": "One of the tallest, heaviest draft horses on Earth",
  "quarterhorse": "Sprinter that outruns others over a quarter mile",
  "palomino": "Golden coat with a white mane and tail",
  "andalusian": "Elegant grey Spanish breed prized for dressage",
  "lipizzaner": "White horses of Vienna’s Spanish Riding School",
  "percheron": "Powerful French draft horse, often dapple grey",
  "welshpony": "Sturdy, versatile pony from the hills of Wales",
  "icelandic": "Small, hardy breed with a unique smooth ‘tölt’ gait",
  "haflinger": "Chestnut Alpine breed with a flaxen mane",
  "morgan": "Early American breed tracing to one stallion",
  "paint": "Stock horse with bold patches of white and colour",
  "belgian": "Massive, gentle draft breed from Belgium",
  "hanoverian": "German warmblood that dominates Olympic sport",
  "connemara": "Ireland’s athletic native pony, a great jumper",
  "gypsyvanner": "Piebald cob with heavy leg feathering",
  "miniature": "Bred to be tiny, often under 34 inches tall",
  "standardbred": "The harness-racing trotter and pacer",
  "americansaddlebred": "High-stepping show horse of the American South",
  // MEDIUM
  "tennesseewalker": "Known for its smooth ‘running walk’ gait",
  "dutchwarmblood": "Top Dutch sport horse for dressage and jumping",
  "trakehner": "Refined East Prussian warmblood, oldest warmblood",
  "oldenburg": "German warmblood bred for elegant sport",
  "holsteiner": "One of Germany’s oldest warmblood breeds",
  "sellefrancais": "France’s premier show-jumping sport horse",
  "irishsporthorse": "Draft-cross bred for eventing and hunting",
  "clevelandbay": "England’s oldest breed, always solid bay",
  "suffolkpunch": "Chestnut English draft horse, rare today",
  "fellpony": "Dark, hardy pony from northern England",
  "dalespony": "Strong Pennine pony once used in lead mines",
  "highlandpony": "Scotland’s largest, hardiest native pony",
  "newforest": "Semi-wild pony of England’s New Forest",
  "exmoor": "Ancient British pony with a ‘mealy’ muzzle",
  "missourifoxtrotter": "Ozark breed with a smooth broken trot",
  "rockymountain": "Kentucky breed with a chocolate coat, flaxen mane",
  "pasofino": "Latin breed with a rapid, smooth four-beat gait",
  "peruvianpaso": "Peru’s smooth-gaited horse with rolling foreleg",
  "azteca": "Mexico’s national breed, Andalusian x Quarter",
  "criollo": "Tough South American ranch and endurance horse",
  "mangalarga": "Brazil’s national breed with a smooth ‘marcha’",
  "knabstrupper": "Danish breed with an Appaloosa-like spotted coat",
  "gelderland": "Elegant Dutch carriage horse breed",
  "dartmoor": "Small, hardy pony from Devon’s moorlands",
  "hackney": "Flashy carriage horse with a high-stepping trot",
  // HARD
  "lusitano": "Portugal’s baroque horse, used in bullfighting",
  "barb": "North African desert breed of great stamina",
  "orlovtrotter": "Russia’s famous grey harness-racing trotter",
  "dolehorse": "Norway’s strong draft-and-trotter valley horse",
  "finnhorse": "Finland’s only native breed, a versatile allrounder",
  "noriker": "Alpine draft breed from Austria, often spotted",
  "murgese": "Black Italian breed from the Puglia region",
  "maremmano": "Tuscan ranch horse ridden by Italian cowboys",
  "boulonnais": "White ‘marble’ draft horse of northern France",
  "breton": "Stocky chestnut draft breed from Brittany",
  "ardennes": "One of Europe’s oldest, heaviest draft breeds",
  "jutland": "Chestnut Danish draft horse with feathering",
  "przewalski": "The last truly wild horse, native to Mongolia",
  "kathiawari": "Indian desert breed with inward-curving ears",
  "dulmen": "Germany’s last semi-wild pony herd",
  "pottok": "Semi-wild pony of the Basque Pyrenees",
  "hucul": "Hardy mountain pony of the Carpathians",
  "konik": "Grey Polish pony resembling the wild tarpan",
  "shagya": "Hungarian Arabian-type bred for cavalry",
  "wielkopolski": "Polish warmblood for sport and light draft",
  "furioso": "Hungarian sport breed from two founding sires",
  "nonius": "Sturdy Hungarian carriage-and-farm breed",
  "kabardian": "Mountain horse of the Caucasus, sure-footed",
  "karabakh": "Azerbaijan’s golden national mountain horse",
  "budyonny": "Russian sport breed with a golden chestnut sheen",
  // IMPOSSIBLE
  "akhalteke": "Turkmen breed with a metallic golden coat",
  "marwari": "Indian breed with dramatic inward-curling ears",
  "falabella": "Argentine breed, one of the smallest horses",
  "fjord": "Dun Norwegian breed with a two-tone upright mane",
  "camargue": "Grey horse of France’s wild wetland delta",
  "sorraia": "Rare primitive Iberian horse with a dorsal stripe",
  "kladruber": "Baroque Czech carriage breed, one of the oldest",
  "nokota": "Feral breed from North Dakota’s badlands",
  "caspian": "Tiny ancient breed rediscovered in Iran",
  "americancreamdraft": "Only US draft breed, cream with amber eyes",
  "galiceno": "Small smooth-gaited horse from Mexico",
  "losino": "Rare black horse from northern Spain",
  "kinsky": "Golden-coated Czech horse bred for racing and cavalry",
  "giara": "Small wild horse of a plateau in Sardinia",
  "asturcon": "Ancient smooth-gaited pony of Asturias, Spain",
  "garrano": "Endangered mountain pony of northern Portugal",
  "misaki": "Protected feral horse of southern Japan",
  "tokara": "Very rare small horse from Japan’s islands",
  "kiso": "Japan’s rare native breed from Nagano",
  "yakutian": "Stocky Siberian horse that survives -70°C",
  "bhutia": "Small mountain horse of the Himalayas",
  "pleven": "Bulgarian chestnut sport horse bred at the Pleven stud",
  "sableisland": "Feral horses on a remote Canadian sandbar",
  "banker": "Feral breed of North Carolina’s Outer Banks",
  "floridacracker": "Colonial Spanish stock horse of Florida",
};
