// «Guess the Insect v2» — GuessSync · E-INSECTS2 · 100 striking/colorful true insects (25 per tier)
// Real photos (Wikimedia Commons). True insects only (6 legs) — no spiders/arachnids.
// Fully distinct from E38 (INSECTS) and the butterflies/moths episode (no Lepidoptera here).
// image: insects2/<slug>.jpg (objectFit cover) | VO: sfx/i2-<slug>.wav ("It's the <name>!")
export const INSECTS2 = [
  // ===== EASY (25) — most familiar of the set =====
  { slug: "crane-fly", name: "Crane Fly", level: "easy" },
  { slug: "fruit-fly", name: "Fruit Fly", level: "easy" },
  { slug: "aphid", name: "Aphid", level: "easy" },
  { slug: "paper-wasp", name: "Paper Wasp", level: "easy" },
  { slug: "carpenter-ant", name: "Carpenter Ant", level: "easy" },
  { slug: "army-ant", name: "Army Ant", level: "easy" },
  { slug: "emperor-dragonfly", name: "Emperor Dragonfly", level: "easy" },
  { slug: "blue-dasher", name: "Blue Dasher", level: "easy" },
  { slug: "chinese-mantis", name: "Chinese Mantis", level: "easy" },
  { slug: "colorado-potato-beetle", name: "Colorado Beetle", level: "easy" },
  { slug: "rose-chafer", name: "Rose Chafer", level: "easy" },
  { slug: "cockchafer", name: "Cockchafer", level: "easy" },
  { slug: "bluebottle-fly", name: "Bluebottle Fly", level: "easy" },
  { slug: "hissing-cockroach", name: "Hissing Cockroach", level: "easy" },
  { slug: "squash-bug", name: "Squash Bug", level: "easy" },
  { slug: "boxelder-bug", name: "Boxelder Bug", level: "easy" },
  { slug: "milkweed-bug", name: "Milkweed Bug", level: "easy" },
  { slug: "robber-fly", name: "Robber Fly", level: "easy" },
  { slug: "mud-dauber", name: "Mud Dauber", level: "easy" },
  { slug: "harvester-ant", name: "Harvester Ant", level: "easy" },
  { slug: "leafcutter-bee", name: "Leafcutter Bee", level: "easy" },
  { slug: "mason-bee", name: "Mason Bee", level: "easy" },
  { slug: "jewel-beetle", name: "Jewel Beetle", level: "easy" },
  { slug: "flesh-fly", name: "Flesh Fly", level: "easy" },
  { slug: "camel-cricket", name: "Camel Cricket", level: "easy" },

  // ===== MEDIUM (25) =====
  { slug: "european-mantis", name: "European Mantis", level: "medium" },
  { slug: "carolina-mantis", name: "Carolina Mantis", level: "medium" },
  { slug: "flame-skimmer", name: "Flame Skimmer", level: "medium" },
  { slug: "widow-skimmer", name: "Widow Skimmer", level: "medium" },
  { slug: "common-whitetail", name: "Common Whitetail", level: "medium" },
  { slug: "ebony-jewelwing", name: "Ebony Jewelwing", level: "medium" },
  { slug: "banded-demoiselle", name: "Banded Demoiselle", level: "medium" },
  { slug: "broad-bodied-chaser", name: "Broad-bodied Chaser", level: "medium" },
  { slug: "golden-ringed-dragonfly", name: "Golden-ringed Dragonfly", level: "medium" },
  { slug: "twelve-spotted-skimmer", name: "Twelve-spotted Skimmer", level: "medium" },
  { slug: "large-red-damselfly", name: "Large Red Damselfly", level: "medium" },
  { slug: "azure-damselfly", name: "Azure Damselfly", level: "medium" },
  { slug: "firebug", name: "Firebug", level: "medium" },
  { slug: "harlequin-bug", name: "Harlequin Bug", level: "medium" },
  { slug: "green-shield-bug", name: "Green Shield Bug", level: "medium" },
  { slug: "forest-bug", name: "Forest Bug", level: "medium" },
  { slug: "leaf-footed-bug", name: "Leaf-footed Bug", level: "medium" },
  { slug: "periodical-cicada", name: "Periodical Cicada", level: "medium" },
  { slug: "dog-day-cicada", name: "Dog-day Cicada", level: "medium" },
  { slug: "cardinal-beetle", name: "Cardinal Beetle", level: "medium" },
  { slug: "soldier-beetle", name: "Soldier Beetle", level: "medium" },
  { slug: "ground-beetle", name: "Ground Beetle", level: "medium" },
  { slug: "rove-beetle", name: "Rove Beetle", level: "medium" },
  { slug: "mealworm-beetle", name: "Mealworm Beetle", level: "medium" },
  { slug: "sawfly", name: "Sawfly", level: "medium" },

  // ===== HARD (25) =====
  { slug: "emerald-cockroach-wasp", name: "Jewel Wasp", level: "hard" },
  { slug: "ruby-tailed-wasp", name: "Ruby-tailed Wasp", level: "hard" },
  { slug: "great-black-wasp", name: "Great Black Wasp", level: "hard" },
  { slug: "spider-wasp", name: "Spider Wasp", level: "hard" },
  { slug: "bullet-ant", name: "Bullet Ant", level: "hard" },
  { slug: "weaver-ant", name: "Weaver Ant", level: "hard" },
  { slug: "trap-jaw-ant", name: "Trap-jaw Ant", level: "hard" },
  { slug: "honeypot-ant", name: "Honeypot Ant", level: "hard" },
  { slug: "bulldog-ant", name: "Bulldog Ant", level: "hard" },
  { slug: "orchid-bee", name: "Orchid Bee", level: "hard" },
  { slug: "sweat-bee", name: "Sweat Bee", level: "hard" },
  { slug: "wool-carder-bee", name: "Wool Carder Bee", level: "hard" },
  { slug: "devils-coach-horse", name: "Devil's Coach Horse", level: "hard" },
  { slug: "burying-beetle", name: "Burying Beetle", level: "hard" },
  { slug: "carrion-beetle", name: "Carrion Beetle", level: "hard" },
  { slug: "net-winged-beetle", name: "Net-winged Beetle", level: "hard" },
  { slug: "candystripe-leafhopper", name: "Candystripe Leafhopper", level: "hard" },
  { slug: "meadow-spittlebug", name: "Meadow Spittlebug", level: "hard" },
  { slug: "buffalo-treehopper", name: "Buffalo Treehopper", level: "hard" },
  { slug: "rainbow-scarab", name: "Rainbow Scarab", level: "hard" },
  { slug: "grapevine-beetle", name: "Grapevine Beetle", level: "hard" },
  { slug: "fig-beetle", name: "Fig Beetle", level: "hard" },
  { slug: "dogbane-beetle", name: "Dogbane Beetle", level: "hard" },
  { slug: "stalk-eyed-fly", name: "Stalk-eyed Fly", level: "hard" },
  { slug: "tsetse-fly", name: "Tsetse Fly", level: "hard" },

  // ===== IMPOSSIBLE (25) — obscure / exotic =====
  { slug: "rainbow-grasshopper", name: "Rainbow Grasshopper", level: "impossible" },
  { slug: "eastern-lubber", name: "Eastern Lubber", level: "impossible" },
  { slug: "elegant-grasshopper", name: "Elegant Grasshopper", level: "impossible" },
  { slug: "violin-mantis", name: "Violin Mantis", level: "impossible" },
  { slug: "dead-leaf-mantis", name: "Dead Leaf Mantis", level: "impossible" },
  { slug: "conehead-mantis", name: "Conehead Mantis", level: "impossible" },
  { slug: "budwing-mantis", name: "Budwing Mantis", level: "impossible" },
  { slug: "domino-cockroach", name: "Domino Cockroach", level: "impossible" },
  { slug: "deaths-head-cockroach", name: "Death's Head Cockroach", level: "impossible" },
  { slug: "cobalt-milkweed-beetle", name: "Cobalt Milkweed Beetle", level: "impossible" },
  { slug: "fiery-searcher", name: "Fiery Searcher", level: "impossible" },
  { slug: "diamond-weevil", name: "Diamond Weevil", level: "impossible" },
  { slug: "elephant-weevil", name: "Elephant Weevil", level: "impossible" },
  { slug: "red-palm-weevil", name: "Red Palm Weevil", level: "impossible" },
  { slug: "acorn-weevil", name: "Acorn Weevil", level: "impossible" },
  { slug: "elephant-beetle", name: "Elephant Beetle", level: "impossible" },
  { slug: "ox-beetle", name: "Ox Beetle", level: "impossible" },
  { slug: "hermit-beetle", name: "Hermit Beetle", level: "impossible" },
  { slug: "bee-beetle", name: "Bee Beetle", level: "impossible" },
  { slug: "fiddler-beetle", name: "Fiddler Beetle", level: "impossible" },
  { slug: "rainbow-leaf-beetle", name: "Rainbow Leaf Beetle", level: "impossible" },
  { slug: "lily-beetle", name: "Lily Beetle", level: "impossible" },
  { slug: "rosemary-beetle", name: "Rosemary Beetle", level: "impossible" },
  { slug: "halloween-pennant", name: "Halloween Pennant", level: "impossible" },
  { slug: "roseate-skimmer", name: "Roseate Skimmer", level: "impossible" },
];
export const INSECTS2_LEVELS = ["easy", "medium", "hard", "impossible"];
