// E104 «Guess the ZOOMED Insect» — GuessSync "What the Zoom" hard-mode.
// Reuses the EXACT E38 insect image set (insects/<slug>.jpg) and E38's INSECT_FACTS + in-<slug>.wav
// answer VOs (copied to inz-<slug>.wav — identical "It's the <name>!" line, zero new audio cost),
// but RE-TIERED by how hard each insect is to name from an EXTREME exoskeleton close-up crop
// (scale 3.0). Difficulty tracks CARAPACE/WING PATTERN & COLOR distinctiveness, NOT general fame:
// EASY = unmistakable pattern/color survives any tiny crop (Ladybug spots, Monarch's orange/black
// veining, Picasso Bug's geometric pattern, iridescent Jewel Scarab...). IMPOSSIBLE = plain dull
// brown/grey exoskeleton that gives no clue in a tiny crop.
// image: insects/<slug>.jpg | answer VO: sfx/inz-<slug>.wav (copied from E38's in-<slug>.wav)
export const INSECTZOOM = [
  // ===== EASY (25) =====
  { slug: "ladybug", name: "Ladybug", level: "easy" },
  { slug: "monarch-butterfly", name: "Monarch Butterfly", level: "easy" },
  { slug: "leaf-insect", name: "Leaf Insect", level: "easy" },
  { slug: "picasso-bug", name: "Picasso Bug", level: "easy" },
  { slug: "man-faced-stink-bug", name: "Man-faced Stink Bug", level: "easy" },
  { slug: "orchid-mantis", name: "Orchid Mantis", level: "easy" },
  { slug: "lanternfly", name: "Spotted Lanternfly", level: "easy" },
  { slug: "velvet-ant", name: "Velvet Ant", level: "easy" },
  { slug: "tarantula-hawk", name: "Tarantula Hawk", level: "easy" },
  { slug: "jewel-scarab", name: "Jewel Scarab", level: "easy" },
  { slug: "golden-tortoise-beetle", name: "Golden Tortoise Beetle", level: "easy" },
  { slug: "flamboyant-flower-beetle", name: "Flamboyant Flower Beetle", level: "easy" },
  { slug: "luna-moth", name: "Luna Moth", level: "easy" },
  { slug: "atlas-moth", name: "Atlas Moth", level: "easy" },
  { slug: "madagascan-sunset-moth", name: "Madagascan Sunset Moth", level: "easy" },
  { slug: "violin-beetle", name: "Violin Beetle", level: "easy" },
  { slug: "japanese-beetle", name: "Japanese Beetle", level: "easy" },
  { slug: "tiger-beetle", name: "Tiger Beetle", level: "easy" },
  { slug: "hoverfly", name: "Hoverfly", level: "easy" },
  { slug: "yellowjacket", name: "Yellowjacket", level: "easy" },
  { slug: "dragonfly", name: "Dragonfly", level: "easy" },
  { slug: "honey-bee", name: "Honey Bee", level: "easy" },
  { slug: "bumblebee", name: "Bumblebee", level: "easy" },
  { slug: "wasp", name: "Wasp", level: "easy" },
  { slug: "hornet", name: "Hornet", level: "easy" },
  // ===== MEDIUM (25) =====
  { slug: "firefly", name: "Firefly", level: "medium" },
  { slug: "damselfly", name: "Damselfly", level: "medium" },
  { slug: "lacewing", name: "Green Lacewing", level: "medium" },
  { slug: "katydid", name: "Katydid", level: "medium" },
  { slug: "rhinoceros-beetle", name: "Rhinoceros Beetle", level: "medium" },
  { slug: "silverfish", name: "Silverfish", level: "medium" },
  { slug: "assassin-bug", name: "Assassin Bug", level: "medium" },
  { slug: "stink-bug", name: "Stink Bug", level: "medium" },
  { slug: "dobsonfly", name: "Dobsonfly", level: "medium" },
  { slug: "scorpionfly", name: "Scorpionfly", level: "medium" },
  { slug: "owlfly", name: "Owlfly", level: "medium" },
  { slug: "mantidfly", name: "Mantidfly", level: "medium" },
  { slug: "planthopper", name: "Planthopper", level: "medium" },
  { slug: "leafhopper", name: "Leafhopper", level: "medium" },
  { slug: "treehopper", name: "Treehopper", level: "medium" },
  { slug: "cicada-killer", name: "Cicada Killer Wasp", level: "medium" },
  { slug: "ichneumon-wasp", name: "Ichneumon Wasp", level: "medium" },
  { slug: "potter-wasp", name: "Potter Wasp", level: "medium" },
  { slug: "bombardier-beetle", name: "Bombardier Beetle", level: "medium" },
  { slug: "blister-beetle", name: "Blister Beetle", level: "medium" },
  { slug: "longhorn-beetle", name: "Longhorn Beetle", level: "medium" },
  { slug: "giraffe-weevil", name: "Giraffe Weevil", level: "medium" },
  { slug: "goliath-beetle", name: "Goliath Beetle", level: "medium" },
  { slug: "frog-legged-leaf-beetle", name: "Frog-legged Leaf Beetle", level: "medium" },
  { slug: "devils-flower-mantis", name: "Devil's Flower Mantis", level: "medium" },
  // ===== HARD (25) =====
  { slug: "praying-mantis", name: "Praying Mantis", level: "hard" },
  { slug: "stag-beetle", name: "Stag Beetle", level: "hard" },
  { slug: "caterpillar", name: "Caterpillar", level: "hard" },
  { slug: "stick-insect", name: "Stick Insect", level: "hard" },
  { slug: "cicada", name: "Cicada", level: "hard" },
  { slug: "weevil", name: "Weevil", level: "hard" },
  { slug: "antlion", name: "Antlion", level: "hard" },
  { slug: "carpenter-bee", name: "Carpenter Bee", level: "hard" },
  { slug: "titan-beetle", name: "Titan Beetle", level: "hard" },
  { slug: "atlas-beetle", name: "Atlas Beetle", level: "hard" },
  { slug: "hercules-beetle", name: "Hercules Beetle", level: "hard" },
  { slug: "wheel-bug", name: "Wheel Bug", level: "hard" },
  { slug: "harlequin-beetle", name: "Harlequin Beetle", level: "hard" },
  { slug: "hickory-horned-devil", name: "Hickory Horned Devil", level: "hard" },
  { slug: "spiny-flower-mantis", name: "Spiny Flower Mantis", level: "hard" },
  { slug: "thorn-bug", name: "Thorn Bug", level: "hard" },
  { slug: "brazilian-treehopper", name: "Brazilian Treehopper", level: "hard" },
  { slug: "peanut-head-bug", name: "Peanut-head Bug", level: "hard" },
  { slug: "ghost-mantis", name: "Ghost Mantis", level: "hard" },
  { slug: "mole-cricket", name: "Mole Cricket", level: "hard" },
  { slug: "grasshopper", name: "Grasshopper", level: "hard" },
  { slug: "locust", name: "Locust", level: "hard" },
  { slug: "earwig", name: "Earwig", level: "hard" },
  { slug: "moth", name: "Moth", level: "hard" },
  { slug: "giant-water-bug", name: "Giant Water Bug", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { slug: "dung-beetle", name: "Dung Beetle", level: "impossible" },
  { slug: "ant", name: "Ant", level: "impossible" },
  { slug: "housefly", name: "Housefly", level: "impossible" },
  { slug: "mosquito", name: "Mosquito", level: "impossible" },
  { slug: "cricket", name: "Cricket", level: "impossible" },
  { slug: "termite", name: "Termite", level: "impossible" },
  { slug: "flea", name: "Flea", level: "impossible" },
  { slug: "cockroach", name: "Cockroach", level: "impossible" },
  { slug: "water-strider", name: "Water Strider", level: "impossible" },
  { slug: "mayfly", name: "Mayfly", level: "impossible" },
  { slug: "horsefly", name: "Horsefly", level: "impossible" },
  { slug: "fire-ant", name: "Fire Ant", level: "impossible" },
  { slug: "leafcutter-ant", name: "Leafcutter Ant", level: "impossible" },
  { slug: "june-beetle", name: "June Beetle", level: "impossible" },
  { slug: "click-beetle", name: "Click Beetle", level: "impossible" },
  { slug: "bedbug", name: "Bedbug", level: "impossible" },
  { slug: "head-louse", name: "Head Louse", level: "impossible" },
  { slug: "caddisfly", name: "Caddisfly", level: "impossible" },
  { slug: "stonefly", name: "Stonefly", level: "impossible" },
  { slug: "snakefly", name: "Snakefly", level: "impossible" },
  { slug: "froghopper", name: "Froghopper", level: "impossible" },
  { slug: "darkling-beetle", name: "Darkling Beetle", level: "impossible" },
  { slug: "diving-beetle", name: "Diving Beetle", level: "impossible" },
  { slug: "whirligig-beetle", name: "Whirligig Beetle", level: "impossible" },
  { slug: "glowworm", name: "Glowworm", level: "impossible" },
];
