// E-INSECTS2 «Guess the Insect v2» — one true ≤70-char fact per insect, shown on the reveal.
export const INSECTS2_FACTS = {
  // ===== EASY =====
  "crane-fly": "Despite its size, the adult barely feeds and does not bite.",
  "fruit-fly": "A lab favorite that helped unlock the secrets of genetics.",
  "aphid": "Females can be born already pregnant with their own young.",
  "paper-wasp": "It builds an open, papery nest from chewed wood fibers.",
  "carpenter-ant": "It tunnels through wood but eats no wood at all.",
  "army-ant": "Huge colonies march in raids instead of building nests.",
  "emperor-dragonfly": "One of the largest, it hunts prey right on the wing.",
  "blue-dasher": "This small pointer perches with wings angled downward.",
  "chinese-mantis": "It can grab and eat insects larger than itself.",
  "colorado-potato-beetle": "A striped pest that devastates potato crops worldwide.",
  "rose-chafer": "Its metallic green body shines in the summer sun.",
  "cockchafer": "Once so common its swarms could darken the evening sky.",
  "bluebottle-fly": "Its shiny blue body is drawn to meat and carrion.",
  "hissing-cockroach": "It hisses by forcing air through breathing holes.",
  "squash-bug": "A garden pest that attacks squash and pumpkin plants.",
  "boxelder-bug": "Black-and-red bugs that gather on warm walls in fall.",
  "milkweed-bug": "Its bold orange warns birds that it tastes foul.",
  "robber-fly": "A fierce hunter that catches other insects in midair.",
  "mud-dauber": "This wasp builds nests from little tubes of mud.",
  "harvester-ant": "It gathers seeds and stores them in the nest.",
  "leafcutter-bee": "It snips neat circles of leaf to line its nest.",
  "mason-bee": "It seals its nest cells with mud, like a mason.",
  "jewel-beetle": "Its shell glitters like polished metal and gems.",
  "flesh-fly": "It gives birth to live maggots instead of eggs.",
  "camel-cricket": "Humpbacked and wingless, it thrives in dark, damp caves.",

  // ===== MEDIUM =====
  "european-mantis": "It is the official state insect of Connecticut.",
  "carolina-mantis": "The female is often too heavy to fly well.",
  "flame-skimmer": "The male glows a bright fiery orange all over.",
  "widow-skimmer": "Dark bands on clear wings give it a mourning look.",
  "common-whitetail": "The male's chalky-white tail flags his territory.",
  "ebony-jewelwing": "This damselfly flashes metallic green over streams.",
  "banded-demoiselle": "The male's wings carry a dark blue-black band.",
  "broad-bodied-chaser": "Its wide, flat body makes it look almost stout.",
  "golden-ringed-dragonfly": "Black with yellow rings, it is Britain's longest.",
  "twelve-spotted-skimmer": "Its wings bear twelve neat dark spots.",
  "large-red-damselfly": "Often the first damselfly seen each spring.",
  "azure-damselfly": "Slim and sky-blue, it hovers near still ponds.",
  "firebug": "Its bright red-and-black back warns off predators.",
  "harlequin-bug": "Boldly patterned, it is a pest of cabbage crops.",
  "green-shield-bug": "Shaped like a shield, it turns bronze in autumn.",
  "forest-bug": "Its shoulders end in two blunt, square corners.",
  "leaf-footed-bug": "Its hind legs widen into little leaf-like flaps.",
  "periodical-cicada": "It stays underground for 13 or 17 whole years.",
  "dog-day-cicada": "Its buzzing song marks the hottest days of summer.",
  "cardinal-beetle": "Its flat body is a vivid, cardinal-red color.",
  "soldier-beetle": "It is a helpful hunter of aphids and pests.",
  "ground-beetle": "A fast night hunter that rarely takes to flight.",
  "rove-beetle": "It curls its tail up like a scorpion when alarmed.",
  "mealworm-beetle": "Its larva, the mealworm, is farmed for animal feed.",
  "sawfly": "Named for the saw-like blade it uses to slit stems.",

  // ===== HARD =====
  "emerald-cockroach-wasp": "It turns a cockroach into a living food supply.",
  "ruby-tailed-wasp": "Its jewel-bright body sparkles red, green and gold.",
  "great-black-wasp": "It stocks its burrow with paralyzed katydids.",
  "spider-wasp": "It hunts spiders to feed its developing young.",
  "bullet-ant": "Its sting is rated the most painful of any insect.",
  "weaver-ant": "Workers stitch leaves together using their own silk.",
  "trap-jaw-ant": "Its jaws snap shut faster than almost any animal.",
  "honeypot-ant": "Some workers swell into living jars of sweet nectar.",
  "bulldog-ant": "One of the largest ants, with a fierce sting.",
  "orchid-bee": "Males gather flower scents to attract a mate.",
  "sweat-bee": "Drawn to sweat, some shine a brilliant metallic green.",
  "wool-carder-bee": "It scrapes plant fuzz to line and pad its nest.",
  "devils-coach-horse": "Threatened, it rears its tail and opens its jaws.",
  "burying-beetle": "A pair buries a small carcass to feed their young.",
  "carrion-beetle": "It helps recycle nature by feeding on dead animals.",
  "net-winged-beetle": "Ridged wing covers look like a fine woven net.",
  "candystripe-leafhopper": "Bright red and blue-green stripes make it glow.",
  "meadow-spittlebug": "Its young hide inside a blob of frothy foam.",
  "buffalo-treehopper": "Its green, humped back looks like a tiny buffalo.",
  "rainbow-scarab": "A dung beetle that gleams in metallic rainbow hues.",
  "grapevine-beetle": "A large spotted beetle drawn to grape leaves.",
  "fig-beetle": "This big green beetle buzzes loudly as it flies.",
  "dogbane-beetle": "Its shell shimmers gold, green and blue at once.",
  "stalk-eyed-fly": "Its eyes sit on long stalks wider than its body.",
  "tsetse-fly": "In Africa it can spread the deadly sleeping sickness.",

  // ===== IMPOSSIBLE =====
  "rainbow-grasshopper": "Its bold colors warn that it tastes bad.",
  "eastern-lubber": "Big and clumsy, it can barely fly at all.",
  "elegant-grasshopper": "Bright warning colors hint that it is toxic.",
  "violin-mantis": "Its slender body is shaped much like a violin.",
  "dead-leaf-mantis": "It mimics a shriveled brown leaf to hide.",
  "conehead-mantis": "A pointed crown tops its narrow, twiggy body.",
  "budwing-mantis": "Its short wings look like tiny unopened buds.",
  "domino-cockroach": "Black with white spots, it looks like a domino.",
  "deaths-head-cockroach": "A skull-like mark sits on its shield.",
  "cobalt-milkweed-beetle": "It shines an intense metallic cobalt blue.",
  "fiery-searcher": "A big iridescent beetle that hunts caterpillars.",
  "diamond-weevil": "Its black shell is dusted with green-blue scales.",
  "elephant-weevil": "Its long snout curves down like a trunk.",
  "red-palm-weevil": "A serious pest that bores into and kills palms.",
  "acorn-weevil": "Its long snout drills into acorns to lay eggs.",
  "elephant-beetle": "Males carry huge horns and are covered in fuzz.",
  "ox-beetle": "The male bears three horns on its broad head.",
  "hermit-beetle": "It lives hidden inside old, hollow tree trunks.",
  "bee-beetle": "Furry and striped, it mimics a bumblebee.",
  "fiddler-beetle": "Green swirls on its back look like violins.",
  "rainbow-leaf-beetle": "A rare beetle streaked in metallic rainbow bands.",
  "lily-beetle": "Bright scarlet, it is a dreaded pest of lilies.",
  "rosemary-beetle": "Metallic green-and-purple stripes cover its back.",
  "halloween-pennant": "Orange, banded wings flag it like festive bunting.",
  "roseate-skimmer": "The mature male turns a striking rosy pink.",
};
