// E167 emoji-instrument facts — one verified <=70-char fact per instrument, shown on reveal.
export const INSTRUMENT_EMOJI_FACTS = {
  // EASY
  "guitar": "A plucked string instrument, usually with six strings.",
  "piano": "A keyboard whose keys drive hammers that strike steel strings.",
  "violin": "The smallest, highest-pitched member of the bowed strings.",
  "drums": "A drum kit groups drums and cymbals for one seated player.",
  "trumpet": "The highest brass instrument, with three valves.",
  "saxophone": "A brass-bodied reed woodwind invented by Adolphe Sax.",
  "flute": "A woodwind sounded by blowing across a side hole, no reed.",
  "banjo": "A plucked string with a round skin head, key to bluegrass.",
  "accordion": "A bellows squeezebox with a piano or button keyboard.",
  "maracas": "Shaken rattles filled with beads or seeds, from Latin America.",
  "congas": "Tall, narrow Afro-Cuban hand drums played standing.",
  "harp": "A large frame of strings plucked with both hands.",
  "cello": "A large bowed string held between the knees, deeper than viola.",
  "harmonica": "A pocket free-reed wind played by breathing in and out.",
  "xylophone": "Tuned wooden bars struck with mallets.",
  "tambourine": "A small frame drum ringed with jingling metal discs.",
  "trombone": "A brass instrument whose pitch is set by a sliding tube.",
  "tuba": "The largest, lowest-pitched brass instrument.",
  "ukulele": "A small four-string guitar from Hawaii.",
  "cymbals": "Two metal plates clashed together for a crash.",
  "triangle": "A steel rod bent into a triangle, struck with a beater.",
  "bass-guitar": "A low-pitched guitar, usually with four thick strings.",
  "bongos": "A joined pair of small Afro-Cuban hand drums.",
  "organ": "A keyboard that sounds pipes driven by pushed air.",
  "recorder": "A simple end-blown flute widely taught in schools.",

  // MEDIUM
  "clarinet": "A single-reed woodwind with a cylindrical bore.",
  "viola": "A bowed string slightly larger and lower than the violin.",
  "double-bass": "The largest, lowest bowed string in the orchestra.",
  "french-horn": "Coiled brass tubing played with a hand in the bell.",
  "mandolin": "A small pear-shaped plucked string with paired courses.",
  "bagpipes": "Reed pipes fed by air from a squeezed bag.",
  "gong": "A large hanging metal disc struck with a mallet.",
  "cowbell": "A clapperless bell struck with a stick as percussion.",
  "djembe": "A goblet-shaped West African hand drum.",
  "steel-drum": "A tuned pan hammered from an oil barrel, born in Trinidad.",
  "marimba": "Wooden bars over resonators, larger and mellower than xylophone.",
  "glockenspiel": "Tuned metal bars struck with mallets, bright and bell-like.",
  "timpani": "Large tunable kettledrums played in the orchestra.",
  "synthesizer": "An electronic keyboard that generates and shapes sound.",
  "electric-guitar": "A guitar with pickups that amplify string vibration.",
  "sitar": "A long-necked Indian plucked lute with sympathetic strings.",
  "didgeridoo": "A long drone pipe of Aboriginal Australians.",
  "kazoo": "A toy that buzzes when you hum into its membrane.",
  "ocarina": "A small egg-shaped vessel flute with finger holes.",
  "pan-flute": "Tuned pipes of different lengths bound side by side.",
  "castanets": "Paired shell-shaped clappers clicked in the hand.",
  "snare-drum": "A drum with wires under the head, key to marching bands.",
  "bass-drum": "The largest, deepest drum, keeping the beat's boom.",
  "bugle": "A valveless brass horn sounded by lip changes alone.",
  "harpsichord": "A keyboard that plucks its strings, ancestor of the piano.",

  // HARD
  "oboe": "A double-reed woodwind with a bright, nasal tone.",
  "bassoon": "A large, low double-reed woodwind of folded wooden tube.",
  "piccolo": "The smallest, highest-pitched flute.",
  "dulcimer": "A trapezoid of strings struck with small hammers.",
  "zither": "A flat box of many strings plucked or strummed on the lap.",
  "lute": "A pear-backed plucked string of Renaissance Europe.",
  "lyre": "An ancient Greek harp with strings across a U-frame.",
  "bouzouki": "A long-necked Greek plucked string with a bright ring.",
  "balalaika": "A triangular-bodied Russian plucked string.",
  "vibraphone": "Metal bars with motor-driven vibrato and a sustain pedal.",
  "celesta": "A keyboard striking metal plates for a bell-like chime.",
  "theremin": "An electronic instrument played by waving hands in the air.",
  "harmonium": "A hand-pumped reed organ common in Indian music.",
  "concertina": "A small hexagonal squeezebox with buttons on each end.",
  "melodica": "A keyboard sounded by blowing through a mouthpiece.",
  "kalimba": "A thumb piano of metal tines plucked by the thumbs.",
  "autoharp": "A chorded zither strummed while bars damp unwanted strings.",
  "hurdy-gurdy": "A string instrument sounded by a hand-cranked rosined wheel.",
  "fife": "A small, shrill flute paired with drums in marching music.",
  "jaw-harp": "A tiny frame twanged against the teeth to shape the tone.",
  "tabla": "A tuned pair of Indian hand drums of classical music.",
  "cajon": "A wooden box drum the player sits on and strikes.",
  "handpan": "A UFO-shaped steel drum played with the hands.",
  "bodhran": "An Irish handheld frame drum struck with a double-ended beater.",
  "sousaphone": "A coiled marching tuba wrapped around the player's body.",

  // IMPOSSIBLE
  "erhu": "A Chinese two-string fiddle bowed between the strings.",
  "guzheng": "A long Chinese zither of many plucked strings over bridges.",
  "pipa": "A pear-shaped Chinese four-string lute held upright.",
  "dizi": "A Chinese bamboo transverse flute with a buzzing membrane.",
  "sheng": "A Chinese mouth organ of vertical free-reed pipes.",
  "guqin": "An ancient Chinese seven-string fretless zither.",
  "koto": "A Japanese zither of 13 silk strings over movable bridges.",
  "shamisen": "A Japanese three-string fretless lute played with a plectrum.",
  "shakuhachi": "A Japanese end-blown bamboo flute used in meditation.",
  "taiko": "Large Japanese barrel drums played with heavy sticks.",
  "sarod": "A fretless Indian plucked lute with a bright metal fingerboard.",
  "veena": "An ancient South Indian plucked string of classical music.",
  "santoor": "A hammered box zither from Kashmir and Persia.",
  "mridangam": "A South Indian two-headed barrel drum of Carnatic music.",
  "oud": "A pear-shaped Arabic fretless lute, ancestor of the lute.",
  "qanun": "A Middle Eastern plucked box zither with many strings.",
  "ney": "An ancient Middle Eastern end-blown reed flute.",
  "duduk": "An Armenian double-reed of apricot wood with a mournful tone.",
  "kora": "A West African 21-string harp-lute with a gourd body.",
  "mbira": "A Zimbabwean thumb piano of metal tines on a wooden board.",
  "talking-drum": "A West African hourglass drum whose pitch bends like speech.",
  "balafon": "A West African wooden xylophone with gourd resonators.",
  "berimbau": "A Brazilian musical bow with a gourd, used in capoeira.",
  "charango": "A small Andean lute once made from an armadillo shell.",
  "bandoneon": "A button squeezebox at the heart of Argentine tango.",
};
