// E206 instrument-emoji facts — one true <=70-char fact per instrument, shown on reveal.
export const INSTRUMENT_EMOJI_2_FACTS = {
  // EASY
  "keytar": "A keyboard synthesizer built to be worn and played like a guitar.",
  "whistle": "A small pealess or pea whistle that makes sound by blown air.",
  "wind-chimes": "Hanging tubes or rods that chime softly when moved by wind.",
  "sleigh-bells": "Small jingling bells traditionally strapped to a horse harness.",
  "rain-stick": "A hollow stick filled with beads that mimics falling rain.",
  "wood-block": "A hollow wooden block struck with a stick for a sharp click.",
  "dj-turntable": "A rotating platform used to spin and scratch vinyl records.",
  "drum-machine": "An electronic device that programs and plays drum patterns.",
  "handbell": "A hand-held bell rung by swinging, often played in choirs.",
  "tuning-fork": "A two-pronged metal fork that rings a fixed reference pitch.",
  "slide-whistle": "A whistle with a sliding piston that bends its pitch up and down.",
  "tin-whistle": "A simple six-holed metal fipple flute common in Irish folk music.",
  "tomtom-drum": "A cylindrical drum without snares, used in kits and orchestras.",
  "claves": "A pair of short wooden sticks struck together in Latin music.",
  "guiro": "A ridged gourd or tube scraped with a stick for a rasping sound.",
  "tubular-bells": "Tuned metal tubes hung in a frame and struck with a mallet.",
  "vuvuzela": "A long plastic horn blown to produce one loud droning note.",
  "cabasa": "A gourd wrapped in a beaded steel chain, twisted for a shaker sound.",
  "timbales": "Shallow single-headed Cuban drums played standing with sticks.",
  "darbuka": "A goblet-shaped hand drum common across the Middle East.",
  "riq": "A small tambourine with cymbals, central to Arabic music.",
  "vibraslap": "A rattling percussion tool with a wooden ball and metal teeth.",
  "flexatone": "A metal sheet shaken so beaters strike it for a wavering tone.",
  "washtub-bass": "A homemade bass made from a tub, a stick, and a taut string.",
  "steel-tongue-drum": "A steel drum cut with tongues that ring melodic notes when tapped.",

  // MEDIUM
  "appalachian-dulcimer": "A fretted lap instrument central to Appalachian folk music.",
  "melodeon": "A small button accordion popular in English and French folk music.",
  "mellotron": "A keyboard that plays back pre-recorded tape sounds of instruments.",
  "hammond-organ": "An electric organ famous for its spinning Leslie speaker sound.",
  "clavichord": "A quiet Renaissance keyboard where metal blades strike the strings.",
  "english-horn": "A double-reed woodwind, lower and mellower than the oboe.",
  "bass-clarinet": "A larger clarinet pitched an octave below the standard clarinet.",
  "contrabassoon": "The lowest-pitched double-reed woodwind in the orchestra.",
  "alphorn": "A very long wooden horn used by Swiss herders in the Alps.",
  "wagner-tuba": "A brass horn Richard Wagner designed for his Ring Cycle operas.",
  "mellophone": "A brass marching band instrument that stands in for the French horn.",
  "resonator-guitar": "A guitar with metal cones inside the body to amplify its sound.",
  "pedal-steel-guitar": "A steel guitar on legs with foot pedals that bend chords.",
  "lap-steel-guitar": "A guitar played flat on the lap with a metal slide bar.",
  "nyckelharpa": "A Swedish keyed fiddle whose keys press the strings while bowed.",
  "cimbalom": "A large hammered dulcimer struck with mallets, key to Hungarian music.",
  "hang-drum": "A UFO-shaped steel instrument played by hand, invented in Switzerland.",
  "log-drum": "A hollowed wooden log slit and struck to produce deep tones.",
  "frame-drum": "A shallow drum whose head is wider than its frame's depth.",
  "udu": "A Nigerian clay pot drum played by hitting its body and opening.",
  "doumbek": "An Egyptian goblet drum played with fingers and palm slaps.",
  "cuica": "A Brazilian friction drum nicknamed the laughing gorilla drum.",
  "angklung": "A shaken bamboo rattle tuned to a note, from West Java, Indonesia.",
  "marimbula": "A large Caribbean box lamellophone plucked to play bass lines.",
  "diddley-bow": "A one-string instrument nailed to a board, an early blues tool.",

  // HARD
  "domra": "A round-bodied Russian folk lute played with a plectrum.",
  "saz": "A long-necked Turkish lute central to Anatolian folk music.",
  "dombra": "A two-stringed Kazakh lute plucked in traditional steppe music.",
  "setar": "A small four-stringed Persian lute plucked with the fingernail.",
  "tar-persian": "A waisted double-bowled long-necked lute from Iran and the Caucasus.",
  "tanpura": "A drone lute that hums a steady pitch under Indian classical music.",
  "dholak": "A two-headed hand drum widely used in North Indian folk music.",
  "dhol": "A large barrel drum played with sticks at South Asian celebrations.",
  "ghatam": "A clay pot played by hand in South Indian Carnatic music.",
  "kanjira": "A small South Indian frame drum, traditionally lizard-skinned.",
  "shehnai": "A double-reed horn played at Indian weddings and ceremonies.",
  "uilleann-pipes": "Irish bagpipes inflated by a bellows pumped with the elbow.",
  "hardanger-fiddle": "A Norwegian fiddle with extra sympathetic strings beneath the bow.",
  "psaltery": "An ancient plucked zither, ancestor to the harpsichord's strings.",
  "crumhorn": "A curved Renaissance reed pipe with a buzzing, capped sound.",
  "shawm": "A loud medieval double-reed horn, ancestor of the oboe.",
  "sackbut": "An early trombone with a narrower bore and softer tone.",
  "viola-da-gamba": "A bowed string instrument held between the legs, its name means leg.",
  "theorbo": "A very long-necked lute with extra bass strings off the fretboard.",
  "vielle": "A medieval bowed fiddle, ancestor of the modern violin family.",
  "serpent": "An S-shaped brass bass horn named for its snaking wooden body.",
  "rebab": "A spike fiddle bowed upright, found across the Middle East and Asia.",
  "kamancheh": "A Persian spike fiddle played upright and rested on the knee.",
  "morin-khuur": "A Mongolian horsehead fiddle carved with a horse's head on top.",
  "sarangi": "A short-necked Indian fiddle prized for mimicking the human voice.",

  // IMPOSSIBLE
  "saron": "A Javanese gamelan metallophone struck with a wooden mallet.",
  "bonang": "A set of small pot gongs arranged in rows, used in gamelan.",
  "rebana": "A frame drum used in Islamic devotional music across Southeast Asia.",
  "kacapi": "A plucked zither central to Sundanese music in West Java.",
  "sasando": "An Indonesian tube zither resonated inside a dried palm leaf.",
  "khaen": "A Laotian mouth organ made of bamboo pipes bound together.",
  "dan-bau": "A Vietnamese one-string zither that bends pitch with a lever.",
  "dan-tranh": "A 16-string Vietnamese zither plucked with fingerpicks.",
  "yangqin": "A Chinese hammered dulcimer struck with light bamboo beaters.",
  "ruan": "A Chinese plucked lute with a round, moon-shaped body.",
  "liuqin": "A small high-pitched Chinese lute shaped like a willow leaf.",
  "banhu": "A Chinese bowed fiddle with a coconut-shell soundbox.",
  "gaohu": "A high-pitched cousin of the erhu, common in Cantonese music.",
  "paixiao": "An ancient Chinese panpipe made of graduated bamboo tubes.",
  "xun": "An egg-shaped Chinese clay vessel flute thousands of years old.",
  "hichiriki": "A small, piercing Japanese double-reed pipe used in court music.",
  "taepyeongso": "A loud Korean conical reed horn played in folk and military bands.",
  "gayageum": "A 12-string plucked Korean zither, the nation's iconic instrument.",
  "geomungo": "A six-string Korean zither plucked with a short bamboo stick.",
  "haegeum": "A two-string Korean fiddle played upright on the knee.",
  "piri": "A cylindrical Korean double-reed pipe with a big, buzzing reed.",
  "janggu": "An hourglass-shaped Korean drum struck on two different heads.",
  "gusli": "An ancient Russian plucked zither, an ancestor of folk harps.",
  "kobza": "A round-bodied Ukrainian lute, ancestor of the modern bandura.",
  "dutar": "A two-stringed Central Asian long-necked lute, its name means two.",
};
