// E206 «Guess the Musical Instrument by Emoji 2» — 100 instruments · 25/tier
// VO: sfx/e206-<id>.wav
export const INSTRUMENT_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "keytar", title: "Keytar", emojis: "🎹🎸", level: "easy" },
  { id: "whistle", title: "Whistle", emojis: "👄💨", level: "easy" },
  { id: "wind-chimes", title: "Wind Chimes", emojis: "🎐🌬", level: "easy" },
  { id: "sleigh-bells", title: "Sleigh Bells", emojis: "🛷🔔", level: "easy" },
  { id: "rain-stick", title: "Rain Stick", emojis: "🌧🪵", level: "easy" },
  { id: "wood-block", title: "Wood Block", emojis: "🪵🔨", level: "easy" },
  { id: "dj-turntable", title: "DJ Turntable", emojis: "🎧💿", level: "easy" },
  { id: "drum-machine", title: "Drum Machine", emojis: "🥁🤖", level: "easy" },
  { id: "handbell", title: "Handbell", emojis: "🔔✋", level: "easy" },
  { id: "tuning-fork", title: "Tuning Fork", emojis: "🍴🎶", level: "easy" },
  { id: "slide-whistle", title: "Slide Whistle", emojis: "🎶↔", level: "easy" },
  { id: "tin-whistle", title: "Tin Whistle", emojis: "🪈☘", level: "easy" },
  { id: "tomtom-drum", title: "Tom-tom Drum", emojis: "🥁🎯", level: "easy" },
  { id: "claves", title: "Claves", emojis: "🪵🥢", level: "easy" },
  { id: "guiro", title: "Güiro", emojis: "🎶🍈", level: "easy" },
  { id: "tubular-bells", title: "Tubular Bells", emojis: "🔔📏", level: "easy" },
  { id: "vuvuzela", title: "Vuvuzela", emojis: "📯⚽", level: "easy" },
  { id: "cabasa", title: "Cabasa", emojis: "🎶⛓", level: "easy" },
  { id: "timbales", title: "Timbales", emojis: "🥁🥢", level: "easy" },
  { id: "darbuka", title: "Darbuka", emojis: "🥁🏺", level: "easy" },
  { id: "riq", title: "Riq", emojis: "🥁🌙", level: "easy" },
  { id: "vibraslap", title: "Vibraslap", emojis: "🎶🦷", level: "easy" },
  { id: "flexatone", title: "Flexatone", emojis: "🎶🥄", level: "easy" },
  { id: "washtub-bass", title: "Washtub Bass", emojis: "🪣🎵", level: "easy" },
  { id: "steel-tongue-drum", title: "Steel Tongue Drum", emojis: "🛢🎶", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "appalachian-dulcimer", title: "Appalachian Dulcimer", emojis: "🎻🏔", level: "medium" },
  { id: "melodeon", title: "Melodeon", emojis: "🪗🌾", level: "medium" },
  { id: "mellotron", title: "Mellotron", emojis: "🎹📼", level: "medium" },
  { id: "hammond-organ", title: "Hammond Organ", emojis: "🎹🌀", level: "medium" },
  { id: "clavichord", title: "Clavichord", emojis: "🎹🕰", level: "medium" },
  { id: "english-horn", title: "English Horn", emojis: "🪈🎩", level: "medium" },
  { id: "bass-clarinet", title: "Bass Clarinet", emojis: "🎷⬇", level: "medium" },
  { id: "contrabassoon", title: "Contrabassoon", emojis: "🪈⬇", level: "medium" },
  { id: "alphorn", title: "Alphorn", emojis: "📯🏔", level: "medium" },
  { id: "wagner-tuba", title: "Wagner Tuba", emojis: "📯🐲", level: "medium" },
  { id: "mellophone", title: "Mellophone", emojis: "📯👣", level: "medium" },
  { id: "resonator-guitar", title: "Resonator Guitar", emojis: "🎸🛢", level: "medium" },
  { id: "pedal-steel-guitar", title: "Pedal Steel Guitar", emojis: "🎸🦶", level: "medium" },
  { id: "lap-steel-guitar", title: "Lap Steel Guitar", emojis: "🎸🎚", level: "medium" },
  { id: "nyckelharpa", title: "Nyckelharpa", emojis: "🎻🔑", level: "medium" },
  { id: "cimbalom", title: "Cimbalom", emojis: "🎹🥢", level: "medium" },
  { id: "hang-drum", title: "Hang Drum", emojis: "🛸🎶", level: "medium" },
  { id: "log-drum", title: "Log Drum", emojis: "🪵🥁", level: "medium" },
  { id: "frame-drum", title: "Frame Drum", emojis: "🥁⭕", level: "medium" },
  { id: "udu", title: "Udu", emojis: "🏺🎵", level: "medium" },
  { id: "doumbek", title: "Doumbek", emojis: "🏺🌙", level: "medium" },
  { id: "cuica", title: "Cuica", emojis: "🐵🥁", level: "medium" },
  { id: "angklung", title: "Angklung", emojis: "🎋🎶", level: "medium" },
  { id: "marimbula", title: "Marímbula", emojis: "🎹📦", level: "medium" },
  { id: "diddley-bow", title: "Diddley Bow", emojis: "🪵🧵", level: "medium" },

  // ===== HARD (25) =====
  { id: "domra", title: "Domra", emojis: "🎻🪆", level: "hard" },
  { id: "saz", title: "Saz", emojis: "🪕🌙", level: "hard" },
  { id: "dombra", title: "Dombra", emojis: "🪕🐎", level: "hard" },
  { id: "setar", title: "Setar", emojis: "🎸🌙", level: "hard" },
  { id: "tar-persian", title: "Tar", emojis: "🎸🐫", level: "hard" },
  { id: "tanpura", title: "Tanpura", emojis: "🎻🕉", level: "hard" },
  { id: "dholak", title: "Dholak", emojis: "🪘🎶", level: "hard" },
  { id: "dhol", title: "Dhol", emojis: "🥁🎉", level: "hard" },
  { id: "ghatam", title: "Ghatam", emojis: "🏺🖐", level: "hard" },
  { id: "kanjira", title: "Kanjira", emojis: "🥁🦎", level: "hard" },
  { id: "shehnai", title: "Shehnai", emojis: "🪈💒", level: "hard" },
  { id: "uilleann-pipes", title: "Uilleann Pipes", emojis: "🪗☘", level: "hard" },
  { id: "hardanger-fiddle", title: "Hardanger Fiddle", emojis: "🎻❄", level: "hard" },
  { id: "psaltery", title: "Psaltery", emojis: "🎼🪶", level: "hard" },
  { id: "crumhorn", title: "Crumhorn", emojis: "🪈🪝", level: "hard" },
  { id: "shawm", title: "Shawm", emojis: "🪈🔊", level: "hard" },
  { id: "sackbut", title: "Sackbut", emojis: "📯🕰", level: "hard" },
  { id: "viola-da-gamba", title: "Viola da Gamba", emojis: "🎻🦵", level: "hard" },
  { id: "theorbo", title: "Theorbo", emojis: "🪕📏", level: "hard" },
  { id: "vielle", title: "Vielle", emojis: "🎻🏰", level: "hard" },
  { id: "serpent", title: "Serpent", emojis: "📯🐍", level: "hard" },
  { id: "rebab", title: "Rebab", emojis: "🎻🐫", level: "hard" },
  { id: "kamancheh", title: "Kamancheh", emojis: "🎻⬆", level: "hard" },
  { id: "morin-khuur", title: "Morin Khuur", emojis: "🎻🐴", level: "hard" },
  { id: "sarangi", title: "Sarangi", emojis: "🎻🗣", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "saron", title: "Saron", emojis: "🎹🪵", level: "impossible" },
  { id: "bonang", title: "Bonang", emojis: "🔔🔨", level: "impossible" },
  { id: "rebana", title: "Rebana", emojis: "🥁🕌", level: "impossible" },
  { id: "kacapi", title: "Kacapi", emojis: "🪕🎋", level: "impossible" },
  { id: "sasando", title: "Sasando", emojis: "🎼🌴", level: "impossible" },
  { id: "khaen", title: "Khaen", emojis: "🪗🎋", level: "impossible" },
  { id: "dan-bau", title: "Dan Bau", emojis: "🎻🪡", level: "impossible" },
  { id: "dan-tranh", title: "Dan Tranh", emojis: "🎼🎏", level: "impossible" },
  { id: "yangqin", title: "Yangqin", emojis: "🎹🎋", level: "impossible" },
  { id: "ruan", title: "Ruan", emojis: "🪕🌕", level: "impossible" },
  { id: "liuqin", title: "Liuqin", emojis: "🪕🍃", level: "impossible" },
  { id: "banhu", title: "Banhu", emojis: "🎻🥥", level: "impossible" },
  { id: "gaohu", title: "Gaohu", emojis: "🎻📈", level: "impossible" },
  { id: "paixiao", title: "Paixiao", emojis: "🪈🀄", level: "impossible" },
  { id: "xun", title: "Xun", emojis: "🥚🎶", level: "impossible" },
  { id: "hichiriki", title: "Hichiriki", emojis: "🪈🌸", level: "impossible" },
  { id: "taepyeongso", title: "Taepyeongso", emojis: "🪈🌶", level: "impossible" },
  { id: "gayageum", title: "Gayageum", emojis: "🪕🍂", level: "impossible" },
  { id: "geomungo", title: "Geomungo", emojis: "🪕🥢", level: "impossible" },
  { id: "haegeum", title: "Haegeum", emojis: "🎻🍂", level: "impossible" },
  { id: "piri", title: "Piri", emojis: "🪈🎶", level: "impossible" },
  { id: "janggu", title: "Janggu", emojis: "🥁⏳", level: "impossible" },
  { id: "gusli", title: "Gusli", emojis: "🎼🐻", level: "impossible" },
  { id: "kobza", title: "Kobza", emojis: "🪕🌻", level: "impossible" },
  { id: "dutar", title: "Dutar", emojis: "🎸🪢", level: "impossible" },
];
