// «Guess the Musical Instrument» — GuessSync · E42 · did-you-know facts, ≤70 chars, verified true.
export const INSTRUMENT_FACTS = {
  // EASY
  "guitar": "A plucked string instrument, usually with six strings",
  "piano": "Keys make hammers strike strings inside the wooden case",
  "violin": "The smallest, highest-pitched member of the string family",
  "drumkit": "A set of drums and cymbals played by one seated drummer",
  "flute": "A woodwind played by blowing across the mouth hole",
  "trumpet": "A brass instrument played with three piston valves",
  "saxophone": "A brass-bodied woodwind invented by Adolphe Sax",
  "cello": "A large bowed string instrument played while seated",
  "harp": "Strings are plucked; one of the oldest known instruments",
  "accordion": "A bellows squeezes air past reeds as keys are pressed",
  "trombone": "Brass instrument whose pitch changes via a sliding tube",
  "clarinet": "A single-reed woodwind with a cylindrical bore",
  "harmonica": "A pocket wind instrument played by breathing in and out",
  "tambourine": "A frame drum ringed with jingling metal discs",
  "xylophone": "Wooden bars struck with mallets to make notes",
  "banjo": "A string instrument with a round drum-like body",
  "ukulele": "A small four-stringed guitar from Hawaii",
  "bagpipes": "Air from a bag is squeezed through sounding pipes",
  "electricguitar": "Its steel strings' vibration is turned into an electric signal",
  "maracas": "A pair of rattles filled with beads or seeds",
  "triangle": "A steel bar bent into a triangle, struck with a beater",
  "cymbals": "Round metal plates crashed together or struck",
  "recorder": "A simple woodwind whistle taught in many schools",
  "bongos": "A pair of small joined hand drums of Cuban origin",
  "organ": "Air is pushed through rows of pipes to make sound",
  // MEDIUM
  "doublebass": "The largest, lowest-pitched bowed string instrument",
  "oboe": "A double-reed woodwind with a bright, piercing tone",
  "frenchhorn": "Brass instrument with tubing coiled into a circle",
  "tuba": "The largest and lowest brass instrument",
  "viola": "A bowed string instrument slightly larger than a violin",
  "mandolin": "A small string instrument with paired strings, plucked",
  "bassguitar": "A four-string guitar tuned to the low bass range",
  "piccolo": "A tiny flute pitched an octave above the normal flute",
  "bassoon": "A tall double-reed woodwind with a deep, low voice",
  "conga": "A tall, narrow single-headed hand drum from Cuba",
  "djembe": "A rope-tuned goblet drum played with bare hands",
  "marimba": "Wooden bars over resonators, struck with soft mallets",
  "timpani": "Large tunable kettle drums used in orchestras",
  "ocarina": "A small oval flute with finger holes, often clay",
  "kalimba": "Metal tines plucked by the thumbs; a thumb piano",
  "castanets": "Handheld shells clicked together to keep rhythm",
  "glockenspiel": "Metal bars struck with mallets for a bright bell tone",
  "steelpan": "A tuned drum made from an oil barrel, from Trinidad",
  "cajon": "A box drum the player sits on and slaps by hand",
  "panflute": "Tuned pipes of different lengths bound side by side",
  "lute": "A pear-shaped plucked string instrument with a bent neck",
  "snaredrum": "A drum with rattling wires stretched across its underside",
  "vibraphone": "Metal bars with a motor-driven vibrato effect",
  "didgeridoo": "A long wooden drone pipe from Aboriginal Australia",
  "gong": "A large hanging metal disc struck with a mallet",
  // HARD
  "zither": "Many strings stretched over a flat sound box, plucked",
  "hammereddulcimer": "Strings struck with small handheld hammers",
  "harpsichord": "A keyboard that plucks its strings instead of striking",
  "cornet": "A compact brass instrument, mellower than a trumpet",
  "flugelhorn": "A brass instrument with a wide, cone-shaped bore",
  "euphonium": "A mid-sized brass instrument with a warm, round tone",
  "bouzouki": "A long-necked plucked string instrument from Greece",
  "erhu": "A two-stringed bowed fiddle from China",
  "guzheng": "A long Chinese zither with movable bridges, plucked",
  "pipa": "A pear-shaped four-string lute from China",
  "koto": "A long Japanese zither with thirteen strings",
  "shamisen": "A three-stringed Japanese lute played with a plectrum",
  "tabla": "A pair of hand drums central to Indian music",
  "sarod": "A fretless plucked lute from India with a metal board",
  "oud": "A fretless pear-shaped lute of the Arab world",
  "qanun": "A flat plucked zither of the Middle East",
  "ney": "An end-blown reed flute of the Middle East",
  "bansuri": "A side-blown bamboo flute from India",
  "charango": "A small Andean lute once made from an armadillo shell",
  "cavaquinho": "A small four-string Portuguese guitar",
  "autoharp": "A zither with chord bars pressed to mute strings",
  "melodica": "A keyboard blown through a mouthpiece like a harmonica",
  "washboard": "A ridged board scraped as a folk rhythm instrument",
  "concertina": "A small hexagonal bellows instrument with buttons",
  "mbira": "African thumb piano with metal tines on a wooden board",
  // IMPOSSIBLE
  "hurdygurdy": "A crank turns a wheel that bows the strings",
  "theremin": "Played without touch, by moving hands near two antennas",
  "sitar": "A long-necked Indian lute with sympathetic strings",
  "kora": "A 21-string harp-lute from West Africa",
  "duduk": "A soft double-reed woodwind of apricot wood, from Armenia",
  "nyckelharpa": "A keyed Swedish fiddle bowed like a violin",
  "bandoneon": "A bellows-driven button instrument key to Argentine tango",
  "shakuhachi": "An end-blown Japanese bamboo flute",
  "balalaika": "A Russian lute with a triangular body and three strings",
  "guqin": "An ancient Chinese seven-string zither, plucked",
  "handpan": "A convex steel instrument played by hand, like a soft bell",
  "kantele": "A plucked zither and the national instrument of Finland",
  "kamancheh": "A spiked bowed fiddle from Persia held upright",
  "rebab": "An early bowed string instrument of the Islamic world",
  "sarangi": "A short-necked bowed lute from India with many strings",
  "dizi": "A side-blown Chinese bamboo flute with a buzzing membrane",
  "sheng": "A Chinese mouth organ made of vertical sounding pipes",
  "suona": "A loud double-reed Chinese shawm with a flared metal bell",
  "morinkhuur": "A two-string Mongolian fiddle with a horsehead scroll",
  "bandura": "A Ukrainian plucked instrument with many strings",
  "cimbalom": "A large hammered dulcimer from Central Europe",
  "hulusi": "A Chinese free-reed pipe with a gourd wind chamber",
  "angklung": "Tuned bamboo tubes shaken to sound, from Indonesia",
  "valiha": "A tube zither from Madagascar made from bamboo",
  "ondesmartenot": "An early electronic keyboard played with a ring slider",
};
