// «Guess the Musical Instrument» — GuessSync · E42 · 100 instruments (25/tier) · real photos from Wikimedia Commons
// Ranked by real global recognizability: easy (Guitar/Piano/Violin) ← impossible (obscure world/folk instruments).
export const INSTRUMENTS = [
  // EASY (25) — household-name, globally recognized
  { slug: "guitar", name: "Acoustic Guitar", level: "easy" },
  { slug: "piano", name: "Piano", level: "easy" },
  { slug: "violin", name: "Violin", level: "easy" },
  { slug: "drumkit", name: "Drum Kit", level: "easy" },
  { slug: "flute", name: "Flute", level: "easy" },
  { slug: "trumpet", name: "Trumpet", level: "easy" },
  { slug: "saxophone", name: "Saxophone", level: "easy" },
  { slug: "cello", name: "Cello", level: "easy" },
  { slug: "harp", name: "Harp", level: "easy" },
  { slug: "accordion", name: "Accordion", level: "easy" },
  { slug: "trombone", name: "Trombone", level: "easy" },
  { slug: "clarinet", name: "Clarinet", level: "easy" },
  { slug: "harmonica", name: "Harmonica", level: "easy" },
  { slug: "tambourine", name: "Tambourine", level: "easy" },
  { slug: "xylophone", name: "Xylophone", level: "easy" },
  { slug: "banjo", name: "Banjo", level: "easy" },
  { slug: "ukulele", name: "Ukulele", level: "easy" },
  { slug: "bagpipes", name: "Bagpipes", level: "easy" },
  { slug: "electricguitar", name: "Electric Guitar", level: "easy" },
  { slug: "maracas", name: "Maracas", level: "easy" },
  { slug: "triangle", name: "Triangle", level: "easy" },
  { slug: "cymbals", name: "Cymbals", level: "easy" },
  { slug: "recorder", name: "Recorder", level: "easy" },
  { slug: "bongos", name: "Bongo Drums", level: "easy" },
  { slug: "organ", name: "Pipe Organ", level: "easy" },
  // MEDIUM (25) — familiar but not top-of-mind
  { slug: "doublebass", name: "Double Bass", level: "medium" },
  { slug: "oboe", name: "Oboe", level: "medium" },
  { slug: "frenchhorn", name: "French Horn", level: "medium" },
  { slug: "tuba", name: "Tuba", level: "medium" },
  { slug: "viola", name: "Viola", level: "medium" },
  { slug: "mandolin", name: "Mandolin", level: "medium" },
  { slug: "bassguitar", name: "Bass Guitar", level: "medium" },
  { slug: "piccolo", name: "Piccolo", level: "medium" },
  { slug: "bassoon", name: "Bassoon", level: "medium" },
  { slug: "conga", name: "Conga", level: "medium" },
  { slug: "djembe", name: "Djembe", level: "medium" },
  { slug: "marimba", name: "Marimba", level: "medium" },
  { slug: "timpani", name: "Timpani", level: "medium" },
  { slug: "ocarina", name: "Ocarina", level: "medium" },
  { slug: "kalimba", name: "Kalimba", level: "medium" },
  { slug: "castanets", name: "Castanets", level: "medium" },
  { slug: "glockenspiel", name: "Glockenspiel", level: "medium" },
  { slug: "steelpan", name: "Steelpan", level: "medium" },
  { slug: "cajon", name: "Cajón", level: "medium" },
  { slug: "panflute", name: "Pan Flute", level: "medium" },
  { slug: "lute", name: "Lute", level: "medium" },
  { slug: "snaredrum", name: "Snare Drum", level: "medium" },
  { slug: "vibraphone", name: "Vibraphone", level: "medium" },
  { slug: "didgeridoo", name: "Didgeridoo", level: "medium" },
  { slug: "gong", name: "Gong", level: "medium" },
  // HARD (25) — enthusiast-level / regional
  { slug: "zither", name: "Zither", level: "hard" },
  { slug: "hammereddulcimer", name: "Hammered Dulcimer", level: "hard" },
  { slug: "harpsichord", name: "Harpsichord", level: "hard" },
  { slug: "cornet", name: "Cornet", level: "hard" },
  { slug: "flugelhorn", name: "Flugelhorn", level: "hard" },
  { slug: "euphonium", name: "Euphonium", level: "hard" },
  { slug: "bouzouki", name: "Bouzouki", level: "hard" },
  { slug: "erhu", name: "Erhu", level: "hard" },
  { slug: "guzheng", name: "Guzheng", level: "hard" },
  { slug: "pipa", name: "Pipa", level: "hard" },
  { slug: "koto", name: "Koto", level: "hard" },
  { slug: "shamisen", name: "Shamisen", level: "hard" },
  { slug: "tabla", name: "Tabla", level: "hard" },
  { slug: "sarod", name: "Sarod", level: "hard" },
  { slug: "oud", name: "Oud", level: "hard" },
  { slug: "qanun", name: "Qanun", level: "hard" },
  { slug: "ney", name: "Ney", level: "hard" },
  { slug: "bansuri", name: "Bansuri", level: "hard" },
  { slug: "charango", name: "Charango", level: "hard" },
  { slug: "cavaquinho", name: "Cavaquinho", level: "hard" },
  { slug: "autoharp", name: "Autoharp", level: "hard" },
  { slug: "melodica", name: "Melodica", level: "hard" },
  { slug: "washboard", name: "Washboard", level: "hard" },
  { slug: "concertina", name: "Concertina", level: "hard" },
  { slug: "mbira", name: "Mbira", level: "hard" },
  // IMPOSSIBLE (25) — obscure world / folk instruments
  { slug: "hurdygurdy", name: "Hurdy-gurdy", level: "impossible" },
  { slug: "theremin", name: "Theremin", level: "impossible" },
  { slug: "sitar", name: "Sitar", level: "impossible" },
  { slug: "kora", name: "Kora", level: "impossible" },
  { slug: "duduk", name: "Duduk", level: "impossible" },
  { slug: "nyckelharpa", name: "Nyckelharpa", level: "impossible" },
  { slug: "bandoneon", name: "Bandoneón", level: "impossible" },
  { slug: "shakuhachi", name: "Shakuhachi", level: "impossible" },
  { slug: "balalaika", name: "Balalaika", level: "impossible" },
  { slug: "guqin", name: "Guqin", level: "impossible" },
  { slug: "handpan", name: "Handpan", level: "impossible" },
  { slug: "kantele", name: "Kantele", level: "impossible" },
  { slug: "kamancheh", name: "Kamancheh", level: "impossible" },
  { slug: "rebab", name: "Rebab", level: "impossible" },
  { slug: "sarangi", name: "Sarangi", level: "impossible" },
  { slug: "dizi", name: "Dizi", level: "impossible" },
  { slug: "sheng", name: "Sheng", level: "impossible" },
  { slug: "suona", name: "Suona", level: "impossible" },
  { slug: "morinkhuur", name: "Morin Khuur", level: "impossible" },
  { slug: "bandura", name: "Bandura", level: "impossible" },
  { slug: "cimbalom", name: "Cimbalom", level: "impossible" },
  { slug: "hulusi", name: "Hulusi", level: "impossible" },
  { slug: "angklung", name: "Angklung", level: "impossible" },
  { slug: "valiha", name: "Valiha", level: "impossible" },
  { slug: "ondesmartenot", name: "Ondes Martenot", level: "impossible" },
];
