// «Guess the Musical Instrument» v2 — GuessSync · did-you-know facts, ≤70 chars, verified true.
export const INSTRUMENTS2_FACTS = {
  // EASY
  "synthesizer": "Generates sound electronically instead of from strings or air",
  "keytar": "A synthesizer worn like a guitar and played on the shoulder",
  "cowbell": "A clapper-less bell struck with a stick in Latin music",
  "kazoo": "You hum into it; a membrane buzzes to change your voice",
  "whistle": "Blowing air past an edge makes its sharp, high tone",
  "windchimes": "Hanging tubes or rods chime when moved by the breeze",
  "sleighbells": "Small round bells on a strap, jingled by shaking",
  "rainstick": "A tube of pins and beads sounds like falling rain when tilted",
  "woodblock": "A hollow wooden block struck with a stick for a sharp click",
  "turntable": "DJs spin vinyl records and scratch them for hip-hop beats",
  "drummachine": "An electronic device that programs and plays drum patterns",
  "handbell": "A handheld bell rung by teams, each playing set notes",
  "tuningfork": "A metal fork that vibrates at one exact pitch when struck",
  "slidewhistle": "A whistle whose pitch slides as you move an inner plunger",
  "bugle": "A valveless brass horn long used for military calls",
  "sousaphone": "A tuba coiled to rest on the body for marching bands",
  "tinwhistle": "A simple six-hole metal flute key to Irish folk music",
  "lyre": "An ancient harp-like string instrument of Greek antiquity",
  "jawharp": "Held to the mouth; a plucked tongue twangs using the mouth",
  "bassdrum": "The largest drum, giving the deep, low beat of the kit",
  "tomtom": "A cylindrical drum with no snares, common on drum kits",
  "claves": "Two wooden sticks struck together in Afro-Cuban rhythms",
  "guiro": "A ridged gourd scraped with a stick for a raspy sound",
  "tubularbells": "Tall metal tubes struck to imitate the sound of church bells",
  "vuvuzela": "A plastic horn made famous at the 2010 World Cup",
  // MEDIUM
  "appalachiandulcimer": "A fretted string instrument played flat on the lap",
  "melodeon": "A small diatonic button accordion used in folk music",
  "mellotron": "A 1960s keyboard that plays taped recordings of real sounds",
  "hammondorgan": "An electric organ prized in jazz, gospel and rock",
  "celesta": "Keys strike metal plates for a soft, bell-like tone",
  "clavichord": "An early keyboard whose metal blades tap the strings",
  "harmonium": "A pump organ where bellows push air through reeds",
  "fife": "A small high-pitched flute used in military bands",
  "englishhorn": "A larger, lower cousin of the oboe, also called cor anglais",
  "bassclarinet": "A clarinet pitched an octave below the standard one",
  "contrabassoon": "A bassoon playing an octave lower, the lowest woodwind",
  "alphorn": "A very long wooden horn once used across the Alps",
  "wagnertuba": "A brass instrument Wagner designed for his operas",
  "mellophone": "A brass instrument used for French horn parts on the march",
  "timbales": "Shallow metal drums played with sticks in Latin music",
  "taiko": "Large Japanese drums played with heavy wooden sticks",
  "darbuka": "A goblet-shaped hand drum of the Middle East",
  "riq": "An ornate Arabic tambourine with jingling cymbals",
  "cabasa": "Steel beads wrapped round a cylinder, twisted to rattle",
  "vibraslap": "A ball strikes a box of pins for a long rattling buzz",
  "flexatone": "A flexible metal sheet with beads that make a wobbling tone",
  "washtubbass": "A one-string bass built from a tub, stick and cord",
  "resonatorguitar": "A guitar with metal cones instead of a wooden soundhole",
  "pedalsteel": "A lap guitar on legs with pedals that bend the pitch",
  "lapsteel": "A guitar played flat, sliding a steel bar on the strings",
  // HARD
  "domra": "A round-bodied Russian string instrument played with a pick",
  "saz": "A long-necked Turkish lute central to folk music",
  "dombra": "A two-string plucked lute of Kazakhstan",
  "setar": "A slender four-string Persian lute played with the finger",
  "tar": "A waisted, double-bowl lute of Iran and the Caucasus",
  "santoor": "A trapezoid box zither struck with light wooden mallets",
  "veena": "An ancient plucked string instrument of Indian classical",
  "tanpura": "A long-necked lute that drones to accompany Indian music",
  "dholak": "A two-headed hand drum of South Asian folk music",
  "dhol": "A large double-headed drum played with sticks in South Asia",
  "mridangam": "The main double-headed drum of South Indian classical music",
  "ghatam": "A clay pot played as a drum in South Indian music",
  "kanjira": "A small South Indian frame drum with one jingle",
  "shehnai": "A North Indian oboe-like reed horn played at weddings",
  "bodhran": "A shallow Irish frame drum beaten with a double-ended stick",
  "uilleannpipes": "Irish bagpipes inflated by a bellows at the elbow",
  "hardangerfiddle": "A Norwegian fiddle with extra strings that ring along",
  "psaltery": "An old zither whose strings are plucked or bowed",
  "crumhorn": "A curved Renaissance reed pipe with a capped mouthpiece",
  "shawm": "A loud double-reed ancestor of the modern oboe",
  "sackbut": "An early trombone used in Renaissance and Baroque music",
  "violadagamba": "A bowed, fretted string instrument held on the legs",
  "theorbo": "A very long-necked lute with extra deep bass strings",
  "vielle": "A medieval bowed string instrument, ancestor of the fiddle",
  "serpent": "A curvy wooden horn covered in leather with finger holes",
  // IMPOSSIBLE
  "saron": "A bronze metallophone used in Indonesian gamelan music",
  "bonang": "A set of tuned bronze pot-gongs in Javanese gamelan",
  "rebana": "A Malay and Indonesian frame drum used in Muslim music",
  "kacapi": "A boat-shaped Sundanese zither from West Java",
  "sasando": "A tube zither with a fanned palm-leaf resonator from Rote",
  "khaen": "A Lao mouth organ made of paired bamboo pipes",
  "danbau": "A one-string Vietnamese zither bent with a flexible rod",
  "dantranh": "A Vietnamese zither with many strings over movable bridges",
  "yangqin": "A Chinese hammered dulcimer struck with bamboo beaters",
  "ruan": "A round-bodied Chinese lute with a long fretted neck",
  "liuqin": "A small, high-pitched Chinese lute shaped like a willow leaf",
  "banhu": "A Chinese bowed fiddle with a coconut or wood body",
  "gaohu": "A high-pitched Chinese two-string bowed fiddle",
  "paixiao": "An ancient Chinese pan flute of bound bamboo pipes",
  "xun": "An egg-shaped Chinese clay vessel flute, blown on top",
  "hichiriki": "A small, loud double-reed pipe of Japanese court music",
  "taepyeongso": "A loud Korean double-reed horn with a metal bell",
  "gayageum": "A Korean zither with twelve silk strings, plucked by hand",
  "geomungo": "A Korean zither struck with a slender bamboo stick",
  "haegeum": "A Korean two-string vertical fiddle with a bamboo body",
  "piri": "A Korean double-reed bamboo pipe with a large reed",
  "janggu": "An hourglass-shaped Korean drum with two heads",
  "gusli": "An ancient Russian plucked zither, laid flat and strummed",
  "kobza": "A Ukrainian plucked lute, forerunner of the bandura",
  "dutar": "A two-string long-necked lute of Central Asia",
};
