// E184 «Guess the Job by Emoji 2» — 100 jobs · 25/tier
// VO: sfx/e184-<id>.wav
export const JOBS_EMOJI_2_FACTS = {
  // EASY
  "dentist": "Doctor who treats teeth, gums, and oral health.",
  "cashier": "Handles payments and receipts at a store checkout.",
  "cleaner": "Keeps buildings and spaces tidy and sanitary.",
  "gardener": "Grows and cares for plants, lawns, and gardens.",
  "soldier": "Trained member of a country's armed forces.",
  "clown": "Comic performer who entertains with jokes and antics.",
  "cowboy": "Herds and tends cattle on horseback.",
  "gamer": "Plays video games, often competitively.",
  "king": "Male monarch who rules a kingdom.",
  "dj": "Mixes and plays recorded music for audiences.",
  "actor": "Performs roles in films, TV, or theater.",
  "film-director": "Guides the creative vision of a film.",
  "writer": "Creates books, articles, or stories.",
  "programmer": "Writes code to build software and apps.",
  "bartender": "Mixes and serves drinks at a bar.",
  "lifeguard": "Watches swimmers and rescues those in danger.",
  "truck-driver": "Transports goods long distances by truck.",
  "makeup-artist": "Applies makeup for looks, film, or events.",
  "model": "Poses to display clothing or products.",
  "athlete": "Competes in sports at a high level.",
  "swimmer": "Competes in races through the water.",
  "surfer": "Rides ocean waves on a board.",
  "footballer": "Plays soccer, scoring goals for a team.",
  "basketball-player": "Plays basketball, shooting hoops to score.",
  "tennis-player": "Competes in tennis matches with a racket.",
  // MEDIUM
  "cardiologist": "Doctor who treats the heart and its diseases.",
  "radiologist": "Reads X-rays and scans to diagnose illness.",
  "midwife": "Assists women through pregnancy and childbirth.",
  "pediatrician": "Doctor who cares for babies and children.",
  "masseur": "Relieves tension by massaging the body.",
  "chiropractor": "Treats the spine and joints by adjustment.",
  "dietitian": "Advises on healthy eating and nutrition.",
  "chemist": "Studies substances and chemical reactions.",
  "biologist": "Studies living organisms and life.",
  "physicist": "Studies matter, energy, and the universe.",
  "mathematician": "Studies numbers, patterns, and equations.",
  "economist": "Studies money, markets, and the economy.",
  "statistician": "Analyzes data and interprets statistics.",
  "surveyor": "Measures land and maps its boundaries.",
  "professor": "Teaches and researches at a university.",
  "diplomat": "Represents a nation in foreign relations.",
  "politician": "Holds or seeks public office to govern.",
  "mayor": "Elected leader of a city or town.",
  "banker": "Manages money, loans, and investments.",
  "stockbroker": "Buys and sells shares for investors.",
  "salesman": "Sells products or services to customers.",
  "receptionist": "Greets visitors and answers calls at a desk.",
  "secretary": "Handles schedules, files, and correspondence.",
  "courier": "Delivers packages and documents quickly.",
  "mover": "Loads and hauls belongings between homes.",
  // HARD
  "welder": "Joins metal parts using intense heat.",
  "bricklayer": "Builds walls by laying bricks and mortar.",
  "roofer": "Installs and repairs building roofs.",
  "machinist": "Shapes metal parts using machine tools.",
  "exterminator": "Removes pests and insects from buildings.",
  "anesthetist": "Keeps patients asleep and pain-free in surgery.",
  "pathologist": "Studies disease in tissues and body fluids.",
  "geneticist": "Studies genes, DNA, and heredity.",
  "marine-biologist": "Studies ocean life and sea creatures.",
  "botanist": "Studies plants and how they grow.",
  "zoologist": "Studies animals and their behavior.",
  "paleontologist": "Studies fossils and prehistoric life.",
  "volcanologist": "Studies volcanoes and their eruptions.",
  "seismologist": "Studies earthquakes and seismic waves.",
  "oceanographer": "Studies the oceans and their processes.",
  "air-traffic-controller": "Guides aircraft safely around airports.",
  "train-conductor": "Manages a train and its passengers.",
  "violinist": "Plays music on the violin.",
  "pianist": "Plays music on the piano.",
  "sculptor": "Shapes stone, metal, or clay into art.",
  "animator": "Creates moving images and cartoons.",
  "graphic-designer": "Designs visuals for print and screen.",
  "fashion-designer": "Creates clothing and style collections.",
  "barista": "Prepares and serves coffee drinks.",
  "brewer": "Makes beer by fermenting grains.",
  // IMPOSSIBLE
  "bookbinder": "Sews and binds pages into books.",
  "typographer": "Designs and arranges printed type.",
  "goldsmith": "Crafts objects and jewelry from gold.",
  "tinsmith": "Makes and repairs items from tin and metal.",
  "luthier": "Builds and repairs stringed instruments.",
  "lapidary": "Cuts and polishes gems and stones.",
  "bowyer": "Crafts bows for archery.",
  "sailmaker": "Cuts and sews sails for boats.",
  "basketweaver": "Weaves baskets from reeds or cane.",
  "bellfounder": "Casts large bells from molten metal.",
  "upholsterer": "Pads and covers furniture with fabric.",
  "puppeteer": "Brings puppets to life in performances.",
  "taxidermist": "Preserves and mounts animals lifelike.",
  "perfumer": "Creates fragrances and perfumes.",
  "chocolatier": "Crafts fine chocolates and confections.",
  "cheesemaker": "Makes cheese from milk.",
  "distiller": "Produces spirits by distilling alcohol.",
  "glassblower": "Shapes molten glass by blowing air.",
  "mosaicist": "Creates art from small tiles and stones.",
  "herbalist": "Uses plants for remedies and healing.",
  "wigmaker": "Crafts wigs and hairpieces.",
  "soapmaker": "Makes soap from oils and lye.",
  "armorer": "Makes and maintains armor and weapons.",
  "swordsmith": "Forges swords and blades from steel.",
  "furrier": "Makes and repairs garments from fur.",
};
