// E136 «Guess the Job by Emoji» — 100 professions · 25/tier · clue = plain Unicode emoji (2 separate object emojis, no ZWJ)
// VO: sfx/e136-<id>.wav
export const JOBS_EMOJI = [
  // ===== EASY (25) =====
  { id: "doctor", title: "Doctor", emojis: "🏥💊", level: "easy" },
  { id: "chef", title: "Chef", emojis: "🍳🔪", level: "easy" },
  { id: "teacher", title: "Teacher", emojis: "📚🎓", level: "easy" },
  { id: "police-officer", title: "Police Officer", emojis: "👮🚔", level: "easy" },
  { id: "firefighter", title: "Firefighter", emojis: "🔥💦", level: "easy" },
  { id: "pilot", title: "Pilot", emojis: "✈🧭", level: "easy" },
  { id: "farmer", title: "Farmer", emojis: "🌾🚜", level: "easy" },
  { id: "nurse", title: "Nurse", emojis: "💉🩹", level: "easy" },
  { id: "artist", title: "Artist", emojis: "🎨🖼", level: "easy" },
  { id: "musician", title: "Musician", emojis: "🎸🎤", level: "easy" },
  { id: "photographer", title: "Photographer", emojis: "📷📸", level: "easy" },
  { id: "mechanic", title: "Mechanic", emojis: "🔧🚗", level: "easy" },
  { id: "barber", title: "Barber", emojis: "💇🪒", level: "easy" },
  { id: "baker", title: "Baker", emojis: "🍞🥐", level: "easy" },
  { id: "waiter", title: "Waiter", emojis: "🍴🥂", level: "easy" },
  { id: "singer", title: "Singer", emojis: "🎤🎶", level: "easy" },
  { id: "dancer", title: "Dancer", emojis: "💃🕺", level: "easy" },
  { id: "house-painter", title: "House Painter", emojis: "🎨🏠", level: "easy" },
  { id: "plumber", title: "Plumber", emojis: "🚿🔧", level: "easy" },
  { id: "librarian", title: "Librarian", emojis: "📚🔍", level: "easy" },
  { id: "mail-carrier", title: "Mail Carrier", emojis: "📦✉", level: "easy" },
  { id: "taxi-driver", title: "Taxi Driver", emojis: "🚕🛣", level: "easy" },
  { id: "bus-driver", title: "Bus Driver", emojis: "🚌🛣", level: "easy" },
  { id: "security-guard", title: "Security Guard", emojis: "💂🔒", level: "easy" },
  { id: "astronaut", title: "Astronaut", emojis: "🚀🌌", level: "easy" },
  // ===== MEDIUM (25) =====
  { id: "lawyer", title: "Lawyer", emojis: "⚖📜", level: "medium" },
  { id: "judge", title: "Judge", emojis: "⚖🔨", level: "medium" },
  { id: "accountant", title: "Accountant", emojis: "💰🔢", level: "medium" },
  { id: "engineer", title: "Engineer", emojis: "🔧📐", level: "medium" },
  { id: "scientist", title: "Scientist", emojis: "🧪🧠", level: "medium" },
  { id: "architect", title: "Architect", emojis: "📐🏛", level: "medium" },
  { id: "electrician", title: "Electrician", emojis: "⚡🔧", level: "medium" },
  { id: "journalist", title: "Journalist", emojis: "📰🎤", level: "medium" },
  { id: "veterinarian", title: "Veterinarian", emojis: "🐶💉", level: "medium" },
  { id: "optometrist", title: "Optometrist", emojis: "👁👓", level: "medium" },
  { id: "pharmacist", title: "Pharmacist", emojis: "💊🧪", level: "medium" },
  { id: "butcher", title: "Butcher", emojis: "🔪🥩", level: "medium" },
  { id: "fisherman", title: "Fisherman", emojis: "🎣🐟", level: "medium" },
  { id: "carpenter", title: "Carpenter", emojis: "🪵🔨", level: "medium" },
  { id: "tailor", title: "Tailor", emojis: "👗🧶", level: "medium" },
  { id: "jeweler", title: "Jeweler", emojis: "💎💍", level: "medium" },
  { id: "florist", title: "Florist", emojis: "🌷🌹", level: "medium" },
  { id: "real-estate-agent", title: "Real Estate Agent", emojis: "🏠🔑", level: "medium" },
  { id: "bank-teller", title: "Bank Teller", emojis: "🏦💵", level: "medium" },
  { id: "flight-attendant", title: "Flight Attendant", emojis: "✈🍷", level: "medium" },
  { id: "zookeeper", title: "Zookeeper", emojis: "🦁🔑", level: "medium" },
  { id: "tour-guide", title: "Tour Guide", emojis: "🗺🧭", level: "medium" },
  { id: "interpreter", title: "Interpreter", emojis: "💬🌐", level: "medium" },
  { id: "meteorologist", title: "Meteorologist", emojis: "☀🌧", level: "medium" },
  { id: "priest", title: "Priest", emojis: "⛪✝", level: "medium" },
  // ===== HARD (25) =====
  { id: "surgeon", title: "Surgeon", emojis: "🔪🩸", level: "hard" },
  { id: "paramedic", title: "Paramedic", emojis: "🩹💊", level: "hard" },
  { id: "locksmith", title: "Locksmith", emojis: "🔑🔨", level: "hard" },
  { id: "blacksmith", title: "Blacksmith", emojis: "🔨🔥", level: "hard" },
  { id: "beekeeper", title: "Beekeeper", emojis: "🐝🍯", level: "hard" },
  { id: "miner", title: "Miner", emojis: "🪨⛏", level: "hard" },
  { id: "sailor", title: "Sailor", emojis: "⚓🌊", level: "hard" },
  { id: "scuba-diver", title: "Scuba Diver", emojis: "🤿🌊", level: "hard" },
  { id: "astronomer", title: "Astronomer", emojis: "⭐🌌", level: "hard" },
  { id: "geologist", title: "Geologist", emojis: "🪨🌋", level: "hard" },
  { id: "archaeologist", title: "Archaeologist", emojis: "🏺🪨", level: "hard" },
  { id: "historian", title: "Historian", emojis: "📜🏛", level: "hard" },
  { id: "philosopher", title: "Philosopher", emojis: "🧠💭", level: "hard" },
  { id: "psychologist", title: "Psychologist", emojis: "🧠💬", level: "hard" },
  { id: "detective", title: "Detective", emojis: "🔍🕵", level: "hard" },
  { id: "magician", title: "Magician", emojis: "🎩🔮", level: "hard" },
  { id: "referee", title: "Referee", emojis: "⚽🟨", level: "hard" },
  { id: "coach", title: "Coach", emojis: "🏆📋", level: "hard" },
  { id: "boxer", title: "Boxer", emojis: "🥊👊", level: "hard" },
  { id: "fencer", title: "Fencer", emojis: "🤺⚔", level: "hard" },
  { id: "lighthouse-keeper", title: "Lighthouse Keeper", emojis: "🌊🔦", level: "hard" },
  { id: "cartoonist", title: "Cartoonist", emojis: "🎨🖊", level: "hard" },
  { id: "calligrapher", title: "Calligrapher", emojis: "✍📜", level: "hard" },
  { id: "potter", title: "Potter", emojis: "🏺🎨", level: "hard" },
  { id: "falconer", title: "Falconer", emojis: "🦅✋", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { id: "farrier", title: "Farrier", emojis: "🐴🔨", level: "impossible" },
  { id: "sommelier", title: "Sommelier", emojis: "🍷🍇", level: "impossible" },
  { id: "cartographer", title: "Cartographer", emojis: "🗺📝", level: "impossible" },
  { id: "actuary", title: "Actuary", emojis: "🔢📄", level: "impossible" },
  { id: "cooper", title: "Cooper", emojis: "🛢🔨", level: "impossible" },
  { id: "milliner", title: "Milliner", emojis: "🎩🧶", level: "impossible" },
  { id: "fletcher", title: "Fletcher", emojis: "🏹🪶", level: "impossible" },
  { id: "chandler", title: "Chandler", emojis: "🕯🔥", level: "impossible" },
  { id: "cordwainer", title: "Cordwainer", emojis: "👟🔨", level: "impossible" },
  { id: "haberdasher", title: "Haberdasher", emojis: "👔🎩", level: "impossible" },
  { id: "vintner", title: "Vintner", emojis: "🍇🌱", level: "impossible" },
  { id: "genealogist", title: "Genealogist", emojis: "🌳📜", level: "impossible" },
  { id: "cryptographer", title: "Cryptographer", emojis: "🔒🔢", level: "impossible" },
  { id: "glazier", title: "Glazier", emojis: "🪟🔨", level: "impossible" },
  { id: "thatcher", title: "Thatcher", emojis: "🏠🌾", level: "impossible" },
  { id: "tanner", title: "Tanner", emojis: "🐄🪒", level: "impossible" },
  { id: "wheelwright", title: "Wheelwright", emojis: "🛞🔨", level: "impossible" },
  { id: "stevedore", title: "Stevedore", emojis: "🚢📦", level: "impossible" },
  { id: "auctioneer", title: "Auctioneer", emojis: "🔨💰", level: "impossible" },
  { id: "embalmer", title: "Embalmer", emojis: "💀⚰", level: "impossible" },
  { id: "lexicographer", title: "Lexicographer", emojis: "📖✍", level: "impossible" },
  { id: "horologist", title: "Horologist", emojis: "⌚🔧", level: "impossible" },
  { id: "ornithologist", title: "Ornithologist", emojis: "🦅📔", level: "impossible" },
  { id: "entomologist", title: "Entomologist", emojis: "🐛🔍", level: "impossible" },
  { id: "notary", title: "Notary", emojis: "📄✍", level: "impossible" },
];
