// E184 «Guess the Job by Emoji 2» — 100 jobs · 25/tier
// VO: sfx/e184-<id>.wav
export const JOBS_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "dentist", title: "Dentist", emojis: "🦷🪥", level: "easy" },
  { id: "cashier", title: "Cashier", emojis: "🛒💵", level: "easy" },
  { id: "cleaner", title: "Cleaner", emojis: "🧹🧼", level: "easy" },
  { id: "gardener", title: "Gardener", emojis: "🪴🌱", level: "easy" },
  { id: "soldier", title: "Soldier", emojis: "🪖🎖", level: "easy" },
  { id: "clown", title: "Clown", emojis: "🤡🎪", level: "easy" },
  { id: "cowboy", title: "Cowboy", emojis: "🤠🐎", level: "easy" },
  { id: "gamer", title: "Gamer", emojis: "🎮🕹", level: "easy" },
  { id: "king", title: "King", emojis: "👑🏰", level: "easy" },
  { id: "dj", title: "DJ", emojis: "🎧🎚", level: "easy" },
  { id: "actor", title: "Actor", emojis: "🎭🎬", level: "easy" },
  { id: "film-director", title: "Film Director", emojis: "🎬📢", level: "easy" },
  { id: "writer", title: "Writer", emojis: "📝📖", level: "easy" },
  { id: "programmer", title: "Programmer", emojis: "💻⌨", level: "easy" },
  { id: "bartender", title: "Bartender", emojis: "🍸🍹", level: "easy" },
  { id: "lifeguard", title: "Lifeguard", emojis: "🛟🏖", level: "easy" },
  { id: "truck-driver", title: "Truck Driver", emojis: "🚚🛣", level: "easy" },
  { id: "makeup-artist", title: "Makeup Artist", emojis: "💄🖌", level: "easy" },
  { id: "model", title: "Model", emojis: "👠👗", level: "easy" },
  { id: "athlete", title: "Athlete", emojis: "🏃🏅", level: "easy" },
  { id: "swimmer", title: "Swimmer", emojis: "🏊🥽", level: "easy" },
  { id: "surfer", title: "Surfer", emojis: "🏄🌊", level: "easy" },
  { id: "footballer", title: "Footballer", emojis: "⚽🥅", level: "easy" },
  { id: "basketball-player", title: "Basketball Player", emojis: "🏀⛹", level: "easy" },
  { id: "tennis-player", title: "Tennis Player", emojis: "🎾🏆", level: "easy" },
  // ===== MEDIUM (25) =====
  { id: "cardiologist", title: "Cardiologist", emojis: "🫀🩺", level: "medium" },
  { id: "radiologist", title: "Radiologist", emojis: "🩻🦴", level: "medium" },
  { id: "midwife", title: "Midwife", emojis: "🤰🍼", level: "medium" },
  { id: "pediatrician", title: "Pediatrician", emojis: "🧒🩺", level: "medium" },
  { id: "masseur", title: "Masseur", emojis: "💆🖐", level: "medium" },
  { id: "chiropractor", title: "Chiropractor", emojis: "🦴👐", level: "medium" },
  { id: "dietitian", title: "Dietitian", emojis: "🥗📋", level: "medium" },
  { id: "chemist", title: "Chemist", emojis: "⚗🧪", level: "medium" },
  { id: "biologist", title: "Biologist", emojis: "🔬🧫", level: "medium" },
  { id: "physicist", title: "Physicist", emojis: "⚛📐", level: "medium" },
  { id: "mathematician", title: "Mathematician", emojis: "➗🔢", level: "medium" },
  { id: "economist", title: "Economist", emojis: "🌐📈", level: "medium" },
  { id: "statistician", title: "Statistician", emojis: "📊📉", level: "medium" },
  { id: "surveyor", title: "Surveyor", emojis: "🗺📐", level: "medium" },
  { id: "professor", title: "Professor", emojis: "🎓📖", level: "medium" },
  { id: "diplomat", title: "Diplomat", emojis: "🤝🌐", level: "medium" },
  { id: "politician", title: "Politician", emojis: "🗳🎙", level: "medium" },
  { id: "mayor", title: "Mayor", emojis: "🏛🔑", level: "medium" },
  { id: "banker", title: "Banker", emojis: "💰🏦", level: "medium" },
  { id: "stockbroker", title: "Stockbroker", emojis: "📈💰", level: "medium" },
  { id: "salesman", title: "Salesman", emojis: "🛍💵", level: "medium" },
  { id: "receptionist", title: "Receptionist", emojis: "☎🛎", level: "medium" },
  { id: "secretary", title: "Secretary", emojis: "📇📝", level: "medium" },
  { id: "courier", title: "Courier", emojis: "📦🛵", level: "medium" },
  { id: "mover", title: "Mover", emojis: "📦💪", level: "medium" },
  // ===== HARD (25) =====
  { id: "welder", title: "Welder", emojis: "🔥🛠", level: "hard" },
  { id: "bricklayer", title: "Bricklayer", emojis: "🧱🔨", level: "hard" },
  { id: "roofer", title: "Roofer", emojis: "🏠🔨", level: "hard" },
  { id: "machinist", title: "Machinist", emojis: "⚙🔩", level: "hard" },
  { id: "exterminator", title: "Exterminator", emojis: "🐜🧴", level: "hard" },
  { id: "anesthetist", title: "Anesthetist", emojis: "😴💉", level: "hard" },
  { id: "pathologist", title: "Pathologist", emojis: "🔬🩸", level: "hard" },
  { id: "geneticist", title: "Geneticist", emojis: "🧬🧪", level: "hard" },
  { id: "marine-biologist", title: "Marine Biologist", emojis: "🐙🔬", level: "hard" },
  { id: "botanist", title: "Botanist", emojis: "🌿🔍", level: "hard" },
  { id: "zoologist", title: "Zoologist", emojis: "🦁📔", level: "hard" },
  { id: "paleontologist", title: "Paleontologist", emojis: "🦕🦴", level: "hard" },
  { id: "volcanologist", title: "Volcanologist", emojis: "🌋🔬", level: "hard" },
  { id: "seismologist", title: "Seismologist", emojis: "🌍📉", level: "hard" },
  { id: "oceanographer", title: "Oceanographer", emojis: "🌊🌡", level: "hard" },
  { id: "air-traffic-controller", title: "Air Traffic Controller", emojis: "🛫🎧", level: "hard" },
  { id: "train-conductor", title: "Train Conductor", emojis: "🚂🎫", level: "hard" },
  { id: "violinist", title: "Violinist", emojis: "🎻🎼", level: "hard" },
  { id: "pianist", title: "Pianist", emojis: "🎹🎼", level: "hard" },
  { id: "sculptor", title: "Sculptor", emojis: "🗿🔨", level: "hard" },
  { id: "animator", title: "Animator", emojis: "🎨💻", level: "hard" },
  { id: "graphic-designer", title: "Graphic Designer", emojis: "🖌🖥", level: "hard" },
  { id: "fashion-designer", title: "Fashion Designer", emojis: "✂👗", level: "hard" },
  { id: "barista", title: "Barista", emojis: "☕🥛", level: "hard" },
  { id: "brewer", title: "Brewer", emojis: "🍺🌾", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { id: "bookbinder", title: "Bookbinder", emojis: "📚🧵", level: "impossible" },
  { id: "typographer", title: "Typographer", emojis: "🖨✒", level: "impossible" },
  { id: "goldsmith", title: "Goldsmith", emojis: "🪙🔨", level: "impossible" },
  { id: "tinsmith", title: "Tinsmith", emojis: "🥫🔨", level: "impossible" },
  { id: "luthier", title: "Luthier", emojis: "🎸🔨", level: "impossible" },
  { id: "lapidary", title: "Lapidary", emojis: "💎🔍", level: "impossible" },
  { id: "bowyer", title: "Bowyer", emojis: "🏹🪵", level: "impossible" },
  { id: "sailmaker", title: "Sailmaker", emojis: "⛵🧵", level: "impossible" },
  { id: "basketweaver", title: "Basket Weaver", emojis: "🧺🌿", level: "impossible" },
  { id: "bellfounder", title: "Bell Founder", emojis: "🔔🔥", level: "impossible" },
  { id: "upholsterer", title: "Upholsterer", emojis: "🛋🪡", level: "impossible" },
  { id: "puppeteer", title: "Puppeteer", emojis: "🎭🪆", level: "impossible" },
  { id: "taxidermist", title: "Taxidermist", emojis: "🦌🪡", level: "impossible" },
  { id: "perfumer", title: "Perfumer", emojis: "🌸👃", level: "impossible" },
  { id: "chocolatier", title: "Chocolatier", emojis: "🍫🍬", level: "impossible" },
  { id: "cheesemaker", title: "Cheesemaker", emojis: "🧀🐄", level: "impossible" },
  { id: "distiller", title: "Distiller", emojis: "🥃⚗", level: "impossible" },
  { id: "glassblower", title: "Glassblower", emojis: "🔥🫧", level: "impossible" },
  { id: "mosaicist", title: "Mosaicist", emojis: "🎨🧩", level: "impossible" },
  { id: "herbalist", title: "Herbalist", emojis: "🌿🧪", level: "impossible" },
  { id: "wigmaker", title: "Wigmaker", emojis: "🦱🎭", level: "impossible" },
  { id: "soapmaker", title: "Soapmaker", emojis: "🧼🌿", level: "impossible" },
  { id: "armorer", title: "Armorer", emojis: "🛡🔨", level: "impossible" },
  { id: "swordsmith", title: "Swordsmith", emojis: "⚔🔥", level: "impossible" },
  { id: "furrier", title: "Furrier", emojis: "🦊🧵", level: "impossible" },
];
