// «Guess the Kitchen Utensil» — GuessSync · E53 · did-you-know facts, ≤70 chars, verified true (what it's used for).
export const KITCHEN_FACTS = {
  // EASY
  "whisk": "Blends and aerates batter, eggs, or cream with wire loops",
  "spatula": "Flips food or scrapes bowls with its flat flexible blade",
  "ladle": "A deep bowled spoon for serving soups and sauces",
  "grater": "Shreds cheese or vegetables across its sharp holes",
  "peeler": "Strips the skin off fruit and vegetables with a blade",
  "rollingpin": "Rolls and flattens dough to an even thickness",
  "colander": "A perforated bowl that drains water from pasta or veg",
  "tongs": "Grips and turns food like a pair of extended fingers",
  "canopener": "Cuts open metal cans with a rotating sharp wheel",
  "measuringcup": "Measures set volumes of liquid or dry ingredients",
  "woodenspoon": "Stirs and mixes without scratching pots or pans",
  "sieve": "Sifts flour or strains liquids through fine mesh",
  "corkscrew": "Pulls corks out of wine bottles with a spiral screw",
  "cuttingboard": "A flat board that protects counters while you chop",
  "chefsknife": "The all-purpose blade for chopping, slicing, and dicing",
  "potatomasher": "Crushes boiled potatoes into a smooth mash",
  "slottedspoon": "Lifts food from liquid while letting the liquid drain",
  "pizzacutter": "Slices pizza cleanly with a rolling sharp wheel",
  "fryingpan": "A shallow flat pan for frying and searing food",
  "saucepan": "A deep round pot for boiling and simmering sauces",
  "kettle": "Heats and boils water for tea and hot drinks",
  "mixingbowl": "A round bowl for combining and beating ingredients",
  "icecreamscoop": "Scoops neat round balls of ice cream",
  "bottleopener": "Pries metal caps off glass bottles",
  "cheeseslicer": "Shaves thin even slices from a block of cheese",
  // MEDIUM
  "garlicpress": "Crushes garlic cloves through small holes into a pulp",
  "eggbeater": "A hand-cranked gear that spins beaters to whip eggs",
  "meattenderizer": "A mallet that pounds meat to make it softer",
  "bastingbrush": "Brushes sauce, butter, or glaze onto food",
  "kitchenshears": "Heavy scissors for cutting herbs, meat, and packaging",
  "saladspinner": "Spins washed salad leaves dry using centrifugal force",
  "funnel": "Guides liquids or powders into a narrow container",
  "measuringspoons": "A set of spoons for measuring small exact amounts",
  "muffintin": "A tray of cups for baking muffins and cupcakes",
  "bakingsheet": "A flat metal tray for baking cookies and roasting",
  "wok": "A deep round pan for high-heat stir-frying",
  "dutchoven": "A heavy lidded pot for slow braising and stews",
  "steamerbasket": "A perforated basket that steams food over boiling water",
  "cookiecutter": "Stamps dough into fun shapes for baking",
  "icecubetray": "A mould that freezes water into ice cubes",
  "nutcracker": "Cracks the hard shells of nuts to reach the kernel",
  "applecorer": "Removes the core and seeds from an apple in one push",
  "eggslicer": "Cuts a peeled boiled egg into even slices with wires",
  "citrusreamer": "A ridged cone that presses juice from citrus halves",
  "peppermill": "Grinds whole peppercorns fresh over your food",
  "splatterscreen": "A mesh guard that stops hot oil from splashing out",
  "kitchenscale": "Weighs ingredients for accurate baking and cooking",
  "mortarandpestle": "A bowl and club that crush spices and herbs by hand",
  "pastryblender": "Cuts cold butter into flour for flaky pastry",
  "grillpan": "A ridged pan that sears grill marks onto food",
  // HARD
  "mandoline": "Slices vegetables into thin even cuts on a flat blade",
  "potatoricer": "Presses cooked potato through holes into fine strands",
  "melonballer": "Scoops small neat balls from melon and other fruit",
  "cherrypitter": "Punches the stone out of cherries and olives",
  "zester": "Grates fine citrus peel or hard cheese into shreds",
  "pipingbag": "Squeezes icing or cream out through a shaped nozzle",
  "benchscraper": "A flat blade that cuts dough and clears the worktop",
  "fishscaler": "Scrapes the scales off a fish before cooking",
  "kitchentorch": "A flame tool that caramelizes sugar on desserts",
  "juliennepeeler": "Cuts vegetables into thin matchstick strips",
  "eggseparator": "Catches the yolk while letting the egg white pass",
  "avocadoslicer": "Splits, pits, and slices an avocado in one tool",
  "herbscissors": "Multiple blades that snip fresh herbs quickly",
  "oysterknife": "A short stout blade for prying open oyster shells",
  "meatthermometer": "Reads the internal temperature of cooking meat",
  "turkeybaster": "A bulb and tube that draws up juices to moisten roasts",
  "spiderstrainer": "A wide wire net that lifts food from hot oil or water",
  "roastingrack": "Raises meat off the pan so heat circulates around it",
  "raviolicutter": "A wheel that cuts and seals pasta into ravioli",
  "grapefruitspoon": "A spoon with a serrated tip to scoop out citrus segments",
  "doughdocker": "A spiked roller that pricks dough to stop it bubbling",
  "pizzapeel": "A flat paddle that slides pizza in and out of the oven",
  "caketester": "A thin metal skewer that checks if a cake is baked",
  "boningknife": "A narrow flexible blade for removing bones from meat",
  "cleaver": "A heavy square blade that chops through bone and meat",
  // IMPOSSIBLE
  "spurtle": "A Scottish wooden stick for stirring porridge",
  "chinois": "A cone-shaped fine sieve for straining silky sauces",
  "tamis": "A drum-shaped fine sieve for sifting and pureeing",
  "aebleskiverpan": "A dimpled pan for cooking round Danish pancake balls",
  "buttercurler": "A ridged tool that shaves butter into decorative curls",
  "mezzaluna": "A curved rocking blade that chops herbs finely",
  "channelknife": "Cuts a thin groove of peel for garnishes and twists",
  "cannolitube": "A metal tube that shapes pastry into cannoli shells",
  "madeleinepan": "A mould with shell shapes for baking madeleine cakes",
  "spatzlemaker": "Presses soft dough into the boiling water as spaetzle",
  "nutmeggrater": "A tiny fine grater for grating whole nutmeg",
  "breadlame": "A sharp blade that scores patterns into bread dough",
  "couscoussier": "A two-tier pot that steams couscous over a stew",
  "tagine": "A cone-lidded clay pot for slow North African stews",
  "escargottongs": "Small tongs that grip a hot snail shell while eating",
  "butterpaddles": "Ridged paddles that shape butter into balls",
  "krumkakeiron": "A patterned iron that bakes thin Norwegian waffle cones",
  "pizzelleiron": "A press that bakes thin patterned Italian waffle cookies",
  "dariolemould": "A small cup mould for baking or setting individual cakes",
  "lardingneedle": "A hollow needle that threads fat strips into lean meat",
  "trussingneedle": "A long needle for stitching poultry closed before roasting",
  "comal": "A flat griddle for toasting tortillas and chillies",
  "molcajete": "A stone mortar and pestle for grinding salsa and spices",
  "suribachi": "A ridged Japanese bowl for grinding sesame and spices",
  "foodmill": "A hand-cranked mill that purees and strains soft food",
};
