// «Guess the Kitchen Utensil» — GuessSync · E53 · 100 utensils (25/tier) · real photos from Wikimedia Commons
// Classified by real recognizability: easy (Whisk/Spatula/Ladle) ← impossible (Spurtle/Chinois/Larding Needle).
// DISTINCT from E48 "Tools" (workshop tools) — this is strictly KITCHEN / cooking utensils & gadgets.
export const KITCHEN = [
  // EASY (25) — everyday utensils in every kitchen
  { slug: "whisk", name: "Whisk", level: "easy" },
  { slug: "spatula", name: "Spatula", level: "easy" },
  { slug: "ladle", name: "Ladle", level: "easy" },
  { slug: "grater", name: "Grater", level: "easy" },
  { slug: "peeler", name: "Peeler", level: "easy" },
  { slug: "rollingpin", name: "Rolling Pin", level: "easy" },
  { slug: "colander", name: "Colander", level: "easy" },
  { slug: "tongs", name: "Tongs", level: "easy" },
  { slug: "canopener", name: "Can Opener", level: "easy" },
  { slug: "measuringcup", name: "Measuring Cup", level: "easy" },
  { slug: "woodenspoon", name: "Wooden Spoon", level: "easy" },
  { slug: "sieve", name: "Sieve", level: "easy" },
  { slug: "corkscrew", name: "Corkscrew", level: "easy" },
  { slug: "cuttingboard", name: "Cutting Board", level: "easy" },
  { slug: "chefsknife", name: "Chef's Knife", level: "easy" },
  { slug: "potatomasher", name: "Potato Masher", level: "easy" },
  { slug: "slottedspoon", name: "Slotted Spoon", level: "easy" },
  { slug: "pizzacutter", name: "Pizza Cutter", level: "easy" },
  { slug: "fryingpan", name: "Frying Pan", level: "easy" },
  { slug: "saucepan", name: "Saucepan", level: "easy" },
  { slug: "kettle", name: "Kettle", level: "easy" },
  { slug: "mixingbowl", name: "Mixing Bowl", level: "easy" },
  { slug: "icecreamscoop", name: "Ice Cream Scoop", level: "easy" },
  { slug: "bottleopener", name: "Bottle Opener", level: "easy" },
  { slug: "cheeseslicer", name: "Cheese Slicer", level: "easy" },
  // MEDIUM (25) — common but a notch up
  { slug: "garlicpress", name: "Garlic Press", level: "medium" },
  { slug: "eggbeater", name: "Rotary Egg Beater", level: "medium" },
  { slug: "meattenderizer", name: "Meat Tenderizer", level: "medium" },
  { slug: "bastingbrush", name: "Basting Brush", level: "medium" },
  { slug: "kitchenshears", name: "Kitchen Shears", level: "medium" },
  { slug: "saladspinner", name: "Salad Spinner", level: "medium" },
  { slug: "funnel", name: "Funnel", level: "medium" },
  { slug: "measuringspoons", name: "Measuring Spoons", level: "medium" },
  { slug: "muffintin", name: "Muffin Tin", level: "medium" },
  { slug: "bakingsheet", name: "Baking Sheet", level: "medium" },
  { slug: "wok", name: "Wok", level: "medium" },
  { slug: "dutchoven", name: "Dutch Oven", level: "medium" },
  { slug: "steamerbasket", name: "Steamer Basket", level: "medium" },
  { slug: "cookiecutter", name: "Cookie Cutter", level: "medium" },
  { slug: "icecubetray", name: "Ice Cube Tray", level: "medium" },
  { slug: "nutcracker", name: "Nutcracker", level: "medium" },
  { slug: "applecorer", name: "Apple Corer", level: "medium" },
  { slug: "eggslicer", name: "Egg Slicer", level: "medium" },
  { slug: "citrusreamer", name: "Citrus Reamer", level: "medium" },
  { slug: "peppermill", name: "Pepper Mill", level: "medium" },
  { slug: "splatterscreen", name: "Splatter Screen", level: "medium" },
  { slug: "kitchenscale", name: "Kitchen Scale", level: "medium" },
  { slug: "mortarandpestle", name: "Mortar and Pestle", level: "medium" },
  { slug: "pastryblender", name: "Pastry Blender", level: "medium" },
  { slug: "grillpan", name: "Grill Pan", level: "medium" },
  // HARD (25) — specialist but findable
  { slug: "mandoline", name: "Mandoline", level: "hard" },
  { slug: "potatoricer", name: "Potato Ricer", level: "hard" },
  { slug: "melonballer", name: "Melon Baller", level: "hard" },
  { slug: "cherrypitter", name: "Cherry Pitter", level: "hard" },
  { slug: "zester", name: "Zester", level: "hard" },
  { slug: "pipingbag", name: "Piping Bag", level: "hard" },
  { slug: "benchscraper", name: "Bench Scraper", level: "hard" },
  { slug: "fishscaler", name: "Fish Scaler", level: "hard" },
  { slug: "kitchentorch", name: "Kitchen Torch", level: "hard" },
  { slug: "juliennepeeler", name: "Julienne Peeler", level: "hard" },
  { slug: "eggseparator", name: "Egg Separator", level: "hard" },
  { slug: "avocadoslicer", name: "Avocado Slicer", level: "hard" },
  { slug: "herbscissors", name: "Herb Scissors", level: "hard" },
  { slug: "oysterknife", name: "Oyster Knife", level: "hard" },
  { slug: "meatthermometer", name: "Meat Thermometer", level: "hard" },
  { slug: "turkeybaster", name: "Turkey Baster", level: "hard" },
  { slug: "spiderstrainer", name: "Spider Strainer", level: "hard" },
  { slug: "roastingrack", name: "Roasting Rack", level: "hard" },
  { slug: "raviolicutter", name: "Ravioli Cutter", level: "hard" },
  { slug: "grapefruitspoon", name: "Grapefruit Spoon", level: "hard" },
  { slug: "doughdocker", name: "Dough Docker", level: "hard" },
  { slug: "pizzapeel", name: "Pizza Peel", level: "hard" },
  { slug: "caketester", name: "Cake Tester", level: "hard" },
  { slug: "boningknife", name: "Boning Knife", level: "hard" },
  { slug: "cleaver", name: "Cleaver", level: "hard" },
  // IMPOSSIBLE (25) — obscure & regional specialist gadgets
  { slug: "spurtle", name: "Spurtle", level: "impossible" },
  { slug: "chinois", name: "Chinois", level: "impossible" },
  { slug: "tamis", name: "Tamis", level: "impossible" },
  { slug: "aebleskiverpan", name: "Aebleskiver Pan", level: "impossible" },
  { slug: "buttercurler", name: "Butter Curler", level: "impossible" },
  { slug: "mezzaluna", name: "Mezzaluna", level: "impossible" },
  { slug: "channelknife", name: "Channel Knife", level: "impossible" },
  { slug: "cannolitube", name: "Cannoli Tube", level: "impossible" },
  { slug: "madeleinepan", name: "Madeleine Pan", level: "impossible" },
  { slug: "spatzlemaker", name: "Spätzle Maker", level: "impossible" },
  { slug: "nutmeggrater", name: "Nutmeg Grater", level: "impossible" },
  { slug: "breadlame", name: "Bread Lame", level: "impossible" },
  { slug: "couscoussier", name: "Couscoussier", level: "impossible" },
  { slug: "tagine", name: "Tagine", level: "impossible" },
  { slug: "escargottongs", name: "Escargot Tongs", level: "impossible" },
  { slug: "butterpaddles", name: "Butter Paddles", level: "impossible" },
  { slug: "krumkakeiron", name: "Krumkake Iron", level: "impossible" },
  { slug: "pizzelleiron", name: "Pizzelle Iron", level: "impossible" },
  { slug: "dariolemould", name: "Dariole Mould", level: "impossible" },
  { slug: "lardingneedle", name: "Larding Needle", level: "impossible" },
  { slug: "trussingneedle", name: "Trussing Needle", level: "impossible" },
  { slug: "comal", name: "Comal", level: "impossible" },
  { slug: "molcajete", name: "Molcajete", level: "impossible" },
  { slug: "suribachi", name: "Suribachi", level: "impossible" },
  { slug: "foodmill", name: "Food Mill", level: "impossible" },
];
