// E79 «Guess the ZOOMED Landmark» — GuessSync "What the Zoom" hard-mode.
// Reuses the EXACT E16 landmark image set (landmarks/<slug>.png) and E16's LANDMARK_FACTS
// (keyed by the same slug), but the ANSWER here is the LANDMARK NAME (not the country) and the
// items are RE-TIERED by how hard each landmark is to name from an EXTREME off-center close-up
// crop (scale 3.0). A random patch shows one surface region only, so:
//   EASY  = an unmistakable iconic detail/texture/colour survives any crop
//           (iron lattice, white marble dome, coloured onion domes, orange torii, glass spire…)
//   IMPOSSIBLE = generic texture (plain stone/water/rooftops) or an ultra-obscure landmark
// slug = image filename (landmarks/<slug>.png, = E16 key) | answer VO: sfx/lz-<slug>.wav
export const LANDMARKZOOM = [
  // ===== EASY (25) — iconic detail / texture / colour recognisable from any patch =====
  { slug: "fr",             name: "Eiffel Tower",            level: "easy" },
  { slug: "us-liberty",     name: "Statue of Liberty",       level: "easy" },
  { slug: "gb",             name: "Big Ben",                 level: "easy" },
  { slug: "it-colosseum",   name: "Colosseum",               level: "easy" },
  { slug: "in-taj",         name: "Taj Mahal",               level: "easy" },
  { slug: "au",             name: "Sydney Opera House",      level: "easy" },
  { slug: "br",             name: "Christ the Redeemer",     level: "easy" },
  { slug: "us-goldengate",  name: "Golden Gate Bridge",      level: "easy" },
  { slug: "es",             name: "Sagrada Familia",         level: "easy" },
  { slug: "ru",             name: "Saint Basil's Cathedral", level: "easy" },
  { slug: "gr",             name: "Santorini blue domes",    level: "easy" },
  { slug: "ae",             name: "Burj Khalifa",            level: "easy" },
  { slug: "my",             name: "Petronas Twin Towers",    level: "easy" },
  { slug: "sa",             name: "Kaaba in Mecca",          level: "easy" },
  { slug: "cl",             name: "Moai of Easter Island",   level: "easy" },
  { slug: "be",             name: "Atomium",                 level: "easy" },
  { slug: "jp-fuji",        name: "Mount Fuji",              level: "easy" },
  { slug: "cn-greatwall",   name: "Great Wall of China",     level: "easy" },
  { slug: "de",             name: "Brandenburg Gate",        level: "easy" },
  { slug: "mx",             name: "Chichen Itza",            level: "easy" },
  { slug: "pe",             name: "Machu Picchu",            level: "easy" },
  { slug: "jo",             name: "Petra Treasury",          level: "easy" },
  { slug: "it-pisa",        name: "Leaning Tower of Pisa",   level: "easy" },
  { slug: "eg",             name: "Pyramids of Giza",        level: "easy" },
  { slug: "jp-fushimi",     name: "Fushimi Inari gates",     level: "easy" },

  // ===== MEDIUM (25) — recognisable form/colour, but the close-up detail is less unique =====
  { slug: "kh",             name: "Angkor Wat",              level: "medium" },
  { slug: "tr",             name: "Hagia Sophia",            level: "medium" },
  { slug: "sg",             name: "Marina Bay Sands",        level: "medium" },
  { slug: "ch",             name: "The Matterhorn",          level: "medium" },
  { slug: "dk",             name: "The Little Mermaid",      level: "medium" },
  { slug: "cz",             name: "Charles Bridge",          level: "medium" },
  { slug: "pt-belem",       name: "Belem Tower",             level: "medium" },
  { slug: "at",             name: "Schonbrunn Palace",       level: "medium" },
  { slug: "hu",             name: "Parliament Building",     level: "medium" },
  { slug: "id",             name: "Borobudur Temple",        level: "medium" },
  { slug: "ma",             name: "Koutoubia Mosque",        level: "medium" },
  { slug: "hr",             name: "Dubrovnik walls",         level: "medium" },
  { slug: "kr",             name: "Gyeongbokgung Palace",    level: "medium" },
  { slug: "th",             name: "Grand Palace, Bangkok",   level: "medium" },
  { slug: "vn",             name: "Ha Long Bay",             level: "medium" },
  { slug: "ie",             name: "Cliffs of Moher",         level: "medium" },
  { slug: "no",             name: "Geirangerfjord",          level: "medium" },
  { slug: "ar",             name: "Iguazu Falls",            level: "medium" },
  { slug: "ca",             name: "Niagara Falls",           level: "medium" },
  { slug: "nl",             name: "Kinderdijk windmills",    level: "medium" },
  { slug: "us-rushmore",    name: "Mount Rushmore",          level: "medium" },
  { slug: "za-table",       name: "Table Mountain",          level: "medium" },
  { slug: "pl",             name: "Wawel Castle",            level: "medium" },
  { slug: "se",             name: "Stockholm City Hall",     level: "medium" },
  { slug: "za-goodhope",    name: "Cape of Good Hope",       level: "medium" },

  // ===== HARD (25) — obscure landmark OR distinctive only when seen whole =====
  { slug: "mm",             name: "Bagan temple plains",     level: "hard" },
  { slug: "uz",             name: "Registan, Samarkand",     level: "hard" },
  { slug: "is",             name: "Hallgrimskirkja",         level: "hard" },
  { slug: "lk",             name: "Sigiriya Rock",           level: "hard" },
  { slug: "ge",             name: "Gergeti Trinity Church",  level: "hard" },
  { slug: "az",             name: "Baku Flame Towers",       level: "hard" },
  { slug: "me",             name: "Bay of Kotor",            level: "hard" },
  { slug: "si",             name: "Lake Bled church",        level: "hard" },
  { slug: "np",             name: "Boudhanath Stupa",        level: "hard" },
  { slug: "et",             name: "Churches of Lalibela",    level: "hard" },
  { slug: "pt-pena",        name: "Pena Palace, Sintra",     level: "hard" },
  { slug: "cn-zhangjiajie", name: "Zhangjiajie pillars",     level: "hard" },
  { slug: "bo",             name: "Salar de Uyuni",          level: "hard" },
  { slug: "ir",             name: "Nasir al-Mulk Mosque",    level: "hard" },
  { slug: "ee",             name: "Tallinn old town",        level: "hard" },
  { slug: "fi",             name: "Helsinki Cathedral",      level: "hard" },
  { slug: "lt",             name: "Trakai Island Castle",    level: "hard" },
  { slug: "ph",             name: "Banaue Rice Terraces",    level: "hard" },
  { slug: "om",             name: "Sultan Qaboos Mosque",    level: "hard" },
  { slug: "qa",             name: "Museum of Islamic Art",   level: "hard" },
  { slug: "ro",             name: "Bran Castle",             level: "hard" },
  { slug: "in-hawamahal",   name: "Hawa Mahal, Jaipur",      level: "hard" },
  { slug: "gt",             name: "Tikal Temple",            level: "hard" },
  { slug: "jm",             name: "Dunn's River Falls",      level: "hard" },
  { slug: "sk",             name: "Bratislava Castle",       level: "hard" },

  // ===== IMPOSSIBLE (25) — generic texture on crop OR ultra-obscure worldwide =====
  { slug: "fo",             name: "Mulafossur Waterfall",    level: "impossible" },
  { slug: "tm",             name: "Darvaza Gas Crater",      level: "impossible" },
  { slug: "mg",             name: "Avenue of the Baobabs",   level: "impossible" },
  { slug: "gh",             name: "Larabanga Mosque",        level: "impossible" },
  { slug: "al",             name: "Gjirokaster old town",    level: "impossible" },
  { slug: "ba",             name: "Stari Most, Mostar",      level: "impossible" },
  { slug: "gy",             name: "Kaieteur Falls",          level: "impossible" },
  { slug: "ml",             name: "Great Mosque of Djenne",  level: "impossible" },
  { slug: "sd",             name: "Pyramids of Meroe",       level: "impossible" },
  { slug: "tj",             name: "Iskanderkul Lake",        level: "impossible" },
  { slug: "kg",             name: "Burana Tower",            level: "impossible" },
  { slug: "bt",             name: "Tiger's Nest Monastery",  level: "impossible" },
  { slug: "la",             name: "Kuang Si Falls",          level: "impossible" },
  { slug: "mt",             name: "Mdina city gate",         level: "impossible" },
  { slug: "mk",             name: "Church of Ohrid",         level: "impossible" },
  { slug: "am",             name: "Khor Virap Monastery",    level: "impossible" },
  { slug: "na",             name: "Deadvlei, Sossusvlei",    level: "impossible" },
  { slug: "sn",             name: "Renaissance Monument",    level: "impossible" },
  { slug: "py",             name: "Palacio de los Lopez",    level: "impossible" },
  { slug: "sr",             name: "Paramaribo Cathedral",    level: "impossible" },
  { slug: "bn",             name: "Sultan Omar Ali Mosque",  level: "impossible" },
  { slug: "mn",             name: "Genghis Khan Statue",     level: "impossible" },
  { slug: "lv",             name: "Rundale Palace",          level: "impossible" },
  { slug: "md",             name: "Old Orhei monastery",     level: "impossible" },
  { slug: "pg",             name: "Tavurvur volcano",        level: "impossible" },
];

export const LANDMARKZOOM_LEVELS = ["easy", "medium", "hard", "impossible"];
