// E182 «Guess the Landmark by Emoji» — 100 landmarks · 25/tier
// VO: sfx/e182-<id>.wav
export const LANDMARK_EMOJI = [
  // ===== EASY =====
  { id: "eiffel-tower", title: "Eiffel Tower", emojis: "🗼🥐", level: "easy" },
  { id: "statue-of-liberty", title: "Statue of Liberty", emojis: "🗽🔥", level: "easy" },
  { id: "great-wall-of-china", title: "Great Wall of China", emojis: "🧱🐉", level: "easy" },
  { id: "taj-mahal", title: "Taj Mahal", emojis: "🕌🤍", level: "easy" },
  { id: "colosseum", title: "Colosseum", emojis: "🏛⚔", level: "easy" },
  { id: "big-ben", title: "Big Ben", emojis: "🕰🎩", level: "easy" },
  { id: "christ-the-redeemer", title: "Christ the Redeemer", emojis: "🙏⛰", level: "easy" },
  { id: "sydney-opera-house", title: "Sydney Opera House", emojis: "🎭🐨", level: "easy" },
  { id: "leaning-tower-of-pisa", title: "Leaning Tower of Pisa", emojis: "🍕📐", level: "easy" },
  { id: "golden-gate-bridge", title: "Golden Gate Bridge", emojis: "🌉🧡", level: "easy" },
  { id: "mount-rushmore", title: "Mount Rushmore", emojis: "🏔🦅", level: "easy" },
  { id: "stonehenge", title: "Stonehenge", emojis: "🪨🌀", level: "easy" },
  { id: "pyramids-of-giza", title: "Pyramids of Giza", emojis: "🔺🐫", level: "easy" },
  { id: "machu-picchu", title: "Machu Picchu", emojis: "⛰🦙", level: "easy" },
  { id: "burj-khalifa", title: "Burj Khalifa", emojis: "🏢🐪", level: "easy" },
  { id: "sagrada-familia", title: "Sagrada Família", emojis: "⛪🎨", level: "easy" },
  { id: "petra", title: "Petra", emojis: "🏜🌹", level: "easy" },
  { id: "angkor-wat", title: "Angkor Wat", emojis: "🛕🌴", level: "easy" },
  { id: "mount-fuji", title: "Mount Fuji", emojis: "🗻🌸", level: "easy" },
  { id: "brandenburg-gate", title: "Brandenburg Gate", emojis: "🏛🐻", level: "easy" },
  { id: "london-eye", title: "London Eye", emojis: "🎡👑", level: "easy" },
  { id: "arc-de-triomphe", title: "Arc de Triomphe", emojis: "🎖🥐", level: "easy" },
  { id: "niagara-falls", title: "Niagara Falls", emojis: "💦🍁", level: "easy" },
  { id: "hollywood-sign", title: "Hollywood Sign", emojis: "🎬🌴", level: "easy" },
  { id: "neuschwanstein-castle", title: "Neuschwanstein Castle", emojis: "🏰🦢", level: "easy" },
  // ===== MEDIUM =====
  { id: "moai", title: "Moai", emojis: "🗿🌊", level: "medium" },
  { id: "tower-of-london", title: "Tower of London", emojis: "🏰💎", level: "medium" },
  { id: "chichen-itza", title: "Chichén Itzá", emojis: "🔺🐆", level: "medium" },
  { id: "parthenon", title: "Parthenon", emojis: "🏛🦉", level: "medium" },
  { id: "saint-basils-cathedral", title: "Saint Basil's Cathedral", emojis: "⛪🪆", level: "medium" },
  { id: "golden-temple", title: "Golden Temple", emojis: "🛕💧", level: "medium" },
  { id: "petronas-towers", title: "Petronas Towers", emojis: "🏢🌴", level: "medium" },
  { id: "cn-tower", title: "CN Tower", emojis: "🗼🍁", level: "medium" },
  { id: "space-needle", title: "Space Needle", emojis: "🗼🛸", level: "medium" },
  { id: "gateway-arch", title: "Gateway Arch", emojis: "🌈🦅", level: "medium" },
  { id: "brooklyn-bridge", title: "Brooklyn Bridge", emojis: "🌉🗽", level: "medium" },
  { id: "tower-bridge", title: "Tower Bridge", emojis: "🌉🎩", level: "medium" },
  { id: "matterhorn", title: "Matterhorn", emojis: "🏔🍫", level: "medium" },
  { id: "table-mountain", title: "Table Mountain", emojis: "🏔🦁", level: "medium" },
  { id: "victoria-falls", title: "Victoria Falls", emojis: "💦🦏", level: "medium" },
  { id: "iguazu-falls", title: "Iguazú Falls", emojis: "💦🦜", level: "medium" },
  { id: "alhambra", title: "Alhambra", emojis: "🕌🌙", level: "medium" },
  { id: "blue-mosque", title: "Blue Mosque", emojis: "🕌💙", level: "medium" },
  { id: "marina-bay-sands", title: "Marina Bay Sands", emojis: "🏨🦁", level: "medium" },
  { id: "sheikh-zayed-mosque", title: "Sheikh Zayed Mosque", emojis: "🕌🐫", level: "medium" },
  { id: "chrysler-building", title: "Chrysler Building", emojis: "🏢🚗", level: "medium" },
  { id: "willis-tower", title: "Willis Tower", emojis: "🏢🌭", level: "medium" },
  { id: "little-mermaid", title: "The Little Mermaid", emojis: "🧜🪨", level: "medium" },
  { id: "st-marks-basilica", title: "St. Mark's Basilica", emojis: "⛪🛶", level: "medium" },
  { id: "mount-kilimanjaro", title: "Mount Kilimanjaro", emojis: "🏔🐘", level: "medium" },
  // ===== HARD =====
  { id: "forbidden-city", title: "Forbidden City", emojis: "🏯🐉", level: "hard" },
  { id: "himeji-castle", title: "Himeji Castle", emojis: "🏯🌸", level: "hard" },
  { id: "potala-palace", title: "Potala Palace", emojis: "🛕🏔", level: "hard" },
  { id: "meteora", title: "Meteora", emojis: "🛕🪨", level: "hard" },
  { id: "park-guell", title: "Park Güell", emojis: "🦎🎨", level: "hard" },
  { id: "sacre-coeur", title: "Sacré-Cœur", emojis: "⛪💗", level: "hard" },
  { id: "mont-saint-michel", title: "Mont-Saint-Michel", emojis: "🏰🌊", level: "hard" },
  { id: "st-peters-basilica", title: "St. Peter's Basilica", emojis: "⛪✝", level: "hard" },
  { id: "westminster-abbey", title: "Westminster Abbey", emojis: "⛪👑", level: "hard" },
  { id: "burj-al-arab", title: "Burj Al Arab", emojis: "⛵🐪", level: "hard" },
  { id: "gateway-of-india", title: "Gateway of India", emojis: "🏛🐘", level: "hard" },
  { id: "qutub-minar", title: "Qutub Minar", emojis: "🗼🕌", level: "hard" },
  { id: "wat-arun", title: "Wat Arun", emojis: "🛕🌅", level: "hard" },
  { id: "shwedagon-pagoda", title: "Shwedagon Pagoda", emojis: "🛕💛", level: "hard" },
  { id: "tokyo-tower", title: "Tokyo Tower", emojis: "🗼🗾", level: "hard" },
  { id: "oriental-pearl-tower", title: "Oriental Pearl Tower", emojis: "🗼🔮", level: "hard" },
  { id: "louvre-pyramid", title: "Louvre Pyramid", emojis: "🔺🎨", level: "hard" },
  { id: "notre-dame", title: "Notre-Dame", emojis: "⛪🔔", level: "hard" },
  { id: "cologne-cathedral", title: "Cologne Cathedral", emojis: "⛪🍺", level: "hard" },
  { id: "milan-cathedral", title: "Milan Cathedral", emojis: "⛪🧵", level: "hard" },
  { id: "reichstag", title: "Reichstag", emojis: "🏛🕊", level: "hard" },
  { id: "guggenheim-bilbao", title: "Guggenheim Bilbao", emojis: "🏛🖼", level: "hard" },
  { id: "gardens-by-the-bay", title: "Gardens by the Bay", emojis: "🌳🦁", level: "hard" },
  { id: "borobudur", title: "Borobudur", emojis: "🛕🌋", level: "hard" },
  { id: "palace-of-versailles", title: "Palace of Versailles", emojis: "🏰⛲", level: "hard" },
  // ===== IMPOSSIBLE =====
  { id: "chateau-de-chambord", title: "Château de Chambord", emojis: "🏰🦌", level: "impossible" },
  { id: "edinburgh-castle", title: "Edinburgh Castle", emojis: "🏰🥃", level: "impossible" },
  { id: "prague-castle", title: "Prague Castle", emojis: "🏰🍺", level: "impossible" },
  { id: "belem-tower", title: "Belém Tower", emojis: "🗼⚓", level: "impossible" },
  { id: "tower-of-hercules", title: "Tower of Hercules", emojis: "🗼🔦", level: "impossible" },
  { id: "alcazar-of-segovia", title: "Alcázar of Segovia", emojis: "🏰🚢", level: "impossible" },
  { id: "hagia-sophia", title: "Hagia Sophia", emojis: "🕌🏺", level: "impossible" },
  { id: "topkapi-palace", title: "Topkapı Palace", emojis: "🏯🗡", level: "impossible" },
  { id: "mezquita-cordoba", title: "Mezquita of Córdoba", emojis: "🕌🌴", level: "impossible" },
  { id: "casa-batllo", title: "Casa Batlló", emojis: "🦴🎨", level: "impossible" },
  { id: "pena-palace", title: "Pena Palace", emojis: "🏰🌈", level: "impossible" },
  { id: "bran-castle", title: "Bran Castle", emojis: "🏰🦇", level: "impossible" },
  { id: "the-kremlin", title: "The Kremlin", emojis: "🏰⭐", level: "impossible" },
  { id: "winter-palace", title: "Winter Palace", emojis: "🏛❄", level: "impossible" },
  { id: "abu-simbel", title: "Abu Simbel", emojis: "🗿🏜", level: "impossible" },
  { id: "karnak-temple", title: "Karnak Temple", emojis: "🛕🏜", level: "impossible" },
  { id: "valley-of-the-kings", title: "Valley of the Kings", emojis: "⚰🏜", level: "impossible" },
  { id: "great-sphinx", title: "Great Sphinx of Giza", emojis: "🦁🔺", level: "impossible" },
  { id: "leptis-magna", title: "Leptis Magna", emojis: "🏛🏜", level: "impossible" },
  { id: "ephesus", title: "Ephesus", emojis: "🏛📜", level: "impossible" },
  { id: "pompeii", title: "Pompeii", emojis: "🏛🌋", level: "impossible" },
  { id: "delphi", title: "Delphi", emojis: "🏛🔮", level: "impossible" },
  { id: "bagan", title: "Bagan", emojis: "🛕🎈", level: "impossible" },
  { id: "terracotta-army", title: "Terracotta Army", emojis: "🏺🗡", level: "impossible" },
  { id: "leshan-giant-buddha", title: "Leshan Giant Buddha", emojis: "🗿⛰", level: "impossible" },
];
