// E16 «Guess the Country by Landmark» — did-you-know facts, ≤70 chars each, verified.
// Keyed by the exact LANDMARKS[].key. One fact per landmark, about the landmark itself.
export const LANDMARK_FACTS = {
  // ---------- EASY ----------
  "fr": "It can grow up to 15 cm taller on hot summer days",
  "us-liberty": "Its copper skin turned green from decades of weather",
  "gb": "Big Ben is really the nickname of the bell inside",
  "eg": "The Great Pyramid was Earth's tallest for millennia",
  "it-colosseum": "It could hold around 50,000 roaring spectators",
  "in-taj": "Around 20,000 workers built it over some 20 years",
  "au": "Its roof is covered in over one million white tiles",
  "br": "The statue itself stands about 30 metres tall",
  "cn-greatwall": "Its many branches stretch over 21,000 km in all",
  "jp-fuji": "It last erupted over 300 years ago, back in 1707",
  "ae": "At 828 metres it is the tallest building on Earth",
  "cl": "Some of its Moai statues weigh more than 80 tonnes",
  "gr": "Its blue domes sit on cliffs above a sunken volcano",
  "de": "It is crowned by a chariot pulled by four horses",
  "es": "Begun in 1882, this church is still unfinished today",
  "my": "A skybridge links the towers on floors 41 and 42",
  "ca": "About 2,400 tonnes of water pour over it each second",
  "ru": "Its swirling colourful domes were finished in 1561",
  "nl": "Its 19 windmills once drained water from the land",
  "us-goldengate": "Its towers rise about 227 metres above the water",
  "sa": "Its black silk cover is replaced once every year",
  "za-table": "Its flat top often wears a cloud 'tablecloth'",
  "us-rushmore": "Four presidents' faces are carved into the granite",
  "kh": "It is the largest religious monument in the world",
  "it-pisa": "The tower leans because its founding soil is soft",

  // ---------- MEDIUM ----------
  "pe": "The Inca built it around 1450 without any mortar",
  "jo": "Its Treasury was carved into a rose-red rock cliff",
  "mx": "Its main pyramid has 365 steps, one for each day",
  "tr": "Its giant dome has stood for nearly 1,500 years",
  "th": "It was the royal home for about 150 years",
  "sg": "A ship-shaped park sits atop its three towers",
  "ch": "This Alpine peak rises to about 4,478 metres",
  "dk": "This bronze statue is just 1.25 metres tall",
  "be": "Its nine spheres form an iron crystal, hugely enlarged",
  "cz": "Work on this stone bridge began back in 1357",
  "pt-belem": "It once guarded the entrance to Lisbon's harbour",
  "at": "This grand palace has over 1,400 rooms",
  "hu": "It has 691 rooms beneath a soaring central dome",
  "ie": "These sea cliffs rise up to about 214 metres high",
  "no": "Waterfalls like the Seven Sisters plunge into it",
  "jp-fushimi": "Thousands of red gates line its mountain paths",
  "id": "It is the world's largest Buddhist temple",
  "vn": "Its waters hide nearly 2,000 limestone islands",
  "ma": "Its minaret rises about 77 metres over Marrakech",
  "hr": "Its stone walls run nearly 2 km around the old town",
  "pl": "Polish kings were crowned here for centuries",
  "ar": "It has around 275 separate falls along its edge",
  "kr": "First built in 1395, it was later rebuilt in full",
  "se": "The Nobel Prize banquet is held in its great hall",
  "za-goodhope": "It marks the rocky south-west tip of the peninsula",

  // ---------- HARD ----------
  "mm": "Over 2,000 ancient temples still dot its plains",
  "uz": "Its three grand old schools frame a public square",
  "is": "Its design echoes Iceland's basalt lava columns",
  "lk": "This palace sits atop a 200-metre-high rock column",
  "ge": "It stands over 2,000 metres up below Mount Kazbek",
  "az": "By night, screens make the towers look like flames",
  "me": "Steep mountains ring this deep, winding bay",
  "si": "A tiny island church sits in the middle of the lake",
  "np": "It is one of the largest Buddhist stupas on Earth",
  "et": "Its churches were carved down into solid rock",
  "pt-pena": "Its bright red and yellow walls crown a hilltop",
  "cn-zhangjiajie": "Its towering stone pillars inspired 'Avatar'",
  "bo": "It is the world's largest salt flat, over 10,000 km2",
  "ir": "Morning light fills it with rainbow colours",
  "ee": "Its medieval old town is remarkably well preserved",
  "fi": "Its bright white form is topped with green domes",
  "lt": "This red-brick castle sits on a lake island",
  "ph": "These rice terraces were carved by hand long ago",
  "om": "Its prayer hall holds one huge handmade carpet",
  "qa": "It was designed by the architect I. M. Pei",
  "ro": "It is often linked to the Dracula legend",
  "in-hawamahal": "Its facade has 953 small windows for cool air",
  "gt": "Its tallest temple rises about 70 metres high",
  "jm": "Visitors climb these falls like a stone staircase",
  "sk": "Its four corner towers overlook the Danube river",

  // ---------- IMPOSSIBLE ----------
  "fo": "A waterfall here drops straight into the ocean",
  "tm": "This fiery gas crater has burned for decades",
  "mg": "Some of these baobab trees are around 800 years old",
  "gh": "This white mud-and-stick mosque is centuries old",
  "al": "Its old stone houses earn it the name 'city of stone'",
  "ba": "Divers leap from this high arched stone bridge",
  "gy": "One of the world's most powerful single-drop waterfalls",
  "ml": "It is the world's largest mud-brick building",
  "sd": "These steep, narrow pyramids were royal tombs",
  "tj": "This mountain lake is named after Alexander",
  "kg": "This old minaret tower stands on the Silk Road",
  "bt": "This monastery clings to a cliff high in the hills",
  "la": "Its turquoise pools cascade down forest terraces",
  "mt": "This walled town was once Malta's capital",
  "mk": "Its church overlooks one of Europe's oldest lakes",
  "am": "It looks out toward snow-capped Mount Ararat",
  "na": "Dead trees stand on white clay among red dunes",
  "sn": "This bronze statue is taller than the Statue of Liberty",
  "py": "This grand white palace is now the seat of government",
  "sr": "It is the largest wooden building in the Americas",
  "bn": "Its main dome is covered in real gold leaf",
  "mn": "This steel horseman statue is 40 metres tall",
  "lv": "This palace was designed by the architect Rastrelli",
  "md": "Monks carved cave churches into these cliffs",
  "pg": "This active volcano rises near the town of Rabaul",
};
