// «Guess the Landmark» v2 — GuessSync · did-you-know facts, ≤70 chars, verified true.
export const LANDMARKS2_FACTS = {
  // EASY
  "arcdetriomphe": "Honors soldiers of the French Revolution and Napoleonic wars",
  "empirestate": "New York skyscraper that was the world's tallest until 1970",
  "stonehenge": "Prehistoric stone circle raised on Salisbury Plain in England",
  "grandcanyon": "Carved by the Colorado River over millions of years in Arizona",
  "everest": "Earth's highest peak at 8,849 m, on the Nepal-Tibet border",
  "sphinx": "Giant limestone lion with a human head, guarding Giza in Egypt",
  "parthenon": "Marble temple to Athena crowning the Acropolis of Athens",
  "stpeters": "Vatican basilica with a dome designed in part by Michelangelo",
  "trevi": "Baroque Rome fountain where coins are tossed for a return trip",
  "neuschwanstein": "Bavarian fairy-tale castle that inspired Disney's palace",
  "towerbridge": "London bascule bridge that lifts to let tall ships pass",
  "uluru": "Huge red sandstone rock sacred to Aboriginal Australians",
  "hollywood": "White letters on Los Angeles hills, first spelled Hollywoodland",
  "buckingham": "London home of the British monarch since Queen Victoria",
  "forbiddencity": "Beijing palace complex of China's emperors for five centuries",
  "terracotta": "Thousands of clay soldiers buried with China's first emperor",
  "victoriafalls": "One of the largest waterfalls, on the Zambezi in Africa",
  "montsaintmichel": "Abbey on a tidal island off the coast of Normandy, France",
  "burjalarab": "Sail-shaped Dubai luxury hotel built on an artificial island",
  "cntower": "Toronto tower that was the world's tallest free-standing one",
  "tokyotower": "Red-and-white Tokyo tower modeled on the Eiffel Tower",
  "notredame": "Gothic Paris cathedral badly damaged by a 2019 fire",
  "whitehouse": "Official residence of the U.S. president in Washington, D.C.",
  "timessquare": "Neon-lit New York junction famed for its New Year's ball drop",
  "louvrepyramid": "Glass pyramid marking the entrance to the Louvre in Paris",

  // MEDIUM
  "colognecathedral": "Twin-spired Gothic cathedral that took over 600 years to finish",
  "sacrecoeur": "White basilica atop Montmartre hill overlooking Paris",
  "alhambra": "Moorish palace and fortress above Granada in southern Spain",
  "milancathedral": "Vast marble cathedral bristling with spires and statues",
  "stmarks": "Byzantine basilica on the main square of Venice, Italy",
  "bluemosque": "Istanbul mosque named for the blue tiles lining its interior",
  "sheikhzayed": "Abu Dhabi's vast white marble mosque with 82 domes",
  "goldentemple": "Gilded Sikh shrine set in a pool at Amritsar, India",
  "watarun": "Bangkok temple with a spire encrusted in porcelain shards",
  "merlion": "Half-lion, half-fish statue that is a symbol of Singapore",
  "gardensbythebay": "Singapore park with towering tree-shaped Supertrees",
  "shwedagon": "Gold-plated Buddhist stupa dominating Yangon, Myanmar",
  "potala": "Hilltop palace in Lhasa, former home of the Dalai Lama",
  "himeji": "White Japanese castle nicknamed the White Heron Castle",
  "kinkakuji": "Kyoto Zen temple with two floors covered in gold leaf",
  "kamakurabuddha": "Great bronze Buddha that has sat outdoors since the 1400s",
  "sugarloaf": "Peak rising over Rio's harbor, reached by cable car",
  "peritomoreno": "Advancing glacier in Argentina's Patagonia that calves ice",
  "teotihuacan": "Ancient Mexican city of vast Sun and Moon pyramids",
  "chrysler": "Art Deco New York skyscraper with a gleaming steel crown",
  "brooklynbridge": "Historic suspension bridge over New York's East River",
  "spaceneedle": "Saucer-topped Seattle tower built for the 1962 World's Fair",
  "gatewayarch": "630-foot stainless steel arch on the St. Louis riverfront",
  "lincolnmemorial": "Marble Washington temple housing a seated Lincoln statue",
  "toweroflondon": "Riverside London fortress that guards the Crown Jewels",

  // HARD
  "meteora": "Greek monasteries perched atop towering natural rock pillars",
  "pontevecchio": "Florence's medieval bridge lined with goldsmiths' shops",
  "alberobello": "Italian town of trulli, cone-roofed whitewashed stone huts",
  "cinqueterre": "Five colorful fishing villages on Italy's rugged coast",
  "chambord": "France's largest Loire Valley chateau, with 440 rooms",
  "predjama": "Slovenian castle built into the mouth of a cliffside cave",
  "plitvice": "Croatian park of terraced lakes linked by cascading falls",
  "rila": "Bulgaria's largest monastery, ringed by painted arcades",
  "peles": "Neo-Renaissance royal castle in Romania's Carpathians",
  "fishermansbastion": "Fairy-tale terrace with seven turrets over Budapest",
  "malbork": "The world's largest brick castle, built by Teutonic Knights",
  "savioronblood": "St. Petersburg church of onion domes on a mosaic facade",
  "pamukkale": "Turkey's white terraces of mineral pools on a hillside",
  "cappadocia": "Turkish region of fairy chimneys famed for balloon rides",
  "wadirum": "Jordan's red desert of sandstone valleys, a film backdrop",
  "persepolis": "Ceremonial capital of ancient Persia, near Shiraz, Iran",
  "goldenrock": "Gilded boulder in Myanmar balanced at a cliff edge",
  "batucaves": "Malaysian cave temple below a giant golden Murugan statue",
  "prambanan": "Towering 9th-century Hindu temple complex on Java",
  "tanahlot": "Balinese sea temple set on a rock lashed by the tide",
  "chocolatehills": "Hundreds of grassy mounds that turn brown in the Philippines",
  "leshanbuddha": "71-meter Buddha carved into a cliff in Sichuan, China",
  "guggenheimbilbao": "Titanium-clad Frank Gehry art museum in Bilbao, Spain",
  "segoviaalcazar": "Ship-shaped Spanish castle said to inspire a Disney one",
  "diocletian": "Roman emperor's palace forming the core of Split, Croatia",

  // IMPOSSIBLE
  "vardzia": "Cave monastery of hundreds of rooms cut into a Georgian cliff",
  "tatev": "Armenian monastery reached by one of the longest cable cars",
  "bandeamir": "Afghanistan's deep-blue lakes dammed by natural mineral walls",
  "chandbaori": "One of India's deepest stepwells, with 3,500 stairs",
  "ninearchbridge": "Colonial-era stone rail viaduct amid Sri Lanka's tea hills",
  "kelimutu": "Indonesian volcano with three crater lakes of shifting colors",
  "danxia": "China's striped rainbow hills of layered colored sandstone",
  "roraima": "Flat-topped tabletop mountain rising above Venezuela's jungle",
  "marblecaves": "Chilean caverns of swirling blue-veined marble over a lake",
  "canocristales": "Colombian river that turns bright red from aquatic plants",
  "rainbowmountain": "Peru's Andean ridge banded in mineral stripes of color",
  "semucchampey": "Guatemalan limestone pools stacked over an underground river",
  "giantscauseway": "Northern Ireland's tens of thousands of basalt columns",
  "eileandonan": "Scottish island castle reached by a stone footbridge",
  "preikestolen": "Norwegian cliff plateau towering above the Lysefjord",
  "kronborg": "Danish castle that is the Elsinore setting of Hamlet",
  "suomenlinna": "Sea fortress on islands guarding Helsinki harbor",
  "belogradchik": "Bulgarian fortress woven among strange red rock formations",
  "ostrog": "Montenegrin monastery set into a sheer vertical rock face",
  "rozafa": "Hilltop castle above Shkoder wrapped in Albanian legend",
  "greatzimbabwe": "Vast dry-stone ruins that gave Zimbabwe its name",
  "aitbenhaddou": "Moroccan mud-brick village used in many films and shows",
  "chefchaouen": "Moroccan mountain town painted in shades of blue",
  "fishrivercanyon": "One of the largest canyons on Earth, in southern Namibia",
  "lakeretba": "Senegal's lake turned pink by salt-loving microbes",
};
