// Shared logo facts for E01/E05/E08 — one verified ≤70-char fact per logo, shown on reveal.
export const LOGO_FACTS = {
  "blender": "Free open-source 3D creation software.",
  "supercell": "Finnish studio behind Clash of Clans.",
  // ===== E01 / LOGOS =====
  "google": "Started as a 1996 research project called BackRub.",
  "mcdonalds": "Fast-food giant that opened its first store in 1940.",
  "instagram": "Photo app launched in 2010; Facebook bought it in 2012.",
  "adidas": "German sportswear brand founded in 1949.",
  "android": "Mobile OS bought by Google in 2005.",
  "starbucks": "Coffee chain founded in Seattle in 1971.",
  "gmail": "Google's email service, launched on April 1, 2004.",
  "snapchat": "Disappearing-photo app launched in 2011.",
  "ferrari": "Italian carmaker; Enzo Ferrari built its first car in 1947.",
  "tesla": "Electric carmaker founded in 2003, named after Nikola Tesla.",
  "ikea": "Swedish furniture giant founded in 1943.",
  "googlemaps": "Google's mapping service, launched in 2005.",
  "spotify": "Music streaming service launched in Sweden in 2008.",
  "googleplay": "Google's app store, launched in 2012.",
  "shell": "Anglo-Dutch oil company; logo is a scallop shell.",
  "lamborghini": "Italian supercar maker founded by a tractor builder in 1963.",
  "ebay": "Online auction site founded in 1995.",
  "nokia": "Finnish firm that started as a paper mill in 1865.",
  "dhl": "Courier named after founders Dalsey, Hillblom, Lynn (1969).",
  "huawei": "Chinese tech giant founded in 1987.",
  "reebok": "Named after the rhebok, a South African antelope.",
  "nvidia": "GPU maker founded in 1993.",
  "chevrolet": "American carmaker founded in 1911.",
  "googletranslate": "Google's translation service, launched in 2006.",
  "spacex": "Rocket company founded by Elon Musk in 2002.",
  "mazda": "Japanese carmaker founded in 1920.",
  "xiaomi": "Chinese electronics maker founded in 2010.",
  "applemusic": "Apple's streaming service, launched in 2015.",
  "fila": "Sportswear brand founded in Italy in 1911.",
  "googlephotos": "Google's photo storage service, launched in 2015.",
  "qatarairways": "Qatar's flag carrier, founded in 1993.",
  "siemens": "German industrial giant founded in 1847.",
  "duolingo": "Language-learning app with an owl, launched in 2012.",
  "newbalance": "American shoe brand founded in Boston in 1906.",
  "twitch": "Live-streaming platform bought by Amazon in 2014.",
  "citroen": "French carmaker founded in 1919.",
  "lidl": "German discount supermarket chain.",
  "pubg": "Battle-royale game released in 2017.",
  "vodafone": "British telecom company founded in 1984.",
  "chrysler": "American carmaker founded in 1925.",
  "etsy": "Online marketplace for handmade goods, founded 2005.",
  "googlemeet": "Google's video-calling service.",
  "icloud": "Apple's cloud storage service, launched in 2011.",
  "maserati": "Italian luxury carmaker founded in 1914.",
  "soundcloud": "Audio-sharing platform founded in Berlin in 2007.",
  "appletv": "Apple's streaming device and service.",
  "garmin": "GPS device maker founded in 1989.",
  "ryanair": "Irish low-cost airline founded in 1984.",
  "airfrance": "France's flag carrier, founded in 1933.",
  "delta": "US airline founded in 1925 as a crop-dusting company.",
  "epicgames": "Game studio behind Fortnite and Unreal Engine.",
  "orange": "French telecom company.",
  "safari": "Apple's web browser, first shipped in 2003.",
  "tumblr": "Microblogging platform launched in 2007.",
  "unitedairlines": "Major US airline with roots back to 1926.",
  "vimeo": "Video platform founded in 2004.",
  "yelp": "Business-review site founded in 2004.",
  "wechat": "Chinese super-app launched by Tencent in 2011.",
  "coinbase": "Cryptocurrency exchange founded in 2012.",
  "oneplus": "Chinese smartphone maker founded in 2013.",
  "cashapp": "Payment app made by Block (Square), launched 2013.",
  "sennheiser": "German audio-gear maker founded in 1945.",
  "vivo": "Chinese smartphone brand.",
  "autocad": "Autodesk's design software, released in 1982.",
  "klarna": "Swedish buy-now-pay-later company, founded 2005.",
  "qualcomm": "US chipmaker founded in 1985.",
  "southwestairlines": "US low-cost airline founded in 1967.",
  "grammarly": "Writing-assistant tool founded in 2009.",
  "duckduckgo": "Privacy-focused search engine, launched in 2008.",
  "rakuten": "Japanese e-commerce giant founded in 1997.",
  "stripe": "Online payments company founded in 2010.",
  "razer": "Gaming-hardware brand founded in 2005.",
  "unity": "Game engine first released in 2005.",
  "stackoverflow": "Q&A site for programmers, launched in 2008.",
  "unrealengine": "Epic Games' engine, first used in 1998.",
  "akamai": "Content delivery network company founded in 1998.",
  "centos": "Free Linux distribution based on Red Hat.",
  "flask": "Python web framework, first released in 2010.",
  "jenkins": "Open-source automation server, forked from Hudson in 2011.",
  "ollama": "Tool to run large language models locally.",
  "splunk": "Machine-data analytics platform founded in 2003.",
  "auth0": "Identity and login platform founded in 2013.",
  "mullvad": "Swedish privacy VPN launched in 2009.",
  "rabbitmq": "Open-source message-broker software.",
  "suse": "German enterprise Linux company founded in 1992.",
  "clickhouse": "Column database open-sourced by Yandex in 2016.",
  "neo4j": "Graph database created in Sweden in 2007.",
  "couchbase": "NoSQL database formed by a 2011 merger.",
  "influxdb": "Time-series database founded in 2012.",
  "pocketbase": "Open-source backend in a single Go file.",
  "scaleway": "French cloud provider founded in 1999.",
  "drizzle": "Lightweight TypeScript ORM.",
  "nxp": "Dutch chipmaker spun off from Philips in 2006.",
  "saltproject": "Open-source infrastructure automation tool.",
  "apachedruid": "Open-source real-time analytics database.",
  "budibase": "Open-source low-code app builder, founded 2019.",
  "dvc": "Data Version Control — Git for machine-learning data.",
  "istio": "Open-source service mesh for Kubernetes.",
  "nordicsemiconductor": "Norwegian chipmaker known for Bluetooth chips.",
  "rollbar": "Error-monitoring service for developers.",

  // ===== E05 / LOGOS2 =====
  "apple": "Tech giant founded by Jobs and Wozniak in 1976.",
  "youtube": "Video platform founded in 2005; Google bought it in 2006.",
  "nike": "US sportswear brand; name is the Greek goddess of victory.",
  "samsung": "South Korean conglomerate founded in 1938.",
  "mastercard": "Payment network founded in 1966.",
  "visa": "Payment network that grew out of BankAmericard.",
  "x": "Social platform formerly known as Twitter.",
  "paypal": "Online payments company founded in 1998.",
  "toyota": "Japanese carmaker founded in 1937.",
  "burgerking": "Fast-food chain founded in 1954.",
  "telegram": "Messaging app launched in 2013.",
  "honda": "Japanese carmaker and the world's top engine maker.",
  "volkswagen": "German carmaker; name means 'people's car'.",
  "porsche": "German sports carmaker founded in 1931.",
  "uber": "Ride-hailing company founded in 2009.",
  "puma": "German sportswear brand founded in 1948.",
  "hyundai": "South Korean carmaker founded in 1967.",
  "pinterest": "Image-pinning platform launched in 2010.",
  "boeing": "American aircraft maker founded in 1916.",
  "panasonic": "Japanese electronics giant founded in 1918.",
  "suzuki": "Japanese carmaker that began making looms in 1909.",
  "airbnb": "Home-rental platform founded in 2008.",
  "dell": "US computer maker founded in a dorm room in 1984.",
  "jeep": "American off-road brand with World War II roots.",
  "discord": "Chat app for communities, launched in 2015.",
  "nikon": "Japanese camera maker founded in 1917.",
  "aliexpress": "Alibaba's global online marketplace, launched 2010.",
  "beats": "Headphone brand bought by Apple in 2014.",
  "firefox": "Mozilla's web browser, first released in 2004.",
  "imdb": "Movie database that started in 1990; Amazon owns it.",
  "renault": "French carmaker founded in 1899.",
  "3m": "US firm behind Post-it Notes and Scotch tape.",
  "fiat": "Italian carmaker founded in 1899.",
  "peugeot": "French carmaker that began making tools in 1810.",
  "bentley": "British luxury carmaker founded in 1919.",
  "hbo": "US premium TV channel launched in 1972.",
  "mini": "British small-car brand now owned by BMW.",
  "sega": "Japanese game company; made the Genesis console.",
  "target": "US retail chain founded in 1902.",
  "cisco": "Networking-equipment giant founded in 1984.",
  "fitbit": "Fitness-tracker brand bought by Google in 2021.",
  "googlepay": "Google's mobile payment service.",
  "jbl": "US audio brand founded in 1946.",
  "opera": "Web browser first released in Norway in 1995.",
  "tripadvisor": "Travel-review website founded in 2000.",
  "mclaren": "British supercar and F1 brand.",
  "github": "Code-hosting platform bought by Microsoft in 2018.",
  "skoda": "Czech carmaker now owned by Volkswagen.",
  "audible": "Amazon's audiobook service, founded in 1995.",
  "dropbox": "Cloud-storage service founded in 2007.",
  "konami": "Japanese game maker behind Metal Gear.",
  "quora": "Question-and-answer site founded in 2009.",
  "steam": "Valve's PC game store, launched in 2003.",
  "turkishairlines": "Turkey's flag carrier, founded in 1933.",
  "valorant": "Riot Games' tactical shooter, released in 2020.",
  "wordpress": "Open-source website software launched in 2003.",
  "acer": "Taiwanese computer maker founded in 1976.",
  "bankofamerica": "One of the largest US banks.",
  "klm": "Dutch airline; the world's oldest still flying (1919).",
  "paramountplus": "Paramount's streaming service.",
  "easyjet": "British low-cost airline founded in 1995.",
  "shopify": "E-commerce platform founded in Canada in 2006.",
  "wellsfargo": "US bank with roots in 1852 stagecoach mail.",
  "baidu": "China's biggest search engine, founded in 2000.",
  "mailchimp": "Email-marketing platform founded in 2001.",
  "riotgames": "Studio behind League of Legends, founded 2006.",
  "brave": "Privacy browser that blocks ads by default.",
  "medium": "Online publishing platform founded in 2012.",
  "iberia": "Spain's flag-carrier airline, founded in 1927.",
  "revolut": "British digital bank founded in 2015.",
  "upwork": "Freelance marketplace; Elance and oDesk merged, renamed 2015.",
  "robinhood": "Commission-free trading app founded in 2013.",
  "javascript": "Web programming language created in just 10 days in 1995.",
  "trello": "Kanban board app now owned by Atlassian.",
  "valve": "Game studio behind Half-Life and Steam.",
  "apachekafka": "Open-source streaming platform built at LinkedIn.",
  "coda": "All-in-one document and app tool, founded 2014.",
  "godotengine": "Free open-source game engine.",
  "kubernetes": "Container tool open-sourced by Google in 2014.",
  "perl": "Programming language created by Larry Wall in 1987.",
  "supabase": "Open-source Firebase alternative, founded in 2020.",
  "circleci": "Continuous-integration platform founded in 2011.",
  "prometheus": "Open-source monitoring tool built at SoundCloud.",
  "retool": "Platform for building internal tools, founded 2017.",
  "vultr": "US cloud-hosting provider founded in 2014.",
  "hashicorp": "Infrastructure-tools company behind Terraform.",
  "apacheflink": "Open-source stream-processing framework.",
  "duckdb": "In-process analytics database from CWI, 2019.",
  "mlflow": "Open-source platform for the machine-learning lifecycle.",
  "puppet": "IT configuration-management tool, first released 2005.",
  "apachepulsar": "Open-source messaging and streaming platform.",
  "envoyproxy": "Open-source service proxy built at Lyft.",
  "opsgenie": "Incident-alerting tool bought by Atlassian in 2018.",
  "trpc": "TypeScript library for end-to-end typesafe APIs.",
  "apachenifi": "Open-source tool for automating data flows.",
  "camunda": "German process-automation company founded in 2008.",
  "fauna": "Serverless database company founded in 2012.",
  "linkerd": "Open-source service mesh for Kubernetes.",
  "packer": "HashiCorp tool for building machine images.",
  "scylladb": "Fast Cassandra-compatible database written in C++.",

  // ===== E08 / LOGOS3 =====
  "cocacola": "Soft drink invented by a pharmacist in 1886.",
  "facebook": "Social network launched from Harvard in 2004.",
  "whatsapp": "Messaging app founded in 2009; Facebook bought it in 2014.",
  "tiktok": "Short-video app launched globally in 2018.",
  "netflix": "Started as a DVD-by-mail service in 1997.",
  "googlechrome": "Google's web browser, first released in 2008.",
  "bmw": "German carmaker that started building aircraft engines.",
  "playstation": "Sony's game console, first launched in 1994.",
  "kfc": "Fried-chicken chain founded by Colonel Sanders.",
  "ford": "US carmaker that built the Model T in 1908.",
  "wikipedia": "Free online encyclopedia launched in 2001.",
  "sony": "Japanese electronics giant founded in 1946.",
  "audi": "German carmaker; four rings mark a 1932 merger.",
  "redbull": "Energy-drink brand launched in Austria in 1987.",
  "hp": "Tech company started in a Palo Alto garage in 1939.",
  "lg": "South Korean electronics giant.",
  "intel": "Chipmaker founded in 1968.",
  "zara": "Spanish fast-fashion brand founded in 1975.",
  "fedex": "US courier founded in 1971.",
  "reddit": "Link-sharing community site founded in 2005.",
  "ups": "US package courier founded in 1907.",
  "americanexpress": "Payments firm that began as an express-mail service.",
  "emirates": "Dubai's flag-carrier airline, founded in 1985.",
  "messenger": "Facebook's chat app, split off in 2011.",
  "googledrive": "Google's cloud storage, launched in 2012.",
  "volvo": "Swedish carmaker known for safety, founded 1927.",
  "amd": "US chipmaker founded in 1969.",
  "cadillac": "American luxury car brand owned by GM.",
  "fortnite": "Battle-royale game released by Epic in 2017.",
  "motorola": "US firm that made the first handheld mobile phone.",
  "roblox": "Online game platform launched in 2006.",
  "asus": "Taiwanese computer-hardware maker.",
  "lenovo": "Chinese PC maker that bought IBM's PC unit.",
  "subaru": "Japanese carmaker; name is a star cluster.",
  "bose": "US audio company founded by an MIT professor in 1964.",
  "hsbc": "British bank with Hong Kong and Shanghai roots.",
  "monster": "Energy-drink brand launched in 2002.",
  "underarmour": "US sportswear brand founded in 1996.",
  "carrefour": "French supermarket chain founded in 1959.",
  "dji": "Chinese company that dominates the drone market.",
  "googlecalendar": "Google's scheduling app, launched in 2006.",
  "hbomax": "Warner's streaming service.",
  "leagueoflegends": "Riot's hit game, released in 2009.",
  "shazam": "Music-identifying app now owned by Apple.",
  "zoom": "Video-conferencing service founded in 2011.",
  "britishairways": "UK flag-carrier airline, formed in 1974.",
  "lufthansa": "Germany's flag-carrier airline.",
  "activision": "Game publisher founded in 1979.",
  "binance": "Cryptocurrency exchange founded in 2017.",
  "ea": "US game publisher founded in 1982.",
  "oppo": "Chinese smartphone brand.",
  "rockstargames": "Studio behind Grand Theft Auto.",
  "tesco": "British supermarket chain founded in 1919.",
  "ubisoft": "French game maker founded in 1986.",
  "verizon": "US telecom company formed in 2000.",
  "americanairlines": "One of the world's largest airlines.",
  "singaporeairlines": "Singapore's flag carrier, known for service.",
  "barclays": "British bank with roots back to 1690.",
  "line": "Messaging app hugely popular in Japan.",
  "alipay": "Chinese payment app run by Ant Group.",
  "lyft": "US ride-hailing company founded in 2012.",
  "venmo": "Payment app owned by PayPal.",
  "aircanada": "Canada's flag-carrier airline, founded in 1937.",
  "chase": "Major US bank, part of JPMorgan Chase.",
  "pandora": "US internet-radio pioneer; streaming service launched 2005.",
  "sap": "German enterprise-software giant founded in 1972.",
  "fiverr": "Freelance marketplace founded in 2010.",
  "msi": "Taiwanese maker of gaming PCs and hardware.",
  "jetblue": "US low-cost airline founded in 1998.",
  "sonos": "US smart-speaker company founded in 2002.",
  "viber": "Messaging app now owned by Rakuten.",
  "tidal": "Music-streaming service with hi-fi audio.",
  "signal": "Encrypted messaging app run by a nonprofit.",
  "ubuntu": "Popular Linux distribution, first released in 2004.",
  "wise": "Money-transfer company founded in 2011.",
  "archlinux": "Minimalist do-it-yourself Linux distribution.",
  "datadog": "Cloud-monitoring platform founded in 2010.",
  "hetzner": "German hosting company founded in 1997.",
  "okta": "Identity and login platform founded in 2009.",
  "sentry": "Open-source error-tracking tool.",
  "svelte": "JavaScript UI framework created by Rich Harris.",
  "fastly": "Content delivery network founded in 2011.",
  "qualys": "Cloud security company founded in 1999.",
  "scala": "Programming language that runs on the Java VM.",
  "appwrite": "Open-source backend platform, open-sourced 2019.",
  "hasura": "GraphQL-API engine company founded in 2017.",
  "cockroachlabs": "Distributed SQL database company founded in 2015.",
  "espressif": "Chinese chipmaker behind the ESP32.",
  "planetscale": "Database platform built on Vitess, founded 2018.",
  "rancher": "Open-source Kubernetes management platform.",
  "consul": "HashiCorp tool for service networking.",
  "milvus": "Open-source vector database for AI apps.",
  "parrotsecurity": "Security-focused Linux distribution.",
  "vault": "HashiCorp tool for managing secrets.",
  "appsmith": "Open-source internal-tools builder, founded 2019.",
  "checkmarx": "Application-security company founded in Israel, 2006.",
  "honeybadger": "Error-monitoring tool for developers.",
  "nomad": "HashiCorp tool for scheduling and orchestration.",
  "qdrant": "Open-source vector database founded in 2021.",
  "timescale": "Time-series database built on PostgreSQL, 2017.",
};
