// «Guess the Brand Logo v2» (E-logos5) — one verified TRUE ≤70-char fact per brand, shown on reveal.
export const LOGOS5_FACTS = {
  // ===== EASY =====
  "cnn": "US 24-hour news channel launched by Ted Turner in 1980.",
  "fox": "US TV network launched in 1986 by Rupert Murdoch.",
  "sky": "British satellite broadcaster now owned by Comcast.",
  "nbc": "US TV network whose logo is a colorful peacock.",
  "cbs": "US network nicknamed the 'Eye' network since 1951.",
  "uniqlo": "Japanese casual clothing brand owned by Fast Retailing.",
  "tacobell": "American Tex-Mex fast-food chain founded in 1962.",
  "dolby": "Audio company behind cinema surround sound, founded 1965.",
  "ticketmaster": "World's largest event ticketing company, founded 1976.",
  "discover": "American credit card brand launched by Sears in 1985.",
  "tinder": "Dating app that popularized swiping, launched in 2012.",
  "norton": "Antivirus brand started by Peter Norton in the 1980s.",
  "mcafee": "Antivirus software founded by John McAfee in 1987.",
  "kaspersky": "Russian cybersecurity company founded in 1997.",
  "fujifilm": "Japanese photography and imaging firm founded in 1934.",
  "bosch": "German engineering firm famous for tools and car parts.",
  "generalmotors": "US carmaker behind Chevrolet, GMC, Buick and Cadillac.",
  "samsungpay": "Samsung's mobile payments service launched in 2015.",
  "googleearth": "Google's 3D globe built from satellite imagery.",
  "aldinord": "German discount supermarket chain founded in 1946.",
  "squarespace": "US website-building platform founded in 2003.",
  "googlelens": "Google app that identifies objects through the camera.",
  "shopee": "Singapore online shopping platform launched in 2015.",
  "coursera": "Online course platform founded by Stanford professors.",
  "tripdotcom": "Global travel booking site owned by Trip.com Group.",

  // ===== MEDIUM =====
  "udemy": "Online learning marketplace with courses on any topic.",
  "khanacademy": "Free education nonprofit founded by Salman Khan in 2008.",
  "skillshare": "Online community for creative classes, founded in 2010.",
  "teamviewer": "German remote-desktop software launched in 2005.",
  "trivago": "German hotel search site known for its TV ads.",
  "zalando": "Germany's largest online fashion retailer, from 2008.",
  "vinted": "Lithuanian second-hand clothing marketplace.",
  "wish": "US bargain shopping app known for cheap goods.",
  "instacart": "US grocery delivery service founded in 2012.",
  "justeat": "European online food-ordering and delivery service.",
  "foodpanda": "Asian food-delivery brand owned by Delivery Hero.",
  "zomato": "Indian restaurant discovery and food delivery app.",
  "swiggy": "Indian food and grocery delivery company.",
  "grab": "Southeast Asian ride-hailing and delivery super-app.",
  "gojek": "Indonesian ride-hailing and payments super-app.",
  "square": "US payments company, now part of Block, from 2009.",
  "kickstarter": "US crowdfunding platform for creative projects.",
  "patreon": "Membership platform that pays creators, founded 2013.",
  "gofundme": "US crowdfunding site for personal and charity causes.",
  "buzzfeed": "US digital media brand known for quizzes and lists.",
  "theguardian": "British daily newspaper founded in 1821.",
  "macys": "US department store famous for its NYC parade.",
  "boots": "British pharmacy and beauty retailer founded in 1849.",
  "thenorthface": "US outdoor clothing and gear brand founded in 1966.",
  "surveymonkey": "Online survey tool founded in 1999.",

  // ===== HARD =====
  "deutschebank": "Germany's largest bank, founded in 1870.",
  "goldmansachs": "US investment bank founded in 1869.",
  "westernunion": "US money-transfer company dating back to 1851.",
  "moneygram": "US money-transfer firm and Western Union rival.",
  "n26": "German mobile-only bank founded in 2013.",
  "afterpay": "Australian buy-now-pay-later service from 2014.",
  "zelle": "US bank-to-bank payment network launched in 2017.",
  "mercadopago": "Payments arm of Latin America's Mercado Libre.",
  "phonepe": "Indian digital payments app built on UPI.",
  "razorpay": "Indian online payment gateway founded in 2014.",
  "airtel": "Indian telecom giant operating in Asia and Africa.",
  "jio": "India's largest mobile network, launched by Reliance.",
  "telefonica": "Spanish telecom giant behind the Movistar brand.",
  "movistar": "Telefónica's mobile brand in Spain and Latin America.",
  "telenor": "Norwegian telecom operator founded in 1855.",
  "o2": "Telefónica-owned mobile brand in the UK and Germany.",
  "bt": "British Telecom, the UK's main telecom company.",
  "caterpillar": "US maker of yellow construction machinery.",
  "johndeere": "US maker of green farm tractors, founded in 1837.",
  "generalelectric": "US industrial conglomerate rooted in Edison's work.",
  "unilever": "British consumer-goods giant behind Dove and Lipton.",
  "merck": "German pharma and chemical company dating to 1668.",
  "gsk": "British pharma giant, formerly GlaxoSmithKline.",
  "asda": "British supermarket chain once owned by Walmart.",
  "morrisons": "British supermarket chain founded in 1899.",

  // ===== IMPOSSIBLE =====
  "opensea": "Marketplace for NFTs, founded in 2017.",
  "kucoin": "Global cryptocurrency exchange founded in 2017.",
  "okx": "Global crypto exchange formerly known as OKEx.",
  "insta360": "Chinese maker of 360-degree action cameras.",
  "corsair": "US maker of gaming PC gear and components.",
  "steelseries": "Danish gaming peripherals brand founded in 2001.",
  "hyperx": "Gaming gear brand once part of Kingston Technology.",
  "toptal": "Network linking companies with freelance developers.",
  "gotomeeting": "Online video meeting tool by GoTo, formerly Citrix.",
  "edx": "Online course platform founded by MIT and Harvard.",
  "udacity": "Online tech education platform known for Nanodegrees.",
  "leetcode": "Site for coding-interview practice problems.",
  "hackerrank": "Coding challenge and tech hiring platform.",
  "codecademy": "Interactive site for learning to code online.",
  "freecodecamp": "Free nonprofit platform for learning to code.",
  "avast": "Czech antivirus company founded in 1988.",
  "bitdefender": "Romanian cybersecurity company founded in 2001.",
  "malwarebytes": "US anti-malware software founded in 2008.",
  "anydesk": "German remote-desktop software launched in 2014.",
  "producthunt": "Site for discovering new tech products daily.",
  "replit": "Browser-based coding environment founded in 2016.",
  "codesandbox": "Online code editor for web development.",
  "glitch": "Browser-based app-building and remixing platform.",
  "picpay": "Brazilian digital wallet and payments app.",
  "jsfiddle": "Online playground for testing HTML, CSS and JS.",
};
