// MEGA «Guess the Logo» facts — one verified TRUE <=70-char fact per slug, shown on reveal.
// Reused from source logo fact files (LOGO_FACTS / LOGO4_FACTS / LOGOS5_FACTS / LOGOS6_FACTS / LOGOS7_FACTS).
export const LOGOS_MEGA_FACTS = {
  "google": "Started as a 1996 research project called BackRub.",
  "mcdonalds": "Fast-food giant that opened its first store in 1940.",
  "instagram": "Photo app launched in 2010; Facebook bought it in 2012.",
  "adidas": "German sportswear brand founded in 1949.",
  "android": "Mobile OS bought by Google in 2005.",
  "starbucks": "Coffee chain founded in Seattle in 1971.",
  "gmail": "Google's email service, launched on April 1, 2004.",
  "snapchat": "Disappearing-photo app launched in 2011.",
  "ferrari": "Italian carmaker; Enzo Ferrari built its first car in 1947.",
  "tesla": "Electric carmaker founded in 2003, named after Nikola Tesla.",
  "ikea": "Swedish furniture giant founded in 1943.",
  "spotify": "Music streaming service launched in Sweden in 2008.",
  "shell": "Anglo-Dutch oil company; logo is a scallop shell.",
  "lamborghini": "Italian supercar maker founded by a tractor builder in 1963.",
  "ebay": "Online auction site founded in 1995.",
  "nokia": "Finnish company founded in 1865, it began as a paper mill",
  "dhl": "Courier named after founders Dalsey, Hillblom, Lynn (1969).",
  "huawei": "Chinese tech giant founded in 1987.",
  "nike": "US sportswear brand; name is the Greek goddess of victory.",
  "apple": "Tech giant founded by Jobs and Wozniak in 1976.",
  "youtube": "Video platform founded in 2005; Google bought it in 2006.",
  "samsung": "South Korean conglomerate founded in 1938.",
  "mastercard": "Payment network founded in 1966.",
  "visa": "Payment network that grew out of BankAmericard.",
  "paypal": "Online payments company founded in 1998.",
  "toyota": "Japanese carmaker founded in 1937.",
  "burgerking": "Fast-food chain founded in 1954.",
  "honda": "Japanese carmaker and the world's top engine maker.",
  "volkswagen": "German carmaker; name means 'people's car'.",
  "porsche": "German sports carmaker founded in 1931.",
  "uber": "Ride-hailing company founded in 2009.",
  "hyundai": "South Korean carmaker founded in 1967.",
  "pinterest": "Image-pinning platform launched in 2010.",
  "boeing": "American aircraft maker founded in 1916.",
  "airbnb": "Home-rental platform founded in 2008.",
  "dell": "US computer maker founded in a dorm room in 1984.",
  "cocacola": "Soft drink invented by a pharmacist in 1886.",
  "facebook": "Social network launched from Harvard in 2004.",
  "whatsapp": "Messaging app founded in 2009; Facebook bought it in 2014.",
  "tiktok": "Short-video app launched globally in 2018.",
  "netflix": "Started as a DVD-by-mail service in 1997.",
  "bmw": "German carmaker that started building aircraft engines.",
  "playstation": "Sony's game console, first launched in 1994.",
  "kfc": "Fried-chicken chain founded by Colonel Sanders.",
  "ford": "US carmaker that built the Model T in 1908.",
  "wikipedia": "Free online encyclopedia launched in 2001.",
  "sony": "Japanese electronics giant founded in 1946.",
  "audi": "German carmaker; four rings mark a 1932 merger.",
  "redbull": "Energy-drink brand launched in Austria in 1987.",
  "hp": "Tech company started in a Palo Alto garage in 1939.",
  "lg": "South Korean electronics giant.",
  "intel": "Chipmaker founded in 1968.",
  "zara": "Spanish fast-fashion brand founded in 1975.",
  "fedex": "US courier founded in 1971.",
  "reddit": "Link-sharing community site founded in 2005.",
  "ups": "US package courier founded in 1907.",
  "americanexpress": "Payments firm that began as an express-mail service.",
  "emirates": "Dubai's flag-carrier airline, founded in 1985.",
  "cnn": "US 24-hour news channel launched by Ted Turner in 1980.",
  "fox": "US TV network launched in 1986 by Rupert Murdoch.",
  "nbc": "US TV network whose logo is a colorful peacock.",
  "cbs": "US network nicknamed the 'Eye' network since 1951.",
  "meta": "Facebook's parent company rebranded to Meta in October 2021.",
  "ios": "Apple's iPhone operating system, first released in 2007.",
  "nba": "The National Basketball Association was founded in 1946.",
  "mlb": "Major League Baseball is North America's oldest major sports league.",
  "nhl": "The National Hockey League was founded in 1917.",
  "wwe": "World Wrestling Entertainment stages scripted pro wrestling shows.",
  "premierleague": "England's top football division, launched in 1992.",
  "nasa": "America's space agency, founded in 1958.",
  "handm": "Swedish fast-fashion retailer founded in 1947.",
  "hermes": "French luxury maker of the Birkin and Kelly bags.",
  "marriott": "World's largest hotel company by rooms.",
  "chevrolet": "American carmaker founded in 1911.",
  "spacex": "Rocket company founded by Elon Musk in 2002.",
  "xiaomi": "Chinese electronics maker founded in 2010.",
  "applemusic": "Apple's streaming service, launched in 2015.",
  "googlephotos": "Google's photo storage service, launched in 2015.",
  "qatarairways": "Qatar's flag carrier, founded in 1993.",
  "siemens": "German industrial giant founded in 1847.",
  "duolingo": "Language-learning app with an owl, launched in 2012.",
  "newbalance": "American shoe brand founded in Boston in 1906.",
  "twitch": "Live-streaming platform bought by Amazon in 2014.",
  "citroen": "French carmaker founded in 1919.",
  "lidl": "German discount supermarket chain.",
  "pubg": "Battle-royale game released in 2017.",
  "vodafone": "British telecom company founded in 1984.",
  "chrysler": "American carmaker founded in 1925.",
  "etsy": "Online marketplace for handmade goods, founded 2005.",
  "icloud": "Apple's cloud storage service, launched in 2011",
  "maserati": "Italian luxury carmaker founded in 1914.",
  "soundcloud": "Audio-sharing platform founded in Berlin in 2007.",
  "appletv": "Apple's digital media player and streaming brand",
  "garmin": "GPS device maker founded in 1989.",
  "ryanair": "Irish low-cost airline founded in 1984.",
  "airfrance": "France's flag carrier, founded in 1933.",
  "delta": "US airline founded in 1925 as a crop-dusting company.",
  "nikon": "Japanese camera maker founded in 1917.",
  "aliexpress": "Alibaba's global online marketplace, launched 2010.",
  "beats": "Headphone brand co-founded by rapper Dr. Dre",
  "firefox": "Mozilla's web browser, first released in 2004.",
  "imdb": "Movie database that started in 1990; Amazon owns it.",
  "renault": "French carmaker founded in 1899.",
  "fiat": "Italian carmaker founded in 1899.",
  "peugeot": "French carmaker that began making tools in 1810.",
  "bentley": "British luxury carmaker founded in 1919.",
  "hbo": "US premium TV channel launched in 1972.",
  "mini": "British small-car brand now owned by BMW.",
  "sega": "Japanese game company; made the Genesis console.",
  "target": "US retail chain founded in 1902.",
  "fitbit": "Fitness-tracker brand bought by Google in 2021.",
  "googlepay": "Google's mobile payment service.",
  "jbl": "US audio brand founded in 1946.",
  "mclaren": "British supercar and F1 brand.",
  "github": "Code-hosting platform bought by Microsoft in 2018.",
  "skoda": "Czech carmaker now owned by Volkswagen.",
  "dropbox": "Cloud-storage service founded in 2007.",
  "volvo": "Swedish carmaker known for safety, founded 1927.",
  "amd": "US chipmaker founded in 1969.",
  "cadillac": "American luxury car brand owned by GM.",
  "fortnite": "Battle-royale game released by Epic in 2017.",
  "motorola": "US firm that built the first handheld mobile phone",
  "roblox": "Online game platform launched in 2006.",
  "asus": "Taiwanese computer-hardware maker.",
  "lenovo": "Chinese PC maker that bought IBM's PC unit.",
  "subaru": "Japanese carmaker; name is a star cluster.",
  "bose": "US audio company founded by an MIT professor in 1964.",
  "hsbc": "British bank with Hong Kong and Shanghai roots.",
  "carrefour": "French supermarket chain founded in 1959.",
  "dji": "Chinese company that dominates the drone market.",
  "zoom": "Video-conferencing service founded in 2011.",
  "britishairways": "UK flag-carrier airline, formed in 1974.",
  "lufthansa": "Germany's flag-carrier airline.",
  "activision": "US video game publisher founded in 1979",
  "binance": "Cryptocurrency exchange founded in 2017.",
  "ea": "US game publisher founded in 1982.",
  "huggingface": "AI hub famous for open-source machine learning",
  "udemy": "Online learning marketplace with courses on any topic.",
  "khanacademy": "Free education nonprofit founded by Salman Khan in 2008.",
  "zalando": "Germany's largest online fashion retailer, from 2008.",
  "instacart": "US grocery delivery service founded in 2012.",
  "square": "US payments company, now part of Block, from 2009.",
  "macys": "US department store famous for its NYC parade.",
  "thenorthface": "US outdoor clothing and gear brand founded in 1966.",
  "dazn": "A sports streaming service launched in 2016.",
  "hellofresh": "Meal-kit company delivering recipes and ingredients.",
  "newyorktimes": "US newspaper founded in 1851.",
  "peloton": "Maker of internet-connected exercise bikes.",
  "strava": "Fitness app for tracking runs and rides.",
  "googlemeet": "Google's video-calling service.",
  "epicgames": "Game studio behind Fortnite and Unreal Engine.",
  "orange": "French telecom company.",
  "safari": "Apple's web browser, first released in 2003",
  "tumblr": "Microblogging platform launched in 2007.",
  "unitedairlines": "Major US airline with roots back to 1926.",
  "vimeo": "Video platform founded in 2004.",
  "yelp": "Business-review site founded in 2004.",
  "wechat": "Chinese super-app launched by Tencent in 2011.",
  "coinbase": "Cryptocurrency exchange founded in 2012.",
  "oneplus": "Chinese smartphone brand founded in 2013",
  "cashapp": "Payment app made by Block (Square), launched 2013.",
  "sennheiser": "German audio company founded in 1945",
  "vivo": "Chinese smartphone brand founded in 2009",
  "autocad": "Design software by Autodesk, released in 1982",
  "klarna": "Swedish buy-now-pay-later company, founded 2005.",
  "qualcomm": "US chipmaker founded in 1985.",
  "southwestairlines": "US low-cost airline founded in 1967.",
  "grammarly": "Writing-assistant tool founded in 2009.",
  "duckduckgo": "US search engine that doesn't track its users",
  "rakuten": "Japanese e-commerce giant founded in 1997",
  "stripe": "Online payments company founded in 2010.",
  "razer": "Gaming-hardware brand founded in 2005.",
  "unity": "Game engine first released in 2005.",
  "stackoverflow": "Q&A site for programmers, launched in 2008",
  "unrealengine": "Epic Games' engine, first used in 1998.",
  "konami": "Japanese maker of Metal Gear and Castlevania",
  "quora": "Question-and-answer site founded in 2009.",
  "steam": "Valve's PC game store, launched in 2003.",
  "turkishairlines": "Turkey's flag carrier, founded in 1933.",
  "valorant": "Riot Games' tactical shooter, released in 2020.",
  "wordpress": "Open-source website software launched in 2003.",
  "bankofamerica": "One of the largest US banks.",
  "klm": "Dutch airline; the world's oldest still flying (1919).",
  "paramountplus": "Paramount's streaming service, launched in 2021",
  "easyjet": "British low-cost airline founded in 1995.",
  "shopify": "E-commerce platform founded in Canada in 2006.",
  "wellsfargo": "US bank with roots in 1852 stagecoach mail.",
  "baidu": "China's biggest search engine, founded in 2000",
  "mailchimp": "US email marketing platform founded in 2001",
  "riotgames": "Studio behind League of Legends, founded 2006.",
  "brave": "Privacy browser created by JavaScript's inventor",
  "medium": "Online publishing platform founded in 2012.",
  "revolut": "British digital bank founded in 2015.",
  "upwork": "Freelance marketplace; Elance and oDesk merged, renamed 2015.",
  "robinhood": "Commission-free trading app founded in 2013.",
  "trello": "Kanban board app now owned by Atlassian.",
  "valve": "Game studio behind Half-Life and the Steam store",
  "oppo": "Chinese smartphone maker founded in 2004",
  "rockstargames": "Studio behind Grand Theft Auto.",
  "tesco": "British supermarket chain founded in 1919.",
  "ubisoft": "French game maker founded in 1986.",
  "verizon": "US telecom company formed in 2000.",
  "americanairlines": "One of the world's largest airlines.",
  "singaporeairlines": "Singapore's flag carrier, known for service.",
  "barclays": "British bank with roots back to 1690.",
  "alipay": "Chinese mobile payment app launched by Alibaba",
  "lyft": "US ride-sharing app founded in 2012",
  "venmo": "Payment app owned by PayPal.",
  "aircanada": "Canada's flag-carrier airline, founded in 1937.",
  "chase": "Major US bank, part of JPMorgan Chase.",
  "pandora": "US music-streaming pioneer founded in 2000",
  "sap": "German enterprise-software giant founded in 1972.",
  "blender": "Free open-source 3D creation suite from the Netherlands",
  "sonos": "US smart-speaker maker founded in 2002",
  "tidal": "Music-streaming service known for hi-fi audio quality",
  "signal": "Encrypted messaging app run by a nonprofit.",
  "ubuntu": "Popular Linux distribution, first released in 2004.",
  "wise": "Money-transfer company founded in 2011.",
  "googlecloud": "Google's cloud computing platform, launched in 2008",
  "deutschebank": "Germany's largest bank, founded in 1870.",
  "goldmansachs": "US investment bank founded in 1869.",
  "westernunion": "US money-transfer company dating back to 1851.",
  "caterpillar": "US maker of yellow construction machinery.",
  "johndeere": "US maker of green farm tractors, founded in 1837.",
  "unilever": "British consumer-goods giant behind Dove and Lipton.",
  "akamai": "Content delivery network company founded in 1998.",
  "jenkins": "Open-source automation server, forked from Hudson in 2011.",
  "splunk": "Machine-data analytics platform founded in 2003.",
  "godotengine": "Free open-source game engine.",
  "kubernetes": "Container tool open-sourced by Google in 2014.",
  "supabase": "Open-source alternative to Google's Firebase",
  "hashicorp": "Infrastructure-tools company behind Terraform.",
  "datadog": "Cloud-monitoring platform founded in 2010.",
  "sentry": "Open-source error-tracking tool.",
  "fastly": "Content delivery network founded in 2011.",
  "opensea": "Marketplace for NFTs, founded in 2017.",
  "kucoin": "Global cryptocurrency exchange founded in 2017.",
  "okx": "Global crypto exchange formerly known as OKEx.",
  "insta360": "Chinese maker of 360-degree action cameras.",
  "corsair": "US maker of gaming PC gear and components.",
  "steelseries": "Danish gaming peripherals brand founded in 2001.",
  "hyperx": "Gaming gear brand once part of Kingston Technology.",
  "toptal": "Network linking companies with freelance developers.",
  "udacity": "Online tech education platform known for Nanodegrees.",
  "leetcode": "Site for coding-interview practice problems.",
  "hackerrank": "Coding challenge and tech hiring platform.",
  "codecademy": "Interactive site for learning to code online.",
  "freecodecamp": "Free nonprofit platform for learning to code.",
  "avast": "Czech antivirus company founded in 1988.",
  "bitdefender": "Romanian cybersecurity company founded in 2001.",
  "malwarebytes": "US anti-malware software founded in 2008.",
  "anydesk": "German remote-desktop software launched in 2014.",
  "producthunt": "Site for discovering new tech products daily.",
  "replit": "Browser-based coding environment founded in 2016.",
  "picpay": "Brazilian digital wallet and payments app.",
  "ghost": "An open-source publishing platform for blogs and newsletters.",
  "contentful": "A headless content management system for developers.",
  "bigcommerce": "An e-commerce platform for building online stores.",
  "woocommerce": "An open-source e-commerce plugin for WordPress.",
  "squareenix": "The Japanese studio behind Final Fantasy games.",
  "mixcloud": "A platform for hosting DJ mixes and radio shows.",
  "iheartradio": "A US internet radio and podcast streaming service.",
  "nebula": "A streaming platform built by online video creators.",
  "itchdotio": "A marketplace for indie games and creative tools.",
  "humblebundle": "A store selling game bundles that fund charity.",
  "pixiv": "A Japanese online community for artists.",
  "abbott": "US healthcare company making medical devices.",
  "abbvie": "US pharmaceutical firm spun off from Abbott.",
  "adp": "Major US payroll and HR services provider.",
  "autodesk": "Maker of AutoCAD design software.",
  "avira": "German antivirus software company.",
  "bigbasket": "Indian online grocery-delivery service.",
  "blackmagicdesign": "Maker of pro cameras and DaVinci Resolve.",
  "bookmyshow": "India's leading movie-ticket booking site.",
  "braintree": "PayPal-owned online payments company.",
  "brex": "US financial services firm for startups.",
  "broadcom": "Major US semiconductor and software company.",
  "bytedance": "Chinese tech giant that owns TikTok.",
  "caixabank": "One of Spain's largest banks.",
  "celestron": "US maker of telescopes.",
  "hdfcbank": "One of India's largest private banks.",
  "icicibank": "Major Indian private-sector bank.",
  "infosys": "Indian IT and consulting giant.",
  "kyocera": "Japanese maker of ceramics and electronics.",
  "schneiderelectric": "French leader in energy and automation.",
  "n26": "German mobile-only bank founded in 2013.",
  "monzo": "British digital bank known for its coral cards",
  "razorpay": "Indian online payment gateway founded in 2014.",
  "phonepe": "Indian digital payments app built on UPI.",
  "moneygram": "US money-transfer firm and Western Union rival.",
  "zelle": "US bank-to-bank payment network launched in 2017.",
  "mercadopago": "Payments arm of Latin America's Mercado Libre.",
  "xiaohongshu": "Chinese social-shopping app, also called RED.",
  "byjus": "Indian education-technology company.",
  "telefonica": "Spanish telecom giant behind the Movistar brand.",
  "movistar": "Telefónica's mobile brand in Spain and Latin America.",
  "airtel": "Indian telecom giant operating in Asia and Africa.",
  "jio": "India's largest mobile network, launched by Reliance.",
  "rumble": "Video platform popular as a YouTube alternative.",
  "myspace": "Social network that dominated the mid-2000s.",
};
