// E05 «Guess the Logo» — GuessSync · 100 شعار · صعوبة مطلقة (سهل ~عالمي ← مستحيل <3%). image: logos/<slug>.svg | VO: sfx/nm-<slug>.wav
export const LOGOS2 = [
  // ===== EASY (25) =====
  { slug: "apple", name: "Apple", level: "easy" },
  { slug: "youtube", name: "YouTube", level: "easy" },
  { slug: "nike", name: "Nike", level: "easy" },
  { slug: "samsung", name: "Samsung", level: "easy" },
  { slug: "mastercard", name: "Mastercard", level: "easy" },
  { slug: "visa", name: "Visa", level: "easy" },
  { slug: "x", name: "X (Twitter)", level: "easy" },
  { slug: "paypal", name: "PayPal", level: "easy" },
  { slug: "toyota", name: "Toyota", level: "easy" },
  { slug: "burgerking", name: "Burger King", level: "easy" },
  { slug: "telegram", name: "Telegram", level: "easy" },
  { slug: "honda", name: "Honda", level: "easy" },
  { slug: "volkswagen", name: "Volkswagen", level: "easy" },
  { slug: "porsche", name: "Porsche", level: "easy" },
  { slug: "uber", name: "Uber", level: "easy" },
  { slug: "puma", name: "Puma", level: "easy" },
  { slug: "hyundai", name: "Hyundai", level: "easy" },
  { slug: "pinterest", name: "Pinterest", level: "easy" },
  { slug: "boeing", name: "Boeing", level: "easy" },
  { slug: "panasonic", name: "Panasonic", level: "easy" },
  { slug: "suzuki", name: "Suzuki", level: "easy" },
  { slug: "airbnb", name: "Airbnb", level: "easy" },
  { slug: "dell", name: "Dell", level: "easy" },
  { slug: "jeep", name: "Jeep", level: "easy" },
  { slug: "discord", name: "Discord", level: "easy" },
  // ===== MEDIUM (25) =====
  { slug: "nikon", name: "Nikon", level: "medium" },
  { slug: "aliexpress", name: "AliExpress", level: "medium" },
  { slug: "beats", name: "Beats", level: "medium" },
  { slug: "firefox", name: "Firefox", level: "medium" },
  { slug: "imdb", name: "IMDb", level: "medium" },
  { slug: "renault", name: "Renault", level: "medium" },
  { slug: "3m", name: "3M", level: "medium" },
  { slug: "fiat", name: "Fiat", level: "medium" },
  { slug: "peugeot", name: "Peugeot", level: "medium" },
  { slug: "bentley", name: "Bentley", level: "medium" },
  { slug: "hbo", name: "HBO", level: "medium" },
  { slug: "mini", name: "MINI", level: "medium" },
  { slug: "sega", name: "Sega", level: "medium" },
  { slug: "target", name: "Target", level: "medium" },
  { slug: "cisco", name: "Cisco", level: "medium" },
  { slug: "fitbit", name: "Fitbit", level: "medium" },
  { slug: "googlepay", name: "Google Pay", level: "medium" },
  { slug: "jbl", name: "JBL", level: "medium" },
  { slug: "opera", name: "Opera", level: "medium" },
  { slug: "tripadvisor", name: "Tripadvisor", level: "medium" },
  { slug: "mclaren", name: "McLaren", level: "medium" },
  { slug: "github", name: "GitHub", level: "medium" },
  { slug: "skoda", name: "Skoda", level: "medium" },
  { slug: "audible", name: "Audible", level: "medium" },
  { slug: "dropbox", name: "Dropbox", level: "medium" },
  // ===== HARD (25) =====
  { slug: "konami", name: "Konami", level: "hard" },
  { slug: "quora", name: "Quora", level: "hard" },
  { slug: "steam", name: "Steam", level: "hard" },
  { slug: "turkishairlines", name: "Turkish Airlines", level: "hard" },
  { slug: "valorant", name: "Valorant", level: "hard" },
  { slug: "wordpress", name: "WordPress", level: "hard" },
  { slug: "acer", name: "Acer", level: "hard" },
  { slug: "bankofamerica", name: "Bank of America", level: "hard" },
  { slug: "klm", name: "KLM", level: "hard" },
  { slug: "paramountplus", name: "Paramount+", level: "hard" },
  { slug: "easyjet", name: "easyJet", level: "hard" },
  { slug: "shopify", name: "Shopify", level: "hard" },
  { slug: "wellsfargo", name: "Wells Fargo", level: "hard" },
  { slug: "baidu", name: "Baidu", level: "hard" },
  { slug: "mailchimp", name: "Mailchimp", level: "hard" },
  { slug: "riotgames", name: "Riot Games", level: "hard" },
  { slug: "brave", name: "Brave", level: "hard" },
  { slug: "medium", name: "Medium", level: "hard" },
  { slug: "iberia", name: "Iberia", level: "hard" },
  { slug: "revolut", name: "Revolut", level: "hard" },
  { slug: "upwork", name: "Upwork", level: "hard" },
  { slug: "robinhood", name: "Robinhood", level: "hard" },
  { slug: "javascript", name: "JavaScript", level: "hard" },
  { slug: "trello", name: "Trello", level: "hard" },
  { slug: "valve", name: "Valve", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { slug: "apachekafka", name: "Apache Kafka", level: "impossible" },
  { slug: "coda", name: "Coda", level: "impossible" },
  { slug: "godotengine", name: "Godot Engine", level: "impossible" },
  { slug: "kubernetes", name: "Kubernetes", level: "impossible" },
  { slug: "perl", name: "Perl", level: "impossible" },
  { slug: "supabase", name: "Supabase", level: "impossible" },
  { slug: "circleci", name: "CircleCI", level: "impossible" },
  { slug: "prometheus", name: "Prometheus", level: "impossible" },
  { slug: "retool", name: "Retool", level: "impossible" },
  { slug: "vultr", name: "Vultr", level: "impossible" },
  { slug: "hashicorp", name: "HashiCorp", level: "impossible" },
  { slug: "apacheflink", name: "Apache Flink", level: "impossible" },
  { slug: "duckdb", name: "DuckDB", level: "impossible" },
  { slug: "mlflow", name: "MLflow", level: "impossible" },
  { slug: "puppet", name: "Puppet", level: "impossible" },
  { slug: "apachepulsar", name: "Apache Pulsar", level: "impossible" },
  { slug: "envoyproxy", name: "Envoy", level: "impossible" },
  { slug: "opsgenie", name: "Opsgenie", level: "impossible" },
  { slug: "trpc", name: "tRPC", level: "impossible" },
  { slug: "apachenifi", name: "Apache NiFi", level: "impossible" },
  { slug: "camunda", name: "Camunda", level: "impossible" },
  { slug: "fauna", name: "Fauna", level: "impossible" },
  { slug: "linkerd", name: "Linkerd", level: "impossible" },
  { slug: "packer", name: "Packer", level: "impossible" },
  { slug: "scylladb", name: "ScyllaDB", level: "impossible" },
];
