// E10 — Guess the Logo (tech/business brands). 100 logos, 25 per tier. image: logos/<slug>.svg | VO: sfx/nm-<slug>.wav
export const LOGOS4 = [
  // ===== EASY (25) =====
  { slug: "safari", name: "Safari", level: "easy" },
  { slug: "opera", name: "Opera", level: "easy" },
  { slug: "icloud", name: "iCloud", level: "easy" },
  { slug: "nokia", name: "Nokia", level: "easy" },
  { slug: "motorola", name: "Motorola", level: "easy" },
  { slug: "brave", name: "Brave", level: "easy" },
  { slug: "duckduckgo", name: "DuckDuckGo", level: "easy" },
  { slug: "lyft", name: "Lyft", level: "easy" },
  { slug: "beats", name: "Beats", level: "easy" },
  { slug: "pandora", name: "Pandora", level: "easy" },
  { slug: "hbomax", name: "HBO Max", level: "easy" },
  { slug: "appletv", name: "Apple TV", level: "easy" },
  { slug: "oppo", name: "OPPO", level: "easy" },
  { slug: "vivo", name: "Vivo", level: "easy" },
  { slug: "alipay", name: "Alipay", level: "easy" },
  { slug: "baidu", name: "Baidu", level: "easy" },
  { slug: "rakuten", name: "Rakuten", level: "easy" },
  { slug: "mailchimp", name: "Mailchimp", level: "easy" },
  { slug: "blender", name: "Blender", level: "easy" },
  { slug: "autocad", name: "AutoCAD", level: "easy" },
  { slug: "stackoverflow", name: "Stack Overflow", level: "easy" },
  { slug: "paramountplus", name: "Paramount+", level: "easy" },
  { slug: "oneplus", name: "OnePlus", level: "easy" },
  { slug: "activision", name: "Activision", level: "easy" },
  { slug: "konami", name: "Konami", level: "easy" },
  // ===== MEDIUM (25) =====
  { slug: "mediatek", name: "MediaTek", level: "medium" },
  { slug: "sennheiser", name: "Sennheiser", level: "medium" },
  { slug: "sonos", name: "Sonos", level: "medium" },
  { slug: "denon", name: "Denon", level: "medium" },
  { slug: "tidal", name: "Tidal", level: "medium" },
  { slug: "plex", name: "Plex", level: "medium" },
  { slug: "kodi", name: "Kodi", level: "medium" },
  { slug: "vivaldi", name: "Vivaldi", level: "medium" },
  { slug: "ecosia", name: "Ecosia", level: "medium" },
  { slug: "naver", name: "Naver", level: "medium" },
  { slug: "bilibili", name: "Bilibili", level: "medium" },
  { slug: "hubspot", name: "HubSpot", level: "medium" },
  { slug: "zendesk", name: "Zendesk", level: "medium" },
  { slug: "zapier", name: "Zapier", level: "medium" },
  { slug: "gimp", name: "GIMP", level: "medium" },
  { slug: "wolfram", name: "WolframAlpha", level: "medium" },
  { slug: "firebase", name: "Firebase", level: "medium" },
  { slug: "valve", name: "Valve", level: "medium" },
  { slug: "supercell", name: "Supercell", level: "medium" },
  { slug: "sketch", name: "Sketch", level: "medium" },
  { slug: "sketchup", name: "SketchUp", level: "medium" },
  { slug: "postman", name: "Postman", level: "medium" },
  { slug: "netlify", name: "Netlify", level: "medium" },
  { slug: "huggingface", name: "Hugging Face", level: "medium" },
  { slug: "perplexity", name: "Perplexity", level: "medium" },
  // ===== HARD (25) =====
  { slug: "monzo", name: "Monzo", level: "hard" },
  { slug: "framer", name: "Framer", level: "hard" },
  { slug: "inkscape", name: "Inkscape", level: "hard" },
  { slug: "krita", name: "Krita", level: "hard" },
  { slug: "mihoyo", name: "miHoYo", level: "hard" },
  { slug: "intercom", name: "Intercom", level: "hard" },
  { slug: "semrush", name: "Semrush", level: "hard" },
  { slug: "hootsuite", name: "Hootsuite", level: "hard" },
  { slug: "buffer", name: "Buffer", level: "hard" },
  { slug: "googlecloud", name: "Google Cloud", level: "hard" },
  { slug: "alibabacloud", name: "Alibaba Cloud", level: "hard" },
  { slug: "supabase", name: "Supabase", level: "hard" },
  { slug: "elevenlabs", name: "ElevenLabs", level: "hard" },
  { slug: "ollama", name: "Ollama", level: "hard" },
  { slug: "kaggle", name: "Kaggle", level: "hard" },
  { slug: "mariadb", name: "MariaDB", level: "hard" },
  { slug: "databricks", name: "Databricks", level: "hard" },
  { slug: "pocketbase", name: "PocketBase", level: "hard" },
  { slug: "hasura", name: "Hasura", level: "hard" },
  { slug: "retool", name: "Retool", level: "hard" },
  { slug: "trpc", name: "tRPC", level: "hard" },
  { slug: "drizzle", name: "Drizzle ORM", level: "hard" },
  { slug: "hetzner", name: "Hetzner", level: "hard" },
  { slug: "vultr", name: "Vultr", level: "hard" },
  { slug: "qualys", name: "Qualys", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { slug: "fauna", name: "Fauna", level: "impossible" },
  { slug: "camunda", name: "Camunda", level: "impossible" },
  { slug: "appsmith", name: "Appsmith", level: "impossible" },
  { slug: "budibase", name: "Budibase", level: "impossible" },
  { slug: "scaleway", name: "Scaleway", level: "impossible" },
  { slug: "envoyproxy", name: "Envoy", level: "impossible" },
  { slug: "istio", name: "Istio", level: "impossible" },
  { slug: "linkerd", name: "Linkerd", level: "impossible" },
  { slug: "rancher", name: "Rancher", level: "impossible" },
  { slug: "apachepulsar", name: "Apache Pulsar", level: "impossible" },
  { slug: "apacheflink", name: "Apache Flink", level: "impossible" },
  { slug: "apachedruid", name: "Apache Druid", level: "impossible" },
  { slug: "apachenifi", name: "Apache NiFi", level: "impossible" },
  { slug: "mlflow", name: "MLflow", level: "impossible" },
  { slug: "dvc", name: "DVC", level: "impossible" },
  { slug: "milvus", name: "Milvus", level: "impossible" },
  { slug: "qdrant", name: "Qdrant", level: "impossible" },
  { slug: "honeybadger", name: "Honeybadger", level: "impossible" },
  { slug: "rollbar", name: "Rollbar", level: "impossible" },
  { slug: "opsgenie", name: "Opsgenie", level: "impossible" },
  { slug: "convex", name: "Convex", level: "impossible" },
  { slug: "parrotsecurity", name: "Parrot Security", level: "impossible" },
  { slug: "nxp", name: "NXP", level: "impossible" },
  { slug: "espressif", name: "Espressif", level: "impossible" },
  { slug: "nordicsemiconductor", name: "Nordic Semiconductor", level: "impossible" },
];
