// «Guess the Brand Logo v2» — GuessSync · 100 famous consumer/retail/finance/media brands · 25/tier
// Absolute difficulty (easy ~household → impossible <3%). Slugs = Simple Icons slugs (monochrome SVG).
// image: logos/<slug>.svg | VO: sfx/nm-<slug>.wav (SHARED per-slug logo namespace). No overlap with E01/E05/E08/E10/E30/car/gaming/airline logo sets.
export const LOGOS5 = [
  // ===== EASY (25) — globally recognizable household names =====
  { slug: "cnn", name: "CNN", level: "easy" },
  { slug: "fox", name: "FOX", level: "easy" },
  { slug: "sky", name: "Sky", level: "easy" },
  { slug: "nbc", name: "NBC", level: "easy" },
  { slug: "cbs", name: "CBS", level: "easy" },
  { slug: "uniqlo", name: "Uniqlo", level: "easy" },
  { slug: "tacobell", name: "Taco Bell", level: "easy" },
  { slug: "dolby", name: "Dolby", level: "easy" },
  { slug: "ticketmaster", name: "Ticketmaster", level: "easy" },
  { slug: "discover", name: "Discover", level: "easy" },
  { slug: "tinder", name: "Tinder", level: "easy" },
  { slug: "norton", name: "Norton", level: "easy" },
  { slug: "mcafee", name: "McAfee", level: "easy" },
  { slug: "kaspersky", name: "Kaspersky", level: "easy" },
  { slug: "fujifilm", name: "Fujifilm", level: "easy" },
  { slug: "bosch", name: "Bosch", level: "easy" },
  { slug: "generalmotors", name: "General Motors", level: "easy" },
  { slug: "samsungpay", name: "Samsung Pay", level: "easy" },
  { slug: "googleearth", name: "Google Earth", level: "easy" },
  { slug: "aldinord", name: "Aldi", level: "easy" },
  { slug: "squarespace", name: "Squarespace", level: "easy" },
  { slug: "googlelens", name: "Google Lens", level: "easy" },
  { slug: "shopee", name: "Shopee", level: "easy" },
  { slug: "coursera", name: "Coursera", level: "easy" },
  { slug: "tripdotcom", name: "Trip.com", level: "easy" },

  // ===== MEDIUM (25) — widely known globally =====
  { slug: "udemy", name: "Udemy", level: "medium" },
  { slug: "khanacademy", name: "Khan Academy", level: "medium" },
  { slug: "skillshare", name: "Skillshare", level: "medium" },
  { slug: "teamviewer", name: "TeamViewer", level: "medium" },
  { slug: "trivago", name: "Trivago", level: "medium" },
  { slug: "zalando", name: "Zalando", level: "medium" },
  { slug: "vinted", name: "Vinted", level: "medium" },
  { slug: "wish", name: "Wish", level: "medium" },
  { slug: "instacart", name: "Instacart", level: "medium" },
  { slug: "justeat", name: "Just Eat", level: "medium" },
  { slug: "foodpanda", name: "Foodpanda", level: "medium" },
  { slug: "zomato", name: "Zomato", level: "medium" },
  { slug: "swiggy", name: "Swiggy", level: "medium" },
  { slug: "grab", name: "Grab", level: "medium" },
  { slug: "gojek", name: "Gojek", level: "medium" },
  { slug: "square", name: "Square", level: "medium" },
  { slug: "surveymonkey", name: "SurveyMonkey", level: "medium" },
  { slug: "kickstarter", name: "Kickstarter", level: "medium" },
  { slug: "patreon", name: "Patreon", level: "medium" },
  { slug: "gofundme", name: "GoFundMe", level: "medium" },
  { slug: "buzzfeed", name: "BuzzFeed", level: "medium" },
  { slug: "theguardian", name: "The Guardian", level: "medium" },
  { slug: "macys", name: "Macy's", level: "medium" },
  { slug: "boots", name: "Boots", level: "medium" },
  { slug: "thenorthface", name: "The North Face", level: "medium" },

  // ===== HARD (25) — known but not universal (finance, telecom, industrial, retail) =====
  { slug: "deutschebank", name: "Deutsche Bank", level: "hard" },
  { slug: "goldmansachs", name: "Goldman Sachs", level: "hard" },
  { slug: "westernunion", name: "Western Union", level: "hard" },
  { slug: "moneygram", name: "MoneyGram", level: "hard" },
  { slug: "n26", name: "N26", level: "hard" },
  { slug: "afterpay", name: "Afterpay", level: "hard" },
  { slug: "zelle", name: "Zelle", level: "hard" },
  { slug: "mercadopago", name: "Mercado Pago", level: "hard" },
  { slug: "phonepe", name: "PhonePe", level: "hard" },
  { slug: "razorpay", name: "Razorpay", level: "hard" },
  { slug: "airtel", name: "Airtel", level: "hard" },
  { slug: "jio", name: "Jio", level: "hard" },
  { slug: "telefonica", name: "Telefónica", level: "hard" },
  { slug: "movistar", name: "Movistar", level: "hard" },
  { slug: "telenor", name: "Telenor", level: "hard" },
  { slug: "o2", name: "O2", level: "hard" },
  { slug: "bt", name: "BT", level: "hard" },
  { slug: "caterpillar", name: "Caterpillar", level: "hard" },
  { slug: "johndeere", name: "John Deere", level: "hard" },
  { slug: "generalelectric", name: "General Electric", level: "hard" },
  { slug: "unilever", name: "Unilever", level: "hard" },
  { slug: "merck", name: "Merck", level: "hard" },
  { slug: "gsk", name: "GSK", level: "hard" },
  { slug: "asda", name: "Asda", level: "hard" },
  { slug: "morrisons", name: "Morrisons", level: "hard" },

  // ===== IMPOSSIBLE (25) — real brands, niche to the general public =====
  { slug: "opensea", name: "OpenSea", level: "impossible" },
  { slug: "kucoin", name: "KuCoin", level: "impossible" },
  { slug: "okx", name: "OKX", level: "impossible" },
  { slug: "insta360", name: "Insta360", level: "impossible" },
  { slug: "corsair", name: "Corsair", level: "impossible" },
  { slug: "steelseries", name: "SteelSeries", level: "impossible" },
  { slug: "hyperx", name: "HyperX", level: "impossible" },
  { slug: "toptal", name: "Toptal", level: "impossible" },
  { slug: "gotomeeting", name: "GoTo Meeting", level: "impossible" },
  { slug: "edx", name: "edX", level: "impossible" },
  { slug: "udacity", name: "Udacity", level: "impossible" },
  { slug: "leetcode", name: "LeetCode", level: "impossible" },
  { slug: "hackerrank", name: "HackerRank", level: "impossible" },
  { slug: "codecademy", name: "Codecademy", level: "impossible" },
  { slug: "freecodecamp", name: "freeCodeCamp", level: "impossible" },
  { slug: "avast", name: "Avast", level: "impossible" },
  { slug: "bitdefender", name: "Bitdefender", level: "impossible" },
  { slug: "malwarebytes", name: "Malwarebytes", level: "impossible" },
  { slug: "anydesk", name: "AnyDesk", level: "impossible" },
  { slug: "jsfiddle", name: "JSFiddle", level: "impossible" },
  { slug: "producthunt", name: "Product Hunt", level: "impossible" },
  { slug: "replit", name: "Replit", level: "impossible" },
  { slug: "codesandbox", name: "CodeSandbox", level: "impossible" },
  { slug: "glitch", name: "Glitch", level: "impossible" },
  { slug: "picpay", name: "PicPay", level: "impossible" },
];
export const LOGO_LEVELS = ["easy", "medium", "hard", "impossible"];
