// MEGA «Guess the Logo» — ~300 most globally recognizable brand logos, curated from
// E01/E05/E08/E10/E72/E77/E-logos7 owned logo sets. image: logos/<slug>.svg | VO: sfx/nm-<slug>.wav
// Absolute difficulty across the full 300 (not per-100 relative tiers). ~75 per tier.
// NOTE: mega-scale (>100 items) — requires the variable-count engine support, added separately.
export const LOGOS_MEGA = [
  // ===== EASY (75) =====
  { slug: "google", name: "Google", level: "easy" },
  { slug: "mcdonalds", name: "McDonald's", level: "easy" },
  { slug: "instagram", name: "Instagram", level: "easy" },
  { slug: "adidas", name: "Adidas", level: "easy" },
  { slug: "android", name: "Android", level: "easy" },
  { slug: "starbucks", name: "Starbucks", level: "easy" },
  { slug: "gmail", name: "Gmail", level: "easy" },
  { slug: "snapchat", name: "Snapchat", level: "easy" },
  { slug: "ferrari", name: "Ferrari", level: "easy" },
  { slug: "tesla", name: "Tesla", level: "easy" },
  { slug: "ikea", name: "IKEA", level: "easy" },
  { slug: "spotify", name: "Spotify", level: "easy" },
  { slug: "shell", name: "Shell", level: "easy" },
  { slug: "lamborghini", name: "Lamborghini", level: "easy" },
  { slug: "ebay", name: "eBay", level: "easy" },
  { slug: "nokia", name: "Nokia", level: "easy" },
  { slug: "dhl", name: "DHL", level: "easy" },
  { slug: "huawei", name: "Huawei", level: "easy" },
  { slug: "nike", name: "Nike", level: "easy" },
  { slug: "apple", name: "Apple", level: "easy" },
  { slug: "youtube", name: "YouTube", level: "easy" },
  { slug: "samsung", name: "Samsung", level: "easy" },
  { slug: "mastercard", name: "Mastercard", level: "easy" },
  { slug: "visa", name: "Visa", level: "easy" },
  { slug: "paypal", name: "PayPal", level: "easy" },
  { slug: "toyota", name: "Toyota", level: "easy" },
  { slug: "burgerking", name: "Burger King", level: "easy" },
  { slug: "honda", name: "Honda", level: "easy" },
  { slug: "volkswagen", name: "Volkswagen", level: "easy" },
  { slug: "porsche", name: "Porsche", level: "easy" },
  { slug: "uber", name: "Uber", level: "easy" },
  { slug: "hyundai", name: "Hyundai", level: "easy" },
  { slug: "pinterest", name: "Pinterest", level: "easy" },
  { slug: "boeing", name: "Boeing", level: "easy" },
  { slug: "airbnb", name: "Airbnb", level: "easy" },
  { slug: "dell", name: "Dell", level: "easy" },
  { slug: "cocacola", name: "Coca-Cola", level: "easy" },
  { slug: "facebook", name: "Facebook", level: "easy" },
  { slug: "whatsapp", name: "WhatsApp", level: "easy" },
  { slug: "tiktok", name: "TikTok", level: "easy" },
  { slug: "netflix", name: "Netflix", level: "easy" },
  { slug: "bmw", name: "BMW", level: "easy" },
  { slug: "playstation", name: "PlayStation", level: "easy" },
  { slug: "kfc", name: "KFC", level: "easy" },
  { slug: "ford", name: "Ford", level: "easy" },
  { slug: "wikipedia", name: "Wikipedia", level: "easy" },
  { slug: "sony", name: "Sony", level: "easy" },
  { slug: "audi", name: "Audi", level: "easy" },
  { slug: "redbull", name: "Red Bull", level: "easy" },
  { slug: "hp", name: "HP", level: "easy" },
  { slug: "lg", name: "LG", level: "easy" },
  { slug: "intel", name: "Intel", level: "easy" },
  { slug: "zara", name: "Zara", level: "easy" },
  { slug: "fedex", name: "FedEx", level: "easy" },
  { slug: "reddit", name: "Reddit", level: "easy" },
  { slug: "ups", name: "UPS", level: "easy" },
  { slug: "americanexpress", name: "American Express", level: "easy" },
  { slug: "emirates", name: "Emirates", level: "easy" },
  { slug: "cnn", name: "CNN", level: "easy" },
  { slug: "fox", name: "FOX", level: "easy" },
  { slug: "nbc", name: "NBC", level: "easy" },
  { slug: "cbs", name: "CBS", level: "easy" },
  { slug: "meta", name: "Meta", level: "easy" },
  { slug: "ios", name: "iOS", level: "easy" },
  { slug: "nba", name: "NBA", level: "easy" },
  { slug: "mlb", name: "MLB", level: "easy" },
  { slug: "nhl", name: "NHL", level: "easy" },
  { slug: "wwe", name: "WWE", level: "easy" },
  { slug: "premierleague", name: "Premier League", level: "easy" },
  { slug: "nasa", name: "NASA", level: "easy" },
  { slug: "handm", name: "H&M", level: "easy" },
  { slug: "hermes", name: "Hermès", level: "easy" },
  { slug: "marriott", name: "Marriott", level: "easy" },
  { slug: "chevrolet", name: "Chevrolet", level: "easy" },
  { slug: "spacex", name: "SpaceX", level: "easy" },
  // ===== MEDIUM (75) =====
  { slug: "xiaomi", name: "Xiaomi", level: "medium" },
  { slug: "applemusic", name: "Apple Music", level: "medium" },
  { slug: "googlephotos", name: "Google Photos", level: "medium" },
  { slug: "qatarairways", name: "Qatar Airways", level: "medium" },
  { slug: "siemens", name: "Siemens", level: "medium" },
  { slug: "duolingo", name: "Duolingo", level: "medium" },
  { slug: "newbalance", name: "New Balance", level: "medium" },
  { slug: "twitch", name: "Twitch", level: "medium" },
  { slug: "citroen", name: "Citroën", level: "medium" },
  { slug: "lidl", name: "Lidl", level: "medium" },
  { slug: "pubg", name: "PUBG", level: "medium" },
  { slug: "vodafone", name: "Vodafone", level: "medium" },
  { slug: "chrysler", name: "Chrysler", level: "medium" },
  { slug: "etsy", name: "Etsy", level: "medium" },
  { slug: "icloud", name: "iCloud", level: "medium" },
  { slug: "maserati", name: "Maserati", level: "medium" },
  { slug: "soundcloud", name: "SoundCloud", level: "medium" },
  { slug: "appletv", name: "Apple TV", level: "medium" },
  { slug: "garmin", name: "Garmin", level: "medium" },
  { slug: "ryanair", name: "Ryanair", level: "medium" },
  { slug: "airfrance", name: "Air France", level: "medium" },
  { slug: "delta", name: "Delta Air Lines", level: "medium" },
  { slug: "nikon", name: "Nikon", level: "medium" },
  { slug: "aliexpress", name: "AliExpress", level: "medium" },
  { slug: "beats", name: "Beats", level: "medium" },
  { slug: "firefox", name: "Firefox", level: "medium" },
  { slug: "imdb", name: "IMDb", level: "medium" },
  { slug: "renault", name: "Renault", level: "medium" },
  { slug: "fiat", name: "Fiat", level: "medium" },
  { slug: "peugeot", name: "Peugeot", level: "medium" },
  { slug: "bentley", name: "Bentley", level: "medium" },
  { slug: "hbo", name: "HBO", level: "medium" },
  { slug: "mini", name: "MINI", level: "medium" },
  { slug: "sega", name: "Sega", level: "medium" },
  { slug: "target", name: "Target", level: "medium" },
  { slug: "fitbit", name: "Fitbit", level: "medium" },
  { slug: "googlepay", name: "Google Pay", level: "medium" },
  { slug: "jbl", name: "JBL", level: "medium" },
  { slug: "mclaren", name: "McLaren", level: "medium" },
  { slug: "github", name: "GitHub", level: "medium" },
  { slug: "skoda", name: "Skoda", level: "medium" },
  { slug: "dropbox", name: "Dropbox", level: "medium" },
  { slug: "volvo", name: "Volvo", level: "medium" },
  { slug: "amd", name: "AMD", level: "medium" },
  { slug: "cadillac", name: "Cadillac", level: "medium" },
  { slug: "fortnite", name: "Fortnite", level: "medium" },
  { slug: "motorola", name: "Motorola", level: "medium" },
  { slug: "roblox", name: "Roblox", level: "medium" },
  { slug: "asus", name: "Asus", level: "medium" },
  { slug: "lenovo", name: "Lenovo", level: "medium" },
  { slug: "subaru", name: "Subaru", level: "medium" },
  { slug: "bose", name: "Bose", level: "medium" },
  { slug: "hsbc", name: "HSBC", level: "medium" },
  { slug: "carrefour", name: "Carrefour", level: "medium" },
  { slug: "dji", name: "DJI", level: "medium" },
  { slug: "zoom", name: "Zoom", level: "medium" },
  { slug: "britishairways", name: "British Airways", level: "medium" },
  { slug: "lufthansa", name: "Lufthansa", level: "medium" },
  { slug: "activision", name: "Activision", level: "medium" },
  { slug: "binance", name: "Binance", level: "medium" },
  { slug: "ea", name: "EA", level: "medium" },
  { slug: "huggingface", name: "Hugging Face", level: "medium" },
  { slug: "udemy", name: "Udemy", level: "medium" },
  { slug: "khanacademy", name: "Khan Academy", level: "medium" },
  { slug: "zalando", name: "Zalando", level: "medium" },
  { slug: "instacart", name: "Instacart", level: "medium" },
  { slug: "square", name: "Square", level: "medium" },
  { slug: "macys", name: "Macy's", level: "medium" },
  { slug: "thenorthface", name: "The North Face", level: "medium" },
  { slug: "dazn", name: "DAZN", level: "medium" },
  { slug: "hellofresh", name: "HelloFresh", level: "medium" },
  { slug: "newyorktimes", name: "New York Times", level: "medium" },
  { slug: "peloton", name: "Peloton", level: "medium" },
  { slug: "strava", name: "Strava", level: "medium" },
  { slug: "googlemeet", name: "Google Meet", level: "medium" },
  // ===== HARD (75) =====
  { slug: "epicgames", name: "Epic Games", level: "hard" },
  { slug: "orange", name: "Orange", level: "hard" },
  { slug: "safari", name: "Safari", level: "hard" },
  { slug: "tumblr", name: "Tumblr", level: "hard" },
  { slug: "unitedairlines", name: "United Airlines", level: "hard" },
  { slug: "vimeo", name: "Vimeo", level: "hard" },
  { slug: "yelp", name: "Yelp", level: "hard" },
  { slug: "wechat", name: "WeChat", level: "hard" },
  { slug: "coinbase", name: "Coinbase", level: "hard" },
  { slug: "oneplus", name: "OnePlus", level: "hard" },
  { slug: "cashapp", name: "Cash App", level: "hard" },
  { slug: "sennheiser", name: "Sennheiser", level: "hard" },
  { slug: "vivo", name: "Vivo", level: "hard" },
  { slug: "autocad", name: "AutoCAD", level: "hard" },
  { slug: "klarna", name: "Klarna", level: "hard" },
  { slug: "qualcomm", name: "Qualcomm", level: "hard" },
  { slug: "southwestairlines", name: "Southwest Airlines", level: "hard" },
  { slug: "grammarly", name: "Grammarly", level: "hard" },
  { slug: "duckduckgo", name: "DuckDuckGo", level: "hard" },
  { slug: "rakuten", name: "Rakuten", level: "hard" },
  { slug: "stripe", name: "Stripe", level: "hard" },
  { slug: "razer", name: "Razer", level: "hard" },
  { slug: "unity", name: "Unity", level: "hard" },
  { slug: "stackoverflow", name: "Stack Overflow", level: "hard" },
  { slug: "unrealengine", name: "Unreal Engine", level: "hard" },
  { slug: "konami", name: "Konami", level: "hard" },
  { slug: "quora", name: "Quora", level: "hard" },
  { slug: "steam", name: "Steam", level: "hard" },
  { slug: "turkishairlines", name: "Turkish Airlines", level: "hard" },
  { slug: "valorant", name: "Valorant", level: "hard" },
  { slug: "wordpress", name: "WordPress", level: "hard" },
  { slug: "bankofamerica", name: "Bank of America", level: "hard" },
  { slug: "klm", name: "KLM", level: "hard" },
  { slug: "paramountplus", name: "Paramount+", level: "hard" },
  { slug: "easyjet", name: "easyJet", level: "hard" },
  { slug: "shopify", name: "Shopify", level: "hard" },
  { slug: "wellsfargo", name: "Wells Fargo", level: "hard" },
  { slug: "baidu", name: "Baidu", level: "hard" },
  { slug: "mailchimp", name: "Mailchimp", level: "hard" },
  { slug: "riotgames", name: "Riot Games", level: "hard" },
  { slug: "brave", name: "Brave", level: "hard" },
  { slug: "medium", name: "Medium", level: "hard" },
  { slug: "revolut", name: "Revolut", level: "hard" },
  { slug: "upwork", name: "Upwork", level: "hard" },
  { slug: "robinhood", name: "Robinhood", level: "hard" },
  { slug: "trello", name: "Trello", level: "hard" },
  { slug: "valve", name: "Valve", level: "hard" },
  { slug: "oppo", name: "OPPO", level: "hard" },
  { slug: "rockstargames", name: "Rockstar Games", level: "hard" },
  { slug: "tesco", name: "Tesco", level: "hard" },
  { slug: "ubisoft", name: "Ubisoft", level: "hard" },
  { slug: "verizon", name: "Verizon", level: "hard" },
  { slug: "americanairlines", name: "American Airlines", level: "hard" },
  { slug: "singaporeairlines", name: "Singapore Airlines", level: "hard" },
  { slug: "barclays", name: "Barclays", level: "hard" },
  { slug: "alipay", name: "Alipay", level: "hard" },
  { slug: "lyft", name: "Lyft", level: "hard" },
  { slug: "venmo", name: "Venmo", level: "hard" },
  { slug: "aircanada", name: "Air Canada", level: "hard" },
  { slug: "chase", name: "Chase", level: "hard" },
  { slug: "pandora", name: "Pandora", level: "hard" },
  { slug: "sap", name: "SAP", level: "hard" },
  { slug: "blender", name: "Blender", level: "hard" },
  { slug: "sonos", name: "Sonos", level: "hard" },
  { slug: "tidal", name: "Tidal", level: "hard" },
  { slug: "signal", name: "Signal", level: "hard" },
  { slug: "ubuntu", name: "Ubuntu", level: "hard" },
  { slug: "wise", name: "Wise", level: "hard" },
  { slug: "googlecloud", name: "Google Cloud", level: "hard" },
  { slug: "deutschebank", name: "Deutsche Bank", level: "hard" },
  { slug: "goldmansachs", name: "Goldman Sachs", level: "hard" },
  { slug: "westernunion", name: "Western Union", level: "hard" },
  { slug: "caterpillar", name: "Caterpillar", level: "hard" },
  { slug: "johndeere", name: "John Deere", level: "hard" },
  { slug: "unilever", name: "Unilever", level: "hard" },
  // ===== IMPOSSIBLE (75) =====
  { slug: "akamai", name: "Akamai", level: "impossible" },
  { slug: "jenkins", name: "Jenkins", level: "impossible" },
  { slug: "splunk", name: "Splunk", level: "impossible" },
  { slug: "godotengine", name: "Godot Engine", level: "impossible" },
  { slug: "kubernetes", name: "Kubernetes", level: "impossible" },
  { slug: "supabase", name: "Supabase", level: "impossible" },
  { slug: "hashicorp", name: "HashiCorp", level: "impossible" },
  { slug: "datadog", name: "Datadog", level: "impossible" },
  { slug: "sentry", name: "Sentry", level: "impossible" },
  { slug: "fastly", name: "Fastly", level: "impossible" },
  { slug: "opensea", name: "OpenSea", level: "impossible" },
  { slug: "kucoin", name: "KuCoin", level: "impossible" },
  { slug: "okx", name: "OKX", level: "impossible" },
  { slug: "insta360", name: "Insta360", level: "impossible" },
  { slug: "corsair", name: "Corsair", level: "impossible" },
  { slug: "steelseries", name: "SteelSeries", level: "impossible" },
  { slug: "hyperx", name: "HyperX", level: "impossible" },
  { slug: "toptal", name: "Toptal", level: "impossible" },
  { slug: "udacity", name: "Udacity", level: "impossible" },
  { slug: "leetcode", name: "LeetCode", level: "impossible" },
  { slug: "hackerrank", name: "HackerRank", level: "impossible" },
  { slug: "codecademy", name: "Codecademy", level: "impossible" },
  { slug: "freecodecamp", name: "freeCodeCamp", level: "impossible" },
  { slug: "avast", name: "Avast", level: "impossible" },
  { slug: "bitdefender", name: "Bitdefender", level: "impossible" },
  { slug: "malwarebytes", name: "Malwarebytes", level: "impossible" },
  { slug: "anydesk", name: "AnyDesk", level: "impossible" },
  { slug: "producthunt", name: "Product Hunt", level: "impossible" },
  { slug: "replit", name: "Replit", level: "impossible" },
  { slug: "picpay", name: "PicPay", level: "impossible" },
  { slug: "ghost", name: "Ghost", level: "impossible" },
  { slug: "contentful", name: "Contentful", level: "impossible" },
  { slug: "bigcommerce", name: "BigCommerce", level: "impossible" },
  { slug: "woocommerce", name: "WooCommerce", level: "impossible" },
  { slug: "squareenix", name: "Square Enix", level: "impossible" },
  { slug: "mixcloud", name: "Mixcloud", level: "impossible" },
  { slug: "iheartradio", name: "iHeartRadio", level: "impossible" },
  { slug: "nebula", name: "Nebula", level: "impossible" },
  { slug: "itchdotio", name: "Itch.io", level: "impossible" },
  { slug: "humblebundle", name: "Humble Bundle", level: "impossible" },
  { slug: "pixiv", name: "Pixiv", level: "impossible" },
  { slug: "abbott", name: "Abbott", level: "impossible" },
  { slug: "abbvie", name: "AbbVie", level: "impossible" },
  { slug: "adp", name: "ADP", level: "impossible" },
  { slug: "autodesk", name: "Autodesk", level: "impossible" },
  { slug: "avira", name: "Avira", level: "impossible" },
  { slug: "bigbasket", name: "bigbasket", level: "impossible" },
  { slug: "blackmagicdesign", name: "Blackmagic", level: "impossible" },
  { slug: "bookmyshow", name: "BookMyShow", level: "impossible" },
  { slug: "braintree", name: "Braintree", level: "impossible" },
  { slug: "brex", name: "Brex", level: "impossible" },
  { slug: "broadcom", name: "Broadcom", level: "impossible" },
  { slug: "bytedance", name: "ByteDance", level: "impossible" },
  { slug: "caixabank", name: "CaixaBank", level: "impossible" },
  { slug: "celestron", name: "Celestron", level: "impossible" },
  { slug: "hdfcbank", name: "HDFC Bank", level: "impossible" },
  { slug: "icicibank", name: "ICICI Bank", level: "impossible" },
  { slug: "infosys", name: "Infosys", level: "impossible" },
  { slug: "kyocera", name: "Kyocera", level: "impossible" },
  { slug: "schneiderelectric", name: "Schneider Electric", level: "impossible" },
  { slug: "n26", name: "N26", level: "impossible" },
  { slug: "monzo", name: "Monzo", level: "impossible" },
  { slug: "razorpay", name: "Razorpay", level: "impossible" },
  { slug: "phonepe", name: "PhonePe", level: "impossible" },
  { slug: "moneygram", name: "MoneyGram", level: "impossible" },
  { slug: "zelle", name: "Zelle", level: "impossible" },
  { slug: "mercadopago", name: "Mercado Pago", level: "impossible" },
  { slug: "xiaohongshu", name: "Xiaohongshu", level: "impossible" },
  { slug: "byjus", name: "Byju's", level: "impossible" },
  { slug: "telefonica", name: "Telefónica", level: "impossible" },
  { slug: "movistar", name: "Movistar", level: "impossible" },
  { slug: "airtel", name: "Airtel", level: "impossible" },
  { slug: "jio", name: "Jio", level: "impossible" },
  { slug: "rumble", name: "Rumble", level: "impossible" },
  { slug: "myspace", name: "Myspace", level: "impossible" },
];
