// «Guess the Brand Logo v3» — one verified TRUE ≤70-char fact per slug (LOGOS6).
export const LOGOS6_FACTS = {
  // EASY
  meta: "Facebook's parent company rebranded to Meta in October 2021.",
  ios: "Apple's iPhone operating system, first released in 2007.",
  macos: "Apple's desktop OS, formerly called Mac OS X.",
  imessage: "Apple's messaging service marks its texts in blue bubbles.",
  itunes: "Apple's media app that once dominated digital music sales.",
  googlemessages: "Google's default texting app for Android, with RCS chat support.",
  nba: "The National Basketball Association was founded in 1946.",
  mlb: "Major League Baseball is North America's oldest major sports league.",
  nhl: "The National Hockey League was founded in 1917.",
  ufc: "The Ultimate Fighting Championship began in 1993.",
  wwe: "World Wrestling Entertainment stages scripted pro wrestling shows.",
  premierleague: "England's top football division, launched in 1992.",
  googlegemini: "Google's AI chatbot, renamed from Bard in 2024.",
  googlehome: "Google's smart speaker line, launched in 2016.",
  googleassistant: "Google's voice assistant debuted in 2016.",
  googletv: "Google's smart-TV platform and content hub.",
  googlenews: "Google's news aggregator launched in 2002.",
  googleads: "Google's advertising platform, once called AdWords.",
  googleanalytics: "Google's free web traffic analytics service.",
  googleclassroom: "Google's free learning platform for schools.",
  googlekeep: "Google's note-taking app, launched in 2013.",
  googlescholar: "Google's search engine for academic papers.",
  oculus: "The VR headset brand Facebook acquired in 2014.",
  showtime: "A US premium cable channel launched in 1976.",
  rottentomatoes: "A film review site famous for its Tomatometer score.",

  // MEDIUM
  toshiba: "A Japanese electronics giant founded in 1875.",
  sharp: "A Japanese electronics maker founded in 1912.",
  hitachi: "A Japanese conglomerate founded in 1910.",
  xcode: "Apple's tool for building iPhone and Mac apps.",
  homebrew: "A popular package manager for macOS and Linux.",
  dazn: "A sports streaming service launched in 2016.",
  tubi: "A free ad-supported streaming service owned by Fox.",
  fubo: "A sports-focused live TV streaming service.",
  starz: "A US premium cable and streaming network.",
  channel4: "A British public-service TV channel launched in 1982.",
  thewashingtonpost: "A major US newspaper founded in 1877.",
  bereal: "A photo app that prompts one unfiltered post daily.",
  clubhouse: "An audio-chat app that surged in popularity in 2020.",
  flipboard: "A news-reading app that lays stories out like a magazine.",
  feedly: "An RSS news reader launched in 2008.",
  kick: "A live-streaming platform launched in 2022.",
  deviantart: "An online art community founded in 2000.",
  artstation: "A portfolio platform for game and film artists.",
  vsco: "A photo-editing app known for its film-like presets.",
  picsart: "A photo and video editing app with over a billion downloads.",
  davinciresolve: "A pro video editing and color-grading suite.",
  streamlabs: "Tools that help creators broadcast live streams.",
  quickbooks: "Accounting software for small businesses by Intuit.",
  tradingview: "A charting platform used by stock and crypto traders.",
  stockx: "An online marketplace for sneakers and streetwear.",

  // HARD
  snowflake: "A cloud data-warehouse company that went public in 2020.",
  webflow: "A tool for building websites without writing code.",
  googlefonts: "A free library of open-source web fonts.",
  googlecolab: "A free cloud notebook for running Python code.",
  googlebigquery: "Google's cloud data-warehouse service.",
  googlestreetview: "Google Maps' 360-degree street-level imagery.",
  googletasks: "Google's simple to-do list app.",
  namecheap: "A domain registrar and web-hosting company.",
  hostinger: "A budget web-hosting provider founded in 2004.",
  ovh: "A French cloud computing and hosting company.",
  netgear: "A maker of routers and networking hardware.",
  tplink: "A maker of routers and Wi-Fi networking gear.",
  synology: "A brand of network-attached storage devices.",
  ubiquiti: "A maker of enterprise networking and Wi-Fi gear.",
  coolermaster: "A maker of PC cases, coolers, and components.",
  nzxt: "A brand of PC cases and cooling gear for gamers.",
  adyen: "A Dutch payments company that handles online checkouts.",
  xero: "A cloud accounting platform from New Zealand.",
  expensify: "An app for tracking receipts and expense reports.",
  gusto: "A US payroll and HR platform for small businesses.",
  allegro: "Poland's largest online shopping marketplace.",
  fnac: "A French retail chain selling books and electronics.",
  mediamarkt: "A German electronics retail chain.",
  argos: "A British catalogue retailer founded in 1972.",
  farfetch: "A luxury fashion online marketplace.",

  // IMPOSSIBLE
  ghost: "An open-source publishing platform for blogs and newsletters.",
  contentful: "A headless content management system for developers.",
  strapi: "An open-source headless CMS built with Node.js.",
  bigcommerce: "An e-commerce platform for building online stores.",
  woocommerce: "An open-source e-commerce plugin for WordPress.",
  squareenix: "The Japanese studio behind Final Fantasy games.",
  beatport: "An online music store aimed at DJs.",
  mixcloud: "A platform for hosting DJ mixes and radio shows.",
  iheartradio: "A US internet radio and podcast streaming service.",
  bandcamp: "A site where artists sell music directly to fans.",
  audiomack: "A music streaming platform popular for hip-hop.",
  napster: "A pioneering file-sharing service from 1999.",
  mubi: "A curated streaming service for arthouse films.",
  nebula: "A streaming platform built by online video creators.",
  steamdeck: "Valve's handheld gaming PC, released in 2022.",
  itchdotio: "A marketplace for indie games and creative tools.",
  humblebundle: "A store selling game bundles that fund charity.",
  kongregate: "A website hosting thousands of browser games.",
  newgrounds: "An early hub for user-made Flash games and animations.",
  pixiv: "A Japanese online community for artists.",
  douban: "A Chinese site for rating films, books, and music.",
  threema: "A privacy-focused encrypted messaging app from Switzerland.",
  ifttt: "A service that automates tasks between web apps.",
  excalidraw: "A tool for sketching hand-drawn-style diagrams.",
  logseq: "An open-source note-taking and knowledge tool.",
};
