// «Guess the Country by its Missing Letters» — GuessSync E121 · 100 countries (25/tier)
// Pure TEXT clue: the country's name in CAPS with a deterministic subset of letters replaced by "_" (spaces kept).
// Tiered by fame + reveal ratio: easy keeps ~66% of letters, medium ~55%, hard ~46%, impossible ~40%.
// Same country pool/tiers as E115/E116/E119 — no blanked pattern collides with any other in its own tier.
// Answer VO mis-<slug>.wav = "It's <name>!"
export const MISSING_LETTERS = [
  // EASY (25)
  { slug: "france", name: "France", blanked: "_RANC_", level: "easy" },
  { slug: "japan", name: "Japan", blanked: "J__AN", level: "easy" },
  { slug: "spain", name: "Spain", blanked: "_PA_N", level: "easy" },
  { slug: "italy", name: "Italy", blanked: "_TA_Y", level: "easy" },
  { slug: "china", name: "China", blanked: "C_I_A", level: "easy" },
  { slug: "india", name: "India", blanked: "_NDI_", level: "easy" },
  { slug: "brazil", name: "Brazil", blanked: "B_AZI_", level: "easy" },
  { slug: "egypt", name: "Egypt", blanked: "E_YP_", level: "easy" },
  { slug: "mexico", name: "Mexico", blanked: "_EXI_O", level: "easy" },
  { slug: "canada", name: "Canada", blanked: "_AN_DA", level: "easy" },
  { slug: "germany", name: "Germany", blanked: "_ERM_NY", level: "easy" },
  { slug: "russia", name: "Russia", blanked: "RUS_I_", level: "easy" },
  { slug: "greece", name: "Greece", blanked: "_RE_CE", level: "easy" },
  { slug: "cuba", name: "Cuba", blanked: "CU_A", level: "easy" },
  { slug: "peru", name: "Peru", blanked: "PER_", level: "easy" },
  { slug: "kenya", name: "Kenya", blanked: "K_N_A", level: "easy" },
  { slug: "ghana", name: "Ghana", blanked: "G_AN_", level: "easy" },
  { slug: "iran", name: "Iran", blanked: "I_AN", level: "easy" },
  { slug: "iraq", name: "Iraq", blanked: "_RAQ", level: "easy" },
  { slug: "turkey", name: "Turkey", blanked: "TU__EY", level: "easy" },
  { slug: "poland", name: "Poland", blanked: "P_L_ND", level: "easy" },
  { slug: "norway", name: "Norway", blanked: "_ORW_Y", level: "easy" },
  { slug: "sweden", name: "Sweden", blanked: "__EDEN", level: "easy" },
  { slug: "ireland", name: "Ireland", blanked: "IREL_N_", level: "easy" },
  { slug: "jordan", name: "Jordan", blanked: "JO__AN", level: "easy" },
  // MEDIUM (25)
  { slug: "portugal", name: "Portugal", blanked: "____UGAL", level: "medium" },
  { slug: "austria", name: "Austria", blanked: "_U__RIA", level: "medium" },
  { slug: "belgium", name: "Belgium", blanked: "_EL_IU_", level: "medium" },
  { slug: "finland", name: "Finland", blanked: "__NLAN_", level: "medium" },
  { slug: "denmark", name: "Denmark", blanked: "_EN_AR_", level: "medium" },
  { slug: "ukraine", name: "Ukraine", blanked: "UKR_I__", level: "medium" },
  { slug: "vietnam", name: "Vietnam", blanked: "VIE_N__", level: "medium" },
  { slug: "thailand", name: "Thailand", blanked: "T_A_L__D", level: "medium" },
  { slug: "nigeria", name: "Nigeria", blanked: "_I__RIA", level: "medium" },
  { slug: "morocco", name: "Morocco", blanked: "M_R__CO", level: "medium" },
  { slug: "ethiopia", name: "Ethiopia", blanked: "__HI__IA", level: "medium" },
  { slug: "colombia", name: "Colombia", blanked: "__LOM_I_", level: "medium" },
  { slug: "pakistan", name: "Pakistan", blanked: "PA__ST__", level: "medium" },
  { slug: "malaysia", name: "Malaysia", blanked: "M__AYS__", level: "medium" },
  { slug: "cambodia", name: "Cambodia", blanked: "_A_B_DI_", level: "medium" },
  { slug: "tanzania", name: "Tanzania", blanked: "TA___N_A", level: "medium" },
  { slug: "zimbabwe", name: "Zimbabwe", blanked: "_IM__B_E", level: "medium" },
  { slug: "botswana", name: "Botswana", blanked: "B_T__A_A", level: "medium" },
  { slug: "slovakia", name: "Slovakia", blanked: "SL___KI_", level: "medium" },
  { slug: "slovenia", name: "Slovenia", blanked: "__O_ENI_", level: "medium" },
  { slug: "bulgaria", name: "Bulgaria", blanked: "_U_GA_I_", level: "medium" },
  { slug: "bahrain", name: "Bahrain", blanked: "BA__A_N", level: "medium" },
  { slug: "kuwait", name: "Kuwait", blanked: "_U__IT", level: "medium" },
  { slug: "lebanon", name: "Lebanon", blanked: "L_B_N_N", level: "medium" },
  { slug: "mongolia", name: "Mongolia", blanked: "M__G__IA", level: "medium" },
  // HARD (25)
  { slug: "madagascar", name: "Madagascar", blanked: "___AGA_C_R", level: "hard" },
  { slug: "mozambique", name: "Mozambique", blanked: "_OZAMB____", level: "hard" },
  { slug: "cameroon", name: "Cameroon", blanked: "___ER_ON", level: "hard" },
  { slug: "venezuela", name: "Venezuela", blanked: "V____UEL_", level: "hard" },
  { slug: "guatemala", name: "Guatemala", blanked: "G_A_E___A", level: "hard" },
  { slug: "honduras", name: "Honduras", blanked: "_O___RAS", level: "hard" },
  { slug: "nicaragua", name: "Nicaragua", blanked: "____RA_UA", level: "hard" },
  { slug: "paraguay", name: "Paraguay", blanked: "P__A_UA_", level: "hard" },
  { slug: "uruguay", name: "Uruguay", blanked: "_RU_U__", level: "hard" },
  { slug: "suriname", name: "Suriname", blanked: "S__IN_M_", level: "hard" },
  { slug: "mauritania", name: "Mauritania", blanked: "_A_R_TAN__", level: "hard" },
  { slug: "mauritius", name: "Mauritius", blanked: "__U_I__US", level: "hard" },
  { slug: "seychelles", name: "Seychelles", blanked: "S___H_LLE_", level: "hard" },
  { slug: "djibouti", name: "Djibouti", blanked: "D___OUT_", level: "hard" },
  { slug: "eritrea", name: "Eritrea", blanked: "_R_T_E_", level: "hard" },
  { slug: "rwanda", name: "Rwanda", blanked: "_WAN__", level: "hard" },
  { slug: "burundi", name: "Burundi", blanked: "__R__DI", level: "hard" },
  { slug: "malawi", name: "Malawi", blanked: "__L_WI", level: "hard" },
  { slug: "zambia", name: "Zambia", blanked: "__MB_A", level: "hard" },
  { slug: "gambia", name: "Gambia", blanked: "GA__I_", level: "hard" },
  { slug: "senegal", name: "Senegal", blanked: "_E_E_A_", level: "hard" },
  { slug: "guinea", name: "Guinea", blanked: "GU__E_", level: "hard" },
  { slug: "somalia", name: "Somalia", blanked: "S__A__A", level: "hard" },
  { slug: "namibia", name: "Namibia", blanked: "NA___I_", level: "hard" },
  { slug: "angola", name: "Angola", blanked: "AN___A", level: "hard" },
  // IMPOSSIBLE (25)
  { slug: "kazakhstan", name: "Kazakhstan", blanked: "_A____S_AN", level: "impossible" },
  { slug: "uzbekistan", name: "Uzbekistan", blanked: "_Z_E_IS___", level: "impossible" },
  { slug: "azerbaijan", name: "Azerbaijan", blanked: "A______JAN", level: "impossible" },
  { slug: "turkmenistan", name: "Turkmenistan", blanked: "TU___E__S_A_", level: "impossible" },
  { slug: "kyrgyzstan", name: "Kyrgyzstan", blanked: "_____ZST_N", level: "impossible" },
  { slug: "tajikistan", name: "Tajikistan", blanked: "___IKI__A_", level: "impossible" },
  { slug: "liechtenstein", name: "Liechtenstein", blanked: "LI__HT_____I_", level: "impossible" },
  { slug: "montenegro", name: "Montenegro", blanked: "__NTE____O", level: "impossible" },
  { slug: "kiribati", name: "Kiribati", blanked: "___IBA__", level: "impossible" },
  { slug: "vanuatu", name: "Vanuatu", blanked: "____ATU", level: "impossible" },
  { slug: "tuvalu", name: "Tuvalu", blanked: "_UV___", level: "impossible" },
  { slug: "nauru", name: "Nauru", blanked: "N_U__", level: "impossible" },
  { slug: "palau", name: "Palau", blanked: "P___U", level: "impossible" },
  { slug: "comoros", name: "Comoros", blanked: "C__O_O_", level: "impossible" },
  { slug: "eswatini", name: "Eswatini", blanked: "_S_AT___", level: "impossible" },
  { slug: "lesotho", name: "Lesotho", blanked: "___OT_O", level: "impossible" },
  { slug: "moldova", name: "Moldova", blanked: "_O__O_A", level: "impossible" },
  { slug: "belarus", name: "Belarus", blanked: "BE____S", level: "impossible" },
  { slug: "micronesia", name: "Micronesia", blanked: "MI__O_E___", level: "impossible" },
  { slug: "saint-lucia", name: "Saint Lucia", blanked: "____T L_C_A", level: "impossible" },
  { slug: "sao-tome-and-principe", name: "Sao Tome and Principe", blanked: "___ _OM_ _ND ____CIP_", level: "impossible" },
  { slug: "burkina-faso", name: "Burkina Faso", blanked: "B_R_I__ __S_", level: "impossible" },
  { slug: "equatorial-guinea", name: "Equatorial Guinea", blanked: "E___TO____ G__N_A", level: "impossible" },
  { slug: "sri-lanka", name: "Sri Lanka", blanked: "SRI _____", level: "impossible" },
  { slug: "bosnia-and-herzegovina", name: "Bosnia and Herzegovina", blanked: "______ __D HERZ__OVI__", level: "impossible" },
];
