// E234 «Guess the Movie by Emoji» (8th movie episode) — facts, one TRUE fact per id, <=70 chars
export const MOVIE_EMOJI8_FACTS = {
  "lilo-stitch": "Disney's 2002 film coined \"ohana means family, nobody left behind\"",
  "mulan": "1998 Disney film based on the Chinese legend of Hua Mulan",
  "pocahontas": "1995 Disney film loosely inspired by a real Powhatan woman",
  "hercules": "1997 Disney film reimagines the Greek demigod's myth",
  "my-neighbor-totoro": "Studio Ghibli's Totoro became the studio's mascot logo",
  "mrs-doubtfire": "Robin Williams played a dad disguised as a Scottish nanny",
  "dirty-dancing": "1987 film made \"the lift\" and \"Time of My Life\" iconic",
  "charlie-chocolate-factory": "Tim Burton's 2005 film starred Johnny Depp as Willy Wonka",
  "justice-league": "2017 DC film united Batman, Superman, Wonder Woman & more",
  "captain-marvel": "2019 film introduced Brie Larson as Carol Danvers",
  "klaus": "2019 Netflix film reimagines the origin of Santa Claus",
  "iron-giant": "1999 animated film about a boy who befriends a robot",
  "fantastic-mr-fox": "Wes Anderson's 2009 stop-motion film based on Roald Dahl",
  "casino-royale": "2006 film introduced Daniel Craig as James Bond",
  "shang-chi": "2021 Marvel film starred Simu Liu as Shang-Chi",
  "league-of-their-own": "1992 film about a real WWII-era women's baseball league",
  "napoleon-dynamite": "2004 indie comedy famous for its tater tot scene",
  "ponyo": "Studio Ghibli's 2008 tale of a fish who wants to be human",
  "fantasia": "1940 Disney film set animation to classical music",
  "spirited-away": "Studio Ghibli's Oscar-winning film about a bathhouse for spirits",
  "deadpool-wolverine": "2024 film became the highest-grossing R-rated movie ever",
  "sonic-3": "2024 film introduced Keanu Reeves as Shadow the Hedgehog",
  "spider-man-far-from-home": "2019 film sent Peter Parker on a European school trip",
  "robin-hood": "1973 Disney film portrayed Robin Hood as an anthropomorphic fox",
  "lady-and-the-tramp": "1955 Disney film's spaghetti kiss scene is a classic",

  "emperors-new-groove": "2000 Disney film turns Kuzco the emperor into a llama",
  "aristocats": "1970 Disney film follows aristocratic cats lost in Paris",
  "kikis-delivery-service": "Studio Ghibli's 1989 film follows a young witch's courier job",
  "howls-moving-castle": "Studio Ghibli's 2004 film is based on a Diana Wynne Jones novel",
  "princess-mononoke": "Studio Ghibli's 1997 epic centers on a forest war",
  "akira": "1988 anime film based on Katsuhiro Otomo's own manga",
  "your-name": "Makoto Shinkai's 2016 body-swap anime became a global smash hit",
  "run-lola-run": "1998 German film replays 20 minutes three different ways",
  "the-intouchables": "2011 French film is based on a real friendship story",
  "leon-professional": "1994 film starred Jean Reno as a hitman who shelters a girl",
  "tenet": "Christopher Nolan's 2020 film centers on time inversion",
  "three-idiots": "2009 Bollywood film became one of India's top-grossing films",
  "dangal": "2016 Bollywood film is based on real wrestler sisters",
  "rrr": "2022 Telugu film's song \"Naatu Naatu\" won an Oscar",
  "baahubali": "2015 Telugu epic was India's costliest film at release",
  "ed-wood": "Tim Burton's 1994 biopic stars Johnny Depp as a B-movie director",
  "sleepy-hollow": "Tim Burton's 1999 film reimagines the Headless Horseman tale",
  "close-encounters": "Spielberg's 1977 film's five-note motif is instantly iconic",
  "ai-artificial-intelligence": "2001 Spielberg film was originally developed by Stanley Kubrick",
  "war-horse": "Spielberg's 2011 film follows a horse through World War I",
  "casino-1995": "Scorsese's 1995 film is set in the Las Vegas mob scene",
  "the-irishman": "Scorsese's 2019 film reunited De Niro and Pacino on screen",
  "dark-knight-rises": "2012 film closed Christopher Nolan's Batman trilogy",
  "goldeneye": "1995 film introduced Pierce Brosnan as James Bond",
  "eternals": "2021 Marvel film introduced a group of ancient immortal heroes",

  "ran": "Akira Kurosawa's 1985 epic reimagines King Lear in feudal Japan",
  "hero-2002": "Zhang Yimou's 2002 film uses color to tell shifting versions of events",
  "house-of-flying-daggers": "2004 Chinese wuxia film stars Zhang Ziyi as a blind dancer",
  "decision-to-leave": "Park Chan-wook's 2022 film won Best Director at Cannes",
  "shoplifters": "Kore-eda's 2018 film won the Palme d'Or at Cannes",
  "lives-of-others": "2006 German film won the Oscar for Best Foreign Language Film",
  "motorcycle-diaries": "2004 film follows young Che Guevara's trip across South America",
  "amores-perros": "Iñárritu's 2000 debut links three stories via a car crash",
  "secret-in-their-eyes": "2009 Argentine film won the Oscar for Best Foreign Language Film",
  "volver": "Pedro Almodóvar's 2006 film stars Penélope Cruz in rural Spain",
  "central-station": "1998 Brazilian film follows a letter-writer and an orphan boy",
  "lagaan": "2001 Bollywood film centers on a cricket match against colonial rule",
  "pk": "2014 Bollywood film follows an alien questioning religion on Earth",
  "timbuktu": "2014 Mauritanian film was nominated for the Oscar's foreign category",
  "wadjda": "2012 film was the first feature shot entirely in Saudi Arabia",
  "theeb": "2014 Jordanian film follows a Bedouin boy during World War I",
  "capernaum": "2018 Lebanese film follows a boy who sues his own parents",
  "tsotsi": "2005 South African film won the Oscar for Best Foreign Language Film",
  "leviathan-2014": "2014 Russian film was nominated for the Oscar's foreign category",
  "come-and-see": "1985 Soviet film depicts a boy's ordeal in Nazi-occupied Belarus",
  "jackie-brown": "Quentin Tarantino's 1997 film is based on an Elmore Leonard novel",
  "rushmore": "Wes Anderson's 1998 film stars Jason Schwartzman as a student",
  "royal-tenenbaums": "Wes Anderson's 2001 film follows three estranged genius siblings",
  "insomnia": "Christopher Nolan's 2002 film is set during endless Alaskan daylight",
  "paths-of-glory": "Stanley Kubrick's 1957 film depicts a WWI court-martial",

  "tampopo": "1985 Japanese \"ramen western\" follows a quest for perfect noodles",
  "departures": "2008 Japanese film about a mortician won the Oscar for foreign film",
  "children-of-heaven": "1997 Iranian film follows siblings sharing one pair of shoes",
  "color-of-paradise": "1999 Iranian film centers on a blind boy and his father",
  "taste-of-cherry": "Abbas Kiarostami's 1997 film won the Palme d'Or at Cannes",
  "the-salesman": "Asghar Farhadi's 2016 film won the Oscar for Best Foreign Film",
  "la-haine": "1995 French film follows three friends after a riot, in b&w",
  "holy-motors": "2012 French film follows a man who lives out strange roles in a limo",
  "a-prophet": "Jacques Audiard's 2009 film follows a young inmate's rise in prison",
  "diving-bell-butterfly": "2007 film is based on a memoir written by blinking one eye",
  "micmacs": "2009 French film follows a man plotting revenge on arms dealers",
  "all-about-my-mother": "Pedro Almodóvar's 1999 film won the Oscar for foreign film",
  "elite-squad": "2007 Brazilian film follows an elite police unit in Rio favelas",
  "yesterday-za": "2004 South African film was the first Zulu-language Oscar nominee",
  "tale-of-princess-kaguya": "Studio Ghibli's 2013 film is based on a 10th-century folktale",
  "weathering-with-you": "Makoto Shinkai's 2019 anime follows a girl who can control the weather",
  "grave-of-the-fireflies": "Studio Ghibli's 1988 film follows siblings in wartime Japan",
  "i-saw-the-devil": "2010 Korean thriller follows a man hunting a serial killer",
  "the-wailing": "2016 Korean horror film is set in a rural village outbreak",
  "broker": "Kore-eda's 2022 film follows a broker selling abandoned babies",
  "death-proof": "Quentin Tarantino's 2007 film stars Kurt Russell as a stuntman killer",
  "after-hours": "Martin Scorsese's 1985 dark comedy unfolds over one bad night in SoHo",
  "empire-of-the-sun": "Spielberg's 1987 film follows a boy in a Japanese internment camp",
  "the-great-beauty": "2013 Italian film won the Oscar for Best Foreign Language Film",
  "yi-yi": "Edward Yang's 2000 Taiwanese film follows a Taipei family over a year",
};
