// E125 emoji-movie-2 facts — one verified <=70-char fact per movie, shown on reveal.
export const MOVIE_EMOJI_2_FACTS = {
  // EASY
  "home-alone": "1990 comedy; an 8-year-old defends his house from burglars.",
  "the-sound-of-music": "1965 musical won Best Picture; based on the Von Trapps.",
  "grease": "1978 musical starring John Travolta and Olivia Newton-John.",
  "willy-wonka-and-the-chocolate-factory": "1971 film; Gene Wilder played the eccentric candy maker.",
  "mary-poppins": "1964 Disney film; Julie Andrews won an Oscar for the role.",
  "spider-man-into-the-spider-verse": "2018 film won the Best Animated Feature Oscar.",
  "monsters-inc": "Pixar's 2001 film powers a city with children's screams.",
  "101-dalmatians": "1961 Disney film; Cruella de Vil wants a spotted-fur coat.",
  "encanto": "2021 Disney film; the Madrigal family lives in a magic house.",
  "sing": "2016 film; animals compete in a singing contest to save a theater.",
  "the-secret-life-of-pets": "2016 film shows what pets do while owners are out.",
  "hotel-transylvania": "2012 film; Dracula runs a hotel for monsters.",
  "shark-tale": "2004 film; a fish pretends to be a shark to gain fame.",
  "the-grinch": "How the Grinch Stole Christmas! is a classic Seuss tale.",
  "elf": "2003 film; Will Ferrell plays a human raised as a Santa's elf.",
  "the-polar-express": "2004 film; a boy rides a train to the North Pole.",
  "night-at-the-museum": "2006 film; museum exhibits come alive at night.",
  "the-mask": "1994 film; Jim Carrey wears a mask with wild powers.",
  "the-nutty-professor": "1996 film; Eddie Murphy plays a shy scientist.",
  "ghostbusters": "1984 film; a team traps ghosts around New York City.",
  "the-santa-clause": "1994 film; Tim Allen accidentally becomes Santa.",
  "cinderella": "1950 Disney classic based on the Charles Perrault fairy tale.",
  "snow-white-and-the-seven-dwarfs": "1937 film was Disney's first full-length animated feature.",
  "pinocchio": "1940 Disney film; a wooden puppet wants to become real.",
  "dumbo": "1941 Disney film; a baby elephant flies with his big ears.",

  // MEDIUM
  "the-truman-show": "1998 film; Jim Carrey's whole life is a live TV show.",
  "gravity": "2013 film won 7 Oscars including Best Director for Cuaron.",
  "the-martian": "2015 film; Matt Damon grows potatoes stranded on Mars.",
  "gone-girl": "2014 film based on Gillian Flynn's bestselling novel.",
  "the-social-network": "2010 film chronicles Facebook's founding at Harvard.",
  "the-wolf-of-wall-street": "2013 Scorsese film; DiCaprio plays a corrupt stockbroker.",
  "die-hard": "1988 film; John McClane fights terrorists in Nakatomi Plaza.",
  "top-gun": "1986 film; Tom Cruise trains as an elite Navy fighter pilot.",
  "the-fast-and-the-furious": "2001 film launched a street-racing franchise.",
  "mission-impossible": "1996 film; Tom Cruise's first outing as Ethan Hunt.",
  "skyfall": "2012 Bond film; Adele's theme song won an Oscar.",
  "the-devil-wears-prada": "2006 film; Streep plays a ruthless fashion editor.",
  "mean-girls": "2004 film; Tina Fey wrote this high school comedy.",
  "legally-blonde": "2001 film; Reese Witherspoon takes on Harvard Law.",
  "bridesmaids": "2011 comedy earned Melissa McCarthy an Oscar nomination.",
  "the-hangover": "2009 film; groomsmen lose the groom after a wild night.",
  "superbad": "2007 comedy; teens scramble to buy alcohol before a party.",
  "12-years-a-slave": "2013 film won Best Picture, based on a true memoir.",
  "the-help": "2011 film; Octavia Spencer won Best Supporting Actress.",
  "green-book": "2018 film won Best Picture; a road trip through the South.",
  "the-shawshank-redemption": "1994 film; based on a Stephen King novella.",
  "the-notebook": "2004 romance based on Nicholas Sparks' novel.",
  "a-star-is-born": "2018 version; Lady Gaga and Bradley Cooper star.",
  "ferris-buellers-day-off": "1986 film; a teen skips school for a day in Chicago.",
  "the-breakfast-club": "1985 film; five students share Saturday detention.",

  // HARD
  "memento": "2000 Nolan film told in reverse about a man who can't form memories.",
  "there-will-be-blood": "2007 film; Day-Lewis won an Oscar as an oilman.",
  "the-prestige": "2006 Nolan film about rival Victorian-era magicians.",
  "donnie-darko": "2001 cult film features a man in a giant rabbit suit.",
  "eternal-sunshine-of-the-spotless-mind": "2004 film; a couple erases memories of each other.",
  "trainspotting": "1996 film follows heroin addicts in Edinburgh.",
  "reservoir-dogs": "1992 Tarantino debut about a botched jewel heist.",
  "goodfellas": "1990 Scorsese film chronicles a mobster's rise and fall.",
  "the-usual-suspects": "1995 film; Kevin Spacey won an Oscar as Verbal Kint.",
  "se7en": "1995 film; detectives hunt a killer using deadly sins.",
  "american-beauty": "1999 film won Best Picture about suburban discontent.",
  "the-sixth-sense": "1999 film; a boy famously sees dead people.",
  "get-out": "2017 film; Peele won the Best Original Screenplay Oscar.",
  "the-substance": "2024 body-horror film earned Demi Moore an Oscar nod.",
  "everything-everywhere-all-at-once": "2022 film swept the Oscars, winning Best Picture.",
  "moonlight": "2016 film won Best Picture after a famous envelope mix-up.",
  "spotlight": "2015 film won Best Picture about uncovering church abuse.",
  "manchester-by-the-sea": "2016 film; Casey Affleck won Best Actor.",
  "the-lighthouse": "2019 film; two keepers descend into madness on an island.",
  "hereditary": "2018 horror film centers on a family's dark inheritance.",
  "midsommar": "2019 film sets a folk-horror cult in bright Swedish daylight.",
  "the-witch": "2015 film; a Puritan family suspects a witch in the woods.",
  "arrival": "2016 film; a linguist decodes an alien language to stop war.",
  "her": "2013 film; a man falls in love with an AI operating system.",
  "drive": "2011 film; Gosling plays a nameless Hollywood stunt driver.",

  // IMPOSSIBLE
  "persona": "1966 Bergman film blends two women's identities together.",
  "eight-and-a-half": "Fellini's 1963 film follows a director's creative block.",
  "rashomon": "1950 Kurosawa film tells one crime from four viewpoints.",
  "sunset-boulevard": "1950 film narrated by a dead man floating in a pool.",
  "double-indemnity": "1944 noir; an insurance man plots murder for a payout.",
  "the-cabinet-of-dr-caligari": "1920 German film pioneered expressionist horror.",
  "battleship-potemkin": "1925 Eisenstein film famous for the Odessa Steps scene.",
  "the-passion-of-joan-of-arc": "1928 silent film; Falconetti's face fills the screen.",
  "un-chien-andalou": "1929 surrealist short by Bunuel and Dali.",
  "wild-strawberries": "1957 Bergman film; an old professor confronts his past.",
  "ordet": "1955 Dreyer film ends with a startling miracle at a funeral.",
  "tokyo-story": "1953 Ozu film; aging parents visit their busy grown children.",
  "ugetsu": "1953 Mizoguchi film blends ghosts with wartime Japan.",
  "andrei-rublev": "1966 Tarkovsky film follows a medieval Russian icon painter.",
  "stalker": "1979 Tarkovsky film journeys into a mysterious forbidden Zone.",
  "solaris": "1972 Tarkovsky film; a sentient ocean haunts a space station.",
  "wings-of-desire": "1987 Wenders film; an angel watches over divided Berlin.",
  "the-passenger": "1975 Antonioni film; a reporter swaps identities abroad.",
  "l-avventura": "1960 Antonioni film; a woman vanishes on a rocky island.",
  "the-earrings-of-madame-de": "1953 Ophuls film traces a pair of earrings' journey.",
  "children-of-paradise": "1945 French film shot during the Nazi occupation.",
  "the-rules-of-the-game": "1939 Renoir film satirizes French high society.",
  "grand-illusion": "1937 Renoir film follows POWs during World War I.",
  "man-with-a-movie-camera": "1929 Vertov film is a day-in-the-life city montage.",
  "hour-of-the-wolf": "1968 Bergman film follows an artist's descent into terror.",
};
