// E223 movie-emoji facts — one true <=70-char fact per movie, shown on reveal.
export const MOVIE_EMOJI7_FACTS = {
  // EASY
  "barbie": "Greta Gerwig's 2023 Barbie topped $1.4 billion worldwide.",
  "wicked": "Wicked (2024) stars Cynthia Erivo and Ariana Grande as leads.",
  "oppenheimer": "Oppenheimer (2023) won 7 Oscars including Best Picture.",
  "dune": "Denis Villeneuve's Dune (2021) is based on Herbert's 1965 novel.",
  "puss-in-boots-the-last-wish": "Puss in Boots: The Last Wish (2022) earned an Oscar nomination.",
  "top-gun-maverick": "Top Gun: Maverick (2022) came 36 years after the original film.",
  "inside-out-2": "Inside Out 2 (2024) is the highest-grossing animated film ever.",
  "the-super-mario-bros-movie": "The Super Mario Bros. Movie (2023) has Chris Pratt voicing Mario.",
  "sonic-the-hedgehog-2": "Sonic the Hedgehog 2 (2022) introduced Idris Elba as Knuckles.",
  "godzilla-x-kong-the-new-empire": "This 2024 film is the 5th movie in the MonsterVerse series.",
  "kung-fu-panda-4": "Kung Fu Panda 4 (2024) brought back Jack Black as Po.",
  "despicable-me-4": "Despicable Me 4 (2024) introduced Gru's baby son, Gru Jr.",
  "beetlejuice-beetlejuice": "Beetlejuice Beetlejuice (2024) came 36 years after the original.",
  "the-wild-robot": "The Wild Robot (2024) is based on Peter Brown's book series.",
  "migration": "Migration (2024) follows a mallard duck family from Illumination.",
  "twisters": "Twisters (2024) is a standalone sequel to 1996's Twister.",
  "five-nights-at-freddys": "Five Nights at Freddy's (2023) is based on Scott Cawthon's game.",
  "a-minecraft-movie": "A Minecraft Movie (2025) stars Jack Black as Steve.",
  "anora": "Anora (2024) won the Palme d'Or and the Best Picture Oscar.",
  "wonder-woman-1984": "Wonder Woman 1984 (2020) is set nearly 70 years after the first film.",
  "spider-man-across-the-spider-verse": "Across the Spider-Verse (2023) introduces Spider-Punk.",
  "guardians-of-the-galaxy-vol-3": "Guardians of the Galaxy Vol. 3 (2023) reveals Rocket's origin story.",
  "thor-love-and-thunder": "Thor: Love and Thunder (2022) has Natalie Portman wielding Mjolnir.",
  "ready-player-one": "Ready Player One (2018) was directed by Steven Spielberg.",
  "ant-man-and-the-wasp-quantumania": "Quantumania (2023) introduced Jonathan Majors as Kang.",

  // MEDIUM
  "conclave": "Conclave (2024) is based on Robert Harris's 2016 novel.",
  "challengers": "Challengers (2024) is scored by Trent Reznor and Atticus Ross.",
  "sinners": "Sinners (2025) is Ryan Coogler's original vampire film.",
  "poor-things": "Poor Things (2023) won Emma Stone her second Best Actress Oscar.",
  "godzilla-minus-one": "Godzilla Minus One (2023) won Japan's first VFX Oscar.",
  "coda": "CODA (2021) was the first Apple film to win Best Picture.",
  "nomadland": "Nomadland (2020) won Chloé Zhao the Best Director Oscar.",
  "isle-of-dogs": "Isle of Dogs (2018) is Wes Anderson's second stop-motion film.",
  "the-holdovers": "The Holdovers (2023) reunites Alexander Payne with Paul Giamatti.",
  "american-fiction": "American Fiction (2023) won the Oscar for Best Adapted Screenplay.",
  "roma": "Roma (2018) was shot in black and white by Alfonso Cuarón.",
  "killers-of-the-flower-moon": "Killers of the Flower Moon (2023) is Scorsese's longest film.",
  "moonrise-kingdom": "Moonrise Kingdom (2012) is set on a fictional 1965 island.",
  "annihilation": "Annihilation (2018) is based on Jeff VanderMeer's novel.",
  "civil-war": "Civil War (2024) was written and directed by Alex Garland.",
  "the-marvels": "The Marvels (2023) has the shortest runtime of any MCU film.",
  "napoleon": "Napoleon (2023) reunites Ridley Scott with Joaquin Phoenix.",
  "past-lives": "Past Lives (2023) was Celine Song's feature directorial debut.",
  "the-menu": "The Menu (2022) stars Ralph Fiennes as an unhinged chef.",
  "bodies-bodies-bodies": "Bodies Bodies Bodies (2022) is a Gen-Z slasher satire.",
  "talk-to-me": "Talk to Me (2023) was made by Australian twins the Philippou brothers.",
  "longlegs": "Longlegs (2024) stars Nicolas Cage as the title killer.",
  "late-night-with-the-devil": "Late Night with the Devil (2024) is styled as a 1977 broadcast.",
  "promising-young-woman": "Promising Young Woman (2020) won Emerald Fennell an Oscar.",
  "triangle-of-sadness": "Triangle of Sadness (2022) won the Palme d'Or at Cannes.",

  // HARD
  "portrait-of-a-lady-on-fire": "Portrait of a Lady on Fire (2019) was directed by Céline Sciamma.",
  "drive-my-car": "Drive My Car (2021) won the Oscar for Best International Feature.",
  "the-favourite": "The Favourite (2018) is set in Queen Anne's 18th-century court.",
  "the-green-knight": "The Green Knight (2021) retells a 14th-century Arthurian poem.",
  "pig": "Pig (2021) has Nicolas Cage hunting for his stolen truffle pig.",
  "a-ghost-story": "A Ghost Story (2017) has Casey Affleck under a plain white sheet.",
  "enemy": "Enemy (2013) is Denis Villeneuve's psychological thriller.",
  "swiss-army-man": "Swiss Army Man (2016) was nicknamed the 'farting corpse' movie.",
  "the-handmaiden": "The Handmaiden (2016) is Park Chan-wook's Korean-set thriller.",
  "under-the-skin": "Under the Skin (2013) has Scarlett Johansson playing an alien.",
  "delicatessen": "Delicatessen (1991) was Jean-Pierre Jeunet's debut feature film.",
  "perfect-days": "Perfect Days (2023) is Wim Wenders' Tokyo toilet-cleaner drama.",
  "the-brutalist": "The Brutalist (2024) won Adrien Brody his second Oscar.",
  "anatomy-of-a-fall": "Anatomy of a Fall (2023) won the Palme d'Or at Cannes.",
  "the-zone-of-interest": "The Zone of Interest (2023) won Best International Feature Oscar.",
  "the-iron-claw": "The Iron Claw (2023) tells the Von Erich wrestling family's story.",
  "aftersun": "Aftersun (2022) was Charlotte Wells' debut feature film.",
  "the-fabelmans": "The Fabelmans (2022) is Steven Spielberg's semi-autobiography.",
  "tar": "Tár (2022) stars Cate Blanchett as a fictional orchestra conductor.",
  "the-whale": "The Whale (2022) won Brendan Fraser the Best Actor Oscar.",
  "emilia-perez": "Emilia Pérez (2024) is a mostly Spanish-language musical crime film.",
  "flow": "Flow (2024) won Best Animated Feature and has no dialogue.",
  "the-banshees-of-inisherin": "The Banshees of Inisherin (2022) reunites the In Bruges duo.",
  "asteroid-city": "Asteroid City (2023) is set in a fictional 1955 desert town.",
  "the-french-dispatch": "The French Dispatch (2021) is styled as a magazine anthology.",

  // IMPOSSIBLE
  "dogtooth": "Dogtooth (2009) is Yorgos Lanthimos' breakout Greek film.",
  "force-majeure": "Force Majeure (2014) centers on an avalanche at a ski resort.",
  "the-worst-person-in-the-world": "The Worst Person in the World (2021) is a Norwegian film.",
  "memories-of-murder": "Memories of Murder (2003) is Bong Joon-ho's second feature.",
  "burning": "Burning (2018) is based on a Haruki Murakami short story.",
  "ida": "Ida (2013) won Poland its first Best Foreign Film Oscar.",
  "cold-war": "Cold War (2018) won Paweł Pawlikowski Best Director at Cannes.",
  "a-separation": "A Separation (2011) won Iran its first competitive Oscar.",
  "chungking-express": "Chungking Express (1994) was directed by Wong Kar-wai.",
  "in-the-mood-for-love": "In the Mood for Love (2000) is set in 1960s Hong Kong.",
  "the-double-life-of-veronique": "The Double Life of Véronique (1991) is by Krzysztof Kieślowski.",
  "aguirre-the-wrath-of-god": "Aguirre, the Wrath of God (1972) stars Klaus Kinski.",
  "petite-maman": "Petite Maman (2021) is by Céline Sciamma and runs 72 minutes.",
  "happy-as-lazzaro": "Happy as Lazzaro (2018) won Best Screenplay at Cannes.",
  "beau-is-afraid": "Beau Is Afraid (2023) is Ari Aster's nearly three-hour odyssey.",
  "the-eternal-daughter": "The Eternal Daughter (2022) has Tilda Swinton in dual roles.",
  "godland": "Godland (2022) was Iceland's Oscar submission that year.",
  "the-taste-of-things": "The Taste of Things (2023) won Tran Anh Hung Best Director.",
  "playtime": "Playtime (1967) is Jacques Tati's nearly wordless comedy.",
  "wild-tales": "Wild Tales (2014) is an Argentine anthology of six stories.",
  "amour": "Amour (2012) won Michael Haneke the Palme d'Or and an Oscar.",
  "the-white-ribbon": "The White Ribbon (2009) won Michael Haneke the Palme d'Or.",
  "toni-erdmann": "Toni Erdmann (2016) is a German comedy about a prankster dad.",
  "cleo-from-5-to-7": "Cléo from 5 to 7 (1962) unfolds in near real time.",
  "the-assassin": "The Assassin (2015) won Hou Hsiao-hsien Best Director at Cannes.",
};
