// E180 «Guess the Movie by Emoji 4» — 100 movies · 25/tier
// VO: sfx/e180-<id>.wav
export const MOVIE_EMOJI_4 = [
  // ===== EASY (25) =====
  { id: "trolls", title: "Trolls", emojis: "🧌🎤", level: "easy" },
  { id: "bolt", title: "Bolt", emojis: "🐕⚡", level: "easy" },
  { id: "chicken-run", title: "Chicken Run", emojis: "🐔🏃", level: "easy" },
  { id: "a-bugs-life", title: "A Bug's Life", emojis: "🐜🦗", level: "easy" },
  { id: "ferdinand", title: "Ferdinand", emojis: "🐂🌸", level: "easy" },
  { id: "rango", title: "Rango", emojis: "🦎🤠", level: "easy" },
  { id: "surfs-up", title: "Surf's Up", emojis: "🐧🏄", level: "easy" },
  { id: "hop", title: "Hop", emojis: "🐰🥚", level: "easy" },
  { id: "flushed-away", title: "Flushed Away", emojis: "🐭🚽", level: "easy" },
  { id: "planes", title: "Planes", emojis: "✈🏁", level: "easy" },
  { id: "the-emoji-movie", title: "The Emoji Movie", emojis: "😀📱", level: "easy" },
  { id: "twilight", title: "Twilight", emojis: "🧛🌗", level: "easy" },
  { id: "the-chronicles-of-narnia", title: "The Chronicles of Narnia", emojis: "🦁🚪", level: "easy" },
  { id: "it", title: "It", emojis: "🤡🎈", level: "easy" },
  { id: "a-quiet-place", title: "A Quiet Place", emojis: "🤫👽", level: "easy" },
  { id: "halloween", title: "Halloween", emojis: "🎃🔪", level: "easy" },
  { id: "sherlock-holmes", title: "Sherlock Holmes", emojis: "🔍🎩", level: "easy" },
  { id: "oceans-eleven", title: "Ocean's Eleven", emojis: "🎰💰", level: "easy" },
  { id: "the-hobbit", title: "The Hobbit", emojis: "🐉💎", level: "easy" },
  { id: "bird-box", title: "Bird Box", emojis: "🐦📦", level: "easy" },
  { id: "free-guy", title: "Free Guy", emojis: "🕶🎮", level: "easy" },
  { id: "wonka", title: "Wonka", emojis: "🎩🍫", level: "easy" },
  { id: "paddington", title: "Paddington", emojis: "🐻🧳", level: "easy" },
  { id: "peter-rabbit", title: "Peter Rabbit", emojis: "🐰🥕", level: "easy" },
  { id: "garfield", title: "Garfield", emojis: "🐱🍝", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "the-italian-job", title: "The Italian Job", emojis: "🚗🥇", level: "medium" },
  { id: "now-you-see-me", title: "Now You See Me", emojis: "🃏🔮", level: "medium" },
  { id: "knives-out", title: "Knives Out", emojis: "🔪🕵", level: "medium" },
  { id: "murder-on-the-orient-express", title: "Murder on the Orient Express", emojis: "🚂🕵", level: "medium" },
  { id: "the-great-gatsby", title: "The Great Gatsby", emojis: "🥂🎊", level: "medium" },
  { id: "catch-me-if-you-can", title: "Catch Me If You Can", emojis: "✈👮", level: "medium" },
  { id: "the-fifth-element", title: "The Fifth Element", emojis: "🚕👽", level: "medium" },
  { id: "total-recall", title: "Total Recall", emojis: "🧠🪐", level: "medium" },
  { id: "edge-of-tomorrow", title: "Edge of Tomorrow", emojis: "👽🔁", level: "medium" },
  { id: "pacific-rim", title: "Pacific Rim", emojis: "🤖🌊", level: "medium" },
  { id: "real-steel", title: "Real Steel", emojis: "🤖🥊", level: "medium" },
  { id: "john-wick", title: "John Wick", emojis: "🐕🔫", level: "medium" },
  { id: "taken", title: "Taken", emojis: "📞🔫", level: "medium" },
  { id: "the-terminal", title: "The Terminal", emojis: "🧳✈", level: "medium" },
  { id: "crazy-rich-asians", title: "Crazy Rich Asians", emojis: "💰💍", level: "medium" },
  { id: "face-off", title: "Face/Off", emojis: "🔫🎭", level: "medium" },
  { id: "the-rock", title: "The Rock", emojis: "🪨🏝", level: "medium" },
  { id: "armageddon", title: "Armageddon", emojis: "☄🛢", level: "medium" },
  { id: "independence-day", title: "Independence Day", emojis: "🛸🏙", level: "medium" },
  { id: "the-day-after-tomorrow", title: "The Day After Tomorrow", emojis: "🌊🥶", level: "medium" },
  { id: "shutter-island", title: "Shutter Island", emojis: "🏝🔦", level: "medium" },
  { id: "baby-driver", title: "Baby Driver", emojis: "👶🚗", level: "medium" },
  { id: "con-air", title: "Con Air", emojis: "✈⛓", level: "medium" },
  { id: "the-fugitive", title: "The Fugitive", emojis: "🏃👮", level: "medium" },
  { id: "bad-boys", title: "Bad Boys", emojis: "👮🚓", level: "medium" },

  // ===== HARD (25) =====
  { id: "scream", title: "Scream", emojis: "📞🔪", level: "hard" },
  { id: "a-nightmare-on-elm-street", title: "A Nightmare on Elm Street", emojis: "😴🔪", level: "hard" },
  { id: "friday-the-13th", title: "Friday the 13th", emojis: "🏕🔪", level: "hard" },
  { id: "the-exorcist", title: "The Exorcist", emojis: "✝😈", level: "hard" },
  { id: "the-ring", title: "The Ring", emojis: "📼📞", level: "hard" },
  { id: "saw", title: "Saw", emojis: "🪚🩸", level: "hard" },
  { id: "final-destination", title: "Final Destination", emojis: "💀🎢", level: "hard" },
  { id: "the-blair-witch-project", title: "The Blair Witch Project", emojis: "📹🌲", level: "hard" },
  { id: "world-war-z", title: "World War Z", emojis: "🧟✈", level: "hard" },
  { id: "shaun-of-the-dead", title: "Shaun of the Dead", emojis: "🧟🍺", level: "hard" },
  { id: "the-girl-with-the-dragon-tattoo", title: "The Girl with the Dragon Tattoo", emojis: "🐉👩", level: "hard" },
  { id: "zodiac", title: "Zodiac", emojis: "🔫✉", level: "hard" },
  { id: "nightcrawler", title: "Nightcrawler", emojis: "📹🌃", level: "hard" },
  { id: "american-psycho", title: "American Psycho", emojis: "🪓💼", level: "hard" },
  { id: "gone-in-60-seconds", title: "Gone in 60 Seconds", emojis: "🏎🔑", level: "hard" },
  { id: "the-bourne-identity", title: "The Bourne Identity", emojis: "🕵🧠", level: "hard" },
  { id: "mr-and-mrs-smith", title: "Mr. & Mrs. Smith", emojis: "💑🔫", level: "hard" },
  { id: "kill-bill", title: "Kill Bill", emojis: "👰⚔", level: "hard" },
  { id: "v-for-vendetta", title: "V for Vendetta", emojis: "🎭🗡", level: "hard" },
  { id: "watchmen", title: "Watchmen", emojis: "😃🩸", level: "hard" },
  { id: "kingsman", title: "Kingsman", emojis: "🕴☂", level: "hard" },
  { id: "the-imitation-game", title: "The Imitation Game", emojis: "🧩💻", level: "hard" },
  { id: "a-beautiful-mind", title: "A Beautiful Mind", emojis: "🧠🔢", level: "hard" },
  { id: "the-theory-of-everything", title: "The Theory of Everything", emojis: "♿🌌", level: "hard" },
  { id: "bohemian-rhapsody", title: "Bohemian Rhapsody", emojis: "🎤👑", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "the-elephant-man", title: "The Elephant Man", emojis: "🐘👨", level: "impossible" },
  { id: "raging-bull", title: "Raging Bull", emojis: "🐂🥊", level: "impossible" },
  { id: "the-color-purple", title: "The Color Purple", emojis: "💜✉", level: "impossible" },
  { id: "my-left-foot", title: "My Left Foot", emojis: "🦶🖌", level: "impossible" },
  { id: "amadeus", title: "Amadeus", emojis: "🎼💀", level: "impossible" },
  { id: "chariots-of-fire", title: "Chariots of Fire", emojis: "🏃🔥", level: "impossible" },
  { id: "platoon", title: "Platoon", emojis: "🪖🌴", level: "impossible" },
  { id: "full-metal-jacket", title: "Full Metal Jacket", emojis: "🪖🔫", level: "impossible" },
  { id: "the-french-connection", title: "The French Connection", emojis: "🕵💊", level: "impossible" },
  { id: "kramer-vs-kramer", title: "Kramer vs. Kramer", emojis: "👨👦", level: "impossible" },
  { id: "the-sting", title: "The Sting", emojis: "🃏💵", level: "impossible" },
  { id: "all-quiet-on-the-western-front", title: "All Quiet on the Western Front", emojis: "🪖⚰", level: "impossible" },
  { id: "midnight-cowboy", title: "Midnight Cowboy", emojis: "🤠🌃", level: "impossible" },
  { id: "annie-hall", title: "Annie Hall", emojis: "👓💗", level: "impossible" },
  { id: "tootsie", title: "Tootsie", emojis: "👗🧔", level: "impossible" },
  { id: "the-graduate", title: "The Graduate", emojis: "🎓👰", level: "impossible" },
  { id: "easy-rider", title: "Easy Rider", emojis: "🏍🌵", level: "impossible" },
  { id: "network", title: "Network", emojis: "📺😡", level: "impossible" },
  { id: "dog-day-afternoon", title: "Dog Day Afternoon", emojis: "🏦🔫", level: "impossible" },
  { id: "cinema-paradiso", title: "Cinema Paradiso", emojis: "🎬💗", level: "impossible" },
  { id: "life-is-beautiful", title: "Life Is Beautiful", emojis: "🚂😊", level: "impossible" },
  { id: "das-boot", title: "Das Boot", emojis: "🌊⚓", level: "impossible" },
  { id: "breathless", title: "Breathless", emojis: "🚬🔫", level: "impossible" },
  { id: "bonnie-and-clyde", title: "Bonnie and Clyde", emojis: "👫🔫", level: "impossible" },
  { id: "giant", title: "Giant", emojis: "🛢🤠", level: "impossible" },
];
