// E215 movie-emoji facts — one true <=70-char fact per movie, shown on reveal.
export const MOVIE_EMOJI_6_FACTS = {
  // EASY
  "pretty-woman": "Garry Marshall's 1990 rom-com starred Julia Roberts and Richard Gere.",
  "home-alone-2-lost-in-new-york": "1992 sequel sent Kevin McCallister alone to New York at Christmas.",
  "alien": "Ridley Scott's 1979 sci-fi horror introduced the xenomorph creature.",
  "shazam": "2019 DC film where a boy says a magic word to become a hero.",
  "the-batman": "Matt Reeves directed this 2022 noir take with Robert Pattinson.",
  "man-of-steel": "2013 Superman reboot directed by Zack Snyder, starring Henry Cavill.",
  "aquaman-and-the-lost-kingdom": "2023 DC sequel with Jason Momoa battling a sunken kingdom's ruler.",
  "black-panther-wakanda-forever": "2022 Marvel film honored Chadwick Boseman after his passing.",
  "avengers-endgame": "2019 Marvel epic became the highest-grossing film ever at release.",
  "avengers-infinity-war": "2018 Marvel film ended with Thanos snapping half of all life away.",
  "captain-america-civil-war": "2016 Marvel film split the Avengers over a superhero registration act.",
  "thor-ragnarok": "2017 Marvel film, directed by Taika Waititi, brought comedy to Asgard.",
  "guardians-of-the-galaxy-vol-2": "2017 Marvel sequel revealed Star-Lord's father, Ego the Living Planet.",
  "spider-man-homecoming": "2017 film was Tom Holland's first solo outing as Spider-Man.",
  "toy-story-2": "1999 Pixar sequel introduced Jessie the cowgirl and Prospector.",
  "toy-story-4": "2019 Pixar film introduced Forky, a spork brought to life.",
  "incredibles-2": "2018 Pixar sequel released 14 years after the original film.",
  "shrek-forever-after": "2010 film had Shrek sign a deal with Rumpelstiltskin.",
  "despicable-me-3": "2017 film gave Gru a long-lost identical twin brother, Dru.",
  "space-jam": "1996 film paired Michael Jordan with Bugs Bunny and the Looney Tunes.",
  "jerry-maguire": "1996 film gave the world the line 'Show me the money.'",
  "field-of-dreams": "1989 film with the line 'If you build it, he will come.'",
  "the-sandlot": "1993 film about kids and a legendary baseball chased by a giant dog.",
  "cool-runnings": "1993 film loosely based on Jamaica's first Olympic bobsled team.",
  "talladega-nights": "2006 NASCAR comedy starred Will Ferrell as Ricky Bobby.",
  // MEDIUM
  "gladiator-ii": "2024 sequel followed Lucius, years after Maximus's story ended.",
  "troy": "2004 epic starred Brad Pitt as Achilles in the Trojan War.",
  "kingdom-of-heaven": "2005 Ridley Scott film set during the Crusades in Jerusalem.",
  "the-last-samurai": "2003 film starred Tom Cruise fighting alongside Japanese samurai.",
  "glass-onion-a-knives-out-mystery": "2022 sequel sent detective Benoit Blanc to a Greek island.",
  "the-girl-on-the-train": "2016 thriller followed a woman obsessing over a couple she watches.",
  "sherlock-holmes-a-game-of-shadows": "2011 sequel pitted Holmes against archenemy Moriarty.",
  "pearl-harbor": "2001 film dramatized the 1941 Japanese attack on the US naval base.",
  "hacksaw-ridge": "2016 Mel Gibson film told the true story of medic Desmond Doss.",
  "american-sniper": "2014 Clint Eastwood film starred Bradley Cooper as Chris Kyle.",
  "black-hawk-down": "2001 film depicted the 1993 Battle of Mogadishu in Somalia.",
  "lone-survivor": "2013 film told the true story of a failed 2005 SEAL mission.",
  "into-the-wild": "2007 film followed Christopher McCandless into the Alaskan wild.",
  "127-hours": "2010 film told the true story of trapped hiker Aron Ralston.",
  "wild": "2014 film had Reese Witherspoon hike the Pacific Crest Trail alone.",
  "everest": "2015 film dramatized the deadly 1996 Mount Everest storm disaster.",
  "contagion": "2011 Soderbergh film followed a global pandemic's rapid spread.",
  "i-am-legend": "2007 film starred Will Smith as a survivor alone in New York City.",
  "train-to-busan": "2016 Korean film had passengers fighting a zombie outbreak on a train.",
  "28-days-later": "2002 Danny Boyle film had a man waking from a coma to an outbreak.",
  "the-conjuring": "2013 film introduced paranormal investigators Ed and Lorraine Warren.",
  "insidious": "2010 horror film had a boy trapped in the astral realm called Further.",
  "sinister": "2012 film followed a writer finding cursed home-movie reels.",
  "the-babadook": "2014 Australian horror film centered on a sinister pop-up book.",
  "smile": "2022 horror film followed a doctor cursed after witnessing a suicide.",
  // HARD
  "m3gan": "2022 film centered on a lifelike AI doll that turns deadly.",
  "childs-play": "1988 horror film introduced Chucky, a doll with a killer's soul.",
  "the-purge": "2013 film imagined a night when all crime is legal for 12 hours.",
  "it-follows": "2014 horror film had a curse passed on through sexual contact.",
  "barbarian": "2022 horror film centered on a rental house with a hidden basement.",
  "nope": "2022 Jordan Peele film had ranchers uncover a creature in the sky.",
  "us": "2019 Jordan Peele film had a family confront their sinister doubles.",
  "dont-breathe": "2016 thriller had burglars trapped by a blind, dangerous veteran.",
  "love-actually": "2003 British film wove together ten interlocking love stories.",
  "notting-hill": "1999 rom-com starred Hugh Grant as a bookseller dating a film star.",
  "sleepless-in-seattle": "1993 rom-com starred Tom Hanks and Meg Ryan atop the Empire State.",
  "youve-got-mail": "1998 rom-com had rival booksellers fall in love over email.",
  "when-harry-met-sally": "1989 rom-com asked if men and women can really just be friends.",
  "big-fish": "2003 Tim Burton film explored a father's tall tales, seen by his son.",
  "sweeney-todd": "2007 Tim Burton musical starred Johnny Depp as a vengeful barber.",
  "batman-returns": "1992 Tim Burton film pitted Batman against Penguin and Catwoman.",
  "batman-forever": "1995 film had Val Kilmer as Batman vs Two-Face and Riddler.",
  "batman-and-robin": "1997 film starred George Clooney as Batman battling Mr. Freeze.",
  "green-lantern": "2011 film starred Ryan Reynolds as a test pilot given a power ring.",
  "fantastic-four": "2005 film gave four astronauts powers after cosmic ray exposure.",
  "the-flash": "2023 DC film had Barry Allen alter time by running faster than light.",
  "black-adam": "2022 DC film starred Dwayne Johnson, freed after 5,000 years.",
  "king-arthur": "2004 film retold the legend of the sword-wielding king of Camelot.",
  "the-last-of-the-mohicans": "1992 film starred Daniel Day-Lewis during the French and Indian War.",
  "the-patriot": "2000 film starred Mel Gibson as a farmer turned war fighter.",
  // IMPOSSIBLE
  "the-perfect-storm": "2000 film dramatized a fishing crew lost in a 1991 nor'easter.",
  "san-andreas": "2015 film had Dwayne Johnson survive a massive California earthquake.",
  "deep-impact": "1998 film followed a comet on a collision course with Earth.",
  "2012": "2009 disaster film imagined a global cataclysm on the Mayan calendar.",
  "the-fly": "1986 Cronenberg film had a scientist's DNA fuse with a housefly's.",
  "poltergeist": "1982 film had a suburban family's home invaded by vengeful spirits.",
  "the-amityville-horror": "1979 film was based on a family's claimed haunted-house ordeal.",
  "paranormal-activity": "2007 found-footage film captured a couple haunted by a demon at night.",
  "annabelle": "2014 spin-off traced the origin of the Warrens' haunted doll.",
  "the-master": "A 2012 Paul Thomas Anderson drama about a cult leader and a drifter.",
  "bridge-of-spies": "2015 Spielberg film had a lawyer negotiate a Cold War spy swap.",
  "lincoln": "2012 Spielberg film had Daniel Day-Lewis pass the 13th Amendment.",
  "the-post": "2017 film had The Washington Post publish the leaked Pentagon Papers.",
  "ford-v-ferrari": "2019 film followed Ford's bid to beat Ferrari at Le Mans in 1966.",
  "rocketman": "2019 biopic starred Taron Egerton as musician Elton John.",
  "elvis": "2022 Baz Luhrmann biopic starred Austin Butler as Elvis Presley.",
  "ray": "2004 biopic starred Jamie Foxx as musician Ray Charles.",
  "walk-the-line": "2005 biopic starred Joaquin Phoenix as country singer Johnny Cash.",
  "remember-the-titans": "2000 film followed a newly integrated high school football team.",
  "we-are-marshall": "2006 film honored Marshall University after a 1970 plane crash.",
  "miracle": "2004 film retold the US hockey team's 1980 Olympic gold-medal upset.",
  "rudy": "1993 film told the true story of a determined Notre Dame walk-on.",
  "coach-carter": "2005 film starred Samuel L. Jackson locking his team out for grades.",
  "hoosiers": "1986 film followed a small-town Indiana team's underdog title run.",
  "the-proposal": "2009 rom-com starred Sandra Bullock in a fake engagement in Alaska.",
};
