// E168 «Guess the Movie by Emoji 3» — 100 movies · 25/tier
// VO: sfx/e168-<id>.wav
export const MOVIE_EMOJI_3_FACTS = {
  // EASY
  "how-to-train-your-dragon": "2010 DreamWorks hit; Toothless became its mascot.",
  "sonic-the-hedgehog": "2020 film redesigned Sonic after fan backlash.",
  "wreck-it-ralph": "2012 Disney film full of real video-game cameos.",
  "inside-out": "2015 Pixar film won the Best Animated Feature Oscar.",
  "puss-in-boots": "2011 Shrek spin-off voiced by Antonio Banderas.",
  "happy-feet": "2006 penguin musical won the Animated Feature Oscar.",
  "brave": "2012 Pixar film; Merida was its first female lead.",
  "jumanji": "1995 film starred Robin Williams in a magic board game.",
  "aquaman": "2018 DC film grossed over $1 billion worldwide.",
  "black-panther": "2018 Marvel film; first superhero Best Picture nominee.",
  "godzilla": "2014 reboot of Japan's iconic 1954 monster franchise.",
  "bee-movie": "2007 comedy written by and starring Jerry Seinfeld.",
  "sleeping-beauty": "1959 Disney classic set to Tchaikovsky's ballet music.",
  "bambi": "1942 Disney film; the forest fire is a famous scene.",
  "rio": "2011 animated film set at Rio de Janeiro's Carnival.",
  "big-hero-6": "2014 Disney film won the Best Animated Feature Oscar.",
  "cloudy-with-a-chance-of-meatballs": "2009 film about a machine that rains food.",
  "the-boss-baby": "2017 DreamWorks comedy voiced by Alec Baldwin.",
  "soul": "2020 Pixar film about a jazz pianist won an Oscar.",
  "peter-pan": "1953 Disney classic about the boy who never grows up.",
  "megamind": "2010 DreamWorks film voiced by Will Ferrell.",
  "turning-red": "2022 Pixar film about a girl who becomes a red panda.",
  "the-good-dinosaur": "2015 Pixar film imagining dinosaurs never died out.",
  "raya-and-the-last-dragon": "2021 Disney film set in the land of Kumandra.",
  "onward": "2020 Pixar film about two elf brothers on a quest.",

  // MEDIUM
  "wonder-woman": "2017 film starred Gal Gadot as the Amazon hero.",
  "venom": "2018 Marvel film starred Tom Hardy as the symbiote.",
  "men-in-black": "1997 hit paired Will Smith and Tommy Lee Jones.",
  "transformers": "2007 Michael Bay film based on the Hasbro toys.",
  "the-karate-kid": "1984 film made 'wax on, wax off' famous.",
  "free-willy": "1993 film about a boy freeing a captive orca.",
  "cast-away": "2000 film; Tom Hanks befriends a volleyball named Wilson.",
  "twister": "1996 blockbuster about storm-chasing tornado hunters.",
  "indiana-jones": "1981 Spielberg saga starred Harrison Ford.",
  "the-goonies": "1985 Spielberg adventure about kids hunting treasure.",
  "gremlins": "1984 film; don't feed them after midnight.",
  "beetlejuice": "1988 Tim Burton comedy starred Michael Keaton.",
  "edward-scissorhands": "1990 Tim Burton film starred Johnny Depp.",
  "speed": "1994 thriller; a bus must stay above 50 mph.",
  "national-treasure": "2004 film; Nicolas Cage steals the Declaration.",
  "babe": "1995 film about a pig who herds sheep.",
  "the-mummy": "1999 adventure starred Brendan Fraser in Egypt.",
  "300": "2007 film based on Frank Miller's Spartan graphic novel.",
  "braveheart": "1995 film won Mel Gibson the Best Director Oscar.",
  "groundhog-day": "1993 comedy; Bill Murray relives the same day.",
  "ghost": "1990 romance famous for its pottery-wheel scene.",
  "the-blind-side": "2009 film won Sandra Bullock a Best Actress Oscar.",
  "rain-man": "1988 film won Best Picture; Dustin Hoffman starred.",
  "good-will-hunting": "1997 film won Damon and Affleck a writing Oscar.",
  "dead-poets-society": "1989 film; Robin Williams inspires his students.",

  // HARD
  "gone-with-the-wind": "1939 epic remains the top box-office film adjusted.",
  "the-green-mile": "1999 prison drama based on a Stephen King novel.",
  "life-of-pi": "2012 film won Ang Lee the Best Director Oscar.",
  "the-shape-of-water": "2017 film won Best Picture for Guillermo del Toro.",
  "gandhi": "1982 biopic won Ben Kingsley the Best Actor Oscar.",
  "the-kings-speech": "2010 film won Colin Firth a Best Actor Oscar.",
  "million-dollar-baby": "2004 boxing drama won Eastwood Best Picture.",
  "the-artist": "2011 silent film won Best Picture in 2012.",
  "argo": "2012 Ben Affleck film won the Best Picture Oscar.",
  "dances-with-wolves": "1990 film won Kevin Costner Best Picture.",
  "dunkirk": "2017 Christopher Nolan WWII evacuation epic.",
  "the-english-patient": "1996 romance won nine Academy Awards.",
  "shakespeare-in-love": "1998 film won Best Picture and Gwyneth Paltrow.",
  "out-of-africa": "1985 film won Best Picture; Meryl Streep starred.",
  "the-deer-hunter": "1978 Vietnam War film won the Best Picture Oscar.",
  "crouching-tiger-hidden-dragon": "2000 martial-arts film won four Oscars.",
  "gattaca": "1997 sci-fi film about genetic discrimination.",
  "minority-report": "2002 Spielberg film based on a Philip K. Dick story.",
  "ex-machina": "2014 film won an Oscar for its visual effects.",
  "district-9": "2009 sci-fi film set in a Johannesburg alien slum.",
  "children-of-men": "2006 film set in a future with no newborns.",
  "looper": "2012 time-travel film starred Joseph Gordon-Levitt.",
  "moon": "2009 sci-fi debut of director Duncan Jones.",
  "sunshine": "2007 Danny Boyle film about reigniting the sun.",
  "snowpiercer": "2013 Bong Joon-ho film set on a frozen-earth train.",

  // IMPOSSIBLE
  "lawrence-of-arabia": "1962 epic won seven Oscars including Best Picture.",
  "ben-hur": "1959 epic won a record eleven Academy Awards.",
  "spartacus": "1960 Kubrick epic; 'I'm Spartacus!' is iconic.",
  "the-bridge-on-the-river-kwai": "1957 WWII epic won seven Oscars.",
  "doctor-zhivago": "1965 epic romance set in the Russian Revolution.",
  "north-by-northwest": "1959 Hitchcock film with the crop-duster chase.",
  "the-maltese-falcon": "1941 noir starred Humphrey Bogart as Sam Spade.",
  "rebecca": "1940 Hitchcock film won his only Best Picture Oscar.",
  "some-like-it-hot": "1959 comedy starred Marilyn Monroe and Jack Lemmon.",
  "roman-holiday": "1953 film won Audrey Hepburn her first Oscar.",
  "an-american-in-paris": "1951 musical won the Best Picture Oscar.",
  "my-fair-lady": "1964 musical won eight Oscars including Best Picture.",
  "west-side-story": "1961 musical won ten Academy Awards.",
  "all-about-eve": "1950 film holds a record fourteen Oscar nominations.",
  "on-the-waterfront": "1954 film won Brando his first Best Actor Oscar.",
  "a-streetcar-named-desire": "1951 film based on Tennessee Williams' play.",
  "the-treasure-of-the-sierra-madre": "1948 film about gold-hunting greed.",
  "mutiny-on-the-bounty": "1935 seafaring film won the Best Picture Oscar.",
  "cleopatra": "1963 epic was the most expensive film of its era.",
  "the-ten-commandments": "1956 DeMille epic starred Charlton Heston.",
  "the-lost-weekend": "1945 film about alcoholism won Best Picture.",
  "from-here-to-eternity": "1953 film famous for its beach-kiss scene.",
  "it-happened-one-night": "1934 film swept the top five Oscars.",
  "hamlet": "1948 Olivier film; first non-US Best Picture winner.",
  "grand-hotel": "1932 film won Best Picture with an all-star cast.",
};
