// E192 movie-emoji facts — one true <=70-char fact per movie, shown on reveal.
export const MOVIE_EMOJI_5_FACTS = {
  // EASY
  "terminator-2-judgment-day": "James Cameron's 1991 sequel with groundbreaking liquid-metal CGI.",
  "aliens": "James Cameron's 1986 sequel pits Ripley against a xenomorph hive.",
  "predator": "1987 sci-fi hit starring Schwarzenegger vs an alien hunter.",
  "robocop": "Paul Verhoeven's 1987 satire about a cyborg police officer.",
  "star-trek": "J.J. Abrams' 2009 reboot relaunched the Star Trek film franchise.",
  "star-wars-the-empire-strikes-back": "1980 sequel revealing Darth Vader is Luke's father.",
  "return-of-the-jedi": "1983 finale of the original Star Wars trilogy.",
  "guardians-of-the-galaxy": "James Gunn's 2014 space team-up led by Star-Lord.",
  "iron-man": "2008 film that launched the Marvel Cinematic Universe.",
  "thor": "2011 film introducing the Norse god of thunder to the MCU.",
  "captain-america-the-first-avenger": "2011 origin story of Steve Rogers set in WWII.",
  "black-widow": "2021 MCU film centered on Natasha Romanoff's past.",
  "doctor-strange": "2016 film introducing Marvel's Sorcerer Supreme.",
  "ant-man": "2015 Marvel film about a shrinking superhero suit.",
  "superman": "1978 film starring Christopher Reeve as the Man of Steel.",
  "batman-begins": "2005 Christopher Nolan film restarting the Batman franchise.",
  "suicide-squad": "2016 film about DC supervillains forced to work together.",
  "x-men": "2000 film that launched the mutant superhero franchise.",
  "logan": "2017 film, Hugh Jackman's final outing as Wolverine.",
  "spider-man-no-way-home": "2021 film bringing multiple Spider-Man villains together.",
  "the-incredible-hulk": "2008 film starring Edward Norton as Bruce Banner.",
  "shrek-2": "2004 sequel where Shrek meets Fiona's royal parents.",
  "despicable-me-2": "2013 sequel where Gru joins the Anti-Villain League.",
  "toy-story-3": "2010 sequel where the toys end up at a daycare center.",
  "finding-dory": "2016 Pixar sequel following the forgetful blue tang fish.",

  // MEDIUM
  "frozen-ii": "2019 Disney sequel exploring Elsa's magical origins.",
  "moana-2": "2024 Disney sequel following Moana on a new ocean voyage.",
  "luca": "2021 Pixar film about a sea monster boy in an Italian village.",
  "monsters-university": "2013 Pixar prequel set during Mike and Sulley's college days.",
  "the-croods": "2013 animated film about a prehistoric family's journey.",
  "elemental": "2023 Pixar film pairing fire and water element characters.",
  "matilda": "1996 film based on Roald Dahl's telekinetic schoolgirl story.",
  "james-and-the-giant-peach": "1996 film based on Roald Dahl's tale of a giant peach.",
  "the-bfg": "2016 Spielberg film based on Roald Dahl's Big Friendly Giant.",
  "hook": "1991 Spielberg film where a grown Peter Pan returns to Neverland.",
  "the-princess-bride": "1987 fantasy classic directed by Rob Reiner.",
  "the-neverending-story": "1984 fantasy film about a boy who enters a magical book.",
  "labyrinth": "1986 fantasy film starring David Bowie as the Goblin King.",
  "corpse-bride": "2005 Tim Burton stop-motion film set between two worlds.",
  "coraline": "2009 stop-motion film about a girl who finds a parallel world.",
  "the-nightmare-before-christmas": "1993 Tim Burton stop-motion holiday classic.",
  "minions-the-rise-of-gru": "2022 prequel showing Gru's beginnings as a supervillain.",
  "sing-2": "2021 sequel where Buster Moon stages an even bigger show.",
  "jumanji-welcome-to-the-jungle": "2017 reboot where teens get pulled into a video game.",
  "the-addams-family": "2019 animated film about the famously spooky family.",
  "zombieland": "2009 horror-comedy about survivors in a zombie apocalypse.",
  "the-mummy-returns": "2001 sequel continuing the adventure-horror mummy saga.",
  "jurassic-world-fallen-kingdom": "2018 sequel where dinosaurs escape an erupting volcano.",
  "king-kong-skull-island": "2017 film reimagining Kong's origin on a mysterious island.",
  "rise-of-the-planet-of-the-apes": "2011 film on the origin of an intelligent ape uprising.",

  // HARD
  "inglourious-basterds": "2009 Tarantino WWII film about soldiers hunting Nazis.",
  "the-hateful-eight": "2015 Tarantino western set almost entirely in a snowbound cabin.",
  "once-upon-a-time-in-hollywood": "2019 Tarantino film set in 1969 Los Angeles.",
  "the-big-lebowski": "1998 Coen brothers comedy about a bowling-loving slacker.",
  "fargo": "1996 Coen brothers crime film set in snowy Minnesota.",
  "gone-baby-gone": "2007 Ben Affleck-directed film about a missing child case.",
  "mystic-river": "2003 Clint Eastwood film about childhood trauma and murder.",
  "moneyball": "2011 film about the Oakland A's data-driven baseball strategy.",
  "the-big-short": "2015 film dramatizing the 2008 financial crisis.",
  "wall-street": "1987 Oliver Stone film starring Michael Douglas as Gordon Gekko.",
  "american-history-x": "1998 film about a former neo-Nazi confronting his past.",
  "training-day": "2001 film starring Denzel Washington as a corrupt LAPD cop.",
  "heat": "1995 Michael Mann film with a famous diner face-off scene.",
  "the-town": "2010 Ben Affleck film about Boston bank robbers.",
  "inside-man": "2006 Spike Lee heist thriller starring Denzel Washington.",
  "collateral": "2004 Michael Mann film about a hitman and his cab driver.",
  "prisoners": "2013 film about a father searching for his missing daughter.",
  "sicario": "2015 Denis Villeneuve film about the U.S.-Mexico drug war.",
  "hell-or-high-water": "2016 film about brothers robbing banks in West Texas.",
  "the-machinist": "2004 thriller starring a drastically thin Christian Bale.",
  "the-wrestler": "2008 Aronofsky film starring Mickey Rourke as an aging wrestler.",
  "blue-valentine": "2010 film tracing a marriage's beginning and unraveling.",
  "marriage-story": "2019 Noah Baumbach film about a couple's divorce.",
  "uncut-gems": "2019 Safdie brothers thriller starring Adam Sandler as a gambler.",
  "good-time": "2017 Safdie brothers thriller about a botched bank robbery.",

  // IMPOSSIBLE
  "the-godfather-part-ii": "1974 sequel, the first sequel ever to win Best Picture.",
  "all-the-presidents-men": "1976 film about journalists uncovering Watergate.",
  "serpico": "1973 film starring Al Pacino as an honest NYPD officer.",
  "the-conversation": "1974 Coppola film about a surveillance expert's paranoia.",
  "klute": "1971 thriller starring Jane Fonda as a call girl aiding a case.",
  "midnight-express": "1978 film about an American imprisoned in a Turkish jail.",
  "papillon": "1973 film about a prisoner's escape from a French penal colony.",
  "cool-hand-luke": "1967 film starring Paul Newman as a defiant chain-gang prisoner.",
  "the-hustler": "1961 film starring Paul Newman as a pool hustler.",
  "days-of-heaven": "1978 Terrence Malick film shot largely at golden hour.",
  "barry-lyndon": "1975 Kubrick film shot with lenses developed for NASA.",
  "the-conformist": "1970 Bertolucci film about a man seeking normalcy under fascism.",
  "fanny-and-alexander": "1982 Ingmar Bergman family drama set in 1900s Sweden.",
  "cries-and-whispers": "1972 Bergman film about sisters facing a sister's illness.",
  "through-a-glass-darkly": "1961 Bergman film, first of his 'Silence of God' trilogy.",
  "winter-light": "1963 Bergman film about a pastor's crisis of faith.",
  "ikiru": "1952 Kurosawa film about a bureaucrat facing his mortality.",
  "throne-of-blood": "1957 Kurosawa adaptation of Macbeth set in feudal Japan.",
  "yojimbo": "1961 Kurosawa film starring Toshiro Mifune as a wandering ronin.",
  "sansho-the-bailiff": "1954 Mizoguchi film about a family torn apart by slavery.",
  "late-spring": "1949 Yasujiro Ozu film about a father-daughter relationship.",
  "autumn-sonata": "1978 Bergman film starring Ingrid Bergman as a distant mother.",
  "the-battle-of-algiers": "1966 film depicting Algeria's fight for independence.",
  "jules-and-jim": "1962 Truffaut film about a lifelong love triangle.",
  "the-umbrellas-of-cherbourg": "1964 French film in which all dialogue is sung.",
};
