// E192 «Guess the Movie by Emoji 5» — 100 movies · 25/tier
// VO: sfx/e192-<id>.wav
export const MOVIE_EMOJI_5 = [
  // ===== EASY (25) =====
  { id: "terminator-2-judgment-day", title: "Terminator 2: Judgment Day", emojis: "🤖🕶", level: "easy" },
  { id: "aliens", title: "Aliens", emojis: "👽🔫", level: "easy" },
  { id: "predator", title: "Predator", emojis: "👽🌴", level: "easy" },
  { id: "robocop", title: "RoboCop", emojis: "🤖👮", level: "easy" },
  { id: "star-trek", title: "Star Trek", emojis: "🖖🚀", level: "easy" },
  { id: "star-wars-the-empire-strikes-back", title: "Star Wars: The Empire Strikes Back", emojis: "🌌❄", level: "easy" },
  { id: "return-of-the-jedi", title: "Return of the Jedi", emojis: "🌌⚔", level: "easy" },
  { id: "guardians-of-the-galaxy", title: "Guardians of the Galaxy", emojis: "🦝🚀", level: "easy" },
  { id: "iron-man", title: "Iron Man", emojis: "🦾⚡", level: "easy" },
  { id: "thor", title: "Thor", emojis: "🔨⚡", level: "easy" },
  { id: "captain-america-the-first-avenger", title: "Captain America: The First Avenger", emojis: "🛡⭐", level: "easy" },
  { id: "black-widow", title: "Black Widow", emojis: "🕷🖤", level: "easy" },
  { id: "doctor-strange", title: "Doctor Strange", emojis: "👁🌀", level: "easy" },
  { id: "ant-man", title: "Ant-Man", emojis: "🐜🤏", level: "easy" },
  { id: "superman", title: "Superman", emojis: "🦸🌆", level: "easy" },
  { id: "batman-begins", title: "Batman Begins", emojis: "🦇🌆", level: "easy" },
  { id: "suicide-squad", title: "Suicide Squad", emojis: "🃏💣", level: "easy" },
  { id: "x-men", title: "X-Men", emojis: "🧬🦸", level: "easy" },
  { id: "logan", title: "Logan", emojis: "🐺⚔", level: "easy" },
  { id: "spider-man-no-way-home", title: "Spider-Man: No Way Home", emojis: "🕷🚪", level: "easy" },
  { id: "the-incredible-hulk", title: "The Incredible Hulk", emojis: "💚👊", level: "easy" },
  { id: "shrek-2", title: "Shrek 2", emojis: "🧌👑", level: "easy" },
  { id: "despicable-me-2", title: "Despicable Me 2", emojis: "🍌💛", level: "easy" },
  { id: "toy-story-3", title: "Toy Story 3", emojis: "🤠🔥", level: "easy" },
  { id: "finding-dory", title: "Finding Dory", emojis: "🐟❓", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "frozen-ii", title: "Frozen II", emojis: "⛄🌊", level: "medium" },
  { id: "moana-2", title: "Moana 2", emojis: "🌺⛵", level: "medium" },
  { id: "luca", title: "Luca", emojis: "🐟🚲", level: "medium" },
  { id: "monsters-university", title: "Monsters University", emojis: "👹🎓", level: "medium" },
  { id: "the-croods", title: "The Croods", emojis: "🦴🔥", level: "medium" },
  { id: "elemental", title: "Elemental", emojis: "🔥💧", level: "medium" },
  { id: "matilda", title: "Matilda", emojis: "📚✋", level: "medium" },
  { id: "james-and-the-giant-peach", title: "James and the Giant Peach", emojis: "🍑🐛", level: "medium" },
  { id: "the-bfg", title: "The BFG", emojis: "👴💤", level: "medium" },
  { id: "hook", title: "Hook", emojis: "⚓🪝", level: "medium" },
  { id: "the-princess-bride", title: "The Princess Bride", emojis: "👸⚔", level: "medium" },
  { id: "the-neverending-story", title: "The NeverEnding Story", emojis: "🐉📖", level: "medium" },
  { id: "labyrinth", title: "Labyrinth", emojis: "🌀🧝", level: "medium" },
  { id: "corpse-bride", title: "Corpse Bride", emojis: "💀👰", level: "medium" },
  { id: "coraline", title: "Coraline", emojis: "🔘👁", level: "medium" },
  { id: "the-nightmare-before-christmas", title: "The Nightmare Before Christmas", emojis: "🎃🎄", level: "medium" },
  { id: "minions-the-rise-of-gru", title: "Minions: The Rise of Gru", emojis: "🍌🕶", level: "medium" },
  { id: "sing-2", title: "Sing 2", emojis: "🐨🎸", level: "medium" },
  { id: "jumanji-welcome-to-the-jungle", title: "Jumanji: Welcome to the Jungle", emojis: "🎮🌴", level: "medium" },
  { id: "the-addams-family", title: "The Addams Family", emojis: "🖤🏚", level: "medium" },
  { id: "zombieland", title: "Zombieland", emojis: "🧟🔫", level: "medium" },
  { id: "the-mummy-returns", title: "The Mummy Returns", emojis: "🧟📜", level: "medium" },
  { id: "jurassic-world-fallen-kingdom", title: "Jurassic World: Fallen Kingdom", emojis: "🦖🌋", level: "medium" },
  { id: "king-kong-skull-island", title: "Kong: Skull Island", emojis: "🦍🏝", level: "medium" },
  { id: "rise-of-the-planet-of-the-apes", title: "Rise of the Planet of the Apes", emojis: "🦍🧠", level: "medium" },

  // ===== HARD (25) =====
  { id: "inglourious-basterds", title: "Inglourious Basterds", emojis: "🎬🔥", level: "hard" },
  { id: "the-hateful-eight", title: "The Hateful Eight", emojis: "❄🔫", level: "hard" },
  { id: "once-upon-a-time-in-hollywood", title: "Once Upon a Time in Hollywood", emojis: "📺🔥", level: "hard" },
  { id: "the-big-lebowski", title: "The Big Lebowski", emojis: "🎳🥛", level: "hard" },
  { id: "fargo", title: "Fargo", emojis: "❄🪓", level: "hard" },
  { id: "gone-baby-gone", title: "Gone Baby Gone", emojis: "👶🔍", level: "hard" },
  { id: "mystic-river", title: "Mystic River", emojis: "🌊🔪", level: "hard" },
  { id: "moneyball", title: "Moneyball", emojis: "⚾📊", level: "hard" },
  { id: "the-big-short", title: "The Big Short", emojis: "🏦📉", level: "hard" },
  { id: "wall-street", title: "Wall Street", emojis: "💵📞", level: "hard" },
  { id: "american-history-x", title: "American History X", emojis: "🖤✊", level: "hard" },
  { id: "training-day", title: "Training Day", emojis: "👮💊", level: "hard" },
  { id: "heat", title: "Heat", emojis: "🔫🏙", level: "hard" },
  { id: "the-town", title: "The Town", emojis: "🏦🎭", level: "hard" },
  { id: "inside-man", title: "Inside Man", emojis: "🏦🕶", level: "hard" },
  { id: "collateral", title: "Collateral", emojis: "🌃🔫", level: "hard" },
  { id: "prisoners", title: "Prisoners", emojis: "🧩🔦", level: "hard" },
  { id: "sicario", title: "Sicario", emojis: "🌵🔫", level: "hard" },
  { id: "hell-or-high-water", title: "Hell or High Water", emojis: "🏦🤠", level: "hard" },
  { id: "the-machinist", title: "The Machinist", emojis: "😰⚙", level: "hard" },
  { id: "the-wrestler", title: "The Wrestler", emojis: "🤼💔", level: "hard" },
  { id: "blue-valentine", title: "Blue Valentine", emojis: "💙💔", level: "hard" },
  { id: "marriage-story", title: "Marriage Story", emojis: "💍💔", level: "hard" },
  { id: "uncut-gems", title: "Uncut Gems", emojis: "💎🎰", level: "hard" },
  { id: "good-time", title: "Good Time", emojis: "🌃🏦", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "the-godfather-part-ii", title: "The Godfather Part II", emojis: "🤵🕰", level: "impossible" },
  { id: "all-the-presidents-men", title: "All the President's Men", emojis: "📰🕵", level: "impossible" },
  { id: "serpico", title: "Serpico", emojis: "👮🧔", level: "impossible" },
  { id: "the-conversation", title: "The Conversation", emojis: "🎧🕵", level: "impossible" },
  { id: "klute", title: "Klute", emojis: "📞🕵", level: "impossible" },
  { id: "midnight-express", title: "Midnight Express", emojis: "⛓🌙", level: "impossible" },
  { id: "papillon", title: "Papillon", emojis: "🦋⛓", level: "impossible" },
  { id: "cool-hand-luke", title: "Cool Hand Luke", emojis: "🥚⛓", level: "impossible" },
  { id: "the-hustler", title: "The Hustler", emojis: "🎱💰", level: "impossible" },
  { id: "days-of-heaven", title: "Days of Heaven", emojis: "🌾🔥", level: "impossible" },
  { id: "barry-lyndon", title: "Barry Lyndon", emojis: "🕯⚔", level: "impossible" },
  { id: "the-conformist", title: "The Conformist", emojis: "🕶🖤", level: "impossible" },
  { id: "fanny-and-alexander", title: "Fanny and Alexander", emojis: "🎭👧", level: "impossible" },
  { id: "cries-and-whispers", title: "Cries and Whispers", emojis: "💔😢", level: "impossible" },
  { id: "through-a-glass-darkly", title: "Through a Glass Darkly", emojis: "🪟🌑", level: "impossible" },
  { id: "winter-light", title: "Winter Light", emojis: "❄⛪", level: "impossible" },
  { id: "ikiru", title: "Ikiru", emojis: "🌸⏳", level: "impossible" },
  { id: "throne-of-blood", title: "Throne of Blood", emojis: "👑🏹", level: "impossible" },
  { id: "yojimbo", title: "Yojimbo", emojis: "⚔🥷", level: "impossible" },
  { id: "sansho-the-bailiff", title: "Sansho the Bailiff", emojis: "⛓👨", level: "impossible" },
  { id: "late-spring", title: "Late Spring", emojis: "🌸👘", level: "impossible" },
  { id: "autumn-sonata", title: "Autumn Sonata", emojis: "🎹🍂", level: "impossible" },
  { id: "the-battle-of-algiers", title: "The Battle of Algiers", emojis: "💣🏙", level: "impossible" },
  { id: "jules-and-jim", title: "Jules and Jim", emojis: "👫🚲", level: "impossible" },
  { id: "the-umbrellas-of-cherbourg", title: "The Umbrellas of Cherbourg", emojis: "☂🎤", level: "impossible" },
];
