export const MOVIE_EMOJI9_FACTS = {
  "mission-impossible-fallout": "Tom Cruise performed a real HALO parachute jump for this 2018 film.",
  "iron-man-2": "Released in 2010; introduced Scarlett Johansson's Black Widow.",
  "iron-man-3": "2013 film directed by Shane Black, the third Iron Man movie.",
  "thor-dark-world": "2013 sequel directed by Alan Taylor, second Thor film.",
  "captain-america-winter-soldier": "2014 Marvel film directed by the Russo brothers.",
  "doctor-strange-multiverse-madness": "2022 film directed by Sam Raimi, second Doctor Strange movie.",
  "ant-man-and-the-wasp": "2018 sequel, first MCU film with a woman in the title.",
  "batman-v-superman": "2016 Zack Snyder film, first live-action Batman/Superman team-up.",
  "joker-folie-a-deux": "2024 sequel co-starring Lady Gaga as Harley Quinn.",
  "deadpool-2": "2018 sequel that introduced Josh Brolin as Cable.",
  "venom-let-there-be-carnage": "2021 sequel directed by Andy Serkis.",
  "fast-five": "2011 film, first Fast & Furious to feature Dwayne Johnson.",
  "transformers-age-of-extinction": "2014 film that introduced the Dinobots.",
  "x2-xmen-united": "2003 sequel, Nightcrawler's first film appearance.",
  "pirates-dead-mans-chest": "2006 sequel introduced Davy Jones and the Flying Dutchman.",
  "now-you-see-me-2": "2016 sequel to the 2013 heist-magician film.",
  "john-wick-chapter-2": "2017 sequel where John Wick travels to Rome.",
  "matrix-reloaded": "2003 sequel featured the famous Burly Brawl fight scene.",
  "harry-potter-chamber-secrets": "2002 film, second in the Harry Potter series.",
  "cars-2": "2011 Pixar sequel that turned Mater into a spy.",
  "hunger-games-catching-fire": "2013 sequel, second film in the Hunger Games series.",
  "twilight-new-moon": "2009 sequel, second film in the Twilight Saga.",
  "mufasa-lion-king": "2024 prequel to the 2019 photorealistic Lion King.",
  "dune-part-two": "2024 sequel directed by Denis Villeneuve.",
  "elio": "2025 Pixar film about a boy who contacts aliens.",
  "shrek-the-third": "2007 sequel, third film in the Shrek franchise.",
  "ice-age-meltdown": "2006 sequel, second film in the Ice Age series.",
  "kung-fu-panda-2": "2011 sequel to the 2008 animated film.",
  "madagascar-escape-2-africa": "2008 sequel, second Madagascar film.",
  "enter-the-dragon": "1973 Bruce Lee film, released shortly after his death.",
  "police-story": "1985 Jackie Chan film famous for its mall stunt finale.",
  "drunken-master": "1978 Jackie Chan film that made him a martial arts star.",
  "infernal-affairs": "2002 Hong Kong film that inspired Scorsese's The Departed.",
  "a-better-tomorrow": "1986 John Woo film starring Chow Yun-fat.",
  "la-femme-nikita": "1990 Luc Besson film about a criminal trained as an assassin.",
  "dilwale-dulhania-le-jayenge": "1995 Bollywood romance, one of India's longest-running films.",
  "sholay": "1975 Bollywood classic, often called India's greatest film.",
  "il-postino": "1994 Italian film, Massimo Troisi's final role before his death.",
  "good-bye-lenin": "2003 German film set after the fall of the Berlin Wall.",
  "castle-in-the-sky": "1986 Studio Ghibli's first theatrical feature film.",
  "nausicaa-valley-of-wind": "1984 Miyazaki film that led to Studio Ghibli's founding.",
  "the-wind-rises": "2013 Miyazaki film about aircraft designer Jiro Horikoshi.",
  "la-strada": "1954 Fellini film starring his wife Giulietta Masina.",
  "nights-of-cabiria": "1957 Fellini film that inspired the musical Sweet Charity.",
  "red-sorghum": "1988 Zhang Yimou debut film starring Gong Li.",
  "the-lego-batman-movie": "2017 spin-off from The Lego Movie.",
  "cloudy-2": "2013 sequel to Cloudy with a Chance of Meatballs.",
  "hotel-transylvania-2": "2015 sequel to the 2012 animated film.",
  "ip-man": "2008 biopic of the Wing Chun master who trained Bruce Lee.",
  "man-from-nowhere": "2010 South Korean action film starring Won Bin.",
  "le-samourai": "1967 French film directed by Jean-Pierre Melville.",
  "fitzcarraldo": "1982 Herzog film; the crew hauled a real ship over a hill.",
  "raise-the-red-lantern": "1991 Zhang Yimou film starring Gong Li.",
  "farewell-my-concubine": "1993 Chen Kaige film that won the Cannes Palme d'Or.",
  "to-live": "1994 Zhang Yimou film starring Gong Li.",
  "the-host-2006": "2006 Korean monster film directed by Bong Joon-ho.",
  "mother-2009": "2009 Korean thriller directed by Bong Joon-ho.",
  "hard-boiled": "1992 John Woo film with a famous hospital shootout scene.",
  "thelma-and-louise": "1991 Ridley Scott film starring Susan Sarandon and Geena Davis.",
  "persepolis": "2007 animated film based on Marjane Satrapi's graphic novel.",
  "burnt-by-the-sun": "1994 Russian film, won the Oscar for Best Foreign Language Film.",
  "loveless": "2017 Russian film directed by Andrey Zvyagintsev.",
  "the-return-2003": "2003 Russian film, Zvyagintsev's directorial debut.",
  "nine-queens": "2000 Argentine film about two con artists.",
  "bacurau": "2019 Brazilian film set in a village erased from maps.",
  "another-round": "2020 Danish film starring Mads Mikkelsen.",
  "the-hunt-2012": "2012 Danish film starring Mads Mikkelsen.",
  "the-square-2017": "2017 Ruben Östlund film that won the Cannes Palme d'Or.",
  "system-crasher": "2019 German film about a troubled nine-year-old girl.",
  "after-the-storm": "2016 film directed by Hirokazu Kore-eda.",
  "our-little-sister": "2015 Kore-eda film about four sisters in Kamakura.",
  "nobody-knows": "2004 Kore-eda film based on a real Tokyo case.",
  "three-colors-blue": "1993 Kieślowski film starring Juliette Binoche.",
  "three-colors-red": "1994 Kieślowski film, his final work before his death.",
  "like-father-like-son": "2013 Kore-eda film about two babies switched at birth.",
  "the-mirror-1975": "1975 Andrei Tarkovsky film, semi-autobiographical.",
  "black-girl-1966": "1966 Ousmane Sembène film, a landmark of African cinema.",
  "close-up-1990": "1990 Kiarostami film blending documentary and drama.",
  "shin-godzilla": "2016 Japanese reboot, co-directed by Hideaki Anno.",
  "three-colors-white": "1994 Kieślowski film, second in the Three Colors trilogy.",
  "an-elephant-sitting-still": "2018 Chinese film, director Hu Bo's only feature.",
  "red-desert": "1964 Michelangelo Antonioni film, his first shot in color.",
  "le-trou": "1960 French prison-escape film by Jacques Becker.",
  "army-of-shadows": "1969 Melville film about the French Resistance.",
  "el-topo": "1970 Alejandro Jodorowsky surrealist western.",
  "flowers-of-shanghai": "1998 Hou Hsiao-hsien film set in 1880s Shanghai.",
  "a-brighter-summer-day": "1991 Edward Yang film set in 1960s Taiwan.",
  "woman-in-the-dunes": "1964 Hiroshi Teshigahara film set in a sand-pit village.",
  "onibaba": "1964 Japanese horror film directed by Kaneto Shindo.",
  "kwaidan": "1964 Japanese anthology film of four ghost stories.",
  "house-1977": "1977 Japanese horror-comedy directed by Nobuhiko Obayashi.",
  "branded-to-kill": "1967 Suzuki film about a hitman obsessed with rice.",
  "tokyo-drifter": "1966 Seijun Suzuki yakuza film known for its bold visuals.",
  "black-orpheus": "1959 French-Brazilian film set during Rio's Carnival.",
  "memories-of-underdevelopment": "1968 Cuban film directed by Tomás Gutiérrez Alea.",
  "the-cow-1969": "1969 Iranian film that helped launch the Iranian New Wave.",
  "daughters-of-the-dust": "1991 Julie Dash film about a Gullah family in 1902.",
  "wanda-1970": "1970 film Barbara Loden wrote, directed, and starred in.",
  "touki-bouki": "1973 Senegalese film directed by Djibril Diop Mambéty.",
  "la-jetee": "1962 French sci-fi short told almost entirely in still photos.",
};
