// E168 «Guess the Movie by Emoji 3» — 100 movies · 25/tier
// VO: sfx/e168-<id>.wav
export const MOVIE_EMOJI_3 = [
  // ===== EASY (25) =====
  { id: "how-to-train-your-dragon", title: "How to Train Your Dragon", emojis: "🐉👦", level: "easy" },
  { id: "sonic-the-hedgehog", title: "Sonic the Hedgehog", emojis: "🦔💨", level: "easy" },
  { id: "wreck-it-ralph", title: "Wreck-It Ralph", emojis: "🎮👊", level: "easy" },
  { id: "inside-out", title: "Inside Out", emojis: "🧠😢", level: "easy" },
  { id: "puss-in-boots", title: "Puss in Boots", emojis: "🐱👢", level: "easy" },
  { id: "happy-feet", title: "Happy Feet", emojis: "🐧💃", level: "easy" },
  { id: "brave", title: "Brave", emojis: "🏹👧", level: "easy" },
  { id: "jumanji", title: "Jumanji", emojis: "🎲🌴", level: "easy" },
  { id: "aquaman", title: "Aquaman", emojis: "🌊🔱", level: "easy" },
  { id: "black-panther", title: "Black Panther", emojis: "🐆👑", level: "easy" },
  { id: "godzilla", title: "Godzilla", emojis: "🦎🌆", level: "easy" },
  { id: "bee-movie", title: "Bee Movie", emojis: "🐝🎬", level: "easy" },
  { id: "sleeping-beauty", title: "Sleeping Beauty", emojis: "👸😴", level: "easy" },
  { id: "bambi", title: "Bambi", emojis: "🦌🌲", level: "easy" },
  { id: "rio", title: "Rio", emojis: "🦜🎉", level: "easy" },
  { id: "big-hero-6", title: "Big Hero 6", emojis: "🤖🎈", level: "easy" },
  { id: "cloudy-with-a-chance-of-meatballs", title: "Cloudy with a Chance of Meatballs", emojis: "🌧🍔", level: "easy" },
  { id: "the-boss-baby", title: "The Boss Baby", emojis: "👶💼", level: "easy" },
  { id: "soul", title: "Soul", emojis: "🎹👻", level: "easy" },
  { id: "peter-pan", title: "Peter Pan", emojis: "🧚⚓", level: "easy" },
  { id: "megamind", title: "Megamind", emojis: "👽🧠", level: "easy" },
  { id: "turning-red", title: "Turning Red", emojis: "🐼😡", level: "easy" },
  { id: "the-good-dinosaur", title: "The Good Dinosaur", emojis: "🦕👦", level: "easy" },
  { id: "raya-and-the-last-dragon", title: "Raya and the Last Dragon", emojis: "🐉🗡", level: "easy" },
  { id: "onward", title: "Onward", emojis: "🧝🚐", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "wonder-woman", title: "Wonder Woman", emojis: "🦸🪢", level: "medium" },
  { id: "venom", title: "Venom", emojis: "👽👅", level: "medium" },
  { id: "men-in-black", title: "Men in Black", emojis: "🕶👽", level: "medium" },
  { id: "transformers", title: "Transformers", emojis: "🤖🚗", level: "medium" },
  { id: "the-karate-kid", title: "The Karate Kid", emojis: "🥋👦", level: "medium" },
  { id: "free-willy", title: "Free Willy", emojis: "🐋🌊", level: "medium" },
  { id: "cast-away", title: "Cast Away", emojis: "🏝🏐", level: "medium" },
  { id: "twister", title: "Twister", emojis: "🌪🐄", level: "medium" },
  { id: "indiana-jones", title: "Indiana Jones", emojis: "🎩🏺", level: "medium" },
  { id: "the-goonies", title: "The Goonies", emojis: "🗺💰", level: "medium" },
  { id: "gremlins", title: "Gremlins", emojis: "👹💧", level: "medium" },
  { id: "beetlejuice", title: "Beetlejuice", emojis: "🪲🧃", level: "medium" },
  { id: "edward-scissorhands", title: "Edward Scissorhands", emojis: "✂🖐", level: "medium" },
  { id: "speed", title: "Speed", emojis: "🚌💣", level: "medium" },
  { id: "national-treasure", title: "National Treasure", emojis: "🗺💎", level: "medium" },
  { id: "babe", title: "Babe", emojis: "🐷🏆", level: "medium" },
  { id: "the-mummy", title: "The Mummy", emojis: "🧟🏜", level: "medium" },
  { id: "300", title: "300", emojis: "🛡🗡", level: "medium" },
  { id: "braveheart", title: "Braveheart", emojis: "⚔🏔", level: "medium" },
  { id: "groundhog-day", title: "Groundhog Day", emojis: "🐿🔁", level: "medium" },
  { id: "ghost", title: "Ghost", emojis: "👻🏺", level: "medium" },
  { id: "the-blind-side", title: "The Blind Side", emojis: "🏈🏠", level: "medium" },
  { id: "rain-man", title: "Rain Man", emojis: "🌧👨", level: "medium" },
  { id: "good-will-hunting", title: "Good Will Hunting", emojis: "🧮🧹", level: "medium" },
  { id: "dead-poets-society", title: "Dead Poets Society", emojis: "📖🎓", level: "medium" },

  // ===== HARD (25) =====
  { id: "gone-with-the-wind", title: "Gone with the Wind", emojis: "🌬🍃", level: "hard" },
  { id: "the-green-mile", title: "The Green Mile", emojis: "💚🚶", level: "hard" },
  { id: "life-of-pi", title: "Life of Pi", emojis: "🐅🛶", level: "hard" },
  { id: "the-shape-of-water", title: "The Shape of Water", emojis: "🐟💧", level: "hard" },
  { id: "gandhi", title: "Gandhi", emojis: "👓🕊", level: "hard" },
  { id: "the-kings-speech", title: "The King's Speech", emojis: "👑🎙", level: "hard" },
  { id: "million-dollar-baby", title: "Million Dollar Baby", emojis: "🥊👩", level: "hard" },
  { id: "the-artist", title: "The Artist", emojis: "🎬🔇", level: "hard" },
  { id: "argo", title: "Argo", emojis: "🎬🛂", level: "hard" },
  { id: "dances-with-wolves", title: "Dances with Wolves", emojis: "💃🐺", level: "hard" },
  { id: "dunkirk", title: "Dunkirk", emojis: "🏖⛴", level: "hard" },
  { id: "the-english-patient", title: "The English Patient", emojis: "🏜✈", level: "hard" },
  { id: "shakespeare-in-love", title: "Shakespeare in Love", emojis: "✍💗", level: "hard" },
  { id: "out-of-africa", title: "Out of Africa", emojis: "🐘🌍", level: "hard" },
  { id: "the-deer-hunter", title: "The Deer Hunter", emojis: "🦌🔫", level: "hard" },
  { id: "crouching-tiger-hidden-dragon", title: "Crouching Tiger, Hidden Dragon", emojis: "🐅🐉", level: "hard" },
  { id: "gattaca", title: "Gattaca", emojis: "🧬🚀", level: "hard" },
  { id: "minority-report", title: "Minority Report", emojis: "🔮👮", level: "hard" },
  { id: "ex-machina", title: "Ex Machina", emojis: "🤖💃", level: "hard" },
  { id: "district-9", title: "District 9", emojis: "👽🦐", level: "hard" },
  { id: "children-of-men", title: "Children of Men", emojis: "👶🌍", level: "hard" },
  { id: "looper", title: "Looper", emojis: "🔫🔁", level: "hard" },
  { id: "moon", title: "Moon", emojis: "🌕👨", level: "hard" },
  { id: "sunshine", title: "Sunshine", emojis: "☀🚀", level: "hard" },
  { id: "snowpiercer", title: "Snowpiercer", emojis: "🚂❄", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "lawrence-of-arabia", title: "Lawrence of Arabia", emojis: "🐪🏜", level: "impossible" },
  { id: "ben-hur", title: "Ben-Hur", emojis: "🐎🏛", level: "impossible" },
  { id: "spartacus", title: "Spartacus", emojis: "⛓🗡", level: "impossible" },
  { id: "the-bridge-on-the-river-kwai", title: "The Bridge on the River Kwai", emojis: "🌉💥", level: "impossible" },
  { id: "doctor-zhivago", title: "Doctor Zhivago", emojis: "❄💌", level: "impossible" },
  { id: "north-by-northwest", title: "North by Northwest", emojis: "✈🌽", level: "impossible" },
  { id: "the-maltese-falcon", title: "The Maltese Falcon", emojis: "🦅🗿", level: "impossible" },
  { id: "rebecca", title: "Rebecca", emojis: "🏰🔥", level: "impossible" },
  { id: "some-like-it-hot", title: "Some Like It Hot", emojis: "🎷👗", level: "impossible" },
  { id: "roman-holiday", title: "Roman Holiday", emojis: "🛵👸", level: "impossible" },
  { id: "an-american-in-paris", title: "An American in Paris", emojis: "🎨🗼", level: "impossible" },
  { id: "my-fair-lady", title: "My Fair Lady", emojis: "🌷🗣", level: "impossible" },
  { id: "west-side-story", title: "West Side Story", emojis: "💃🔪", level: "impossible" },
  { id: "all-about-eve", title: "All About Eve", emojis: "🎭🔪", level: "impossible" },
  { id: "on-the-waterfront", title: "On the Waterfront", emojis: "🚢🥊", level: "impossible" },
  { id: "a-streetcar-named-desire", title: "A Streetcar Named Desire", emojis: "🚋🔥", level: "impossible" },
  { id: "the-treasure-of-the-sierra-madre", title: "The Treasure of the Sierra Madre", emojis: "⛏🏜", level: "impossible" },
  { id: "mutiny-on-the-bounty", title: "Mutiny on the Bounty", emojis: "⚓⚔", level: "impossible" },
  { id: "cleopatra", title: "Cleopatra", emojis: "👸🐍", level: "impossible" },
  { id: "the-ten-commandments", title: "The Ten Commandments", emojis: "📜🌊", level: "impossible" },
  { id: "the-lost-weekend", title: "The Lost Weekend", emojis: "🍸😖", level: "impossible" },
  { id: "from-here-to-eternity", title: "From Here to Eternity", emojis: "🏖💋", level: "impossible" },
  { id: "it-happened-one-night", title: "It Happened One Night", emojis: "🚌🌙", level: "impossible" },
  { id: "hamlet", title: "Hamlet", emojis: "💀👑", level: "impossible" },
  { id: "grand-hotel", title: "Grand Hotel", emojis: "🏨🔑", level: "impossible" },
];
