// «Guess the Mushroom 2» — GuessSync · MUSHROOMS2 · did-you-know facts, ≤70 chars, verified true.
export const MUSHROOMS2_FACTS = {
  // EASY
  "lobstermushroom": "Edible: a parasite fungus that turns other mushrooms bright orange",
  "splitgill": "Edible in parts of Asia; its gills split open when air is dry",
  "commoninkcap": "Edible, but never with alcohol — it causes a nasty reaction",
  "fairyinkcap": "Edible, tiny caps grow in dense clusters on buried wood",
  "dogstinkhorn": "Not toxic but foul-smelling; flies spread its spores",
  "winterchanterelle": "Edible, fruits into early winter after frost hits the woods",
  "blackmorel": "Edible when cooked; grows in spring after forest fires",
  "nameko": "Edible, prized in Japan for its slippery, gelatinous cap",
  "elmoyster": "Edible, grows in large shelf-like clusters on dying elms",
  "falsedeathcap": "Toxic, smells of raw potato and closely resembles Death Cap",
  "whitetruffle": "Edible, among the most expensive foods hunted with trained dogs",
  "birchpolypore": "Medicinal; found carried by Ötzi the 5,300-year-old iceman",
  "meadowpuffball": "Edible when young and white inside, before it turns brown",
  "yellowstainer": "Toxic, flesh turns bright yellow when bruised or cut",
  "falsechanterelle": "Mildly toxic; a famous lookalike often confused for real chanterelles",
  "bitterbolete": "Not toxic but intensely bitter, ruining any dish it's cooked in",
  "foolsmushroom": "Deadly poisonous, an all-white relative of the Death Cap",
  "deadlywebcap": "Deadly poisonous; symptoms can take days or weeks to appear",
  "deadlydapperling": "Deadly poisonous despite its small, harmless-looking cap",
  "lividpinkgill": "Deadly poisonous, Europe's most dangerous non-Amanita mushroom",
  "commonearthball": "Toxic; often mistaken for a puffball but has thick, tough skin",
  "magpieinkcap": "Edible for some, striking with bold black-and-white speckles",
  "friedchickenmushroom": "Edible, grows in dense clumps and smells faintly of fresh bread",
  "almondmushroom": "Edible, prized for its strong almond-like sweet aroma",
  "stumppuffball": "Edible when young, grows in tight clusters on rotting stumps",
  // MEDIUM
  "woollymilkcap": "Toxic raw, causes severe stomach upset unless cooked well",
  "pepperymilkcap": "Edible after cooking, its raw milk has a fiery peppery taste",
  "milkwhitebrittlegill": "Edible, a chalky-white cap that stains yellow when bruised",
  "themiller": "Edible with caution, smells strongly of fresh ground flour",
  "yellowcrackedbolete": "Edible, its cracked yellow-brown cap oozes faint blue when cut",
  "chestnutbolete": "Edible, named for its smooth chestnut-brown cap and hollow stem",
  "troopingfunnel": "Edible, forms large fairy rings in grassy woodland clearings",
  "sheathedwoodtuft": "Edible, grows in dense tufts on stumps with a ringed stem",
  "poplarfieldcap": "Edible, cultivated commercially and grows on poplar wood",
  "snowywaxcap": "Edible but bland, pure white and waxy on grassland turf",
  "goldenwaxcap": "Edible, bright golden-yellow with a slimy, waxy cap",
  "weepingwidow": "Edible when young; its gills 'weep' dark liquid droplets",
  "aniseedfunnel": "Edible, smells strongly of aniseed and often tinted blue-green",
  "yellowfieldcap": "Edible, a fragile bright-yellow cap that fades within a day",
  "ivoryfunnel": "Toxic, an all-white funnel that has caused fatal poisonings",
  "termitemushroom": "Edible, grown by termites and can reach record-breaking sizes",
  "artistsconk": "Inedible; artists etch pictures onto its pale, canvas-like underside",
  "oldmanofthewoods": "Edible, its shaggy grey-black scales resemble an old man's beard",
  "rootingshank": "Edible, has a long taproot-like base buried deep underground",
  "commonbonnet": "Not edible, a common tiny bell-shaped mushroom on rotting wood",
  "dungroundhead": "Not edible, grows specifically on the dung of grazing animals",
  "blackeningwaxcap": "Not toxic, its bright red-orange cap slowly blackens with age",
  "orangejellyspot": "Not edible, a bright orange jelly blob common on conifer wood",
  "chickenfatsuillus": "Edible, has a greasy yellow cap and grows under white pine",
  "deershield": "Edible, common on decaying wood with a soft grey-brown cap",
  // HARD
  "combtoothfungus": "Edible, forms cascading white spines like icicles on dead wood",
  "blackbulgar": "Edible for some, a rubbery black jelly disc on fallen oak bark",
  "devilsurn": "Not edible, a tough black goblet-shaped cup on buried sticks",
  "jellybabyfungus": "Not edible, small olive-green stalked blobs on mossy ground",
  "bleedingfairyhelmet": "Not edible, oozes a dark red latex when its stem is broken",
  "powderypiggyback": "Not edible, a parasite that grows only on other mushrooms",
  "deadlyconecap": "Deadly poisonous, a tiny brown cap that has killed unwary foragers",
  "ergotfungus": "Highly toxic, this grain parasite once caused mass poisonings",
  "elfinsaddle": "Toxic raw, its dark saddle-shaped cap must be cooked thoroughly",
  "whitesaddle": "Edible after cooking, has a pale, brain-like folded cap",
  "deadlyparasol": "Toxic, North America's most common cause of mushroom poisoning",
  "angelwings": "Toxic to some, delicate white shelf fungus on conifer logs",
  "sulphurknight": "Inedible, smells strongly of gas due to its sulphur compounds",
  "earthtongue": "Not edible, a thin black tongue-shaped fungus in mossy grass",
  "beechwoodsickener": "Toxic, a bright red cap that causes severe vomiting if eaten",
  "blackfootpolypore": "Not edible, a tough bracket with a dark, velvety black base",
  "luridbolete": "Toxic raw, its pores turn deep blue instantly when bruised",
  "satansbolete": "Toxic, a red-pored bolete whose flesh turns blue when cut",
  "tigerknight": "Toxic, a scaly grey cap that causes severe gastric illness",
  "bleedingmilkcap": "Edible, oozes wine-red latex that stains everything it touches",
  "redbeltedpolypore": "Inedible, a hard bracket ringed with a distinct red band",
  "hairycurtaincrust": "Inedible, an orange bracket covered in fine velvety hairs",
  "lilacbonnet": "Toxic, a small purple-lilac cap common on forest litter",
  "shaggybracket": "Not edible, a shaggy orange-brown bracket on old fruit trees",
  "abortedentoloma": "Edible and prized, formed when one fungus parasitizes another",
  // IMPOSSIBLE
  "poisonfirecoral": "Deadly poisonous, one of the most toxic fungi known, found in Asia",
  "basketstinkhorn": "Not edible, its lattice ball smells of rotting meat to lure flies",
  "squidstinkhorn": "Not edible, splits into tentacle-like red-orange squid arms",
  "deadmansfoot": "Inedible, a rock-hard brown ball once used as a natural dye",
  "earpickfungus": "Not edible, a tiny toothed cap growing only on fallen pinecones",
  "cedarapplerust": "Not a mushroom cap; forms bizarre orange gelatinous horns on cedar",
  "cornsmut": "Edible and prized in Mexican cuisine as a corn delicacy",
  "falsetruffle": "Inedible for humans, an underground fungus favored by wild deer",
  "hairyrubbercup": "Not edible, a rubbery reddish-brown cup covered in stiff hairs",
  "mazegillfungus": "Inedible, its pore surface forms a maze-like labyrinth pattern",
  "zombieantfungus": "Infects ants and controls their bodies before sprouting from the head",
  "barometerearthstar": "Not edible, its star arms open in damp air and curl shut when dry",
  "toothedjellyfungus": "Edible but bland, a translucent jelly fungus covered in soft teeth",
  "dryrotfungus": "Not edible, a destructive fungus that can collapse wooden buildings",
  "bicolorbolete": "Edible, a striking bolete with a red cap and bright yellow pores",
  "silkyrosegill": "Edible when young, has a silky grey cap and pink spore print",
  "willowbracket": "Inedible, a hoof-shaped bracket that can live for decades",
  "hareearfungus": "Not edible, a curled brown cup fungus shaped like a hare's ear",
  "rufousmilkcap": "Oozes white latex with an intensely hot, acrid taste",
  "lilacoysterling": "Edible when cooked, an oyster-shaped cap tinted violet-lilac",
  "lumpybracket": "Inedible, a tough white bracket related to turkey tail fungus",
  "rubystinkhorn": "Not edible, a slender ruby-red stinkhorn found in warm climates",
  "purpleporebracket": "Inedible, a thin bracket fungus with a striking violet pore edge",
  "cloudearfungus": "Edible, widely used dried in Asian soups and stir-fries",
  "greenpepe": "Not edible, glows a faint green in the dark through bioluminescence",
};
