// «Guess the Mushroom 2» — GuessSync · MUSHROOMS2 · 100 fungi (25/tier) · real photos from Wikimedia Commons.
// Distinct set from E50 (mushroomsData.js) — unique slug AND name vs both. Mix of edible, poisonous, and bizarre species.
// Tiered by relative recognizability within this pool: easy (well-known names) → impossible (obscure/bizarre real species).
export const MUSHROOMS2 = [
  // ===== EASY (25) =====
  { slug: "lobstermushroom", name: "Lobster Mushroom", level: "easy" },
  { slug: "splitgill", name: "Split Gill", level: "easy" },
  { slug: "commoninkcap", name: "Common Ink Cap", level: "easy" },
  { slug: "fairyinkcap", name: "Fairy Inkcap", level: "easy" },
  { slug: "dogstinkhorn", name: "Dog Stinkhorn", level: "easy" },
  { slug: "winterchanterelle", name: "Winter Chanterelle", level: "easy" },
  { slug: "blackmorel", name: "Black Morel", level: "easy" },
  { slug: "nameko", name: "Nameko", level: "easy" },
  { slug: "elmoyster", name: "Elm Oyster", level: "easy" },
  { slug: "falsedeathcap", name: "False Death Cap", level: "easy" },
  { slug: "whitetruffle", name: "White Truffle", level: "easy" },
  { slug: "birchpolypore", name: "Birch Polypore", level: "easy" },
  { slug: "meadowpuffball", name: "Meadow Puffball", level: "easy" },
  { slug: "yellowstainer", name: "Yellow Stainer", level: "easy" },
  { slug: "falsechanterelle", name: "False Chanterelle", level: "easy" },
  { slug: "bitterbolete", name: "Bitter Bolete", level: "easy" },
  { slug: "foolsmushroom", name: "Fool's Mushroom", level: "easy" },
  { slug: "deadlywebcap", name: "Deadly Webcap", level: "easy" },
  { slug: "deadlydapperling", name: "Deadly Dapperling", level: "easy" },
  { slug: "lividpinkgill", name: "Livid Pinkgill", level: "easy" },
  { slug: "commonearthball", name: "Common Earthball", level: "easy" },
  { slug: "magpieinkcap", name: "Magpie Inkcap", level: "easy" },
  { slug: "friedchickenmushroom", name: "Fried Chicken", level: "easy" },
  { slug: "almondmushroom", name: "Almond Mushroom", level: "easy" },
  { slug: "stumppuffball", name: "Stump Puffball", level: "easy" },
  // ===== MEDIUM (25) =====
  { slug: "woollymilkcap", name: "Woolly Milkcap", level: "medium" },
  { slug: "pepperymilkcap", name: "Peppery Milkcap", level: "medium" },
  { slug: "milkwhitebrittlegill", name: "Milk-white Brittlegill", level: "medium" },
  { slug: "themiller", name: "The Miller", level: "medium" },
  { slug: "yellowcrackedbolete", name: "Yellow-cracked Bolete", level: "medium" },
  { slug: "chestnutbolete", name: "Chestnut Bolete", level: "medium" },
  { slug: "troopingfunnel", name: "Trooping Funnel", level: "medium" },
  { slug: "sheathedwoodtuft", name: "Sheathed Woodtuft", level: "medium" },
  { slug: "poplarfieldcap", name: "Poplar Fieldcap", level: "medium" },
  { slug: "snowywaxcap", name: "Snowy Waxcap", level: "medium" },
  { slug: "goldenwaxcap", name: "Golden Waxcap", level: "medium" },
  { slug: "weepingwidow", name: "Weeping Widow", level: "medium" },
  { slug: "aniseedfunnel", name: "Aniseed Funnel", level: "medium" },
  { slug: "yellowfieldcap", name: "Yellow Fieldcap", level: "medium" },
  { slug: "ivoryfunnel", name: "Ivory Funnel", level: "medium" },
  { slug: "termitemushroom", name: "Termite Mushroom", level: "medium" },
  { slug: "artistsconk", name: "Artist's Conk", level: "medium" },
  { slug: "oldmanofthewoods", name: "Old Man of the Woods", level: "medium" },
  { slug: "rootingshank", name: "Rooting Shank", level: "medium" },
  { slug: "commonbonnet", name: "Common Bonnet", level: "medium" },
  { slug: "dungroundhead", name: "Dung Roundhead", level: "medium" },
  { slug: "blackeningwaxcap", name: "Blackening Waxcap", level: "medium" },
  { slug: "orangejellyspot", name: "Orange Jelly Spot", level: "medium" },
  { slug: "chickenfatsuillus", name: "Chicken Fat Suillus", level: "medium" },
  { slug: "deershield", name: "Deer Shield", level: "medium" },
  // ===== HARD (25) =====
  { slug: "combtoothfungus", name: "Comb Tooth", level: "hard" },
  { slug: "blackbulgar", name: "Black Bulgar", level: "hard" },
  { slug: "devilsurn", name: "Devil's Urn", level: "hard" },
  { slug: "jellybabyfungus", name: "Jelly Baby", level: "hard" },
  { slug: "bleedingfairyhelmet", name: "Bleeding Fairy Helmet", level: "hard" },
  { slug: "powderypiggyback", name: "Powdery Piggyback", level: "hard" },
  { slug: "deadlyconecap", name: "Deadly Conecap", level: "hard" },
  { slug: "ergotfungus", name: "Ergot Fungus", level: "hard" },
  { slug: "elfinsaddle", name: "Elfin Saddle", level: "hard" },
  { slug: "whitesaddle", name: "White Saddle", level: "hard" },
  { slug: "deadlyparasol", name: "Deadly Parasol", level: "hard" },
  { slug: "angelwings", name: "Angel Wings", level: "hard" },
  { slug: "sulphurknight", name: "Sulphur Knight", level: "hard" },
  { slug: "earthtongue", name: "Earth Tongue", level: "hard" },
  { slug: "beechwoodsickener", name: "Beechwood Sickener", level: "hard" },
  { slug: "blackfootpolypore", name: "Blackfoot Polypore", level: "hard" },
  { slug: "luridbolete", name: "Lurid Bolete", level: "hard" },
  { slug: "satansbolete", name: "Satan's Bolete", level: "hard" },
  { slug: "tigerknight", name: "Tiger Knight", level: "hard" },
  { slug: "bleedingmilkcap", name: "Bleeding Milkcap", level: "hard" },
  { slug: "redbeltedpolypore", name: "Red-belted Polypore", level: "hard" },
  { slug: "hairycurtaincrust", name: "Hairy Curtain Crust", level: "hard" },
  { slug: "lilacbonnet", name: "Lilac Bonnet", level: "hard" },
  { slug: "shaggybracket", name: "Shaggy Bracket", level: "hard" },
  { slug: "abortedentoloma", name: "Aborted Entoloma", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { slug: "poisonfirecoral", name: "Poison Fire Coral", level: "impossible" },
  { slug: "basketstinkhorn", name: "Basket Stinkhorn", level: "impossible" },
  { slug: "squidstinkhorn", name: "Squid Stinkhorn", level: "impossible" },
  { slug: "deadmansfoot", name: "Dead Man's Foot", level: "impossible" },
  { slug: "earpickfungus", name: "Earpick Fungus", level: "impossible" },
  { slug: "cedarapplerust", name: "Cedar-apple Rust", level: "impossible" },
  { slug: "cornsmut", name: "Corn Smut", level: "impossible" },
  { slug: "falsetruffle", name: "False Truffle", level: "impossible" },
  { slug: "hairyrubbercup", name: "Hairy Rubber Cup", level: "impossible" },
  { slug: "mazegillfungus", name: "Mazegill Fungus", level: "impossible" },
  { slug: "zombieantfungus", name: "Zombie Ant Fungus", level: "impossible" },
  { slug: "barometerearthstar", name: "Barometer Earthstar", level: "impossible" },
  { slug: "toothedjellyfungus", name: "Toothed Jelly Fungus", level: "impossible" },
  { slug: "dryrotfungus", name: "Dry Rot Fungus", level: "impossible" },
  { slug: "bicolorbolete", name: "Bicolor Bolete", level: "impossible" },
  { slug: "silkyrosegill", name: "Silky Rosegill", level: "impossible" },
  { slug: "willowbracket", name: "Willow Bracket", level: "impossible" },
  { slug: "hareearfungus", name: "Hare's Ear Fungus", level: "impossible" },
  { slug: "rufousmilkcap", name: "Rufous Milkcap", level: "impossible" },
  { slug: "lilacoysterling", name: "Lilac Oysterling", level: "impossible" },
  { slug: "lumpybracket", name: "Lumpy Bracket", level: "impossible" },
  { slug: "rubystinkhorn", name: "Ruby Stinkhorn", level: "impossible" },
  { slug: "purpleporebracket", name: "Purplepore Bracket", level: "impossible" },
  { slug: "cloudearfungus", name: "Cloud Ear Fungus", level: "impossible" },
  { slug: "greenpepe", name: "Green Pepe", level: "impossible" },
];

export const MUSHROOMS2_LEVELS = ["easy", "medium", "hard", "impossible"];
