// «Guess the Mushroom» — GuessSync · E50 · 100 fungi (25/tier) · real photos from Wikimedia Commons.
// Tiered by real recognizability: easy (Button/Fly Agaric/Porcini) → impossible (Bleeding Tooth/Devil's Fingers/Veiled Lady).
export const MUSHROOMS = [
  // EASY (25) — household-name & iconic species
  { slug: "button", name: "Button Mushroom", level: "easy" },
  { slug: "portobello", name: "Portobello", level: "easy" },
  { slug: "shiitake", name: "Shiitake", level: "easy" },
  { slug: "flyagaric", name: "Fly Agaric", level: "easy" },
  { slug: "chanterelle", name: "Chanterelle", level: "easy" },
  { slug: "porcini", name: "Porcini", level: "easy" },
  { slug: "oyster", name: "Oyster Mushroom", level: "easy" },
  { slug: "morel", name: "Morel", level: "easy" },
  { slug: "blacktruffle", name: "Black Truffle", level: "easy" },
  { slug: "enoki", name: "Enoki", level: "easy" },
  { slug: "puffball", name: "Common Puffball", level: "easy" },
  { slug: "deathcap", name: "Death Cap", level: "easy" },
  { slug: "kingoyster", name: "King Oyster", level: "easy" },
  { slug: "maitake", name: "Hen of the Woods", level: "easy" },
  { slug: "woodear", name: "Wood Ear", level: "easy" },
  { slug: "giantpuffball", name: "Giant Puffball", level: "easy" },
  { slug: "shaggyinkcap", name: "Shaggy Ink Cap", level: "easy" },
  { slug: "destroyingangel", name: "Destroying Angel", level: "easy" },
  { slug: "honeyfungus", name: "Honey Fungus", level: "easy" },
  { slug: "turkeytail", name: "Turkey Tail", level: "easy" },
  { slug: "reishi", name: "Reishi", level: "easy" },
  { slug: "chickenofthewoods", name: "Chicken of the Woods", level: "easy" },
  { slug: "beefsteakfungus", name: "Beefsteak Fungus", level: "easy" },
  { slug: "jackolantern", name: "Jack-o'-lantern", level: "easy" },
  { slug: "strawmushroom", name: "Straw Mushroom", level: "easy" },
  // MEDIUM (25) — familiar to foragers & enthusiasts
  { slug: "saffronmilkcap", name: "Saffron Milk Cap", level: "medium" },
  { slug: "horsemushroom", name: "Horse Mushroom", level: "medium" },
  { slug: "fieldmushroom", name: "Field Mushroom", level: "medium" },
  { slug: "parasol", name: "Parasol Mushroom", level: "medium" },
  { slug: "blusher", name: "The Blusher", level: "medium" },
  { slug: "panthercap", name: "Panther Cap", level: "medium" },
  { slug: "falsemorel", name: "False Morel", level: "medium" },
  { slug: "sulphurtuft", name: "Sulphur Tuft", level: "medium" },
  { slug: "woodblewit", name: "Wood Blewit", level: "medium" },
  { slug: "deceiver", name: "The Deceiver", level: "medium" },
  { slug: "fairyring", name: "Fairy Ring Mushroom", level: "medium" },
  { slug: "cauliflowerfungus", name: "Cauliflower Fungus", level: "medium" },
  { slug: "hedgehog", name: "Hedgehog Mushroom", level: "medium" },
  { slug: "blacktrumpet", name: "Black Trumpet", level: "medium" },
  { slug: "winecap", name: "Wine Cap", level: "medium" },
  { slug: "shimeji", name: "Shimeji", level: "medium" },
  { slug: "slipperyjack", name: "Slippery Jack", level: "medium" },
  { slug: "birchbolete", name: "Birch Bolete", level: "medium" },
  { slug: "dryadssaddle", name: "Dryad's Saddle", level: "medium" },
  { slug: "chaga", name: "Chaga", level: "medium" },
  { slug: "cordyceps", name: "Cordyceps", level: "medium" },
  { slug: "amethystdeceiver", name: "Amethyst Deceiver", level: "medium" },
  { slug: "shaggyparasol", name: "Shaggy Parasol", level: "medium" },
  { slug: "matsutake", name: "Matsutake", level: "medium" },
  { slug: "brownrollrim", name: "Brown Roll-rim", level: "medium" },
  // HARD (25) — enthusiast / mycologist level
  { slug: "baybolete", name: "Bay Bolete", level: "hard" },
  { slug: "charcoalburner", name: "Charcoal Burner", level: "hard" },
  { slug: "sickener", name: "The Sickener", level: "hard" },
  { slug: "grisette", name: "Grisette", level: "hard" },
  { slug: "stinkhorn", name: "Common Stinkhorn", level: "hard" },
  { slug: "collaredearthstar", name: "Collared Earthstar", level: "hard" },
  { slug: "scarletelfcup", name: "Scarlet Elf Cup", level: "hard" },
  { slug: "orangepeelfungus", name: "Orange Peel Fungus", level: "hard" },
  { slug: "candlesnuff", name: "Candlesnuff Fungus", level: "hard" },
  { slug: "deadmansfingers", name: "Dead Man's Fingers", level: "hard" },
  { slug: "witchesbutter", name: "Witch's Butter", level: "hard" },
  { slug: "yellowstagshorn", name: "Yellow Stagshorn", level: "hard" },
  { slug: "kingalfredscakes", name: "King Alfred's Cakes", level: "hard" },
  { slug: "hooffungus", name: "Hoof Fungus", level: "hard" },
  { slug: "dyerspolypore", name: "Dyer's Polypore", level: "hard" },
  { slug: "wrinkledpeach", name: "Wrinkled Peach", level: "hard" },
  { slug: "porcelainfungus", name: "Porcelain Fungus", level: "hard" },
  { slug: "scarletwaxcap", name: "Scarlet Waxcap", level: "hard" },
  { slug: "parrotwaxcap", name: "Parrot Waxcap", level: "hard" },
  { slug: "bloodredwebcap", name: "Bloodred Webcap", level: "hard" },
  { slug: "funeralbell", name: "Funeral Bell", level: "hard" },
  { slug: "deadlyfibrecap", name: "Deadly Fibrecap", level: "hard" },
  { slug: "poisonpie", name: "Poison Pie", level: "hard" },
  { slug: "verdigrisagaric", name: "Verdigris Agaric", level: "hard" },
  { slug: "libertycap", name: "Liberty Cap", level: "hard" },
  // IMPOSSIBLE (25) — obscure & bizarre real species
  { slug: "bleedingtooth", name: "Bleeding Tooth Fungus", level: "impossible" },
  { slug: "lionsmane", name: "Lion's Mane", level: "impossible" },
  { slug: "birdsnest", name: "Bird's Nest Fungus", level: "impossible" },
  { slug: "devilsfingers", name: "Devil's Fingers", level: "impossible" },
  { slug: "indigomilkcap", name: "Indigo Milk Cap", level: "impossible" },
  { slug: "veiledlady", name: "Veiled Lady", level: "impossible" },
  { slug: "latticedstinkhorn", name: "Latticed Stinkhorn", level: "impossible" },
  { slug: "crowntippedcoral", name: "Crown-tipped Coral", level: "impossible" },
  { slug: "violetcoral", name: "Violet Coral", level: "impossible" },
  { slug: "skybluemushroom", name: "Sky Blue Mushroom", level: "impossible" },
  { slug: "devilscigar", name: "Devil's Cigar", level: "impossible" },
  { slug: "starfishfungus", name: "Starfish Fungus", level: "impossible" },
  { slug: "greenelfcup", name: "Green Elfcup", level: "impossible" },
  { slug: "bluetooth", name: "Blue Tooth Fungus", level: "impossible" },
  { slug: "pinkoyster", name: "Pink Oyster", level: "impossible" },
  { slug: "goldenoyster", name: "Golden Oyster", level: "impossible" },
  { slug: "ghostfungus", name: "Ghost Fungus", level: "impossible" },
  { slug: "bitteroyster", name: "Bitter Oyster", level: "impossible" },
  { slug: "eyelashcup", name: "Eyelash Cup", level: "impossible" },
  { slug: "purplejellydisc", name: "Purple Jellydisc", level: "impossible" },
  { slug: "snowfungus", name: "Snow Fungus", level: "impossible" },
  { slug: "caesarsmushroom", name: "Caesar's Mushroom", level: "impossible" },
  { slug: "bluechanterelle", name: "Blue Chanterelle", level: "impossible" },
  { slug: "apricotjelly", name: "Apricot Jelly", level: "impossible" },
  { slug: "goldenspindles", name: "Golden Spindles", level: "impossible" },
];
