// E185 «Guess the Mythical Creature by Emoji 2» — 100 creatures · 25/tier
// VO: sfx/e185-<id>.wav
export const MYTHCREATURE_EMOJI_2_FACTS = {
  // EASY
  "oni": "Horned Japanese demon-ogre that swings a spiked iron club.",
  "mummy": "Bandaged undead corpse risen from an ancient Egyptian tomb.",
  "krampus": "Horned Alpine devil who punishes bad children at Christmas.",
  "ghoul": "Desert grave-haunting demon that feeds on the dead.",
  "grim-reaper": "Cloaked skeletal figure who harvests departing souls.",
  "jiangshi": "Chinese hopping vampire drained of will by a paper talisman.",
  "hellhound": "Fire-eyed demonic black dog that guards the underworld.",
  "sea-serpent": "Giant serpent said to coil through the deep ocean.",
  "firebird": "Glowing Slavic bird whose feathers shine like living fire.",
  "sandman": "Folklore figure who sprinkles sand to bring sleep and dreams.",
  "yuki-onna": "Japanese snow-woman spirit who freezes lost travelers.",
  "boogeyman": "Shadowy monster said to lurk in closets and under beds.",
  "tooth-fairy": "Fairy who swaps children's lost teeth for coins at night.",
  "headless-horseman": "Sleepy Hollow ghost who rides hunting for his lost head.",
  "jersey-devil": "New Jersey's winged, hoofed cryptid of the Pine Barrens.",
  "kobold": "German goblin-like sprite that haunts mines and homes.",
  "brownie": "Scottish house-elf that tidies homes for a bowl of milk.",
  "boggart": "English household spirit that turns mischievous when angered.",
  "grindylow": "English water demon that drags children beneath the ponds.",
  "puca": "Irish shapeshifting spirit, often a wild dark horse.",
  "barghest": "Monstrous black dog of English legend, an omen of death.",
  "nisse": "Nordic farm gnome who guards the household and its barn.",
  "sylph": "Graceful elemental spirit of the air and open sky.",
  "gorgon": "Snake-haired sister whose gaze turns onlookers to stone.",
  "la-llorona": "Latin American ghost weeping for her drowned children.",
  // MEDIUM
  "draugr": "Norse undead warrior guarding treasure in its grave-mound.",
  "huldra": "Scandinavian forest woman betrayed by her hidden cow's tail.",
  "nixie": "Germanic water sprite whose song lures people to drown.",
  "undine": "Water elemental who gains a soul by wedding a human.",
  "tarasque": "French dragon-beast with a spiked turtle shell and lion head.",
  "melusine": "French noblewoman cursed to grow a serpent's tail in secret.",
  "wolpertinger": "Bavarian critter mixing a rabbit with antlers, wings and fangs.",
  "taniwha": "Maori guardian monster dwelling in rivers, caves and seas.",
  "bakunawa": "Philippine sea serpent that swallows the moon in eclipses.",
  "grootslang": "South African beast half-elephant, half-serpent, hoarding gems.",
  "impundulu": "African lightning bird, a witch's blood-drinking familiar.",
  "ninki-nanka": "West African swamp-dwelling dragon feared across the Gambia.",
  "tokoloshe": "Small mischievous Zulu water-goblin that torments sleepers.",
  "curupira": "Brazilian forest guardian with backward feet to fool hunters.",
  "boitata": "Brazilian fire-serpent with blazing eyes guarding the woods.",
  "cadejo": "Central American spirit dog that shadows night travelers.",
  "peuchen": "Chilean flying serpent that shapeshifts and drinks blood.",
  "wampus-cat": "Appalachian cat spirit said to stalk the misty mountains.",
  "snallygaster": "Maryland dragon-bird cryptid with tentacles and a metal beak.",
  "nagual": "Mesoamerican shaman who shapeshifts into a jaguar or beast.",
  "pontianak": "Malay vampiric ghost of a woman who died in childbirth.",
  "kapre": "Philippine tree giant seen smoking a huge cigar at night.",
  "aswang": "Philippine shapeshifting monster that preys on the sleeping.",
  "lindworm": "European wingless dragon that slithers like a giant serpent.",
  "questing-beast": "Arthurian hybrid whose belly bays like a pack of hounds.",
  // HARD
  "typhon": "Greek serpent-legged storm giant, the deadliest of monsters.",
  "echidna": "Greek half-woman, half-snake who mothered many monsters.",
  "ladon": "Greek hundred-headed dragon guarding the golden apples.",
  "scylla": "Greek sea monster ringed with snarling dog-heads at her waist.",
  "charybdis": "Greek sea monster that swallows the tide into a whirlpool.",
  "nemean-lion": "Greek lion with golden hide no weapon could ever pierce.",
  "orthrus": "Greek two-headed dog with a serpent tail, Cerberus's brother.",
  "stymphalian-birds": "Greek man-eating birds with bronze beaks and metal feathers.",
  "talos": "Greek giant bronze automaton that guarded the isle of Crete.",
  "cetus": "Greek sea monster sent to devour the princess Andromeda.",
  "hippocampus": "Greek sea-horse with a horse's front and a fish's tail.",
  "fafnir": "Norse dwarf transformed into a dragon guarding cursed gold.",
  "nuckelavee": "Skinless Orcadian sea-demon whose breath blights the crops.",
  "wulver": "Shetland wolf-headed man who leaves fish for the poor.",
  "spriggan": "Cornish grotesque fairy that guards buried treasure and ruins.",
  "nekomata": "Japanese two-tailed cat yokai that raises and controls the dead.",
  "gashadokuro": "Giant Japanese skeleton formed from the bones of the starved.",
  "rokurokubi": "Japanese yokai woman whose neck stretches to great lengths.",
  "umibozu": "Giant shadowy sea-spirit that capsizes ships on calm nights.",
  "raiju": "Japanese thunder-beast that leaps through storms as lightning.",
  "pixiu": "Chinese winged lion that hoards gold and wards off evil.",
  "baize": "Chinese wise beast that knows every creature and demon.",
  "taotie": "Chinese gluttonous monster-face that devours all in its path.",
  "zmey": "Slavic multi-headed fire-breathing dragon of the mountains.",
  "vodyanoy": "Slavic frog-faced water-spirit that drowns careless swimmers.",
  // IMPOSSIBLE
  "mokele-mbembe": "Congo River cryptid said to resemble a living sauropod.",
  "popobawa": "Zanzibari one-eyed bat-demon that attacks victims at night.",
  "asanbosam": "West African vampire with iron teeth that hangs from trees.",
  "adze": "West African vampire that takes the form of a firefly.",
  "inkanyamba": "Southern African giant serpent that stirs storms and floods.",
  "sirin": "Slavic bird-woman whose song brings listeners joy then doom.",
  "gamayun": "Slavic prophetic bird that speaks of things yet to come.",
  "domovoi": "Slavic bearded house-spirit that protects the family home.",
  "kikimora": "Slavic house-spirit that spins thread and rattles at night.",
  "alp": "German elf-demon that sits on sleepers to bring nightmares.",
  "tatzelwurm": "Alpine cryptid, a serpent with a cat's head and clawed limbs.",
  "basajaun": "Basque hairy forest giant, protector of flocks and builders.",
  "erlking": "Germanic forest king whose touch means death to children.",
  "zhulong": "Chinese giant torch-dragon whose eyes make day and night.",
  "xiezhi": "Chinese one-horned goat-beast that gores the guilty in court.",
  "karkadann": "Persian ferocious one-horned beast of the open grasslands.",
  "shahmaran": "Anatolian wise queen of serpents, half-woman and half-snake.",
  "azi-dahaka": "Persian three-headed serpent-dragon of storm and deceit.",
  "huma": "Persian bird of fortune that never lands upon the ground.",
  "anqa": "Enormous Arabian bird of legend that vanished from the world.",
  "marid": "Mightiest class of Arabian jinn, tied to water and pride.",
  "bahamut": "Colossal Arabian fish that carries the world on its back.",
  "nasnas": "Arabian creature with half a body who hops on one leg.",
  "sigbin": "Philippine goat-like creature that walks backward for blood.",
  "penanggalan": "Malay detached head that flies trailing its own entrails.",
};
