// E208 mythical-creature facts — one true <=70-char fact per id, shown on reveal.
export const MYTHCREATURE_EMOJI_3_FACTS = {
  // EASY
  "giant": "Huge humanlike beings appear in folklore across nearly every culture.",
  "angel": "A winged messenger of God in Abrahamic religious tradition.",
  "demon": "An evil supernatural being said to tempt or torment humans.",
  "cupid": "The Roman god of desire, shown as a winged archer of love.",
  "merman": "The male counterpart to a mermaid, half man and half fish.",
  "faun": "A Roman woodland spirit with goat legs, half man and half goat.",
  "djinn": "A supernatural being of smokeless fire in Arabian folklore.",
  "nymph": "A minor nature goddess tied to trees, rivers, or mountains.",
  "dryad": "A Greek tree spirit believed to live and die with her tree.",
  "muse": "One of nine Greek goddesses who inspire art and knowledge.",
  "titan": "A primordial giant deity from Greek myth, elder to the gods.",
  "frost-giant": "A Norse giant of ice and cold, foe of the Aesir gods.",
  "fire-giant": "A Norse giant of flame ruled by Surtr, foretold to burn the world.",
  "naiad": "A Greek water nymph who presides over springs and streams.",
  "amazon-warrior": "A legendary all-female warrior of Greek myth.",
  "colossus": "A giant animated statue, echoing the Colossus of Rhodes myth.",
  "skeleton-warrior": "An animated bone warrior found across folklore and legend.",
  "sea-monster": "A giant beast said to lurk in deep, uncharted waters.",
  "sorceress": "A woman wielding powerful magic in folklore and fairy tales.",
  "wizard": "A folklore figure who commands magic through spells and study.",
  "shapeshifter": "A being able to change its physical form at will.",
  "frankensteins-monster": "A creature stitched from corpses and reanimated by science.",
  "grendel": "A monster from the swamp in the Old English epic Beowulf.",
  "nereid": "A Greek sea nymph, daughter of the sea god Nereus.",
  "spectre": "A ghostly apparition said to haunt the living.",

  // MEDIUM
  "lamia": "A Greek child-devouring monster, once a queen cursed by Hera.",
  "empusa": "A shape-shifting Greek demon with one bronze leg, aide to Hecate.",
  "cecaelia": "A folkloric hybrid with an octopus's tentacles and a woman's torso.",
  "rakshasa": "A shape-shifting demon from Hindu mythology, foe of gods and men.",
  "yaksha": "A nature spirit in Hindu and Buddhist lore who guards treasure.",
  "apsara": "A celestial dancer of Hindu and Buddhist mythology.",
  "kinnara": "A half-human, half-bird musician spirit of South Asian myth.",
  "vetala": "A ghost-like being in Hindu myth that reanimates corpses.",
  "preta": "A 'hungry ghost' in Buddhist lore, tormented by endless craving.",
  "makara": "A sea-creature hybrid of crocodile and fish, mount of the Ganges.",
  "asura": "A powerful being in Hindu myth locked in eternal war with the devas.",
  "feng-huang": "The Chinese phoenix, a symbol of virtue and harmony.",
  "huli-jing": "A Chinese fox spirit that can shapeshift into a beautiful woman.",
  "nurarihyon": "A Japanese yokai leader who strolls into homes uninvited.",
  "tsuchinoko": "A stout, snake-like Japanese cryptid said to drink alcohol.",
  "kamaitachi": "A Japanese weasel yokai that slashes with blades of wind.",
  "amabie": "A Japanese mermaid-like yokai that predicts plagues and good harvest.",
  "merrow": "Irish merfolk; the males famously wear red cocked hats.",
  "redcap": "A murderous Scottish border goblin who dyes his cap in blood.",
  "sluagh": "A host of restless, unforgiven dead in Irish and Scottish folklore.",
  "cu-sith": "A giant green fairy dog of Scottish and Irish legend.",
  "glaistig": "A Scottish spirit, half woman and half goat, that lures travelers.",
  "fear-gorta": "An Irish 'man of hunger' spirit born from famine, begging for food.",
  "bean-nighe": "A Scottish washerwoman spirit who washes the clothes of the doomed.",
  "vila": "A Slavic nature fairy of forests, winds, and clouds.",

  // HARD
  "nurikabe": "A Japanese yokai that becomes an invisible wall blocking travelers.",
  "yamauba": "A mountain-dwelling crone of Japanese folklore who preys on travelers.",
  "nue": "A Japanese chimera with a monkey head, tiger limbs, and snake tail.",
  "futakuchi-onna": "A Japanese yokai woman with a second mouth on the back of her head.",
  "ittan-momen": "A Japanese yokai that appears as a living roll of cotton cloth.",
  "shan-xiao": "A one-legged mountain spirit of Chinese folklore linked to fire.",
  "jiuweihu": "The nine-tailed fox of Chinese legend, an omen tied to royalty.",
  "nuno-sa-punso": "A dwarf-like Filipino spirit said to live inside anthills.",
  "duwende": "A small goblin-like spirit of Filipino folklore living near mounds.",
  "wakwak": "A vampiric bird-like creature of Filipino legend named for its cry.",
  "santelmo": "A Filipino will-o'-the-wisp fireball spirit seen over swamps.",
  "berbalang": "A Filipino ghoul that leaves its body at night to feed on corpses.",
  "aigamuxa": "A man-eating African folk creature said to have eyes on its feet.",
  "eloko": "A bell-carrying dwarf spirit of Congolese forest folklore.",
  "obayifo": "A West African witch-being said to drain the life from victims.",
  "mishipeshu": "An underwater panther spirit of Ojibwe legend guarding lakes.",
  "piasa": "A winged, antlered monster painted on an Illinois river bluff.",
  "iara": "A Brazilian water spirit who lures fishermen with her song.",
  "alicanto": "A Chilean bird said to eat metal and glow while guarding treasure.",
  "al-miraj": "A horned rabbit of Arabian folklore said to hunt larger prey.",
  "buraq": "A swift winged steed of Islamic tradition, faster than any horse.",
  "silat": "A shape-shifting female jinn of Arabian folklore tied to the night.",
  "qareen": "A jinn companion said in Islamic folklore to be born with each person.",
  "hinn": "A type of jinn in Arabian lore said to roam the desert as animals.",
  "poludnitsa": "A Slavic noon-day spirit who haunts wheat fields at midday.",

  // IMPOSSIBLE
  "likho": "A Slavic personification of evil fate, often shown as one-eyed.",
  "chernobog": "A Slavic 'black god' associated with darkness and misfortune.",
  "rarog": "A Slavic fire spirit that takes the form of a fiery falcon.",
  "xolotl": "An Aztec dog-headed god of lightning, death, and the underworld.",
  "cipactli": "A primordial earth-crocodile monster of Aztec creation myth.",
  "tzitzimitl": "An Aztec skeletal star-demon linked to solar eclipses.",
  "camazotz": "A Mayan bat god of night, death, and sacrifice.",
  "yara-ma-yha-who": "An Aboriginal Australian vampiric tree-dweller that drains blood.",
  "drop-bear": "A folkloric predatory koala-like creature of Australian tall tales.",
  "muldjewangk": "A river monster of Aboriginal Australian legend near the Murray River.",
  "wagyl": "A Rainbow Serpent creator-being of Noongar Aboriginal tradition.",
  "argus-panoptes": "A hundred-eyed giant of Greek myth, set to guard by Hera.",
  "stheno": "An immortal Gorgon sister of Medusa in Greek mythology.",
  "euryale": "A Gorgon sister of Medusa known for her piercing wail.",
  "telchines": "Malevolent sea-demon metalworkers of Greek myth from Rhodes.",
  "blemmyes": "Legendary headless men said to have faces on their chests.",
  "sciapod": "A one-legged bestiary being that shades itself with its own foot.",
  "nidhogg": "A Norse dragon that gnaws the roots of the world tree Yggdrasil.",
  "garm": "A blood-stained hound of Norse myth that guards Hel's gate.",
  "skoll": "A Norse wolf fated to chase and one day devour the sun.",
  "hati": "A Norse wolf fated to chase and one day devour the moon.",
  "aos-si": "The mound-dwelling fairy folk of Irish mythology.",
  "fomorian": "A race of monstrous sea raiders in Irish mythology.",
  "church-grim": "A black dog spirit of English folklore that guards churchyards.",
  "barbegazi": "A snow-dwelling gnome of Alpine folklore with huge frosty feet.",
};
