// E144 «Guess the Mythical Creature by Emoji» — 100 legendary creatures from world folklore
// 25/tier · clue = plain single-codepoint Unicode emoji (mirrors E125 movieEmoji2 isEmoji rendering)
// VO: sfx/e144-<id>.wav — phrase "It's <Creature>!" (edge-tts GuyNeural --rate=-8%)
// Every emoji fairly points to the creature's iconic form; no bare color-blob filler; each set unique.
export const MYTHCREATURE_EMOJI = [
  // ===== EASY (25) — household-name creatures =====
  { id: "dragon", title: "Dragon", emojis: "🐉🔥", level: "easy" },
  { id: "unicorn", title: "Unicorn", emojis: "🦄🌈", level: "easy" },
  { id: "mermaid", title: "Mermaid", emojis: "🧜🌊", level: "easy" },
  { id: "phoenix", title: "Phoenix", emojis: "🔥🐦", level: "easy" },
  { id: "vampire", title: "Vampire", emojis: "🧛🦇", level: "easy" },
  { id: "werewolf", title: "Werewolf", emojis: "🐺🌕", level: "easy" },
  { id: "fairy", title: "Fairy", emojis: "🧚✨", level: "easy" },
  { id: "genie", title: "Genie", emojis: "🧞🪔", level: "easy" },
  { id: "zombie", title: "Zombie", emojis: "🧟🧠", level: "easy" },
  { id: "ghost", title: "Ghost", emojis: "👻🕯", level: "easy" },
  { id: "witch", title: "Witch", emojis: "🧙🧹", level: "easy" },
  { id: "troll", title: "Troll", emojis: "🧌🌉", level: "easy" },
  { id: "centaur", title: "Centaur", emojis: "🏹🐴", level: "easy" },
  { id: "minotaur", title: "Minotaur", emojis: "🐂🌀", level: "easy" },
  { id: "cyclops", title: "Cyclops", emojis: "👁👹", level: "easy" },
  { id: "pegasus", title: "Pegasus", emojis: "🐴🪽", level: "easy" },
  { id: "griffin", title: "Griffin", emojis: "🦅🦁", level: "easy" },
  { id: "yeti", title: "Yeti", emojis: "🏔👣", level: "easy" },
  { id: "kraken", title: "Kraken", emojis: "🐙🚢", level: "easy" },
  { id: "cerberus", title: "Cerberus", emojis: "🐕🔥", level: "easy" },
  { id: "leprechaun", title: "Leprechaun", emojis: "🍀🎩", level: "easy" },
  { id: "elf", title: "Elf", emojis: "🧝🏹", level: "easy" },
  { id: "goblin", title: "Goblin", emojis: "👺🗡", level: "easy" },
  { id: "loch-ness-monster", title: "Loch Ness Monster", emojis: "🌊🦕", level: "easy" },
  { id: "bigfoot", title: "Bigfoot", emojis: "🦶🌲", level: "easy" },

  // ===== MEDIUM (25) — well-known myth, needs a beat =====
  { id: "sphinx", title: "Sphinx", emojis: "🦁🏜", level: "medium" },
  { id: "hydra", title: "Hydra", emojis: "🐍🐍🐍", level: "medium" },
  { id: "chimera", title: "Chimera", emojis: "🦁🐐🐍", level: "medium" },
  { id: "medusa", title: "Medusa", emojis: "🐍👩", level: "medium" },
  { id: "harpy", title: "Harpy", emojis: "🦅👩", level: "medium" },
  { id: "satyr", title: "Satyr", emojis: "🐐🪈", level: "medium" },
  { id: "siren", title: "Siren", emojis: "🧜🎶", level: "medium" },
  { id: "basilisk", title: "Basilisk", emojis: "🐍👑", level: "medium" },
  { id: "golem", title: "Golem", emojis: "🗿🧱", level: "medium" },
  { id: "valkyrie", title: "Valkyrie", emojis: "🛡🪽", level: "medium" },
  { id: "kitsune", title: "Kitsune", emojis: "🦊🔥", level: "medium" },
  { id: "dwarf", title: "Dwarf", emojis: "⛏🧔", level: "medium" },
  { id: "gnome", title: "Gnome", emojis: "🍄🧙", level: "medium" },
  { id: "ogre", title: "Ogre", emojis: "👹🪓", level: "medium" },
  { id: "gargoyle", title: "Gargoyle", emojis: "🗿⛪", level: "medium" },
  { id: "banshee", title: "Banshee", emojis: "👻😱", level: "medium" },
  { id: "kelpie", title: "Kelpie", emojis: "🐴🌊", level: "medium" },
  { id: "selkie", title: "Selkie", emojis: "🦭🌊", level: "medium" },
  { id: "wendigo", title: "Wendigo", emojis: "🦌❄", level: "medium" },
  { id: "thunderbird", title: "Thunderbird", emojis: "⚡🦅", level: "medium" },
  { id: "naga", title: "Naga", emojis: "🐍🛕", level: "medium" },
  { id: "garuda", title: "Garuda", emojis: "🦅🔱", level: "medium" },
  { id: "kappa", title: "Kappa", emojis: "🐢🥒", level: "medium" },
  { id: "manticore", title: "Manticore", emojis: "🦁🦂", level: "medium" },
  { id: "wyvern", title: "Wyvern", emojis: "🐉🪽", level: "medium" },

  // ===== HARD (25) — named legends, deeper folklore =====
  { id: "fenrir", title: "Fenrir", emojis: "🐺⛓", level: "hard" },
  { id: "jormungandr", title: "Jormungandr", emojis: "🐍🌍", level: "hard" },
  { id: "sleipnir", title: "Sleipnir", emojis: "🐴🦵", level: "hard" },
  { id: "roc", title: "Roc", emojis: "🦅🥚", level: "hard" },
  { id: "cockatrice", title: "Cockatrice", emojis: "🐔🐍", level: "hard" },
  { id: "wraith", title: "Wraith", emojis: "👻🌫", level: "hard" },
  { id: "dullahan", title: "Dullahan", emojis: "💀🐎", level: "hard" },
  { id: "baba-yaga", title: "Baba Yaga", emojis: "🏚🐔", level: "hard" },
  { id: "chupacabra", title: "Chupacabra", emojis: "🐐🩸", level: "hard" },
  { id: "mothman", title: "Mothman", emojis: "🪽👁", level: "hard" },
  { id: "jackalope", title: "Jackalope", emojis: "🐰🦌", level: "hard" },
  { id: "salamander", title: "Salamander", emojis: "🦎🔥", level: "hard" },
  { id: "behemoth", title: "Behemoth", emojis: "🦬🌍", level: "hard" },
  { id: "leviathan", title: "Leviathan", emojis: "🐋🌊", level: "hard" },
  { id: "hippogriff", title: "Hippogriff", emojis: "🦅🐴", level: "hard" },
  { id: "pixie", title: "Pixie", emojis: "🧚🍄", level: "hard" },
  { id: "imp", title: "Imp", emojis: "😈🔥", level: "hard" },
  { id: "ifrit", title: "Ifrit", emojis: "🔥👹", level: "hard" },
  { id: "poltergeist", title: "Poltergeist", emojis: "👻🪑", level: "hard" },
  { id: "changeling", title: "Changeling", emojis: "👶🧚", level: "hard" },
  { id: "will-o-the-wisp", title: "Will-o'-the-Wisp", emojis: "🕯🌫", level: "hard" },
  { id: "gremlin", title: "Gremlin", emojis: "👹🔧", level: "hard" },
  { id: "doppelganger", title: "Doppelganger", emojis: "👥🪞", level: "hard" },
  { id: "hobgoblin", title: "Hobgoblin", emojis: "👺🥛", level: "hard" },
  { id: "revenant", title: "Revenant", emojis: "💀⚰", level: "hard" },

  // ===== IMPOSSIBLE (25) — lesser-known world mythos, still gettable on reveal =====
  { id: "anansi", title: "Anansi", emojis: "🕷📖", level: "impossible" },
  { id: "baku", title: "Baku", emojis: "🐘💤", level: "impossible" },
  { id: "tengu", title: "Tengu", emojis: "👺🪽", level: "impossible" },
  { id: "leshy", title: "Leshy", emojis: "🌲👤", level: "impossible" },
  { id: "rusalka", title: "Rusalka", emojis: "👻🌊", level: "impossible" },
  { id: "qilin", title: "Qilin", emojis: "🦌🔥", level: "impossible" },
  { id: "bunyip", title: "Bunyip", emojis: "🐊🌊", level: "impossible" },
  { id: "ammit", title: "Ammit", emojis: "🐊⚖", level: "impossible" },
  { id: "apep", title: "Apep", emojis: "🐍🌑", level: "impossible" },
  { id: "bakeneko", title: "Bakeneko", emojis: "🐈🔥", level: "impossible" },
  { id: "tanuki", title: "Tanuki", emojis: "🦝🍶", level: "impossible" },
  { id: "amphithere", title: "Amphithere", emojis: "🐍🪽", level: "impossible" },
  { id: "catoblepas", title: "Catoblepas", emojis: "🐃💀", level: "impossible" },
  { id: "peryton", title: "Peryton", emojis: "🦌🪽", level: "impossible" },
  { id: "alkonost", title: "Alkonost", emojis: "🐦👩", level: "impossible" },
  { id: "simurgh", title: "Simurgh", emojis: "🦚🔥", level: "impossible" },
  { id: "nian", title: "Nian", emojis: "🦁🧨", level: "impossible" },
  { id: "encantado", title: "Encantado", emojis: "🐬🎩", level: "impossible" },
  { id: "ahuizotl", title: "Ahuizotl", emojis: "🐵💧", level: "impossible" },
  { id: "gaki", title: "Gaki", emojis: "👻🍚", level: "impossible" },
  { id: "tikbalang", title: "Tikbalang", emojis: "🐴🌴", level: "impossible" },
  { id: "manananggal", title: "Manananggal", emojis: "🦇👩", level: "impossible" },
  { id: "yowie", title: "Yowie", emojis: "🦶🌏", level: "impossible" },
  { id: "jorogumo", title: "Jorogumo", emojis: "🕷👩", level: "impossible" },
  { id: "lou-carcolh", title: "Lou Carcolh", emojis: "🐌🐍", level: "impossible" },
];
