// E146 «Guess the Ancient God by Emoji» — 100 ancient/extinct-pantheon deities · 25/tier · clue = plain Unicode emoji (mirrors E125 isEmoji rendering)
// Each emoji set fairly evokes the deity via its canonical attribute/symbol. Ancient polytheistic pantheons ONLY (no Abrahamic figures).
// VO: sfx/e146-<id>.wav — phrase "It's <God>!"
export const MYTHGOD_EMOJI = [
  // ===== EASY (25) — globally famous =====
  { id: "zeus", title: "Zeus", emojis: "⚡👑", level: "easy" },
  { id: "poseidon", title: "Poseidon", emojis: "🔱🌊", level: "easy" },
  { id: "hades", title: "Hades", emojis: "💀🔥", level: "easy" },
  { id: "ares", title: "Ares", emojis: "⚔🛡", level: "easy" },
  { id: "aphrodite", title: "Aphrodite", emojis: "💗🕊", level: "easy" },
  { id: "apollo", title: "Apollo", emojis: "☀🎵", level: "easy" },
  { id: "athena", title: "Athena", emojis: "🦉🛡", level: "easy" },
  { id: "hermes", title: "Hermes", emojis: "🪽👟", level: "easy" },
  { id: "artemis", title: "Artemis", emojis: "🏹🌙", level: "easy" },
  { id: "hera", title: "Hera", emojis: "👑🦚", level: "easy" },
  { id: "thor", title: "Thor", emojis: "⚡🔨", level: "easy" },
  { id: "odin", title: "Odin", emojis: "👁🐦", level: "easy" },
  { id: "loki", title: "Loki", emojis: "🐍🎭", level: "easy" },
  { id: "ra", title: "Ra", emojis: "☀🦅", level: "easy" },
  { id: "anubis", title: "Anubis", emojis: "🐕⚰", level: "easy" },
  { id: "isis", title: "Isis", emojis: "🪽👑", level: "easy" },
  { id: "horus", title: "Horus", emojis: "🦅👁", level: "easy" },
  { id: "osiris", title: "Osiris", emojis: "⚰👑", level: "easy" },
  { id: "jupiter", title: "Jupiter", emojis: "⚡🦅", level: "easy" },
  { id: "saturn", title: "Saturn", emojis: "🪐🌾", level: "easy" },
  { id: "janus", title: "Janus", emojis: "🚪🎭", level: "easy" },
  { id: "cupid", title: "Cupid", emojis: "🏹💘", level: "easy" },
  { id: "dionysus", title: "Dionysus", emojis: "🍇🍷", level: "easy" },
  { id: "hephaestus", title: "Hephaestus", emojis: "🔨🔥", level: "easy" },
  { id: "hercules", title: "Hercules", emojis: "💪🦁", level: "easy" },

  // ===== MEDIUM (25) — well-known with a beat =====
  { id: "hestia", title: "Hestia", emojis: "🔥🏠", level: "medium" },
  { id: "pan", title: "Pan", emojis: "🐐🎶", level: "medium" },
  { id: "demeter", title: "Demeter", emojis: "🌾🌸", level: "medium" },
  { id: "freya", title: "Freya", emojis: "🐈💗", level: "medium" },
  { id: "freyr", title: "Freyr", emojis: "🐗🌾", level: "medium" },
  { id: "baldr", title: "Baldr", emojis: "🌼✨", level: "medium" },
  { id: "heimdall", title: "Heimdall", emojis: "🌈📯", level: "medium" },
  { id: "tyr", title: "Tyr", emojis: "⚔🐺", level: "medium" },
  { id: "hel", title: "Hel", emojis: "💀❄", level: "medium" },
  { id: "sekhmet", title: "Sekhmet", emojis: "🦁🔥", level: "medium" },
  { id: "bastet", title: "Bastet", emojis: "🐈☀", level: "medium" },
  { id: "thoth", title: "Thoth", emojis: "🐦📜", level: "medium" },
  { id: "sobek", title: "Sobek", emojis: "🐊🌊", level: "medium" },
  { id: "set", title: "Set", emojis: "🌪🏜", level: "medium" },
  { id: "hathor", title: "Hathor", emojis: "🐄💗", level: "medium" },
  { id: "persephone", title: "Persephone", emojis: "🌷💀", level: "medium" },
  { id: "nike", title: "Nike", emojis: "🏆🪽", level: "medium" },
  { id: "gaia", title: "Gaia", emojis: "🌏🌱", level: "medium" },
  { id: "cronus", title: "Cronus", emojis: "⏳🌾", level: "medium" },
  { id: "tiamat", title: "Tiamat", emojis: "🐉🌊", level: "medium" },
  { id: "maat", title: "Maat", emojis: "🪶⚖", level: "medium" },
  { id: "vulcan", title: "Vulcan", emojis: "🌋⚒", level: "medium" },
  { id: "nephthys", title: "Nephthys", emojis: "🪽⚰", level: "medium" },
  { id: "shamash", title: "Shamash", emojis: "☀⚖", level: "medium" },
  { id: "diana", title: "Diana", emojis: "🦌🌙", level: "medium" },

  // ===== HARD (25) — lesser-known, gettable to a fan =====
  { id: "quetzalcoatl", title: "Quetzalcoatl", emojis: "🐍🪶", level: "hard" },
  { id: "huitzilopochtli", title: "Huitzilopochtli", emojis: "🐦⚔", level: "hard" },
  { id: "tlaloc", title: "Tlaloc", emojis: "🌧🌽", level: "hard" },
  { id: "xochipilli", title: "Xochipilli", emojis: "🌺🎶", level: "hard" },
  { id: "mictlantecuhtli", title: "Mictlantecuhtli", emojis: "💀🦇", level: "hard" },
  { id: "tezcatlipoca", title: "Tezcatlipoca", emojis: "🐆🪞", level: "hard" },
  { id: "cernunnos", title: "Cernunnos", emojis: "🦌🌿", level: "hard" },
  { id: "morrigan", title: "The Morrigan", emojis: "🐦💀", level: "hard" },
  { id: "lugh", title: "Lugh", emojis: "☀🗡", level: "hard" },
  { id: "brigid", title: "Brigid", emojis: "🔥📜", level: "hard" },
  { id: "dagda", title: "The Dagda", emojis: "🍲🎵", level: "hard" },
  { id: "marduk", title: "Marduk", emojis: "🐉⚡", level: "hard" },
  { id: "ishtar", title: "Ishtar", emojis: "⭐💗", level: "hard" },
  { id: "enki", title: "Enki", emojis: "🌊🐐", level: "hard" },
  { id: "anu", title: "Anu", emojis: "👑☁", level: "hard" },
  { id: "nergal", title: "Nergal", emojis: "💀🦁", level: "hard" },
  { id: "perun", title: "Perun", emojis: "⚡🪓", level: "hard" },
  { id: "veles", title: "Veles", emojis: "🐍🐂", level: "hard" },
  { id: "svarog", title: "Svarog", emojis: "☀⚒", level: "hard" },
  { id: "mokosh", title: "Mokosh", emojis: "🧵🌾", level: "hard" },
  { id: "amun", title: "Amun", emojis: "👑🐏", level: "hard" },
  { id: "ptah", title: "Ptah", emojis: "🔨🏺", level: "hard" },
  { id: "nut", title: "Nut", emojis: "🌌⭐", level: "hard" },
  { id: "geb", title: "Geb", emojis: "🌍🌾", level: "hard" },
  { id: "khonsu", title: "Khonsu", emojis: "🌙🦅", level: "hard" },

  // ===== IMPOSSIBLE (25) — real but obscure deities =====
  { id: "njord", title: "Njord", emojis: "🌊⛵", level: "impossible" },
  { id: "idun", title: "Idun", emojis: "🍎🌸", level: "impossible" },
  { id: "bragi", title: "Bragi", emojis: "🎵📜", level: "impossible" },
  { id: "skadi", title: "Skadi", emojis: "🎿🏔", level: "impossible" },
  { id: "ullr", title: "Ullr", emojis: "🏹❄", level: "impossible" },
  { id: "nyx", title: "Nyx", emojis: "🌌🦉", level: "impossible" },
  { id: "selene", title: "Selene", emojis: "🌕🐎", level: "impossible" },
  { id: "helios", title: "Helios", emojis: "☀🐎", level: "impossible" },
  { id: "eos", title: "Eos", emojis: "🌅🌹", level: "impossible" },
  { id: "hecate", title: "Hecate", emojis: "🔥🗝", level: "impossible" },
  { id: "nemesis", title: "Nemesis", emojis: "⚖🗡", level: "impossible" },
  { id: "tyche", title: "Tyche", emojis: "🎲🍀", level: "impossible" },
  { id: "hypnos", title: "Hypnos", emojis: "😴🌙", level: "impossible" },
  { id: "thanatos", title: "Thanatos", emojis: "💀🪽", level: "impossible" },
  { id: "nuada", title: "Nuada", emojis: "🗡✋", level: "impossible" },
  { id: "epona", title: "Epona", emojis: "🐎🌾", level: "impossible" },
  { id: "xolotl", title: "Xolotl", emojis: "🐕🌑", level: "impossible" },
  { id: "coatlicue", title: "Coatlicue", emojis: "🐍💀", level: "impossible" },
  { id: "ereshkigal", title: "Ereshkigal", emojis: "💀👑", level: "impossible" },
  { id: "ran", title: "Ran", emojis: "🌊🕸", level: "impossible" },
  { id: "forseti", title: "Forseti", emojis: "⚖🪑", level: "impossible" },
  { id: "ixchel", title: "Ixchel", emojis: "🌙🧵", level: "impossible" },
  { id: "itzamna", title: "Itzamna", emojis: "🦎📜", level: "impossible" },
  { id: "chac", title: "Chac", emojis: "🌧🪓", level: "impossible" },
  { id: "kukulkan", title: "Kukulkan", emojis: "🐍🏛", level: "impossible" },
];
