// E144 emoji mythical-creature facts — one verified <=70-char origin fact per creature, shown on reveal.
export const MYTHCREATURE_EMOJI_FACTS = {
  // EASY
  "dragon": "Fire-breathing winged serpent found in myths worldwide.",
  "unicorn": "Horse with a single horn, a symbol of purity in legend.",
  "mermaid": "Half-woman, half-fish who lures sailors from the sea.",
  "phoenix": "Bird that burns up and is reborn from its own ashes.",
  "vampire": "Undead being that rises at night to drink human blood.",
  "werewolf": "A human who transforms into a wolf under the full moon.",
  "fairy": "Tiny winged magical being from European folklore.",
  "genie": "Spirit bound to a lamp, granting wishes in Arabian lore.",
  "zombie": "A reanimated corpse that hungers for living flesh.",
  "ghost": "The lingering spirit of a dead person, haunting places.",
  "witch": "A woman with magic powers, said to fly on a broomstick.",
  "troll": "Hulking Norse creature that lurks under bridges.",
  "centaur": "Greek being with a man's torso on a horse's body.",
  "minotaur": "Bull-headed man trapped in the Cretan Labyrinth.",
  "cyclops": "One-eyed giant of Greek myth who forged Zeus's bolts.",
  "pegasus": "The winged white stallion of Greek mythology.",
  "griffin": "Beast with an eagle's head and a lion's body.",
  "yeti": "The Abominable Snowman of the Himalayan mountains.",
  "kraken": "Colossal octopus said to drag ships beneath the sea.",
  "cerberus": "Three-headed hound guarding the Underworld's gates.",
  "leprechaun": "Irish fairy shoemaker who hides a pot of gold.",
  "elf": "Graceful woodland archer of Norse and fantasy lore.",
  "goblin": "Small, greedy, mischievous creature of European myth.",
  "loch-ness-monster": "Nessie, a beast said to lurk in a Scottish lake.",
  "bigfoot": "Large hairy ape-man of North American forests.",

  // MEDIUM
  "sphinx": "Lion-bodied guardian who posed riddles in Egypt.",
  "hydra": "Serpent that grew two heads for each one cut off.",
  "chimera": "Fire-breathing mix of lion, goat, and serpent.",
  "medusa": "Gorgon with snake hair whose gaze turned men to stone.",
  "harpy": "Winged woman-bird that snatched food and souls.",
  "satyr": "Goat-legged companion of Dionysus who played pipes.",
  "siren": "Sea creature whose song lured sailors to their deaths.",
  "basilisk": "Serpent king said to kill with a single glance.",
  "golem": "Clay figure brought to life in Jewish folklore.",
  "valkyrie": "Norse maiden who chose the slain for Valhalla.",
  "kitsune": "Japanese fox spirit with many tails and fox-fire.",
  "dwarf": "Stout underground miner and smith of Norse myth.",
  "gnome": "Small earth spirit that guards underground treasure.",
  "ogre": "Large brutish man-eating monster of fairy tales.",
  "gargoyle": "Stone guardian on cathedrals, said to ward off evil.",
  "banshee": "Irish spirit whose wail foretells a coming death.",
  "kelpie": "Scottish shape-shifting water horse of rivers.",
  "selkie": "Seal that sheds its skin to become human on land.",
  "wendigo": "Gaunt, antlered spirit of hunger in Algonquian lore.",
  "thunderbird": "Giant bird whose beating wings make thunder.",
  "naga": "Serpent deity of water and rain in Hindu myth.",
  "garuda": "Eagle-like bird that serves as Vishnu's mount.",
  "kappa": "Japanese water imp that loves cucumbers.",
  "manticore": "Persian beast: lion's body, scorpion's tail.",
  "wyvern": "Two-legged winged dragon of heraldry.",

  // HARD
  "fenrir": "Monstrous Norse wolf chained until Ragnarok.",
  "jormungandr": "The Norse world serpent that encircles the earth.",
  "sleipnir": "Odin's eight-legged horse that rides through the sky.",
  "roc": "Enormous bird of Arabian tales that lifts elephants.",
  "cockatrice": "Rooster-serpent hybrid hatched from a cock's egg.",
  "wraith": "A ghostly apparition, often an omen of death.",
  "dullahan": "Headless horseman of Irish legend who carries his head.",
  "baba-yaga": "Slavic witch in a hut that stands on hen's legs.",
  "chupacabra": "Latin American beast that drains goats of blood.",
  "mothman": "Winged red-eyed cryptid seen in West Virginia.",
  "jackalope": "American folklore rabbit with antelope horns.",
  "salamander": "Lizard-like elemental spirit born of fire.",
  "behemoth": "Colossal land beast from the Book of Job.",
  "leviathan": "Vast sea monster of biblical and Hebrew lore.",
  "hippogriff": "Offspring of a griffin and a mare, half eagle.",
  "pixie": "Small mischievous fairy of Cornish folklore.",
  "imp": "Little mischievous demon that torments people.",
  "ifrit": "Powerful fiery jinn of Arabian and Islamic myth.",
  "poltergeist": "Noisy ghost that hurls objects around a home.",
  "changeling": "Fairy child left in place of a stolen human baby.",
  "will-o-the-wisp": "Ghostly light that lures travelers into marshes.",
  "gremlin": "Sprite blamed for sabotaging aircraft and machines.",
  "doppelganger": "A ghostly double of a living person, an ill omen.",
  "hobgoblin": "Household sprite, helpful but easily angered.",
  "revenant": "A corpse that returns from the grave to haunt the living.",

  // IMPOSSIBLE
  "anansi": "West African trickster spider who owns all stories.",
  "baku": "Japanese chimera spirit that devours nightmares.",
  "tengu": "Japanese mountain goblin with wings and a long nose.",
  "leshy": "Slavic forest guardian who leads travelers astray.",
  "rusalka": "Slavic spirit of a drowned maiden haunting rivers.",
  "qilin": "Chinese chimeric beast appearing in times of peace.",
  "bunyip": "Australian Aboriginal monster lurking in swamps.",
  "ammit": "Egyptian devourer of hearts with a crocodile head.",
  "apep": "Egyptian serpent of chaos who fought the sun god.",
  "bakeneko": "Japanese cat that shape-shifts and walks upright.",
  "tanuki": "Japanese shape-shifting raccoon dog fond of sake.",
  "amphithere": "A winged, legless serpent of heraldic legend.",
  "catoblepas": "Beast whose heavy head hides a deadly downward gaze.",
  "peryton": "Winged stag that casts a human shadow until it kills.",
  "alkonost": "Slavic bird-woman whose song brings bliss.",
  "simurgh": "Benevolent giant bird of ancient Persian myth.",
  "nian": "Chinese New Year beast scared off by red and noise.",
  "encantado": "Amazon river dolphin that shape-shifts into a man.",
  "ahuizotl": "Aztec water beast with a grasping hand on its tail.",
  "gaki": "Japanese hungry ghost cursed with endless hunger.",
  "tikbalang": "Philippine horse-headed trickster of the wilds.",
  "manananggal": "Philippine vampire that splits its body in half.",
  "yowie": "Australia's hairy ape-man of the outback.",
  "jorogumo": "Japanese spider that becomes a seductive woman.",
  "lou-carcolh": "French snail-serpent with long, slimy tentacles.",
};
