// «Guess the Nut or Seed» — GuessSync · E63 · did-you-know facts, ≤70 chars, verified true.
export const NUT_FACTS = {
  // EASY
  almond: "It is the seed of a fruit related to peaches and plums",
  walnut: "Its wrinkled kernel looks a bit like a tiny brain",
  peanut: "Not a true nut; it is a legume that grows underground",
  cashew: "Grows attached to the bottom of a fleshy cashew apple",
  pistachio: "It splits its own shell open with a pop as it ripens",
  hazelnut: "Blended with cocoa, it is the base of chocolate spreads",
  pecan: "A hickory native to North America; 'pecan' is a Native word",
  sunflowerseed: "Harvested from the dark centre of a sunflower head",
  pumpkinseed: "Flat green seeds also known by the name pepitas",
  chestnut: "Low in fat and roasted whole; often sold hot in winter",
  coconut: "The largest seed you can easily buy in a shop",
  pinenut: "Tiny seed hand-picked from inside pine cones",
  macadamia: "A very hard-shelled nut native to Australia",
  brazilnut: "One nut can exceed your daily need for the mineral selenium",
  chiaseed: "Tiny seeds that swell into a gel when soaked in water",
  flaxseed: "Also called linseed; pressed to make linseed oil",
  sesameseed: "Ground into tahini and the sweet paste behind halva",
  lentil: "A lens-shaped legume that cooks without soaking",
  chickpea: "The main ingredient in hummus and falafel",
  kidneybean: "Named for its shape; must be boiled to be safe to eat",
  soybean: "Turned into tofu, soy milk, soy sauce and miso",
  blackbean: "A staple in Latin American rice-and-bean dishes",
  greenpea: "Picked young and sweet before the pod dries out",
  pomegranateseed: "The juicy red seeds are called arils",
  poppyseed: "Tiny blue-grey seeds that top many breads and rolls",
  // MEDIUM
  pintobean: "Speckled when raw; turns solid brown once cooked",
  navybean: "Small white bean used for classic baked beans",
  limabean: "Also called the butter bean for its creamy texture",
  blackeyedpea: "A cream bean with a single black spot or 'eye'",
  cannellinibean: "A large white kidney bean popular in Italy",
  mungbean: "Sprouted for the crunchy bean sprouts in stir-fries",
  favabean: "One of the oldest cultivated legumes; also called broad bean",
  edamame: "Young soybeans boiled and served in the pod",
  splitpea: "Dried peas split in half; the base of pea soup",
  hempseed: "A soft seed from hemp with no drug effect",
  quinoa: "A seed eaten like a grain; a staple of the ancient Inca",
  buckwheat: "Not wheat; its seed is ground for pancakes and soba",
  cacaobean: "Fermented and roasted, it becomes chocolate",
  coffeebean: "Actually the roasted seed of a red coffee cherry",
  adzukibean: "Small red bean sweetened into East Asian red-bean paste",
  cranberrybean: "Cream bean with red streaks; also called borlotti",
  waterchestnut: "A crunchy water plant tuber, not a true nut",
  amaranth: "Tiny seed that pops like miniature popcorn when heated",
  millet: "Small round grains and a common ingredient in birdseed",
  watermelonseed: "Roasted and cracked for a snack across the Middle East",
  acorn: "The nut of oak trees; must be leached to remove bitterness",
  greatnorthernbean: "A mild white bean larger than the navy bean",
  blackwalnut: "A native American walnut with an intensely bold flavour",
  butternut: "The white walnut, a mild sweet nut of eastern North America",
  sorghum: "A cereal grain also boiled down into a sweet syrup",
  // HARD
  pilinut: "A buttery Philippine nut inside a hard black shell",
  beechnut: "The small triangular nut of the beech tree",
  chinquapin: "A small sweet relative of the chestnut",
  hickorynut: "The rich nut of hickory trees; a pecan cousin",
  gevuina: "The Chilean hazelnut, from an evergreen tree",
  bambaragroundnut: "An African legume that ripens underground like a peanut",
  wingedbean: "A tropical bean whose pod has four frilly wings",
  lupinibean: "A yellow bean brined and eaten as a snack in Italy",
  ricebean: "A tiny Asian bean about the size of a rice grain",
  mothbean: "A drought-hardy Indian bean, sprouted for moth dal",
  teparybean: "A desert bean grown by peoples of the US Southwest",
  hyacinthbean: "A legume with striking purple pods, also called lablab",
  jackbean: "A large flat white bean from a vigorous tropical vine",
  yardlongbean: "A bean whose slender pods can grow up to a metre long",
  maramabean: "A protein-rich bean from the Kalahari desert vine",
  guarbean: "Its seed gum, guar gum, thickens many packaged foods",
  carob: "Its sweet pods are ground into a cocoa substitute",
  jobstears: "A grass seed with hard beads once used as necklaces",
  perillaseed: "The seed of shiso, pressed for a nutty Korean oil",
  nigerseed: "A small black oilseed and a favourite finch food",
  safflowerseed: "Pressed for a light cooking oil; also a birdseed",
  camelinaseed: "An ancient oilseed nicknamed 'false flax'",
  cottonseed: "The fuzzy seed of cotton, pressed for cottonseed oil",
  grasspea: "A hardy legume that survives drought and flood",
  bittervetch: "One of the first legumes ever farmed in the Near East",
  // IMPOSSIBLE
  tigernut: "A small sweet tuber, not a nut; base of Spanish horchata",
  kolanut: "A caffeine-rich seed once used to flavour cola drinks",
  ginkgonut: "The seed of the ancient ginkgo tree, eaten in East Asia",
  barunut: "An almond-like nut from the Brazilian savanna",
  sachainchi: "A star-shaped Amazon seed pod rich in omega-3 oil",
  candlenut: "So oily its kernels were once burned like candles",
  breadnut: "The seed of a breadfruit relative, boiled or roasted",
  marula: "The nut inside marula fruit, used in a cream liqueur",
  mongongonut: "A staple nut of the San people of southern Africa",
  paradisenut: "A Brazil-nut relative housed in a lidded woody pod",
  souarinut: "A rich butternut-like nut from tropical South America",
  watercaltrop: "A horned water-plant seed also called the water chestnut",
  ogbono: "The wild-mango seed ground to thicken West African soups",
  karuka: "A pandanus nut and highland staple of New Guinea",
  yehebnut: "A sweet nut from a shrub of the Somali desert",
  malabarchestnut: "Seed of the money tree, tasting of roasted peanuts",
  jackfruitseed: "The starchy seed inside jackfruit, boiled like a chestnut",
  lotusseed: "The seed of the lotus flower, used in Asian sweets",
  foxnut: "Puffed lotus-family seeds sold as the snack makhana",
  detarium: "A West African seed ground into a soup thickener",
  velvetbean: "A tropical legume covered in itchy velvety hairs",
  africanlocustbean: "Its seeds are fermented into the condiment dawadawa",
  swordbean: "A giant curved pod bean of tropical Asia and Africa",
  gacseed: "The seed of a bright orange-red Southeast Asian fruit",
  coquitonut: "A tiny 'mini-coconut' from the Chilean wine palm",
};
