// E18 · «Guess the Painting» — 100 لوحة ملكية عامة (25/مستوى) · صورة paintings/<slug>.jpg (من ويكيبيديا) · صوت pt-<slug>.wav
// wiki = عنوان مقالة ويكيبيديا الإنجليزية (لجلب الصورة) · title = الإجابة · artist = الفنان (سطر فرعي)
export const PAINTINGS = [
  // ===== EASY (25) =====
  { slug: "mona-lisa", title: "Mona Lisa", artist: "Leonardo da Vinci", wiki: "Mona Lisa", level: "easy" },
  { slug: "the-starry-night", title: "The Starry Night", artist: "Vincent van Gogh", wiki: "The Starry Night", level: "easy" },
  { slug: "the-scream", title: "The Scream", artist: "Edvard Munch", wiki: "The Scream", level: "easy" },
  { slug: "the-last-supper", title: "The Last Supper", artist: "Leonardo da Vinci", wiki: "The Last Supper (Leonardo)", level: "easy" },
  { slug: "girl-with-a-pearl-earring", title: "Girl with a Pearl Earring", artist: "Johannes Vermeer", wiki: "Girl with a Pearl Earring", level: "easy" },
  { slug: "the-birth-of-venus", title: "The Birth of Venus", artist: "Sandro Botticelli", wiki: "The Birth of Venus", level: "easy" },
  { slug: "american-gothic", title: "American Gothic", artist: "Grant Wood", wiki: "American Gothic", level: "easy" },
  { slug: "the-creation-of-adam", title: "The Creation of Adam", artist: "Michelangelo", wiki: "The Creation of Adam", level: "easy" },
  { slug: "the-kiss-klimt", title: "The Kiss", artist: "Gustav Klimt", wiki: "The Kiss (Klimt)", level: "easy" },
  { slug: "the-great-wave-off-kanagawa", title: "The Great Wave off Kanagawa", artist: "Katsushika Hokusai", wiki: "The Great Wave off Kanagawa", level: "easy" },
  { slug: "sunflowers-van-gogh", title: "Sunflowers", artist: "Vincent van Gogh", wiki: "Sunflowers (Van Gogh series)", level: "easy" },
  { slug: "the-night-watch", title: "The Night Watch", artist: "Rembrandt", wiki: "The Night Watch", level: "easy" },
  { slug: "water-lilies-monet", title: "Water Lilies", artist: "Claude Monet", wiki: "Water Lilies (Monet series)", level: "easy" },
  { slug: "the-school-of-athens", title: "The School of Athens", artist: "Raphael", wiki: "The School of Athens", level: "easy" },
  { slug: "the-garden-of-earthly-delights", title: "The Garden of Earthly Delights", artist: "Hieronymus Bosch", wiki: "The Garden of Earthly Delights", level: "easy" },
  { slug: "liberty-leading-the-people", title: "Liberty Leading the People", artist: "Eugène Delacroix", wiki: "Liberty Leading the People", level: "easy" },
  { slug: "cafe-terrace-at-night", title: "Café Terrace at Night", artist: "Vincent van Gogh", wiki: "Café Terrace at Night", level: "easy" },
  { slug: "the-arnolfini-portrait", title: "The Arnolfini Portrait", artist: "Jan van Eyck", wiki: "Arnolfini Portrait", level: "easy" },
  { slug: "the-third-of-may-1808", title: "The Third of May 1808", artist: "Francisco Goya", wiki: "The Third of May 1808", level: "easy" },
  { slug: "las-meninas", title: "Las Meninas", artist: "Diego Velázquez", wiki: "Las Meninas", level: "easy" },
  { slug: "a-sunday-on-la-grande-jatte", title: "A Sunday on La Grande Jatte", artist: "Georges Seurat", wiki: "A Sunday Afternoon on the Island of La Grande Jatte", level: "easy" },
  { slug: "whistlers-mother", title: "Whistler's Mother", artist: "James McNeill Whistler", wiki: "Whistler's Mother", level: "easy" },
  { slug: "the-hay-wain", title: "The Hay Wain", artist: "John Constable", wiki: "The Hay Wain", level: "easy" },
  { slug: "wanderer-above-the-sea-of-fog", title: "Wanderer above the Sea of Fog", artist: "Caspar David Friedrich", wiki: "Wanderer above the Sea of Fog", level: "easy" },
  { slug: "the-bedroom-van-gogh", title: "The Bedroom", artist: "Vincent van Gogh", wiki: "Bedroom in Arles", level: "easy" },

  // ===== MEDIUM (25) =====
  { slug: "the-fighting-temeraire", title: "The Fighting Temeraire", artist: "J. M. W. Turner", wiki: "The Fighting Temeraire", level: "medium" },
  { slug: "bal-du-moulin-de-la-galette", title: "Bal du moulin de la Galette", artist: "Pierre-Auguste Renoir", wiki: "Bal du moulin de la Galette", level: "medium" },
  { slug: "ophelia-millais", title: "Ophelia", artist: "John Everett Millais", wiki: "Ophelia (Millais)", level: "medium" },
  { slug: "the-ambassadors-holbein", title: "The Ambassadors", artist: "Hans Holbein the Younger", wiki: "The Ambassadors (Holbein)", level: "medium" },
  { slug: "impression-sunrise", title: "Impression, Sunrise", artist: "Claude Monet", wiki: "Impression, Sunrise", level: "medium" },
  { slug: "napoleon-crossing-the-alps", title: "Napoleon Crossing the Alps", artist: "Jacques-Louis David", wiki: "Napoleon Crossing the Alps", level: "medium" },
  { slug: "the-anatomy-lesson", title: "The Anatomy Lesson", artist: "Rembrandt", wiki: "The Anatomy Lesson of Dr. Nicolaes Tulp", level: "medium" },
  { slug: "the-swing-fragonard", title: "The Swing", artist: "Jean-Honoré Fragonard", wiki: "The Swing (Fragonard)", level: "medium" },
  { slug: "the-milkmaid-vermeer", title: "The Milkmaid", artist: "Johannes Vermeer", wiki: "The Milkmaid (Vermeer)", level: "medium" },
  { slug: "primavera-botticelli", title: "Primavera", artist: "Sandro Botticelli", wiki: "Primavera (Botticelli)", level: "medium" },
  { slug: "the-death-of-marat", title: "The Death of Marat", artist: "Jacques-Louis David", wiki: "The Death of Marat", level: "medium" },
  { slug: "irises-van-gogh", title: "Irises", artist: "Vincent van Gogh", wiki: "Irises (painting)", level: "medium" },
  { slug: "composition-red-blue-yellow", title: "Composition with Red, Blue and Yellow", artist: "Piet Mondrian", wiki: "Composition with Red, Blue and Yellow", level: "medium" },
  { slug: "the-raft-of-the-medusa", title: "The Raft of the Medusa", artist: "Théodore Géricault", wiki: "The Raft of the Medusa", level: "medium" },
  { slug: "the-gleaners", title: "The Gleaners", artist: "Jean-François Millet", wiki: "The Gleaners", level: "medium" },
  { slug: "luncheon-of-the-boating-party", title: "Luncheon of the Boating Party", artist: "Pierre-Auguste Renoir", wiki: "Luncheon of the Boating Party", level: "medium" },
  { slug: "olympia-manet", title: "Olympia", artist: "Édouard Manet", wiki: "Olympia (Manet)", level: "medium" },
  { slug: "the-luncheon-on-the-grass", title: "The Luncheon on the Grass", artist: "Édouard Manet", wiki: "Le Déjeuner sur l'herbe", level: "medium" },
  { slug: "saturn-devouring-his-son", title: "Saturn Devouring His Son", artist: "Francisco Goya", wiki: "Saturn Devouring His Son", level: "medium" },
  { slug: "the-card-players", title: "The Card Players", artist: "Paul Cézanne", wiki: "The Card Players", level: "medium" },
  { slug: "the-tower-of-babel", title: "The Tower of Babel", artist: "Pieter Bruegel the Elder", wiki: "The Tower of Babel (Bruegel)", level: "medium" },
  { slug: "hunters-in-the-snow", title: "The Hunters in the Snow", artist: "Pieter Bruegel the Elder", wiki: "The Hunters in the Snow", level: "medium" },
  { slug: "the-sleeping-gypsy", title: "The Sleeping Gypsy", artist: "Henri Rousseau", wiki: "The Sleeping Gypsy", level: "medium" },
  { slug: "the-fifer", title: "The Fifer", artist: "Édouard Manet", wiki: "The Fifer", level: "medium" },
  { slug: "portrait-of-adele-bloch-bauer", title: "Portrait of Adele Bloch-Bauer I", artist: "Gustav Klimt", wiki: "Portrait of Adele Bloch-Bauer I", level: "medium" },

  // ===== HARD (25) =====
  { slug: "the-tempest-giorgione", title: "The Tempest", artist: "Giorgione", wiki: "The Tempest (Giorgione)", level: "hard" },
  { slug: "the-calling-of-st-matthew", title: "The Calling of Saint Matthew", artist: "Caravaggio", wiki: "The Calling of Saint Matthew", level: "hard" },
  { slug: "mont-sainte-victoire", title: "Mont Sainte-Victoire", artist: "Paul Cézanne", wiki: "Mont Sainte-Victoire (Cézanne)", level: "hard" },
  { slug: "the-embarkation-for-cythera", title: "The Embarkation for Cythera", artist: "Antoine Watteau", wiki: "The Embarkation for Cythera", level: "hard" },
  { slug: "the-lady-of-shalott", title: "The Lady of Shalott", artist: "John William Waterhouse", wiki: "The Lady of Shalott (painting)", level: "hard" },
  { slug: "the-oath-of-the-horatii", title: "Oath of the Horatii", artist: "Jacques-Louis David", wiki: "Oath of the Horatii", level: "hard" },
  { slug: "grande-odalisque", title: "Grande Odalisque", artist: "Jean-Auguste-Dominique Ingres", wiki: "Grande Odalisque", level: "hard" },
  { slug: "portrait-of-madame-x", title: "Portrait of Madame X", artist: "John Singer Sargent", wiki: "Portrait of Madame X", level: "hard" },
  { slug: "the-ballet-class", title: "The Dance Class", artist: "Edgar Degas", wiki: "The Dance Class", level: "hard" },
  { slug: "vision-after-the-sermon", title: "Vision after the Sermon", artist: "Paul Gauguin", wiki: "Vision after the Sermon", level: "hard" },
  { slug: "the-yellow-christ", title: "The Yellow Christ", artist: "Paul Gauguin", wiki: "The Yellow Christ", level: "hard" },
  { slug: "an-experiment-on-a-bird", title: "An Experiment on a Bird in the Air Pump", artist: "Joseph Wright of Derby", wiki: "An Experiment on a Bird in the Air Pump", level: "hard" },
  { slug: "the-wounded-angel", title: "The Wounded Angel", artist: "Hugo Simberg", wiki: "The Wounded Angel", level: "hard" },
  { slug: "the-nightmare-fuseli", title: "The Nightmare", artist: "Henry Fuseli", wiki: "The Nightmare", level: "hard" },
  { slug: "the-isle-of-the-dead", title: "Isle of the Dead", artist: "Arnold Böcklin", wiki: "Isle of the Dead (painting)", level: "hard" },
  { slug: "the-gross-clinic", title: "The Gross Clinic", artist: "Thomas Eakins", wiki: "The Gross Clinic", level: "hard" },
  { slug: "a-bar-at-the-folies-bergere", title: "A Bar at the Folies-Bergère", artist: "Édouard Manet", wiki: "A Bar at the Folies-Bergère", level: "hard" },
  { slug: "a-burial-at-ornans", title: "A Burial at Ornans", artist: "Gustave Courbet", wiki: "A Burial at Ornans", level: "hard" },
  { slug: "watson-and-the-shark", title: "Watson and the Shark", artist: "John Singleton Copley", wiki: "Watson and the Shark", level: "hard" },
  { slug: "the-death-of-sardanapalus", title: "The Death of Sardanapalus", artist: "Eugène Delacroix", wiki: "The Death of Sardanapalus", level: "hard" },
  { slug: "the-birth-of-venus-bouguereau", title: "Birth of Venus (Bouguereau)", artist: "William-Adolphe Bouguereau", wiki: "The Birth of Venus (Bouguereau)", level: "hard" },
  { slug: "the-scapegoat-hunt", title: "The Scapegoat", artist: "William Holman Hunt", wiki: "The Scapegoat (painting)", level: "hard" },
  { slug: "proserpine-rossetti", title: "Proserpine", artist: "Dante Gabriel Rossetti", wiki: "Proserpine (Rossetti painting)", level: "hard" },
  { slug: "the-fog-warning", title: "The Fog Warning", artist: "Winslow Homer", wiki: "The Fog Warning", level: "hard" },
  { slug: "composition-vii-kandinsky", title: "Composition VII", artist: "Wassily Kandinsky", wiki: "Composition VII", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { slug: "the-cardsharps", title: "The Cardsharps", artist: "Caravaggio", wiki: "The Cardsharps", level: "impossible" },
  { slug: "the-concert-vermeer", title: "The Concert", artist: "Johannes Vermeer", wiki: "The Concert (Vermeer)", level: "impossible" },
  { slug: "the-jewish-bride", title: "The Jewish Bride", artist: "Rembrandt", wiki: "The Jewish Bride", level: "impossible" },
  { slug: "the-avenue-at-middelharnis", title: "The Avenue at Middelharnis", artist: "Meindert Hobbema", wiki: "The Avenue at Middelharnis", level: "impossible" },
  { slug: "the-ninth-wave", title: "The Ninth Wave", artist: "Ivan Aivazovsky", wiki: "The Ninth Wave", level: "impossible" },
  { slug: "barge-haulers-on-the-volga", title: "Barge Haulers on the Volga", artist: "Ilya Repin", wiki: "Barge Haulers on the Volga", level: "impossible" },
  { slug: "the-floor-scrapers", title: "The Floor Scrapers", artist: "Gustave Caillebotte", wiki: "The Floor Scrapers", level: "impossible" },
  { slug: "paris-street-rainy-day", title: "Paris Street; Rainy Day", artist: "Gustave Caillebotte", wiki: "Paris Street; Rainy Day", level: "impossible" },
  { slug: "the-cornfield-constable", title: "The Cornfield", artist: "John Constable", wiki: "The Cornfield", level: "impossible" },
  { slug: "venus-cupid-folly-time", title: "Venus, Cupid, Folly and Time", artist: "Agnolo Bronzino", wiki: "Venus, Cupid, Folly and Time", level: "impossible" },
  { slug: "the-ambassadors-of-agamemnon", title: "The Ambassadors of Agamemnon", artist: "Jean-Auguste-Dominique Ingres", wiki: "The Ambassadors of Agamemnon in the tent of Achilles", level: "impossible" },
  { slug: "the-white-horse-constable", title: "The White Horse", artist: "John Constable", wiki: "The White Horse (Constable)", level: "impossible" },
  { slug: "the-abbey-in-the-oakwood", title: "The Abbey in the Oakwood", artist: "Caspar David Friedrich", wiki: "The Abbey in the Oakwood", level: "impossible" },
  { slug: "the-triumph-of-galatea", title: "The Triumph of Galatea", artist: "Raphael", wiki: "Galatea (Raphael)", level: "impossible" },
  { slug: "the-hireling-shepherd", title: "The Hireling Shepherd", artist: "William Holman Hunt", wiki: "The Hireling Shepherd", level: "impossible" },
  { slug: "the-ghent-altarpiece", title: "The Ghent Altarpiece", artist: "Jan van Eyck", wiki: "Ghent Altarpiece", level: "impossible" },
  { slug: "the-return-of-the-herd", title: "The Return of the Herd", artist: "Pieter Bruegel the Elder", wiki: "The Return of the Herd", level: "impossible" },
  { slug: "the-blue-boy", title: "The Blue Boy", artist: "Thomas Gainsborough", wiki: "The Blue Boy", level: "impossible" },
  { slug: "rain-steam-and-speed", title: "Rain, Steam and Speed", artist: "J. M. W. Turner", wiki: "Rain, Steam and Speed – The Great Western Railway", level: "impossible" },
  { slug: "the-boyhood-of-raleigh", title: "The Boyhood of Raleigh", artist: "John Everett Millais", wiki: "The Boyhood of Raleigh", level: "impossible" },
  { slug: "a-cotton-office-in-new-orleans", title: "A Cotton Office in New Orleans", artist: "Edgar Degas", wiki: "A Cotton Office in New Orleans", level: "impossible" },
  { slug: "flaming-june", title: "Flaming June", artist: "Frederic Leighton", wiki: "Flaming June", level: "impossible" },
  { slug: "the-cyclops-redon", title: "The Cyclops", artist: "Odilon Redon", wiki: "The Cyclops (Redon)", level: "impossible" },
  { slug: "whistlejacket", title: "Whistlejacket", artist: "George Stubbs", wiki: "Whistlejacket", level: "impossible" },
  { slug: "the-stone-breakers", title: "The Stone Breakers", artist: "Gustave Courbet", wiki: "The Stone Breakers", level: "impossible" },
];

export const PAINTING_LEVELS = ["easy", "medium", "hard", "impossible"];
