// «Guess the Pasta» — GuessSync · E61 · 100 pasta shapes (25/level) · real photos from Wikimedia Commons
// Absolute difficulty by global recognizability: easy (Spaghetti/Penne) ← impossible (Lorighittas/Su Filindeu/Corzetti).
export const PASTA = [
  // EASY (25) — household-name shapes everyone knows
  { slug: "spaghetti", name: "Spaghetti", level: "easy" },
  { slug: "penne", name: "Penne", level: "easy" },
  { slug: "macaroni", name: "Macaroni", level: "easy" },
  { slug: "fusilli", name: "Fusilli", level: "easy" },
  { slug: "farfalle", name: "Farfalle", level: "easy" },
  { slug: "lasagne", name: "Lasagne", level: "easy" },
  { slug: "ravioli", name: "Ravioli", level: "easy" },
  { slug: "rigatoni", name: "Rigatoni", level: "easy" },
  { slug: "fettuccine", name: "Fettuccine", level: "easy" },
  { slug: "linguine", name: "Linguine", level: "easy" },
  { slug: "tortellini", name: "Tortellini", level: "easy" },
  { slug: "gnocchi", name: "Gnocchi", level: "easy" },
  { slug: "cannelloni", name: "Cannelloni", level: "easy" },
  { slug: "vermicelli", name: "Vermicelli", level: "easy" },
  { slug: "ziti", name: "Ziti", level: "easy" },
  { slug: "tagliatelle", name: "Tagliatelle", level: "easy" },
  { slug: "conchiglie", name: "Conchiglie", level: "easy" },
  { slug: "rotini", name: "Rotini", level: "easy" },
  { slug: "orzo", name: "Orzo", level: "easy" },
  { slug: "pappardelle", name: "Pappardelle", level: "easy" },
  { slug: "manicotti", name: "Manicotti", level: "easy" },
  { slug: "capellini", name: "Capellini", level: "easy" },
  { slug: "rotelle", name: "Rotelle", level: "easy" },
  { slug: "ditalini", name: "Ditalini", level: "easy" },
  { slug: "cavatappi", name: "Cavatappi", level: "easy" },
  // MEDIUM (25) — common in shops, less top-of-mind
  { slug: "tortelloni", name: "Tortelloni", level: "medium" },
  { slug: "campanelle", name: "Campanelle", level: "medium" },
  { slug: "radiatori", name: "Radiatori", level: "medium" },
  { slug: "gigli", name: "Gigli", level: "medium" },
  { slug: "bigoli", name: "Bigoli", level: "medium" },
  { slug: "pici", name: "Pici", level: "medium" },
  { slug: "trenette", name: "Trenette", level: "medium" },
  { slug: "malloreddus", name: "Malloreddus", level: "medium" },
  { slug: "stelline", name: "Stelline", level: "medium" },
  { slug: "fregola", name: "Fregola", level: "medium" },
  { slug: "agnolotti", name: "Agnolotti", level: "medium" },
  { slug: "calamarata", name: "Calamarata", level: "medium" },
  { slug: "lumaconi", name: "Lumaconi", level: "medium" },
  { slug: "gramigna", name: "Gramigna", level: "medium" },
  { slug: "sedanini", name: "Sedanini", level: "medium" },
  { slug: "pastina", name: "Pastina", level: "medium" },
  { slug: "anelli", name: "Anelli", level: "medium" },
  { slug: "conchiglioni", name: "Conchiglioni", level: "medium" },
  { slug: "fideo", name: "Fideo", level: "medium" },
  { slug: "maltagliati", name: "Maltagliati", level: "medium" },
  { slug: "quadrucci", name: "Quadrucci", level: "medium" },
  { slug: "girandole", name: "Girandole", level: "medium" },
  { slug: "bavette", name: "Bavette", level: "medium" },
  { slug: "cappelletti", name: "Cappelletti", level: "medium" },
  { slug: "tortiglioni", name: "Tortiglioni", level: "medium" },
  // HARD (25) — regional Italian shapes, foodie territory
  { slug: "bucatini", name: "Bucatini", level: "hard" },
  { slug: "orecchiette", name: "Orecchiette", level: "hard" },
  { slug: "paccheri", name: "Paccheri", level: "hard" },
  { slug: "trofie", name: "Trofie", level: "hard" },
  { slug: "casarecce", name: "Casarecce", level: "hard" },
  { slug: "strozzapreti", name: "Strozzapreti", level: "hard" },
  { slug: "gemelli", name: "Gemelli", level: "hard" },
  { slug: "cavatelli", name: "Cavatelli", level: "hard" },
  { slug: "garganelli", name: "Garganelli", level: "hard" },
  { slug: "mafaldine", name: "Mafaldine", level: "hard" },
  { slug: "busiate", name: "Busiate", level: "hard" },
  { slug: "fileja", name: "Fileja", level: "hard" },
  { slug: "testaroli", name: "Testaroli", level: "hard" },
  { slug: "culurgiones", name: "Culurgiones", level: "hard" },
  { slug: "casoncelli", name: "Casoncelli", level: "hard" },
  { slug: "pansotti", name: "Pansotti", level: "hard" },
  { slug: "stringozzi", name: "Stringozzi", level: "hard" },
  { slug: "scialatielli", name: "Scialatielli", level: "hard" },
  { slug: "cencioni", name: "Cencioni", level: "hard" },
  { slug: "foglieulivo", name: "Foglie d'Ulivo", level: "hard" },
  { slug: "spaccatelle", name: "Spaccatelle", level: "hard" },
  { slug: "chifferi", name: "Chifferi", level: "hard" },
  { slug: "creste", name: "Creste di Gallo", level: "hard" },
  { slug: "cellentani", name: "Cellentani", level: "hard" },
  { slug: "cappellacci", name: "Cappellacci", level: "hard" },
  // IMPOSSIBLE (25) — ultra-rare / obscure regional shapes
  { slug: "corzetti", name: "Corzetti", level: "impossible" },
  { slug: "pizzoccheri", name: "Pizzoccheri", level: "impossible" },
  { slug: "lorighittas", name: "Lorighittas", level: "impossible" },
  { slug: "sacchettini", name: "Sacchettini", level: "impossible" },
  { slug: "filindeu", name: "Su Filindeu", level: "impossible" },
  { slug: "lagane", name: "Lagane", level: "impossible" },
  { slug: "maccheroncini", name: "Maccheroncini di Campofilone", level: "impossible" },
  { slug: "chitarra", name: "Spaghetti alla Chitarra", level: "impossible" },
  { slug: "sagnarelli", name: "Sagnarelli", level: "impossible" },
  { slug: "caramelle", name: "Caramelle", level: "impossible" },
  { slug: "fiori", name: "Fiori", level: "impossible" },
  { slug: "piperigate", name: "Pipe Rigate", level: "impossible" },
  { slug: "mezzemaniche", name: "Mezze Maniche", level: "impossible" },
  { slug: "tacconi", name: "Tacconi", level: "impossible" },
  { slug: "fagottini", name: "Fagottini", level: "impossible" },
  { slug: "umbricelli", name: "Umbricelli", level: "impossible" },
  { slug: "sagneincannulate", name: "Sagne 'ncannulate", level: "impossible" },
  { slug: "ferretto", name: "Maccheroni al Ferretto", level: "impossible" },
  { slug: "strascinati", name: "Strascinati", level: "impossible" },
  { slug: "fusillilunghi", name: "Fusilli Lunghi", level: "impossible" },
  { slug: "schlutzkrapfen", name: "Schlutzkrapfen", level: "impossible" },
  { slug: "passatelli", name: "Passatelli", level: "impossible" },
  { slug: "capunti", name: "Capunti", level: "impossible" },
  { slug: "sorprese", name: "Sorprese", level: "impossible" },
  { slug: "grattini", name: "Grattini", level: "impossible" },
];
