// «Guess the Pasta» — GuessSync · E61 · did-you-know facts, ≤70 chars, verified true.
export const PASTA_FACTS = {
  // EASY
  spaghetti: "Long thin round rods; Italy's most famous pasta shape",
  penne: "Short tubes cut on the diagonal into quill-like points",
  macaroni: "Short curved tubes; the classic 'mac and cheese' pasta",
  fusilli: "Corkscrew spirals that trap thick sauces in their coils",
  farfalle: "Bow-tie shape pinched tight in the middle",
  lasagne: "Wide flat sheets layered and baked with sauce",
  ravioli: "Square pockets of pasta filled and sealed at the edges",
  rigatoni: "Large ridged tubes with straight-cut ends",
  fettuccine: "Flat egg-ribbon noodles, a Roman classic",
  linguine: "Flattened strands, like a pressed spaghetti",
  tortellini: "Small ring-shaped pasta stuffed and folded by hand",
  gnocchi: "Soft dumplings usually made from potato and flour",
  cannelloni: "Large tubes stuffed with filling and baked",
  vermicelli: "Long round strands; the name means 'little worms'",
  ziti: "Long straight tubes, popular baked in Southern Italy",
  tagliatelle: "Flat egg ribbons traditional to Bologna",
  conchiglie: "Seashell-shaped pasta that scoops up sauce",
  rotini: "Tight corkscrew spirals, often sold tricolor",
  orzo: "Rice-grain-shaped pasta used in soups and salads",
  pappardelle: "Very broad flat ribbons, great with rich ragu",
  manicotti: "Large ridged tubes stuffed and baked like cannelloni",
  capellini: "'Angel hair'; among the thinnest pasta strands",
  rotelle: "Wagon-wheel shape with spokes",
  ditalini: "Tiny short tubes, 'little thimbles', used in soups",
  cavatappi: "Ridged corkscrew tubes; the name means 'corkscrew'",
  // MEDIUM
  tortelloni: "Larger version of tortellini, usually cheese-filled",
  campanelle: "Bell- or cone-shaped with a ruffled edge",
  radiatori: "Shaped like little radiators with ridged fins",
  gigli: "Cone shaped like a lily; named after Florence",
  bigoli: "Thick long strands from Veneto, like fat spaghetti",
  pici: "Thick hand-rolled strands from Tuscany",
  trenette: "Narrow flat ribbons from Liguria, classic with pesto",
  malloreddus: "Small ridged Sardinian shells, 'gnocchetti sardi'",
  stelline: "Tiny star-shaped pasta used in soups",
  fregola: "Toasted Sardinian semolina beads, like couscous",
  agnolotti: "Piedmont filled pasta pockets, often folded",
  calamarata: "Wide rings that resemble sliced squid (calamari)",
  lumaconi: "Large snail-shell shapes made for stuffing",
  gramigna: "Short curled tubes from Emilia-Romagna",
  sedanini: "Short curved ridged tubes named after celery stalks",
  pastina: "'Little pasta'; tiny shapes for soups and children",
  anelli: "Small pasta rings, popular in Sicilian dishes",
  conchiglioni: "Jumbo shells, big enough to stuff and bake",
  fideo: "Thin short noodles used in Spanish and Mexican dishes",
  maltagliati: "'Badly cut' irregular scraps of rolled pasta",
  quadrucci: "Small flat squares, usually cooked in broth",
  girandole: "Pinwheel-shaped spirals, like a small windmill",
  bavette: "Narrow flat strands, a Ligurian cousin of linguine",
  cappelletti: "'Little hats' of filled pasta, served in broth",
  tortiglioni: "Tubes with spiral ridges running around them",
  // HARD
  bucatini: "Thick spaghetti-like strands with a hole running through",
  orecchiette: "'Little ears' from Puglia, shaped by hand",
  paccheri: "Very large smooth tubes from Campania",
  trofie: "Short thin twists from Liguria, classic with pesto",
  casarecce: "Short rolled S-shaped twists from Sicily",
  strozzapreti: "Hand-rolled twists; name means 'priest stranglers'",
  gemelli: "Single strand twisted to look like two; means 'twins'",
  cavatelli: "Small hollowed shell-like shapes, often hand-made",
  garganelli: "Ridged rolled tubes from Emilia-Romagna",
  mafaldine: "Ribbon pasta with ruffled edges, also called reginette",
  busiate: "Long spiral twists from Sicily made around a rod",
  fileja: "Hand-rolled twisted strands from Calabria",
  testaroli: "Ancient Ligurian flatbread-pasta cut into diamonds",
  culurgiones: "Sardinian filled pasta sealed in a wheat-ear pleat",
  casoncelli: "Stuffed folded pasta from the Bergamo area",
  pansotti: "Ligurian triangles stuffed with herbs and cheese",
  stringozzi: "Long hand-rolled Umbrian strands, like shoelaces",
  scialatielli: "Short fresh strands from the Amalfi Coast",
  cencioni: "Flat rag-shaped pasta; name means 'little rags'",
  foglieulivo: "Shaped like olive leaves, a Puglia specialty",
  spaccatelle: "Short curved shapes split open along one side",
  chifferi: "Small curved elbow tubes, often ridged",
  creste: "'Rooster crests' with a ruffled curved ridge",
  cellentani: "Ridged corkscrew tubes, also called cavatappi",
  cappellacci: "Ferrara pasta filled with pumpkin, like big hats",
  // IMPOSSIBLE
  corzetti: "Ligurian coins stamped with decorative patterns",
  pizzoccheri: "Buckwheat ribbons from Valtellina in the Alps",
  lorighittas: "Sardinian pasta twisted into small braided rings",
  sacchettini: "Little pasta 'purses' gathered at the top and filled",
  filindeu: "'Threads of God'; rare hand-woven Sardinian pasta",
  lagane: "Ancient wide flat pasta, an ancestor of lasagne",
  maccheroncini: "Very thin long pasta from Campofilone in the Marche",
  chitarra: "Square-cut strands made on a guitar-string tool",
  sagnarelli: "Small rectangles with rippled, wavy edges",
  caramelle: "Filled pasta wrapped like a piece of candy",
  fiori: "Flower-shaped pasta with petal-like edges",
  piperigate: "Curved ridged tubes shaped like little pipes",
  mezzemaniche: "'Half sleeves'; short wide ridged tubes",
  tacconi: "Flat pasta squares or diamonds from central Italy",
  fagottini: "Little filled bundles pinched shut like a purse",
  umbricelli: "Thick hand-rolled Umbrian strands, like fat pici",
  sagneincannulate: "Ribbon pasta rolled into loose spirals, from Puglia",
  ferretto: "Pasta rolled around a thin iron rod into a tube",
  strascinati: "'Dragged' pasta pressed thin against a board",
  fusillilunghi: "Long spring-like coils, a stretched-out fusilli",
  schlutzkrapfen: "Half-moon filled pasta from South Tyrol",
  passatelli: "Thick short strands pressed from breadcrumb dough",
  capunti: "Open canoe-shaped pasta from Puglia and Basilicata",
  sorprese: "Curved hollow shell shapes; the name means 'surprises'",
  grattini: "Tiny grated pasta bits cooked in broth",
};
