// E165 phobia-emoji facts — one true <=70-char definition per phobia, shown on reveal.
export const PHOBIA_EMOJI_FACTS = {
  // EASY
  "arachnophobia": "The intense fear of spiders and other arachnids.",
  "acrophobia": "The fear of heights and high places.",
  "claustrophobia": "The fear of enclosed or confined spaces.",
  "ophidiophobia": "The fear of snakes.",
  "cynophobia": "The fear of dogs.",
  "coulrophobia": "The fear of clowns.",
  "aerophobia": "The fear of flying in airplanes.",
  "nyctophobia": "The fear of the dark or nighttime.",
  "thalassophobia": "The fear of the deep open sea or ocean.",
  "astraphobia": "The fear of thunder and lightning.",
  "hemophobia": "The fear of blood.",
  "trypanophobia": "The fear of needles and injections.",
  "pyrophobia": "The fear of fire.",
  "glossophobia": "The fear of public speaking.",
  "musophobia": "The fear of mice and rats.",
  "ailurophobia": "The fear of cats.",
  "ornithophobia": "The fear of birds.",
  "mysophobia": "The fear of germs and contamination.",
  "trypophobia": "The fear of clusters of small holes.",
  "agoraphobia": "The fear of open or crowded public places.",
  "aquaphobia": "The fear of water.",
  "emetophobia": "The fear of vomiting.",
  "phasmophobia": "The fear of ghosts.",
  "apiphobia": "The fear of bees.",
  "dentophobia": "The fear of dentists and dental work.",
  // MEDIUM
  "entomophobia": "The fear of insects.",
  "batrachophobia": "The fear of frogs and amphibians.",
  "ichthyophobia": "The fear of fish.",
  "selachophobia": "The fear of sharks.",
  "equinophobia": "The fear of horses.",
  "chiroptophobia": "The fear of bats.",
  "alektorophobia": "The fear of chickens.",
  "chionophobia": "The fear of snow.",
  "ombrophobia": "The fear of rain.",
  "nephophobia": "The fear of clouds.",
  "heliophobia": "The fear of sunlight.",
  "selenophobia": "The fear of the moon.",
  "lilapsophobia": "The fear of tornadoes and hurricanes.",
  "necrophobia": "The fear of death and dead things.",
  "taphophobia": "The fear of being buried alive.",
  "coimetrophobia": "The fear of cemeteries.",
  "gamophobia": "The fear of marriage or commitment.",
  "nomophobia": "The fear of being without a mobile phone.",
  "technophobia": "The fear of technology and computers.",
  "robophobia": "The fear of robots.",
  "chrometophobia": "The fear of money.",
  "ergophobia": "The fear of work.",
  "bibliophobia": "The fear of books.",
  "somniphobia": "The fear of sleep.",
  "ablutophobia": "The fear of bathing or washing.",
  // HARD
  "myrmecophobia": "The fear of ants.",
  "lepidopterophobia": "The fear of butterflies and moths.",
  "scoleciphobia": "The fear of worms.",
  "katsaridaphobia": "The fear of cockroaches.",
  "herpetophobia": "The fear of reptiles.",
  "pogonophobia": "The fear of beards.",
  "bovinophobia": "The fear of cattle and cows.",
  "cetaphobia": "The fear of whales.",
  "ostraconophobia": "The fear of shellfish.",
  "zoophobia": "The fear of animals in general.",
  "dendrophobia": "The fear of trees.",
  "hylophobia": "The fear of forests.",
  "anthophobia": "The fear of flowers.",
  "botanophobia": "The fear of plants.",
  "mycophobia": "The fear of mushrooms and fungi.",
  "lachanophobia": "The fear of vegetables.",
  "carnophobia": "The fear of meat.",
  "turophobia": "The fear of cheese.",
  "ovophobia": "The fear of eggs.",
  "alliumphobia": "The fear of garlic and onions.",
  "oenophobia": "The fear of wine.",
  "methyphobia": "The fear of alcohol.",
  "mageirocophobia": "The fear of cooking.",
  "cibophobia": "The fear of food and eating.",
  "fructophobia": "The fear of fruit.",
  // IMPOSSIBLE
  "bananaphobia": "The fear of bananas.",
  "lactophobia": "The fear of milk.",
  "numerophobia": "The fear of numbers.",
  "chronophobia": "The fear of time and its passing.",
  "chronomentrophobia": "The fear of clocks.",
  "catoptrophobia": "The fear of mirrors.",
  "pediophobia": "The fear of dolls.",
  "globophobia": "The fear of balloons.",
  "aichmophobia": "The fear of sharp objects.",
  "belonephobia": "The fear of pins and sharp points.",
  "chromophobia": "The fear of colors.",
  "melophobia": "The fear of music.",
  "ligyrophobia": "The fear of loud noises.",
  "cardiophobia": "The fear of heart disease or heart attacks.",
  "encephalophobia": "The fear of brain disease.",
  "osteophobia": "The fear of bones.",
  "ophthalmophobia": "The fear of being stared at.",
  "podophobia": "The fear of feet.",
  "chirophobia": "The fear of hands.",
  "genuphobia": "The fear of knees.",
  "pharmacophobia": "The fear of medicine and drugs.",
  "iatrophobia": "The fear of doctors.",
  "nosocomephobia": "The fear of hospitals.",
  "cometophobia": "The fear of comets.",
  "astrophobia": "The fear of stars and celestial space.",
};
