// E159 emoji-fictional-place facts — one <=70-char fact per place (franchise), shown on reveal.
export const PLACE_EMOJI_FACTS = {
  // EASY
  "hogwarts": "Wizarding school in J.K. Rowling's Harry Potter series.",
  "narnia": "Magic land reached via a wardrobe in C.S. Lewis's Narnia.",
  "gotham-city": "Batman's crime-ridden home city in DC Comics.",
  "mordor": "Sauron's volcanic realm in Tolkien's Lord of the Rings.",
  "atlantis": "Legendary sunken city, retold in Disney's Atlantis.",
  "wakanda": "Hidden African nation in Marvel's Black Panther.",
  "neverland": "The island where Peter Pan never grows up.",
  "emerald-city": "Capital of Oz in The Wonderful Wizard of Oz.",
  "jurassic-park": "The dinosaur theme park from Michael Crichton's story.",
  "hobbiton": "The hobbits' village in Tolkien's The Shire.",
  "springfield": "The Simpsons' hometown in the long-running cartoon.",
  "bikini-bottom": "SpongeBob SquarePants' undersea town.",
  "pandora": "The lush alien moon in James Cameron's Avatar.",
  "mushroom-kingdom": "Princess Peach's realm in Nintendo's Super Mario.",
  "jumanji": "The jungle world inside the board game Jumanji.",
  "asgard": "Home of Thor and the gods in Marvel's Asgard.",
  "krypton": "Superman's doomed home planet in DC Comics.",
  "hyrule": "The kingdom Link protects in The Legend of Zelda.",
  "wonka-factory": "Willy Wonka's factory in Roald Dahl's tale.",
  "bedrock": "The Stone Age town of The Flintstones.",
  "duckburg": "Scrooge McDuck's city in Disney's DuckTales.",
  "wonderland": "The dream world Alice falls into via a rabbit hole.",
  "land-of-oz": "The magical land Dorothy visits in The Wizard of Oz.",
  "the-matrix": "The simulated reality in the film The Matrix.",
  "whoville": "The tiny town of the Whos in Dr. Seuss's stories.",

  // MEDIUM
  "westeros": "The continent of the Iron Throne in Game of Thrones.",
  "rivendell": "Elrond's elven refuge in Tolkien's Middle-earth.",
  "metropolis": "The city Superman defends in DC Comics.",
  "mount-olympus": "Home of the Greek gods in myth and Disney's Hercules.",
  "camelot": "King Arthur's legendary castle and court.",
  "the-shire": "The peaceful hobbit homeland in Lord of the Rings.",
  "south-park": "The Colorado mountain town of the cartoon South Park.",
  "toontown": "Where cartoons live in Who Framed Roger Rabbit.",
  "el-dorado": "The mythical city of gold in The Road to El Dorado.",
  "shangri-la": "The hidden paradise from the novel Lost Horizon.",
  "the-upside-down": "The dark parallel world in Stranger Things.",
  "pride-rock": "Simba's home landmark in Disney's The Lion King.",
  "death-star": "The Empire's moon-sized battle station in Star Wars.",
  "tatooine": "Luke Skywalker's twin-sun desert planet in Star Wars.",
  "the-nether": "The fiery underworld dimension in Minecraft.",
  "diagon-alley": "The wizard shopping street in Harry Potter.",
  "castle-grayskull": "The fortress of power in He-Man's Masters of the Universe.",
  "halloween-town": "Jack's home in The Nightmare Before Christmas.",
  "arendelle": "Elsa and Anna's frozen kingdom in Disney's Frozen.",
  "shrek-swamp": "The ogre's boggy home in DreamWorks' Shrek.",
  "zootopia": "The mammal metropolis in Disney's Zootopia.",
  "monstropolis": "The monsters' city powered by scares in Monsters, Inc.",
  "radiator-springs": "The Route 66 town in Pixar's Cars.",
  "agrabah": "The desert city of Aladdin in Disney's film.",
  "gravity-falls": "The mysterious Oregon town of the cartoon Gravity Falls.",

  // HARD
  "rohan": "The realm of horse-lords in Tolkien's Lord of the Rings.",
  "dagobah": "The swamp planet where Yoda hides in Star Wars.",
  "mos-eisley": "The cantina spaceport town in Star Wars.",
  "raccoon-city": "The zombie-outbreak city in the Resident Evil games.",
  "silent-hill": "The fog-shrouded town of the Silent Hill horror games.",
  "los-santos": "The sprawling city of Grand Theft Auto V.",
  "hill-valley": "The DeLorean's hometown in Back to the Future.",
  "the-overlook-hotel": "The haunted hotel in Stephen King's The Shining.",
  "kings-landing": "The Iron Throne's capital in Game of Thrones.",
  "winterfell": "House Stark's northern castle in Game of Thrones.",
  "hogsmeade": "The all-wizard village near Hogwarts in Harry Potter.",
  "the-thunderdome": "The gladiator arena in Mad Max Beyond Thunderdome.",
  "isla-nublar": "The island housing the park in Jurassic Park.",
  "skull-island": "The prehistoric home of King Kong.",
  "castle-dracula": "The vampire count's Transylvanian castle in Dracula.",
  "the-underworld": "Hades' realm of the dead in Greek myth.",
  "wall-maria": "The outermost giant wall in Attack on Titan.",
  "amity-island": "The shark-plagued beach town in Jaws.",
  "hundred-acre-wood": "The forest home of Winnie the Pooh.",
  "stars-hollow": "The cozy Connecticut town in Gilmore Girls.",
  "twin-peaks": "The eerie logging town in the show Twin Peaks.",
  "panem": "The dystopian nation of The Hunger Games.",
  "mystic-falls": "The vampire-filled town in The Vampire Diaries.",
  "derry": "The Maine town haunted by Pennywise in Stephen King's It.",
  "the-grid": "The digital world inside the computer in Tron.",

  // IMPOSSIBLE
  "ankh-morpork": "The great city of Terry Pratchett's Discworld.",
  "gormenghast": "The vast crumbling castle in Mervyn Peake's novels.",
  "earthsea": "The wizard archipelago in Ursula K. Le Guin's books.",
  "lankhmar": "The city of thieves in Fritz Leiber's fantasy tales.",
  "hyboria": "The ancient world of Robert E. Howard's Conan.",
  "the-culture": "The spacefaring utopia of Iain M. Banks's novels.",
  "trantor": "The Empire's capital planet in Asimov's Foundation.",
  "arrakis": "The desert spice planet of Frank Herbert's Dune.",
  "gilead": "Roland's fallen homeland in King's The Dark Tower.",
  "fillory": "The magical land in Lev Grossman's The Magicians.",
  "prydain": "The Welsh-inspired land of Lloyd Alexander's chronicles.",
  "pern": "The dragonrider world of Anne McCaffrey's novels.",
  "redwall": "The mouse abbey in Brian Jacques's Redwall series.",
  "lilliput": "The land of tiny people in Gulliver's Travels.",
  "brobdingnag": "The land of giants in Gulliver's Travels.",
  "solaris": "The sentient ocean planet in Stanislaw Lem's novel.",
  "vulcan": "Spock's desert home planet in Star Trek.",
  "endor": "The Ewoks' forest moon in Return of the Jedi.",
  "klendathu": "The bugs' homeworld in Starship Troopers.",
  "lv-426": "The moon where the eggs are found in Alien.",
  "rlyeh": "The sunken city of Cthulhu in Lovecraft's tales.",
  "barsoom": "The name for Mars in Burroughs's John Carter stories.",
  "oa": "Home planet of the Green Lantern Corps in DC Comics.",
  "gallifrey": "Home planet of the Time Lords in Doctor Who.",
  "cybertron": "The robotic home planet of the Transformers.",
};
