// «Guess the Primate» — GuessSync · E59 · did-you-know facts, ≤70 chars, verified true.
export const PRIMATE_FACTS = {
  // EASY
  "chimpanzee": "Our closest living relative; shares ~98% of our DNA",
  "gorilla": "The largest living primate; a big male can top 180 kg",
  "orangutan": "Asia's great ape; its name means 'person of the forest'",
  "baboon": "Ground-dwelling monkey that lives in large noisy troops",
  "mandrill": "The world's largest monkey, with a rainbow-colored face",
  "ringtailedlemur": "Madagascar lemur famous for its black-and-white ringed tail",
  "gibbon": "A small tree ape that swings arm-over-arm through canopy",
  "rhesusmacaque": "Widely studied monkey; the Rh blood factor is named for it",
  "capuchin": "Clever New World monkey known for using stone tools",
  "spidermonkey": "Uses its long prehensile tail like a fifth limb",
  "marmoset": "A tiny New World monkey that gnaws bark to feed on gum",
  "howlermonkey": "Its dawn roar carries for miles, among the loudest of animals",
  "proboscismonkey": "Borneo monkey; males grow a huge pendulous nose",
  "tarsier": "Tiny nocturnal primate with eyes bigger than its brain",
  "bonobo": "Great ape known for peaceful, female-led societies",
  "japanesemacaque": "The 'snow monkey' bathes in steaming hot springs",
  "squirrelmonkey": "Small, agile monkey that travels in troops of dozens",
  "vervetmonkey": "Uses distinct alarm calls for eagles, snakes and leopards",
  "goldenliontamarin": "A bright orange monkey saved from the edge of extinction",
  "gelada": "Ethiopian grazer with a bare red 'bleeding heart' chest",
  "colobus": "Leaf-eating monkey with a flowing black-and-white cape",
  "slowloris": "The only venomous primate; its bite can cause a nasty wound",
  "barbarymacaque": "Europe's only wild monkey, living on the Rock of Gibraltar",
  "emperortamarin": "Tiny monkey named for its long white mustache",
  "graylangur": "Sacred Hindu monkey linked to the god Hanuman",
  // MEDIUM
  "siamang": "Largest gibbon; inflates a throat sac to boom loudly",
  "patasmonkey": "The fastest primate, sprinting up to 55 km/h on the ground",
  "debrazzamonkey": "Guenon with a white beard and orange brow crescent",
  "crabeatingmacaque": "Also called the long-tailed macaque; swims and forages in water",
  "pigtailedmacaque": "Trained in Asia to climb palms and pick coconuts",
  "liontailedmacaque": "Rare Indian monkey with a silver mane and tufted tail",
  "bonnetmacaque": "South Indian monkey with a whorled cap of head hair",
  "chacmababoon": "One of the largest monkeys, native to southern Africa",
  "hamadryasbaboon": "Sacred to ancient Egyptians; males grow a silver cape",
  "drill": "A stocky forest relative of the mandrill from West Africa",
  "cottontoptamarin": "Tiny monkey crowned with a shock of white hair",
  "pygmymarmoset": "The world's smallest monkey, light enough to sit on a finger",
  "woollymonkey": "Sturdy Amazon monkey with dense woolly fur and a gripping tail",
  "whitefacedsaki": "Males wear a pale face mask against black fur",
  "nightmonkey": "The only truly nocturnal monkey, with huge round eyes",
  "titimonkey": "Mated pairs bond for life and twine their tails together",
  "redruffedlemur": "Rust-red Madagascar lemur that pollinates flowers as it feeds",
  "ruffedlemur": "Noisy Madagascar lemur with a striking black-and-white coat",
  "mouselemur": "Among the smallest primates, fitting in the palm of a hand",
  "brownlemur": "Madagascar lemur active by both day and night",
  "goldensnubnosed": "Lives in snowy Chinese forests; golden fur and a blue face",
  "duskyleaf": "Leaf monkey with white eye-rings like a pair of spectacles",
  "sootymangabey": "West African monkey that forages on the forest floor",
  "whitecheekedgibbon": "Males turn black, females golden; pairs duet at dawn",
  "bluemonkey": "Forest guenon that is more olive-gray than truly blue",
  // HARD
  "coquerelssifaka": "Madagascar lemur that 'dances' sideways across open ground",
  "verreauxsifaka": "White sifaka that bounds upright on two legs over the ground",
  "crownedlemur": "Northern Madagascar lemur with a V-shaped orange crown",
  "redbelliedlemur": "Forms devoted pairs; males have a teardrop eye patch",
  "blacklemur": "Only males are black; females are rich reddish-brown",
  "bamboolemur": "Eats bamboo laced with cyanide that would kill other animals",
  "sportivelemur": "Nocturnal lemur that leaps between vertical trunks",
  "dwarflemur": "The only primate known to hibernate for months at a time",
  "greatergalago": "Nocturnal African bushbaby with a loud wailing cry",
  "pygmyslowloris": "Tiny venomous loris that slows right down in cold weather",
  "slenderloris": "Big-eyed nocturnal primate with very thin twig-like limbs",
  "potto": "Slow-moving African primate with a bony spine shield on its neck",
  "spectraltarsier": "Sulawesi tarsier that sings duets to defend its territory",
  "blacksnubnosed": "Lives higher in the mountains than almost any other primate",
  "francoislangur": "Black leaf monkey with white sideburns, born bright orange",
  "purplefacedlangur": "Sri Lankan leaf monkey with white whiskers on a dark face",
  "nilgirilangur": "Glossy black langur from the hills of southern India",
  "silveredlangur": "Silver-tipped leaf monkey whose babies are bright orange",
  "cappedlangur": "Leaf monkey with a neat dark cap over golden underparts",
  "goldenlangur": "Rare golden monkey from the Himalayan foothills of Assam",
  "graycheekedmangabey": "Dark forest monkey with a shaggy mantle and gray cheeks",
  "redcappedmangabey": "West African monkey with a chestnut cap and white eyelids",
  "moustachedguenon": "Small guenon with a bright blue face and white mustache",
  "monamonkey": "Colorful West African guenon with a dark stripe by each eye",
  "dianamonkey": "Sleek black guenon with a white throat and crescent brow",
  // IMPOSSIBLE
  "ayeaye": "Nocturnal lemur that taps wood and gnaws grubs with a thin finger",
  "indri": "The largest living lemur; sings eerie whale-like songs",
  "redshankeddouc": "Vibrant monkey with maroon 'stockings' on its lower legs",
  "uakari": "Amazon monkey with a bald bright-red face and short tail",
  "tonkinsnubnosed": "One of the rarest primates, with pink lips and blue face",
  "kipunji": "African monkey new to science, first described in 2005",
  "angwantibo": "Tiny nocturnal 'golden potto' loris of Central Africa",
  "pygmytarsier": "Thought extinct until it was rediscovered alive in 2008",
  "muriqui": "Brazil's largest monkey, also called the woolly spider monkey",
  "goldenheadedtamarin": "Black tamarin with a golden mane, found only in Brazil",
  "piedtamarin": "Amazon tamarin with a bare black face and white forequarters",
  "geoffroystamarin": "Small Panama tamarin with a mottled black-and-white head",
  "silverymarmoset": "Amazon marmoset with silvery-white fur and a bare pink face",
  "goeldismonkey": "Small black Amazon monkey midway between marmoset and tamarin",
  "beardedsaki": "Amazon monkey with a bushy beard and thick bottlebrush tail",
  "hamlynsmonkey": "Owl-faced guenon with a pale stripe down its dark nose",
  "lhoestsmonkey": "Mountain guenon with a white bib that carries its tail in a hook",
  "talapoin": "The smallest African monkey, an agile swimmer near water",
  "allensswampmonkey": "African monkey with partly webbed fingers for wetland life",
  "rolowaymonkey": "Critically endangered guenon with a long white beard",
  "redcolobus": "Leaf monkey with reddish fur and a stub of a thumb",
  "simakobu": "Pig-tailed langur of Indonesia's remote Mentawai Islands",
  "mentawaimacaque": "Macaque found only on Siberut in Indonesia's Mentawai Islands",
  "celebescrestedmacaque": "Jet-black Sulawesi macaque famous for a self-taken photo",
  "diademedsifaka": "Colorful large lemur with a white brow and golden limbs",
};
