// E100 «Guess the ZOOMED Reptile» — GuessSync "What the Zoom" hard-mode.
// Reuses the EXACT E45 reptile image set (reptiles/<slug>.jpg) and E45's REPTILE_FACTS +
// rp-<slug>.wav answer VOs (copied to rz-<slug>.wav — identical "It's the <name>!" line, zero
// new audio cost), but RE-TIERED by how easy each reptile is to name from an EXTREME close-up
// crop of skin/scale/shell texture (scale 3.0). A random patch shows one skin-patch region only,
// so difficulty here tracks SCALE/SKIN pattern distinctiveness of the crop, NOT general fame:
//   EASY = unmistakable color/scale texture survives any crop (chameleon rainbow skin, beaded
//          gila monster pattern, leopard gecko spots, snake blotch patterns, etc.)
//   IMPOSSIBLE = plain/generic croc-grey or tortoise-shell texture, or an obscure species with
//          no signature crop pattern
// image: reptiles/<slug>.jpg | answer VO: sfx/rz-<slug>.wav (copied from E45's rp-<slug>.wav)
export const REPTILEZOOM = [
  // ===== EASY (25) — unmistakable color/scale pattern in any close-up patch =====
  { slug: "pantherchameleon", name: "Panther Chameleon", level: "easy" },
  { slug: "gilamonster", name: "Gila Monster", level: "easy" },
  { slug: "tokaygecko", name: "Tokay Gecko", level: "easy" },
  { slug: "leopardgecko", name: "Leopard Gecko", level: "easy" },
  { slug: "pinkiguana", name: "Pink Land Iguana", level: "easy" },
  { slug: "blueiguana", name: "Blue Iguana", level: "easy" },
  { slug: "fijiiguana", name: "Fiji Crested Iguana", level: "easy" },
  { slug: "mossygecko", name: "Mossy Leaf-tailed Gecko", level: "easy" },
  { slug: "satanicgecko", name: "Satanic Leaf-tailed Gecko", level: "easy" },
  { slug: "gargoylegecko", name: "Gargoyle Gecko", level: "easy" },
  { slug: "thornydevil", name: "Thorny Devil", level: "easy" },
  { slug: "armadillolizard", name: "Armadillo Lizard", level: "easy" },
  { slug: "ocellatedlizard", name: "Ocellated Lizard", level: "easy" },
  { slug: "cornsnake", name: "Corn Snake", level: "easy" },
  { slug: "gaboonviper", name: "Gaboon Viper", level: "easy" },
  { slug: "greenanaconda", name: "Green Anaconda", level: "easy" },
  { slug: "ballpython", name: "Ball Python", level: "easy" },
  { slug: "boaconstrictor", name: "Boa Constrictor", level: "easy" },
  { slug: "westerndiamondback", name: "Diamondback Rattlesnake", level: "easy" },
  { slug: "perentie", name: "Perentie", level: "easy" },
  { slug: "greentreemonitor", name: "Green Tree Monitor", level: "easy" },
  { slug: "mwanzaagama", name: "Mwanza Flat-headed Agama", level: "easy" },
  { slug: "veiledchameleon", name: "Veiled Chameleon", level: "easy" },
  { slug: "hornedlizard", name: "Horned Lizard", level: "easy" },
  { slug: "shingleback", name: "Shingleback Skink", level: "easy" },
  // ===== MEDIUM (25) — distinctive texture but needs a bit more of the crop to read =====
  { slug: "komododragon", name: "Komodo Dragon", level: "medium" },
  { slug: "bluetongueskink", name: "Blue-tongued Skink", level: "medium" },
  { slug: "frilledlizard", name: "Frilled Lizard", level: "medium" },
  { slug: "beardeddragon", name: "Bearded Dragon", level: "medium" },
  { slug: "webfootedgecko", name: "Web-footed Gecko", level: "medium" },
  { slug: "sandfish", name: "Sandfish Skink", level: "medium" },
  { slug: "knobtailedgecko", name: "Knob-tailed Gecko", level: "medium" },
  { slug: "caimanlizard", name: "Caiman Lizard", level: "medium" },
  { slug: "crocodilemonitor", name: "Crocodile Monitor", level: "medium" },
  { slug: "jacksonschameleon", name: "Jackson's Chameleon", level: "medium" },
  { slug: "flapneckchameleon", name: "Flap-necked Chameleon", level: "medium" },
  { slug: "chinesewaterdragon", name: "Chinese Water Dragon", level: "medium" },
  { slug: "plumedbasilisk", name: "Green Basilisk", level: "medium" },
  { slug: "sailfinlizard", name: "Sailfin Lizard", level: "medium" },
  { slug: "uromastyx", name: "Uromastyx", level: "medium" },
  { slug: "rhinocerosiguana", name: "Rhinoceros Iguana", level: "medium" },
  { slug: "kingcobra", name: "King Cobra", level: "medium" },
  { slug: "blackmamba", name: "Black Mamba", level: "medium" },
  { slug: "flyingdragon", name: "Flying Dragon", level: "medium" },
  { slug: "collaredlizard", name: "Collared Lizard", level: "medium" },
  { slug: "argentinetegu", name: "Argentine Tegu", level: "medium" },
  { slug: "desertiguana", name: "Desert Iguana", level: "medium" },
  { slug: "spinytailediguana", name: "Spiny-tailed Iguana", level: "medium" },
  { slug: "crestedgecko", name: "Crested Gecko", level: "medium" },
  { slug: "madagascardaygecko", name: "Day Gecko", level: "medium" },
  // ===== HARD (25) — generic croc/turtle skin texture, a tight crop gives little away =====
  { slug: "greeniguana", name: "Green Iguana", level: "hard" },
  { slug: "marineiguana", name: "Marine Iguana", level: "hard" },
  { slug: "saltwatercrocodile", name: "Saltwater Crocodile", level: "hard" },
  { slug: "nilecrocodile", name: "Nile Crocodile", level: "hard" },
  { slug: "americanalligator", name: "American Alligator", level: "hard" },
  { slug: "moreletcrocodile", name: "Morelet's Crocodile", level: "hard" },
  { slug: "muggercrocodile", name: "Mugger Crocodile", level: "hard" },
  { slug: "yacarecaiman", name: "Yacare Caiman", level: "hard" },
  { slug: "spectacledcaiman", name: "Spectacled Caiman", level: "hard" },
  { slug: "americancrocodile", name: "American Crocodile", level: "hard" },
  { slug: "gharial", name: "Gharial", level: "hard" },
  { slug: "savannahmonitor", name: "Savannah Monitor", level: "hard" },
  { slug: "rockmonitor", name: "Rock Monitor", level: "hard" },
  { slug: "crocodilelizard", name: "Chinese Crocodile Lizard", level: "hard" },
  { slug: "alligatorlizard", name: "Alligator Lizard", level: "hard" },
  { slug: "mexicanbeadedlizard", name: "Mexican Beaded Lizard", level: "hard" },
  { slug: "housegecko", name: "House Gecko", level: "hard" },
  { slug: "redearedslider", name: "Red-eared Slider", level: "hard" },
  { slug: "paintedturtle", name: "Painted Turtle", level: "hard" },
  { slug: "snappingturtle", name: "Snapping Turtle", level: "hard" },
  { slug: "leatherbackturtle", name: "Leatherback Turtle", level: "hard" },
  { slug: "matamata", name: "Mata Mata", level: "hard" },
  { slug: "hawksbillturtle", name: "Hawksbill Turtle", level: "hard" },
  { slug: "chuckwalla", name: "Chuckwalla", level: "hard" },
  { slug: "earlessmonitor", name: "Earless Monitor Lizard", level: "hard" },
  // ===== IMPOSSIBLE (25) — obscure species / no signature crop texture =====
  { slug: "loggerheadturtle", name: "Loggerhead Turtle", level: "impossible" },
  { slug: "aldabratortoise", name: "Aldabra Tortoise", level: "impossible" },
  { slug: "leopardtortoise", name: "Leopard Tortoise", level: "impossible" },
  { slug: "russiantortoise", name: "Russian Tortoise", level: "impossible" },
  { slug: "greenseaturtle", name: "Green Sea Turtle", level: "impossible" },
  { slug: "galapagostortoise", name: "Galápagos Tortoise", level: "impossible" },
  { slug: "easternboxturtle", name: "Box Turtle", level: "impossible" },
  { slug: "glasslizard", name: "Glass Lizard", level: "impossible" },
  { slug: "sheltopusik", name: "Sheltopusik", level: "impossible" },
  { slug: "parsonschameleon", name: "Parson's Chameleon", level: "impossible" },
  { slug: "alligatorsnappingturtle", name: "Alligator Snapping Turtle", level: "impossible" },
  { slug: "africanspurredtortoise", name: "African Spurred Tortoise", level: "impossible" },
  { slug: "radiatedtortoise", name: "Radiated Tortoise", level: "impossible" },
  { slug: "hermanntortoise", name: "Hermann's Tortoise", level: "impossible" },
  { slug: "flyinggecko", name: "Flying Gecko", level: "impossible" },
  { slug: "brookesia", name: "Pygmy Leaf Chameleon", level: "impossible" },
  { slug: "labordschameleon", name: "Labord's Chameleon", level: "impossible" },
  { slug: "bigheadedturtle", name: "Big-headed Turtle", level: "impossible" },
  { slug: "pignoseturtle", name: "Pig-nosed Turtle", level: "impossible" },
  { slug: "spinyturtle", name: "Spiny Turtle", level: "impossible" },
  { slug: "ploughsharetortoise", name: "Ploughshare Tortoise", level: "impossible" },
  { slug: "pancaketortoise", name: "Pancake Tortoise", level: "impossible" },
  { slug: "egyptiantortoise", name: "Egyptian Tortoise", level: "impossible" },
  { slug: "landiguana", name: "Land Iguana", level: "impossible" },
  { slug: "tuatara", name: "Tuatara", level: "impossible" },
];
