// «Guess the Reptile» — GuessSync · E45 · did-you-know facts, ≤70 chars, verified true.
export const REPTILE_FACTS = {
  // EASY
  "greeniguana": "Has a 'third eye' on its head that senses light and shadow",
  "komododragon": "World's largest lizard; can grow over 3 metres long",
  "veiledchameleon": "Its tongue can shoot out longer than its whole body",
  "greenseaturtle": "Can hold its breath and sleep underwater for hours",
  "nilecrocodile": "Africa's largest croc; has one of the strongest bites",
  "americanalligator": "Males bellow so hard the water 'dances' above their back",
  "leopardgecko": "Unlike most geckos, it has movable eyelids and can blink",
  "beardeddragon": "Puffs out a spiky black 'beard' when it feels threatened",
  "gilamonster": "One of the few venomous lizards in the world",
  "galapagostortoise": "Can live over 100 years and weigh 250 kilograms",
  "pantherchameleon": "Males flash bright blue, red and green colours",
  "saltwatercrocodile": "The largest living reptile; can swim far out to sea",
  "marineiguana": "The only lizard that forages in the sea for algae",
  "tokaygecko": "Named for its loud 'to-kay' call heard at night",
  "redearedslider": "Named for the red stripe behind each of its eyes",
  "frilledlizard": "Flares a wide neck frill and runs on two legs to flee",
  "hornedlizard": "Some species squirt blood from their eyes at predators",
  "bluetongueskink": "Flashes a bright blue tongue to startle attackers",
  "leatherbackturtle": "The largest turtle; its shell is leathery, not hard",
  "snappingturtle": "Has powerful jaws and a long, dinosaur-like tail",
  "housegecko": "Sticky toe pads let it walk upside down on ceilings",
  "kingcobra": "The longest venomous snake; it can 'stand' up tall",
  "ballpython": "Curls into a tight ball when it feels scared",
  "greenanaconda": "One of the heaviest snakes; squeezes prey to subdue it",
  "easternboxturtle": "Its hinged shell closes fully like a box for safety",

  // MEDIUM
  "jacksonschameleon": "Males have three horns, like a tiny triceratops",
  "chinesewaterdragon": "Dives into water and can stay submerged to escape",
  "plumedbasilisk": "Can sprint across water on its hind legs",
  "savannahmonitor": "A stocky African monitor that eats mostly insects",
  "americancrocodile": "Lives in both fresh and salty coastal waters",
  "spectacledcaiman": "A bony ridge between its eyes looks like eyeglasses",
  "hawksbillturtle": "Its narrow beak reaches sponges inside coral reefs",
  "loggerheadturtle": "Named for its very large, powerful head and jaws",
  "aldabratortoise": "A giant tortoise from a remote Indian Ocean atoll",
  "leopardtortoise": "Its high domed shell has a bold leopard-like pattern",
  "russiantortoise": "A small tortoise that digs burrows to escape the heat",
  "crestedgecko": "Has soft eyelash-like spines and cannot regrow its tail",
  "madagascardaygecko": "Bright green and active by day, unlike most geckos",
  "uromastyx": "A spiny-tailed desert lizard that mostly eats plants",
  "argentinetegu": "A large, smart lizard that can be quite tame",
  "desertiguana": "Stays active in heat that sends other lizards hiding",
  "sailfinlizard": "Males have a tall sail on the tail and swim well",
  "thornydevil": "Grooves in its skin channel dew straight to its mouth",
  "collaredlizard": "Runs on its back legs and has two black neck bands",
  "paintedturtle": "Bright red and yellow markings edge its smooth shell",
  "boaconstrictor": "Squeezes prey and gives birth to live young",
  "cornsnake": "A gentle rat snake with a bright orange, blotched back",
  "westerndiamondback": "Rattles its tail as a warning before it strikes",
  "gharial": "Has a very long, thin snout lined with sharp teeth",
  "spinytailediguana": "One of the fastest lizards, clocked sprinting on land",

  // HARD
  "parsonschameleon": "One of the largest chameleons in the world",
  "flapneckchameleon": "Raises flaps on its neck to look bigger when scared",
  "perentie": "Australia's largest monitor lizard",
  "crocodilemonitor": "A tree-dwelling monitor with an extremely long tail",
  "rockmonitor": "A large African monitor that shelters among rocks",
  "muggercrocodile": "A broad-snouted crocodile from South Asian wetlands",
  "moreletcrocodile": "A small croc from freshwater swamps of Central America",
  "yacarecaiman": "Lives in huge numbers across South American wetlands",
  "matamata": "Its flat, leafy head and neck help it ambush fish",
  "alligatorsnappingturtle": "Wiggles a worm-like tongue lure to catch fish",
  "africanspurredtortoise": "The largest mainland tortoise; digs deep burrows",
  "radiatedtortoise": "Its shell has a striking star-burst yellow pattern",
  "hermanntortoise": "A small tortoise native to southern Europe",
  "satanicgecko": "Its flat, notched tail mimics a dead, curled leaf",
  "gargoylegecko": "Bumpy head knobs give it a little gargoyle look",
  "flyinggecko": "Skin flaps let it glide between trees in the forest",
  "armadillolizard": "Bites its tail and rolls up like a tiny armadillo",
  "rhinocerosiguana": "Named for horn-like bumps on its snout",
  "fijiiguana": "A rare green iguana found only on Fiji's islands",
  "chuckwalla": "Wedges into rock cracks and puffs up to hide",
  "caimanlizard": "Crushes snails with strong jaws and blunt teeth",
  "greentreemonitor": "A slender emerald monitor that lives up in trees",
  "gaboonviper": "Has the longest fangs of any venomous snake",
  "blackmamba": "One of the fastest snakes; the mouth is inky black",
  "flyingdragon": "Spreads rib 'wings' to glide from tree to tree",

  // IMPOSSIBLE
  "brookesia": "Among the tiniest reptiles; fits on a fingertip",
  "labordschameleon": "May have the shortest lifespan of any land vertebrate",
  "shingleback": "A stumpy-tailed skink that mates with the same partner",
  "pinkiguana": "A pink iguana found only on one Galápagos volcano",
  "blueiguana": "A rare turquoise iguana from Grand Cayman island",
  "webfootedgecko": "Webbed feet act like snowshoes on desert sand",
  "mossygecko": "Fringed skin blends perfectly against mossy bark",
  "bigheadedturtle": "Its head is so big it cannot pull it into its shell",
  "pignoseturtle": "Has flipper-like limbs and a soft, pig-like snout",
  "spinyturtle": "Spiky shell edges make it look like a small cog",
  "ploughsharetortoise": "One of the rarest tortoises; a gold, high-domed shell",
  "pancaketortoise": "Has a flat, flexible shell for hiding in rock cracks",
  "egyptiantortoise": "One of the smallest tortoises; critically endangered",
  "landiguana": "A yellow Galápagos iguana that eats cactus pads",
  "earlessmonitor": "A rare Borneo lizard, cousin to true monitors",
  "crocodilelizard": "Bony ridges on its tail look like a small crocodile",
  "mwanzaagama": "Bright blue and red, like a real-life Spider-Man",
  "ocellatedlizard": "Europe's largest wall lizard, dotted with blue eye-spots",
  "glasslizard": "A legless lizard whose tail snaps off like glass",
  "sheltopusik": "A large legless lizard often mistaken for a snake",
  "mexicanbeadedlizard": "A venomous lizard with bead-like scales",
  "alligatorlizard": "Stiff-bodied lizard with a fold along each side",
  "sandfish": "A skink that 'swims' through loose desert sand",
  "tuatara": "Not a lizard; the last of an ancient reptile order",
  "knobtailedgecko": "Has a tiny knob on the tip of its short tail",
};
