// «Guess the Reptile 2» — GuessSync · REPTILES2 · 100 reptiles (25/tier) · real photos from Wikimedia Commons
// Non-snake led (lizards, turtles/tortoises, crocodilians, monitors, geckos, chameleons, skinks, iguanas).
// Distinct set from E45 (reptilesData.js) and E23 snakes (snakesData.js) — unique slug AND name vs both.
// Absolute difficulty by global recognizability: easy → impossible.
export const REPTILES2 = [
  // ===== EASY (25) =====
  { slug: "asianwatermonitor", name: "Asian Water Monitor", level: "easy" },
  { slug: "nilemonitor", name: "Nile Monitor", level: "easy" },
  { slug: "chinesealligator", name: "Chinese Alligator", level: "easy" },
  { slug: "cubancrocodile", name: "Cuban Crocodile", level: "easy" },
  { slug: "greenanole", name: "Green Anole", level: "easy" },
  { slug: "commonchameleon", name: "Common Chameleon", level: "easy" },
  { slug: "giantdaygecko", name: "Giant Day Gecko", level: "easy" },
  { slug: "indianstartortoise", name: "Indian Star Tortoise", level: "easy" },
  { slug: "redfootedtortoise", name: "Red-footed Tortoise", level: "easy" },
  { slug: "diamondbackterrapin", name: "Diamondback Terrapin", level: "easy" },
  { slug: "softshellturtle", name: "Softshell Turtle", level: "easy" },
  { slug: "muskturtle", name: "Musk Turtle", level: "easy" },
  { slug: "blackcaiman", name: "Black Caiman", level: "easy" },
  { slug: "siamesecrocodile", name: "Siamese Crocodile", level: "easy" },
  { slug: "dwarfcrocodile", name: "Dwarf Crocodile", level: "easy" },
  { slug: "bengalmonitor", name: "Bengal Monitor", level: "easy" },
  { slug: "fireskink", name: "Fire Skink", level: "easy" },
  { slug: "namaquachameleon", name: "Namaqua Chameleon", level: "easy" },
  { slug: "bluetreemonitor", name: "Blue Tree Monitor", level: "easy" },
  { slug: "lacemonitor", name: "Lace Monitor", level: "easy" },
  { slug: "brownanole", name: "Brown Anole", level: "easy" },
  { slug: "yellowfoottortoise", name: "Yellow-foot Tortoise", level: "easy" },
  { slug: "fattailedgecko", name: "Fat-tailed Gecko", level: "easy" },
  { slug: "goldengecko", name: "Golden Gecko", level: "easy" },
  { slug: "walllizard", name: "Wall Lizard", level: "easy" },

  // ===== MEDIUM (25) =====
  { slug: "cuvierdwarfcaiman", name: "Cuvier's Dwarf Caiman", level: "medium" },
  { slug: "broadsnoutcaiman", name: "Broad-snout Caiman", level: "medium" },
  { slug: "orinococrocodile", name: "Orinoco Crocodile", level: "medium" },
  { slug: "philippinecrocodile", name: "Philippine Crocodile", level: "medium" },
  { slug: "freshwatercrocodile", name: "Freshwater Crocodile", level: "medium" },
  { slug: "reevesturtle", name: "Reeves's Turtle", level: "medium" },
  { slug: "europeanpondturtle", name: "European Pond Turtle", level: "medium" },
  { slug: "mapturtle", name: "Map Turtle", level: "medium" },
  { slug: "woodturtle", name: "Wood Turtle", level: "medium" },
  { slug: "spottedturtle", name: "Spotted Turtle", level: "medium" },
  { slug: "bogturtle", name: "Bog Turtle", level: "medium" },
  { slug: "marginatedtortoise", name: "Marginated Tortoise", level: "medium" },
  { slug: "spidertortoise", name: "Spider Tortoise", level: "medium" },
  { slug: "gophertortoise", name: "Gopher Tortoise", level: "medium" },
  { slug: "deserttortoise", name: "Desert Tortoise", level: "medium" },
  { slug: "oustaletschameleon", name: "Oustalet's Chameleon", level: "medium" },
  { slug: "carpetchameleon", name: "Carpet Chameleon", level: "medium" },
  { slug: "mellerschameleon", name: "Meller's Chameleon", level: "medium" },
  { slug: "newcaledoniangecko", name: "New Caledonian Gecko", level: "medium" },
  { slug: "moorishgecko", name: "Moorish Gecko", level: "medium" },
  { slug: "standingsdaygecko", name: "Standing's Day Gecko", level: "medium" },
  { slug: "electricbluegecko", name: "Electric Blue Gecko", level: "medium" },
  { slug: "fivelinedskink", name: "Five-lined Skink", level: "medium" },
  { slug: "prehensileskink", name: "Prehensile Skink", level: "medium" },
  { slug: "berberskink", name: "Berber Skink", level: "medium" },

  // ===== HARD (25) =====
  { slug: "anegadaiguana", name: "Anegada Iguana", level: "hard" },
  { slug: "cubanrockiguana", name: "Cuban Rock Iguana", level: "hard" },
  { slug: "antilleaniguana", name: "Antillean Iguana", level: "hard" },
  { slug: "utilaiguana", name: "Utila Iguana", level: "hard" },
  { slug: "crocodileskink", name: "Crocodile Skink", level: "hard" },
  { slug: "sandskink", name: "Sand Skink", level: "hard" },
  { slug: "chahouagecko", name: "Chahoua Gecko", level: "hard" },
  { slug: "bandedgecko", name: "Banded Gecko", level: "hard" },
  { slug: "wondergecko", name: "Wonder Gecko", level: "hard" },
  { slug: "reticulatedgecko", name: "Reticulated Gecko", level: "hard" },
  { slug: "angleheadlizard", name: "Anglehead Lizard", level: "hard" },
  { slug: "greencrestedlizard", name: "Green Crested Lizard", level: "hard" },
  { slug: "malleedragon", name: "Mallee Dragon", level: "hard" },
  { slug: "brownbasilisk", name: "Brown Basilisk", level: "hard" },
  { slug: "flatbackturtle", name: "Flatback Turtle", level: "hard" },
  { slug: "kempsridleyturtle", name: "Kemp's Ridley Turtle", level: "hard" },
  { slug: "oliveridleyturtle", name: "Olive Ridley Turtle", level: "hard" },
  { slug: "rotisnakeneckturtle", name: "Roti Snake-neck Turtle", level: "hard" },
  { slug: "chickenturtle", name: "Chicken Turtle", level: "hard" },
  { slug: "cooterturtle", name: "Cooter Turtle", level: "hard" },
  { slug: "newguineacrocodile", name: "New Guinea Crocodile", level: "hard" },
  { slug: "schneiderscaiman", name: "Schneider's Caiman", level: "hard" },
  { slug: "rankinsdragon", name: "Rankin's Dragon", level: "hard" },
  { slug: "sungazerlizard", name: "Sungazer Lizard", level: "hard" },
  { slug: "capegirdledlizard", name: "Cape Girdled Lizard", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { slug: "burmesestartortoise", name: "Burmese Star Tortoise", level: "impossible" },
  { slug: "speckledtortoise", name: "Speckled Tortoise", level: "impossible" },
  { slug: "roundislandgecko", name: "Round Island Gecko", level: "impossible" },
  { slug: "henkelsleafgecko", name: "Henkel's Leaf Gecko", level: "impossible" },
  { slug: "rainbowagama", name: "Rainbow Agama", level: "impossible" },
  { slug: "petersbandedskink", name: "Peter's Banded Skink", level: "impossible" },
  { slug: "galapagoslavalizard", name: "Galapagos Lava Lizard", level: "impossible" },
  { slug: "turniptailedgecko", name: "Turnip-tailed Gecko", level: "impossible" },
  { slug: "flattailedgecko", name: "Flat-tailed Gecko", level: "impossible" },
  { slug: "barkinggecko", name: "Barking Gecko", level: "impossible" },
  { slug: "capedwarfgecko", name: "Cape Dwarf Gecko", level: "impossible" },
  { slug: "peninsuladaygecko", name: "Peninsula Day Gecko", level: "impossible" },
  { slug: "keeledskink", name: "Keeled Skink", level: "impossible" },
  { slug: "broadheadedskink", name: "Broad-headed Skink", level: "impossible" },
  { slug: "greatplainsskink", name: "Great Plains Skink", level: "impossible" },
  { slug: "coalskink", name: "Coal Skink", level: "impossible" },
  { slug: "africanstripedskink", name: "African Striped Skink", level: "impossible" },
  { slug: "egyptianspinylizard", name: "Egyptian Spiny Lizard", level: "impossible" },
  { slug: "hicateeriverturtle", name: "Hicatee River Turtle", level: "impossible" },
  { slug: "cantorsgiantturtle", name: "Cantor's Giant Turtle", level: "impossible" },
  { slug: "taricayaturtle", name: "Taricaya Turtle", level: "impossible" },
  { slug: "arrauturtle", name: "Arrau Turtle", level: "impossible" },
  { slug: "falsegharial", name: "False Gharial", level: "impossible" },
  { slug: "yangtzesoftshell", name: "Yangtze Softshell", level: "impossible" },
  { slug: "aldabradaygecko", name: "Aldabra Day Gecko", level: "impossible" },
];

export const REPTILES2_LEVELS = ["easy", "medium", "hard", "impossible"];
