// «Guess the Country by its Reversed Name» — GuessSync E119 · 100 countries (25/tier)
// Pure TEXT clue: the country name spelled fully backwards (uppercase, whole string reversed incl. spaces).
// Tiered by fame + length + how recognizable the reversal is (matches E115/E116 country pool/tiers).
// Answer VO rev-<slug>.wav = "It's <name>!"
export const REVERSED = [
  // EASY (25)
  { slug: "france", name: "France", reversed: "ECNARF", level: "easy" },
  { slug: "japan", name: "Japan", reversed: "NAPAJ", level: "easy" },
  { slug: "spain", name: "Spain", reversed: "NIAPS", level: "easy" },
  { slug: "italy", name: "Italy", reversed: "YLATI", level: "easy" },
  { slug: "china", name: "China", reversed: "ANIHC", level: "easy" },
  { slug: "india", name: "India", reversed: "AIDNI", level: "easy" },
  { slug: "brazil", name: "Brazil", reversed: "LIZARB", level: "easy" },
  { slug: "egypt", name: "Egypt", reversed: "TPYGE", level: "easy" },
  { slug: "mexico", name: "Mexico", reversed: "OCIXEM", level: "easy" },
  { slug: "canada", name: "Canada", reversed: "ADANAC", level: "easy" },
  { slug: "germany", name: "Germany", reversed: "YNAMREG", level: "easy" },
  { slug: "russia", name: "Russia", reversed: "AISSUR", level: "easy" },
  { slug: "greece", name: "Greece", reversed: "ECEERG", level: "easy" },
  { slug: "cuba", name: "Cuba", reversed: "ABUC", level: "easy" },
  { slug: "peru", name: "Peru", reversed: "UREP", level: "easy" },
  { slug: "kenya", name: "Kenya", reversed: "AYNEK", level: "easy" },
  { slug: "ghana", name: "Ghana", reversed: "ANAHG", level: "easy" },
  { slug: "iran", name: "Iran", reversed: "NARI", level: "easy" },
  { slug: "iraq", name: "Iraq", reversed: "QARI", level: "easy" },
  { slug: "turkey", name: "Turkey", reversed: "YEKRUT", level: "easy" },
  { slug: "poland", name: "Poland", reversed: "DNALOP", level: "easy" },
  { slug: "norway", name: "Norway", reversed: "YAWRON", level: "easy" },
  { slug: "sweden", name: "Sweden", reversed: "NEDEWS", level: "easy" },
  { slug: "ireland", name: "Ireland", reversed: "DNALERI", level: "easy" },
  { slug: "jordan", name: "Jordan", reversed: "NADROJ", level: "easy" },
  // MEDIUM (25)
  { slug: "portugal", name: "Portugal", reversed: "LAGUTROP", level: "medium" },
  { slug: "austria", name: "Austria", reversed: "AIRTSUA", level: "medium" },
  { slug: "belgium", name: "Belgium", reversed: "MUIGLEB", level: "medium" },
  { slug: "finland", name: "Finland", reversed: "DNALNIF", level: "medium" },
  { slug: "denmark", name: "Denmark", reversed: "KRAMNED", level: "medium" },
  { slug: "ukraine", name: "Ukraine", reversed: "ENIARKU", level: "medium" },
  { slug: "vietnam", name: "Vietnam", reversed: "MANTEIV", level: "medium" },
  { slug: "thailand", name: "Thailand", reversed: "DNALIAHT", level: "medium" },
  { slug: "nigeria", name: "Nigeria", reversed: "AIREGIN", level: "medium" },
  { slug: "morocco", name: "Morocco", reversed: "OCCOROM", level: "medium" },
  { slug: "ethiopia", name: "Ethiopia", reversed: "AIPOIHTE", level: "medium" },
  { slug: "colombia", name: "Colombia", reversed: "AIBMOLOC", level: "medium" },
  { slug: "pakistan", name: "Pakistan", reversed: "NATSIKAP", level: "medium" },
  { slug: "malaysia", name: "Malaysia", reversed: "AISYALAM", level: "medium" },
  { slug: "cambodia", name: "Cambodia", reversed: "AIDOBMAC", level: "medium" },
  { slug: "tanzania", name: "Tanzania", reversed: "AINAZNAT", level: "medium" },
  { slug: "zimbabwe", name: "Zimbabwe", reversed: "EWBABMIZ", level: "medium" },
  { slug: "botswana", name: "Botswana", reversed: "ANAWSTOB", level: "medium" },
  { slug: "slovakia", name: "Slovakia", reversed: "AIKAVOLS", level: "medium" },
  { slug: "slovenia", name: "Slovenia", reversed: "AINEVOLS", level: "medium" },
  { slug: "bulgaria", name: "Bulgaria", reversed: "AIRAGLUB", level: "medium" },
  { slug: "bahrain", name: "Bahrain", reversed: "NIARHAB", level: "medium" },
  { slug: "kuwait", name: "Kuwait", reversed: "TIAWUK", level: "medium" },
  { slug: "lebanon", name: "Lebanon", reversed: "NONABEL", level: "medium" },
  { slug: "mongolia", name: "Mongolia", reversed: "AILOGNOM", level: "medium" },
  // HARD (25)
  { slug: "madagascar", name: "Madagascar", reversed: "RACSAGADAM", level: "hard" },
  { slug: "mozambique", name: "Mozambique", reversed: "EUQIBMAZOM", level: "hard" },
  { slug: "cameroon", name: "Cameroon", reversed: "NOOREMAC", level: "hard" },
  { slug: "venezuela", name: "Venezuela", reversed: "ALEUZENEV", level: "hard" },
  { slug: "guatemala", name: "Guatemala", reversed: "ALAMETAUG", level: "hard" },
  { slug: "honduras", name: "Honduras", reversed: "SARUDNOH", level: "hard" },
  { slug: "nicaragua", name: "Nicaragua", reversed: "AUGARACIN", level: "hard" },
  { slug: "paraguay", name: "Paraguay", reversed: "YAUGARAP", level: "hard" },
  { slug: "uruguay", name: "Uruguay", reversed: "YAUGURU", level: "hard" },
  { slug: "suriname", name: "Suriname", reversed: "EMANIRUS", level: "hard" },
  { slug: "mauritania", name: "Mauritania", reversed: "AINATIRUAM", level: "hard" },
  { slug: "mauritius", name: "Mauritius", reversed: "SUITIRUAM", level: "hard" },
  { slug: "seychelles", name: "Seychelles", reversed: "SELLEHCYES", level: "hard" },
  { slug: "djibouti", name: "Djibouti", reversed: "ITUOBIJD", level: "hard" },
  { slug: "eritrea", name: "Eritrea", reversed: "AERTIRE", level: "hard" },
  { slug: "rwanda", name: "Rwanda", reversed: "ADNAWR", level: "hard" },
  { slug: "burundi", name: "Burundi", reversed: "IDNURUB", level: "hard" },
  { slug: "malawi", name: "Malawi", reversed: "IWALAM", level: "hard" },
  { slug: "zambia", name: "Zambia", reversed: "AIBMAZ", level: "hard" },
  { slug: "gambia", name: "Gambia", reversed: "AIBMAG", level: "hard" },
  { slug: "senegal", name: "Senegal", reversed: "LAGENES", level: "hard" },
  { slug: "guinea", name: "Guinea", reversed: "AENIUG", level: "hard" },
  { slug: "somalia", name: "Somalia", reversed: "AILAMOS", level: "hard" },
  { slug: "namibia", name: "Namibia", reversed: "AIBIMAN", level: "hard" },
  { slug: "angola", name: "Angola", reversed: "ALOGNA", level: "hard" },
  // IMPOSSIBLE (25)
  { slug: "kazakhstan", name: "Kazakhstan", reversed: "NATSHKAZAK", level: "impossible" },
  { slug: "uzbekistan", name: "Uzbekistan", reversed: "NATSIKEBZU", level: "impossible" },
  { slug: "azerbaijan", name: "Azerbaijan", reversed: "NAJIABREZA", level: "impossible" },
  { slug: "turkmenistan", name: "Turkmenistan", reversed: "NATSINEMKRUT", level: "impossible" },
  { slug: "kyrgyzstan", name: "Kyrgyzstan", reversed: "NATSZYGRYK", level: "impossible" },
  { slug: "tajikistan", name: "Tajikistan", reversed: "NATSIKIJAT", level: "impossible" },
  { slug: "liechtenstein", name: "Liechtenstein", reversed: "NIETSNETHCEIL", level: "impossible" },
  { slug: "montenegro", name: "Montenegro", reversed: "ORGENETNOM", level: "impossible" },
  { slug: "kiribati", name: "Kiribati", reversed: "ITABIRIK", level: "impossible" },
  { slug: "vanuatu", name: "Vanuatu", reversed: "UTAUNAV", level: "impossible" },
  { slug: "tuvalu", name: "Tuvalu", reversed: "ULAVUT", level: "impossible" },
  { slug: "nauru", name: "Nauru", reversed: "URUAN", level: "impossible" },
  { slug: "palau", name: "Palau", reversed: "UALAP", level: "impossible" },
  { slug: "comoros", name: "Comoros", reversed: "SOROMOC", level: "impossible" },
  { slug: "eswatini", name: "Eswatini", reversed: "INITAWSE", level: "impossible" },
  { slug: "lesotho", name: "Lesotho", reversed: "OHTOSEL", level: "impossible" },
  { slug: "moldova", name: "Moldova", reversed: "AVODLOM", level: "impossible" },
  { slug: "belarus", name: "Belarus", reversed: "SURALEB", level: "impossible" },
  { slug: "micronesia", name: "Micronesia", reversed: "AISENORCIM", level: "impossible" },
  { slug: "saint-lucia", name: "Saint Lucia", reversed: "AICUL TNIAS", level: "impossible" },
  { slug: "sao-tome-and-principe", name: "Sao Tome and Principe", reversed: "EPICNIRP DNA EMOT OAS", level: "impossible" },
  { slug: "burkina-faso", name: "Burkina Faso", reversed: "OSAF ANIKRUB", level: "impossible" },
  { slug: "equatorial-guinea", name: "Equatorial Guinea", reversed: "AENIUG LAIROTAUQE", level: "impossible" },
  { slug: "sri-lanka", name: "Sri Lanka", reversed: "AKNAL IRS", level: "impossible" },
  { slug: "bosnia-and-herzegovina", name: "Bosnia and Herzegovina", reversed: "ANIVOGEZREH DNA AINSOB", level: "impossible" },
];
