// «Guess the Rock or Mineral» — GuessSync · E66 · did-you-know facts, ≤70 chars, verified true.
export const ROCK_FACTS = {
  // EASY
  "granite": "Coarse igneous rock made of quartz, feldspar and mica",
  "marble": "Metamorphosed limestone long prized by sculptors",
  "basalt": "Dark volcanic rock that forms most of the ocean floor",
  "gold": "Soft, heavy native metal that never tarnishes",
  "limestone": "Sedimentary rock made mostly of calcium carbonate",
  "sandstone": "Sedimentary rock of cemented sand-sized grains",
  "slate": "Fine metamorphic rock that splits into flat sheets",
  "pumice": "Frothy volcanic rock so light it floats on water",
  "chalk": "Soft white limestone made of tiny marine fossils",
  "coal": "Combustible black rock formed from ancient plants",
  "flint": "Hard quartz rock once knapped into tools and sparks",
  "shale": "Sedimentary rock of hardened mud that splits thin",
  "silver": "Shiny white metal and the best natural conductor",
  "mica": "Mineral that peels into thin, shiny flexible sheets",
  "gypsum": "Soft mineral used to make plaster and drywall",
  "talc": "Softest known mineral, ground into talcum powder",
  "feldspar": "The most abundant mineral group in Earth's crust",
  "mudstone": "Sedimentary rock of hardened mud that will not split",
  "siltstone": "Sedimentary rock made of compacted silt-sized grains",
  "magnetite": "A naturally magnetic iron-oxide mineral",
  "graphite": "Soft carbon mineral used as pencil 'lead'",
  "halite": "Rock salt, the natural mineral form of table salt",
  "sulfur": "Bright yellow mineral common around volcanic vents",
  "calcite": "Common carbonate mineral that fizzes in weak acid",
  "copper": "Reddish native metal worked since ancient times",

  // MEDIUM
  "galena": "Heavy lead-grey mineral, the main ore of lead",
  "barite": "Dense barium mineral used in oil-drilling mud",
  "bauxite": "Lumpy rock that is the chief ore of aluminium",
  "breccia": "Rock of sharp angular fragments cemented together",
  "conglomerate": "Rock of rounded pebbles cemented in finer matrix",
  "quartzite": "Hard rock formed when sandstone is metamorphosed",
  "chert": "Hard, fine-grained silica rock similar to flint",
  "travertine": "Banded limestone deposited by mineral springs",
  "tuff": "Rock made of compacted volcanic ash",
  "andesite": "Volcanic rock named for the Andes mountains",
  "dolomite": "Carbonate rock rich in calcium and magnesium",
  "diorite": "Speckled black-and-white coarse igneous rock",
  "olivine": "Green mineral abundant in Earth's mantle",
  "bornite": "Copper ore that tarnishes to 'peacock' colours",
  "chalcopyrite": "Brassy copper-iron sulfide, a major copper ore",
  "cassiterite": "Dark heavy mineral, the chief ore of tin",
  "limonite": "Rusty yellow-brown iron-oxide ore mineral",
  "goethite": "Brown iron mineral and a main part of rust",
  "chromite": "Black mineral, the only ore of chromium",
  "hornblende": "Dark rock-forming mineral of the amphibole group",
  "selenite": "Clear, colourless crystal variety of gypsum",
  "aragonite": "Carbonate mineral that also builds seashells",
  "siderite": "Brown iron-carbonate mineral and minor iron ore",
  "serpentine": "Green mineral group and California's state rock",
  "augite": "Dark green-black pyroxene mineral common in lavas",

  // HARD
  "peridotite": "Dense green rock from Earth's upper mantle",
  "anorthosite": "Feldspar-rich rock also found in the Moon's crust",
  "pegmatite": "Igneous rock with exceptionally large crystals",
  "migmatite": "Swirled rock that is part-melted, part-solid",
  "phyllite": "Metamorphic rock with a silky, wavy sheen",
  "marl": "Crumbly sedimentary mix of clay and lime mud",
  "greywacke": "Dark sandstone of poorly sorted rock grains",
  "arkose": "Sandstone rich in pink feldspar grains",
  "syenite": "Coarse igneous rock like granite but quartz-poor",
  "dunite": "Green rock made almost entirely of olivine",
  "trachyte": "Fine volcanic rock rich in alkali feldspar",
  "dacite": "Volcanic rock between andesite and rhyolite",
  "scoria": "Dark bubbly volcanic rock, heavier than pumice",
  "molybdenite": "Soft silvery mineral, the main ore of molybdenum",
  "arsenopyrite": "Silvery mineral and the chief ore of arsenic",
  "wolframite": "Black heavy mineral, an important tungsten ore",
  "orpiment": "Bright orange-yellow arsenic-sulfide mineral",
  "rutile": "Reddish mineral and a major ore of titanium",
  "ilmenite": "Black iron-titanium mineral and titanium ore",
  "pyrolusite": "Sooty black mineral, the main ore of manganese",
  "zeolite": "Porous minerals used to soften and filter water",
  "actinolite": "Green amphibole mineral, often in bladed sprays",
  "muscovite": "Pale, transparent sheet variety of mica",
  "biotite": "Dark brown-black sheet variety of mica",
  "apophyllite": "Glassy crystals popular with mineral collectors",

  // IMPOSSIBLE
  "kimberlite": "Volcanic rock that carries diamonds up from depth",
  "rhyolite": "Fine volcanic rock with granite's composition",
  "gabbro": "Coarse dark igneous rock, the deep form of basalt",
  "gneiss": "Banded metamorphic rock of light and dark stripes",
  "schist": "Flaky metamorphic rock rich in shiny mica",
  "serpentinite": "Green rock formed from altered mantle minerals",
  "eclogite": "Red-and-green rock formed deep under high pressure",
  "amphibolite": "Dark metamorphic rock rich in hornblende",
  "hornfels": "Tough rock baked hard beside intruding magma",
  "blueschist": "Bluish rock formed in cold subduction zones",
  "komatiite": "Rare ancient lava that erupted extremely hot",
  "anhydrite": "Calcium sulfate mineral; gypsum without its water",
  "stibnite": "Silvery bladed mineral, the main ore of antimony",
  "realgar": "Bright red arsenic mineral that fades in light",
  "cinnabar": "Scarlet mineral and the main ore of mercury",
  "erythrite": "Crimson 'cobalt bloom' crust on cobalt ores",
  "bournonite": "Grey sulfide ore nicknamed the 'cogwheel' mineral",
  "enargite": "Dark grey-black copper-arsenic ore mineral",
  "tetrahedrite": "Grey ore named for its triangular crystal faces",
  "scheelite": "Pale tungsten mineral that glows blue under UV",
  "torbernite": "Vivid green radioactive uranium mineral",
  "autunite": "Yellow-green uranium mineral that glows under UV",
  "adamite": "Yellow-green zinc mineral that often fluoresces",
  "mimetite": "Yellow-orange lead-arsenic mineral",
  "pyromorphite": "Green, barrel-shaped lead mineral crystals",
};
