// E160 «Guess the Scientist by Emoji» — 100 scientists · 25/tier · clue via OpenMoji · VO: sfx/e160-<id>.wav
// Emoji chosen for their iconic discovery/field; single-codepoint only (no FE0F/ZWJ). Built from codepoint table.
export const SCIENTIST_EMOJI = [
  // ===== EASY =====
  { id: "einstein", title: "Albert Einstein", emojis: "🧠⚛", level: "easy" },
  { id: "newton", title: "Isaac Newton", emojis: "🍎🌍", level: "easy" },
  { id: "darwin", title: "Charles Darwin", emojis: "🐢🐒", level: "easy" },
  { id: "tesla", title: "Nikola Tesla", emojis: "⚡🗼", level: "easy" },
  { id: "curie", title: "Marie Curie", emojis: "☢🔬", level: "easy" },
  { id: "galileo", title: "Galileo Galilei", emojis: "🔭🪐", level: "easy" },
  { id: "edison", title: "Thomas Edison", emojis: "💡🔊", level: "easy" },
  { id: "archimedes", title: "Archimedes", emojis: "🛁💧", level: "easy" },
  { id: "davinci", title: "Leonardo da Vinci", emojis: "🎨🚁", level: "easy" },
  { id: "franklin-ben", title: "Benjamin Franklin", emojis: "⚡🪁", level: "easy" },
  { id: "wright", title: "The Wright Brothers", emojis: "✈👬", level: "easy" },
  { id: "fleming", title: "Alexander Fleming", emojis: "🍄💊", level: "easy" },
  { id: "copernicus", title: "Nicolaus Copernicus", emojis: "☀🌍", level: "easy" },
  { id: "pasteur", title: "Louis Pasteur", emojis: "🦠💉", level: "easy" },
  { id: "hawking", title: "Stephen Hawking", emojis: "🕳🌌", level: "easy" },
  { id: "turing", title: "Alan Turing", emojis: "💻🔢", level: "easy" },
  { id: "nobel", title: "Alfred Nobel", emojis: "💥🏅", level: "easy" },
  { id: "bell", title: "Alexander Graham Bell", emojis: "☎🔔", level: "easy" },
  { id: "mendel", title: "Gregor Mendel", emojis: "🌱🧬", level: "easy" },
  { id: "volta", title: "Alessandro Volta", emojis: "🔋⚡", level: "easy" },
  { id: "faraday", title: "Michael Faraday", emojis: "🧲⚡", level: "easy" },
  { id: "pythagoras", title: "Pythagoras", emojis: "📐➗", level: "easy" },
  { id: "goodall", title: "Jane Goodall", emojis: "🐵📓", level: "easy" },
  { id: "sagan", title: "Carl Sagan", emojis: "🌌📡", level: "easy" },
  { id: "watt", title: "James Watt", emojis: "⚙💨", level: "easy" },
  // ===== MEDIUM =====
  { id: "kepler", title: "Johannes Kepler", emojis: "🪐📐", level: "medium" },
  { id: "mendeleev", title: "Dmitri Mendeleev", emojis: "🧪📋", level: "medium" },
  { id: "pavlov", title: "Ivan Pavlov", emojis: "🐕🔔", level: "medium" },
  { id: "jenner", title: "Edward Jenner", emojis: "🐄💉", level: "medium" },
  { id: "hubble", title: "Edwin Hubble", emojis: "🔭🌌", level: "medium" },
  { id: "freud", title: "Sigmund Freud", emojis: "🛋💭", level: "medium" },
  { id: "hopper", title: "Grace Hopper", emojis: "💻🐛", level: "medium" },
  { id: "lovelace", title: "Ada Lovelace", emojis: "💻📜", level: "medium" },
  { id: "watson-crick", title: "Watson and Crick", emojis: "🧬🔬", level: "medium" },
  { id: "wegener", title: "Alfred Wegener", emojis: "🌍🧩", level: "medium" },
  { id: "carver", title: "George Washington Carver", emojis: "🥜🌱", level: "medium" },
  { id: "schrodinger", title: "Erwin Schrödinger", emojis: "🐱📦", level: "medium" },
  { id: "galvani", title: "Luigi Galvani", emojis: "🐸⚡", level: "medium" },
  { id: "maxwell", title: "James Clerk Maxwell", emojis: "🧲🌈", level: "medium" },
  { id: "nightingale", title: "Florence Nightingale", emojis: "🪔📊", level: "medium" },
  { id: "boyle", title: "Robert Boyle", emojis: "🎈🧪", level: "medium" },
  { id: "lavoisier", title: "Antoine Lavoisier", emojis: "🔥⚗", level: "medium" },
  { id: "fibonacci", title: "Fibonacci", emojis: "🐚🔢", level: "medium" },
  { id: "doppler", title: "Christian Doppler", emojis: "🚑🔊", level: "medium" },
  { id: "rontgen", title: "Wilhelm Röntgen", emojis: "🦴📷", level: "medium" },
  { id: "marconi", title: "Guglielmo Marconi", emojis: "📻🗼", level: "medium" },
  { id: "leeuwenhoek", title: "Antonie van Leeuwenhoek", emojis: "🔬🦠", level: "medium" },
  { id: "harvey", title: "William Harvey", emojis: "❤🔄", level: "medium" },
  { id: "linnaeus", title: "Carl Linnaeus", emojis: "🌿🏷", level: "medium" },
  { id: "anning", title: "Mary Anning", emojis: "🦕🏖", level: "medium" },
  // ===== HARD =====
  { id: "heisenberg", title: "Werner Heisenberg", emojis: "⚛❓", level: "hard" },
  { id: "planck", title: "Max Planck", emojis: "🌈⚛", level: "hard" },
  { id: "feynman", title: "Richard Feynman", emojis: "🥁➗", level: "hard" },
  { id: "dirac", title: "Paul Dirac", emojis: "⚛🔀", level: "hard" },
  { id: "rutherford", title: "Ernest Rutherford", emojis: "⚛🎯", level: "hard" },
  { id: "thomson", title: "J.J. Thomson", emojis: "⚛➖", level: "hard" },
  { id: "becquerel", title: "Henri Becquerel", emojis: "☢📸", level: "hard" },
  { id: "gauss", title: "Carl Friedrich Gauss", emojis: "📐🔢", level: "hard" },
  { id: "euler", title: "Leonhard Euler", emojis: "🌉➕", level: "hard" },
  { id: "babbage", title: "Charles Babbage", emojis: "⚙🔢", level: "hard" },
  { id: "dalton", title: "John Dalton", emojis: "⚛⚖", level: "hard" },
  { id: "avogadro", title: "Amedeo Avogadro", emojis: "🧪🔢", level: "hard" },
  { id: "cavendish", title: "Henry Cavendish", emojis: "⚖🌍", level: "hard" },
  { id: "hooke", title: "Robert Hooke", emojis: "🔬🧫", level: "hard" },
  { id: "koch", title: "Robert Koch", emojis: "🦠🧫", level: "hard" },
  { id: "salk", title: "Jonas Salk", emojis: "💉🛡", level: "hard" },
  { id: "mcclintock", title: "Barbara McClintock", emojis: "🌽🧬", level: "hard" },
  { id: "franklin-ros", title: "Rosalind Franklin", emojis: "🧬📷", level: "hard" },
  { id: "lister", title: "Joseph Lister", emojis: "🧼🔪", level: "hard" },
  { id: "bunsen", title: "Robert Bunsen", emojis: "🔥🧪", level: "hard" },
  { id: "kelvin", title: "Lord Kelvin", emojis: "🌡❄", level: "hard" },
  { id: "ohm", title: "Georg Ohm", emojis: "⚡📏", level: "hard" },
  { id: "hertz", title: "Heinrich Hertz", emojis: "📻〰", level: "hard" },
  { id: "joule", title: "James Joule", emojis: "🔥⚡", level: "hard" },
  { id: "bernoulli", title: "Daniel Bernoulli", emojis: "✈💨", level: "hard" },
  // ===== IMPOSSIBLE =====
  { id: "huygens", title: "Christiaan Huygens", emojis: "🪐⏰", level: "impossible" },
  { id: "pascal", title: "Blaise Pascal", emojis: "🎲💧", level: "impossible" },
  { id: "cuvier", title: "Georges Cuvier", emojis: "🦴🔍", level: "impossible" },
  { id: "lamarck", title: "Jean-Baptiste Lamarck", emojis: "🦒🌿", level: "impossible" },
  { id: "lyell", title: "Charles Lyell", emojis: "🪨⏳", level: "impossible" },
  { id: "humboldt", title: "Alexander von Humboldt", emojis: "🗺🌿", level: "impossible" },
  { id: "audubon", title: "John James Audubon", emojis: "🐦🖌", level: "impossible" },
  { id: "carson", title: "Rachel Carson", emojis: "🌿📕", level: "impossible" },
  { id: "richter", title: "Charles Richter", emojis: "📈🫨", level: "impossible" },
  { id: "vesalius", title: "Andreas Vesalius", emojis: "🦴📖", level: "impossible" },
  { id: "brahe", title: "Tycho Brahe", emojis: "🌟👃", level: "impossible" },
  { id: "herschel", title: "William Herschel", emojis: "🔭♨", level: "impossible" },
  { id: "avicenna", title: "Avicenna", emojis: "📖⚕", level: "impossible" },
  { id: "alhazen", title: "Ibn al-Haytham", emojis: "👁📷", level: "impossible" },
  { id: "alkhwarizmi", title: "Al-Khwarizmi", emojis: "🔢📖", level: "impossible" },
  { id: "khayyam", title: "Omar Khayyam", emojis: "📐📅", level: "impossible" },
  { id: "semmelweis", title: "Ignaz Semmelweis", emojis: "🧼👐", level: "impossible" },
  { id: "lind", title: "James Lind", emojis: "🍋⚓", level: "impossible" },
  { id: "banting", title: "Frederick Banting", emojis: "💉🍬", level: "impossible" },
  { id: "landsteiner", title: "Karl Landsteiner", emojis: "🩸🔤", level: "impossible" },
  { id: "morgan", title: "Thomas Hunt Morgan", emojis: "🪰🧬", level: "impossible" },
  { id: "pauling", title: "Linus Pauling", emojis: "🍊⚗", level: "impossible" },
  { id: "sanger", title: "Frederick Sanger", emojis: "🧬🔤", level: "impossible" },
  { id: "hodgkin", title: "Dorothy Hodgkin", emojis: "💎🔬", level: "impossible" },
  { id: "lorenz", title: "Konrad Lorenz", emojis: "🦆👣", level: "impossible" },
];
