// «Guess the Country by its Scrambled Name» — GuessSync E115 · did-you-know facts, <=70 chars, verified true.
export const SCRAMBLED_FACTS = {
  // EASY
  france: "It's the most-visited country in the world by tourists",
  japan: "It has over 6,800 islands, though most are uninhabited",
  spain: "It's home to the world's oldest restaurant still operating",
  italy: "It has more UNESCO World Heritage Sites than any other nation",
  china: "It has the world's largest population of any country",
  india: "It's the birthplace of chess, yoga, and the number zero",
  brazil: "It's home to about 60% of the Amazon rainforest",
  egypt: "The Great Pyramid stood as the tallest structure for 3,800 years",
  mexico: "It gave the world chocolate, corn, and chili peppers",
  canada: "It has more lakes than the rest of the world combined",
  germany: "It has over 1,500 different types of sausage",
  russia: "It's the largest country on Earth by land area",
  greece: "It's considered the birthplace of democracy",
  cuba: "It's the largest island in the Caribbean Sea",
  peru: "It's home to the ancient Inca city of Machu Picchu",
  kenya: "The Great Rift Valley runs through much of this country",
  ghana: "It was the first sub-Saharan African nation to gain independence",
  iran: "It was known as Persia until 1935",
  iraq: "Ancient Mesopotamia, the 'cradle of civilization', was here",
  turkey: "It spans two continents, Europe and Asia",
  poland: "It has one of Europe's oldest and largest primeval forests",
  norway: "It has the world's longest road tunnel, over 24 km long",
  sweden: "It has more than 267,000 islands along its coast",
  ireland: "It's nicknamed the Emerald Isle for its green landscape",
  jordan: "The ancient city of Petra is carved into rose-colored rock here",
  // MEDIUM
  portugal: "It's the oldest nation-state in Europe with fixed borders",
  austria: "It's the birthplace of composer Wolfgang Amadeus Mozart",
  belgium: "It produces around 220,000 tonnes of chocolate every year",
  finland: "It has more saunas than cars",
  denmark: "The toy brand LEGO was founded here in 1932",
  ukraine: "It's the largest country entirely within Europe",
  vietnam: "It's the world's second-largest exporter of coffee",
  thailand: "It's the only Southeast Asian nation never colonized by Europe",
  nigeria: "It's Africa's most populous country",
  morocco: "It's home to Chefchaouen, a city painted almost entirely blue",
  ethiopia: "It has its own unique calendar, about 7 years behind the West",
  colombia: "It grows more than 500 species of orchids",
  pakistan: "It's home to K2, the world's second-highest mountain",
  malaysia: "The Petronas Towers were once the world's tallest buildings",
  cambodia: "Angkor Wat here is the largest religious monument on Earth",
  tanzania: "It's home to Mount Kilimanjaro, Africa's tallest peak",
  zimbabwe: "Victoria Falls, one of the world's largest waterfalls, is here",
  botswana: "The Okavango Delta here never reaches the sea",
  slovakia: "It has the most castles per capita of any country",
  slovenia: "Over half of its territory is covered by forest",
  bulgaria: "It's one of the oldest countries in Europe, founded in 681 AD",
  bahrain: "It's made up of more than 30 islands in the Persian Gulf",
  kuwait: "It holds some of the world's largest proven oil reserves",
  lebanon: "Its cedar tree is a national symbol shown on the flag",
  mongolia: "It's the least densely populated country in the world",
  // HARD
  madagascar: "About 90% of its wildlife exists nowhere else on Earth",
  mozambique: "Its coastline stretches over 2,500 km along the Indian Ocean",
  cameroon: "It's nicknamed 'Africa in miniature' for its varied landscapes",
  venezuela: "It's home to Angel Falls, the world's tallest waterfall",
  guatemala: "It's the origin of chocolate, first used by the ancient Maya",
  honduras: "It has the second-largest barrier reef system in the world",
  nicaragua: "It's home to Lake Nicaragua, one of few lakes with sharks",
  paraguay: "It's one of only two landlocked countries in South America",
  uruguay: "It was the first country to legalize marijuana nationwide",
  suriname: "It's the smallest sovereign country in South America",
  mauritania: "The Sahara Desert covers most of its territory",
  mauritius: "The dodo bird went extinct here in the 17th century",
  seychelles: "It's made up of 115 islands in the Indian Ocean",
  djibouti: "It sits on one of the world's busiest shipping routes",
  eritrea: "Its capital Asmara is a UNESCO-listed Art Deco city",
  rwanda: "It's known as the 'land of a thousand hills'",
  burundi: "It borders Lake Tanganyika, one of the world's deepest lakes",
  malawi: "Lake Malawi holds more fish species than any other lake",
  zambia: "It shares Victoria Falls with neighboring Zimbabwe",
  gambia: "It's the smallest country on mainland Africa",
  senegal: "It's home to Lake Retba, famous for its pink-colored water",
  guinea: "It's a top global source of bauxite, used to make aluminum",
  somalia: "It has the longest coastline of any mainland African country",
  namibia: "It's home to the Namib, one of the world's oldest deserts",
  angola: "It's one of Africa's largest oil-producing nations",
  // IMPOSSIBLE
  kazakhstan: "It's the largest landlocked country in the world",
  uzbekistan: "It's one of only two doubly landlocked countries on Earth",
  azerbaijan: "It's nicknamed the 'Land of Fire' for its natural gas vents",
  turkmenistan: "The 'Door to Hell' gas crater has burned here since 1971",
  kyrgyzstan: "About 90% of its territory is covered by mountains",
  tajikistan: "The Pamir Highway, one of the world's highest roads, crosses it",
  liechtenstein: "It's one of the smallest countries, doubly landlocked in Europe",
  montenegro: "Its name means 'Black Mountain' in Italian",
  kiribati: "It's the only country located in all four hemispheres",
  vanuatu: "It's home to some of the world's most active volcanoes",
  tuvalu: "It's one of the least visited countries on Earth",
  nauru: "It's the smallest island nation in the world",
  palau: "Jellyfish Lake here is home to millions of stingless jellyfish",
  comoros: "It's known as the 'Perfume Isles' for its ylang-ylang exports",
  eswatini: "It's one of the last absolute monarchies in the world",
  lesotho: "It's the only country entirely above 1,000 meters elevation",
  moldova: "It's home to the world's largest wine cellar network",
  belarus: "About 40% of its land is covered by forest",
  micronesia: "It's made up of over 600 islands in the Pacific Ocean",
  "saint-lucia": "It's the only country named after a woman, Saint Lucy",
  "sao-tome-and-principe": "It's the second-smallest country in Africa",
  "burkina-faso": "Its name means 'land of honest people'",
  "equatorial-guinea": "It's the only African country with Spanish as an official language",
  "sri-lanka": "It was known as Ceylon until 1972",
  "bosnia-and-herzegovina": "Its capital Sarajevo hosted the 1984 Winter Olympics",
};
