// E150 emoji sea-creature facts — one verified <=70-char fact per creature, shown on reveal.
export const SEACREATURE_EMOJI_FACTS = {
  // EASY
  "octopus": "An octopus has three hearts and blue, copper-based blood.",
  "shark": "Sharks have existed for over 400 million years, before trees.",
  "dolphin": "Dolphins sleep with one half of the brain awake at a time.",
  "whale": "The blue whale is the largest animal ever known to have lived.",
  "crab": "Crabs can walk and run sideways faster than they move forward.",
  "fish": "Fish were the first animals with backbones on Earth.",
  "lobster": "Lobsters taste with their legs and chew with their stomachs.",
  "shrimp": "A shrimp's heart is located in its head.",
  "pufferfish": "A pufferfish can inflate to several times its normal size.",
  "tropical-fish": "Many reef fish can change color to blend into coral.",
  "squid": "The giant squid has the largest eyes in the animal kingdom.",
  "jellyfish": "Jellyfish have no brain, heart, bones, or blood.",
  "seal": "Seals can slow their heart rate to dive for a long time.",
  "sea-turtle": "Sea turtles can hold their breath for hours while resting.",
  "sea-otter": "Sea otters hold hands while sleeping so they don't drift apart.",
  "penguin": "Penguins are birds that cannot fly but are superb swimmers.",
  "coral": "Coral reefs are living animals, not plants or rocks.",
  "oyster": "An oyster can filter up to 50 gallons of water a day.",
  "seashell": "A seashell is the hard outer home of a soft-bodied mollusk.",
  "starfish": "A starfish can regrow an arm it has lost.",
  "seahorse": "In seahorses, the male carries and gives birth to the young.",
  "clownfish": "Clownfish are immune to the sting of their host anemone.",
  "hermit-crab": "Hermit crabs move into empty shells and swap up as they grow.",
  "sea-lion": "Sea lions can rotate their rear flippers to walk on land.",
  "orca": "Orcas are the largest members of the dolphin family.",

  // MEDIUM
  "hammerhead-shark": "A hammerhead's wide head gives it near-360-degree vision.",
  "swordfish": "A swordfish uses its long bill to slash at its prey.",
  "manta-ray": "Manta rays have the largest brains of any fish.",
  "stingray": "A stingray's barbed tail is used only for self-defense.",
  "electric-eel": "An electric eel can deliver a shock of up to 600 volts.",
  "moray-eel": "Moray eels have a second set of jaws deep in their throat.",
  "barracuda": "Barracudas can swim in short bursts up to 27 mph.",
  "anglerfish": "The anglerfish dangles a glowing lure to attract prey.",
  "catfish": "Catfish have whisker-like barbels packed with taste buds.",
  "lionfish": "The lionfish's showy fins hide venomous, defensive spines.",
  "walrus": "A walrus uses its long tusks to haul itself onto the ice.",
  "manatee": "Manatees are gentle plant-eaters called sea cows.",
  "narwhal": "A narwhal's tusk is actually a giant spiral tooth.",
  "beluga-whale": "Belugas are so vocal they're nicknamed sea canaries.",
  "cuttlefish": "Cuttlefish can change color in less than a second.",
  "nautilus": "The nautilus has drifted the seas nearly unchanged for ages.",
  "sea-urchin": "A sea urchin moves on hundreds of tiny tube feet.",
  "sand-dollar": "A sand dollar is a flat relative of the sea urchin.",
  "great-white-shark": "Great white sharks can smell a drop of blood far away.",
  "tiger-shark": "Tiger sharks are named for the dark stripes on young ones.",
  "whale-shark": "The whale shark is the largest fish in the ocean.",
  "flying-fish": "Flying fish can glide over 600 feet above the water.",
  "parrotfish": "Parrotfish make sand by grinding up and eating coral.",
  "angelfish": "Marine angelfish are famous for their bright reef colors.",
  "butterflyfish": "Many butterflyfish pair up and mate for life.",

  // HARD
  "marlin": "The marlin is one of the fastest fish in the ocean.",
  "mahi-mahi": "Mahi-mahi flash bright gold and blue when caught.",
  "tuna": "Tuna are warm-blooded and never stop swimming.",
  "salmon": "Salmon return from the sea to spawn in their home river.",
  "cod": "Cod was so vital it shaped the history of whole nations.",
  "sardine": "Sardines swim in huge schools for safety in numbers.",
  "red-herring": "Smoking a herring turns it red, giving us 'red herring'.",
  "anchovy": "Anchovies are tiny fish packed with a strong savory flavor.",
  "mackerel": "Mackerel are known for the wavy stripes on their backs.",
  "grouper": "Groupers swallow prey whole by sucking in water fast.",
  "snapper": "Red snapper can live for more than 50 years.",
  "flounder": "A flounder has both eyes on one side of its flat body.",
  "halibut": "The halibut is the largest of all the flatfish.",
  "sole": "The sole is a flatfish named for its flat, shoe-like shape.",
  "sea-cucumber": "A sea cucumber breathes through its rear end.",
  "sea-sponge": "Sea sponges are animals with no brain, heart, or nerves.",
  "sea-anemone": "The sea anemone is an animal named after a flower.",
  "sea-slug": "Sea slugs are among the most colorful animals in the sea.",
  "sea-spider": "Sea spiders breathe and digest through their long legs.",
  "horseshoe-crab": "Horseshoe crabs have blue blood used in medicine.",
  "mantis-shrimp": "A mantis shrimp punches as fast as a speeding bullet.",
  "krill": "Tiny krill are the main food of the giant blue whale.",
  "plankton": "Plankton produce over half of the oxygen we breathe.",
  "barnacle": "A barnacle glues its head to a rock and feeds with its legs.",
  "stonefish": "The stonefish is the most venomous fish in the world.",

  // IMPOSSIBLE
  "blobfish": "The blobfish looks like jelly only out of deep-sea pressure.",
  "leafy-seadragon": "The leafy seadragon is camouflaged to look like seaweed.",
  "weedy-seadragon": "The weedy seadragon drifts like a floating piece of weed.",
  "coelacanth": "The coelacanth was thought extinct for 65 million years.",
  "dugong": "The dugong is a sea cow that likely inspired mermaid tales.",
  "oarfish": "The oarfish is the longest bony fish, reaching 36 feet.",
  "sunfish": "The ocean sunfish is the heaviest bony fish alive.",
  "hagfish": "A hagfish oozes slime to choke and repel its attackers.",
  "lamprey": "The lamprey has a round mouth ringed with rows of teeth.",
  "wolffish": "The wolffish crushes shellfish with its fang-like teeth.",
  "scorpionfish": "The scorpionfish hides in plain sight with venomous spines.",
  "frogfish": "A frogfish walks on fin-legs and can gulp prey in a flash.",
  "stargazer": "The stargazer buries itself with eyes pointing straight up.",
  "archerfish": "The archerfish shoots water to knock insects into the sea.",
  "needlefish": "Needlefish have a long, thin beak lined with sharp teeth.",
  "pipefish": "A pipefish is a straightened-out relative of the seahorse.",
  "trumpetfish": "The trumpetfish hovers head-down to hide among coral.",
  "goblin-shark": "The goblin shark shoots its jaws out to snatch its prey.",
  "gulper-eel": "The gulper eel's huge mouth swallows prey bigger than itself.",
  "viperfish": "The viperfish has fangs too big to fit inside its mouth.",
  "fangtooth": "The fangtooth has the largest teeth for its size of any fish.",
  "dragonfish": "The deep-sea dragonfish makes its own glowing light.",
  "lanternfish": "Lanternfish glow with light organs along their bodies.",
  "vampire-squid": "The vampire squid lives where there is almost no oxygen.",
  "sea-snake": "Sea snakes are venomous but rarely bite people.",
};
