// E205 sea-creature-emoji-2 facts — one true <=70-char fact per creature, shown on reveal.
export const SEACREATURE_EMOJI_2_FACTS = {
  // EASY
  "humpback-whale": "Males sing long, complex songs that can travel for miles.",
  "blue-whale": "The largest animal ever known to have lived on Earth.",
  "sperm-whale": "Has the biggest brain of any animal and hunts giant squid.",
  "blue-crab": "A prized Atlantic swimming crab with bright blue claws.",
  "king-crab": "A huge, spiny crab prized for its long, meaty legs.",
  "snow-crab": "A cold-water crab with long thin legs and sweet meat.",
  "scallop": "A shellfish with rows of tiny eyes along its shell edge.",
  "clam": "A burrowing shellfish that filters food from the sand.",
  "mussel": "Clings to rocks with tough threads called a byssus.",
  "moon-jellyfish": "A pale, round jellyfish with a mild, gentle sting.",
  "box-jellyfish": "Has cube-shaped bells and among the most toxic stings.",
  "green-sea-turtle": "Named for the green fat beneath its shell, not its color.",
  "leatherback-turtle": "The largest turtle, with a soft, leathery shell.",
  "harp-seal": "Pups are born with fluffy white fur that later darkens.",
  "elephant-seal": "Males have a large trunk-like nose used to bellow.",
  "leopard-seal": "A spotted Antarctic predator that hunts penguins.",
  "bull-shark": "Can survive in both salt water and freshwater rivers.",
  "nurse-shark": "A slow, bottom-dwelling shark that rests on the seafloor.",
  "giant-squid": "A deep-sea giant with plate-sized eyes and ten long arms.",
  "triggerfish": "Locks its dorsal spine upright to wedge into coral cracks.",
  "sea-bass": "A firm-fleshed reef and coastal fish prized by anglers.",
  "sawfish": "Uses its long toothed snout to slash and stun prey.",
  "conch": "A large sea snail whose shell was once used as a horn.",
  "sailfish": "The fastest fish in the ocean, with a tall sail-like fin.",
  "tarpon": "Nicknamed the 'Silver King' for its huge silver scales.",

  // MEDIUM
  "gray-whale": "Makes one of the longest migrations of any mammal.",
  "pilot-whale": "Actually a large member of the dolphin family.",
  "coconut-crab": "The largest land crab, strong enough to crack coconuts.",
  "fiddler-crab": "Males wave one oversized claw to attract mates.",
  "spider-crab": "A long-legged crab that can grow larger than an octopus.",
  "ghost-crab": "A pale sand crab so fast it seems to vanish.",
  "abalone": "A sea snail whose shell shines with rainbow colors inside.",
  "loggerhead-turtle": "Named for its unusually large, block-shaped head.",
  "saltwater-crocodile": "The largest living reptile, found in coastal waters.",
  "reef-shark": "A common coral-reef predator that patrols shallow waters.",
  "zebra-shark": "Born with stripes that fade into spots as it grows.",
  "leopard-shark": "A slender shark with dark saddle-like spots.",
  "mako-shark": "The fastest shark, able to leap high out of the water.",
  "lemon-shark": "Named for its pale yellowish skin tone.",
  "thresher-shark": "Uses its whip-like tail to stun schooling fish.",
  "boxfish": "Has a rigid, box-shaped body armored with bony plates.",
  "blue-tang": "A bright blue reef fish made famous by an animated film.",
  "electric-ray": "Can generate a shock of over 200 volts to stun prey.",
  "eagle-ray": "Glides through open water flapping wing-like fins.",
  "cowrie": "Its glossy shell was once used as money in many cultures.",
  "brittle-star": "A starfish relative that easily sheds an arm to escape.",
  "colossal-squid": "Has the largest eyes of any animal, bigger than a soccer ball.",
  "wahoo": "One of the fastest fish, prized as a sport-fishing catch.",
  "bonito": "A fast tuna relative often dried into flakes for broth.",
  "garden-eel": "Lives in burrows in colonies that sway like a garden.",

  // HARD
  "minke-whale": "The smallest of the baleen whales found worldwide.",
  "harbor-porpoise": "One of the smallest cetaceans, shy of boats.",
  "hawksbill-turtle": "Has a narrow, hooked beak used to eat sponges.",
  "marine-iguana": "The only lizard that forages for food in the sea.",
  "pistol-shrimp": "Snaps a claw to create a bubble louder than a gunshot.",
  "cleaner-shrimp": "Removes parasites from fish that visit its cleaning station.",
  "crown-of-thorns-starfish": "A spiny starfish that can devastate coral reefs.",
  "lions-mane-jellyfish": "Its trailing tentacles can stretch over 100 feet long.",
  "portuguese-man-o-war": "Not one animal but a colony of specialized organisms.",
  "limpet": "Clamps onto rocks so tightly it resists strong waves.",
  "sturgeon": "An ancient fish whose eggs are harvested as caviar.",
  "sand-tiger-shark": "Looks fierce but is calm and swims slowly near beaches.",
  "blacktip-shark": "Known for spinning leaps out of the water while feeding.",
  "bamboo-shark": "A small shark that can survive out of water for hours.",
  "basking-shark": "The second-largest fish, filter-feeding near the surface.",
  "conger-eel": "A large eel that hides by day in rocky crevices.",
  "ribbon-eel": "Changes from black to blue to yellow as it matures.",
  "remora": "Attaches to sharks with a suction disk to hitch a ride.",
  "wrasse": "Many species change sex as they grow older.",
  "damselfish": "A small, feisty reef fish that guards its own algae patch.",
  "surgeonfish": "Has a scalpel-sharp spine near its tail for defense.",
  "jackfish": "A fast-swimming predator that hunts in open-water schools.",
  "skate": "A flat cartilaginous fish that lays eggs in leathery cases.",
  "whelk": "A predatory sea snail that drills through other shells.",
  "rockfish": "A slow-growing fish that can live over a century.",

  // IMPOSSIBLE
  "fin-whale": "The second-largest animal on Earth after the blue whale.",
  "right-whale": "Named because whalers called it the 'right' whale to hunt.",
  "bowhead-whale": "Has the thickest blubber of any animal for Arctic cold.",
  "vaquita": "The world's smallest and most endangered marine mammal.",
  "dumbo-octopus": "Flaps ear-like fins to swim in the deep sea, like its namesake.",
  "blanket-octopus": "Females trail huge webbed sheets many times their body size.",
  "mimic-octopus": "Impersonates other sea animals like lionfish and sea snakes.",
  "flapjack-octopus": "A round, flat deep-sea octopus resembling a pancake.",
  "firefly-squid": "Glows blue when it swarms to shallow waters to spawn.",
  "bobtail-squid": "A tiny squid that glows to erase its shadow from predators.",
  "giant-isopod": "A deep-sea crustacean resembling a giant pill bug.",
  "yeti-crab": "Its claws are covered in pale, hair-like bristles.",
  "copepod": "A tiny crustacean that may be the most numerous animal on Earth.",
  "basket-star": "Has branching arms that fan out into a basket-like net.",
  "feather-star": "An echinoderm with feathery arms once mistaken for a plant.",
  "sea-pig": "A deep-sea sea cucumber that walks on plump, stubby legs.",
  "sea-pen": "A colony of polyps shaped like an antique quill pen.",
  "fire-coral": "Not true coral, and its sting can cause a painful burn.",
  "chiton": "A shelled mollusk with eight overlapping armor plates.",
  "nudibranch": "A shell-less sea slug known for vivid, vibrant colors.",
  "sea-hare": "A soft sea slug named for rabbit-like head tentacles.",
  "sea-butterfly": "A tiny swimming sea snail that flaps wing-like flaps.",
  "sea-angel": "A see-through swimming sea slug that preys on sea butterflies.",
  "cookiecutter-shark": "Bites round plugs of flesh out of much larger animals.",
  "megamouth-shark": "A rare deep-sea shark with a huge, glowing mouth.",
};
