// E20 · «Guess the Sea Creature» — 100 (25/مستوى) · صور iNaturalist (CC0/CC-BY) sea/<slug>.jpg · صوت sc-<slug>.wav (edge-tts مجاني)
export const SEA = [
  // ===== EASY (25) =====
  { slug: "great-white-shark", name: "Great White Shark", sci: "Carcharodon carcharias", level: "easy" },
  { slug: "common-bottlenose-dolphin", name: "Bottlenose Dolphin", sci: "Tursiops truncatus", level: "easy" },
  { slug: "orca", name: "Orca", sci: "Orcinus orca", level: "easy" },
  { slug: "common-octopus", name: "Common Octopus", sci: "Octopus vulgaris", level: "easy" },
  { slug: "green-sea-turtle", name: "Green Sea Turtle", sci: "Chelonia mydas", level: "easy" },
  { slug: "clownfish", name: "Clownfish", sci: "Amphiprion ocellaris", level: "easy" },
  { slug: "giant-pacific-octopus", name: "Giant Pacific Octopus", sci: "Enteroctopus dofleini", level: "easy" },
  { slug: "humpback-whale", name: "Humpback Whale", sci: "Megaptera novaeangliae", level: "easy" },
  { slug: "manta-ray", name: "Manta Ray", sci: "Mobula birostris", level: "easy" },
  { slug: "moon-jellyfish", name: "Moon Jellyfish", sci: "Aurelia aurita", level: "easy" },
  { slug: "common-seahorse", name: "Seahorse", sci: "Hippocampus guttulatus", level: "easy" },
  { slug: "hammerhead-shark", name: "Hammerhead Shark", sci: "Sphyrna lewini", level: "easy" },
  { slug: "walrus", name: "Walrus", sci: "Odobenus rosmarus", level: "easy" },
  { slug: "harbor-seal", name: "Harbor Seal", sci: "Phoca vitulina", level: "easy" },
  { slug: "california-sea-lion", name: "Sea Lion", sci: "Zalophus californianus", level: "easy" },
  { slug: "american-lobster", name: "Lobster", sci: "Homarus americanus", level: "easy" },
  { slug: "blue-crab", name: "Blue Crab", sci: "Callinectes sapidus", level: "easy" },
  { slug: "common-cuttlefish", name: "Cuttlefish", sci: "Sepia officinalis", level: "easy" },
  { slug: "whale-shark", name: "Whale Shark", sci: "Rhincodon typus", level: "easy" },
  { slug: "lions-mane-jellyfish", name: "Lion's Mane Jellyfish", sci: "Cyanea capillata", level: "easy" },
  { slug: "giant-clam", name: "Giant Clam", sci: "Tridacna gigas", level: "easy" },
  { slug: "pufferfish", name: "Pufferfish", sci: "Arothron hispidus", level: "easy" },
  { slug: "common-starfish", name: "Starfish", sci: "Asterias rubens", level: "easy" },
  { slug: "loggerhead-turtle", name: "Loggerhead Turtle", sci: "Caretta caretta", level: "easy" },
  { slug: "blue-marlin", name: "Blue Marlin", sci: "Makaira nigricans", level: "easy" },

  // ===== MEDIUM (25) =====
  { slug: "leafy-seadragon", name: "Leafy Seadragon", sci: "Phycodurus eques", level: "medium" },
  { slug: "mandarinfish", name: "Mandarinfish", sci: "Synchiropus splendidus", level: "medium" },
  { slug: "chambered-nautilus", name: "Nautilus", sci: "Nautilus pompilius", level: "medium" },
  { slug: "horseshoe-crab", name: "Horseshoe Crab", sci: "Limulus polyphemus", level: "medium" },
  { slug: "blue-tang", name: "Blue Tang", sci: "Paracanthurus hepatus", level: "medium" },
  { slug: "green-moray-eel", name: "Moray Eel", sci: "Gymnothorax funebris", level: "medium" },
  { slug: "southern-stingray", name: "Stingray", sci: "Hypanus americanus", level: "medium" },
  { slug: "sea-otter", name: "Sea Otter", sci: "Enhydra lutris", level: "medium" },
  { slug: "narwhal", name: "Narwhal", sci: "Monodon monoceros", level: "medium" },
  { slug: "west-indian-manatee", name: "Manatee", sci: "Trichechus manatus", level: "medium" },
  { slug: "beluga-whale", name: "Beluga Whale", sci: "Delphinapterus leucas", level: "medium" },
  { slug: "flying-fish", name: "Flying Fish", sci: "Exocoetus volitans", level: "medium" },
  { slug: "great-barracuda", name: "Barracuda", sci: "Sphyraena barracuda", level: "medium" },
  { slug: "swordfish", name: "Swordfish", sci: "Xiphias gladius", level: "medium" },
  { slug: "ocean-sunfish", name: "Ocean Sunfish", sci: "Mola mola", level: "medium" },
  { slug: "cownose-ray", name: "Cownose Ray", sci: "Rhinoptera bonasus", level: "medium" },
  { slug: "hermit-crab", name: "Hermit Crab", sci: "Pagurus bernhardus", level: "medium" },
  { slug: "sea-cucumber", name: "Sea Cucumber", sci: "Apostichopus californicus", level: "medium" },
  { slug: "spanish-dancer", name: "Spanish Dancer", sci: "Hexabranchus sanguineus", level: "medium" },
  { slug: "lionfish", name: "Lionfish", sci: "Pterois volitans", level: "medium" },
  { slug: "porcupinefish", name: "Porcupinefish", sci: "Diodon hystrix", level: "medium" },
  { slug: "giant-green-anemone", name: "Sea Anemone", sci: "Anthopleura xanthogrammica", level: "medium" },
  { slug: "purple-sea-urchin", name: "Sea Urchin", sci: "Strongylocentrotus purpuratus", level: "medium" },
  { slug: "leopard-shark", name: "Leopard Shark", sci: "Triakis semifasciata", level: "medium" },
  { slug: "clown-triggerfish", name: "Clown Triggerfish", sci: "Balistoides conspicillum", level: "medium" },

  // ===== HARD (25) =====
  { slug: "peacock-mantis-shrimp", name: "Peacock Mantis Shrimp", sci: "Odontodactylus scyllarus", level: "hard" },
  { slug: "blue-ringed-octopus", name: "Blue-ringed Octopus", sci: "Hapalochlaena maculosa", level: "hard" },
  { slug: "warty-frogfish", name: "Warty Frogfish", sci: "Antennarius maculatus", level: "hard" },
  { slug: "spotted-wobbegong", name: "Wobbegong", sci: "Orectolobus maculatus", level: "hard" },
  { slug: "sarcastic-fringehead", name: "Sarcastic Fringehead", sci: "Neoclinus blanchardi", level: "hard" },
  { slug: "flamboyant-cuttlefish", name: "Flamboyant Cuttlefish", sci: "Metasepia pfefferi", level: "hard" },
  { slug: "ribbon-eel", name: "Ribbon Eel", sci: "Rhinomuraena quaesita", level: "hard" },
  { slug: "christmas-tree-worm", name: "Christmas Tree Worm", sci: "Spirobranchus giganteus", level: "hard" },
  { slug: "basket-star", name: "Basket Star", sci: "Gorgonocephalus eucnemis", level: "hard" },
  { slug: "leaf-scorpionfish", name: "Leaf Scorpionfish", sci: "Taenianotus triacanthus", level: "hard" },
  { slug: "frilled-shark", name: "Frilled Shark", sci: "Chlamydoselachus anguineus", level: "hard" },
  { slug: "zebra-shark", name: "Zebra Shark", sci: "Stegostoma tigrinum", level: "hard" },
  { slug: "longhorn-cowfish", name: "Longhorn Cowfish", sci: "Lactoria cornuta", level: "hard" },
  { slug: "harlequin-shrimp", name: "Harlequin Shrimp", sci: "Hymenocera picta", level: "hard" },
  { slug: "weedy-seadragon", name: "Weedy Seadragon", sci: "Phyllopteryx taeniolatus", level: "hard" },
  { slug: "ornate-ghost-pipefish", name: "Ghost Pipefish", sci: "Solenostomus paradoxus", level: "hard" },
  { slug: "banggai-cardinalfish", name: "Banggai Cardinalfish", sci: "Pterapogon kauderni", level: "hard" },
  { slug: "pineapplefish", name: "Pineapplefish", sci: "Cleidopus gloriamaris", level: "hard" },
  { slug: "argonaut", name: "Argonaut", sci: "Argonauta argo", level: "hard" },
  { slug: "persian-carpet-flatworm", name: "Persian Carpet Flatworm", sci: "Pseudobiceros bedfordi", level: "hard" },
  { slug: "sea-pen", name: "Sea Pen", sci: "Ptilosarcus gurneyi", level: "hard" },
  { slug: "decorator-crab", name: "Decorator Crab", sci: "Hyas araneus", level: "hard" },
  { slug: "tasseled-scorpionfish", name: "Scorpionfish", sci: "Scorpaenopsis oxycephala", level: "hard" },
  { slug: "flying-gurnard", name: "Flying Gurnard", sci: "Dactylopterus volitans", level: "hard" },
  { slug: "chocolate-chip-starfish", name: "Chocolate Chip Sea Star", sci: "Protoreaster nodosus", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { slug: "blue-dragon", name: "Blue Dragon", sci: "Glaucus atlanticus", level: "impossible" },
  { slug: "giant-isopod", name: "Giant Isopod", sci: "Bathynomus giganteus", level: "impossible" },
  { slug: "red-lipped-batfish", name: "Red-lipped Batfish", sci: "Ogcocephalus darwini", level: "impossible" },
  { slug: "sea-angel", name: "Sea Angel", sci: "Clione limacina", level: "impossible" },
  { slug: "coconut-octopus", name: "Coconut Octopus", sci: "Amphioctopus marginatus", level: "impossible" },
  { slug: "fried-egg-jellyfish", name: "Fried Egg Jellyfish", sci: "Cotylorhiza tuberculata", level: "impossible" },
  { slug: "pom-pom-crab", name: "Pom-pom Crab", sci: "Lybia tessellata", level: "impossible" },
  { slug: "hairy-frogfish", name: "Hairy Frogfish", sci: "Antennarius striatus", level: "impossible" },
  { slug: "wunderpus", name: "Wunderpus Octopus", sci: "Wunderpus photogenicus", level: "impossible" },
  { slug: "mimic-octopus", name: "Mimic Octopus", sci: "Thaumoctopus mimicus", level: "impossible" },
  { slug: "spanish-shawl", name: "Spanish Shawl", sci: "Flabellina iodinea", level: "impossible" },
  { slug: "leaf-sheep", name: "Leaf Sheep", sci: "Costasiella kuroshimae", level: "impossible" },
  { slug: "sunflower-sea-star", name: "Sunflower Sea Star", sci: "Pycnopodia helianthoides", level: "impossible" },
  { slug: "pikachu-nudibranch", name: "Pikachu Nudibranch", sci: "Thecacera pacifica", level: "impossible" },
  { slug: "sea-bunny", name: "Sea Bunny", sci: "Jorunna parva", level: "impossible" },
  { slug: "candy-crab", name: "Candy Crab", sci: "Hoplophrys oatesii", level: "impossible" },
  { slug: "porcelain-anemone-crab", name: "Porcelain Crab", sci: "Neopetrolisthes maculatus", level: "impossible" },
  { slug: "bobbit-worm", name: "Bobbit Worm", sci: "Eunice aphroditois", level: "impossible" },
  { slug: "feather-duster-worm", name: "Feather Duster Worm", sci: "Sabella spallanzanii", level: "impossible" },
  { slug: "flamingo-tongue-snail", name: "Flamingo Tongue Snail", sci: "Cyphoma gibbosum", level: "impossible" },
  { slug: "chromodoris-nudibranch", name: "Chromodoris Nudibranch", sci: "Chromodoris willani", level: "impossible" },
  { slug: "longnose-hawkfish", name: "Longnose Hawkfish", sci: "Oxycirrhites typus", level: "impossible" },
  { slug: "atlantic-wolffish", name: "Atlantic Wolffish", sci: "Anarhichas lupus", level: "impossible" },
  { slug: "sea-lamprey", name: "Sea Lamprey", sci: "Petromyzon marinus", level: "impossible" },
  { slug: "cleaner-wrasse", name: "Cleaner Wrasse", sci: "Labroides dimidiatus", level: "impossible" },
];

export const SEA_LEVELS = ["easy", "medium", "hard", "impossible"];
