// E20 «Guess the Sea Creature» — did-you-know facts, ≤70 chars each, verified.
export const SEA_FACTS = {
  // ===== EASY =====
  "great-white-shark": "Can smell one drop of blood in an Olympic-size pool",
  "common-bottlenose-dolphin": "Calls each other by unique signature whistles like names",
  "orca": "Actually the largest species of dolphin, not a whale",
  "common-octopus": "Has three hearts and blue, copper-based blood",
  "green-sea-turtle": "Named for the green fat under its shell, not the shell",
  "clownfish": "Immune to the stinging tentacles of its host anemone",
  "giant-pacific-octopus": "The largest octopus, with an arm span up to 20 feet",
  "humpback-whale": "Males sing complex songs that can last for hours",
  "manta-ray": "Has the largest brain of any fish",
  "moon-jellyfish": "Has no brain, heart, or bones, and is about 95% water",
  "common-seahorse": "Males, not females, carry and give birth to the young",
  "hammerhead-shark": "Its wide head gives it near-360-degree vision",
  "walrus": "Uses its long tusks to haul its body out onto the ice",
  "harbor-seal": "Slows its heart rate to a few beats while diving deep",
  "california-sea-lion": "Can rotate its hind flippers to walk on land",
  "american-lobster": "Can live over 100 years and never stops growing",
  "blue-crab": "Its scientific name means beautiful savory swimmer",
  "common-cuttlefish": "Can change color instantly despite being colorblind",
  "whale-shark": "The largest fish in the sea, reaching 40 feet long",
  "lions-mane-jellyfish": "The largest jellyfish, with tentacles over 100 feet",
  "giant-clam": "The largest bivalve mollusk, it can weigh over 400 pounds",
  "pufferfish": "Carries a toxin far deadlier than cyanide",
  "common-starfish": "Can regrow a lost arm, and has no brain or blood",
  "loggerhead-turtle": "Uses Earth's magnetic field to navigate the ocean",
  "blue-marlin": "Females can grow far heavier than the males",

  // ===== MEDIUM =====
  "leafy-seadragon": "Its leaf-like flaps are for camouflage, not swimming",
  "mandarinfish": "One of the only animals with true blue pigment cells",
  "chambered-nautilus": "A living fossil, little changed for millions of years",
  "horseshoe-crab": "Its blue blood is used to test medical vaccines",
  "blue-tang": "Can play dead and has sharp spines near its tail",
  "green-moray-eel": "It's actually brown; yellow mucus makes it look green",
  "southern-stingray": "Breathes through openings called spiracles behind eyes",
  "sea-otter": "Holds hands while sleeping so it won't drift apart",
  "narwhal": "Its long tusk is actually a giant spiral tooth",
  "west-indian-manatee": "A gentle giant thought to inspire mermaid legends",
  "beluga-whale": "Nicknamed the canary of the sea for its songs",
  "flying-fish": "Can glide over 600 feet through the air above water",
  "great-barracuda": "Attracted to shiny objects, mistaking them for prey",
  "swordfish": "Uses its bill to slash at prey, not to spear it",
  "ocean-sunfish": "The heaviest bony fish, weighing over 2 tons",
  "cownose-ray": "Migrates in huge schools of thousands at a time",
  "hermit-crab": "Lives in empty shells and upgrades as it grows",
  "sea-cucumber": "Can expel its own guts to defend against predators",
  "spanish-dancer": "A sea slug that swims by flexing its red body",
  "lionfish": "An invasive reef fish armed with venomous spines",
  "porcupinefish": "Inflates into a spiky ball to deter predators",
  "giant-green-anemone": "Its green color comes from algae living inside it",
  "purple-sea-urchin": "Moves and feeds using hundreds of tiny tube feet",
  "leopard-shark": "A harmless shark named for its spotted pattern",
  "clown-triggerfish": "Can lock itself into crevices with a stout spine",

  // ===== HARD =====
  "peacock-mantis-shrimp": "Strikes with the acceleration of a .22 caliber bullet",
  "blue-ringed-octopus": "Tiny, but carries venom that can kill a human",
  "warty-frogfish": "Uses a built-in lure to fish for its prey",
  "spotted-wobbegong": "A carpet shark that ambushes prey while camouflaged",
  "sarcastic-fringehead": "Opens its huge mouth wide to fight off rivals",
  "flamboyant-cuttlefish": "So toxic that its flesh is poisonous to eat",
  "ribbon-eel": "Born male, it later changes into a female",
  "christmas-tree-worm": "Its colorful spirals are gills for breathing and feeding",
  "basket-star": "Unfurls branching arms to catch drifting plankton",
  "leaf-scorpionfish": "Sways like a leaf and sheds its skin to stay clean",
  "frilled-shark": "A living fossil with 300 needle-like teeth",
  "zebra-shark": "Born with stripes that fade into spots as it grows",
  "longhorn-cowfish": "Has horns and releases toxins when stressed",
  "harlequin-shrimp": "Eats only starfish, flipping them over to feed",
  "weedy-seadragon": "Males carry the eggs on their tails until they hatch",
  "ornate-ghost-pipefish": "Hovers head-down to blend with corals and crinoids",
  "banggai-cardinalfish": "Males brood the eggs and young inside their mouths",
  "pineapplefish": "Glows using light-producing bacteria on its head",
  "argonaut": "Females make a paper-thin shell to hold their eggs",
  "persian-carpet-flatworm": "A flatworm that swims with rippling frilled edges",
  "sea-pen": "A colony of animals shaped like an old quill pen",
  "decorator-crab": "Sticks bits of sponge and algae on itself to hide",
  "tasseled-scorpionfish": "A venomous ambush predator that mimics the reef",
  "flying-gurnard": "Spreads huge wing-like fins to startle predators",
  "chocolate-chip-starfish": "Named for the dark horn-like bumps on its back",

  // ===== IMPOSSIBLE =====
  "blue-dragon": "Steals stinging cells from the man o' war it eats",
  "giant-isopod": "A deep-sea relative of the pillbug, up to 20 inches",
  "red-lipped-batfish": "Walks on its fins and sports bright red lips",
  "sea-angel": "A swimming sea slug that flaps wing-like feet",
  "coconut-octopus": "Carries coconut shells to use as portable armor",
  "fried-egg-jellyfish": "Looks just like a fried egg floating in the sea",
  "pom-pom-crab": "Holds tiny anemones in its claws like pom-poms",
  "hairy-frogfish": "Covered in hair-like spines and lures its prey",
  "wunderpus": "Has a unique spot pattern, like a fingerprint",
  "mimic-octopus": "Can imitate lionfish, sea snakes, and flatfish",
  "spanish-shawl": "A vivid purple sea slug tipped with fiery orange frills",
  "leaf-sheep": "A sea slug that photosynthesizes like a plant",
  "sunflower-sea-star": "One of the largest sea stars, with up to 24 arms",
  "pikachu-nudibranch": "A sea slug named for resembling Pikachu",
  "sea-bunny": "A fuzzy sea slug whose 'ears' are sensory organs",
  "candy-crab": "Camouflages perfectly among soft coral polyps",
  "porcelain-anemone-crab": "Lives safely among a host anemone's tentacles",
  "bobbit-worm": "Buries itself and strikes prey with lightning speed",
  "feather-duster-worm": "Filters food with a crown that looks like a duster",
  "flamingo-tongue-snail": "Its bright spots are living tissue, not the shell",
  "chromodoris-nudibranch": "A striking sea slug that stores toxins from sponges",
  "longnose-hawkfish": "Perches on coral, watching prey with its long snout",
  "atlantic-wolffish": "Uses strong fang-like teeth to crush shellfish",
  "sea-lamprey": "A jawless fish that latches on with a sucker mouth",
  "cleaner-wrasse": "Sets up stations to eat parasites off bigger fish",
};
