// E12 «Guess the Country by Shape #2» — did-you-know facts, ≤70 chars each, verified.
export const SHAPE2_FACTS = {
  // ===== EASY (25) — iconic outlines almost everyone knows =====
  "it": "The city of Venice is built across many islands.",
  "fr": "Home to the Louvre, the world's most-visited museum.",
  "es": "The Sagrada Familia rises in the city of Barcelona.",
  "gb": "Made up of England, Scotland, Wales and N. Ireland.",
  "br": "Rio's Christ the Redeemer statue overlooks the bay.",
  "in": "The Ganges is a river sacred to millions here.",
  "au": "The Great Barrier Reef lies off its northeast coast.",
  "ca": "Its capital city is Ottawa, not Toronto.",
  "cn": "Home to wild giant pandas in its bamboo forests.",
  "cl": "The Atacama is the driest desert on Earth.",
  "de": "Home to the fairy-tale Neuschwanstein Castle.",
  "eg": "The Nile River flows north through its deserts.",
  "ar": "The tango dance was born in Buenos Aires.",
  "id": "Home to the Komodo dragon, the largest lizard.",
  "ch": "The Matterhorn towers over its Alpine peaks.",
  "pt": "Lisbon, its capital, sits on the Atlantic coast.",
  "cu": "The largest island in the Caribbean Sea.",
  "gr": "It has thousands of islands across two seas.",
  "tn": "Its capital Tunis lies near ancient Carthage.",
  "cr": "It abolished its army back in 1948.",
  "pa": "The Panama Canal links two great oceans.",
  "vn": "Halong Bay is dotted with limestone islands.",
  "th": "Bangkok is its busy, temple-filled capital.",
  "jm": "Reggae music was born on this island.",
  "co": "Home to lush, world-famous coffee highlands.",

  // ===== MEDIUM (25) — fairly known outlines =====
  "ie": "Dublin, its capital, sits on the River Liffey.",
  "kp": "Mount Paektu is its highest volcanic peak.",
  "dk": "Lego bricks were invented in this country.",
  "at": "Vienna, its capital, was a city of great composers.",
  "be": "Famous for its chocolate, waffles and comics.",
  "ae": "Dubai's Burj Khalifa is the world's tallest tower.",
  "hr": "The walled city of Dubrovnik sits on its coast.",
  "sy": "Damascus is one of the world's oldest cities.",
  "jo": "The ancient city of Petra is carved into rock.",
  "lb": "The cedar tree is its national symbol.",
  "om": "Muscat is its capital on the Arabian Sea.",
  "ec": "It is named after the Equator that crosses it.",
  "uy": "Montevideo is its capital beside the sea.",
  "ro": "Bran Castle helped inspire the Dracula legend.",
  "hu": "Budapest is split in two by the Danube river.",
  "cz": "Prague's castle is among the world's largest.",
  "by": "A landlocked land of vast forests and marshes.",
  "cy": "An island in the eastern Mediterranean Sea.",
  "so": "It has mainland Africa's longest coastline.",
  "tw": "Taipei 101 was once the world's tallest tower.",
  "sg": "A city-state at the tip of the Malay Peninsula.",
  "ht": "It shares one island with the Dominican Republic.",
  "do": "It shares Hispaniola island with Haiti.",
  "qa": "Doha is its modern capital on the Gulf.",
  "kw": "Kuwait City sits at the head of the Gulf.",

  // ===== HARD (25) — shapes known to geography fans =====
  "ge": "Tbilisi is its capital in the Caucasus Mountains.",
  "am": "One of the world's oldest Christian nations.",
  "az": "Baku, its capital, lies on the Caspian Sea.",
  "lt": "Vilnius Old Town is a UNESCO baroque gem.",
  "lv": "Riga sits on the Baltic Sea coast.",
  "ee": "Tallinn has a well-preserved medieval old town.",
  "md": "A landlocked country known for its wines.",
  "al": "Tirana is its capital in the Balkans.",
  "ba": "Sarajevo hosted the 1984 Winter Olympics.",
  "rs": "Belgrade sits where the Sava meets the Danube.",
  "sk": "Bratislava is its capital on the Danube river.",
  "si": "Lake Bled has a church on a tiny island.",
  "bg": "Sofia is one of Europe's oldest capital cities.",
  "cm": "Mount Cameroon is a towering active volcano.",
  "mr": "Most of its land lies in the Sahara Desert.",
  "gn": "The Niger River begins in its highlands.",
  "sl": "Freetown is its capital on the Atlantic coast.",
  "gt": "Home to the ancient Maya temples of Tikal.",
  "hn": "The great Maya ruins of Copan lie here.",
  "ni": "Home to Central America's largest lake.",
  "sv": "The smallest country in Central America.",
  "bh": "An island nation in the Persian Gulf.",
  "pg": "Over 800 languages are spoken across it.",
  "mv": "A chain of low coral islands and atolls.",
  "tt": "The birthplace of the steelpan drum.",

  // ===== IMPOSSIBLE (25) — obscure/small/lookalike outlines (<3%) =====
  "bs": "Made up of hundreds of islands and cays.",
  "bt": "A Himalayan kingdom that measures its happiness.",
  "bn": "A tiny, oil-rich state on Borneo island.",
  "km": "Volcanic islands in the Indian Ocean.",
  "sc": "An island nation northeast of Madagascar.",
  "mu": "Once home to the extinct flightless dodo bird.",
  "fj": "A Pacific nation of over 300 islands.",
  "ws": "A Polynesian island nation in the Pacific.",
  "to": "A Polynesian kingdom of many islands.",
  "ki": "Its islands straddle both the Equator and date line.",
  "nr": "One of the world's smallest island nations.",
  "pw": "Famous for its stingless Jellyfish Lake.",
  "mt": "A small archipelago south of Sicily.",
  "lu": "A tiny, wealthy landlocked grand duchy.",
  "li": "A tiny Alpine state that has no army.",
  "ad": "A tiny country high in the Pyrenees mountains.",
  "me": "Its name means 'Black Mountain'.",
  "mk": "Home to ancient, deep Lake Ohrid.",
  "sz": "A small kingdom in southern Africa.",
  "st": "Two islands on the Equator off West Africa.",
  "ag": "A Caribbean nation of two main islands.",
  "va": "The smallest country in the whole world.",
  "sm": "One of the world's oldest surviving republics.",
  "dm": "Known as the 'Nature Island' of the Caribbean.",
  "gd": "Known as the 'Spice Isle' for its nutmeg.",
};
