// E12 «Guess the Country by Shape» — did-you-know facts, ≤70 chars each, verified.
export const SHAPE1_FACTS = {
  "us": "Home to the Grand Canyon and 50 states",
  "it": "Its capital Rome surrounds tiny Vatican City",
  "jp": "Mount Fuji is its highest peak, near Tokyo",
  "au": "The only country that is also a continent",
  "gb": "London's Big Ben chimes over the Thames",
  "in": "Home to the Taj Mahal in the city of Agra",
  "br": "The Amazon rainforest covers much of it",
  "fr": "The Eiffel Tower stands in its capital, Paris",
  "eg": "The Great Pyramids of Giza rise near Cairo",
  "ca": "It has the longest coastline of any nation",
  "ru": "The largest country on Earth by land area",
  "cn": "The Great Wall stretches thousands of miles",
  "cl": "A long, thin country over 4,000 km from top to bottom",
  "es": "Madrid is one of Europe's highest capitals",
  "mx": "Ancient Maya and Aztec pyramids dot the land",
  "de": "Berlin, its capital, was split by a wall",
  "tr": "Istanbul spans both Europe and Asia",
  "se": "Stockholm is built across 14 islands",
  "no": "Famous for deep fjords carved by glaciers",
  "kr": "Seoul is its huge, high-tech capital",
  "id": "An archipelago of over 17,000 islands",
  "za": "It has three capital cities",
  "sa": "Home to the vast Rub' al Khali desert",
  "gr": "The Parthenon crowns Athens, its capital",
  "nz": "Made of two main islands, North and South",
  "ar": "Home to vast Pampas plains and Iguazu Falls",
  "ir": "Its capital Tehran lies below the Alborz range",
  "iq": "The Tigris and Euphrates rivers cross it",
  "pl": "Warsaw, its capital, was rebuilt after WWII",
  "ua": "Kyiv sits on the Dnieper River",
  "ph": "An archipelago of over 7,000 islands",
  "my": "Kuala Lumpur's Petronas Towers are twin giants",
  "cu": "The largest island in the Caribbean Sea",
  "ng": "Its planned capital city is Abuja",
  "ke": "The Great Rift Valley runs through it",
  "ma": "The Atlas Mountains cross this land",
  "pk": "K2, the world's 2nd-highest peak, lies here",
  "af": "A landlocked land of high mountain passes",
  "np": "Mount Everest rises on its northern border",
  "lk": "An island nation south of India",
  "ie": "Known as the Emerald Isle for its greenery",
  "is": "A volcanic island of geysers and glaciers",
  "fi": "Known as the land of a thousand lakes",
  "nl": "Much of its land lies below sea level",
  "ve": "Home to Angel Falls, the tallest waterfall",
  "co": "Bogota, its capital, sits high in the Andes",
  "pe": "The Inca city of Machu Picchu sits here",
  "et": "Its capital is Addis Ababa",
  "kz": "The world's largest landlocked country",
  "mn": "Home to the vast Gobi Desert",
  "sd": "The Nile flows north right through it",
  "ly": "Mostly covered by the Sahara Desert",
  "uz": "Home to the Silk Road city of Samarkand",
  "tm": "The Karakum Desert covers most of it",
  "la": "The only landlocked country in SE Asia",
  "kh": "Home to the temples of Angkor Wat",
  "bd": "Crossed by the mighty Ganges river delta",
  "mm": "Its largest city is Yangon",
  "bo": "Home to the world's largest salt flat",
  "py": "A landlocked country in South America",
  "sn": "The westernmost country of mainland Africa",
  "ml": "The ancient city of Timbuktu lies here",
  "ne": "Mostly covered by the Sahara Desert",
  "td": "Named after Lake Chad in its west",
  "ao": "Its capital is Luanda on the Atlantic",
  "mz": "A long coastline on the Indian Ocean",
  "zw": "Shares mighty Victoria Falls with Zambia",
  "zm": "Home to part of thundering Victoria Falls",
  "bw": "The Okavango Delta spreads across it",
  "na": "Home to the towering Namib Desert dunes",
  "ug": "By Lake Victoria, a source of the Nile",
  "tz": "Mount Kilimanjaro is Africa's highest peak",
  "mg": "A huge island off Africa's east coast",
  "gh": "Its capital city is Accra",
  "ci": "Its largest city is Abidjan",
  "cf": "Landlocked in the heart of Africa",
  "cg": "Its capital is Brazzaville",
  "cd": "The Congo River winds through it",
  "ga": "Its capital Libreville sits on the coast",
  "bf": "A landlocked country in West Africa",
  "bj": "Its largest city is Cotonou",
  "tg": "A narrow strip of land in West Africa",
  "rw": "Known as the land of a thousand hills",
  "mw": "Lake Malawi runs along much of its border",
  "ls": "A mountain kingdom encircled by South Africa",
  "gm": "Africa's smallest mainland country",
  "gw": "Includes the Bijagos island group",
  "dj": "Home to Lake Assal, Africa's lowest point",
  "er": "It lies along the Red Sea coast",
  "gq": "Its capital, Malabo, sits on an island",
  "tl": "Shares an island with Indonesia",
  "sr": "The smallest country in South America",
  "gy": "Home to the towering Kaieteur Falls",
  "bz": "Home to the Great Blue Hole reef sinkhole",
  "tj": "Nearly half its land lies above 3,000m",
  "kg": "A mountainous land in Central Asia",
  "sb": "A Pacific archipelago of nearly 1,000 isles",
  "vu": "A chain of islands in the South Pacific",
  "cv": "Volcanic islands off West Africa's coast",
  "ss": "The world's youngest nation, formed in 2011",
};
