// «Guess the Seashell» — GuessSync · E52 · 100 seashells (25/tier) · real photos from Wikimedia Commons
// Absolute difficulty by recognizability: easy (Scallop/Conch/Cowrie) → impossible (Glory of the Sea Cone, Junonia).
export const SHELLS = [
  // EASY (25) — iconic, household-name shells
  { slug: "scallop", name: "Scallop", level: "easy" },
  { slug: "queenconch", name: "Queen Conch", level: "easy" },
  { slug: "tigercowrie", name: "Tiger Cowrie", level: "easy" },
  { slug: "nautilus", name: "Chambered Nautilus", level: "easy" },
  { slug: "giantclam", name: "Giant Clam", level: "easy" },
  { slug: "pacificoyster", name: "Pacific Oyster", level: "easy" },
  { slug: "sanddollar", name: "Sand Dollar", level: "easy" },
  { slug: "commonwhelk", name: "Common Whelk", level: "easy" },
  { slug: "redabalone", name: "Red Abalone", level: "easy" },
  { slug: "commoncockle", name: "Common Cockle", level: "easy" },
  { slug: "bluemussel", name: "Blue Mussel", level: "easy" },
  { slug: "periwinkle", name: "Common Periwinkle", level: "easy" },
  { slug: "commonlimpet", name: "Common Limpet", level: "easy" },
  { slug: "textilecone", name: "Textile Cone", level: "easy" },
  { slug: "razorshell", name: "Razor Shell", level: "easy" },
  { slug: "moonsnail", name: "Moon Snail", level: "easy" },
  { slug: "tritontrumpet", name: "Triton's Trumpet", level: "easy" },
  { slug: "truetulip", name: "True Tulip", level: "easy" },
  { slug: "spiderconch", name: "Common Spider Conch", level: "easy" },
  { slug: "kinghelmet", name: "King Helmet", level: "easy" },
  { slug: "marlinspike", name: "Marlinspike Auger", level: "easy" },
  { slug: "greenturban", name: "Green Turban", level: "easy" },
  { slug: "quahog", name: "Hard Clam", level: "easy" },
  { slug: "dyemurex", name: "Spiny Dye-Murex", level: "easy" },
  { slug: "letteredolive", name: "Lettered Olive", level: "easy" },
  // MEDIUM (25)
  { slug: "lightningwhelk", name: "Lightning Whelk", level: "medium" },
  { slug: "scotchbonnet", name: "Scotch Bonnet", level: "medium" },
  { slug: "commonwentletrap", name: "Common Wentletrap", level: "medium" },
  { slug: "angelwing", name: "Angel Wing", level: "medium" },
  { slug: "pearloyster", name: "Pearl Oyster", level: "medium" },
  { slug: "keyholelimpet", name: "Keyhole Limpet", level: "medium" },
  { slug: "slippershell", name: "Common Slipper Shell", level: "medium" },
  { slug: "topshell", name: "Purple Top Shell", level: "medium" },
  { slug: "noblepenshell", name: "Noble Pen Shell", level: "medium" },
  { slug: "noahsark", name: "Noah's Ark Shell", level: "medium" },
  { slug: "gianttun", name: "Giant Tun", level: "medium" },
  { slug: "figshell", name: "Common Fig Shell", level: "medium" },
  { slug: "bleedingtooth", name: "Bleeding Tooth Nerite", level: "medium" },
  { slug: "turkeywing", name: "Turkey Wing", level: "medium" },
  { slug: "jingleshell", name: "Jingle Shell", level: "medium" },
  { slug: "westindiantopshell", name: "West Indian Top Shell", level: "medium" },
  { slug: "commonharp", name: "Common Harp", level: "medium" },
  { slug: "carriersnail", name: "Carrier Shell", level: "medium" },
  { slug: "fuzzychiton", name: "Fuzzy Chiton", level: "medium" },
  { slug: "commonnutmeg", name: "Common Nutmeg", level: "medium" },
  { slug: "horseconch", name: "Florida Horse Conch", level: "medium" },
  { slug: "bubbleshell", name: "Striped Bubble Shell", level: "medium" },
  { slug: "spindleshell", name: "Distaff Spindle", level: "medium" },
  { slug: "babylonshell", name: "Spotted Babylon", level: "medium" },
  { slug: "chestnutturban", name: "Chestnut Turban", level: "medium" },
  // HARD (25)
  { slug: "episcopalmiter", name: "Episcopal Miter", level: "hard" },
  { slug: "partridgetun", name: "Partridge Tun", level: "hard" },
  { slug: "channeledwhelk", name: "Channeled Whelk", level: "hard" },
  { slug: "knobbedwhelk", name: "Knobbed Whelk", level: "hard" },
  { slug: "flamingotongue", name: "Flamingo Tongue", level: "hard" },
  { slug: "moneycowrie", name: "Money Cowrie", level: "hard" },
  { slug: "commonsundial", name: "Common Sundial", level: "hard" },
  { slug: "bullmouthhelmet", name: "Bullmouth Helmet", level: "hard" },
  { slug: "chestnutcowrie", name: "Chestnut Cowrie", level: "hard" },
  { slug: "thornyoyster", name: "Thorny Oyster", level: "hard" },
  { slug: "windowpaneoyster", name: "Windowpane Oyster", level: "hard" },
  { slug: "donkeysear", name: "Donkey's Ear Abalone", level: "hard" },
  { slug: "papernautilus", name: "Paper Nautilus", level: "hard" },
  { slug: "pelicansfoot", name: "Pelican's Foot", level: "hard" },
  { slug: "roostertailconch", name: "Rooster-tail Conch", level: "hard" },
  { slug: "milkconch", name: "Milk Conch", level: "hard" },
  { slug: "fightingconch", name: "Florida Fighting Conch", level: "hard" },
  { slug: "giantspiderconch", name: "Giant Spider Conch", level: "hard" },
  { slug: "caribbeanvase", name: "Caribbean Vase", level: "hard" },
  { slug: "westindianchank", name: "West Indian Chank", level: "hard" },
  { slug: "sacredchank", name: "Sacred Chank", level: "hard" },
  { slug: "heartcockle", name: "Heart Cockle", level: "hard" },
  { slug: "bandedtulip", name: "Banded Tulip", level: "hard" },
  { slug: "eyedcowrie", name: "Eyed Cowrie", level: "hard" },
  { slug: "giantcerith", name: "Giant Knobbed Cerith", level: "hard" },
  // IMPOSSIBLE (25) — prized / obscure collector shells
  { slug: "gloryofthesea", name: "Glory of the Sea Cone", level: "impossible" },
  { slug: "preciouswentletrap", name: "Precious Wentletrap", level: "impossible" },
  { slug: "venuscombmurex", name: "Venus Comb Murex", level: "impossible" },
  { slug: "junonia", name: "Junonia", level: "impossible" },
  { slug: "matchlesscone", name: "Matchless Cone", level: "impossible" },
  { slug: "goldencowrie", name: "Golden Cowrie", level: "impossible" },
  { slug: "mapcowrie", name: "Map Cowrie", level: "impossible" },
  { slug: "royalcloakscallop", name: "Royal Cloak Scallop", level: "impossible" },
  { slug: "batvolute", name: "Bat Volute", level: "impossible" },
  { slug: "princelyvolute", name: "Princely Volute", level: "impossible" },
  { slug: "imperialvolute", name: "Imperial Volute", level: "impossible" },
  { slug: "japanesewondershell", name: "Japanese Wonder Shell", level: "impossible" },
  { slug: "delphinula", name: "Delphinula Snail", level: "impossible" },
  { slug: "shinbonetibia", name: "Shinbone Tibia", level: "impossible" },
  { slug: "orangespiderconch", name: "Orange Spider Conch", level: "impossible" },
  { slug: "tapestryturban", name: "Tapestry Turban", level: "impossible" },
  { slug: "marbledcone", name: "Marbled Cone", level: "impossible" },
  { slug: "leopardcone", name: "Leopard Cone", level: "impossible" },
  { slug: "generalcone", name: "General Cone", level: "impossible" },
  { slug: "admiralcone", name: "Admiral Cone", level: "impossible" },
  { slug: "papalmiter", name: "Papal Miter", level: "impossible" },
  { slug: "endivemurex", name: "Endive Murex", level: "impossible" },
  { slug: "ramosemurex", name: "Ramose Murex", level: "impossible" },
  { slug: "gloryofindia", name: "Glory of India Cone", level: "impossible" },
  { slug: "distaffspindle", name: "Ornamented Spindle", level: "impossible" },
];
