// «Guess the Seashell» — GuessSync · E52 · did-you-know facts, ≤70 chars, verified true.
export const SHELL_FACTS = {
  // EASY
  "scallop": "Rows of tiny blue eyes line the edge of its open shell",
  "queenconch": "Its glossy pink lip only flares once the animal matures",
  "tigercowrie": "Glassy shine comes from the mantle that wraps the shell",
  "nautilus": "Its coiled shell is split into gas-filled buoyancy chambers",
  "giantclam": "The largest can top a metre wide and weigh over 200 kg",
  "pacificoyster": "A farmed oyster that can filter 200 litres of water a day",
  "sanddollar": "The flat 'test' is the skeleton of a burrowing urchin kin",
  "commonwhelk": "Its egg cases wash ashore as spongy 'sea wash balls'",
  "redabalone": "Its ear-shaped shell has a row of small breathing holes",
  "commoncockle": "A heart-shaped ribbed shell buried in sandy shores",
  "bluemussel": "Anchors to rocks with tough threads called the byssus",
  "periwinkle": "A small edible sea snail grazing algae on rocky shores",
  "commonlimpet": "Its cone shell clamps to rock so tight it resists waves",
  "textilecone": "Its 'tent' pattern hides venom strong enough to kill",
  "razorshell": "Named for its shape; it digs down fast to escape danger",
  "moonsnail": "Drills a neat round hole to eat other shelled molluscs",
  "tritontrumpet": "Used as a horn for millennia; it hunts the crown-of-thorns",
  "truetulip": "A sleek spindle shell that preys on other sea snails",
  "spiderconch": "Finger-like spines around the lip give it its name",
  "kinghelmet": "A thick heavy shell once carved into cameo jewellery",
  "marlinspike": "A long pointed auger named after a sailor's rigging tool",
  "greenturban": "Its thick shell yields a green mother-of-pearl layer",
  "quahog": "Its growth rings record decades of ocean climate data",
  "dyemurex": "Ancient dye 'Tyrian purple' was extracted from this shell",
  "letteredolive": "Its glossy shell looks hand-inked with tiny letters",
  // MEDIUM
  "lightningwhelk": "Rare left-handed shell; its opening is on the left side",
  "scotchbonnet": "Named for its plaid-like squares of orange and brown",
  "commonwentletrap": "Its blade-like ribs cross a tall, ladder-like spire",
  "angelwing": "A brittle white bivalve that bores deep into soft clay",
  "pearloyster": "The mollusc that coats grit with nacre to form pearls",
  "keyholelimpet": "Water and waste exit through the hole at its peak",
  "slippershell": "A shelf inside gives it the look of a tiny slipper",
  "topshell": "A neat cone with a pearly rainbow layer beneath",
  "noblepenshell": "A giant fan shell that once yielded golden 'sea silk'",
  "noahsark": "A boxy ark shell that gapes to anchor by fine threads",
  "gianttun": "A thin light globe-shaped shell despite its large size",
  "figshell": "A thin fig-shaped shell carried by a huge fleshy foot",
  "bleedingtooth": "Red-stained 'teeth' at its opening give the name",
  "turkeywing": "Bold red-brown stripes recall a turkey's folded wing",
  "jingleshell": "Thin translucent shells that clink like tiny bells",
  "westindiantopshell": "A large black-and-white top shell of Caribbean reefs",
  "commonharp": "Sharp curved ribs run like the strings of a harp",
  "carriersnail": "It cements shells and stones onto its own shell",
  "fuzzychiton": "Eight plates girdled by a bristly leathery band",
  "commonnutmeg": "Its cross-hatched surface resembles a grated nutmeg",
  "horseconch": "One of the largest US snails, with a bright orange body",
  "bubbleshell": "A thin fragile shell the animal cannot fully hide in",
  "spindleshell": "A slender spindle drawn out into a very long canal",
  "babylonshell": "Neat brown spots on a cream shell, prized as food",
  "chestnutturban": "A small knobbly turban in warm chestnut tones",
  // HARD
  "episcopalmiter": "Bright red blotches mark this spindle-shaped shell",
  "partridgetun": "Mottled browns recall a partridge's speckled plumage",
  "channeledwhelk": "A deep groove spirals along each turn of the shell",
  "knobbedwhelk": "A row of blunt knobs crowns the shoulder of the shell",
  "flamingotongue": "Live, its bright spotted mantle covers a plain shell",
  "moneycowrie": "These small shells were used as money across Asia and Africa",
  "commonsundial": "Its flat coil shows a neat spiral like a sundial face",
  "bullmouthhelmet": "A glossy helmet shell long carved into shell cameos",
  "chestnutcowrie": "A rich chestnut oval bordered by a paler ring",
  "thornyoyster": "Long spines camouflage it as it cements to reef rock",
  "windowpaneoyster": "Flat translucent shells once used as glass panes",
  "donkeysear": "A flattened ear-shaped abalone with vivid inner nacre",
  "papernautilus": "Females make a paper-thin shell to hold their eggs",
  "pelicansfoot": "The flared lip splays out like a webbed bird's foot",
  "roostertailconch": "A long curved spine sweeps back like a rooster's tail",
  "milkconch": "A stout conch with a milky-white flaring lip",
  "fightingconch": "Males shove rivals with a sickle-shaped foot claw",
  "giantspiderconch": "Huge finger spines fringe this heavy reef conch",
  "caribbeanvase": "A thick vase-shaped shell with a blunt spiny shoulder",
  "westindianchank": "A heavy solid shell used for lime and ornaments",
  "sacredchank": "Sacred in India; a rare right-coiled one is holy",
  "heartcockle": "Seen from the side its two halves form a heart",
  "bandedtulip": "Fine dark spiral lines band this smooth spindle",
  "eyedcowrie": "Countless tiny ringed spots dot its glossy back",
  "giantcerith": "A tall knobby tower, the largest of the cerith snails",
  // IMPOSSIBLE
  "gloryofthesea": "Once so rare that single shells sold for a fortune",
  "preciouswentletrap": "Loose lacy ribs make a delicate white spiral tower",
  "venuscombmurex": "A row of long fine spines forms a comb-like fringe",
  "junonia": "A prized Florida find, dotted with brown squares",
  "matchlesscone": "Its name means 'second to none'; patterns vary widely",
  "goldencowrie": "A glossy golden cowrie once worn by Pacific chiefs",
  "mapcowrie": "Wavy lines on its back trace out map-like outlines",
  "royalcloakscallop": "Vivid red-and-white flakes cloak this reef scallop",
  "batvolute": "Dark zigzags spread like a bat's outstretched wings",
  "princelyvolute": "A prized volute with orderly bands of tent markings",
  "imperialvolute": "Sharp shoulder spines crown this large heavy volute",
  "japanesewondershell": "Its stepped spire coils into a striking pagoda shape",
  "delphinula": "Curling frilly spines make a spiky star-like whorl",
  "shinbonetibia": "Drawn into a needle-thin canal like a slender bone",
  "orangespiderconch": "Bright orange lip lines its long clawed spines",
  "tapestryturban": "Its round green 'cat's eye' lid is used in jewellery",
  "marbledcone": "Black shell tiled with white triangles like marble",
  "leopardcone": "One of the biggest cones, dotted like a leopard",
  "generalcone": "Banded 'epaulettes' recall a general's uniform",
  "admiralcone": "Fine bands and tents give it an admiral's finery",
  "papalmiter": "Red flecks on white recall a bishop's tall mitre",
  "endivemurex": "Frilly curled fronds ruffle like endive leaves",
  "ramosemurex": "A big murex with branching frond-like spines",
  "gloryofindia": "A rare deep-water cone long treasured by collectors",
  "distaffspindle": "A very long slender spire tapering to a fine point",
};
