// «Guess the Animal by Silhouette» — GuessSync E90 · SILHOUETTES · 100 animals (25/tier)
// Format: the clue is a solid BLACK silhouette of the animal on the white answer card.
// Difficulty here is ranked by how identifiable each animal is FROM ITS OUTLINE ALONE —
// distinctive-outline animals (trunk, long neck, pouch shape) are easy even if the species
// itself is common; generic four-legged-mammal outlines are pushed to hard/impossible
// even when the animal is otherwise well known. Household/common animals favored in
// the easy tiers. Answer VO sl-<slug>.wav = "It's the <name>!"
export const SILHOUETTES = [
  // EASY (25) — unmistakable outline: trunk, neck, pouch, beak, ears etc.
  { slug: "elephant", name: "Elephant", level: "easy" },
  { slug: "giraffe", name: "Giraffe", level: "easy" },
  { slug: "kangaroo", name: "Kangaroo", level: "easy" },
  { slug: "penguin", name: "Penguin", level: "easy" },
  { slug: "cat", name: "Cat", level: "easy" },
  { slug: "dog", name: "Dog", level: "easy" },
  { slug: "horse", name: "Horse", level: "easy" },
  { slug: "rabbit", name: "Rabbit", level: "easy" },
  { slug: "owl", name: "Owl", level: "easy" },
  { slug: "flamingo", name: "Flamingo", level: "easy" },
  { slug: "camel", name: "Camel", level: "easy" },
  { slug: "deer", name: "Deer", level: "easy" },
  { slug: "squirrel", name: "Squirrel", level: "easy" },
  { slug: "bat", name: "Bat", level: "easy" },
  { slug: "swan", name: "Swan", level: "easy" },
  { slug: "peacock", name: "Peacock", level: "easy" },
  { slug: "rooster", name: "Rooster", level: "easy" },
  { slug: "pig", name: "Pig", level: "easy" },
  { slug: "cow", name: "Cow", level: "easy" },
  { slug: "sheep", name: "Sheep", level: "easy" },
  { slug: "duck", name: "Duck", level: "easy" },
  { slug: "fox", name: "Fox", level: "easy" },
  { slug: "wolf", name: "Wolf", level: "easy" },
  { slug: "bear", name: "Bear", level: "easy" },
  { slug: "lion", name: "Lion", level: "easy" },

  // MEDIUM (25) — recognizable outline once you know the species, still fairly common
  { slug: "tiger", name: "Tiger", level: "medium" },
  { slug: "zebra", name: "Zebra", level: "medium" },
  { slug: "rhino", name: "Rhino", level: "medium" },
  { slug: "hippo", name: "Hippo", level: "medium" },
  { slug: "gorilla", name: "Gorilla", level: "medium" },
  { slug: "monkey", name: "Monkey", level: "medium" },
  { slug: "koala", name: "Koala", level: "medium" },
  { slug: "panda", name: "Panda", level: "medium" },
  { slug: "moose", name: "Moose", level: "medium" },
  { slug: "elk", name: "Elk", level: "medium" },
  { slug: "goat", name: "Goat", level: "medium" },
  { slug: "turtle", name: "Turtle", level: "medium" },
  { slug: "crocodile", name: "Crocodile", level: "medium" },
  { slug: "ostrich", name: "Ostrich", level: "medium" },
  { slug: "pelican", name: "Pelican", level: "medium" },
  { slug: "crab", name: "Crab", level: "medium" },
  { slug: "octopus", name: "Octopus", level: "medium" },
  { slug: "dolphin", name: "Dolphin", level: "medium" },
  { slug: "whale", name: "Whale", level: "medium" },
  { slug: "shark", name: "Shark", level: "medium" },
  { slug: "seahorse", name: "Seahorse", level: "medium" },
  { slug: "snail", name: "Snail", level: "medium" },
  { slug: "frog", name: "Frog", level: "medium" },
  { slug: "hedgehog", name: "Hedgehog", level: "medium" },
  { slug: "raccoon", name: "Raccoon", level: "medium" },

  // HARD (25) — generic four-legged/mid-size outline, needs real knowledge
  { slug: "cheetah", name: "Cheetah", level: "hard" },
  { slug: "leopard", name: "Leopard", level: "hard" },
  { slug: "jaguar", name: "Jaguar", level: "hard" },
  { slug: "hyena", name: "Hyena", level: "hard" },
  { slug: "wildebeest", name: "Wildebeest", level: "hard" },
  { slug: "buffalo", name: "Buffalo", level: "hard" },
  { slug: "bison", name: "Bison", level: "hard" },
  { slug: "walrus", name: "Walrus", level: "hard" },
  { slug: "seal", name: "Seal", level: "hard" },
  { slug: "otter", name: "Otter", level: "hard" },
  { slug: "beaver", name: "Beaver", level: "hard" },
  { slug: "chipmunk", name: "Chipmunk", level: "hard" },
  { slug: "mole", name: "Mole", level: "hard" },
  { slug: "armadillo", name: "Armadillo", level: "hard" },
  { slug: "anteater", name: "Anteater", level: "hard" },
  { slug: "sloth", name: "Sloth", level: "hard" },
  { slug: "meerkat", name: "Meerkat", level: "hard" },
  { slug: "mongoose", name: "Mongoose", level: "hard" },
  { slug: "wombat", name: "Wombat", level: "hard" },
  { slug: "platypus", name: "Platypus", level: "hard" },
  { slug: "tapir", name: "Tapir", level: "hard" },
  { slug: "warthog", name: "Warthog", level: "hard" },
  { slug: "boar", name: "Boar", level: "hard" },
  { slug: "lynx", name: "Lynx", level: "hard" },
  { slug: "bobcat", name: "Bobcat", level: "hard" },

  // IMPOSSIBLE (25) — obscure species, near-identical generic outlines
  { slug: "pangolin", name: "Pangolin", level: "impossible" },
  { slug: "aardvark", name: "Aardvark", level: "impossible" },
  { slug: "okapi", name: "Okapi", level: "impossible" },
  { slug: "tarsier", name: "Tarsier", level: "impossible" },
  { slug: "fossa", name: "Fossa", level: "impossible" },
  { slug: "binturong", name: "Binturong", level: "impossible" },
  { slug: "quokka", name: "Quokka", level: "impossible" },
  { slug: "numbat", name: "Numbat", level: "impossible" },
  { slug: "duiker", name: "Duiker", level: "impossible" },
  { slug: "gerenuk", name: "Gerenuk", level: "impossible" },
  { slug: "blackbuck", name: "Blackbuck", level: "impossible" },
  { slug: "kudu", name: "Kudu", level: "impossible" },
  { slug: "takin", name: "Takin", level: "impossible" },
  { slug: "serval", name: "Serval", level: "impossible" },
  { slug: "caracal", name: "Caracal", level: "impossible" },
  { slug: "ocelot", name: "Ocelot", level: "impossible" },
  { slug: "margay", name: "Margay", level: "impossible" },
  { slug: "genet", name: "Genet", level: "impossible" },
  { slug: "civet", name: "Civet", level: "impossible" },
  { slug: "coati", name: "Coati", level: "impossible" },
  { slug: "kinkajou", name: "Kinkajou", level: "impossible" },
  { slug: "capybara", name: "Capybara", level: "impossible" },
  { slug: "agouti", name: "Agouti", level: "impossible" },
  { slug: "paca", name: "Paca", level: "impossible" },
  { slug: "dhole", name: "Dhole", level: "impossible" },
];
export const SILHOUETTES_LEVELS = ["easy", "medium", "hard", "impossible"];
