// E23 — one-line "did-you-know" fact per snake, shown on the reveal screen.
// Adds original commentary value (YouTube inauthentic-content safeguard). All facts verified true, <70 chars.
export const SNAKE_FACTS = {
  "king-cobra": "Only snake that builds a nest for its eggs.",
  "ball-python": "Curls into a tight ball when scared — hence the name.",
  "boa-constrictor": "Kills by squeezing, not venom — it has none.",
  "green-anaconda": "Heaviest snake on Earth — can top 200 pounds.",
  "western-diamondback-rattlesnake": "Rattles a warning by shaking its hollow tail tip.",
  "corn-snake": "A gentle escape artist and a top beginner pet.",
  "black-mamba": "Fastest snake on land — up to 12 mph.",
  "cottonmouth": "Gapes a white mouth as a warning before it strikes.",
  "copperhead": "Babies use a yellow tail tip to lure in prey.",
  "common-garter-snake": "Gathers by the thousands to hibernate together.",
  "reticulated-python": "Longest snake alive — can exceed 20 feet.",
  "burmese-python": "Invasive in Florida, where it swallows whole deer.",
  "california-kingsnake": "Eats other snakes — even venomous rattlers.",
  "eastern-milk-snake": "Harmless mimic of the deadly coral snake.",
  "eastern-coral-snake": "Bright bands warn of one of the strongest venoms.",
  "gaboon-viper": "Has the longest fangs of any snake — up to 2 inches.",
  "green-tree-python": "Coils in a saddle loop over a branch to rest.",
  "sidewinder": "Slides sideways across hot desert sand.",
  "eastern-hognose-snake": "Plays dead, flips over, and even smells rotten.",
  "bushmaster": "Longest venomous snake in the Americas.",
  "indian-cobra": "One of India's deadly 'Big Four' snakes.",
  "egyptian-cobra": "The asp linked to Cleopatra's legendary death.",
  "grass-snake": "Plays dead and oozes a foul stench to escape.",
  "black-rat-snake": "A skilled climber that raids birds' nests.",
  "timber-rattlesnake": "Waits motionless for days to ambush prey.",
  "puff-adder": "Among the top snakebite killers across Africa.",
  "boomslang": "Rear fangs deliver a slow, deadly bleeding venom.",
  "eastern-green-mamba": "A shy tree-dweller with fast-acting venom.",
  "eyelash-viper": "Named for the spiny scales above its eyes.",
  "bullsnake": "Hisses and mimics a rattlesnake to scare foes.",
  "western-fox-snake": "Gives off a musk that smells like a fox.",
  "rosy-boa": "One of the slowest snakes — a calm, gentle crawler.",
  "kenyan-sand-boa": "Buries itself in sand to ambush from below.",
  "emerald-tree-boa": "Newborns are red or orange, not green.",
  "carpet-python": "Senses body heat with pits along its lips.",
  "blood-python": "Short, thick, and famous for its blood-red blotches.",
  "common-death-adder": "Wiggles its tail tip like a worm to lure prey.",
  "tiger-snake": "Striped like a tiger with highly potent venom.",
  "inland-taipan": "Most venomous snake on Earth by drop of venom.",
  "fer-de-lance": "A leading cause of snakebite deaths in the tropics.",
  "saw-scaled-viper": "Rubs its scales together to make a sizzling sound.",
  "russells-viper": "Kills thousands across Asia every single year.",
  "monocled-cobra": "Hood bears a single ring like an eye.",
  "mozambique-spitting-cobra": "Spits venom at the eyes from several feet away.",
  "asian-vine-snake": "Has odd keyhole-shaped pupils.",
  "common-egg-eater": "Swallows whole eggs and spits out the shell.",
  "rubber-boa": "Feels rubbery and uses its blunt tail as a decoy.",
  "northern-water-snake": "Harmless but often mistaken for a cottonmouth.",
  "prairie-rattlesnake": "Dens in huge groups through the cold winter.",
  "cape-cobra": "One of Africa's most dangerous cobras.",
  "malayan-pit-viper": "Its venom is used to make a real blood thinner.",
  "waglers-pit-viper": "The famous 'temple viper' left free to roam shrines.",
  "rhinoceros-viper": "Sports a cluster of horns on its nose.",
  "desert-horned-viper": "Buries in sand with only its horned eyes showing.",
  "mangrove-snake": "Glossy black with striking yellow bands.",
  "paradise-flying-snake": "Glides between trees by flattening its body.",
  "sunbeam-snake": "Scales shimmer with a rainbow sheen in sunlight.",
  "cape-mole-snake": "Burrows underground chasing golden moles.",
  "okinawa-habu": "Once feared enough to be pickled in local liquor.",
  "japanese-mamushi": "Japan's most common cause of snakebite.",
  "neotropical-rattlesnake": "Its venom can attack the nerves and vision.",
  "terciopelo": "A deadly lancehead behind many tropical snakebites.",
  "aesculapian-snake": "The snake curled on the medical symbol.",
  "smooth-snake": "Constricts its prey despite being non-venomous.",
  "ringneck-snake": "Flashes a bright belly and coils its tail when scared.",
  "scarlet-snake": "A harmless mimic of the venomous coral snake.",
  "sharp-nosed-viper": "Nicknamed 'hundred-pacer' for its fast venom.",
  "eastern-worm-snake": "Tiny and worm-like, it lives hidden underground.",
  "red-bellied-mud-snake": "Pokes with a pointed tail — the 'stinging snake' myth.",
  "rainbow-snake": "Glossy scales shine red, black, and yellow.",
  "green-bush-viper": "A vivid green ambush hunter that lives in trees.",
  "cat-eyed-snake": "Vertical cat-like pupils for hunting at night.",
  "coachwhip": "Fast racer with a tail patterned like a braided whip.",
  "banded-krait": "Bold black-and-yellow bands with a ridged back.",
  "red-tailed-green-ratsnake": "Bright green body ending in a rusty-red tail.",
  "tentacled-snake": "Only snake with two tentacles on its snout.",
  "dragon-snake": "Three ridges of raised scales run down its back.",
  "elephant-trunk-snake": "Baggy, loose skin feels like an elephant's trunk.",
  "malagasy-leaf-nosed-snake": "Males and females grow different nose shapes.",
  "long-nosed-vine-snake": "A slender green snake with a pointed snout.",
  "twig-snake": "Freezes stiff like a twig to hide in plain sight.",
  "spider-tailed-horned-viper": "Wiggles a spider-like tail to lure in birds.",
  "mangshan-pit-viper": "A rare giant viper found on one Chinese mountain.",
  "aruba-rattlesnake": "Lives only on the tiny island of Aruba.",
  "calabar-burrowing-python": "Uses its blunt tail as a fake second head.",
  "brahminy-blind-snake": "All-female species — every one is a clone.",
  "blue-krait": "One of Asia's deadliest land snakes.",
  "banded-sea-krait": "A sea snake that returns to land to lay eggs.",
  "yellow-bellied-sea-snake": "The only snake living in the open ocean.",
  "blunt-headed-tree-snake": "Huge eyes on a pencil-thin body for night hunting.",
  "speckled-racer": "Speckles of blue and yellow flash as it races.",
  "eastern-indigo-snake": "Longest native snake in the United States.",
  "many-horned-adder": "Wears a cluster of tiny horns above each eye.",
  "tiger-keelback": "Steals toad toxins to make its own defense.",
  "west-african-carpet-viper": "West Africa's deadliest snake by bite count.",
  "arafura-file-snake": "Rough file-like skin grips slippery fish.",
  "false-water-cobra": "Flattens its neck into a hood but isn't a cobra.",
  "green-cat-eyed-snake": "Emerald green with slit cat-like eyes.",
  "ornate-flying-snake": "Glides tree to tree by flattening into a ribbon.",
  "peringueys-adder": "Buries in dunes with its eyes on top of its head.",
};
