// E23 — Guess the Snake. 100 snakes, 25 per difficulty tier.
// image: snakes/<slug>.jpg (objectFit cover) | VO: sfx/sn-<slug>.wav ("It's the <name>!")
// images from iNaturalist (CC0/CC-BY only). iNat is CLEAN for reptiles (adults, no life-stage issue).
export const SNAKES = [
  // ===== EASY (25) =====
  { slug: "king-cobra", name: "King Cobra", sci: "Ophiophagus hannah", level: "easy" },
  { slug: "ball-python", name: "Ball Python", sci: "Python regius", level: "easy" },
  { slug: "boa-constrictor", name: "Boa Constrictor", sci: "Boa constrictor", level: "easy" },
  { slug: "green-anaconda", name: "Green Anaconda", sci: "Eunectes murinus", level: "easy" },
  { slug: "western-diamondback-rattlesnake", name: "Western Diamondback Rattlesnake", sci: "Crotalus atrox", level: "easy" },
  { slug: "corn-snake", name: "Corn Snake", sci: "Pantherophis guttatus", level: "easy" },
  { slug: "black-mamba", name: "Black Mamba", sci: "Dendroaspis polylepis", level: "easy" },
  { slug: "cottonmouth", name: "Cottonmouth", sci: "Agkistrodon piscivorus", level: "easy" },
  { slug: "copperhead", name: "Copperhead", sci: "Agkistrodon contortrix", level: "easy" },
  { slug: "common-garter-snake", name: "Garter Snake", sci: "Thamnophis sirtalis", level: "easy" },
  { slug: "reticulated-python", name: "Reticulated Python", sci: "Malayopython reticulatus", level: "easy" },
  { slug: "burmese-python", name: "Burmese Python", sci: "Python bivittatus", level: "easy" },
  { slug: "california-kingsnake", name: "King Snake", sci: "Lampropeltis californiae", level: "easy" },
  { slug: "eastern-milk-snake", name: "Milk Snake", sci: "Lampropeltis triangulum", level: "easy" },
  { slug: "eastern-coral-snake", name: "Coral Snake", sci: "Micrurus fulvius", level: "easy" },
  { slug: "gaboon-viper", name: "Gaboon Viper", sci: "Bitis gabonica", level: "easy" },
  { slug: "green-tree-python", name: "Green Tree Python", sci: "Morelia viridis", level: "easy" },
  { slug: "sidewinder", name: "Sidewinder", sci: "Crotalus cerastes", level: "easy" },
  { slug: "eastern-hognose-snake", name: "Hognose Snake", sci: "Heterodon platirhinos", level: "easy" },
  { slug: "bushmaster", name: "Bushmaster", sci: "Lachesis muta", level: "easy" },
  { slug: "indian-cobra", name: "Indian Cobra", sci: "Naja naja", level: "easy" },
  { slug: "egyptian-cobra", name: "Egyptian Cobra", sci: "Naja haje", level: "easy" },
  { slug: "grass-snake", name: "Grass Snake", sci: "Natrix natrix", level: "easy" },
  { slug: "black-rat-snake", name: "Rat Snake", sci: "Pantherophis obsoletus", level: "easy" },
  { slug: "timber-rattlesnake", name: "Timber Rattlesnake", sci: "Crotalus horridus", level: "easy" },

  // ===== MEDIUM (25) =====
  { slug: "puff-adder", name: "Puff Adder", sci: "Bitis arietans", level: "medium" },
  { slug: "boomslang", name: "Boomslang", sci: "Dispholidus typus", level: "medium" },
  { slug: "eastern-green-mamba", name: "Green Mamba", sci: "Dendroaspis angusticeps", level: "medium" },
  { slug: "eyelash-viper", name: "Eyelash Viper", sci: "Bothriechis schlegelii", level: "medium" },
  { slug: "bullsnake", name: "Bullsnake", sci: "Pituophis catenifer", level: "medium" },
  { slug: "western-fox-snake", name: "Fox Snake", sci: "Pantherophis vulpinus", level: "medium" },
  { slug: "rosy-boa", name: "Rosy Boa", sci: "Lichanura trivirgata", level: "medium" },
  { slug: "kenyan-sand-boa", name: "Sand Boa", sci: "Eryx colubrinus", level: "medium" },
  { slug: "emerald-tree-boa", name: "Emerald Tree Boa", sci: "Corallus caninus", level: "medium" },
  { slug: "carpet-python", name: "Carpet Python", sci: "Morelia spilota", level: "medium" },
  { slug: "blood-python", name: "Blood Python", sci: "Python brongersmai", level: "medium" },
  { slug: "common-death-adder", name: "Death Adder", sci: "Acanthophis antarcticus", level: "medium" },
  { slug: "tiger-snake", name: "Tiger Snake", sci: "Notechis scutatus", level: "medium" },
  { slug: "inland-taipan", name: "Inland Taipan", sci: "Oxyuranus microlepidotus", level: "medium" },
  { slug: "fer-de-lance", name: "Fer-de-lance", sci: "Bothrops atrox", level: "medium" },
  { slug: "saw-scaled-viper", name: "Saw-scaled Viper", sci: "Echis carinatus", level: "medium" },
  { slug: "russells-viper", name: "Russell's Viper", sci: "Daboia russelii", level: "medium" },
  { slug: "monocled-cobra", name: "Monocled Cobra", sci: "Naja kaouthia", level: "medium" },
  { slug: "mozambique-spitting-cobra", name: "Spitting Cobra", sci: "Naja mossambica", level: "medium" },
  { slug: "asian-vine-snake", name: "Vine Snake", sci: "Ahaetulla prasina", level: "medium" },
  { slug: "common-egg-eater", name: "Egg-eating Snake", sci: "Dasypeltis scabra", level: "medium" },
  { slug: "rubber-boa", name: "Rubber Boa", sci: "Charina bottae", level: "medium" },
  { slug: "northern-water-snake", name: "Water Snake", sci: "Nerodia sipedon", level: "medium" },
  { slug: "prairie-rattlesnake", name: "Prairie Rattlesnake", sci: "Crotalus viridis", level: "medium" },
  { slug: "cape-cobra", name: "Cape Cobra", sci: "Naja nivea", level: "medium" },

  // ===== HARD (25) =====
  { slug: "malayan-pit-viper", name: "Malayan Pit Viper", sci: "Calloselasma rhodostoma", level: "hard" },
  { slug: "waglers-pit-viper", name: "Wagler's Pit Viper", sci: "Tropidolaemus wagleri", level: "hard" },
  { slug: "rhinoceros-viper", name: "Rhinoceros Viper", sci: "Bitis nasicornis", level: "hard" },
  { slug: "desert-horned-viper", name: "Horned Viper", sci: "Cerastes cerastes", level: "hard" },
  { slug: "mangrove-snake", name: "Mangrove Snake", sci: "Boiga dendrophila", level: "hard" },
  { slug: "paradise-flying-snake", name: "Paradise Flying Snake", sci: "Chrysopelea paradisi", level: "hard" },
  { slug: "sunbeam-snake", name: "Sunbeam Snake", sci: "Xenopeltis unicolor", level: "hard" },
  { slug: "cape-mole-snake", name: "Mole Snake", sci: "Pseudaspis cana", level: "hard" },
  { slug: "okinawa-habu", name: "Habu", sci: "Protobothrops flavoviridis", level: "hard" },
  { slug: "japanese-mamushi", name: "Mamushi", sci: "Gloydius blomhoffii", level: "hard" },
  { slug: "neotropical-rattlesnake", name: "Cascabel", sci: "Crotalus durissus", level: "hard" },
  { slug: "terciopelo", name: "Terciopelo", sci: "Bothrops asper", level: "hard" },
  { slug: "aesculapian-snake", name: "Aesculapian Snake", sci: "Zamenis longissimus", level: "hard" },
  { slug: "smooth-snake", name: "Smooth Snake", sci: "Coronella austriaca", level: "hard" },
  { slug: "ringneck-snake", name: "Ringneck Snake", sci: "Diadophis punctatus", level: "hard" },
  { slug: "scarlet-snake", name: "Scarlet Snake", sci: "Cemophora coccinea", level: "hard" },
  { slug: "sharp-nosed-viper", name: "Hundred-pacer", sci: "Deinagkistrodon acutus", level: "hard" },
  { slug: "eastern-worm-snake", name: "Worm Snake", sci: "Carphophis amoenus", level: "hard" },
  { slug: "red-bellied-mud-snake", name: "Mud Snake", sci: "Farancia abacura", level: "hard" },
  { slug: "rainbow-snake", name: "Rainbow Snake", sci: "Farancia erytrogramma", level: "hard" },
  { slug: "green-bush-viper", name: "Bush Viper", sci: "Atheris squamigera", level: "hard" },
  { slug: "cat-eyed-snake", name: "Cat Snake", sci: "Leptodeira annulata", level: "hard" },
  { slug: "coachwhip", name: "Whip Snake", sci: "Masticophis flagellum", level: "hard" },
  { slug: "banded-krait", name: "Banded Krait", sci: "Bungarus fasciatus", level: "hard" },
  { slug: "red-tailed-green-ratsnake", name: "Red-tailed Green Ratsnake", sci: "Gonyosoma oxycephalum", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { slug: "tentacled-snake", name: "Tentacled Snake", sci: "Erpeton tentaculatum", level: "impossible" },
  { slug: "dragon-snake", name: "Dragon Snake", sci: "Xenodermus javanicus", level: "impossible" },
  { slug: "elephant-trunk-snake", name: "Elephant Trunk Snake", sci: "Acrochordus javanicus", level: "impossible" },
  { slug: "malagasy-leaf-nosed-snake", name: "Malagasy Leaf-nosed Snake", sci: "Langaha madagascariensis", level: "impossible" },
  { slug: "long-nosed-vine-snake", name: "Long-nosed Vine Snake", sci: "Ahaetulla nasuta", level: "impossible" },
  { slug: "twig-snake", name: "Twig Snake", sci: "Thelotornis capensis", level: "impossible" },
  { slug: "spider-tailed-horned-viper", name: "Spider-tailed Horned Viper", sci: "Pseudocerastes urarachnoides", level: "impossible" },
  { slug: "mangshan-pit-viper", name: "Mangshan Pit Viper", sci: "Protobothrops mangshanensis", level: "impossible" },
  { slug: "aruba-rattlesnake", name: "Aruba Rattlesnake", sci: "Crotalus unicolor", level: "impossible" },
  { slug: "calabar-burrowing-python", name: "Calabar Burrowing Python", sci: "Calabaria reinhardtii", level: "impossible" },
  { slug: "brahminy-blind-snake", name: "Brahminy Blind Snake", sci: "Indotyphlops braminus", level: "impossible" },
  { slug: "blue-krait", name: "Blue Krait", sci: "Bungarus candidus", level: "impossible" },
  { slug: "banded-sea-krait", name: "Sea Krait", sci: "Laticauda colubrina", level: "impossible" },
  { slug: "yellow-bellied-sea-snake", name: "Yellow-bellied Sea Snake", sci: "Hydrophis platurus", level: "impossible" },
  { slug: "blunt-headed-tree-snake", name: "Blunt-headed Tree Snake", sci: "Imantodes cenchoa", level: "impossible" },
  { slug: "speckled-racer", name: "Speckled Racer", sci: "Drymobius margaritiferus", level: "impossible" },
  { slug: "eastern-indigo-snake", name: "Indigo Snake", sci: "Drymarchon couperi", level: "impossible" },
  { slug: "many-horned-adder", name: "Many-horned Adder", sci: "Bitis cornuta", level: "impossible" },
  { slug: "tiger-keelback", name: "Tiger Keelback", sci: "Rhabdophis tigrinus", level: "impossible" },
  { slug: "west-african-carpet-viper", name: "Ocellated Carpet Viper", sci: "Echis ocellatus", level: "impossible" },
  { slug: "arafura-file-snake", name: "File Snake", sci: "Acrochordus arafurae", level: "impossible" },
  { slug: "false-water-cobra", name: "False Water Cobra", sci: "Hydrodynastes gigas", level: "impossible" },
  { slug: "green-cat-eyed-snake", name: "Green Cat-eyed Snake", sci: "Boiga cyanea", level: "impossible" },
  { slug: "ornate-flying-snake", name: "Ornate Flying Snake", sci: "Chrysopelea ornata", level: "impossible" },
  { slug: "peringueys-adder", name: "Peringuey's Adder", sci: "Bitis peringueyi", level: "impossible" },
];
