// E226 emoji-song facts — one verified <=70-char fact per song, shown on reveal.
export const SONG_EMOJI6_FACTS = {
  // EASY
  "ring-of-fire": "1963 Johnny Cash hit written by June Carter Cash.",
  "payphone": "2012 Maroon 5 hit featuring rapper Wiz Khalifa.",
  "party-in-the-usa": "2009 Miley Cyrus pop hit and radio smash.",
  "i-wanna-dance-with-somebody": "1987 Whitney Houston No. 1 dance-pop hit.",
  "vogue": "1990 Madonna hit that popularized voguing dance.",
  "since-u-been-gone": "2004 Kelly Clarkson pop-rock breakup anthem.",
  "what-do-you-mean": "2015 Justin Bieber comeback single, a US No. 1.",
  "traitor": "2023 Olivia Rodrigo ballad from the album GUTS.",
  "as-it-was": "2022 Harry Styles hit, his longest-running No. 1.",
  "espresso": "2024 Sabrina Carpenter summer smash hit.",
  "lover": "2019 Taylor Swift title track and wedding-song favorite.",
  "fearless": "2008 Taylor Swift title track from her second album.",
  "karma": "2022 Taylor Swift track from the album Midnights.",
  "snooze": "2022 SZA hit from the album SOS.",
  "good-4-u": "2021 Olivia Rodrigo pop-punk No. 1 hit.",
  "drivers-license": "2021 Olivia Rodrigo debut single, a viral chart-topper.",
  "happier-than-ever": "2021 Billie Eilish title track that shifts genres midsong.",
  "ocean-eyes": "2016 Billie Eilish debut single that launched her career.",
  "when-the-partys-over": "2019 Billie Eilish ballad with a haunting piano line.",
  "no-time-to-die": "2020 Billie Eilish James Bond theme, won an Oscar.",
  "diamonds-are-forever": "1971 Shirley Bassey Bond theme song.",
  "live-and-let-die": "1973 Paul McCartney and Wings Bond theme.",
  "writings-on-the-wall": "2015 Sam Smith Bond theme for Spectre.",
  "fast-car": "1988 Tracy Chapman folk hit and Grammy winner.",
  "yesterday": "1965 Beatles ballad, one of the most covered songs ever.",

  // MEDIUM
  "mambo-no-5": "1999 Lou Bega hit sampling a 1949 Perez Prado tune.",
  "nothing-compares-2-u": "1990 Sinead O'Connor hit written by Prince.",
  "we-dont-talk-about-bruno": "2021 Encanto ensemble song, a surprise Billboard No. 1.",
  "surface-pressure": "2021 Encanto song sung by the character Luisa.",
  "common-people": "1995 Pulp Britpop anthem about class divides.",
  "the-boxer": "1969 Simon & Garfunkel folk-rock classic.",
  "blue-monday": "1983 New Order track, the best-selling 12-inch single ever.",
  "west-end-girls": "1984 Pet Shop Boys synth-pop UK and US No. 1.",
  "its-a-sin": "1987 Pet Shop Boys hit later used as a TV series title.",
  "video-killed-the-radio-star": "1979 The Buggles song, first video ever aired on MTV.",
  "danger-zone": "1986 Kenny Loggins song from the film Top Gun.",
  "flashdance-what-a-feeling": "1983 Irene Cara hit that won an Academy Award.",
  "maniac": "1983 Michael Sembello hit from the film Flashdance.",
  "st-elmos-fire": "1985 John Parr hit from the film St. Elmo's Fire.",
  "glory-of-love": "1986 Peter Cetera hit from The Karate Kid Part II.",
  "right-here-waiting": "1989 Richard Marx ballad, a US No. 1 hit.",
  "against-all-odds": "1984 Phil Collins ballad from the film of the same name.",
  "easy-lover": "1984 Philip Bailey and Phil Collins duet hit.",
  "sledgehammer": "1986 Peter Gabriel hit known for its claymation video.",
  "in-your-eyes": "1986 Peter Gabriel song famous from Say Anything.",
  "solsbury-hill": "1977 Peter Gabriel's first solo hit, written in 7/4 time.",
  "i-want-to-know-what-love-is": "1984 Foreigner power ballad, a US and UK No. 1.",
  "waiting-for-a-girl-like-you": "1981 Foreigner ballad, spent 10 weeks at US No. 2.",
  "faithfully": "1983 Journey power ballad written by Jonathan Cain.",
  "open-arms": "1981 Journey ballad, one of their biggest hits.",

  // HARD
  "iris": "1998 Goo Goo Dolls hit from the film City of Angels.",
  "kryptonite": "2000 3 Doors Down debut single, a rock radio staple.",
  "scar-tissue": "1999 Red Hot Chili Peppers hit, won a Grammy.",
  "everlong": "1997 Foo Fighters fan-favorite rock ballad.",
  "my-hero": "1997 Foo Fighters song written for everyday heroes.",
  "learn-to-fly": "1999 Foo Fighters hit with a famous costume video.",
  "best-of-you": "2005 Foo Fighters rock anthem, a Grammy nominee.",
  "in-bloom": "1991 Nirvana track from the album Nevermind.",
  "come-as-you-are": "1991 Nirvana single, second from Nevermind.",
  "fade-to-black": "1984 Metallica's first ballad, from Ride the Lightning.",
  "war-pigs": "1970 Black Sabbath anti-war metal classic.",
  "mama-im-coming-home": "1991 Ozzy Osbourne ballad co-written by Lemmy.",
  "no-more-tears": "1991 Ozzy Osbourne title track and rock radio hit.",
  "livin-after-midnight": "1980 Judas Priest anthem from British Steel.",
  "painkiller": "1990 Judas Priest title track, a speed-metal classic.",
  "do-you-hear-the-people-sing": "Les Miserables revolutionary anthem sung by the students.",
  "castle-on-a-cloud": "Les Miserables song sung by young Cosette.",
  "master-of-the-house": "Les Miserables comic song sung by the Thenardiers.",
  "one-day-more": "Les Miserables act one finale ensemble number.",
  "seasons-of-love": "Rent's opening number, famous for '525,600 minutes'.",
  "defying-gravity": "Wicked act one finale sung by Elphaba.",
  "popular": "Wicked song sung by Glinda to Elphaba.",
  "no-good-deed": "Wicked act two song sung by Elphaba.",
  "for-good": "Wicked duet between Elphaba and Glinda.",
  "music-of-the-night": "The Phantom of the Opera's signature ballad.",

  // IMPOSSIBLE
  "tarzan-boy": "1985 Baltimora Italo-disco hit known for its yodel-like hook.",
  "erotic-city": "1984 Prince B-side to Let's Go Crazy, a club favorite.",
  "sign-o-the-times": "1987 Prince title track, a stark funk-pop single.",
  "cream": "1991 Prince and the New Power Generation US No. 1 hit.",
  "lovecats": "1983 The Cure single with a playful upright-bass groove.",
  "this-charming-man": "1983 The Smiths breakthrough single.",
  "there-is-a-light-that-never-goes-out": "1986 The Smiths fan-favorite from The Queen Is Dead.",
  "how-soon-is-now": "1985 The Smiths song famous for its tremolo guitar riff.",
  "bizarre-love-triangle": "1986 New Order synth-pop favorite.",
  "country-house": "1995 Blur single that won the chart battle with Oasis.",
  "girls-and-boys": "1994 Blur single satirizing package-holiday romance.",
  "fake-plastic-trees": "1995 Radiohead single from The Bends.",
  "the-man-who-sold-the-world": "1970 David Bowie title track, later covered by Nirvana.",
  "otherside": "1999 Red Hot Chili Peppers single from Californication.",
  "ebony-and-ivory": "1982 Paul McCartney and Stevie Wonder duet, a US No. 1.",
  "say-say-say": "1983 Paul McCartney and Michael Jackson duet, a US No. 1.",
  "dirty-diana": "1988 Michael Jackson rock-tinged single from Bad.",
  "rock-with-you": "1979 Michael Jackson disco-funk single from Off the Wall.",
  "dont-stop-til-you-get-enough": "1979 Michael Jackson disco hit, his first solo US No. 1.",
  "pyt": "1982 Michael Jackson single from the album Thriller.",
  "cecilia": "1970 Simon & Garfunkel upbeat hit from Bridge Over Troubled Water.",
  "mr-tambourine-man": "1965 Bob Dylan song, a US No. 1 as covered by The Byrds.",
  "knockin-on-heavens-door": "1973 Bob Dylan song from the film Pat Garrett & Billy the Kid.",
  "the-times-they-are-a-changin": "1964 Bob Dylan protest-song title track.",
  "sound-of-silence": "1964 Simon & Garfunkel folk classic.",
};
