// E237 «Guess the Song by Emoji» (7th song episode) — 100 songs · 25/tier · clue via OpenMoji · VO: sfx/es-<id>.wav
export const SONG_EMOJI7 = [
  // ===== EASY (25) =====
  { id: "stayin-alive", title: "Stayin' Alive", emojis: "🕺💓", level: "easy" },
  { id: "hips-dont-lie", title: "Hips Don't Lie", emojis: "💃🤥", level: "easy" },
  { id: "castle-on-the-hill", title: "Castle on the Hill", emojis: "🏰⛰", level: "easy" },
  { id: "someone-you-loved", title: "Someone You Loved", emojis: "💔😢", level: "easy" },
  { id: "let-her-go", title: "Let Her Go", emojis: "👋💔", level: "easy" },
  { id: "get-lucky", title: "Get Lucky", emojis: "🍀🤖", level: "easy" },
  { id: "cotton-eye-joe", title: "Cotton Eye Joe", emojis: "🤠🐴", level: "easy" },
  { id: "what-is-love", title: "What Is Love", emojis: "❓❤", level: "easy" },
  { id: "i-gotta-feeling", title: "I Gotta Feeling", emojis: "🎉🥳", level: "easy" },
  { id: "sexy-and-i-know-it", title: "Sexy and I Know It", emojis: "😎💪", level: "easy" },
  { id: "one-more-time", title: "One More Time", emojis: "🔁⏰", level: "easy" },
  { id: "around-the-world", title: "Around the World", emojis: "🌍🔁", level: "easy" },
  { id: "blue-da-ba-dee", title: "Blue (Da Ba Dee)", emojis: "💙👽", level: "easy" },
  { id: "mr-blue-sky", title: "Mr. Blue Sky", emojis: "💙☀", level: "easy" },
  { id: "walking-on-sunshine", title: "Walking on Sunshine", emojis: "🚶☀", level: "easy" },
  { id: "i-want-to-hold-your-hand", title: "I Want to Hold Your Hand", emojis: "🤝❤", level: "easy" },
  { id: "all-you-need-is-love", title: "All You Need Is Love", emojis: "🌍❤", level: "easy" },
  { id: "holding-out-for-a-hero", title: "Holding Out for a Hero", emojis: "🦸⏳", level: "easy" },
  { id: "what-makes-you-beautiful", title: "What Makes You Beautiful", emojis: "😍💄", level: "easy" },
  { id: "thats-what-i-like", title: "That's What I Like", emojis: "👍😎", level: "easy" },
  { id: "jump-around", title: "Jump Around", emojis: "🦘🔄", level: "easy" },
  { id: "all-star", title: "All Star", emojis: "🌟🏆", level: "easy" },
  { id: "price-tag", title: "Price Tag", emojis: "🏷💰", level: "easy" },
  { id: "we-found-love", title: "We Found Love", emojis: "🔍❤", level: "easy" },
  { id: "we-are-young", title: "We Are Young", emojis: "🔥🌍", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "bailando", title: "Bailando", emojis: "💃🕺", level: "medium" },
  { id: "freed-from-desire", title: "Freed from Desire", emojis: "🔓💘", level: "medium" },
  { id: "cha-cha-slide", title: "Cha Cha Slide", emojis: "🕺👟", level: "medium" },
  { id: "turn-down-for-what", title: "Turn Down for What", emojis: "📢❓", level: "medium" },
  { id: "chasing-pavements", title: "Chasing Pavements", emojis: "🏃🛣", level: "medium" },
  { id: "skinny-love", title: "Skinny Love", emojis: "🥀💔", level: "medium" },
  { id: "a-thousand-years", title: "A Thousand Years", emojis: "⏳❤", level: "medium" },
  { id: "jar-of-hearts", title: "Jar of Hearts", emojis: "🫙❤", level: "medium" },
  { id: "permission-to-dance", title: "Permission to Dance", emojis: "🙋💃", level: "medium" },
  { id: "kill-this-love", title: "Kill This Love", emojis: "🔪❤", level: "medium" },
  { id: "how-you-like-that", title: "How You Like That", emojis: "😏👍", level: "medium" },
  { id: "mi-gente", title: "Mi Gente", emojis: "👥🎉", level: "medium" },
  { id: "taki-taki", title: "Taki Taki", emojis: "💃🔥", level: "medium" },
  { id: "loca", title: "Loca", emojis: "🤪💃", level: "medium" },
  { id: "danza-kuduro", title: "Danza Kuduro", emojis: "💃🥁", level: "medium" },
  { id: "gasolina", title: "Gasolina", emojis: "⛽💃", level: "medium" },
  { id: "dura", title: "Dura", emojis: "💪💃", level: "medium" },
  { id: "vivir-mi-vida", title: "Vivir Mi Vida", emojis: "🎉🕺", level: "medium" },
  { id: "bidi-bidi-bom-bom", title: "Bidi Bidi Bom Bom", emojis: "💓🎶", level: "medium" },
  { id: "suavemente", title: "Suavemente", emojis: "🌬💃", level: "medium" },
  { id: "dna", title: "DNA", emojis: "🧬❤", level: "medium" },
  { id: "idol", title: "Idol", emojis: "👑🎤", level: "medium" },
  { id: "ddu-du-ddu-du", title: "DDU-DU DDU-DU", emojis: "💥👑", level: "medium" },
  { id: "take-me-to-church", title: "Take Me to Church", emojis: "⛪🙏", level: "medium" },
  { id: "latch", title: "Latch", emojis: "🔒❤", level: "medium" },

  // ===== HARD (25) =====
  { id: "enjoy-the-silence", title: "Enjoy the Silence", emojis: "🤫🔇", level: "hard" },
  { id: "personal-jesus", title: "Personal Jesus", emojis: "🙏☎", level: "hard" },
  { id: "true-faith", title: "True Faith", emojis: "🙏✅", level: "hard" },
  { id: "just-like-heaven", title: "Just Like Heaven", emojis: "😇☁", level: "hard" },
  { id: "boys-dont-cry", title: "Boys Don't Cry", emojis: "👦🙅", level: "hard" },
  { id: "friday-im-in-love", title: "Friday I'm in Love", emojis: "📅❤", level: "hard" },
  { id: "no-surprises", title: "No Surprises", emojis: "😐❗", level: "hard" },
  { id: "karma-chameleon", title: "Karma Chameleon", emojis: "🦎🔄", level: "hard" },
  { id: "cars", title: "Cars", emojis: "🚗🎹", level: "hard" },
  { id: "dont-you-want-me", title: "Don't You Want Me", emojis: "🙅💕", level: "hard" },
  { id: "come-on-eileen", title: "Come On Eileen", emojis: "👋👧", level: "hard" },
  { id: "the-winner-takes-it-all", title: "The Winner Takes It All", emojis: "🏆🎴", level: "hard" },
  { id: "dancing-on-my-own", title: "Dancing on My Own", emojis: "💃🚶", level: "hard" },
  { id: "never-ever", title: "Never Ever", emojis: "🚫🔁", level: "hard" },
  { id: "wuthering-heights", title: "Wuthering Heights", emojis: "👻🏚", level: "hard" },
  { id: "running-up-that-hill", title: "Running Up That Hill", emojis: "🏃⛰", level: "hard" },
  { id: "toms-diner", title: "Tom's Diner", emojis: "☕🍽", level: "hard" },
  { id: "just-a-girl", title: "Just a Girl", emojis: "👧❗", level: "hard" },
  { id: "dont-speak", title: "Don't Speak", emojis: "🤐🚫", level: "hard" },
  { id: "shes-a-rainbow", title: "She's a Rainbow", emojis: "👩🌈", level: "hard" },
  { id: "the-gambler", title: "The Gambler", emojis: "🎰🤠", level: "hard" },
  { id: "9-to-5", title: "9 to 5", emojis: "⏰💼", level: "hard" },
  { id: "islands-in-the-stream", title: "Islands in the Stream", emojis: "🏝🎶", level: "hard" },
  { id: "independence-day", title: "Independence Day", emojis: "🎆🗽", level: "hard" },
  { id: "no-scrubs", title: "No Scrubs", emojis: "🧹🚫", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "institutionalized", title: "Institutionalized", emojis: "🏥🤪", level: "impossible" },
  { id: "where-is-my-mind", title: "Where Is My Mind?", emojis: "❓🧠", level: "impossible" },
  { id: "debaser", title: "Debaser", emojis: "🔪👁", level: "impossible" },
  { id: "the-killing-moon", title: "The Killing Moon", emojis: "🔪🌙", level: "impossible" },
  { id: "panic", title: "Panic", emojis: "😱📻", level: "impossible" },
  { id: "bigmouth-strikes-again", title: "Bigmouth Strikes Again", emojis: "👄⚡", level: "impossible" },
  { id: "life-on-mars", title: "Life on Mars?", emojis: "🪐❓", level: "impossible" },
  { id: "rebel-rebel", title: "Rebel Rebel", emojis: "🤘👑", level: "impossible" },
  { id: "just-like-honey", title: "Just Like Honey", emojis: "🍯💛", level: "impossible" },
  { id: "sowing-the-seeds-of-love", title: "Sowing the Seeds of Love", emojis: "🌱❤", level: "impossible" },
  { id: "mad-world", title: "Mad World", emojis: "🌍🤪", level: "impossible" },
  { id: "head-over-heels", title: "Head Over Heels", emojis: "🙃❤", level: "impossible" },
  { id: "melt-with-you", title: "Melt with You", emojis: "🍦❤", level: "impossible" },
  { id: "once-in-a-lifetime", title: "Once in a Lifetime", emojis: "⏳🌍", level: "impossible" },
  { id: "psycho-killer", title: "Psycho Killer", emojis: "🔪🤪", level: "impossible" },
  { id: "burning-down-the-house", title: "Burning Down the House", emojis: "🔥🏠", level: "impossible" },
  { id: "whip-it", title: "Whip It", emojis: "⚡👊", level: "impossible" },
  { id: "pop-muzik", title: "Pop Muzik", emojis: "🎵🤖", level: "impossible" },
  { id: "are-friends-electric", title: "Are 'Friends' Electric?", emojis: "🤖⚡", level: "impossible" },
  { id: "games-without-frontiers", title: "Games Without Frontiers", emojis: "🎮🚧", level: "impossible" },
  { id: "shock-the-monkey", title: "Shock the Monkey", emojis: "🐒⚡", level: "impossible" },
  { id: "land-of-confusion", title: "Land of Confusion", emojis: "🌍😵", level: "impossible" },
  { id: "tom-sawyer", title: "Tom Sawyer", emojis: "📖👦", level: "impossible" },
  { id: "limelight", title: "Limelight", emojis: "🔦⭐", level: "impossible" },
  { id: "kayleigh", title: "Kayleigh", emojis: "💐❤", level: "impossible" },
];
