// E226 «Guess the Song by Emoji» — 100 songs · 25/tier · clue via OpenMoji · VO: sfx/es-<id>.wav
export const SONG_EMOJI6 = [
  // ===== EASY (25) =====
  { id: "ring-of-fire", title: "Ring of Fire", emojis: "💍🔥", level: "easy" },
  { id: "payphone", title: "Payphone", emojis: "📞💔", level: "easy" },
  { id: "party-in-the-usa", title: "Party in the U.S.A.", emojis: "🎉🗽", level: "easy" },
  { id: "i-wanna-dance-with-somebody", title: "I Wanna Dance with Somebody", emojis: "💃🤝", level: "easy" },
  { id: "vogue", title: "Vogue", emojis: "📸🕺", level: "easy" },
  { id: "since-u-been-gone", title: "Since U Been Gone", emojis: "💔👋", level: "easy" },
  { id: "what-do-you-mean", title: "What Do You Mean", emojis: "❓🧐", level: "easy" },
  { id: "traitor", title: "Traitor", emojis: "🔪💔", level: "easy" },
  { id: "as-it-was", title: "As It Was", emojis: "⏳🔄", level: "easy" },
  { id: "espresso", title: "Espresso", emojis: "☕⚡", level: "easy" },
  { id: "lover", title: "Lover", emojis: "💕💍", level: "easy" },
  { id: "fearless", title: "Fearless", emojis: "🦁💪", level: "easy" },
  { id: "karma", title: "Karma", emojis: "😇👿", level: "easy" },
  { id: "snooze", title: "Snooze", emojis: "⏰😴", level: "easy" },
  { id: "good-4-u", title: "good 4 u", emojis: "😡👍", level: "easy" },
  { id: "drivers-license", title: "drivers license", emojis: "🚗🔑", level: "easy" },
  { id: "happier-than-ever", title: "Happier Than Ever", emojis: "😊💥", level: "easy" },
  { id: "ocean-eyes", title: "Ocean Eyes", emojis: "🌊👀", level: "easy" },
  { id: "when-the-partys-over", title: "when the party's over", emojis: "🎉🛑", level: "easy" },
  { id: "no-time-to-die", title: "No Time to Die", emojis: "⏰💀", level: "easy" },
  { id: "diamonds-are-forever", title: "Diamonds Are Forever", emojis: "💎👑", level: "easy" },
  { id: "live-and-let-die", title: "Live and Let Die", emojis: "🌱💀", level: "easy" },
  { id: "writings-on-the-wall", title: "Writing's on the Wall", emojis: "📝🧱", level: "easy" },
  { id: "fast-car", title: "Fast Car", emojis: "🚗💨", level: "easy" },
  { id: "yesterday", title: "Yesterday", emojis: "📅🔙", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "mambo-no-5", title: "Mambo No. 5", emojis: "🔢💃", level: "medium" },
  { id: "nothing-compares-2-u", title: "Nothing Compares 2 U", emojis: "🚫💔", level: "medium" },
  { id: "we-dont-talk-about-bruno", title: "We Don't Talk About Bruno", emojis: "🤐🙅", level: "medium" },
  { id: "surface-pressure", title: "Surface Pressure", emojis: "💪😖", level: "medium" },
  { id: "common-people", title: "Common People", emojis: "🙋👥", level: "medium" },
  { id: "the-boxer", title: "The Boxer", emojis: "🥊😢", level: "medium" },
  { id: "blue-monday", title: "Blue Monday", emojis: "😢📅", level: "medium" },
  { id: "west-end-girls", title: "West End Girls", emojis: "🌆👧", level: "medium" },
  { id: "its-a-sin", title: "It's a Sin", emojis: "⛪❌", level: "medium" },
  { id: "video-killed-the-radio-star", title: "Video Killed the Radio Star", emojis: "📺📻", level: "medium" },
  { id: "danger-zone", title: "Danger Zone", emojis: "🚨✈", level: "medium" },
  { id: "flashdance-what-a-feeling", title: "Flashdance... What a Feeling", emojis: "💃✨", level: "medium" },
  { id: "maniac", title: "Maniac", emojis: "😵💃", level: "medium" },
  { id: "st-elmos-fire", title: "St. Elmo's Fire", emojis: "🔥🏃", level: "medium" },
  { id: "glory-of-love", title: "Glory of Love", emojis: "🏆💕", level: "medium" },
  { id: "right-here-waiting", title: "Right Here Waiting", emojis: "📍⏳", level: "medium" },
  { id: "against-all-odds", title: "Against All Odds", emojis: "🎲🚫", level: "medium" },
  { id: "easy-lover", title: "Easy Lover", emojis: "😎💘", level: "medium" },
  { id: "sledgehammer", title: "Sledgehammer", emojis: "🔨💥", level: "medium" },
  { id: "in-your-eyes", title: "In Your Eyes", emojis: "👀💕", level: "medium" },
  { id: "solsbury-hill", title: "Solsbury Hill", emojis: "🏔🚶", level: "medium" },
  { id: "i-want-to-know-what-love-is", title: "I Want to Know What Love Is", emojis: "❓💘", level: "medium" },
  { id: "waiting-for-a-girl-like-you", title: "Waiting for a Girl Like You", emojis: "⏳👧", level: "medium" },
  { id: "faithfully", title: "Faithfully", emojis: "🙏💍", level: "medium" },
  { id: "open-arms", title: "Open Arms", emojis: "👐💕", level: "medium" },

  // ===== HARD (25) =====
  { id: "iris", title: "Iris", emojis: "👀🌼", level: "hard" },
  { id: "kryptonite", title: "Kryptonite", emojis: "🦸💎", level: "hard" },
  { id: "scar-tissue", title: "Scar Tissue", emojis: "🩹💪", level: "hard" },
  { id: "everlong", title: "Everlong", emojis: "⏳🔁", level: "hard" },
  { id: "my-hero", title: "My Hero", emojis: "🦸👏", level: "hard" },
  { id: "learn-to-fly", title: "Learn to Fly", emojis: "🐦📖", level: "hard" },
  { id: "best-of-you", title: "Best of You", emojis: "🏆👤", level: "hard" },
  { id: "in-bloom", title: "In Bloom", emojis: "🌸💥", level: "hard" },
  { id: "come-as-you-are", title: "Come as You Are", emojis: "👋🙋", level: "hard" },
  { id: "fade-to-black", title: "Fade to Black", emojis: "🌑🖤", level: "hard" },
  { id: "war-pigs", title: "War Pigs", emojis: "💣🐷", level: "hard" },
  { id: "mama-im-coming-home", title: "Mama, I'm Coming Home", emojis: "👩🏠", level: "hard" },
  { id: "no-more-tears", title: "No More Tears", emojis: "🚫😢", level: "hard" },
  { id: "livin-after-midnight", title: "Livin' After Midnight", emojis: "🌙🏍", level: "hard" },
  { id: "painkiller", title: "Painkiller", emojis: "💊🗡", level: "hard" },
  { id: "do-you-hear-the-people-sing", title: "Do You Hear the People Sing", emojis: "👂🎶", level: "hard" },
  { id: "castle-on-a-cloud", title: "Castle on a Cloud", emojis: "🏰☁", level: "hard" },
  { id: "master-of-the-house", title: "Master of the House", emojis: "🏠👑", level: "hard" },
  { id: "one-day-more", title: "One Day More", emojis: "📅➕", level: "hard" },
  { id: "seasons-of-love", title: "Seasons of Love", emojis: "🍂💕", level: "hard" },
  { id: "defying-gravity", title: "Defying Gravity", emojis: "🧙⬆", level: "hard" },
  { id: "popular", title: "Popular", emojis: "⭐🙋", level: "hard" },
  { id: "no-good-deed", title: "No Good Deed", emojis: "🚫🦹", level: "hard" },
  { id: "for-good", title: "For Good", emojis: "🤝🌿", level: "hard" },
  { id: "music-of-the-night", title: "Music of the Night", emojis: "🎭🌙", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "tarzan-boy", title: "Tarzan Boy", emojis: "🌴🗣", level: "impossible" },
  { id: "erotic-city", title: "Erotic City", emojis: "💋🌆", level: "impossible" },
  { id: "sign-o-the-times", title: "Sign o' the Times", emojis: "🚧⏰", level: "impossible" },
  { id: "cream", title: "Cream", emojis: "🥛👑", level: "impossible" },
  { id: "lovecats", title: "Lovecats", emojis: "🐱💘", level: "impossible" },
  { id: "this-charming-man", title: "This Charming Man", emojis: "🎩😍", level: "impossible" },
  { id: "there-is-a-light-that-never-goes-out", title: "There Is a Light That Never Goes Out", emojis: "💡🌌", level: "impossible" },
  { id: "how-soon-is-now", title: "How Soon Is Now", emojis: "⏱❓", level: "impossible" },
  { id: "bizarre-love-triangle", title: "Bizarre Love Triangle", emojis: "🔺💘", level: "impossible" },
  { id: "country-house", title: "Country House", emojis: "🌾🏠", level: "impossible" },
  { id: "girls-and-boys", title: "Girls & Boys", emojis: "👧👦", level: "impossible" },
  { id: "fake-plastic-trees", title: "Fake Plastic Trees", emojis: "🌳🚫", level: "impossible" },
  { id: "the-man-who-sold-the-world", title: "The Man Who Sold the World", emojis: "🧑🌍", level: "impossible" },
  { id: "otherside", title: "Otherside", emojis: "🚪🌗", level: "impossible" },
  { id: "ebony-and-ivory", title: "Ebony and Ivory", emojis: "🎹🤝", level: "impossible" },
  { id: "say-say-say", title: "Say Say Say", emojis: "🗣💬", level: "impossible" },
  { id: "dirty-diana", title: "Dirty Diana", emojis: "💧👑", level: "impossible" },
  { id: "rock-with-you", title: "Rock with You", emojis: "🪨🕺", level: "impossible" },
  { id: "dont-stop-til-you-get-enough", title: "Don't Stop 'Til You Get Enough", emojis: "🕺🔁", level: "impossible" },
  { id: "pyt", title: "P.Y.T. (Pretty Young Thing)", emojis: "😍👧", level: "impossible" },
  { id: "cecilia", title: "Cecilia", emojis: "😴💔", level: "impossible" },
  { id: "mr-tambourine-man", title: "Mr. Tambourine Man", emojis: "🥁🎶", level: "impossible" },
  { id: "knockin-on-heavens-door", title: "Knockin' on Heaven's Door", emojis: "🚪😇", level: "impossible" },
  { id: "the-times-they-are-a-changin", title: "The Times They Are a-Changin'", emojis: "⏳🔀", level: "impossible" },
  { id: "sound-of-silence", title: "Sound of Silence", emojis: "🔇🎶", level: "impossible" },
];
