// E171 «Guess the Song by Emoji 3» — 100 songs · 25/tier
// VO: sfx/e171-<id>.wav
export const SONG_EMOJI_3 = [
  // ===== EASY (25) =====
  { id: "cake-by-the-ocean", title: "Cake by the Ocean", emojis: "🎂🌊", level: "easy" },
  { id: "yellow-submarine", title: "Yellow Submarine", emojis: "🍋🚢", level: "easy" },
  { id: "sk8er-boi", title: "Sk8er Boi", emojis: "🛹👦", level: "easy" },
  { id: "fireflies", title: "Fireflies", emojis: "🔥🪰", level: "easy" },
  { id: "rockstar", title: "Rockstar", emojis: "🎸⭐", level: "easy" },
  { id: "starboy", title: "Starboy", emojis: "⭐👦", level: "easy" },
  { id: "dynamite", title: "Dynamite", emojis: "🧨🎵", level: "easy" },
  { id: "butter", title: "Butter", emojis: "🧈🎵", level: "easy" },
  { id: "peaches", title: "Peaches", emojis: "🍑🎵", level: "easy" },
  { id: "ghost", title: "Ghost", emojis: "👻🎵", level: "easy" },
  { id: "moonlight", title: "Moonlight", emojis: "🌙💡", level: "easy" },
  { id: "gold-digger", title: "Gold Digger", emojis: "🥇⛏", level: "easy" },
  { id: "paper-planes", title: "Paper Planes", emojis: "📄✈", level: "easy" },
  { id: "hot-n-cold", title: "Hot n Cold", emojis: "🔥❄", level: "easy" },
  { id: "dark-horse", title: "Dark Horse", emojis: "🌑🐴", level: "easy" },
  { id: "love-story", title: "Love Story", emojis: "💕📖", level: "easy" },
  { id: "anti-hero", title: "Anti-Hero", emojis: "🚫🦸", level: "easy" },
  { id: "paparazzi", title: "Paparazzi", emojis: "📸💃", level: "easy" },
  { id: "teenage-dream", title: "Teenage Dream", emojis: "🧑💭", level: "easy" },
  { id: "california-gurls", title: "California Gurls", emojis: "🌴👧", level: "easy" },
  { id: "rain-on-me", title: "Rain on Me", emojis: "🌧🙋", level: "easy" },
  { id: "bad-romance", title: "Bad Romance", emojis: "😈💋", level: "easy" },
  { id: "black-widow", title: "Black Widow", emojis: "🖤🕷", level: "easy" },
  { id: "sweet-emotion", title: "Sweet Emotion", emojis: "🍬😢", level: "easy" },
  { id: "crazy-train", title: "Crazy Train", emojis: "🤪🚂", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "dream-on", title: "Dream On", emojis: "💭▶", level: "medium" },
  { id: "walk-this-way", title: "Walk This Way", emojis: "🚶➡", level: "medium" },
  { id: "man-in-the-mirror", title: "Man in the Mirror", emojis: "👨🪞", level: "medium" },
  { id: "beat-it", title: "Beat It", emojis: "👊🚪", level: "medium" },
  { id: "paradise-city", title: "Paradise City", emojis: "🌴🏙", level: "medium" },
  { id: "welcome-to-the-jungle", title: "Welcome to the Jungle", emojis: "🌴🐯", level: "medium" },
  { id: "patience", title: "Patience", emojis: "⏳🎸", level: "medium" },
  { id: "runaway", title: "Runaway", emojis: "🏃➡", level: "medium" },
  { id: "wanted-dead-or-alive", title: "Wanted Dead or Alive", emojis: "💀🤠", level: "medium" },
  { id: "you-give-love-a-bad-name", title: "You Give Love a Bad Name", emojis: "💘🔫", level: "medium" },
  { id: "jump", title: "Jump", emojis: "🦘🎸", level: "medium" },
  { id: "somebody-to-love", title: "Somebody to Love", emojis: "🙋💗", level: "medium" },
  { id: "under-pressure", title: "Under Pressure", emojis: "⬇😖", level: "medium" },
  { id: "we-are-the-champions", title: "We Are the Champions", emojis: "🏆🎤", level: "medium" },
  { id: "another-one-bites-the-dust", title: "Another One Bites the Dust", emojis: "🎸💀", level: "medium" },
  { id: "crazy-little-thing-called-love", title: "Crazy Little Thing Called Love", emojis: "🤪💗", level: "medium" },
  { id: "i-want-to-break-free", title: "I Want to Break Free", emojis: "⛓🕊", level: "medium" },
  { id: "bicycle-race", title: "Bicycle Race", emojis: "🚲🏁", level: "medium" },
  { id: "radio-ga-ga", title: "Radio Ga Ga", emojis: "📻👶", level: "medium" },
  { id: "hot-stuff", title: "Hot Stuff", emojis: "🔥🎤", level: "medium" },
  { id: "i-feel-love", title: "I Feel Love", emojis: "💗🕺", level: "medium" },
  { id: "heaven", title: "Heaven", emojis: "😇🎸", level: "medium" },
  { id: "summer-of-69", title: "Summer of '69", emojis: "☀🎸", level: "medium" },
  { id: "take-my-breath-away", title: "Take My Breath Away", emojis: "💨💋", level: "medium" },
  { id: "the-power-of-love", title: "The Power of Love", emojis: "💪💗", level: "medium" },

  // ===== HARD (25) =====
  { id: "tears-in-heaven", title: "Tears in Heaven", emojis: "😢😇", level: "hard" },
  { id: "voodoo-child", title: "Voodoo Child", emojis: "🧙👶", level: "hard" },
  { id: "sunshine-of-your-love", title: "Sunshine of Your Love", emojis: "☀💗", level: "hard" },
  { id: "born-to-be-wild", title: "Born to Be Wild", emojis: "🏍🐯", level: "hard" },
  { id: "house-of-the-rising-sun", title: "House of the Rising Sun", emojis: "🏠🌅", level: "hard" },
  { id: "brown-eyed-girl", title: "Brown Eyed Girl", emojis: "🤎👁", level: "hard" },
  { id: "american-pie", title: "American Pie", emojis: "🦅🥧", level: "hard" },
  { id: "fire-and-rain", title: "Fire and Rain", emojis: "🔥🌧", level: "hard" },
  { id: "your-song", title: "Your Song", emojis: "🎼🎁", level: "hard" },
  { id: "goodbye-yellow-brick-road", title: "Goodbye Yellow Brick Road", emojis: "👋🧱", level: "hard" },
  { id: "take-me-home-country-roads", title: "Take Me Home, Country Roads", emojis: "🏠🛣", level: "hard" },
  { id: "leaving-on-a-jet-plane", title: "Leaving on a Jet Plane", emojis: "✈👋", level: "hard" },
  { id: "horse-with-no-name", title: "A Horse with No Name", emojis: "🐴🚫", level: "hard" },
  { id: "lonely-boy", title: "Lonely Boy", emojis: "😢👦", level: "hard" },
  { id: "mellow-yellow", title: "Mellow Yellow", emojis: "🍋😌", level: "hard" },
  { id: "black-velvet", title: "Black Velvet", emojis: "🖤🧵", level: "hard" },
  { id: "brass-in-pocket", title: "Brass in Pocket", emojis: "🎺👖", level: "hard" },
  { id: "relax", title: "Relax", emojis: "😌🎤", level: "hard" },
  { id: "dont-you-forget-about-me", title: "Don't You (Forget About Me)", emojis: "🙅🧠", level: "hard" },
  { id: "spinning-wheel", title: "Spinning Wheel", emojis: "🎡🎺", level: "hard" },
  { id: "proud-mary", title: "Proud Mary", emojis: "🚢💃", level: "hard" },
  { id: "dream-weaver", title: "Dream Weaver", emojis: "💭🕸", level: "hard" },
  { id: "year-of-the-cat", title: "Year of the Cat", emojis: "📅🐈", level: "hard" },
  { id: "magic-carpet-ride", title: "Magic Carpet Ride", emojis: "🧞🏇", level: "hard" },
  { id: "walk-like-an-egyptian", title: "Walk Like an Egyptian", emojis: "🚶🐫", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "white-rabbit", title: "White Rabbit", emojis: "🐇🍄", level: "impossible" },
  { id: "in-a-gadda-da-vida", title: "In-A-Gadda-Da-Vida", emojis: "🌿🥁", level: "impossible" },
  { id: "season-of-the-witch", title: "Season of the Witch", emojis: "🍂🧙", level: "impossible" },
  { id: "green-onions", title: "Green Onions", emojis: "🧅🎹", level: "impossible" },
  { id: "fortunate-son", title: "Fortunate Son", emojis: "🍀👦", level: "impossible" },
  { id: "bad-moon-rising", title: "Bad Moon Rising", emojis: "😈🌙", level: "impossible" },
  { id: "have-you-ever-seen-the-rain", title: "Have You Ever Seen the Rain", emojis: "👁🌧", level: "impossible" },
  { id: "run-through-the-jungle", title: "Run Through the Jungle", emojis: "🏃🌴", level: "impossible" },
  { id: "spirit-in-the-sky", title: "Spirit in the Sky", emojis: "👻🌌", level: "impossible" },
  { id: "american-woman", title: "American Woman", emojis: "🦅👩", level: "impossible" },
  { id: "these-eyes", title: "These Eyes", emojis: "👀🎹", level: "impossible" },
  { id: "crimson-and-clover", title: "Crimson and Clover", emojis: "❤🍀", level: "impossible" },
  { id: "crystal-blue-persuasion", title: "Crystal Blue Persuasion", emojis: "🔮💙", level: "impossible" },
  { id: "sugar-sugar", title: "Sugar, Sugar", emojis: "🍬🍭", level: "impossible" },
  { id: "venus", title: "Venus", emojis: "🪐👩", level: "impossible" },
  { id: "hooked-on-a-feeling", title: "Hooked on a Feeling", emojis: "🪝💗", level: "impossible" },
  { id: "black-water", title: "Black Water", emojis: "🖤🌊", level: "impossible" },
  { id: "china-grove", title: "China Grove", emojis: "🀄🌳", level: "impossible" },
  { id: "listen-to-the-music", title: "Listen to the Music", emojis: "👂🎵", level: "impossible" },
  { id: "midnight-rider", title: "Midnight Rider", emojis: "🌃🏇", level: "impossible" },
  { id: "ramblin-man", title: "Ramblin' Man", emojis: "🚶🎸", level: "impossible" },
  { id: "spiders-and-snakes", title: "Spiders and Snakes", emojis: "🕷🐍", level: "impossible" },
  { id: "brand-new-key", title: "Brand New Key", emojis: "🔑🛼", level: "impossible" },
  { id: "long-train-runnin", title: "Long Train Runnin'", emojis: "🚂🏃", level: "impossible" },
  { id: "long-cool-woman", title: "Long Cool Woman", emojis: "🖤👗", level: "impossible" },
];
