// «Guess the Space Object» — GuessSync · E51 · did-you-know facts, ≤70 chars, verified true.
export const SPACE_FACTS = {
  // EASY
  "sun": "The star at the center of our Solar System",
  "moon": "Earth's only natural satellite, 384,000 km away",
  "earth": "The only known planet with life and liquid water",
  "mars": "The 'Red Planet', tinted by rusty iron-oxide dust",
  "jupiter": "The largest planet; a giant ball of gas",
  "saturn": "Famous for its bright, icy ring system",
  "venus": "The hottest planet, wrapped in thick clouds",
  "mercury": "The smallest planet and closest to the Sun",
  "uranus": "An ice giant that rotates tipped on its side",
  "neptune": "The windiest planet, a deep-blue ice giant",
  "pluto": "A dwarf planet with a huge heart-shaped plain",
  "milkyway": "The barred spiral galaxy that holds our Sun",
  "solar-eclipse": "When the Moon passes in front of the Sun",
  "iss": "A crewed laboratory orbiting about 400 km up",
  "hubble": "A space telescope launched in 1990, still working",
  "james-webb": "The largest space telescope, launched in 2021",
  "space-shuttle": "NASA's reusable winged spacecraft, 1981-2011",
  "halleys-comet": "A famous comet that returns about every 76 years",
  "andromeda-galaxy": "Our nearest large galaxy, 2.5M light-years away",
  "orion-nebula": "A bright stellar nursery in Orion's sword",
  "great-red-spot": "A giant storm on Jupiter, wider than Earth",
  "moon-landing": "Apollo 11 first landed humans on the Moon in 1969",
  "aurora": "Glowing lights from solar particles hitting the air",
  "saturn-v": "The giant rocket that sent Apollo to the Moon",
  "voyager": "Twin probes launched in 1977, now in deep space",
  // MEDIUM
  "titan": "Saturn's largest moon, with lakes of liquid methane",
  "europa": "A moon of Jupiter with a hidden ocean under ice",
  "io": "Jupiter's moon, the most volcanic world we know",
  "ganymede": "Jupiter's moon, the biggest moon in the Solar System",
  "callisto": "One of Jupiter's moons, heavily cratered and old",
  "phobos": "The larger, closer of Mars's two tiny moons",
  "enceladus": "Saturn's moon that jets icy geysers into space",
  "triton": "Neptune's largest moon; it orbits backwards",
  "whirlpool-galaxy": "A classic face-on spiral with a small companion",
  "sombrero-galaxy": "A galaxy shaped like a wide-brimmed hat",
  "pinwheel-galaxy": "A large, bright face-on spiral galaxy",
  "triangulum-galaxy": "The third-largest galaxy in our Local Group",
  "ring-nebula": "A glowing ring of gas cast off by a dying star",
  "crab-nebula": "The remnant of a supernova seen in 1054 AD",
  "eagle-nebula": "Star-forming cloud home to the Pillars of Creation",
  "horsehead-nebula": "A dark cloud shaped like a horse's head",
  "pillars-of-creation": "Towering gas columns in the Eagle Nebula",
  "pleiades": "A blue star cluster called the Seven Sisters",
  "curiosity-rover": "A car-sized NASA rover exploring Mars since 2012",
  "perseverance-rover": "A NASA rover hunting for past life on Mars",
  "cassini": "A probe that studied Saturn from 2004 to 2017",
  "comet-neowise": "A bright comet widely seen from Earth in 2020",
  "comet-hale-bopp": "A very bright comet widely seen in 1997",
  "olympus-mons": "The tallest volcano in the Solar System, on Mars",
  "carina-nebula": "A huge, bright nebula full of newborn stars",
  // HARD
  "deimos": "The smaller, outer moon of Mars",
  "mimas": "Saturn's moon with a crater like the Death Star",
  "iapetus": "Saturn's moon: one dark half, one bright half",
  "rhea": "Saturn's second-largest, heavily cratered moon",
  "miranda": "A moon of Uranus with dramatic cliffs and grooves",
  "ceres": "The largest asteroid, and also a dwarf planet",
  "vesta": "One of the largest asteroids in the main belt",
  "bennu": "A small asteroid visited by NASA's OSIRIS-REx",
  "ryugu": "An asteroid sampled by Japan's Hayabusa2 probe",
  "comet-67p": "The comet orbited by the Rosetta spacecraft",
  "centaurus-a": "A galaxy crossed by a striking dark dust lane",
  "cartwheel-galaxy": "A ring galaxy shaped by a past collision",
  "black-eye-galaxy": "A spiral with a dark dust band across its face",
  "large-magellanic-cloud": "A small galaxy orbiting the Milky Way",
  "small-magellanic-cloud": "A dwarf galaxy near the Milky Way",
  "cats-eye-nebula": "A complex glowing shell around a dying star",
  "helix-nebula": "A nearby ring nebula nicknamed the Eye of God",
  "lagoon-nebula": "A giant, glowing cloud where new stars are born",
  "tarantula-nebula": "A vast star-forming region in a nearby galaxy",
  "veil-nebula": "Wispy remains of a star that exploded long ago",
  "rosette-nebula": "A flower-shaped cloud of glowing hydrogen gas",
  "omega-centauri": "The brightest globular cluster in our sky",
  "hercules-cluster": "A dense ball of hundreds of thousands of stars",
  "betelgeuse": "A huge red supergiant star in Orion",
  "valles-marineris": "A vast canyon system stretching across Mars",
  // IMPOSSIBLE
  "itokawa": "A peanut-shaped asteroid visited by Hayabusa",
  "eros": "A large near-Earth asteroid, orbited by NEAR",
  "dione": "A cratered icy moon of Saturn",
  "tethys": "An icy moon of Saturn with a giant crater",
  "hyperion": "Saturn's sponge-like, oddly tumbling moon",
  "hoags-object": "A rare ring galaxy with a bright core",
  "antennae-galaxies": "Two galaxies colliding, with long tidal tails",
  "cigar-galaxy": "A galaxy bursting with new stars, called M82",
  "bodes-galaxy": "A bright grand-design spiral galaxy, M81",
  "needle-galaxy": "A spiral galaxy seen almost perfectly edge-on",
  "sunflower-galaxy": "A spiral galaxy with many short, patchy arms",
  "butterfly-nebula": "Gas wings cast off by a hot dying star",
  "ant-nebula": "A dying star's gas shaped like an ant",
  "boomerang-nebula": "One of the coldest known places in the universe",
  "owl-nebula": "A round nebula with two dark 'owl' eyes",
  "dumbbell-nebula": "A bright, easy-to-see planetary nebula",
  "red-spider-nebula": "A nebula with waves driven by a hot star",
  "47-tucanae": "A brilliant globular cluster of ancient stars",
  "new-horizons": "The probe that flew past Pluto in 2015",
  "parker-solar-probe": "A NASA probe flying through the Sun's corona",
  "juno": "A NASA spacecraft orbiting Jupiter since 2016",
  "sputnik": "The first artificial satellite, launched in 1957",
  "tycho-crater": "A bright young crater on the Moon, with rays",
  "eskimo-nebula": "A dying star shedding glowing shells of gas",
  "ngc1300": "A striking barred spiral galaxy, NGC 1300",
};
