// «Guess the Space Object» — GuessSync · E51 · 100 objects (25/tier) · real NASA/ESA/Wikimedia images
// Tiered by recognizability: EASY (Sun/Moon/planets/Milky Way) → IMPOSSIBLE (obscure nebulae/asteroids/probes).
export const SPACE = [
  // EASY (25)
  { slug: "sun", name: "The Sun", level: "easy" },
  { slug: "moon", name: "The Moon", level: "easy" },
  { slug: "earth", name: "Earth", level: "easy" },
  { slug: "mars", name: "Mars", level: "easy" },
  { slug: "jupiter", name: "Jupiter", level: "easy" },
  { slug: "saturn", name: "Saturn", level: "easy" },
  { slug: "venus", name: "Venus", level: "easy" },
  { slug: "mercury", name: "Mercury", level: "easy" },
  { slug: "uranus", name: "Uranus", level: "easy" },
  { slug: "neptune", name: "Neptune", level: "easy" },
  { slug: "pluto", name: "Pluto", level: "easy" },
  { slug: "milkyway", name: "The Milky Way", level: "easy" },
  { slug: "solar-eclipse", name: "Solar Eclipse", level: "easy" },
  { slug: "iss", name: "International Space Station", level: "easy" },
  { slug: "hubble", name: "Hubble Space Telescope", level: "easy" },
  { slug: "james-webb", name: "James Webb Space Telescope", level: "easy" },
  { slug: "space-shuttle", name: "Space Shuttle", level: "easy" },
  { slug: "halleys-comet", name: "Halley's Comet", level: "easy" },
  { slug: "andromeda-galaxy", name: "Andromeda Galaxy", level: "easy" },
  { slug: "orion-nebula", name: "Orion Nebula", level: "easy" },
  { slug: "great-red-spot", name: "Great Red Spot", level: "easy" },
  { slug: "moon-landing", name: "Apollo Moon Landing", level: "easy" },
  { slug: "aurora", name: "Aurora", level: "easy" },
  { slug: "saturn-v", name: "Saturn V Rocket", level: "easy" },
  { slug: "voyager", name: "Voyager Probe", level: "easy" },
  // MEDIUM (25)
  { slug: "titan", name: "Titan", level: "medium" },
  { slug: "europa", name: "Europa", level: "medium" },
  { slug: "io", name: "Io", level: "medium" },
  { slug: "ganymede", name: "Ganymede", level: "medium" },
  { slug: "callisto", name: "Callisto", level: "medium" },
  { slug: "phobos", name: "Phobos", level: "medium" },
  { slug: "enceladus", name: "Enceladus", level: "medium" },
  { slug: "triton", name: "Triton", level: "medium" },
  { slug: "whirlpool-galaxy", name: "Whirlpool Galaxy", level: "medium" },
  { slug: "sombrero-galaxy", name: "Sombrero Galaxy", level: "medium" },
  { slug: "pinwheel-galaxy", name: "Pinwheel Galaxy", level: "medium" },
  { slug: "triangulum-galaxy", name: "Triangulum Galaxy", level: "medium" },
  { slug: "ring-nebula", name: "Ring Nebula", level: "medium" },
  { slug: "crab-nebula", name: "Crab Nebula", level: "medium" },
  { slug: "eagle-nebula", name: "Eagle Nebula", level: "medium" },
  { slug: "horsehead-nebula", name: "Horsehead Nebula", level: "medium" },
  { slug: "pillars-of-creation", name: "Pillars of Creation", level: "medium" },
  { slug: "pleiades", name: "The Pleiades", level: "medium" },
  { slug: "curiosity-rover", name: "Curiosity Rover", level: "medium" },
  { slug: "perseverance-rover", name: "Perseverance Rover", level: "medium" },
  { slug: "cassini", name: "Cassini Spacecraft", level: "medium" },
  { slug: "comet-neowise", name: "Comet NEOWISE", level: "medium" },
  { slug: "comet-hale-bopp", name: "Comet Hale-Bopp", level: "medium" },
  { slug: "olympus-mons", name: "Olympus Mons", level: "medium" },
  { slug: "carina-nebula", name: "Carina Nebula", level: "medium" },
  // HARD (25)
  { slug: "deimos", name: "Deimos", level: "hard" },
  { slug: "mimas", name: "Mimas", level: "hard" },
  { slug: "iapetus", name: "Iapetus", level: "hard" },
  { slug: "rhea", name: "Rhea", level: "hard" },
  { slug: "miranda", name: "Miranda", level: "hard" },
  { slug: "ceres", name: "Ceres", level: "hard" },
  { slug: "vesta", name: "Vesta", level: "hard" },
  { slug: "bennu", name: "Bennu", level: "hard" },
  { slug: "ryugu", name: "Ryugu", level: "hard" },
  { slug: "comet-67p", name: "Comet 67P", level: "hard" },
  { slug: "centaurus-a", name: "Centaurus A", level: "hard" },
  { slug: "cartwheel-galaxy", name: "Cartwheel Galaxy", level: "hard" },
  { slug: "black-eye-galaxy", name: "Black Eye Galaxy", level: "hard" },
  { slug: "large-magellanic-cloud", name: "Large Magellanic Cloud", level: "hard" },
  { slug: "small-magellanic-cloud", name: "Small Magellanic Cloud", level: "hard" },
  { slug: "cats-eye-nebula", name: "Cat's Eye Nebula", level: "hard" },
  { slug: "helix-nebula", name: "Helix Nebula", level: "hard" },
  { slug: "lagoon-nebula", name: "Lagoon Nebula", level: "hard" },
  { slug: "tarantula-nebula", name: "Tarantula Nebula", level: "hard" },
  { slug: "veil-nebula", name: "Veil Nebula", level: "hard" },
  { slug: "rosette-nebula", name: "Rosette Nebula", level: "hard" },
  { slug: "omega-centauri", name: "Omega Centauri", level: "hard" },
  { slug: "hercules-cluster", name: "Hercules Globular Cluster", level: "hard" },
  { slug: "betelgeuse", name: "Betelgeuse", level: "hard" },
  { slug: "valles-marineris", name: "Valles Marineris", level: "hard" },
  // IMPOSSIBLE (25)
  { slug: "itokawa", name: "Itokawa", level: "impossible" },
  { slug: "eros", name: "Eros", level: "impossible" },
  { slug: "dione", name: "Dione", level: "impossible" },
  { slug: "tethys", name: "Tethys", level: "impossible" },
  { slug: "hyperion", name: "Hyperion", level: "impossible" },
  { slug: "hoags-object", name: "Hoag's Object", level: "impossible" },
  { slug: "antennae-galaxies", name: "Antennae Galaxies", level: "impossible" },
  { slug: "cigar-galaxy", name: "Cigar Galaxy", level: "impossible" },
  { slug: "bodes-galaxy", name: "Bode's Galaxy", level: "impossible" },
  { slug: "needle-galaxy", name: "Needle Galaxy", level: "impossible" },
  { slug: "sunflower-galaxy", name: "Sunflower Galaxy", level: "impossible" },
  { slug: "butterfly-nebula", name: "Butterfly Nebula", level: "impossible" },
  { slug: "ant-nebula", name: "Ant Nebula", level: "impossible" },
  { slug: "boomerang-nebula", name: "Boomerang Nebula", level: "impossible" },
  { slug: "owl-nebula", name: "Owl Nebula", level: "impossible" },
  { slug: "dumbbell-nebula", name: "Dumbbell Nebula", level: "impossible" },
  { slug: "red-spider-nebula", name: "Red Spider Nebula", level: "impossible" },
  { slug: "47-tucanae", name: "47 Tucanae", level: "impossible" },
  { slug: "new-horizons", name: "New Horizons Spacecraft", level: "impossible" },
  { slug: "parker-solar-probe", name: "Parker Solar Probe", level: "impossible" },
  { slug: "juno", name: "Juno Spacecraft", level: "impossible" },
  { slug: "sputnik", name: "Sputnik 1", level: "impossible" },
  { slug: "tycho-crater", name: "Tycho Crater", level: "impossible" },
  { slug: "eskimo-nebula", name: "NGC 2392", level: "impossible" },
  { slug: "ngc1300", name: "NGC 1300", level: "impossible" },
];
