// «Guess the Herb or Spice» — GuessSync · E62 · 100 herbs & spices (25/level) · real photos from Wikimedia Commons
// Absolute difficulty by global recognizability: easy (Basil/Cinnamon/Black Pepper) ← impossible (Asafoetida/Mahleb/Grains of Paradise).
export const SPICES = [
  // EASY (25) — kitchen staples everyone knows
  { slug: "basil", name: "Basil", level: "easy" },
  { slug: "oregano", name: "Oregano", level: "easy" },
  { slug: "cinnamon", name: "Cinnamon", level: "easy" },
  { slug: "blackpepper", name: "Black Pepper", level: "easy" },
  { slug: "ginger", name: "Ginger", level: "easy" },
  { slug: "rosemary", name: "Rosemary", level: "easy" },
  { slug: "thyme", name: "Thyme", level: "easy" },
  { slug: "parsley", name: "Parsley", level: "easy" },
  { slug: "mint", name: "Mint", level: "easy" },
  { slug: "cumin", name: "Cumin", level: "easy" },
  { slug: "paprika", name: "Paprika", level: "easy" },
  { slug: "turmeric", name: "Turmeric", level: "easy" },
  { slug: "nutmeg", name: "Nutmeg", level: "easy" },
  { slug: "cloves", name: "Cloves", level: "easy" },
  { slug: "bayleaf", name: "Bay Leaf", level: "easy" },
  { slug: "chili", name: "Chili", level: "easy" },
  { slug: "vanilla", name: "Vanilla", level: "easy" },
  { slug: "saffron", name: "Saffron", level: "easy" },
  { slug: "cardamom", name: "Cardamom", level: "easy" },
  { slug: "coriander", name: "Coriander", level: "easy" },
  { slug: "dill", name: "Dill", level: "easy" },
  { slug: "garlic", name: "Garlic", level: "easy" },
  { slug: "sage", name: "Sage", level: "easy" },
  { slug: "chives", name: "Chives", level: "easy" },
  { slug: "cayenne", name: "Cayenne Pepper", level: "easy" },
  // MEDIUM (25) — common but need thought
  { slug: "fennel", name: "Fennel Seed", level: "medium" },
  { slug: "mustardseed", name: "Mustard Seed", level: "medium" },
  { slug: "fenugreek", name: "Fenugreek", level: "medium" },
  { slug: "tarragon", name: "Tarragon", level: "medium" },
  { slug: "marjoram", name: "Marjoram", level: "medium" },
  { slug: "caraway", name: "Caraway", level: "medium" },
  { slug: "allspice", name: "Allspice", level: "medium" },
  { slug: "anise", name: "Anise", level: "medium" },
  { slug: "staranise", name: "Star Anise", level: "medium" },
  { slug: "whitepepper", name: "White Pepper", level: "medium" },
  { slug: "cilantro", name: "Cilantro", level: "medium" },
  { slug: "lemongrass", name: "Lemongrass", level: "medium" },
  { slug: "poppyseed", name: "Poppy Seed", level: "medium" },
  { slug: "sesame", name: "Sesame Seed", level: "medium" },
  { slug: "juniper", name: "Juniper Berry", level: "medium" },
  { slug: "peppermint", name: "Peppermint", level: "medium" },
  { slug: "chamomile", name: "Chamomile", level: "medium" },
  { slug: "horseradish", name: "Horseradish", level: "medium" },
  { slug: "wasabi", name: "Wasabi", level: "medium" },
  { slug: "chervil", name: "Chervil", level: "medium" },
  { slug: "savory", name: "Savory", level: "medium" },
  { slug: "curryleaf", name: "Curry Leaf", level: "medium" },
  { slug: "cubeb", name: "Cubeb Pepper", level: "medium" },
  { slug: "mace", name: "Mace", level: "medium" },
  { slug: "screwpine", name: "Pandan", level: "medium" },
  // HARD (25) — world spices, less familiar
  { slug: "sumac", name: "Sumac", level: "hard" },
  { slug: "zaatar", name: "Za'atar", level: "hard" },
  { slug: "galangal", name: "Galangal", level: "hard" },
  { slug: "nigella", name: "Nigella", level: "hard" },
  { slug: "amchoor", name: "Amchoor", level: "hard" },
  { slug: "ajwain", name: "Ajwain", level: "hard" },
  { slug: "annatto", name: "Annatto", level: "hard" },
  { slug: "epazote", name: "Epazote", level: "hard" },
  { slug: "sichuanpepper", name: "Sichuan Pepper", level: "hard" },
  { slug: "kaffirlime", name: "Kaffir Lime Leaf", level: "hard" },
  { slug: "lovage", name: "Lovage", level: "hard" },
  { slug: "hyssop", name: "Hyssop", level: "hard" },
  { slug: "borage", name: "Borage", level: "hard" },
  { slug: "angelica", name: "Angelica", level: "hard" },
  { slug: "sorrel", name: "Sorrel", level: "hard" },
  { slug: "rue", name: "Rue", level: "hard" },
  { slug: "safflower", name: "Safflower", level: "hard" },
  { slug: "grainsofparadise", name: "Grains of Paradise", level: "hard" },
  { slug: "longpepper", name: "Long Pepper", level: "hard" },
  { slug: "asafoetida", name: "Asafoetida", level: "hard" },
  { slug: "mahleb", name: "Mahleb", level: "hard" },
  { slug: "sansho", name: "Sansho", level: "hard" },
  { slug: "urfabiber", name: "Urfa Biber", level: "hard" },
  { slug: "alepposorpepper", name: "Aleppo Pepper", level: "hard" },
  { slug: "greencardamom", name: "Black Cardamom", level: "hard" },
  // IMPOSSIBLE (25) — obscure / regional / botanical
  { slug: "grainsofselim", name: "Grains of Selim", level: "impossible" },
  { slug: "tonkabean", name: "Tonka Bean", level: "impossible" },
  { slug: "wattleseed", name: "Wattleseed", level: "impossible" },
  { slug: "salep", name: "Salep", level: "impossible" },
  { slug: "kokum", name: "Kokum", level: "impossible" },
  { slug: "candlenut", name: "Candlenut", level: "impossible" },
  { slug: "voatsiperifery", name: "Voatsiperifery Pepper", level: "impossible" },
  { slug: "andaliman", name: "Andaliman", level: "impossible" },
  { slug: "mastic", name: "Mastic", level: "impossible" },
  { slug: "akudjura", name: "Akudjura", level: "impossible" },
  { slug: "pinkpepper", name: "Pink Peppercorn", level: "impossible" },
  { slug: "grainsofparadiseblack", name: "Alligator Pepper", level: "impossible" },
  { slug: "nagkesar", name: "Nagkesar", level: "impossible" },
  { slug: "kalpasi", name: "Kalpasi", level: "impossible" },
  { slug: "anardana", name: "Anardana", level: "impossible" },
  { slug: "zedoary", name: "Zedoary", level: "impossible" },
  { slug: "quassia", name: "Quassia", level: "impossible" },
  { slug: "calamus", name: "Calamus", level: "impossible" },
  { slug: "spikenard", name: "Spikenard", level: "impossible" },
  { slug: "orris", name: "Orris Root", level: "impossible" },
  { slug: "blacklime", name: "Black Lime (Loomi)", level: "impossible" },
  { slug: "fingerroot", name: "Fingerroot", level: "impossible" },
  { slug: "winteredsavory", name: "Culantro", level: "impossible" },
  { slug: "hoja", name: "Hoja Santa", level: "impossible" },
  { slug: "boldo", name: "Boldo", level: "impossible" },
];
