// «Guess the Spider» — GuessSync · E57 · did-you-know facts, ≤70 chars, verified true.
export const SPIDER_FACTS = {
  // EASY
  "tarantula": "Large hairy spider; most species are harmless to humans",
  "blackwidow": "Red hourglass mark; its venom is a potent neurotoxin",
  "wolfspider": "Hunts prey on foot instead of spinning a web",
  "jumpingspider": "Can leap many times its body length to catch prey",
  "daddylonglegs": "This cellar spider vibrates its web to blur when scared",
  "gardenspider": "Wears a white cross of spots on its round abdomen",
  "brownrecluse": "Has a violin-shaped mark; its bite can kill tissue",
  "huntsman": "Large, fast, flat spider that hides under bark and walls",
  "orbweaver": "Spins the classic wheel-shaped web to catch insects",
  "scorpion": "An arachnid with pincers and a venomous stinging tail",
  "camelspider": "Fast desert hunter that is neither spider nor scorpion",
  "housespider": "Common indoor spider that builds messy sheet webs",
  "redback": "Australian relative of the black widow with a red stripe",
  "funnelweb": "One of the world's deadliest spiders; fangs pierce nails",
  "crabspider": "Holds its front legs sideways and walks like a crab",
  "goldsilkorbweaver": "Its golden silk is strong enough to catch small birds",
  "fishingspider": "Walks on water and can dive to catch tiny fish",
  "zebraspider": "Tiny black-and-white jumper often seen on sunny walls",
  "jorospider": "Bright invasive orb-weaver that can balloon on the wind",
  "hobospider": "A funnel-weaver once blamed for wounds it rarely causes",
  "barnspider": "The spider that inspired Charlotte in Charlotte's Web",
  "grassspider": "Builds flat sheet webs with a funnel retreat in grass",
  "yellowsacspider": "Spins a silk sac to sleep in by day and hunts at night",
  "emperorscorpion": "One of the largest scorpions, yet its sting is mild",
  "writingspider": "Weaves a zigzag silk 'signature' down its web center",
  // MEDIUM
  "greenlynx": "Bright green hunter that can spit venom at attackers",
  "nurserywebspider": "Males offer a silk-wrapped insect gift to win a mate",
  "spittingspider": "Spits sticky venomous silk to glue prey in place",
  "woodlousespider": "Huge red fangs built to pierce armored woodlice",
  "wanderingspider": "A roaming hunter with one of the most toxic venoms",
  "mousespider": "Stout burrowing spider; males often have red jaws",
  "deathstalker": "A pale scorpion with one of the deadliest venoms",
  "barkscorpion": "The most venomous scorpion in North America",
  "vinegaroon": "Sprays a vinegar-smelling acid from its whip-like tail",
  "harvestman": "A daddy long-legs that is not a spider and has no venom",
  "waspspider": "Its yellow-and-black stripes mimic a warning of a wasp",
  "purseweb": "Strikes prey through the wall of its silken tube",
  "divingbellspider": "The only spider that lives its whole life underwater",
  "cavespider": "Lives in dark caves and hangs its eggs like teardrops",
  "longjawedorbweaver": "Slender spider that stretches thin along a reed or stem",
  "groundspider": "Fast nocturnal hunter with no web, roaming the ground",
  "spinyorbweaver": "Its hard shell has crab-like spines to deter predators",
  "pinktoetarantula": "A tree tarantula with pink tips on each of its feet",
  "mexicanredknee": "Docile tarantula with bright red-orange leg joints",
  "curlyhairtarantula": "Covered in long curling bronze-tipped hairs",
  "sixeyedsandspider": "Buries in sand; a relative of the deadly recluse",
  "bolasspider": "Swings a sticky glue ball to lasso passing moths",
  "pseudoscorpion": "Tiny pincered arachnid with no tail or stinger",
  "falsewidow": "Often mistaken for a black widow but far less harmful",
  "marbledorbweaver": "Its swollen orange belly earns it the name pumpkin spider",
  // HARD
  "arrowheadorbweaver": "Has a bright triangular arrowhead mark on its back",
  "candystripespider": "Small spider streaked with pink or red candy stripes",
  "cucumberspider": "A tiny leaf-green orb-weaver the color of a cucumber",
  "ladybirdspider": "The male's red spotted back mimics a ladybird beetle",
  "antmimicspider": "Waves its front legs like antennae to pose as an ant",
  "featherleggedspider": "One of the few spiders with no venom glands at all",
  "piratespider": "Invades other webs and eats the resident spider",
  "tentwebspider": "Weaves a dense dome-shaped web like a tiny tent",
  "greenhuntsman": "A vivid green huntsman that hides among fresh leaves",
  "cobaltbluetarantula": "Its legs shine an electric metallic blue in light",
  "gootysapphire": "A rare tarantula covered in dazzling metallic blue",
  "indianornamental": "A fast tree tarantula with striking geometric patterns",
  "braziliansalmonpink": "One of the biggest tarantulas, with pinkish leg hairs",
  "kingbaboonspider": "A large, slow African tarantula that hisses in defense",
  "greenbottleblue": "Blue legs, green shell and an orange belly, all at once",
  "orangebaboon": "A bright orange African tarantula famed for its temper",
  "twotailedspider": "Long twin spinnerets look like two tails at its rear",
  "scorpiontailedspider": "Curls a long tail-like tip over its back like a scorpion",
  "happyfacespider": "Hawaiian spider with a clown-like smiley pattern",
  "whipspider": "Flat, harmless arachnid with long whip-like feeler legs",
  "anteatingspider": "Hunts ants while disguising itself among the colony",
  "gardenorbweaver": "Rebuilds its large wheel web fresh almost every night",
  "regaljumper": "A large jumper with iridescent green fangs",
  "lichenhuntsman": "Mottled body vanishes against lichen-covered bark",
  "wraparoundspider": "Flattens and wraps its body around a twig by day",
  // IMPOSSIBLE
  "peacockspider": "Males raise a rainbow flap and dance to court females",
  "goliathbirdeater": "The heaviest spider on Earth by body mass",
  "ogrefacedspider": "Casts a silk net over prey with two huge night eyes",
  "assassinspider": "A long neck lets it spear other spiders from a distance",
  "trapdoorspider": "Ambushes prey from a burrow with a hinged silk lid",
  "mirrorspider": "Silver scales on its back shift like tiny mirrors",
  "coinspider": "A flat orb-weaver that presses against tree trunks",
  "wheelspider": "Escapes wasps by cartwheeling down desert dunes",
  "birddungspider": "Disguises itself as a bird dropping to avoid predators",
  "twigspider": "Stretches out to mimic a broken twig in daylight",
  "leafcurlingspider": "Hides inside a dead leaf curled into its web center",
  "hermitspider": "Builds a hidden retreat off the edge of its orb web",
  "longhornedorbweaver": "Has two enormous curved horns spanning its wide back",
  "triangularspider": "A heart- or triangle-shaped ambush hunter of leaves",
  "jewelspider": "A shiny black spider studded with white jewel-like spots",
  "gianthuntsman": "Holds the record for the largest leg-span of any spider",
  "redwidow": "A rare Florida widow with a red head and black belly",
  "brownwidow": "Its spiky egg sacs look like tiny spiked balls",
  "arizonablonde": "A pale desert tarantula that can live over 20 years",
  "wallspider": "So flat it can turn in mid-air to land on a wall",
  "slingshotspider": "Pulls its web into a cone and fires it at flying prey",
  "greenjumper": "A large green jumper; males wear a white-and-black crest",
  "vegetarianspider": "The only spider that mainly eats plant matter",
  "portiaspider": "A jumping spider clever enough to plan hunting routes",
  "socialspider": "Thousands live and hunt together in one giant web",
};
