// E110 «Guess the ZOOMED Spider» — GuessSync "What the Zoom" hard-mode.
// Reuses the EXACT E57 spider image set (spiders/<slug>.jpg) and E57's SPIDER_FACTS + sd-<slug>.wav
// answer VOs (copied to sdz-<slug>.wav — identical "It's the <name>!" line, zero new audio cost),
// but RE-TIERED by how hard each spider is to name from an EXTREME off-center close-up crop
// (leg/abdomen/carapace patch, scale 3.0). Difficulty tracks COLOR/PATTERN distinctiveness, NOT
// general spider fame: EASY = bold color/markings survive any tiny crop (Peacock Spider rainbow
// abdomen, Cobalt Blue Tarantula, Redback's red stripe...). IMPOSSIBLE = plain brown/black/generic
// hairy or shelled body — a crop of it looks like any other spider (Trapdoor Spider, Wall Spider, etc.)
// image: spiders/<slug>.jpg | answer VO: sfx/sdz-<slug>.wav (copied from E57's sd-<slug>.wav)
export const SPIDERZOOM = [
  // ===== EASY (25) =====
  { slug: "candystripespider", name: "Candy-striped Spider", level: "easy" },
  { slug: "marbledorbweaver", name: "Marbled Orb-weaver", level: "easy" },
  { slug: "goldsilkorbweaver", name: "Golden Silk Orb-weaver", level: "easy" },
  { slug: "cobaltbluetarantula", name: "Cobalt Blue Tarantula", level: "easy" },
  { slug: "greenbottleblue", name: "Green Bottle Blue Tarantula", level: "easy" },
  { slug: "blackwidow", name: "Black Widow", level: "easy" },
  { slug: "redback", name: "Redback Spider", level: "easy" },
  { slug: "zebraspider", name: "Zebra Spider", level: "easy" },
  { slug: "pinktoetarantula", name: "Pink-toe Tarantula", level: "easy" },
  { slug: "greenhuntsman", name: "Green Huntsman", level: "easy" },
  { slug: "peacockspider", name: "Peacock Spider", level: "easy" },
  { slug: "jewelspider", name: "Jewel Spider", level: "easy" },
  { slug: "redwidow", name: "Red Widow", level: "easy" },
  { slug: "yellowsacspider", name: "Yellow Sac Spider", level: "easy" },
  { slug: "greenlynx", name: "Green Lynx Spider", level: "easy" },
  { slug: "mexicanredknee", name: "Mexican Redknee Tarantula", level: "easy" },
  { slug: "curlyhairtarantula", name: "Curly Hair Tarantula", level: "easy" },
  { slug: "cucumberspider", name: "Cucumber Green Spider", level: "easy" },
  { slug: "gootysapphire", name: "Gooty Sapphire Tarantula", level: "easy" },
  { slug: "orangebaboon", name: "Orange Baboon Tarantula", level: "easy" },
  { slug: "greenjumper", name: "Green Jumping Spider", level: "easy" },
  { slug: "waspspider", name: "Wasp Spider", level: "easy" },
  { slug: "writingspider", name: "Writing Spider", level: "easy" },
  { slug: "jorospider", name: "Joro Spider", level: "easy" },
  { slug: "ladybirdspider", name: "Ladybird Spider", level: "easy" },
  // ===== MEDIUM (25) =====
  { slug: "tarantula", name: "Tarantula", level: "medium" },
  { slug: "wolfspider", name: "Wolf Spider", level: "medium" },
  { slug: "jumpingspider", name: "Jumping Spider", level: "medium" },
  { slug: "daddylonglegs", name: "Daddy Long-legs", level: "medium" },
  { slug: "gardenspider", name: "Garden Spider", level: "medium" },
  { slug: "brownrecluse", name: "Brown Recluse", level: "medium" },
  { slug: "huntsman", name: "Huntsman Spider", level: "medium" },
  { slug: "orbweaver", name: "Orb-weaver", level: "medium" },
  { slug: "ghostspider", name: "Ghost Spider", level: "medium" },
  { slug: "housespider", name: "House Spider", level: "medium" },
  { slug: "funnelweb", name: "Sydney Funnel-web", level: "medium" },
  { slug: "crabspider", name: "Crab Spider", level: "medium" },
  { slug: "fishingspider", name: "Fishing Spider", level: "medium" },
  { slug: "hobospider", name: "Hobo Spider", level: "medium" },
  { slug: "barnspider", name: "Barn Spider", level: "medium" },
  { slug: "grassspider", name: "Grass Spider", level: "medium" },
  { slug: "moneyspider", name: "Money Spider", level: "medium" },
  { slug: "spittingspider", name: "Spitting Spider", level: "medium" },
  { slug: "woodlousespider", name: "Woodlouse Spider", level: "medium" },
  { slug: "lacewebspider", name: "Lace-web Spider", level: "medium" },
  { slug: "purseweb", name: "Purse-web Spider", level: "medium" },
  { slug: "spinyorbweaver", name: "Spiny-backed Orb-weaver", level: "medium" },
  { slug: "mousespider", name: "Mouse Spider", level: "medium" },
  { slug: "happyfacespider", name: "Happy-face Spider", level: "medium" },
  { slug: "regaljumper", name: "Regal Jumping Spider", level: "medium" },
  // ===== HARD (25) =====
  { slug: "cavespider", name: "Cave Spider", level: "hard" },
  { slug: "longjawedorbweaver", name: "Long-jawed Orb-weaver", level: "hard" },
  { slug: "groundspider", name: "Ground Spider", level: "hard" },
  { slug: "bolasspider", name: "Bolas Spider", level: "hard" },
  { slug: "walnutorbweaver", name: "Walnut Orb-weaver", level: "hard" },
  { slug: "falsewidow", name: "False Widow", level: "hard" },
  { slug: "arrowheadorbweaver", name: "Arrowhead Orb-weaver", level: "hard" },
  { slug: "antmimicspider", name: "Ant-mimic Spider", level: "hard" },
  { slug: "featherleggedspider", name: "Feather-legged Spider", level: "hard" },
  { slug: "piratespider", name: "Pirate Spider", level: "hard" },
  { slug: "tentwebspider", name: "Tent-web Spider", level: "hard" },
  { slug: "twotailedspider", name: "Two-tailed Spider", level: "hard" },
  { slug: "scorpiontailedspider", name: "Scorpion-tailed Spider", level: "hard" },
  { slug: "anteatingspider", name: "Ant-eating Spider", level: "hard" },
  { slug: "gardenorbweaver", name: "Garden Orb-weaver", level: "hard" },
  { slug: "lichenhuntsman", name: "Lichen Huntsman", level: "hard" },
  { slug: "wraparoundspider", name: "Wrap-around Spider", level: "hard" },
  { slug: "goliathbirdeater", name: "Goliath Birdeater", level: "hard" },
  { slug: "ogrefacedspider", name: "Ogre-faced Spider", level: "hard" },
  { slug: "assassinspider", name: "Assassin Spider", level: "hard" },
  { slug: "trapdoorspider", name: "Trapdoor Spider", level: "hard" },
  { slug: "mirrorspider", name: "Mirror Spider", level: "hard" },
  { slug: "blackhousespider", name: "Black House Spider", level: "hard" },
  { slug: "brazilianblack", name: "Brazilian Black Tarantula", level: "hard" },
  { slug: "braziliansalmonpink", name: "Brazilian Salmon Pink", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { slug: "coinspider", name: "Coin Spider", level: "impossible" },
  { slug: "birddungspider", name: "Bird-dung Spider", level: "impossible" },
  { slug: "twigspider", name: "Twig Spider", level: "impossible" },
  { slug: "leafcurlingspider", name: "Leaf-curling Spider", level: "impossible" },
  { slug: "hermitspider", name: "Hermit Spider", level: "impossible" },
  { slug: "longhornedorbweaver", name: "Long-horned Orb-weaver", level: "impossible" },
  { slug: "triangularspider", name: "Triangular Spider", level: "impossible" },
  { slug: "gianthuntsman", name: "Giant Huntsman", level: "impossible" },
  { slug: "brownwidow", name: "Brown Widow", level: "impossible" },
  { slug: "wallspider", name: "Wall Spider", level: "impossible" },
  { slug: "slingshotspider", name: "Slingshot Spider", level: "impossible" },
  { slug: "vegetarianspider", name: "Vegetarian Spider", level: "impossible" },
  { slug: "portiaspider", name: "Portia Spider", level: "impossible" },
  { slug: "socialspider", name: "Social Spider", level: "impossible" },
  { slug: "boldjumper", name: "Bold Jumping Spider", level: "impossible" },
  { slug: "nurserywebspider", name: "Nursery Web Spider", level: "impossible" },
  { slug: "wanderingspider", name: "Brazilian Wandering Spider", level: "impossible" },
  { slug: "tubewebspider", name: "Tube Web Spider", level: "impossible" },
  { slug: "flowercrabspider", name: "Flower Crab Spider", level: "impossible" },
  { slug: "divingbellspider", name: "Diving Bell Spider", level: "impossible" },
  { slug: "sixeyedsandspider", name: "Six-eyed Sand Spider", level: "impossible" },
  { slug: "indianornamental", name: "Indian Ornamental Tarantula", level: "impossible" },
  { slug: "kingbaboonspider", name: "King Baboon Spider", level: "impossible" },
  { slug: "arizonablonde", name: "Arizona Blonde Tarantula", level: "impossible" },
  { slug: "wheelspider", name: "Golden Wheel Spider", level: "impossible" },
];
