// «Guess the Spider» — GuessSync · E57 · 100 arachnids (25/level) · real photos from Wikimedia Commons
// Sorted by real recognizability: easy (Tarantula/Black Widow) → impossible (Peacock Spider/Goliath Birdeater). Arachnids only — distinct from insects (E38).
export const SPIDERS = [
  // EASY (25) — household-name spiders
  { slug: "tarantula", name: "Tarantula", level: "easy" },
  { slug: "blackwidow", name: "Black Widow", level: "easy" },
  { slug: "wolfspider", name: "Wolf Spider", level: "easy" },
  { slug: "jumpingspider", name: "Jumping Spider", level: "easy" },
  { slug: "daddylonglegs", name: "Daddy Long-legs", level: "easy" },
  { slug: "gardenspider", name: "Garden Spider", level: "easy" },
  { slug: "brownrecluse", name: "Brown Recluse", level: "easy" },
  { slug: "huntsman", name: "Huntsman Spider", level: "easy" },
  { slug: "orbweaver", name: "Orb-weaver", level: "easy" },
  { slug: "scorpion", name: "Scorpion", level: "easy" },
  { slug: "camelspider", name: "Camel Spider", level: "easy" },
  { slug: "housespider", name: "House Spider", level: "easy" },
  { slug: "redback", name: "Redback Spider", level: "easy" },
  { slug: "funnelweb", name: "Sydney Funnel-web", level: "easy" },
  { slug: "crabspider", name: "Crab Spider", level: "easy" },
  { slug: "goldsilkorbweaver", name: "Golden Silk Orb-weaver", level: "easy" },
  { slug: "fishingspider", name: "Fishing Spider", level: "easy" },
  { slug: "zebraspider", name: "Zebra Spider", level: "easy" },
  { slug: "jorospider", name: "Joro Spider", level: "easy" },
  { slug: "hobospider", name: "Hobo Spider", level: "easy" },
  { slug: "barnspider", name: "Barn Spider", level: "easy" },
  { slug: "grassspider", name: "Grass Spider", level: "easy" },
  { slug: "yellowsacspider", name: "Yellow Sac Spider", level: "easy" },
  { slug: "emperorscorpion", name: "Emperor Scorpion", level: "easy" },
  { slug: "writingspider", name: "Writing Spider", level: "easy" },
  // MEDIUM (25)
  { slug: "greenlynx", name: "Green Lynx Spider", level: "medium" },
  { slug: "nurserywebspider", name: "Nursery Web Spider", level: "medium" },
  { slug: "spittingspider", name: "Spitting Spider", level: "medium" },
  { slug: "woodlousespider", name: "Woodlouse Spider", level: "medium" },
  { slug: "wanderingspider", name: "Brazilian Wandering Spider", level: "medium" },
  { slug: "mousespider", name: "Mouse Spider", level: "medium" },
  { slug: "deathstalker", name: "Deathstalker Scorpion", level: "medium" },
  { slug: "barkscorpion", name: "Arizona Bark Scorpion", level: "medium" },
  { slug: "vinegaroon", name: "Vinegaroon", level: "medium" },
  { slug: "harvestman", name: "Harvestman", level: "medium" },
  { slug: "waspspider", name: "Wasp Spider", level: "medium" },
  { slug: "purseweb", name: "Purse-web Spider", level: "medium" },
  { slug: "divingbellspider", name: "Diving Bell Spider", level: "medium" },
  { slug: "cavespider", name: "Cave Spider", level: "medium" },
  { slug: "longjawedorbweaver", name: "Long-jawed Orb-weaver", level: "medium" },
  { slug: "groundspider", name: "Ground Spider", level: "medium" },
  { slug: "spinyorbweaver", name: "Spiny-backed Orb-weaver", level: "medium" },
  { slug: "pinktoetarantula", name: "Pink-toe Tarantula", level: "medium" },
  { slug: "mexicanredknee", name: "Mexican Redknee Tarantula", level: "medium" },
  { slug: "curlyhairtarantula", name: "Curly Hair Tarantula", level: "medium" },
  { slug: "sixeyedsandspider", name: "Six-eyed Sand Spider", level: "medium" },
  { slug: "bolasspider", name: "Bolas Spider", level: "medium" },
  { slug: "pseudoscorpion", name: "Pseudoscorpion", level: "medium" },
  { slug: "falsewidow", name: "False Widow", level: "medium" },
  { slug: "marbledorbweaver", name: "Marbled Orb-weaver", level: "medium" },
  // HARD (25)
  { slug: "arrowheadorbweaver", name: "Arrowhead Orb-weaver", level: "hard" },
  { slug: "candystripespider", name: "Candy-striped Spider", level: "hard" },
  { slug: "cucumberspider", name: "Cucumber Green Spider", level: "hard" },
  { slug: "ladybirdspider", name: "Ladybird Spider", level: "hard" },
  { slug: "antmimicspider", name: "Ant-mimic Spider", level: "hard" },
  { slug: "featherleggedspider", name: "Feather-legged Spider", level: "hard" },
  { slug: "piratespider", name: "Pirate Spider", level: "hard" },
  { slug: "tentwebspider", name: "Tent-web Spider", level: "hard" },
  { slug: "greenhuntsman", name: "Green Huntsman", level: "hard" },
  { slug: "cobaltbluetarantula", name: "Cobalt Blue Tarantula", level: "hard" },
  { slug: "gootysapphire", name: "Gooty Sapphire Tarantula", level: "hard" },
  { slug: "indianornamental", name: "Indian Ornamental Tarantula", level: "hard" },
  { slug: "braziliansalmonpink", name: "Brazilian Salmon Pink", level: "hard" },
  { slug: "kingbaboonspider", name: "King Baboon Spider", level: "hard" },
  { slug: "greenbottleblue", name: "Green Bottle Blue Tarantula", level: "hard" },
  { slug: "orangebaboon", name: "Orange Baboon Tarantula", level: "hard" },
  { slug: "twotailedspider", name: "Two-tailed Spider", level: "hard" },
  { slug: "scorpiontailedspider", name: "Scorpion-tailed Spider", level: "hard" },
  { slug: "happyfacespider", name: "Happy-face Spider", level: "hard" },
  { slug: "whipspider", name: "Whip Spider", level: "hard" },
  { slug: "anteatingspider", name: "Ant-eating Spider", level: "hard" },
  { slug: "gardenorbweaver", name: "Garden Orb-weaver", level: "hard" },
  { slug: "regaljumper", name: "Regal Jumping Spider", level: "hard" },
  { slug: "lichenhuntsman", name: "Lichen Huntsman", level: "hard" },
  { slug: "wraparoundspider", name: "Wrap-around Spider", level: "hard" },
  // IMPOSSIBLE (25) — obscure/exotic real species
  { slug: "peacockspider", name: "Peacock Spider", level: "impossible" },
  { slug: "goliathbirdeater", name: "Goliath Birdeater", level: "impossible" },
  { slug: "ogrefacedspider", name: "Ogre-faced Spider", level: "impossible" },
  { slug: "assassinspider", name: "Assassin Spider", level: "impossible" },
  { slug: "trapdoorspider", name: "Trapdoor Spider", level: "impossible" },
  { slug: "mirrorspider", name: "Mirror Spider", level: "impossible" },
  { slug: "coinspider", name: "Coin Spider", level: "impossible" },
  { slug: "wheelspider", name: "Golden Wheel Spider", level: "impossible" },
  { slug: "birddungspider", name: "Bird-dung Spider", level: "impossible" },
  { slug: "twigspider", name: "Twig Spider", level: "impossible" },
  { slug: "leafcurlingspider", name: "Leaf-curling Spider", level: "impossible" },
  { slug: "hermitspider", name: "Hermit Spider", level: "impossible" },
  { slug: "longhornedorbweaver", name: "Long-horned Orb-weaver", level: "impossible" },
  { slug: "triangularspider", name: "Triangular Spider", level: "impossible" },
  { slug: "jewelspider", name: "Jewel Spider", level: "impossible" },
  { slug: "gianthuntsman", name: "Giant Huntsman", level: "impossible" },
  { slug: "redwidow", name: "Red Widow", level: "impossible" },
  { slug: "brownwidow", name: "Brown Widow", level: "impossible" },
  { slug: "arizonablonde", name: "Arizona Blonde Tarantula", level: "impossible" },
  { slug: "wallspider", name: "Wall Spider", level: "impossible" },
  { slug: "slingshotspider", name: "Slingshot Spider", level: "impossible" },
  { slug: "greenjumper", name: "Green Jumping Spider", level: "impossible" },
  { slug: "vegetarianspider", name: "Vegetarian Spider", level: "impossible" },
  { slug: "portiaspider", name: "Portia Spider", level: "impossible" },
  { slug: "socialspider", name: "Social Spider", level: "impossible" },
];
