// E181 sport-emoji facts — one true <=70-char note per sport, shown on reveal.
export const SPORTS_EMOJI_2_FACTS = {
  // EASY
  "american-football": "US contact sport; teams advance an oval ball to end zones.",
  "field-hockey": "Teams hit a ball into goals with curved sticks on turf.",
  "roller-skating": "Gliding on wheeled boots for sport or recreation.",
  "breakdancing": "Acrobatic street dance; an Olympic sport as 'breaking'.",
  "chess": "Two-player strategy board game of kings and checkmate.",
  "hiking": "Long vigorous walks across trails and mountains.",
  "rock-climbing": "Ascending rock faces using grips, holds, and ropes.",
  "ultimate-frisbee": "Team sport scoring by passing a flying disc to end zones.",
  "scuba-diving": "Underwater diving using a tank of breathing air.",
  "esports": "Competitive organized video gaming for prizes.",
  "dodgeball": "Teams throw balls to hit and eliminate opponents.",
  "arm-wrestling": "Two people grip hands and force the other's arm down.",
  "powerlifting": "Lifting max weight in squat, bench press, and deadlift.",
  "bodybuilding": "Building and posing muscles judged on size and form.",
  "disc-golf": "Throwing a flying disc into baskets in fewest throws.",
  "pool-billiards": "Potting balls into pockets on a cloth table with a cue.",
  "ice-fishing": "Catching fish through a hole cut in a frozen lake.",
  "skydiving": "Jumping from aircraft and freefalling before a parachute.",
  "pickleball": "Paddle sport mixing tennis, badminton, and ping-pong.",
  "hurdles": "Sprint race leaping over evenly spaced barriers.",
  "rally-racing": "Timed car racing on public roads and rough terrain.",
  "motorcycle-racing": "Racing motorcycles at speed around a circuit.",
  "kayaking": "Paddling a small covered boat with a double-bladed oar.",
  "bmx-racing": "Sprint bicycle racing on a dirt track with jumps.",
  "mixed-martial-arts": "Full-contact combat blending striking and grappling.",
  // MEDIUM
  "windsurfing": "Sailing on a board powered by a hand-held sail.",
  "water-skiing": "Skimming water on skis while towed behind a boat.",
  "white-water-rafting": "Riding rough river rapids in an inflatable raft.",
  "cross-country-skiing": "Skiing across flat snowy terrain under your own power.",
  "alpine-skiing": "Racing downhill on skis around gates and slopes.",
  "sledding": "Sliding down snow-covered slopes on a small sled.",
  "ice-climbing": "Ascending frozen waterfalls and ice walls with axes.",
  "high-jump": "Leaping over a raised horizontal bar for height.",
  "long-jump": "Sprinting then jumping for maximum horizontal distance.",
  "triple-jump": "A hop, a step, and a jump for total distance.",
  "racewalking": "Long-distance walk race; one foot always on the ground.",
  "hammer-throw": "Hurling a heavy metal ball on a wire for distance.",
  "kickboxing": "Combat sport of punches and kicks in a ring.",
  "muay-thai": "Thai boxing using fists, elbows, knees, and shins.",
  "kendo": "Japanese fencing with bamboo swords and armor.",
  "kung-fu": "Chinese martial arts with strikes, forms, and weapons.",
  "capoeira": "Brazilian art blending martial moves, dance, and music.",
  "drag-racing": "Two cars sprint a straight strip as fast as possible.",
  "kart-racing": "Racing small open go-karts around tight circuits.",
  "speedway": "Motorcycle racing on oval dirt tracks with no brakes.",
  "track-cycling": "Bicycle racing on a steep banked oval velodrome.",
  "barrel-racing": "Rodeo event racing a horse around barrels for time.",
  "vaulting": "Gymnastic moves performed on a moving horse's back.",
  "wheelchair-basketball": "Basketball played by athletes in sport wheelchairs.",
  "beach-tennis": "Tennis-like sport played over a net on sand.",
  // HARD
  "padel": "Racket sport in an enclosed glass court; walls in play.",
  "spearfishing": "Hunting fish underwater using a spear or speargun.",
  "snorkeling": "Swimming at the surface with a mask and breathing tube.",
  "freediving": "Diving deep on a single breath with no air tank.",
  "dragon-boat-racing": "Teams paddle long ornate boats to a beating drum.",
  "cliff-diving": "Diving into water from high natural cliffs.",
  "skeet-shooting": "Shooting clay targets flung across the sky.",
  "sport-shooting": "Firing at fixed targets for accuracy and precision.",
  "relay-race": "Team running race passing a baton between runners.",
  "steeplechase": "Distance run over fixed barriers and a water jump.",
  "decathlon": "Ten track-and-field events scored over two days.",
  "bungee-jumping": "Leaping from a height tied to an elastic cord.",
  "base-jumping": "Parachuting from fixed points like cliffs or buildings.",
  "hang-gliding": "Flying a light unpowered wing from high ground.",
  "wingsuit-flying": "Gliding in a webbed jumpsuit before a parachute opens.",
  "crossfit": "Timed high-intensity mix of strength and cardio.",
  "strongman": "Lifting and carrying huge stones, logs, and weights.",
  "calisthenics": "Bodyweight strength training and gymnastic moves.",
  "aikido": "Japanese martial art redirecting an attacker's force.",
  "wushu": "Modern Chinese martial art of forms and sparring.",
  "brazilian-jiu-jitsu": "Grappling art using holds and submissions on the ground.",
  "checkers": "Board game jumping and capturing an opponent's discs.",
  "backgammon": "Race board game moving pieces by rolls of dice.",
  "speedcubing": "Solving a twisting cube puzzle as fast as possible.",
  "roller-hockey": "Hockey played on roller skates instead of ice.",
  // IMPOSSIBLE
  "pesapallo": "Finland's national sport, a fast variant of baseball.",
  "jai-alai": "Basque game hurling a ball off a wall with a scoop.",
  "camogie": "Irish women's stick-and-ball game, akin to hurling.",
  "gilli-danda": "South Asian game hitting a small stick with a bigger one.",
  "kho-kho": "Indian tag sport where chasers catch fleeing runners.",
  "pato": "Argentine sport on horseback with a six-handled ball.",
  "kubb": "Nordic game toppling wooden blocks by throwing batons.",
  "molkky": "Finnish game knocking numbered pins with a wooden throw.",
  "fistball": "Teams strike a ball over a net using only fist or arm.",
  "tchoukball": "Teams score by bouncing a ball off a rebound net.",
  "kin-ball": "Three teams play with one huge 1.2-metre ball.",
  "spikeball": "Teams bounce a small ball off a round net near the ground.",
  "goalball": "Paralympic sport rolling a bell ball past blindfolded foes.",
  "sitting-volleyball": "Paralympic volleyball played seated on the floor.",
  "wheelchair-rugby": "Full-contact rugby in wheelchairs, once called murderball.",
  "blind-football": "Five-a-side football played with a ball that rattles.",
  "hornussen": "Swiss sport flicking a puck for teammates to block.",
  "harness-racing": "Horses trot pulling a driver in a two-wheeled cart.",
  "eventing": "Equestrian test of dressage, cross-country, and jumping.",
  "drone-racing": "Piloting fast FPV drones through aerial gate courses.",
  "truck-racing": "Big-rig trucks race side by side around a circuit.",
  "boat-racing": "Powerboats race at high speed around a water course.",
  "lawn-bowls": "Rolling biased balls close to a small target ball.",
  "contract-bridge": "Trick-taking partnership card game; a rated mind sport.",
  "speed-climbing": "Racing to scale a standard wall in mere seconds.",
};
