// E202 «Guess the Sport by Emoji 3» — 100 sports · 25/tier
// VO: sfx/e202-<id>.wav
export const SPORTS_EMOJI_3 = [
  // ===== EASY (25) =====
  { id: "softball", title: "Softball", emojis: "🥎🧢", level: "easy" },
  { id: "cheerleading", title: "Cheerleading", emojis: "📣⭐", level: "easy" },
  { id: "tug-of-war", title: "Tug of War", emojis: "🪢💪", level: "easy" },
  { id: "bull-riding", title: "Bull Riding", emojis: "🤠🐂", level: "easy" },
  { id: "jet-skiing", title: "Jet Skiing", emojis: "🚤🌊", level: "easy" },
  { id: "bouldering", title: "Bouldering", emojis: "🧗🪨", level: "easy" },
  { id: "parkour", title: "Parkour", emojis: "🏃🧱", level: "easy" },
  { id: "fly-fishing", title: "Fly Fishing", emojis: "🎣🪰", level: "easy" },
  { id: "cornhole", title: "Cornhole", emojis: "🌽🕳", level: "easy" },
  { id: "horseshoes", title: "Horseshoes", emojis: "🐴🎯", level: "easy" },
  { id: "shuffleboard", title: "Shuffleboard", emojis: "🥌🪵", level: "easy" },
  { id: "kickball", title: "Kickball", emojis: "⚽👟", level: "easy" },
  { id: "wheelchair-tennis", title: "Wheelchair Tennis", emojis: "🎾♿", level: "easy" },
  { id: "hula-hoop", title: "Hula Hoop", emojis: "💃⭕", level: "easy" },
  { id: "longboarding", title: "Longboarding", emojis: "🛹🏁", level: "easy" },
  { id: "wakesurfing", title: "Wakesurfing", emojis: "🏄🚤", level: "easy" },
  { id: "airsoft", title: "Airsoft", emojis: "🔫🥽", level: "easy" },
  { id: "paintball", title: "Paintball", emojis: "🎨🔫", level: "easy" },
  { id: "dog-agility", title: "Dog Agility", emojis: "🐕🏆", level: "easy" },
  { id: "jump-rope", title: "Jump Rope", emojis: "🪢👟", level: "easy" },
  { id: "beach-soccer", title: "Beach Soccer", emojis: "⚽🩴", level: "easy" },
  { id: "roller-derby", title: "Roller Derby", emojis: "🛼💥", level: "easy" },
  { id: "cross-country-running", title: "Cross Country Running", emojis: "🏃🌲", level: "easy" },
  { id: "skimboarding", title: "Skimboarding", emojis: "🏄🏖", level: "easy" },
  { id: "tetherball", title: "Tetherball", emojis: "🎾🪢", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "duathlon", title: "Duathlon", emojis: "🏃🚲", level: "medium" },
  { id: "aquathlon", title: "Aquathlon", emojis: "🏊🏃", level: "medium" },
  { id: "footbag", title: "Footbag", emojis: "🦶⭕", level: "medium" },
  { id: "ringette", title: "Ringette", emojis: "🏒⭕", level: "medium" },
  { id: "broomball", title: "Broomball", emojis: "🧹⛸", level: "medium" },
  { id: "floorball", title: "Floorball", emojis: "🏒🏢", level: "medium" },
  { id: "field-archery", title: "Field Archery", emojis: "🏹🌲", level: "medium" },
  { id: "sled-dog-racing", title: "Sled Dog Racing", emojis: "🐕🛷", level: "medium" },
  { id: "wingfoiling", title: "Wingfoiling", emojis: "🪁🏄", level: "medium" },
  { id: "skijoring", title: "Skijoring", emojis: "🐕🎿", level: "medium" },
  { id: "snowshoeing", title: "Snowshoeing", emojis: "🥾❄", level: "medium" },
  { id: "snow-kiting", title: "Snow Kiting", emojis: "🪁❄", level: "medium" },
  { id: "street-luge", title: "Street Luge", emojis: "🛹🛷", level: "medium" },
  { id: "slacklining", title: "Slacklining", emojis: "🪢🌲", level: "medium" },
  { id: "obstacle-course-racing", title: "Obstacle Course Racing", emojis: "🧗🚧", level: "medium" },
  { id: "adventure-racing", title: "Adventure Racing", emojis: "🧭🏃", level: "medium" },
  { id: "endurance-riding", title: "Endurance Riding", emojis: "🐎⏱", level: "medium" },
  { id: "polocrosse", title: "Polocrosse", emojis: "🐴🥍", level: "medium" },
  { id: "horseball", title: "Horseball", emojis: "🐴🏐", level: "medium" },
  { id: "land-sailing", title: "Land Sailing", emojis: "⛵🏜", level: "medium" },
  { id: "ice-yachting", title: "Ice Yachting", emojis: "⛵❄", level: "medium" },
  { id: "kite-buggying", title: "Kite Buggying", emojis: "🪁🏜", level: "medium" },
  { id: "downhill-mountain-biking", title: "Downhill Mountain Biking", emojis: "🚲⛰", level: "medium" },
  { id: "enduro-racing", title: "Enduro Racing", emojis: "🏍🌲", level: "medium" },
  { id: "gravel-racing", title: "Gravel Racing", emojis: "🚲🪨", level: "medium" },

  // ===== HARD (25) =====
  { id: "beach-handball", title: "Beach Handball", emojis: "🤾🏖", level: "hard" },
  { id: "beach-rugby", title: "Beach Rugby", emojis: "🏉🏖", level: "hard" },
  { id: "footgolf", title: "Footgolf", emojis: "⚽⛳", level: "hard" },
  { id: "snow-polo", title: "Snow Polo", emojis: "🐴🎿", level: "hard" },
  { id: "camel-racing", title: "Camel Racing", emojis: "🐫🏁", level: "hard" },
  { id: "greyhound-racing", title: "Greyhound Racing", emojis: "🐕🏁", level: "hard" },
  { id: "pigeon-racing", title: "Pigeon Racing", emojis: "🐦🏁", level: "hard" },
  { id: "rounders", title: "Rounders", emojis: "🏏🏟", level: "hard" },
  { id: "stoolball", title: "Stoolball", emojis: "🪑🏏", level: "hard" },
  { id: "baseball5", title: "Baseball5", emojis: "✋⚾", level: "hard" },
  { id: "axe-throwing", title: "Axe Throwing", emojis: "🪓🎯", level: "hard" },
  { id: "log-rolling", title: "Log Rolling", emojis: "🪵🌊", level: "hard" },
  { id: "woodchopping", title: "Woodchopping", emojis: "🪓🪵", level: "hard" },
  { id: "marbles", title: "Marbles", emojis: "🔮⭕", level: "hard" },
  { id: "tiddlywinks", title: "Tiddlywinks", emojis: "🪙⭕", level: "hard" },
  { id: "conkers", title: "Conkers", emojis: "🌰🪢", level: "hard" },
  { id: "egg-and-spoon-race", title: "Egg-and-Spoon Race", emojis: "🥚🏃", level: "hard" },
  { id: "pillow-fighting", title: "Pillow Fighting", emojis: "🛏💥", level: "hard" },
  { id: "real-tennis", title: "Real Tennis", emojis: "🎾🏰", level: "hard" },
  { id: "eton-fives", title: "Eton Fives", emojis: "✋🧱", level: "hard" },
  { id: "tamburello", title: "Tamburello", emojis: "🎾🥁", level: "hard" },
  { id: "ringo", title: "Ringo", emojis: "🏓⭕", level: "hard" },
  { id: "ice-stock-sport", title: "Ice Stock Sport", emojis: "❄🥌", level: "hard" },
  { id: "finswimming", title: "Finswimming", emojis: "🤿🏊", level: "hard" },
  { id: "sanshou", title: "Sanshou", emojis: "🥋🐲", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "tejo", title: "Tejo", emojis: "🎯💥", level: "impossible" },
  { id: "quadball", title: "Quadball", emojis: "🧹🏆", level: "impossible" },
  { id: "chovgan", title: "Chovgan", emojis: "🐴🎪", level: "impossible" },
  { id: "shin-kicking", title: "Shin Kicking", emojis: "🦵👞", level: "impossible" },
  { id: "zorbing", title: "Zorbing", emojis: "🫧⛰", level: "impossible" },
  { id: "nordic-walking", title: "Nordic Walking", emojis: "🚶🏔", level: "impossible" },
  { id: "stone-skimming", title: "Stone Skimming", emojis: "🪨🌊", level: "impossible" },
  { id: "combat-juggling", title: "Combat Juggling", emojis: "🤹⚔", level: "impossible" },
  { id: "yak-racing", title: "Yak Racing", emojis: "🐂🏔", level: "impossible" },
  { id: "ostrich-racing", title: "Ostrich Racing", emojis: "🐦🏃", level: "impossible" },
  { id: "snail-racing", title: "Snail Racing", emojis: "🐌🏁", level: "impossible" },
  { id: "worm-charming", title: "Worm Charming", emojis: "🪱🎵", level: "impossible" },
  { id: "crab-racing", title: "Crab Racing", emojis: "🦀🏁", level: "impossible" },
  { id: "sepak-raga", title: "Sepak Raga", emojis: "🦶⚽", level: "impossible" },
  { id: "bat-and-trap", title: "Bat-and-Trap", emojis: "🏏🪤", level: "impossible" },
  { id: "aunt-sally", title: "Aunt Sally", emojis: "🪵🪤", level: "impossible" },
  { id: "skittles", title: "Skittles", emojis: "🎳🪵", level: "impossible" },
  { id: "bunnock", title: "Bunnock", emojis: "🦴🎯", level: "impossible" },
  { id: "drone-soccer", title: "Drone Soccer", emojis: "🚁⚽", level: "impossible" },
  { id: "savate", title: "Savate", emojis: "🥊👞", level: "impossible" },
  { id: "pencak-silat", title: "Pencak Silat", emojis: "🥋🌴", level: "impossible" },
  { id: "hapkido", title: "Hapkido", emojis: "🥋💫", level: "impossible" },
  { id: "ice-swimming", title: "Ice Swimming", emojis: "🏊❄", level: "impossible" },
  { id: "combat-robotics", title: "Combat Robotics", emojis: "🤖⚔", level: "impossible" },
  { id: "wing-chun", title: "Wing Chun", emojis: "🥋✊", level: "impossible" },
];
