// E135 "Guess the Sport by Emoji" — 100 sports · 25/tier · clue = plain Unicode emoji
// VO: sfx/e135-<id>.wav
export const SPORTS_EMOJI = [
  // ===== EASY =====
  { id: "football", title: "Football (Soccer)", emojis: "⚽🥅", level: "easy" },
  { id: "basketball", title: "Basketball", emojis: "🏀🏆", level: "easy" },
  { id: "baseball", title: "Baseball", emojis: "⚾👟", level: "easy" },
  { id: "tennis", title: "Tennis", emojis: "🎾🏆", level: "easy" },
  { id: "cricket", title: "Cricket", emojis: "🏏🏆", level: "easy" },
  { id: "ice-hockey", title: "Ice Hockey", emojis: "🏒❄", level: "easy" },
  { id: "table-tennis", title: "Table Tennis", emojis: "🏓🏆", level: "easy" },
  { id: "boxing", title: "Boxing", emojis: "🥊🔥", level: "easy" },
  { id: "bowling", title: "Bowling", emojis: "🎳🎯", level: "easy" },
  { id: "skiing", title: "Skiing", emojis: "🎿❄", level: "easy" },
  { id: "skateboarding", title: "Skateboarding", emojis: "🛹🔥", level: "easy" },
  { id: "surfing", title: "Surfing", emojis: "🏄🌊", level: "easy" },
  { id: "swimming", title: "Swimming", emojis: "🏊🌊", level: "easy" },
  { id: "track-and-field", title: "Track and Field", emojis: "🏃🏆", level: "easy" },
  { id: "horse-racing", title: "Horse Racing", emojis: "🏇🏆", level: "easy" },
  { id: "motocross", title: "Motocross", emojis: "🏍🔥", level: "easy" },
  { id: "formula-1-racing", title: "Formula 1 Racing", emojis: "🏎🏁", level: "easy" },
  { id: "cycling", title: "Cycling", emojis: "🚲🏆", level: "easy" },
  { id: "sailing", title: "Sailing", emojis: "⛵🌊", level: "easy" },
  { id: "archery", title: "Archery", emojis: "🏹🎯", level: "easy" },
  { id: "fencing", title: "Fencing", emojis: "🤺⚔", level: "easy" },
  { id: "karate", title: "Karate", emojis: "🥋⛩", level: "easy" },
  { id: "judo", title: "Judo", emojis: "🥋🤝", level: "easy" },
  { id: "taekwondo", title: "Taekwondo", emojis: "🥋💥", level: "easy" },
  { id: "canoeing", title: "Canoeing", emojis: "🛶🌊", level: "easy" },
  // ===== MEDIUM =====
  { id: "golf", title: "Golf", emojis: "🌳⚪", level: "medium" },
  { id: "volleyball", title: "Volleyball", emojis: "🥅🌊", level: "medium" },
  { id: "badminton", title: "Badminton", emojis: "🐦🎾", level: "medium" },
  { id: "rugby", title: "Rugby", emojis: "🟤🏆", level: "medium" },
  { id: "wrestling", title: "Wrestling", emojis: "🐻🤝", level: "medium" },
  { id: "gymnastics", title: "Gymnastics", emojis: "⭐🎪", level: "medium" },
  { id: "weightlifting", title: "Weightlifting", emojis: "🐂🔥", level: "medium" },
  { id: "water-polo", title: "Water Polo", emojis: "🏊🥅", level: "medium" },
  { id: "handball", title: "Handball", emojis: "🤝🥅", level: "medium" },
  { id: "figure-skating", title: "Figure Skating", emojis: "❄🌟", level: "medium" },
  { id: "speed-skating", title: "Speed Skating", emojis: "⚡❄", level: "medium" },
  { id: "curling", title: "Curling", emojis: "⚫🎯", level: "medium" },
  { id: "bobsled", title: "Bobsled", emojis: "🛷👥", level: "medium" },
  { id: "luge", title: "Luge", emojis: "🛷🧍", level: "medium" },
  { id: "triathlon", title: "Triathlon", emojis: "🏊🚲", level: "medium" },
  { id: "marathon", title: "Marathon", emojis: "🏃🌆", level: "medium" },
  { id: "squash", title: "Squash", emojis: "🎾🧱", level: "medium" },
  { id: "snooker", title: "Snooker", emojis: "🔴⚫", level: "medium" },
  { id: "beach-volleyball", title: "Beach Volleyball", emojis: "🏖🥅", level: "medium" },
  { id: "polo", title: "Polo", emojis: "🐴🏆", level: "medium" },
  { id: "diving", title: "Diving", emojis: "🌊🐠", level: "medium" },
  { id: "rowing", title: "Rowing", emojis: "🛶🏆", level: "medium" },
  { id: "snowboarding", title: "Snowboarding", emojis: "🛹❄", level: "medium" },
  { id: "darts", title: "Darts", emojis: "🎯🍺", level: "medium" },
  { id: "mountain-biking", title: "Mountain Biking", emojis: "🚲🏔", level: "medium" },
  // ===== HARD =====
  { id: "lacrosse", title: "Lacrosse", emojis: "🥅🏒", level: "hard" },
  { id: "netball", title: "Netball", emojis: "🥅🏀", level: "hard" },
  { id: "racquetball", title: "Racquetball", emojis: "🎾🏢", level: "hard" },
  { id: "bocce", title: "Bocce", emojis: "🟢⚫", level: "hard" },
  { id: "petanque", title: "Petanque", emojis: "⚫🟡", level: "hard" },
  { id: "croquet", title: "Croquet", emojis: "🌳⚫", level: "hard" },
  { id: "javelin-throw", title: "Javelin Throw", emojis: "🏹🚀", level: "hard" },
  { id: "shot-put", title: "Shot Put", emojis: "⚫🔥", level: "hard" },
  { id: "discus-throw", title: "Discus Throw", emojis: "🟠🌀", level: "hard" },
  { id: "pole-vault", title: "Pole Vault", emojis: "🏃⭐", level: "hard" },
  { id: "biathlon", title: "Biathlon", emojis: "🎿🏹", level: "hard" },
  { id: "skeleton", title: "Skeleton", emojis: "🛷💀", level: "hard" },
  { id: "freestyle-skiing", title: "Freestyle Skiing", emojis: "🎿🌀", level: "hard" },
  { id: "wakeboarding", title: "Wakeboarding", emojis: "🌊🛹", level: "hard" },
  { id: "kitesurfing", title: "Kitesurfing", emojis: "🌊🦅", level: "hard" },
  { id: "paragliding", title: "Paragliding", emojis: "🦅🏔", level: "hard" },
  { id: "rodeo", title: "Rodeo", emojis: "🤠🐴", level: "hard" },
  { id: "ski-jumping", title: "Ski Jumping", emojis: "🎿🦅", level: "hard" },
  { id: "trampoline", title: "Trampoline", emojis: "🐇🌟", level: "hard" },
  { id: "synchronized-swimming", title: "Synchronized Swimming", emojis: "🌊👥", level: "hard" },
  { id: "modern-pentathlon", title: "Modern Pentathlon", emojis: "🏊🏇", level: "hard" },
  { id: "orienteering", title: "Orienteering", emojis: "🗺🌲", level: "hard" },
  { id: "cyclo-cross", title: "Cyclo-cross", emojis: "🚲🌲", level: "hard" },
  { id: "dressage", title: "Dressage", emojis: "🐴👑", level: "hard" },
  { id: "show-jumping", title: "Show Jumping", emojis: "🐴🌈", level: "hard" },
  // ===== IMPOSSIBLE =====
  { id: "sepak-takraw", title: "Sepak Takraw", emojis: "⚽🕸", level: "impossible" },
  { id: "kabaddi", title: "Kabaddi", emojis: "🤝🏃", level: "impossible" },
  { id: "hurling", title: "Hurling", emojis: "🏒🍀", level: "impossible" },
  { id: "pelota-vasca", title: "Pelota Vasca", emojis: "⚫🧱", level: "impossible" },
  { id: "sumo-wrestling", title: "Sumo Wrestling", emojis: "⛩🐻", level: "impossible" },
  { id: "buzkashi", title: "Buzkashi", emojis: "🐐🐴", level: "impossible" },
  { id: "calcio-storico", title: "Calcio Storico", emojis: "⚽🏰", level: "impossible" },
  { id: "shinty", title: "Shinty", emojis: "🏒⛰", level: "impossible" },
  { id: "bandy", title: "Bandy", emojis: "🏒⚽", level: "impossible" },
  { id: "underwater-hockey", title: "Underwater Hockey", emojis: "🏒🐠", level: "impossible" },
  { id: "chess-boxing", title: "Chess Boxing", emojis: "🥊🧠", level: "impossible" },
  { id: "footvolley", title: "Footvolley", emojis: "⚽🏖", level: "impossible" },
  { id: "vovinam", title: "Vovinam", emojis: "🥋🐉", level: "impossible" },
  { id: "bossaball", title: "Bossaball", emojis: "⚽🎪", level: "impossible" },
  { id: "kok-boru", title: "Kok-Boru", emojis: "🐐🏇", level: "impossible" },
  { id: "wife-carrying", title: "Wife Carrying", emojis: "👫🏃", level: "impossible" },
  { id: "cheese-rolling", title: "Cheese Rolling", emojis: "🧀⛰", level: "impossible" },
  { id: "bog-snorkelling", title: "Bog Snorkelling", emojis: "🐸🌊", level: "impossible" },
  { id: "camel-wrestling", title: "Camel Wrestling", emojis: "🐫🎪", level: "impossible" },
  { id: "elephant-polo", title: "Elephant Polo", emojis: "🐘🏆", level: "impossible" },
  { id: "underwater-rugby", title: "Underwater Rugby", emojis: "🌊⚫", level: "impossible" },
  { id: "toe-wrestling", title: "Toe Wrestling", emojis: "🤝👟", level: "impossible" },
  { id: "gaelic-football", title: "Gaelic Football", emojis: "⚽🍀", level: "impossible" },
  { id: "australian-rules-football", title: "Australian Rules Football", emojis: "⚽🦘", level: "impossible" },
  { id: "korfball", title: "Korfball", emojis: "🥅👫", level: "impossible" },
];
