// «Guess the Sport» — GuessSync · E47 · did-you-know facts, ≤70 chars, verified true.
export const SPORT_FACTS = {
  // EASY
  "soccer": "The world's most popular sport, played by over 250 million",
  "basketball": "Invented in 1891 by James Naismith using a peach basket",
  "tennis": "Scoring runs 15, 30, 40; a tie at 40 is called deuce",
  "golf": "The term 'birdie' means finishing a hole one under par",
  "baseball": "A regulation game lasts nine innings unless it is tied",
  "cricket": "A Test match can last up to five days of play",
  "volleyball": "Each team may touch the ball three times before returning it",
  "swimming": "Freestyle, backstroke, breaststroke and butterfly are the strokes",
  "boxing": "The Marquess of Queensberry rules introduced padded gloves",
  "cycling": "The Tour de France covers roughly 3,500 km each year",
  "skiing": "Alpine racing includes slalom, giant slalom and downhill",
  "tabletennis": "Also called ping-pong; it began in 1880s England",
  "badminton": "The shuttlecock can fly off the racket at over 400 km/h",
  "rugby": "Legend says it began when a boy picked up a football and ran",
  "americanfootball": "A touchdown is worth six points in the NFL",
  "icehockey": "The puck can travel over 160 km/h on a slap shot",
  "bowling": "Knocking down all ten pins on one throw is a strike",
  "archery": "Hitting the gold center of the target scores ten points",
  "skateboarding": "It became an Olympic sport at Tokyo 2020",
  "surfing": "Riders stand on a board to ride breaking ocean waves",
  "gymnastics": "Artistic events include beam, vault, bars and floor",
  "wrestling": "One of the oldest sports, contested in the ancient Olympics",
  "karate": "A Japanese martial art whose name means 'empty hand'",
  "weightlifting": "The two lifts are the snatch and the clean and jerk",
  "running": "The 100 m sprint is often called athletics' blue-ribbon event",
  // MEDIUM
  "fencing": "The three weapons are foil, epee and sabre",
  "rowing": "Crews race backward, facing away from the finish line",
  "judo": "Founded by Jigoro Kano in Japan in 1882",
  "taekwondo": "A Korean martial art famous for high, fast kicks",
  "snowboarding": "Grew from surfing and skating; Olympic since 1998",
  "diving": "Athletes are judged on takeoff, flight and entry into water",
  "handball": "Teams of seven try to throw the ball into a goal",
  "fieldhockey": "Players may only hit the ball with the flat stick side",
  "horseracing": "Often called the 'Sport of Kings'",
  "motocross": "Off-road motorcycle racing over rough dirt tracks",
  "autoracing": "Formula One cars can exceed 350 km/h on straights",
  "sailing": "Boats race a course powered only by the wind",
  "rockclimbing": "Sport climbing debuted at the Tokyo 2020 Olympics",
  "squash": "Players hit a small rubber ball against a front wall",
  "darts": "A standard board's highest single-throw score is 180",
  "snooker": "Played with 15 reds, six colours and one white cue ball",
  "billiards": "A cue-and-ball sport played on a cloth-covered table",
  "waterpolo": "Players tread water and cannot touch the pool bottom",
  "figureskating": "Judged on jumps, spins and artistry on the ice",
  "speedskating": "Racers reach speeds over 60 km/h on long-track ovals",
  "triathlon": "Combines swimming, cycling and running in one race",
  "curling": "Sweepers brush the ice to steer the sliding stone",
  "polo": "Teams on horseback drive a ball with long-handled mallets",
  "kickboxing": "A combat sport blending punches with kicking techniques",
  "canoeing": "Racers paddle canoes or kayaks on flat water or rapids",
  // HARD
  "lacrosse": "Invented by Indigenous peoples of North America",
  "netball": "Developed from basketball; players cannot dribble the ball",
  "biathlon": "Combines cross-country skiing with rifle target shooting",
  "skijumping": "Jumpers can soar more than 200 metres down the hill",
  "luge": "Sliders race feet-first lying on their backs on a sled",
  "bobsled": "Crews sprint to push-start before leaping into the sled",
  "skeleton": "Athletes slide head-first, face-down on a small sled",
  "rhythmicgymnastics": "Uses apparatus like ribbon, hoop, ball and clubs",
  "artisticswimming": "Swimmers perform synchronized routines to music",
  "bmx": "Riders sprint over jumps and berms on small bikes",
  "sumo": "A wrestler loses if he steps out or touches down inside",
  "muaythai": "Thailand's 'art of eight limbs' uses fists, elbows, knees, shins",
  "bjj": "A grappling art focused on ground fighting and submissions",
  "capoeira": "An Afro-Brazilian art blending fighting, dance and music",
  "parkour": "Moving through obstacles with running, jumping and climbing",
  "rodeo": "Cowboys compete in bull riding and bronc riding events",
  "croquet": "Players use mallets to drive balls through wire hoops",
  "dressage": "Horse and rider perform precise, memorized movements",
  "showjumping": "Horses clear a course of fences without knocking bars",
  "kayaking": "Paddlers use a double-bladed paddle in a closed boat",
  "crosscountryskiing": "Skiers travel long distances over snowy terrain",
  "waterskiing": "A skier is towed across water behind a motorboat",
  "ultimatefrisbee": "A team sport scored by catching a flying disc in the end zone",
  "racewalking": "One foot must stay on the ground at all times",
  "powerlifting": "The three lifts are the squat, bench press and deadlift",
  // IMPOSSIBLE
  "sepaktakraw": "Like volleyball but players use feet, knees and head",
  "hurling": "An ancient Irish game played with a stick and small ball",
  "kabaddi": "A raider must tag opponents while chanting on one breath",
  "pelota": "A Basque game of hurling a ball against a fronton wall",
  "shinty": "A Scottish stick-and-ball game related to Irish hurling",
  "bandy": "Like ice hockey but played with a ball on a large rink",
  "korfball": "A mixed-gender sport shooting into a high basket",
  "pesapallo": "Finland's national sport, a variant of baseball",
  "buzkashi": "Central Asian riders drag a goat carcass to score",
  "jaialai": "Players hurl a ball at high speed using a curved basket",
  "gaelicfootball": "An Irish sport mixing soccer and rugby elements",
  "afl": "Australian rules football is played on a large oval field",
  "camogie": "The women's version of the Irish game of hurling",
  "bossaball": "Mixes volleyball and football on an inflatable trampoline",
  "footvolley": "Beach volleyball played using football skills, no hands",
  "underwaterhockey": "Players push a puck along a pool bottom while diving",
  "tchoukball": "Players score by bouncing the ball off a rebound frame",
  "hornussen": "A Swiss sport of striking a puck launched from a ramp",
  "kubb": "A Scandinavian lawn game of toppling wooden blocks",
  "finswimming": "Swimmers wear a monofin to move quickly through water",
  "timbersports": "Athletes race to chop and saw through logs of wood",
  "gateball": "A Japanese team game similar to croquet",
  "cycleball": "Players score goals on bicycles using their wheels",
  "fistball": "Teams punch a ball over a high net using a fist or arm",
  "footgolf": "Players kick a football into a hole in fewest shots",
};
