// E135 emoji-sport facts — one verified <=70-char fact per sport, shown on reveal.
export const SPORTS_EMOJI_FACTS = {
  // EASY
  "football": "The world's most popular sport, played in nearly every country.",
  "basketball": "Invented in 1891 by James Naismith using two peach baskets.",
  "baseball": "America's pastime; a team scores by running around four bases.",
  "tennis": "Played with a racquet; Grand Slams include Wimbledon and the US Open.",
  "cricket": "Bat-and-ball sport; a single match can last up to five days.",
  "ice-hockey": "Players skate on ice, using sticks to shoot a puck into a net.",
  "table-tennis": "Also called ping pong; the ball can travel over 100 km/h.",
  "boxing": "Two fighters trade punches in a ring, scored by rounds.",
  "bowling": "Players roll a ball to knock down ten pins for a strike.",
  "skiing": "Athletes glide down snowy slopes on two long, narrow boards.",
  "skateboarding": "Became an Olympic sport at the Tokyo 2020 Games.",
  "surfing": "Riders balance on a board while gliding along ocean waves.",
  "swimming": "One of the oldest Olympic sports, dating back to 1896.",
  "track-and-field": "Covers running, jumping, and throwing events on a track.",
  "horse-racing": "Jockeys race thoroughbred horses over set distances.",
  "motocross": "Off-road motorcycle racing over dirt tracks with jumps.",
  "formula-1-racing": "Open-wheel cars race at speeds over 300 km/h on circuits.",
  "cycling": "Riders race bicycles on roads, tracks, or off-road trails.",
  "sailing": "Boats race using wind power; an Olympic sport since 1900.",
  "archery": "Competitors shoot arrows at a target from set distances.",
  "fencing": "Sword-fighting sport with three weapons: foil, epee, sabre.",
  "karate": "Japanese striking martial art using punches, kicks, and blocks.",
  "judo": "Japanese martial art focused on throws and grappling holds.",
  "taekwondo": "Korean martial art famous for its fast, high kicks.",
  "canoeing": "Paddlers propel a canoe or kayak through water using paddles.",

  // MEDIUM
  "golf": "Players hit a ball into holes with clubs, using the fewest strokes.",
  "volleyball": "Two teams hit a ball over a net without letting it touch the floor.",
  "badminton": "Players hit a shuttlecock over a net using lightweight racquets.",
  "rugby": "Players carry and pass an oval ball to score by grounding it.",
  "wrestling": "Grappling sport where athletes try to pin or control an opponent.",
  "gymnastics": "Athletes perform routines on apparatus like beam and rings.",
  "weightlifting": "Athletes lift a loaded barbell overhead in two set techniques.",
  "water-polo": "Teams in a pool try to throw a ball into the opposing goal.",
  "handball": "Players throw a ball into a goal using only their hands.",
  "figure-skating": "Skaters perform jumps and spins set to music on ice.",
  "speed-skating": "Racers skate laps on an oval ice track for the fastest time.",
  "curling": "Players slide granite stones across ice toward a target.",
  "bobsled": "Teams race a sled down an icy, curved track at high speed.",
  "luge": "Athletes race feet-first, lying on a small sled down an icy track.",
  "triathlon": "A single race combining swimming, cycling, and running.",
  "marathon": "A long-distance run covering 42.195 kilometers.",
  "squash": "Players hit a small ball against a wall inside a court.",
  "snooker": "A cue sport played on a large table with 22 colored balls.",
  "beach-volleyball": "Played on sand, usually with two players per team.",
  "polo": "Players on horseback use long mallets to hit a ball into a goal.",
  "diving": "Athletes perform acrobatic jumps into water from a board or platform.",
  "rowing": "Athletes propel a boat using oars, racing in a straight line.",
  "snowboarding": "Riders descend snowy slopes standing sideways on one board.",
  "darts": "Players throw small darts at a circular target board.",
  "mountain-biking": "Off-road cycling over rough, hilly, and forested terrain.",

  // HARD
  "lacrosse": "Players use a netted stick to catch, carry, and throw a ball.",
  "netball": "Similar to basketball, but players cannot dribble the ball.",
  "racquetball": "Played on an enclosed indoor court with a rubber ball.",
  "bocce": "Italian lawn sport where players roll balls near a target ball.",
  "petanque": "French sport where players toss metal balls near a small target.",
  "croquet": "Players use mallets to hit balls through wickets on a lawn.",
  "javelin-throw": "Athletes hurl a long spear-like javelin for distance.",
  "shot-put": "Athletes throw a heavy metal ball as far as possible.",
  "discus-throw": "Athletes spin and release a heavy disc for maximum distance.",
  "pole-vault": "Athletes use a flexible pole to launch themselves over a bar.",
  "biathlon": "Combines cross-country skiing with rifle target shooting.",
  "skeleton": "Athletes race headfirst on a small sled down an icy track.",
  "freestyle-skiing": "Skiers perform jumps, spins, and tricks over terrain features.",
  "wakeboarding": "Riders are towed behind a boat while standing on a board.",
  "kitesurfing": "Riders use a large kite to glide across water on a board.",
  "paragliding": "Pilots fly using a fabric wing after launching on foot.",
  "rodeo": "Cowboys compete in events like bull riding and roping.",
  "ski-jumping": "Skiers launch off a ramp, aiming to fly as far as possible.",
  "trampoline": "Gymnasts perform aerial flips and twists while bouncing.",
  "synchronized-swimming": "Swimmers perform routines in unison, timed to music.",
  "modern-pentathlon": "Combines fencing, swimming, riding, shooting, and running.",
  "orienteering": "Racers navigate wooded terrain using a map and compass.",
  "cyclo-cross": "Cyclists race a muddy off-road course, sometimes carrying bikes.",
  "dressage": "A horse performs precise, choreographed movements on command.",
  "show-jumping": "Riders guide horses over a course of raised obstacles.",

  // IMPOSSIBLE
  "sepak-takraw": "Southeast Asian sport played with a rattan ball, no hands allowed.",
  "kabaddi": "Ancient Indian sport; a raider must chant 'kabaddi' on one breath.",
  "hurling": "Fast Irish stick sport, among the world's oldest field games.",
  "pelota-vasca": "Basque ball sport where a scoop-like cesta hurls the ball at speed.",
  "sumo-wrestling": "Japanese sport where wrestlers try to push each other from a ring.",
  "buzkashi": "Afghan national sport; riders vie for a goat carcass on horseback.",
  "calcio-storico": "Brutal Florentine sport blending football, rugby, and wrestling.",
  "shinty": "Scottish Highland stick-and-ball sport related to Irish hurling.",
  "bandy": "Team sport on a large ice rink, played with sticks and a small ball.",
  "underwater-hockey": "Players use short sticks to push a puck along a pool floor.",
  "chess-boxing": "Competitors alternate rounds of chess and boxing in one match.",
  "footvolley": "Beach sport combining volleyball rules with soccer-only footwork.",
  "vovinam": "Vietnamese martial art founded in 1938, blending strikes and locks.",
  "bossaball": "Belgian sport mixing volleyball, football, and a trampoline net.",
  "kok-boru": "Central Asian horseback sport where riders carry a goat carcass.",
  "wife-carrying": "Finnish race where men carry a partner over an obstacle course.",
  "cheese-rolling": "Racers chase a rolling cheese wheel down a steep English hill.",
  "bog-snorkelling": "Welsh race through a muddy peat bog using only flippers.",
  "camel-wrestling": "Turkish tradition where two male camels wrestle for dominance.",
  "elephant-polo": "Polo played atop elephants, with a mahout steering each mount.",
  "underwater-rugby": "Teams score by placing a ball in a basket on a pool floor.",
  "toe-wrestling": "British contest where opponents lock bare feet to pin the other.",
  "gaelic-football": "Irish sport blending soccer and rugby, played with a round ball.",
  "australian-rules-football": "Fast-paced Australian sport on an oval field with tall goalposts.",
  "korfball": "Dutch sport with mixed-gender teams shooting into a basket.",
};
