// E231 "Guess the Sport by Emoji" — 4th sport-emoji episode — 100 sports · 25/tier · clue = plain Unicode emoji
// VO: sfx/e231-<id>.wav
export const SPORTS_EMOJI4 = [
  // ===== EASY =====
  { id: "flag-football", title: "Flag Football", emojis: "🏈🚩", level: "easy" },
  { id: "bodyboarding", title: "Bodyboarding", emojis: "🏄🛟", level: "easy" },
  { id: "stand-up-paddleboarding", title: "Stand-Up Paddleboarding", emojis: "🛶🧘", level: "easy" },
  { id: "rhythmic-gymnastics", title: "Rhythmic Gymnastics", emojis: "🤸🎀", level: "easy" },
  { id: "acrobatic-gymnastics", title: "Acrobatic Gymnastics", emojis: "🤸🤝", level: "easy" },
  { id: "baton-twirling", title: "Baton Twirling", emojis: "🪄🌀", level: "easy" },
  { id: "trail-running", title: "Trail Running", emojis: "🏃🌲", level: "easy" },
  { id: "ultramarathon", title: "Ultramarathon", emojis: "🏃🌙", level: "easy" },
  { id: "sack-race", title: "Sack Race", emojis: "🦵👜", level: "easy" },
  { id: "three-legged-race", title: "Three-Legged Race", emojis: "🦵🤝", level: "easy" },
  { id: "yo-yo", title: "Yo-Yo", emojis: "🪀🌀", level: "easy" },
  { id: "kite-flying", title: "Kite Flying", emojis: "🪁🌬", level: "easy" },
  { id: "foosball", title: "Foosball", emojis: "🕹⚽", level: "easy" },
  { id: "air-hockey", title: "Air Hockey", emojis: "🏒🧊", level: "easy" },
  { id: "mahjong", title: "Mahjong", emojis: "🀄🏆", level: "easy" },
  { id: "poker", title: "Poker", emojis: "🃏🏆", level: "easy" },
  { id: "scrabble", title: "Scrabble", emojis: "🔤🏆", level: "easy" },
  { id: "canoe-slalom", title: "Canoe Slalom", emojis: "🛶🚩", level: "easy" },
  { id: "outrigger-canoe-racing", title: "Outrigger Canoe Racing", emojis: "🛶🏝", level: "easy" },
  { id: "reining", title: "Reining", emojis: "🐎🌀", level: "easy" },
  { id: "tent-pegging", title: "Tent Pegging", emojis: "🐎🎯", level: "easy" },
  { id: "flyball", title: "Flyball", emojis: "🐕🎾", level: "easy" },
  { id: "carrom", title: "Carrom", emojis: "🎯🪙", level: "easy" },
  { id: "lucha-libre", title: "Lucha Libre", emojis: "🤼🎭", level: "easy" },
  { id: "slamball", title: "Slamball", emojis: "🏀🤸", level: "easy" },
  // ===== MEDIUM =====
  { id: "sambo", title: "Sambo", emojis: "🥋🐻", level: "medium" },
  { id: "kurash", title: "Kurash", emojis: "🥋🎗", level: "medium" },
  { id: "kalaripayattu", title: "Kalaripayattu", emojis: "🤺🛡", level: "medium" },
  { id: "kyudo", title: "Kyudo", emojis: "🏹⛩", level: "medium" },
  { id: "iaido", title: "Iaido", emojis: "⚔⛩", level: "medium" },
  { id: "krabi-krabong", title: "Krabi-Krabong", emojis: "⚔🛡", level: "medium" },
  { id: "mallakhamba", title: "Mallakhamba", emojis: "🤸🪵", level: "medium" },
  { id: "tractor-pulling", title: "Tractor Pulling", emojis: "🚜🏆", level: "medium" },
  { id: "caber-toss", title: "Caber Toss", emojis: "🪵🏆", level: "medium" },
  { id: "stone-lifting", title: "Stone Lifting", emojis: "🪨💪", level: "medium" },
  { id: "finger-wrestling", title: "Finger Wrestling", emojis: "👆💪", level: "medium" },
  { id: "pig-racing", title: "Pig Racing", emojis: "🐷🏁", level: "medium" },
  { id: "cockroach-racing", title: "Cockroach Racing", emojis: "🪳🏁", level: "medium" },
  { id: "frog-jumping", title: "Frog Jumping", emojis: "🐸🏆", level: "medium" },
  { id: "dambe", title: "Dambe", emojis: "🥊🪢", level: "medium" },
  { id: "lethwei", title: "Lethwei", emojis: "🥊🩸", level: "medium" },
  { id: "catch-wrestling", title: "Catch Wrestling", emojis: "🤼🎪", level: "medium" },
  { id: "schwingen", title: "Schwingen", emojis: "🤼🧀", level: "medium" },
  { id: "laamb", title: "Laamb", emojis: "🤼🏖", level: "medium" },
  { id: "water-jousting", title: "Water Jousting", emojis: "🚣🤺", level: "medium" },
  { id: "ulama", title: "Ulama", emojis: "🏐🗿", level: "medium" },
  { id: "chinlone", title: "Chinlone", emojis: "🥎🎋", level: "medium" },
  { id: "torball", title: "Torball", emojis: "🥎🔔", level: "medium" },
  { id: "platform-tennis", title: "Platform Tennis", emojis: "🎾🧱", level: "medium" },
  { id: "frontenis", title: "Frontenis", emojis: "🎾🏛", level: "medium" },
  // ===== HARD =====
  { id: "bubble-soccer", title: "Bubble Soccer", emojis: "⚽🫧", level: "hard" },
  { id: "mountainboarding", title: "Mountainboarding", emojis: "🛹⛰", level: "hard" },
  { id: "sandboarding", title: "Sandboarding", emojis: "🏂🏜", level: "hard" },
  { id: "dune-bashing", title: "Dune Bashing", emojis: "🚙🏜", level: "hard" },
  { id: "grass-skiing", title: "Grass Skiing", emojis: "🎿🌿", level: "hard" },
  { id: "ice-cross-downhill", title: "Ice Cross Downhill", emojis: "⛸⬇", level: "hard" },
  { id: "sport-stacking", title: "Sport Stacking", emojis: "🥤🏆", level: "hard" },
  { id: "kneeboarding", title: "Kneeboarding", emojis: "🦵🌊", level: "hard" },
  { id: "canyoning", title: "Canyoning", emojis: "🧗💦", level: "hard" },
  { id: "coasteering", title: "Coasteering", emojis: "🧗🌊", level: "hard" },
  { id: "river-boarding", title: "River Boarding", emojis: "🏄🏞", level: "hard" },
  { id: "team-roping", title: "Team Roping", emojis: "🐎🪢", level: "hard" },
  { id: "cutting", title: "Cutting", emojis: "🐎🐄", level: "hard" },
  { id: "steer-wrestling", title: "Steer Wrestling", emojis: "🐂💪", level: "hard" },
  { id: "speed-riding", title: "Speed Riding", emojis: "🎿🪂", level: "hard" },
  { id: "kite-fighting", title: "Kite Fighting", emojis: "🪁⚔", level: "hard" },
  { id: "segway-polo", title: "Segway Polo", emojis: "🛴🏑", level: "hard" },
  { id: "rogaining", title: "Rogaining", emojis: "🧭🏃", level: "hard" },
  { id: "aerobatics", title: "Aerobatics", emojis: "✈🌀", level: "hard" },
  { id: "plogging", title: "Plogging", emojis: "🏃🗑", level: "hard" },
  { id: "wheelbarrow-racing", title: "Wheelbarrow Racing", emojis: "🛒🏁", level: "hard" },
  { id: "bathtub-racing", title: "Bathtub Racing", emojis: "🛁🏁", level: "hard" },
  { id: "swamp-football", title: "Swamp Football", emojis: "⚽🥾", level: "hard" },
  { id: "camel-polo", title: "Camel Polo", emojis: "🐫🏑", level: "hard" },
  { id: "naginatajutsu", title: "Naginatajutsu", emojis: "🥍⛩", level: "hard" },
  // ===== IMPOSSIBLE =====
  { id: "course-landaise", title: "Course Landaise", emojis: "🐂🤸", level: "impossible" },
  { id: "battledore-and-shuttlecock", title: "Battledore and Shuttlecock", emojis: "🏸🪶", level: "impossible" },
  { id: "jugger", title: "Jugger", emojis: "🏃🦴", level: "impossible" },
  { id: "powerbocking", title: "Powerbocking", emojis: "🦵🦘", level: "impossible" },
  { id: "trugo", title: "Trugo", emojis: "🛞🔨", level: "impossible" },
  { id: "extreme-ironing", title: "Extreme Ironing", emojis: "👕🏔", level: "impossible" },
  { id: "wing-walking", title: "Wing Walking", emojis: "✈🤸", level: "impossible" },
  { id: "bo-taoshi", title: "Bo-Taoshi", emojis: "🏫🪵", level: "impossible" },
  { id: "snow-snake", title: "Snow Snake", emojis: "❄🐍", level: "impossible" },
  { id: "bokator", title: "Bokator", emojis: "🥋🦁", level: "impossible" },
  { id: "silambam", title: "Silambam", emojis: "🥍🎋", level: "impossible" },
  { id: "systema", title: "Systema", emojis: "🥋❄", level: "impossible" },
  { id: "pankration", title: "Pankration", emojis: "🏛🥊", level: "impossible" },
  { id: "dachshund-racing", title: "Dachshund Racing", emojis: "🐕🏁", level: "impossible" },
  { id: "camel-jumping", title: "Camel Jumping", emojis: "🐫⬆", level: "impossible" },
  { id: "haggis-hurling", title: "Haggis Hurling", emojis: "🍖🎯", level: "impossible" },
  { id: "welly-wanging", title: "Welly Wanging", emojis: "👢🎯", level: "impossible" },
  { id: "gurning", title: "Gurning", emojis: "😜🏆", level: "impossible" },
  { id: "egg-throwing", title: "Egg Throwing", emojis: "🥚🎯", level: "impossible" },
  { id: "black-pudding-throwing", title: "Black Pudding Throwing", emojis: "🌭🎯", level: "impossible" },
  { id: "pumpkin-boat-racing", title: "Pumpkin Boat Racing", emojis: "🎃🌊", level: "impossible" },
  { id: "buffalo-racing", title: "Buffalo Racing", emojis: "🐃🏁", level: "impossible" },
  { id: "bed-racing", title: "Bed Racing", emojis: "🛏🏁", level: "impossible" },
  { id: "barrel-jumping", title: "Barrel Jumping", emojis: "⛸🛢", level: "impossible" },
  { id: "tour-skating", title: "Tour Skating", emojis: "⛸🌲", level: "impossible" },
];
