// E231 emoji-sport facts — one verified <=70-char fact per sport, shown on reveal.
export const SPORTS_EMOJI4_FACTS = {
  // EASY
  "flag-football": "A no-tackle football variant; pulling a flag replaces tackling.",
  "bodyboarding": "Riders lie or kneel on a short board to ride ocean waves.",
  "stand-up-paddleboarding": "Paddlers stand on a wide board and use one oar to move.",
  "rhythmic-gymnastics": "Gymnasts perform with ribbon, hoop, ball, or clubs to music.",
  "acrobatic-gymnastics": "Partners build lifts and balances, unlike solo gymnastics.",
  "baton-twirling": "Athletes spin, toss, and catch a baton in time with music.",
  "trail-running": "Distance running on off-road trails through hills and forests.",
  "ultramarathon": "Any footrace longer than the standard 42.2 km marathon.",
  "sack-race": "Racers hop toward the finish with both legs inside a sack.",
  "three-legged-race": "Two partners tie one leg together and run as a team.",
  "yo-yo": "Competitors perform tricks with a spinning, string-looped toy.",
  "kite-flying": "Competitive flyers are judged on control, height, and design.",
  "foosball": "A tabletop soccer game played with rows of spinning figures.",
  "air-hockey": "Players use paddles to slide a puck across a low-friction table.",
  "mahjong": "A Chinese tile game; competitive play has world championships.",
  "poker": "A betting card game of skill; the World Series crowns champions.",
  "scrabble": "Players form words on a board using lettered tiles for points.",
  "canoe-slalom": "Paddlers navigate a whitewater course through hanging gates.",
  "outrigger-canoe-racing": "Crews paddle a canoe with a stabilizing float, a Pacific sport.",
  "reining": "A Western riding event judging a horse's spins, stops, and circles.",
  "tent-pegging": "Riders spear small ground targets with a lance at a gallop.",
  "flyball": "Dogs race a relay over hurdles to fetch a ball from a box.",
  "carrom": "Players flick a striker disc to pocket smaller discs on a board.",
  "lucha-libre": "Mexican wrestling famous for colorful masks and aerial moves.",
  "slamball": "A basketball hybrid played on trampolines for huge dunks.",
  // MEDIUM
  "sambo": "A Russian combat sport blending judo and wrestling techniques.",
  "kurash": "An Uzbek belt-wrestling sport; only upper-body grips are allowed.",
  "kalaripayattu": "One of the oldest martial arts, from Kerala, India.",
  "kyudo": "Japanese archery focused on form and spirit, not just accuracy.",
  "iaido": "A Japanese martial art centered on drawing the sword smoothly.",
  "krabi-krabong": "A Thai weapons martial art using swords and staves.",
  "mallakhamba": "Indian gymnasts perform poses while gripping a wooden pole.",
  "tractor-pulling": "Tractors drag a heavy sled as far as possible down a track.",
  "caber-toss": "Highland Games athletes flip a long wooden pole end over end.",
  "stone-lifting": "Basque athletes lift heavy stones as a traditional strength test.",
  "finger-wrestling": "Bavarian rivals hook fingers through a loop and try to pull.",
  "pig-racing": "Piglets sprint down a short track at county fairs.",
  "cockroach-racing": "Insects race on a track each Australia Day in Brisbane.",
  "frog-jumping": "Frogs compete for distance, inspired by a Mark Twain story.",
  "dambe": "A Nigerian boxing sport where one fist is wrapped in cord.",
  "lethwei": "Myanmar's bare-knuckle boxing, fought without gloves.",
  "catch-wrestling": "A grappling style once performed at carnivals and fairs.",
  "schwingen": "Swiss wrestlers grip canvas shorts and fight in a sawdust ring.",
  "laamb": "Traditional Senegalese wrestling, often fought on sand.",
  "water-jousting": "A standing jouster lances his rival off a high platform into the water.",
  "ulama": "An ancient Mesoamerican ball game still played in Mexico today.",
  "chinlone": "A flowing, noncompetitive cane-ball game from Myanmar.",
  "torball": "A bell inside the ball lets blind athletes play by sound.",
  "platform-tennis": "Paddle tennis on a small court enclosed by wire screens.",
  "frontenis": "A Basque pelota sport played with rackets against a wall.",
  // HARD
  "bubble-soccer": "Players wear inflatable bubbles and bounce off each other.",
  "mountainboarding": "Riders bomb down dirt trails on a board with four wheels.",
  "sandboarding": "Boarders slide down sand dunes much like snowboarding.",
  "dune-bashing": "Drivers navigate 4x4s over steep desert dunes for sport.",
  "grass-skiing": "Skiers use roller-tracked skis to glide down grassy hills.",
  "ice-cross-downhill": "Skaters race downhill together on a twisting, icy track.",
  "sport-stacking": "Competitors stack and unstack cups in set patterns for speed.",
  "kneeboarding": "Riders kneel on a small board while towed behind a boat.",
  "canyoning": "Athletes descend canyons by climbing, jumping, and swimming.",
  "coasteering": "Explorers move along rocky coastlines by climbing and swimming.",
  "river-boarding": "Riders lie on a small board and surf whitewater rapids.",
  "team-roping": "Two mounted riders rope a steer's head and heels together.",
  "cutting": "A rider and horse work together to separate a cow from a herd.",
  "steer-wrestling": "A rider leaps from a horse to wrestle a steer to the ground.",
  "speed-riding": "Skiers use a small paraglider wing to fly down mountain slopes.",
  "kite-fighting": "Flyers coat kite strings with glass to cut down rivals' kites.",
  "segway-polo": "Players ride Segways instead of horses to hit a ball.",
  "rogaining": "Teams navigate long distances by compass over 24-hour events.",
  "aerobatics": "Pilots perform loops and rolls, judged in world championships.",
  "plogging": "Joggers pick up litter along their run; it began in Sweden.",
  "wheelbarrow-racing": "One racer pushes a partner walking on their hands.",
  "bathtub-racing": "Modified bathtubs race across open water in Nanaimo, Canada.",
  "swamp-football": "Soccer played in ankle-deep mud, popular in Finland.",
  "camel-polo": "Polo played while riding camels instead of horses.",
  "naginatajutsu": "A Japanese martial art using a long-handled bladed pole.",
  // IMPOSSIBLE
  "course-landaise": "French athletes dodge a charging cow without harming it.",
  "battledore-and-shuttlecock": "A racket-and-shuttlecock game that predates modern badminton.",
  "jugger": "A foam-weapon team sport inspired by a 1989 cult film.",
  "powerbocking": "Athletes bound high and fast on spring-loaded jumping stilts.",
  "trugo": "Australian railway workers invented this ring-and-mallet game.",
  "extreme-ironing": "Competitors iron clothes in extreme places like cliffs.",
  "wing-walking": "Performers stand and move on the wings of a flying biplane.",
  "bo-taoshi": "Teams battle to topple or defend a tall pole in Japan.",
  "snow-snake": "A carved wooden dart is thrown to slide far across snow.",
  "bokator": "A Cambodian martial art whose name loosely means 'lion fighting'.",
  "silambam": "A Tamil martial art built around a long bamboo staff.",
  "systema": "A Russian martial art built on breathing, relaxation, and timing.",
  "pankration": "An ancient Greek combat sport combining boxing and wrestling.",
  "dachshund-racing": "Wiener dogs sprint short tracks at novelty racing events.",
  "camel-jumping": "Yemeni tribesmen leap over a row of standing camels.",
  "haggis-hurling": "Competitors throw a haggis for distance in Scotland.",
  "welly-wanging": "Britons compete to throw a rubber Wellington boot the farthest.",
  "gurning": "Competitors pull the most extreme, distorted facial expression.",
  "egg-throwing": "Pairs toss a raw egg back and forth without breaking it.",
  "black-pudding-throwing": "Throwers knock Yorkshire puddings off a plinth with black puddings.",
  "pumpkin-boat-racing": "Racers paddle hollowed-out giant pumpkins across a lake.",
  "buffalo-racing": "Farmers race water buffalo through mud in Thailand each year.",
  "bed-racing": "Teams push wheeled beds down a course as fast as possible.",
  "barrel-jumping": "Skaters leap over a row of barrels on ice for distance.",
  "tour-skating": "Dutch skaters tour long distances across frozen canals.",
};
