// E170 «Guess the Superpower by Emoji» — 100 superpowers · 25/tier
// VO: sfx/e170-<id>.wav
export const SUPERPOWER_EMOJI_FACTS = {
  // EASY
  "flight": "Soaring through the air unaided — Superman's classic power.",
  "invisibility": "Becoming unseen by bending or blocking light.",
  "super-strength": "Lifting far beyond human limits, like the Hulk.",
  "super-speed": "Moving faster than the eye can follow — the Flash's gift.",
  "telepathy": "Reading and projecting thoughts, like Professor X.",
  "telekinesis": "Moving objects with the mind alone.",
  "time-travel": "Journeying into the past or the future.",
  "teleportation": "Vanishing here and reappearing elsewhere instantly.",
  "pyrokinesis": "Creating and controlling fire with the mind.",
  "cryokinesis": "Generating and shaping ice and cold.",
  "x-ray-vision": "Seeing through solid objects, like Superman.",
  "laser-eyes": "Firing energy beams straight from the eyes.",
  "healing-factor": "Rapidly healing wounds — Wolverine's power.",
  "shapeshifting": "Changing one's form or appearance at will.",
  "mind-control": "Bending others' will and actions to your own like a puppet.",
  "force-field": "Projecting a protective energy barrier.",
  "fire-breathing": "Exhaling flames like a dragon.",
  "super-hearing": "Detecting sounds far beyond normal range.",
  "night-vision": "Seeing clearly in total darkness.",
  "wall-crawling": "Sticking to and climbing sheer walls.",
  "web-slinging": "Shooting webs to swing and trap — Spider-Man's.",
  "super-jump": "Leaping enormous heights and distances.",
  "electrokinesis": "Generating and controlling electricity.",
  "water-control": "Bending and shaping water at will.",
  "freeze-breath": "Exhaling frost to freeze things solid.",
  // MEDIUM
  "levitation": "Floating in the air without moving a muscle.",
  "regeneration": "Regrowing lost limbs and tissue.",
  "elasticity": "Stretching the body like rubber — Mr. Fantastic.",
  "duplication": "Creating multiple copies of oneself.",
  "intangibility": "Passing through solid matter like a ghost.",
  "precognition": "Seeing events before they happen.",
  "magnetism": "Controlling metal and magnetic fields — Magneto.",
  "super-agility": "Superhuman balance, reflexes, and coordination.",
  "enhanced-durability": "A body that resists damage and injury.",
  "sonic-scream": "Unleashing destructive sound waves — Black Bolt.",
  "astral-projection": "Sending the spirit outside the body.",
  "immortality": "Living forever, immune to aging and death.",
  "aerokinesis": "Controlling wind and air currents.",
  "geokinesis": "Manipulating earth, rock, and stone.",
  "light-manipulation": "Bending and generating light itself.",
  "shadow-manipulation": "Controlling darkness and shadows.",
  "plant-control": "Commanding plants to grow — Poison Ivy's power.",
  "weather-control": "Summoning storms and wind — Storm's power.",
  "animal-communication": "Speaking with and commanding animals.",
  "necromancy": "Raising and controlling the dead.",
  "enhanced-senses": "Sight, hearing, and smell far above human.",
  "danger-sense": "A tingling warning of nearby threats.",
  "camouflage": "Blending perfectly into any surroundings.",
  "density-control": "Altering body density to be light or unbreakable.",
  "gravity-control": "Bending gravity to lift or crush.",
  // HARD
  "chronokinesis": "Speeding up or slowing down time itself.",
  "time-stop": "Freezing time completely for everyone but you.",
  "biokinesis": "Manipulating living organisms and biology.",
  "technopathy": "Controlling machines and tech with the mind.",
  "sound-manipulation": "Shaping and controlling sound waves.",
  "empathy": "Sensing and feeling the emotions of others.",
  "illusion-casting": "Creating vivid illusions to fool the senses.",
  "portal-creation": "Opening doorways across space.",
  "echolocation": "Navigating by sound like a bat.",
  "molecular-combustion": "Making matter explode at a touch.",
  "probability-manipulation": "Bending luck and odds — Domino's power.",
  "acid-generation": "Producing corrosive acid from the body.",
  "poison-generation": "Secreting deadly toxins and venom.",
  "super-intelligence": "A genius-level mind beyond any human.",
  "photographic-memory": "Recalling everything seen in perfect detail.",
  "size-manipulation": "Growing giant or shrinking tiny — Ant-Man.",
  "gigantification": "Growing to colossal size at will.",
  "miniaturization": "Shrinking down to microscopic size.",
  "super-reflexes": "Reacting and dodging faster than possible.",
  "retractable-claws": "Retractable claws that cut through anything.",
  "underwater-breathing": "Breathing freely beneath the sea — Aquaman.",
  "heat-vision": "Emitting searing heat beams from the eyes.",
  "frost-touch": "Freezing anything with a single touch.",
  "healing-touch": "Mending others' wounds with a touch.",
  "energy-blast": "Firing concentrated bolts of raw energy.",
  // IMPOSSIBLE
  "ergokinesis": "Controlling pure energy in all its forms.",
  "vibration-manipulation": "Generating and controlling vibrations and tremors.",
  "telumkinesis": "Controlling and summoning weapons at will.",
  "osteokinesis": "Manipulating bone, one's own or others'.",
  "hemokinesis": "Controlling blood inside and outside the body.",
  "thermokinesis": "Controlling heat and temperature.",
  "vitakinesis": "Manipulating life force to heal or harm.",
  "void-manipulation": "Controlling empty void and black-hole nothingness.",
  "molecular-manipulation": "Rearranging matter atom by atom at will.",
  "ferrokinesis": "Bending and shaping metal at will.",
  "petrification": "Turning living flesh to solid stone with a touch.",
  "fungus-control": "Growing and commanding fungi, mold, and mushrooms.",
  "reactive-adaptation": "Body adapts instantly to any threat — Darwin.",
  "power-mimicry": "Copying the powers of anyone nearby.",
  "power-absorption": "Draining others' abilities — Rogue's power.",
  "reality-warping": "Rewriting reality itself at will.",
  "transmutation": "Turning one substance into another.",
  "invulnerability": "A body no attack can harm or pierce.",
  "antigravity": "Defying gravity to float and hover freely.",
  "dimensional-travel": "Crossing between parallel worlds and realms.",
  "clairvoyance": "Perceiving distant people, places, and events.",
  "psychometry": "Reading an object's history by touch.",
  "crystal-manipulation": "Growing and shaping crystals and gems at will.",
  "sound-mimicry": "Perfectly imitating any voice or sound.",
  "omnilingualism": "Instantly understanding every language.",
};
