// E170 «Guess the Superpower by Emoji» — 100 superpowers · 25/tier
// VO: sfx/e170-<id>.wav
export const SUPERPOWER_EMOJI = [
  // ===== EASY =====
  { id: "flight", title: "Flight", emojis: "🦅☁", level: "easy" },
  { id: "invisibility", title: "Invisibility", emojis: "👤❓", level: "easy" },
  { id: "super-strength", title: "Super Strength", emojis: "💪🪨", level: "easy" },
  { id: "super-speed", title: "Super Speed", emojis: "🏃💨", level: "easy" },
  { id: "telepathy", title: "Telepathy", emojis: "🧠🗣", level: "easy" },
  { id: "telekinesis", title: "Telekinesis", emojis: "🧠📦", level: "easy" },
  { id: "time-travel", title: "Time Travel", emojis: "⏰🌀", level: "easy" },
  { id: "teleportation", title: "Teleportation", emojis: "👤🚪", level: "easy" },
  { id: "pyrokinesis", title: "Pyrokinesis", emojis: "🔥🧠", level: "easy" },
  { id: "cryokinesis", title: "Cryokinesis", emojis: "❄🧠", level: "easy" },
  { id: "x-ray-vision", title: "X-Ray Vision", emojis: "👁🦴", level: "easy" },
  { id: "laser-eyes", title: "Laser Vision", emojis: "👀⚡", level: "easy" },
  { id: "healing-factor", title: "Healing Factor", emojis: "🩹✨", level: "easy" },
  { id: "shapeshifting", title: "Shapeshifting", emojis: "🎭🌀", level: "easy" },
  { id: "mind-control", title: "Mind Control", emojis: "🧠🎮", level: "easy" },
  { id: "force-field", title: "Force Field", emojis: "🛡👤", level: "easy" },
  { id: "fire-breathing", title: "Fire Breathing", emojis: "🐉🔥", level: "easy" },
  { id: "super-hearing", title: "Super Hearing", emojis: "👂🔊", level: "easy" },
  { id: "night-vision", title: "Night Vision", emojis: "👁🌑", level: "easy" },
  { id: "wall-crawling", title: "Wall-Crawling", emojis: "🕷👤", level: "easy" },
  { id: "web-slinging", title: "Web-Slinging", emojis: "🕷🕸", level: "easy" },
  { id: "super-jump", title: "Super Jump", emojis: "🦘💨", level: "easy" },
  { id: "electrokinesis", title: "Electrokinesis", emojis: "⚡✋", level: "easy" },
  { id: "water-control", title: "Hydrokinesis", emojis: "🌊✋", level: "easy" },
  { id: "freeze-breath", title: "Freeze Breath", emojis: "🌬❄", level: "easy" },
  // ===== MEDIUM =====
  { id: "levitation", title: "Levitation", emojis: "🧘☁", level: "medium" },
  { id: "regeneration", title: "Regeneration", emojis: "🦎✨", level: "medium" },
  { id: "elasticity", title: "Elasticity", emojis: "✋📏", level: "medium" },
  { id: "duplication", title: "Duplication", emojis: "👤👥", level: "medium" },
  { id: "intangibility", title: "Intangibility", emojis: "👻🧱", level: "medium" },
  { id: "precognition", title: "Precognition", emojis: "🔮👁", level: "medium" },
  { id: "magnetism", title: "Magnetism", emojis: "🧲🔩", level: "medium" },
  { id: "super-agility", title: "Super Agility", emojis: "🤸💨", level: "medium" },
  { id: "enhanced-durability", title: "Enhanced Durability", emojis: "🛡🪨", level: "medium" },
  { id: "sonic-scream", title: "Sonic Scream", emojis: "📢💥", level: "medium" },
  { id: "astral-projection", title: "Astral Projection", emojis: "👻🌟", level: "medium" },
  { id: "immortality", title: "Immortality", emojis: "♾💀", level: "medium" },
  { id: "aerokinesis", title: "Aerokinesis", emojis: "🌬✋", level: "medium" },
  { id: "geokinesis", title: "Geokinesis", emojis: "🪨✋", level: "medium" },
  { id: "light-manipulation", title: "Photokinesis", emojis: "☀✋", level: "medium" },
  { id: "shadow-manipulation", title: "Umbrakinesis", emojis: "🌑✋", level: "medium" },
  { id: "plant-control", title: "Chlorokinesis", emojis: "🌱✋", level: "medium" },
  { id: "weather-control", title: "Weather Control", emojis: "🌩✋", level: "medium" },
  { id: "animal-communication", title: "Animal Communication", emojis: "🗣🐾", level: "medium" },
  { id: "necromancy", title: "Necromancy", emojis: "💀✨", level: "medium" },
  { id: "enhanced-senses", title: "Enhanced Senses", emojis: "👁👂", level: "medium" },
  { id: "danger-sense", title: "Danger Sense", emojis: "🕷💥", level: "medium" },
  { id: "camouflage", title: "Camouflage", emojis: "🦎🎨", level: "medium" },
  { id: "density-control", title: "Density Control", emojis: "👤⚖", level: "medium" },
  { id: "gravity-control", title: "Gravity Control", emojis: "🌍✋", level: "medium" },
  // ===== HARD =====
  { id: "chronokinesis", title: "Chronokinesis", emojis: "⏳✋", level: "hard" },
  { id: "time-stop", title: "Time Stop", emojis: "⏱🤚", level: "hard" },
  { id: "biokinesis", title: "Biokinesis", emojis: "🧬✋", level: "hard" },
  { id: "technopathy", title: "Technopathy", emojis: "🧠💻", level: "hard" },
  { id: "sound-manipulation", title: "Audiokinesis", emojis: "🔊✋", level: "hard" },
  { id: "empathy", title: "Empathy", emojis: "💗🧠", level: "hard" },
  { id: "illusion-casting", title: "Illusion Casting", emojis: "🪄👁", level: "hard" },
  { id: "portal-creation", title: "Portal Creation", emojis: "🌌🪄", level: "hard" },
  { id: "echolocation", title: "Echolocation", emojis: "🦇🔊", level: "hard" },
  { id: "molecular-combustion", title: "Molecular Combustion", emojis: "💥✋", level: "hard" },
  { id: "probability-manipulation", title: "Probability Manipulation", emojis: "🎲🪄", level: "hard" },
  { id: "acid-generation", title: "Acid Generation", emojis: "🧪💧", level: "hard" },
  { id: "poison-generation", title: "Poison Generation", emojis: "🧪🐍", level: "hard" },
  { id: "super-intelligence", title: "Super Intelligence", emojis: "🧠💡", level: "hard" },
  { id: "photographic-memory", title: "Photographic Memory", emojis: "🧠📸", level: "hard" },
  { id: "size-manipulation", title: "Size Manipulation", emojis: "🐘🐜", level: "hard" },
  { id: "gigantification", title: "Gigantification", emojis: "👤🐘", level: "hard" },
  { id: "miniaturization", title: "Miniaturization", emojis: "👤🐜", level: "hard" },
  { id: "super-reflexes", title: "Super Reflexes", emojis: "🤚💨", level: "hard" },
  { id: "retractable-claws", title: "Retractable Claws", emojis: "🐈🗡", level: "hard" },
  { id: "underwater-breathing", title: "Underwater Breathing", emojis: "🐟🫧", level: "hard" },
  { id: "heat-vision", title: "Heat Vision", emojis: "👁🔥", level: "hard" },
  { id: "frost-touch", title: "Frost Touch", emojis: "✋❄", level: "hard" },
  { id: "healing-touch", title: "Healing Touch", emojis: "✋✨", level: "hard" },
  { id: "energy-blast", title: "Energy Blast", emojis: "💥✨", level: "hard" },
  // ===== IMPOSSIBLE =====
  { id: "ergokinesis", title: "Ergokinesis", emojis: "💫✋", level: "impossible" },
  { id: "vibration-manipulation", title: "Vibration Manipulation", emojis: "📳✋", level: "impossible" },
  { id: "telumkinesis", title: "Weapon Manipulation", emojis: "⚔✋", level: "impossible" },
  { id: "osteokinesis", title: "Bone Manipulation", emojis: "🦴✋", level: "impossible" },
  { id: "hemokinesis", title: "Blood Manipulation", emojis: "🩸✋", level: "impossible" },
  { id: "thermokinesis", title: "Thermokinesis", emojis: "🌡✋", level: "impossible" },
  { id: "vitakinesis", title: "Life Manipulation", emojis: "🌿✨", level: "impossible" },
  { id: "void-manipulation", title: "Void Manipulation", emojis: "🕳✋", level: "impossible" },
  { id: "molecular-manipulation", title: "Molecular Manipulation", emojis: "⚛✋", level: "impossible" },
  { id: "ferrokinesis", title: "Metal Manipulation", emojis: "🔩✋", level: "impossible" },
  { id: "petrification", title: "Petrification", emojis: "🗿✋", level: "impossible" },
  { id: "fungus-control", title: "Mycokinesis", emojis: "🍄✋", level: "impossible" },
  { id: "reactive-adaptation", title: "Reactive Adaptation", emojis: "🧬🔄", level: "impossible" },
  { id: "power-mimicry", title: "Power Mimicry", emojis: "🪞✨", level: "impossible" },
  { id: "power-absorption", title: "Power Absorption", emojis: "🔋✨", level: "impossible" },
  { id: "reality-warping", title: "Reality Warping", emojis: "🌀✨", level: "impossible" },
  { id: "transmutation", title: "Transmutation", emojis: "🪨💎", level: "impossible" },
  { id: "invulnerability", title: "Invulnerability", emojis: "🛡💥", level: "impossible" },
  { id: "antigravity", title: "Antigravity", emojis: "🎈👤", level: "impossible" },
  { id: "dimensional-travel", title: "Dimensional Travel", emojis: "🕳👤", level: "impossible" },
  { id: "clairvoyance", title: "Clairvoyance", emojis: "👁🌍", level: "impossible" },
  { id: "psychometry", title: "Psychometry", emojis: "✋🔮", level: "impossible" },
  { id: "crystal-manipulation", title: "Crystallokinesis", emojis: "💎✋", level: "impossible" },
  { id: "sound-mimicry", title: "Sound Mimicry", emojis: "🦜🔊", level: "impossible" },
  { id: "omnilingualism", title: "Omnilingualism", emojis: "🌐🗣", level: "impossible" },
];
