// E30 «Guess the Tech & App Logo» — GuessSync · 100 شعار · صعوبة مطلقة (سهل ~عالمي ← مستحيل <3%). image: logos/<slug>.svg | VO: sfx/nm-<slug>.wav
export const TECHLOGOS = [
  // ===== EASY (25) =====
  { slug: "notion", name: "Notion", level: "easy" },
  { slug: "figma", name: "Figma", level: "easy" },
  { slug: "threads", name: "Threads", level: "easy" },
  { slug: "mastodon", name: "Mastodon", level: "easy" },
  { slug: "bluesky", name: "Bluesky", level: "easy" },
  { slug: "bitcoin", name: "Bitcoin", level: "easy" },
  { slug: "ethereum", name: "Ethereum", level: "easy" },
  { slug: "python", name: "Python", level: "easy" },
  { slug: "react", name: "React", level: "easy" },
  { slug: "googledocs", name: "Google Docs", level: "easy" },
  { slug: "googlesheets", name: "Google Sheets", level: "easy" },
  { slug: "ubereats", name: "Uber Eats", level: "easy" },
  { slug: "doordash", name: "DoorDash", level: "easy" },
  { slug: "deliveroo", name: "Deliveroo", level: "easy" },
  { slug: "applepay", name: "Apple Pay", level: "easy" },
  { slug: "giphy", name: "GIPHY", level: "easy" },
  { slug: "imgur", name: "Imgur", level: "easy" },
  { slug: "roku", name: "Roku", level: "easy" },
  { slug: "crunchyroll", name: "Crunchyroll", level: "easy" },
  { slug: "deezer", name: "Deezer", level: "easy" },
  { slug: "dailymotion", name: "Dailymotion", level: "easy" },
  { slug: "bookingdotcom", name: "Booking.com", level: "easy" },
  { slug: "expedia", name: "Expedia", level: "easy" },
  { slug: "godaddy", name: "GoDaddy", level: "easy" },
  { slug: "goodreads", name: "Goodreads", level: "easy" },
  // ===== MEDIUM (25) =====
  { slug: "gitlab", name: "GitLab", level: "medium" },
  { slug: "vercel", name: "Vercel", level: "medium" },
  { slug: "cloudflare", name: "Cloudflare", level: "medium" },
  { slug: "digitalocean", name: "DigitalOcean", level: "medium" },
  { slug: "docker", name: "Docker", level: "medium" },
  { slug: "mongodb", name: "MongoDB", level: "medium" },
  { slug: "obsidian", name: "Obsidian", level: "medium" },
  { slug: "evernote", name: "Evernote", level: "medium" },
  { slug: "todoist", name: "Todoist", level: "medium" },
  { slug: "clickup", name: "ClickUp", level: "medium" },
  { slug: "asana", name: "Asana", level: "medium" },
  { slug: "jira", name: "Jira", level: "medium" },
  { slug: "confluence", name: "Confluence", level: "medium" },
  { slug: "miro", name: "Miro", level: "medium" },
  { slug: "airtable", name: "Airtable", level: "medium" },
  { slug: "calendly", name: "Calendly", level: "medium" },
  { slug: "loom", name: "Loom", level: "medium" },
  { slug: "dribbble", name: "Dribbble", level: "medium" },
  { slug: "behance", name: "Behance", level: "medium" },
  { slug: "unsplash", name: "Unsplash", level: "medium" },
  { slug: "flickr", name: "Flickr", level: "medium" },
  { slug: "vk", name: "VK", level: "medium" },
  { slug: "kakaotalk", name: "KakaoTalk", level: "medium" },
  { slug: "paytm", name: "Paytm", level: "medium" },
  { slug: "nubank", name: "Nubank", level: "medium" },
  // ===== HARD (25) =====
  { slug: "typescript", name: "TypeScript", level: "hard" },
  { slug: "nodedotjs", name: "Node.js", level: "hard" },
  { slug: "nextdotjs", name: "Next.js", level: "hard" },
  { slug: "tailwindcss", name: "Tailwind CSS", level: "hard" },
  { slug: "bootstrap", name: "Bootstrap", level: "hard" },
  { slug: "vuedotjs", name: "Vue.js", level: "hard" },
  { slug: "angular", name: "Angular", level: "hard" },
  { slug: "django", name: "Django", level: "hard" },
  { slug: "laravel", name: "Laravel", level: "hard" },
  { slug: "kotlin", name: "Kotlin", level: "hard" },
  { slug: "swift", name: "Swift", level: "hard" },
  { slug: "rust", name: "Rust", level: "hard" },
  { slug: "mysql", name: "MySQL", level: "hard" },
  { slug: "postgresql", name: "PostgreSQL", level: "hard" },
  { slug: "astro", name: "Astro", level: "hard" },
  { slug: "graphql", name: "GraphQL", level: "hard" },
  { slug: "nginx", name: "Nginx", level: "hard" },
  { slug: "linux", name: "Linux", level: "hard" },
  { slug: "raspberrypi", name: "Raspberry Pi", level: "hard" },
  { slug: "arduino", name: "Arduino", level: "hard" },
  { slug: "androidstudio", name: "Android Studio", level: "hard" },
  { slug: "intellijidea", name: "IntelliJ IDEA", level: "hard" },
  { slug: "pycharm", name: "PyCharm", level: "hard" },
  { slug: "sublimetext", name: "Sublime Text", level: "hard" },
  { slug: "npm", name: "npm", level: "hard" },
  // ===== IMPOSSIBLE (25) =====
  { slug: "argo", name: "Argo", level: "impossible" },
  { slug: "grafana", name: "Grafana", level: "impossible" },
  { slug: "terraform", name: "Terraform", level: "impossible" },
  { slug: "ansible", name: "Ansible", level: "impossible" },
  { slug: "deno", name: "Deno", level: "impossible" },
  { slug: "electron", name: "Electron", level: "impossible" },
  { slug: "sqlite", name: "SQLite", level: "impossible" },
  { slug: "debian", name: "Debian", level: "impossible" },
  { slug: "fedora", name: "Fedora", level: "impossible" },
  { slug: "wireshark", name: "Wireshark", level: "impossible" },
  { slug: "neovim", name: "Neovim", level: "impossible" },
  { slug: "vim", name: "Vim", level: "impossible" },
  { slug: "git", name: "Git", level: "impossible" },
  { slug: "notepadplusplus", name: "Notepad++", level: "impossible" },
  { slug: "obsstudio", name: "OBS Studio", level: "impossible" },
  { slug: "audacity", name: "Audacity", level: "impossible" },
  { slug: "jellyfin", name: "Jellyfin", level: "impossible" },
  { slug: "substack", name: "Substack", level: "impossible" },
  { slug: "gumroad", name: "Gumroad", level: "impossible" },
  { slug: "podman", name: "Podman", level: "impossible" },
  { slug: "webex", name: "Webex", level: "impossible" },
  { slug: "mattermost", name: "Mattermost", level: "impossible" },
  { slug: "zoho", name: "Zoho", level: "impossible" },
  { slug: "torproject", name: "Tor", level: "impossible" },
  { slug: "wetransfer", name: "WeTransfer", level: "impossible" },
];
