// E30 «Guess the Tech & App Logo» — one verified ≤70-char fact per logo, shown on reveal.
export const TECHLOGO_FACTS = {
  // ===== EASY =====
  "notion": "All-in-one notes and docs app launched in 2016.",
  "figma": "Browser-based design tool; Adobe deal was called off in 2023.",
  "threads": "Meta's text app hit 100M users in under a week in 2023.",
  "mastodon": "Open-source decentralized social network launched in 2016.",
  "bluesky": "Decentralized social app that spun out of Twitter.",
  "bitcoin": "First cryptocurrency, created by Satoshi Nakamoto in 2009.",
  "ethereum": "Blockchain with smart contracts, launched in 2015.",
  "python": "Popular language named after Monty Python, not the snake.",
  "react": "JavaScript UI library open-sourced by Facebook in 2013.",
  "googledocs": "Google's online word processor, part of Workspace.",
  "googlesheets": "Google's cloud spreadsheet app, part of Workspace.",
  "ubereats": "Uber's food delivery service launched in 2014.",
  "doordash": "Largest food-delivery company in the United States.",
  "deliveroo": "British food-delivery firm founded in London in 2013.",
  "applepay": "Apple's mobile payment service launched in 2014.",
  "giphy": "GIF search engine and library founded in 2013.",
  "imgur": "Image-sharing site born on Reddit in 2009.",
  "roku": "Streaming-device maker; name means 'six' in Japanese.",
  "crunchyroll": "Anime streaming service founded in 2006.",
  "deezer": "French music-streaming service launched in 2007.",
  "dailymotion": "French video-sharing site founded in 2005.",
  "bookingdotcom": "Dutch travel site, one of the world's biggest.",
  "expedia": "Online travel agency spun out of Microsoft in 1996.",
  "godaddy": "Domain registrar and web host founded in 1997.",
  "goodreads": "Book-cataloguing social site bought by Amazon in 2013.",
  // ===== MEDIUM =====
  "gitlab": "DevOps platform run by a fully remote company.",
  "vercel": "Hosting platform and the company behind Next.js.",
  "cloudflare": "CDN and security firm that runs 1.1.1.1 DNS.",
  "digitalocean": "Cloud host known for simple developer droplets.",
  "docker": "Container platform released as open source in 2013.",
  "mongodb": "Popular NoSQL document database launched in 2009.",
  "obsidian": "Markdown note app that stores files locally.",
  "evernote": "Note-taking app once famous for its elephant logo.",
  "todoist": "To-do list app made by Doist, founded in 2007.",
  "clickup": "Project-management app founded in 2017.",
  "asana": "Work-tracking tool from a Facebook co-founder.",
  "jira": "Atlassian's issue tracker, popular with dev teams.",
  "confluence": "Atlassian's team wiki and documentation tool.",
  "miro": "Online collaborative whiteboard platform.",
  "airtable": "Spreadsheet-database hybrid launched in 2012.",
  "calendly": "Scheduling app that automates meeting bookings.",
  "loom": "Screen-recording tool bought by Atlassian in 2023.",
  "dribbble": "Portfolio community for designers, started in 2009.",
  "behance": "Adobe-owned network for showcasing creative work.",
  "unsplash": "Free high-resolution stock photo library.",
  "flickr": "Photo-sharing site founded in 2004.",
  "vk": "Russia's biggest social network, launched in 2006.",
  "kakaotalk": "South Korea's dominant messaging app.",
  "paytm": "Indian digital payments and fintech giant.",
  "nubank": "Brazilian digital bank, one of the world's largest.",
  // ===== HARD =====
  "typescript": "Microsoft's typed superset of JavaScript, 2012.",
  "nodedotjs": "JavaScript runtime built on Chrome's V8 engine.",
  "nextdotjs": "React framework maintained by Vercel.",
  "tailwindcss": "Utility-first CSS framework released in 2017.",
  "bootstrap": "CSS framework created at Twitter in 2011.",
  "vuedotjs": "JS framework created by Evan You in 2014.",
  "angular": "TypeScript web framework maintained by Google.",
  "django": "Python web framework named after Django Reinhardt.",
  "laravel": "PHP web framework created by Taylor Otwell in 2011.",
  "kotlin": "JetBrains language named after an island near Russia.",
  "swift": "Apple's programming language unveiled in 2014.",
  "rust": "Memory-safe language that began at Mozilla.",
  "mysql": "Open-source database now owned by Oracle.",
  "postgresql": "Open-source database with an elephant mascot.",
  "astro": "Web framework for fast, content-focused sites; 2021.",
  "graphql": "API query language developed at Facebook, 2015.",
  "nginx": "High-performance web server and reverse proxy.",
  "linux": "Open-source kernel started by Linus Torvalds in 1991.",
  "raspberrypi": "Low-cost single-board computer from the UK.",
  "arduino": "Open-source electronics prototyping platform.",
  "androidstudio": "Google's official IDE for building Android apps.",
  "intellijidea": "JetBrains' Java IDE, first released in 2001.",
  "pycharm": "JetBrains IDE built for Python development.",
  "sublimetext": "Fast code editor known for its speed.",
  "npm": "Default package manager for Node.js.",
  // ===== IMPOSSIBLE =====
  "argo": "Open-source GitOps and workflow tools for Kubernetes.",
  "grafana": "Open-source dashboards for metrics and monitoring.",
  "terraform": "HashiCorp's infrastructure-as-code tool.",
  "ansible": "Red Hat automation tool that needs no agents.",
  "deno": "JavaScript runtime from Node.js creator Ryan Dahl.",
  "electron": "Framework for desktop apps using web tech.",
  "sqlite": "The world's most widely deployed database engine.",
  "debian": "One of the oldest Linux distributions, from 1993.",
  "fedora": "Community Linux distro sponsored by Red Hat.",
  "wireshark": "Open-source network packet analyzer.",
  "neovim": "Modern fork of the Vim text editor.",
  "vim": "Modal text editor first released in 1991.",
  "git": "Version-control system created by Linus Torvalds.",
  "notepadplusplus": "Free Windows source-code editor.",
  "obsstudio": "Free open-source streaming and recording tool.",
  "audacity": "Free open-source audio editor and recorder.",
  "jellyfin": "Free open-source media server software.",
  "substack": "Newsletter platform for paid subscriptions.",
  "gumroad": "Platform for creators to sell digital products.",
  "podman": "Daemonless container engine from Red Hat.",
  "webex": "Cisco's video-conferencing platform.",
  "mattermost": "Open-source, self-hosted team chat tool.",
  "zoho": "Indian firm offering a large suite of business apps.",
  "torproject": "Nonprofit behind the anonymity-focused Tor Browser.",
  "wetransfer": "Dutch service for sending large files free.",
};
