// E155 «Guess the Toy by Emoji» — 100 toys · 25/tier · clue = plain single-codepoint Unicode emoji (mirrors emoji-quiz rendering)
// VO: sfx/e155-<id>.wav ("It's <Toy>!"). Born fair: every emoji fairly leads to the toy; no bare color-blob-only clues.
export const TOY_EMOJI = [
  // ===== EASY (25) — universal toys everyone knows =====
  { id: "teddy-bear", title: "Teddy Bear", emojis: "🧸", level: "easy" },
  { id: "kite", title: "Kite", emojis: "🪁", level: "easy" },
  { id: "yo-yo", title: "Yo-Yo", emojis: "🪀", level: "easy" },
  { id: "jigsaw-puzzle", title: "Jigsaw Puzzle", emojis: "🧩", level: "easy" },
  { id: "rubber-duck", title: "Rubber Duck", emojis: "🦆🛁", level: "easy" },
  { id: "building-blocks", title: "Building Blocks", emojis: "🧱🧱", level: "easy" },
  { id: "toy-train", title: "Toy Train", emojis: "🚂🪵", level: "easy" },
  { id: "rocking-horse", title: "Rocking Horse", emojis: "🐴🪵", level: "easy" },
  { id: "rubiks-cube", title: "Rubik's Cube", emojis: "🧊🌈", level: "easy" },
  { id: "water-gun", title: "Water Gun", emojis: "🔫💦", level: "easy" },
  { id: "bubbles", title: "Bubble Wand", emojis: "🫧🪄", level: "easy" },
  { id: "toy-drum", title: "Toy Drum", emojis: "🥁🧸", level: "easy" },
  { id: "doll", title: "Doll", emojis: "🎎", level: "easy" },
  { id: "frisbee", title: "Frisbee", emojis: "🥏", level: "easy" },
  { id: "dice", title: "Dice", emojis: "🎲", level: "easy" },
  { id: "hula-hoop", title: "Hula Hoop", emojis: "⭕💃", level: "easy" },
  { id: "jack-in-the-box", title: "Jack-in-the-Box", emojis: "📦🤡", level: "easy" },
  { id: "toy-robot", title: "Toy Robot", emojis: "🤖🧸", level: "easy" },
  { id: "sled", title: "Sled", emojis: "🛷", level: "easy" },
  { id: "skateboard", title: "Skateboard", emojis: "🛹", level: "easy" },
  { id: "toy-car", title: "Toy Car", emojis: "🚗🧸", level: "easy" },
  { id: "balloon", title: "Balloon", emojis: "🎈", level: "easy" },
  { id: "crayons", title: "Crayons", emojis: "🖍🌈", level: "easy" },
  { id: "video-game-controller", title: "Game Controller", emojis: "🎮", level: "easy" },
  { id: "roller-skates", title: "Roller Skates", emojis: "🛼", level: "easy" },

  // ===== MEDIUM (25) — recognizable, needs a beat of thought =====
  { id: "spinning-top", title: "Spinning Top", emojis: "🌀🪵", level: "medium" },
  { id: "kaleidoscope", title: "Kaleidoscope", emojis: "🔭🌈", level: "medium" },
  { id: "pinwheel", title: "Pinwheel", emojis: "🌸💨", level: "medium" },
  { id: "bowling-set", title: "Toy Bowling Set", emojis: "🎳🧸", level: "medium" },
  { id: "darts", title: "Darts", emojis: "🎯", level: "medium" },
  { id: "boomerang", title: "Boomerang", emojis: "🪃", level: "medium" },
  { id: "nesting-doll", title: "Nesting Doll", emojis: "🪆", level: "medium" },
  { id: "pinata", title: "Piñata", emojis: "🪅", level: "medium" },
  { id: "magic-set", title: "Magic Set", emojis: "🪄🎩", level: "medium" },
  { id: "sock-puppet", title: "Sock Puppet", emojis: "🧦🎭", level: "medium" },
  { id: "toy-soldier", title: "Toy Soldier", emojis: "🪖🧸", level: "medium" },
  { id: "modeling-clay", title: "Modeling Clay", emojis: "🎨🖐", level: "medium" },
  { id: "jump-rope", title: "Jump Rope", emojis: "🪢🏃", level: "medium" },
  { id: "pogo-stick", title: "Pogo Stick", emojis: "🦘🦯", level: "medium" },
  { id: "slinky", title: "Slinky", emojis: "🌀🪜", level: "medium" },
  { id: "toy-boat", title: "Toy Boat", emojis: "⛵🛁", level: "medium" },
  { id: "toy-airplane", title: "Toy Airplane", emojis: "✈🧸", level: "medium" },
  { id: "toy-helicopter", title: "Toy Helicopter", emojis: "🚁🧸", level: "medium" },
  { id: "wind-up-toy", title: "Wind-Up Toy", emojis: "🔑🤖", level: "medium" },
  { id: "water-balloon", title: "Water Balloon", emojis: "🎈💦", level: "medium" },
  { id: "beach-ball", title: "Beach Ball", emojis: "🏖⚪", level: "medium" },
  { id: "paper-airplane", title: "Paper Airplane", emojis: "📄✈", level: "medium" },
  { id: "toy-piano", title: "Toy Piano", emojis: "🎹🧸", level: "medium" },
  { id: "playing-cards", title: "Playing Cards", emojis: "🃏", level: "medium" },
  { id: "marble-run", title: "Marble Run", emojis: "🔵🛝", level: "medium" },

  // ===== HARD (25) — specific but nameable classics =====
  { id: "etch-a-sketch", title: "Etch A Sketch", emojis: "🔴✏", level: "hard" },
  { id: "simon-game", title: "Simon", emojis: "🔴🟡🔵🟢🎵", level: "hard" },
  { id: "lite-brite", title: "Lite-Brite", emojis: "💡🌈", level: "hard" },
  { id: "view-master", title: "View-Master", emojis: "👓🎞", level: "hard" },
  { id: "kendama", title: "Kendama", emojis: "🔴🥢", level: "hard" },
  { id: "cap-gun", title: "Cap Gun", emojis: "🔫💥", level: "hard" },
  { id: "gyroscope", title: "Gyroscope", emojis: "🌀⚙", level: "hard" },
  { id: "cats-cradle", title: "Cat's Cradle", emojis: "🧶🖐", level: "hard" },
  { id: "jacks", title: "Jacks", emojis: "⭐🔴", level: "hard" },
  { id: "paddle-ball", title: "Paddle Ball", emojis: "🏓🔴", level: "hard" },
  { id: "stomp-rocket", title: "Stomp Rocket", emojis: "🚀🦶", level: "hard" },
  { id: "diabolo", title: "Diabolo", emojis: "⏳🪢", level: "hard" },
  { id: "finger-puppet", title: "Finger Puppet", emojis: "👆🎭", level: "hard" },
  { id: "hobby-horse", title: "Hobby Horse", emojis: "🐴🦯", level: "hard" },
  { id: "music-box", title: "Music Box", emojis: "🎵📦", level: "hard" },
  { id: "cup-and-ball", title: "Cup and Ball", emojis: "🥤🔴", level: "hard" },
  { id: "windup-mouse", title: "Wind-Up Mouse", emojis: "🔑🐭", level: "hard" },
  { id: "pull-along-duck", title: "Pull-Along Duck", emojis: "🦆🪢", level: "hard" },
  { id: "whistle", title: "Toy Whistle", emojis: "😗💨", level: "hard" },
  { id: "jumping-jack", title: "Jumping Jack", emojis: "🪵🤸", level: "hard" },
  { id: "toy-xylophone", title: "Toy Xylophone", emojis: "🌈🔨", level: "hard" },
  { id: "toy-telephone", title: "Toy Telephone", emojis: "📞🧸", level: "hard" },
  { id: "magnetic-tiles", title: "Magnetic Tiles", emojis: "🧲🔺", level: "hard" },
  { id: "stacking-rings", title: "Stacking Rings", emojis: "🌈⭕", level: "hard" },
  { id: "pull-back-car", title: "Pull-Back Car", emojis: "🚗💨", level: "hard" },

  // ===== IMPOSSIBLE (25) — niche brand/heritage toys, still nameable =====
  { id: "spirograph", title: "Spirograph", emojis: "🌀🖊", level: "impossible" },
  { id: "stretch-armstrong", title: "Stretch Armstrong", emojis: "💪↔", level: "impossible" },
  { id: "furby", title: "Furby", emojis: "🦉🤖", level: "impossible" },
  { id: "tamagotchi", title: "Tamagotchi", emojis: "🥚🎮", level: "impossible" },
  { id: "speak-and-spell", title: "Speak & Spell", emojis: "🔤🔊", level: "impossible" },
  { id: "magic-8-ball", title: "Magic 8-Ball", emojis: "🎱🔮", level: "impossible" },
  { id: "rock-em-sock-em", title: "Rock 'Em Sock 'Em Robots", emojis: "🤖🥊", level: "impossible" },
  { id: "lawn-darts", title: "Lawn Darts", emojis: "🎯🌱", level: "impossible" },
  { id: "cootie-catcher", title: "Cootie Catcher", emojis: "📄🔮", level: "impossible" },
  { id: "troll-doll", title: "Troll Doll", emojis: "🧌🌈", level: "impossible" },
  { id: "moon-shoes", title: "Moon Shoes", emojis: "👟🌙", level: "impossible" },
  { id: "sea-monkeys", title: "Sea-Monkeys", emojis: "🦐🔬", level: "impossible" },
  { id: "ant-farm", title: "Ant Farm", emojis: "🐜🪟", level: "impossible" },
  { id: "easy-bake-oven", title: "Easy-Bake Oven", emojis: "🧁💡", level: "impossible" },
  { id: "bop-it", title: "Bop It", emojis: "🔊🤜", level: "impossible" },
  { id: "tin-can-phone", title: "Tin Can Telephone", emojis: "🥫📞", level: "impossible" },
  { id: "mr-potato-head", title: "Mr. Potato Head", emojis: "🥔👀", level: "impossible" },
  { id: "whoopee-cushion", title: "Whoopee Cushion", emojis: "💨🪑", level: "impossible" },
  { id: "jacobs-ladder", title: "Jacob's Ladder", emojis: "🪵🪜", level: "impossible" },
  { id: "zoetrope", title: "Zoetrope", emojis: "🎞🌀", level: "impossible" },
  { id: "flip-book", title: "Flip Book", emojis: "📖🏃", level: "impossible" },
  { id: "pet-rock", title: "Pet Rock", emojis: "🪨📦", level: "impossible" },
  { id: "newtons-cradle", title: "Newton's Cradle", emojis: "⚪🔗", level: "impossible" },
  { id: "thaumatrope", title: "Thaumatrope", emojis: "🐦🌀", level: "impossible" },
  { id: "koosh-ball", title: "Koosh Ball", emojis: "🔵🧶", level: "impossible" },
];
