// E155 emoji-toy facts — one verified <=70-char fact per toy, shown on reveal.
export const TOY_EMOJI_FACTS = {
  // EASY
  "teddy-bear": "Named for Teddy Roosevelt, who spared a bear's life in 1902.",
  "kite": "Kites were invented in China over 2,000 years ago.",
  "yo-yo": "One of the oldest toys, used in ancient Greece around 500 BC.",
  "jigsaw-puzzle": "Invented in the 1760s as a map-cutting teaching tool.",
  "rubber-duck": "The classic rubber duck shape was sculpted by Peter Ganine, 1949.",
  "building-blocks": "The modern interlocking brick was patented in 1958.",
  "toy-train": "Early toy trains were pulled along the floor by a string.",
  "rocking-horse": "Rocking horses date back to 17th century England.",
  "rubiks-cube": "Invented in 1974 by Hungarian professor Erno Rubik.",
  "water-gun": "Early squirt guns date back to the late 1800s.",
  "bubbles": "Bubble wands turn a simple soap film into floating spheres.",
  "toy-drum": "Toy drums mimic drums used in ceremonies for millennia.",
  "doll": "Dolls are among the oldest toys, found in Egyptian tombs.",
  "frisbee": "Named after the Frisbie Pie Company, whose tins got tossed.",
  "dice": "Dice have been used in games for over 5,000 years.",
  "hula-hoop": "Wham-O sold over 100 million Hula-Hoops in two years.",
  "jack-in-the-box": "Jack-in-the-box toys date back to 16th century Europe.",
  "toy-robot": "Tin toy robots became hugely popular in 1950s Japan.",
  "sled": "Sleds have carried people over snow for thousands of years.",
  "skateboard": "Skateboards began as roller-skate wheels bolted to boards.",
  "toy-car": "Early toy cars were made of tin before plastic took over.",
  "balloon": "The first rubber balloons were made in London in 1824.",
  "crayons": "Crayola crayons first sold in 1903 for just a nickel.",
  "video-game-controller": "Early game controllers were simple joysticks in the 1970s.",
  "roller-skates": "Roller skates were invented in the 1760s by a Belgian.",

  // MEDIUM
  "spinning-top": "Spinning tops are among humanity's oldest known toys.",
  "kaleidoscope": "Invented in 1816 by Scottish scientist David Brewster.",
  "pinwheel": "Pinwheels spin using nothing but a breath of wind.",
  "bowling-set": "Toy bowling echoes a sport dating back 5,000 years.",
  "darts": "Darts likely evolved from soldiers throwing broken arrows.",
  "boomerang": "Boomerangs were used by Aboriginal Australians for hunting.",
  "nesting-doll": "Russian nesting dolls, matryoshka, first appeared in 1890.",
  "pinata": "Pinatas may trace back to 14th century China and Italy.",
  "magic-set": "Beginner magic sets popularized simple tricks at home.",
  "sock-puppet": "Sock puppets need nothing but a sock and two hands.",
  "toy-soldier": "Tin toy soldiers became popular in 18th century Germany.",
  "modeling-clay": "Play-Doh started in the 1930s as a wallpaper cleaner.",
  "jump-rope": "Jump rope games date back to ancient Egypt and China.",
  "pogo-stick": "The pogo stick was patented in the United States in 1919.",
  "slinky": "Invented by accident in 1943 by engineer Richard James.",
  "toy-boat": "Toy boats have floated in bathtubs since the 1800s.",
  "toy-airplane": "Toy airplanes surged in popularity after the 1920s.",
  "toy-helicopter": "Toy helicopters took off after real ones flew in the 1940s.",
  "wind-up-toy": "Wind-up clockwork toys date back to the 18th century.",
  "water-balloon": "Water balloons took off once rubber grew stretchy enough.",
  "beach-ball": "Beach balls were first mass-produced in the early 1900s.",
  "paper-airplane": "Paper folding for flight dates back centuries in China.",
  "toy-piano": "Toy pianos were first made in Germany in the 1800s.",
  "playing-cards": "Playing cards are believed to have originated in China.",
  "marble-run": "Marble runs use gravity to race marbles down a track.",

  // HARD
  "etch-a-sketch": "Invented by Andre Cassagnes of France, launched in 1960.",
  "simon-game": "Simon, the memory game, launched by Milton Bradley in 1978.",
  "lite-brite": "Lite-Brite let kids peg glowing pictures, launched in 1967.",
  "view-master": "The View-Master stereoscope debuted at the 1939 World's Fair.",
  "kendama": "Kendama, a ball-and-cup toy, has roots in old Japan.",
  "cap-gun": "Cap guns use tiny paper caps to make a bang, no bullets.",
  "gyroscope": "Toy gyroscopes show off the physics of spinning motion.",
  "cats-cradle": "Cat's cradle string games are found in cultures worldwide.",
  "jacks": "Jacks evolved from an ancient game played with knucklebones.",
  "paddle-ball": "Paddle ball toys bounce a ball on an elastic string.",
  "stomp-rocket": "Stomp rockets launch using air pressure, no batteries needed.",
  "diabolo": "Diabolo spinning-top juggling began in ancient China.",
  "finger-puppet": "Finger puppets are among the smallest puppets ever made.",
  "hobby-horse": "Hobby horses were popular children's toys by the 1600s.",
  "music-box": "Music boxes use a pinned cylinder to pluck tuned teeth.",
  "cup-and-ball": "The cup-and-ball toy is a classic skill game centuries old.",
  "windup-mouse": "Wind-up mice were a popular clockwork novelty toy.",
  "pull-along-duck": "Pull-along toys have delighted toddlers for generations.",
  "whistle": "Toy whistles have been carved from clay and wood for ages.",
  "jumping-jack": "Jumping jack toys dance when you pull a single string.",
  "toy-xylophone": "Xylophone toys teach rhythm with colorful metal bars.",
  "toy-telephone": "Toy telephones let kids imitate grown-up phone calls.",
  "magnetic-tiles": "Magnetic building tiles snap together into 3D shapes.",
  "stacking-rings": "Stacking ring toys teach toddlers size and color order.",
  "pull-back-car": "Pull-back cars store energy in a wound-up gear motor.",

  // IMPOSSIBLE
  "spirograph": "Spirograph, launched in 1965, draws geometric spiral art.",
  "stretch-armstrong": "Stretch Armstrong, released in 1976, stretches but won't tear.",
  "furby": "Furby launched in 1998 and learned English words over time.",
  "tamagotchi": "Tamagotchi virtual pets debuted in Japan in 1996.",
  "speak-and-spell": "Speak & Spell, from 1978, used early speech-synthesis chips.",
  "magic-8-ball": "The Magic 8-Ball was invented in the 1950s by Albert Carter.",
  "rock-em-sock-em": "Rock 'Em Sock 'Em Robots was launched by Marx Toys in 1964.",
  "lawn-darts": "Lawn darts, called Jarts, were banned in the US in 1988.",
  "cootie-catcher": "Cootie catchers are paper fortune-tellers folded by hand.",
  "troll-doll": "Troll dolls were created by Thomas Dam in Denmark in 1959.",
  "moon-shoes": "Moon Shoes strap mini trampolines onto your feet.",
  "sea-monkeys": "Sea-Monkeys are brine shrimp sold since 1957 as a novelty.",
  "ant-farm": "Ant farms let kids watch ants dig tunnels through sand.",
  "easy-bake-oven": "The Easy-Bake Oven, launched in 1963, bakes with a light bulb.",
  "bop-it": "Bop It, launched in 1996, tests reflexes with quick commands.",
  "tin-can-phone": "Tin can telephones carry sound through a taut string.",
  "mr-potato-head": "Mr. Potato Head was the first toy ever advertised on TV, 1952.",
  "whoopee-cushion": "Whoopee cushions were mass-produced by JEM Rubber Co.",
  "jacobs-ladder": "Jacob's Ladder toys create a falling-block optical illusion.",
  "zoetrope": "The zoetrope spins images to create the illusion of motion.",
  "flip-book": "Flip books animate drawings through fast page flipping.",
  "pet-rock": "The Pet Rock fad made creator Gary Dahl a millionaire in 1975.",
  "newtons-cradle": "Newton's Cradle demonstrates the conservation of momentum.",
  "thaumatrope": "A thaumatrope blends two images into one when spun fast.",
  "koosh-ball": "The Koosh Ball, invented in 1987, is made of stretchy filaments.",
};
