// E225 «Guess the TV Show by Emoji 5» — one true fact per id, <=70 chars
export const TV_EMOJI5_FACTS = {
  "lupin": "Netflix hit inspired by Maurice Leblanc's 1905 gentleman-thief novels.",
  "sex-education": "Netflix British comedy set at fictional Moordale Secondary School.",
  "elite": "Spanish Netflix teen thriller Elite premiered in 2018.",
  "13-reasons-why": "Netflix drama based on Jay Asher's 2007 novel, ran 4 seasons.",
  "crash-landing-on-you": "2019 K-drama about a paraglider crashing into North Korea.",
  "doraemon": "Robotic cat manga began in Japan in 1969 by Fujiko Fujio.",
  "detective-conan": "Also known as Case Closed, running in Japan since 1996.",
  "inuyasha": "Rumiko Takahashi's half-demon anime aired 2000 to 2004.",
  "jojos-bizarre-adventure": "Famous for its ORA ORA punching battle cry.",
  "phineas-and-ferb": "Disney show about two step-brothers' summer inventions.",
  "my-little-pony": "Hasbro's 2010 reboot gained a huge adult Brony fandom.",
  "kim-possible": "Disney teen spy show ran from 2002 to 2007.",
  "total-drama-island": "Canadian animated reality-show parody premiered in 2007.",
  "legend-of-korra": "Direct sequel to Avatar: The Last Airbender, aired 2012.",
  "boy-meets-world": "ABC coming-of-age sitcom ran from 1993 to 2000.",
  "thats-so-raven": "Disney sitcom about a girl with psychic visions.",
  "drake-and-josh": "Nickelodeon sitcom about mismatched stepbrothers, 2004.",
  "victorious": "Nickelodeon show launched Ariana Grande's TV career.",
  "one-tree-hill": "The WB/CW drama set in fictional Tree Hill, North Carolina.",
  "beverly-hills-90210": "Fox teen drama that ran an original 10 seasons from 1990.",
  "keeping-up-with-the-kardashians": "E! reality series ran for 20 seasons from 2007 to 2021.",
  "rupauls-drag-race": "Reality competition that has won over 30 Emmy Awards.",
  "the-bachelor": "ABC dating show has aired since 2002 across 28+ seasons.",
  "ertugrul": "Turkish historical drama Dirilis: Ertugrul aired 2014-2019.",
  "big-brother": "Reality format created in the Netherlands in 1999.",
  "goblin-2016": "2016 K-drama also known as Guardian: The Lonely and Great God.",
  "descendants-of-the-sun": "2016 K-drama about a soldier and a surgeon in love.",
  "itaewon-class": "2020 K-drama about rebuilding a bar after prison.",
  "vincenzo": "2021 K-drama about a Korean-Italian mafia consigliere.",
  "business-proposal": "2022 K-drama based on a hit webtoon romance.",
  "my-love-from-the-star": "2013 K-drama about an alien stranded on Earth for 400 years.",
  "la-reina-del-sur": "Telemundo drama based on Arturo Perez-Reverte's novel.",
  "narcos-mexico": "Netflix spinoff following the rise of the Guadalajara Cartel.",
  "call-my-agent": "French comedy-drama Dix pour Cent about talent agents.",
  "sacred-games": "Netflix's first original Indian series, released in 2018.",
  "mirzapur": "Amazon Prime India crime drama set in Uttar Pradesh.",
  "kara-sevda": "Turkish drama title literally translates to Black Love.",
  "fatmagul": "Turkish drama Fatmagul'un Sucu Ne aired 2010 to 2012.",
  "are-you-being-served": "BBC sitcom set in a London department store, from 1972.",
  "only-fools-and-horses": "BBC sitcom about market traders, voted UK's best sitcom.",
  "keeping-up-appearances": "BBC sitcom starred Patricia Routledge as snobbish Hyacinth.",
  "yes-minister": "BBC political satire ran from 1980 to 1984.",
  "the-inbetweeners": "E4 British sitcom followed four socially awkward sixth-formers.",
  "misfits": "E4 show about young offenders who gain superpowers, 2009.",
  "top-boy": "Channel 4 drama revived by Netflix, executive produced by Drake.",
  "daredevil": "Marvel Netflix series about a blind lawyer-vigilante, 2015.",
  "jessica-jones": "Marvel Netflix series starred Krysten Ritter as a hard-drinking PI.",
  "luke-cage": "Marvel Netflix series set in Harlem, premiered 2016.",
  "ms-marvel": "Disney+ series introduced Kamala Khan, Marvel's first Muslim lead.",
  "moon-knight": "Disney+ series starred Oscar Isaac with dissociative identity.",
  "she-hulk-attorney-at-law": "Disney+ series starred Tatiana Maslany as Jennifer Walters.",
  "hawkeye": "Disney+ series introduced Kate Bishop alongside Clint Barton.",
  "the-punisher": "Marvel Netflix series starred Jon Bernthal as Frank Castle.",
  "agents-of-shield": "ABC series ran seven seasons from 2013 to 2020.",
  "doom-patrol": "DC series about a dysfunctional team of accident-born heroes.",
  "titans": "Live-action DC series launched HBO Max in 2018.",
  "peacemaker": "HBO Max spinoff of The Suicide Squad, starred John Cena.",
  "watchmen": "HBO 2019 sequel series won 11 Emmy Awards.",
  "izombie": "The CW series about a zombie medical examiner, ran 2015-2019.",
  "angel": "Buffy the Vampire Slayer spinoff set in Los Angeles, from 1999.",
  "smallville": "The WB/CW series followed young Clark Kent for ten seasons.",
  "fuller-house": "Netflix sequel to Full House premiered in 2016.",
  "friday-night-lights": "NBC drama followed Texas high school football, from 2006.",
  "the-oc": "Fox teen drama set in wealthy Orange County, 2003-2007.",
  "dawsons-creek": "WB drama launched Katie Holmes and Michelle Williams.",
  "melrose-place": "Fox primetime soap spun off from Beverly Hills, 90210.",
  "zoey-101": "Nickelodeon show starred a young Jamie Lynn Spears.",
  "girl-meets-world": "Disney Channel sequel followed Boy Meets World's Cory and Topanga.",
  "never-have-i-ever": "Netflix comedy created by Mindy Kaling, premiered 2020.",
  "the-originals": "The Vampire Diaries spinoff followed the Mikaelson family.",
  "regular-show": "Cartoon Network series about a groundskeeper duo, ran 2010-2017.",
  "danny-phantom": "Nickelodeon show about a half-ghost teen superhero, 2004.",
  "recess": "Disney Channel show following a playground gang, from 1997.",
  "crayon-shinchan": "Japanese manga about a mischievous five-year-old, since 1990.",
  "black-clover": "Shonen anime about a boy without magic seeking to be Wizard King.",
  "trigun": "1998 anime about gunslinger Vash the Stampede in a desert world.",
  "hellsing": "Manga about a vampire hunting organization, began in 1997.",
  "black-lagoon": "Anime about mercenary pirates set in Southeast Asia.",
  "baccano": "2007 anime set aboard a 1930s train, told out of order.",
  "parasyte": "Manga about alien parasites that take over human hosts.",
  "steins-gate": "Acclaimed anime about a microwave that sends texts to the past.",
  "death-parade": "Anime where the dead play games to decide their fate.",
  "monster-anime": "Naoki Urasawa's thriller about a doctor who saved a killer.",
  "serial-experiments-lain": "1998 cult anime exploring identity inside the internet.",
  "erased": "Anime where a man travels back to prevent a childhood murder.",
  "akame-ga-kill": "Dark fantasy anime about assassins fighting a corrupt empire.",
  "claymore": "Manga about half-human female warriors who slay demons.",
  "mushishi": "Anime following a wanderer who studies supernatural life-forms.",
  "1899": "Netflix mystery from the creators of Dark, cancelled after one season.",
  "who-killed-sara": "Mexican Netflix thriller about a man seeking his sister's killer.",
  "gomorrah": "Italian crime series based on Roberto Saviano's Naples mafia book.",
  "the-young-pope": "HBO series starred Jude Law as a rebellious young pontiff.",
  "my-brilliant-friend": "HBO adaptation of Elena Ferrante's Neapolitan novels.",
  "deutschland-83": "German series about an East German spy in the Cold War West.",
  "the-bureau": "French spy series Le Bureau des Legendes praised for realism.",
  "marcella": "ITV crime drama starred Anna Friel as a detective with blackouts.",
  "bloodlands": "BBC crime drama set on the Northern Ireland coast, from 2021.",
  "fortitude": "Sky Atlantic mystery set in a remote Arctic town.",
  "humans-uk": "Channel 4/AMC series imagined homes with lifelike android servants.",
  "z-nation": "Syfy zombie series ran five seasons from 2014 to 2018.",
};
