// E235 «Guess the TV Show by Emoji» (6th TV episode) — 100 shows · 25/tier · clue via OpenMoji · VO: sfx/em-<id>.wav
export const TV_EMOJI6 = [
  // ===== EASY (25) =====
  { id: "american-idol", title: "American Idol", emojis: "🎤🏆", level: "easy" },
  { id: "the-voice", title: "The Voice", emojis: "🎤🔄", level: "easy" },
  { id: "americas-got-talent", title: "America's Got Talent", emojis: "🎤✨", level: "easy" },
  { id: "shark-tank", title: "Shark Tank", emojis: "🦈💰", level: "easy" },
  { id: "dancing-with-the-stars", title: "Dancing with the Stars", emojis: "💃⭐", level: "easy" },
  { id: "wheel-of-fortune", title: "Wheel of Fortune", emojis: "🎡💰", level: "easy" },
  { id: "jeopardy", title: "Jeopardy!", emojis: "❓💰", level: "easy" },
  { id: "queer-eye", title: "Queer Eye", emojis: "🌈✂", level: "easy" },
  { id: "parks-and-recreation", title: "Parks and Recreation", emojis: "🌳🏛", level: "easy" },
  { id: "home-improvement", title: "Home Improvement", emojis: "🔨🏠", level: "easy" },
  { id: "married-with-children", title: "Married... with Children", emojis: "💍👶", level: "easy" },
  { id: "saved-by-the-bell", title: "Saved by the Bell", emojis: "🔔🏫", level: "easy" },
  { id: "the-golden-girls", title: "The Golden Girls", emojis: "👵🌴", level: "easy" },
  { id: "impractical-jokers", title: "Impractical Jokers", emojis: "🎭😂", level: "easy" },
  { id: "property-brothers", title: "Property Brothers", emojis: "🏠👬", level: "easy" },
  { id: "mythbusters", title: "MythBusters", emojis: "💥🔬", level: "easy" },
  { id: "deadliest-catch", title: "Deadliest Catch", emojis: "🦀⚓", level: "easy" },
  { id: "gold-rush", title: "Gold Rush", emojis: "⛏🥇", level: "easy" },
  { id: "pawn-stars", title: "Pawn Stars", emojis: "💰🏺", level: "easy" },
  { id: "american-pickers", title: "American Pickers", emojis: "🚚🔍", level: "easy" },
  { id: "duck-dynasty", title: "Duck Dynasty", emojis: "🦆👑", level: "easy" },
  { id: "90-day-fiance", title: "90 Day Fiancé", emojis: "💍✈", level: "easy" },
  { id: "love-island", title: "Love Island", emojis: "❤🏝", level: "easy" },
  { id: "the-masked-singer", title: "The Masked Singer", emojis: "🎭🎤", level: "easy" },
  { id: "fixer-upper", title: "Fixer Upper", emojis: "🔨🏡", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "everybody-loves-raymond", title: "Everybody Loves Raymond", emojis: "❤🍝", level: "medium" },
  { id: "that-70s-show", title: "That '70s Show", emojis: "🛋🎸", level: "medium" },
  { id: "malcolm-in-the-middle", title: "Malcolm in the Middle", emojis: "👦🌪", level: "medium" },
  { id: "king-of-the-hill", title: "King of the Hill", emojis: "⛽🤠", level: "medium" },
  { id: "american-dad", title: "American Dad!", emojis: "🦅🕵", level: "medium" },
  { id: "archer", title: "Archer", emojis: "🍸🕵", level: "medium" },
  { id: "growing-pains", title: "Growing Pains", emojis: "🏡👦", level: "medium" },
  { id: "family-matters", title: "Family Matters", emojis: "🤓🏠", level: "medium" },
  { id: "step-by-step", title: "Step by Step", emojis: "👣💑", level: "medium" },
  { id: "lizzie-mcguire", title: "Lizzie McGuire", emojis: "📓🎀", level: "medium" },
  { id: "good-luck-charlie", title: "Good Luck Charlie", emojis: "🍀👶", level: "medium" },
  { id: "jessie", title: "Jessie", emojis: "🏙👧", level: "medium" },
  { id: "shake-it-up", title: "Shake It Up", emojis: "💃🎶", level: "medium" },
  { id: "austin-and-ally", title: "Austin & Ally", emojis: "🎸🎹", level: "medium" },
  { id: "wizards-of-waverly-place", title: "Wizards of Waverly Place", emojis: "🪄🏙", level: "medium" },
  { id: "ravens-home", title: "Raven's Home", emojis: "🔮🏠", level: "medium" },
  { id: "liv-and-maddie", title: "Liv and Maddie", emojis: "👯🏀", level: "medium" },
  { id: "kc-undercover", title: "K.C. Undercover", emojis: "🕶🥋", level: "medium" },
  { id: "andi-mack", title: "Andi Mack", emojis: "🎨👧", level: "medium" },
  { id: "california-dreams", title: "California Dreams", emojis: "🏄🎸", level: "medium" },
  { id: "the-amazing-race", title: "The Amazing Race", emojis: "🌍🏁", level: "medium" },
  { id: "britains-got-talent", title: "Britain's Got Talent", emojis: "🎤🔔", level: "medium" },
  { id: "the-x-factor", title: "The X Factor", emojis: "❌🎤", level: "medium" },
  { id: "naked-and-afraid", title: "Naked and Afraid", emojis: "🌴😱", level: "medium" },
  { id: "american-ninja-warrior", title: "American Ninja Warrior", emojis: "🥷🏋", level: "medium" },

  // ===== HARD (25) =====
  { id: "chuck", title: "Chuck", emojis: "💻🕵", level: "hard" },
  { id: "leverage", title: "Leverage", emojis: "🎭💼", level: "hard" },
  { id: "numb3rs", title: "Numb3rs", emojis: "🔢🚔", level: "hard" },
  { id: "nip-tuck", title: "Nip/Tuck", emojis: "💉👃", level: "hard" },
  { id: "private-practice", title: "Private Practice", emojis: "🏥💔", level: "hard" },
  { id: "new-amsterdam", title: "New Amsterdam", emojis: "🏥🗽", level: "hard" },
  { id: "chicago-med", title: "Chicago Med", emojis: "🏥🚑", level: "hard" },
  { id: "law-and-order-svu", title: "Law & Order: SVU", emojis: "⚖🚔", level: "hard" },
  { id: "csi-miami", title: "CSI: Miami", emojis: "🔬🌴", level: "hard" },
  { id: "entourage", title: "Entourage", emojis: "🎬🚙", level: "hard" },
  { id: "master-of-none", title: "Master of None", emojis: "🍜🎬", level: "hard" },
  { id: "my-name-is-earl", title: "My Name Is Earl", emojis: "📝🍀", level: "hard" },
  { id: "raising-hope", title: "Raising Hope", emojis: "👶🏡", level: "hard" },
  { id: "superstore", title: "Superstore", emojis: "🛒📋", level: "hard" },
  { id: "sex-and-the-city", title: "Sex and the City", emojis: "👠🗽", level: "hard" },
  { id: "grace-and-frankie", title: "Grace and Frankie", emojis: "👵🍷", level: "hard" },
  { id: "dead-to-me", title: "Dead to Me", emojis: "⚰😢", level: "hard" },
  { id: "ghosts", title: "Ghosts", emojis: "👻🏚", level: "hard" },
  { id: "derry-girls", title: "Derry Girls", emojis: "🎒☘", level: "hard" },
  { id: "peep-show", title: "Peep Show", emojis: "👀🛋", level: "hard" },
  { id: "black-books", title: "Black Books", emojis: "📚🍷", level: "hard" },
  { id: "miranda", title: "Miranda", emojis: "🛍😂", level: "hard" },
  { id: "the-it-crowd", title: "The IT Crowd", emojis: "💻🤓", level: "hard" },
  { id: "tuca-and-bertie", title: "Tuca and Bertie", emojis: "🦜🐦", level: "hard" },
  { id: "solar-opposites", title: "Solar Opposites", emojis: "👽🛸", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "we-bare-bears", title: "We Bare Bears", emojis: "🐻🐼", level: "impossible" },
  { id: "samurai-jack", title: "Samurai Jack", emojis: "⚔🥷", level: "impossible" },
  { id: "teen-titans", title: "Teen Titans", emojis: "🦸🏙", level: "impossible" },
  { id: "static-shock", title: "Static Shock", emojis: "⚡🛹", level: "impossible" },
  { id: "the-fairly-oddparents", title: "The Fairly OddParents", emojis: "🧚🍽", level: "impossible" },
  { id: "rugrats", title: "Rugrats", emojis: "👶🛼", level: "impossible" },
  { id: "hey-arnold", title: "Hey Arnold!", emojis: "🏈👦", level: "impossible" },
  { id: "catdog", title: "CatDog", emojis: "🐱🐶", level: "impossible" },
  { id: "ren-and-stimpy", title: "Ren & Stimpy", emojis: "🐕🐈", level: "impossible" },
  { id: "rockos-modern-life", title: "Rocko's Modern Life", emojis: "🦘📺", level: "impossible" },
  { id: "doug", title: "Doug", emojis: "📓👦", level: "impossible" },
  { id: "the-wild-thornberrys", title: "The Wild Thornberrys", emojis: "🦁📹", level: "impossible" },
  { id: "angry-beavers", title: "Angry Beavers", emojis: "🦫😠", level: "impossible" },
  { id: "alice-in-borderland", title: "Alice in Borderland", emojis: "🃏🏙", level: "impossible" },
  { id: "the-glory", title: "The Glory", emojis: "🔥🏫", level: "impossible" },
  { id: "hellbound", title: "Hellbound", emojis: "👹🔥", level: "impossible" },
  { id: "sweet-home", title: "Sweet Home", emojis: "🏢👹", level: "impossible" },
  { id: "kingdom", title: "Kingdom", emojis: "👑🧟", level: "impossible" },
  { id: "all-of-us-are-dead", title: "All of Us Are Dead", emojis: "🏫🧟", level: "impossible" },
  { id: "reply-1988", title: "Reply 1988", emojis: "📻🏘", level: "impossible" },
  { id: "skam", title: "Skam", emojis: "📱🎒", level: "impossible" },
  { id: "borgen", title: "Borgen", emojis: "🏛👩", level: "impossible" },
  { id: "trapped", title: "Trapped", emojis: "🧊🚔", level: "impossible" },
  { id: "kleo", title: "Kleo", emojis: "🎯🕶", level: "impossible" },
  { id: "barbarians", title: "Barbarians", emojis: "🛡🌲", level: "impossible" },
];
