// E127 «Guess the TV Show by Emoji 2» — 100 shows · 25/tier · clue via OpenMoji · VO: sfx/et2-<id>.wav
export const TV_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "sesame-street", title: "Sesame Street", emojis: "🔢🐦", level: "easy" },
  { id: "power-rangers", title: "Power Rangers", emojis: "🦸🌈", level: "easy" },
  { id: "greys-anatomy", title: "Grey's Anatomy", emojis: "🏥❤", level: "easy" },
  { id: "csi", title: "CSI: Crime Scene Investigation", emojis: "🔍🩸", level: "easy" },
  { id: "ben-10", title: "Ben 10", emojis: "👽⌚", level: "easy" },
  { id: "pretty-little-liars", title: "Pretty Little Liars", emojis: "💌🤫", level: "easy" },
  { id: "ted-lasso", title: "Ted Lasso", emojis: "⚽😊", level: "easy" },
  { id: "full-house", title: "Full House", emojis: "🏠👨", level: "easy" },
  { id: "fresh-prince-bel-air", title: "The Fresh Prince of Bel-Air", emojis: "🤴🏠", level: "easy" },
  { id: "icarly", title: "iCarly", emojis: "📷😊", level: "easy" },
  { id: "hannah-montana", title: "Hannah Montana", emojis: "🎤🎭", level: "easy" },
  { id: "death-note", title: "Death Note", emojis: "📓💀", level: "easy" },
  { id: "attack-on-titan", title: "Attack on Titan", emojis: "🦖🧱", level: "easy" },
  { id: "my-hero-academia", title: "My Hero Academia", emojis: "🦸🎓", level: "easy" },
  { id: "demon-slayer", title: "Demon Slayer", emojis: "👹🔥", level: "easy" },
  { id: "cocomelon", title: "Cocomelon", emojis: "🍉👶", level: "easy" },
  { id: "paw-patrol", title: "PAW Patrol", emojis: "🐶🚔", level: "easy" },
  { id: "blues-clues", title: "Blue's Clues", emojis: "🐶🔍", level: "easy" },
  { id: "barney-friends", title: "Barney & Friends", emojis: "🦕💜", level: "easy" },
  { id: "masha-and-the-bear", title: "Masha and the Bear", emojis: "👧🐻", level: "easy" },
  { id: "powerpuff-girls", title: "The Powerpuff Girls", emojis: "👧💥", level: "easy" },
  { id: "big-bang-theory", title: "The Big Bang Theory", emojis: "🧪💡", level: "easy" },
  { id: "mickey-mouse-clubhouse", title: "Mickey Mouse Clubhouse", emojis: "🐭🏠", level: "easy" },
  { id: "winnie-the-pooh", title: "Winnie the Pooh", emojis: "🍯🐻", level: "easy" },
  { id: "amazing-world-of-gumball", title: "The Amazing World of Gumball", emojis: "🐱🌈", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "shameless", title: "Shameless", emojis: "🍺🏠", level: "medium" },
  { id: "suits", title: "Suits", emojis: "👔⚖", level: "medium" },
  { id: "how-to-get-away-with-murder", title: "How to Get Away with Murder", emojis: "⚖🔪", level: "medium" },
  { id: "modern-family", title: "Modern Family", emojis: "📷🏠", level: "medium" },
  { id: "its-always-sunny-in-philadelphia", title: "It's Always Sunny in Philadelphia", emojis: "🍻☀", level: "medium" },
  { id: "brooklyn-nine-nine", title: "Brooklyn Nine-Nine", emojis: "👮📋", level: "medium" },
  { id: "the-good-place", title: "The Good Place", emojis: "😇🌈", level: "medium" },
  { id: "the-blacklist", title: "The Blacklist", emojis: "🕴🔫", level: "medium" },
  { id: "how-i-met-your-mother", title: "How I Met Your Mother", emojis: "💍🍻", level: "medium" },
  { id: "two-and-a-half-men", title: "Two and a Half Men", emojis: "🍺🏖", level: "medium" },
  { id: "the-good-doctor", title: "The Good Doctor", emojis: "🏥🧩", level: "medium" },
  { id: "supernatural", title: "Supernatural", emojis: "🚗👻", level: "medium" },
  { id: "teen-wolf", title: "Teen Wolf", emojis: "🐺🏫", level: "medium" },
  { id: "gilmore-girls", title: "Gilmore Girls", emojis: "☕📚", level: "medium" },
  { id: "shadowhunters", title: "Shadowhunters", emojis: "⚔👁", level: "medium" },
  { id: "glee", title: "Glee", emojis: "🎤🎓", level: "medium" },
  { id: "arrow", title: "Arrow", emojis: "🏹🎭", level: "medium" },
  { id: "the-100", title: "The 100", emojis: "🚀🌍", level: "medium" },
  { id: "jane-the-virgin", title: "Jane the Virgin", emojis: "📚💗", level: "medium" },
  { id: "skins", title: "Skins", emojis: "🎉🚬", level: "medium" },
  { id: "euphoria", title: "Euphoria", emojis: "💊✨", level: "medium" },
  { id: "outer-banks", title: "Outer Banks", emojis: "⚓💰", level: "medium" },
  { id: "yellowstone", title: "Yellowstone", emojis: "🤠🐴", level: "medium" },
  { id: "cobra-kai", title: "Cobra Kai", emojis: "🥋🐍", level: "medium" },
  { id: "locke-and-key", title: "Locke & Key", emojis: "🔑🚪", level: "medium" },

  // ===== HARD (25) =====
  { id: "the-good-fight", title: "The Good Fight", emojis: "⚖🗽", level: "hard" },
  { id: "babylon-berlin", title: "Babylon Berlin", emojis: "🚂🕵", level: "hard" },
  { id: "this-is-us", title: "This Is Us", emojis: "🎂👨", level: "hard" },
  { id: "six-feet-under", title: "Six Feet Under", emojis: "⚰🌹", level: "hard" },
  { id: "deadwood", title: "Deadwood", emojis: "🤠🪓", level: "hard" },
  { id: "the-shield", title: "The Shield", emojis: "👮🔥", level: "hard" },
  { id: "justified", title: "Justified", emojis: "🤠🔫", level: "hard" },
  { id: "banshee", title: "Banshee", emojis: "🎭🔫", level: "hard" },
  { id: "luther", title: "Luther", emojis: "🕵🖤", level: "hard" },
  { id: "the-night-of", title: "The Night Of", emojis: "🔪🌃", level: "hard" },
  { id: "the-affair", title: "The Affair", emojis: "💔🌊", level: "hard" },
  { id: "big-little-lies", title: "Big Little Lies", emojis: "🌊🤫", level: "hard" },
  { id: "sharp-objects", title: "Sharp Objects", emojis: "🔪🩸", level: "hard" },
  { id: "mare-of-easttown", title: "Mare of Easttown", emojis: "🔍🏘", level: "hard" },
  { id: "yellowjackets", title: "Yellowjackets", emojis: "✈🌲", level: "hard" },
  { id: "severance", title: "Severance", emojis: "🧠🏢", level: "hard" },
  { id: "barry", title: "Barry", emojis: "🎭💥", level: "hard" },
  { id: "atlanta", title: "Atlanta", emojis: "🎤🌆", level: "hard" },
  { id: "the-bear", title: "The Bear", emojis: "🍴🔥", level: "hard" },
  { id: "veep", title: "Veep", emojis: "🏛😡", level: "hard" },
  { id: "transparent", title: "Transparent", emojis: "🏠🌈", level: "hard" },
  { id: "orange-is-the-new-black", title: "Orange Is the New Black", emojis: "🟠🔒", level: "hard" },
  { id: "unbelievable", title: "Unbelievable", emojis: "🔍💔", level: "hard" },
  { id: "maniac", title: "Maniac", emojis: "🧠💊", level: "hard" },
  { id: "legion", title: "Legion", emojis: "🧠✨", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "the-avengers-1961", title: "The Avengers (1961)", emojis: "🎩☂", level: "impossible" },
  { id: "the-saint", title: "The Saint", emojis: "😇🚗", level: "impossible" },
  { id: "randall-and-hopkirk-deceased", title: "Randall and Hopkirk (Deceased)", emojis: "👻🕴", level: "impossible" },
  { id: "the-forsyte-saga", title: "The Forsyte Saga", emojis: "🏛📜", level: "impossible" },
  { id: "upstairs-downstairs", title: "Upstairs, Downstairs", emojis: "🏠🔑", level: "impossible" },
  { id: "steptoe-and-son", title: "Steptoe and Son", emojis: "🐴🛒", level: "impossible" },
  { id: "porridge", title: "Porridge", emojis: "🔒🥣", level: "impossible" },
  { id: "rising-damp", title: "Rising Damp", emojis: "🏚💧", level: "impossible" },
  { id: "till-death-us-do-part", title: "Till Death Us Do Part", emojis: "💍😡", level: "impossible" },
  { id: "the-sweeney", title: "The Sweeney", emojis: "🚗👮", level: "impossible" },
  { id: "tinker-tailor-soldier-spy", title: "Tinker Tailor Soldier Spy", emojis: "🕴🔍", level: "impossible" },
  { id: "callan", title: "Callan", emojis: "🔫🎩", level: "impossible" },
  { id: "z-cars", title: "Z Cars", emojis: "🚔👮", level: "impossible" },
  { id: "dixon-of-dock-green", title: "Dixon of Dock Green", emojis: "👮🔔", level: "impossible" },
  { id: "bonanza", title: "Bonanza", emojis: "🗺🔥", level: "impossible" },
  { id: "gunsmoke", title: "Gunsmoke", emojis: "🔫💨", level: "impossible" },
  { id: "the-rifleman", title: "The Rifleman", emojis: "🔫👦", level: "impossible" },
  { id: "have-gun-will-travel", title: "Have Gun – Will Travel", emojis: "🔫🃏", level: "impossible" },
  { id: "wagon-train", title: "Wagon Train", emojis: "🐴🌵", level: "impossible" },
  { id: "rawhide", title: "Rawhide", emojis: "🐴🔥", level: "impossible" },
  { id: "combat", title: "Combat!", emojis: "🪖💥", level: "impossible" },
  { id: "the-fugitive", title: "The Fugitive", emojis: "🏃🚔", level: "impossible" },
  { id: "route-66", title: "Route 66", emojis: "🚗🛣", level: "impossible" },
  { id: "the-outer-limits", title: "The Outer Limits", emojis: "📺🛸", level: "impossible" },
  { id: "sea-hunt", title: "Sea Hunt", emojis: "🤿🌊", level: "impossible" },
];
