// E193 «Guess the TV Show by Emoji 4» — 100 shows · 25/tier
// VO: sfx/e193-<id>.wav
export const TV_EMOJI_4 = [
  // ===== EASY (25) =====
  { id: "buffy-the-vampire-slayer", title: "Buffy the Vampire Slayer", emojis: "🧛🗡", level: "easy" },
  { id: "house-of-the-dragon", title: "House of the Dragon", emojis: "🥚🐲", level: "easy" },
  { id: "loki", title: "Loki", emojis: "🐍🎭", level: "easy" },
  { id: "bobs-burgers", title: "Bob's Burgers", emojis: "🍔👨", level: "easy" },
  { id: "futurama", title: "Futurama", emojis: "🚀🦞", level: "easy" },
  { id: "survivor", title: "Survivor", emojis: "🏝🔥", level: "easy" },
  { id: "sailor-moon", title: "Sailor Moon", emojis: "🌙🎀", level: "easy" },
  { id: "er", title: "ER", emojis: "🚑🏥", level: "easy" },
  { id: "frasier", title: "Frasier", emojis: "🎙🧠", level: "easy" },
  { id: "downton-abbey", title: "Downton Abbey", emojis: "🏰🎩", level: "easy" },
  { id: "yu-gi-oh", title: "Yu-Gi-Oh!", emojis: "🃏🔺", level: "easy" },
  { id: "digimon", title: "Digimon", emojis: "💻🐉", level: "easy" },
  { id: "scrubs", title: "Scrubs", emojis: "🩺🎭", level: "easy" },
  { id: "homeland", title: "Homeland", emojis: "🦅🕵", level: "easy" },
  { id: "person-of-interest", title: "Person of Interest", emojis: "👁💻", level: "easy" },
  { id: "once-upon-a-time", title: "Once Upon a Time", emojis: "🏰📖", level: "easy" },
  { id: "chilling-adventures-of-sabrina", title: "Chilling Adventures of Sabrina", emojis: "🧙🎃", level: "easy" },
  { id: "jujutsu-kaisen", title: "Jujutsu Kaisen", emojis: "👹🌀", level: "easy" },
  { id: "new-girl", title: "New Girl", emojis: "👓🏠", level: "easy" },
  { id: "30-rock", title: "30 Rock", emojis: "🎬🗽", level: "easy" },
  { id: "schitts-creek", title: "Schitt's Creek", emojis: "🧳🏨", level: "easy" },
  { id: "abbott-elementary", title: "Abbott Elementary", emojis: "🍎🏫", level: "easy" },
  { id: "curb-your-enthusiasm", title: "Curb Your Enthusiasm", emojis: "😒🎬", level: "easy" },
  { id: "chicago-fire", title: "Chicago Fire", emojis: "🚒🔥", level: "easy" },
  { id: "killing-eve", title: "Killing Eve", emojis: "🔪👗", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "charlies-angels", title: "Charlie's Angels", emojis: "👠🔫", level: "medium" },
  { id: "all-in-the-family", title: "All in the Family", emojis: "👨📺", level: "medium" },
  { id: "the-andy-griffith-show", title: "The Andy Griffith Show", emojis: "⭐👮", level: "medium" },
  { id: "charmed", title: "Charmed", emojis: "🔮✨", level: "medium" },
  { id: "grimm", title: "Grimm", emojis: "🐺📖", level: "medium" },
  { id: "young-sheldon", title: "Young Sheldon", emojis: "🧒🔬", level: "medium" },
  { id: "chicago-pd", title: "Chicago P.D.", emojis: "🚔🌆", level: "medium" },
  { id: "criminal-minds", title: "Criminal Minds", emojis: "🧠🚨", level: "medium" },
  { id: "cold-case", title: "Cold Case", emojis: "📁❄", level: "medium" },
  { id: "elementary", title: "Elementary", emojis: "🎻🔍", level: "medium" },
  { id: "veronica-mars", title: "Veronica Mars", emojis: "🕵🎒", level: "medium" },
  { id: "nikita", title: "Nikita", emojis: "🔫💃", level: "medium" },
  { id: "alias", title: "Alias", emojis: "🕶🌍", level: "medium" },
  { id: "lie-to-me", title: "Lie to Me", emojis: "😐🔍", level: "medium" },
  { id: "the-resident", title: "The Resident", emojis: "💉🏥", level: "medium" },
  { id: "warrior-nun", title: "Warrior Nun", emojis: "⛪🗡", level: "medium" },
  { id: "vikings-valhalla", title: "Vikings: Valhalla", emojis: "🪓⚔", level: "medium" },
  { id: "manifest", title: "Manifest", emojis: "✈🔮", level: "medium" },
  { id: "reacher", title: "Reacher", emojis: "💪🎒", level: "medium" },
  { id: "interview-with-the-vampire", title: "Interview with the Vampire", emojis: "📜🧛", level: "medium" },
  { id: "silo", title: "Silo", emojis: "🕳🌾", level: "medium" },
  { id: "line-of-duty", title: "Line of Duty", emojis: "🕵👮", level: "medium" },
  { id: "happy-valley", title: "Happy Valley", emojis: "⛰👮", level: "medium" },
  { id: "bosch", title: "Bosch", emojis: "🕵🌃", level: "medium" },
  { id: "insecure", title: "Insecure", emojis: "🎤👩", level: "medium" },

  // ===== HARD (25) =====
  { id: "bloodline", title: "Bloodline", emojis: "🌴⚖", level: "hard" },
  { id: "ray-donovan", title: "Ray Donovan", emojis: "🧹💼", level: "hard" },
  { id: "billions", title: "Billions", emojis: "💹🦈", level: "hard" },
  { id: "snowfall", title: "Snowfall", emojis: "❄🌆", level: "hard" },
  { id: "power", title: "Power", emojis: "👑💊", level: "hard" },
  { id: "the-night-manager", title: "The Night Manager", emojis: "🕴🏨", level: "hard" },
  { id: "slow-horses", title: "Slow Horses", emojis: "🐴🕵", level: "hard" },
  { id: "the-diplomat", title: "The Diplomat", emojis: "🕊🌍", level: "hard" },
  { id: "wentworth", title: "Wentworth", emojis: "🔒👩", level: "hard" },
  { id: "girls", title: "Girls", emojis: "🗽👩", level: "hard" },
  { id: "the-newsroom", title: "The Newsroom", emojis: "📰🎙", level: "hard" },
  { id: "weeds", title: "Weeds", emojis: "🌿🏠", level: "hard" },
  { id: "nurse-jackie", title: "Nurse Jackie", emojis: "💉😷", level: "hard" },
  { id: "dopesick", title: "Dopesick", emojis: "💊⚖", level: "hard" },
  { id: "victoria", title: "Victoria", emojis: "👑🎀", level: "hard" },
  { id: "call-the-midwife", title: "Call the Midwife", emojis: "👶🚲", level: "hard" },
  { id: "unforgotten", title: "Unforgotten", emojis: "🕯🔍", level: "hard" },
  { id: "vera", title: "Vera", emojis: "🌧🕵", level: "hard" },
  { id: "shetland", title: "Shetland", emojis: "🏝🔦", level: "hard" },
  { id: "the-bridge", title: "The Bridge", emojis: "🌉🔍", level: "hard" },
  { id: "wallander", title: "Wallander", emojis: "🕵❄", level: "hard" },
  { id: "prime-suspect", title: "Prime Suspect", emojis: "🎖🔍", level: "hard" },
  { id: "the-killing", title: "The Killing", emojis: "🌧🔪", level: "hard" },
  { id: "top-of-the-lake", title: "Top of the Lake", emojis: "🏔🔍", level: "hard" },
  { id: "the-split", title: "The Split", emojis: "⚖👪", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "the-rockford-files", title: "The Rockford Files", emojis: "🚗🕵", level: "impossible" },
  { id: "starsky-and-hutch", title: "Starsky and Hutch", emojis: "🚗🔫", level: "impossible" },
  { id: "naked-city", title: "Naked City", emojis: "🌃🚔", level: "impossible" },
  { id: "peter-gunn", title: "Peter Gunn", emojis: "🎷🔫", level: "impossible" },
  { id: "perry-mason", title: "Perry Mason", emojis: "📜⚖", level: "impossible" },
  { id: "dragnet", title: "Dragnet", emojis: "🚔🎙", level: "impossible" },
  { id: "the-untouchables", title: "The Untouchables", emojis: "🍾🔫", level: "impossible" },
  { id: "highway-patrol", title: "Highway Patrol", emojis: "🚔🛣", level: "impossible" },
  { id: "alfred-hitchcock-presents", title: "Alfred Hitchcock Presents", emojis: "🔪🕴", level: "impossible" },
  { id: "the-virginian", title: "The Virginian", emojis: "🤠🐎", level: "impossible" },
  { id: "the-big-valley", title: "The Big Valley", emojis: "🐴💰", level: "impossible" },
  { id: "kung-fu", title: "Kung Fu", emojis: "🥋🎋", level: "impossible" },
  { id: "the-waltons", title: "The Waltons", emojis: "🏠🌲", level: "impossible" },
  { id: "little-house-on-the-prairie", title: "Little House on the Prairie", emojis: "🌾🏡", level: "impossible" },
  { id: "maverick", title: "Maverick", emojis: "🃏🤠", level: "impossible" },
  { id: "cheyenne", title: "Cheyenne", emojis: "🤠🏹", level: "impossible" },
  { id: "the-lone-ranger", title: "The Lone Ranger", emojis: "🎭🐴", level: "impossible" },
  { id: "zorro", title: "Zorro", emojis: "🗡🎭", level: "impossible" },
  { id: "77-sunset-strip", title: "77 Sunset Strip", emojis: "🕶🚗", level: "impossible" },
  { id: "ben-casey", title: "Ben Casey", emojis: "🩺⚕", level: "impossible" },
  { id: "dr-kildare", title: "Dr. Kildare", emojis: "💊👨", level: "impossible" },
  { id: "the-defenders-1961", title: "The Defenders", emojis: "⚖🗽", level: "impossible" },
  { id: "the-beverly-hillbillies", title: "The Beverly Hillbillies", emojis: "💰🌵", level: "impossible" },
  { id: "green-acres", title: "Green Acres", emojis: "🐷🚜", level: "impossible" },
  { id: "f-troop", title: "F Troop", emojis: "🪖😂", level: "impossible" },
];
