// E193 tv-emoji facts — one true <=70-char fact per show, shown on reveal.
export const TV_EMOJI_4_FACTS = {
  // EASY
  "buffy-the-vampire-slayer": "A WB/UPN show (1997-2003) about a teen who slays vampires.",
  "house-of-the-dragon": "An HBO prequel to Game of Thrones about House Targaryen.",
  "loki": "A Marvel Disney+ series about the trickster god across timelines.",
  "bobs-burgers": "A Fox animated sitcom about a family-run burger restaurant.",
  "futurama": "Fox/Adult Swim sci-fi cartoon about a man frozen into the year 3000.",
  "survivor": "A CBS reality show stranding contestants to outlast each other.",
  "sailor-moon": "A 1990s anime about a schoolgirl who becomes a moon warrior.",
  "er": "An NBC medical drama (1994-2009) set in a Chicago hospital.",
  "frasier": "An NBC sitcom about a Seattle radio psychiatrist, spun off Cheers.",
  "downton-abbey": "A British period drama about an aristocratic Edwardian family.",
  "yu-gi-oh": "An anime about a boy who plays a mystical trading card game.",
  "digimon": "An anime where kids partner with monsters in a digital world.",
  "scrubs": "An NBC sitcom set in a teaching hospital, following young doctors.",
  "homeland": "A Showtime thriller about a CIA officer hunting a returned POW.",
  "person-of-interest": "A CBS sci-fi drama about an AI that predicts violent crimes.",
  "once-upon-a-time": "An ABC fantasy where fairy-tale characters live in our world.",
  "chilling-adventures-of-sabrina": "A Netflix show about a half-witch teen navigating two worlds.",
  "jujutsu-kaisen": "An anime about students who battle deadly cursed spirits.",
  "new-girl": "A Fox sitcom about a quirky teacher living with three roommates.",
  "30-rock": "An NBC sitcom set behind the scenes of a sketch comedy show.",
  "schitts-creek": "A CBC/Pop sitcom about a rich family exiled to a small town.",
  "abbott-elementary": "An ABC mockumentary sitcom set in a Philadelphia public school.",
  "curb-your-enthusiasm": "An HBO sitcom improvised around Larry David's daily mishaps.",
  "chicago-fire": "An NBC drama following Chicago firefighters and paramedics.",
  "killing-eve": "A BBC America thriller about an agent obsessed with an assassin.",

  // MEDIUM
  "charlies-angels": "A 1970s ABC show about three glamorous private detectives.",
  "all-in-the-family": "A 1970s CBS sitcom centered on outspoken Archie Bunker.",
  "the-andy-griffith-show": "A 1960s CBS sitcom about a small-town North Carolina sheriff.",
  "charmed": "A WB show about three sisters who are practicing witches.",
  "grimm": "An NBC show about a detective who sees fairy-tale creatures.",
  "young-sheldon": "A CBS sitcom prequel following a young genius in Texas.",
  "chicago-pd": "An NBC police drama set in Chicago's Intelligence Unit.",
  "criminal-minds": "A CBS crime drama following FBI behavioral profilers.",
  "cold-case": "A CBS drama about a detective reopening unsolved murders.",
  "elementary": "A CBS modern take on Sherlock Holmes set in New York.",
  "veronica-mars": "A UPN/CW show about a teen private investigator.",
  "nikita": "A CW show about a former assassin fighting her old agency.",
  "alias": "An ABC spy drama about a double agent, Sydney Bristow.",
  "lie-to-me": "A Fox drama about an expert who reads micro-expressions.",
  "the-resident": "A Fox medical drama exposing flaws inside a hospital system.",
  "warrior-nun": "A Netflix show about a nun with a supernatural halo weapon.",
  "vikings-valhalla": "A Netflix sequel to Vikings set a century later in Scandinavia.",
  "manifest": "An NBC/Netflix drama about a flight that lands five years later.",
  "reacher": "A Prime Video show about a drifting ex-military investigator.",
  "interview-with-the-vampire": "An AMC drama about a vampire recounting his life story.",
  "silo": "An Apple TV+ show set in an underground silo after an apocalypse.",
  "line-of-duty": "A BBC drama about police officers who investigate corrupt cops.",
  "happy-valley": "A BBC crime drama about a police sergeant in West Yorkshire.",
  "bosch": "An Amazon show about an LAPD homicide detective, Harry Bosch.",
  "insecure": "An HBO comedy-drama about a Black woman navigating LA life.",

  // HARD
  "bloodline": "A Netflix drama about a Florida family unraveling over secrets.",
  "ray-donovan": "A Showtime drama about a Hollywood fixer for the rich.",
  "billions": "A Showtime drama about a hedge fund titan versus a US attorney.",
  "snowfall": "An FX drama about the 1980s crack epidemic's roots in LA.",
  "power": "A Starz drama about a nightclub owner secretly running drugs.",
  "the-night-manager": "A BBC miniseries about a hotel manager turned spy informant.",
  "slow-horses": "An Apple TV+ show about MI5's disgraced agents at Slough House.",
  "the-diplomat": "A Netflix drama about a US ambassador thrust into crisis.",
  "wentworth": "An Australian drama set inside a women's prison.",
  "girls": "An HBO comedy-drama about four young women in New York City.",
  "the-newsroom": "An HBO drama by Aaron Sorkin set behind a cable news desk.",
  "weeds": "A Showtime dark comedy about a suburban mom who sells marijuana.",
  "nurse-jackie": "A Showtime dark comedy about an ER nurse hiding an addiction.",
  "dopesick": "A Hulu miniseries on the opioid crisis and Purdue Pharma.",
  "victoria": "A British drama chronicling the reign of Queen Victoria.",
  "call-the-midwife": "A BBC drama about midwives in 1950s-60s East London.",
  "unforgotten": "A British crime drama solving cold cases from old remains.",
  "vera": "An ITV crime drama about a gruff Northumberland detective.",
  "shetland": "A BBC crime drama set on Scotland's remote Shetland Islands.",
  "the-bridge": "A Scandinavian crime drama starting with a body on a bridge.",
  "wallander": "A BBC/Swedish drama about detective Kurt Wallander in Ystad.",
  "prime-suspect": "An ITV drama about a female detective fighting for respect.",
  "the-killing": "A Danish/US crime drama unraveling one murder over a season.",
  "top-of-the-lake": "A Jane Campion drama about a detective in rural New Zealand.",
  "the-split": "A BBC drama about a family of divorce lawyers in London.",

  // IMPOSSIBLE
  "the-rockford-files": "A 1970s NBC show about an ex-con private investigator.",
  "starsky-and-hutch": "A 1970s ABC show about two plainclothes police detectives.",
  "naked-city": "A 1950s-60s ABC crime drama filmed on New York City streets.",
  "peter-gunn": "A 1958 NBC show about a jazz-loving private detective.",
  "perry-mason": "A 1950s-60s CBS show about a defense attorney who never loses.",
  "dragnet": "A 1950s NBC show following LAPD Sergeant Joe Friday's cases.",
  "the-untouchables": "A 1950s-60s ABC show on agents fighting Prohibition gangsters.",
  "highway-patrol": "A 1950s syndicated show following a state highway patrol chief.",
  "alfred-hitchcock-presents": "A 1950s-60s CBS/NBC anthology hosted by Alfred Hitchcock.",
  "the-virginian": "A 1960s NBC western set on a Wyoming cattle ranch.",
  "the-big-valley": "A 1960s ABC western about a wealthy California ranch family.",
  "kung-fu": "A 1970s ABC show about a Shaolin monk wandering the Old West.",
  "the-waltons": "A 1970s CBS drama about a large family in rural Virginia.",
  "little-house-on-the-prairie": "A 1970s-80s NBC show about a pioneer family in Minnesota.",
  "maverick": "A 1950s-60s ABC western about a card-sharp gambler brothers.",
  "cheyenne": "A 1950s ABC western about a drifter in the post-Civil War West.",
  "the-lone-ranger": "A 1950s ABC western about a masked lawman and Tonto.",
  "zorro": "A 1950s ABC show about a masked swordsman defending old California.",
  "77-sunset-strip": "A 1958 ABC show about private eyes on the Sunset Strip.",
  "ben-casey": "A 1960s ABC medical drama about a driven young neurosurgeon.",
  "dr-kildare": "A 1960s NBC medical drama about an idealistic young doctor.",
  "the-defenders-1961": "A 1960s CBS legal drama about a father-son lawyer team.",
  "the-beverly-hillbillies": "A 1960s CBS sitcom about an oil-rich family in Beverly Hills.",
  "green-acres": "A 1960s CBS sitcom about a couple who move to a rundown farm.",
  "f-troop": "A 1960s ABC sitcom about a bumbling US Cavalry outpost.",
};
