// E246 TV Emoji 7 — one TRUE fact per id, <=70 chars
export const TV_EMOJI7_FACTS = {
  "the-white-lotus": "The White Lotus is set at a new luxury resort each season.",
  "masterchef": "MasterChef began in the UK before its global franchise spread.",
  "hells-kitchen": "Hell's Kitchen is hosted by chef Gordon Ramsay.",
  "top-chef": "Top Chef pits professional chefs against each other in challenges.",
  "the-great-british-bake-off": "The Great British Bake Off films its tent in Berkshire, England.",
  "tiger-king": "Tiger King centers on zoo owner Joe Exotic.",
  "cheer": "Cheer follows a competitive cheer squad at Navarro College.",
  "selling-sunset": "Selling Sunset follows agents at The Oppenheim Group.",
  "love-is-blind": "On Love Is Blind, couples date and get engaged unseen.",
  "too-hot-to-handle": "Too Hot to Handle bans contestants from physical contact.",
  "the-real-housewives": "The Real Housewives franchise began in Orange County in 2006.",
  "jersey-shore": "Jersey Shore followed roommates at a Seaside Heights house.",
  "big-mouth": "Big Mouth is an animated show about puberty, co-created by Nick Kroll.",
  "berserk": "Berserk follows the lone swordsman Guts in a dark fantasy world.",
  "bodyguard": "Bodyguard is a BBC thriller starring Richard Madden.",
  "below-deck": "Below Deck follows the crew of a chartered superyacht.",
  "storage-wars": "Storage Wars follows buyers bidding on abandoned storage units.",
  "undercover-boss": "On Undercover Boss, executives work disguised as new employees.",
  "say-yes-to-the-dress": "Say Yes to the Dress is filmed at Kleinfeld Bridal in NYC.",
  "cops": "Cops was one of the longest-running reality shows on US TV.",
  "yu-yu-hakusho": "Yu Yu Hakusho follows a delinquent turned spirit detective.",
  "gintama": "Gintama mixes samurai comedy in an alien-ruled Edo Japan.",
  "fruits-basket": "In Fruits Basket, Sohma family members turn into zodiac animals.",
  "cardcaptor-sakura": "Cardcaptor Sakura follows a girl collecting magical Clow Cards.",
  "re-zero": "In Re:Zero, Subaru relives death in a repeating time loop.",
  "reign": "Reign is a CW drama about young Mary, Queen of Scots.",
  "vigil": "Vigil is a BBC thriller set aboard a Royal Navy submarine.",
  "mcmafia": "McMafia follows a Russian émigré drawn into organized crime.",
  "amphibia": "Amphibia follows Anne, a girl stranded in a frog world.",
  "star-vs-the-forces-of-evil": "Star vs. the Forces of Evil follows a magical princess on Earth.",
  "the-loud-house": "The Loud House centers on Lincoln and his ten sisters.",
  "ed-edd-n-eddy": "Ed, Edd n Eddy follows three boys scheming for jawbreakers.",
  "codename-kids-next-door": "Codename: Kids Next Door follows kid spies fighting adult tyranny.",
  "dexters-laboratory": "Dexter's Laboratory follows a boy genius with a secret lab.",
  "johnny-bravo": "Johnny Bravo is a vain, muscle-bound cartoon ladies' man.",
  "courage-the-cowardly-dog": "Courage the Cowardly Dog protects his owners from horrors.",
  "fosters-home-for-imaginary-friends": "Foster's Home is a shelter for abandoned imaginary friends.",
  "konosuba": "Konosuba follows a hapless hero reborn into a fantasy world.",
  "overlord": "Overlord follows a gamer trapped as an undead overlord.",
  "violet-evergarden": "Violet Evergarden follows a former soldier writing letters for others.",
  "toradora": "Toradora! pairs a fierce girl and gentle boy as reluctant allies.",
  "assassination-classroom": "Students try to kill their tentacled teacher for prize money.",
  "blue-lock": "Blue Lock trains strikers to become Japan's deadliest scorer.",
  "slam-dunk": "Slam Dunk follows a delinquent who joins his school's basketball team.",
  "ranma": "In Ranma ½, cold water turns Ranma into a girl.",
  "jack-ryan": "Jack Ryan stars John Krasinski as the Tom Clancy CIA analyst.",
  "the-man-in-the-high-castle": "The Man in the High Castle imagines the Axis winning WWII.",
  "goliath": "Goliath stars Billy Bob Thornton as a washed-up lawyer.",
  "for-all-mankind": "For All Mankind imagines the Soviets winning the moon race.",
  "preacher": "Preacher follows a Texas pastor possessed by a strange entity.",
  "doctor-foster": "Doctor Foster follows a GP who suspects her husband is unfaithful.",
  "craig-of-the-creek": "Craig of the Creek follows kids adventuring in a local creek.",
  "cow-and-chicken": "Cow and Chicken are cartoon siblings with mismatched species.",
  "camp-lazlo": "Camp Lazlo is set at Camp Kidney, a scout camp for animals.",
  "chowder": "Chowder follows an apprentice at Mung Daal's catering company.",
  "higurashi-when-they-cry": "Higurashi centers on mysterious deaths tied to a village festival.",
  "angel-beats": "Angel Beats! is set in an afterlife school for lost souls.",
  "k-on": "K-On! follows high schoolers in a light music club.",
  "the-melancholy-of-haruhi-suzumiya": "Haruhi Suzumiya's club investigates the supernatural at school.",
  "captain-tsubasa": "Captain Tsubasa follows a boy chasing his soccer dream.",
  "goblin-slayer": "Goblin Slayer follows an adventurer obsessed with killing goblins.",
  "that-time-i-got-reincarnated-as-a-slime": "Rimuru is reborn as a slime with powerful skills in a new world.",
  "your-lie-in-april": "Your Lie in April follows a pianist who lost his musical ear.",
  "kurulus-osman": "Kuruluş Osman follows the founder of the Ottoman Empire.",
  "cukur": "Çukur follows a crime family ruling an Istanbul neighborhood.",
  "hospital-playlist": "Hospital Playlist follows five doctor friends who play in a band.",
  "its-okay-to-not-be-okay": "It's Okay to Not Be Okay pairs a caretaker and a children's author.",
  "twenty-five-twenty-one": "Twenty Five Twenty One follows a fencer during the 1998 IMF crisis.",
  "extraordinary-attorney-woo": "Woo is an autistic lawyer who loves sharing whale facts.",
  "physical-100": "Physical: 100 has contestants compete for the perfect physique.",
  "counterpart": "Counterpart follows a man who meets his double from a parallel world.",
  "gen-v": "Gen V is a spinoff of The Boys set at a superhero college.",
  "mythic-quest": "Mythic Quest follows the team behind a hit video game.",
  "see": "See is set in a future where humanity has lost its sight.",
  "bad-sisters": "Bad Sisters follows sisters accused of killing their brother-in-law.",
  "my-name": "My Name follows a woman infiltrating police to avenge her father.",
  "d-p": "D.P. follows soldiers hunting deserters in the Korean army.",
  "move-to-heaven": "Move to Heaven follows a crime-scene cleanup company.",
  "start-up": "Start-Up follows entrepreneurs in a Korean tech incubator.",
  "hometown-cha-cha-cha": "Hometown Cha-Cha-Cha is set in a small Korean seaside town.",
  "signal": "Signal links a modern detective to the past via a walkie-talkie.",
  "weightlifting-fairy-kim-bok-joo": "Kim Bok-joo follows a college weightlifter finding romance.",
  "boys-over-flowers": "Boys Over Flowers follows a poor girl among four rich heirs.",
  "stranger": "Stranger (Secret Forest) follows an emotionless prosecutor.",
  "mr-sunshine": "Mr. Sunshine is set during Korea's early 1900s Joseon era.",
  "reply-1994": "Reply 1994 follows roommates at a Seoul boarding house.",
  "reply-1997": "Reply 1997 follows fans obsessed with a K-pop boy band.",
  "bir-zamanlar-cukurova": "Bir Zamanlar Çukurova is set among Turkish cotton plantations.",
  "harvey-beaks": "Harvey Beaks follows a bird who breaks his parents' rules.",
  "sanjay-and-craig": "Sanjay and Craig follows a boy and his talking pet snake.",
  "breadwinners": "Breadwinners follows two ducks who deliver bread by van.",
  "pig-goat-banana-cricket": "Pig Goat Banana Cricket follows four odd roommates' antics.",
  "the-marvelous-misadventures-of-flapjack": "Flapjack sails with Captain K'nuckles seeking Candied Island.",
  "uncle-grandpa": "Uncle Grandpa is everyone's uncle and grandpa at once.",
  "nana": "Nana follows two women who share the same first name in Tokyo.",
  "vampire-knight": "Vampire Knight is set at a school with day and night classes.",
  "elfen-lied": "Elfen Lied follows a mutant girl named Lucy with deadly powers.",
  "clannad": "Clannad follows a delinquent who befriends a girl by a tree.",
  "manhattan": "Manhattan dramatizes scientists building the first atomic bomb.",
  "hap-and-leonard": "Hap and Leonard follows two friends solving crimes in East Texas.",
};
