// E120 «Guess the US State by its Scrambled Name» — true facts, each ≤70 chars.
// Same 50 US states as E117; facts reused 1:1 by slug (verified true, ≤70 chars).
export const USSTATE_SCRAMBLED_FACTS = {
  california: "Home to Hollywood and Silicon Valley.",
  texas: "Was once its own nation — the Republic of Texas.",
  florida: "Home to the most theme parks in the world.",
  alaska: "The largest US state by far, bigger than Texas twice over.",
  hawaii: "The only state made entirely of islands.",
  "new-york": "Home to the Statue of Liberty and Times Square.",
  michigan: "Touches four of the five Great Lakes.",
  louisiana: "Home to New Orleans and Mardi Gras.",
  montana: "Called 'Big Sky Country' for its huge open skies.",
  maine: "The first US state to see the sunrise.",
  arizona: "Home to the Grand Canyon.",
  washington: "Named after the first US president.",
  colorado: "Home to over 50 mountains above 14,000 feet.",
  illinois: "Home to Chicago, the 'Windy City'.",
  nevada: "Home to Las Vegas, the entertainment capital.",
  oregon: "Home to Crater Lake, the deepest US lake.",
  utah: "Home to five stunning national parks.",
  idaho: "The top US state for growing potatoes.",
  wyoming: "The least populated US state.",
  minnesota: "Known as the 'Land of 10,000 Lakes'.",
  wisconsin: "The top US state for cheese production.",
  georgia: "The top US state for growing peanuts.",
  virginia: "Birthplace of eight US presidents.",
  "north-carolina": "Where the Wright brothers first flew.",
  "south-carolina": "Home to the historic city of Charleston.",
  oklahoma: "Home to more man-made lakes than any other state.",
  kansas: "One of the flattest states, great for growing wheat.",
  nebraska: "Home to the world's largest hand-planted forest.",
  "north-dakota": "Home to more cattle than people.",
  "south-dakota": "Home to Mount Rushmore.",
  missouri: "Home to the Gateway Arch in St. Louis.",
  iowa: "The top US state for growing corn.",
  arkansas: "Home to the only US diamond mine open to the public.",
  mississippi: "Named after the river that forms its western border.",
  alabama: "Where the modern civil rights movement began.",
  tennessee: "Home to Nashville, the country music capital.",
  kentucky: "Home to the Kentucky Derby.",
  ohio: "Birthplace of seven US presidents.",
  indiana: "Home to the Indianapolis 500 race.",
  pennsylvania: "Home to the Liberty Bell.",
  "west-virginia": "The only state formed by seceding from another.",
  maryland: "Home to the Chesapeake Bay, the largest US estuary.",
  delaware: "The very first state to join the Union.",
  "new-jersey": "Home to the first boardwalk in America.",
  connecticut: "Home to the oldest US newspaper still published.",
  "rhode-island": "The smallest US state by area.",
  massachusetts: "Where the Pilgrims first landed in 1620.",
  vermont: "The top US state for producing maple syrup.",
  "new-hampshire": "Hosts the first primary in every US election.",
  "new-mexico": "Home to White Sands, dunes of pure gypsum.",
};
