// E187 «Guess the Vehicle by Emoji 2» — 100 vehicles · 25/tier
// VO: sfx/e187-<id>.wav
// Born FAIR second-hundred: no vehicle repeats E142. Every clue = EXACTLY 2 single-codepoint
// emoji that fairly signal the vehicle (type + domain/trait). Easy tiers lean on a few dedicated
// glyphs left unused by E142; harder tiers use fair 2-emoji a knower can connect. No FE0F/ZWJ/
// keycap/skin-tone/flag. No banned color-blobs. No two items share the same unordered emoji SET.
export const VEHICLE_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "train", title: "Train", emojis: "🚆🛤", level: "easy" },
  { id: "motorcycle", title: "Motorcycle", emojis: "🏍💨", level: "easy" },
  { id: "ocean-liner", title: "Ocean Liner", emojis: "🛳🧳", level: "easy" },
  { id: "satellite", title: "Satellite", emojis: "🛰🌍", level: "easy" },
  { id: "roller-coaster", title: "Roller Coaster", emojis: "🎢🎡", level: "easy" },
  { id: "convertible", title: "Convertible", emojis: "🚗☀", level: "easy" },
  { id: "sports-car", title: "Sports Car", emojis: "🚗💨", level: "easy" },
  { id: "van", title: "Van", emojis: "🚐📦", level: "easy" },
  { id: "moving-truck", title: "Moving Truck", emojis: "🚚🏠", level: "easy" },
  { id: "fuel-truck", title: "Fuel Truck", emojis: "🚚⛽", level: "easy" },
  { id: "food-truck", title: "Food Truck", emojis: "🚚🌮", level: "easy" },
  { id: "ice-cream-truck", title: "Ice Cream Truck", emojis: "🚚🍦", level: "easy" },
  { id: "container-ship", title: "Container Ship", emojis: "🚢📦", level: "easy" },
  { id: "oil-tanker", title: "Oil Tanker", emojis: "🚢🛢", level: "easy" },
  { id: "fireboat", title: "Fireboat", emojis: "🚒🌊", level: "easy" },
  { id: "golf-cart", title: "Golf Cart", emojis: "⛳🚙", level: "easy" },
  { id: "dune-buggy", title: "Dune Buggy", emojis: "🏜🚙", level: "easy" },
  { id: "dirt-bike", title: "Dirt Bike", emojis: "🏍🏜", level: "easy" },
  { id: "houseboat", title: "Houseboat", emojis: "🏠🚤", level: "easy" },
  { id: "camper-van", title: "Camper Van", emojis: "🏕🚐", level: "easy" },
  { id: "mail-truck", title: "Mail Truck", emojis: "✉🚚", level: "easy" },
  { id: "water-taxi", title: "Water Taxi", emojis: "🚕🌊", level: "easy" },
  { id: "steamboat", title: "Steamboat", emojis: "♨🚢", level: "easy" },
  { id: "armored-truck", title: "Armored Truck", emojis: "🔒🚚", level: "easy" },
  { id: "police-boat", title: "Police Boat", emojis: "🚓🌊", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "car-ferry", title: "Car Ferry", emojis: "🚗⛴", level: "medium" },
  { id: "minivan", title: "Minivan", emojis: "🚐👶", level: "medium" },
  { id: "logging-truck", title: "Logging Truck", emojis: "🚛🪵", level: "medium" },
  { id: "car-carrier", title: "Car Carrier", emojis: "🚛🚗", level: "medium" },
  { id: "cattle-truck", title: "Cattle Truck", emojis: "🚛🐂", level: "medium" },
  { id: "milk-tanker", title: "Milk Tanker", emojis: "🚛🥛", level: "medium" },
  { id: "horsebox", title: "Horsebox", emojis: "🚛🐴", level: "medium" },
  { id: "cement-mixer", title: "Cement Mixer", emojis: "🚛🌀", level: "medium" },
  { id: "flatbed-truck", title: "Flatbed Truck", emojis: "🚛📦", level: "medium" },
  { id: "ladder-truck", title: "Ladder Truck", emojis: "🚒🪜", level: "medium" },
  { id: "street-sweeper", title: "Street Sweeper", emojis: "🧹🚙", level: "medium" },
  { id: "air-tanker", title: "Air Tanker", emojis: "✈💧", level: "medium" },
  { id: "crop-duster", title: "Crop Duster", emojis: "✈🌾", level: "medium" },
  { id: "glider", title: "Glider", emojis: "✈☁", level: "medium" },
  { id: "jumbo-jet", title: "Jumbo Jet", emojis: "✈🌍", level: "medium" },
  { id: "attack-helicopter", title: "Attack Helicopter", emojis: "🚁💣", level: "medium" },
  { id: "air-ambulance", title: "Air Ambulance", emojis: "🚁🏥", level: "medium" },
  { id: "police-helicopter", title: "Police Helicopter", emojis: "🚁👮", level: "medium" },
  { id: "space-shuttle", title: "Space Shuttle", emojis: "🚀🌍", level: "medium" },
  { id: "moon-buggy", title: "Moon Buggy", emojis: "🌙🚙", level: "medium" },
  { id: "rack-railway", title: "Rack Railway", emojis: "🚂⛰", level: "medium" },
  { id: "steam-train", title: "Steam Train", emojis: "🚂♨", level: "medium" },
  { id: "freight-train", title: "Freight Train", emojis: "🚂📦", level: "medium" },
  { id: "mining-train", title: "Mining Train", emojis: "🚂⛏", level: "medium" },
  { id: "trolley", title: "Trolley", emojis: "🚋⚡", level: "medium" },

  // ===== HARD (25) =====
  { id: "pedicab", title: "Pedicab", emojis: "🚲🪑", level: "hard" },
  { id: "tandem-bicycle", title: "Tandem Bicycle", emojis: "🚲👥", level: "hard" },
  { id: "cargo-bike", title: "Cargo Bike", emojis: "🚲📦", level: "hard" },
  { id: "mountain-bike", title: "Mountain Bike", emojis: "🚲⛰", level: "hard" },
  { id: "penny-farthing", title: "Penny-Farthing", emojis: "🚲🎩", level: "hard" },
  { id: "bmx-bike", title: "BMX Bike", emojis: "🚲🤸", level: "hard" },
  { id: "electric-bike", title: "Electric Bike", emojis: "🚲🔋", level: "hard" },
  { id: "bendy-bus", title: "Bendy Bus", emojis: "🚌🔗", level: "hard" },
  { id: "shuttle-bus", title: "Shuttle Bus", emojis: "🚌🏨", level: "hard" },
  { id: "party-bus", title: "Party Bus", emojis: "🚌🎉", level: "hard" },
  { id: "troop-carrier", title: "Troop Carrier", emojis: "🚌🪖", level: "hard" },
  { id: "prison-van", title: "Prison Van", emojis: "🚐⛓", level: "hard" },
  { id: "monster-truck", title: "Monster Truck", emojis: "🚙🛞", level: "hard" },
  { id: "amphibious-car", title: "Amphibious Car", emojis: "🚗🌊", level: "hard" },
  { id: "half-track", title: "Half-Track", emojis: "🚗🐛", level: "hard" },
  { id: "armored-car", title: "Armored Car", emojis: "🪖🚗", level: "hard" },
  { id: "minesweeper", title: "Minesweeper", emojis: "💣🚢", level: "hard" },
  { id: "aircraft-carrier", title: "Aircraft Carrier", emojis: "✈🚢", level: "hard" },
  { id: "battleship", title: "Battleship", emojis: "🚢🔫", level: "hard" },
  { id: "whaler", title: "Whaler", emojis: "🚢🐋", level: "hard" },
  { id: "pontoon-boat", title: "Pontoon Boat", emojis: "🚤🛋", level: "hard" },
  { id: "airboat", title: "Airboat", emojis: "🚤🌬", level: "hard" },
  { id: "hydrofoil", title: "Hydrofoil", emojis: "🚤💨", level: "hard" },
  { id: "catamaran", title: "Catamaran", emojis: "⛵💨", level: "hard" },
  { id: "windsurfer", title: "Windsurfer", emojis: "🏄💨", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "dhow", title: "Dhow", emojis: "⛵🏜", level: "impossible" },
  { id: "junk", title: "Junk", emojis: "⛵🏮", level: "impossible" },
  { id: "sampan", title: "Sampan", emojis: "⛵🎋", level: "impossible" },
  { id: "coracle", title: "Coracle", emojis: "🛶⭕", level: "impossible" },
  { id: "outrigger-canoe", title: "Outrigger Canoe", emojis: "🛶🌴", level: "impossible" },
  { id: "dragon-boat", title: "Dragon Boat", emojis: "🛶🐉", level: "impossible" },
  { id: "snowcat", title: "Snowcat", emojis: "🚜🏔", level: "impossible" },
  { id: "forklift", title: "Forklift", emojis: "🚜📦", level: "impossible" },
  { id: "road-roller", title: "Road Roller", emojis: "🛣🚜", level: "impossible" },
  { id: "pile-driver", title: "Pile Driver", emojis: "🏗🔨", level: "impossible" },
  { id: "mobile-crane", title: "Mobile Crane", emojis: "🏗🚛", level: "impossible" },
  { id: "ice-resurfacer", title: "Ice Resurfacer", emojis: "🧊🚜", level: "impossible" },
  { id: "handcar", title: "Handcar", emojis: "🛤🖐", level: "impossible" },
  { id: "autogyro", title: "Autogyro", emojis: "🚁🌀", level: "impossible" },
  { id: "tiltrotor", title: "Tiltrotor", emojis: "🚁✈", level: "impossible" },
  { id: "blimp", title: "Blimp", emojis: "🎈☁", level: "impossible" },
  { id: "hang-glider", title: "Hang Glider", emojis: "🪂⛰", level: "impossible" },
  { id: "ultralight", title: "Ultralight", emojis: "✈🪶", level: "impossible" },
  { id: "submersible", title: "Submersible", emojis: "🤿⬇", level: "impossible" },
  { id: "glass-bottom-boat", title: "Glass-Bottom Boat", emojis: "🚤🐠", level: "impossible" },
  { id: "cable-ferry", title: "Cable Ferry", emojis: "⛴🪢", level: "impossible" },
  { id: "ski-tow", title: "Ski Tow", emojis: "🎿⬆", level: "impossible" },
  { id: "luge", title: "Luge", emojis: "🛷💨", level: "impossible" },
  { id: "stagecoach", title: "Stagecoach", emojis: "🐎🏜", level: "impossible" },
  { id: "war-elephant", title: "War Elephant", emojis: "🐘⚔", level: "impossible" },
];
