// E187 «Guess the Vehicle by Emoji 2» — 100 vehicles · 25/tier
// VO: sfx/e187-<id>.wav
// One TRUE <=70-char fact per vehicle, shown on reveal.
export const VEHICLE_EMOJI_2_FACTS = {
  // EASY
  "train": "Linked carriages hauled along rails by an engine.",
  "motorcycle": "A two-wheeled motor vehicle straddled by the rider.",
  "ocean-liner": "A large ship built for long scheduled sea voyages.",
  "satellite": "A craft placed in orbit around Earth or a planet.",
  "roller-coaster": "A rail ride of steep drops and loops at fairgrounds.",
  "convertible": "A car with a folding or removable soft or hard top.",
  "sports-car": "A low, fast car built for speed and sharp handling.",
  "van": "A boxy road vehicle for carrying goods or people.",
  "moving-truck": "A large truck hired to move household furniture.",
  "fuel-truck": "A tanker truck that delivers petrol or diesel.",
  "food-truck": "A van fitted with a kitchen to cook and sell meals.",
  "ice-cream-truck": "A van that drives streets selling ice cream.",
  "container-ship": "A ship carrying stacked steel shipping containers.",
  "oil-tanker": "A huge ship built to carry crude oil across seas.",
  "fireboat": "A boat with pumps that fights fires on the water.",
  "golf-cart": "A small electric cart for riding around a golf course.",
  "dune-buggy": "A light open car built for driving on sand dunes.",
  "dirt-bike": "A rugged motorcycle made for off-road and trails.",
  "houseboat": "A boat built or fitted out to be lived in as a home.",
  "camper-van": "A van fitted with beds and a kitchen for travel.",
  "mail-truck": "A vehicle that carries and delivers the post.",
  "water-taxi": "A small boat that ferries paying passengers for hire.",
  "steamboat": "A boat driven by a steam-powered paddle wheel.",
  "armored-truck": "A reinforced van that transports cash securely.",
  "police-boat": "A patrol boat used by police on rivers and coasts.",

  // MEDIUM
  "car-ferry": "A ferry that carries cars and trucks across water.",
  "minivan": "A tall family van seating seven or more people.",
  "logging-truck": "A truck that hauls felled tree trunks from forests.",
  "car-carrier": "A truck that transports several cars at once.",
  "cattle-truck": "A truck built to transport livestock like cattle.",
  "milk-tanker": "A tanker truck that collects and carries raw milk.",
  "horsebox": "A trailer or truck for transporting horses safely.",
  "cement-mixer": "A truck with a rotating drum that mixes concrete.",
  "flatbed-truck": "A truck with a flat open bed for bulky loads.",
  "ladder-truck": "A fire truck with a tall extending aerial ladder.",
  "street-sweeper": "A vehicle with brushes that cleans road surfaces.",
  "air-tanker": "A plane that drops water to fight wildfires.",
  "crop-duster": "A plane that sprays crops with seed or pesticide.",
  "glider": "An engineless aircraft that soars on rising air.",
  "jumbo-jet": "A very large wide-body airliner for long flights.",
  "attack-helicopter": "A military helicopter armed for combat strikes.",
  "air-ambulance": "A helicopter that rushes patients to hospital.",
  "police-helicopter": "A helicopter police use to patrol from the air.",
  "space-shuttle": "A reusable spacecraft that launched into orbit.",
  "moon-buggy": "A wheeled rover astronauts drove on the Moon.",
  "rack-railway": "A steep railway using a toothed rack rail for grip.",
  "steam-train": "A train pulled by a coal-fired steam locomotive.",
  "freight-train": "A train of wagons that hauls cargo, not people.",
  "mining-train": "A small train that hauls ore inside mines.",
  "trolley": "A street tram drawing power from an overhead wire.",

  // HARD
  "pedicab": "A pedal-powered cycle that carries paying riders.",
  "tandem-bicycle": "A bicycle built for two riders, one behind another.",
  "cargo-bike": "A bicycle with a box or rack to haul heavy loads.",
  "mountain-bike": "A rugged bike with fat tyres for rough trails.",
  "penny-farthing": "An 1800s bike with a huge front and tiny rear wheel.",
  "bmx-bike": "A small tough bike used for stunts and dirt racing.",
  "electric-bike": "A bicycle with a battery-powered assist motor.",
  "bendy-bus": "A long bus with a flexible joint in the middle.",
  "shuttle-bus": "A bus running a short fixed route, as to a hotel.",
  "party-bus": "A bus fitted out for celebrating on the move.",
  "troop-carrier": "A large vehicle that transports soldiers.",
  "prison-van": "A secure van that transports prisoners in custody.",
  "monster-truck": "A pickup on giant wheels that crushes cars at shows.",
  "amphibious-car": "A car built to drive on land and float on water.",
  "half-track": "A vehicle with front wheels and rear crawler tracks.",
  "armored-car": "A wheeled military vehicle with armour plating.",
  "minesweeper": "A warship that finds and clears sea mines.",
  "aircraft-carrier": "A warship with a deck that launches aircraft.",
  "battleship": "A heavily armed and armoured large warship.",
  "whaler": "A ship once used to hunt whales at sea.",
  "pontoon-boat": "A flat boat floated on sealed buoyant tubes.",
  "airboat": "A flat boat pushed by a big rear aircraft propeller.",
  "hydrofoil": "A boat that rises on underwater wings at speed.",
  "catamaran": "A boat with two parallel hulls for stability.",
  "windsurfer": "A board with a sail steered by the standing rider.",

  // IMPOSSIBLE
  "dhow": "A traditional Arab sailing ship with lateen sails.",
  "junk": "A traditional Chinese sailing ship with batten sails.",
  "sampan": "A small flat wooden boat used in East Asia.",
  "coracle": "A small round boat woven from wood and hide.",
  "outrigger-canoe": "A canoe with a side float for ocean stability.",
  "dragon-boat": "A long paddled racing canoe with a dragon head.",
  "snowcat": "A tracked vehicle that grooms deep mountain snow.",
  "forklift": "A truck with forks that lifts and stacks pallets.",
  "road-roller": "A machine with heavy drums that flattens roads.",
  "pile-driver": "A machine that hammers piles into the ground.",
  "mobile-crane": "A truck-mounted crane that lifts heavy loads.",
  "ice-resurfacer": "A machine that smooths and refreshes ice rinks.",
  "handcar": "A rail cart moved by pumping a hand lever.",
  "autogyro": "An aircraft lifted by a freely spinning rotor.",
  "tiltrotor": "An aircraft with rotors that tilt to fly forward.",
  "blimp": "A steerable airship with no rigid inner frame.",
  "hang-glider": "A foot-launched wing the pilot hangs beneath.",
  "ultralight": "A very light one- or two-seat small aircraft.",
  "submersible": "A small craft that dives deep underwater.",
  "glass-bottom-boat": "A boat with a clear floor for viewing reefs.",
  "cable-ferry": "A ferry pulled across water by a fixed cable.",
  "ski-tow": "A cable lift that drags skiers uphill on their skis.",
  "luge": "A tiny sled ridden feet-first down an ice track.",
  "stagecoach": "A horse-drawn coach that once carried passengers.",
  "war-elephant": "An elephant ridden into battle in ancient armies.",
};
