// E142 emoji-vehicle facts — one verified <=70-char fact per vehicle, shown on reveal.
export const VEHICLE_EMOJI_FACTS = {
  // EASY
  "car": "The modern gasoline car dates to Karl Benz's 1886 Motorwagen.",
  "taxi": "Taxis get their name from the taximeter that measures the fare.",
  "bus": "The word 'bus' is short for the Latin 'omnibus', meaning for all.",
  "bicycle": "A bicycle is one of the most energy-efficient vehicles ever made.",
  "motor-scooter": "Scooters have a step-through frame and a small-diameter wheel.",
  "airplane": "The Wright brothers made the first powered flight in 1903.",
  "helicopter": "A helicopter can hover, and take off and land vertically.",
  "rocket": "Rockets carry their own oxidizer, so they work in outer space.",
  "ship": "Over 80% of world trade by volume is carried by sea on ships.",
  "sailboat": "A sailboat is pushed by the wind pressing against its sails.",
  "police-car": "Police cars often use flashing lights and a siren for calls.",
  "fire-engine": "A fire engine carries a water pump, hoses, and ladders.",
  "ambulance": "'Ambulance' text is often mirror-reversed to read in mirrors.",
  "tractor": "Tractors deliver high pulling force at low speeds for farming.",
  "locomotive": "Steam locomotives powered the railways of the 1800s.",
  "bullet-train": "Japan's Shinkansen opened in 1964 as the first bullet train.",
  "metro": "A metro is an urban railway, often running underground.",
  "delivery-truck": "Delivery trucks carry goods the 'last mile' to your door.",
  "skateboard": "A skateboard is a short board mounted on four small wheels.",
  "kick-scooter": "A kick scooter is pushed along by one foot on the ground.",
  "canoe": "A canoe is an open boat paddled with a single-bladed paddle.",
  "speedboat": "A speedboat is a small powerboat built for high speed.",
  "suv": "SUV stands for sport utility vehicle, built for rougher roads.",
  "minibus": "A minibus seats more than a car but fewer than a full bus.",
  "tram": "A tram runs on rails set into the streets of a city.",

  // MEDIUM
  "trolleybus": "A trolleybus draws electric power from overhead wires.",
  "articulated-lorry": "An articulated lorry bends at a joint behind the cab.",
  "pickup-truck": "A pickup truck has an open cargo bed at the rear.",
  "auto-rickshaw": "The three-wheeled auto rickshaw is common across Asia.",
  "high-speed-train": "High-speed trains typically run at 250 km/h or faster.",
  "light-rail": "Light rail is an urban railway lighter than a full metro.",
  "mountain-railway": "Mountain railways use steep grades to climb hillsides.",
  "aerial-tramway": "An aerial tramway hangs its cabins from a steel cable.",
  "ferry": "A ferry carries people and vehicles across water on a route.",
  "roller-skate": "A classic roller skate has four wheels in two pairs.",
  "ufo": "UFO means unidentified flying object, often linked to aliens.",
  "sled": "A sled slides over snow and ice on smooth runners.",
  "parachute": "A parachute uses air drag to slow a safe descent to earth.",
  "wheelchair": "A manual wheelchair is pushed by hand along its large wheels.",
  "rowboat": "A rowboat is moved by oars pulled against the water.",
  "railway-car": "A railway car is one unit coupled into a longer train.",
  "monorail": "A monorail runs on or beneath a single guiding rail.",
  "cable-car": "A cable car is pulled along by a continuously moving cable.",
  "train-station": "A train station is where trains stop to load passengers.",
  "elevator": "An elevator carries people vertically between floors.",
  "hot-air-balloon": "A hot air balloon rises because heated air is lighter.",
  "horse": "Humans have ridden horses for transport for thousands of years.",
  "camel": "Camels store fat in their humps, aiding long desert travel.",
  "school-bus": "School buses are painted yellow for high visibility.",
  "race-car": "Race cars are built low and light for maximum speed.",

  // HARD
  "motorized-wheelchair": "A motorized wheelchair moves using an electric motor.",
  "suspension-railway": "A suspension railway hangs its cars below the track.",
  "zeppelin": "The rigid Zeppelin airship is named after Count von Zeppelin.",
  "seaplane": "A seaplane has floats or a hull to land on water.",
  "cargo-plane": "Cargo planes carry freight instead of passengers.",
  "drone": "A drone is a small uncrewed aircraft flown by remote control.",
  "jet-ski": "A jet ski is a stand- or sit-on personal watercraft.",
  "kayak": "A kayak is paddled with a double-bladed paddle, sitting low.",
  "yacht": "A yacht is a boat used for cruising, racing, or leisure.",
  "tugboat": "A tugboat pushes or tows much larger ships in harbors.",
  "chariot": "The ancient chariot was a two-wheeled cart pulled by horses.",
  "rickshaw": "A pulled rickshaw is a cart drawn by a person on foot.",
  "tricycle": "A tricycle has three wheels and is popular with children.",
  "unicycle": "A unicycle has a single wheel and needs constant balance.",
  "dump-truck": "A dump truck tilts its bed to unload loose material.",
  "garbage-truck": "A garbage truck collects and compacts household waste.",
  "tow-truck": "A tow truck hauls away broken-down or illegally parked cars.",
  "snowplow": "A snowplow pushes snow off roads with a wide front blade.",
  "snowmobile": "A snowmobile glides over snow on a track and front skis.",
  "dog-sled": "A dog sled is pulled across snow by a team of dogs.",
  "limousine": "A limousine is a long luxury car with a driver up front.",
  "hearse": "A hearse carries a coffin in a funeral procession.",
  "cruise-ship": "A cruise ship is a floating resort for holiday voyages.",
  "fishing-boat": "Fishing boats range from small skiffs to large trawlers.",
  "double-decker-bus": "A double-decker bus has seating on two stacked levels.",

  // IMPOSSIBLE
  "submarine": "A submarine can dive and travel deep beneath the water.",
  "hovercraft": "A hovercraft rides on a cushion of air over land or water.",
  "gondola": "A gondola is a flat boat rowed through the canals of Venice.",
  "raft": "A raft is a flat craft, often just logs lashed together.",
  "fighter-jet": "Fighter jets are fast military aircraft built for combat.",
  "jetpack": "A jetpack straps to the back to lift a single person up.",
  "covered-wagon": "Covered wagons carried pioneers across the American West.",
  "ox-cart": "The ox cart is one of the oldest wheeled farm vehicles.",
  "horse-carriage": "A horse carriage is a wheeled cart pulled by horses.",
  "wheelbarrow": "A wheelbarrow moves loads on one wheel and two handles.",
  "excavator": "An excavator digs with a bucket on a swinging arm.",
  "bulldozer": "A bulldozer pushes soil and rubble with a heavy blade.",
  "bobsled": "A bobsled is a fast sled raced down an icy track.",
  "reindeer-sleigh": "A reindeer sleigh is a snow sled pulled by reindeer.",
  "ski-lift": "A ski lift carries skiers uphill on a moving cable.",
  "icebreaker": "An icebreaker ship smashes through frozen polar sea routes.",
  "hoverboard": "A hoverboard is a self-balancing two-wheeled board.",
  "e-scooter": "An e-scooter is a kick scooter driven by an electric motor.",
  "pedal-boat": "A pedal boat is pushed through water by foot pedals.",
  "palanquin": "A palanquin is an enclosed seat carried on poles by bearers.",
  "tank": "A tank is an armored fighting vehicle that runs on tracks.",
  "jeep": "The Jeep began as a rugged military vehicle in World War II.",
  "maglev": "Shanghai's maglev floats on magnets, hitting 431 km/h.",
  "funicular": "A funicular uses paired cars on a cable up a steep slope.",
  "lifeboat": "A lifeboat is kept aboard a ship to save lives at sea.",
};
