// E248 «Guess the Video Game by Emoji 7» — facts, one TRUE fact per id, ≤70 chars
export const VIDEOGAME_EMOJI7_FACTS = {
  "red-dead-redemption-2": "Made by Rockstar Games, released in 2018.",
  "zelda-breath-of-the-wild": "Nintendo's 2017 open-world reinvention of Zelda.",
  "zelda-tears-of-the-kingdom": "2023 sequel adding sky islands and Ultrahand.",
  "animal-crossing-new-horizons": "2020 Nintendo life sim set on a deserted island.",
  "super-smash-bros-ultimate": "2018 crossover fighter with the largest roster ever.",
  "super-mario-64": "1996 Nintendo 64 game that pioneered 3D platforming.",
  "mario-kart-8-deluxe": "2017 Switch racer, one of the best-selling games ever.",
  "ea-sports-fc-24": "2023 EA soccer game after the FIFA license ended.",
  "forza-horizon-5": "2021 Playground Games racer set in Mexico.",
  "gran-turismo-7": "2022 PlayStation racer by Polyphony Digital.",
  "counter-strike-2": "Valve's 2023 rebuild of the classic shooter.",
  "marvel-rivals": "2024 NetEase hero shooter with Marvel characters.",
  "overwatch-2": "Blizzard's 2022 free-to-play sequel shooter.",
  "temple-run-2": "2013 Imangi Studios endless-runner sequel.",
  "plants-vs-zombies-2": "2013 PopCap sequel adding time-travel worlds.",
  "adopt-me": "Popular Roblox pet-raising game by Uplift Games.",
  "mobile-legends-bang-bang": "Moonton's 2016 mobile MOBA, big in Southeast Asia.",
  "splatoon-3": "2022 Nintendo ink-based shooter, third entry.",
  "the-sims-4": "2014 EA life simulation game, still updated today.",
  "kirby-and-the-forgotten-land": "2022 HAL Laboratory game, Kirby's first 3D outing.",
  "grand-theft-auto-v": "Rockstar's 2013 open-world crime game, top seller.",
  "diablo-iv": "Blizzard's 2023 dark fantasy action-RPG.",
  "tekken-8": "Bandai Namco's 2024 entry in the fighting series.",
  "street-fighter-6": "Capcom's 2023 fighter with the Drive system.",
  "mortal-kombat-1": "NetherRealm's 2023 franchise reboot.",
  "doors": "Roblox horror game about escaping through doors.",
  "piggy": "Roblox horror game by MiniToon, launched 2020.",
  "blox-fruits": "Popular Roblox game inspired by One Piece.",
  "balatro": "2024 poker-roguelike by LocalThunk, a breakout indie hit.",
  "marvels-spider-man-2": "Insomniac Games' 2023 sequel with two playable heroes.",
  "batman-arkham-city": "Rocksteady's 2011 open-world Batman game.",
  "assassins-creed-valhalla": "2020 Ubisoft entry set in the Viking age.",
  "far-cry-5": "2018 Ubisoft shooter set in Montana, USA.",
  "watch-dogs-2": "2016 Ubisoft hacking game set in San Francisco.",
  "dying-light-2": "2022 Techland parkour-zombie sequel.",
  "league-of-legends-wild-rift": "Riot Games' 2020 mobile version of League of Legends.",
  "persona-3-reload": "Atlus's 2024 remake of the 2006 RPG.",
  "path-of-exile-2": "Grinding Gear Games' action-RPG sequel.",
  "age-of-empires-iv": "2021 Relic Entertainment real-time strategy game.",
  "civilization-vi": "2016 Firaxis strategy game, sixth main entry.",
  "xcom-2": "2016 Firaxis tactical strategy sequel.",
  "frostpunk-2": "2024 11 bit studios city-survival sequel.",
  "cities-skylines-ii": "2023 Colossal Order city-builder sequel.",
  "final-fantasy-vii-remake": "Square Enix's 2020 remake of the 1997 classic.",
  "kingdom-hearts-iii": "2019 Square Enix Disney-crossover RPG.",
  "monster-hunter-rise": "2021 Capcom entry with the Wirebug mechanic.",
  "dragons-dogma-2": "Capcom's 2024 sequel to the 2012 action-RPG.",
  "pizza-tower": "2023 indie platformer by Tour De Pizza.",
  "alan-wake-2": "Remedy Entertainment's 2023 survival-horror sequel.",
  "a-plague-tale-requiem": "Asobo Studio's 2022 sequel about rats and plague.",
  "half-life-2": "Valve's 2004 sci-fi shooter, a genre landmark.",
  "portal-2": "Valve's 2011 puzzle-shooter sequel.",
  "bioshock-infinite": "Irrational Games' 2013 entry set in Columbia.",
  "dark-souls-iii": "FromSoftware's 2016 punishing action-RPG.",
  "demons-souls": "Bluepoint Games' 2020 remake of the 2009 original.",
  "resident-evil-2": "Capcom's acclaimed 2019 remake set in Raccoon City.",
  "resident-evil-village": "Capcom's 2021 entry with a castle setting.",
  "silent-hill-2": "Bloober Team's 2024 remake of the 2001 horror classic.",
  "titanfall-2": "Respawn Entertainment's 2016 mech shooter sequel.",
  "battlefield-1": "DICE's 2016 shooter set in World War I.",
  "dead-space-2": "Visceral Games' 2011 sci-fi horror sequel.",
  "mafia-ii": "2K Czech's 2010 crime drama set in the 1940s-50s.",
  "shadow-of-the-tomb-raider": "2018 Eidos-Montréal entry in the Tomb Raider reboot.",
  "uncharted-4": "Naughty Dog's 2016 adventure, Drake's final chapter.",
  "the-witcher-3-wild-hunt": "CD Projekt Red's acclaimed 2015 open-world RPG.",
  "fallout-4": "Bethesda's 2015 post-apocalyptic RPG set in Boston.",
  "horizon-forbidden-west": "Guerrilla Games' 2022 sequel to Zero Dawn.",
  "the-last-of-us-part-ii": "Naughty Dog's 2020 post-apocalyptic sequel.",
  "mortal-kombat-x": "NetherRealm's 2015 entry in the fighting series.",
  "sons-of-the-forest": "Endnight Games' 2023 survival-horror sequel.",
  "dead-island-2": "Dambuster Studios' 2023 zombie action game.",
  "left-4-dead-2": "Valve's 2009 cooperative zombie shooter sequel.",
  "payday-3": "Starbreeze's 2023 heist shooter sequel.",
  "hunt-showdown": "Crytek's 2019 bounty-hunter survival shooter.",
  "diablo-ii": "Blizzard's 1997 dungeon-crawler, hugely influential.",
  "chrono-cross": "Square's 1999 spiritual successor to Chrono Trigger.",
  "divinity-original-sin-ii": "Larian Studios' 2017 acclaimed party RPG.",
  "ori-and-the-will-of-the-wisps": "Moon Studios' 2020 metroidvania sequel.",
  "sky-children-of-the-light": "thatgamecompany's 2019 social exploration game.",
  "monkey-island-2": "LucasArts' 1991 classic point-and-click adventure.",
  "axiom-verge-2": "Thomas Happ's 2021 solo-developed metroidvania.",
  "anodyne-2": "Analgesic Productions' 2019 surreal action-adventure.",
  "oxenfree-ii": "Night School Studio's 2023 supernatural sequel.",
  "immortality": "Sam Barlow's 2022 interactive-film mystery.",
  "norco": "Geography of Robots' 2022 Louisiana-set narrative game.",
  "citizen-sleeper": "Jump Over the Age's 2022 sci-fi RPG with dice.",
  "chants-of-sennaar": "Rundisc's 2023 ancient-language puzzle game.",
  "venba": "Visai Games' 2023 South Indian cooking narrative game.",
  "dordogne": "Un Je Ne Sais Quoi's 2023 watercolor-style adventure.",
  "season-a-letter-to-the-future": "Scavengers Studio's 2023 bicycle-journey game.",
  "planet-of-lana": "Wishfully's 2023 cinematic puzzle-platformer.",
  "botany-manor": "Balloon Studios' 2024 gardening puzzle game.",
  "thank-goodness-youre-here": "Coal Supper's 2024 BAFTA-winning comedy game.",
  "animal-well": "Billy Basso's solo-developed 2024 metroidvania.",
  "ufo-50": "Mossmouth's 2024 collection of 50 retro-style games.",
  "chained-echoes": "Matthias Linda's 2022 solo-developed indie JRPG.",
  "rollerdrome": "Roll7's 2022 rollerskating combat shooter.",
  "the-forgotten-city": "Modern Storyteller's 2021 time-loop mystery.",
  "1000xresist": "sunset visitor's 2024 sci-fi narrative adventure.",
  "harold-halibut": "Slow Bros' 2024 stop-motion underwater adventure.",
};
