// E169 «Guess the Video Game by Emoji 3» — 100 games · 25/tier
// VO: sfx/e169-<id>.wav
export const VIDEOGAME_EMOJI_3_FACTS = {
  "elden-ring": "2022 FromSoftware open-world hit; sold over 25 million copies.",
  "spider-man": "2018 Insomniac PS4 exclusive that redefined superhero games.",
  "free-fire": "2017 Garena mobile battle royale; billions of downloads.",
  "brawl-stars": "2018 Supercell 3v3 mobile arena shooter.",
  "toon-blast": "2017 Peak Games cartoon cube-blasting puzzle hit.",
  "monopoly-go": "2023 Scopely mobile Monopoly; a fast billion-dollar earner.",
  "eight-ball-pool": "2010 Miniclip's massively popular online pool game.",
  "gardenscapes": "2016 Playrix match-3 meets garden renovation.",
  "royal-match": "2021 Dream Games match-3 that topped mobile charts.",
  "stumble-guys": "2020 Kitka Games party battle royale for up to 32 players.",
  "gorilla-tag": "2021 VR tag game where you move by swinging your arms.",
  "wordle": "2021 daily word puzzle bought by The New York Times.",
  "gran-turismo": "1997 Polyphony PlayStation racing-sim landmark.",
  "sea-of-thieves": "2018 Rare shared-world pirate adventure on Xbox and PC.",
  "overcooked": "2016 co-op cooking chaos from Ghost Town Games.",
  "it-takes-two": "2021 Hazelight co-op game; won Game of the Year.",
  "township": "2013 Playrix city-building and farming mobile game.",
  "goat-simulator": "2014 Coffee Stain physics-chaos goat sandbox.",
  "palworld": "2024 Pocketpair survival hit dubbed Pokemon with guns.",
  "plague-inc": "2012 Ndemic strategy game about ending humanity.",
  "powerwash-simulator": "2022 FuturLab game about relaxing pressure-washing.",
  "gears-of-war": "2006 Epic Games cover-shooter for the Xbox 360.",
  "fallout": "1997 post-nuclear RPG revived by Bethesda in 2008.",
  "hitman": "2000 IO Interactive stealth series starring Agent 47.",
  "tekken": "1994 Namco 3D fighting series; the King of Iron Fist.",
  "mass-effect": "2007 BioWare sci-fi RPG trilogy with branching choices.",
  "dragon-age": "2009 BioWare dark-fantasy RPG series.",
  "monster-hunter": "2004 Capcom series about hunting giant monsters.",
  "helldivers-2": "2024 Arrowhead co-op shooter; a surprise smash hit.",
  "valheim": "2021 Iron Gate Viking survival; sold millions in weeks.",
  "baldurs-gate-3": "2023 Larian D&D RPG; multiple Game of the Year wins.",
  "vampire-survivors": "2022 Poncle bullet-heaven roguelike phenomenon.",
  "xcom": "1994 turn-based series defending Earth from aliens.",
  "civilization": "1991 Sid Meier turn-based empire-building series.",
  "age-of-empires": "1997 Ensemble historical real-time strategy classic.",
  "starcraft": "1998 Blizzard RTS; a cornerstone of esports.",
  "warframe": "2013 Digital Extremes free-to-play space-ninja shooter.",
  "destiny-2": "2017 Bungie online shooter with an MMO twist.",
  "rainbow-six-siege": "2015 Ubisoft tactical shooter about destructible sieges.",
  "titanfall": "2014 Respawn shooter mixing pilots and giant mechs.",
  "battlefield": "2002 DICE large-scale military FPS series.",
  "the-division": "2016 Ubisoft looter-shooter in a pandemic New York.",
  "dead-cells": "2018 Motion Twin roguelike-metroidvania hybrid.",
  "dave-the-diver": "2023 Mintrocket diving-and-sushi-restaurant hit.",
  "cult-of-the-lamb": "2022 Massive Monster roguelike about running a cult.",
  "slime-rancher": "2017 first-person ranching of adorable slimes.",
  "little-nightmares": "2017 Tarsier eerie puzzle-platformer horror.",
  "detroit-become-human": "2018 Quantic Dream branching android drama.",
  "life-is-strange": "2015 Dontnod episodic drama with time rewind.",
  "until-dawn": "2015 Supermassive teen-slasher with branching fates.",
  "dishonored": "2012 Arkane stealth game with supernatural powers.",
  "prey": "2017 Arkane sci-fi shooter aboard a space station.",
  "wolfenstein": "1992 id Software FPS pioneer versus the Nazis.",
  "team-fortress-2": "2007 Valve class-based shooter famous for hats.",
  "left-4-dead": "2008 Valve co-op shooter against zombie hordes.",
  "dead-rising": "2006 Capcom game of zombie mayhem in a mall.",
  "project-zomboid": "2013 open-world zombie survival sandbox.",
  "ark-survival-evolved": "2017 Studio Wildcard survival with tamable dinosaurs.",
  "rimworld": "2018 Ludeon sci-fi colony-management sim.",
  "factorio": "2020 Wube factory-building and automation game.",
  "kerbal-space-program": "2015 Squad sim about building and flying rockets.",
  "raft": "2018 ocean-survival game on a floating raft.",
  "the-forest": "2018 Endnight survival horror on a cannibal island.",
  "dont-starve": "2013 Klei wilderness-survival with gothic art.",
  "outlast": "2013 Red Barrels camcorder horror in an asylum.",
  "amnesia": "2010 Frictional first-person survival-horror hit.",
  "soma": "2015 Frictional sci-fi horror about identity.",
  "layers-of-fear": "2016 Bloober first-person psychological horror.",
  "blasphemous": "2019 dark religious metroidvania by The Game Kitchen.",
  "hyper-light-drifter": "2016 Heart Machine action game with striking pixel art.",
  "shovel-knight": "2014 Yacht Club retro-style platformer hit.",
  "enter-the-gungeon": "2016 Dodge Roll bullet-hell dungeon crawler.",
  "risk-of-rain": "2013 Hopoo roguelike shooter that scales in difficulty.",
  "darkest-dungeon": "2016 Red Hook gothic RPG about stress and dread.",
  "vampire-the-masquerade": "1991 World of Darkness tabletop-inspired RPG series.",
  "gris": "2018 Nomada watercolor platformer about grief.",
  "night-in-the-woods": "2017 story game about a cat returning to her town.",
  "to-the-moon": "2011 Freebird story of a dying man's final wish.",
  "deltarune": "2018 Toby Fox RPG set beside the Undertale world.",
  "omori": "2020 psychological-horror RPG by Omocat.",
  "doki-doki-literature-club": "2017 free visual novel with a dark horror twist.",
  "rusty-lake": "2015 surreal point-and-click puzzle series.",
  "machinarium": "2009 Amanita hand-drawn robot puzzle adventure.",
  "grim-fandango": "1998 LucasArts noir in the Land of the Dead.",
  "monkey-island": "1990 LucasArts pirate comedy adventure classic.",
  "the-walking-dead-game": "2012 Telltale episodic drama; Game of the Year.",
  "the-wolf-among-us": "2013 Telltale noir set in the Fables universe.",
  "gone-home": "2013 Fullbright story game exploring an empty house.",
  "pathologic": "2005 Ice-Pick Lodge bleak survival in a plague town.",
  "darkwood": "2017 Acid Wizard top-down survival horror.",
  "loop-hero": "2021 Four Quarters deck-building roguelike.",
  "the-messenger": "2018 Sabotage ninja action-platformer.",
  "axiom-verge": "2015 solo-made metroidvania by Thomas Happ.",
  "owlboy": "2016 D-Pad Studio pixel-art flying adventure.",
  "iconoclasts": "2018 action-platformer by solo dev Joakim Sandberg.",
  "gorogoa": "2017 hand-drawn tile-sliding puzzle by Jason Roberts.",
  "opus-magnum": "2017 Zachtronics alchemy-engineering puzzle game.",
  "pony-island": "2016 Daniel Mullins meta-horror hiding as a pony game.",
  "lisa-the-painful": "2014 Dingaling bleak post-apocalyptic RPG.",
  "signalis": "2022 rose-engine retro survival-horror homage.",
};
