// E241 «Guess the Video Game by Emoji 6» — facts, one TRUE fact per id, ≤70 chars
export const VIDEOGAME_EMOJI6_FACTS = {
  "ratchet-and-clank": "A lombax and a robot team up across galaxies with gadget guns",
  "sly-cooper": "Sly is a raccoon master thief from a long line of thieves",
  "bayonetta": "Bayonetta is an umbra witch who fights angels with her hair",
  "mega-man": "Mega Man copies boss powers after defeating them",
  "bomberman": "Bomberman blasts through mazes with a trail of bombs",
  "contra": "Contra sends two soldiers to fight an alien invasion alone",
  "doodle-jump": "Doodle Jump has players bounce a doodle character sky-high",
  "zuma": "In Zuma a stone frog shoots color-matching balls",
  "toy-blast": "Toy Blast is a match-and-blast puzzle game by Peak Games",
  "sudoku": "Sudoku fills a 9x9 grid so every row and column has 1-9",
  "adventure-capitalist": "AdVenture Capitalist is an idle tycoon game about lemonade stands",
  "tap-titans": "Tap Titans has players tap to battle giant titans",
  "mario-vs-donkey-kong": "Mario vs. Donkey Kong has Mario chase stolen wind-up toys",
  "new-super-mario-bros": "New Super Mario Bros. brought Mario back to 2D platforming",
  "wii-fit": "Wii Fit used a balance board for exercise mini-games",
  "nintendogs": "Nintendogs lets players raise a virtual puppy on handheld",
  "duck-hunt": "Duck Hunt used a light gun to shoot ducks on screen",
  "punch-out": "In Punch-Out!! players box Little Mac up the rankings",
  "dr-mario": "Dr. Mario has players match colored pills to clear viruses",
  "yoshis-island": "Yoshi's Island has Yoshi carry Baby Mario on his back",
  "sonic-adventure": "Sonic Adventure was Sonic's first fully 3D console game",
  "street-fighter-ii": "Street Fighter II popularized the versus fighting genre",
  "mortal-kombat-11": "Mortal Kombat 11 lets players fight across shifting timelines",
  "injustice-2": "Injustice 2 pits DC heroes and villains in gear-based combat",
  "angry-birds-2": "Angry Birds 2 added spell cards to the slingshot formula",
  "ni-no-kuni": "Ni no Kuni was co-animated by Studio Ghibli",
  "bravely-default": "Bravely Default lets players save turns with a Default command",
  "star-ocean": "Star Ocean blends sci-fi space travel with fantasy RPG combat",
  "dauntless": "In Dauntless hunters team up to slay giant Behemoths",
  "lies-of-p": "Lies of P reimagines Pinocchio as a dark souls-like puppet",
  "dino-crisis": "Dino Crisis traps its heroine on an island full of dinosaurs",
  "onimusha": "Onimusha has a samurai fight demons in feudal Japan",
  "ninja-gaiden": "Ninja Gaiden stars ninja Ryu Hayabusa in fast sword combat",
  "resident-evil-4": "Resident Evil 4 moved the series to an over-the-shoulder view",
  "gears-5": "Gears 5 lets players explore an open map as Kait Diaz",
  "halo-infinite": "Halo Infinite gave Master Chief a grappling hook tool",
  "remnant-2": "Remnant II has players fight through procedural worlds",
  "monster-hunter-world": "Monster Hunter: World let hunters roam one seamless map",
  "wo-long-fallen-dynasty": "Wo Long is set during China's Three Kingdoms era",
  "persona-3": "Persona 3 has students fight shadows at midnight in Tartarus",
  "final-fantasy-x": "Final Fantasy X sends Tidus into the world of Spira",
  "fire-emblem-three-houses": "Three Houses has the player teach at a strategy academy",
  "god-of-war-ragnarok": "Ragnarök follows Kratos and Atreus into Norse mythology",
  "hades-ii": "Hades II has players fight as the witch princess Melinoë",
  "lego-marvel-super-heroes": "LEGO Marvel Super Heroes lets players play as dozens of Marvel heroes",
  "saints-row-the-third": "Saints Row: The Third has the gang battling a global cartel",
  "words-of-wonders": "Words of Wonders is a crossword puzzle game set in city landmarks",
  "dance-dance-revolution": "Dance Dance Revolution has players step on arrows to the beat",
  "rock-band": "Rock Band lets a group play guitar, drums, bass, and vocals",
  "pikuniku": "Pikuniku stars a pink bean-shaped creature with kicking legs",
  "etrian-odyssey": "Etrian Odyssey has players hand-draw their own dungeon maps",
  "wild-arms": "Wild Arms blends a Wild West setting with fantasy RPG combat",
  "legend-of-dragoon": "The Legend of Dragoon lets warriors transform into dragoons",
  "shadow-of-war": "Shadow of War features a Nemesis system for rival orcs",
  "dishonored-2": "Dishonored 2 lets players choose between Corvo and Emily",
  "wolfenstein-the-new-order": "The New Order has B.J. Blazkowicz fight an alternate Nazi regime",
  "hellblade-senuas-sacrifice": "Hellblade portrays Senua's psychosis through binaural audio",
  "remember-me": "Remember Me lets players remix people's memories",
  "metal-gear-rising-revengeance": "Revengeance has Raiden slice enemies with a cyborg blade",
  "astral-chain": "Astral Chain has officers battle using tethered Legion creatures",
  "the-evil-within-2": "The Evil Within 2 sends Sebastian into a simulated town",
  "observation": "Observation has players see the story through a space station AI",
  "tacoma": "Tacoma has players explore an abandoned space station's AR logs",
  "everybodys-gone-to-the-rapture": "The game unfolds in an empty English village after a strange event",
  "pathologic-2": "Pathologic 2 has a healer fight to save a plague-stricken town",
  "griftlands": "Griftlands is a deck-building game about outlaws and negotiation",
  "blasphemous-2": "Blasphemous 2 sends the Penitent One through a cursed land again",
  "sifu": "Sifu has its hero age with every death while seeking revenge",
  "hollow-knight-silksong": "Silksong stars Hornet exploring a new kingdom called Pharloom",
  "dredge": "Dredge has a fisherman haul in eerie catches at night",
  "cassette-beasts": "Cassette Beasts has players record monsters onto cassette tapes",
  "children-of-morta": "Children of Morta follows a family of guardians fighting corruption",
  "moonlighter": "Moonlighter has a shopkeeper raid dungeons by night",
  "subnautica-below-zero": "Below Zero explores a frozen alien ocean world",
  "drakengard-3": "Drakengard 3 has a sword-wielding woman bond with a dragon",
  "thimbleweed-park": "Thimbleweed Park is a point-and-click mystery in a dying town",
  "anodyne": "Anodyne is a top-down adventure exploring surreal dreamscapes",
  "yume-nikki": "Yume Nikki has a girl explore worlds only through her dreams",
  "lone-survivor": "Lone Survivor has a masked man scavenge a monster-filled city",
  "kathy-rain": "Kathy Rain has a student probe her grandfather's mysterious death",
  "fran-bow": "Fran Bow follows a girl searching for her missing cat",
  "the-cat-lady": "The Cat Lady follows a woman who cannot permanently die",
  "va-11-hall-a": "VA-11 HALL-A has players mix drinks for a cyberpunk bartender",
  "the-cave": "The Cave has seven characters explore a talking, sentient cave",
  "costume-quest": "Costume Quest has kids battle in Halloween costumes with real powers",
  "brutal-legend": "Brütal Legend has a roadie fight in a world of heavy metal",
  "psychonauts-2": "Psychonauts 2 has players dive into the minds of psychic agents",
  "grow-home": "Grow Home has a robot climb a giant beanstalk to space",
  "rime": "RiME follows a boy shipwrecked on a mysterious island",
  "kona": "Kona has a detective investigate a snowbound Canadian town",
  "old-mans-journey": "Old Man's Journey has players reshape hills to guide an old man",
  "mutazione": "Mutazione is set in a village transformed by a meteor strike",
  "rakuen": "Rakuen has a boy and his mother explore a magical storybook world",
  "kingdom-two-crowns": "Kingdom: Two Crowns has a monarch build and defend a kingdom",
  "west-of-loathing": "West of Loathing is a comedic stick-figure Wild West RPG",
  "duskers": "Duskers has players pilot drones through derelict spaceships",
  "neversong": "Neversong follows a boy searching for his missing love in a dream",
  "iris-fall": "Iris Fall follows a girl exploring a mysterious old theater",
  "among-the-sleep": "Among the Sleep has players explore as a frightened toddler",
  "the-longing": "The Longing has a shade wait 400 days alone for a king to wake",
};
