// E248 «Guess the Video Game by Emoji 7» — 100 games · 25/tier
// VO: sfx/e248-<id>.wav
export const VIDEOGAME_EMOJI7 = [
  // ===== EASY (25) =====
  { id: "red-dead-redemption-2", title: "Red Dead Redemption 2", emojis: "🤠🐴", level: "easy" },
  { id: "zelda-breath-of-the-wild", title: "The Legend of Zelda: Breath of the Wild", emojis: "🗡🌳", level: "easy" },
  { id: "zelda-tears-of-the-kingdom", title: "The Legend of Zelda: Tears of the Kingdom", emojis: "🏝⚡", level: "easy" },
  { id: "animal-crossing-new-horizons", title: "Animal Crossing: New Horizons", emojis: "🏝🦝", level: "easy" },
  { id: "super-smash-bros-ultimate", title: "Super Smash Bros. Ultimate", emojis: "👊🌟", level: "easy" },
  { id: "super-mario-64", title: "Super Mario 64", emojis: "🍄⭐", level: "easy" },
  { id: "mario-kart-8-deluxe", title: "Mario Kart 8 Deluxe", emojis: "🏎🍌", level: "easy" },
  { id: "ea-sports-fc-24", title: "EA Sports FC 24", emojis: "⚽🏆", level: "easy" },
  { id: "forza-horizon-5", title: "Forza Horizon 5", emojis: "🚗🌵", level: "easy" },
  { id: "gran-turismo-7", title: "Gran Turismo 7", emojis: "🏎🥇", level: "easy" },
  { id: "counter-strike-2", title: "Counter-Strike 2", emojis: "🔫💣", level: "easy" },
  { id: "marvel-rivals", title: "Marvel Rivals", emojis: "🦸🛡", level: "easy" },
  { id: "overwatch-2", title: "Overwatch 2", emojis: "🎯🦾", level: "easy" },
  { id: "temple-run-2", title: "Temple Run 2", emojis: "🏃🐒", level: "easy" },
  { id: "plants-vs-zombies-2", title: "Plants vs. Zombies 2", emojis: "🌻⏰", level: "easy" },
  { id: "adopt-me", title: "Adopt Me!", emojis: "🐶🍼", level: "easy" },
  { id: "mobile-legends-bang-bang", title: "Mobile Legends: Bang Bang", emojis: "⚔📱", level: "easy" },
  { id: "splatoon-3", title: "Splatoon 3", emojis: "🦑🎨", level: "easy" },
  { id: "the-sims-4", title: "The Sims 4", emojis: "🛍🏠", level: "easy" },
  { id: "kirby-and-the-forgotten-land", title: "Kirby and the Forgotten Land", emojis: "💗🏚", level: "easy" },
  { id: "grand-theft-auto-v", title: "Grand Theft Auto V", emojis: "🚔💵", level: "easy" },
  { id: "diablo-iv", title: "Diablo IV", emojis: "👹🔥", level: "easy" },
  { id: "tekken-8", title: "Tekken 8", emojis: "🤜🥋", level: "easy" },
  { id: "street-fighter-6", title: "Street Fighter 6", emojis: "👊💥", level: "easy" },
  { id: "mortal-kombat-1", title: "Mortal Kombat 1", emojis: "🐉👊", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "doors", title: "Doors", emojis: "🚪👣", level: "medium" },
  { id: "piggy", title: "Piggy", emojis: "🐷🔪", level: "medium" },
  { id: "blox-fruits", title: "Blox Fruits", emojis: "🍇⚔", level: "medium" },
  { id: "balatro", title: "Balatro", emojis: "🃏💰", level: "medium" },
  { id: "marvels-spider-man-2", title: "Marvel's Spider-Man 2", emojis: "🕸🌆", level: "medium" },
  { id: "batman-arkham-city", title: "Batman: Arkham City", emojis: "🦇🌃", level: "medium" },
  { id: "assassins-creed-valhalla", title: "Assassin's Creed Valhalla", emojis: "🪓⛵", level: "medium" },
  { id: "far-cry-5", title: "Far Cry 5", emojis: "🌾🔫", level: "medium" },
  { id: "watch-dogs-2", title: "Watch Dogs 2", emojis: "🐕💻", level: "medium" },
  { id: "dying-light-2", title: "Dying Light 2", emojis: "🏃🌇", level: "medium" },
  { id: "league-of-legends-wild-rift", title: "League of Legends: Wild Rift", emojis: "🏆📱", level: "medium" },
  { id: "persona-3-reload", title: "Persona 3 Reload", emojis: "🎭🌙", level: "medium" },
  { id: "path-of-exile-2", title: "Path of Exile 2", emojis: "💀🛤", level: "medium" },
  { id: "age-of-empires-iv", title: "Age of Empires IV", emojis: "🏰🗡", level: "medium" },
  { id: "civilization-vi", title: "Civilization VI", emojis: "🌾🏛", level: "medium" },
  { id: "xcom-2", title: "XCOM 2", emojis: "👽🚀", level: "medium" },
  { id: "frostpunk-2", title: "Frostpunk 2", emojis: "❄🏙", level: "medium" },
  { id: "cities-skylines-ii", title: "Cities: Skylines II", emojis: "🚦🌆", level: "medium" },
  { id: "final-fantasy-vii-remake", title: "Final Fantasy VII Remake", emojis: "⚔🌸", level: "medium" },
  { id: "kingdom-hearts-iii", title: "Kingdom Hearts III", emojis: "🔑💫", level: "medium" },
  { id: "monster-hunter-rise", title: "Monster Hunter Rise", emojis: "🐲🏯", level: "medium" },
  { id: "dragons-dogma-2", title: "Dragon's Dogma 2", emojis: "🐉🏔", level: "medium" },
  { id: "pizza-tower", title: "Pizza Tower", emojis: "🍕🏃", level: "medium" },
  { id: "alan-wake-2", title: "Alan Wake 2", emojis: "🔦🌲", level: "medium" },
  { id: "a-plague-tale-requiem", title: "A Plague Tale: Requiem", emojis: "🐀⚔", level: "medium" },

  // ===== HARD (25) =====
  { id: "half-life-2", title: "Half-Life 2", emojis: "🔫🚧", level: "hard" },
  { id: "portal-2", title: "Portal 2", emojis: "🧊🤖", level: "hard" },
  { id: "bioshock-infinite", title: "BioShock Infinite", emojis: "🎈🌆", level: "hard" },
  { id: "dark-souls-iii", title: "Dark Souls III", emojis: "💀🌋", level: "hard" },
  { id: "demons-souls", title: "Demon's Souls", emojis: "💀🛡", level: "hard" },
  { id: "resident-evil-2", title: "Resident Evil 2", emojis: "🧟🚔", level: "hard" },
  { id: "resident-evil-village", title: "Resident Evil Village", emojis: "🧟🏰", level: "hard" },
  { id: "silent-hill-2", title: "Silent Hill 2", emojis: "🔦🪞", level: "hard" },
  { id: "titanfall-2", title: "Titanfall 2", emojis: "🤖🪂", level: "hard" },
  { id: "battlefield-1", title: "Battlefield 1", emojis: "⚔🎖", level: "hard" },
  { id: "dead-space-2", title: "Dead Space 2", emojis: "👽🔪", level: "hard" },
  { id: "mafia-ii", title: "Mafia II", emojis: "🎩🚔", level: "hard" },
  { id: "shadow-of-the-tomb-raider", title: "Shadow of the Tomb Raider", emojis: "🏹🌴", level: "hard" },
  { id: "uncharted-4", title: "Uncharted 4", emojis: "🧭🚂", level: "hard" },
  { id: "the-witcher-3-wild-hunt", title: "The Witcher 3: Wild Hunt", emojis: "🐺⚔", level: "hard" },
  { id: "fallout-4", title: "Fallout 4", emojis: "☢🏚", level: "hard" },
  { id: "horizon-forbidden-west", title: "Horizon Forbidden West", emojis: "🏹🌊", level: "hard" },
  { id: "the-last-of-us-part-ii", title: "The Last of Us Part II", emojis: "🍄🎸", level: "hard" },
  { id: "mortal-kombat-x", title: "Mortal Kombat X", emojis: "🦂🩸", level: "hard" },
  { id: "sons-of-the-forest", title: "Sons of the Forest", emojis: "🌲🧟", level: "hard" },
  { id: "dead-island-2", title: "Dead Island 2", emojis: "🏖🧟", level: "hard" },
  { id: "left-4-dead-2", title: "Left 4 Dead 2", emojis: "🧟🚌", level: "hard" },
  { id: "payday-3", title: "PAYDAY 3", emojis: "🏦🎭", level: "hard" },
  { id: "hunt-showdown", title: "Hunt: Showdown", emojis: "🎯🐺", level: "hard" },
  { id: "diablo-ii", title: "Diablo II", emojis: "😈📜", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "chrono-cross", title: "Chrono Cross", emojis: "🌊⏳", level: "impossible" },
  { id: "divinity-original-sin-ii", title: "Divinity: Original Sin II", emojis: "📜🔥", level: "impossible" },
  { id: "ori-and-the-will-of-the-wisps", title: "Ori and the Will of the Wisps", emojis: "🦉🌌", level: "impossible" },
  { id: "sky-children-of-the-light", title: "Sky: Children of the Light", emojis: "☁🕯", level: "impossible" },
  { id: "monkey-island-2", title: "Monkey Island 2: LeChuck's Revenge", emojis: "🐒👻", level: "impossible" },
  { id: "axiom-verge-2", title: "Axiom Verge 2", emojis: "🌴🔬", level: "impossible" },
  { id: "anodyne-2", title: "Anodyne 2: Return to Dust", emojis: "🌫🚗", level: "impossible" },
  { id: "oxenfree-ii", title: "Oxenfree II: Lost Signals", emojis: "📻🌊", level: "impossible" },
  { id: "immortality", title: "Immortality", emojis: "🎬🔄", level: "impossible" },
  { id: "norco", title: "Norco", emojis: "🏭🌙", level: "impossible" },
  { id: "citizen-sleeper", title: "Citizen Sleeper", emojis: "🛰🎲", level: "impossible" },
  { id: "chants-of-sennaar", title: "Chants of Sennaar", emojis: "📜🗿", level: "impossible" },
  { id: "venba", title: "Venba", emojis: "🍛📖", level: "impossible" },
  { id: "dordogne", title: "Dordogne", emojis: "🎨🚲", level: "impossible" },
  { id: "season-a-letter-to-the-future", title: "Season: A Letter to the Future", emojis: "🚴🌅", level: "impossible" },
  { id: "planet-of-lana", title: "Planet of Lana", emojis: "🐾🌌", level: "impossible" },
  { id: "botany-manor", title: "Botany Manor", emojis: "🌱🏡", level: "impossible" },
  { id: "thank-goodness-youre-here", title: "Thank Goodness You're Here!", emojis: "🐝🏘", level: "impossible" },
  { id: "animal-well", title: "Animal Well", emojis: "🕳🐇", level: "impossible" },
  { id: "ufo-50", title: "UFO 50", emojis: "🛸🕹", level: "impossible" },
  { id: "chained-echoes", title: "Chained Echoes", emojis: "⚔🌾", level: "impossible" },
  { id: "rollerdrome", title: "Rollerdrome", emojis: "🛼🔫", level: "impossible" },
  { id: "the-forgotten-city", title: "The Forgotten City", emojis: "🏛🔄", level: "impossible" },
  { id: "1000xresist", title: "1000xRESIST", emojis: "🧬🎬", level: "impossible" },
  { id: "harold-halibut", title: "Harold Halibut", emojis: "🐟🧵", level: "impossible" },
];
