// E228 «Guess the Video Game by Emoji 5» — 100 games · 25/tier
// VO: sfx/e228-<id>.wav
export const VIDEOGAME_EMOJI5 = [
  // ===== EASY (25) =====
  { id: "bloons-td-6", title: "Bloons TD 6", emojis: "🎈🎯", level: "easy" },
  { id: "hill-climb-racing", title: "Hill Climb Racing", emojis: "🚙⛰", level: "easy" },
  { id: "crash-team-racing", title: "Crash Team Racing", emojis: "📦🏁", level: "easy" },
  { id: "star-fox", title: "Star Fox", emojis: "🦊🚀", level: "easy" },
  { id: "diddy-kong-racing", title: "Diddy Kong Racing", emojis: "🐵🏁", level: "easy" },
  { id: "burnout-paradise", title: "Burnout Paradise", emojis: "🚗🔥", level: "easy" },
  { id: "bubble-witch-saga", title: "Bubble Witch Saga", emojis: "🧙🫧", level: "easy" },
  { id: "cooking-mama", title: "Cooking Mama", emojis: "🍳👵", level: "easy" },
  { id: "diner-dash", title: "Diner Dash", emojis: "🍽🏃", level: "easy" },
  { id: "dig-dug", title: "Dig Dug", emojis: "⛏👾", level: "easy" },
  { id: "micro-machines", title: "Micro Machines", emojis: "🚗🔍", level: "easy" },
  { id: "wwe-2k", title: "WWE 2K", emojis: "🤼🏆", level: "easy" },
  { id: "ufc", title: "UFC", emojis: "🥊🏆", level: "easy" },
  { id: "madden-nfl", title: "Madden NFL", emojis: "🏈🏆", level: "easy" },
  { id: "nba-jam", title: "NBA Jam", emojis: "🏀🔥", level: "easy" },
  { id: "skate", title: "Skate", emojis: "🛹🏆", level: "easy" },
  { id: "papas-pizzeria", title: "Papa's Pizzeria", emojis: "🍕⏱", level: "easy" },
  { id: "bubble-bobble", title: "Bubble Bobble", emojis: "🐉🫧", level: "easy" },
  { id: "traffic-rider", title: "Traffic Rider", emojis: "🏍🚦", level: "easy" },
  { id: "hungry-shark-evolution", title: "Hungry Shark Evolution", emojis: "🦈🍖", level: "easy" },
  { id: "zombie-tsunami", title: "Zombie Tsunami", emojis: "🧟🌊", level: "easy" },
  { id: "farm-heroes-saga", title: "Farm Heroes Saga", emojis: "🚜🍬", level: "easy" },
  { id: "sniper-elite", title: "Sniper Elite", emojis: "🎯🔫", level: "easy" },
  { id: "pga-tour", title: "PGA Tour", emojis: "⛳🏆", level: "easy" },
  { id: "nhl", title: "NHL", emojis: "🏒🥅", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "mini-motorways", title: "Mini Motorways", emojis: "🚗🗺", level: "medium" },
  { id: "ftl-faster-than-light", title: "FTL: Faster Than Light", emojis: "🚀⚡", level: "medium" },
  { id: "batman-arkham-asylum", title: "Batman: Arkham Asylum", emojis: "🦇🃏", level: "medium" },
  { id: "a-way-out", title: "A Way Out", emojis: "🚔👥", level: "medium" },
  { id: "shadow-fight", title: "Shadow Fight", emojis: "🥷🥋", level: "medium" },
  { id: "guardians-of-the-galaxy", title: "Marvel's Guardians of the Galaxy", emojis: "🚀🦝", level: "medium" },
  { id: "marvels-avengers", title: "Marvel's Avengers", emojis: "🦸💥", level: "medium" },
  { id: "lego-star-wars", title: "LEGO Star Wars", emojis: "🧱🚀", level: "medium" },
  { id: "lego-batman", title: "LEGO Batman", emojis: "🧱🦇", level: "medium" },
  { id: "judgment", title: "Judgment", emojis: "🕵🏙", level: "medium" },
  { id: "ghostwire-tokyo", title: "Ghostwire: Tokyo", emojis: "👻🏙", level: "medium" },
  { id: "deathloop", title: "Deathloop", emojis: "🔄🔫", level: "medium" },
  { id: "dragons-dogma", title: "Dragon's Dogma", emojis: "🐉✊", level: "medium" },
  { id: "nioh", title: "Nioh", emojis: "🥷⛩", level: "medium" },
  { id: "hi-fi-rush", title: "Hi-Fi Rush", emojis: "🎸🤖", level: "medium" },
  { id: "conan-exiles", title: "Conan Exiles", emojis: "🗡🏜", level: "medium" },
  { id: "new-world", title: "New World", emojis: "🗡🌍", level: "medium" },
  { id: "lost-ark", title: "Lost Ark", emojis: "⚓🗡", level: "medium" },
  { id: "black-desert-online", title: "Black Desert Online", emojis: "🐎⚔", level: "medium" },
  { id: "tower-of-fantasy", title: "Tower of Fantasy", emojis: "🗼✨", level: "medium" },
  { id: "honkai-star-rail", title: "Honkai: Star Rail", emojis: "🚂✨", level: "medium" },
  { id: "7-days-to-die", title: "7 Days to Die", emojis: "🧟⏳", level: "medium" },
  { id: "green-hell", title: "Green Hell", emojis: "🌴🩹", level: "medium" },
  { id: "the-long-dark", title: "The Long Dark", emojis: "❄🐺", level: "medium" },
  { id: "we-happy-few", title: "We Happy Few", emojis: "🎭😊", level: "medium" },

  // ===== HARD (25) =====
  { id: "escape-from-tarkov", title: "Escape from Tarkov", emojis: "🎒🔫", level: "hard" },
  { id: "darksiders", title: "Darksiders", emojis: "💀🐎", level: "hard" },
  { id: "medievil", title: "MediEvil", emojis: "💀🛡", level: "hard" },
  { id: "vagrant-story", title: "Vagrant Story", emojis: "🗡🏯", level: "hard" },
  { id: "shadow-tactics", title: "Shadow Tactics", emojis: "🥷🎩", level: "hard" },
  { id: "guacamelee", title: "Guacamelee!", emojis: "🐔🤼", level: "hard" },
  { id: "broforce", title: "Broforce", emojis: "💪🔥", level: "hard" },
  { id: "wasteland", title: "Wasteland", emojis: "☢🏜", level: "hard" },
  { id: "rage", title: "RAGE", emojis: "☢🏍", level: "hard" },
  { id: "metro-2033", title: "Metro 2033", emojis: "☢🚇", level: "hard" },
  { id: "stalker", title: "S.T.A.L.K.E.R.", emojis: "☢🐺", level: "hard" },
  { id: "this-war-of-mine", title: "This War of Mine", emojis: "🏚💔", level: "hard" },
  { id: "frostpunk", title: "Frostpunk", emojis: "❄🏭", level: "hard" },
  { id: "kingdom-come-deliverance", title: "Kingdom Come: Deliverance", emojis: "⚔🏰", level: "hard" },
  { id: "kenshi", title: "Kenshi", emojis: "⚔🏜", level: "hard" },
  { id: "mount-and-blade-warband", title: "Mount & Blade: Warband", emojis: "🏹🐎", level: "hard" },
  { id: "age-of-mythology", title: "Age of Mythology", emojis: "🏛⚡", level: "hard" },
  { id: "homeworld", title: "Homeworld", emojis: "🌌🛸", level: "hard" },
  { id: "company-of-heroes", title: "Company of Heroes", emojis: "🎖💥", level: "hard" },
  { id: "homefront", title: "Homefront", emojis: "🎖🔫", level: "hard" },
  { id: "dead-island", title: "Dead Island", emojis: "🏝🧟", level: "hard" },
  { id: "remnant-from-the-ashes", title: "Remnant: From the Ashes", emojis: "🌌🔫", level: "hard" },
  { id: "vampyr", title: "Vampyr", emojis: "🧛🩸", level: "hard" },
  { id: "salt-and-sanctuary", title: "Salt and Sanctuary", emojis: "⚔🧂", level: "hard" },
  { id: "chivalry-medieval-warfare", title: "Chivalry: Medieval Warfare", emojis: "⚔🩸", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "papo-and-yo", title: "Papo & Yo", emojis: "👦🐗", level: "impossible" },
  { id: "superliminal", title: "Superliminal", emojis: "🖼🔍", level: "impossible" },
  { id: "antichamber", title: "Antichamber", emojis: "🧩🌀", level: "impossible" },
  { id: "manifold-garden", title: "Manifold Garden", emojis: "🏛🔄", level: "impossible" },
  { id: "viewfinder", title: "Viewfinder", emojis: "📷🌀", level: "impossible" },
  { id: "jusant", title: "Jusant", emojis: "🧗⛰", level: "impossible" },
  { id: "neva", title: "Neva", emojis: "🐺🎨", level: "impossible" },
  { id: "sable", title: "Sable", emojis: "🏍🏜", level: "impossible" },
  { id: "lonely-mountains-downhill", title: "Lonely Mountains: Downhill", emojis: "🚲⛰", level: "impossible" },
  { id: "roki", title: "Röki", emojis: "🦊🌲", level: "impossible" },
  { id: "ashen", title: "Ashen", emojis: "⚔🌑", level: "impossible" },
  { id: "below", title: "Below", emojis: "⚔🏝", level: "impossible" },
  { id: "sword-and-sworcery", title: "Superbrothers: Sword & Sworcery EP", emojis: "🗡🎵", level: "impossible" },
  { id: "frog-detective", title: "Frog Detective", emojis: "🐸🕵", level: "impossible" },
  { id: "chicory", title: "Chicory: A Colorful Tale", emojis: "🐕🎨", level: "impossible" },
  { id: "cocoon", title: "Cocoon", emojis: "🪲🌍", level: "impossible" },
  { id: "neon-white", title: "Neon White", emojis: "😇🔫", level: "impossible" },
  { id: "sayonara-wild-hearts", title: "Sayonara Wild Hearts", emojis: "🏍💔", level: "impossible" },
  { id: "solar-ash", title: "Solar Ash", emojis: "🛹🌌", level: "impossible" },
  { id: "pyre", title: "Pyre", emojis: "🔥⚾", level: "impossible" },
  { id: "transistor", title: "Transistor", emojis: "⚔💻", level: "impossible" },
  { id: "the-gardens-between", title: "The Gardens Between", emojis: "⏳🌿", level: "impossible" },
  { id: "unpacking", title: "Unpacking", emojis: "📦🏠", level: "impossible" },
  { id: "a-plague-tale-innocence", title: "A Plague Tale: Innocence", emojis: "🐀🕯", level: "impossible" },
  { id: "void-bastards", title: "Void Bastards", emojis: "🚀🎨", level: "impossible" },
];
