// E194 video-game-emoji facts — one true <=70-char fact per game, shown on reveal.
export const VIDEOGAME_EMOJI_4_FACTS = {
  // EASY
  "super-mario-odyssey": "Nintendo's 2017 sandbox platformer starring Mario's hat, Cappy.",
  "luigis-mansion": "Nintendo's 2001 game where Luigi vacuums ghosts with the Poltergust.",
  "pokemon-go": "Niantic's 2016 AR game that sent millions walking to catch Pokémon.",
  "genshin-impact": "miHoYo's 2020 open-world gacha RPG set in fantasy Teyvat.",
  "watch-dogs": "Ubisoft's 2014 game where you hack Chicago's city grid.",
  "call-of-duty-warzone": "Activision's 2020 free-to-play battle royale spin-off of Call of Duty.",
  "yakuza": "Sega's crime-drama series following Kazuma Kiryu in Japan.",
  "ghost-of-tsushima": "Sucker Punch's 2020 samurai epic set during the Mongol invasion.",
  "crazy-taxi": "Sega's 1999 arcade game of speeding cabbies chasing fares.",
  "streets-of-rage": "Sega's 1991 beat-'em-up of street fighters cleaning up the city.",
  "fire-emblem": "Nintendo's tactical RPG series since 1990, known for unit permadeath.",
  "coin-master": "Moon Active's 2010 mobile game of slot spins and village raids.",
  "homescapes": "Playrix's 2017 puzzle game renovating a butler's family home.",
  "candy-crush-soda-saga": "King's 2014 match-3 sequel adding rising soda levels.",
  "bingo-blitz": "Buffalo Studios' 2013 social bingo app with virtual travel themes.",
  "words-with-friends": "Zynga's 2009 mobile Scrabble-style word game with friends.",
  "merge-dragons": "Gram Games' 2017 puzzle game merging objects to raise dragons.",
  "brain-out": "A 2019 mobile puzzle game full of trick questions and riddles.",
  "bubble-shooter": "A classic match-color puzzle game of popping bubble clusters.",
  "farming-simulator": "Giants Software's series letting players run a realistic farm.",
  "simcity": "Maxis' 1989 city-building sim that founded the genre.",
  "house-flipper": "Frozen District's 2018 game of renovating and reselling houses.",
  "mario-party": "Nintendo's 1998 party series of minigames and board-game boards.",
  "wordscapes": "PeopleFun's 2017 mobile word-search and crossword puzzle game.",
  "toca-life-world": "Toca Boca's open-ended sandbox app for kids' imaginative play.",
  // MEDIUM
  "pikmin": "Nintendo's 2001 strategy game commanding tiny plant creatures.",
  "two-point-hospital": "Two Point Studios' 2018 comedic hospital-management sim.",
  "saints-row": "Volition's open-world crime series known for its wild absurdity.",
  "mafia": "2K's crime-drama series set across mob-era American cities.",
  "infamous": "Sucker Punch's PS3 series of superpowered open-world action.",
  "sleeping-dogs": "United Front's 2012 open-world game set in Hong Kong's underworld.",
  "just-cause": "Avalanche Studios' series famed for its grappling-hook chaos.",
  "days-gone": "Bend Studio's 2019 open-world game of a biker in a zombie outbreak.",
  "horizon-zero-dawn": "Guerrilla Games' 2017 game of hunting robotic beasts as Aloy.",
  "parasite-eve": "Square's 1998 survival-horror RPG blending sci-fi and mitochondria.",
  "jak-and-daxter": "Naughty Dog's 2001 platformer starring a boy and his ottsel friend.",
  "littlebigplanet": "Media Molecule's 2008 platformer built around user-made levels.",
  "cities-skylines": "Colossal Order's 2015 city-building sim praised for its depth.",
  "house-of-the-dead": "Sega's 1996 arcade rail shooter battling zombie hordes.",
  "total-war": "Creative Assembly's series blending real-time battles and strategy.",
  "advance-wars": "Nintendo's turn-based war strategy series on Game Boy Advance.",
  "jet-set-radio": "Sega's 2000 game of graffiti gangs skating through Tokyo.",
  "alan-wake": "Remedy's 2010 psychological thriller where light is a weapon.",
  "the-evil-within": "Tango Gameworks' 2014 survival horror by Resident Evil's creator.",
  "slender": "Parsec's 2012 free horror game that popularized the Slender Man.",
  "splinter-cell": "Ubisoft's stealth series starring spy Sam Fisher.",
  "heavy-rain": "Quantic Dream's 2010 interactive thriller about a serial killer hunt.",
  "beyond-two-souls": "Quantic Dream's 2013 game starring a psychic woman bonded to a spirit.",
  "returnal": "Housemarque's 2021 roguelike of an astronaut trapped in a time loop.",
  "rogue-legacy": "Cellar Door Games' 2013 roguelike where each heir has new traits.",
  // HARD
  "injustice": "NetherRealm's 2013 fighting game pitting DC superheroes head-to-head.",
  "guilty-gear": "Arc System Works' anime fighting series known for its rock soundtrack.",
  "king-of-fighters": "SNK's team-based fighting series running since 1994.",
  "soulcalibur": "Namco's weapon-based fighting series starring the sword Soul Edge.",
  "marvel-vs-capcom": "Capcom's crossover fighting series pairing Marvel and Capcom heroes.",
  "splitgate": "1047 Games' 2021 shooter that adds Portal-style portal guns.",
  "path-of-exile": "Grinding Gear Games' 2013 free action RPG with a vast skill tree.",
  "divinity-original-sin": "Larian Studios' RPG series praised for deep co-op tactics.",
  "octopath-traveler": "Square Enix's 2018 RPG with eight interwoven character stories.",
  "dragon-quest": "Enix's 1986 RPG series that pioneered the genre in Japan.",
  "persona-4": "Atlus' 2008 RPG about students solving murders in a TV world.",
  "xenoblade-chronicles": "Monolith Soft's 2010 RPG set on the bodies of two frozen titans.",
  "fable": "Lionhead Studios' RPG series where player choices shape morality.",
  "psychonauts": "Double Fine's 2005 platformer exploring characters' minds.",
  "state-of-decay": "Undead Labs' 2013 open-world zombie survival management game.",
  "grounded": "Obsidian's 2020 survival game shrinking players to insect size.",
  "tetris-effect": "Enhance's 2018 audiovisual reimagining of the classic puzzle game.",
  "prince-of-persia": "Ubisoft's series famed for its time-rewinding Sands of Time.",
  "dead-or-alive": "Team Ninja's fighting series known for its counter-hold system.",
  "virtua-fighter": "Sega's 1993 game that pioneered 3D fighting graphics.",
  "shin-megami-tensei": "Atlus' RPG series of demon-negotiation, since 1987.",
  "tales-of-symphonia": "Namco's 2003 RPG praised for its Linear Motion Battle System.",
  "suikoden": "Konami's 1995 RPG series famed for recruiting 108 party members.",
  "drakengard": "Cavia's 2003 RPG that later spun off into the NieR series.",
  "nier-replicant": "Square Enix's reworked 2021 remaster of the 2010 cult RPG NieR.",
  // IMPOSSIBLE
  "shadow-hearts": "Sacnoth's 2001 RPG blending horror with a rhythm-based combat wheel.",
  "valkyrie-profile": "tri-Ace's 1999 RPG about a Norse goddess recruiting fallen souls.",
  "panzer-dragoon": "Sega's 1995 rail shooter riding a dragon through ruins.",
  "jet-force-gemini": "Rare's 1999 N64 shooter of twins battling an alien insect army.",
  "rez": "Sega's 2001 rhythm rail shooter set inside a computer network.",
  "eternal-darkness": "Silicon Knights' 2002 horror game with a sanity-effects system.",
  "killer7": "Grasshopper Manufacture's 2005 surreal rail shooter by Suda51.",
  "shadow-of-mordor": "Monolith's 2014 game introducing the Nemesis orc-memory system.",
  "viewtiful-joe": "Capcom's 2003 side-scroller starring a film-powered superhero.",
  "beyond-good-and-evil": "Ubisoft's 2003 cult classic starring reporter Jade and her pig uncle.",
  "ape-escape": "SCE Japan's 1999 platformer, the first game built for the DualShock.",
  "no-more-heroes": "Grasshopper Manufacture's 2007 game of an assassin with a beam katana.",
  "killer-instinct": "Rare's 1994 arcade fighting game famous for its combo counters.",
  "vanquish": "PlatinumGames' 2010 shooter starring a rocket-powered exosuit.",
  "gunstar-heroes": "Treasure's 1993 run-and-gun famed for its frantic boss fights.",
  "ristar": "Sega's 1995 platformer starring a star-shaped hero with stretchy arms.",
  "comix-zone": "Sega's 1995 beat-'em-up where the hero fights inside his own comic.",
  "zombies-ate-my-neighbors": "LucasArts' 1993 co-op shooter saving neighbors from movie monsters.",
  "mother-3": "Nintendo's 2006 Japan-only RPG sequel in the EarthBound series.",
  "live-a-live": "Square's 1994 RPG telling seven stories across different eras.",
  "secret-of-mana": "Square's 1993 action RPG known for its real-time ring menu.",
  "actraiser": "Quintet's 1990 hybrid of god-sim city building and action platforming.",
  "shining-force": "Sega's 1992 tactical RPG series of grid-based fantasy battles.",
  "phantasy-star": "Sega's 1987 sci-fi RPG series, among the earliest console RPGs.",
  "skies-of-arcadia": "Overworks' 2000 RPG about sky pirates sailing flying ships.",
};
