// E194 «Guess the Video Game by Emoji 4» — 100 games · 25/tier
// VO: sfx/e194-<id>.wav
export const VIDEOGAME_EMOJI_4 = [
  // ===== EASY (25) =====
  { id: "super-mario-odyssey", title: "Super Mario Odyssey", emojis: "🍄🎩", level: "easy" },
  { id: "luigis-mansion", title: "Luigi's Mansion", emojis: "👻🔦", level: "easy" },
  { id: "pokemon-go", title: "Pokémon GO", emojis: "📱🐭", level: "easy" },
  { id: "genshin-impact", title: "Genshin Impact", emojis: "⚔✨", level: "easy" },
  { id: "watch-dogs", title: "Watch Dogs", emojis: "🐕📱", level: "easy" },
  { id: "call-of-duty-warzone", title: "Call of Duty: Warzone", emojis: "🪖🌍", level: "easy" },
  { id: "yakuza", title: "Yakuza", emojis: "🐉💼", level: "easy" },
  { id: "ghost-of-tsushima", title: "Ghost of Tsushima", emojis: "👻⚔", level: "easy" },
  { id: "crazy-taxi", title: "Crazy Taxi", emojis: "🚕💨", level: "easy" },
  { id: "streets-of-rage", title: "Streets of Rage", emojis: "👊🌆", level: "easy" },
  { id: "fire-emblem", title: "Fire Emblem", emojis: "🔥⚔", level: "easy" },
  { id: "coin-master", title: "Coin Master", emojis: "🪙👑", level: "easy" },
  { id: "homescapes", title: "Homescapes", emojis: "🏠🧩", level: "easy" },
  { id: "candy-crush-soda-saga", title: "Candy Crush Soda Saga", emojis: "🥤🍬", level: "easy" },
  { id: "bingo-blitz", title: "Bingo Blitz", emojis: "🎯🎉", level: "easy" },
  { id: "words-with-friends", title: "Words With Friends", emojis: "🔤🤝", level: "easy" },
  { id: "merge-dragons", title: "Merge Dragons", emojis: "🐉🔀", level: "easy" },
  { id: "brain-out", title: "Brain Out", emojis: "🧠🚪", level: "easy" },
  { id: "bubble-shooter", title: "Bubble Shooter", emojis: "🫧🎯", level: "easy" },
  { id: "farming-simulator", title: "Farming Simulator", emojis: "🚜🌱", level: "easy" },
  { id: "simcity", title: "SimCity", emojis: "🏙🖥", level: "easy" },
  { id: "house-flipper", title: "House Flipper", emojis: "🏠🔨", level: "easy" },
  { id: "mario-party", title: "Mario Party", emojis: "🎲🍄", level: "easy" },
  { id: "wordscapes", title: "Wordscapes", emojis: "🔤🌄", level: "easy" },
  { id: "toca-life-world", title: "Toca Life World", emojis: "🧸🌍", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "pikmin", title: "Pikmin", emojis: "🌱👽", level: "medium" },
  { id: "two-point-hospital", title: "Two Point Hospital", emojis: "🏥🩺", level: "medium" },
  { id: "saints-row", title: "Saints Row", emojis: "👑🔫", level: "medium" },
  { id: "mafia", title: "Mafia", emojis: "🎩🔫", level: "medium" },
  { id: "infamous", title: "Infamous", emojis: "⚡🦸", level: "medium" },
  { id: "sleeping-dogs", title: "Sleeping Dogs", emojis: "🐕😴", level: "medium" },
  { id: "just-cause", title: "Just Cause", emojis: "🪂💥", level: "medium" },
  { id: "days-gone", title: "Days Gone", emojis: "🧟🏍", level: "medium" },
  { id: "horizon-zero-dawn", title: "Horizon Zero Dawn", emojis: "🏹🤖", level: "medium" },
  { id: "parasite-eve", title: "Parasite Eve", emojis: "🧬🔥", level: "medium" },
  { id: "jak-and-daxter", title: "Jak and Daxter", emojis: "🦦🔫", level: "medium" },
  { id: "littlebigplanet", title: "LittleBigPlanet", emojis: "🧵🌍", level: "medium" },
  { id: "cities-skylines", title: "Cities: Skylines", emojis: "🚦🏙", level: "medium" },
  { id: "house-of-the-dead", title: "The House of the Dead", emojis: "🧟🔫", level: "medium" },
  { id: "total-war", title: "Total War", emojis: "🏰⚔", level: "medium" },
  { id: "advance-wars", title: "Advance Wars", emojis: "🎖⚔", level: "medium" },
  { id: "jet-set-radio", title: "Jet Set Radio", emojis: "🛼🎧", level: "medium" },
  { id: "alan-wake", title: "Alan Wake", emojis: "🔦📖", level: "medium" },
  { id: "the-evil-within", title: "The Evil Within", emojis: "😈🩸", level: "medium" },
  { id: "slender", title: "Slender: The Eight Pages", emojis: "👤📄", level: "medium" },
  { id: "splinter-cell", title: "Splinter Cell", emojis: "🥷🔦", level: "medium" },
  { id: "heavy-rain", title: "Heavy Rain", emojis: "🌧🔪", level: "medium" },
  { id: "beyond-two-souls", title: "Beyond: Two Souls", emojis: "👻👥", level: "medium" },
  { id: "returnal", title: "Returnal", emojis: "🔄🚀", level: "medium" },
  { id: "rogue-legacy", title: "Rogue Legacy", emojis: "🏰🧬", level: "medium" },

  // ===== HARD (25) =====
  { id: "injustice", title: "Injustice: Gods Among Us", emojis: "⚖👊", level: "hard" },
  { id: "guilty-gear", title: "Guilty Gear", emojis: "⚙🗡", level: "hard" },
  { id: "king-of-fighters", title: "The King of Fighters", emojis: "👑👊", level: "hard" },
  { id: "soulcalibur", title: "Soulcalibur", emojis: "⚔🛡", level: "hard" },
  { id: "marvel-vs-capcom", title: "Marvel vs. Capcom", emojis: "🦸⚔", level: "hard" },
  { id: "splitgate", title: "Splitgate", emojis: "🌀🔫", level: "hard" },
  { id: "path-of-exile", title: "Path of Exile", emojis: "🛤🔥", level: "hard" },
  { id: "divinity-original-sin", title: "Divinity: Original Sin", emojis: "⚡📜", level: "hard" },
  { id: "octopath-traveler", title: "Octopath Traveler", emojis: "🧭⚔", level: "hard" },
  { id: "dragon-quest", title: "Dragon Quest", emojis: "🐉📜", level: "hard" },
  { id: "persona-4", title: "Persona 4", emojis: "🎭🌫", level: "hard" },
  { id: "xenoblade-chronicles", title: "Xenoblade Chronicles", emojis: "⚔🌍", level: "hard" },
  { id: "fable", title: "Fable", emojis: "📖⚔", level: "hard" },
  { id: "psychonauts", title: "Psychonauts", emojis: "🧠🎩", level: "hard" },
  { id: "state-of-decay", title: "State of Decay", emojis: "🧟🏚", level: "hard" },
  { id: "grounded", title: "Grounded", emojis: "🐜🔬", level: "hard" },
  { id: "tetris-effect", title: "Tetris Effect", emojis: "🧩✨", level: "hard" },
  { id: "prince-of-persia", title: "Prince of Persia", emojis: "🏃⏳", level: "hard" },
  { id: "dead-or-alive", title: "Dead or Alive", emojis: "💀🥊", level: "hard" },
  { id: "virtua-fighter", title: "Virtua Fighter", emojis: "🥊🕹", level: "hard" },
  { id: "shin-megami-tensei", title: "Shin Megami Tensei", emojis: "😈📿", level: "hard" },
  { id: "tales-of-symphonia", title: "Tales of Symphonia", emojis: "🎻⚔", level: "hard" },
  { id: "suikoden", title: "Suikoden", emojis: "⭐⚔", level: "hard" },
  { id: "drakengard", title: "Drakengard", emojis: "🐉⚔", level: "hard" },
  { id: "nier-replicant", title: "NieR Replicant", emojis: "🤖🌾", level: "hard" },

  // ===== IMPOSSIBLE (25) =====
  { id: "shadow-hearts", title: "Shadow Hearts", emojis: "👤❤", level: "impossible" },
  { id: "valkyrie-profile", title: "Valkyrie Profile", emojis: "👼⚔", level: "impossible" },
  { id: "panzer-dragoon", title: "Panzer Dragoon", emojis: "🐉🚀", level: "impossible" },
  { id: "jet-force-gemini", title: "Jet Force Gemini", emojis: "🚀👯", level: "impossible" },
  { id: "rez", title: "Rez", emojis: "🎵🐍", level: "impossible" },
  { id: "eternal-darkness", title: "Eternal Darkness", emojis: "🌀😱", level: "impossible" },
  { id: "killer7", title: "Killer7", emojis: "🔫👤", level: "impossible" },
  { id: "shadow-of-mordor", title: "Middle-earth: Shadow of Mordor", emojis: "👁⚔", level: "impossible" },
  { id: "viewtiful-joe", title: "Viewtiful Joe", emojis: "🎬👊", level: "impossible" },
  { id: "beyond-good-and-evil", title: "Beyond Good & Evil", emojis: "🐷📷", level: "impossible" },
  { id: "ape-escape", title: "Ape Escape", emojis: "🐒🥅", level: "impossible" },
  { id: "no-more-heroes", title: "No More Heroes", emojis: "🏍⚔", level: "impossible" },
  { id: "killer-instinct", title: "Killer Instinct", emojis: "🔪👊", level: "impossible" },
  { id: "vanquish", title: "Vanquish", emojis: "🚀🔫", level: "impossible" },
  { id: "gunstar-heroes", title: "Gunstar Heroes", emojis: "🔫⭐", level: "impossible" },
  { id: "ristar", title: "Ristar", emojis: "⭐🤜", level: "impossible" },
  { id: "comix-zone", title: "Comix Zone", emojis: "📓👊", level: "impossible" },
  { id: "zombies-ate-my-neighbors", title: "Zombies Ate My Neighbors", emojis: "🧟🏠", level: "impossible" },
  { id: "mother-3", title: "Mother 3", emojis: "👦✨", level: "impossible" },
  { id: "live-a-live", title: "Live A Live", emojis: "⏳🗡", level: "impossible" },
  { id: "secret-of-mana", title: "Secret of Mana", emojis: "🌳⚔", level: "impossible" },
  { id: "actraiser", title: "ActRaiser", emojis: "🏛☁", level: "impossible" },
  { id: "shining-force", title: "Shining Force", emojis: "✨🛡", level: "impossible" },
  { id: "phantasy-star", title: "Phantasy Star", emojis: "🌌⚔", level: "impossible" },
  { id: "skies-of-arcadia", title: "Skies of Arcadia", emojis: "☁🚢", level: "impossible" },
];
