// E154 «Guess the Villain by Emoji» — 100 fictional villains · 25/tier · clue = plain Unicode emoji (mirrors E125 isEmoji rendering)
// VO: sfx/e154-<id>.wav — phrase "It's <Villain>!" (distinct prefix, no collisions)
// FAIRNESS: every emoji is the villain's iconic look/weapon/motif; single-codepoint only; no two items share the same emoji SET.
export const VILLAIN_EMOJI = [
  // ===== EASY (25) — globally famous =====
  { id: "joker", title: "Joker", emojis: "🃏🤡", level: "easy" },
  { id: "thanos", title: "Thanos", emojis: "🧤💜", level: "easy" },
  { id: "voldemort", title: "Voldemort", emojis: "🐍💀", level: "easy" },
  { id: "darth-vader", title: "Darth Vader", emojis: "⚔🖤", level: "easy" },
  { id: "sauron", title: "Sauron", emojis: "👁🔥", level: "easy" },
  { id: "maleficent", title: "Maleficent", emojis: "😈🐉", level: "easy" },
  { id: "scar", title: "Scar", emojis: "🦁🌚", level: "easy" },
  { id: "cruella", title: "Cruella de Vil", emojis: "🐶🖤", level: "easy" },
  { id: "ursula", title: "Ursula", emojis: "🐙👑", level: "easy" },
  { id: "jafar", title: "Jafar", emojis: "🐍🪄", level: "easy" },
  { id: "pennywise", title: "Pennywise", emojis: "🤡🎈", level: "easy" },
  { id: "freddy-krueger", title: "Freddy Krueger", emojis: "🔪🧤", level: "easy" },
  { id: "bowser", title: "Bowser", emojis: "🐢🔥", level: "easy" },
  { id: "dracula", title: "Count Dracula", emojis: "🧛🦇", level: "easy" },
  { id: "gollum", title: "Gollum", emojis: "💍🐟", level: "easy" },
  { id: "terminator", title: "The Terminator", emojis: "🤖💀", level: "easy" },
  { id: "captain-hook", title: "Captain Hook", emojis: "🪝🐊", level: "easy" },
  { id: "hades", title: "Hades", emojis: "🔥💀", level: "easy" },
  { id: "wicked-witch-of-the-west", title: "Wicked Witch of the West", emojis: "🧙🧹", level: "easy" },
  { id: "chucky", title: "Chucky", emojis: "🔪🧸", level: "easy" },
  { id: "gaston", title: "Gaston", emojis: "💪🦌", level: "easy" },
  { id: "shere-khan", title: "Shere Khan", emojis: "🐅🔥", level: "easy" },
  { id: "jaws", title: "Jaws", emojis: "🦈🌊", level: "easy" },
  { id: "palpatine", title: "Emperor Palpatine", emojis: "⚡🖤", level: "easy" },
  { id: "the-grinch", title: "The Grinch", emojis: "🟢🎄", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "green-goblin", title: "Green Goblin", emojis: "🎃🛹", level: "medium" },
  { id: "magneto", title: "Magneto", emojis: "🧲🪖", level: "medium" },
  { id: "bane", title: "Bane", emojis: "🎭💪", level: "medium" },
  { id: "harley-quinn", title: "Harley Quinn", emojis: "🃏🔨", level: "medium" },
  { id: "loki", title: "Loki", emojis: "🎭👑", level: "medium" },
  { id: "hannibal-lecter", title: "Hannibal Lecter", emojis: "🍷🔪", level: "medium" },
  { id: "norman-bates", title: "Norman Bates", emojis: "🔪🚿", level: "medium" },
  { id: "jack-torrance", title: "Jack Torrance", emojis: "🪓🚪", level: "medium" },
  { id: "michael-myers", title: "Michael Myers", emojis: "🔪🎃", level: "medium" },
  { id: "jason-voorhees", title: "Jason Voorhees", emojis: "🏒⛺", level: "medium" },
  { id: "leatherface", title: "Leatherface", emojis: "🪚🥩", level: "medium" },
  { id: "ghostface", title: "Ghostface", emojis: "👻📞", level: "medium" },
  { id: "mother-gothel", title: "Mother Gothel", emojis: "🌸👵", level: "medium" },
  { id: "yzma", title: "Yzma", emojis: "🐱🧪", level: "medium" },
  { id: "dr-facilier", title: "Dr. Facilier", emojis: "🎩🐸", level: "medium" },
  { id: "smaug", title: "Smaug", emojis: "🐉💰", level: "medium" },
  { id: "saruman", title: "Saruman", emojis: "🧙🗼", level: "medium" },
  { id: "big-bad-wolf", title: "Big Bad Wolf", emojis: "🐺🐷", level: "medium" },
  { id: "eggman", title: "Dr. Eggman", emojis: "🥚🤖", level: "medium" },
  { id: "mr-freeze", title: "Mr. Freeze", emojis: "🧊🔫", level: "medium" },
  { id: "two-face", title: "Two-Face", emojis: "🪙🎭", level: "medium" },
  { id: "poison-ivy", title: "Poison Ivy", emojis: "🌿💋", level: "medium" },
  { id: "the-riddler", title: "The Riddler", emojis: "❓🟢", level: "medium" },
  { id: "catwoman", title: "Catwoman", emojis: "🐱💎", level: "medium" },
  { id: "penguin", title: "The Penguin", emojis: "🐧☔", level: "medium" },

  // ===== HARD (25) =====
  { id: "hal-9000", title: "HAL 9000", emojis: "🔴🚀", level: "hard" },
  { id: "agent-smith", title: "Agent Smith", emojis: "🕶💊", level: "hard" },
  { id: "venom", title: "Venom", emojis: "🖤👅", level: "hard" },
  { id: "doctor-octopus", title: "Doctor Octopus", emojis: "🐙🔬", level: "hard" },
  { id: "red-skull", title: "Red Skull", emojis: "🟥💀", level: "hard" },
  { id: "ultron", title: "Ultron", emojis: "🤖🔩", level: "hard" },
  { id: "scarecrow", title: "Scarecrow", emojis: "🌾😱", level: "hard" },
  { id: "randall", title: "Randall Boggs", emojis: "🦎🚪", level: "hard" },
  { id: "lotso", title: "Lotso", emojis: "🧸🍓", level: "hard" },
  { id: "hopper", title: "Hopper", emojis: "🦗👑", level: "hard" },
  { id: "clayton", title: "Clayton", emojis: "🔫🦍", level: "hard" },
  { id: "frollo", title: "Judge Frollo", emojis: "🔥⛪", level: "hard" },
  { id: "prince-john", title: "Prince John", emojis: "🦁👑", level: "hard" },
  { id: "davy-jones", title: "Davy Jones", emojis: "🐙⚓", level: "hard" },
  { id: "glados", title: "GLaDOS", emojis: "🤖🎂", level: "hard" },
  { id: "ganondorf", title: "Ganondorf", emojis: "🐗👑", level: "hard" },
  { id: "xenomorph", title: "Xenomorph", emojis: "👽🥚", level: "hard" },
  { id: "candyman", title: "Candyman", emojis: "🍬🐝", level: "hard" },
  { id: "jigsaw", title: "Jigsaw", emojis: "🧩🚲", level: "hard" },
  { id: "patrick-bateman", title: "Patrick Bateman", emojis: "🪓💼", level: "hard" },
  { id: "the-babadook", title: "The Babadook", emojis: "🎩📖", level: "hard" },
  { id: "samara", title: "Samara", emojis: "📺🌀", level: "hard" },
  { id: "annabelle", title: "Annabelle", emojis: "🪆👹", level: "hard" },
  { id: "charles-muntz", title: "Charles Muntz", emojis: "🐕🎈", level: "hard" },
  { id: "king-candy", title: "King Candy", emojis: "🍬🏁", level: "hard" },

  // ===== IMPOSSIBLE (25) — real villains die-hard fans know =====
  { id: "galactus", title: "Galactus", emojis: "🌍🍴", level: "impossible" },
  { id: "darth-maul", title: "Darth Maul", emojis: "👹🌌", level: "impossible" },
  { id: "kylo-ren", title: "Kylo Ren", emojis: "🌌⚔", level: "impossible" },
  { id: "jabba-the-hutt", title: "Jabba the Hutt", emojis: "🐌👑", level: "impossible" },
  { id: "the-balrog", title: "The Balrog", emojis: "🔥👹", level: "impossible" },
  { id: "bellatrix-lestrange", title: "Bellatrix Lestrange", emojis: "🗡🖤", level: "impossible" },
  { id: "dolores-umbridge", title: "Dolores Umbridge", emojis: "🐸🩷", level: "impossible" },
  { id: "sephiroth", title: "Sephiroth", emojis: "🪽🔥", level: "impossible" },
  { id: "pyramid-head", title: "Pyramid Head", emojis: "🔺🔪", level: "impossible" },
  { id: "bill-cipher", title: "Bill Cipher", emojis: "🔺👁", level: "impossible" },
  { id: "hexxus", title: "Hexxus", emojis: "💀🏭", level: "impossible" },
  { id: "ernesto-de-la-cruz", title: "Ernesto de la Cruz", emojis: "🎸💀", level: "impossible" },
  { id: "the-other-mother", title: "The Other Mother", emojis: "🧵👁", level: "impossible" },
  { id: "rasputin", title: "Rasputin", emojis: "💚🧪", level: "impossible" },
  { id: "governor-ratcliffe", title: "Governor Ratcliffe", emojis: "⛏💰", level: "impossible" },
  { id: "tamatoa", title: "Tamatoa", emojis: "🦀✨", level: "impossible" },
  { id: "bellwether", title: "Dawn Bellwether", emojis: "🐑💊", level: "impossible" },
  { id: "prince-hans", title: "Prince Hans", emojis: "🤴🧊", level: "impossible" },
  { id: "anton-chigurh", title: "Anton Chigurh", emojis: "🪙💨", level: "impossible" },
  { id: "immortan-joe", title: "Immortan Joe", emojis: "💀🚗", level: "impossible" },
  { id: "hans-gruber", title: "Hans Gruber", emojis: "🏢🔫", level: "impossible" },
  { id: "mr-hyde", title: "Mr. Hyde", emojis: "🧪👹", level: "impossible" },
  { id: "queen-of-hearts", title: "Queen of Hearts", emojis: "🌹👑", level: "impossible" },
  { id: "jadis-the-white-witch", title: "The White Witch", emojis: "🧊👑", level: "impossible" },
  { id: "moriarty", title: "Professor Moriarty", emojis: "🧠🕸", level: "impossible" },
];
