// E154 villain-emoji facts — one verified <=70-char fact per villain, shown on reveal.
export const VILLAIN_EMOJI_FACTS = {
  // EASY
  "joker": "Batman's clown-faced archenemy from DC Comics.",
  "thanos": "Marvel titan who hunts the six Infinity Stones.",
  "voldemort": "The snake-loving Dark Lord of Harry Potter.",
  "darth-vader": "Masked Sith Lord of the Star Wars saga.",
  "sauron": "The Dark Lord of The Lord of the Rings.",
  "maleficent": "Evil fairy of Disney's Sleeping Beauty (1959).",
  "scar": "Simba's uncle in Disney's The Lion King (1994).",
  "cruella": "101 Dalmatians villain obsessed with fur coats.",
  "ursula": "Sea witch of Disney's The Little Mermaid (1989).",
  "jafar": "Scheming sorcerer of Disney's Aladdin (1992).",
  "pennywise": "Shape-shifting clown from Stephen King's It.",
  "freddy-krueger": "Dream-stalker of A Nightmare on Elm Street.",
  "bowser": "Koopa king who kidnaps Peach in Super Mario.",
  "dracula": "Bram Stoker's iconic blood-drinking vampire count.",
  "gollum": "Ring-obsessed creature in The Lord of the Rings.",
  "terminator": "Cyborg assassin from the 1984 sci-fi film.",
  "captain-hook": "Peter Pan's pirate foe who fears a crocodile.",
  "hades": "Underworld god of Disney's Hercules (1997).",
  "wicked-witch-of-the-west": "Green villain of The Wizard of Oz (1939).",
  "chucky": "Killer doll from the Child's Play horror films.",
  "gaston": "Vain hunter in Disney's Beauty and the Beast.",
  "shere-khan": "Tiger who hunts Mowgli in The Jungle Book.",
  "jaws": "Great white shark from Spielberg's Jaws (1975).",
  "palpatine": "Sith Emperor who rules the Star Wars galaxy.",
  "the-grinch": "Green grump who tries to steal Christmas.",

  // MEDIUM
  "green-goblin": "Spider-Man foe on a glider with pumpkin bombs.",
  "magneto": "Mutant master of magnetism and X-Men villain.",
  "bane": "Masked brute who breaks Batman in DC Comics.",
  "harley-quinn": "The Joker's mallet-wielding sidekick in DC.",
  "loki": "Thor's trickster brother, Marvel's God of Mischief.",
  "hannibal-lecter": "Cannibal doctor of The Silence of the Lambs.",
  "norman-bates": "Motel killer from Hitchcock's Psycho (1960).",
  "jack-torrance": "Axe-wielding father in Kubrick's The Shining.",
  "michael-myers": "Masked killer from the Halloween films.",
  "jason-voorhees": "Hockey-masked killer of Friday the 13th.",
  "leatherface": "Chainsaw killer of The Texas Chain Saw Massacre.",
  "ghostface": "Masked phone-calling killer from Scream (1996).",
  "mother-gothel": "Youth-stealing villain in Disney's Tangled.",
  "yzma": "Scheming advisor in The Emperor's New Groove.",
  "dr-facilier": "Voodoo Shadow Man of The Princess and the Frog.",
  "smaug": "Gold-hoarding dragon in Tolkien's The Hobbit.",
  "saruman": "Corrupted white wizard of The Lord of the Rings.",
  "big-bad-wolf": "Fairy-tale wolf who huffs and puffs at pigs.",
  "eggman": "Dr. Robotnik, Sonic the Hedgehog's mustached foe.",
  "mr-freeze": "Ice-gun Batman villain who can't feel warmth.",
  "two-face": "Coin-flipping, half-scarred Batman villain.",
  "poison-ivy": "Plant-controlling eco-villain from Batman.",
  "the-riddler": "Batman foe who leaves question-mark clues.",
  "catwoman": "Jewel-thief antiheroine and Batman's foil.",
  "penguin": "Umbrella-wielding Batman villain in a top hat.",

  // HARD
  "hal-9000": "Murderous ship computer in 2001: A Space Odyssey.",
  "agent-smith": "Rogue program antagonist of The Matrix (1999).",
  "venom": "Alien symbiote and Spider-Man's toothy nemesis.",
  "doctor-octopus": "Four-armed scientist who battles Spider-Man.",
  "red-skull": "HYDRA leader and Captain America's archenemy.",
  "ultron": "AI villain who fights the Avengers in Marvel.",
  "scarecrow": "Fear-toxin Batman villain in a burlap mask.",
  "randall": "Chameleon-like villain in Pixar's Monsters, Inc.",
  "lotso": "Strawberry-scented bear villain in Toy Story 3.",
  "hopper": "Grasshopper who bullies ants in A Bug's Life.",
  "clayton": "Gorilla-hunting villain in Disney's Tarzan (1999).",
  "frollo": "Judge villain of The Hunchback of Notre Dame.",
  "prince-john": "Thumb-sucking lion in Disney's Robin Hood.",
  "davy-jones": "Tentacle-faced Pirates of the Caribbean captain.",
  "glados": "Sardonic AI antagonist of the Portal games.",
  "ganondorf": "Boar-like villain of The Legend of Zelda.",
  "xenomorph": "Acid-blooded creature from the Alien films.",
  "candyman": "Hook-handed ghost summoned by name; 1992 horror.",
  "jigsaw": "Trap-building killer of the Saw film series.",
  "patrick-bateman": "Yuppie killer from American Psycho (2000).",
  "the-babadook": "Top-hatted pop-up-book monster; 2014 horror.",
  "samara": "Vengeful well ghost from The Ring (2002).",
  "annabelle": "Haunted doll from The Conjuring universe.",
  "charles-muntz": "Dog-loving explorer villain in Pixar's Up.",
  "king-candy": "Turbo who rules Sugar Rush in Wreck-It Ralph.",

  // IMPOSSIBLE
  "galactus": "Planet-devouring cosmic being in Marvel Comics.",
  "darth-maul": "Horned, double-saber Sith of The Phantom Menace.",
  "kylo-ren": "Masked Sith of the Star Wars sequel trilogy.",
  "jabba-the-hutt": "Sluglike crime lord in Return of the Jedi.",
  "the-balrog": "Fiery demon Gandalf fights in Lord of the Rings.",
  "bellatrix-lestrange": "Deranged Death Eater in Harry Potter.",
  "dolores-umbridge": "Toad-like Hogwarts tyrant in Harry Potter.",
  "sephiroth": "One-winged swordsman villain of Final Fantasy VII.",
  "pyramid-head": "Metal-helmed monster of the Silent Hill games.",
  "bill-cipher": "Triangular dream demon in Gravity Falls.",
  "hexxus": "Pollution demon in the 1992 film FernGully.",
  "ernesto-de-la-cruz": "Singer who poisons Hector in Pixar's Coco.",
  "the-other-mother": "Button-eyed Beldam villain of Coraline (2009).",
  "rasputin": "Undead sorcerer in the animated film Anastasia.",
  "governor-ratcliffe": "Gold-greedy villain of Disney's Pocahontas.",
  "tamatoa": "Treasure-hoarding giant crab in Disney's Moana.",
  "bellwether": "Sheep mastermind behind the plot in Zootopia.",
  "prince-hans": "Betraying prince villain of Disney's Frozen.",
  "anton-chigurh": "Coin-flipping hitman of No Country for Old Men.",
  "immortan-joe": "Masked warlord of Mad Max: Fury Road.",
  "hans-gruber": "Suave thief villain of Die Hard (1988).",
  "mr-hyde": "Dr. Jekyll's monstrous alter ego by Stevenson.",
  "queen-of-hearts": "Head-chopping tyrant of Alice in Wonderland.",
  "jadis-the-white-witch": "Eternal-winter witch of Narnia.",
  "moriarty": "Sherlock Holmes' criminal-mastermind nemesis.",
};
