// E188 «Guess the Villain by Emoji 2» — 100 villains · 25/tier
// VO: sfx/e188-<id>.wav
// FAIRNESS: every clue = 2 single-codepoint emoji signalling the villain's franchise/power/signature prop.
// No two items share the same unordered emoji SET; no title/id overlaps E154 (villainEmojiData.js).
export const VILLAIN_EMOJI_2 = [
  // ===== EASY (25) — globally famous =====
  { id: "megatron", title: "Megatron", emojis: "🤖⚙", level: "easy" },
  { id: "shredder", title: "Shredder", emojis: "🥷🔪", level: "easy" },
  { id: "skeletor", title: "Skeletor", emojis: "💀🗡", level: "easy" },
  { id: "frieza", title: "Frieza", emojis: "👽💥", level: "easy" },
  { id: "lex-luthor", title: "Lex Luthor", emojis: "🧠🦹", level: "easy" },
  { id: "doctor-doom", title: "Doctor Doom", emojis: "🤖👑", level: "easy" },
  { id: "evil-queen", title: "The Evil Queen", emojis: "🍎👑", level: "easy" },
  { id: "mr-burns", title: "Mr. Burns", emojis: "💰☢", level: "easy" },
  { id: "plankton", title: "Plankton", emojis: "🦠🍔", level: "easy" },
  { id: "godzilla", title: "Godzilla", emojis: "🦖⚡", level: "easy" },
  { id: "scorpion", title: "Scorpion", emojis: "🦂🔥", level: "easy" },
  { id: "sub-zero", title: "Sub-Zero", emojis: "🧊👊", level: "easy" },
  { id: "syndrome", title: "Syndrome", emojis: "🦸🚀", level: "easy" },
  { id: "emperor-zurg", title: "Emperor Zurg", emojis: "🚀👾", level: "easy" },
  { id: "gargamel", title: "Gargamel", emojis: "🧙🐈", level: "easy" },
  { id: "heisenberg", title: "Heisenberg", emojis: "🧪🎩", level: "easy" },
  { id: "diablo", title: "Diablo", emojis: "😈🔥", level: "easy" },
  { id: "mojo-jojo", title: "Mojo Jojo", emojis: "🐒🧠", level: "easy" },
  { id: "predator", title: "The Predator", emojis: "🌀🗡", level: "easy" },
  { id: "te-ka", title: "Te Kā", emojis: "🌋👿", level: "easy" },
  { id: "oogie-boogie", title: "Oogie Boogie", emojis: "🎲🐛", level: "easy" },
  { id: "azula", title: "Azula", emojis: "🔥⚡", level: "easy" },
  { id: "negan", title: "Negan", emojis: "⚾🩸", level: "easy" },
  { id: "shan-yu", title: "Shan Yu", emojis: "🦅⚔", level: "easy" },
  { id: "cersei-lannister", title: "Cersei Lannister", emojis: "🍷👑", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "lord-farquaad", title: "Lord Farquaad", emojis: "👑📏", level: "medium" },
  { id: "mysterio", title: "Mysterio", emojis: "🔮🌫", level: "medium" },
  { id: "kingpin", title: "Kingpin", emojis: "🕴💰", level: "medium" },
  { id: "deathstroke", title: "Deathstroke", emojis: "🗡👁", level: "medium" },
  { id: "darkseid", title: "Darkseid", emojis: "🌌👊", level: "medium" },
  { id: "the-nun", title: "The Nun", emojis: "🙏👹", level: "medium" },
  { id: "pinhead", title: "Pinhead", emojis: "📌💀", level: "medium" },
  { id: "krampus", title: "Krampus", emojis: "⛓😈", level: "medium" },
  { id: "slender-man", title: "Slender Man", emojis: "👤🌲", level: "medium" },
  { id: "audrey-ii", title: "Audrey II", emojis: "🪴🩸", level: "medium" },
  { id: "count-olaf", title: "Count Olaf", emojis: "🎭👁", level: "medium" },
  { id: "arthas", title: "Arthas", emojis: "❄👑", level: "medium" },
  { id: "wesker", title: "Albert Wesker", emojis: "🕶🧬", level: "medium" },
  { id: "dio-brando", title: "Dio Brando", emojis: "🧛⏰", level: "medium" },
  { id: "light-yagami", title: "Light Yagami", emojis: "📓💀", level: "medium" },
  { id: "orochimaru", title: "Orochimaru", emojis: "🐍🧪", level: "medium" },
  { id: "hela", title: "Hela", emojis: "🦌💀", level: "medium" },
  { id: "mor-du", title: "Mor'du", emojis: "🐻🏹", level: "medium" },
  { id: "shao-kahn", title: "Shao Kahn", emojis: "💀🔨", level: "medium" },
  { id: "yokai", title: "Yokai", emojis: "🎭🔬", level: "medium" },
  { id: "count-dooku", title: "Count Dooku", emojis: "⚡🗡", level: "medium" },
  { id: "general-grievous", title: "General Grievous", emojis: "🤖⚔", level: "medium" },
  { id: "president-snow", title: "President Snow", emojis: "🌹💊", level: "medium" },
  { id: "kaa", title: "Kaa", emojis: "🐍😵", level: "medium" },
  { id: "lord-business", title: "Lord Business", emojis: "🧱🎩", level: "medium" },

  // ===== HARD (25) =====
  { id: "ozai", title: "Fire Lord Ozai", emojis: "🔥👑", level: "hard" },
  { id: "ridley", title: "Ridley", emojis: "🐉🚀", level: "hard" },
  { id: "kefka", title: "Kefka", emojis: "🤡🌍", level: "hard" },
  { id: "griffith", title: "Griffith", emojis: "🥚🗡", level: "hard" },
  { id: "all-for-one", title: "All For One", emojis: "🫁🦹", level: "hard" },
  { id: "shigaraki", title: "Tomura Shigaraki", emojis: "✋💀", level: "hard" },
  { id: "muzan", title: "Muzan Kibutsuji", emojis: "🌙🩸", level: "hard" },
  { id: "aizen", title: "Sosuke Aizen", emojis: "👓⚔", level: "hard" },
  { id: "nemesis", title: "Nemesis", emojis: "🧟🚀", level: "hard" },
  { id: "the-thing", title: "The Thing", emojis: "🧬👽", level: "hard" },
  { id: "sabretooth", title: "Sabretooth", emojis: "🐾🗡", level: "hard" },
  { id: "juggernaut", title: "Juggernaut", emojis: "🪖💥", level: "hard" },
  { id: "bullseye", title: "Bullseye", emojis: "🎯🔪", level: "hard" },
  { id: "kang", title: "Kang the Conqueror", emojis: "⏳👑", level: "hard" },
  { id: "chernabog", title: "Chernabog", emojis: "🦇🌋", level: "hard" },
  { id: "horned-king", title: "The Horned King", emojis: "💀👑", level: "hard" },
  { id: "ratigan", title: "Professor Ratigan", emojis: "🐀🎩", level: "hard" },
  { id: "madam-mim", title: "Madam Mim", emojis: "🧙🐉", level: "hard" },
  { id: "sid-phillips", title: "Sid Phillips", emojis: "🧨🧸", level: "hard" },
  { id: "the-coachman", title: "The Coachman", emojis: "🫏🚬", level: "hard" },
  { id: "stromboli", title: "Stromboli", emojis: "🎪🧵", level: "hard" },
  { id: "headless-horseman", title: "The Headless Horseman", emojis: "🎃🐎", level: "hard" },
  { id: "pazuzu", title: "Pazuzu", emojis: "🛏😈", level: "hard" },
  { id: "kayako", title: "Kayako", emojis: "👻🩸", level: "hard" },
  { id: "annie-wilkes", title: "Annie Wilkes", emojis: "🔨🛏", level: "hard" },

  // ===== IMPOSSIBLE (25) — deep cuts fans still recognize =====
  { id: "randall-flagg", title: "Randall Flagg", emojis: "🌾😈", level: "impossible" },
  { id: "the-lich", title: "The Lich", emojis: "☠🐌", level: "impossible" },
  { id: "aku", title: "Aku", emojis: "👹🌀", level: "impossible" },
  { id: "vilgax", title: "Vilgax", emojis: "🦑🚀", level: "impossible" },
  { id: "mumm-ra", title: "Mumm-Ra", emojis: "🏺🔮", level: "impossible" },
  { id: "hordak", title: "Hordak", emojis: "🦇⚙", level: "impossible" },
  { id: "gmork", title: "Gmork", emojis: "🐺🌫", level: "impossible" },
  { id: "grand-high-witch", title: "The Grand High Witch", emojis: "🧹🐭", level: "impossible" },
  { id: "miss-trunchbull", title: "Miss Trunchbull", emojis: "🔨🏫", level: "impossible" },
  { id: "child-catcher", title: "The Child Catcher", emojis: "🍭🕸", level: "impossible" },
  { id: "king-dice", title: "King Dice", emojis: "🎲🎩", level: "impossible" },
  { id: "the-devil", title: "The Devil", emojis: "😈🎰", level: "impossible" },
  { id: "andrew-ryan", title: "Andrew Ryan", emojis: "🌊🏛", level: "impossible" },
  { id: "handsome-jack", title: "Handsome Jack", emojis: "🎭🔫", level: "impossible" },
  { id: "dr-wily", title: "Dr. Wily", emojis: "🤖🔧", level: "impossible" },
  { id: "liquid-snake", title: "Liquid Snake", emojis: "🐍🧬", level: "impossible" },
  { id: "aloysius-ohare", title: "Aloysius O'Hare", emojis: "💨💰", level: "impossible" },
  { id: "chef-skinner", title: "Chef Skinner", emojis: "🍳🐀", level: "impossible" },
  { id: "rourke", title: "Commander Rourke", emojis: "💎🔫", level: "impossible" },
  { id: "madame-medusa", title: "Madame Medusa", emojis: "💎🐊", level: "impossible" },
  { id: "lord-shen", title: "Lord Shen", emojis: "🦚🎆", level: "impossible" },
  { id: "tai-lung", title: "Tai Lung", emojis: "🐆👊", level: "impossible" },
  { id: "kai", title: "Kai", emojis: "🐂🌀", level: "impossible" },
  { id: "general-mandible", title: "General Mandible", emojis: "🐜⚔", level: "impossible" },
  { id: "soto", title: "Soto", emojis: "🐅❄", level: "impossible" },
];
