// E207 «Guess the Villain by Emoji 3» — 100 villains · 25/tier
// VO: sfx/e207-<id>.wav
// FAIRNESS: every clue = 2 single-codepoint emoji signalling the villain's franchise/power/signature prop.
// No two items share the same unordered emoji SET; no title/id overlaps E154 (villainEmojiData.js) or E188 (villainEmoji2Data.js).
export const VILLAIN_EMOJI_3 = [
  // ===== EASY (25) — globally famous =====
  { id: "skynet", title: "Skynet", emojis: "🤖☢", level: "easy" },
  { id: "carnage", title: "Carnage", emojis: "🩸🕷", level: "easy" },
  { id: "mystique", title: "Mystique", emojis: "🦎🧬", level: "easy" },
  { id: "apocalypse", title: "Apocalypse", emojis: "⚔🌍", level: "easy" },
  { id: "killmonger", title: "Killmonger", emojis: "🐆⚔", level: "easy" },
  { id: "megan", title: "M3GAN", emojis: "🤖🎀", level: "easy" },
  { id: "freddy-fazbear", title: "Freddy Fazbear", emojis: "🐻🕐", level: "easy" },
  { id: "general-zod", title: "General Zod", emojis: "🌍👊", level: "easy" },
  { id: "doomsday", title: "Doomsday", emojis: "👹💥", level: "easy" },
  { id: "brainiac", title: "Brainiac", emojis: "🧠🛸", level: "easy" },
  { id: "starscream", title: "Starscream", emojis: "✈🤖", level: "easy" },
  { id: "cobra-commander", title: "Cobra Commander", emojis: "🐍🎖", level: "easy" },
  { id: "vulture", title: "Vulture", emojis: "🦅🛠", level: "easy" },
  { id: "electro", title: "Electro", emojis: "⚡🕸", level: "easy" },
  { id: "sandman", title: "Sandman", emojis: "🏖👊", level: "easy" },
  { id: "lizard", title: "The Lizard", emojis: "🦎🧪", level: "easy" },
  { id: "giovanni", title: "Giovanni", emojis: "💼🐈", level: "easy" },
  { id: "alien-queen", title: "Alien Queen", emojis: "👽👑", level: "easy" },
  { id: "barbossa", title: "Captain Barbossa", emojis: "💰🦜", level: "easy" },
  { id: "nurse-ratched", title: "Nurse Ratched", emojis: "💊🏥", level: "easy" },
  { id: "majin-buu", title: "Majin Buu", emojis: "👹🍬", level: "easy" },
  { id: "cell", title: "Cell", emojis: "🧬👹", level: "easy" },
  { id: "madara-uchiha", title: "Madara Uchiha", emojis: "🌙👁", level: "easy" },
  { id: "big-brother", title: "Big Brother", emojis: "👁📺", level: "easy" },
  { id: "king-k-rool", title: "King K. Rool", emojis: "👑🐊", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "unicron", title: "Unicron", emojis: "🪐👹", level: "medium" },
  { id: "doofenshmirtz", title: "Dr. Doofenshmirtz", emojis: "🧪🏙", level: "medium" },
  { id: "sheriff-of-nottingham", title: "Sheriff of Nottingham", emojis: "🐺💰", level: "medium" },
  { id: "broly", title: "Broly", emojis: "💚💥", level: "medium" },
  { id: "pain-nagato", title: "Pain (Nagato)", emojis: "🌧👁", level: "medium" },
  { id: "m-bison", title: "M. Bison", emojis: "👊🎖", level: "medium" },
  { id: "shang-tsung", title: "Shang Tsung", emojis: "👻🔥", level: "medium" },
  { id: "sigma", title: "Sigma", emojis: "🤖👁", level: "medium" },
  { id: "ghetsis", title: "Ghetsis", emojis: "🐉🏰", level: "medium" },
  { id: "cyrus", title: "Cyrus", emojis: "🌌⏳", level: "medium" },
  { id: "wheatley", title: "Wheatley", emojis: "🤖🍰", level: "medium" },
  { id: "springtrap", title: "Springtrap", emojis: "🐰🔥", level: "medium" },
  { id: "pumpkinhead", title: "Pumpkinhead", emojis: "🎃👹", level: "medium" },
  { id: "grindelwald", title: "Grindelwald", emojis: "🪄⚡", level: "medium" },
  { id: "witch-king", title: "The Witch-king", emojis: "👑🦇", level: "medium" },
  { id: "iago", title: "Iago", emojis: "👂🗡", level: "medium" },
  { id: "fagin", title: "Fagin", emojis: "🧢💰", level: "medium" },
  { id: "long-john-silver", title: "Long John Silver", emojis: "🦜🗺", level: "medium" },
  { id: "snidely-whiplash", title: "Snidely Whiplash", emojis: "🚂🎩", level: "medium" },
  { id: "lady-tremaine", title: "Lady Tremaine", emojis: "🐈👠", level: "medium" },
  { id: "boris-badenov", title: "Boris Badenov", emojis: "🕵💣", level: "medium" },
  { id: "vaas-montenegro", title: "Vaas Montenegro", emojis: "🌴🔪", level: "medium" },
  { id: "pagan-min", title: "Pagan Min", emojis: "👑🌸", level: "medium" },
  { id: "meruem", title: "Meruem", emojis: "👑🐜", level: "medium" },
  { id: "johan-liebert", title: "Johan Liebert", emojis: "🩺😈", level: "medium" },

  // ===== HARD (25) =====
  { id: "mundus", title: "Mundus", emojis: "😈⚡", level: "hard" },
  { id: "yhwach", title: "Yhwach", emojis: "🌌🩸", level: "hard" },
  { id: "diavolo", title: "Diavolo", emojis: "🖤⏳", level: "hard" },
  { id: "yoshikage-kira", title: "Yoshikage Kira", emojis: "👊💎", level: "hard" },
  { id: "gilgamesh", title: "Gilgamesh", emojis: "👑🗡", level: "hard" },
  { id: "alucard", title: "Alucard", emojis: "🧛🩸", level: "hard" },
  { id: "zamasu", title: "Zamasu", emojis: "🌌⚡", level: "hard" },
  { id: "overhaul", title: "Overhaul", emojis: "💊🩸", level: "hard" },
  { id: "dabi", title: "Dabi", emojis: "🔥🖤", level: "hard" },
  { id: "obito-uchiha", title: "Obito Uchiha", emojis: "🌀👁", level: "hard" },
  { id: "doflamingo", title: "Doflamingo", emojis: "🦩🧵", level: "hard" },
  { id: "big-mom", title: "Big Mom", emojis: "🍰👑", level: "hard" },
  { id: "enel", title: "Enel", emojis: "⚡👁", level: "hard" },
  { id: "kaido", title: "Kaido", emojis: "🐉🍶", level: "hard" },
  { id: "crocodile", title: "Sir Crocodile", emojis: "🐊🏜", level: "hard" },
  { id: "napoleon-pig", title: "Napoleon the Pig", emojis: "🐖👑", level: "hard" },
  { id: "count-orlok", title: "Count Orlok", emojis: "🧛🐀", level: "hard" },
  { id: "baba-yaga", title: "Baba Yaga", emojis: "🏚🐔", level: "hard" },
  { id: "zarbon", title: "Zarbon", emojis: "💄🦂", level: "hard" },
  { id: "ares-gow", title: "Ares", emojis: "🗡🔥", level: "hard" },
  { id: "the-kurgan", title: "The Kurgan", emojis: "🗡🦴", level: "hard" },
  { id: "the-governor", title: "The Governor", emojis: "🔫👁", level: "hard" },
  { id: "king-ghidorah", title: "King Ghidorah", emojis: "🐉⚡", level: "hard" },
  { id: "rita-repulsa", title: "Rita Repulsa", emojis: "👹🪄", level: "hard" },
  { id: "lord-zedd", title: "Lord Zedd", emojis: "💀🦂", level: "hard" },

  // ===== IMPOSSIBLE (25) — deep cuts fans still recognize =====
  { id: "ivan-ooze", title: "Ivan Ooze", emojis: "🧪🦠", level: "impossible" },
  { id: "grendel", title: "Grendel", emojis: "👹🌊", level: "impossible" },
  { id: "fenrir-greyback", title: "Fenrir Greyback", emojis: "🐺🦷", level: "impossible" },
  { id: "salazar-slytherin", title: "Salazar Slytherin", emojis: "🐍🖋", level: "impossible" },
  { id: "snoke", title: "Snoke", emojis: "🌌🖤", level: "impossible" },
  { id: "darth-nihilus", title: "Darth Nihilus", emojis: "🖤🕳", level: "impossible" },
  { id: "xemnas", title: "Xemnas", emojis: "🌑💔", level: "impossible" },
  { id: "majora", title: "Majora", emojis: "🎭🌙", level: "impossible" },
  { id: "vaati", title: "Vaati", emojis: "🌪👁", level: "impossible" },
  { id: "zant", title: "Zant", emojis: "👑🌀", level: "impossible" },
  { id: "andross", title: "Andross", emojis: "🧠🐵", level: "impossible" },
  { id: "neo-cortex", title: "Dr. Neo Cortex", emojis: "🧪🧠", level: "impossible" },
  { id: "uka-uka", title: "Uka Uka", emojis: "🎭👹", level: "impossible" },
  { id: "nightmare-kirby", title: "Nightmare", emojis: "🌑😈", level: "impossible" },
  { id: "dark-matter-kirby", title: "Dark Matter", emojis: "🌑👁", level: "impossible" },
  { id: "marx", title: "Marx", emojis: "🤡⭐", level: "impossible" },
  { id: "king-boo", title: "King Boo", emojis: "👑👻", level: "impossible" },
  { id: "wart", title: "Wart", emojis: "🐸💣", level: "impossible" },
  { id: "tabuu", title: "Tabuu", emojis: "🪽🖤", level: "impossible" },
  { id: "mother-brain", title: "Mother Brain", emojis: "🧠🤖", level: "impossible" },
  { id: "sa-x", title: "SA-X", emojis: "👽🧊", level: "impossible" },
  { id: "chaos-sonic", title: "Chaos", emojis: "💧👹", level: "impossible" },
  { id: "metal-sonic", title: "Metal Sonic", emojis: "⚙🦔", level: "impossible" },
  { id: "naraku", title: "Naraku", emojis: "🕷😈", level: "impossible" },
  { id: "porky-minch", title: "Porky Minch", emojis: "🐷🤖", level: "impossible" },
];
