// E188 villain-emoji facts — one true <=70-char fact per villain, shown on reveal.
// VO: sfx/e188-<id>.wav
export const VILLAIN_EMOJI_2_FACTS = {
  // EASY
  "megatron": "Tyrannical leader of the Decepticons in Transformers.",
  "shredder": "Bladed archenemy of the Teenage Mutant Ninja Turtles.",
  "skeletor": "Skull-faced foe of He-Man on Eternia.",
  "frieza": "Planet-destroying galactic tyrant of Dragon Ball Z.",
  "lex-luthor": "Superman's genius, power-hungry archenemy.",
  "doctor-doom": "Armored monarch who battles the Fantastic Four.",
  "evil-queen": "Snow White's poisoned-apple stepmother.",
  "mr-burns": "Greedy nuclear-plant owner in The Simpsons.",
  "plankton": "Tiny schemer chasing the Krabby Patty formula.",
  "godzilla": "Atomic-breathing kaiju that levels cities.",
  "scorpion": "Hellfire ninja of the Mortal Kombat games.",
  "sub-zero": "Ice-wielding ninja of the Mortal Kombat games.",
  "syndrome": "Fan-turned-foe supervillain of The Incredibles.",
  "emperor-zurg": "Buzz Lightyear's evil archenemy in Toy Story.",
  "gargamel": "Wizard who hunts the Smurfs with his cat.",
  "heisenberg": "Walter White's meth-cooking alter ego.",
  "diablo": "The Lord of Terror in the Diablo games.",
  "mojo-jojo": "Simian criminal genius foe of the Powerpuff Girls.",
  "predator": "Invisible alien trophy hunter of the jungle.",
  "te-ka": "Lava demon that battles Moana in the ocean.",
  "oogie-boogie": "Bug-filled boogeyman of Halloween Town.",
  "azula": "Fire-and-lightning princess of Avatar.",
  "negan": "Barbed-bat tyrant of The Walking Dead.",
  "shan-yu": "Ruthless leader of the Huns in Mulan.",
  "cersei-lannister": "Ruthless scheming queen of Game of Thrones.",
  // MEDIUM
  "lord-farquaad": "Pint-sized ruler of Duloc in Shrek.",
  "mysterio": "Fishbowl-helmed illusionist foe of Spider-Man.",
  "kingpin": "Crime boss who rules New York's underworld.",
  "deathstroke": "One-eyed mercenary who fights the Teen Titans.",
  "darkseid": "Tyrant of Apokolips seeking the Anti-Life Equation.",
  "the-nun": "Demon Valak from The Conjuring films.",
  "pinhead": "Cenobite leader of the Hellraiser films.",
  "krampus": "Horned demon who punishes naughty children.",
  "slender-man": "Faceless suited figure who stalks the woods.",
  "audrey-ii": "Man-eating plant of Little Shop of Horrors.",
  "count-olaf": "Disguise-loving villain of A Series of Unfortunate Events.",
  "arthas": "The Lich King who rules the Scourge in Warcraft.",
  "wesker": "Sunglasses-wearing schemer of Resident Evil.",
  "dio-brando": "Time-stopping vampire of JoJo's Bizarre Adventure.",
  "light-yagami": "Kira, who kills with the Death Note.",
  "orochimaru": "Snake-obsessed rogue ninja of Naruto.",
  "hela": "Marvel's antlered goddess of death.",
  "mor-du": "Giant cursed bear hunted in Brave.",
  "shao-kahn": "Warhammer-wielding emperor of Mortal Kombat.",
  "yokai": "Kabuki-masked microbot villain of Big Hero 6.",
  "count-dooku": "Sith lord and fallen Jedi of Star Wars.",
  "general-grievous": "Lightsaber-collecting cyborg general of Star Wars.",
  "president-snow": "Tyrant president of Panem in The Hunger Games.",
  "kaa": "Hypnotic python of The Jungle Book.",
  "lord-business": "Uptight ruler who wields the Kragle in The Lego Movie.",
  // HARD
  "ozai": "Fire Lord and Azula's father in Avatar.",
  "ridley": "Space-dragon nemesis of Samus in Metroid.",
  "kefka": "Mad clown mage who wrecks the world in Final Fantasy VI.",
  "griffith": "Betrayer of the Band of the Hawk in Berserk.",
  "all-for-one": "Quirk-stealing archvillain of My Hero Academia.",
  "shigaraki": "Decay-touch villain of My Hero Academia.",
  "muzan": "Demon king who hunts the slayers in Demon Slayer.",
  "aizen": "Betrayer captain and mastermind of Bleach.",
  "nemesis": "Rocket-toting Tyrant that stalks Jill in Resident Evil.",
  "the-thing": "Shape-shifting alien of John Carpenter's horror film.",
  "sabretooth": "Feral, clawed healing villain of the X-Men.",
  "juggernaut": "Unstoppable helmeted powerhouse of the X-Men.",
  "bullseye": "Never-miss assassin who battles Daredevil.",
  "kang": "Time-traveling conqueror of the Marvel multiverse.",
  "chernabog": "Winged demon atop Bald Mountain in Fantasia.",
  "horned-king": "Undead sorcerer of Disney's The Black Cauldron.",
  "ratigan": "Rat criminal genius of The Great Mouse Detective.",
  "madam-mim": "Shapeshifting witch who duels Merlin in The Sword in the Stone.",
  "sid-phillips": "Toy-torturing kid next door in Toy Story.",
  "the-coachman": "Villain who turns boys into donkeys in Pinocchio.",
  "stromboli": "Puppeteer who cages Pinocchio for profit.",
  "headless-horseman": "Ghostly rider who hunts in Sleepy Hollow.",
  "pazuzu": "Demon that possesses a girl in The Exorcist.",
  "kayako": "Vengeful ghost of The Grudge.",
  "annie-wilkes": "Obsessed 'number one fan' of Misery.",
  // IMPOSSIBLE
  "randall-flagg": "Recurring demon-man of Stephen King's novels.",
  "the-lich": "Ancient undead embodiment of evil in Adventure Time.",
  "aku": "Shape-shifting demon overlord of Samurai Jack.",
  "vilgax": "Alien warlord who hunts the Omnitrix in Ben 10.",
  "mumm-ra": "Undead mummy sorcerer of ThunderCats.",
  "hordak": "Cybernetic leader of the Horde in She-Ra.",
  "gmork": "Wolf servant of the Nothing in The NeverEnding Story.",
  "grand-high-witch": "Child-hating witch leader in Roald Dahl's The Witches.",
  "miss-trunchbull": "Tyrannical child-tossing headmistress of Matilda.",
  "child-catcher": "Kidnapper who lures kids in Chitty Chitty Bang Bang.",
  "king-dice": "The Devil's dapper right-hand man in Cuphead.",
  "the-devil": "Soul-collecting Devil of the game Cuphead.",
  "andrew-ryan": "Founder of the undersea city of Rapture in BioShock.",
  "handsome-jack": "Tyrannical masked CEO villain of Borderlands 2.",
  "dr-wily": "Robot-master creator who battles Mega Man.",
  "liquid-snake": "Cloned twin who leads a revolt in Metal Gear Solid.",
  "aloysius-ohare": "Air-selling businessman in The Lorax.",
  "chef-skinner": "Scheming chef who runs Gusteau's in Ratatouille.",
  "rourke": "Mercenary who betrays the crew in Atlantis.",
  "madame-medusa": "Diamond-hunting pawnshop villain of The Rescuers.",
  "lord-shen": "Peacock warlord with cannons in Kung Fu Panda 2.",
  "tai-lung": "Snow leopard who seeks the scroll in Kung Fu Panda.",
  "kai": "Spirit-warrior bull villain of Kung Fu Panda 3.",
  "general-mandible": "Ant general plotting a coup in Antz.",
  "soto": "Sabertooth pack leader in Ice Age.",
};
