// E236 «Guess the Villain by Emoji» — facts for VILLAIN_EMOJI4 (villainEmoji4Data.js). One TRUE fact per id, <=70 chars.
export const VILLAIN_EMOJI4_FACTS = {
  "night-king": "Night King leads the White Walkers in Game of Thrones.",
  "homelander": "Homelander is The Boys' corrupt Supe with laser-vision eyes.",
  "ryuk": "Ryuk is the death god who drops the Death Note in the manga.",
  "vecna": "Vecna stalks Hawkins in Netflix's Stranger Things season 4.",
  "demogorgon": "Demogorgon hunts from the Upside Down in Stranger Things.",
  "sukuna": "Sukuna is the King of Curses in Jujutsu Kaisen.",
  "blofeld": "Blofeld heads SPECTRE and pets a white cat in Bond films.",
  "joffrey-baratheon": "Joffrey Baratheon is the cruel boy-king in Game of Thrones.",
  "front-man": "Front Man oversees the deadly games in Squid Game.",
  "ras-al-ghul": "Ra's al Ghul leads the League of Assassins in Batman lore.",
  "phantom-of-the-opera": "The Phantom haunts the Paris Opera House in Leroux's tale.",
  "baron-zemo": "Baron Zemo wears a purple mask in Marvel's Civil War era.",
  "taskmaster": "Taskmaster copies any fighting move he sees, in Marvel comics.",
  "mandarin": "Mandarin wields ten power rings in Marvel's Iron Man lore.",
  "agatha-harkness": "Agatha Harkness is the witch behind WandaVision's twist.",
  "moff-gideon": "Moff Gideon wields the Darksaber in The Mandalorian.",
  "akaza": "Akaza is an Upper Moon demon in Demon Slayer.",
  "reverse-flash": "Reverse-Flash is Eobard Thawne, The Flash's speedster foe.",
  "steppenwolf": "Steppenwolf invades Earth in Zack Snyder's Justice League.",
  "vector": "Vector is Gru's rival with a fish-shaped gun in Despicable Me.",
  "gus-fring": "Gus Fring runs a meth empire behind Los Pollos Hermanos.",
  "tyler-durden": "Tyler Durden starts Fight Club in Chuck Palahniuk's novel.",
  "ramsay-bolton": "Ramsay Bolton tortures captives in Game of Thrones.",
  "javert": "Javert relentlessly pursues Valjean in Les Misérables.",
  "black-manta": "Black Manta is Aquaman's helmeted deep-sea nemesis.",

  "littlefinger": "Littlefinger schemes his way up in Game of Thrones.",
  "mahito": "Mahito reshapes human souls in Jujutsu Kaisen.",
  "hisoka": "Hisoka fights only for thrills in Hunter x Hunter.",
  "prince-charming": "Prince Charming rules Far Far Away in Shrek 2 and 3.",
  "fairy-godmother": "The Fairy Godmother sells potions in Shrek's Far Far Away.",
  "nigel": "Nigel is the villainous cockatoo in the animated film Rio.",
  "drago-bludvist": "Drago Bludvist commands a dragon army in HTTYD 2.",
  "el-macho": "El Macho fakes his own death in Despicable Me 2.",
  "balthazar-bratt": "Balthazar Bratt is an '80s star turned villain in Despicable Me 3.",
  "stinky-pete": "Stinky Pete schemes to reach a museum in Toy Story 2.",
  "bill-sikes": "Bill Sikes is the brutal criminal in Dickens' Oliver Twist.",
  "dr-no": "Dr. No has metal hands in the first James Bond film.",
  "auric-goldfinger": "Auric Goldfinger schemes to raid Fort Knox's gold in Bond.",
  "kronos": "Kronos is the Titan of time in Percy Jackson.",
  "mrs-coulter": "Mrs. Coulter has a golden monkey daemon in His Dark Materials.",
  "judge-turpin": "Judge Turpin wrongs Sweeney Todd in the Sondheim musical.",
  "zoom": "Zoom is a rival speedster villain on The Flash TV series.",
  "ocean-master": "Ocean Master is Aquaman's half-brother rival, Orm.",
  "screenslaver": "Screenslaver hypnotizes people via screens in Incredibles 2.",
  "abomination": "Abomination is Emil Blonsky, the Hulk's monstrous foe.",
  "ronan-the-accuser": "Ronan the Accuser wields a cosmic hammer in Guardians of the Galaxy.",
  "surtur": "Surtur is the fire demon who destroys Asgard in Thor: Ragnarok.",
  "chick-hicks": "Chick Hicks cheats to win races in the film Cars.",
  "captain-ginyu": "Captain Ginyu swaps bodies with his Change move in Dragon Ball.",
  "luke-castellan": "Luke Castellan hosts the Titan Kronos in Percy Jackson.",

  "ultimecia": "Ultimecia seeks Time Compression in Final Fantasy VIII.",
  "jenova": "Jenova is the alien source of Sephiroth's power in FF VII.",
  "kuja": "Kuja is a vain Genome sorcerer villain in Final Fantasy IX.",
  "exdeath": "Exdeath is a tree-born fiend of the Void in Final Fantasy V.",
  "seymour-guado": "Seymour Guado seeks death as a summoner in Final Fantasy X.",
  "frank-fontaine": "Frank Fontaine secretly rules Rapture in BioShock.",
  "sofia-lamb": "Sofia Lamb leads a cult in the sequel BioShock 2.",
  "dark-samus": "Dark Samus is Samus's corrupted double in Metroid Prime.",
  "n-gin": "N. Gin is Cortex's rocket-headed scientist in Crash Bandicoot.",
  "salazar": "Ramon Salazar leads Los Illuminados in Resident Evil 4.",
  "infinite": "Infinite wields the Phantom Ruby in Sonic Forces.",
  "envy": "Envy is a shape-shifting Homunculus in Fullmetal Alchemist.",
  "father": "Father created the Homunculi in Fullmetal Alchemist.",
  "chrollo-lucilfer": "Chrollo Lucilfer leads the Phantom Troupe in Hunter x Hunter.",
  "ulquiorra-cifer": "Ulquiorra Cifer is a black-winged Espada in Bleach.",
  "gin-ichimaru": "Gin Ichimaru hides his schemes behind a grin, in Bleach.",
  "enmu": "Enmu traps train riders in dreams in Demon Slayer: Mugen Train.",
  "doma": "Doma is an Upper Moon Two demon in Demon Slayer.",
  "gyutaro": "Gyutaro wields a poisoned sickle in Demon Slayer.",
  "dorian-gray": "Dorian Gray's portrait ages as his soul rots, in Wilde's novel.",
  "grimmel": "Grimmel the Grisly hunts dragons in How to Train Your Dragon 3.",
  "walder-frey": "Walder Frey hosts the Red Wedding in Game of Thrones.",
  "reiner-braun": "Reiner Braun is the Armored Titan in Attack on Titan.",
  "he-who-remains": "He Who Remains created the TVA in Marvel's Loki series.",
  "madame-morrible": "Madame Morrible spins Oz's press in the musical Wicked.",

  "shodan": "SHODAN is the rogue AI antagonist of System Shock.",
  "iblis": "Iblis is the fire half split from Solaris in Sonic '06.",
  "solaris": "Solaris is a god-like time entity in Sonic the Hedgehog (2006).",
  "lust": "Lust is a seductive Homunculus in Fullmetal Alchemist.",
  "obrien": "O'Brien tortures Winston in Orwell's novel 1984.",
  "max-cady": "Max Cady stalks his old defense lawyer in Cape Fear.",
  "lou-bloom": "Lou Bloom films crime scenes for profit in Nightcrawler.",
  "tom-ripley": "Tom Ripley cons and kills in The Talented Mr. Ripley.",
  "general-woundwort": "General Woundwort tyrannizes rabbits in Watership Down.",
  "opal-koboi": "Opal Koboi is a fairy genius villain in Artemis Fowl.",
  "agatha-prenderghast": "Agatha Prenderghast is the vengeful ghost witch in ParaNorman.",
  "rudy": "Rudy is a giant albino dino predator in Ice Age 3.",
  "jack-merridew": "Jack Merridew turns savage as chief in Lord of the Flies.",
  "zeke-yeager": "Zeke Yeager is the Beast Titan in Attack on Titan.",
  "amy-dunne": "Amy Dunne fakes her death to frame her husband in Gone Girl.",
  "trinity-killer": "The Trinity Killer follows a ritual murder cycle in Dexter.",
  "mrs-danvers": "Mrs. Danvers obsesses over the dead Rebecca in du Maurier's novel.",
  "colonel-kurtz": "Colonel Kurtz rules his own jungle outpost in Apocalypse Now.",
  "the-master": "The Master is the Doctor's renegade Time Lord rival in Doctor Who.",
  "davros": "Davros created the Daleks in Doctor Who.",
  "le-chiffre": "Le Chiffre bankrolls terror via poker in Casino Royale.",
  "alec-trevelyan": "Alec Trevelyan is the rogue agent 006 in GoldenEye.",
  "elliot-carver": "Elliot Carver engineers war for ratings in Tomorrow Never Dies.",
  "vandal-savage": "Vandal Savage is an immortal caveman villain in DC Comics.",
  "solomon-grundy": "Solomon Grundy is an undead brute villain in DC Comics.",
};
