// E207 villain-emoji facts — one true <=70-char fact per villain, shown on reveal.
export const VILLAIN_EMOJI_3_FACTS = {
  // EASY
  "skynet": "AI defense network from Terminator that turns on humanity.",
  "carnage": "A red symbiote bonded to serial killer Cletus Kasady.",
  "mystique": "A shape-shifting mutant assassin in Marvel's X-Men.",
  "apocalypse": "The first mutant, an ancient tyrant in X-Men lore.",
  "killmonger": "Erik Killmonger challenges T'Challa for Wakanda's throne.",
  "megan": "An AI android doll turns deadly protector in M3GAN.",
  "freddy-fazbear": "A haunted animatronic bear from Five Nights at Freddy's.",
  "general-zod": "Kryptonian general who conquers Earth in Superman lore.",
  "doomsday": "A monster bred to kill Superman in DC Comics.",
  "brainiac": "A super-intelligent alien who collects shrunken cities.",
  "starscream": "A power-hungry Decepticon jet in Transformers.",
  "cobra-commander": "Leader of the terrorist group Cobra in G.I. Joe.",
  "vulture": "Adrian Toomes flies a scavenger suit against Spider-Man.",
  "electro": "Max Dillon becomes a living bolt of electricity.",
  "sandman": "Flint Marko's body turns to living, shifting sand.",
  "lizard": "Curt Connors mutates into a reptilian Spider-Man foe.",
  "giovanni": "Boss of Team Rocket in the Pokémon games.",
  "alien-queen": "The egg-laying matriarch of the Xenomorph hive.",
  "barbossa": "A cursed pirate captain in Pirates of the Caribbean.",
  "nurse-ratched": "A cold, controlling nurse in Cuckoo's Nest.",
  "majin-buu": "A pink, candy-loving destroyer in Dragon Ball Z.",
  "cell": "A bio-engineered perfect fighter in Dragon Ball Z.",
  "madara-uchiha": "A legendary Uchiha who plots the Infinite Tsukuyomi.",
  "big-brother": "The unseen dictator watching all in Orwell's 1984.",
  "king-k-rool": "Reptilian king of the Kremlings, Donkey Kong's foe.",

  // MEDIUM
  "unicron": "A planet-sized robot god who devours worlds.",
  "doofenshmirtz": "A scheming inventor plotting Tri-State domination.",
  "sheriff-of-nottingham": "A greedy wolf lawman in Disney's Robin Hood.",
  "broly": "The Legendary Super Saiyan with unstoppable rage.",
  "pain-nagato": "Nagato's Six Paths bring 'true peace' through pain.",
  "m-bison": "Dictator of Shadaloo wielding Psycho Power.",
  "shang-tsung": "A soul-stealing sorcerer in Mortal Kombat.",
  "sigma": "A rogue Maverick Hunter leading robot revolts.",
  "ghetsis": "The manipulative leader behind Team Plasma.",
  "cyrus": "Team Galactic's leader who seeks to remake the universe.",
  "wheatley": "A sarcastic AI core who betrays you in Portal 2.",
  "springtrap": "A rotting animatronic suit hiding a killer.",
  "pumpkinhead": "A vengeance demon summoned from a pumpkin patch.",
  "grindelwald": "A dark wizard seeking wizard rule over Muggles.",
  "witch-king": "Leader of the Nazgûl, Sauron's deadliest servant.",
  "iago": "Othello's scheming ensign who plots his downfall.",
  "fagin": "An old thief who trains child pickpockets.",
  "long-john-silver": "A one-legged pirate cook hunting buried gold.",
  "snidely-whiplash": "A villain who ties victims to train tracks.",
  "lady-tremaine": "Cinderella's cruel and jealous stepmother.",
  "boris-badenov": "A bumbling spy scheming against Rocky & Bullwinkle.",
  "vaas-montenegro": "A deranged pirate warlord ruling Far Cry 3's island.",
  "pagan-min": "The flamboyant dictator of Kyrat in Far Cry 4.",
  "meruem": "The genius Chimera Ant King in Hunter x Hunter.",
  "johan-liebert": "A charming yet monstrous serial manipulator.",

  // HARD
  "mundus": "The Demon King ruling the underworld in Devil May Cry.",
  "yhwach": "The Quincy King who threatens to end all worlds.",
  "diavolo": "The unseen boss who erases time itself, in JoJo.",
  "yoshikage-kira": "A serial killer whose hand turns things into bombs.",
  "gilgamesh": "A golden king with infinite weapons in Fate.",
  "alucard": "A powerful vampire servant hunting monsters.",
  "zamasu": "A god who tries to erase humanity in Dragon Ball Super.",
  "overhaul": "A yakuza boss who removes quirks in My Hero Academia.",
  "dabi": "A fire-quirked villain with a burning family secret.",
  "obito-uchiha": "A masked Uchiha manipulating the shinobi world.",
  "doflamingo": "A string-wielding warlord ruling Dressrosa.",
  "big-mom": "A cake-obsessed Yonko pirate empress.",
  "enel": "A lightning god ruling Skypiea in One Piece.",
  "kaido": "The 'strongest creature,' a dragon Yonko.",
  "crocodile": "A sand-powered warlord scheming in Alabasta.",
  "napoleon-pig": "A power-hungry pig dictator in Animal Farm.",
  "count-orlok": "A rat-like vampire spreading plague in Nosferatu.",
  "baba-yaga": "A folklore witch who lives in a hut on chicken legs.",
  "zarbon": "A vain warrior who hides a monstrous form.",
  "ares-gow": "The God of War manipulating Kratos in the game series.",
  "the-kurgan": "An immortal warrior seeking the Prize in Highlander.",
  "the-governor": "A tyrant ruling Woodbury in The Walking Dead.",
  "king-ghidorah": "A three-headed dragon rival to Godzilla.",
  "rita-repulsa": "A space witch who first attacks Earth in Power Rangers.",
  "lord-zedd": "A skeletal emperor of evil in Power Rangers.",

  // IMPOSSIBLE
  "ivan-ooze": "A goo villain freed after 6,000 years in Power Rangers.",
  "grendel": "A monster terrorizing the mead hall in Beowulf.",
  "fenrir-greyback": "A savage werewolf who bites victims for Voldemort.",
  "salazar-slytherin": "A Hogwarts founder who left the Chamber of Secrets.",
  "snoke": "The Supreme Leader of the First Order in Star Wars.",
  "darth-nihilus": "A Sith Lord who devours the Force itself.",
  "xemnas": "The leader of Organization XIII in Kingdom Hearts.",
  "majora": "A cursed mask that brings the moon crashing down.",
  "vaati": "A wind sorcerer who seeks the Triforce in Zelda.",
  "zant": "A usurper king who plunges Hyrule into twilight.",
  "andross": "A mad scientist turned giant brain-monster.",
  "neo-cortex": "A mad scientist who mutates bandicoots.",
  "uka-uka": "An evil mask spirit commanding Cortex.",
  "nightmare-kirby": "A dream demon who corrupts Dream Land's dreams.",
  "dark-matter-kirby": "A shadowy entity that possesses kings and stars.",
  "marx": "A jester who betrays Kirby after granted a wish.",
  "king-boo": "The ghostly ruler of Boos who traps Mario's friends.",
  "wart": "A frog tyrant who outlawed vegetables.",
  "tabuu": "A masked being who shatters the Smash Bros. roster.",
  "mother-brain": "A cybernetic brain commanding the Space Pirates.",
  "sa-x": "A parasite copy of Samus armed with her own weapons.",
  "chaos-sonic": "A watery ancient god awakened by Chaos Emeralds.",
  "metal-sonic": "Dr. Eggman's robotic copy built to outrace Sonic.",
  "naraku": "A shapeshifting demon born of hatred in Inuyasha.",
  "porky-minch": "A cruel boy who becomes an eternal robotic tyrant.",
};
