// E145 «Guess the Weather or Nature Phenomenon by Emoji» — 100 items · 25/tier · clue = plain Unicode emoji (mirrors E125 isEmoji rendering)
// VO: sfx/e145-<id>.wav ("It's <Phenomenon>!"). Single-codepoint emoji only, no FE0F/ZWJ; every set unique; born FAIR.
export const WEATHER_EMOJI = [
  // ===== EASY (25) — everyday weather =====
  { id: "rain", title: "Rain", emojis: "🌧💧", level: "easy" },
  { id: "sunshine", title: "Sunshine", emojis: "☀🕶", level: "easy" },
  { id: "snow", title: "Snow", emojis: "❄☃", level: "easy" },
  { id: "wind", title: "Wind", emojis: "🌬🍃", level: "easy" },
  { id: "thunderstorm", title: "Thunderstorm", emojis: "⛈⚡", level: "easy" },
  { id: "rainbow", title: "Rainbow", emojis: "🌈☔", level: "easy" },
  { id: "cloudy", title: "Cloudy", emojis: "☁⛅", level: "easy" },
  { id: "fog", title: "Fog", emojis: "🌫🌁", level: "easy" },
  { id: "lightning", title: "Lightning", emojis: "⚡🌩", level: "easy" },
  { id: "hail", title: "Hail", emojis: "🌨🧊", level: "easy" },
  { id: "heatwave", title: "Heatwave", emojis: "🌡🔥", level: "easy" },
  { id: "frost", title: "Frost", emojis: "❄🍂", level: "easy" },
  { id: "drizzle", title: "Drizzle", emojis: "🌦💧", level: "easy" },
  { id: "sunrise", title: "Sunrise", emojis: "🌅🐓", level: "easy" },
  { id: "sunset", title: "Sunset", emojis: "🌇🏙", level: "easy" },
  { id: "blizzard", title: "Blizzard", emojis: "❄🌬", level: "easy" },
  { id: "tornado", title: "Tornado", emojis: "🌪🏚", level: "easy" },
  { id: "hurricane", title: "Hurricane", emojis: "🌀🌴", level: "easy" },
  { id: "flood", title: "Flood", emojis: "🌊🏠", level: "easy" },
  { id: "drought", title: "Drought", emojis: "🌵☀", level: "easy" },
  { id: "dew", title: "Dew", emojis: "💧🌿", level: "easy" },
  { id: "monsoon", title: "Monsoon", emojis: "🌧🌴", level: "easy" },
  { id: "mist", title: "Mist", emojis: "🌫🌲", level: "easy" },
  { id: "gale", title: "Gale", emojis: "🌬⛵", level: "easy" },
  { id: "heat", title: "Heat", emojis: "☀🥵", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "aurora", title: "Aurora (Northern Lights)", emojis: "🌌❄", level: "medium" },
  { id: "eclipse", title: "Solar Eclipse", emojis: "🌑☀", level: "medium" },
  { id: "meteor-shower", title: "Meteor Shower", emojis: "🌠✨", level: "medium" },
  { id: "comet", title: "Comet", emojis: "☄🔭", level: "medium" },
  { id: "tsunami", title: "Tsunami", emojis: "🌊🏯", level: "medium" },
  { id: "avalanche", title: "Avalanche", emojis: "🏔❄", level: "medium" },
  { id: "sandstorm", title: "Sandstorm", emojis: "🏜💨", level: "medium" },
  { id: "volcano", title: "Volcanic Eruption", emojis: "🌋🔥", level: "medium" },
  { id: "wildfire", title: "Wildfire", emojis: "🔥🌲", level: "medium" },
  { id: "waterfall", title: "Waterfall", emojis: "⛰💦", level: "medium" },
  { id: "geyser", title: "Geyser", emojis: "♨💦", level: "medium" },
  { id: "whirlpool", title: "Whirlpool", emojis: "🌀🌊", level: "medium" },
  { id: "mirage", title: "Mirage", emojis: "🏜🌴", level: "medium" },
  { id: "earthquake", title: "Earthquake", emojis: "🏚💥", level: "medium" },
  { id: "iceberg", title: "Iceberg", emojis: "🧊🚢", level: "medium" },
  { id: "glacier", title: "Glacier", emojis: "🧊⛰", level: "medium" },
  { id: "downpour", title: "Downpour", emojis: "☔🌧", level: "medium" },
  { id: "sleet", title: "Sleet", emojis: "🌨🌧", level: "medium" },
  { id: "waterspout", title: "Waterspout", emojis: "🌪🌊", level: "medium" },
  { id: "dust-devil", title: "Dust Devil", emojis: "🌵🌀", level: "medium" },
  { id: "landslide", title: "Landslide", emojis: "⛰🪨", level: "medium" },
  { id: "sinkhole", title: "Sinkhole", emojis: "🕳🏠", level: "medium" },
  { id: "quicksand", title: "Quicksand", emojis: "🏜🦴", level: "medium" },
  { id: "tide", title: "Tide", emojis: "🌊🌙", level: "medium" },
  { id: "humidity", title: "Humidity", emojis: "🌡💧", level: "medium" },

  // ===== HARD (25) =====
  { id: "hailstorm", title: "Hailstorm", emojis: "⛈🧊", level: "hard" },
  { id: "typhoon", title: "Typhoon", emojis: "🌀🚢", level: "hard" },
  { id: "solar-flare", title: "Solar Flare", emojis: "☀💥", level: "hard" },
  { id: "rip-current", title: "Rip Current", emojis: "🌊🏖", level: "hard" },
  { id: "sun-dog", title: "Sun Dog", emojis: "☀🐕", level: "hard" },
  { id: "fire-rainbow", title: "Fire Rainbow", emojis: "🌈🔥", level: "hard" },
  { id: "st-elmos-fire", title: "St. Elmo's Fire", emojis: "⚡⛵", level: "hard" },
  { id: "ball-lightning", title: "Ball Lightning", emojis: "⚡🔮", level: "hard" },
  { id: "bioluminescence", title: "Bioluminescence", emojis: "🌊✨", level: "hard" },
  { id: "fog-bow", title: "Fog Bow", emojis: "🌫🌈", level: "hard" },
  { id: "frostbite", title: "Frostbite", emojis: "❄🥶", level: "hard" },
  { id: "permafrost", title: "Permafrost", emojis: "🧊🌲", level: "hard" },
  { id: "haboob", title: "Haboob", emojis: "🏜🌪", level: "hard" },
  { id: "derecho", title: "Derecho", emojis: "💨⛈", level: "hard" },
  { id: "supercell", title: "Supercell", emojis: "⛈🌪", level: "hard" },
  { id: "microburst", title: "Microburst", emojis: "🌩💨", level: "hard" },
  { id: "flash-flood", title: "Flash Flood", emojis: "🌊💨", level: "hard" },
  { id: "whiteout", title: "Whiteout", emojis: "❄🌫", level: "hard" },
  { id: "graupel", title: "Graupel", emojis: "🌨❄", level: "hard" },
  { id: "hoarfrost", title: "Hoarfrost", emojis: "❄🌿", level: "hard" },
  { id: "rime-ice", title: "Rime Ice", emojis: "🧊🌬", level: "hard" },
  { id: "black-ice", title: "Black Ice", emojis: "🧊🚗", level: "hard" },
  { id: "katabatic-wind", title: "Katabatic Wind", emojis: "🏔🌬", level: "hard" },
  { id: "chinook", title: "Chinook Wind", emojis: "🏔🔥", level: "hard" },
  { id: "storm-surge", title: "Storm Surge", emojis: "🌊🏚", level: "hard" },

  // ===== IMPOSSIBLE (25) — rare but real & nameable =====
  { id: "firenado", title: "Fire Whirl (Firenado)", emojis: "🔥🌪", level: "impossible" },
  { id: "brinicle", title: "Brinicle", emojis: "🧊🌊", level: "impossible" },
  { id: "sun-pillar", title: "Sun Pillar", emojis: "☀🌇", level: "impossible" },
  { id: "light-pillar", title: "Light Pillar", emojis: "❄💡", level: "impossible" },
  { id: "moonbow", title: "Moonbow", emojis: "🌙🌈", level: "impossible" },
  { id: "green-flash", title: "Green Flash", emojis: "🌅✨", level: "impossible" },
  { id: "nacreous-clouds", title: "Nacreous Clouds", emojis: "🌈☁", level: "impossible" },
  { id: "noctilucent-clouds", title: "Noctilucent Clouds", emojis: "☁🌌", level: "impossible" },
  { id: "mammatus-clouds", title: "Mammatus Clouds", emojis: "☁🌩", level: "impossible" },
  { id: "lenticular-cloud", title: "Lenticular Cloud", emojis: "☁🛸", level: "impossible" },
  { id: "virga", title: "Virga", emojis: "🌧🏜", level: "impossible" },
  { id: "petrichor", title: "Petrichor", emojis: "🌧🌿", level: "impossible" },
  { id: "diamond-dust", title: "Diamond Dust", emojis: "❄💎", level: "impossible" },
  { id: "snow-roller", title: "Snow Roller", emojis: "☃🌬", level: "impossible" },
  { id: "penitentes", title: "Penitentes", emojis: "🧊☀", level: "impossible" },
  { id: "blood-rain", title: "Blood Rain", emojis: "🌧🩸", level: "impossible" },
  { id: "thundersnow", title: "Thundersnow", emojis: "⛈❄", level: "impossible" },
  { id: "ice-storm", title: "Ice Storm", emojis: "🧊🌧", level: "impossible" },
  { id: "aurora-australis", title: "Aurora Australis", emojis: "🌌🐧", level: "impossible" },
  { id: "zodiacal-light", title: "Zodiacal Light", emojis: "🌌☀", level: "impossible" },
  { id: "sun-halo", title: "Sun Halo", emojis: "🌞⭕", level: "impossible" },
  { id: "airglow", title: "Airglow", emojis: "🌌🌈", level: "impossible" },
  { id: "red-sprite", title: "Red Sprite", emojis: "⚡✨", level: "impossible" },
  { id: "blue-jet", title: "Blue Jet", emojis: "⚡🌌", level: "impossible" },
  { id: "elves-lightning", title: "ELVES (Upper-Atmosphere Ring)", emojis: "⚡🌀", level: "impossible" },
];
