// E209 «Guess the Weather by Emoji 2» — 100 phenomena · 25/tier
// VO: sfx/e209-<id>.wav
export const WEATHER_EMOJI_2 = [
  // ===== EASY (25) =====
  { id: "overcast-sky", title: "Overcast Sky", emojis: "☁🌫", level: "easy" },
  { id: "sun-shower", title: "Sun Shower", emojis: "☀🌧", level: "easy" },
  { id: "snow-flurry", title: "Snow Flurry", emojis: "❄💨", level: "easy" },
  { id: "freezing-rain", title: "Freezing Rain", emojis: "🌧🥶", level: "easy" },
  { id: "cold-front", title: "Cold Front", emojis: "🌡🥶", level: "easy" },
  { id: "warm-front", title: "Warm Front", emojis: "🌡🥵", level: "easy" },
  { id: "snow-squall", title: "Snow Squall", emojis: "❄⛄", level: "easy" },
  { id: "heat-dome", title: "Heat Dome", emojis: "☀🏜", level: "easy" },
  { id: "cold-snap", title: "Cold Snap", emojis: "🥶🌬", level: "easy" },
  { id: "dust-storm", title: "Dust Storm", emojis: "🏜🌬", level: "easy" },
  { id: "windstorm", title: "Windstorm", emojis: "🌬🏚", level: "easy" },
  { id: "rain-shower", title: "Rain Shower", emojis: "☂🌧", level: "easy" },
  { id: "snowstorm", title: "Snowstorm", emojis: "❄🌀", level: "easy" },
  { id: "cloudburst", title: "Cloudburst", emojis: "☁💦", level: "easy" },
  { id: "full-moon", title: "Full Moon", emojis: "🌕✨", level: "easy" },
  { id: "new-moon", title: "New Moon", emojis: "🌑🌌", level: "easy" },
  { id: "starry-sky", title: "Starry Sky", emojis: "🌌⭐", level: "easy" },
  { id: "cumulus-cloud", title: "Cumulus Cloud", emojis: "⛅☀", level: "easy" },
  { id: "cirrus-cloud", title: "Cirrus Cloud", emojis: "☁🌬", level: "easy" },
  { id: "thunderclap", title: "Thunderclap", emojis: "⚡🔊", level: "easy" },
  { id: "muggy-weather", title: "Muggy Weather", emojis: "🥵💧", level: "easy" },
  { id: "smog", title: "Smog", emojis: "🏙🌫", level: "easy" },
  { id: "haze", title: "Haze", emojis: "🌫☀", level: "easy" },
  { id: "icicle", title: "Icicle", emojis: "🧊💧", level: "easy" },
  { id: "puddle", title: "Puddle", emojis: "💧🍃", level: "easy" },

  // ===== MEDIUM (25) =====
  { id: "cumulonimbus-cloud", title: "Cumulonimbus Cloud", emojis: "⛈☁", level: "medium" },
  { id: "stratus-cloud", title: "Stratus Cloud", emojis: "☁🌥", level: "medium" },
  { id: "contrail", title: "Contrail", emojis: "☁💨", level: "medium" },
  { id: "squall-line", title: "Squall Line", emojis: "🌬⛈", level: "medium" },
  { id: "jet-stream", title: "Jet Stream", emojis: "🌬🧭", level: "medium" },
  { id: "trade-winds", title: "Trade Winds", emojis: "💨⛵", level: "medium" },
  { id: "polar-vortex", title: "Polar Vortex", emojis: "🌀🧊", level: "medium" },
  { id: "heat-lightning", title: "Heat Lightning", emojis: "⚡🌆", level: "medium" },
  { id: "rogue-wave", title: "Rogue Wave", emojis: "🌊💥", level: "medium" },
  { id: "king-tide", title: "King Tide", emojis: "🌊🌕", level: "medium" },
  { id: "el-nino", title: "El Niño", emojis: "🌊🌡", level: "medium" },
  { id: "la-nina", title: "La Niña", emojis: "🌊🥶", level: "medium" },
  { id: "red-tide", title: "Red Tide", emojis: "🌊🩸", level: "medium" },
  { id: "sea-smoke", title: "Sea Smoke", emojis: "🌊🌫", level: "medium" },
  { id: "pack-ice", title: "Pack Ice", emojis: "🧊🐧", level: "medium" },
  { id: "slush", title: "Slush", emojis: "🌨💧", level: "medium" },
  { id: "indian-summer", title: "Indian Summer", emojis: "🍂☀", level: "medium" },
  { id: "lake-effect-snow", title: "Lake-Effect Snow", emojis: "🌊❄", level: "medium" },
  { id: "urban-heat-island", title: "Urban Heat Island", emojis: "🏙🌡", level: "medium" },
  { id: "crepuscular-rays", title: "Crepuscular Rays", emojis: "☀☁", level: "medium" },
  { id: "alpenglow", title: "Alpenglow", emojis: "🏔🌅", level: "medium" },
  { id: "golden-hour", title: "Golden Hour", emojis: "🌇✨", level: "medium" },
  { id: "blue-hour", title: "Blue Hour", emojis: "🌆🌌", level: "medium" },
  { id: "frost-flower", title: "Frost Flower", emojis: "❄🌸", level: "medium" },
  { id: "ice-fog", title: "Ice Fog", emojis: "🧊🌫", level: "medium" },

  // ===== HARD (25) =====
  { id: "foehn-wind", title: "Foehn Wind", emojis: "🏔💨", level: "hard" },
  { id: "sirocco", title: "Sirocco", emojis: "🏜⛵", level: "hard" },
  { id: "mistral-wind", title: "Mistral Wind", emojis: "🌬⚓", level: "hard" },
  { id: "bora-wind", title: "Bora Wind", emojis: "🏔🥶", level: "hard" },
  { id: "santa-ana-winds", title: "Santa Ana Winds", emojis: "🏜🔥", level: "hard" },
  { id: "harmattan", title: "Harmattan", emojis: "🏜🌫", level: "hard" },
  { id: "noreaster", title: "Nor'easter", emojis: "⚓🌀", level: "hard" },
  { id: "alberta-clipper", title: "Alberta Clipper", emojis: "🌨💨", level: "hard" },
  { id: "bomb-cyclone", title: "Bomb Cyclone", emojis: "🌀💥", level: "hard" },
  { id: "atmospheric-river", title: "Atmospheric River", emojis: "🌊🌧", level: "hard" },
  { id: "gustnado", title: "Gustnado", emojis: "🌪💨", level: "hard" },
  { id: "landspout", title: "Landspout", emojis: "🌪🌾", level: "hard" },
  { id: "wall-cloud", title: "Wall Cloud", emojis: "☁🌪", level: "hard" },
  { id: "shelf-cloud", title: "Shelf Cloud", emojis: "🌥⛈", level: "hard" },
  { id: "roll-cloud", title: "Roll Cloud", emojis: "🌀☁", level: "hard" },
  { id: "arcus-cloud", title: "Arcus Cloud", emojis: "☁⚡", level: "hard" },
  { id: "pileus-cloud", title: "Pileus Cloud", emojis: "☁🎩", level: "hard" },
  { id: "fallstreak-hole", title: "Fallstreak Hole", emojis: "☁🕳", level: "hard" },
  { id: "iridescent-clouds", title: "Iridescent Clouds", emojis: "🌥🌈", level: "hard" },
  { id: "anticrepuscular-rays", title: "Anticrepuscular Rays", emojis: "🌆☀", level: "hard" },
  { id: "belt-of-venus", title: "Belt of Venus", emojis: "🌅🌙", level: "hard" },
  { id: "brocken-spectre", title: "Brocken Spectre", emojis: "🌫👤", level: "hard" },
  { id: "circumzenithal-arc", title: "Circumzenithal Arc", emojis: "🌈⬆", level: "hard" },
  { id: "22-degree-halo", title: "22-Degree Halo", emojis: "☀⭕", level: "hard" },
  { id: "sun-cups", title: "Sun Cups", emojis: "☀🏔", level: "hard" },

  // ===== IMPOSSIBLE (25) — rare but real & nameable =====
  { id: "morning-glory-cloud", title: "Morning Glory Cloud", emojis: "🌀🌅", level: "impossible" },
  { id: "undulatus-asperatus", title: "Undulatus Asperatus", emojis: "🌊☁", level: "impossible" },
  { id: "kelvin-helmholtz-cloud", title: "Kelvin-Helmholtz Cloud", emojis: "🌊🌬", level: "impossible" },
  { id: "pyrocumulonimbus", title: "Pyrocumulonimbus", emojis: "🔥⛈", level: "impossible" },
  { id: "volcanic-lightning", title: "Volcanic Lightning", emojis: "🌋⚡", level: "impossible" },
  { id: "frazil-ice", title: "Frazil Ice", emojis: "🌊🌨", level: "impossible" },
  { id: "neve", title: "Névé", emojis: "🏔🧊", level: "impossible" },
  { id: "serac", title: "Serac", emojis: "⛰❄", level: "impossible" },
  { id: "polar-night", title: "Polar Night", emojis: "🌑🧊", level: "impossible" },
  { id: "midnight-sun", title: "Midnight Sun", emojis: "🌞🌙", level: "impossible" },
  { id: "white-night", title: "White Night", emojis: "🌙✨", level: "impossible" },
  { id: "willy-willy", title: "Willy-Willy", emojis: "🌪🦘", level: "impossible" },
  { id: "simoom", title: "Simoom", emojis: "🏜🥵", level: "impossible" },
  { id: "vog", title: "Vog", emojis: "🌋🌫", level: "impossible" },
  { id: "crevasse", title: "Crevasse", emojis: "🧊🕳", level: "impossible" },
  { id: "snow-cornice", title: "Snow Cornice", emojis: "🌨🏔", level: "impossible" },
  { id: "gloaming", title: "Gloaming", emojis: "🌆🌙", level: "impossible" },
  { id: "zenith-flash", title: "Zenith Flash", emojis: "☀⬆", level: "impossible" },
  { id: "ice-jam", title: "Ice Jam", emojis: "🧊🚧", level: "impossible" },
  { id: "freshet", title: "Freshet", emojis: "🌊☀", level: "impossible" },
  { id: "anvil-crawler", title: "Anvil Crawler", emojis: "🌩➡", level: "impossible" },
  { id: "sheet-lightning", title: "Sheet Lightning", emojis: "🌩🏙", level: "impossible" },
  { id: "lunar-corona", title: "Corona (Lunar Ring)", emojis: "🌙⭕", level: "impossible" },
  { id: "dust-whirl", title: "Dust Whirl", emojis: "🌪🍂", level: "impossible" },
  { id: "orographic-rain", title: "Orographic Rain", emojis: "🏔🌧", level: "impossible" },
];
