// E209 weather-emoji-2 facts — one true <=70-char fact per phenomenon, shown on reveal.
export const WEATHER_EMOJI_2_FACTS = {
  // EASY
  "overcast-sky": "A sky fully covered by a uniform layer of grey cloud.",
  "sun-shower": "Rain falling while the sun is still shining brightly.",
  "snow-flurry": "A brief, light burst of snow with little accumulation.",
  "freezing-rain": "Rain that freezes on contact, coating surfaces in ice.",
  "cold-front": "A boundary where cold air pushes out warmer air ahead of it.",
  "warm-front": "A boundary where warm air slides up and over cooler air.",
  "snow-squall": "A sudden, intense burst of heavy snow and gusty wind.",
  "heat-dome": "High pressure traps hot air, causing prolonged extreme heat.",
  "cold-snap": "A sudden, short period of very cold temperatures.",
  "dust-storm": "Strong winds lift huge amounts of sand and dust into the air.",
  "windstorm": "A storm marked by very strong, damaging winds with little rain.",
  "rain-shower": "A short spell of rain, often from a passing cloud.",
  "snowstorm": "A storm bringing heavy snowfall and strong winds.",
  "cloudburst": "A sudden, extremely heavy and brief rainfall.",
  "full-moon": "The moon appears fully illuminated as seen from Earth.",
  "new-moon": "The moon is dark, positioned between Earth and the sun.",
  "starry-sky": "A clear night sky where many stars are visible.",
  "cumulus-cloud": "Puffy, cotton-like clouds with flat bases, sign of fair weather.",
  "cirrus-cloud": "Thin, wispy clouds made of ice crystals high in the sky.",
  "thunderclap": "The loud crack of sound produced by nearby lightning.",
  "muggy-weather": "Uncomfortably warm and humid air that feels sticky.",
  "smog": "A mix of smoke and fog that pollutes and dims the air.",
  "haze": "Fine dust or moisture particles that make the air look hazy.",
  "icicle": "A hanging spike of ice formed by dripping water that freezes.",
  "puddle": "A small, shallow pool of water left after rain.",

  // MEDIUM
  "cumulonimbus-cloud": "A towering cloud that produces thunderstorms and heavy rain.",
  "stratus-cloud": "A flat, featureless grey cloud layer covering the sky.",
  "contrail": "A trail of ice crystals left behind by a high-flying aircraft.",
  "squall-line": "A line of severe thunderstorms forming along a cold front.",
  "jet-stream": "A fast-flowing air current high in the atmosphere steering weather.",
  "trade-winds": "Steady winds blowing toward the equator from the subtropics.",
  "polar-vortex": "A vast pool of cold air that spins near the Earth's poles.",
  "heat-lightning": "Distant lightning seen without hearing its thunder.",
  "rogue-wave": "An unusually large, unpredictable ocean wave far bigger than others.",
  "king-tide": "An exceptionally high tide occurring during a new or full moon.",
  "el-nino": "A periodic warming of Pacific waters that shifts global weather.",
  "la-nina": "A periodic cooling of Pacific waters that shifts global weather.",
  "red-tide": "A harmful algae bloom that tints coastal water reddish.",
  "sea-smoke": "Fog that forms when cold air passes over warmer ocean water.",
  "pack-ice": "Large sheets of sea ice drifting and packed together.",
  "slush": "Partly melted snow turned into a wet, slippery mix.",
  "indian-summer": "An unusually warm, dry spell occurring after the first autumn frost.",
  "lake-effect-snow": "Heavy snow formed as cold air crosses relatively warm lake water.",
  "urban-heat-island": "A city that is notably warmer than its surrounding rural areas.",
  "crepuscular-rays": "Sunbeams that appear to fan out through gaps in clouds.",
  "alpenglow": "A pink or orange glow lighting mountain peaks near sunrise or sunset.",
  "golden-hour": "The warm, soft light shortly after sunrise or before sunset.",
  "blue-hour": "The period of soft blue twilight just before sunrise or after sunset.",
  "frost-flower": "Delicate ice crystals that form in flower-like patterns on plants.",
  "ice-fog": "Fog made of tiny suspended ice crystals in extreme cold.",

  // HARD
  "foehn-wind": "A warm, dry wind that descends on the leeward side of mountains.",
  "sirocco": "A hot, dusty wind blowing from the Sahara toward southern Europe.",
  "mistral-wind": "A strong, cold, northerly wind that blows through southern France.",
  "bora-wind": "A cold, gusty wind that rushes down mountains toward the Adriatic.",
  "santa-ana-winds": "Hot, dry offshore winds that fuel wildfires in Southern California.",
  "harmattan": "A dry, dusty trade wind blowing across West Africa from the Sahara.",
  "noreaster": "A powerful coastal storm bringing wind and snow to the US Northeast.",
  "alberta-clipper": "A fast-moving, low-snow winter storm sweeping from Canada.",
  "bomb-cyclone": "A storm whose pressure drops rapidly, intensifying explosively.",
  "atmospheric-river": "A narrow band of concentrated moisture flowing through the sky.",
  "gustnado": "A brief, weak whirlwind spun up along a thunderstorm's gust front.",
  "landspout": "A tornado-like vortex forming from the ground up, not a supercell.",
  "wall-cloud": "A lowered, rotating cloud base beneath a severe thunderstorm.",
  "shelf-cloud": "A low, wedge-shaped cloud along the leading edge of a storm.",
  "roll-cloud": "A rare, tube-shaped cloud that rolls horizontally along its axis.",
  "arcus-cloud": "A low, arc-shaped cloud formation at a storm's leading edge.",
  "pileus-cloud": "A small cap cloud that briefly forms atop a growing storm cloud.",
  "fallstreak-hole": "A large circular gap that forms in a cloud layer.",
  "iridescent-clouds": "Clouds that shimmer with rainbow colors near the sun or moon.",
  "anticrepuscular-rays": "Sunbeams appearing to converge opposite the sun in the sky.",
  "belt-of-venus": "A pink glowing band visible opposite the sun at twilight.",
  "brocken-spectre": "A giant shadow of a person cast onto fog or clouds.",
  "circumzenithal-arc": "A bright, colorful arc appearing high overhead near the zenith.",
  "22-degree-halo": "A ring of light around the sun from ice-crystal refraction.",
  "sun-cups": "Bowl-shaped hollows melted into snow by sunlight.",

  // IMPOSSIBLE
  "morning-glory-cloud": "A rare rolling cloud tube seen over northern Australia.",
  "undulatus-asperatus": "A dramatic, wave-like cloud formation resembling a rough sea.",
  "kelvin-helmholtz-cloud": "Wave-shaped clouds formed by wind shear between air layers.",
  "pyrocumulonimbus": "A thunderstorm cloud generated by the intense heat of a fire.",
  "volcanic-lightning": "Lightning generated within the ash plume of an erupting volcano.",
  "frazil-ice": "Fine ice crystals that form in turbulent, supercooled water.",
  "neve": "Granular, partly compacted snow that is becoming glacial ice.",
  "serac": "A jagged block or pinnacle of ice on a glacier's surface.",
  "polar-night": "A period near the poles when the sun stays below the horizon.",
  "midnight-sun": "A period near the poles when the sun stays visible all night.",
  "white-night": "A twilight summer night at high latitudes that never fully darkens.",
  "willy-willy": "A small, spinning whirlwind of dust common in the Australian outback.",
  "simoom": "A fierce, hot, sand-laden desert wind of North Africa and Arabia.",
  "vog": "Volcanic smog formed by gases and particles from an eruption.",
  "crevasse": "A deep crack that opens in a glacier's surface ice.",
  "snow-cornice": "An overhanging ledge of wind-packed snow on a ridge.",
  "gloaming": "The soft, dim twilight period just after sunset.",
  "zenith-flash": "A rare green flash of light seen near the sky's highest point.",
  "ice-jam": "A blockage of river ice that can cause sudden flooding.",
  "freshet": "A rapid rise in a river's flow from snowmelt or heavy rain.",
  "anvil-crawler": "Lightning that travels sideways along the anvil top of a storm.",
  "sheet-lightning": "Lightning whose flash is diffused across a wide sheet of cloud.",
  "lunar-corona": "A colorful ring of light around the moon from water droplets.",
  "dust-whirl": "A small spinning column of dust and dry debris in open terrain.",
  "orographic-rain": "Rain produced when moist air is forced to rise over mountains.",
};
