// E145 weather/nature-phenomenon facts — one verified <=70-char true fact per item, shown on reveal.
export const WEATHER_EMOJI_FACTS = {
  // EASY
  "rain": "Water droplets falling from clouds down to the ground.",
  "sunshine": "Direct sunlight reaching the ground on a clear day.",
  "snow": "Ice crystals that fall as soft, white flakes.",
  "wind": "Air moving from high- to low-pressure areas.",
  "thunderstorm": "A storm with thunder, lightning and heavy rain.",
  "rainbow": "Sunlight split by raindrops into a colored arc.",
  "cloudy": "Sky mostly covered by clouds, hiding the sun.",
  "fog": "A cloud at ground level that cuts visibility.",
  "lightning": "A giant electric spark between cloud and ground.",
  "hail": "Balls of ice that fall from strong storm clouds.",
  "heatwave": "A long spell of unusually hot weather.",
  "frost": "Ice crystals that form on surfaces near freezing.",
  "drizzle": "Very light rain made of tiny, fine droplets.",
  "sunrise": "The moment the sun appears over the horizon.",
  "sunset": "The moment the sun sinks below the horizon.",
  "blizzard": "A severe snowstorm with strong, blinding winds.",
  "tornado": "A violently spinning column of air touching ground.",
  "hurricane": "A huge spinning tropical storm with fierce winds.",
  "flood": "Water overflowing onto normally dry land.",
  "drought": "A long period with little or no rainfall.",
  "dew": "Water droplets that form on cool surfaces at night.",
  "monsoon": "A seasonal wind bringing months of heavy rain.",
  "mist": "Light fog of tiny droplets; thinner than fog.",
  "gale": "A very strong, sustained wind.",
  "heat": "Very high air temperature that feels oppressive.",

  // MEDIUM
  "aurora": "Colored polar sky lights from solar particles.",
  "eclipse": "The Moon passes in front of and hides the Sun.",
  "meteor-shower": "Many meteors streak as Earth crosses debris.",
  "comet": "An icy body that grows a glowing tail near the Sun.",
  "tsunami": "Giant sea waves triggered by undersea quakes.",
  "avalanche": "A mass of snow sliding fast down a mountain.",
  "sandstorm": "Strong winds carrying thick clouds of sand.",
  "volcano": "Molten rock and ash erupting from the Earth.",
  "wildfire": "An uncontrolled fire spreading through wildland.",
  "waterfall": "A river dropping steeply over a rocky ledge.",
  "geyser": "A spring that erupts jets of boiling water.",
  "whirlpool": "Water spinning rapidly in a swirling vortex.",
  "mirage": "Bent light creates a fake watery image in heat.",
  "earthquake": "Ground shaking as Earth's plates suddenly shift.",
  "iceberg": "A large chunk of freshwater ice afloat at sea.",
  "glacier": "A slow-moving river of ice on land.",
  "downpour": "A sudden burst of very heavy rain.",
  "sleet": "A mix of rain and snow, or icy rain pellets.",
  "waterspout": "A tornado that forms over open water.",
  "dust-devil": "A small whirlwind of dust on hot, dry ground.",
  "landslide": "Rock and soil sliding down a slope.",
  "sinkhole": "Ground collapsing into a hole as rock dissolves.",
  "quicksand": "Loose wet sand that traps and sinks heavy objects.",
  "tide": "Sea level rising and falling by the Moon's pull.",
  "humidity": "The amount of water vapor held in the air.",

  // HARD
  "hailstorm": "A storm dropping heavy, damaging hailstones.",
  "typhoon": "A hurricane-strength storm in the NW Pacific.",
  "solar-flare": "A sudden burst of radiation from the Sun.",
  "rip-current": "A strong narrow current pulling away from shore.",
  "sun-dog": "Bright spots beside the Sun from ice crystals.",
  "fire-rainbow": "A rainbow-colored band in high, icy clouds.",
  "st-elmos-fire": "A glowing plasma on ship masts during storms.",
  "ball-lightning": "A rare glowing sphere seen during storms.",
  "bioluminescence": "Living organisms making the sea glow at night.",
  "fog-bow": "A pale, nearly colorless rainbow formed in fog.",
  "frostbite": "Skin and tissue freezing in extreme cold.",
  "permafrost": "Ground that stays frozen for two or more years.",
  "haboob": "A towering wall of dust driven by a storm.",
  "derecho": "A long, fast line of destructive straight winds.",
  "supercell": "A rotating thunderstorm that can spawn tornadoes.",
  "microburst": "A powerful downward blast of wind from a storm.",
  "flash-flood": "A sudden, fast flood from intense rainfall.",
  "whiteout": "Snow and fog erasing all visibility outdoors.",
  "graupel": "Soft, snow-coated ice pellets; not true hail.",
  "hoarfrost": "Feathery ice crystals coating cold surfaces.",
  "rime-ice": "Ice from freezing fog blown onto surfaces.",
  "black-ice": "A thin, near-invisible ice glaze on roads.",
  "katabatic-wind": "Cold, dense air rushing downhill from heights.",
  "chinook": "A warm, dry wind that melts mountain snow fast.",
  "storm-surge": "Sea pushed inland by a storm's strong winds.",

  // IMPOSSIBLE
  "firenado": "A whirling vortex of flame and hot rising air.",
  "brinicle": "An underwater ice finger from sinking cold brine.",
  "sun-pillar": "A vertical shaft of light above a low sun.",
  "light-pillar": "A beam of light from flat, floating ice crystals.",
  "moonbow": "A faint rainbow made by moonlight at night.",
  "green-flash": "A brief green light as the Sun sets or rises.",
  "nacreous-clouds": "Rainbow polar clouds high in the stratosphere.",
  "noctilucent-clouds": "Glowing night clouds at the edge of space.",
  "mammatus-clouds": "Pouch-like lumps hanging under storm clouds.",
  "lenticular-cloud": "A smooth, lens-shaped cloud over mountains.",
  "virga": "Rain that evaporates before reaching the ground.",
  "petrichor": "The earthy smell after rain hits dry soil.",
  "diamond-dust": "Tiny ice crystals sparkling in still, cold air.",
  "snow-roller": "Wind rolls snow into natural hollow cylinders.",
  "penitentes": "Tall snow spikes carved by sun on high peaks.",
  "blood-rain": "Rain reddened by desert dust or red algae.",
  "thundersnow": "A snowstorm that also has thunder and lightning.",
  "ice-storm": "Freezing rain coating everything in glaze ice.",
  "aurora-australis": "The southern polar version of the aurora.",
  "zodiacal-light": "A faint cone of light from space dust at dusk.",
  "sun-halo": "A bright ring around the Sun from ice crystals in cirrus cloud.",
  "airglow": "A faint natural glow of the night sky itself.",
  "red-sprite": "Red flashes high above a thunderstorm.",
  "blue-jet": "Blue lightning shooting up from storm tops.",
  "elves-lightning": "An expanding ring of light high above storms.",
};
